### ISSUE TITLE
[Suggestion] Increase drop chance for quest item from 4 to 50

### ISSUE THREAD

**Issue by Hacaw** [chromiecraft/chromiecraft#10]
##### SMALL DESCRIPTION:
- Killed more than 35+ mobs to get a quest item to finish https://www.wowhead.com/quest=9579/galaens-fate.
- [BUG]: It looks like a dead Galaen is not spawned when you accept the quest from it's body as shown [here](https://youtu.be/ycHw6A4ndzM) and described [here](https://wow.gamepedia.com/Galaen%27s_Fate)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.wowhead.com/item=23873/galaens-amulet#objective-of is 4.75% drop-chance.

##### CURRENT BEHAVIOUR:
In our database, drop-chance is 4%.
SELECT * FROM creature_loot_template WHERE item = 23873;

##### STEPS TO REPRODUCE THE PROBLEM:
1. q a 9579
2. go c id 17606
3. kill and check loot

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/38bf355bf479

**Comment by Yehonal** [comment]
1. The title says "50" but actually we should increase it to 5, however, the wowhead is not a good source and the wotlk website around show a percentage of 4. I don't think this can be considered a bug. Can we close it?

2. Can you open another issue for the "cosmetic bug" of the quest? 

Thank you for the report !
