### ISSUE TITLE
Wrong textures and or emitter color used on shoulders/helmets/glove. Client Side 

### ISSUE THREAD

**Issue by Thimzion** [chromiecraft/chromiecraft#1005]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There are a a handfull of equipment and gear that have errors or wrong textures displayed on their model
Below is a list of affected gear

[Hope Bearer Helm](https://wowgaming.altervista.org/aowow/?item=27408)
[Soulforge Helmet](https://wowgaming.altervista.org/aowow/?item=22091)
All of Paladin Dungeon Tier 0 recolor and 0.5
Gem part on the helmets uses the Lightforge Helm texture in the M2 file.

[Fanblade  Pauldrons](https://wowgaming.altervista.org/aowow/?item=27847)
Emitter texture in the M2 file for the eye glow uses the Green color variant of the PVP raptor eye glow texture

[Demonfang Ritual Helm](https://wowgaming.altervista.org/aowow/?item=27781)
[Mantle of Three Terrors](https://wowgaming.altervista.org/aowow/?item=27994)
Uses the same M2 file as the Nemesis Shoulders or Headpiece

[Gloves of the Deadwatcher](https://wowgaming.altervista.org/aowow/?item=27493)
Hands texture uses the Nemesis Glove texture

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All of the mentioned equipment are working as it did back in the day simply because Blizzard for some reason, let these oversights slipped through.

The Lightforge recolors helmets
Soulforge and Hope Bearer Helm uses same M2 file as Lightforge, the devs hardcoded the texture used for the gem part to use the Lightforge Texture and not the Recolor textuers.

The devs at blizzard should have created seperate m2 files and entries in the ItemDisplayInfo.DBC for each of the recolors of lightforge helmets where the hardcoded texture in the m2 is changed to the use the correct recolor texture filename instead of the Lightforge texture filename. 

[Fanblade  Pauldrons](https://wowgaming.altervista.org/aowow/?item=27847)
The emitter texture uses the Green Eye glow texture used on the Epic/PVP raptor mount. The glow in the eye sockets in the  Textures of the recolored T2 shoulders are blue in color. The devs didn't create a separate m2 file for these shoulders that uses the Blue Epic/PVP Raptor Eye glow variant texture that exists in the MPQ.

[Demonfang Ritual Helm](https://wowgaming.altervista.org/aowow/?item=27781)
[Mantle of Three Terrors](https://wowgaming.altervista.org/aowow/?item=27994)

The emitter colors on both the helmet and shoulders should be a yellow/orange ish color, just like the textures have inside the mouth or eye. Sinch they used the same M2 models for both the head and shoulders that the Nemesis set uses, the emitters RBG values are hardcoded to a greenish and yellow color. 

the devs should have created  separate M2 files and entries in the ItemDsiplayInfo.dbc for the recolor and adjusted the RGB values of the emitters to reflect the reddish, orange and yellow colors used in the recolored textures.

[Gloves of the Deadwatcher](https://wowgaming.altervista.org/aowow/?item=27493)
![nemesis hands red](https://user-images.githubusercontent.com/45111277/123499241-979a1380-d635-11eb-93f1-fb042f3f31a7.png)
The correct textures that is supposed to be used in Texture3 cell of ID 42903 in ItemDisplayInfo.DBC as it has the "OutlandRed" naming to it.
![dbc nemesis gloves recolor](https://user-images.githubusercontent.com/45111277/123499624-4f302500-d638-11eb-860d-176b8a9c6c75.png)
Whoever was at work that day used the green nemesis texture on the hand part instead of he red version of it exists in the MPQ.

##### SOURCE:

MPQ files of a 3.3.5 client

Looking up the textures inside the MPQ files shows what the texture artists intended these items where supposed to look like. The devs during TBC decided to cut corners and save themselves work by not creating separate M2 files with the correct emitter RBG values or texture to make these items look as the artists envisioned.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Obtain the listed items above or use Atlasloot and shift click to equip them in the dressing room.

##### EXTRA NOTES:

Fixing these requires editing of server side SQL and client side requires a patched MPQ as well. this would end up being a tedious task to do. 

On my own Vanilla Vmangos Vanilla Server I've managed to patch some of fixes to the affected equipments.
![wrath](https://user-images.githubusercontent.com/45111277/123496823-56e8cd00-d62a-11eb-944f-c14852044037.png)
<sup>Wrath Set</sup>

![Fanblade fixed](https://user-images.githubusercontent.com/45111277/123496786-18531280-d62a-11eb-8b1e-a34a51ec681a.png)
<sup>Modified M2 Shoulders that uses the Blue Raptor Eye texture that exists in the MPQ files.</sup>

![Ligthforge orange](https://user-images.githubusercontent.com/45111277/123496999-61579680-d62b-11eb-8d7f-c2e49e71c240.png)
<sup>Modified M2 of the Lightforge helmet where the hardcoded texture is change to use the Soulforge texture instead of the Ligth forge</sup>

![Ligthforge green](https://user-images.githubusercontent.com/45111277/123497048-af6c9a00-d62b-11eb-8c09-d43c4da33495.png)
<sup>Same as above but edited the hardcoded texture to use the Blue recolor instead.</sup>

![nemesis red](https://user-images.githubusercontent.com/45111277/123497140-299d1e80-d62c-11eb-8ebe-de4f96437b79.png)
<sup>Modified M2 shoulders where I've changed the RGB values of the emitters to reflect the colors used in the recolor</sup>

I am unsure on whether or not this is something worth fixing as these "bugs" were present when it was live back in the day, and some are actual still present Shadowlands expansion.

I've personally mostly worked on editing client side DBC and MPQ and Server SQL for 1.12.1 while 3.3.5a I don't have so much experience with, I am able to modify and edit 3.3.5 Trinitycore SQL and I don't think editing M2 files and DBC aren't that diffrent from 1.12.1.

I may try and fix these items on my own 3.3.5a server and share whatever I did to fix these things with the Chromiecraft team if you all are interested. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
This is really interesting and an accurate report, but it's a client-side issue so, not strictly related to the **server**.
I also worked on DBC and MPQ, you could create an MPQ patch to fix this, but it's always a client-side issue, so we can't do much on our side I think.

If it can be solved (as you said) server-side via some SQL it's ok, but I am not sure.

Anyways, thank you for the report, if you want to share some updates or progress, please, do.

**Comment by Thimzion** [comment]
I've checked up some more on this issue and the only way to fix this is a client-side patch.
I can try and make a patch that fixes these things that not even Blizzard has bothered fixing and are still present in the TBC Classic servers.

The easiest fixes are the [Gloves of the Deadwatcher ](https://tbc.wowhead.com/item=27493/gloves-of-the-deadwatcher?bonus=6710) All I need to do is to change the texture name to the correct one in the ItemDisplayInfo DBC and that should be solved.

The Lighforge helmets, Nemesis helm and pauldrons and Wrath Pauldron recolors might be a bit tedios as I have to create a modified version of the m2 files.

Fanblade Pauldrons I just need the texture name to be changed to a blue version of the eyeglow that already exists in the MPQ

Soulforge Helm and Hope Bearer Helm I have to do the same as above, just change the texture name to the correct texture, for all the races and their male and female

Demonfang Ritual Helm and Mantle of Three Terrors are a bit different as I need to mess around with the RGB values so it matches the colors in the texture files

This patched MPQ will only contain some new M2 files,  ItemDisplayInfo.DBC and some Textures that are identical to the ones that already exists but with the file name shortened so it fits within the Hex offset of the m2 files that i need to create duplicates of.

I'll try and share some previews on the progress some time in the future.

**Comment by Thimzion** [comment]
Had some progress on making a patch for 3.3.5 

Gloves of the Deadwatcher has been fixed and I've tinkered with one side on Mantle of Three Terrors.  So are I think I've got the values alright
![onesidefixed](https://user-images.githubusercontent.com/45111277/123574097-8ab12780-d7cf-11eb-89ef-71da8243e9a9.png)

Fanblade Pauldrons are done on both sides for now. Not exactly the right blue color but it's better than the neon green I suppose.
![fanblades fixed](https://user-images.githubusercontent.com/45111277/123574397-0612d900-d7d0-11eb-95f2-60acdf779568.png)

**Comment by Thimzion** [comment]
Finished making the patch where all these client side issues have been resolved.

**Comment by Helias** [comment]
Thank you a lot!

We should make a patch that fixes the known blizzards bugs like this https://github.com/azerothcore/azerothcore-wotlk/issues/4902

if you think that your job is done about this issue, you can close it, thanks again! :+1:

**Comment by Thimzion** [comment]
Noticed one more helmet which is the [Helmet of the Steadfast Champion](https://tbc.wowhead.com/item=32084/helmet-of-the-steadfast-champion) that uses the M2 where the Lightforge textures is hardcoded for the gem

What the texture looks like in the MPQ for that recolor
![steadfast tex](https://user-images.githubusercontent.com/45111277/123888693-59ae2f80-d954-11eb-999f-c377c2dfbb8b.png)

I've added in that fix to my client side patch and I don't think there is anything more to do.
![steadfast](https://user-images.githubusercontent.com/45111277/123888793-8a8e6480-d954-11eb-81d1-052c33628933.png)

Will say I'm done with this issue now for good.
