### ISSUE TITLE
Macro to switch weapons having a duplicate not soulbound

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#1009]
Macro equip duplicate items

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When using a macro to equip an item, if there's a duplicate item and one of them is soulbound, the macro won't work.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

To be able to switch items even when there's a duplicate since one of them is souldbound.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get 2 duplicated weapons and one of them being soulbound, since these macros are usually used in combat
2. Use macro to equip the weapon
3. The equip doesn't work

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
is this a client issue?

**Comment by claudiodfc** [comment]
I don't think so, it's probably just not handled behaviour when player requests item and the first item is not soulbound

**Comment by Eldarix** [comment]
I have not been able to reproduce it, it equips without problem when using the macro (AC Hash/commit 2a2e54d8c586)

![WoWScrnShot_062721_170715](https://user-images.githubusercontent.com/82579073/123547706-8272d100-d76a-11eb-86bc-4c543d21dfd7.jpg)
![WoWScrnShot_062721_170723](https://user-images.githubusercontent.com/82579073/123547721-93bbdd80-d76a-11eb-90a5-6acdd3866fea.jpg)
![WoWScrnShot_062721_170802](https://user-images.githubusercontent.com/82579073/123547744-a504ea00-d76a-11eb-8ddf-13b7d8f9e8e6.jpg)

I have also observed that if you put the unlinked item on the left, it is also equipped, asking first with the typical form.

**Comment by pop-pig** [comment]
I've managed to reproduce this issue on a local AC server.
It seems like it will happen depending on the order of the items in your bag: https://youtu.be/U1bq4M2PLqY
In the first equip, I have the soulbound sword closer to the "first slot" / "top left of my bag" , and it correctly equips the soulbound sword.
In the second equip, I have the NOT soulbound sword closer to the "first slot", and it tries to equip the NOT soulbound sword.
