### ISSUE TITLE
Quest "Thresher Oil" bugged

### ISSUE THREAD

**Issue by Lexine1** [chromiecraft/chromiecraft#1013]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The quest requires you to kill threshers next to Theramore to loot their oil. I have killed around 20 now and haven't seen a single Thresher oil drop, so I believe they're not coded to drop it.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should drop the item. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to Theramore and accept the quest "This old lighthouse"
2. Delivering the quest will allow you to take the "Thresher oil" quest
3. Kill threshers and notice they don't drop anything.
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
They drop, I did it over a month ago. Drop rate is low, just keep killing.

**Comment by Efymer** [comment]
Cannot reproduce it in my local AzerothCore server, they drop from https://wowgaming.altervista.org/aowow/?npc=4388

**Comment by Efymer** [comment]
Also screenshot from Keira3:


![loot](https://user-images.githubusercontent.com/79163132/123524816-024a5e00-d6cd-11eb-9e06-16a551e55406.PNG)
