### ISSUE TITLE
[Warrior] One-Handed Weapon Specialization isn't increasing Thunderclap dmg

### ISSUE THREAD

**Issue by tbcxd** [chromiecraft/chromiecraft#1018]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

https://wowgaming.altervista.org/aowow/?spell=16542
One-Handed Weapon Specialization is a protection talent which increase the physical damage dealt by the warrior when an one-handed weapon is equiped by 10% at 5/5 level.

Currently on Chromie Craft thunderclap skill is not affected by this talent.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Thunderclap's damage should be increased by the talent mentioned above as it is a physical damage skill

##### SOURCE: https://xpoff.com/threads/thunderclap-vs-whirlwind.603/
![Screenshot_20210627-145544_Chrome](https://user-images.githubusercontent.com/85901661/123544368-a37ff580-d75b-11eb-93c1-f4cffd6d0dec.jpg)

More sources: 

![Screenshot_20210627-144546_Chrome](https://user-images.githubusercontent.com/85901661/123544365-a11d9b80-d75b-11eb-95fd-ede406281da9.jpg)
![Screenshot_20210627-145236_Chrome](https://user-images.githubusercontent.com/85901661/123544367-a24ec880-d75b-11eb-982c-052dcfabd81a.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use thunderclap
2. Spec 5/5 One-Handed Weapon Specialization
3. Use thunderclap again
4. The damage of second thunderclap will be the same as the first one.

##### EXTRA NOTES:

Might also be bugged for shield slam too, so please do test it for that one as well.
10% damage is huge, especially in a pvp 
environment.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. Damage does not increase for thunderclap after going 5/5 into 1H weapon spec.

Checking shield slam, it does increase damage.
