### ISSUE TITLE
Melee Auto Attack mistiming

### ISSUE THREAD

**Issue by kuzaan** [chromiecraft/chromiecraft#1021]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

My paladin's auto attacks sometimes miss the auto attack timer, then lands 2 attacks simultaneously on the next auto attack queue.

Example: auto attack hits (2 sec CD), auto attack hits (2 sec CD), auto attack SKIPS (2 sec CD), auto attack DOUBLE hits. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Auto attacks should respect the weapon timer, without skipping or "queuing" hits to be landed simultaneously on the next timer. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Simply auto attack a target and watch for any hits skipping / queuing. 
2. If 1 fails, add a spell to the mix (in my case Paladin's Judgement) and watch for any auto attacks skipping / queuing
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
I think it's only a display issue, if you check your combat log the damage should be correct.
If it's not, could you provide a short video of it happening?
Also, reminds me of issue #609

**Comment by Stump876** [comment]
Pop-pig beat me to it! 😄I couldn't reproduce it, and was curious about the combat log as well.

**Comment by kuzaan** [comment]
It seems to be a display issue indeed. Combat log displays the first auto
attack correctly.
Video attached.

Thanks folks!

**Comment by Stump876** [comment]
No problem. Thanks for the report.
