### ISSUE TITLE
Need for a Cure quest is not obtainable despite quest mark

### ISSUE THREAD

**Issue by dumikachromiecraft** [chromiecraft/chromiecraft#1023]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The NPC called Rhinag is supposed to give me the quest called Need for a Cure (https://classic.wowhead.com/quest=812/need-for-a-cure). Upon arriving, I see the ! mark, but the quest will not appear. I am currently playing a tauren druid. Based on wowhead, I see no prerequisites to this quest.

Image:

![image](https://user-images.githubusercontent.com/36760053/123593655-10909b00-d7ef-11eb-8327-2ac5fd51b032.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The quest should be obtainable without any prerequisites, just by visiting Rhinag.

##### STEPS TO REPRODUCE THE PROBLEM:

Visit the NPC, the quest will not show up.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Efymer** [comment]
Hello @dumikachromiecraft! 
Unfortunately I couldn't reproduce it in my local AzerothCore server. I created a Tauren Druid level 38 and I could pick up the quest.
I also checked the requistes of the quest in the AzerothCore Database and they should be available for all the races of the Horde.
I'll leave it as _Needs second opinion_ just in case, from your side, try to relog and check that the NPC is trying to give you the quest properly 🙏 

Thanks!

**Comment by dumikachromiecraft** [comment]
Hm weird, I tried cache clearing, relogging, to no avail. I got another player (although he was using enGB) to try it, and it worked for him.

**Comment by temperrr** [comment]
I can also take the quest as lv 22 druid on Local AC
![image](https://user-images.githubusercontent.com/20357406/123628858-dab1dd80-d813-11eb-9b7d-8c89a0031e70.png)

**Comment by Azcobu** [comment]
Had a look and was able to pick up the quest at lvl 7 (minimum level required) and 39 (your level) with no problems.

@dumikachromiecraft had you been in any BGs prior to this, especially ones where you were faction-swapped?

**Comment by dumikachromiecraft** [comment]
@Azcobu 

Yeah, I frequently go to battlegrounds, but it doesn't affect picking up other quests though. I did like 30 quests after this. :-)

**Comment by pop-pig** [comment]
On live CC I have no issue taking the quest but as a 39 tauren hunter.

**Comment by dumikachromiecraft** [comment]
Guys, is it possible the issue is related to this?

https://github.com/chromiecraft/chromiecraft/issues/1003

It is something about timed quests.

**Comment by pop-pig** [comment]
Looks like it is indeed related, I started a timer quest before taking the "Need for a Cure" quest, and it displays the same "Greetings <character>" dialog.
![WoWScrnShot_062821_141351](https://user-images.githubusercontent.com/81818678/123634796-2d42c800-d81b-11eb-88c3-ce8242195505.jpg)

**Comment by dumikachromiecraft** [comment]
Cheers mate. Looks like it is indeed a general issue then.
What should we do with the ticket? Keep it up, or close it since one ticket has already mentioned this issue?

**Comment by Stump876** [comment]
It's really part of a larger issue. It's linked to the other one with the timers overlapping. If needed it can be used for reference.
