### ISSUE TITLE
Trolls in the dwarf/gnome starring area should aggro automatically 

### ISSUE THREAD

**Issue by burlytadpole1** [chromiecraft/chromiecraft#1025]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.
The trolls in and around the ice cave in the dwarf/gnome starting area should be aggressive towards players but are not.  This includes the named troll in the cave needed for a quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
Approaching a troll should cause the troll to automatically attack.
##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a dwarf or gnome.
2. Approach a troll.
3. 
4.

##### EXTRA NOTES:

Type here.
Every starting area has one aggressive mob to teach new players before venturing into the world.  For dwarves and gnomes it should be the trolls.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
Hi, I think you're talking about the Frostmane Troll Whelp, right? https://wowgaming.altervista.org/aowow/?npc=706
I checked wowpedia, it says here https://wowpedia.fandom.com/wiki/Frostmane_Troll_Whelp that they were changed to neutral in patch 3.3.0, so in game behaviour seems to match both the DB and the wowpedia.
I'll close this issue.

Thanks for the report anyways!

**Comment by burlytadpole1** [comment]
Ok, sorry.  I will do more patch specific research next time.  Seems odd
that they are neutral but I guess it was done on preparation for Cata.

Thanks.
