### ISSUE TITLE
[Mulgore] Skinning mobs in starting area gives light leather, medium leather/hide, red whelp scales

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1026]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Mountain Cougars (https://wowgaming.altervista.org/aowow/?npc=2961), Plainstriders (https://wowgaming.altervista.org/aowow/?npc=2955) and Battleboars (https://wowgaming.altervista.org/aowow/?npc=2966) can be skinned for light leather, medium leather, medium hides and red whelp scales.

There wasnt an issue open on these mobs when I searched, but there was a comment under Issue #38 , yet an issue for these mobs was never open so it was never fixed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs in starting zones should not be dropping medium leathers/hides/red whelp scales.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 25114 and start killing and Skinning Plainstriders
2. Teleport to GUID 25725 and start killing and skinning Mountain Cougars
3. Teleport to GUID 25978 and start killing and skinning Battleboars
4. Observe the loots you get from skinning

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Thanks for your report. This is already a known issue over at AC. https://github.com/azerothcore/azerothcore-wotlk/issues/6250
I am going to mark it as Known Issue.

**Comment by gurveleg** [comment]
Damn, I should have searched Azerothcore github also. Thanks.
