### ISSUE TITLE
Erk and Fang are on top of eachother

### ISSUE THREAD

**Issue by NethanosGit** [chromiecraft/chromiecraft#1027]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.
Erk and Fang are one on top of eachother.
![WoWScrnShot_062821_195406](https://user-images.githubusercontent.com/86041526/123675973-ffc24280-d84b-11eb-9c10-c226fdf6667e.jpg)

https://classic.wowhead.com/npc=14857/erk
https://classic.wowhead.com/npc=14892/fang

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should be like in the picture here
https://classic.wowhead.com/npc=14857/erk
Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go in Barrens at the location of the NPCs, you should see them on top of eachother.
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/091b072be10ecbe75d9aa38c19e2262e0cbc7690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Efymer** [comment]
Thanks for you report 😸 

I couldn't reproduce it though:

![WoWScrnShot_062821_192611](https://user-images.githubusercontent.com/79163132/123679537-e0c1b180-d847-11eb-85e8-6f5022dddc85.jpg)

**Comment by NethanosGit** [comment]
Maybe it was just for me
