### ISSUE TITLE
[Stranglethorn Fishing Extravaganza] Master Angler quest resets if server restart during the event, allowing for multiple winners on the same day

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#1028]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If server restart happens during the Stranglethorn Fishing Extravaganza, after the winner has been selected, another player can deliver 40 Speckled Tastyfish required for Quest:Master Angler and be another winner on the same day, obtaining one of the rewards and achievement.

Despite the rare environment, this may open a window for easy achievement and quest rewards from the Quest:Master Angler. Quest also resets for the previous winner so the same person can get two rewards on the same day if they are 'lucky'.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Server restart should not affect the Quest:Master Angler and reset its completion once the winner is selected for the day.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wait till the Stranglethorn Fishing Extravaganza event is up
2. Collect 40 Speckled Tastyfish https://wowgaming.altervista.org/aowow/?item=19807
3. Approach Riggle Bassbait <Fishmaster> https://wowgaming.altervista.org/aowow/?npc=15077 in Booty Bay
4. Wait until someone completes Quest:Master Angler https://wowgaming.altervista.org/aowow/?quest=8193
5. Trigger/Wait for server restart while the Stranglethorn Fishing Extravaganza event is still up
6. Log in as fast as possible
7. Try to complete Quest:Master Angler https://wowgaming.altervista.org/aowow/?quest=8193
8. Inspect your achievements for Master Angler of Azeroth https://wowgaming.altervista.org/aowow/?achievement=306

##### EXTRA NOTES:
The same issue may be also affecting Kalu'ak Fishing Derby https://wowgaming.altervista.org/aowow/?quest=24803 in Northrend where rewards from the event are even more lucrative.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/091b072be10ecbe75d9aa38c19e2262e0cbc7690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
thanks for the detailed report and sorry for the delay in checking it !!
