### ISSUE TITLE
[Warrior] Debuff from Improved Thunder Clap talent is overwritten by regular Thunder Clap spell

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#1029]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If warrior without any point in Improved Thunder Clap talent uses Thunder Clap spell on mob which has already applied Thunder Clap debuff from the warrior, who has at least one point in Improved Thunder Clap talent, the debuff is overwritten as they would be the same effect.

The above bug makes investing points in Improved Thunder Clap talent a bit of waste for warrior tanks as they need to constantly apply their improved effect when they are paired with other warriors that spam regular Thunder Clap.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Debuff of Thunder Clap spell, enhanced by Improved Thunder Clap talent, should be only overwritten by the same or more powerful version.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have one warrior with at least one point in Improved Thunder Clap talent
2. Have one warrior with no points in Improved Thunder Clap talent
3. Let both warriors attack the same target
4. Wait till Warrior with Improved Thunder Clap applies Thunder Clap debuff on the target
5. Pay attention to debuffs on target while the other warrior (the one without Improved Thunder Clap) applies Thunder Clap debuff

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/091b072be10ecbe75d9aa38c19e2262e0cbc7690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
While I agree with your assessment, do you have a source for blizzlike behavior?

**Comment by Hihilist** [comment]
Actually no text on that. Only found an entry that debuff from Thunderfury overwrites Improved Thunder Clap (3/3) and vice versa...but they are of the same strength which makes sense.

Plus current overwrite would also hamper usability of Warrior T2,5 bonus.

**Comment by tbcxd** [comment]
> While I agree with your assessment, do you have a source for blizzlike behavior?

This should work the same for all debuffs/buffs.
The stronger effect should always take the place of a weaker one and not get replaced if the weaker spell is casted again

**Comment by Stump876** [comment]
I agree, but proof goes a long way if it can be found. I did find something that shows buff/debuff stacking- see the Blue post [here](https://wowwiki-archive.fandom.com/wiki/Buff), but nothing on overriding it.
