### ISSUE TITLE
Tirisfal Glades - Cursed Darkhound

### ISSUE THREAD

**Issue by blackcrowX** [chromiecraft/chromiecraft#103]
##### ISSUE: FACTION SIDE:

 ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1 - 19

##### SMALL DESCRIPTION:

In the Tirisfal Glades in Nightmare Vale there are Cursed Darkhounds spawning underground.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mob would spawn aboveground.

##### CURRENT BEHAVIOUR:

The Mob Cursed Darkhound spawns "underground" and if not targeted beforehand it appears as if it just randomly spawned out of the ground.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1   Go to the Spawn Point at 51.2 / 70.2
Step 2   Mob is under the Terrain 
Step 3   Mob aggros and comes out the ground

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a4115862de1cd6f37b70969c87df79f327457dd1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by blackcrowX** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/79520609/108848832-c352b180-75e1-11eb-91ab-4263a8bf5918.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/79520609/108848834-c3eb4800-75e1-11eb-8ae2-4dc1efeea2e4.jpg)

**Comment by Stifler82** [comment]
It is not a bug, do you have the **enGB** or **enUS** Client?


**Video Test:** [Tirisfal Glades   Cursed Darkhound](https://youtu.be/VeCXTTl3tw4)

**Comment by Cosmic-Cocoa** [comment]
I actually encountered this darkhound too. It was one in particular and I ran into blackcrowX when they were out in Tirisfal with the same issue. My screenshot has the minimap location where we were when we encountered it.

![Darkhound Spawned Underground](https://user-images.githubusercontent.com/78349628/109268424-ad571380-77d0-11eb-8c7b-22d1055f4824.png)

I'm stealthed right on top of the mob, but it's under the world. I'm using an enUS client.

We're by this tower, just south of it, in Tirisfal, and usually there's a scarlet mob near the area too, but we had already killed it for these screenshots:
![tirisfal](https://user-images.githubusercontent.com/78349628/109268797-34a48700-77d1-11eb-8ea2-6e024893d6c6.png)

**Comment by Stifler82** [comment]
**You must realize** that when you post a Bug **(of any kind it is)**, you **must be precise**, giving coordinates, showing references on the map (as in this case), **trying to make us understand where the problem is**, because **we cannot fix something we don't able to see**..

So, **since I am not able to reproduce the bug**, for me **THERE IS NO BUG**, I leave the report open for a day, waiting for you to give me more details, **if** by tomorrow you do not give any update about it, I will close the report..

**Another Video TEST:** [Cursed Darkhound](https://youtu.be/wnM774FKzdM)

**Comment by Cosmic-Cocoa** [comment]
I hear you, Stifler82. Sorry for the trouble you've had reproducing it so far.

I ran out to check if it's still there and managed to find it again. It's health bar / nametag didn't show up until I managed to aggro it. I'm downloading a coordinates addon now, reinstalling a clean ChromieCraft enUS client, and will see if I can still reproduce it and get better screenshots for ya.

**Comment by Cosmic-Cocoa** [comment]
Okay, fresh ChromieCraft install. TomTom addon.

I started out directly south of the tower in between it and the tunnel that leads to Undercity.

![Darkhound_1](https://user-images.githubusercontent.com/78349628/110036299-7027df80-7d02-11eb-8245-071c25d01a82.png)

I killed the missionary in the screenshot and walked toward the tunnel.

The dog popped out of the ground at the coordinates (under the minimap) in this second screenshot.
![Darkhound_2](https://user-images.githubusercontent.com/78349628/110036345-7c13a180-7d02-11eb-9087-04db8dd75466.png)

It might be easier to find if you are on a lower level character and mobs can aggro to you (so not in GM mode). I did not kill the darkhound, I ran off its aggro.

**Comment by Stifler82** [comment]
thanks for the right coordinates, now I fix it.
![WoWScrnShot_030621_235430](https://user-images.githubusercontent.com/1884642/110224842-5e4b6580-7ed7-11eb-8896-44e3e407a268.jpg)

**Comment by Stifler82** [comment]
Fixed!
-
**Fix will be up soon...**
![WoWScrnShot_030721_000629](https://user-images.githubusercontent.com/1884642/110225021-0877bd00-7ed9-11eb-8d33-35e6e0b50a98.jpg)

**Comment by Cosmic-Cocoa** [comment]
Awesome, thanks for working with us, @Stifler82!
