### ISSUE TITLE
[Fishing] Empty catches despite max skill and ofther fishing enhancments applied

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#1030]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Despite having max skill in the Fishing profession and having applied multiple fishing enhancements (hat & boots, fishing rod, lure and enchantment, all with + fishing) player may experience cases where they would properly reel a fish but instead they get nothing.

On Wowiki website for Fishing article we can find "As of 3.1, there is no longer a minimum skill requirement to fish in any zone, and **all casts will catch something and award a chance for a skill-up**. However, if your skill level is too low for a zone, you will catch mostly vendor trash items. The skill level required to guarantee "no junk" catches is equivalent to the old "no get away" level."

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Using Fishing skill and properly reeling should always rewards the player with something as follows:
- if the player has enough skill in Fishing, assigned to the zone they fish, they should get proper fish from that area with according chance for a skill up
- if the player has not enough skill in Fishing, assigned to the zone they fish, they should get junk catches with also according chance for a skill up

##### SOURCE:
https://wowwiki-archive.fandom.com/wiki/Fishing 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Reach the maximum skill in Fishing profession (right now 300)
2. Got to any area that yields fishes from Fishing with 300 skill (e.g. Stranglethorn Vale)
3. Apply all the fishing enhancements you can have (hat & boots, fishing rod, lure and enchantment, all with + fishing)
4. Start fishing, each time paying attention to the caught fish

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/091b072be10ecbe75d9aa38c19e2262e0cbc7690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
It's something I've noticed as well on CC, though my fishing is not maxxed. You will fish up a blank. I don't think it has anything to do with fishing skill, it's just more noticeable at max level. I was able to confirm this on a local AC server. If you turn auto loot off (or shift click when fishing) the loot screen will remain until you "loot" even if it's empty.
