### ISSUE TITLE
Boat from Baradin Bay -> Darkshore doesn't run

### ISSUE THREAD

**Issue by monnie17** [chromiecraft/chromiecraft#1034]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When waiting for the boat to take you from baradin bay to darkshore, it never turns up. The other boat from the same port that takes you to Dustwallow marsh does run though.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The boat should turn up.

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to baradin bay
2. go to the right hand side port
3. wait for the boat
4. it doesn't show

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
Thats because in Wotlk the Boat from Baradin bay goes to HOwling Fjord in Northrend, whic his currently disabled. The boat to Darkshore in Linked to Stormwind now.

**Comment by monnie17** [comment]
Then my guide misleads me! Sorry about that. Now I'm running through the
barrens for no reason!

**Comment by pop-pig** [comment]
No worries :) WotLK is a whole new world if you've never played it before!
I'll close this issue, thanks for reporting anyways :D
