### ISSUE TITLE
Battleground queuing announcement advertise the wrong number of required players.

### ISSUE THREAD

**Issue by iEmpress** [chromiecraft/chromiecraft#1035]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Warsong Gulch has an announcement when players queue. Saying x/4 players queued. But the match does not start until 5 players are queued.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wait for 4 people to queue for the bracket.
2. Queue does not pop.
3. Wait for 5 people to queue for the bracket.
4. Queue pop.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Tachtzehn** [comment]
Experienced the same thing. Queued as 4/4, nothing happened. 5th member queues, the BG starts.
![WoWScrnShot_062921_134534](https://user-images.githubusercontent.com/83389835/123862368-e07bf180-d8ed-11eb-8c61-e7069c9948ae.jpg)
![WoWScrnShot_062921_134715](https://user-images.githubusercontent.com/83389835/123862375-e4a80f00-d8ed-11eb-8c4c-73256bf3b8bb.jpg)

**Comment by Helias** [comment]
probably related to https://github.com/azerothcore/mod-cfbg/issues/68
hope to investigate and fix asap
