### ISSUE TITLE
Render's rock mobs (blackrock champions etc) drop an unusual amount of green items

### ISSUE THREAD

**Issue by Lexine1** [chromiecraft/chromiecraft#1038]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Not sure if this is intended but, blackrock champions and other mobs in Render's rock (Northside of Redrige Mountains) drop way too many greens. 
In total I killed around 20 mobs, and I got 6 uncommon and 1 rare item when I was doing my quest. 
I kept killing more after that and their droprates stay the same. I'm getting rich here.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Not sure if this is suppossed to work like that or not.

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just go there and kill mobs I guess??
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I can't confirm it, killed several dozens and only got one green and one blue (AC HASH/COMMIT: 53ab534) :

![WoWScrnShot_063021_041727](https://user-images.githubusercontent.com/82579073/123887692-a39a1400-d95a-11eb-9c80-29c44f70722d.jpg)
![WoWScrnShot_063021_041753](https://user-images.githubusercontent.com/82579073/123887723-af85d600-d95a-11eb-8058-9b4ceb734206.jpg)

This is a work for one of our experts in data tables ;)

**Comment by temperrr** [comment]
Can confirm the initial triagers response. There does not seem to anything wrong with the droprates of the monsters there. I guess you were just lucky!
