### ISSUE TITLE
Infinite Victory Rush is still usable

### ISSUE THREAD

**Issue by DotAthame** [chromiecraft/chromiecraft#1039]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [x] 20-29
- [x] 30-39
- [x] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

I noticed how Victory rush is still bugged. I can infinitly use it. First I kill a mob, then the second mob my last hit would be [Execute] but instead of using [Execute] I use [Victory Rush]. Because of that there will be a problem occuring in codes making me infinitly use it. 
![image](https://user-images.githubusercontent.com/86686088/123856828-d7a51300-d921-11eb-85ed-c7c96bbb5efe.png)
as seen in the picture above tested with my friend. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not make it infinitly?

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to any mob that holds experience or honor nearby.
2. Kill that mob and make sure you have victory rush.
3. Go to the second mob and hit it till its 1%HP.
4. Kill the 2nd mob with victory rush.

##### EXTRA NOTES:

Non are needed, just victory rush

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
Hi, thanks for the report.
Confirmed and reproduced (badly) on a local AC server https://youtu.be/drGbSmA_7A8
I had cheats for rage cost & cooldowns, but you can see that you still can't cast Victory rush when you're not supposed to, except if Victory rush is used as the killing blow.
