### ISSUE TITLE
Did not receive RDF satchel at end of dungeon

### ISSUE THREAD

**Issue by formiclol** [chromiecraft/chromiecraft#1041]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Queued for RDF on my tank (L39).  Queue popped and got teleported to SM:GY.  2 members of the group got teleported to SM:Cath so we had to kick.  One of the 2 got added back.  Completed dungeon and did not receive satchel or gold reward.  Plenty of free bagspace and it did not show up in the mail.  Note that SM:GY is not available when I select 'Specific Dungeon' in the RDF window.  I can't remember if the Completed Dungeon UI element popped up or not.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should receive Satchel of Helpful Goods upon killing the final boss, or it gets sent in the mail if bags are full.

##### STEPS TO REPRODUCE THE PROBLEM:

Not sure if this is repeatable, don't have time to run another dungeon
1. Queue for dungeon
2. Complete dungeon
3. Should receive satchel in bags or mail if bags are full

##### EXTRA NOTES:

Character name is Krunk if you want to check logs or something?

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
Not in a position to test right now, but I think this is probably another symptom of #569

**Comment by syssneck** [comment]
Yes, this seems like another issue/side effect caused by: [AC issue#5914](https://github.com/azerothcore/azerothcore-wotlk/issues/5914). I don't think we need another issue on AC for this, as we already have one.
