### ISSUE TITLE
Improved blizzard not working properly

### ISSUE THREAD

**Issue by giveitusaraw** [chromiecraft/chromiecraft#1042]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Improved Blizzard isn't working properly, it slows the targets but not at the correct %. 
https://wowgaming.altervista.org/aowow/?spell=12488

##### EXPECTED BLIZZLIKE BEHAVIOUR:

With the correct % (60) i could use 2 times blizzard at max range without mobs hitting me.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
Hi, thanks for the report!
From your report, I understand that in your opinon, rank 3 of Improved Blizzard should slow by 50%, is that correct?
If that's the case, your bug report is incorrect, according to wowpedia: https://wowpedia.fandom.com/wiki/Improved_Blizzard_(mage_talent)
> Patch 3.0.8 (2009-01-20): The snaring effect has been reduced to 20/40/50%.

**Comment by tbcxd** [comment]
> Hi, thanks for the report!
> From your report, I understand that in your opinon, rank 3 of Improved Blizzard should slow by 60%, is that correct?
> If that's the case, your bug report is incorrect, according to wowpedia: https://wowpedia.fandom.com/wiki/Improved_Blizzard_(mage_talent)
> 
> > Patch 3.0.8 (2009-01-20): The snaring effect has been reduced to 20/40/50%.
> 
> edit: moreover, rank 1 slows by 25%, I think the wowpedia page is incorrect, if you check the patch 3.0.8 page: https://wowpedia.fandom.com/wiki/Patch_3.0.8
> 
> > [Improved Blizzard]: The snaring effect has been reduced to 25/40/50%.

Your reply is correct.
Imp blizzard rank 3 should be 50%.
It starts at 25% for rank 1, 40 for rank 2 and 50% for last rank.

The report is not correctly filled.
