### ISSUE TITLE
Stormwind Guard directs you to wrong place in chat when asking for a shaman trainer. 

### ISSUE THREAD

**Issue by Hemingway1970** [chromiecraft/chromiecraft#105]
##### CONTENT PHASE:

N/A

##### CURRENT BEHAVIOUR:

Guard directs you to see Shaman trainer not available until after Cataclysm launch. 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Ask Stormwind Guard for Shaman trainer
Step 2 Read reply
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a4115862de1cd6f37b70969c87df79f327457dd1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
I assume it's this repsonse from [Stormwind City Patrollers](https://wotlkdb.com/?npc=1976) or [Stormwind City Guards](https://wotlkdb.com/?npc=68) when asked for a **Shaman Class Trainer** which smells a lot like it's from Cataclysm.
![image](https://user-images.githubusercontent.com/7461137/109325063-c81f9b80-7855-11eb-8f96-cec5493103a9.png)

**Comment by FrancescoBorzi** [comment]
@necropola thanks for clarifying this and for the screenshots. The issue has been correctly linked.

thanks for your report @Hemingway1970 , next time please try to be more descriptive
