### ISSUE TITLE
[Ungoro Crater] Ravasaur Runner spamming Trash

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1052]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Ravasaur Runners (https://wowgaming.altervista.org/aowow/?npc=6506) are Spamming Trash every attack.
![trash](https://user-images.githubusercontent.com/80769357/124307138-ab7ad380-db67-11eb-9bfb-a0c9a67faeb6.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should be using Trash at appropriate interval.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 23821
2.  Observe damage

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. The problem here seems to be not so much that it is spamming Thrash, but that it has it at all. Note that TBC WH and Wowpedia both do not mention this in the list of the Ravasaur's abilities. Therefore this is another instance of a wider known issue (https://github.com/azerothcore/azerothcore-wotlk/issues/6118) where creatures have Thrash when they shouldn't. (Note the Ravasaur is listed here.) 

Closing this as a known issue accordingly.
