### ISSUE TITLE
A few barrels fade out too soon in Redridge Mountains

### ISSUE THREAD

**Issue by syssneck** [chromiecraft/chromiecraft#1054]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

A few barrels in Redridge Mountains disappear even when other barrels are still visible. It depends a bit on the angle you are looking from. I noticed this disappearing for guid: 20788 Barrel of Milk (the first number is the guid? Just see the screenshots) and guid: 31127 Battered Chest (Idk why it says Battered Chest these are also a barrels for me).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The barrels shouldn't fade out so early. Other barrels and other game objects are still visible even at greater distances.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the mentioned game objects
2. walk close to the objects and move away
3. try from different angles 
4. see that the objects disappear/fade and others around do not

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft
![Example 1](https://user-images.githubusercontent.com/68868567/124311952-d3ba0080-db6e-11eb-9042-9a970420c924.png)
![Example 1 missing](https://user-images.githubusercontent.com/68868567/124312290-56db5680-db6f-11eb-8ceb-1487aac7edd6.jpg)
![Example 2](https://user-images.githubusercontent.com/68868567/124312300-5ba00a80-db6f-11eb-86c9-da85473b60e0.jpg)
![Example 2 missing](https://user-images.githubusercontent.com/68868567/124312307-5e9afb00-db6f-11eb-9d82-55caf2e1f27e.jpg)

**Comment by Azcobu** [comment]
Thanks for the report. The small barrels you're looking at don't show up on `.gobject near` because they're not world objects spawned from the AC database, the way the Battered Chest and the Barrel of Milk nearby are. Instead, the barrels are just world decorations ('passive doodads' as the game engine calls them). The upshot of all this is that their visibility or fade distance isn't controlled by the AC server as far as I know, it's client-side and thus can't be modified or fixed without patching the client.

Will leave this open for a day or two in case anyone else has more info.
