### ISSUE TITLE
(Young) Moonkin should not cast Moonfire

### ISSUE THREAD

**Issue by necropola** [chromiecraft/chromiecraft#106]
##### ISSUE: FACTION SIDE:
![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
[Moonkin](https://wotlkdb.com/?npc=10158) and [Young Moonkin](https://wotlkdb.com/?npc=10159) should not be able to cast [Moonfire](https://wotlkdb.com/?spell=8921). They don't even have a Mana bar but they spam this ability from range and in melee.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They only should have melee attacks.

##### CURRENT BEHAVIOUR:
See **Small Decsription**

##### STEPS TO REPRODUCE THE PROBLEM:
Visit the Moonkin cave near Auberdine, e. g. as part of the Night Elf Druid Bear Form quest, and fight them.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7ec204943a3080071e0f1d7b7d18e10cbc4d1918

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
hello @necropola , first of all thanks for your report!

> EXPECTED BLIZZLIKE BEHAVIOUR:
> They only should have melee attacks.

Do we have any official sources showing that?

**Comment by necropola** [comment]
- Neither WotLKDB nor aowow show any abilitiies
- They have no mana bar
- My memory, i. e. I thought WTF when I did the druid quest
That's the best I can come up with.

**Comment by Stifler82** [comment]
I confirm, this NPC has no skill whatsoever,
  it only does melee attacks

**Comment by Stifler82** [comment]
There is no Bug!
what are you talking about?
**Video Test:** [Young Moonkin should not cast Moonfire](https://youtu.be/nI60KLlhCTA)
