### ISSUE TITLE
Maraudon - Purple Crystals mobs not spawning on second run after first run.

### ISSUE THREAD

**Issue by baaronz** [chromiecraft/chromiecraft#1063]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I did a run of Maraudon - Purple Crystals. After I queued for another run we got into the dungeon but the mobs we killed in the last dungeon weren't here in the new instance. I was queued with completely different people than the last run and even they were surprised because it was their first run. Every time I queue for it all the mobs are missing even after relogging. I tried resetting all instances and it still does not help.

I have provided a video of it happening.
https://youtu.be/EWLIYT7Zowg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should be all there like it was in the first run before they all dissapeared.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Clear out one run
2. Kill last boss
3. Queue again
4. Mobs killed in first run shouldnt be there in the second run despite there being other people

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
Hey @baaronz  can you give us an update on the situation? I heard of no other player with that issue. I assume the issue resolved itself (maybe through a server restart)?

**Comment by iraizo** [comment]
I could also not reproduce this

**Comment by Azcobu** [comment]
No response and no other reports of this that I'm aware of, think we're okay to close this one now.
