### ISSUE TITLE
Hunter's "Volley" doesn't proc "Aspect of The Viper"

### ISSUE THREAD

**Issue by XionDemise** [chromiecraft/chromiecraft#1064]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So as of right now, When using volley with Aspect Of The Viper nothing happens but the usual 60 mana gain, it won't even trigger the aspect in general.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If my memory serves right the skill "Volley" should trigger "Aspect of the Viper" because explosive trap ALSO triggers it, And that's an AoE trap skill. as well as freezing trap.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use aspect of the viper on a hunter
2. Use volley and see as nothing happen but the passive viper mana gain
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
@XionDemise 

I've looked into this behavior. 
As per 

> https://wowwiki-archive.fandom.com/wiki/Aspect_of_the_Viper

You can read:

> Aspect of the Viper causes each ranged attack (including the initial application of Serpent Sting, all three charges of Explosive 
> Shot, all three missiles of Multi-Shot, but not including the ticks of Serpent Sting or the damage of Volley) to generate a percentage of the Hunter's maximum mana. 

Unless you have any evidence from 3.3.5a patch that it should regenerate mana, I will mark it as invalid for now.
