### ISSUE TITLE
[Dungeon] Zul Farrak - Sometimes Seargent Bly gets reset after first wave/or doesnt leave the cage at all

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1066]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Sergeant Bly  (https://wotlk.evowow.com/?npc=7604) is sometimes refusing to leave the cage, or "gets reset" and runs back to the cage after 1st wave of mobs dies.
Seems something is breaking the script, doesnt happen every time tho, sometimes it works fine.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Seargent Bly should leave the cage when cages are unlocked and stay out of the cage so players can interact with him to progress the dungeon.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do Zul Farrak dungeon up to the Cages part.
2. Unlock the cages and see if the script works correctly

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
On top of that, i had people reporting (and seen it with my own eyes) that the NPCs never started moving, even though their cages were unlocked and opened.
It also happened repeatedly, that all NPCs stood at the bottom of the stairs and never engaged in the final fight vs the trolls.

**Comment by gurveleg** [comment]
It seem that engaging the mobs too fast, before they come p the stairs and aggro on npcs is one cause of them bugging.
