### ISSUE TITLE
Kolkar Drudge and Outrunner have extreme Fire Resistance 

### ISSUE THREAD

**Issue by necropola** [chromiecraft/chromiecraft#107]
##### ISSUE: FACTION SIDE:
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
[Kolkar Drudge](https://wotlkdb.com/?npc=3119) and [Kolkar Ourunner](https://wotlkdb.com/?npc=3120) resist more than 50% of any Fire Damage thrown at them. Frost Damage works as expected, though.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They should not have any elemental resistance at all ...
... but I cannot find any information/source about elemental resistance on NPCs in any database, although I know that there are certain NPCs in game (usually elementals) that are supposed to have high resistance against a particular school of magic. 

##### CURRENT BEHAVIOUR:
See above.
This is from the combat log of my level 11 Blood Elf Mage (Fireball and Frostbolt are both Rank 2):
![image](https://user-images.githubusercontent.com/7461137/109346106-76850a00-7871-11eb-95e3-336d485e0217.png)
Fireballs work fine on other NPCs in the area, e. g. Scorpids.

##### STEPS TO REPRODUCE THE PROBLEM:
* Go to Kolkar Crag in Southern Durotar near Sen'jin Village
* Fight a few of the Kolkar as a Mage
* Watch the difference in damage between Frost and Fire spells
* Check your Combat Log 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7ec204943a3080071e0f1d7b7d18e10cbc4d1918

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
@necropola : Have you tried checking if that issue is present in other servers, say, for example, in the TrinityCore server (https://tcubuntu.northeurope.cloudapp.azure.com/), or would that be too time-consuming and intrusive to your current testing and gameplay?

**Comment by necropola** [comment]
Well, I have (a bit outdated) local instances of AC and TC running on my Liinux Host (My gaming Windows 10 is running as a VM with GPU passthrough). Maybe I should update them and use them as a reference. Which has the additional advantage of me being a GM on these servers. 😺 
  
I have to say that I'm slightly shocked about certain properties that NPCs have on CC. Those properties -- daze from the front, moonkins casting moonfire when they should not, Kolkar having extreme fire resistance, city guards having cataclysm dialogue -- do not materialize out of thin air. Someone put them there and I would have expected those oddities to have been spotted by someone else already.

Sadly the way in which the World DB is modified and maintained (lots and lost of SQL statements) makes it really hard to find the commits that are responsible for a certain NPC behavior. If the source of the World DB woudl be a set of JSON, YAML or TOML files it woudl be a lot easier.

**Comment by FrancescoBorzi** [comment]
> Maybe I should update them and use them as a reference

definitely! it would be of help if you could do it. By the way, not strictly related to this issue but you might find this document useful: https://www.azerothcore.org/wiki/getting-started

**Comment by necropola** [comment]
OK, I have both a current AC-3.3.5 and a current TC-3.3.5 running locally on my Linux Host and both show the same **funny** fire resistance. The following screenshot is from hitting a Kolkar Drduge with a Fireball Rank 16 on a level 80 Fire Mage. 

![image](https://user-images.githubusercontent.com/7461137/109433417-82f39900-7a10-11eb-9ed7-cbdeb1ee4ed1.png)

Though I don't think that just because it's also in TC makes it correct.

**Comment by illfated** [comment]
> Though I don't think that just because it's also in TC makes it correct.

Fair point, I would also not think so. That is mainly why I asked if it was easy enough to test. We may have to file an issue ticket on TC as well.
I am trying to think if I remember someone in the TC group who enjoys the mage class more than others and finds it easy to test, but I could also mention it in IRC or Discord.

**Comment by necropola** [comment]
I still have no idea what source has been used to determine/justify the current resistance values for NPCs, but here are the results of some SQL statements I ran against `acore_world.creature_template`:
```
select count(*) from creature_template;
+----------+
| count(*) |
+----------+
|    29952 |
+----------+
1 row in set (0.000 sec)
```
**29952 creatures total**

```
select count(*) from creature_template
where resistance1>0 or resistance2>0 or resistance3>0 or resistance4>0 or resistance5>0 or resistance6>0;
+----------+
| count(*) |
+----------+
|      782 |
+----------+
1 row in set (0.013 sec)
```
**782 creatures (2.6%) are having some kind of magic resistance**

```
select count(*) from creature_template where resistance1>50 or resistance2>50 or resistance3>50 or resistance4>50 or resistance5>50 or resistance6>50;
+----------+
| count(*) |
+----------+
|      570 |
+----------+
1 row in set (0.015 sec)
```
**570 creatures (1.9%)  are having at least one magic resistance > 50**

```
select count(*) from creature_template where minLevel<20;
+----------+
| count(*) |
+----------+
|     5296 |
+----------+
1 row in set (0.010 sec)
```
**5296 creatures can spawn with level < 20**

```
select entry, name, minLevel, maxLevel,
resistance1, resistance2, resistance3, resistance4, resistance5, resistance6 
from creature_template
where (resistance1>50 or resistance2>50 or resistance3>50 or resistance4>50 or resistance5>50 or resistance6>50)
and minLevel<20 order by minLevel;
+-------+---------------------+----------+----------+-------------+-------------+-------------+-------------+-------------+-------------+
| entry | name                | minLevel | maxLevel | resistance1 | resistance2 | resistance3 | resistance4 | resistance5 | resistance6 |
+-------+---------------------+----------+----------+-------------+-------------+-------------+-------------+-------------+-------------+
|  3119 | Kolkar Drudge       |        6 |        7 |           0 |          70 |           0 |           0 |          30 |           0 |
|  3120 | Kolkar Outrunner    |        7 |        8 |           0 |          70 |           0 |           0 |          30 |           0 |
|  6123 | Dark Iron Spy       |        9 |       10 |           0 |           0 |           0 |           0 |           0 |         100 |
|  3568 | Mist                |       10 |       10 |         150 |         150 |         150 |         150 |         150 |         150 |
|  1981 | Dark Iron Ambusher  |       10 |       10 |           0 |           0 |           0 |           0 |           0 |         100 |
|  6124 | Captain Beld        |       11 |       11 |           0 |           0 |           0 |           0 |           0 |         100 |
|  3272 | Kolkar Wrangler     |       12 |       13 |           0 |          70 |           0 |           0 |          30 |           0 |
| 16292 | Aquantion           |       13 |       13 |           0 |           0 |         144 |         144 |           0 |           0 |
|  3273 | Kolkar Stormer      |       13 |       14 |           0 |          70 |           0 |           0 |          30 |           0 |
| 12431 | Gorefang            |       13 |       13 |          70 |          70 |          70 |          70 |          70 |          70 |
|  3274 | Kolkar Pack Runner  |       14 |       15 |           0 |          70 |           0 |           0 |          30 |           0 |
|  2149 | Dark Iron Raider    |       14 |       14 |           0 |           0 |           0 |           0 |           0 |         100 |
|  3397 | Kolkar Bloodcharger |       14 |       15 |           0 |          70 |           0 |           0 |          30 |           0 |
|  9523 | Kolkar Stormseer    |       15 |       16 |           0 |          70 |           0 |           0 |          30 |           0 |
|  3275 | Kolkar Marauder     |       15 |       16 |           0 |          70 |           0 |           0 |          30 |           0 |
|  1253 | Father Gavin        |       15 |       15 |           0 |          30 |           0 |           0 |           0 |          70 |
|  3641 | Deviate Lurker      |       16 |       17 |           0 |           0 |           0 |         100 |           0 |           0 |
|  9524 | Kolkar Invader      |       16 |       17 |           0 |          70 |           0 |           0 |          30 |           0 |
|  3662 | Delmanis the Hated  |       17 |       17 |           0 |           0 |           0 |           0 |           0 |          68 |
|  1222 | Dark Iron Sapper    |       17 |       17 |           0 |           0 |           0 |           0 |           0 |         100 |
|  1169 | Dark Iron Insurgent |       18 |       19 |           0 |           0 |           0 |           0 |           0 |         100 |
| 17358 | Fouled Water Spirit |       18 |       19 |           0 |           0 |           0 |          75 |           0 |           0 |
|  5761 | Deviate Shambler    |       19 |       19 |         100 |         100 |         100 |         100 |         100 |         100 |
+-------+---------------------+----------+----------+-------------+-------------+-------------+-------------+-------------+-------------+
23 rows in set (0.000 sec)
```
**23 creatures below level 20 (0.4% of all < 20) are having at least one magic resistance > 50**

**Comment by necropola** [comment]
Since June 2019 TC maintains resistances (and spells) in separate tables. but it looks like this is only a change in structure not content: https://github.com/TrinityCore/TrinityCore/commit/d5fb0a30ec62f3799416326d81d5d14992f9a6df

This change to teh structure was already suggested in 2017 and what I find remakable is teh discussion about the source of the resistance values you find here: https://github.com/TrinityCore/TrinityCore/pull/20977

**Comment by illfated** [comment]
Nice job doing that research. Well done. Good basis for a discussion for what to do about the discrepancies in NPC Resistance stats.

**Comment by FrancescoBorzi** [comment]
thanks all for the feedback. @illfated can you please link this to AC, reporting all the good feedback there?

**Comment by illfated** [comment]
Done. 🙂
