### ISSUE TITLE
[Sunken Temple] Avatar of Hakkar resummon item and gossip menu missing

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#1070]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When finishing [https://classic.wowhead.com/quest=3528/the-god-hakkar](https://classic.wowhead.com/quest=3528/the-god-hakkar) you dont receive [https://classic.wowhead.com/item=10818/yehkinyas-scroll](https://classic.wowhead.com/item=10818/yehkinyas-scroll).
And you should also be able to talk with [https://classic.wowhead.com/npc=8579/yehkinya](https://classic.wowhead.com/npc=8579/yehkinya) to retrieve another scroll (repeatable, but you can carry only one scroll at any time).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When finishing [https://classic.wowhead.com/quest=3528/the-god-hakkar](https://classic.wowhead.com/quest=3528/the-god-hakkar) you should receive [https://classic.wowhead.com/item=10818/yehkinyas-scroll](https://classic.wowhead.com/item=10818/yehkinyas-scroll) and you should also be able to talk with [https://classic.wowhead.com/npc=8579/yehkinya](https://classic.wowhead.com/npc=8579/yehkinya) to retrieve another scroll (repeatable, but you can carry only one scroll at any time).

##### SOURCE:

[https://classic.wowhead.com/npc=8443/avatar-of-hakkar#comments](https://classic.wowhead.com/npc=8443/avatar-of-hakkar#comments)
[https://classic.wowhead.com/item=10818/yehkinyas-scroll](https://classic.wowhead.com/item=10818/yehkinyas-scroll)
[https://classic.wowhead.com/quest=3528/the-god-hakkar#comments](https://classic.wowhead.com/quest=3528/the-god-hakkar#comments)

##### STEPS TO REPRODUCE THE PROBLEM:

1. turn in [https://classic.wowhead.com/quest=3528/the-god-hakkar](https://classic.wowhead.com/quest=3528/the-god-hakkar)
2. dont receive [https://classic.wowhead.com/item=10818/yehkinyas-scroll](https://classic.wowhead.com/item=10818/yehkinyas-scroll)
3. dont be able to talk to [https://classic.wowhead.com/npc=8579/yehkinya](https://classic.wowhead.com/npc=8579/yehkinya) to receive a scroll

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Tested and completed without issues:

![WoWScrnShot_070421_075924](https://user-images.githubusercontent.com/82579073/124373786-03b3f180-dc9e-11eb-9d05-4a6643da2a54.jpg)
![WoWScrnShot_070421_075935](https://user-images.githubusercontent.com/82579073/124373793-13333a80-dc9e-11eb-9bd4-061164f1a347.jpg)
![WoWScrnShot_070421_075944](https://user-images.githubusercontent.com/82579073/124373799-22b28380-dc9e-11eb-8b8d-2befdfac610f.jpg)
![WoWScrnShot_070421_075953](https://user-images.githubusercontent.com/82579073/124373803-31993600-dc9e-11eb-9915-d6e2655a6003.jpg)

**Comment by Stump876** [comment]
Confirmed. Thanks for the report.  He does not offer the scroll after completion of  "The God of Hakkar" quest. 

https://wowpedia.fandom.com/wiki/The_God_Hakkar

"At the completion of this quest, you will be able to ask Yeh'kinya for  [Yeh'kinya's Scroll] to re-spawn the Avatar of Hakkar if you wish.

Through my studies, I see that defeating the god Hakkar's avatar has weakened him. But the bulk of his strength remains, lurking at the far end of the Nether.
You have defeated his avatar once, <name>. Perhaps if you defeat it again you can further weaken the god so that, one day, we might face his true self.
I have prepared a spell that you may use to again summon an avatar of Hakkar within the Sanctum of the Fallen God. Do you want to confront it once again?
Gossip Yes. Give me the spell to summon the avatar."

**Comment by j-hdt** [comment]
potential code fix:

> -- Yeh'kinya's Scroll
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=8579;
UPDATE `creature_template` SET `gossip_menu_id`=60076 WHERE  `entry`=8579;
DELETE FROM `gossip_menu_option` WHERE `menu_id`=60076;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES
(60076, 0, 0, 'I\'d like to have another Yeh\'kinya\'s Scroll', 1, 1, 0, 0, 0, 0, NULL);
DELETE FROM `locales_gossip_menu_option` WHERE `menu_id`=60076;
INSERT INTO `locales_gossip_menu_option` (`menu_id`, `id`, `option_text_loc3`) VALUES
(60076, 0, 'Ich möchte eine neue Rolle.');
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=60076;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(15, 60076, 0, 0, 1, 8, 0, 3528, 0, 0, 0, 0, 0, '', 'Gossip for adding quest item - Player must have q The God Hakkar completed'),
(15, 60076, 0, 0, 1, 2, 0, 10818, 1, 1, 1, 0, 0, '', 'Gossip for adding quest item - Player may not have item in bank');
DELETE FROM `smart_scripts` WHERE `entryorguid`=8579;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(8579, 0, 1, 2, 62, 0, 100, 0, 60076, 0, 0, 0, 56, 10818, 1, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Yeh\'kinya - On gossip select - Add new egg item'),
(8579, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Yeh\'kinya - On gossip select - Close gossip');

**Comment by Wulffgang** [comment]
can confirm, just finished the egg quest and cant get a scroll to re-summon the bonus boss anymore.. (on horde side)

**Comment by aljazz159** [comment]
Confirming the bug, finished the quest yesterday (alliance), can not get the scroll.
