### ISSUE TITLE
[NPC] Jartsam (Darnassus riding trainer) doesn't let non-night elves train how to ride tigers

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1072]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Jartsam doesn't offer the option of learning how to ride mounts at non-night elves that are exalted with Darnassus.
![image](https://user-images.githubusercontent.com/22718174/124369612-7344c500-dc3b-11eb-8a27-cb5234846d8b.png)

I also saw a dwarf asking on the world channel, the same day, if he could learn how to ride mounts in Darnassus.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should let everyone exalted with Darnassus trains how to use mounts.

##### SOURCE:

He litterally tells me he can teach me "the finer points of Tiger Riding"!

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be a non-night elf and be exalted with Darnassus.
2. Talk to Jartsam.

##### EXTRA NOTES:

Jartsam: https://wowgaming.altervista.org/aowow/?npc=4753

Is his dialog option wrong? It seems to refer to the mount training skill back on early Vanilla when you had "Horse Riding", "Tiger Riding", "Raptor Riding".

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

Client HD ground textures "Texturen_0.96"

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. However, as of Patch 1.12.1 there is no specialty riding training at all https://wowwiki-archive.fandom.com/wiki/Patch_1.12.1
"Patch 1.12.1 (26-Sep-2006): The cost structure and functionality of Riding and Mounts was changed.
            Prior to that patch, Riding was an ability rather than a secondary Profession, and had only one rank. Each faction had its own riding skill (tiger riding, horse riding, mechanostrider piloting, ram riding) and the cost was 20g, available at level 40. Exalted reputation was required to learn cross-faction riding skill, but mounts were Bind on Use and purchasable by anyone for 80g." 

The new structure was implemented where trainers trained riding levels, Apprentice: Level 20, Journeyman: Level 40.  You do need the rep to purchase mounts for whatever race's mount you want, but you do not need to train special riding to use the mount.
