### ISSUE TITLE
[Feralas] Quest Hippogryph Muisek - Using Vessel on corpses do not count toward completion

### ISSUE THREAD

**Issue by rdallastra** [chromiecraft/chromiecraft#1073]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When doing quest [Hippogryph Muisek](https://wowgaming.altervista.org/aowow/?quest=3124) using [Hippogryph Muisek Vessel](https://wowgaming.altervista.org/aowow/?item=9619) on corpses do not count towards quest completion (need 10).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Using said item on corpses should count towards quest completion.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get quest [Hippogryph Muisek](https://wowgaming.altervista.org/aowow/?quest=3124)
2. Go to quest area, such as (57,62) in Feralas
3. Kill [Frayfeather Hippogryph](https://wowgaming.altervista.org/aowow/?npc=5300)
4. Use [Hippogryph Muisek Vessel](https://wowgaming.altervista.org/aowow/?item=9619) on corpse

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Tested and completed without issues:

![WoWScrnShot_070421_080459](https://user-images.githubusercontent.com/82579073/124373877-f21f1980-dc9e-11eb-8124-1a551c09189d.jpg)
![WoWScrnShot_070421_080617](https://user-images.githubusercontent.com/82579073/124373885-0236f900-dc9f-11eb-8158-ef30eb669447.jpg)
![WoWScrnShot_070421_080623](https://user-images.githubusercontent.com/82579073/124373890-0ebb5180-dc9f-11eb-8a6a-61e170121092.jpg)
![WoWScrnShot_070421_080635](https://user-images.githubusercontent.com/82579073/124373901-1bd84080-dc9f-11eb-8745-c1e6044ca077.jpg)

**Comment by rdallastra** [comment]
@Eldarix I found what was the problem: my bag was full! After playing the drums an item is created and sent to the bag, but my bag was full and no "bag is full" message was shown. I went back to Feralas with room in my bag and managed to complete the quest. Thanks a lot for your support, I consider this issue closed.
