### ISSUE TITLE
[Dungeon][Sunken Temple] Serpent statue missing - bonus boss (Atal'alarion) not accessible.

### ISSUE THREAD

**Issue by mturca** [chromiecraft/chromiecraft#1074]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Serpent statue missing - bonus boss (Atal'alarion) not accessible.

- Link for the walkthrough -> https://wowwiki-archive.fandom.com/wiki/Temple_of_Atal%27Hakkar/Old_walkthrough

Each of the highlighted platform should have an interactive statue and a puzzle (they need to be activated in order) to spawn an extra boss in the Basement part of the dungeon 

![image](https://user-images.githubusercontent.com/47978220/124370380-ad37ba80-dc7f-11eb-8136-e4c2daece123.png)

Order for the puzzle 
![image](https://user-images.githubusercontent.com/47978220/124370410-17505f80-dc80-11eb-9f68-f5d5f4bb73cb.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Interactive Statues should be present and interactable in order to solve the puzzle for the last boss

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter Sunken Temple
2. advance to the upper floor 
3. kill the mini-bosses present on each platform 
4. No Interactive statue for the puzzle completion present on the platform

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by aithdruid** [comment]
There is another lower level which contains 6 similar platforms with oozes/elementals/worms. The serpent statues are not supposed to be with the troll minibosses. I haven't checked whether atal'alarion actually is accesible, but this screenshot is not where the statues are supposed to be.

**Comment by mturca** [comment]
@aithdruid 

they should be there, were there in vanilla and TBC - they were on those platform with the minibooses - that wasn't changed until after Cata rework 


"Inside the circular hallway there are tunnels that lead to balconies in the inner chamber. Each balcony contains a serpent statue - by activating the statues in a specific pattern (south, north, south west, south east, north west, north east) you will summon Atal'alarion. If you want to save time here, you'll have to try and minimize the number of groups you take on in the circular hallway (although the running distance to avoid mobs may be just as burdensome)."

**Comment by mturca** [comment]
you were right - don't know why i was under the impression that they were on the miniboss platforms - will close the issue

**Comment by mturca** [comment]
you were right - don't know why i was under the impression that they were on the miniboss platforms - will close the issue
