### ISSUE TITLE
[Feralas] Quest Wandering Shay does not complete upon reaching destination/also missing scripted text

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1083]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The quest Wandering Shay (https://wowgaming.altervista.org/aowow/?quest=2845) does not complete upon reaching the end destination.

Shay Leafrunner (https://wotlk.evowow.com/?npc=7774) Is also missing her scripted text lines, also her movement speed is too fast judging by classic WoW video.
GUID 50144

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quest should complete upon reacing the end destianation.
Shay Leafrunner should be using her scripted text lines during the escort.

##### SOURCE:

https://youtu.be/sb3H2P1yT5U?t=1329
https://classic.wowhead.com/quest=2845/wandering-shay#comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 50144
2. Accept the quest Wandering Shay and loot the bell from the box nea rher feet
3. Escort her to Rockbiter camp and see it does not complete
4. Observe no scripted text from her

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Crixxus99** [comment]
Could not complete quest.  Shay or Rockbiter do not acknowledge that she has been brought back to the camp site.

**Comment by Dims21** [comment]
Can confirm, the same thing happened to me as of this afternoon, walked around the camp with Shay but couldn't get the Rockbiter to acknowledge her presence.

**Comment by Orixim** [comment]
It also happened to me at the time of writing this.

**Comment by ukidono** [comment]
still bugged

**Comment by ntrna** [comment]
This also happened to me. I'm hoping that by continuing to mention it, perhaps it will gain some traction.

**Comment by Orixim** [comment]
So, I've been waiting for a couple of hours in the location Shae should be spawning and nothing. She is simply not there nor respawning. Perhaps it is a new bug or am I just unlucky?

**Comment by Orixim** [comment]
So, after some more waiting and asking Linedara to respawn her (request refused), I've opened a new [issue](https://github.com/chromiecraft/chromiecraft/issues/1830) to tackle this.

**Comment by Orixim** [comment]
I went back there today and she was there. I've completed the quest without any issue. She started to wander around only once and got under the ground surface, but the bell worked just fine and she came back on track. Congratulations on the fix!
