### ISSUE TITLE
Cooking Quest "Camlette Surprise" didn't Reward with Cooking Artisan

### ISSUE THREAD

**Issue by snubu** [chromiecraft/chromiecraft#1084]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Finished the quest Clamlette Surprise (Dirge Quikcleave - Gadgezan/Tanaris) at lvl 43 and didn'1 receive the Cooking (up to 300) skill.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Cooking skill should be 300 (Ingame name Itje).

##### STEPS TO REPRODUCE THE PROBLEM:

Quest is completed and Dirge Quikcleave is not offering any quest.

##### EXTRA NOTES:

https://classic.wowhead.com/quest=6610/clamlette-surprise

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
In Wotlk you learn Artisan Cooking from a trainer. This quest only awards the receipe now.

**Comment by Eldarix** [comment]
Indeed: 

https://wotlkdb.com/?quest=6610

Take care and enjoy ;)

**Comment by Eldarix** [comment]
Here you have a complete list of trainers:

https://wotlkdb.com/?skill=185#trainer

**Comment by snubu** [comment]
Played Classic for too long. Thanks for your help and sorry for my clumsiness!
