### ISSUE TITLE
Artisan quest turn in for clamette surprise can be turned in multiple times 

### ISSUE THREAD

**Issue by Bolixz** [chromiecraft/chromiecraft#1087]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance 
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

so basically im able to go to cooking trainers around other cities and get quest to go to Tanaris to turn in quest to start clamette surprise , did this on my Warrior Barz 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

so this quest should be a one time thing that closes all other cooking trainers from giving it 

##### STEPS TO REPRODUCE THE PROBLEM:

1. get quest from cooking trainers from faction cities - requires 225 cooking
2. go to tanaris INN 
3. turn in quest multiple times 
4. may or may not give XP per turn in , did not test it 

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I cann't confirm it in local installation (AC HASH/COMMIT: dc76e6b) :, it does not allow to deliver when 'complete' the second time:

![WoWScrnShot_070521_071801](https://user-images.githubusercontent.com/82579073/124417340-98335800-dd61-11eb-88f0-8b4ad0534a7c.jpg)
![WoWScrnShot_070521_071811](https://user-images.githubusercontent.com/82579073/124417367-a5e8dd80-dd61-11eb-8c57-08b7fe1dc377.jpg)
![WoWScrnShot_070521_071856](https://user-images.githubusercontent.com/82579073/124417390-b305cc80-dd61-11eb-8130-470521fc80dc.jpg)
![WoWScrnShot_070521_071908](https://user-images.githubusercontent.com/82579073/124417411-c1ec7f00-dd61-11eb-9f0c-60f83d7c7612.jpg)

**Comment by Bolixz** [comment]
i forgot to mention , its after completing the quest , the other city cooking trainers will tell you to go there to start the cooking quest , try completing it then turn in the other quest and see if XP is gained from it

**Comment by Stump876** [comment]
@Bolixz Thanks for the report. Can you provide locations, names, screenshots, or GUID's for the NPC's that give the quest? Anything to help ID the NPC giving the quest again. You can get the GUID by typing `.npc info` while having the npc targeted. It will spit out a lot of info, but the GUID will be the second or third line down.

From what I found, the only ones that should give the quests are Daryl Riknussun with alliance quest 6612 [I Know A Guy](https://www.wowhead.com/quest=6612/i-know-a-guy#comments) and Zamja for horde quest 6611 [To Gadgetzen You Go](https://www.wowhead.com/quest=6611/to-gadgetzan-you-go#comments) and these are one time only quests. So if you're able to pick it up from multiple trainers, then that is indeed a bug. However, doing it on my local sever I was only able to do it once. from the NPC above, and I couldn't find a cooking trainer in any city that would give the quest again.

**Comment by Bolixz** [comment]
ill try to reproduce bug this with my alts

**Comment by Stump876** [comment]
I'm going to close this for now. If this can be reproduced, please post it here and I will reopen.
