### ISSUE TITLE
[Item] "Rugged Armor Kit" can't be used on item level 35 legs

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1092]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

(Should also happens to Horde)

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Using some Rugged Armor Kit on some Blidghted Leggings doesn't work because the "level" is too low (notice the error message doesn't specity "item" level).
Rugged Armor Kit: https://wowgaming.altervista.org/aowow/?item=15564
Blighted Leggings: https://wowgaming.altervista.org/aowow/?item=7709

https://user-images.githubusercontent.com/22718174/124401315-bfa10b00-dcf6-11eb-85fe-52de99b63c44.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Because the Blighted Leggings have an item level of 35 (which is the lower end of the item level requirement), you should be able to use Rugged Armor Kit on them.

##### SOURCE:

![image](https://user-images.githubusercontent.com/22718174/124401212-09d5bc80-dcf6-11eb-8bc7-4e84abdddde3.png)
![image](https://user-images.githubusercontent.com/22718174/124401222-1a863280-dcf6-11eb-97d0-2214a7f74cf6.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use a Rugged Armor Kit on some Blighted Leggings.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

Client HD ground textures "Texturen_0.96"

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I think we have to differentiate between the item level and the minimum level required for use the item, it looks the same but it's not  ;) 

Thanks for the report.

**Comment by gurveleg** [comment]
Indeed, it is same with enchants. They take the level required, and not the item level of the item.

**Comment by temperrr** [comment]
As listed above, it has always looked at item level required to wear.
