### ISSUE TITLE
[The Hinterlands] Rescue OOX-09/HL!

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#1096]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Quest [Rescue OOX-09/HL!](https://tbc.wowhead.com/quest=836/rescue-oox-09-hl) has wrong spawn scripts. At 1st spawn point there is x5 waves of mobs, at the 2nd point x2 waves of mobs.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should only x1 waves of mobs at any spawn points.

##### SOURCE:

[Youtube 1](https://youtu.be/fqpvGlC-wvs?t=288),[ youtube 2](https://youtu.be/9OkcOz7rFmU?t=168)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Start quest
2. At 1st point 57 49 were x5 waves
3. At 2nd point 70 63 were x2 waves

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Crixxus99** [comment]
I got infinite waves of 3-4 Owlkin at the first spawn point.  Could kill them all, but the chicken keeps returning to the trigger point.  I could kite them all away and drag the chicken with me, but as soon as they were dead it would return to the ambush site and re-trigger another wave.

**Comment by Crixxus99** [comment]
Managed to complete this today.  Only got about 6 waves at the firdst encounter and 2 waves at the second.

**Comment by lokhengchau** [comment]
Tried the quest today. Got 3 waves of 3 owlbeasts at the first spawn point. Unfortunately I died and failed at 3rd wave.
