### ISSUE TITLE
"Meshlok The Harvester" rare spawn doesn't spawn in Maraudon:Purple Crystals

### ISSUE THREAD

**Issue by XionDemise** [chromiecraft/chromiecraft#1098]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So i and many others tried to farm this rare spawn myself 10 runs of purple crystals and a few others 30 runs and 50 runs but he doesn't seem to pop up. maybe an incorrect spawn rate?

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I understand he's a rare spawn and he won't spawn every single time but watching countless youtube videos in the specified location and checking pristine waters, Purple crystals and even Orange crystals none of them will trigger Meshlok to show up. maybe a broken spawn cycle, According to wowhead it should be a 50% spawn chance but it seems like 0% and even so its so very low compared to the blizzard spawn rate.

##### STEPS TO REPRODUCE THE PROBLEM:

1. https://classic.wowhead.com/npc=12237/meshlok-the-harvester
2. https://www.youtube.com/watch?v=aqXBKqv9XjY
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
Possibly related to https://github.com/azerothcore/azerothcore-wotlk/issues/6658?

**Comment by Azcobu** [comment]
Went and checked on his spawn and he was up, so he does appear:
![WoWScrnShot_070521_200826](https://user-images.githubusercontent.com/81782124/124459166-06f9cb00-ddcd-11eb-9b56-6fecd6a645dc.jpg)

But that's on a freshly started server. Checking the DB shows he has a respawn timer of 1 day, and on top of that, when he spawns he runs a script that has an 85% chance of immediately despawning himself. And that's not even taking pooling into account as per above. So it does seem as if the respawn timer/depsawn chance means he's much too rare compared to retail.

**Comment by T1ti** [comment]
This is due to the pool indeed, in addition to having a 85% chance to despawn from SAI, he only has a 30% chance to spawn from pool. He is spawned with some weird unused placeholders
![image](https://user-images.githubusercontent.com/40864460/124643690-a97b8200-de91-11eb-9922-96f3941d1d25.png)
As a fix I recommend to just drop the pool

**Comment by eTzmNcbkrng** [comment]
>Checking the DB shows he has a respawn timer of 1 day.

This is kind of irrelevant because he exists in a dungeon. A lot of dungeon mobs will have very high respawn times up to 1,209,600 seconds in some cases.
