### ISSUE TITLE
Food and Drink not Stacking

### ISSUE THREAD

**Issue by sergeyburnos** [chromiecraft/chromiecraft#1103]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.
Food and Drink do not stack, it means if i use for instance some Food (https://wowgaming.altervista.org/aowow/?item=21072, or https://wowgaming.altervista.org/aowow/?item=5477 ) and then/or before Drink (https://wowgaming.altervista.org/aowow/?item=21114) i always get only the latest buff.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
I would be expect that 2 Buffs should appear: one for Food and one for Drink.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use Food (https://wowgaming.altervista.org/aowow/?item=21072)
2. Use Drink ((https://wowgaming.altervista.org/aowow/?item=21114)
3. See that only 1 Buff is applied
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Is working as intended: As of Patch 2.1, these buffs count as Well Fed and do not stack with food buffs anymore. https://wowwiki-archive.fandom.com/wiki/Drink

Always a good idea to research it before making a bug report. Sometimes memories can be wrong since stuff changed a lot over the years.
