### ISSUE TITLE
Events missing on "Kill'Em With Sleep Deprivation"

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1104]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

(Should happens to both factions)

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

You may pick all 8 available pillows and wait until they respawn and repeat until you get all 20 of them without ever triggering the event for sleepy dark iron dwarves or Chambermaid Pillaclencher to come.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

> About 8-10 Sleepy Dark Iron Dwarves with 300-400 hp charged at me halfway through gathering pillows. A few minutes after I was done, I heard an emote from Chambermaid Pillaclencher.

Comment on the quest: https://www.wowhead.com/quest=7702/kill-em-with-sleep-deprivation#comments:id=919787

> Takes a good 5 minutes for the Chambermaid to spawn after you loot the first pillow, so be patient. When she spawns, she yells: "_Thieves! Scallywags! Rapscallions! Come face me gigantic pillas!_"

Comment on the quest: https://www.wowhead.com/quest=7702/kill-em-with-sleep-deprivation#comments:id=1033726

> In order for her to spawn, you do not need to continually pick up and delete dark iron pillows. What happens is that as you start to collect them, an event starts. Two waves of 10 sleepy dark iron dwarves will spawn, then the Chambermaid will spawn. Just hang out in the barracks and keep the trash cleared and you should get it eventually.

Comment on Chambermaid Pillaclencher: https://www.wowhead.com/npc=14636/chambermaid-pillaclencher#comments:id=936073

> About 12 of these spawn and run as a group after you've stolen half the pillows for Kill 'Em With Sleep Deprivation. Very low hp. You'll know they've spawned when you see: _Sleepy Dark Iron Work yells: Our pillas! Someone has stolen our pillas!_

Comment on Sleepy Dark Iron Worker: https://www.wowhead.com/npc=14635/sleepy-dark-iron-worker

The amount of Sleepy Dark Iron Worker might be dependent on how many pillows you have managed to steal.

##### SOURCE:

Comments on wowhead. The quest has been added on 3.3 so it's not on TBC wowhead.
The quest: https://www.wowhead.com/quest=7702/kill-em-with-sleep-deprivation
Chambermaid Pillaclencher: https://www.wowhead.com/npc=14636/chambermaid-pillaclencher
Sleepy Dark Iron Worker: https://www.wowhead.com/npc=14635/sleepy-dark-iron-worker

##### STEPS TO REPRODUCE THE PROBLEM:

1. Steal some pillows and wait.
2. Maybe repeat step 1 until you have all 20 pillows.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

Client HD ground textures "Texturen_0.96"

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
Thank you for the report! The event also did not trigger for me. I also noticed, that the respawn time for the pillows is much too low (only about 3 seconds).

**Comment by syssneck** [comment]
[No event for the quest "Kill'Em With Sleep Deprivation" (ID=7702) #6773](https://github.com/azerothcore/azerothcore-wotlk/issues/6773)
