### ISSUE TITLE
Mages' [Glyph of Ice Armor] not applying buff changes

### ISSUE THREAD

**Issue by Madocite** [chromiecraft/chromiecraft#1109]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When a Mage player adds [Glyph of Ice Armor](https://wowgaming.altervista.org/aowow/?item=42743) into their Glyphs it doesn't change their [Frost Armor](https://wowgaming.altervista.org/aowow/?spell=7301)'s buff accordingly on the players active buffs, it seemingly is only changing the contents of the spell tooltip. At the moment the buff does not appear to be applying the 50% increase to its 200 armor bonus on the buff casted, however there is a chance it may be only a visual bug.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Glyph should be altering the buff as described by the tootip text.

##### SOURCE:

Official tooltip information provided for the spell and glyph for the 3.3.5a client.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have a Mage with Frost Armor (Rank 3).
2. Have Glyph of Ice Armor added as a Glyph.
3. Cast your buff.
4. Compare tooltip information when hovering over the spell and the buff on yourself.

##### EXTRA NOTES:

Frost Armor  https://wowgaming.altervista.org/aowow/?spell=7301
Glyph of Ice Armor  https://wowgaming.altervista.org/aowow/?item=42743

- Unknown if numbers displayed on casted buff are incorrect due to a visual bug or the stats are legitimately changed.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
I tested it and the Glyph of Ice Armor does correctly change the armor, but the tooltip does not update. I assume the tooltip not updating with glyphs is a client-side issue. The glyph works as described:
No buff: 85 armor

Frost Armor (no glyph): 85 + 200 = 285 armor (correct)
![unknown_2021 07 06-14 29](https://user-images.githubusercontent.com/68868567/124601403-12e69b00-de68-11eb-9d64-b8fdd56026cd.png)

Ice Armor (no glyph): 85 + 930 = 1015 armor (correct)
![unknown_2021 07 06-14 29_1](https://user-images.githubusercontent.com/68868567/124601367-09f5c980-de68-11eb-933f-5c3e93679d80.png)

Frost Armor (WITH glyph): 85 + 1,5 * 200 = 385 armor (correct)
![unknown_2021 07 06-14 30](https://user-images.githubusercontent.com/68868567/124601241-e763b080-de67-11eb-8354-c7d44a0ccd9e.png)

Ice Armor (WITH glyph): 85 + 1,5 * 930 = 1480 armor (correct)
![unknown_2021 07 06-14 30_1](https://user-images.githubusercontent.com/68868567/124601000-a2d81500-de67-11eb-894d-6688ac4a6f65.png)

**Comment by Madocite** [comment]
![WoWScrnShot_070621_085420](https://user-images.githubusercontent.com/86999264/124621811-d0a56580-de37-11eb-8442-970e3102e663.jpg)
![WoWScrnShot_070621_085426](https://user-images.githubusercontent.com/86999264/124621859-d9963700-de37-11eb-99eb-ce5a47a2137f.jpg)
<img width="437" alt="armor" src="https://user-images.githubusercontent.com/86999264/124622656-8e305880-de38-11eb-987e-c5d14e249d40.png">

Look in chat and you can see I asked someone else in UC what my buff was, they respond with 200. However you can see that the spell information before casted states 300. I'm not sure whats going on but its not my client specifically causing this issue.

**Comment by syssneck** [comment]
Hi Madocite, thank you for your answer!
I think there is a misunderstanding. The tooltip does indeed NOT show the correct armor value, you spotted this one correctly.
The glyph however works as intended (see my post above). To check, whether a buff works correctly, don't read the tooltip, but check the values in your character window instead. If you do so, you will see, that your armor increases by 300 (as it should) when you activate the Frost Armor.

What I meant with client-side issue is, that we can not do anything about the wrong numbers in the tooltips.
If you are interested in the topic, here is another case, where the tooltip does show the wrong value, but it works as intended: [Enhancement Shaman Improved Windfury Totem not applying 4% haste](https://github.com/chromiecraft/chromiecraft/issues/546)

Thanks again for your report, and have a nice day/evening!

**Comment by Madocite** [comment]
Ahh alright thank you! I thought you implied there was something incorrect with my client! All is well then. Thank you for the detailed response.
