### ISSUE TITLE
[Badlands] Quest: Tremors of the Earth (Part 2)

### ISSUE THREAD

**Issue by AchrafB94** [chromiecraft/chromiecraft#1111]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Unable to complete this quest because two of the three pillars are missing: the pillar of Amethyst and the pillar of Opal
The pillar of Diamond is there and drops the item correctly.

![WoWScrnShot_070621_102435](https://user-images.githubusercontent.com/38129241/124579441-03a32580-de47-11eb-960d-ad3719541f79.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Youtube video from classic wow
https://www.youtube.com/watch?v=o7feaCOmsWg

Wowhead
https://classic.wowhead.com/quest=717/tremors-of-the-earth

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to badlands https://wowgaming.altervista.org/aowow/?npc=2888 
2. Start the second quest https://wowgaming.altervista.org/aowow/?quest=717
3. Search for the pillars Amethyst (81:64) - Opal (72:66) - Diamond (84:33)
4. Only the pillar of diamond is found, the other two are missing

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. This is a known issue, and I've submitted a bug fix for this (see https://github.com/azerothcore/azerothcore-wotlk/pull/6726) that should hopefully be merged soon.
