### ISSUE TITLE
[Druid] Tiger's Fury not does not affect Rake, Rip, Ferocious Bite (and maybe others)

### ISSUE THREAD

**Issue by Ziedge** [chromiecraft/chromiecraft#1112]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [X] other frFR

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Using Tiger's Fury does not inscrease Rake, Rip, Ferocious Bite damages. (maybe other spells too)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Tiger's fury, uppon use, should increase damages of feral druids attacks/spells.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Engage a mob and get 5 combo points (for damage visibility overs spells/attacks)
2. Check your attack/spells damages
3. Use Tiger's Fury
4. Some attacks/spells damages are not increased.

https://user-images.githubusercontent.com/82708448/124595745-b1233280-de61-11eb-9ff4-5a2e2b13cdb2.mp4

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
It's working as intended. The extra damage get's added as weapon damage, so only skills that benefit from that will do more damage. rake does not benefit from this as it's purely bleed damage. You can try this yourself using claw with and without tigers fury, same with swipe, ferocious bite etc.
You can see when opening your character window and select the melee stats that it gets added. 

Tested it on local ac.
Here are screenshots from Chromiecraft:
with
![Screenshot from 2021-07-06 17-59-19](https://user-images.githubusercontent.com/20357406/124631778-007a5a80-de84-11eb-80c7-0d9bfbe822a9.png)

without:
![Screenshot from 2021-07-06 17-59-57](https://user-images.githubusercontent.com/20357406/124631800-04a67800-de84-11eb-9e2e-503b42d4b3f9.png)

I
