### ISSUE TITLE
Makrura Clacker and Surf Crawler buggy movement and sometimes freezing inside the water

### ISSUE THREAD

**Issue by RaiseN777** [chromiecraft/chromiecraft#1115]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The mobs called Makrura Clacker and Surf Crawler have a buggy movement on the location Echo Isles in Durotar. Sometimes during a fight with them they go down in the water and sometimes freeze in one place and you can attack them without them coming to you. As well as that, some of them just move left to right without stopping and it says "Evade" when you try to attack these ones.

Makrura clacker: https://wotlkdb.com/?npc=3103
Surf crawler: https://wotlkdb.com/?npc=3107

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They just should have a normal movement like any other mobs you fight and not freeze at one place at times.

##### SOURCE:
I don't have screenshots but if you teleport to Echo Isles and go to the waters you will instantly see these NPC's are buggy.

##### STEPS TO REPRODUCE THE PROBLEM:

 - Which commands to use? Which NPC to teleport to?

Just teleport to npc's called Makrura Clacker and Surf Crawler.

##### EXTRA NOTES:

I provided links above for the NPC's.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Valjan** [comment]
Confirmed, of note the Surf Crawlers will sometimes behave as if they can't swim when in combat with the player moving along the bottom of the ocean until they reach under your location when swimming or moving along the bottom of the ocean until finally reaching you on the beach.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9272
