### ISSUE TITLE
[Item] Winterfall Spirit Beads

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#1119]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

[Winterfall Spirit Beads](https://tbc.wowhead.com/item=21383/winterfall-spirit-beads) missing in loot tables. Can confirm for all Winterfall mobs

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This item is exist in Blizzard universe.

##### SOURCE:

Wowhead. Logic.

##### STEPS TO REPRODUCE THE PROBLEM:

Kill any of Winterfall mobs 100 times.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
You need to complete the pre-quest "Winterfall Activity" by Salfa before Winterfall Spirit Beads can drop [Timbermaw Hold reputation](https://wotlkdb.com/?faction=576). After completing the quest, Winterfall Spirit Beads can drop from Winterfall furbolgs. I killed 70 Winterfall furbolgs after completing the pre-quest and 16 Winterfall Spirit Beads dropped (at this point I already handed in 5 of them, to see if the quest "Beads for Salfa" is working correctly):
![unknown_2021 07 07-16 29_1](https://user-images.githubusercontent.com/68868567/124777498-89ef6280-df40-11eb-998a-f4faeb634fe7.png)

**Comment by Shineslippers** [comment]
Sorry, then i have to check this. Probably my bad.
