### ISSUE TITLE
Fear duration (PVP)

### ISSUE THREAD

**Issue by 123Bug123** [chromiecraft/chromiecraft#112]
##### ISSUE: 
FACTION SIDE: 

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

All contents

##### SMALL DESCRIPTION:

 Any damage caused to a target that is under the effects of either Fear or Psychic Scream should have a chance to interrupt the effect. 

Spell: [Psychic Scream](https://wotlkdb.com/?spell=8122)
Spell: [Fear](https://wotlkdb.com/?spell=5782)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The duration of fear is generally proportional to the amount of damage and number of times the target is damaged. 
Fear + 0 damage/hits = full duration
Fear + lots of damage = very short duration (i.e. breaks early)

##### CURRENT BEHAVIOUR:

Fear is lasting too long in PVP. Multiple instances of feared players being hit by multiple others taking large amounts of damage and the effect does not get interrupted quickly as expected.

EDIT: <s>Hard</s> Unable to replicate in a duels.  Bug was being experienced in Warsong Gulch Battleground.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Fear/Psychic scream another player
Step 2 Have lots of damage applied to said player from multiple characters
Step 3 Observe duration of fear effect

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 123Bug123** [comment]
Tried replicating today in warsong, unable to get much evidence but tried the following

Warlock alone --> fear lasts long, dots not interrupting fear
Warlock + Warrior --> interrupted when warrior charged early in the fear
Warlock + Hunter --> interrupted by unknown, fear lasted 2-3 seconds (as would be expected)

Will try more testing with casters only, was either a fluke to have two different people experience full duration fears with lots of damage in the same battleground or something harder to pinpoint

**Comment by bonfax4** [comment]
Think in wotlk Fear has a damage cap , not a chance to break on damage. Can't find any info on how much the damage cap should be tho.

**Comment by Stifler82** [comment]
The reasons why you are unable **"to replicate The Bug"** and why **you are unable to provide tangible proof** of the problem are two:

**1 - It is not a Bug.
2 - You have no idea how spell Fear works.**

But don't worry, it's all explained here in **the video I made**:
**Video TEST:** [Fear duration PVP](https://youtu.be/ONzC94ZDAMI)

I close.
