### ISSUE TITLE
[The Hinterlands] Razorbeak Skylord missing movement.

### ISSUE THREAD

**Issue by Ziedge** [chromiecraft/chromiecraft#1120]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [X] other frFR

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

 [Razorbeak Skylord](https://wowgaming.altervista.org/aowow/?npc=2659) not moving at all from his spawn point.
 
GUID: 1830

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mob should be roaming a bit and not be glued to it's spawn point.

##### STEPS TO REPRODUCE THE PROBLEM:

1. port to GUID: 1830
2. You can see the mob standing still with no movement.

https://user-images.githubusercontent.com/82708448/124770722-da63c180-df3a-11eb-926f-628ee6bcfe49.mp4

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
Confirmed, no random movement for Razorbeak Skylord (guid = 93612):
![unknown_2021 07 07-18 43](https://user-images.githubusercontent.com/68868567/124801287-f83f1f80-df56-11eb-8bf3-f1eed3badd80.png)
I guess one bug-report for one type of creature is enough.
