### ISSUE TITLE
[The Hinterlands] Razorbeak Skylord not using any spells.

### ISSUE THREAD

**Issue by Ziedge** [chromiecraft/chromiecraft#1121]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [X] other frFR

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

 [Razorbeak Skylord](https://wowgaming.altervista.org/aowow/?npc=2659) not using any spells when attacking you.
 
GUID: 1830

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mob should use [rend flesh](https://www.wowhead.com/spell=3147/rend-flesh) & [wing flap](https://www.wowhead.com/spell=11019/wing-flap) when fighting you.

##### SOURCE:

https://wowpedia.fandom.com/wiki/Razorbeak_Skylord
https://www.wowhead.com/npc=2659/razorbeak-skylord#abilities

##### STEPS TO REPRODUCE THE PROBLEM:

1. Port to GUID: 1830
2. Engage fight and wait long enough without killing him
3. Mob isn't using any spells, only auto attacks

https://user-images.githubusercontent.com/82708448/124774055-c8375280-df3d-11eb-852b-bdd2ea72148a.mp4

##### EXTRA NOTES:

EDIT; it seems that every Razorbeak Skylord in the zone are missing spells.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
Confirmed, no Razorbeak Skylord that I engaged in the Hinterlands is using Rend Flesh nor Wing Flap on me. Multiple sources suggest that they should have these abilities:
![unknown_2021 07 07-19 04](https://user-images.githubusercontent.com/68868567/124801962-bebae400-df57-11eb-87ce-50727bb95419.png)
I guess one bug-report for one type of creature is enough.

**Comment by Ziedge** [comment]
Yep my bad I did the first one then I saw the other bug a few minutes later, I'll try to gather everything in one report next time!

**Comment by syssneck** [comment]
Hey, no problem! Thank you for the report. You can edit your bug-report by clicking on the three dots on top of your post.
