### ISSUE TITLE
Redeeming the Dead Quest NPC not present.

### ISSUE THREAD

**Issue by Tebec** [chromiecraft/chromiecraft#1123]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The body of Sangrias Stillblade for the quest Redeeming the Dead (Blood Elf Paladin resurrection quest) is not present to bring back.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The should be a body to complete the quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Get the quest.
2.  Go to cave where you killed him on a previous quest
3.  Body is not present

##### EXTRA NOTES:

Redeeming the Dead
https://wowgaming.altervista.org/aowow/?quest=9685

Clicking the NPC from the quest results in a DB error, but it says link is:
https://wowgaming.altervista.org/aowow/?npc=17768

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I just ran through this on a belf pally and had no problems, although I'm a bit confused by your mention of a cave, as the body is in Silvermoon City. Was the quest marker pointing somewhere else for you?

![WoWScrnShot_070821_233739](https://user-images.githubusercontent.com/81782124/124936625-de303a80-e045-11eb-8df6-adbea8746dff.jpg)
![WoWScrnShot_070821_233752](https://user-images.githubusercontent.com/81782124/124936630-dff9fe00-e045-11eb-811a-ba0f3c8ed229.jpg)
![WoWScrnShot_070821_233800](https://user-images.githubusercontent.com/81782124/124936644-e12b2b00-e045-11eb-9f44-9fb109a92294.jpg)
![WoWScrnShot_070821_233858](https://user-images.githubusercontent.com/81782124/124936655-e2f4ee80-e045-11eb-9b34-c01275243c84.jpg)

**Comment by Tebec** [comment]
Yeah, it was pointing back to the cave where you killed him, which is where I vaguely remember having to go to rez him before.  Not sure if they moved it or if my memory is just bad.  Thanks.
