### ISSUE TITLE
[Feralas] Rescue OOX-22/FE!

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#1125]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Rescue OOX-22/FE!](https://tbc.wowhead.com/quest=2767/rescue-oox-22-fe). Here is atleast 2 places during the quest were chicken clipping through textures. Waves of mobs and not flat ground is good trigger to it.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No clipping.

##### STEPS TO REPRODUCE THE PROBLEM:

Do quest.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I just ran through the quest on my local server and didn't run into any visible clipping issues. (I'd post the video, but the quest takes about 9 minutes to finish, so it's a bit long to fit here.) Can you say more about where the clipping was happening?

**Comment by Shineslippers** [comment]
OOF, i'll try to repeat with another character but it took a while. I'll update this message later.

**Comment by Azcobu** [comment]
No worries, better to have too many reports than too few. I'll have to check out the underground ape you mentioned though, that sounds worth a look.
