### ISSUE TITLE
[Darkmoon Faire] "Rituals of Strength" and "More Dense Grinding Stones" unavailable at 2500 friendly

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1126]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

(Should happens to both factions)

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The quest "Rituals of Strength" is no longer available once you hit 2500 friendly with Darkmoon Faire.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Rituals of Strength should be available until 5999 friendly (since it's the quest that gives the rep).
Once at least 5999 friendly, More Dense Grinding Stones should be available in order to replace Rituals of Strength.

##### SOURCE:

Says turning in Dense Grinding Stones will be always available (for tickets): https://classic.wowhead.com/item=19491/amulet-of-the-darkmoon#comments:id=2697068
Says the Reputation Cutoff is 5999/6000 (the moment the quest switches). https://classic.wowhead.com/guides/classic-darkmoon-faire

##### STEPS TO REPRODUCE THE PROBLEM:

1. 

##### EXTRA NOTES:

I am level 49 on the screenshot.
![WoWScrnShot_070721_000114](https://user-images.githubusercontent.com/22718174/124846120-1c562d00-df66-11eb-83c5-7a8ba44b6fe0.jpg)

Rituals of Strength: https://classic.wowhead.com/quest=7893/rituals-of-strength
More Dense Grinding Stones: https://classic.wowhead.com/quest=7939/more-dense-grinding-stones

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

Client HD ground textures "Texturen_0.96"

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
I've just tested this and found the issue seems to be an incorrect questgiver ID, rather than the rep issue. "Rituals of Strength" is available for me up to 5500 rep from Kerri Hicks, but after that, the followup quest "More Dense Grinding Stones" is given by Chronos, the undead near the wagons at the opposite end of the fairground. The handin is still at Kerri though. So the workaround for now is just to talk to Chronos instead until we can fix this questgiver ID.
