### ISSUE TITLE
[Ashenvale] Quest Supplies to Auberdine - First Ambush Ignored by NPC

### ISSUE THREAD

**Issue by adriansutanahadi** [chromiecraft/chromiecraft#1127]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Quest: Supplies to Auberdine (https://classic.wowhead.com/quest=976/supplies-to-auberdine)

In short, I have to escort an NPC (Feero Ironhand https://classic.wowhead.com/npc=4484/feero-ironhand). During the escort, there are supposed to be 3 ambushes. During the first ambush, the NPC (Feero Ironhand) completely ignored the mobs as I aggroed them. This does not happen in the second and third ambush (it works as expected, Feero Ironhand helped me hit the mobs).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC Feero Ironhand should not ignore the mobs during the first ambush.

##### SOURCE:

I can't reproduce the bug again since I have turned the quest in, but the expected blizzlike behaviour should be like this: https://www.youtube.com/watch?v=xIaSP8YE_xg

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept quest Supplies to Auberdine
2. Follow NPC Feero Ironhand until the first ambush
3. NPC Feero Ironhand will ignore the mobs during the first ambush
4.

##### EXTRA NOTES:

Edit: I am not really sure, but I might have been invisible as a druid in cat form during the first ambush. Hope this info can help

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
Hi, I tried the quest two times and also as a druid in catform the second time, but each time he engaged on all three ambushes.
First time (first ambush):
![unknown_2021 07 08-10 38_1](https://user-images.githubusercontent.com/68868567/124893298-e3a46b00-dfda-11eb-9893-afa0fef97b29.png)
Second time prowling in catform (first ambush):
![unknown_2021 07 08-10 52](https://user-images.githubusercontent.com/68868567/124893427-020a6680-dfdb-11eb-82b9-b64a757faf4c.png)

**Comment by gurveleg** [comment]
Should have been fixed with #395 , dont know if it is live on Chromiecraft tho.

**Comment by Efymer** [comment]
This quest has some issues:

TBC video: https://www.youtube.com/watch?v=NZaDRm3E9T4

- The NPC Feero Ironhand should be running instead of walking.
- Spawn points of Assassins is wrong.
- First assasins wave is using caster spells being melee and not attacking the NPC Feero Ironhand (I could reproduce it on my AC env).

And I just checked until the first wave...

**Comment by adriansutanahadi** [comment]
I have been able to reproduce it. Apparently, I was on bear form, not prowling on cat form.

Steps to reproduce:

1. Accept quest Supplies to Auberdine
2. Follow NPC Feero Ironhand until the first ambush
3. Taunt the mobs before NPC Feero Ironhand have the chance of being hit
4. NPC Feero Ironhand will ignore the mobs during the first ambush

Screenshot:
![capture](https://user-images.githubusercontent.com/6983246/125009420-1ca21580-e097-11eb-9dc4-57b9c379a632.jpg)

I haven't checked it with the second and third ambush though.
