### ISSUE TITLE
Zul'Farrak Rares 

### ISSUE THREAD

**Issue by airness456** [chromiecraft/chromiecraft#1128]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So I have been farming Zul'Farrak over and over for the last few days and none of the 3 rare bosses ever spawned. I also went solo in stealth and resetted the instance countless times and no rare ever spawn either.

1- [Dustwraith ](https://www.wowhead.com/npc=10081/dustwraith)
2- [Sandarr Dunereaver ](https://www.wowhead.com/npc=10080/sandarr-dunereaver)
3- [Zerillis ](https://www.wowhead.com/npc=10082/zerillis)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should spawn randomly with a low spawn chance.

##### SOURCE:

Trinitycore right now doesnt support a correct pooling/spawning mechanism to cover rare creatures in vanilla dungeons.
Its either have them always spawned or not at all. Therefore, nearly all rare creatures in vanilla dungeons are handled wrong, if at all.

Since AzerothCore is based on Trinitycore, they probably share the same problem too.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Farm ZF and notice that none of the rares ever spawns.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
> Trinitycore right now doesnt support a correct pooling/spawning mechanism to cover rare creatures in vanilla dungeons.
Its either have them always spawned or not at all. Therefore, nearly all rare creatures in vanilla dungeons are handled wrong, if at all. Since AzerothCore is based on Trinitycore, they probably share the same problem too.

This is true and there's already an open issue here https://github.com/azerothcore/azerothcore-wotlk/issues/6658

If I understand correctly, this causes the set of rares that spawn in any given dungeon to be exactly the same in all instances until the next server restart. The CC server restarts once a day under normal circumstances. I'm not aware of how the pools for ZF rares are constructed, so I suppose it may be possible that all 3 rares are missing (throughout the whole day) on certain days. 

With that being said, I've definitely met Dustwraith and Zerillis multiple times in ZF before, so they *do* spawn sometimes. Unsure about Sandarr Dunereaver. I was never really looking for them so it's possible I missed some spawns.

**Comment by anguaive** [comment]
These 3 creatures are not pooled (which means this isn't related to the issue I brought up), so they spawn independently from each other. Their chance to spawn is 10% (*technically* they always spawn and they get culled with 90% probability, but the outcome is the same). Over the course of 4 instance resets I came across all 3 of them.

![WoWScrnShot_070821_213627](https://user-images.githubusercontent.com/39011611/124981068-6ce88b80-e035-11eb-84a4-23fb5df49d0d.jpg)
![WoWScrnShot_070821_213758](https://user-images.githubusercontent.com/39011611/124981074-6d812200-e035-11eb-9e23-309e38d1cd11.jpg)
![WoWScrnShot_070821_213821](https://user-images.githubusercontent.com/39011611/124981076-6e19b880-e035-11eb-83fd-2f81a1ad95ae.jpg)

**Comment by airness456** [comment]
This works on the local server but no on CC, ive been reseting the instance non stop on CC and they never even spawned once any of them.
