### ISSUE TITLE
[Quest] The Brokering of Peace is missing pre-quest requirement 

### ISSUE THREAD

**Issue by Beastmasterwow** [chromiecraft/chromiecraft#1131]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Quest "The Brokering of Peace" is available for alliance players before completing required pre-quest "The Root of All Evil"
Quest: https://classic.wowhead.com/quest=8484/the-brokering-of-peace
Pre-quest required: https://classic.wowhead.com/quest=8481/the-root-of-all-evil
![Screenshot_5](https://user-images.githubusercontent.com/81812276/124921608-dd24ec00-dff8-11eb-93a7-9e78a2146eba.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quest "The Brokering of Peace" should not be available before completing required pre-quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Timbermaw Hold and be exalted with them.
2. Speak to NPC "Gorn One Eye"
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Note that I'm tagging this as a 40-49 issue even though the quest itself is level 60, because it can be picked up (and has been by players on CC) at a minimum level of 45.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/10634
