### ISSUE TITLE
[Felwood] Corrupted flowers quests

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#1134]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Most of corrupted flowers doesn't despawn or immediately respawn(idk what exacly going on). Only few of flowers near Ashenvale is working properly.Quests: [Corrupted Night Dragon](https://tbc.wowhead.com/quest=4119/corrupted-night-dragon#comments), [Corrupted Songflower](https://tbc.wowhead.com/quest=4118/corrupted-songflower#comments), [Corrupted Whipper Root](https://tbc.wowhead.com/quest=4117/corrupted-whipper-root#comments), [Corrupted Windblossom](https://tbc.wowhead.com/quest=996/corrupted-windblossom#see-also).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After complete quest corrupted flowers should despawn and respawn later. I can't confirm spawn-despawn timer but it should be atleas 3m. 

##### SOURCE:

[Youtube](https://youtu.be/NoLC1rBoBe0?t=146).

##### STEPS TO REPRODUCE THE PROBLEM:

Complete quests.

##### EXTRA NOTES:

Don't forget to check all related quests in "See Also". Here is around 30 related quests. I checked around 20 and most of it without despawn script.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
SQL query to get the GUID of all the spawns:
```SQL
select obj.name, obj.entry, spawn.guid from gameobject_template obj
join gameobject spawn on spawn.id = obj.entry
where obj.name IN ('Corrupted Night Dragon','Corrupted Songflower','Corrupted Windblossom','Corrupted Whipper Root')
```

Add items required to complete quests (stacks up 100):
`.additem 11516 100`

Results of checking each GUID:

name|entry|guid|teleportcommand|comment
--|--|--|--|--|
Corrupted Night Dragon|164885|48848|`.go obj 48848`|Yes but no despawn
Corrupted Night Dragon|173324|48849|`.go obj 48849`|Yes but no despawn
Corrupted Night Dragon|174608|48847|`.go obj 48847`|Yes but no despawn
Corrupted Night Dragon|174684|48850|`.go obj 48850`|Yes but no despawn
Corrupted Songflower|164886|48943|`.go obj 48943`|Instant Despawn?
Corrupted Songflower|171939|48852|`.go obj 48852`|Instant Despawn?
Corrupted Songflower|171942|48924|`.go obj 48924`|Instant Despawn?
Corrupted Songflower|174594|48929|`.go obj 48929`|Instant Despawn?
Corrupted Songflower|174595|48955|`.go obj 48955`|Instant Despawn?
Corrupted Songflower|174596|48851|`.go obj 48851`|Instant Despawn?
Corrupted Songflower|174598|48952|`.go obj 48952`|Instant Despawn?
Corrupted Songflower|174712|48942|`.go obj 48942`|Instant Despawn?
Corrupted Songflower|174713|48957|`.go obj 48957`|Instant Despawn?
Corrupted Whipper Root|164888|48844|`.go obj 48844`|After teleport
Corrupted Whipper Root|173284|48935|`.go obj 48935`|After teleport???
Corrupted Whipper Root|174605|48845|`.go obj 48845`|After teleport
Corrupted Whipper Root|174606|48915|`.go obj 48915`|After teleport
Corrupted Whipper Root|174607|48846|`.go obj 48846`|After teleport
Corrupted Whipper Root|174686|48843|`.go obj 48843`|After teleport
Corrupted Windblossom|164887|48928|`.go obj 48928`|Nothing
Corrupted Windblossom|173327|48856|`.go obj 48856`|After Teleport
Corrupted Windblossom|174599|48858|`.go obj 48858`|Nothing
Corrupted Windblossom|174600|48854|`.go obj 48854`|After moving
Corrupted Windblossom|174601|48857|`.go obj 48857`|Nothing (was in combat)
Corrupted Windblossom|174602|48914|`.go obj 48914`|Nothing
Corrupted Windblossom|174603|48855|`.go obj 48855`|Nothing
Corrupted Windblossom|174604|48951|`.go obj 48951`|After moving
Corrupted Windblossom|174708|48853|`.go obj 48853`|Nothing
Corrupted Windblossom|174709|48936|`.go obj 48936`|Nothing

Conclusion:
Looks like Songflower works as intended. Completing the quest causes the Corrupted Songflower to instantly disappear and Cleansed Songflower takes it's place, then disappears when interacted with.
Night Dragon kind of works, completing the quest causes the Cleansed Night Dragon to spawn but the Corrupted Night Dragon does not despawn, neither does the Cleansed Night Dragon after interacting with it (possibly until server restart).
Whipper Root and Windblossom have unusual behaviour, they have the same non-depsawning issue the is present on Night Dragon, but they don't always spawn a cleansed version, I was unable to find a consistent method for getting the Cleansed object to spawn.

Disclaimer: I'm not personally familiar with how these objects are supposed to work.

**Comment by eTzmNcbkrng** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/7196
