### ISSUE TITLE
[Tanaris] Uldum Pedestal

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#1138]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Uldum Pedestal](https://tbc.wowhead.com/object=142343/uldum-pedestal) on multiple usage call new copies of NPC.
![WoWScrnShot_070921_151757](https://user-images.githubusercontent.com/85256266/125077855-4163b080-e0ca-11eb-8bcb-cdb3583483e8.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Idk how should it be exactly, but not like this. It's hard to find videos or something regarding to multiple usage. Probably it should refresh current NPC call.

##### STEPS TO REPRODUCE THE PROBLEM:

Do quest like [Seeing What Happens](https://tbc.wowhead.com/quest=2966/seeing-what-happens) or [The Stone Watcher](https://tbc.wowhead.com/quest=2954/the-stone-watcher)

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Not sure if it's a client side issue, tried with 2 characters without the npc cloning :D

![WoWScrnShot_071621_070108](https://user-images.githubusercontent.com/82579073/125890220-efccf31e-5af0-4f92-8971-8361c616b96f.jpg)
![WoWScrnShot_071621_070121](https://user-images.githubusercontent.com/82579073/125890255-c139fa99-0e21-45bb-a240-709ebd7cdc59.jpg)
![WoWScrnShot_071621_070138](https://user-images.githubusercontent.com/82579073/125890289-ac1c7ca7-1569-43c7-8f41-ca55ebfc7be0.jpg)
![WoWScrnShot_071621_070507](https://user-images.githubusercontent.com/82579073/125890156-09ece570-87b8-45dc-813a-3d2a54d19443.jpg)

Let's wait to see what other testers say ;) thanks for the report !!

**Comment by Shineslippers** [comment]
Looks like i explained it not clear. You need 2 or more characters to turn in quests.

**Comment by Stump876** [comment]
Multiple turn ins spawn multiple NPC's. Correct? 
You're right, I've looked around and can't find any evidence how this should work with multiples, or that this is not blizzlike behavior. 

My thoughts on it- Completing then starting the next quest begins the script, making it unique to each person doing it. Much like the escort quests in the caverns of time.  

I'm going to close this for now. There's just not enough to show it is incorrect, or how it should work. If you do find any evidence that this is not blizzlike post it here, and we can reopen it. Thanks again for the report.
