### ISSUE TITLE
[FELWOOD] Curse of the deadwood malfunction (Edit: Specific to Bloodthirst ?)

### ISSUE THREAD

**Issue by Taly1337** [chromiecraft/chromiecraft#1139]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Deadwood Shamans correctly apply curse of the deadwood. But it has no effect.
Deadwood shaman : https://wowgaming.altervista.org/aowow?npc=7158 
Curse of the deadwood : https://wowgaming.altervista.org/aowow?spell=13583

![Github](https://user-images.githubusercontent.com/87186363/125082178-2e9bac80-e0c7-11eb-93b4-2b5af1f02f3a.png)

As you can see on the screen : 
My health is 3019. 
I have a gain of +30 (1%) health because of Bloodthirst (https://wowgaming.altervista.org/aowow?spell=23881).
But as I am suffering from the curse of the deadwood, I should only gain (3019*0.01)*0.5=15 health

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Curse of the deadwood should reduce the healing effect by 50% for 2 minutes.

##### SOURCE:

https://wowgaming.altervista.org/aowow?spell=13583
##### STEPS TO REPRODUCE THE PROBLEM:

1. Port to GUID : 4964
2. Engage a deadwood shaman until he casts the curse of the deadwood
3. Cast any healing spell on yourself
4. See if the 50% reduction is correctly applied to the healing

##### EXTRA NOTES:

EDIT: The curse reduces the healing of bandages by 50%. The bug seems to be very specific to Bloodthirst.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I can't confirm it in my local AzerothCore setup (dc76e6b), seems normal the reduction:

![WoWScrnShot_070921_211629](https://user-images.githubusercontent.com/82579073/125120485-2493a100-e0fb-11eb-8bac-7274587dacff.jpg)
![WoWScrnShot_070921_211335](https://user-images.githubusercontent.com/82579073/125120548-3d9c5200-e0fb-11eb-9935-d99c51a88550.jpg)

**Comment by jamadaha** [comment]
It works fine for me as well on local setup (9b3993b) @Eldarix 
![image](https://user-images.githubusercontent.com/53914190/125199539-f206b700-e266-11eb-9869-e26d69d0b5f8.png)
![image](https://user-images.githubusercontent.com/53914190/125199542-f501a780-e266-11eb-941e-16577e41229f.png)

**Comment by jamadaha** [comment]
As for bloodthirst (9b3993b):
![image](https://user-images.githubusercontent.com/53914190/125199898-a6eda380-e268-11eb-91e1-26d40b995afc.png)
![image](https://user-images.githubusercontent.com/53914190/125199923-bd93fa80-e268-11eb-8e19-f88fbbad1af6.png)

Seems to not work on bloodthirst.

**Comment by Stump876** [comment]
Since the triage has been done, did someone want to link this to AC?
