### ISSUE TITLE
Verog the Dervish despawn

### ISSUE THREAD

**Issue by Eistorm** [chromiecraft/chromiecraft#114]
Linked AC issue: https://github.com/azerothcore/azerothcore-wotlk/issues/11236

##### ISSUE: FACTION SIDE:

 ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

 Quest: [Verog the Dervish](https://classic.wowhead.com/quest=851/verog-the-dervish) 
NPC_Start: [Regthar Deathgate](https://classic.wowhead.com/npc=3389/regthar-deathgate) 

NPC: [Verog the Dervish](https://classic.wowhead.com/npc=3395/verog-the-dervish)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As you're killing centaur/Kolkar around the Stagnant Oasis, Verog may be summoned.
In red text this is announced in your chat log.
You kill him to get his head, [Verog's Head](https://classic.wowhead.com/item=5023/verogs-head), for the quest.
##### CURRENT BEHAVIOUR:

Verog spawned properly. I not only saw his red chat announcement, I physically actually visually saw him and left-clicked on him. He spawned in front of his command tent, though that's not the only place he can spawn. I had to fight a mob on the way to him, and in that time (green/low-leveled mob, to give an idea of how little time that was), he had despawned.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Not sure if it's necessary, but pick up the quest from Regthar Deathgate.
Step 2 Idk if a gm can force the mob to spawn? If not, a random number of Kolkar must be killed near the Stagnant Oasis.
Step 3 When Verog announces he has spawned, locate him, and see if he despawns.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
you can make spawn the Verog? Because I can't :/
Tested with two different NPCs.

**Comment by Helias** [comment]
I cannot reproduce it, I killed several centaurs, he spawned and I had the time to kill him and loot the head, like in this video 
https://www.youtube.com/watch?v=M0IMPG9H0oQ

**Comment by rpk0714** [comment]
Verog spawned on top of me (another player triggered the spawn). Not being an asshole I disengaged the fight to invite the person also doing the quest.
A couple seconds (10s - 15s) after resetting Verog he just despawned.

**Comment by rpk0714** [comment]
> Verog spawned on top of me (another player triggered the spawn). Not being an asshole I disengaged the fight to invite the person also doing the quest. A couple seconds (10s - 15s) after resetting Verog he just despawned.

We managed to get Verog to spawn a second time (quite lucky), but he despawned again after a couple seconds.

**Comment by acidmanifesto** [comment]
So looking up the database. We have 18 Kolkar Bloodcharger Entry 3397 spawned in the database linked to smart scripts. all of them, when on death will spawn Verog The Dervish Entry 3395 at one particular location only and not multiple. .go xyz -1209.65 -2738.38 102.646 is what the smart script shows. however. Upon killing Bloodchargers which i have done a .npc info on each one to confirm they are smartai linked, i am not getting their text on death and i am not seeing the Verog npc being spawned at all.  I am not certain if there has been a recent sai source handling change that would contribute to that issue happening now.  So at this moment i am seeing this as completely broken on my end.

**Comment by DavuKnight** [comment]
Quick update killed about 50 Blood Chargers. When I killed the third one he yelled as he died and Verog Yelled as well but then that was it. He didnt seem to spawn. After that he never Yelled pr spawned again no matter how many I killed.

**Comment by DavuKnight** [comment]
In the end if you have to kill 30 mobs on average to get him to spawn you could be a good distance from him and have several fights to get through to reach him. Its going to be a pain to finally get him to spawn only to be to far away to tag him in the 60 seconds you have to reach him Which I think is what this Bug really boils down to. 
By the time folks get him to spawn and reach the tent he's already gone.
