### ISSUE TITLE
[Spell] Autocast for The Imp's Fire Shield Spell Doesn't Work 

### ISSUE THREAD

**Issue by Philomathus** [chromiecraft/chromiecraft#1141]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Autocast for Fire Shield (https://wowgaming.altervista.org/aowow/?spell=2947) doesn't autocast the spell on the owner of the imp nor other party members within range.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When autocast is on for Fire Shield (https://wowgaming.altervista.org/aowow/?spell=2947) it should autocast the spell on the owner of the imp and all party members within range. 

##### SOURCE:

It has always worked like this. When you turn on autocast on Fire Shield, it should "autocast" Fire Shield on the owner and other party members within range. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be a warlock.
2. Summon an imp.
3. Turn on autocast for Fire Shield.

##### EXTRA NOTES:

https://user-images.githubusercontent.com/25198252/125089387-ed27f300-e100-11eb-9729-cb2c16f895e9.mp4

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Imp only casts fireshield on players within 30 yards that receive a melee attack. Which is the correct and intended behaviour as linked here: https://wowwiki-archive.fandom.com/wiki/Fire_Shield?oldid=2394971

**Comment by Philomathus** [comment]
I played TBC on Atlantiss Karazhan. The imp casts Fire Shield even when you weren't being stuck. Is this a wotlk thing?

**Comment by temperrr** [comment]
Nop. They probably had it working incorrectly. It always worked as such
