### ISSUE TITLE
Goblin Bomb Dispenser Bugged

### ISSUE THREAD

**Issue by Eccies** [chromiecraft/chromiecraft#1143]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enUS

##### FACTION

- [ ] Alliance

##### CONTENT PHASE:

- [ ] 40-49

##### CURRENT BEHAVIOUR:

Goblin Bomb Dispenser ( https://classic.wowhead.com/item=10587/goblin-bomb-dispenser ) does not work. It doesn't spawn a bomb nor anything else. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Goblin Bomb Dispenser should spawn a mobile bomb that rushes the enemy. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Craft Item
2. Equip Item
3. Use Item
4. Nothing happens

##### EXTRA NOTES:

Type here. https://classic.wowhead.com/item=10587/goblin-bomb-dispenser

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eccies** [comment]
I made sure to choose version enUS

**Comment by Stump876** [comment]
Thanks for the report. It's on the [AC bug list](https://github.com/azerothcore/azerothcore-wotlk/issues/6609) but not in CC. That was my mistake. But thanks for confirming! I'll link them.
