### ISSUE TITLE
Herb node clusters / indoor node

### ISSUE THREAD

**Issue by kuzaan** [chromiecraft/chromiecraft#1144]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Big amount of herb nodes clustered in small spaces. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nodes should be rarer and more spaced out across the map.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Area and coordinates below:

Alterac Mountains 41-17
![Alterac Mountains 41-17](https://user-images.githubusercontent.com/72312283/125144542-dbf1dd00-e126-11eb-8b55-00708b09339c.png)

Alterac Mountains 47-46
![Alterac Mountains 47-46 8](https://user-images.githubusercontent.com/72312283/125144544-dd230a00-e126-11eb-8d74-6f90d191ec30.png)

Alterac Mountains 48-63
![Alterac Mountains 48 6-63](https://user-images.githubusercontent.com/72312283/125144545-ddbba080-e126-11eb-8f98-fb9f6d5f2365.png)

Alterac Mountains 51-20
![Alterac Mountains 51-20](https://user-images.githubusercontent.com/72312283/125144546-de543700-e126-11eb-93e5-c2a8b5b60e42.png)

Alterac Mountains 54-45
![Alterac Mountains 54 7-45 3](https://user-images.githubusercontent.com/72312283/125144547-deeccd80-e126-11eb-8eed-fc8c4410d8b8.png)

Alterac Mountains 61-43
![Alterac Mountains 60 9-43](https://user-images.githubusercontent.com/72312283/125144548-df856400-e126-11eb-8ffb-e12346b23296.png)

Arathi Highlands 28-55
![Arathi Highlands 28-55 8](https://user-images.githubusercontent.com/72312283/125144554-e1e7be00-e126-11eb-8d6b-c303a30ede72.png)

Arathi Highlands 32-21
![Arathi Highlands 32 5-21 9](https://user-images.githubusercontent.com/72312283/125144558-e2805480-e126-11eb-896b-dc6c0ba132d3.png)

2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jamadaha** [comment]
Found the indoor node (GUID 3564 - ID 1622) on my local instance (AzerothCore 9b3993b).
![image](https://user-images.githubusercontent.com/53914190/125204643-8597b200-e27e-11eb-8b96-7b1daddf183b.png)

**Comment by jamadaha** [comment]
Tested on local server(AC 28a764641)
Got the exact same pattern for the nodes in Alterac Mountains.

The indoor node is reported in https://github.com/azerothcore/azerothcore-wotlk/issues/6312

As for the ones in Arathi highlands, I'm not certain that those are wrong.
They change pattern each time they spawn, so they should be in a pool. But it also allows close spawns:
![image](https://user-images.githubusercontent.com/53914190/129595112-9ce395e3-0a18-4eff-880e-11a02af81892.png)

**Comment by Tereneckla** [comment]
Problem is that herbs and mining nodes are individual spawns right now. There should be a pooling system so that when an area isn't mined herb for a long time you don't have all spawns up at the same time (which causes these clusters) 
Pool should have a maximum and a minimum amount of nodes spawned and force spawns new nodes if it depletes
