### ISSUE TITLE
Shadowfang Keep wrong mob chaning

### ISSUE THREAD

**Issue by Volkyte** [chromiecraft/chromiecraft#1146]
#### WHAT CLIENT DO YOU PLAY ON?
3.3.5

- [x] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION
alliance

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Mobs in baron rooma re wrongly chained to each other. The worgen Razorclaw the butcher is escorted by wolf that run around aimlessl after aggroing the boss (see screens)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

mobs should follow boss in aggro

##### STEPS TO REPRODUCE THE PROBLEM:

1. go shadowfang keep
2. go galley
3. aggro boss
4.

##### EXTRA NOTES:

https://imgur.com/dNJgzjY
https://imgur.com/undefined

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
Thank you for the report. The Worgen belongs to the Shadowfang Wolfguard, not to Razorclaw. I tested it multiple times, but couldn't aggro Baron from the room you are in. The Worgen behaved pretty normally and didn't run off.
