### ISSUE TITLE
shadowfang keep 6th room chain pull bug

### ISSUE THREAD

**Issue by Volkyte** [chromiecraft/chromiecraft#1147]
#### WHAT CLIENT DO YOU PLAY ON?

- [x] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION
alliance

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Mobs in 6th room (2nd rom after silverlane) are all chained in pull (ragetooth+lupine horrors). they are in 2nd floor and still aggro 1st floor los around 40 yards away (25ish party)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

aggro range should be a lot more shrinked

##### STEPS TO REPRODUCE THE PROBLEM:

1. go shadowfang keep
2. go to the room as per screenshot
3. pull lowest level pack of mobs tehn step in the first platform
4.

##### EXTRA NOTES:

https://imgur.com/aWYo6G1

shows the whole pack aggroed in lower platform

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
I tried this around 10 times, but couldn't chain pull them, as you explained. I only got aggro, when I walked close to them. Mobs on 2nd floor didn't aggro when I was downstairs and mobs from downstairs didn't aggro, when I was at the 2nd floor. Maybe their aggro range is slightly higher than I expected, but I'm not even sure about this.
