### ISSUE TITLE
Seal of Righteousness visual bug in spellbook

### ISSUE THREAD

**Issue by Volkyte** [chromiecraft/chromiecraft#1148]
#### WHAT CLIENT DO YOU PLAY ON?

- [x ] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

as per screenshot, with spell ranks deactivated, you see double seal of righteousness

##### EXPECTED BLIZZLIKE BEHAVIOUR:

only 1 per paladin! :D

##### STEPS TO REPRODUCE THE PROBLEM:

1. be a paladin
2. level to 6 where you stack more ap
3. 
4.

##### EXTRA NOTES:

https://imgur.com/GcdZ2sT

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I was getting ready to give the usual rundown on "enGB client bad, enUS client good" because of issues like this, but then checked on the enUS client and it's doing the exact same thing.

However, some searching shows this is a known issue, and a fix has been merged and is on the way - see https://github.com/azerothcore/azerothcore-wotlk/pull/6727 - so hopefully this should be corrected on CC very soon.
