### ISSUE TITLE
Various mobs in Tirisfal hitting in melee from several yards away

### ISSUE THREAD

**Issue by Cosmic-Cocoa** [chromiecraft/chromiecraft#115]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Mobs are hitting in melee from really far away (max distance frost bolt is 30 yards and they will melee hit me right after I engage with them).
NPC: [Rattlecage Soldier](https://classic.wowhead.com/npc=1520/rattlecage-soldier)
NPC: [Thurman Agamand](https://classic.wowhead.com/npc=1656/thurman-agamand)
NPC: [Nissa Agamand](https://classic.wowhead.com/npc=1655/nissa-agamand)
NPC: [Gregor Agamand](https://classic.wowhead.com/npc=1654/gregor-agamand)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs that rely on melee damage should not be able to hit a character until they are within melee range.

##### CURRENT BEHAVIOUR:

I noticed this while fighting Rattlecage Soldiers. When I open with a frostbolt on them, I enter combat and immediately get hit in melee twice despite being 30 yards away. You can see in the below screenshot my scrolling combat text from the default ui is "Entering Combat" and my log shows the -7 and -8 as melee swings even though the target is super far away.

![longest reach ever](https://user-images.githubusercontent.com/78349628/109456429-71b18900-7a1e-11eb-9c82-b912532fc66b.png)

I noticed similar behavior from Thurman Agamand, Gregor Agamand, and Nissa Agamand (who was hitting as I was kiting her within the house, so not quite from as far of a distance, but still too far).

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1. Go to Agamand Mills in Tirisfal as anything with a ranged attack. 
Step 2. Attack one of the named mobs above from max distance.
Step 3. See if your combat log shows you taking any damage from melee attacks.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Cosmic-Cocoa** [comment]
I noticed that the NPC [Captain Dargol](https://classic.wowhead.com/npc=1658/captain-dargol) also seemed to hit me from outside melee range and my combat log said he also used Thrash. Now I'm wondering if that's related. I wish I'd taken screenshots, but I didn't think to at the time.

**Comment by 55Honey** [comment]
Tested for [Thurman Agmand](https://classic.wowhead.com/npc=1656/thurman-agamand), confirmed.

**Comment by aithdruid** [comment]
This also happens with [Venture Co. Drudgers](https://classic.wowhead.com/npc=3284/venture-co-drudger) whenever they use their Thrash ability.

**Comment by Sathrenor** [comment]
Confirmed in Darkshore.

  [Blackwood Pathfinder](https://classic.wowhead.com/npc=2167/blackwood-pathfinder) can execute the next melee attack without any range restrictions (Or limited to spell range) after casting a spell.
 It can even proc [Nature's Gasp](https://classic.wowhead.com/spell=16689/natures-grasp#see-also-ability)

[Look at combat log](https://www.youtube.com/watch?v=deVcndbmuPA)
_As You can see Pathfinder managed to land a classified as "melee" attack despite not being in range._

As @Cosmic-Cocoa and @aithdruid noticed, it also refers to a [Thrash](https://classic.wowhead.com/spell=3391/thrash) skill

**Comment by 55Honey** [comment]
@Sathrenor can you please confirm here: https://github.com/azerothcore/azerothcore-wotlk/issues/4673

**Comment by Stifler82** [comment]
https://user-images.githubusercontent.com/1884642/110249900-7a4f1580-7f70-11eb-81cf-342f62541c78.mp4

**Comment by Sathrenor** [comment]
@55Honey Done, Thank You. ;)

**Comment by Stifler82** [comment]
I don't think that it's a bug..

**Comment by AbraKabastard** [comment]
Can confirm @Sathrenor 

```c++
void Spell::EffectAddExtraAttacks(SpellEffIndex effIndex)
{
    if (effectHandleMode != SPELL_EFFECT_HANDLE_HIT_TARGET)
        return;

    if (!unitTarget || !unitTarget->IsAlive() || !unitTarget->GetVictim())
        return;

    if (unitTarget->m_extraAttacks)
        return;

    unitTarget->m_extraAttacks = damage;

    ExecuteLogEffectExtraAttacks(effIndex, unitTarget->GetVictim(), damage);
}
```

**Comment by 55Honey** [comment]
I don't understand how it's not bug. Is Thrash supposed to be a ranged ability?

**Comment by Stifler82** [comment]
> I don't understand how it's not bug. Is Thrash supposed to be a ranged ability?

https://github.com/azerothcore/azerothcore-wotlk/issues/4673#issuecomment-793655365

**Comment by Stifler82** [comment]
@Cosmic-Cocoa

Fixed!
-
**Video Test:** [Various mobs in Tirisfal](https://youtu.be/mW6IqYpu02k)
