### ISSUE TITLE
[Desolace] Bodyguard for Hire escort quest fail every time

### ISSUE THREAD

**Issue by Mainbexel** [chromiecraft/chromiecraft#1150]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The escort get failed every time at the end. I was close to the npc, he survived and I tried several times.
Links for the quest: https://wotlk.evowow.com/?quest=5821 , https://classic.wowhead.com/quest=5821/bodyguard-for-hire

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Don't fail at the end... :D

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wait for the caravan in Desolace at 61, 38
2. After a while they will start. Follow them untill the first goblin (Cork Gizelton) stops and gives the quest at 67, 37
3. Do the escort, protect him and it will fail at the end.

##### EXTRA NOTES:

The kodos and the other goblin is buggy, they stop at some point before the quest start. Maybe that's the problem cuz Cork Gizelton is alone in this quest.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report - we've had no end of troubles with this particular quest. However, it is a known issue with a currently open ticket - see https://github.com/azerothcore/azerothcore-wotlk/issues/6593 - so will close this.
