### ISSUE TITLE
[Incorrect drop] Highland Razormaw

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#1151]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Highland Razormaw drops Dreamsinger Legguards.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

According to wowhead tbc it shouldn't drop it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Wetlands
2. Kill Highland Razormaw on repeat
3. Observe

##### EXTRA NOTES:

Dreamsinger Legguards: https://tbc.wowhead.com/item=13010/dreamsinger-legguards#dropped-by;0+3-10-9+1
Highland Razormaw: https://tbc.wowhead.com/npc=1018/highland-razormaw#drops;50

![WoWScrnShot_062021_124413](https://user-images.githubusercontent.com/84775498/125166399-bfdc5300-e19b-11eb-9880-2cb0ff611c46.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jamadaha** [comment]
First time verifying, so I hope I've done it correctly.
I cannot reproduce it dropping that specific item, but it does drop several others which are also not in the drop table.
![image](https://user-images.githubusercontent.com/53914190/125172523-8830d380-e1ba-11eb-95b6-be6c65e0b36a.png)
![image](https://user-images.githubusercontent.com/53914190/125172527-8e26b480-e1ba-11eb-8ea0-d075f45db201.png)

**Comment by Azcobu** [comment]
Thanks for the report @Avyxis17, and thanks to @jamadaha for verifying. Fortunately this should be an easy fix as the Dreamsinger Legguards are in an RLT that contains no other valid items listed on Wowhead for this NPC.

**Comment by vexima** [comment]
you can't rely on wowhead database when deciding on random world drop loot. like in this case, it reports only a single rare item in loot table, which means it dropped only once for someone with wowhead addon installed. it doesn't mean it can't drop other world drop rares in that level range, it just means it happen not to be reported by wowhead contributors. i hope whoever is responsible for AC loot tables understands this.

**Comment by Avyxis17** [comment]
And how would you recommend we tackle this issue then? Since we don't have any official loot tables from Blizzard, wowhead database is our best and only choice quite frankly.

**Comment by vexima** [comment]
i'd say it's a non-issue. random world drops should rely on appropriate mob level range.
