### ISSUE TITLE
[Incorrect Drop] Forsaken Bodyguard

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#1152]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Forsaken Bodyguard drops Gloves of Old.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

According to wowhead tbc it shouldn't drop it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Arathi Highlands
2. Kill Forsaken Bodyguard on repeat
3. Observe

##### EXTRA NOTES:

Gloves of Old: https://tbc.wowhead.com/item=9395/gloves-of-old#dropped-by;0+3-10-9+1
Forsaken Bodyguard: https://tbc.wowhead.com/npc=2721/forsaken-bodyguard#drops

![WoWScrnShot_062021_134158](https://user-images.githubusercontent.com/84775498/125166496-35e0ba00-e19c-11eb-9433-e4a850160018.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report, which is confirmed. Unfortunately this is not one of the easy-to-fix RLT issues. The Gloves of Old are in RLT 24053, but so are other valid items listed on Wowhead for this NPC like Viscous Hammer, Tigerstrike Mantle and Ravasaur Scale Boots. As a result, will close this as an instance of the broader problem and link it to the relevant issue: https://github.com/chromiecraft/chromiecraft/issues/907
