### ISSUE TITLE
Missing quest: The Disruption Ends

### ISSUE THREAD

**Issue by Eistorm** [chromiecraft/chromiecraft#116]
##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Quest: [The Disruption Ends](https://wotlk.evowow.com/?quest=872)
Quest: [Disrupt the Attacks](https://wotlk.evowow.com/?quest=871)
Quest: [Supplies for the Crossroads](https://wotlk.evowow.com/?quest=5041)
NPC_Start and NPC_End of all pertinent quests: [Thork](https://wotlk.evowow.com/?npc=3429)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After turning in the quest [Disrupt the Attacks](https://wotlk.evowow.com/?quest=871) to [Thork](https://wotlk.evowow.com/?npc=3429), he should offer the quests [The Disruption Ends](https://wotlk.evowow.com/?quest=872) and [Supplies for the Crossroads](https://wotlk.evowow.com/?quest=5041).

##### CURRENT BEHAVIOUR:

[Thork](https://wotlk.evowow.com/?npc=3429) offers the quest, [Supplies for the Crossroads](https://wotlk.evowow.com/?quest=5041), but the quest [The Disruption Ends](https://wotlk.evowow.com/?quest=872) is not currently available.
I don't know if this is a bug or something else. 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Complete the [Disrupt the Attacks](https://wotlk.evowow.com/?quest=871) quest
Step 2 See if [Thork](https://wotlk.evowow.com/?npc=3429) offers [The Disruption Ends](https://wotlk.evowow.com/?quest=872) quest

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
Confirmed. After handing in [Disrupt the Attacks](https://wotlk.evowow.com/?quest=871) [Thork](https://wotlk.evowow.com/?npc=3429) only offers [Supplies for the Crossroads](https://wotlk.evowow.com/?quest=5041) but not [The Disruption Ends](https://wotlk.evowow.com/?quest=872) which should unlock, too.

**Comment by illfated** [comment]
https://wow.gamepedia.com/The_Disruption_Ends#Notes :

### Notes

The Razormane Quilboars you need to kill are to the northeast of Crossroads. They will be in large numbers along the north and northeast side of the mountains east of Crossroads.
Kreenig Snarlsnout will be south southwest the Crossroads' Supply Crates northeast of the mountains east of Crossroads. There will be Razormane Mystics, Razormane Defenders, and some Razormane Hunters near this area, too. You will need one inventory space free to retrieve Kreenig Snarlsnout's Tusk from his corpse. This is a required item to complete the quest.

You may wish to complete this quest along with the ![image](https://user-images.githubusercontent.com/38162891/109565843-53fa2780-7ae3-11eb-8702-df647c7adda1.png) [[12] Supplies for the Crossroads](https://wow.gamepedia.com/Supplies_for_the_Crossroads) quest, as you will find the Crossroads' Supply Crates around the Razormane Defenders and the Razormane Geomancers.

**Comment by Eistorm** [comment]
> P. S.: I have the feeling that this has been wrong on many/all private servers I have played on.

I'm pretty certain you're right. I think the only reason I noticed this is because the last time I did it was on Classic.
So not a bug per se, nor even a missing quest, just a quest offered out of order.
Still, helps clean up AzerothCore for all future users.

**Comment by Helias** [comment]
fixed, it will be available in the next update
