### ISSUE TITLE
 [Improved Mind Blast] does not use the effect for healing reduce ( my bad i need shadowform for that buff ) can delete 

### ISSUE THREAD

**Issue by BasiliskEU** [chromiecraft/chromiecraft#1160]
#### WHAT CLIENT DO YOU PLAY ON?

- [x] enUS

##### FACTION

- [x] Horde

##### CONTENT PHASE:

- [x] 20-29
- [ ] soon 30-39

##### CURRENT BEHAVIOUR:

while I was in the battleground I noticed that when I cast Mind Blast the effect of talent https://wowgaming.altervista.org/aowow/?spell=15316 didnt work. No healing reduce.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I cant found video with that talent but if u cast mind blast to target and if u have 5/5 on this talent should the main target to get healing reduce like debuff :)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just that bug nothing more !
2. 
3. 
4.

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?spell=15316 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Sathrenor** [comment]
I think You can close Your own issue next to the "comment" button. Just FYI, but correct me if I am wrong. ^^

**Comment by Azcobu** [comment]
Closing as per above. :)
