### ISSUE TITLE
[Stranglethorn Vale] Several Ironjaw Basilisks missing movement.

### ISSUE THREAD

**Issue by Ziedge** [chromiecraft/chromiecraft#1166]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [X] other frFR

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Some Ironjaw Basilisk  is standing still without any movement.
GUID: 13309
GUID: 2174
GUID: 2185

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Ironjaw Basilisk should roam a bit and not be static.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Port to GUID: 2174, GUID: 13309, GUID: 2185
2. You can see the mob standing still with no movement.

https://user-images.githubusercontent.com/82708448/125193911-39814900-e24f-11eb-9a94-94b2dc781fe9.mp4

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jamadaha** [comment]
The specified GUID does not match any Ironjaw Basilisk on my local instance. (AzerothCore 9b3993b) I did, however, find the Basilisk shown in the video (GUID 756) and it does indeed not move in the five minutes that I looked at it. (Very interesting stuff I must say)
![image](https://user-images.githubusercontent.com/53914190/125203797-5c752280-e27a-11eb-8dfb-7a3d12e7196a.png)

**Comment by Ziedge** [comment]
Strange because I used .npc info on every one I saw bugged !
Did you find the 2 other ?

**Comment by jamadaha** [comment]
I'm pretty new to this, so it could be a mistake on my side in terms of GUID.
No I didn't find others.

**Comment by jamadaha** [comment]
The DB shows that it is the Basilisk with GUIDs 373, 612, 756, 981 & 1062. Although, I don't think 612 is supposed to move.

**Comment by Azcobu** [comment]
Thanks for the report @Ziedge , and for checking it @jamadaha.

The problem with the GUIDs was that you were quoting the number labelled as "current GUID", whereas we're after the "DB GUID". No harm done though, identifying the species type is enough to find them with the right DB query, so the report is confirmed, thanks for that.

**Comment by Ziedge** [comment]
Thanks for the information, I'll use the DB GUID on my next report !

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/6903
