### ISSUE TITLE
Blade Flurry

### ISSUE THREAD

**Issue by serecya** [chromiecraft/chromiecraft#1167]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Blade Flurrys(Rogue Talent https://wotlk-twinhead.twinstar.cz/?spell=13877)  behavior is not correct, it calculates the Armor reduction of the second Target two times. for Example if i hit 2 identical monsters, the main target gets hit for 500 while the second target gets hit for 250, getting reduced by armor again. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

the second Target should receive the same damage as the main target if their armor values are the same, not getting reduced again. here is a old Youtube Video from Wotlk of a Rogue hitting 2 Targets with Bladeflurry while both receive around the same dmg https://www.youtube.com/watch?v=ats4GrMUgVc.

##### SOURCE:

https://www.youtube.com/watch?v=ats4GrMUgVc
##### STEPS TO REPRODUCE THE PROBLEM:

1.  get on a atleast level 30 Rogue with the Talent Blade Flurry specced
2.  pull 2 mobs with near the same Armor Values and hit them while Blade Flurry is activated
3.  notice the second target gets significantly less damage than the first
4.

##### EXTRA NOTES:

multiple more Videos for evidence! also its the way it works in Classic WoW at the moment, while the Spell didnt got changed in Wotlk.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jamadaha** [comment]
Followed the steps on my local instance (AzerothCore 9b3993b). There does seem to be less damage done to the second target.

![image](https://user-images.githubusercontent.com/53914190/125204262-ac54e900-e27c-11eb-811f-381ec986a35f.png)
![image](https://user-images.githubusercontent.com/53914190/125204269-b5de5100-e27c-11eb-992b-aae812ebe41c.png)
![image](https://user-images.githubusercontent.com/53914190/125204313-df977800-e27c-11eb-878d-c4d455a913b9.png)
![image](https://user-images.githubusercontent.com/53914190/125204317-e625ef80-e27c-11eb-9e42-d2a4441708ff.png)
