### ISSUE TITLE
[Statistics] Average gold earned per day equals Total gold aquired.

### ISSUE THREAD

**Issue by LundmarkJ** [chromiecraft/chromiecraft#1168]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

In the statistics tab, the average gold earned per day does not scale with time.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Average gold earned per day should be total gold aquired divided by the number of days since your character was created.

##### SOURCE:

![image](https://user-images.githubusercontent.com/82000605/125200234-6c850600-e26a-11eb-8159-07d7f5cb2973.png)
Picture from Retail

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have a character older than 1 day.
2. View statistics -> Wealth.

##### EXTRA NOTES:

![image](https://user-images.githubusercontent.com/82000605/125200258-93433c80-e26a-11eb-9018-0f5438bda305.png)
Picture from Chromiecraft

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jamadaha** [comment]
I concur.
![image](https://user-images.githubusercontent.com/53914190/125202542-5419e900-e274-11eb-8d28-e78926a73e94.png)

**Comment by sudlud** [comment]
Can be closed, fixed in azerothcore/azerothcore-wotlk#6901

**Comment by LundmarkJ** [comment]
Closed due to Merge https://github.com/azerothcore/azerothcore-wotlk/pull/17263#issue-1898411467
