### ISSUE TITLE
Chance on hit: Grants an extra attack on your next Swing. aswell as the Talent Hack & Slash

### ISSUE THREAD

**Issue by serecya** [chromiecraft/chromiecraft#1170]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Chance on hit: Grants an extra attack on your next Swing(from Weapon in your Maind). aswell as Hack & Slash are also capable of using your Offhand to do the Procc while all the extra attack Proccs should be done by your Mainhand.
I would be fine with the Weapon proccs, but the Talent is really underperforming and needs a fix!

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Extra Swings(in your Mainhand) from any Source being an Item or Talent should always be performed by your Mainhand.
I cant find any clear evidence on the Weaponprocc,(really hard to find) but i cant imagine that your Thrash Blade Procc should be used by your offhand. Atleast it wasnt like that on Classic WoW  but i might be wrong. but the point for Hack and Slash still stands.
##### SOURCE:

Correct Behavior:
https://wowwiki-archive.fandom.com/wiki/Hack_and_Slash
there it says that the extra procc should be done by your Mainhand

here are Numbers showing that the offhand is being used:
![WoWScrnShot_071121_174428](https://user-images.githubusercontent.com/87269487/125201497-bc1a0080-e26f-11eb-9887-befa33e60d7d.jpg) 
With Thrash Blade in Mainhand not being able to hit for as low as 45 on a Target Dummy
here also Numbers for Thrash Blade Procc aswell as Flurry Axe Procc:
![WoWScrnShot_071121_174433](https://user-images.githubusercontent.com/87269487/125201529-ebc90880-e26f-11eb-81c9-5e31323794ea.jpg)
![WoWScrnShot_071121_174435](https://user-images.githubusercontent.com/87269487/125201537-ef5c8f80-e26f-11eb-92df-1474390ef5f9.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  start auto attacking Targetdummy
2.  keep document of damage numbers
3. 
4.

##### EXTRA NOTES:

all tests were done with Thrash Blade in Mainhand and Flurry Axe in Offhand while having 5/5 points in Hack and Slash.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Tested on local AC. The extra attack proc is always done with main hand, the talent 1 thrash one. If you can show your combat log entries from this, then I can confirm possibly that its a chromiecraft specific issue.
![Screenshot from 2021-07-14 09-19-25](https://user-images.githubusercontent.com/20357406/125580002-a6237679-093f-41aa-b8ca-2d8f207977ea.png)

as you can see I get 2 knife hits in a row from hack and slash.

**Comment by serecya** [comment]
Gonna do some further testing today or tomorrow. I will document combat logs aswell!

**Comment by syssneck** [comment]
@serecya Hey, did you do some further tests?

**Comment by serecya** [comment]
No but i can today!
________________________________
Von: syssneck ***@***.***>
Gesendet: Montag, 26. Juli 2021 11:42
An: chromiecraft/chromiecraft ***@***.***>
Cc: serecya ***@***.***>; Mention ***@***.***>
Betreff: Re: [chromiecraft/chromiecraft] Chance on hit: Grants an extra attack on your next Swing. aswell as the Talent Hack & Slash (#1170)


@serecya<https://github.com/serecya> Hey, did you do some further tests?

**Comment by temperrr** [comment]
Closed. If you have more evidence feel free to make a new ticket.
