### ISSUE TITLE
Mob Garek doesn't give me a quest.

### ISSUE THREAD

**Issue by Lexine1** [chromiecraft/chromiecraft#1172]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So, there's this questgiver called Garek in Badlands that is supposed to give a quest without any previous requirements, at level 40. I'm level 46 and it just doesn't have the exclamation mark on top of his head. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mob should just be able to give you the quest.
##### STEPS TO REPRODUCE THE PROBLEM:

1.  Idk just go and try to grab the quest at level 40? 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Sathrenor** [comment]
AoWoW DB says it requires quest [Mirages](https://wowgaming.altervista.org/aowow/?quest=718). Could You please check if You have those 2 quests done?

_[Tremors of the Earth](https://wowgaming.altervista.org/aowow/?quest=732)_

**Comment by Lexine1** [comment]
Oh I didn't know that. I don't have that quest yet, thanks.

**Comment by jamadaha** [comment]
Tested on local server (AzerothCore 9b3993b).
Yea, think you might just be missing the prior quest. On my local server, I can take it just fine.
![image](https://user-images.githubusercontent.com/53914190/125212561-8b0cf080-e2ae-11eb-8794-398d9a920aa2.png)

**Comment by Sathrenor** [comment]
When You think something is missing, please first check https://wowgaming.altervista.org/aowow/
It has the most relevant database when it comes to Chromiecraft.

Issue can be closed. ^^
