### ISSUE TITLE
Account Log Problem

### ISSUE THREAD

**Issue by Jhay82** [chromiecraft/chromiecraft#1173]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ x] Horde

##### CONTENT PHASE:

- [ x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I have 3 accounts, using them in one computer, cleared cache and using chromiecraft website game client.
account 2 & 3 goes after i type password. Handshaking > Success > Character Selection Screen
account 1 goes Handshaking > Success > Disconnected! sometimes in like 2-3 tries but generally after around 20 tries sometimes even more it usccesfully logs int ocharacter selection.
Whats wrong with the account? 

Account details i guess i need to give it to you with something like a private message or something?

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Everything should work fine.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Your best option is probably to go to the #support channel on our Discord server. You can access Discord directly from the CC home page at https://www.chromiecraft.com (button in bottom right) Someone there should hopefully be able to help you, and you can give them account details privately if needed, which you can't do here.
