### ISSUE TITLE
Lv 40 armor type is falsely shown as equippable and drops from RDF satchel

### ISSUE THREAD

**Issue by JanEbbing** [chromiecraft/chromiecraft#1176]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

This happened on my hunter, I assume its the same for shamans with mail and Paladins/warriors with plate. (It might also be the case for shields)
Items with "Mail" armor type are not equippable by hunters, so the "Mail" should be in red font. It currently isnt equippable, but is displayed as equippable (white font).
In addition, hunters get mail armor from Satchel of Helpful goods (see screenshot).
Patch Notes 3.3.0 say it is a "level-appropriate reward" so they should get leather.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Hunters <lv 40 should get leather armor.
Mail/Plate should be displayed in red font to indicate you cannot yet wear it.

##### SOURCE:

First source I could find on mail being lv40+
https://vanilla-wow-archive.fandom.com/wiki/Mail_Armor

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a hunter at lv 35
2. Mail armor will be shown as equippable
3. Complete RDF to get satchel of helpful goods
4. Open satchel of helpful goods, receive Mail

##### EXTRA NOTES:

![WoWScrnShot_071221_190520](https://user-images.githubusercontent.com/5873110/125337210-9f9cc780-e346-11eb-8635-c6318c770ced.jpg)

This might be linked to https://github.com/chromiecraft/chromiecraft/issues/248

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jamadaha** [comment]
This is really two issues:
1. RDF satchel drop
This is, as you mentioned, linked to issue #248.
2. Mail armour for hunter < lvl 40
As for this, it would seem that you are using add-ons that change how it looks. That might be what causes it, so for more clear information it could be an idea to turn those off.

I can at least not reproduce it on my local server (AC 920825b75):

![image](https://user-images.githubusercontent.com/53914190/125338969-23f44800-e351-11eb-87b3-f7ea2414b9f8.png)
