### ISSUE TITLE
NPC: ''Dead-tooth Jack''

### ISSUE THREAD

**Issue by OxyImmortal** [chromiecraft/chromiecraft#1184]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:>

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Dead-Tooth Jack, NPC id 6093, for the quest Dead-Tooth Jack ID 1667, hits about 15-20 times per swing, oneshotting or two shotting level appropriate players. Screenshot below of combat log from 1 swing.
https://imgur.com/a/wVMh3us

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Well, he should swing once and hit once :p

https://www.youtube.com/watch?v=R6dS94nVcQ8&ab_channel=WarcraftStory 
This video is from wow classic, so not 3.3.5 but the quest and NPC is the same in both versions.

##### STEPS TO REPRODUCE THE PROBLEM:
Let Dead-tooth Jack attack you I guess.
https://imgur.com/a/naLKe0N
This image is .npc info of Dead-tooth Jack ingame.
-->

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
It's Thrash.
![image](https://user-images.githubusercontent.com/26512802/125525986-3042f98a-cdeb-40d9-8691-78fe6b87a6d4.png)

**Comment by Shineslippers** [comment]
It looks like every extra attack can proc more extra attacks. Sounds wrong. Felpaw in Felwood do the same.

**Comment by syssneck** [comment]
I can confirm this bug on my local AC (114d55d):
![grafik](https://user-images.githubusercontent.com/68868567/125609923-bea1c6a7-bc3c-4e17-8e69-29436490725b.png)

There seems to be something wrong with the Thrash ability, but should he even have that ability?

**Comment by Eldarix** [comment]
There doesn't seem to be any clear information in the typical sources, no one even mentions anything about multiplied attacks in the comments from 2005 :D :D 

https://wowpedia.fandom.com/wiki/Dead-Tooth_Jack

https://www.wowhead.com/npc=6093/dead-tooth-jack

**Comment by syssneck** [comment]
I also can't find Dead-tooth Jack, when I search for whom has the Thrash ability: [https://tbc.wowhead.com/spell=3391/thrash](https://tbc.wowhead.com/spell=3391/thrash)
The only mob that is supposed to have Thrash in Elwynn Forest is Riverpaw Outrunner. 
I think we have enough information to say, that he shouldn't have the ability to start with. 

@Eldarix: I saw you already opened this one here: [azerothcore-wotlk/issues/6118](https://github.com/azerothcore/azerothcore-wotlk/issues/6118), so I don't think I should open a new issue on azerothcore for this, what do you think? I also think the issue is not necessarily "low priority", as it can be impossible to kill the mob for the quest if you try it alone.
