### ISSUE TITLE
Thrash blade has a hidden 1% extra crit chance

### ISSUE THREAD

**Issue by Lexine1** [chromiecraft/chromiecraft#1186]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So, I got my Gryphon Rider's Stormhammer from the Hinterlands questchain and enchanted it with 15 agility because I wanted to try it instead of Thrash Blade. 
With TB on I have 16.86% crit chance. With GRS, I have 15.94% crit chance. Both weapons have the 15 agility enchant on them. I'm a subtlety rogue with no talents that affect weapon usage. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Well TB isn't supposed to have any stats on it so this is rather weird. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. I don't know, just equip both weapons and try???
2. 
3. 
4.

##### EXTRA NOTES:

I have the screenshots if whoever reads this wants them. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by vexima** [comment]
are both of your weapon skills maxed out?

**Comment by Lexine1** [comment]
My 1h mace skill is like 2 points lower. 243/245. Swords are 245/245.

**Comment by syssneck** [comment]
Hi, I can't confirm it on my local AC (114d55d). I have the same crit chance with both weapons (5.36 % cc):
![unknown_2021 07 14-11 58](https://user-images.githubusercontent.com/68868567/125603340-88784d55-666d-4eb9-bf00-65bf09d03c32.png)
![unknown_2021 07 14-11 57](https://user-images.githubusercontent.com/68868567/125603356-8cc89cb5-cc27-440a-8d2c-68666457e7e1.png)
I then tried it with the +15 agility enchant, but the result was the same for both weapons (6.3 % cc):
![unknown_2021 07 14-12 09](https://user-images.githubusercontent.com/68868567/125604815-e5cc8a5d-b150-4c8d-b1c8-f756d421558f.png)
![unknown_2021 07 14-12 09_3](https://user-images.githubusercontent.com/68868567/125604824-09adc1b0-5204-491d-848c-430d50b40785.png)
