### ISSUE TITLE
[Loot Table] Design: Ruby Serpent (and possibly other patterns/designs/...)

### ISSUE THREAD

**Issue by Vekt** [chromiecraft/chromiecraft#1191]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

The Design: Ruby Serpent item (https://wowgaming.altervista.org/aowow/?item=21949) is dropping only from 11 mobs, most of them being in the DK starting zone.

### Expected Blizzlike Behaviour

It's supposed to be a world drop, as it is for other patterns like https://wowgaming.altervista.org/aowow/?item=14467.
In wowpedia, it says this item is a random world drop from level 40-60 mobs. You can also check the comments from tbc wowhead, saying it dropped from multiple random mobs.

### Source

https://wowpedia.fandom.com/wiki/Design:_Ruby_Serpent
https://fr.tbc.wowhead.com/item=21949/dessin-serpent-de-rubis#english-comments

### Steps to reproduce the problem

1. Check the database (I also checked directly the database using Keira3, it seems the loot table looks the same)

**Comment by jamadaha** [comment]
Tested on local server(AzerothCore 920825b75)
There does indeed seem to be [11 creatures](https://user-images.githubusercontent.com/53914190/125635995-d080fc49-506e-4805-a846-8aea2f54da71.png) which can drop it:
Black Dragonspawn - ID 7040
Blazing Fireguard - ID 8910
Mangled Cadaver - ID 10382
Scarlet Commander - ID 28936
Scarlet Courier - ID 29076
Scarlet Crusader - ID 28940
Scarlet Ghost ID - 28846
Scarlet Infantryman - ID 28609
Scarlet Medic - ID 28608
