### ISSUE TITLE
Lil Timmy does not vendor anything

### ISSUE THREAD

**Issue by iraizo** [chromiecraft/chromiecraft#1194]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

![image](https://user-images.githubusercontent.com/35413558/125651769-b6aa6020-815c-43a2-be0e-7b802acdd88e.png)

No vendor items

### Expected Blizzlike Behaviour

It should sell https://wotlk-twinhead.twinstar.cz/?item=8489 based on https://wotlk-twinhead.twinstar.cz/?npc=8666

### Source

https://wotlk-twinhead.twinstar.cz/?npc=8666

### Steps to reproduce the problem

1. teleport to 8666
2. right click lil timmy
3. no items are being sold

**Comment by gurveleg** [comment]
He sells it, but its just sold out. It has only 1 stock of the white kitten, so when someone buys it you then have to wait for it to respawn in the inventory. Its showing empty vendor window while waiting for restock.

**Comment by temperrr** [comment]
He sells items. you were just too late to catch him and somebody else bought it before you!

**Comment by iraizo** [comment]
Ah my bad, i dont know the mechanics of him!
