### ISSUE TITLE
[Tanaris] Two mobs missing movement in the same small area.

### ISSUE THREAD

**Issue by Ziedge** [chromiecraft/chromiecraft#1196]
### What client do you play on?

frFR

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Starving Blisterpaw (DB GUID: 22418) and Scorpid Tail Lasher (DB GUID: 22190) standing still without any movement.

### Expected Blizzlike Behaviour

They both should roam a little.

### Steps to reproduce the problem

1. Port to DB GUID: 22418 & DB GUID: 22190
2. Observe no movement.

https://user-images.githubusercontent.com/82708448/125666909-f29f1334-184f-497d-add5-ce715ab9f5a4.mp4

https://user-images.githubusercontent.com/82708448/125667846-cecc9e62-ca7c-4276-92bd-2638a769161f.mp4

**Comment by jamadaha** [comment]
Tested on my local server (AC 920825b75)
The DB shows both of them having wandering. They also move in my server.
![image](https://user-images.githubusercontent.com/53914190/125687305-4ce4fa84-34a5-432d-a134-fcaf835c08fb.png)
![image](https://user-images.githubusercontent.com/53914190/125687310-bfd8c519-b274-4fac-8234-e5598782ed38.png)

![image](https://user-images.githubusercontent.com/53914190/125687215-99a15ddd-82bf-466f-a1ba-a3903576a573.png)
![image](https://user-images.githubusercontent.com/53914190/125687231-c849cca3-5589-4ed8-8f3e-6206d01ebd06.png)

This could however be related to https://github.com/chromiecraft/chromiecraft/issues/1182, where it might that it's stuck in a specific place?

**Comment by Ziedge** [comment]
They go back to their spot and stay stuck again even after pulling/aggro and vanishing on my side !

**Comment by jamadaha** [comment]
Seems pretty standard on my side.
https://user-images.githubusercontent.com/53914190/125690086-3bdebb12-43d0-43af-9e64-8d4f890ac828.mp4

Maybe someone else can confirm it

**Comment by Ziedge** [comment]
I came back to the spot ingame, they do move now, I dont understand ;,,,;

**Comment by iraizo** [comment]
Also seems to wander on my local AC server, can this be closed?

<img src="https://i.imgur.com/dmJdhLI.jpg">

**Comment by Ziedge** [comment]
Yep, sorry for that, it seems that it was a temp bug...
