### ISSUE TITLE
[Tanaris] A few Dunemaul npc are missing movements.

### ISSUE THREAD

**Issue by Ziedge** [chromiecraft/chromiecraft#1198]
### What client do you play on?

frFR

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

A few Dunemaul npcs are standing still without any movements.

for exemple : 

- DB GUID: 23184
- DB GUID: 23183

### Expected Blizzlike Behaviour

Mobs should be at least walking around a bit and not stick a straight position.

### Steps to reproduce the problem

1. Port to DB GUID: 23184 or DB GUID: 23183
2. Observe no movement from the mob.

https://user-images.githubusercontent.com/82708448/125687763-329f45b9-568f-4639-93cf-83897254e8a9.mp4

**Comment by jamadaha** [comment]
Tested on local server(AC 920825b75)
In game - Viewed for 4 min, moved not an inch:
![image](https://user-images.githubusercontent.com/53914190/125704570-82730774-d776-4bc6-982d-9998b7851967.png)

In DB:
The two Dunemaul Brutes both have MovementType 0 and no wander distance.
