### ISSUE TITLE
[Maraudon] Double Mining Vein Spawn

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1199]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Truseilver Vein GUID 32922 and Mithril Vein GUID 63965 are spawned in same spot.
![maraudon](https://user-images.githubusercontent.com/80769357/125695631-5028a0ed-0948-4839-8a27-3ede447cd8bf.jpg)

### Expected Blizzlike Behaviour

Mining nodes should not spawn in same spot.

### Steps to reproduce the problem

1. Teleport to GUID 32922 or 63965
2. observe double spawn

**Comment by jamadaha** [comment]
Tested on local server(AC 920825b75)
In game:
![image](https://user-images.githubusercontent.com/53914190/125703447-46e22080-1e16-456d-a51e-1aafc05d2852.png)

In DB:
The 2 objects have the same position and neither is in a pool.
