### ISSUE TITLE
Quest item in the bank will keep dropping after having the objective completed

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1200]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Mobs will keep dropping the quest item you no longer need if you already have some of them (or all of them) stored in your bank.
![image](https://user-images.githubusercontent.com/22718174/125705136-8cf09309-38be-498a-83b4-955a3d2650e7.png)

### Expected Blizzlike Behaviour

The quest item should stop dropping for you after you hit the quest requirements for the said items.

### Steps to reproduce the problem

I have experienced it with Troll Temper.
1. Get the quest Troll Temper (id 3042).
2. Get all 20 Troll Temper (id 9523).
3. Put them in your bank.
4. Run Zul'Farrak once again and take 20 more Troll Temper. You have 40 of them now.

I have also tried with Divino-matic Rod. It did drop but I couldn't pick it up again because it was Unique and I had it stored in my bank, it shouldn't have proposed me to loot it.

I was running Zul'Farrak with the dungeon finder so nobody could have changed the loot rule.

### Extra Notes

I can grief other people of my group by stealing their quest items that I no longer need extra of them because they are in my bank!

Edit: added quest and item id for Troll Temper.

**Comment by Eldarix** [comment]
May be related to this issue:

https://github.com/azerothcore/azerothcore-wotlk/issues/6442

**Comment by Synful-Syn** [comment]
My bad, I'm closing it. It's a duplicate of https://github.com/chromiecraft/chromiecraft/issues/902
