### ISSUE TITLE
[Arathi Highlands] Feeboz running away up in the air

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1203]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

After killing Fozruk, I engaged his guards, who were now running away and engaging me in intervals. While Znort and Sleeby were doing so on the ground, Feeboz GUID 14517 (https://wowgaming.altervista.org/aowow/?npc=4063) decided it was time to fly away, but he kept casting fireballs at me. It might have been bacause I killed fozruk on a hill and he just start running away in straight line thus getting up in the air.

![qq](https://user-images.githubusercontent.com/80769357/125738070-dcad11d5-1267-4364-b28d-b58a4dc042db.jpg)
![aa](https://user-images.githubusercontent.com/80769357/125738073-d9e4094c-b43b-4e04-bacc-9729e9a8435c.jpg)

### Expected Blizzlike Behaviour

Mobs should not run away up into the air.

### Steps to reproduce the problem

1. Teleport to GUID 14517
2. Engage and Kill Fozruk first, preferably when he is on a small hill
3.  Observe what guards do

**Comment by Stump876** [comment]
Thanks for the report. Unfortunately I can't duplicate this. He walks over hills normally for me. I tried on several mounds, Even ran him back and forth over them. No luck.

![image](https://user-images.githubusercontent.com/68164076/131265372-1543ad83-ea8e-459b-911f-2945a0743cde.png)
