### ISSUE TITLE
[Felwood] Mongress (rare) missing movement

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1204]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Mongress GUID 51895 (https://wowgaming.altervista.org/aowow/?npc=14344) is stationary in its spawn location.

### Expected Blizzlike Behaviour

Mongress should wander around its spawn.

### Source

https://classic.wowhead.com/npc=14344/mongress#comments

https://www.youtube.com/watch?v=2_zZ8gzgWQw
https://youtu.be/iSqn4QEOhHo?t=6

### Steps to reproduce the problem

1. Teleport to GUID 51895
2. Observe no movement

**Comment by iraizo** [comment]
Tested on local AC server, Behaviour is not set.

<img src="https://i.imgur.com/2sjlxfv.jpg">
