### ISSUE TITLE
[Crossfaction] [Spell] Resurrection doesn't work on enemy faction corpses

### ISSUE THREAD

**Issue by Foodlenz** [chromiecraft/chromiecraft#1205]
Me: Alliance Priest
Them: Horde
Where: RDF -> BFD

We wiped, I had a soul stone. I used that to get back up and rez people. I could rez anyone that hadn't released no problem (guessing since i could target them).
The two that had released I couldn't. Usually you'd be able to find their corpse and manually click the res spell and target the corpse in the world, but it didn't work, the targeting cursor doesn't light up showing them as a valid target when hovering over the corpse.

**Comment by iraizo** [comment]
Please follow the bug report template.

**Comment by Foodlenz** [comment]
What template?

**Comment by iraizo** [comment]
[This one](https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&template=bug_report.yml)

**Comment by Foodlenz** [comment]
Cheers, dunno why the create new ticket link on this page (https://github.com/chromiecraft/chromiecraft#readme) didn't link to that.

**Comment by iraizo** [comment]
Oh yeah i will report this, thank you for informing me!
