### ISSUE TITLE
[Cross Faction] [Spell] Resurrection of released players on opposing faction.

### ISSUE THREAD

**Issue by Foodlenz** [chromiecraft/chromiecraft#1206]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

While in a cross faction random dungeon finder group, resurrecting a player **who has released** on the **opposing** faction doesn't work.

Likely an issue with how the corpse is flagged, but while hovering over an opposing faction's corpse with the resurrection spell targeting cursor, it doesn't see the corpse as a valid target.

Resurrecting opposing faction who **haven't** released works fine. 

### Expected Blizzlike Behaviour

Can only compare it to same faction blizzlike/current behavior, where you should be able to find the body of the dead player and manually target it in the game world to rez them.

### Steps to reproduce the problem

1. Create a cross faction group with a rez'er the opposite faction of the others.
2. Kill the opposing faction players and get them to release.
3. Try rez them.

**Comment by Eldarix** [comment]
I have tried to reproduce it without success (AC HASH/COMMIT: 05bbf4a)

**Comment by j-hdt** [comment]
can confirm the issue for chromiecraft - present since atleast April - likely older.
In an rdf, you cannot resurrect players of the opposite faction if they already released.
