### ISSUE TITLE
Venomhide Eggs Quest not bound to prerequisite Quest

### ISSUE THREAD

**Issue by Falcio** [chromiecraft/chromiecraft#1208]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When you speak to Mor'vek NPC ( https://wowgaming.altervista.org/aowow/?npc=11701 ) he has the following quest available:
- Toxic Tolerance (https://wowgaming.altervista.org/aowow/?quest=13850) is the 1st quest of then Chain
- Venomhide Eggs (https://wowgaming.altervista.org/aowow/?quest=13887) is the 2nd quest of then Chain

If you accept one of them the other one is not listed as available anymore.
When you complete Venomhide Eggs quest the 3rd quest of the chain (https://wowgaming.altervista.org/aowow/?quest=13906 - They Grow up so Fast) become available.

### Expected Blizzlike Behaviour

The only quest available from Mor'vek NPC should be "toxic tolerance". After its completion the second quest "Venomhide eggs" should become available.
Wowhead comments describe this behavior: https://www.wowhead.com/npc=11701/morvek#comments

### Steps to reproduce the problem

Teleport at coords 71.2, 73.7 to Mor'vek (should be guid 11701) in Un'Goro and speak with him to see the available quests.
Both the 1st and the 2nd quests of the chain are available.

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=11701 ( Mor'vek)
https://wowgaming.altervista.org/aowow/?quest=13850 ( Toxic Tolerance - 1st quest)
https://wowgaming.altervista.org/aowow/?quest=13887 ( Venomhide Eggs - 2nd quest)

AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@7c21d56

OPERATING SYSTEM:

Ubuntu 20.04

MODULES:

    mod-ah-bot
    mod-cfbg
    mod-chromie-xp
    mod-desertion-warnings
    mod-duel-reset
    mod-eluna-lua-engine
    mod-ip-tracker
    mod-low-level-arena
    mod-multi-client-check
    mod-pvp-titles
    mod-pvpstats-announcer
    mod-queue-list-cache
    mod-server-auto-shutdown
    lua-CarbonCopy
    lua-LevelUpReward
    lua-send-and-bind
    lua-Zonecheck

OTHER CUSTOMIZATIONS:

None

SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Thanks for the report pal ;)

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/6968
