### ISSUE TITLE
Undercity Paladin Trainer uses Alliance language text instead of Horde when Horde Paladins speak to her

### ISSUE THREAD

**Issue by Tachtzehn** [chromiecraft/chromiecraft#1212]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Champion Cyssa Dawnrose's main page text is in an Alliance language (Common I think) when viewed by Paladins, making her unable to be understood.
![WoWScrnShot_071521_095350](https://user-images.githubusercontent.com/83389835/125811392-7012ac79-796c-4e59-a2b8-56a4e06a2b88.jpg)
Note DBGUID in screenshot chat

### Expected Blizzlike Behaviour

She is a Horde character, so she should speak Orcish, making the text appear in English (or primary game language) to players.

### Source

Cyssa's text when non-paladins speak to her, as well as Horde paladin trainers in other cities.

### Steps to reproduce the problem

1. Be a Blood-Elf Paladin
2. R-click to talk to the NPC
3. Look at the text

**Comment by Eldarix** [comment]
Thanks for the report pal ;)
