### ISSUE TITLE
[NPC] Thauris Balgarr, doesn't use his "Shoot" ability

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1218]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

The npc Thauris Balgarr doesn't use his "Shoot" ability.
![WoWScrnShot_071521_170845](https://user-images.githubusercontent.com/22718174/125858328-a1e22a20-a102-436d-bd38-88fd92b1c052.jpg)

### Expected Blizzlike Behaviour

He should use his shooting ability.

### Steps to reproduce the problem

Attack in range!

### Extra Notes

NPC: https://wowgaming.altervista.org/aowow/?npc=8978
His "Shoot" ability: https://wowgaming.altervista.org/aowow/?spell=6660

**Comment by Gultask** [comment]
Closed via above
