### ISSUE TITLE
[Talents and Spells] Shadow Priest - Devouring Plague does not proc Shadow Weaving

### ISSUE THREAD

**Issue by hehepwnd39** [chromiecraft/chromiecraft#1221]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

So Shadow weaving 3/3 procs 100% on shadow damage, for example Shadow Word Pain procs 1 stack of shadow weaving when i use the spell, but devouring plague which is a disease and shadow damage, does not proc shadow weaving talent.

### Expected Blizzlike Behaviour

Devouring Plague should proc 1 stack of shadow weaving , sadly i do not think i have any proof for this, but i do think it is self explanatory

### Steps to reproduce the problem

Try to use a shadow priest with 3/3 shadow weaving and use devouring plage on a mob.

### Extra Notes

Jaxen on discord and Ruannon in game.

**Comment by syssneck** [comment]
Hi, thank you for the report. 
This issue is already known to us, see here: [chromiecraft/issues/1049](https://github.com/chromiecraft/chromiecraft/issues/1049)
and here for AC: [azerothcore-wotlk/issues/6689](https://github.com/azerothcore/azerothcore-wotlk/issues/6689).

**Comment by hehepwnd39** [comment]
Thx, have a nice day.
    On Saturday, July 17, 2021, 09:16:58 AM GMT+3, syssneck ***@***.***> wrote:  
 
 


Hi, thank you for the report.
This issue is already known to us, see here: chromiecraft/issues/1049
and here for AC: azerothcore-wotlk/issues/6689.
