### ISSUE TITLE
Mountaineer Stormpike's Task not given 

### ISSUE THREAD

**Issue by Malthorian** [chromiecraft/chromiecraft#1223]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

https://wowgaming.altervista.org/aowow/?quest=1339

This quest should be given to my dwarven warrior Logan at level 9.  I am currently level 15 and Mountaineer Kadrell is still showing a grey exclamation point.  I had not been to Stormwind at all so I had no way of completing this quest.  Mountaineer Stormpike does not appear to offer the follow up quest for some reason.  I have successfully completed this task on other characters without issue.
![WoWScrnShot_071721_234411](https://user-images.githubusercontent.com/80268841/126040626-eccd5e90-0908-4144-9a6e-793d2c48ff0e.jpg)
![WoWScrnShot_071721_234849](https://user-images.githubusercontent.com/80268841/126040687-905e4282-2f7f-4041-8f33-05a11467b3a7.jpg)

### Expected Blizzlike Behaviour

I believe that at level 9, the quest should be available to anyone talking to Mountaineer Kadrell, who will send you to Mountaineer Stormpike, who then sends you to Stormwind to complete it.  I currently am unable to get this quest after trying UI reloads.

### Steps to reproduce the problem

Report to Mountaineer Kadrell in Loch Modan at level 9 or 10 with any character who has not completed the Stormpike's delivery task.

**Comment by Shineslippers** [comment]
I assume you did [Stormpike's Order](https://wowgaming.altervista.org/aowow/?quest=1338). That's why you can't do Mountaineer Stormpike's Task. Problem is about order, not about quest accessibility. Grey mark is just another quest.

**Comment by Malthorian** [comment]
Actually, I haven't done the Stormpike delivery.  My character Logan had not been to Stormwind at all to complete the Stormpike's delivery quest.  I'm unsure why it isn't giving the quest to me.  I'm unable to check it by quest ID inside the game, but my quest tracker addon shows both quests as not completed.

Can my character Logan be checked for quest ID 1338 and 1339?

Thank you!

________________________________

**Comment by Malthorian** [comment]
Second reply, I checked again and it seems that the quest had been completed earlier, my quest database wasn't working for a few quests and I found the finished quest tags.  Sorry for the confusion, I was checking quests on many characters to see if races and class caused problems.

Take care!
________________________________
