### ISSUE TITLE
Tome of Divinity and Tome of Valor bugged in inventory after finishing the quest (paladin)

### ISSUE THREAD

**Issue by Bloodelf099** [chromiecraft/chromiecraft#1225]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

after finishing the quest of the paladin to unlock detect undead and ressurect hability, the tomes what are given to you in the begining of the quest still on your inventory with the mark of "!" and when you click it they show a message telling you dont meet the quallifications to start the quest, but you can finish the quest anyway, so its just confuse i just trow it out of my inventory when i was out doing minning so was fine

### Expected Blizzlike Behaviour

dunno what should be his natural behavior.  here is a link from wowhead classic, besides i dont found in net nothing recording that bug, not even know if its a true bug, 

https://classic.wowhead.com/quest=1786/the-tome-of-divinity 

### Source

Paladin quest line for habilities

### Steps to reproduce the problem

1. paladin level 12 and talk to the paladin trainer on goldshire he will direct you to stormwind
2. in stormwind take the quest from the paladin  Duthorian Rall on the church 
3. talk with a dwarf
3. go ressurect another dwarf in the woods
4. go back to the cathedral
5. turn in the quest
6. in that point the tome was bugged in my inventory with the quest giver mark "!" ( i was like wtf , another quest ?) but it dont give not  other quest i was just saying i dont meet que qualification so i take a look on net dont see nono other quest with and I just destroy it and freed space on the bag

### Extra Notes

besides this little non harmfull issue it all going realy smoth good job guys.

**Comment by wizzymore** [comment]
Hi @Bloodelf099, are you a dwarf or a human?

**Comment by Bloodelf099** [comment]
Human

Em sáb, 21 de ago de 2021 08:15, EPTIC ***@***.***> escreveu:

**Comment by Hurgadil** [comment]
Encountered issue at Daphne Stilwell
Hailed Daphne (she then de-spawned)

**Comment by Bloodelf099** [comment]
Nice, some people haver said that was happening, is the tome of valor quest

Em seg, 23 de ago de 2021 22:48, Hurgadil ***@***.***>
escreveu:

**Comment by Snufflenose** [comment]
I'd like to add the "Ironforge Edition" of this bug.

At level 12 dwarven paladins are sent to Tiza Battleforge in Ironforge, who offers two quests:

A. "Tome of Divinity"
She hands you the "Tome of Divinity", a quest item which starts a quest (level 12), but when right-clicking it nothing happens - instead it says that "You don't meet the requirements for that quests".

B. "Tome of Divinity"
This is the quest (chain) for paladin's resurrection spell (redemption) and it works nicely.

**Comment by Nyeriah** [comment]
Tome of divinity part fixed, tome of valor still needs to be checked

**Comment by Shineslippers** [comment]
@Nyeriah There is already exist not closed report of Valor https://github.com/chromiecraft/chromiecraft/issues/676.  You can add fix to it if it will be neccesary. This one i will close.
About issues with Valor book. On quest accept it disapear. I don't see the way how it leave in inventory.
