### ISSUE TITLE
[Felwood] Jadefire Shadowstalker using wrong stealth ability

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1226]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Jadefire Shadowstalkers (https://wowgaming.altervista.org/aowow/?npc=7110) are using the ability Sneak (https://wowgaming.altervista.org/aowow/?spell=11013) which doesnt actually put them into stealth and are clearly visible from far away. 

![jadefire](https://user-images.githubusercontent.com/80769357/126059815-b80252de-7f9e-47d4-97ef-041338f2773a.jpg)

### Expected Blizzlike Behaviour

They should be using Sneak rank 1 ability per wowhead, and videos clearly show them being properly stealthed.

### Source

https://tbc.wowhead.com/npc=7110/jadefire-shadowstalker#abilities

https://youtu.be/BTP42cFGsT8?t=48
https://youtu.be/f78IXO87pVU?t=59

### Steps to reproduce the problem

1. Teleport to GUID 40743 for example
2. Observe the Jadefire Shadowstalkers

**Comment by syssneck** [comment]
You are probably right, but I'm not 100 % sure about this one. 
Both [wowgaming](https://wowgaming.altervista.org/aowow/?npc=7110#controlled-abilities) and [wotlkdb](https://wotlkdb.com/?npc=7110) suggest, that they should have this sneak ability. wotlkdb even says they should have sneak and sneak rank 1 lol. It is probably an error in their db. Is it possible, that a patch somewhere between 1.12 and 3.3.5a changed it from sneak rank 1 to the other sneak ability for those mobs?
I would like to wait for a third opinion on this one.

**Comment by gurveleg** [comment]
Don't think thats the case. Their names are not visible unless you target them, and even when you target them, the nameplate isnt there.
 In https://wotlk.evowow.com/?npc=7110 there are both abilites listed. So I think they should be using both together - since sneak just gives the animation and the actual stealth. Going through wowhead mobs with stealth they always have stealth + stealth rank 1 abilites.

**Comment by syssneck** [comment]
Yeah, I guess it makes sense, that they have both abilities then. Thank you for the research.
It seems to me, that wotlkdb and wotlk.evowow are the exact same db with a slightly different layout?
