### ISSUE TITLE
Getting a dissconected from server error when trying to log in.

### ISSUE THREAD

**Issue by Wolverinewarcraft** [chromiecraft/chromiecraft#1231]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I have tried to login to the server on both my computer and another PC. Everytime it gives me a message saying you have been disconnected from the server. I have reset my password as well as tried to update my files. A friend was able to login with his credentials on my machine.

### Expected Blizzlike Behaviour

It should allow me to just log in using my credentials. I am unsure if I was banned somehow but I am not sure as to why I might have been banned. So of that is the case I would appreciate a review on the ban or a reason as to why.

### Steps to reproduce the problem

Not sure how it could be replicated.

### Extra Notes

I am not sure if this is where this report should have gone but I cant find another place to get this solved.

**Comment by syssneck** [comment]
Hi, please contact the staff on the ChromieCraft [Discord server](https://discord.com/invite/jUdJRhmT3J) regarding your login problems. You can send a DM to Honey#4836, who is usually online and really helpful with this stuff.
You can also check mod-log, to see whether your account has been banned and for what reason.
