### ISSUE TITLE
[NPC][Reputation] "Wailing Death" doesn't "give 10 rep. through Exalted." at honored

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1232]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Wailing Death doesn't give 10 rep. through Exalted. when you're 4/12000 honored.
![WoWScrnShot_071821_134959](https://user-images.githubusercontent.com/22718174/126077258-5e513971-0c43-43ad-83b6-452a1c4361ee.jpg)

### Expected Blizzlike Behaviour

They should give 10 rep. through Exalted.

### Source

https://wowwiki-archive.fandom.com/wiki/Argent_Dawn#Outdoor_reputation_grinds
All the way down to "A few tips on Gahrron's Withering: ".

### Steps to reproduce the problem

Get honored with Argent Dawn.
Kill a Wailing Death.

### Extra Notes

Wailing Death: https://wowgaming.altervista.org/aowow/?npc=1804

**Comment by syssneck** [comment]
wowgaming says, that the reputation gain stops at friendly, but I'm not sure if the db is correct.
