### ISSUE TITLE
Fishing not working in Orgrimmar

### ISSUE THREAD

**Issue by aceangelwing** [chromiecraft/chromiecraft#124]
##### CONTENT PHASE:

1-19?

##### SMALL DESCRIPTION:

Zone: Orgrimmar (https://wowgaming.altervista.org/aowow/?zone=1637#fishing)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Fishing should be enabled in both the valley of spirits and the valley of honor.

##### CURRENT BEHAVIOUR:

Fishing in Orgrimmar doesn't work. Attempting to fish in either The Valley of Honor or The Valley of Spirits just gives a "You can't use that here" error message (occasionally gives a "water too shallow" message in some spots)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Go to either Valley of Spirits (Ur'kyo is a nearby NPC to teleport to) or Valley of Honor (Lumak is close)
Step 2 Attempt to fish in any of the surrounding water

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Confirmed https://github.com/azerothcore/azerothcore-wotlk/issues/4510
