### ISSUE TITLE
Brother Crowley does not appear to be spawned in SW Cathedral

### ISSUE THREAD

**Issue by Smokky** [chromiecraft/chromiecraft#1242]
I can see on my minimap a quest marker, when I mouseover it it says Brother Crowley, he is meant to be standing behind the First Aid trainer in SW Cathedral, I checked in the Crypts underneath the Cathedral and he is not there either.
apparently he gives a quest for Scarlet Monastery.

**Comment by Azcobu** [comment]
Thanks for the report, although please try to fill out the template in future, as it's there for a reason.

However, went and checked, and the NPC is spawned and accessible on my local server. 

![WoWScrnShot_071921_234021](https://user-images.githubusercontent.com/81782124/126173604-be477dcc-c0b2-4d7a-8e9e-ef39413cb107.jpg)

So closing accordingly.
