### ISSUE TITLE
[Loch Modan] Tunnel Rat Kobolds sometimes drop multiple ears

### ISSUE THREAD

**Issue by Joy-ccraft** [chromiecraft/chromiecraft#1245]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Tunnel Rat Foragers for quest [Rat Catching] are able to drop multiple ears.
I have checked the two camps on the eastern side of Loch Modan. 
My screen capture shows a drop from NPC GUID 9095 but it can happen from any kobold.
Looking through their loot table I don’t believe this should happen.

### Expected Blizzlike Behaviour

Each Tunnel Rat Forager should have a chance to drop a single ear only.

### Source

https://wowgaming.altervista.org/aowow/?npc=1176#drops 

### Steps to reproduce the problem

1. Pick up quest [Rat Catching]
2. Port to Loch Modan Kobold camps and begin clearing Tunnel Rat Foragers. 
3. Have patience until a kobold drops two ears. It may take some time.

### Extra Notes

![Screenshot from 2021-07-19 19-13-28 copy](https://user-images.githubusercontent.com/85800188/126202042-a1cd11b6-2011-4872-9358-3135ea29c602.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by iraizo** [comment]
Im not a pro at loot tables but Tunnel Rat Foragers loot table has a Tunnel Rat Ear and a reference loot table which also has a Tunnel Rat Ear which might cause them to drop twice?

<img src="https://i.imgur.com/UJ3maOE.png">

**Comment by Joy-ccraft** [comment]
Hi iraizo, thanks for taking time to look into the database. 

I cannot vouch for the accuracy of wowgaming's loot table. 
Assuming it was accurate and the mob _can_ drop two ears, the table should then read "1-2" for Tunnel Rat Ear, similarly to how it reads "1-3" below for Linen Cloth.

Either way, I have no objections against leaving the poor kobolds with two ears. :)

**Comment by iraizo** [comment]
The question is rather if its blizzlike that only 1 ear drops, which im not sure

**Comment by Joy-ccraft** [comment]
I personally don’t think we need fret about blizzlike behavior in this case, it’s so marginal.

However, if blizzlike is the standard then maybe the nearest we will get to an official source is wowhead’s classic database, which presumably reflects observations from classic: https://classic.wowhead.com/npc=1176/tunnel-rat-forager
Here we again see a single ear with 1-4 Linen Cloth for comparison.

That said, we can save the devs some time by leaving the kobolds with two ears, so I say, close the issue.  :)
