### ISSUE TITLE
Wand/Meele weapon Fast switch attack.

### ISSUE THREAD

**Issue by Razorce** [chromiecraft/chromiecraft#1246]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

While using a Wand, if you get in melee range, you can attack with Wand and then press 1 to attack with Melee. The attacks are almost simultaneous and result in constant high dmg. It is basically the same as attacking 2 times in a row, only this can be done continuously.

It would best be shown in the video I attached

https://user-images.githubusercontent.com/87674808/126230907-de13ca0c-d736-412f-8ee9-ba82f891c44a.mp4

### Expected Blizzlike Behaviour

As far as I  know.
The moment I attack I should get an attack Cooldown that's either = to the Cooldown of the WAnd or Melee weapon.

### Steps to reproduce the problem

1. Get a Wand
2. Getting into Melee range
3. Put Melee and range attacks on 1 and 2 hotkeys for fast switch
4. Attack with  wand
5. Attack with Melee

### Extra Notes

I would like to NOTe, that the only reason I think this is a bug, is because it deals crazy dmg, more then any Melee class can do as a ranged.

There is still a slight delay sometimes between attacks but it's at most 0.3-0.5 secs, which is still to fast.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Hey, thank you for the report. Can you quickly help me out with further testing, by telling me what weapon speed is your staff? I would assume it is 2.7 sec or faster than that.

**Comment by Razorce** [comment]
> Hey, thank you for the report. Can you quickly help me out with further testing, by telling me what weapon speed is your staff? I would assume it is 2.7 sec or faster than that. I also need the weapon speed of the wand.
> Edit: Nevermind, I got it.

Sorry I wasn't home.
But the staff speed is 2.2 and wand is 1.5. 
Hope it helps.
