### ISSUE TITLE
[Azshara] Truesilver Vein spawned above ground

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1247]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Truesilver Vein GUID 9329 is spawned too hight above ground and appears to be in the air.
![9329](https://user-images.githubusercontent.com/80769357/126239087-9bb8b088-94d2-4273-a925-6b334e690c25.jpg)

### Expected Blizzlike Behaviour

Node should be spawned lower so not all of it is above ground.

### Steps to reproduce the problem

1. Teleport to GUID 9329
2. Observe the node spawn

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by iraizo** [comment]
<img src="https://i.imgur.com/9TNnQUb.jpg"> 

Its perfectly fine on the ground. Tested on local ac server rev https://github.com/azerothcore/azerothcore-wotlk/commit/439a9403ac5d

**Comment by gurveleg** [comment]
What I mean is, the whole vein model is visible, only touching the ground with the bottom. Usually the model is placed so that about 60%-70% of it is above the ground.

**Comment by iraizo** [comment]
> What I mean is, the whole vein model is visible, only touching the ground with the bottom. Usually the model is placed so that about 60%-70% or less of it is above the ground.

Is there a source for this?

**Comment by gurveleg** [comment]
Well there's no official source, but just look at other mining veins and how they are spawned. Its very very rare to see a vein so high above ground. The rare exceptions where a big chunk of vein model is seen is usually when they are spawned at the side of a very steep hill, but even then you dont see the bottom of it.

**Comment by iraizo** [comment]
> 
> 
> @iraizo What is the status of this? Is it still being worked on?

Still needs to be linked to a AC issue

**Comment by damnablebear** [comment]
This is still the same as it was when @iraizo tested it, for me, on CC's PTR. 
![image](https://github.com/chromiecraft/chromiecraft/assets/127447064/d2139e66-c17f-465d-a266-adda16a45f55)
If you want to go directly to it, .tele azshara and .go xyz 3276.414062 -5124.830078 87.242325

It feels like barely an issue but I guess this specific node could be lowered a tiny bit.
