### ISSUE TITLE
Npc clipping through cage

### ISSUE THREAD

**Issue by satke** [chromiecraft/chromiecraft#1256]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

![image](https://user-images.githubusercontent.com/50931326/126407597-d5d0e0e7-35d2-4e02-9007-233a5034a8c1.png)

The mob that is hostile, in a cage, clips through the cage to fight with the guards.

### Expected Blizzlike Behaviour

The mob does not clip through the cage and does not engage in a fight with nearby hostile characters.

### Steps to reproduce the problem

Hinterlands, Quel'Danil Lodge, Rin'ji (npc name).
If he does not automatically start fighting the guards, get near him to pull aggro. This was the only mob where I saw this behavior so far.

GUID: 46065 (Entry: 142036)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I checked this character on an Ally and although he was hostile he never left his cage or aggroed onto the nearby guards.

However, there is a Horde escort quest that does let him out of his cage - I'm wondering if perhaps a Horde player started that, then saw you coming and ran away, leaving him out of his cage and attacking guards. Does that sound plausible, or did you see him actually leave his cage by himself?

**Comment by satke** [comment]
![WoWScrnShot_072521_151031](https://user-images.githubusercontent.com/50931326/126901092-fde97a85-8c00-45be-9111-4f5a07fe4338.jpg)
![WoWScrnShot_072521_150830](https://user-images.githubusercontent.com/50931326/126901094-5b8a13dc-72d8-44f4-a886-bcef5b938b24.jpg)
![WoWScrnShot_072521_151029](https://user-images.githubusercontent.com/50931326/126901095-03112672-50f2-4480-b239-c3edeeee02fa.jpg)

He spawns, he either aggroes or gets aggroed, he leaves the cage to fight.
On the live server it happens every time.

**Comment by TheRiddermark** [comment]
@Azcobu I made you a video to confirm this issue. Starts at the 1:40 mark. [[LINK]](https://streamable.com/s23yhw)

The NPC [Rin'ji](https://wowgaming.altervista.org/aowow/?npc=7780) seems to aggro on the [Highvale Rangers](https://wowgaming.altervista.org/aowow/?npc=2694) and goes through the cage to attack them. I was about to report this the other day, but I also thought someone started the escort quest and just left him there.

However, after that I observed this situation a few times more (including 3 times while making the video above)

Hope this helps! Cheers!

**Comment by Azcobu** [comment]
Thanks for that, appreciate you taking the time. That pretty clearly rules out the abandoned quest theory. However, a vanilla AC still doesn't show this behaviour, with Rin'ji being stuck in the cage even with enemies nearby:

![WoWScrnShot_110621_152425](https://user-images.githubusercontent.com/81782124/140598496-70eb867e-bc70-470a-8509-ca0e98a39ec7.jpg)

So for some reason the script is not working the same way on CC as it does on AC. You may also notice that on this occasion Rin'ji also spawned as a female, which is definitely not right.
