### ISSUE TITLE
[Quest] A little slime goes a long way - quest item usable on same mob

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1262]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

The quest item (https://wowgaming.altervista.org/aowow/?item=11953) for a quest A little slime goes a long way (https://wowgaming.altervista.org/aowow/?quest=4513) is usable on same mob repeatedly. I got all 10 samples from the same ooze.

### Expected Blizzlike Behaviour

Quest item should only be usable once per mob, like with previous quest in the chain (https://wowgaming.altervista.org/aowow/?quest=4512)

### Source

https://tbc.wowhead.com/quest=4513/a-little-slime-goes-a-long-way#comments

### Steps to reproduce the problem

1. Have the quest https://wowgaming.altervista.org/aowow/?quest=4512 completed
2. Take https://wowgaming.altervista.org/aowow/?quest=4513
3. teleport to one of the oozes in ungoro like https://wowgaming.altervista.org/aowow/?npc=6556
4. Kill it and then use the quest item on the corpse
5. see it can be used repeatedly on same mob

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Okay, I will close this one here then. We can do further discussion/testing in the AC issue. Ty nonetheless!
