### ISSUE TITLE
[Maraudon] Subterranean Diemetradons silence DRs with first application, overwriting debuff length

### ISSUE THREAD

**Issue by JanEbbing** [chromiecraft/chromiecraft#1266]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

In Maraudon, there are Packs of 3-4 [Subterranean Diemetradons ](https://wowgaming.altervista.org/aowow/?npc=13323) that cast an [AoE silence.](https://wowgaming.altervista.org/aowow/?spell=8281)

1. Pull the pack
2. Shortly after, they will cast Sonic Burst, with slight delays
3. The first sonic Burst applies a 10 second debuff
4. Subsequent Sonic Bursts apply the debuff again, but with Diminishing returns, resulting in a short debuff on the player.

### Expected Blizzlike Behaviour

Sonic Burst should not DR while it's still on the player.

### Source

This is a video from vanilla classic where 3 of them cast it at once, and the 10s silence is on the player.
https://youtu.be/PWdm5RYzKAk?t=620

### Steps to reproduce the problem

1. Pull the pack
2. Shortly after, they will cast Sonic Burst, with slight delays
3. The first sonic Burst applies a 10 second debuff
4. Subsequent Sonic Bursts apply the debuff again, but with Diminishing returns, resulting in a short debuff on the player.

### Extra Notes

I checked if this was changed in wotlk, but this doesnt seem to be the case: https://vanilla-wow-archive.fandom.com/wiki/Diminishing_returns#Diminishing_Returns_in_PvE

I probably mixed it up with DR affecting things like dodge rating etc in wotlk.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by j-hdt** [comment]
The applied DR is correct. In TBC dimishing returns were introduced, example is sheep from mage. In classic (pvp) you could chain cc people for 50 secs with each cast.
in TBC the timers got reduced to 12s on first cast, 6s on second and 3s on third cast (iirc).

Instead, the npcs shouldnt cast the silence when their target is already affected by the silencing debuff.
