### ISSUE TITLE
Node cluster #2

### ISSUE THREAD

**Issue by kuzaan** [chromiecraft/chromiecraft#1267]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Gathering nodes too close to one another.

### Expected Blizzlike Behaviour

Gathering nodes should be more spread out across the map.

### Steps to reproduce the problem

1. Below is a series of screenshots detailing the location and coordinates (below clock)

![Copper veins](https://user-images.githubusercontent.com/72312283/126630317-24da8b4b-fe71-4de9-af07-a6da88df6e46.png)
![hinterlands](https://user-images.githubusercontent.com/72312283/126630334-c4585aec-9cbe-42ee-9ddb-037e57dd40c1.png)
![hinterlands2](https://user-images.githubusercontent.com/72312283/126630335-1eadb090-5a4b-40f3-9072-86fb5c7f0c6f.png)
![hinterlands3](https://user-images.githubusercontent.com/72312283/126630336-6a9f4d48-307b-4764-a473-7baf74aa3978.png)
![hinterlands4](https://user-images.githubusercontent.com/72312283/126630340-9445cabc-1b26-4e3e-b5db-97dc75f9fa61.png)
![hinterlands5](https://user-images.githubusercontent.com/72312283/126630342-3afcc9ee-971f-4bbe-81c0-faa460f0f642.png)
![stv 2](https://user-images.githubusercontent.com/72312283/126630344-19b53a74-fcde-4bd1-aec0-04ff6b39691f.png)
![stv](https://user-images.githubusercontent.com/72312283/126630348-57fad492-3946-4602-b344-13d0813e1285.png)
![tanaris](https://user-images.githubusercontent.com/72312283/126630349-df5c1e6f-9064-491e-b74c-3b614b085468.png)
![tanaris2](https://user-images.githubusercontent.com/72312283/126630374-1e8f9c7d-6a1a-4cfc-8fd7-7e8a9da889bc.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 28a764641)
1:
Already known - https://github.com/azerothcore/azerothcore-wotlk/issues/6092

2:
![image](https://user-images.githubusercontent.com/53914190/129578124-3612d306-2bce-451f-8e35-909b2deb7146.png)

3:
GUID: 7824 & 7823
![image](https://user-images.githubusercontent.com/53914190/129578443-dfbef2cf-8b5c-4ec2-82b1-c63fe51aab4a.png)

6:
Could not reproduce.

7 & 8: 
I got completely different node clusters on multiple spawns, none of them anywhere near as clustered as the one pictured. So I don't see it as an issue.
They are pooled, so the cluster can spawn in a "lucky" configuration.

9:
GUID: 5845 & 357
![image](https://user-images.githubusercontent.com/53914190/129572925-1f4d0f94-6024-4b19-92f3-0da5aa148baa.png)

10:
GUID: 6581 & 17480
![image](https://user-images.githubusercontent.com/53914190/129573135-f636c922-0113-4a15-94d1-1b8284413583.png)

**Comment by Tereneckla** [comment]
Problem is that herbs and mining nodes are individual spawns right now. There should be a pooling system so that when an area isn't mined herb for a long time you don't have all spawns up at the same time (which causes these clusters) 
Pool should have a maximum and a minimum amount of nodes spawned and force spawns new nodes if it depletes
