### ISSUE TITLE
[Quests][Achievement] Corrupted Flowers in Felwood wrongly count towards Loremaster achivement

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1272]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Quests for Corrupted flowers in Felwood are counting towards Loremaster Achivement.

The quests (and all of the see also quests)
https://wowgaming.altervista.org/aowow/?quest=2523
https://wowgaming.altervista.org/aowow/?quest=996
https://wowgaming.altervista.org/aowow/?quest=4117
https://wowgaming.altervista.org/aowow/?quest=4119

### Expected Blizzlike Behaviour

The quests should not count towards Loremaster.

<html><body>
<div class="comment-header">

By 28451 on 2008/11/08 (Patch 3.0.3) |   |  
-- | -- | --

</div><div class="text comment-body comment-high-rating" lang="en"><b>The Cenarion Plant Salve quests do not add up for the Loremaster of Kalimdor achievement.</b><br><br>Not even on the first turn-in.</div>
</body>
</html>

### Source

https://www.wowhead.com/quest=2523/corrupted-songflower#comments

The are also not flagged as Loremaster quests in databases.

### Steps to reproduce the problem

1. Add a number of https://wowgaming.altervista.org/aowow/?item=11516
2. Go to any of the corrupted flowers in Felwood
3. Complete the quest and see it counted towards Loremaster achievement quest count

### Extra Notes

Been doing Felwood quest and corrupted flowers to report another bug with the spawn/loot of the flowers, when I randomly got Loremaster Achievement. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Idk, Not every corruped flower does it. Only 2 specific. Same for other flowers. I guess Everyquest addon can't count as evidance of wrong issue because it's retreaving info from server.

**Comment by gurveleg** [comment]
They are listed in everyquest yes, but they should not count towards Loremaster. I must have got over 20 quest entries from them, I checked nearly all of them.
