### ISSUE TITLE
Arena 2v2, 3v3 and 5v5 skirmish - Issue CD

### ISSUE THREAD

**Issue by Cromisaid** [chromiecraft/chromiecraft#1273]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Cds from active trinkets actually don't reset.
Take a look here:
https://youtu.be/GdAdyTb2w8w

### Expected Blizzlike Behaviour

Every single CD's should be reset before arena starting

### Steps to reproduce the problem

1. Join Arena on Chromiecraft, with a previously used active trinket cd as you see from the video.
2. Enter in Arena
3. Look at your trinket cd

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Hi, I tried with two trinkets, but the CD always reset when I entered the Arena. 
I will wait for someone else to test it. Also, can you give me the item name of your trinket? Ty!

**Comment by IntelligentQuantum** [comment]
Item ID: 21326 - 10455 - 7734 - 11905 - 18634 - 17744 - 10574 - 744 - 1713 
I tested all of these trinkets and the Cooldowns always reset when i entered the arena
