### ISSUE TITLE
[Dun Morogh] Charged under the map, fall and died.

### ISSUE THREAD

**Issue by TorgusGitHub** [chromiecraft/chromiecraft#1289]
What happened: I was killing Wendigo Yetis in the cave in Dun Morogh as a Warrior after I charged one of them my character charged into the textures of little uphill, clipped through it and fall to oblivion then died. 
How to reproduce this bug: Charge a mob in the cave which is on higher ground lvl than your character.
Expected behaviour: Charging to the mob instead of falling in to the void.
![WoWScrnShot_072521_204347](https://user-images.githubusercontent.com/61697091/126910766-3bdf969c-4e35-40c8-acb0-7d69ca71284d.jpg)
![meme](https://user-images.githubusercontent.com/61697091/126910774-03aafa97-9c64-4ad9-b616-11f7c4da5373.png)

**Comment by syssneck** [comment]
Hi, thank you for your report. Please don't delete the template, it is there for a reason. When you create a new issue on Chromiecraft, fill in the template with the necessary information.
I will close this issue now. You can create a new issue, fill in the template and copy your text and images from here. Ty!

**Comment by Azcobu** [comment]
As it turns out this is a known issue in any case (see https://github.com/azerothcore/azerothcore-wotlk/issues/6232) so don't worry about filing a new report as we already have an open issue for this. Nice meme though.
