### ISSUE TITLE
[Stranglethorn Vale]

### ISSUE THREAD

**Issue by Gizmoh** [chromiecraft/chromiecraft#1295]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Respawn rate is too high, about 30 mins give or take.

### Expected Blizzlike Behaviour

Should be around 5 minutes

### Source

https://classic.wowhead.com/npc=818/maizoth#comments
https://github.com/dalaranwow/dalaran-wow/issues/134
Couldn't find a better source, official patch notes are too bare.

### Steps to reproduce the problem

Kill mob
???
???
???
Profit

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report, which I'm inferring from the link is about Mai'Zoth. However, the Wowhead link you give has no info about his respawn time at all that I can see. The link to Dalaran Wow also has no actual source for a 5 min respawn, just assertions. The only relevant quote on Wowhead was "I couldn't find him. I searched the whole cave three times and nothing. Besides that ,all other mobs have long respawning time.' (from patch 3.3.5, https://www.wowhead.com/npc=818/maizoth#comments:id=1092038) which suggests a longer respawn time than 5 minutes. 

However, if you have any other sources or evidence for the shorter respawn, feel free to send it in.
