### ISSUE TITLE
Low population of Ghostclaw Lynx

### ISSUE THREAD

**Issue by nicoaravena** [chromiecraft/chromiecraft#13]
I was doing the quest https://www.wowhead.com/quest=9158/bearers-of-the-plague and searching for Ghostclaw lynx was hard, because of the low population of them.
![imagen](https://user-images.githubusercontent.com/4155059/103162483-eaeaf080-47cf-11eb-84ce-394df44a7249.png)
On the image, the left blue area, was empty of any kind of mobs and near of the Farstrider Enclave, there was 5 or 6 of them, so you need to wait a moment for the respawn.

Fun fact, I thought that I was disconnected of the server because of the lac of mobs 😆 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/672057316a51

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Yehonal** [comment]
I can confirm, according to Keira3 the creature with ID 16348 has only 19 spawns:

![image](https://user-images.githubusercontent.com/147092/103168742-23bdb080-4836-11eb-9203-8a9f30deb119.png)

way more less than expected, but we should check on other db sources too

I could also get the positions from retail eventually

**Comment by FrancescoBorzi** [comment]
moved here: https://github.com/azerothcore/azerothcore-wotlk/issues/4065
