### ISSUE TITLE
Multiple Chests spawning close to each other

### ISSUE THREAD

**Issue by Asipdk** [chromiecraft/chromiecraft#1309]
Not sure how much of a bug this really is, figured I'd report it anyway, while out in the world In Mulgore at one of the palemane camps I looted one chest and noticed a 2nd away just a few steps away. The chest I looted was directly to the left of my character in the picture, and you can see the other in the picture. 

![image](https://user-images.githubusercontent.com/5192790/127431161-b961b9e6-8f9d-4527-9df8-1d63f7ad1289.png)

**Comment by Azcobu** [comment]
Thanks for the report. However, without more details this isn't really fixable. There's a command you can use, `.gobject near` which will give object details about anything if you're standing near it. If you stand next to one of these chests, type that command, and screenshot the results, we can have a look. Will close this in the meantime.
