### ISSUE TITLE
Mailbox Duping Bug

### ISSUE THREAD

**Issue by Ahnkheg** [chromiecraft/chromiecraft#1310]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I purchased a Gnoll Punisher (https://wowgaming.altervista.org/aowow/?item=1214) from the AH and after that I purchased a leather chestpiece. I picked up the Gnoll Punisher from the mailbox but my leather chestpiece was not there. I /reloaded the game and another Gnoll Punisher was in my mailbox. I can keep doing this indefinitely, reloading and getting another Gnoll Punisher. I think this would classify as a duping bug.

### Expected Blizzlike Behaviour

It shouldn't be giving me another Gnoll Punisher everytime I reload my UI.

### Steps to reproduce the problem

1. Bought Gnoll Punisher from the AH
2. Bought a random leather Chestpiece from the AH
3. Received the Gnoll Punisher from the mailbox
4. Leather chestpiece was not in the mailbox
5. /reload the UI
6. Receive another Gnoll Punisher from the mailbox
7. Rinse and repeat for duping the Gnoll Punisher

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Ahnkheg** [comment]
The leather chestpiece was a Lupine Vest of the Eagle. Also all of the duped items seem to be linked. I cannot sell one without my equipped weapon also selling. I stored them in the bank for now.

**Comment by Helias** [comment]
thanks for the report, this seems a critical issue

**Comment by syssneck** [comment]
@Ahnkheg Hi, ty for the report! 
I've tried multiple times to reproduce the issue without success. Could it be that it is only a visual bug?
Please clarify, what you mean by "I cannot sell one without my equipped weapon also selling."
Can you try to exit the game, rename your WTF folder to WTF_old and disable all addons and see if the duped items are still there in your bank? Ty!

**Comment by Azcobu** [comment]
I've tried reproducing this, buying and selling items on the AH between characters, and then /reloading the UI when accessing items from the mailbox, with no issues found so far.

**Comment by Ahnkheg** [comment]
I have renamed my WTF folder and that seems to have fixed the problem. The duplicated items seems to have vanished from my bank. Weird that it allowed me to do it in the first place, but it all seems to be resolved now!

**Comment by Azcobu** [comment]
Thanks for the update, glad to hear it's all sorted now.
