### ISSUE TITLE
Khan Hratha quest bugged despawn

### ISSUE THREAD

**Issue by TauraqRekt** [chromiecraft/chromiecraft#1311]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When arriving at the horn for the quest Khan Hratha, the boss was already spawned in. I did not have to blow the horn.

### Expected Blizzlike Behaviour

This might have happened because someone spawned him earlier and he never despawned. The correct Blizzlike behaviour would be for the boss and his adds to despawn at a certain point.

### Steps to reproduce the problem

1, Accept quest: Khan Hratha
2. Blow the horn on top of the hill after acquiring the mouthpiece
3. Wait to see if the boss despawns after a certain point, don't engage him.
4. ???
5. Profit

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC df7230748)
After an hour, they despawned:
![image](https://user-images.githubusercontent.com/53914190/127706618-19fe88ea-207c-4d40-a9f6-10b4779f3c77.png)
![image](https://user-images.githubusercontent.com/53914190/127706632-5da27315-d7bf-443d-add7-82de936c582d.png)
![image](https://user-images.githubusercontent.com/53914190/127706641-e7fcc3b3-b86d-439d-87e6-703da99fbff5.png)

Presumably what happened is that someone didn't kill it, and you arrived within that hour. Which I think is the intended behavior?

**Comment by Azcobu** [comment]
Just had a look at the event script for this one, and the relevant table shows the despawn timer for these mobs is 3000 seconds = 50 minutes. That does seem pretty long, but seeing lots of reports from people on WH of making multiple corpse runs to kill this mob and his group, so it seems as it's probably Blizz-like, or at least in the general area.
