### ISSUE TITLE
Barrens Ore Spawns

### ISSUE THREAD

**Issue by Asipdk** [chromiecraft/chromiecraft#1315]
Ores spawn way too much all throughout the barrens, but this is the worst example I have found so far. These 2 copper ores are practically ontop of each other in the Bristleback area. Along with like 7 more ore nodes nearby along the mountain not picked up in the gobject near command. 
![WoWScrnShot_073021_184648](https://user-images.githubusercontent.com/5192790/127718837-6c40891b-f8a9-43a5-888a-28f3b4174d91.jpg)

**Comment by Azcobu** [comment]
Thanks for the report. This pair of copper nodes has already been reported in https://github.com/chromiecraft/chromiecraft/issues/712, so closing this as a duplicate. The overall copper spawns situation was also being worked on in https://github.com/azerothcore/azerothcore-wotlk/pull/6647 last I saw, so a more general fix may be on the way.
