### ISSUE TITLE
Wailing Caverns Final Boss Reset

### ISSUE THREAD

**Issue by Asipdk** [chromiecraft/chromiecraft#1316]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

While doing Wailing Caverns dungeon, our group after having to find another picked up a second tank. Our paladin tank did not realize their role got switched to Healer causing us to wipe. After this wipe we ran back in to attempt the final boss fight again protecting Naralex, However, upon our arrival we noted Naralex still stuck in his animation of rezzing the sleeping guy. There was no way to reset the fight at this point causing the group to have to disband and give up on the run as we could no longer progress any further.

### Expected Blizzlike Behaviour

Boss if Im not mistaken should reset back to the start and go through the escort and wave event again. 

### Steps to reproduce the problem

Wipe on the final boss fight in Wailing Caverns

### Extra Notes

![WoWScrnShot_073021_210106](https://user-images.githubusercontent.com/5192790/127723902-c659a0e4-1f5b-4905-b550-8533b509004a.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

HD Model Pack
ELVUI 
DBM
Atlas
AtlasLoot

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I'm a bit confused about how you all wiped but the Disciple of Naralex survived to get stuck. I thought if the party wiped the mobs would then go and kill him. At what stage of the event did you wipe?

Incidentally, for anyone else testing, the speedrun for WC is:
1. `.go c id 3678`
2. `.go c id 3671` (kill)
3. `.go c id 3669` (kill)
4. `.go c id 3670` (kill)
5. `.go c id 3673` (kill)
6. `.go c id 3678` (Start the event)

**Comment by Asipdk** [comment]
So we wiped just as big murloc dude((Forget his name)) spawned, and apparently he just reset running back to the water instead before despawning. We also tried seeing if we could pull mobs over to Naralex and then try to drop aggro to let them kill him, which also didn't work.

**Comment by Azcobu** [comment]
Thanks for the info, managed to repeat the behaviour. 

![WoWScrnShot_080121_144533](https://user-images.githubusercontent.com/81782124/127760115-05956544-b926-4698-bca6-11cb050a2f40.jpg)
![WoWScrnShot_080121_144824](https://user-images.githubusercontent.com/81782124/127760119-7603642e-d75a-447c-b9ba-c9e258159a3e.jpg)

However, looking into it further it seems as if the event resetting on failure wasn't added until version 5.3, and before then, a party wipe meant the event couldn't be completed. To quote from TBC Wowhead, "if the Disciple is killed or the group wipes, the entire event will fail. The event cannot be repeated until the instance is reset and all Lords of the Fang are killed again." (from https://classic.wowhead.com/guides/wailing-caverns-classic-dungeon). So annoying as it is, this appears to be Blizz-like.
