### ISSUE TITLE
Auctionator not scanning properly

### ISSUE THREAD

**Issue by Razorce** [chromiecraft/chromiecraft#1317]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [X] 1-19
- [X] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When you scan the auction house with auctionator it only scans about 5 items and stops as if the scan was complete.
Everything else from the add-on works fi
![image_2021-07-31_142617](https://user-images.githubusercontent.com/87674808/127739815-e5c1d6d4-7d04-4749-8fad-aaf554d352b9.png)
ne.

### Expected Blizzlike Behaviour

Auctionator should scan every single item in the Auction house, in the span of about 10-30 seconds.
Which is used to show prices in item tooltips.
![image_2021-07-31_143418](https://user-images.githubusercontent.com/87674808/127740005-42a44891-1c71-4ca9-a435-977116c0428e.png)

### Steps to reproduce the problem

1. Download Auctionator Add-on
2. Open Auction House
3. Open the More tab and click Full scan.
4. See buggy results.

### Extra Notes

The addon used to work 2 weeks ago no problem. I used to scan the AH 2-3 times, and then it stopped working like this.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Unfortunately this is a known issue with AC, as the Auction House doesn't (yet) support the `getAll` scan that Auctionator uses. We have an open feature request for it at https://github.com/azerothcore/azerothcore-wotlk/issues/5068 - but as yet the necessary changes to the codebase haven't been made.

If you are looking for a compatible AH addon, there was a comment on Discord that [Auctioneer v5.9.4961](https://www.curseforge.com/wow/addons/auctioneer/files/466767) works with our AH even if it's for 4.0.1 because the AH is upgraded for hardware checks to 4.0.1. Haven't tried it myself, but probably worth a look.
