### ISSUE TITLE
The Black Knight

### ISSUE THREAD

**Issue by mchasur** [chromiecraft/chromiecraft#1318]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Hello, I have an issue with the item The Black Knight (https://wowgaming.altervista.org/aowow/?ttem=12974)
When the passive proc happens, the item launches a Lightning bolt which deals nature damage.
![black knightres](https://user-images.githubusercontent.com/22340824/127740192-3ddcf52e-854b-4886-940c-cf6540b1487a.png)
![Uploading black knightres.png…]()

### Expected Blizzlike Behaviour

The item discription states that the item cast a shadowy bolt which deals shadow damage. (https://wowgaming.altervista.org/aowow/?spell=14106)

### Steps to reproduce the problem

1. Add The Black Knight to inventory (item code: 12974)
2. Equip The Black Knight
3. Attack a training dummy in a major city
4. Observe the combat log on self mode

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Synful-Syn** [comment]
That nature damage came from this shield.
![image](https://user-images.githubusercontent.com/22718174/127742843-c5e60602-a417-4083-9667-305fd2850792.png)
![image](https://user-images.githubusercontent.com/22718174/127742880-703540a7-1987-48ab-aa04-1d11f6402020.png)
