### ISSUE TITLE
The Missing Diplomat - A specific part does not trigger the Npc RP Event

### ISSUE THREAD

**Issue by mturca** [chromiecraft/chromiecraft#132]
ISSUE: FACTION SIDE: Alliance

 ![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:
The Missing Diplomat quest - Theramore phase does not trigger the RP event (https://wowgaming.altervista.org/aowow/?quest=1324)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once you subdue Private Hendel, an RP event should start with Archmage Tervosh and Lady Jaina Proudmoore at the location of Private Hendel that allows you to advance / complete the quest.

##### CURRENT BEHAVIOUR:

The RP event does not start. 

Workaround for completing the quest -> move to the Theramore Magic tower and interact with the NPC there

##### STEPS TO REPRODUCE THE PROBLEM:

1. Advance with the quest line up to https://wowgaming.altervista.org/aowow/?quest=1324 
2. Subdue the NPC (note that during the time i performed the steps the NPC guards assisted me with lowering the target HP)
3. Once Private Hendel is subdued - the NPC RP event should start

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment]
![WoWScrnShot_030521_151918](https://user-images.githubusercontent.com/47978220/110124901-5b634e80-7dcb-11eb-94ad-a22efda6f46d.jpg)
Above location is where the NPC RP event should occur after subduing the NPC

Workaround location 
![WoWScrnShot_030521_152246](https://user-images.githubusercontent.com/47978220/110124994-7a61e080-7dcb-11eb-991d-b2d415cc4a09.jpg)

**Comment by Fuchal** [comment]
![image](https://user-images.githubusercontent.com/226239/125149843-0e72f880-e16e-11eb-8b57-49e661d41352.png)
![image](https://user-images.githubusercontent.com/226239/125149851-1894f700-e16e-11eb-9844-a0de78573448.png)
![image](https://user-images.githubusercontent.com/226239/125149853-1c287e00-e16e-11eb-9325-e712c8dd909c.png)
![image](https://user-images.githubusercontent.com/226239/125149856-20ed3200-e16e-11eb-94ca-91044230b483.png)

Hendel is crazy, can't be kill nor be friendly, sorry with my poor english

**Comment by FrancescoBorzi** [comment]
@Fuchal please open a new bug report
