### ISSUE TITLE
[Wailing Caverns] Unable to enter dungeon after Wipe

### ISSUE THREAD

**Issue by Asipdk** [chromiecraft/chromiecraft#1322]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

While in LFD for Wailing Caverns the group initially got messed up after the tank left, I tried to swap to Tank and fury tank the instance however this bugged out and kept giving an error saying No dungeon is available. We continued on with 4 of us, then one of the hunters had to relog and then was removed from the group and kicked and couldn't rejoin. We finished the instance up to the Naralex encounter, wiped on the serpents. They reset the boss, when we tried to run back into the dungeon we received the following error in chat and were only able to resurrect via spirit rez. This had also completely put us out of the LFD functionality. 

![image](https://user-images.githubusercontent.com/5192790/127771849-a281c891-3445-42b1-ac41-b806331e997b.png)

### Expected Blizzlike Behaviour

Unable to re-enter instance after wiping.

### Steps to reproduce the problem

1. Enter dungeon in RFD
2. Have a player leave
3. Requeue
4. Leave queue to queue as different role
5. Wipe during dungeon

### Extra Notes

I am unsure if this will be reproducible this seems very one-off.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

AtlasLoot
Atlas
Elvui
Recount
Postal

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. You really are having a bad run in WC recently. You're right, this is not easy to replicate, but we do have an open ticket for what looks like the same issue, or at least the same error message already. Your ticket adds some useful information and I've linked it accordingly. Better luck in WC next time...
