### ISSUE TITLE
[Quest] Speaking with Nezzliok, Permanent object disappears

### ISSUE THREAD

**Issue by iEmpress** [chromiecraft/chromiecraft#1324]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Once a skull is looted, the object looted from despawns. It has a respawn time of 900s.

### Expected Blizzlike Behaviour

The object should stay, this should be easily identified by the floating skull should it disappear.

### Source

https://youtu.be/KC7xSHUJTjg?t=55

### Steps to reproduce the problem

1. Be Horde
2. Give yourself quest 585
3. Teleport to one of the skulls. Example:
9986 (Entry: 2891) - [Balia'mah Trophy Skulls X:-12544.000000 Y:-723.062988 Z:40.443199 MapId:0] 
4. Pick the Object. Notice it despawning.
5. I have confirmed 15 minute respawn.

### Extra Notes

https://wotlkdb.com/?object=2892
https://wotlkdb.com/?object=2891
https://wotlkdb.com/?object=2893

https://wotlkdb.com/?quest=585

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello, Thanks for the report. I can confirm that the skull piles do despawn, and watching the youtube from wow classic, I do not believe they should.

On a side note- running with GM mode on, the piles respawn almost instantly, which threw me off for a minute.
