### ISSUE TITLE
Darnassus bank

### ISSUE THREAD

**Issue by dockillborn** [chromiecraft/chromiecraft#1326]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

If you bank is full & you go to place more items in your bank by right clicking your items disappear . 

### Expected Blizzlike Behaviour

Your items are not supposed to move or disappear

### Steps to reproduce the problem

1. Darnassus bank
2. have a full bank.
3. right click a full stack of items of the same stack in the back (leather)
4. your stack in your characters bag will disappear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Greetings, Thanks for the report. Unfortunately, I wasn't able to duplicate this. 
I used light leather, and was in Darnassus. I had a stack of 20 in the bank, with a full bank. I tried to place another stack of 20 by right clicking. I would get a notice saying my bank was full, and the stack of light leather stayed in my backpack.

I'd like to help resolve this. Can you be more specific? Such as what exactly you were trying to put into the bank? Were you able to repeat the issue? 

One last thing, it might seem dumb but I have to ask. Any chance it went into one of your extra bags that may have had an additional slot? Or maybe stacked with a partial stack already in your bank?

**Comment by dockillborn** [comment]
I curios because im using bagon & bartender4 with Carbonite. Im going to look into this remove all of my gui addons & see if I can track it down. I will post soon & report back

**Comment by dockillborn** [comment]
![image](https://user-images.githubusercontent.com/55373261/127790499-a1158ce0-59de-4ef6-a29e-cd932c5f79ee.png)
I have disabled every addon, cache. I right clicked on to two more stacks of light leather, it just disappears & no sound

**Comment by Stump876** [comment]
Hmm, that is odd. Let's see if someone else can reproduce it.

**Comment by syssneck** [comment]
@dockillborn: I have to ask the obvious first. You have two Journeyman's Backpacks in your bank, that you did not open. Is the light leather in there?

**Comment by dockillborn** [comment]
I went through each bag in my bank & my 4 stacks of leather is not in any of those bags :/. I can share my screen on discord. I dont even get "Your bank is full" message. Is there anyway I can get recompensed for losing my leather?

**Comment by dockillborn** [comment]
I really thought I was having the worst glitch/ bug but your right I thought bagon automatically opens all bank bags & didn't realize I didn't have it set todo that. I'm so very sorry for wasting your all's time. :\
