### ISSUE TITLE
[Quest] 

### ISSUE THREAD

**Issue by ninjaskija** [chromiecraft/chromiecraft#1327]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The following Horde/Kalimdor quest is bugged:
Finding the Antidote
Quest Id: 813
Open-WoW Link: http://wotlk.openwow.com/quest=813

What's the problem?
This is a follow-up quest of "Need for a Cure", Quest Id: 813 (http://wotlk.openwow.com/quest=812).
You can only get and complete the quest if you started "Need for a Cure".

But here the quest is ALWAYS available, and I can repeat it endlessly - even after completing the whole quest chain and delivering the antidote.

### Expected Blizzlike Behaviour

The quest should be available ONLY if you get "Need for a Cure" and it should be unavailable after you finish "Need for a Cure".

### Source

 NA

### Steps to reproduce the problem

Finish "Need for a Cure"
Observe that "Finding the Antidote" is still available

### Extra Notes

NA

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello, Thank you for the report. Actually this seems like this is the correct blizzlike behavior. https://www.wowhead.com/quest=813/finding-the-antidote#comments  Apparently the quest was left in case you lost the antidote.

Doing it myself. The quest was not available to me until I accepted "[Need for a Cure](https://www.wowhead.com/quest=812/need-for-a-cure" After completing the quest "[Finding the Antidote](https://www.wowhead.com/quest=813/finding-the-antidote)" He did have a repeat of the quest. However, repeating the quest gave no reward (other than the antidote) and awarded no exp, rep, or quest count towards lore master after the completion of the initial quest. It is just a way to get more antidote.

Additional video from WOW classic showing the quest repeatable after completion of the initial quest. https://youtu.be/a8UsVQ0nQZc?t=98
