### ISSUE TITLE
Feero Ironhand respawn timer

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#133]
ISSUE: FACTION SIDE:
Alliance
CONTENT PHASE:
level 24
SMALL DESCRIPTION:
Quest: supplies to Auberdine https://classic.wowhead.com/quest=976/supplies-to-auberdine
NPC Start Feero Ironhand https://classic.wowhead.com/npc=4484/feero-ironhand
NPC_End: Feeron Ironhand
EXPECTED BLIZZLIKE BEHAVIOUR:
NPC Should spawn in 5 minutes
Npc should assist with killing mobs on the way
CURRENT BEHAVIOUR:
Respawn time is over 10 minutes and the first wave,he just kept walking while I was dealing with the mobs.
STEPS TO REPRODUCE THE PROBLEM:
Take quest,wait for first mob wave,aggro them.

**Comment by Helias** [comment]
The NPC Feero Ironhand respawned in about 5 minutes, I've just verified
