### ISSUE TITLE
Twilight Elementalist's in BFD

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#1333]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

https://wowgaming.altervista.org/aowow/?npc=4814
Mobs are immune to bleeds despite being categorized as humanoids 

### Expected Blizzlike Behaviour

You should be able to put bleeds on these enemies I.E Deep Wounds Rend Garrote Rupture Etc.  

### Steps to reproduce the problem

Go to Blackfathom Deeps 
Use rend on Twilight Elementalist 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. This particular mob is a known oddity, and has been reported before (in https://github.com/chromiecraft/chromiecraft/issues/579) as it's basically immune to almost everything:

![twilight-ele-bleed-immunity](https://user-images.githubusercontent.com/81782124/117562287-f2ef6100-b0dc-11eb-8bf9-c739021499ae.png)

The problem with fixing it is that the database is pretty inconsistent when it comes to what kinds of mobs are immune to bleeds (and other effects) and in this case we don't have the evidence or the sources to say clearly what is correct and what isn't. (Although if you have some source that we haven't spotted, we'd like to see it.) I should also note that the Elementalists are not unique in being humanoids with bleed immunity, as there are at least 4 others in the DB, and that's only counting those that are *just* bleed immune and not those who are immune to other effects as well. More on this general topic in https://github.com/azerothcore/azerothcore-wotlk/issues/5915. 

Anyway, as a result, closing this as a known issue.
