### ISSUE TITLE
[Badlands] Anathemus Epic rare is missing patrolling

### ISSUE THREAD

**Issue by Asthalor** [chromiecraft/chromiecraft#1334]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

The elite rare, Anathemus. is static on his spawn point.  https://wowgaming.altervista.org/aowow/?npc=2754
Reading wowhead comments like this one https://classic.wowhead.com/npc=2754/anathemus#comments:id=2897817
indicates that he should patrol the zone.

![image](https://user-images.githubusercontent.com/87535580/128064091-a37623a4-78b6-4b58-bba9-f63f1d04d337.png)

### Expected Blizzlike Behaviour

He should be patrolling around this zone
![image](https://user-images.githubusercontent.com/87535580/128063654-c9862f3c-208a-451d-be97-e6d472229d95.png)

### Source

https://classic.wowhead.com/npc=2754/anathemus

### Steps to reproduce the problem

.go c id 2754
Check that he is not moving at all.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, we already have a report for this NPC, https://github.com/chromiecraft/chromiecraft/issues/959, so closing this.
