### ISSUE TITLE
Thousand needles epic 70BS recipe

### ISSUE THREAD

**Issue by Bredlyy** [chromiecraft/chromiecraft#1335]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Killed bunch of a Kolkars in Thousand Needles (cave in Splithoof Crag) and epic 70lvl BS recipe dropped
https://imgur.com/a/04Opy4k
Was precisely npc=4096 / Galak Windchaser

### Expected Blizzlike Behaviour

Shouldnt drop from 25lvl mob

### Steps to reproduce the problem

No, it just dropped

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. Lucky you, it has a .04% drop chance. 

Confirmed through Kiera. It's in the loot table for Galak Windchaser, along with [Belt of Deep Shadow pattern](https://tbc.wowhead.com/item=30302/pattern-belt-of-deep-shadow)
![image](https://user-images.githubusercontent.com/68164076/128101305-b8929bef-e287-4bdc-b271-128a8309b166.png)

**Comment by Stump876** [comment]
@Bredlyy Could you also contact a GM in Discord and give them your Character name? It will save a lot of time. Thanks.

**Comment by Bredlyy** [comment]
> 
> 
> @Bredlyy Could you also contact a GM in Discord and give them your Character name? It will save a lot of time. Thanks.

Will do!
