### ISSUE TITLE
 NPC Kolkar Packhound/Oasis Snapjaw - Skinning Loot table

### ISSUE THREAD

**Issue by NightwindOI** [chromiecraft/chromiecraft#1347]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When u skin [Kolkar Packhound](https://classic.wowhead.com/npc=4316/kolkar-packhound) and [Oasis Snapjaw](https://classic.wowhead.com/npc=3461/oasis-snapjaw) , you got [Rugged Leather](https://classic.wowhead.com/item=8170/rugged-leather) or [Thick Leather](https://classic.wowhead.com/item=4304/thick-leather)

### Expected Blizzlike Behaviour

There is other leather in the loot table
https://classic.wowhead.com/npc=4316/kolkar-packhound#skinning
https://classic.wowhead.com/npc=3461/oasis-snapjaw#skinning

### Steps to reproduce the problem

Teleport to  4316 or 3461
Kill and skin the beast's
Check the loot table

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Seft35** [comment]
Confirmed myself: Thick Leather and Rugged Leather get constantly skinned off of lvl 12(may be lower; 1 test on druid = lvl 8 mulgore mob dropped Light Leather - correct ) up to lvl 16(may be  even higher) in The Barrens...
Please fix, more ppl on Discord know about this + asked a low level druid near crossroads confirmed even for him Thick + Rugged but said off of 17-18 lvl he got Light Leather (correct)..

**Comment by Foodlenz** [comment]
Was just about to report this too. Same thing happening in Belf-land.
Got thick leather, rugged leather and hides off of level 13-15 vamp mistbats.

https://user-images.githubusercontent.com/72258441/128576231-0c2ba5f5-30d9-4ac2-81ce-087c50e0a90c.mp4

**Comment by Azcobu** [comment]
Thanks for the reporting everyone, it turns out you were all reporting the same faulty skinning loot table, which made it much easier to find. It turns out there are 58 low level creatures dropping these high-level skins, so a bit surprised this is the first report we've had for it.

**Comment by NightwindOI** [comment]
None refuse free money  ( that's none reported it ) . Glad it gonna be fixed , and thx the other dude's who add more mobs to the issue.
