### ISSUE TITLE
[warlock] Nightfall Proc without having Nightfall

### ISSUE THREAD

**Issue by Ystrella** [chromiecraft/chromiecraft#1348]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Was in a dungeon and kept Proccing Shadow Trance, which warlocks get when they put talent points into Nightfall. I currently do not have any points in Nightfall and therefore should not be able to enter into the shadow trance.

### Expected Blizzlike Behaviour

Should not enter shadow trance without talent points in Nightfall.

### Steps to reproduce the problem

Problem with a talent ability happening without having the talent.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by vexima** [comment]
are you sure you didn't have [Glyph of Corruption](https://wotlkdb.com/?item=42455)?

**Comment by Azcobu** [comment]
Good question, sounds like that would be worth checking.

**Comment by Ystrella** [comment]
Ok. I feel sheepish. I do have that glyph. I forgot all about it. Not used
to playing with glyphs. I am really embarrassed to have wasted your time.
Sorry!!!

**Comment by Azcobu** [comment]
No worries, you didn't waste any of my time because @vexima did all the thinking, so it's all good. :)
