### ISSUE TITLE
potion and auto attack bug

### ISSUE THREAD

**Issue by krogoth4242** [chromiecraft/chromiecraft#1350]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Off and on I've had troubles with potions and auto attack getting stuck unable to turn on, fixed with completely reloading the game, except sometimes the game will continue to lock up when using a potion again.

The most detail I can give is today I repeated this bug the whole evening.  I think it may have to do with guardian elixir's, and healing potions (multilpe types).  Earlier in town I tried this: (out of combat)

Strong troll's blood potion (guardian elixir)- would highlight and stay highlighted on action bars, would not use item.
elixir of agility (battle elixir) - worked fine, highlighted only while clicking, used item and deselected.
strong troll's blood potion (guardian) - used item, but remained pressed down (gold box around on action bar) 

From the time the guardian elixir was used the first time, auto attack locks up and will not work at all without game restart.

At some point after removing all buffs and restarting the game I was able to use a healing potion.  Healing potions of various levels all were glitching with the box highlighted and turning off auto attack until game restart at one point.

I have tried disabling all addons, it works the same.

### Expected Blizzlike Behaviour

Expected is when clicking the guardian, battle elixirs, healing potions, invisibility potions, is instantaniously seeing the item consumed.

### Steps to reproduce the problem

simply clicking healing potions, invisibility potions, and strong troll's blood potion (possibly all guardian elixir)

### Extra Notes

This was tested on a blood elf rogue level 31 with 209 alchemy in stonetalon and undercity zones around 1am CST 8/7/2021

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. This appears to be a reoccurrence of an issue we thought was fixed - see https://github.com/chromiecraft/chromiecraft/issues/386 and https://github.com/azerothcore/azerothcore-wotlk/issues/5263. However, as those issues were closed, will use this as the current exemplar. 

Demo showing the procedure - drink troll's blood, exit, log back in, try to drink health potions, which all fail, and autoattack stops working. Right clicking on enemy mobs or clicking the autoattack button (bottom left button) both fail. This confims that the faulty behaviour described in #386 is still occurring:

https://user-images.githubusercontent.com/81782124/128601723-fa9d4ccd-d3a5-417a-8140-53394c5013a6.mp4

Have also reopened AC issue https://github.com/azerothcore/azerothcore-wotlk/issues/5263 accordingly.

**Comment by Lanakh187** [comment]
Not only potions cause the bug. It occurs to me always on Battlegrounds, when i try to use any of my trinkets or drink a potion, but i die in the moment of the use. It remains highlighted on the action bar, and my auto attack is bugged. When i use warrior's Charge (not intercept) it allows me to attack the charged target with normal attacks, but if i kill it or switch target, the auto attack is bugged again. It won't enable auto attack with right click , nor using the "Attack" ability in the General tab in spellbook. Removing the bugged item (either its a trinket or a potion) from the bag DEBUGS the auto attack. Equipping another trinket does not, tho. Relog works for debug also. It occurs so often i have to play with 2 opened clients, logging into the other one as soon as i experience the bug.
### Dolohov, human warrior ###
i can stream it happening in discord

**Comment by shinzo69** [comment]
I can confirm what @Lanakh187 wrote. For me its the Major Healing Draught Potion thats causing the issue all the time. Relogging or removing the potions fixes this issue but then I'll get a 30min deserter or im making minus stonks.
(also playing with 20ms)
