### ISSUE TITLE
The Missing Diplomat Private Hendel being hostile 

### ISSUE THREAD

**Issue by Mothtracker** [chromiecraft/chromiecraft#1352]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Quest: https://wowgaming.altervista.org/aowow/?quest=1266
Quest start: https://wotlkdb.com/?npc=4967
Quest end: https://wotlkdb.com/?npc=4966

For this quest you're supposed to talk to Private Hendel in order to complete the quest. The problem is that he is standing there, being hostile(when he shouldn't be) and the 2 npc guards that stand close to him are attacking him(when they shouldn't be). He then kills them, because on top of being hostile he is also not dying, then they respawn again and the same thing keeps happening indefinitely. And if you try to go near him he will attack you which doesn't lead to anything besides you having to run away from him to reset him and not die from him. I'm pointing out those details just incase they are a factor of importance, the only actual problem I believe is him being hostile.

### Expected Blizzlike Behaviour

You are supposed to find Private Hendel and then talk to him in order to complete the quest. 
https://wowwiki-archive.fandom.com/wiki/Quest:The_Missing_Diplomat_(15)

### Steps to reproduce the problem

Get to the part of the quest chain before this quest, which is https://wowwiki-archive.fandom.com/wiki/Quest:The_Missing_Diplomat_(14). After taking the next quest teleport to NPC "Private Hendel" and you will see that he is hostile.
DB GUID: 31274, current GUID: 19225

### Extra Notes

This bug might be happening, because of the next part of the quest where you need to subdue Private Hendel. Something must be going wrong there with the guard npcs that are involved.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I went and had a look at this NPC, and on my local server he seems to be behaving properly:

![WoWScrnShot_080821_150146](https://user-images.githubusercontent.com/81782124/128622686-1bfa3073-7224-4242-b318-50b0d230d5f7.jpg)

I also tried turning him hostile and then running away. If you do that he and his two minions seem to stay hostile to players from then on. However, your report mentions that his minions were attacking him, which I couldn't reproduce, as they weren't hostile to each other on my tests, just hostile to everyone else. 

Anyway, it may be worth checking back after a server restart on CC to see if the odd behaviour is continuing.

**Comment by Mothtracker** [comment]
Not his minions, mate, the guards attack him. Those 2 guards that are
behind him on that picture of yours.

**Comment by Azcobu** [comment]
> Not his minions, mate, the guards attack him. Those 2 guards that are behind him on that picture of yours.

Yeah sorry, that's who I meant. I called them his minions because when you confront Hendel, they join in and attack you:

![WoWScrnShot_080821_153601](https://user-images.githubusercontent.com/81782124/128695781-ee20c14d-9f3b-457b-b791-ee631ffcfa7b.jpg)

But you wouldn't have seen that bit because of the bug you're reporting. It also seems like you're not alone, from @TheRiddermark's link above, though I'm still unsure of how or where the difference between AC and CC regarding this NPC's behaviour/scripting could be coming from.

**Comment by wizzymore** [comment]
Based on this:
https://www.youtube.com/watch?v=1nlDIXYygio

He should be hostile and you need to get him to 1HP.
He is stil scripted wrong but the problem here is not the one you are describing, the guards should help him and attack you, then you "kill" the private and the npcs run away and despawn, then the script rolls in.

**Comment by Mothtracker** [comment]
Not exactly sure 1hp but you need to get him low(probably something like
20% up). The problem I described was the private being hostile in the first
place which somehow makes the guards attack him. I couldn’t even turn the
“talk to him” quest at the first place in order to get the confronting one
next, because of him being hostile. I don’t know how he got hostile in the
first place, I just wanted to do my quest, so I reported it and gave you
every detail I could notice.

**Comment by wizzymore** [comment]
Ok i get what you are saying now.

I think another user started the quest but never defeated him.

I tried all the questline now and this is the only one that is not working, seems like you he needs to get under 20% for the script to start but it never starts, i got him to 1 hp and nothing happens.

This is confirmed, i will come with a fix soon

**Comment by Mothtracker** [comment]
I’m glad we figured it out. Good luck on the fixing.

**Comment by Hurgadil** [comment]
He appears to be bugged again, cohorts do not spawn, Private Hendel is currently auto-hostile and Jiana is not spawning to apprehend him. Asked in world chat, another player whispered me they had the same issue several days ago.

**Comment by FrancescoBorzi** [comment]
@Hurgadil please open a new bug report
