### ISSUE TITLE
[Boss] "Golem Lord Argelmach" missing script

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1355]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

While fighting Golem Lord Argelmach, the 2 golems behind him doesn't come to help him.
![WoWScrnShot_080721_143904](https://user-images.githubusercontent.com/22718174/128614286-f1883762-06da-427d-bfb7-b5c30a366e2b.jpg)

We also didn't clear the room before attacking Golem Lord Argelmach and he didn't run for help.

### Expected Blizzlike Behaviour

I couldn't find how the golems are supposed to become attackable but it definitely feels wrong that both golems behind him does nothing while Golem Lord Argelmach ia having a terrible and painful death!

### Source

This comment speaks of golems killing fighting the players.
https://classic.wowhead.com/npc=8983/golem-lord-argelmach#comments:id=2806597

(There are many comments that contradicts themselves but this one does seem to cut the contradictions).

> he does run out of the room to rally the troops but only if you don't clear the those rooms first. If you clear the room before him he stays and fights when you pull

https://classic.wowhead.com/npc=8983/golem-lord-argelmach#comments:id=3172945

> If threatened, Argelmach will draw all living Manufactory technicians and golems to eliminate adventurers. Before taking him down, adventurers would probably find it advantageous to kill all mobs in the Manufactory first to lessen the difficulty of the fight.

https://wowpedia.fandom.com/wiki/Golem_Lord_Argelmach

### Steps to reproduce the problem

Run directly at Golem Lord Argelmach and fight him.

### Extra Notes

Golem Lord Argelmach: https://classic.wowhead.com/npc=8983/golem-lord-argelmach
Wrath Hammer Construct: https://classic.wowhead.com/npc=8907/wrath-hammer-construct
Ragereaver Golem: https://classic.wowhead.com/npc=8906/ragereaver-golem

Golem Lord Argelmach has a quote but I might have missed it when we fought him. That quote mentions he will have his golems fight for him.
> Intruders in the Manufactory? My constructs will destroy you!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. We do already have an open issue for this problem, but this one has much better sources, so linking it across as further evidence.
