### ISSUE TITLE
Veteran Gladiator in Silvermoon has glitchy textures, incorrect model.

### ISSUE THREAD

**Issue by ServiusII** [chromiecraft/chromiecraft#1357]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The Veteran Gladiator NPC (https://wowgaming.altervista.org/aowow/?npc=22097), located in the same room as the Silvermoon Battlemaster, has strange, glitchy textures all over their body and face. It looks like their armor isn't rendering properly, and they have a female model despite having a male voice.
![WoWScrnShot_080821_002214](https://user-images.githubusercontent.com/88596879/128620903-826c70e9-4326-448f-b272-2d32b9816a30.jpg)
![WoWScrnShot_080821_002126](https://user-images.githubusercontent.com/88596879/128620910-af3d3585-5012-4426-b185-ae4b1718bd24.jpg)

### Expected Blizzlike Behaviour

I haven't been able to find any videos or screenshots of the model working properly, but Wowpedia (https://wowpedia.fandom.com/wiki/Veteran_Gladiator) lists the NPC as a human male. 

### Steps to reproduce the problem

1. Go to Silvermoon.
2. Enter the room with the Paladin Trainers.
3. Go further until you reach the room with the Battlemaster NPCs.
4. The glitchy Veteran Gladiator should be on the left when you enter the room. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the (rather unsettling) report. Just checked on my AC instance and the Gladiator is dressed a bit more sensibly.

![WoWScrnShot_080821_170444](https://user-images.githubusercontent.com/81782124/128624641-e30c1934-bbc8-4d4d-9d36-21152ec73f34.jpg)

Are you running any texture mods or packs that might be affecting models/textures? It's probably also worth clearing your client cache to see if that helps.

**Comment by ServiusII** [comment]
Thankfully, I just went back and checked this NPC again after clearing my cache a second time, and he now looks fine. I had been using some of the HD graphics patches, but had deleted them, so maybe that was the issue. Hopefully, it should be fine for good now.
