### ISSUE TITLE
Skybox textures in Silvermoon's Murder Row don't cover the whole sky, zoom in and out when you move the camera.

### ISSUE THREAD

**Issue by ServiusII** [chromiecraft/chromiecraft#1359]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When running southward through Murder Row from the Court of the Sun in Silvermoon, if you move the camera upward while running, you see that the the skybox textures that are distinct for Murder Row appear as a sort of "rectangle" in the sky, which grows and shrinks whenever you move the camera. 
![WoWScrnShot_080821_002614](https://user-images.githubusercontent.com/88596879/128621101-8112617c-2bef-44a7-882b-c1ff2a4ee501.jpg)
![WoWScrnShot_080821_002553](https://user-images.githubusercontent.com/88596879/128621103-a15a9b26-24b6-46b4-aa59-425a0975e41b.jpg)

### Expected Blizzlike Behaviour

As far as I can recall, the skybox textures should apply consistently to the sky in that area, covering it entirely whenever you walk through that part of the city.

### Steps to reproduce the problem

1. Travel to the Court of the Sun in Silvermoon
2. From there, run southward into Murder Row.
3. As you run that way, turn the camera upward towards the sky. Then move the camera up and down slightly as you run.
4. Stop running for a moment and keep moving the camera up and down to see if the problem continues.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. In this case it appears to be a client-side graphics/display issue - at least, I've never heard of AC making any changes to skyboxes. They're client-side rather than being controlled by our database or server code, and thus can't be modified or fixed without patching the client. As such, this issue is outside the scope of the project, so closing this accordngly.
