### ISSUE TITLE
Assault on Zeb'Nowa Shadowpine Catlords

### ISSUE THREAD

**Issue by mistertinkles** [chromiecraft/chromiecraft#1362]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Doing the Ghostlands quest "Assault on Zeb'Nowa" involves killing 10 Shadowpine Catlords. The Shadowpine Catalords contained within the huts in the troll town areas will appear to be within melee range, but autoattacks and abilities are not firing correctly. Dragging them out of the huts appears to resolve the issue, but mob density makes that a bit complicated at times.

### Expected Blizzlike Behaviour

Shadowpine Catlords will operate like every other melee mob and be attacked easily when in range.

### Steps to reproduce the problem

1. Travel to southeaast Ghostlands, in the Zeb'Nowa region.
2. Get into melee combat with a Shadowpine Catlord that is in one of the huts
3. Have trouble getting any attacks - particularly autoattacks - to operate as per usual.
4. Drag the mob out of the hut and commence normal melee combat.

### Extra Notes

https://wotlkdb.com/?quest=9277

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I've just gone and beaten up quite a few indoor Catlords on a warrior and a pally and haven't run into any issues with attacks so far. (Well, not entirely true - their pets despawn when they die which is wrong, but we have an open ticket for that.) Your other two issues were both pretty easy to replicate, but having trouble with this one. Could you tell me which race/class you were on and more about the problems you were getting? Were there out of range errors on targets you were standing next to, or what was going on exactly? Thanks.

**Comment by mistertinkles** [comment]
I originally was on my paladin and just now tried to unsuccessfully replicate the issue on the same character. So, nevermind on this one.

**Comment by Azcobu** [comment]
No worries, thanks for the update.

**Comment by Riddian** [comment]
I just did the quest as a Blood Elf Priest, I found that the Shadowpine Catlords themselves worked correctly, but aslong as I did not touch the Lynx they just walked up to me and did not attack(and then despawn when the Catlord died). And if I ran away from them the Catlord reseted correctly but the Lynx kept following me all the way to Farstrider Enclave. If I attacked the Lynx it started to attack but when I ran away from it it reseted to the position it was when I attacked it(so just outside Farstrider Enclave).

Also related, the Shadowpine Hexxers are not displaying a message when they start to flee when low health.

**Comment by Azcobu** [comment]
Ouch, that's quite the list of errors. Fortunately some at least are being addressed - the pets despawning when their master dies now has a fix (see https://github.com/azerothcore/azerothcore-wotlk/pull/7607) although it hasn't made it across to Chromie yet. I think the others are all known bugs with open issues (except perhaps the Hexxers.)
