### ISSUE TITLE
Unable to enter instance when dead or teleport away after a party member leaves after requeuing for dungeon finder

### ISSUE THREAD

**Issue by da-stealth** [chromiecraft/chromiecraft#1366]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When a dungeon group is formed via the dungeon finder and a member leaves the group has the option to requeue. Once requeued, if another member leaves, the party state gets jumbled and the option to teleport out of the instance goes missing. Additionally if a party member dies whilst in the instance, they will be unable to enter the instance to resurrect themselves until they leave the party.

### Expected Blizzlike Behaviour

Any character should be able to enter the instance where their body is contained at any point. Additionally, you should always have access to the "teleport out of instance" option when inside the instance until you have left the group.

### Steps to reproduce the problem

1. Find a group using dungeon finder
2. A party member leaves (so long as a party of at least 3 still remains)
3. The group requeues to find another member for the dungeon using the dungeon finder
4. Another member leaves the party (so long a party of at least 2 remains)
5. NOTE here that the option for "Teleport out of instance" is now missing. The only way to leave the instance and be teleported back to your original location is to exit via the instance entry.
6. Die with at least 1 of the remaining part members
7. Try to re-enter the instance to resurrect via reuniting with corpse
8. In order to enter the instance, you must leave the party
9. Exiting via the instance entry will not teleport you to your original location

### Extra Notes

I have tested this with a Deadmines, Blackfathom Deeps and Wailing Caverns on a local AzerothCore server also with the same result.

![Screenshot 2021-08-09 120451](https://user-images.githubusercontent.com/38900105/128654768-147b48eb-8e1a-4a60-bfa0-e989cec3a7f8.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. This looks like the same issue as https://github.com/azerothcore/azerothcore-wotlk/issues/6790 - the error message 'the map cannot be entered at this time' and missing teleport option after at least one person leaves the party, and then a party wipe, seems very similar. Will link this across. Looking at that issue, a fix so that dead players can at least rez at the instance entrance if you can't enter it has been merged, though I don't think it's made it to Chromie just yet. However, the wider issue where RDF is breaking is still open.
