### ISSUE TITLE
>2 primary professions on same character

### ISSUE THREAD

**Issue by ChristianTheBob** [chromiecraft/chromiecraft#1370]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

My character got 3 primary professions. I abandoned the two professions I originally had and learned tailoring instead. When I logged out and back in, Inscription and Herbalism was back, but Tailoring was still there. Furthermore, Tailoring had now been decreased to 1 from 70 and First Aid back to 80 from 106. 
Everything else done throughout the game session was saved properly.

### Expected Blizzlike Behaviour

I'm not supposed to be able to have 3 primary professions

### Steps to reproduce the problem

learn herb/inc, level them to 60ish
abandon herb/inc
learn tailor
relearn herb
level tailor to 70
relog

### Extra Notes

It was the end of a longer session, where I also did DM. All loot and experience from the dungeon as well as items spent and crafted from tailoring were saved properly.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. This has already been reported in https://github.com/chromiecraft/chromiecraft/issues/1044 and raised as a high priority issue in https://github.com/azerothcore/azerothcore-wotlk/issues/7165, so closing this as a duplicate.
