### ISSUE TITLE
Faction change and reward: Corruption of Earth and Seed

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1372]
### What client do you play on?

enUS

### Faction

- [x] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Can be completed twice after faction change.

Rewards 7 reputation for Cenerion Circle.

### Expected Blizzlike Behaviour

Rewards 500 reputation.

### Source

https://wotlkdb.com/?quest=7064

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by baranzadeoglu** [comment]
faction change:
UPDATE quest_template_addon SET ExclusiveGroup = 7065 WHERE (ID = 7064);
UPDATE quest_template_addon SET ExclusiveGroup = 7064 WHERE (ID = 7065);
rewards:
UPDATE quest_template SET RewardFactionValue1 = 500 WHERE (ID = 7065);
UPDATE quest_template SET RewardFactionValue1 = 500 WHERE (ID = 7064);

**Comment by JamesGent** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/7273

**Comment by jamadaha** [comment]
I'm gonna assume this is no longer being triaged, considering the triager? has deleted account

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/11403
