### ISSUE TITLE
Impossible to use [Call Pet] when pet is dead and hidden

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1378]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Impossible to use [Call Pet] when pet is dead and hidden

### Expected Blizzlike Behaviour

**Even** if pet is **dead** you **can call him** (dead body) with [Call Pet]. Dead pet spawn (appear) at hunter.

### Steps to reproduce the problem

have dead pet
hide him (move so far)
try call him

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Mitradis** [comment]
**because of this macros do not work**

**Comment by Azcobu** [comment]
> Even if pet is dead you can call him (dead body) with [Call Pet]. Dead pet spawn (appear) at hunter.

I don't think is accurate, and haven't found any sources that say this is how Call Pet should work. As you have left the "Source" section empty here, it seems you have not either. If you do have evidence of this behaviour, please give a source for it.

Users on TrinityCore discussed this issue [here](https://github.com/TrinityCore/TrinityCore/issues/1090#issuecomment-1185678) and decided that having a dead pet teleport to you was not Blizzlike, which is probably why AC behaves the way it does. (It could be worse - there's a TC thread where using Call Pet on a dead pet used to crash the server.)

As for the macro not working, that appears to be a limitation of the macro system - there's a discussion [here](https://www.wowhead.com/forums/topic/pet-revive-call-macro-help-needed-2190#p23843) where someone talking about this kind of revive macro says:

> I've tried the last suggestion; unforturately it didn't work. It returns an error message if pet is dead and non-summoned. Call Pet doesn't work in that case but the macro doesn't jump to next command either. I think I'm convinced that there, for now, is no way to make a macro tell if your pet is dead or alive while it's non-summoned.

**Comment by Mitradis** [comment]
Seriously? did you close it? macros don't work because of this
https://wowwiki-archive.fandom.com/wiki/Useful_macros_for_hunters

**/cast [@pet,dead][mod:shift] Revive Pet
/cast [nopet,nomod] Call Pet 1
/clearfocus [@focus,dead]
/focus [@focus,exists]player;target
/clearfocus [@focus,noharm]
/petattack [@focus,exists]
/petfollow [@focus,noexists]
/cast Hunter's Mark**

this macro does not work if the pet is dead and gone.

**Comment by Mitradis** [comment]
do you need proof? are we in court? you should check how it works on the original. And there it works as I wrote it.

**Comment by Mitradis** [comment]
you just need to allow the dead pet to be summoned. It's so simple. Set off to complicate everything and try to get away from the solution.
You need source? You not play on official servers? Okey just go on Warname server this is most blizz like server. I play 8 years hunters on off servers and warname and other. I know what i say.
