### ISSUE TITLE
Using objects must generate further agro distance

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1379]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

If player use any objects he does not attract attention if npc are behind the object.

### Expected Blizzlike Behaviour

If player use mining\herb or other ANY object, server must generate agro FROM this object (**I guess so**). 
In other words: when the player uses any object in the game world, any NPCs standing around him (behind him) should pay attention to the player, as if he were standing there.
I know that if you use an object, then the npc around it should react to it.

### Steps to reproduce the problem

use any object with NPCs near.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Mitradis** [comment]
it will also partially solve the problem with bots. They will have to fight more.

**Comment by Azcobu** [comment]
Thanks for the report. I'm not aware of any system where a mining/herb/other spawn would generate threat from using/interacting with it. If you could provide a source of some kind to demonstrate what you mean, that would be good. I'll close this in the meantime.

**Comment by Mitradis** [comment]
of course you closed it, you didn't even understand what I mean
