### ISSUE TITLE
Teldrasil - Mangy Nightsaber drop rates

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#138]
##### SMALL DESCRIPTION: I'm not sure if this is a bug or not so I'd like you to help me understand this. 
Are Mangy Nightsabers suposed to drop this many grey items in 3 kills? I played in classic and it didn't feel like this much:

![WoWScrnShot_030521_200459](https://user-images.githubusercontent.com/54484196/110169109-1b629280-7df0-11eb-8061-520985d5f93b.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
This is not a Bug, **this is just our rate**, in addiction, what **"Classic"** have you played?
The **(ORIGINAL)** "Classic"**(The OLD ONE)** or the **NEW "Classic"**?

**Comment by illfated** [comment]
@claudiodfc : Just to ease your mind, the drop rates (especially for scrap) in modern Classic WoW are usually improved with regards to amount and frequency, compared to 3.3.5a, TBC and some of the other expansions.
