### ISSUE TITLE
[Ravenholdt] Milton Beats <Giver of the Beatings> model and spawn position

### ISSUE THREAD

**Issue by Blackmane11** [chromiecraft/chromiecraft#1380]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I had the stupid idea of clicking on the DO NOT TOUCH chest and spawn Milton Beats - he quickly got the best of me but i noticed two things.
The model should be a He instead of a She, now i am not sure i am seeing the right one because of the HD mod installed on the client but it shouldn't matter.
The spawn location is right on the chest instead of beside it.
The next screenshot shows the situation.
![WoWScrnShot_080721_103622](https://user-images.githubusercontent.com/88534145/129003723-5e774c80-4acc-49e0-9106-2124c6c4a6fe.jpg)

### Expected Blizzlike Behaviour

The expected behaviour should be at first that the model is a Male, just as shown below - the character is just similar to the Syndicate ones in Stormgarde in Arathi Highlands.
![Milton](https://user-images.githubusercontent.com/88534145/129003914-f339413e-efc9-4097-a58a-1975d658bac3.PNG)
I will put also the link to WoWHead.
https://www.wowhead.com/npc=13082/milton-beats
The spawn should be as shown below in this video clip from Youtube. (You are also able to clearly see the model)
https://youtube.com/clip/UgyrrD_CedTETMn3WRB4AaABCQ

### Source

YouTube and WoWHead just as wrote in Expected Blizzlike Behaviour.

### Steps to reproduce the problem

As seen here the spawn rate is every two hours: https://wowgaming.altervista.org/aowow/?object=178324
Location: 79.8, 79.4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello, thanks for the report. I believe this might have something to do with your textures. Running on a clean AC server He shows up just as you picture.
![image](https://user-images.githubusercontent.com/68164076/129137729-b010ec93-4df6-43a7-9b36-96e6fe2f5733.png)
