### ISSUE TITLE
Ghostlands needs to be settled

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1381]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

no NPCs
![WoWScrnShot_081121_131107](https://user-images.githubusercontent.com/21084600/129011667-7dd79602-60de-4482-a155-4b9af75040a7.jpg)
![WoWScrnShot_081121_131110](https://user-images.githubusercontent.com/21084600/129011672-6b45a104-9dd9-4b3e-9832-109c0a759d63.jpg)

### Expected Blizzlike Behaviour

must be

### Steps to reproduce the problem

see screenshots

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello, Thanks for the report. There is a small empty spot right where you took the screen shot. But walking in any direction you will find mobs. Do you have any more info, maybe something that shows what blizzlike behavior as to what should be in the spot you're standing? What quest is that you're on that shows something in that area?

**Comment by Mitradis** [comment]
https://tbc.wowhead.com/npc=16354/vampiric-mistbat
https://tbc.wowhead.com/npc=16348/ghostclaw-lynx

**Comment by Stump876** [comment]
Thank you. Please remember that the more info you give us, the easier it is to confirm the issue. Even if it seems to be common sense, we need expected behavior and a source to back it up. 
That being said I can confirm that Vampiric Duskbat and Ghostclaw Lynx population is lacking in a section of ghostlands.
