### ISSUE TITLE
Wanted: Caliph Scorpidsting Adds Not Attacking Bug

### ISSUE THREAD

**Issue by Patterns111** [chromiecraft/chromiecraft#1392]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When doing the quest WANTED: Caliph Scorpidsting, I, as a frost mage, rooted (frost nova, rank 3) both of the adds that follow Caliph, and then proceeded to kill Caliph Scorpidsting before they got out of the root. Once I had killed Caliph Scorpidsting, the adds that I had aggro on, continued to aggro me, but stood completely still and did not move or attack. The adds are two Wastewander Rogue npc's. 

### Expected Blizzlike Behaviour

Here is a youtube video: https://www.youtube.com/watch?v=5ZWEmj5F3Hk 

The mage kills Caliph before the adds, and yet they continue to attack. Also, there are 3 adds? When I went to kill him he only had 2 with him. 

### Source

My source is myself? Don't quite understand this box. 

### Steps to reproduce the problem

Go to Caliph Scorpidsting in Tanaris (south of Gadgetzan). I have no idea if you need debug flags, or need to look at the console. Kill him before the adds, and this problem will occur. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 444383a58)
Both items stated verified in game:
Only two adds spawn. After killing him, with the adds frozen by frost nova, they remained motionless.
![image](https://user-images.githubusercontent.com/53914190/129281910-98843d45-66d3-49f5-a61a-6f94d89b3b7c.png)
![image](https://user-images.githubusercontent.com/53914190/129281929-9753c42a-c4d2-4062-b817-5d0d5022577c.png)
![image](https://user-images.githubusercontent.com/53914190/129281934-33189a12-16f1-43aa-9ee9-ac7c3db6a6a9.png)
