### ISSUE TITLE
WoW API - QueryAuctionItems() still not working properly

### ISSUE THREAD

**Issue by VFaleiro** [chromiecraft/chromiecraft#1393]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

This issue existed before, but could not be detected because the [previous issue](https://github.com/chromiecraft/chromiecraft/issues/1323) "obfuscated" it.
What I mean is the queries I was making to test it only involved grey items (which rarely take more than 1 AH page, people usually don't post that much junk), so there would be no difference between a common query or a getAll query. That's why I though the qualityIndex parameter was the only issue.
It **did** have issues and **it was fixed** (before, it was returning all grey items instead of all grey and superior items, now the function is properly respecting the qualityIndex argument).

The problem now is another argument of the same function, getAll. It's being completely ignored (doesn't matter if it's _true_, _false_, or _nil_, the Auction House will return the same thing).

### Expected Blizzlike Behaviour

1. When this argument is  _false_ or _nil_, it should behave exactly like an empty query using the default Auction House frames.
**This part is working completely fine.**

2. However, when this argument is _true_, it should return the same items but instead in one single page. That's why the getAll type of query has a 15 minute cooldown.
**The issue is here, the argument is ignored and the Auction House returns exactly what it would in case 1.**

Just to be transparent, I'm posting the structure of the function (how it should be called) again:
QueryAuctionItems(
name, -- string
minLevel, -- int or nil
maxLevel, -- int or nil
invTypeIndex, -- int (0 - 22)
classIndex, -- int
subclassIndex, -- int
page, -- int (0+)
isUsable, -- int (1 = true, 0 = no restrictions)
qualityIndex, -- int (0, 1, 2, 3 or 4)
getAll -- bool
)
So, a few example queries would be:

- This returns all items usable by you.
`QueryAuctionItems("", nil, nil, 0, 0, 0, 0, 1, 0, nil)`
This query has no cooldown.

- This returns all items that require level 10 to 19 to be used.
`QueryAuctionItems("", 10, 19, 0, 0, 0, 0, 0, 0, nil)`
This query has no cooldown.

- This returns only necklaces without any other restriction.
`QueryAuctionItems("", nil, nil, 2, 0, 0, 0, 0, 0, nil)`
This query has no cooldown.

- And, last but not least, the getAll query, returns everything posted in one single page.
`QueryAuctionItems("", nil, nil, 0, 0, 0, 0, 0, 0, true)`
It can also have filters like this, returns everything posted that is green or better in one single page.
`QueryAuctionItems("", nil, nil, 0, 0, 0, 0, 0, 2, true)`
This query has a 15-minute cooldown.

You can check if you are able to make a query by using the function CanSendAuctionQuery(), it returns 2 values.
In LUA
`local CanIQueryAH, CanIQueryAH_getAll = CanSendAuctionQuery()`
- The first variable _CanIQueryAH_ will always return 1 if you are allowed to make any common queries (I'm not sure exactly when it can return _nil_).
- The second variable _CanIQueryAH_getAll_ will return 1 only if you have not made a getAll query in the last 15 minutes.

I'm posting a list of useful script macros in the Extra Notes section, so anyone can copy and paste it into in-game chat to check anything needed.

### Source

https://wowwiki-archive.fandom.com/wiki/API_QueryAuctionItems#Pre-Patch_7.0.3

### Steps to reproduce the problem

1. Open the AH window by interacting with any auctioneer.
- NPC ID [8723](https://wowgaming.altervista.org/aowow/?npc=8723) for Alliance
- NPC ID [8724](https://wowgaming.altervista.org/aowow/?npc=8724) for Horde

2. Type this command in chat to query for all items posted without any quality/level/gear slot/etc restrictions.
`/run QueryAuctionItems("", nil, nil, 0, 0, 0, 0, 0, 0, true)`

3. Notice it will still split items posted in pages instead of making a complete list at once.

### Extra Notes

The macros, you can either directly paste them into in-game chat text-box or make an actual in-game macro.

- getAll query
`/run QueryAuctionItems("", nil, nil, 0, 0, 0, 0, 0, 0, true)`

- Check if you can make an AH query (it looks messy because of the 255 character restriction).
`/run local p=print;local a,b,c,d,e="You can"," make an AH query right now."," make a getAll AH query right now.","","";local canQ,canQAll=CanSendAuctionQuery(); if not canQ then d="'t" end; if not canQAll then e="'t" end; p(a..d..b); p(a..e..c)`

- Create an "event listener" that will tell you when the AH query is complete (any query, so anything you search on AH afterwards will still trigger it).
`/run local f=CreateFrame("Frame"); f:RegisterEvent("AUCTION_ITEM_LIST_UPDATE"); f:SetScript("OnEvent", function() print("AH query complete!"); end)`

- Just so you know, you can get rid of the "event listener" without having to relog with
`/reload`

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
When I say the previous issue obfuscated the detection of this, what I mean is que queries I was making to test it only involved grey items (which rarely take more than 1 AH page), so there would be no difference between a common query or a getAll query. That's why I though the _qualityIndex_ parameter was the only issue.
It **did** have issues and **it was fixed**. 

I guess I should have tested it more before making the other issue.

**Comment by Azcobu** [comment]
Thanks for the report and the accompanying information. Unfortunately this is a known issue and thus a duplicate, but have linked your information to the ticket so when someone is able to take a look at it, the information here will be available to them.

**Comment by VFaleiro** [comment]
Thanks.
