### ISSUE TITLE
Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by JamesGent** [chromiecraft/chromiecraft#14]
##### SMALL DESCRIPTION:

STV Fishing Extravaganza not working as intended from my experience.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPCs spawn (working)
2pm fishing tourney is announced (working)
All schools become tastyfish schools (not working)
Someone hands in 40 fish and wins (also a second place prize)

##### CURRENT BEHAVIOUR:

The schools do not become Tastyfish Schools.

https://classic.wowhead.com/object=180248/school-of-tastyfish

https://classic.wowhead.com/guides/wow-classic-stranglethorn-vale-fishing-extravaganza

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wait until 2pm next Sunday
2. See if the schools are tastyfish schools
3. Cry

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/672057316a51

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
moved: https://github.com/azerothcore/azerothcore-wotlk/issues/4066

please read: https://github.com/chromiecraft/chromiecraft#bug-reports
