### ISSUE TITLE
Offer: Disable Dungeon Finder system for testers

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1403]
Because testers must test world and quests in the world! And they only use DF for fast up level.

The role of a tester is meaningless if they don't explore the world or do quests.

**Comment by gurveleg** [comment]
![huh](https://user-images.githubusercontent.com/80769357/129394448-2dbd6e28-9ac6-4d98-9dcc-b622f3b166c9.jpg)

And if RDF was disabled, how would we then test and fix the RDF bugs?

**Comment by Mitradis** [comment]
it is not difficult to check each dungeon with a small group of people. In addition, no one will forbid people to get ready to go through these dungeons in the classic version (gather a group and go).
although as always you are of course right.

**Comment by Stump876** [comment]
If you wish to discuss suggestions for Chromiecraft, please join the [discord](https://discord.com/invite/jUdJRhmT3J). There is an entire channel dedicated to suggestions.
