### ISSUE TITLE
Gromsblood spawn in Azuremyst Isle

### ISSUE THREAD

**Issue by Gadixsp** [chromiecraft/chromiecraft#1417]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

A single node of [Gromsblood](https://wowgaming.altervista.org/aowow/?object=142145) spawns inside Stillpine Hold in Northern Azuremyst Isle. Judging by the database link, it appears there's also a spawn in Durotar that shouldn't be there.

![WoWScrnShot_081221_222242](https://user-images.githubusercontent.com/10586372/129446758-84ba5090-09de-4478-8783-b1ffb9a1b278.jpg)

### Expected Blizzlike Behaviour

Gromsblood should spawn in level 40-50 zones, with a few outliers in certain areas of level 30 zones.

### Source

[Wowhead TBC link](https://tbc.wowhead.com/object=142145/gromsblood)

### Steps to reproduce the problem

Enter Stillpine Hold and travel north along the lower path until you reach the red crystal where [Search Stillpine Hold](https://wowgaming.altervista.org/aowow/?quest=9565) is turned in.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 444383a58)
Found the one in Azuremyst Isle:
![image](https://user-images.githubusercontent.com/53914190/129451917-c9da7f81-b1f8-4ef9-8ad7-e48c39450eb7.png)

The one in Durotar, however, I believe to be in Ashenvale. Found these eight Gromsblood(ID 142145) in Ashenvale:
47871
16517
16515
16511
16481
16478
16457
16456

The one showed in Durotar, I think, is 47871, as seen in the picture where I'm standing atop it.
![image](https://user-images.githubusercontent.com/53914190/129452002-84cd83e1-b211-47db-b380-942a6794a8f9.png)

Whether that's another bug I don't know.
