### ISSUE TITLE
Never again quest

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#142]
ISSUE: FACTION SIDE:
Alliance
CONTENT PHASE:
25-30
SMALL DESCRIPTION:
Never again quest Diathorus The Seeker life drain,he is also now in the right spot in the cave.
Diathorus the Seeker in the cave
EXPECTED BLIZZLIKE BEHAVIOUR:
Diathorus the Seeker should not life drain
CURRENT BEHAVIOUR:
Diathorus the Seeker life drains all your hp and heals
STEPS TO REPRODUCE THE PROBLEM:
Take quest and go to the cave.

Step 1
Step 2
Step 3
AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@c2f274e
OPERATING SYSTEM:

Ubuntu 20.04
MODULES:

    mod-cfbg
    mod-duel-reset
    mod-desertion-warnings
    mod-ah-bot

OTHER CUSTOMIZATIONS:

None.
SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Narixel 
**Video Test:** [Quest - Never again](https://youtu.be/G78Kzvh7NK0)
![qqqq](https://user-images.githubusercontent.com/1884642/110195802-df532000-7e37-11eb-8d84-5f37711218b7.png)

LAST WARNING
-
So, I had already warned you, and you redid the same type of report, that is: ignoring the fields and instructions of our Form.
In addition, this is your 2 report I checked out, and this is the second time you
 make an invalid report, reporting a NON-EXISTING bug.
This is the second WARNING I give you, if you repeat the same mistakes again your reports will be closed directly.
