### ISSUE TITLE
Incorrect music in interior

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1420]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

In addition: In Undercity play music from Sylvanas' Music Box.

here in house play music from WOTLK location (Grizzly Hills):
![WoWScrnShot_081421_163755](https://user-images.githubusercontent.com/21084600/129449327-4e5e60fd-7f5c-41ba-ada2-57ebdc251963.jpg)
![WoWScrnShot_081421_163812](https://user-images.githubusercontent.com/21084600/129449329-bdd2eae2-03dc-4c27-9b45-a7dcc2bcf938.jpg)
music play if enter in second room

### Expected Blizzlike Behaviour

she definitely shouldn't play there

### Steps to reproduce the problem

screens

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 444383a58)
On entering the room, music begins to play. It sounds similar to what I could find on YouTube in terms of Grizzly Hills Music, but whether it actually is, or for that matter whether it should be there, I don't know.

**Comment by Mitradis** [comment]
yes I agree it's weird. I wrote about this. Music with Grizzly Hills in classic interior...

**Comment by Mitradis** [comment]
Yes I agree it's weird. I wrote about this. Music with Grizzly Hills in classic interior...
Need specialists in dbc\maps\mmaps (server files). I think this data is responsible for this. At least I know for sure that the music from the locations is in them.

**Comment by Mitradis** [comment]
In Undercity play music from Sylvanas' Music Box. Not sure, but she shouldn't play there either

**Comment by wizzymore** [comment]
> 
> 
> In Undercity play music from Sylvanas' Music Box. Not sure, but she shouldn't play there either
OffTopic:
Why not? Sylvanas "made" the undercity, she was already under the lich king control in classic, lore wise TBC and vanilla are after Arthas killed his father

**Comment by Mitradis** [comment]
@wizzymore "Why not?" What? this is you server for you or this Blizz like server? If you want you can do it on you local server.

**Comment by Faq** [comment]
1.) When something is reported, would be nice to know about what music exactly report is about. Other way each of You could be talking about different melodies.
2.) here it is, with gnomes step sound walking up stairs: [listen here](https://mega.nz/file/z9tRWYpQ#NDadabzNdSdQUqnJgY_6g28ydMfzvCk8dGZF2Wz4W08)
Recorded on: TrinityCore rev. 94c03b2107ad 2021-01-01 04:03:52 +0100 (3.3.5 branch)
If that is the same sound, then can be considered as blizzlike.
3.) if OP thinks that sound should not be there but other, then please provide some proof or this is just discussion.

**Comment by Stump876** [comment]
Agreed, Without a blizzlike source this is all just speculation.

**Comment by VFaleiro** [comment]
The music that plays there is actually [Howling Fjord's (during the day)](https://wotlkdb.com/?sound=12800).

What should be playing instead (an in all the other buildings around, ships included, which have no music at all) should be [this one](https://wotlkdb.com/?sound=2529).

This is just for reference though, if anyone who has a retail account wants to log classic and check, you can follow the link above (of what should be) to compare and confirm it.

**Comment by VFaleiro** [comment]
The music that plays there is actually [Howling Fjord's (during the day)](https://wotlkdb.com/?sound=12800).

What should be playing instead (an in all the other buildings around, ships included, which have no music at all) should be [this one](https://wotlkdb.com/?sound=2529).

This is just for reference though, it still needs someone who has a retail account and wants to log classic to confirm it. This someone can follow the link above (of what should be) for comparing.

**Comment by VFaleiro** [comment]
The music that plays there is actually [Howling Fjord's (during the day)](https://wotlkdb.com/?sound=12800).

What should be playing instead should be [this one](https://wotlkdb.com/?sound=2529).

This is just for reference though, it still needs someone who has a retail account and wants to log classic to confirm it. This someone can follow the link above (of what should be) for comparing.

**Comment by Gultask** [comment]
Since the music is from Northrend we might need someone to check this location in WotLK Classic to make sure.

**Comment by benjymansy123** [comment]
Forgive me if I'm wrong, but isn't music played in a location determined by client files as opposed to the server?

**Comment by Gultask** [comment]
>Forgive me if I'm wrong, but isn't music played in a location determined by client files as opposed to the server?

Probably. I asked one of the devs and I think they said it could be overriden, though.

However, I did check right now in the WotLK Classic PTR that just went live that this track really does play in that interior, for whatever reason.
