### ISSUE TITLE
Undermap Stormwind Critters

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1421]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

There are a few critters that are under the Stormwind's map.
![WoWScrnShot_081421_095432](https://user-images.githubusercontent.com/22718174/129448650-64e5131d-300d-4757-a102-551db00db900.jpg)
![image](https://user-images.githubusercontent.com/22718174/129449536-eaf7832d-f327-408f-8e88-898a309a4aff.png)
![image](https://user-images.githubusercontent.com/22718174/129449554-9c0f27ab-bd85-407b-8ebe-0443b0d543fc.png)

### Expected Blizzlike Behaviour

They should be wandering inside Stormwind.

### Steps to reproduce the problem

Get under the Stormwind map. Find them.
Here's the list of GUIDs
120819
120820
120767
79743

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 444383a58)
I found all the specified critters above map, in the city:
120819:
![image](https://user-images.githubusercontent.com/53914190/129450949-3bd7b50a-a0c4-4f97-a1a0-00a5ed713a19.png)

120820:
![image](https://user-images.githubusercontent.com/53914190/129450958-fd629635-1845-4d17-a432-06c3358146ea.png)

120767:
![image](https://user-images.githubusercontent.com/53914190/129450967-ed3394d0-82bb-4a5d-8296-2da815c45d24.png)

79743:
![image](https://user-images.githubusercontent.com/53914190/129450974-6ffcde78-1c2c-41c7-863f-4bea4a72209d.png)

**Comment by Synful-Syn** [comment]
Closed, might be related to having a terrible internet with 600ms latency.
