### ISSUE TITLE
Camera height is not updated when mount

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1428]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Sometimes camera height not updates
![WoWScrnShot_081521_130642](https://user-images.githubusercontent.com/21084600/129474884-5564dbee-7b4d-41ff-ace4-0a2e7a4e8724.jpg)
![WoWScrnShot_081521_130639](https://user-images.githubusercontent.com/21084600/129474891-217761f7-20e1-4e4f-8954-755dbdd802f9.jpg)
normal heingt
![WoWScrnShot_081521_130649](https://user-images.githubusercontent.com/21084600/129474888-3ce7dcb0-c03d-4a75-8e6f-dae73c5c2630.jpg)

### Expected Blizzlike Behaviour

always update

### Steps to reproduce the problem

mount and unmount until you see an error

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Avyxis17** [comment]
Can confirm, doesn't happen very often but it does nonetheless.

**Comment by Shineslippers** [comment]
This one i will close as https://github.com/chromiecraft/chromiecraft/issues/593 duplicate, but will report issue to AC.
