### ISSUE TITLE
High-level NPCs do not have a larger radius agro

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1431]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

High-level NPCs do not have a larger radius agro. I noticed this from the very beginning of the game. When passing by very high-level NPCs, they did not react to me, although I was much lower than them. Their agro radius was the same as those of my level (as if they are of my level).
![WoWScrnShot_081521_144854](https://user-images.githubusercontent.com/21084600/129477594-194675cd-d368-4edf-be59-a372593aab2b.jpg)

### Expected Blizzlike Behaviour

RED (level) NPCs react as soon as they see you. If it's no joke, then they have a very large radius agro on player if he is much lower than them.

### Steps to reproduce the problem

walk, run at high level npc

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
I tested a bit and saw nothing unusual. You seem to be on the edge of the detection range on your screenshot. No, the aggro distance is not the same and increases with mob level discrepancy.

**Comment by syssneck** [comment]
Lvl 43 player - lvl 40 mob (came as close as ~11 yards without aggroing):
![Screenshot 2021-08-16 00 44 46](https://user-images.githubusercontent.com/68868567/129494946-67068dc7-4b6b-4a67-bef5-092bd4d91365.png)

Lvl 43 player - lvl 48 mob (like in your screenshot, came as close as ~19 before aggroing):
![Screenshot 2021-08-16 00 46 17](https://user-images.githubusercontent.com/68868567/129494976-761bff64-d4b3-4426-9985-21f9551ac7e3.png)
