### ISSUE TITLE
To Gadgetzan You Go! - button complete quest not pressed

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1433]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

To Gadgetzan You Go! - button complete quest not pressed. Quest window not close or not proposed next quest.
![WoWScrnShot_081521_161633](https://user-images.githubusercontent.com/21084600/129479889-e6268fd7-1b63-4959-a404-5377cf36f4cb.jpg)

### Expected Blizzlike Behaviour

pressed. After this quest must proposed next quest.
![WoWScrnShot_081521_161842](https://user-images.githubusercontent.com/21084600/129479935-45670acd-9d43-4838-bb79-018d2fc90d38.jpg)

### Steps to reproduce the problem

pass quest To Gadgetzan You Go!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Can you please elaborate, what exactly is the issue here? Or can someone else help?

**Comment by Mitradis** [comment]
I don't know, it's just that sometimes you come across quests that you have to close through ESC.

**Comment by syssneck** [comment]
Yeah, this is a client issue. Try /reload or if this doesn't work, delete your Cache folder and restart the game. We can't/won't fix client side issues (it's not server side).
