### ISSUE TITLE
[Teldrassil] Herbalism spawns

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1439]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Being the first real zone –aside from tutorial area– from Night Elves and the first one in which you can learn the Herbalism profession, one would expect to have the lowest level of herbs spawning here, so we can get our skill a little bit up. However, currently many of the nodes (maybe 50%?) are spawning Mageroyal, which is a much higher herb that requires skill level 50. Not only is impossible to pick, but also it takes over the node and doesn't allow lower lvl herbs to spawn.

### Expected Blizzlike Behaviour

According to guides and many comments on wowhead, the area should have mostly Peacebloom and Silverleaf on the grassy open areas, Earthroot on slopes and rocks and RARELY some Mageroyal. These herbs should also give the chance to drop Swifthistle.

### Source

https://wowpedia.fandom.com/wiki/Herbs_by_area

https://classic.wowhead.com/guides/classic-herbalism-best-farming-basics-early-herbs

### Steps to reproduce the problem

There are no necessary steps to reproduce the issue, just go there and see it by yoruself.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report!
Both the first link you gave and [Wowhead TBC](https://tbc.wowhead.com/object=1620/mageroyal) for mage royal, show Mageroyal spawning in Teldrassil.
I can't find in either of the sources that Mageroyal spawns in Teldrassil being rare.

In fact, assuming that the prior comment is correct, there should actually be more Mageroyals. [Wowhead TBC](https://tbc.wowhead.com/object=1620/mageroyal) states 37 spawn points.
![image](https://user-images.githubusercontent.com/53914190/129591325-eb1ec3cd-a26b-488e-a4ee-5c744a9b95d2.png)

For now, I will close this issue. If you have any further sources for Mageroyals not spawning in Teldrassil, or them being rare, you are welcome to add them.

**Comment by cachocarne** [comment]
Hi! I think there is a missunderstanding. I agree there could be some Mageroyal in Teldrassil. The issue is that there is ALMOST NO Silverleaf and Peacebloom! How is one supposed to skill up Herbalism? Darkshore is the next zone for leveling and already has Mageroyal (50). Briarthorn (70) and Bruiseweed (100). Most of spawn nodes for Silverleaf and Peacebloom in Teldrassil are USED by Mageroyal, which nobody who just started leveling herbalism can pick. There should be more of the earlier herbs, that's all.

![ 2021-08-16 at 21 06 25](https://user-images.githubusercontent.com/77953030/129609397-f4d30783-1055-41ee-8c81-ed839b5c2244.png)
![ 2021-08-16 at 21 07 11](https://user-images.githubusercontent.com/77953030/129609493-68b23019-e1de-4c34-b296-ff64739f530c.png)
![ 2021-08-16 at 21 07 56](https://user-images.githubusercontent.com/77953030/129609590-697f5496-f759-4a7a-b0fe-80a97e39fece.png)

**Comment by jamadaha** [comment]
Ah! I'm sorry.
I'll open it again and take another look.

**Comment by jamadaha** [comment]
Hmm. I don't think the issue here is the Mageroyals spawning, rather that not enough herbs spawn.

Currently, all herbs in Teldrassil zone 141, is in one pool(entry 957), with a spawn limit of 35. This pool contains 140 herbs, while it only contains 13 Mageroyals. So it should only spawn around 3 of them at a time.

In game (local server AC 28a764641) I found 5'ish (just a quick fly by) Mageroyals. Albeit high, not unreasonable. This, however, leaves around 30 herbs of other kinds.

I don't know whether that is the correct amount tho.

**Comment by wizzymore** [comment]
Based on the following query that takes all herbs from Teldrasil:

```sql
SELECT COUNT(*), id, gameobject_template.name FROM gameobject INNER JOIN gameobject_template ON gameobject.id = gameobject_template.entry WHERE id IN (1618, 1617, 1619, 1620) AND map = 1 AND position_x > 9000 AND position_y > 200 AND position_x < 11000 AND POSITION_Y < 2800 GROUP BY ID 
```
| COUNT(*) | id | name | 
| ---: | ---: | --- | 
| 46 | 1618 | Peacebloom | 
| 30 | 1619 | Earthroot | 
| 51 | 1617 | Silverleaf | 
| 13 | 1620 | Mageroyal |

**Comment by syssneck** [comment]
@wizzymore thank you! 
Now if I just had scrolled one comment further, I could have saved 20 minutes, because I did the exact same thing :)
Oh nice, you searched for all nodes in a specific area. Alternatively, all the 140 nodes belong to the pool 957.

I guess we can close this one now?

**Comment by wizzymore** [comment]
> 
> 
> @wizzymore thank you!
> Now if I just had scrolled one comment further, I could have saved 20 minutes, because I did the exact same thing :)
> Oh nice, you searched for all nodes in a specific area. Alternatively, all the 140 nodes belong to the pool 957.
> 
> I guess @cachocarne was a bit unlucky with the herbs. :)

For real? Didn't notice the pool, i had to map out all teldrassil to reduce the nodes based on coordinates xD
