### ISSUE TITLE
[Quest marker on wrong location] Tears of the Moon (Quest ID: 2518)

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1441]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

On this quest we are asked to kill and take an item from Lady Sathrah (npc 7319), a big spider that stands at 48.1 , 25.1 in Teldrassil. However, quest marker appears in completely wrong place, much more to the west.

https://i.imgur.com/FbiKj02.png

### Expected Blizzlike Behaviour

Quest marker on map should appear where the mob is standing.

### Steps to reproduce the problem

1. Take quest Tears of the Moon (2518)
2. Go to spot indicated on map and see there is nothing there
3. Move further East to coords 48.1 , 25.1 and you will find Lady Sathrah there
4.

### Extra Notes

https://i.imgur.com/FbiKj02.png

https://wowgaming.altervista.org/aowow/?quest=2518
https://wowgaming.altervista.org/aowow/?npc=7319

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@cachocarne thanks for your report, this looks to be [1-19] and not [generic]

**Comment by Gadixsp** [comment]
I think in this case, there was a slight error where Blizzard's quest tracker wasn't working quite right. In retail she can spawn on either side of the river (as well as having some subtle movement instead of staying in one place), but the quest tracker only marks one spawn point instead of marking two possible areas like with many other quests.

https://tbc.wowhead.com/npc=7319/lady-sathrah

**Comment by Faq** [comment]
2 spawn locations what are pooled so she might be spawned in one or other place.
