### ISSUE TITLE
Toxic Tolerance - can't get poisoned

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1442]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Toxic Tolerance - can't get poisoned
![WoWScrnShot_081621_105837](https://user-images.githubusercontent.com/21084600/129531900-ad2481cd-3179-4119-8772-1243f61798f6.jpg)
![WoWScrnShot_081621_110136](https://user-images.githubusercontent.com/21084600/129531903-b710d519-65c8-4e67-9050-7c5d6e6cd69f.jpg)

### Expected Blizzlike Behaviour

poisoned
https://wowgaming.altervista.org/aowow/?quest=13850
https://www.wowhead.com/quest=13850/toxic-tolerance

### Steps to reproduce the problem

https://www.youtube.com/watch?v=z-Ao3p_Z7z0

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Mitradis** [comment]
I made many such attempts to get poisoned. I think these NPCs don't have this spell.
![WoWScrnShot_081621_112956](https://user-images.githubusercontent.com/21084600/129534757-b88a38f6-9aa2-4b72-9146-0d845d6b232c.jpg)

**Comment by syssneck** [comment]
You are attacking the wrong mobs. You need to attack Venomhide Ravasaurs. The normal Ravasaurs don't have the Venomhide Poison ability. Please read the quest text first.

**Comment by Mitradis** [comment]
@syssneck they are not there. I ran everywhere and did not find them.
