### ISSUE TITLE
Attack animation missing - NPC 1123 - Frostmane Headhunter

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1449]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

There are several Frostmane Headhunters in Dun Morogh, most of them (but not all) in a cave. When attacked, they stand far away and don't move at all, yet they are damaging our character and our HP goes down. The throwing animation is missing.

### Expected Blizzlike Behaviour

The "main" ability from these npcs is "Throw" and can also daze when they hit on melee. There should be an animation of them throwing axes when aggroed

### Source

https://classic.wowhead.com/npc=1123/frostmane-headhunter#abilities

### Steps to reproduce the problem

Approach or attack one of these Frostmane Headhunters.
Place yourself at enough range.
Watch them stand still and your health go down, although they apparently do nothing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 28a764641)
I get a throwing animation, as can be seen in the picture below.
![image](https://user-images.githubusercontent.com/53914190/129721206-00c39b14-0bea-49ff-9cb8-d8d014a09809.png)

**Comment by cachocarne** [comment]
Of course it might be a client-side problem. I actually noticed the same in other npcs, so maybe it's only on my version… Thanks a lot for checking it.

**Comment by Azcobu** [comment]
Yep, just checked these NPCs as well and they were working fine for me. As mentioned in the other ticket, deleting your cache folder (preferably after making a backup) and checking without any third-part texture/graphics mods you may have installed might be a good idea. Let us know if you have further problems.
