### ISSUE TITLE
Attack Animation missing - NPC 95 - Defias smuggler

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1450]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

There are many Defias Smugglers all over Westfall and particularly many of them in the north mine. When attacked, they stand far away and don't move at all, yet they are damaging our character and our HP goes down. The throwing animation is missing.

### Expected Blizzlike Behaviour

There should be an animation of them throwing when aggroed and attacked from distance.

### Source

https://vanillawowdb.com/?npc=95#abilities
https://classicdb.ch/?npc=95#abilities
https://classic-wow-archive.fandom.com/wiki/Defias_Smuggler

### Steps to reproduce the problem

Attack or aggro any of the Defias Smugglers from Westfall and stand at range so they don't Backstab  you or use melee attacks.
Watch them stand still and look at you while they don't move, yet our character gets damaged and our hp goes down

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Just had a look at these NPCS and they were animating correctly for me, so it appears you ran into a client side error of some kind. If you're using any third-party mods it may be worth checking without them, as well as deleting your cache folder. I'll close this for now, but if you continue to have problems, feel free to let us know.
