### ISSUE TITLE
I'm exalted with Timbermaw Hold but can't click them without attacking them

### ISSUE THREAD

**Issue by DarylBlake21** [chromiecraft/chromiecraft#1451]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

I was grinding to reach exalted with Timbermaw Hold. Every time I ranked up I could interact with them without any problem but once I logged out or left the zone (Felwood) I couldn't interact with them unless I ranked up again. I almost completed the exalted quest (The Root of All Evil), killed Xandivious and can't give Essence of Xandivious to complete the quest cause every time I click Gorn One Eye (Timbermaw Hold furbolg) I attack him.

### Expected Blizzlike Behaviour

I should interact with every furbolg on Timbermaw Hold without attacking, that includes buying and delivering quests.

### Steps to reproduce the problem

Rank up with Timbermaw Hold (honored, revered, exalted)
Log out from the game or leave the zone (Felwood)
Interact with them (click them)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
Check if you have At War ticked under their reputation by any chance.

**Comment by Stump876** [comment]
I'm going to assume this solved the problem and close this issue. If it does not please post here and we can repoen it.
