### ISSUE TITLE
Bingles Blastenheimer in Loch should give a quest

### ISSUE THREAD

**Issue by Junctionbe** [chromiecraft/chromiecraft#1458]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

This NPC https://classic.wowhead.com/npc=6577/bingles-blastenheimer should give a quest to the player, but he does not in game..

![image](https://user-images.githubusercontent.com/5745060/129887642-8dabf4fd-fd4f-418c-8922-4c013989c28b.png)

### Expected Blizzlike Behaviour

The NPC is giving a quest Missing Supplies (see Wow head for quest detail)

### Source

![image](https://user-images.githubusercontent.com/5745060/129887613-f7cf7f76-badb-4c14-8ea4-71cd8bc8e083.png)

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/5745060/129887695-e0f641d4-902b-4e54-ab5a-61ccf9c0e4e5.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
Did you take the quest Find Bingles https://wowgaming.altervista.org/aowow/?quest=2039 from Ironforge? That quest is the one which sends you to Bingles in Loch modan, and after you turn it in, you can accept the next one, which is the Missing Supplies.

**Comment by Azcobu** [comment]
Yep, it's a chain, and both TBC Wowhead and Wowpedia list "Find Bingles" as the previous quest in the series. Will close this accordingly.
