### ISSUE TITLE
[Item] [error on value] Staff of the Purifier (5613)

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1462]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Item Staff of the Purifier (https://classic.wowhead.com/item=5613/staff-of-the-purifier), reward of level 24 quest [ https://classic.wowhead.com/quest=973/the-tower-of-althalaxx ] is displaying a bugged price. Its current vendor value is 1 copper.

### Expected Blizzlike Behaviour

According to online databases, its vendor value is 26 silver 35 copper.

### Source

https://classic.wowhead.com/item=5613/staff-of-the-purifier
https://wowpedia.fandom.com/wiki/Staff_of_the_Purifier
https://wowwiki-archive.fandom.com/wiki/Staff_of_the_Purifier

### Steps to reproduce the problem

Complete the quest 973 and obtain the item.
![ 2021-08-19 at 09 27 40](https://user-images.githubusercontent.com/77953030/130018987-9176eccf-7c8d-4c7a-8bf3-073bf855c749.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, this is a known client issue, where for whatever reason, the sell price is 1 copper, but the actual price you get if you do sell is correct. Checked in game here:

Character with no money at all:
![WoWScrnShot_081921_200244](https://user-images.githubusercontent.com/81782124/130055038-067be6a6-78ed-450f-98d1-b0976096373d.jpg)

Staff sold, 26s 35c credited.
![WoWScrnShot_081921_200248](https://user-images.githubusercontent.com/81782124/130055098-d0b0c7a0-06e8-4bc3-a26d-cd551763c316.jpg)

It's bit of a nuisance as a bug, but it's display only, and sales do work properly. Unfortunately, as it's a client issue, we can't fix it. Closing this accordingly.
