### ISSUE TITLE
Warrior Charge swing timer pause problem

### ISSUE THREAD

**Issue by Jonsse** [chromiecraft/chromiecraft#1463]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Charging with warrior sometimes pauses the swing timer. First swing doesn't go through immediately. Instead does a double swing on the next one.

### Expected Blizzlike Behaviour

The first swing should go through straight away after the charge.

### Steps to reproduce the problem

https://i.imgur.com/tNEcziC.mp4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. This seems to be the same issue as https://github.com/azerothcore/azerothcore-wotlk/issues/7266, where charge was causing a pause in autoattacks, although I don't remember a double swing afterwards. Anyway, a fix for this has been completed and merged into AC, but hasn't yet made it to Chromie. (See https://github.com/azerothcore/azerothcore-wotlk/pull/7316).

**Comment by Jonsse** [comment]
Good to hear. The double swing seemed to happen sometimes, not very often. Mostly it's just no attack.

**Comment by Jonsse** [comment]
This still doesn't work, seems something was done as it doesn't skip first melee every time, but it still seems 50/50 at best.
