### ISSUE TITLE
Amnen Vale NPC are all neutral

### ISSUE THREAD

**Issue by KukacDambo** [chromiecraft/chromiecraft#1466]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When I play a Dranei, all NPC characters are neutral, including those that should attack you on sight, like the blood elves.
Every NPC stands by until I attack them.

### Expected Blizzlike Behaviour

Some enemies should attack players on sight, like the blood elves and some others.

### Steps to reproduce the problem

1. Create a Dranei character
2. Find the blood elves or any other NPC that should be hostile
3. If they are not hostile, the bug is there.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gadixsp** [comment]
I believe this was a change in wrath on retail, I suppose as a way of incentivizing people to roll new characters. I definitely remember that they switched from hostile to neutral at some point in retail and I think it was during wrath.

**Comment by gurveleg** [comment]
You are correct. All starting zone npcs were changed to neutral in Wotlk patch 3.3.0
https://wowpedia.fandom.com/wiki/Patch_3.3.0_(undocumented_changes)

**Comment by Azcobu** [comment]
Well, that seems to explain it, so will close this accordingly.
