### ISSUE TITLE
Deathmaw missing patrol

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1481]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Small loop around the spawn location

### Expected Blizzlike Behaviour

Larger loop around south west of Burning steppes

### Source

https://classic.wowhead.com/npc=10077/deathmaw

### Steps to reproduce the problem

Go to spawn location
Observe

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
![deathmaw](https://user-images.githubusercontent.com/80769357/130317536-c22d3c4d-c03b-4790-9b69-ca0692458b90.jpg)
How Large should the small area be?

**Comment by baranzadeoglu** [comment]
![image](https://user-images.githubusercontent.com/84640316/130318378-41557399-bf51-4ce0-b56c-aca2ac52cdd0.png)
This location was where I saw it.
I appeared that the loop it took was smaller than depicted here. I can't be exact as I don't have access to official classic servers atm.

**Comment by Gultask** [comment]
Vmangos, Cmangos and TrinityCore use the same wander distance of 20y as AzerothCore, so it should be fairly safe to say it's correct unless a sniff or a video provides otherwise.
