### ISSUE TITLE
Rich thorium vein wrong minimum number

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1485]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Rich thorium vein drops 1-5 thorium ore 1-7 dense stone

### Expected Blizzlike Behaviour

3-5 thorium ore, 4-7 dense stone

### Source

https://wotlkdb.com/?object=175404

https://wotlk.evowow.com/?object=175404

### Steps to reproduce the problem

find rich thorium vein
mine

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by baranzadeoglu** [comment]
fix below:

DELETE FROM `gameobject_loot_template` WHERE (`Entry` = 12883) AND (`Item` IN (10620, 12365));
INSERT INTO `gameobject_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(12883, 10620, 0, 100, 0, 1, 0, 3, 5, 'Rich Thorium Vein - Thorium Ore'),
(12883, 12365, 0, 50, 0, 1, 1, 4, 7, 'Rich Thorium Vein - Dense Stone');

**Comment by jamadaha** [comment]
Are those the correct drop rates tho? [Wowhead TBC](https://tbc.wowhead.com/object=175404/rich-thorium-vein) states 1 ore to 1-3 dense stone

**Comment by Gadixsp** [comment]
The TBC numbers are different because each node was able to be mined multiple times. In Wrath they changed to one collection per node and increased the drop rate accordingly.

**Comment by jamadaha** [comment]
Ah, okay.

**Comment by baranzadeoglu** [comment]
> Are those the correct drop rates tho? [Wowhead TBC](https://tbc.wowhead.com/object=175404/rich-thorium-vein) states 1 ore and 1-3 dense stone

It is I think a visual issue with the webpage. I played classic, rich thoriums would drop 2-4. Never 1.

**Comment by Stump876** [comment]
https://wowpedia.fandom.com/wiki/Thorium_Ore Small veins yield 1-3 ore. Rich veins yield 3-5. I can find no info on the amount of stone given.
