### ISSUE TITLE
[Hunter Skill] Multi-Shot has a casting time

### ISSUE THREAD

**Issue by rdallastra** [chromiecraft/chromiecraft#1487]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Multi-shot has a casting time (0.362s) when [according to DB](https://wotlkdb.com/?spell=2643) it should not. This makes it so hunters cannot cast it when running, for instance, and it's not Blizzlike behaviour
![Multi-shot Tooltip](https://user-images.githubusercontent.com/45319286/130324143-a6a487ff-5d1d-4082-b19d-53cb7f3a1af0.jpg)

### Expected Blizzlike Behaviour

Multi-Shot should be an instant cast skill.

### Source

https://wotlkdb.com/?spell=2643

### Steps to reproduce the problem

Says in the tooltip, but if you want to confirm, you could do this:

1. Be a hunter
2. Target a mob
3. Start running/walking and try to use multi-shot
4. It won't fire because it's not instant cast

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 7b343d008)
It does seem to have a cast time and can't be used while moving.

Tho, I'm uncertain whether this is incorrect behaviour. [Wowpeadia](https://wowpedia.fandom.com/wiki/Multi-Shot?oldid=1722276) has this written from 2008
![image](https://user-images.githubusercontent.com/53914190/130326355-8d71aff7-caf5-4b80-83cd-3983b88bbf8c.png)

**Comment by VFaleiro** [comment]
> Tho, I'm uncertain whether this is incorrect behaviour. [Wowpeadia](https://wowpedia.fandom.com/wiki/Multi-Shot?oldid=1722276) has this written from 2008

I'm certain it having a cast time is the correct behaviour.

The same text you posted can also be found in the Multi-Shot page on [WoWWiki (Web Archive - Sep 2010, after 3.3.5a and before Cata)](https://web.archive.org/web/20100901113448/http://www.wowwiki.com:80/Multi-Shot)
> -  Multi-Shot has always had a short cast time (even when it used to be labeled as an instant attack), and thus cannot be used while moving.

**Comment by slicplaya** [comment]
Multishot should NOT have any cast modifiers on it at all, and is .5 baseline without benefits from haste. This is how it should work.
