### ISSUE TITLE
NPC - Shapeshifted death

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#149]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

All content probably

##### SMALL DESCRIPTION:

When an NPC is shapeshifted and dies, his shapeshift aura is not removed before the death animation making him appear dead without the smoke immediatly.

Quest: [Druid of the claw](https://wotlkdb.com/?quest=2561)
NPC_Start: [Oben Rageclaw](https://wotlkdb.com/?npc=7317)
NPC_End: [Oben Rageclaw](https://wotlkdb.com/?npc=7317)

NPC: [Rageclaw](https://wotlkdb.com/?npc=7318)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After the druid dies on shapeshifted form, you can see the smoke around his corpse.
[youtube video](https://www.youtube.com/watch?v=191c5WniyYk&ab_channel=Bue)

##### CURRENT BEHAVIOUR:

On death, his corpse pops immediatly without any animation.

##### STEPS TO REPRODUCE THE PROBLEM:

Take quest Druid of the Claw
Kill Rageclaw when he's shapeshifted

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
Just tested in https://github.com/azerothcore/azerothcore-wotlk/commit/e59041ddb1fcbcfaec57cc0d24baf13b7e29efb1 (newer than chromie's version) and can't replicate this.

If some have the issue after an update I will triage this issue.
