### ISSUE TITLE
[Hunter] Glyph of Arcane Shot is not refunding mana when target is afflicted by Sting

### ISSUE THREAD

**Issue by rdallastra** [chromiecraft/chromiecraft#1490]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Hunter's [Arcane Shot](https://wotlkdb.com/?spell=3044) is not refunding mana while [Glyph of Arcane Shot](https://wotlkdb.com/?item=42898) is glyphed and target is affected by a Sting.

### Expected Blizzlike Behaviour

[Arcane Shot](https://wotlkdb.com/?spell=3044) should refund 20% of its cost if target is afflicted by a Sting (such as [Serpent Sting](https://wotlkdb.com/?spell=1978)) and [Glyph of Arcane Shot](https://wotlkdb.com/?item=42898) is glyphed.

### Source

![hunter log](https://user-images.githubusercontent.com/45319286/130326098-3b142f64-be57-47fa-b644-93a729c85c84.jpg)

### Steps to reproduce the problem

1. Glyph hunter with [Glyph of Arcane Shot](https://wotlkdb.com/?item=42898)
2. Fire a sting at target (such as [Serpent Sting](https://wotlkdb.com/?spell=1978), tested as well with Scorpid and Viper)
3. Fire [Arcane Shot](https://wotlkdb.com/?spell=3044) at target, check combat log and mana level

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report, but this is a duplicate issue https://github.com/chromiecraft/chromiecraft/issues/1020 This issue was just closed yesterday. So, I'm not sure if the fix is live just yet. If the issue persists, please post in the issue linked here, so the Dev knows.
