### ISSUE TITLE
[mage talent] Clearcasting frequency needs to be checked (at least with Blizzard spell)

### ISSUE THREAD

**Issue by ypoptos** [chromiecraft/chromiecraft#1502]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

![Clearcasting](https://user-images.githubusercontent.com/88951926/130338802-f4b82510-f034-4efa-98bb-1df9667dfb61.jpg)

The mage talent Arcane Concentration looks that procs Clearcasting all the time when you cast Blizzard spell. My mage can aoe casting Blizzard without wasting any mana. Other spells like Arcane Missiles looks also that procs Clearcasting over the described 10%.
My mage in dungeons has no mana problems by casting Blizzard and Arcane Missiles

### Expected Blizzlike Behaviour

Clearcasting procs less (I think)
See the first video and notice when you hear the sound. Everytime you hear it the Clearcasting procs. In the retail the Clearcasting was proced when you started the spell and not when you channel it. This is the reason it procs that often.

### Steps to reproduce the problem

Gather some mobs and cast Blizzard. Its better to have a tank because you cast without been hit

### Extra Notes

Example Video 1: https://youtu.be/-JRGW4P9g0c
Example Video 2: https://youtu.be/fpmenPU332k

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
In all pservers I've played -probably using TrinityCore- this was the usual behavior. Hitting so many mobs so many times would make it proc almost for sure, so it was possible to spam blizzard as long as there were enough targets alive. I think you need to find a reliable source to affirm it should be different, a "I think it should not be like this" is not enough for Devs. ;-)

**Comment by ypoptos** [comment]
> 
> 
> In all pservers I've played -probably using TrinityCore- this was the usual behavior. Hitting so many mobs so many times would make it proc almost for sure, so it was possible to spam blizzard as long as there were enough targets alive. I think you need to find a reliable source to affirm it should be different, a "I think it should not be like this" is not enough for Devs. ;-)

See the first video and notice when you hear the sound. Everytime you hear it the Clearcasting procs. In the retail the Clearcasting was proc when you started the spell and not when you channel it. This is the reason it procs that often. I will add it to my comments above. With this behavior a mage don't don't need to waste mana with aoe

**Comment by syssneck** [comment]
Currently, I'm much more interested in how you got the Netherweave Bags? They should not be obtainable in the current bracket.

**Comment by cachocarne** [comment]
I was replying but something went wrong. Anyway, here's what I wrote:

"Blizzards often proc clearcasting when allowed to run to their full duration, due to the large number of times Blizzard strikes and thus has a chance at proc'ing, which can sometimes mean that you can chain two, three, or even four Blizzards for no mana cost that all (combined with Arcane Potency) have a +15% crit chance."

https://wowpedia.fandom.com/wiki/Arcane_Concentration

**Comment by cachocarne** [comment]
Similar behavior happens with Arcane Missiles, since they HIT several times. This doesn't apply to dots from fireball, etc. It's part of the mechanics of the talent.

**Comment by ypoptos** [comment]
> 
> 
> I was replying but something went wrong. Anyway, here's what I wrote:
> 
> "Blizzards often proc clearcasting when allowed to run to their full duration, due to the large number of times Blizzard strikes and thus has a chance at proc'ing, which can sometimes mean that you can chain two, three, or even four Blizzards for no mana cost that all (combined with Arcane Potency) have a +15% crit chance."
> 
> https://wowpedia.fandom.com/wiki/Arcane_Concentration

Yes, but the telent tooltip says:
Gives you a 13/27/40% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.
Our tooltip says 10%
To be honest I like it as is. It makes my leveling easy. The same thing happens with Arcane Missale. They can proc Clearcasting with the 3rd hit and make this talent read good. But I don't remember this at retail. I could be wrong ofc

**Comment by Gadixsp** [comment]
I checked into some sources for you, expecting something like a hidden internal cooldown, but the [Wowwiki](https://wowwiki-archive.fandom.com/wiki/Arcane_Concentration) page describes the same behavior with Blizzard.

> Further, Blizzards often proc clearcasting when allowed to run to their full duration, due to the large number of times Blizzard strikes and thus has a chance at proc'ing, which can sometimes mean that you can chain two, three, or even four Blizzards for no mana cost that all

However it does confirm that Arcane Missiles should only have a chance to proc on hit, not on each tick.

> Unlike "on spell hit" effects, Arcane Concentration cannot proc off each hit of an Arcane Missiles' bolt, but only off the initial hit of AM itself.

**Comment by cachocarne** [comment]
It would make sense if it works on Blizzard or Flamestrike and not in other things. It's possible to walk under a Blizzard at middle cast and get damage. Same with Flamestrike. But other spells are just one cast. So I would say Clearcasting could proc during the channeling of these two.

**Comment by Azcobu** [comment]
I've been trying to find other sources for what correct behaviour should be here, and have found a number that claim Arcane Concentration should be give a flat 10% chance to proc when a mage spell damages an enemy. For example:

From a related emulator project: 

> Talent Arcane Concentration works incorrectly when combined with Blizzard, repeatedly proc. during one Blizzard cast (the frequency depends on the number of mobs under the blizzard).
How it should work:
Chance of proc. Arcane Concentration must be calculated on the activation of the Blizzard. ([Source](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/572))

From a vanilla Mage FAQ:

> How does Clearcasting work?											
> - This talent has a fixed 10% chance to proc as long as one mob is hit by one of your spells.												
> - Hitting multiple enemies will NOT increase your chance to get a proc.		
> - Yes, Clearcasting was """"""""""buffed"""""""""" on your private server.  ([Source](https://docs.google.com/spreadsheets/d/1uCXQni8Ndf0RuKfgNUlQ_jzfKIYmsCVuYXS_P3OaKUY/edit#gid=1879540205 ))

However, this quote comes from vanilla Classic, although I haven't found patch notes recording any changes between then and Wrath either.

Even from Reddit of all places has a discussion on the mechanics here: https://www.reddit.com/r/classicwow/comments/b478j2/arcane_concentration/

There's also more discussion at https://tbc.wowhead.com/spell=12577/arcane-concentration#comments with the usual varying claims, some saying it's a flat 10% chance on a hit, and thus Blizzard shouldn't proc it any more than any other spell, and others pparently disagreeing.

However, there is also that Wowwiki quote which says multiple Blizzards proccing Arcane Concentration 2, 3 or 4 times in a row isn't unusual, which does contradict most of the above. Wowwiki/Wowpedia is typically a good source, so I'm reluctant to dismiss it, but should note in this case that it's a player-edited site like any other, so can contain errors too. I dislike arguing from game design, but should also note the proc rate does feel much too high - i have video of Arcane Concentration proccing 5 times in about 8 seconds while testing this, which seems a bit silly.

**Comment by cachocarne** [comment]
off-topic, but very curious… how come you have Netherweave bags on your mage? I thought they were not available yet
