### ISSUE TITLE
[Reputation] Repetable quest "Gaining Acceptance" should no longer be available at Honored

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1503]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59

### Current Behaviour

The repetable quest "Gaining Acceptance" is available at 600/12000 honored.
![image](https://user-images.githubusercontent.com/22718174/130338819-9583ff8f-75bd-4828-b8a2-cb5d6b6264f9.png)

### Expected Blizzlike Behaviour

The repetable quest "Gaining Acceptance" should no longer be available once the player has hit 0/12000 honored.

### Source

https://wowpedia.fandom.com/wiki/Thorium_Brotherhood?oldid=2592601
It guides the player to get as far as they can into Honored (600/12000) only with Dark Iron Residue by going all the way up to 5975/6000 friendly with a combinaison of "Gaining Acceptance" and "Gaining Even More Acceptance".

Once Honored, it suggest to do a few quests (but the links are broken) since you would normally no longer be able to hand over Dark Iron Residue for some reputation.

https://classic.wowhead.com/quest=7737/gaining-acceptance
Classic WoWHead comments also suggest once at honored to hand-in materials that are far more complicated to obtain in order to progress.

### Steps to reproduce the problem

Hit honored with Thorium Brotherhood.
See that the repetable quest "Gaining Acceptance" is still available.

### Extra Notes

Dark Iron Residue: https://classic.wowhead.com/item=18945/dark-iron-residue

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
https://wowpedia.fandom.com/wiki/Thorium_Brotherhood

According to this, it was possible. I remember doing this long ago with Fiery cores and so on, but too blurry to remember if brackets worked as you suggest.

**Comment by gadaotada** [comment]
Yep I can confirm this is a bug as of WOTLK 3.3.5a patch. Here is some examples of it
