### ISSUE TITLE
[spell]100% got stuck in drinking red medicine and can not auto attack too

### ISSUE THREAD

**Issue by Fuchal** [chromiecraft/chromiecraft#1506]
### What client do you play on?

other

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

![image](https://user-images.githubusercontent.com/226239/130344348-9a034ac3-6b6e-40d7-9c07-a14956b82165.png)
![image](https://user-images.githubusercontent.com/226239/130344384-6191a288-33dd-4428-9eef-c81b2b937d77.png)
![image](https://user-images.githubusercontent.com/226239/130344411-6b6a7945-6ee0-4bf7-8834-f75d10d02b42.png)

1. almost get stuck in drinking red medicine, 100% get stuck!!!
2. it cant be auto attack any more but relogin, and i can also use spells
3. maybe because of i‘m Alchemist ,  other role never got suck 

### Expected Blizzlike Behaviour

1. let me drink normal
2. let me auto attack

### Steps to reproduce the problem

100% get stuck!!!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. This is a known issue - see #386, https://github.com/chromiecraft/chromiecraft/issues/1350 and azerothcore/azerothcore-wotlk#5263. Note the troll's blood potion, which is linked to all these issues, and which is shown in your screenshot as well. Closing this as a duplicate accordingly.
