### ISSUE TITLE
bug(DB/SAI): Webwood lurker doesn't cast poison

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#151]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Webwood Lurker doesn't cast poison.

NPC: [Webwood Lurker](https://wotlkdb.com/?npc=1998#abilities)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Acording to several databases, It should be casting the poison ability.

##### CURRENT BEHAVIOUR:

Not casting any abilities

##### STEPS TO REPRODUCE THE PROBLEM:

Fight any Webwood Lurker in Teldrassil.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/110209313-0fc4a980-7e8c-11eb-871e-272a99ef7899.png)
Can not replicate.
