### ISSUE TITLE
Grik'nir the Cold and all nearby moobs are neutral and they should be aggressive 

### ISSUE THREAD

**Issue by evillalo985** [chromiecraft/chromiecraft#1516]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Grik'nir the Cold and all nearby trolls moobs inside the Coldridge valley cave are neutral and they should be aggressive.

![image](https://user-images.githubusercontent.com/43247811/130524516-d49caaa8-a227-4520-a775-91abd801829d.png)

### Expected Blizzlike Behaviour

According to the wowhead information, all the moobs from the cavern should be aggressive.

https://www.wowhead.com/npc=808/griknir-the-cold

![image](https://user-images.githubusercontent.com/43247811/130524560-5ce3ee8e-bdc5-4221-89b3-4e61a8eecd0e.png)

### Steps to reproduce the problem

1. Create a Dwarf or Gnome.
2. Go to the ColdRidge cave:

![image](https://user-images.githubusercontent.com/43247811/130524854-a8ed0bb5-71e7-4189-a0c0-5795beeaede2.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report!
Tested on local server(AC bbc071aa5)
Yep, they do seem to be passive, to both sides in fact. Also found a [video](https://www.youtube.com/watch?v=-9V0GjuT27Q) from 2008 showing that they are supposed to be aggressive.
