### ISSUE TITLE
Wool cloth price bug

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#152]
ISSUE: FACTION SIDE:
Alliance
CONTENT PHASE:
Any
SMALL DESCRIPTION:
Wool cloth auction bug
proof: https://www.youtube.com/watch?v=18DE3s6qZZY&feature=youtu.be
EXPECTED BLIZZLIKE BEHAVIOUR:
Wool cloth should be sold with the price you choose
CURRENT BEHAVIOUR:
My wool cloth price after puttin into acution was 5x bigger than the one I chose to put.
STEPS TO REPRODUCE THE PROBLEM:
Sell wool cloth in auction with a price and see it rise higher.

Step 1
Step 2
Step 3
AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@c2f274e
OPERATING SYSTEM:

Ubuntu 20.04
MODULES:

    mod-cfbg
    mod-duel-reset
    mod-desertion-warnings
    mod-ah-bot

OTHER CUSTOMIZATIONS:

None.
SERVER:ChromieCraft

ChromieCraft

**Comment by illfated** [comment]
@Narixel : I wish you could have kept the issue ticket formatting, because when you remove the formatting, you make it harder for us others to read and thereby make it harder for us to get interested in troubleshooting the issue you want to tell us about.

**Comment by nicoaravena** [comment]
Did you use the price Per stack or Per Item? I try every way, different stacks quantity, item per stack quantity and nothing wrong happens.
