### ISSUE TITLE
Obscure Mounting Bug

### ISSUE THREAD

**Issue by luhacky** [chromiecraft/chromiecraft#1521]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Mounting inside major cities (IF, SW, Darn) leads to an immediate dismount.
Occasionally allows normal mounting (on very specific spots on some ledges).
Mounting outside of the city works without a problem.
See attached video for an example.
Did try without addons & on another machine to no avail.

https://user-images.githubusercontent.com/88512346/130659007-a356f795-2c63-4fdf-abe3-04c8be96bcd0.mp4

### Expected Blizzlike Behaviour

Should mount inside major cities.

### Steps to reproduce the problem

This seems to be unique to this character. I did not have this problem with any other character. 

### Extra Notes

Charactername: Gnomess.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

WoD models client.

### Server

ChromieCraft

**Comment by cachocarne** [comment]
The interesting thing is that you get to see the Mechanostrider mount buff on you before you dismount. It's almost like you had something cancelling the aura. If it wasn't because you are using mount directly from Pets/Mounts tab I would think you have a wrong macro. Did you try with any other classes/races/mounts?

**Comment by luhacky** [comment]
It works with other characters and mounts. I did buy a second mechanostrider on that character, that didn't help. 
I am curious about the situation at level 40.

**Comment by jamadaha** [comment]
Thanks for the report!
Tested on local server(AC 731dec37a)
First tried mounting a kodo as an orc in the first spot shown: it worked. Then tried mounting a Blue Mechanostrider as a human in that spot, which also worked. Then tried as a female gnome to mount a Blue Mechanostrider in both spots, which again worked.
So I'll wait for more feedback.

**Comment by luhacky** [comment]
This also did not work with an Unpainted Mechanostrider. When mounting outside of a major city (or when it randomly works inside of it) it works until I teleport in some way (Hearthstone, Mage-Teleports, RDF). From then on it will instantly dismount again.

**Comment by luhacky** [comment]
Trying out a non-WoD-client did the trick.
