### ISSUE TITLE
[QUEST] Satyr Slaying! - NPCs pets do not attack the player.

### ISSUE THREAD

**Issue by TheRiddermark** [chromiecraft/chromiecraft#1528]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

While doing the quest [Satyr Slaying!](https://wowgaming.altervista.org/aowow/?quest=1032) I've noticed that certain Satyr NPCs' pets do not attack me at all. The NPC in question is [Bleakheart Hellcaller](https://wowgaming.altervista.org/aowow/?npc=3771) who has an IMP or Voidwalker minion.

Below is a video of me fighting both variations and you can clearly see the pets do not engage me. If I move around they follow but do not attack. [[VIDEO]](https://www.youtube.com/watch?v=Zy45e5pVMhk)

I have also noticed in the video I have attached in "expected behaviour" that the summoned imp/voidwalker does not despawn when you kill its master. Currently on the server they do - but that might be something to do with classic vs wotlk, not sure.

### Expected Blizzlike Behaviour

Pets should attack. Check the video of the quest I found [here](https://youtu.be/E7YANN1B0Z4?t=375). (linked exact moment of interaction with pets)

### Steps to reproduce the problem

Go to the zone and attack the NPC in question (not the minions).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report!
Not quite sure about this one.
I found some cases where the minion does nothing, but other times when they attack, as seen below.
![image](https://user-images.githubusercontent.com/53914190/130780674-cf85351b-dbb8-451f-8418-15e09205c803.png)
No attack:
![image](https://user-images.githubusercontent.com/53914190/130781017-d274b9e5-857d-4f15-84bb-044148f7b31e.png)

I'd say it's a bug, as even that occurring rarely is still wrong, but I'll wait for more feedback.

**Comment by Azcobu** [comment]
This is an instance of a known issue with NPC warlock pets not attacking properly - see https://github.com/azerothcore/azerothcore-wotlk/issues/6239 and for a specific CC instance, https://github.com/chromiecraft/chromiecraft/issues/862, so will close this as we already have an open ticket for this.
