### ISSUE TITLE
Add in the "The Absent Minded Prospector" quest don't attack.

### ISSUE THREAD

**Issue by chromier** [chromiecraft/chromiecraft#1536]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Doing this escort quest some trogg adds spawn and just stay there standing and doing nothing.

### Expected Blizzlike Behaviour

Adds should attack the escorted dude after they spawn.

### Source

![WoWScrnShot_080721_180214](https://user-images.githubusercontent.com/89538610/130845650-ea3fae32-a9ae-4a00-bbfc-483cebe9327c.jpg)

### Steps to reproduce the problem

1. Start the escort quest
2. Wait for the troggs to spawn

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
I just did this myself on CC and I had no issues. 
![image](https://user-images.githubusercontent.com/68164076/131230111-5207e5aa-f790-4ad6-bb67-e8e17d266f7a.png)
![image](https://user-images.githubusercontent.com/68164076/131230135-4d7fd113-54c7-49b9-89ea-cef4915de00e.png)
I'm going to close this for now. If anyone has issues with it later it can be revisited.
