### ISSUE TITLE
[Achievement] Obtaining Onyx Panther does not reward Feat of Strength

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1541]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Obtaining and Learning Onyx panther (https://wowgaming.altervista.org/aowow/?item=48527) does not reward Onyx Panther Feat of Strength (https://wowgaming.altervista.org/aowow/?achievement=3896)

### Expected Blizzlike Behaviour

Player should recieve the Feat of Strength when learning Onyx Panther.

### Source

https://www.wowhead.com/achievement=3896/onyx-panther
https://wowwiki-archive.fandom.com/wiki/Onyx_Panther_(achievement)

https://wowgaming.altervista.org/aowow/?achievement=3896

### Steps to reproduce the problem

1. Add https://wowgaming.altervista.org/aowow/?item=48527 and learn it
2. See you don't get achivement

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
On CC test realm also nothing

![image](https://user-images.githubusercontent.com/85256266/142501018-54cb8120-952f-4af3-906c-5d542c659044.png)

**Comment by Lynethris** [comment]
This happen to me today. But I don't really think that it's a "bug". This achievement is specific to korean server. So maybe the config for the classic realm block it.

Source: https://wowwiki-archive.fandom.com/wiki/Onyx_Panther_(achievement)

**Comment by heyitsbench** [comment]
This also happened to me on my character on CC recently, bought from the rewards catalogue.
