### ISSUE TITLE
[Warrior ability] [Victory Rush] usable past 20 seconds if last killing shot was done with Victory Rush

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1542]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Warrior skill: After obtaining a kill that yields XP or Honor, we are able to use [Victory Rush](https://wotlkdb.com/?spell=34428) for only the next 20 seconds.
However, sometimes it is possible to use Victory Rush even after these 20 seconds have passed. This bug happens occasionally and is hard to reproduce, it requires that our last VR was actually a killing strike.

### Expected Blizzlike Behaviour

The XP/Honor killing shot applies an invisible aura called [Victorious](https://tbc.wowhead.com/spell=32216/victorious) that has a duration of 20 seconds.
Although invisible, it is possible to track VR and the aura with WeakAuras. I was surprised to see that sometimes my WA icon will remain on screen well past 20 seconds, only to realise that I could actually open combat on an enemy by using Victory Rush.

**UPDATE: Hidden Aura remains on player EVEN AFTER DEATH. I gained the bugged buff, then died, recovered my body and STILL I could use VR on first mob I encountered.**

### Steps to reproduce the problem

Get a lvl 10 Warrior with Victory Rush
Get a XP-Honor killing shot and gain Victorious (hidden aura).
Fight another enemy and try to deal the **killing shot with the available Victory Rush**
Wait 20 seconds for it to pass
Engage another enemy and use Victory Rush, since the aura is still up when it should have faded.

On image 1 you can see how I keep track of Victory Rush both with a 20 scs timer (under player frame) and with icon in mid screen. On combat log you can see I killed my last enemy with VR (80 overkill)
![image 1](https://user-images.githubusercontent.com/77953030/130944179-c0625bfc-8482-4bcc-9620-849e5ac31e01.png)

On image 2 you can see I waited some time, used Bloodrage, refreshed my Shout and around 1 minute has passed. However, I engage with new enemy and hit it with Victory Rush for 48 physical.
![image 2](https://user-images.githubusercontent.com/77953030/130944463-3a7f6045-51eb-4b07-8f00-c151a6535bb4.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 8388578ce)
As this is still an issue, I confirmed both cases on local server, it is safe to say it is not directly related to the mentioned issue.

**Comment by cachocarne** [comment]
Any updates on this? I don't want to be annoying, but I think Class abilities/skills should be high priority, over any items or quests.

**Comment by jamadaha** [comment]
@cachocarne There doesn't seem to any fix yet, and no one seems to be working on it. I can up the priority, but it doesn't seem to be game breaking.
In any case, it will only be fixed when someone feels like fixing it.
