### ISSUE TITLE
Renewed hope

### ISSUE THREAD

**Issue by magixlol** [chromiecraft/chromiecraft#1552]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

shielding while disc/renewed hope specced puts you in combat if you arent in combat. example: if im at bg ally entrance and a team member is at horde entrance, when i shield, it should procc renewed hope on everyone but not put me in combat if im not in combat. 

### Expected Blizzlike Behaviour

shouldnt put priest in combat if priest isnt in combat himself. self explanatory. ofc some guy will be in combat, making it impossible for me to leave combat most of the bg 

### Steps to reproduce the problem

specc disc
specc renewed hope
pw: shield urself while any team member while beeing miles away in combat also puts u in combat 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
How can you shield an ally at the horde entrance, if you are at the ally entrance? Sorry, I don't understand your example.
Does someone know, or have a source, how that is supposed to work?

**Comment by magixlol** [comment]
on the "steps to reproduce" section i explained. you shield urself or someone near you. the point is, the buff proccs on everyone, and if a player is in combat it puts you automatically in combat even if u are 1 mile away. https://wowpedia.fandom.com/wiki/Renewed_Hope_(priest_talent)

**Comment by magixlol** [comment]
if u dont fix, i can never be sapped in arena lol. i will just shield myself while my partner is in combat with other guy. i actually dont mind if u dont fix tbh ahah
