### ISSUE TITLE
mageroyal drops from anvilrage enforcer

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1555]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

mageroyal drops from anvilrage enforcer

Couldn't find it on Keria3 suprisingly...
![image](https://user-images.githubusercontent.com/84640316/131033017-9291de1e-a88d-4aee-a946-95e25c75e3f9.png)

### Expected Blizzlike Behaviour

it shouldn't drop.

### Source

https://tbc.wowhead.com/npc=24819/anvilrage-enforcer

### Steps to reproduce the problem

Slain anvilrage enforcers (a lot of them)
observe

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Is this related to https://github.com/chromiecraft/chromiecraft/issues/1560? Can we close this?

**Comment by baranzadeoglu** [comment]
> Is this related to #1560? Can we close this?

don't think it is. Not too good with sql but as far as I can see mageroyal actually does not appear in the loot table for this mob. That is why I think it might be an overarching issue. 

Below is the mobs I get (ordered by min level enforcers should be 49 min) with the query below it
![image](https://user-images.githubusercontent.com/84640316/131264732-da0a26fe-2ab1-42ea-a9dc-8e0dd9a847b2.png)

select creature_template.name, creature_template.minlevel , creature_loot_template.entry, creature_loot_template.chance, creature_template.faction from creature_loot_template join creature_template on creature_loot_template.Entry=creature_template.entry where creature_loot_template.item="785" and creature_template.faction!="91" order by creature_template.minlevel ;

**Comment by baranzadeoglu** [comment]
> Is this related to #1560? Can we close this?

yes. My previous answer was wrong. Probably I killed a taskmaster and thought I killed an enforcer....
