### ISSUE TITLE
[Paladin] [Talent] Improved Blessing of Might not showing up properly.

### ISSUE THREAD

**Issue by Jogi-Pala** [chromiecraft/chromiecraft#156]
##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Jogi-Pala** [comment]
it didnt save the stuff in between the lines but basically title.

**Comment by JamesGent** [comment]
Unfortunately this is a client issue, there's nothing AzerothCore can do on their end to fix this. :(
