### ISSUE TITLE
[Rogue] Enemy stealth detection is too far

### ISSUE THREAD

**Issue by swishahendrix** [chromiecraft/chromiecraft#1566]
I feel like mobs my same level can detect me in stealth from too far away, it’s difficult to get around mobs without being attacked.

**Comment by cachocarne** [comment]
You need to complete your post with some proof or sources to make your claim, a "feels like" won't be enough to get any DEV's attention into it. Do an effort, a bit of work or your post will get closed.
In any case, there are talents to make your stealth better for a reason.

**Comment by Azcobu** [comment]
Please don't delete the reporting template, it's there for a reason. 

@cachocarne is correct, we would like to see some hard evidence or sources for any claim that behaviour on the server is not Blizz-like. You're generally looking at sources like Wowhead, Wowpedia or Youtube to try to prove what you're saying. Come back with some evidence that things are not working the way they should, and we can look into it. Until then, closing this issue.
