### ISSUE TITLE
Missing Quest: Supplies to Tannok

### ISSUE THREAD

**Issue by CameronWoof** [chromiecraft/chromiecraft#157]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Quest: [Supplies to Tannok](https://wotlkdb.com/?quest=2160)
NPC_Start: [Hands Springsprocket](https://wotlkdb.com/?npc=6782)
NPC_End: [Tannok Frosthammer](https://wotlkdb.com/?npc=6806)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Hands should offer the quest.

##### CURRENT BEHAVIOUR:

He does not.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Finish the starting zone at or around level 5.
Step 2: Go to Hands, do not receive quest.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
Just go as a level 3 gnome and then in my test env with a dwarf lvl 5 and both can receive the quest.
![imagen](https://user-images.githubusercontent.com/4155059/110404970-9a5d0280-805e-11eb-9a73-c76d5319ef2b.png)
