### ISSUE TITLE
[Ghostlands] Pathing Issues for mobs inside Deatholme Ziggurat

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1572]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

WHen you enter a ziggurat and aggro the mobs inside (Deatholme Necromancers and their minions), if you try to avoid LOS on Necromancers they will run around and clip through the Ziggurat walls and go inside it.

![daw](https://user-images.githubusercontent.com/80769357/131223126-6fee0bd3-8245-4ebd-80f6-34b0bd8b79fe.jpg)
![dgdgd](https://user-images.githubusercontent.com/80769357/131223129-4a5d20bb-c5c3-475d-898a-e6773e3ac1e8.jpg)

### Expected Blizzlike Behaviour

Mobs should not go under/inside structures.

### Source

This is not controversial.

### Steps to reproduce the problem

1. Teleport to Deatholme Ziggurat, GUID 82874 for example
2. Aggro the mobs inside and move around the ziggurat a bit so that you go out of LOS of Necromancers, they will try try to get into your los and will clip through Ziggurat walls
3. See that some mobs go inside the Ziggurat structure/possibly aggro other mobs outside

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Duplicate https://github.com/azerothcore/azerothcore-wotlk/issues/5796
