### ISSUE TITLE
Boss Tho'grun thrashes way too often

### ISSUE THREAD

**Issue by YunataSavior** [chromiecraft/chromiecraft#1576]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Boss Tho'grun thrashes literally every melee attack, causing him to burst you down VERY FAST.

### Expected Blizzlike Behaviour

He should be thrashing way less often.

### Source

https://tbc.wowhead.com/spell=12787/thrash
https://tbc.wowhead.com/spell=3417/thrash
https://tbc.wowhead.com/spell=8876/thrash

Look at "Aura proc chance" and "4s cooldown".

1. It seems that "Aura proc chance" is 100%, and the cooldown is non-existent.
2. I don't even know if Boss Tho'grun is supposed to Thrash anyway.

### Steps to reproduce the problem

1. Go to Badlands, search for Boss Tho'grun, then let him melee you. Look at "What happened to me".

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report!
This seems to be a common issue at the moment. This specific mob, has already been mentioned before [here](https://github.com/azerothcore/azerothcore-wotlk/issues/6118). So I'll close this as a known issue.
