### ISSUE TITLE
Northshire Valley empty of mobs, besides Wolves & Critters, and missing some NPCs

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#1589]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I had spent some time personalizing my interface options and keybinds from the escape menu, and I saw other players questing & spoke with them. I exited & re-opened the game a few times to ensure that my changes would stick upon logout.

However, once I started to quest, I could not see or interact with any Kobolds or Defias, although very rarely I saw Kobold text, such as, "You no take candle!" Milly Osworth was missing, although I had a quest to speak to her, and so were some of the Northshire Peasants.

I enabled PvP to lure what I expected was a Horde rogue, but nothing changed. I asked other players, and they saw the Kobolds & completed the Defias quest, even as I sat there.

I created another Human character & logged into it, only to find the Kobolds & Defias & Milly Osworth & Northshire Peasants again visible, so I logged onto my first character, and now I can see & interact with them.

### Expected Blizzlike Behaviour

The mobs & NPCs were visible & able to be interacted with, as other players did even as I sat there.

### Steps to reproduce the problem

1. Login
2. Create human character
3. Fiddle with interface options & keybinds, logging out occasionally
4. (potentially unnecessary) Complete quest to collect 8 wolf pelts
5. search for Kobolds & Defias

### Extra Notes

I'm not sure about the modules section below.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ntrna** [comment]
*IMPORTANT* At the time I think I was playing thru a VPN, and not on enUS. The info posted by AC/ChromieCraft in the chat pane upon login was different. I will login with a VPN again to confirm.

Also, there were no Kobold/Defias corpses.

**Comment by Gadixsp** [comment]
This happens to me as well in the draenei starting zone after creating a character. It seems to be misapplying the phased zone feature that Wrath introduced for Northrend zones. It always seems to correct itself after relogging.

**Comment by syssneck** [comment]
As you said, you were able to see everything after relogging and on your other char. 
This problem is completely client-side and can't be fixed from the server perspective. Your best bet to solve this issue is:
- deactivate all addons
- /reload
- close the game, delete everything inside the Cache folder and restart
