### ISSUE TITLE
NPC Paths through wall when LoS pulling

### ISSUE THREAD

**Issue by NachtRitter84** [chromiecraft/chromiecraft#1596]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Pulled https://wowgaming.altervista.org/aowow/?npc=16317 and ran around a corner to Line of Sight. The NPC pathed through the wall of the building, aggroing everything inside the building(which it was running away from when it pathed through the wall), and ran around to the entryway(behind me) in order to attack.

### Expected Blizzlike Behaviour

Expected blizzlike behavior would be that the mob doesn't path through the wall but stays within the bounds of existing terrain when line of sight pulling :)

### Steps to reproduce the problem

Target mob
Pull with hand of reckoning
Step back through door way and to the side of it, blocking NPC sight of you
Watch the mob

### Extra Notes

The mob didn't come at first so I stepped further back, which is when I saw it running around the outside of the building to me after pathing through the wall.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Win 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

Shadowed Unit Frames
Pally Power

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. These ziggurats are bit of a problem right now, and we have active issues for all of them including Deatholme - see https://github.com/azerothcore/azerothcore-wotlk/issues/5796. As such, closing this as a known issue.
