### ISSUE TITLE
Missing plaques in the Royal Gallery of Stormind Keep

### ISSUE THREAD

**Issue by Lomsikka** [chromiecraft/chromiecraft#1597]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

In the Royal Gallery of Stormwind Keep each statue of the Alliance Heroes should have its own plaque to click and read. But only 2 of them are available and one of them is rotated and facing backwards. I know this is the most minor bug you can find but it is a bug nonetheless.

### Expected Blizzlike Behaviour

Each statue should have its own usable (readable) plaque and facing correctly.

### Steps to reproduce the problem

I'm sorry but I have no idea what any of this means.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC a69be39fc)
![image](https://user-images.githubusercontent.com/53914190/131650040-39938de2-349f-47c6-9789-6a14c9b8a14a.png)
As seen in [wowpedia](https://wowpedia.fandom.com/wiki/Royal_Gallery?oldid=869948&file=Royal_Gallery.jpg) there should be atleast 3 plagues, they should also be flat. 
![image](https://user-images.githubusercontent.com/53914190/131649707-9e29237c-f760-4324-8bc3-0433cd63e2f0.png)

I can not find the missing plague information anywhere.

**Comment by Lomsikka** [comment]
Thank you for your work! I haven't visited the gallery in Classic or Retail, so I don't know how many plaqures there's supposed to be. But nonetheless, thank you.

**Comment by VFaleiro** [comment]
> I can not find the missing plague information anywhere.

I think only 3 statues are labeled
[Lady Mara Fordragon](https://wowpedia.fandom.com/wiki/Lady_Mara_Fordragon?direction=prev&oldid=2776151)
`unlabeled statues identical to those of Archmage Khadgar and Ranger Captain Alleria Windrunner are also present`
Also, the description of Mara Fordragon's statue is also there.

By the way, I've found the following objects on Wowhead
[Mara's plaque](https://tbc.wowhead.com/object=177202/lady-mara-fordragon)
[Daelin's plaque](https://tbc.wowhead.com/object=177201/grand-admiral-daelin-proudmoore#screenshots)
[Llane's plaque](https://tbc.wowhead.com/object=177200/king-llane-i-of-the-house-of-wrynn)

**Comment by jamadaha** [comment]
@VFaleiro Thanks for the information! 
I've added it to the linked issue.
