### ISSUE TITLE
The Unwritten Prophecy in Blood Watch--minor minor bug

### ISSUE THREAD

**Issue by Janeliu2** [chromiecraft/chromiecraft#1599]
After turning in the quest "Ending Their World" Velen appears at the end of the path down from the hut with a yellow question mark over his head. Clicking on him offers rewards which are accepted. However the yellow question mark does not disappear (meaning the quest is complete) and it stays until he despawns. 

Totally minor bug but it bugged me (sorry for the pun)

**Comment by VFaleiro** [comment]
All quests that have only the turn in part (the ones that come easiest to mind are the cloth turn-ins for reputation in major cities) behave like that. I'm not sure if it's possible to make a list of these quests (or if that's even needed).

**Comment by Stump876** [comment]
Hello @Janeliu2 Thanks for the report. However you bypassed the template. Can you please recreate this report using the template please? It will pop up when clicking the `Get started` button. 
![image](https://user-images.githubusercontent.com/68164076/132280397-b355c7af-bbea-4bc5-ac0e-8e1a1e12bc5c.png)
It contains information that will help out triage team, and the Devs if it gets verified and moved to AC. Thanks.
