### ISSUE TITLE
Dun Morogh: Crag Boar drops are incorrect

### ISSUE THREAD

**Issue by CameronWoof** [chromiecraft/chromiecraft#160]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

NPC: [Crag Boar](https://classic.wowhead.com/npc=1125/crag-boar)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Crag Boars should drop *no more than* one [Crag Boar Rib](https://classic.wowhead.com/item=2886/crag-boar-rib) or [Chunk of Boar Meat](https://classic.wowhead.com/item=769/chunk-of-boar-meat) at a time. 

##### CURRENT BEHAVIOUR:

They drop up to three of each per boar, which is way too much meat for any random low-level animal to drop. 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Kill and loot a few Crag Boars.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
CLOSED
-
**This is not a Bug, these are our rates.**
**Video:** [Crag Boar drops](https://youtu.be/gsXZuEWEFXM)
