### ISSUE TITLE
Quest: Rescue OOX-09/HL

### ISSUE THREAD

**Issue by Sirileja** [chromiecraft/chromiecraft#1600]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

The Quest [Rescue OOX-09/HL](https://wowgaming.altervista.org/aowow/?quest=836) in the Hinterlands triggers an infinite spawner of Owlbeasts at the first Ambush.   You get ambushed normally by a pair of 3 "Marauding Owlbeast",  but as this bug occured, there were endless waves of those Owlbeasts.  As soon we killed them, the "Homing Robot OOX-09/HL" ran back to his last place and triggered instantly another wave of those.  What is also to mention, that there stood 6 of those Owlbeasts, as we came to that spot + those which spawned due to the event.

We managed to do ~8 waves of them, before we finally tricked the event by luring them away, so that the Homing Robot OOX-09/HL could pass the trigger spot, without triggering them again.

It should be near the coordinates  42/51 ;  Time was around 22:20 Server Time, 01. September;   Involved were Valery (Myself) and Barzee.    Unfortunately I couldn't make a Screenshot, as I was too busy healing and also didn't thought about that in this moment.

### Expected Blizzlike Behaviour

There should spawn only one wave of the Marauding Owlbeasts.

### Steps to reproduce the problem

1. Get the [OOX-09/HL Distress Beacon](https://wowgaming.altervista.org/aowow/?item=8704) Itemid = 8704
2. Get to the Homing Robot OOX-09/HL  ;  Coordinates: 49/37, The Hinterlands
3. Escort the Homing Robot OOX-09/HL till to the first ambush of Owlbeasts on the road between 38/55 and 52/44 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Thank you for the report! 
We are aware of the problem, see here:
https://github.com/chromiecraft/chromiecraft/issues/1096
https://github.com/azerothcore/azerothcore-wotlk/issues/6738
