### ISSUE TITLE
[Quest] (10) Flight to Auberdine - Error on race requirement

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1601]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

https://classic.wowhead.com/quest=6342/flight-to-auberdine
On details it shows that this is a race quest for Night Elves. Later I found out that the whole questline starting with npc 4241 shoudn't even be available to any other races.

This quest is a follow up to "[The Bounty of Teldrassil](https://wotlkdb.com/?quest=6341)". We are required to talk with the flight master at Rut'theran village and purchase a hippogryph trip to Auberdine.

- When doing this quest as Night Elf, we can simply talk to the flight master and get a flight to Auberdine for free and even if we haven't been there before.
- We can also get this quest as a different race, but in that case, we will not be able to fly to Auberdine (not even paying) unless we have visited the harbor before. We can instead take the boat and turn in the quest when we arrive.

The quest was later removed and changed for another one. There are some old comments on Wowhead which state: "(Patch 3.0.1) This is part 3 of the Night Elf flight quests. Other races are not eligible."

### Expected Blizzlike Behaviour

Would be good to review the requirements for this quest and find out if:

a) is it only for Night Elves or for all Alliance races?
b) if it's available to other races, should the flight to Auberdine be available even if we don't know the FP at that town?
c) if the flight to Auberdine is possible, should it be free of cost?

### Source

https://wotlkdb.com/?quest=6342
https://classic.wowhead.com/quest=6342/flight-to-auberdine
https://www.youtube.com/watch?v=7hr7D4l3tIE

### Steps to reproduce the problem

Get an Alliance character at lvl 10 (Night Elf and non-Night Elf)
Get quest 6342
Talk to npc Vesprystus (3838)
Wait for flight map to appear (or not)

![ 2021-09-02 at 12 47 24](https://user-images.githubusercontent.com/77953030/131822638-f925087f-78eb-40b4-8a46-349e2efa06dd.png)
![ 2021-09-02 at 12 47 38](https://user-images.githubusercontent.com/77953030/131822672-0fb89c7d-5fe7-4506-91c5-0e227850d273.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gadixsp** [comment]
I can confirm that it's doable as a Draenei as well. In addition I was able to do the human equivalent in Westfall. I haven't done the Dwarf zones yet but I suspect an equivalent racial quest might have the same issue.

**Comment by Azcobu** [comment]
Thanks for the report, confirmed on a non-nelf character and will post to AC shortly. For your other queries:

a) [TBC Wowhead](https://tbc.wowhead.com/quest=6342/flight-to-auberdine) and [Wowpedia](https://wowpedia.fandom.com/wiki/Flight_to_Auberdine?oldid=2178485) both have this race flagged as night elf-only. 
b) Not applicable, as the quest shouldn't be available to other races.
c) I think it probably should be free, as the other similar flights are, but haven't found a definitive source saying so yet.
