### ISSUE TITLE
Killed at the Winterfall Village cave and respawn at Alterac Valley

### ISSUE THREAD

**Issue by DarylBlake21** [chromiecraft/chromiecraft#1605]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

I've been at the Winterfall Village a few times and this happened to me 4-6 times. Whenever I got killed inside the High Chief Winterfall cave while I was doing The Root of all Evil (https://classic.wowhead.com/quest=8481/the-root-of-all-evil), my spirit ended up at Alterac Valley, and whenever I tried to respawn paying for resurrection sickness, I ended up killed again by Horde NPC's.  The other day I went there again to farm Winterfall Firewater from the High Chief Winterfall cause the drop rate is high but I got killed after I farmed 6-8 of him. To my surprise, i ended up back at the Alterac Valley.

### Expected Blizzlike Behaviour

When I get killed at the Winterfall village cave, my spirit should appear at Winterspring, not at the other side of the world (Alterac Mountains).

### Steps to reproduce the problem

1. Go to the High Chief Winterfall cave at the top of the Winterfall Village on Winterspring
2. Get killed inside the cave, not outside nor the entrance
Optional (for resurrection bug)
3. Pay for resurrection sickness to respawn at the Horde Alterac Valley side and get killed again (and pay again for double respawn sickness). 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, this is a known issue for which we currently have an open ticket - see https://github.com/azerothcore/azerothcore-wotlk/issues/7014. Closing this as a duplicate accordingly.
