### ISSUE TITLE
Orc female stuck on stairs

### ISSUE THREAD

**Issue by Peebspam** [chromiecraft/chromiecraft#1606]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Orc female character model runs into an inviswall when trying to walk up stairs. Happens in multiple locations. Examples include: orgrimmar zeppelin platforms. Stairs in Subken Temple, etc. any stairs. 

### Expected Blizzlike Behaviour

Orc female should not get stuck on any stairs or small ledges. No other toon gets stuck. 

### Steps to reproduce the problem

Take orc female character and attempt to walk up a set of stairs. Good examples are Sunken Temple. Also gets stuck on orgrimmar zeppelin platforms. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by JamesGent** [comment]
I believe human female models also get stuck on lots of stairs, especially the stairs that let you change floors between Sunken Temple layers.

**Comment by Azcobu** [comment]
Thanks for the report. This does seem to affect more than just orc females, but it's something of a moot point in any case, as this issue has been raised in the past before - see https://github.com/chromiecraft/chromiecraft/issues/949 and https://github.com/azerothcore/azerothcore-wotlk/issues/6537. Both were closed as a dev says [here](https://github.com/azerothcore/azerothcore-wotlk/issues/6537#issuecomment-889293944) that this is a client side issue, which means that unfortunately we can't fix it.
