### ISSUE TITLE
[NPC] [Mith'rethis the Enchanter] Loot issue

### ISSUE THREAD

**Issue by Steelcold** [chromiecraft/chromiecraft#1607]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

[Mith'retis the Enchanter](https://wowgaming.altervista.org/aowow/?npc=8217) (rare elite), Hinterlands, missing loot. I've already killed him 15 times give or take and only got silver. 
p.s. can you please check what his respawn time is as well.

### Expected Blizzlike Behaviour

I've seen a report saying he always respawns in the same place, and it's true. What I'd like to ask you is to check if he's got loot at all, since he drops [bis chest](https://wowgaming.altervista.org/aowow/?item=17050) for some cloth casters with a 19.8% probability (according to https://wowgaming.altervista.org/ and https://wotlkdb.com/ and also https://wotlk.evowow.com/)

### Source

https://wotlkdb.com/?npc=8217#drops
https://wotlk.evowow.com/?npc=8217#drops
https://db.rising-gods.de/?npc=8217

### Steps to reproduce the problem

1. Check out GUID 82469
2. check db if hes got loot

### Extra Notes

None

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
Thanks for the report. i tested this elite with Horde & Alliance and it works fine for me

SpawnTime: Full:20h Remain:20h3m8s

![Screenshot_20210903_075303](https://user-images.githubusercontent.com/14080516/131946231-13e18474-787b-4709-9ba7-d2d91b15b4ed.png)

![Screenshot_20210903_075705](https://user-images.githubusercontent.com/14080516/131946397-039a0983-2422-4dd9-aa82-c591c6718f0a.png)

![Screenshot_20210903_080123](https://user-images.githubusercontent.com/14080516/131946698-1fe08370-2fa2-4bb7-a94e-fe9bb87790a7.png)

**Comment by Steelcold** [comment]
Thanks for your help. Seems like I'm not so lucky then :)
