### ISSUE TITLE
Wailing Caverns: Naralex waves

### ISSUE THREAD

**Issue by mistertinkles** [chromiecraft/chromiecraft#1613]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

During the final fight of Wailing Caverns the Disciple of Naralexx correctly paths to the chamber containing Naralex and begins the waves of vipers. Twice for our group a pack of 3 elite, level 19 vipers spawned and were dealing astounding damage - our level 24 protection paladin (sorry, I don't know their total hp but they had no problems tanking the dungeon with 0 deaths and making massive pulls) was losing about half their hp per hit.

I don't have specific numbers, but on my level 17 priest with ~400hp shows a combat log where these vipers were dealing over 200 physical damage per hit.

### Expected Blizzlike Behaviour

We were unable to advance past the first wave in the gauntlet due to the vipers hitting incredibly hard on all party members, but I would normally expect the vipers to deal significantly less damage than they do despite being elites.

### Steps to reproduce the problem

1. Proceed through the Wailing Caverns instance killing all of the snake-themed bosses.
2. Participate in the Disciple of Naralex escort that becomes available after killing the snake-themed bosses.
3. Engage in combat with the vipers that spawn in the first wave of enemies.
4. Cry as the vipers demand your lunch money.
5. Welcome the cold embrace of death with open arms.
6. Log off and go eat some ice cream (or other delicious dessert item if you are lactose intolerant).

### Extra Notes

https://wotlkdb.com/?npc=3654

The above link is to the boss that spawns at the end of the event - we failed to reach the point of fighting him and died twice on the first wave. It seemed incredibly obvious that the mobs were hitting way too hard.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
Just for reference, the NPCs @mistertinkles is reporting (I believe) are [Deviate Moccasins (NPC ID 5762)](https://wowgaming.altervista.org/aowow/?npc=5762).

**Comment by syssneck** [comment]
Yeah, they hit hard, but it is manageable. We need a  reliable source, that they indeed should be weaker. We can't just change values, because it is "feeling" too hard.

**Comment by Si1ker** [comment]
No source provided, re-open if you have a source.
