### ISSUE TITLE
Random dismounts when in ships/zeppelins

### ISSUE THREAD

**Issue by VFaleiro** [chromiecraft/chromiecraft#1615]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When running around (while mounted) ships/zeppelins, or even standing by (as soon as the ship/zeppelin begin to move), you can get randomly dismounted as if just walking through a door, but still outdoors. You can mount right after it without any problems.

### Expected Blizzlike Behaviour

You only get dismounted if you get indoors.

### Steps to reproduce the problem

1. Be level 20+ and mount;
2. Go to Ratchet and wait for the Booty Bay ship;
3. Get on board;
4. Run around randomly or just stand still and wait for the ship to start moving.

### Extra Notes

Zeppelins that got me dismounted:
- Tirisfal-Durotar
- Tirisfal-Stranglethorn Vale
- Durotar-Stranglethorn Vale

Ships that got me dismounted
- Ratchet-Booty Bay

Did not test the zeppelin Durotar-Mulgore.

I was playing horde, but for Alliance it probably behaves the same way since most Alliance ships (E.G. Darkshore-Stormwind or Wetlands-Dustwallow) use the exact same model as the Ratchet-Booty Bay ship.

Have no clue about the behaviour of Alliance ships that have no indoors (E.G. Teldrassil-Darkshore or Azuremyst-Darkshore), and evidently Northrend ships/zeppelins cannot be tested (but they also have no indoors).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Well, you getting dismount when new zone is loading. That's not about something.

**Comment by Azcobu** [comment]
Thanks for the report. We already have an open ticket for this issue, but I'll copy across both your findings there so the information is preserved.
