### ISSUE TITLE
[Quest] Ending the Bloodcurse: can't destroy the statue after abandoning quest

### ISSUE THREAD

**Issue by youdasz** [chromiecraft/chromiecraft#1618]
I apologize for my english, hope to explain my issue. There's a chain quest at Bloodmyst Isle giving you by Captain Hanes. I have an issue with the last quest: Ending the Bloodcurse. I destoyed statue but didn't killed Atoph in time and he dissapered. I couldn't brake the statue once again so I abandoned quest and took it again. When I came back the statue was still destroyed and it was impossible to summon again Atoph. It happens all the time when I abandon quest and I can't complete quest chain. Relog doesn't solve the problem.

**Comment by Stump876** [comment]
Hello @youdasz Thanks for the report. However you bypassed the template. Can you please recreate this report using the template please? It will pop up when clicking the `Get started` button. 
![image](https://user-images.githubusercontent.com/68164076/132280397-b355c7af-bbea-4bc5-ac0e-8e1a1e12bc5c.png)
It contains information that will help out triage team, and the Devs if it gets verified and moved to AC. Thanks.
