### ISSUE TITLE
daze issues

### ISSUE THREAD

**Issue by ukidono** [chromiecraft/chromiecraft#1619]
### What client do you play on?

enGB

### Faction

- [x] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Daze feels so inorganic with its hit chance even in dungeons you cannot grab 2 different of packs without getting dazed even on lower level mobs. 

Also https://wotlkdb.com/?spell=13496#used-by-item many monster have this 10second daze from a weapon effect which should not exist.

### Expected Blizzlike Behaviour

1) https://wowwiki-archive.fandom.com/wiki/Daze

2) spell id 13496 shouldnt exist on mobs https://i.imgur.com/392hoMZ.jpg

### Source

https://wowwiki-archive.fandom.com/wiki/Daze

### Steps to reproduce the problem

>Get hit by non gray mobs .

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

![WoWScrnShot_090321_195742](https://user-images.githubusercontent.com/5203307/132046752-5c040c1a-aedf-458e-821d-be259768f73b.jpg)

### Server

ChromieCraft

**Comment by Si1ker** [comment]
Im lvl 80
Mob is lvl 11
I get 13496 every single time if I'm in the opposite direction: 10sec of -50% movement

Weird, this seems classic behavior, not woltk behavior.

![image](https://user-images.githubusercontent.com/61223313/132396368-61b41171-f423-408b-b5b1-4c13839e0114.png)
