### ISSUE TITLE
[Find Herbs] and [Lifeblood] (Rank 4) remained in SpellBook after removing Herbalism

### ISSUE THREAD

**Issue by Santaria94** [chromiecraft/chromiecraft#1624]
### What client do you play on?

ruRU

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

[Find Herbs] and [Lifeblood] (Rank 4) remaine in SpellBook after removing Herbalism.

### Expected Blizzlike Behaviour

[Find Herbs] and [Lifeblood] (Rank 4) must be removed along with Herbalism

### Source

You can check my character. Nickname: Santaria
I use ruRu client, sorry for the screenshot.
<details>
<summary>Screenshot</summary>

![34235](https://user-images.githubusercontent.com/32459796/132096496-b6d02783-3c3f-4411-b88d-cd76c3e1773a.jpg)
</details>

### Steps to reproduce the problem

1. Learn Herbalism and upgrade 300/300
2. Remove Herbalism
3. Learn any other profession. In my case tailoring.
4. Check [Find Herbs] and [Lifeblood] in SpellBook

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC 5c7d07ff8)
Can confirm.
![image](https://user-images.githubusercontent.com/53914190/132096850-5b1863bc-30f9-4739-8fd7-f4304ae4a18f.png)
![image](https://user-images.githubusercontent.com/53914190/132096856-b12a0fdc-0c4c-4c14-96de-d5bb5a54d387.png)

But I'm uncertain whether I did it correctly, as this is an already fixed issue. See https://github.com/azerothcore/azerothcore-wotlk/pull/7290.
So I'd prefer if someone could double-check.

**Comment by IntelligentQuantum** [comment]
Confirm, But when you Logout and login again the spell is not there anymore

**Comment by Santaria94** [comment]
Logout and login didn't helped me even after rebooting the ChromieCraft

**Comment by temperrr** [comment]
I can only sometimes keep the spell when I unlearn prof. When I relog I don't have it anymore. I notice that I will get 2x lifeblood and 2x find herb when I learn it (though the second 1 removes itself when relogging (even without unlearning)

**Comment by syssneck** [comment]
Possibly another repercussion of this issue: https://github.com/azerothcore/azerothcore-wotlk/issues/7415

**Comment by VFaleiro** [comment]
Just recently found out my warrior still has [Master of Anatomy](https://wowgaming.altervista.org/aowow/?spell=53662) even though I abandonned Skinning for Engineering a week ago or so. Was going to report it but saw this issue.
Maybe all other professions have the same problem, and not just Herbalism/Skinning?

**Comment by Elexias** [comment]
Can confirm that nowdays when you unlearn herbalism, it will remove lifeblood but not find herb.

**Comment by Elexias** [comment]
![WoWScrnShot_092321_113030](https://user-images.githubusercontent.com/80590226/134484724-f9c1084b-cd81-4fe9-84ba-722551f04c1d.jpg)

Still issue.

**Comment by 55Honey** [comment]
related: https://github.com/chromiecraft/chromiecraft/issues/1044
