### ISSUE TITLE
[Dustwallow Marsh] Horse Vendor in Theramore named "Unknown"

### ISSUE THREAD

**Issue by awshew** [chromiecraft/chromiecraft#1626]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The Horse vendor in Theramore is named "Unknown" and has no reputation faction

### Expected Blizzlike Behaviour

He should be named "Gregor MacVince"

### Source

https://wowpedia.fandom.com/wiki/Gregor_MacVince

### Steps to reproduce the problem

* Travel to Theramore
* 65.2, 51.4 - NPC with name "Unknown"

### Extra Notes

https://wowpedia.fandom.com/wiki/Gregor_MacVince
https://tbc.wowhead.com/npc=4885/gregor-macvince

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report!
I found the correct person(On local server), I think, but his name is correct. Although I don't know how to check for reputation faction.
![image](https://user-images.githubusercontent.com/53914190/132098663-2ff2e5cf-bdc5-4260-a2c2-560109018b18.png)
So, I'd wait for more feedback.

**Comment by awshew** [comment]
That's interesting. On Chromiecraft live server, the NPC is named "Unknown". Maybe this is fixed on a newer version then?

![image](https://user-images.githubusercontent.com/26572445/132099269-e6acb9a8-553e-4cb4-9a4f-7fa71b7fafc9.png)

**Comment by awshew** [comment]
The NPCs in Theramore appear to not have factions on second look, so I removed that part of the report.

**Comment by gurveleg** [comment]
In the past npcs/mobs labeled unknown were s+considered game client bug so i dunno. Maybe clear cache and try again?

**Comment by awshew** [comment]
Confirmed it's a client-side problem - his name is back. Closing this.
