### ISSUE TITLE
item 22318 is missing from 2 loot tables 

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1628]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

item is in the loot tables of 4 mobs

### Expected Blizzlike Behaviour

item is in the loot tables of 6 mobs

### Source

https://wotlkdb.com/?item=22318

https://wotlk.evowow.com/?item=22318#dropped-by

### Steps to reproduce the problem

Query the following with mysql:

select creature_template.name, creature_loot_template.entry, creature_loot_template.chance from creature_loot_template join creature_template on creature_loot_template.Entry=creature_template.entry where creature_loot_template.item="22318";

![image](https://user-images.githubusercontent.com/84640316/132100034-bf9af933-690e-4cb4-a503-d916dc6c149c.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Wotlkdb.com isn't proper source.

**Comment by baranzadeoglu** [comment]
> Wotlkdb.com isn't proper source. Quick overview of wowhead says it should contain only in [Arena spoils](https://wowgaming.altervista.org/aowow/?object=181074) object. So probably you have to delete it from loot table of thoose 4 NPCs. Also need to chek other items from object and delete it too.
> 
> ```
> Malgen's Long Bow is a new item added to WoW Classic in Phase 5 with the introduction of the Tier 0.5 Summonable bosses.
> This item drops from the Theldren encounter, who can be summoned at the Ring of Law in Blackrock Depths.
> Once the boss is defeated, you'll be able to loot Arena Spoils, which has a chance to contain this item.
> ```

Wowhead is classic or tbc not wotlk. It is quite likely that they changed the mechanic at wotlk.

**Comment by Shineslippers** [comment]
@baranzadeoglu absolutely agree it's not. But you need better proofs. Not private DB.

**Comment by jamadaha** [comment]
As stated, the provided sources aren't primary sources. As such, they themselves are not enough to warrant change. If you would like an overview of sources, you can find it in this [link](https://www.azerothcore.org/wiki/guide-to-triaging) under the section called 'sources'.
Wowhead [claims](https://tbc.wowhead.com/item=22318/malgens-long-bow#contained-in-object), for TBC, that it only drops from the arena spoils, but as stated that could have changed from TBC to WOLTK. However, if you look at Wowpedia for the [changelog](https://wowpedia.fandom.com/wiki/Malgen's_Long_Bow), you will find that no such change is mentioned. Moreover, Wowhead for [live](https://www.wowhead.com/item=22318/malgens-long-bow?bonus=6710#contained-in-object), still states the same drop condition.

So I'd say that the current behaviour is wrong: no mob should drop it — not 4 or 6.

**Comment by baranzadeoglu** [comment]
If you have a definite source, I can edit the original post. Or fell free to do yourself if you wish so

**Comment by Azcobu** [comment]
I agree with @jamadaha - a contemporary version of the Wowpedia page from the Wrath era ([November 2009](https://wowpedia.fandom.com/wiki/Malgen's_Long_Bow?oldid=2110488)) also says this exclusively drops from the Arena Spoils item. As such it should be removed from the drop tables of any NPCs. Some further checking also shows the other items contained in the Arena Spoils bags (Ironweave Mantle, Lefty's Brass Knucle, Shroud of Arcane Mastery) are also all dropping from various NPCs who shouldn't have access to them, so will need to clear all these out.

Also note your SQL query is slightly incorrect, in that you link `creature_template`.`Entry` to `creature_loot_template`.`Entry`. This will usually work because the creature loot templates have been set up so they mostly use the creature's entry as the template ID, but every so often you find a creature where this has not been done. (For example, see Mosshide Mongrel ID 1008). The correct join to make it work consistently is to use the `creature_template`'s`lootid` field instead.

**Comment by baranzadeoglu** [comment]
> Also note your SQL query is slightly incorrect, in that you link `creature_template`.`Entry` to `creature_loot_template`.`Entry`. This will usually work because the creature loot templates have been set up so they mostly use the creature's entry as the template ID, but every so often you find a creature where this has not been done. (For example, see Mosshide Mongrel ID 1008). The correct join to make it work consistently is to use the `creature_template`'s `lootid` field instead.

thank you
