### ISSUE TITLE
Copper Veins may have an improper loot table

### ISSUE THREAD

**Issue by CameronWoof** [chromiecraft/chromiecraft#163]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

GameObject: [Copper Vein](https://wotlkdb.com/?object=1731)

Mined a copper vein in Elwynn Forest and received 11 rough stone from it.

![image](https://user-images.githubusercontent.com/20717737/110238513-0d0b9800-7f10-11eb-87ab-0d323845966b.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Blizzlike amounts are no more than 4 copper ore and no more than 6 rough stone. 11 is very far out of line.

##### CURRENT BEHAVIOUR:

I don't know how to see exactly what the possible values are, but as per the above screenshot, they definitely seem out of line.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Mine copper ore, possibly specifically in Elwynn Forest.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
**Video Test:** [5 minutes and 14 seconds of my life that I will never have back](https://youtu.be/b4DF_h4jvpc)

**Comment by illfated** [comment]
@CameronWoof : That one event where you received 11 Rough Stone from mining 1 node of copper ore can easily be seen as a glitch in the Random Number Generator, which can happen. If you are able to reproduce that issue, it would suggest that something could be done to set limitations for the RNG when used with the mining skill. As it is now, only 1 occurrence is not enough evidence that the source RNG needs to be reworked for this type of issue.
