### ISSUE TITLE
[Roleplay] Clearing the Senate should make Dagran Thaurissan say some quotes

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1630]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Emperor Dagran Thaurissan does not use his quotes when clearing the Senate.

### Expected Blizzlike Behaviour

![image](https://user-images.githubusercontent.com/22718174/132107429-c6dd517c-4a56-492d-a08a-035bc8bcc4e6.png)

### Source

https://wowpedia.fandom.com/wiki/Dagran_Thaurissan

### Steps to reproduce the problem

Do things to make Emperor Dagran Thaurissan talk.

### Extra Notes

Getting Emperor Dagran Thaurissan into combat when there are mobs alive in the Senate does make Dragan say his quote properly.

Getting Emperor Dagran Thaurissan into combat when the Senate is dead needs testing.

Getting a player killed needs testing.

Completely clearing the Senate needs testing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/8102
