### ISSUE TITLE
[Arathi Basin] Dying a moment when your base get's assaulted leaves you without ressurection

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1633]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

It doesn't happen that much often, nor happened to many people as there is really low chance that you die same moment when they assault your base in Arathi Basin.
What happened is that I got teleported to the zone that was mine (Gold Mine), when I died Gold mine got assaulted and because of that, mob that ressurects people dissapeared, leaving me without ressurection.
Solution: Wait for my BG friends to assault or defend that part of Arathi Basin or walk to any other friendly base which takes 2 mins or more.
Again happens very rare as it is low chance that in same moment when you die base get's assaulted

On a screenshot you can see me on graveyard after I died, Outplayed assaulted Gold Mine and was not a Horde teritory anymore, my spirit healer dissapeared and I couldn't ressurect.

![WoWScrnShot_090421_222115](https://user-images.githubusercontent.com/80590226/132115734-85be97fc-39a2-4243-9336-98a7163d3c4d.jpg)

### Expected Blizzlike Behaviour

Should be immediately teleported at any other nearest graveyard if die when base is assaulted.
Again teleporting to other graveyard works perfectly if base is assaulted. BUT IF base is assaulted SAME moment when you die, it doesn't work.

### Steps to reproduce the problem

Try to die on a same moment when someone is assaulting your controled base in Arathi Basin.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
![WoWScrnShot_091421_162226](https://user-images.githubusercontent.com/80590226/133275586-374026c0-6aeb-4957-b45e-663b76fb9b64.jpg)

Random guy in BG running from Stables dead as ghost to Lumber Mill, because Stables got assaulted same moment before he got released. Results in him being a ghost and not having spirit healer to ress him at his base.

**Comment by Shineslippers** [comment]
Idk is it blizzlike or no. I will report as suggestion.
