### ISSUE TITLE
Dropping combat while jumping above the water surface

### ISSUE THREAD

**Issue by Thar3l** [chromiecraft/chromiecraft#1641]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Dropping combat when jumping out of the water, also character does not autoattack while fighting under the water.

You can clearly see that in the video below:
[https://www.youtube.com/watch?v=7gqEzOdHOH0](url)

### Expected Blizzlike Behaviour

Combat should not drop when you jump out of water (it's okay when it drops when you jump on the shore, but it drops when you jump above water surface, even if Im in the center of the river) and player character should autoattack monsters while combat under the water.

### Steps to reproduce the problem

1. Find a place where mobs are chillin under the water.
2. Start combat with them.
3. Try jumping out of water to see if the combat drops.
4. Try autoattack mobs while fighting under the water.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
I cannot confirm the auto attack. It works just for multiple characters I have used. Can you try again to see? Just right click and you should attack. Can confirm that you drop aggro when jumping out of the water if you are being attack by water only monsters, like frenzy fish and Threshers. I cannot find any source / video on how they should behave when you are jumping out of the water. I am asking you and anyone reading this if they may be able to find something so we can see how it should be and if this behaviour is actually wrong.

**Comment by VFaleiro** [comment]
> I cannot confirm the auto attack. It works just for multiple characters I have used.

It happened to me before, but it doesn't always happen. I believe it has something to do with the mob being hit and its position on the ground underwater. I was actually hitting [Murk Threshers](https://wowgaming.altervista.org/aowow/?npc=4389) and [Elder Murk Threshers](https://wowgaming.altervista.org/aowow/?npc=4390) (trying to farm Big-mouth Clams).

They have large hitboxes that are located below their ingame models, and are most of the time close to the ground underwater. Very likely their hitbox was partially inside the ground, so my character couldn't autoattack them because of LoS? Just a theory though.
