### ISSUE TITLE
Mob health not reset when you take dungeon queue

### ISSUE THREAD

**Issue by jacketcrypto** [chromiecraft/chromiecraft#1651]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

If you leave the world in the middle of a fight to take a dungeon finder queue the monsters health is not reset. 

I was in Redrige in a cave, I attacked a gnoll and took a queue to a Stockades run, when I returned the gnoll I had taken down to ~30% was in aggro range and still at 30% health when it ran at me. I was in the dungeon for 10-15 minutes. 

### Expected Blizzlike Behaviour

Monsters should completely reset back to their original status when you take dungeon queues. 

### Steps to reproduce the problem

1. Queue for any dungeon
2. Be in a fight when the popup to enter the dungeon comes up
3. (I suppose having nobody else encounter the mob during this time is needed)
4. Finish or leave the dungeon

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ntrna** [comment]
This has also happened to me while soloing dungeons. I run out to heal, and when I enter, the mobs are often right at the entrance, ready to aggro me & at the same health they were at when I left - so, not 100%, and not in their reset positions.

**Comment by Si1ker** [comment]
It happened to me yesterday at night when I got the dungeon announcer to join, a wolf at 20% HP was still there after the entire run🐱

**Comment by vexima** [comment]
it's an old issue with azerothcore deactivating mobs once no players are present within its sight. see https://github.com/azerothcore/azerothcore-wotlk/issues/3269
