### ISSUE TITLE
[Human] Sword & Mace Specialization remain while unarmed, only reducing Expertise once you then equip a weapon which is not a mace or sword

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#1652]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Equipping/unequipping a sword or a mace, at least the 1 handers I have, does not change my human character's expertise rating in the character pane. Only once I equip another weapon type do I lose the expertise - not when disarmed of sword / mace.

### Expected Blizzlike Behaviour

Sword & Mace Specialization should work as in tooltip, +3 Expertise when equipping a 1h or 2h sword or mace, but not otherwise (as in when unarmed).

### Steps to reproduce the problem

1. Make a human
2. Open character pane, mouseover expertise stat in melee pane below character model
3. Equip/unequip 1h/2h mace/sword

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report, but I can't seem to replicate it. When equipping either a sword or mace, the expertise rating increases the expected amount. Although, it doesn't increase if the item is broken, but I don't know whether that is wrong.
When the bug occurs for you, is it a specific weapon or all?
![image](https://user-images.githubusercontent.com/53914190/132328226-0499d8c8-393e-4232-bfc3-728c38e3d5b1.png)
![image](https://user-images.githubusercontent.com/53914190/132328246-773ab024-32f1-43f6-a0b4-599180a290e7.png)
![image](https://user-images.githubusercontent.com/53914190/132328278-bb5b25fb-a4ea-4c09-b297-ceb61e20d5d8.png)
![image](https://user-images.githubusercontent.com/53914190/132328653-ebc2e922-47f6-4ede-80d6-d5ea5b0a07a3.png)

**Comment by ntrna** [comment]
![WoWScrnShot_090721_063003](https://user-images.githubusercontent.com/89823720/132330302-35386078-d52b-400d-8033-4890b770b663.jpg)
![WoWScrnShot_090721_063007](https://user-images.githubusercontent.com/89823720/132330307-8b992d66-f80a-445d-a82b-d6ade61b4860.jpg)
![WoWScrnShot_090721_063016](https://user-images.githubusercontent.com/89823720/132330312-c2262932-903a-42eb-94a2-28d46c19f22b.jpg)
![WoWScrnShot_090721_063021](https://user-images.githubusercontent.com/89823720/132330318-a592db63-9931-4fc4-a65c-85764309685f.jpg)

**Comment by jamadaha** [comment]
Hmmm, I think I replicated it. When unequipping the item, the expertise doesn't disappear(Tried deleting cache). But it does leave when equipping another item e.g., axe. Could you check whether it is the same for you? Either case, it is a bug.

What I think is happening in your case, is that 14 is with buff, but if you were to equip an axe it would go to 11.

![image](https://user-images.githubusercontent.com/53914190/132343159-c9f4fea1-eb86-4064-94fb-4f292b4ae406.png)
![image](https://user-images.githubusercontent.com/53914190/132343174-c2089705-749e-4282-9795-8507a29472b3.png)
![image](https://user-images.githubusercontent.com/53914190/132343345-5f403fba-6e1d-42b4-8046-e4905e281140.png)

**Comment by ntrna** [comment]
Yup, when I unequip the weapon, the bonus remains, and only after I equip a weapon which isn't a sword or a mace does it disappear. Editing title.
