### ISSUE TITLE
Random Dungeon's cooldown doesn't show up in Dungeon Finder's window without relog.

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#1654]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

If you, for example, have been removed from RD queue there is no way to find out cooldown of it.
![WoWScrnShot_090721_173432](https://user-images.githubusercontent.com/85256266/132364764-6d73c1f3-05dd-4f41-8044-678d6bb6ec3e.jpg)

### Expected Blizzlike Behaviour

For some reason it's available only after relog.
![WoWScrnShot_090721_173452](https://user-images.githubusercontent.com/85256266/132365716-745bf608-9056-4685-97fc-bda3c3eec1db.jpg)

### Source

I don't know but this is frustrating.

### Steps to reproduce the problem

Don't accept invite to RDF and look to DF's window.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
I believe this is really the case on CC, but I can't confirm it on my local AC.
It is showing the cooldown right away.

**Comment by Shineslippers** [comment]
Well, i violated 1st rule - disable addons. Without addons there is no problem. Sorry for bothering.
