### ISSUE TITLE
Warlock life tap interrupts mana regen

### ISSUE THREAD

**Issue by Aleksiye** [chromiecraft/chromiecraft#1655]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Casting Life Tap interrupts mana regen both in and out of combat (as if the player is casting or channeling a spell)

### Expected Blizzlike Behaviour

Life Tap should not interrupt mana regen. Mana should regenerate at the speed it does as if no spells are being cast (in addition to mana provided by the life tap itself)

### Source

Section: patch changes, patch 0.12
https://wowpedia.fandom.com/wiki/Life_Tap

Also in section Warlock, line 4
https://wowpedia.fandom.com/wiki/Patch_0.12

### Steps to reproduce the problem

1. Play Warlock
2. Drain some mana by casting spells
3. Leave combat
4. Notice mana starting to regenerate
5. Cast life tap and observe how regeneration is interrupted

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
I cannot replicate your issue on chromiecraft nor azerothcore. When casting life tap it switches from gaining mana every second (I see it grow bigger) to every few seconds but still generating the same amount of mana. Is this the issue you are describing?

**Comment by Aleksiye** [comment]
> I cannot replicate your issue on chromiecraft nor azerothcore. When casting life tap it switches from gaining mana every second (I see it grow bigger) to every few seconds but still generating the same amount of mana. Is this the issue you are describing?

Yes, I think that's it, sorry for false report then.
