### ISSUE TITLE
[Warsong Gulch - Achievement] Warsong Gulch Veteran completed achievement but no credit

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1657]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

After getting 100 wins, which did count properly for achievement  [Warsong Gulch Veteran], I did get achievement. But gained achievement did not count properly for group achievement called  [Master of Warsong Gulch]. Seems that winning as difference faction when getting into BGs count for Veteran achievement, but that Veteran achievement does not count coz in the real count it count wins only as your faction. Example I did total of 100 wins and they counted, but maybe I had 47 as horde, 53 as alliance (counter faction).

### Expected Blizzlike Behaviour

Non Blizzlike experience, in Blizzlike BGs you can't get counter faction.

### Steps to reproduce the problem

Not sure how to reproduce 100 wins manually, would take ages for tester
But getting 100 wins will give you achievement, but that achievement won't count for Master of Warsong Gulch achievement.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
@Elexias is issue resolved? Can you do screenshotwith of your `Master` achivement if not
![image](https://user-images.githubusercontent.com/85256266/144410472-f40a76d3-26e7-45dc-987a-317944f98f6e.png)

**Comment by Elexias** [comment]
I was gained achievement by Honey herself. I had all criteria meeted, so she granted me achievement by database or comand idk. I did get 100 wins achievement after getting 100 wins but problem was not getting Master after finishing last part of it.

**Comment by Shineslippers** [comment]
I just wanna know do you had `check sign` in your `Master` achi near `Veteran`

**Comment by Elexias** [comment]
I think that I had problem with check sign with CAPTURE THE FLAG achievement, probably first time I entered WSG I completed it as other factions. Other check ins are ok, but all check ins are now ok since Honey did fix it for me. But If I remember as I've said think that problem was with check sign of other achi.

**Comment by Shineslippers** [comment]
Thank you. I will try to check it.

**Comment by Shineslippers** [comment]
I think i have to check other achievements same way as `Warsong Gulch Veteran`. Thank you.
