### ISSUE TITLE
[Arathi Basin - Achievement] We Had It All Along *cough* does not grand when played by other faction

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1658]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

I just played alliance faction in BG and I'm myself troll (Horde), we did win with 1600 vs 1590 in Arathi Basin, I was not granted achievement by system.
![WoWScrnShot_090721_220721](https://user-images.githubusercontent.com/80590226/132405053-3373c90d-6088-4a25-b6ce-e38a4127223f.jpg)

On screenshot you can see that I'm alliance in BG. And that we won with 1600 vs 1590.
https://wotlk.evowow.com/?achievement=162

### Expected Blizzlike Behaviour

Can't be Blizzlike as you can't be other faction on Blizzlike BGs.

### Steps to reproduce the problem

Get in BG as other faction
Win with 1600 vs 1590 difference
Not get achievement.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by 55Honey** [comment]
The player was awarded neither criteria 3442 nor 3427.

**Comment by mdawx** [comment]
Looks like similar to https://github.com/chromiecraft/chromiecraft/issues/305

**Comment by ntrna** [comment]
If this is not necessary, please let me know, but I am commenting to add I had the same experience.

![WoWScrnShot_091321_144733](https://user-images.githubusercontent.com/89823720/133140001-8ca3cb77-1938-4ba4-b0ce-61e0cecfb1e0.jpg)

**Comment by gurveleg** [comment]
Can confirm this doesn't wrok even if you are on the right faction. I did 2 1600 vs 1590 victories, one on allaince side and one crossfactioned on horde side, and neither I or anyone on my teams got an achivement either time.
