### ISSUE TITLE
[Blackrock Depths - Boss] Summoner's Tomb event in BRD is faster than normal

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1659]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

### Current Behaviour

When you get to Summoner's Tomb and when you pull the event. Bosses that should spawn every 45 seconds or so, but here they spawn every 20 sec or so, might be wrong, never counted. But everyone in multiple runs (over 20) stated that they spawn faster than expected leading to fight 3 bosses at once instead max 2.
https://classic.wowhead.com/npc=9039/doomrel#drops;mode:normal

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=wW84027e2JU&ab_channel=Chou-chiChang

At lower levels in BRD you on Blizzlike WoW have time to kill 1 by 1 boss, while here bosses spawns so fast that you get 3 at some point even with BiS lvl 49 gear and so fast killing with WoTLK talents. Our spawn times are insane.

### Steps to reproduce the problem

1. Enter BRD and get to Summoner's Tob (Near the end of BRD full run)
2. Start the event by talking to one of bosses (straight forward when you enter door)
3. Bosses spawning so fast, literally 20 sec or 25, get 3 bosses at some point to handle.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
Can confirm that they spawn too early. Trying to figure out what timing it should have. Found a vid with at least 30 seconds between spawns, as of now its closer to 14 seconds.
