### ISSUE TITLE
The mission "Chieftain Oomooroo" is not available for accept it.

### ISSUE THREAD

**Issue by Drincor** [chromiecraft/chromiecraft#1665]
### What client do you play on?

other

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Quest is not available.

### Expected Blizzlike Behaviour

This quest is given by the npc Stillpine the Younger from level 11 in Azuremyst Isle (46.1, 21.2).
https://tbc.wowhead.com/quest=9573/chieftain-oomooroo
https://www.youtube.com/watch?v=hfY8kx0HZH0

### Steps to reproduce the problem

1. Be from the alliance (Draenei race)
2. Go up to level 11
3. Travel to 46.1, 21.2 Azuremyst Isle
4. See that the mission is not available https://tbc.wowhead.com/quest=9573/chieftain-oomooroo

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
Thanks for report but first of all you must complete this quest [murlocs why here why now](https://tbc.wowhead.com/quest=9562/murlocs-why-here-why-now)

![Screenshot_20210908_093647](https://user-images.githubusercontent.com/14080516/132450093-186a3c6b-98c9-4611-b838-3602bdbff3dc.png)
