### ISSUE TITLE
Dead as a ghost/spirit. 

### ISSUE THREAD

**Issue by RolyNuki** [chromiecraft/chromiecraft#1672]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

While in a solo instance of Ragefire Chasm I died and was ported to the graveyard outside of Orgrimmar after hitting release spirit. After loading into the overworld I was still dead, but as a ghost, could not move or interact with the spirit healer. I logged out to the character screen which still showed me as a ghost but after logging back in I was alive with half hp/mana like I had recovered my body normally. 

### Expected Blizzlike Behaviour

You shouldn't be able to die as a ghost? Releasing from a dungeon should put you in ghost form at the spirit healer to move around and recover your body.

### Source

Normal game mechanics

### Steps to reproduce the problem

Tried twice to replicate but couldn't get it to happen again. Corpse also did not leave a skeleton in the instance like a normal player body would. Tried searching for similar event in the issues but couldn't find one.

### Extra Notes

Was playing on a level 19 female tauren druid, in bear form when I died.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Tried to do as described: a level 19 female tauren druid in bear form, dying in ragefire chasm. Yet, I couldn't replicate it. The normal death occurs. Also a couple other characters just to check, but couldn't reproduce.

**Comment by awshew** [comment]
I've died as a ghost to exhaustion before, is it possible they fell through the world into an exhaustion zone?

**Comment by dieing4me** [comment]
Can confirm but with different circumstances. Level 49 Male Human Rogue in solo Blackrock Depths on the live CC server. I was not trying to replicate.

Died in BRD, went to graveyard in Burning Steppes and was dead as a ghost still in the graveyard. Had a button prompt to release, which when clicked did nothing. Logged out, was a ghost on character select screen, logged in, alive in the graveyard with no skeleton on the ground.

additional notes:
I clicked the release as ghost button when I died inside the dungeon very quickly.
I was in a RDF for BRD beforehand, which was completed. The group left and I stayed inside the dungeon but died, went to the graveyard which reset the RDF instance and I entered BRD as a ghost to a fresh instance.

**Comment by RolyNuki** [comment]
Reading this reply sounded very similar to how my instance/issue happened as well. I also released very quickly and was in a similar state dungeon. Did RDF for ragefire chasm, died trying to kill some stuff with a normal death and corpse run, and then zoning back in to retrieve my body put me in a fresh instance which is where the 'dead ghost' release happened.

**Comment by RolyNuki** [comment]
Replying to this again, was able to reproduce the same way just now. Cleared RDF, let the other party members leave the dungeon and died inside. Ran back normally and zoned into a fresh instance, died again and was ported to the spirit healer as a ghost. I had a "release spirit" button but clicking it just removed it and nothing happened.
![image](https://user-images.githubusercontent.com/90322639/133337157-fa11cb90-1ee2-4ba7-b5d6-57b7d131918c.png)
