### ISSUE TITLE
[Badlands] Battered Footlockers are spawning in inaccessible places

### ISSUE THREAD

**Issue by awshew** [chromiecraft/chromiecraft#1677]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Battered Footlockers (item 179490) are supposedly inside the fortress as expected, but in the walls/under things that make them inaccessible.

Found them using `.gobject near` :

11472 (Entry: 179490) - [Battered Footlocker X:-6375.259766 Y:-3106.560059 Z:310.834015 MapId:0] 
11471 (Entry: 179490) - [Battered Footlocker X:-6386.620117 Y:-3110.129883 Z:310.835999 MapId:0] 
11475 (Entry: 179490) - [Battered Footlocker X:-6403.750000 Y:-3127.550049 Z:302.500000 MapId:0] 
11470 (Entry: 179490) - [Battered Footlocker X:-6353.899902 Y:-3086.600098 Z:310.835999 MapId:0] 
11474 (Entry: 179490) - [Battered Footlocker X:-6323.379883 Y:-3108.489990 Z:310.835999 MapId:0] 
11454 (Entry: 179490) - [Battered Footlocker X:-6382.770020 Y:-3168.550049 Z:301.079010 MapId:0] 

### Expected Blizzlike Behaviour

Footlockers should be accessible to be unlocked by rogues trying to level lockpicking

### Source

https://tbc.wowhead.com/object=179490/battered-footlocker

### Steps to reproduce the problem

Head to Badlands
Try to find the battered footlockers. Open them and force respawns until all available spawns are actually inside the walls.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by awshew** [comment]
Suspect this is contributing to the perception of https://github.com/chromiecraft/chromiecraft/issues/1185 - boxes are probably respawning, but the number in accessible places dwindles until none are available at all.

**Comment by IntelligentQuantum** [comment]
https://github.com/chromiecraft/chromiecraft/issues/1678

**Comment by gurveleg** [comment]
Same thing as in the other topic, the battered footlockers inside the fortress ar eon 2h cooldown. They do spawn fine, it's just that someone opened them and they have not yet respawned.

**Comment by syssneck** [comment]
Same here.
