### ISSUE TITLE
[Badlands] Dented Footlockers are spawning in inaccessible places

### ISSUE THREAD

**Issue by awshew** [chromiecraft/chromiecraft#1678]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Dented Footlockers (item id 179492) are spawning into walls/floors/other objects making them impossible to open. Here are 4 I've been unable to locate, wandering around the entirety of the bottom floor of Angor Fortress

Located using `.gobject near`:

11499 (Entry: 179492) - [Dented Footlocker X:-6360.689941 Y:-3131.610107 Z:283.889008 MapId:0] 
11497 (Entry: 179492) - [Dented Footlocker X:-6344.029785 Y:-3100.830078 Z:293.056000 MapId:0] 
11498 (Entry: 179492) - [Dented Footlocker X:-6365.049805 Y:-3094.300049 Z:293.056000 MapId:0] 
11496 (Entry: 179492) - [Dented Footlocker X:-6355.080078 Y:-3092.070068 Z:293.056000 MapId:0] 

### Expected Blizzlike Behaviour

All dented footlockers should be accessible and openable by rogues trying to level lockpicking

### Source

https://tbc.wowhead.com/object=179492/dented-footlocker

### Steps to reproduce the problem

Travel to the Badlands
open Dented Footlockers in the basement of Angor Fortress until they respawn in impossible-to-get-to places

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
@awshew Dented flootlockers can be opened at 175 lockpicking AND it works fine for me.

**Comment by awshew** [comment]
Not a matter of whether they can be opened, they're spawning inside walls. Can't actually be accessed.

**Comment by IntelligentQuantum** [comment]
They do not appear inside the wall either. The problem is that after opening the box, you can only see the box when the gm is active

**Comment by gurveleg** [comment]
The problem with not seeing them is that they are on a 2h spawn timer. They all spawn perfectly fine, it is just tha tsomeone opened them already.

**Comment by syssneck** [comment]
Others already pointed out, what was wrong. The spawn locations are all fine.
