### ISSUE TITLE
[PvP - Huntere/Warlock pet] Pets have insanely long aggro range 

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1681]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

![WoWScrnShot_090921_152442](https://user-images.githubusercontent.com/80590226/132696789-2945dae7-1b4c-40e0-986a-28cd8862fd3c.jpg)

First Screenshot, you can see Imp targeting me while warlock is far away behind the second pillar.

![WoWScrnShot_090921_152931](https://user-images.githubusercontent.com/80590226/132696881-00b3d33d-1be1-4ab7-b201-dcb7da4da536.jpg)

Second screenshot you can see Voidwalker again and he is far away from his master.

![WoWScrnShot_090921_153141](https://user-images.githubusercontent.com/80590226/132696969-90a2bc86-78f8-48d9-84a7-9870a6013530.jpg)
![WoWScrnShot_090921_153147](https://user-images.githubusercontent.com/80590226/132696977-fb484c4f-1caf-45f0-9bd5-3dfbd0851371.jpg)
![WoWScrnShot_090921_153144](https://user-images.githubusercontent.com/80590226/132696982-c3c19142-f744-4fa4-a18b-84673a53831a.jpg)
![WoWScrnShot_090921_153143](https://user-images.githubusercontent.com/80590226/132696983-dd061e66-0c95-44b4-9c1f-d75847647ba7.jpg)

Last 4 screenshots you can see hunter miles away from our flag carrier who is inside tunnel, pet still attacking him.
That is bugged, after running away for some range, pets should always return to master, here you can see hunter actually killing people with pets while being tons away and not being able to be killed.

### Expected Blizzlike Behaviour

Pets should return to master after they run away for short range.
Here pets can kill you, while thier masters are far away and not to be targeted by us.

### Steps to reproduce the problem

1. Play BG or do duel/PvP vs Hunter or Warlock
2. Run far away, let lock/hunt pull pet on you
3. Pet attacks you while their masters are far far away.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Don't have much to add here, as I didn't find a way to test the BG element of this bug. But can confirm that pets — hunter pets at least — disengage correctly, when outside the hunter's range in open world PVP.

**Comment by Elexias** [comment]
> Don't have much to add here, as I didn't find a way to test the BG element of this bug. But can confirm that pets — hunter pets at least — disengage correctly, when outside the hunter's range in open world PVP.

Yes but from screenshots you can see that as hunter or warlock you can put your pet to chase enemy for really long range, leading to you getting killed by pet while their master is killing someone else far far away.

**Comment by Lemonadez** [comment]
This is normal from WOTLK-Cata.. Pet distance only change after MOP..

**Comment by Elexias** [comment]
![WoWScrnShot_091221_130910](https://user-images.githubusercontent.com/80590226/132985324-6cf90bb7-1689-49e2-9ba3-d938e805ef59.jpg)
![WoWScrnShot_091221_130913](https://user-images.githubusercontent.com/80590226/132985326-270d277f-732d-4db3-ae38-d97717a1c21a.jpg)

Range of pet aggro :D

**Comment by Elexias** [comment]
![WoWScrnShot_091221_164954](https://user-images.githubusercontent.com/80590226/132994637-0511637d-eace-4e76-b66a-2fd1c4d484c6.jpg)
Look from where did warlock send his pet to kill me.

**Comment by jamadaha** [comment]
I don't think anyone disagrees that the range is long in BGs. But, first, someone has to confirm it on a local instance. 
Moreover, a large change, such as this, requires more evidence as to it being wrong, and what the correct range would be.

**Comment by Shineslippers** [comment]
Right now pet aggro is same as view distance. As far player can see target, as far player can send pet to attack. Since we don't have any sources about how it should be i have to close this report. If you will find anything regarding to this theme you can reopen this issue or create new. Thank you for your understanding.
