### ISSUE TITLE
[Missing Diplomat Quest cannot be continued] Private Hendel does not get subdued even after killing both his guards.

### ISSUE THREAD

**Issue by plankgg** [chromiecraft/chromiecraft#1683]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Quest: The Missing Diplomat (Subdue Private Hendel)
https://wowgaming.altervista.org/aowow/?quest=1324

![WoWScrnShot_090921_194227](https://user-images.githubusercontent.com/90416511/132744405-3d2946e4-0f98-4bbf-8186-05f06a293d1d.jpg)

As you can see, I have killed both guards at the camp he was in, and also lowered him to 1hp and kept fighting him until my hp was low so i had to lure him away, he's been getting hit by that guard for about 10 minutes now.

### Expected Blizzlike Behaviour

From what I've been reading on wowhead, people were fine completing this, and supposedly two npcs and they mention that at 30% health from Private Hendel, he should surrender, but from two fights with him, he never surrendered even though his hp dropped all the way to 1.

### Source

https://classic.wowhead.com/quest=1324/the-missing-diplomat#comments

### Steps to reproduce the problem

1. Quest was continued from an npc inside "Sentry Point" tower (can't remember the name of him).
2. Start the fight and beat up Private Hendel.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
![Screenshot_20210910_104239](https://user-images.githubusercontent.com/14080516/132808599-ef9e5b82-20fc-4f2a-a243-371590944aad.png)
![Screenshot_20210910_104256](https://user-images.githubusercontent.com/14080516/132808681-fdabb1bd-2704-472f-8eea-eb444e1b1e83.png)
![Screenshot_20210910_104313](https://user-images.githubusercontent.com/14080516/132808845-fe8b33d2-8605-485e-8cea-a8218515ca28.png)

It works fine for me :thinking:

**Comment by plankgg** [comment]
Hello, I tried to test it this morning again and the questline finally worked after having to abandon the quest, I do remember last night he was getting hit by that guard for about an hour, and another player mentioned not being able to move on with the questline around the same part. I think this quest can get bugged easily by others if they're not careful.

**Comment by Nightdawg** [comment]
![image](https://user-images.githubusercontent.com/77711219/132924340-9febb5a8-798e-4495-a3e4-a8e22736186c.png)
He's permanently aggressive, he's killing his own guards.

![image](https://user-images.githubusercontent.com/77711219/132924393-9e3262f8-867a-490a-9aaa-bb95daef376b.png)
He's unkillable.
I assume he bugs out when someone doesn't finish the quest and he resets on server restarts.
