### ISSUE TITLE
Rested XP indicator missing

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#1684]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When logged back into the game, the xp bar is filled up with blue color, indicating rested xp. However, the little vertical bar that indicates how far the rested xp goes is missing. The vertical bar will show up once you gain xp the first time after logging in.

### Expected Blizzlike Behaviour

Definitely a (minor) bug, right? Not sure whether it is a also a bug in retail though.

### Steps to reproduce the problem

Log a char out of the game for some time and log back in.

### AC rev. hash/commit

https://grithub.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by discorder0** [comment]
Could be a client-side issue though.

**Comment by Stump876** [comment]
I'm not quite sure I understand the issue. Do you have a screenshot of what your talking about? 
Blue bar means your on rested exp, also a mouse over will tell you if youre rested. If you do not see the end it could just mean you're rested into the next level. Try running this as a macro `/script p="player";x=UnitXP(p);m=UnitXPMax(p);r=GetXPExhaustion();if -1==(r or -1)then t="No rest."else t="Rest: "..(math.floor(20*r/m+0.5)).." bubbles ("if r+x<m then t=t..r else t=t.."level +"..(r+x-m)end t=t.."XP)"end;DEFAULT_CHAT_FRAME:AddMessage(t)` this should tell you how much rested you have.

**Comment by discorder0** [comment]
I was talking about the situation when the end indicator should be within current level. It was just missing. But I found out later that I can make it appear with /reload.

**Comment by discorder0** [comment]
> I'm not quite sure I understand the issue. Do you have a screenshot of what your talking about?
> Blue bar means your on rested exp, also a mouse over will tell you if you're rested. If you do not see the end it could just mean you're rested into the next level. Try running this as a macro `/script p="player";x=UnitXP(p);m=UnitXPMax(p);r=GetXPExhaustion();if -1==(r or -1)then t="No rest."else t="Rest: "..(math.floor(20*r/m+0.5)).." bubbles ("if r+x<m then t=t..r else t=t.."level +"..(r+x-m)end t=t.."XP)"end;DEFAULT_CHAT_FRAME:AddMessage(t)` this should tell you how much rested you have.

I was talking about the situation when the end indicator should be within current level. It was just missing. But I found out later that I can make it appear with /reload.

**Comment by discorder0** [comment]
I was talking about the situation when the end indicator should be within current level. It was just missing. But I found out later that I can make it appear with /reload. (I’m not using any addons.)

**Comment by gurveleg** [comment]
Okay I tested this on local AC.
When you log in you can see the clored bar with rested XP, but theres no marker showing where it ends
![rested1](https://user-images.githubusercontent.com/80769357/132819327-46b0c125-46a3-4a44-9135-43b303e771f3.jpg)

After you do a /reload it shows up
![rested2](https://user-images.githubusercontent.com/80769357/132819363-c698bf32-7916-4102-88d1-4f326ab526a8.jpg)

**Comment by discorder0** [comment]
@gurveleg, thank you. One picture (or two) is worth one thousand words.

**Comment by Stump876** [comment]
So this is confirmed, not blizzlike? 
@gurveleg Do you want to link this to AC since you did the leg work to duplicate it. I would add this as a source. https://wowwiki-archive.fandom.com/wiki/Rest `When rested, your XP bar will turn blue, and a notch will appear indicating exactly how rested you are.`

**Comment by gurveleg** [comment]
Okay will do.

**Comment by discorder0** [comment]
@gurveleg @Stump876, an update: not sure whether the cause is the same but the notch, even if correctly displayed after /reload or gaining xp, will disappear when one (1) enter/leave deeprun tram, (2) use hearthstone, and (3) use the ChromieCraft main city portal. The last one is custom content, but there is definitely a pattern, and I won’t be surpirsed if the notch disappears when (1) a mage teleports itself, (2) someone uses a mage portal created by a mage player. But I don’t have chars to prove this. Hopefully this additional info helps you fix the bug.
