### ISSUE TITLE
Multi-Poison of Nerubis Centurion in Deatholme

### ISSUE THREAD

**Issue by jeanpaulcm94** [chromiecraft/chromiecraft#1686]
Nerubis Centurion makes an multiple Deadly Poison in Deatholme when u fight with 2 or more

![image](https://user-images.githubusercontent.com/90436202/132797106-5d905326-e849-4c5d-9c71-0e3bcbdaedd8.png)

**Comment by IntelligentQuantum** [comment]
Could you please fill out the whole form? 

https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&template=bug_report.yml
