### ISSUE TITLE
The bar in BRD

### ISSUE THREAD

**Issue by flagatron** [chromiecraft/chromiecraft#1688]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

After killing the bartender we were immediately rushed by the entire floor. As i recall, the mobs merely become hostile with their typical aggro ranges.

### Expected Blizzlike Behaviour

I only have my recollection as evidence, but the mods should act as if they have been turned hostile and not immediately aggro unless in range.

### Source

none

### Steps to reproduce the problem

KIll Plugger Spazzring

Pass leader while in queue

### Extra Notes

Also had issues with the LFG tool after. Was a bit of a mess invovling a d/c. Essentially the leader passed lead but that didn't pass the group finder lead. Resulting in us not being able to res at the dungeon portal.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report!
Tried replicating the whole floor attacking part, but could not. See below.
![image](https://user-images.githubusercontent.com/53914190/132902245-b4b27fa3-bb83-4470-8f4b-81519d552bff.png)
![image](https://user-images.githubusercontent.com/53914190/132902761-e582e87c-c79d-49fc-b33d-66e8ec8de0bf.png)

Although, it will pull a large amount when getting aggro.
![image](https://user-images.githubusercontent.com/53914190/132902907-ca29f3e1-e53c-49ec-95f9-631c0818257c.png)

So I'd wait for someone else to confirm this as a bug, as the behaviour seems fine by me.

**Comment by flagatron** [comment]
It's likely a group member did not admit to being out of position. Thanks
for testing!

**Comment by jamadaha** [comment]
I'll just assume this is closed then, if not, you're welcome to comment.
