### ISSUE TITLE
[Quest] One Shot. One Kill. - melee ranger

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#169]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

During the Quest [One Shot. One Kill.](https://classic.wowhead.com/quest=5713/one-shot-one-kill) questgiver [Sentinel Aynasha](https://classic.wowhead.com/npc=11711/sentinel-aynasha) should support player with her bow, but instead of attacking from distance she is fighting the enemy [with bare fists](https://www.youtube.com/watch?v=kL6UuC9pfSc).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC player has to protect should attack enemies [with a bow](https://www.youtube.com/watch?v=QjA1aDhfgy8).

##### CURRENT BEHAVIOUR:

Sentinel Aynasha is fighting in melee without any weapon.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Go to the Sentinel Aynasha location
Step 2 Start the quest
Step 3 Pay attention to her attack style

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
I am guessing that her SAI is incomplete and that the spell [Shoot] (ID 6660) is missing. Compare with the following TC info:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=11711
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=6660

```sql
entryorguid  source_type  id  link  event_type  event_phase_mask  event_chance  event_flags  event_param1  event_param2  event_param3  event_param4  event_param5  action_type  action_param1  action_param2  action_param3  action_param4  action_param5  action_param6  target_type  target_param1  target_param2  target_param3  target_param4  target_x  target_y  target_z  target_o  comment
-----------  -----------  --  ----  ----------  ----------------  ------------  -----------  ------------  ------------  ------------  ------------  ------------  -----------  -------------  -------------  -------------  -------------  -------------  -------------  -----------  -------------  -------------  -------------  -------------  --------  --------  --------  --------  -----------------------------------------
    11711         0        0    0        0              0              100            0             0             0          2300          3900             0           11           6660             64              0              0              0            0             19          11713              0              0              0         0         0         0         0      Sentinel Aynasha - In Combat - Cast Shoot
```

**Comment by Helias** [comment]
@illfated, unfortunately not, I would create it, but the last version of AoWoW is not totally compatible with AzerothCore, we have a version of AoWoW that is compatible with AC but it is not online. I should create it sooner or later :sweat: , I know that it would be really useful.
P.S. thanks for your support.

**Comment by illfated** [comment]
You are very welcome. Had I been permanently on disabled benefits, I would certainly have contributed more. I try as much as I can, based on how I spend my free time after work and before bedtime.

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [One Shot  One Kill](https://youtu.be/ZCep83j4sG4)

**Comment by Stifler82** [comment]
> I am guessing that her SAI is incomplete and that the spell [Shoot] (ID 6660) is missing. Compare with the following TC info:
> 
> * https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=11711
> * https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=6660
> 
> ```sql
> entryorguid  source_type  id  link  event_type  event_phase_mask  event_chance  event_flags  event_param1  event_param2  event_param3  event_param4  event_param5  action_type  action_param1  action_param2  action_param3  action_param4  action_param5  action_param6  target_type  target_param1  target_param2  target_param3  target_param4  target_x  target_y  target_z  target_o  comment
> -----------  -----------  --  ----  ----------  ----------------  ------------  -----------  ------------  ------------  ------------  ------------  ------------  -----------  -------------  -------------  -------------  -------------  -------------  -------------  -----------  -------------  -------------  -------------  -------------  --------  --------  --------  --------  -----------------------------------------
>     11711         0        0    0        0              0              100            0             0             0          2300          3900             0           11           6660             64              0              0              0            0             19          11713              0              0              0         0         0         0         0      Sentinel Aynasha - In Combat - Cast Shoot
> ```
> 
> edit: I don't know, but does ChromieCraft or AzerothCore have any online AoWoW DB viewer like TrinityCore does, making it easier to see the current state of creatures, gameobjects, spells and quests?

I Added another spell, but doesn't metter, it worked in any case! 😜
