### ISSUE TITLE
[Warrior - Charge underground] Charge leading to underground effect - death

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1694]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

I looked at closed issues, and I see GM's closed issue of charge problem because there were no more evidence for Un'Goro fell underground problem.
This one happened when I was in Arathi Basin BG as Alliance, and warrior whos spot is marked as blue, bellow cliff tried to charge on me, while I was on cliff, leading to underground death charge. You can see his damage while he is bellow me dying :D 

![WoWScrnShot_091021_173802](https://user-images.githubusercontent.com/80590226/132899447-4b3690e8-2f34-4263-96c9-43606c6622a1.jpg)

### Expected Blizzlike Behaviour

Charge should not go underground.

### Steps to reproduce the problem

1. Play any class or race
2. Be above warrior on cliff or any object
3. Try to charge from bellow as warrior on target who is above
4. Happens that those things leads warrior to death

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. We do have an open ticket for charges clipping through the ground and plunging the charger to their deaths - see https://github.com/azerothcore/azerothcore-wotlk/issues/6232. So will close this as a known issue.
