### ISSUE TITLE
Quest text wrong in quest tracker

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#1696]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [x] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

For several quests, the text displayed in the built-in quest tracker is incorrect regarding the location of the ending NPC, even though that displayed in the quest log is correct:

1. Ferocitas the Dream Eater: This quest should be turned in to Tallonkai Swiftroot, who is on the top floor of the tower at Dolanaar. But in the quest tracker, the text asks players to go to this person at Lake Al'Ameth.
2. Stocking Jetsteam: This quest should be turned in to Pilot Bellowfiz, who is at Steelgrill's Depot. But in the quest tracker, the text asks players to go to this person at Tundrid Hills.
3. Frostmane Hold: This quest should be turned in to Senir Whitebeard, who is at Kharanos. But in the quest tracker, the text asks players to go to this person at Shimmer Ridge.

These could be client-side issues but I don't know.

### Expected Blizzlike Behaviour

See "Current Behaviour". The locations given in the quest tracker are wrong for sure. I don't know whether this is a Blizzlike bug though. The issues are about text in quest tracker, which is not recorded by online databases (like wotlkdb.com). 

### Steps to reproduce the problem

1. Turn on built-in quest tracker.
2. Create a char to accept and complete the aforementioned three quests.
3. See what the quest tracker says.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by discorder0** [comment]
@Azcobu, sorry but I realized that another quest (Twisted Hatred) also ends at Tallonkai Swiftroot (the same NPC for Ferocitas the Dream Eater), and it is affected by the same issue (the text in quest tracker gives wrong location of this NPC). Thanks.

**Comment by Azcobu** [comment]
Thanks for the update, I'll take care of it.
