### ISSUE TITLE
[Hunter - Flare] Ability has higher range than shown to players

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1699]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When hunter is using this spell he sees normal green circle for using AOE spell, but we see lower part of it on the ground, so what actually happens is that I as rogue get caught when I'm out of range (how it looks to me), but actually FLARE has effect on that part.

Let's analyse the first screenshot, those circles:
-Red circle is what players see when he casts FLARE
-Green circle is what hunter sees when casting spell

Problem is I see RED but I get caught when I get near Green, which I Cannot see. Flare needs to be fixed by increasing it's range to be seen by players.

![WoWScrnShot_091121_114854](https://user-images.githubusercontent.com/80590226/132944100-740e6b15-214e-4f72-a476-4d4754306683.jpg)

Second screenshot, look where FLARE is, and where I'm

![WoWScrnShot_091121_114856](https://user-images.githubusercontent.com/80590226/132944137-ddcf0bd0-ec77-4790-beec-6000daff21ab.jpg)

Third screenshot, look what hunter told me to confirm.

![WoWScrnShot_091121_114911](https://user-images.githubusercontent.com/80590226/132944152-3bd9cb32-afea-40d8-b098-5b56a3344275.jpg)

This is not same report as Flare revealing people before it lands, the other issue is https://github.com/chromiecraft/chromiecraft/issues/650 and is closed.

### Expected Blizzlike Behaviour

https://classic.wowhead.com/spell=1543/flare#comments

Flare should reveal people on the location where we can see it.

### Steps to reproduce the problem

1. Make hunter use flare near invisible target outside of our visible area
2. Visible area to hunter, but not to players get's revealed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Can confirm that the range is longer than the visual aspect:
![image](https://user-images.githubusercontent.com/53914190/132958746-8a5b3363-407b-4279-9434-bbb17ea3bda9.png)

But I can't find where in the provided source that it states anything with the visual element. Although, I did find that the range is even longer that the displayed circle of the hunter. Below cast still reveals the rogue:
![image](https://user-images.githubusercontent.com/53914190/132959083-2620b20d-f391-4971-9a9c-66e9049102ac.png)
![image](https://user-images.githubusercontent.com/53914190/132959102-a9363db0-b892-4fca-aabf-0e1bf4e803c7.png)

But without a more clear source, or someone with more game knowledge to confirm, I'd wait for someone else to confirm/deny. Then again, I don't think it's a bold claim to say that you should be able to see where it ends.

**Comment by Elexias** [comment]
@jamadaha There is a reason why flare is visible on the ground, so we can se where it ends. Consecration from Paladins is working properly and can be seen fully. Flare is not.

**Comment by Shineslippers** [comment]
[Flare](https://wowgaming.altervista.org/aowow/?spell=1543) description states:
> Exposes all hidden and invisible enemies **_within 10 yards_** of the targeted area for 20 sec

Radius of ability seems correct from what i can say after tests. There  is issue with radius of animation it's about 6-8 yd. There was a [fix](https://wowpedia.fandom.com/wiki/Flare?oldid=2378631) regarding to radius:
> World of Warcraft Patch 1.7.0 (13-Sep-2005): Fixed the tooltip to accurately reflect the actual radius of the effect.

On this video https://youtu.be/RtkraBQbpgI?t=146 animation doesn't reflect actual radius. Same there https://youtu.be/cZBemXyvHys?t=188. If you will find more info will be apreciated, but for now i have to close this report.
