### ISSUE TITLE
NPC audio banter heard from afar

### ISSUE THREAD

**Issue by a-man-of-culture** [chromiecraft/chromiecraft#17]
##### SMALL DESCRIPTION:

You can hear lazy peons from a fairly big range, even underground.
https://vimeo.com/501255732

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC sounds should fade out with distance.

##### CURRENT BEHAVIOUR:

When Lazy Peon NPCs say their classic WC3 "Work-work!", you can hear them from half a valley away, even in the cave.
The volume is like they are standing right next to you.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Valley of Trials.
2. Find a Lazy Peon.
3. Get some distance.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
Looks like an issue in the client, nothing we can do. Thanks anyway for your report.

**Comment by axzn** [comment]
I know it's closed as a client issue, but just for possible future reference:

Similar bug seems to manifest itself with **fish splashing sounds coming from schools of fish**. These also seem to have infinite or very high radius. For example, when idling in Ratchet, nowhere near the shoreline, but still close enough for the schools of fish to be loaded in, I hear the splashing sounds as if they were at full volume, not attenuated as they should be.

**Comment by illfated** [comment]
Thank you for the note, I will keep that in mind. I usually notice details like that, but it has not happened to me yet, as far as I can remember. Have you tried using the 3.3.5 version of Carbonite and set the zoom camera distance to "further than the game client allows" ?

**Comment by Mitradis** [comment]
Not Client bug. On other servers no have this bug. Like warname. Reopen.

**Comment by Mitradis** [comment]
@FrancescoBorzi this happened when Lazy Peon starts chopping wood. To determine the cause, I slowly approached and listened at first. Then I looked at the map (I am a hunter), who exactly appears at this moment.
![WoWScrnShot_081721_112421](https://user-images.githubusercontent.com/21084600/129691160-2bc7c9c9-3792-47f0-82f2-e491f8349be0.jpg)

**Comment by Mitradis** [comment]
@FrancescoBorzi @Sedatyf this happened when Lazy Peon starts chopping wood. To determine the cause, I slowly approached and listened at first. Then I looked at the map (I am a hunter), who exactly appears at this moment.
![WoWScrnShot_081721_112421](https://user-images.githubusercontent.com/21084600/129691160-2bc7c9c9-3792-47f0-82f2-e491f8349be0.jpg)

**Comment by Mitradis** [comment]
if you don’t open it, I will have a reason to think.

**Comment by FrancescoBorzi** [comment]
@Mitradis you check on TC 3.3.5a for the same bug

**Comment by Faq** [comment]
Actually that is not "VUK VUK" what they say, but work, work before start to cut the tree. Those peons are lot in that zone, so no wonder they can be heard.

The same behavior on:
`TrinityCore rev. 94c03b2107ad 2021-01-01 04:03:52 +0100 (3.3.5 branch), wow client enUS`

**Comment by Mitradis** [comment]
@FrancescoBorzi I do not understand, this is a bug, I indicated what the problem is and how to determine it. But don't you want to open? Okay, you hate me, it's mutual, but what does the bug have to do with it? Do you hate the horde?

**Comment by Mitradis** [comment]
it's just a waste of time. you just want to be right and don't want to admit that you were wrong and this is a server bug.

**Comment by Faq** [comment]
@Mitradis like I mentioned in other issue reported with sounds. Can you show any proof that such sound behavior is not blizzlike? If yes, link it.

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9525
Sniff obtained. Issue validated. Pr put in to correct it.
