### ISSUE TITLE
Valley of Trials Skinning Drops

### ISSUE THREAD

**Issue by aceangelwing** [chromiecraft/chromiecraft#170]
##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

NPC: [Mottled Boar](https://wowgaming.altervista.org/aowow/?npc=3098#skinning)
NPC: [Scorpid Worker](https://wowgaming.altervista.org/aowow/?npc=3124#skinning)

Item: [Medium Leather](https://wowgaming.altervista.org/aowow/?item=2319#contained-in-item)

Zone: [Durotar](https://wowgaming.altervista.org/aowow/?zone=14)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

These boars and scopidsshould skin for Ruined Leather Scraps, or Light Leather when skinned.

##### CURRENT BEHAVIOUR:

Mottled Boars and Scorpid Workers skin mostly Medium Leather and occasionally Light Leather and Medium Hides. A scorpid and a boar also dropped a [red whelp scale](https://wowgaming.altervista.org/aowow/?item=7287)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Go to some Mottled Boars or Scorpid Workers found in the Valley of Trials.
Step 2 Kill and skin them, it should readily drop Medium Leather.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
Similar, but not identical, to the issue ticket https://github.com/chromiecraft/chromiecraft/issues/38 (**Skinnable Level 1-2 Duskbats in Deathknell**).

Also notice the discussion after that ticket got closed, from comment https://github.com/chromiecraft/chromiecraft/issues/38#issuecomment-783991321 and below.

**Comment by necropola** [comment]
This is actually the same issue. Maybe it would be better to have this all grouped under a generic issue "Creatures in starting areas should not be skinnable".

**Comment by aceangelwing** [comment]
I'm pretty sure they are supposed to be skinnable in wrath. Every database I look at has a skinning loot table for them. https://wowgaming.altervista.org/aowow/?npc=3098#skinning

**Comment by necropola** [comment]
Those DBs may or may not be correct. Probably not.
There was a change during WotLK which made all (but a few) starting area mobs neutral and no longer skinnable. IMHO, anything better than Runined Leather Scraps should definitely not drop as skinning loot from such low level mobs.  See: https://github.com/chromiecraft/chromiecraft/issues/38#issuecomment-776251209

**Comment by Helias** [comment]
On TC these NPCs have the skinning loot.
I don't know what should we do for this, if removing or not the skinning loot, on wowhead classic and the last there is no skinning loot, but I need some retail proof for Wotlk.

I am closing this issue, we need proof to be sure before removing the skinning loot even for these NPCs.

**Comment by cachocarne** [comment]
2021.09.27
Scorpid Workers still drop Medium Leather and Medium Hides, which makes no sense. According to database, they should only give Ruined Leather Scraps (88%)or Light Leather (10%)
https://wotlkdb.com/?npc=3124#skinning

Twinstar DB, however, lists Medium Leather with the highest probability, which makes no sense for a mob lvl 3 [https://wotlk-twinhead.twinstar.cz/?npc=3124#skinning]

![ 2021-09-27 at 23 46 27](https://user-images.githubusercontent.com/77953030/134984183-79d4a3bc-23d6-4dc6-8824-c53ae8b82efb.png)

**Comment by cachocarne** [comment]
And FOR SURE they shouldn't drop Red Whelp Scale !!!  https://wotlk.evowow.com/?item=7287
![ 2021-09-28 at 00 08 23](https://user-images.githubusercontent.com/77953030/134985791-ec0f819a-783d-41ed-a60d-c9a02e36e349.png)
