### ISSUE TITLE
Incorrect Northfold Manor Rewards

### ISSUE THREAD

**Issue by plankgg** [chromiecraft/chromiecraft#1700]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

![WoWScrnShot_091121_113543](https://user-images.githubusercontent.com/90416511/132945418-8ed3d9d7-1850-4b12-8733-0a0425026283.jpg)

This quest only gives 250xp for killing 16 mobs. Not sure if it's because of my level or not, but this unlocks another quest which gives rewards like 4900xp

### Expected Blizzlike Behaviour

Upon completion of this quest you will gain:
2,540 experience
250 reputation with Stormwind

https://wowgaming.altervista.org/aowow/?quest=681

You only receive 250xp and no reputation at all
![WoWScrnShot_091121_115555](https://user-images.githubusercontent.com/90416511/132945479-f2bed485-d80a-453b-9644-490b22ed67cf.jpg)

### Steps to reproduce the problem

1. Pretty sure Captain Nials starts the quest in Arathi Highlands
2. I've only noticed this when I was lvl 41 and decided doing it after googling what quests it can lead to.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Works fine for me:
![grafik](https://user-images.githubusercontent.com/68868567/132946672-06b34fc1-c120-423c-8def-31f70929ea4d.png)
Did you deactivate the rep gain in the chat settings?

**Comment by plankgg** [comment]
Yeah, probably what happened, I just forgot the xp gain is so low as well.
