### ISSUE TITLE
4 items appear in wrong loot tables

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1704]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

4 items appear in wrong loot tables
Namely, item ids:
22330
22317
22305
22318 (already fixed)

### Expected Blizzlike Behaviour

These items drop only from arena spoils chest.

### Source

https://classic.wowhead.com/object=181074/arena-spoils

https://classic.wowhead.com/item=22317/leftys-brass-knuckle

https://classic.wowhead.com/item=22330/shroud-of-arcane-mastery

https://classic.wowhead.com/item=22305/ironweave-mantle

### Steps to reproduce the problem

Run the query:

select creature_template.name, creature_loot_template.entry, creature_loot_template.chance from creature_loot_template join creature_template on creature_loot_template.Entry=creature_template.lootid where creature_loot_template.item="22330";

run the query also with other item ids

### Extra Notes

related:

https://github.com/chromiecraft/chromiecraft/issues/1628

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, I noticed these items when dealing with your original report for item 22318, and ended up clearing out the loot tables for the various BRD arena team members, which removed all these items from their drop tables as well. You can see the details in the PR here: https://github.com/azerothcore/azerothcore-wotlk/pull/7728. This PR has been merged to the main AC branch, so if you update your copy of AC to the newest version and run either your query above or the one I supply in the PR, you should get zero results back.
