### ISSUE TITLE
Mai'Zoth not spawning after waiting for almost 10 minutes

### ISSUE THREAD

**Issue by keelmae** [chromiecraft/chromiecraft#1706]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Stood in the spot in the cave where he is supposed to spawn.  Killed the mob in the area 3 times while waiting and he still didn't spawn.  Killed everything in the cave just to make sure that my coordinates weren't wrong
![Capture](https://user-images.githubusercontent.com/90533467/132990350-1e116d02-f232-4582-af49-acad622d96e1.JPG)

### Expected Blizzlike Behaviour

https://classic.wowhead.com/quest=206/maizoth

The only difference is they are no longer elites in the cave

### Steps to reproduce the problem

kill mob in area
wait
kill mob again
wait some more
kill mob again
sadly give up and leave the cave :-(

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
Mai'zoth has a 30 minutes respawn timer. While the elite status of mobs was changed in patch 2.3.0, the spawn times were not adjusted for several Npcs in Stranglethorn Vale, Mai'zoth being one of them. From Cataclysm onwards the spawn times got reduced.

https://wowpedia.fandom.com/wiki/Mai%27Zoth
https://www.wowhead.com/npc=818/maizoth#comments
