### ISSUE TITLE
Repetable quests in Blasted Lands should have blue exclamation marks instead of yellow

### ISSUE THREAD

**Issue by mdawx** [chromiecraft/chromiecraft#1707]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Following repetable quests have yellow explanation marks:
* https://wowgaming.altervista.org/aowow/?quest=2602
* https://wowgaming.altervista.org/aowow/?quest=2604
* https://wowgaming.altervista.org/aowow/?quest=2582
* https://wowgaming.altervista.org/aowow/?quest=2584
* https://wowgaming.altervista.org/aowow/?quest=2586
* https://wowgaming.altervista.org/aowow/?quest=3502

### Expected Blizzlike Behaviour

Repeatable quests should appear as blue exclamation marks.

### Source

https://wowwiki-archive.fandom.com/wiki/Repeatable_quest

### Steps to reproduce the problem

1. .go npc 2685
2. Finish required for every quest for 2602 you need to finish 2601 https://wowgaming.altervista.org/aowow/?quest=2601
3. See yellow yellow exclamation mark.

### Extra Notes

Similar issues was resolved, for example: https://github.com/azerothcore/azerothcore-wotlk/issues/1862.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
On a local instance of AC, I found the quest to have yellow question marks as stated. But I'm not quite sure whether that's incorrect. I found this [video](https://www.youtube.com/watch?v=AalsQFT2Qy4) from 2010, showing specifically quest 3502 'One Draenei's Junk...' to have a yellow question mark. Tho, not certain whether it's retail.

**Comment by mdawx** [comment]
You are right. I think they are 3 types of quests:
* Daily (blue exclamation mark and question mark)
* AutoComplete - (only blue question mark) 
* rest (normal quests, weekly and seasonal and repeatable)

**Comment by gurveleg** [comment]
Indeed. The quest can be repeated multiple times per day and is thus not counted as a daily quest with a blue !/? marks. Its a repeatable quest that also utilizes yellow marks like normal and seasonal quests do.
If you look at WoW classic Wowhead, it also shows yellow marks for those quests, for example:
https://classic.wowhead.com/quest=2584/spirit-of-the-boar
https://classic.wowhead.com/quest=3502/one-draeneis-junk

I will close this accordingly.
