### ISSUE TITLE
Warrior charge bug

### ISSUE THREAD

**Issue by Pudjero** [chromiecraft/chromiecraft#171]
##### ISSUE: FACTION SIDE:
 ![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:
any phase i guess

##### SMALL DESCRIPTION:

Spell: [Charge](https://wowgaming.altervista.org/aowow/?spell=100)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When i charge in movement i must move into target

##### CURRENT BEHAVIOUR:
When i charge in movement i just get rage and not even start combat
[video](https://www.youtube.com/watch?v=BSRXd6kf3a4)

##### STEPS TO REPRODUCE THE PROBLEM:
1. Target any mob
2. Move and use charge at the same time

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by Stifler82** [comment]
In my opinion Charge works well and does not need any Fix, as you can see from my video..
**Video Test:** [Charge](https://youtu.be/GAqi6ebgUfo)
