### ISSUE TITLE
Mining Nodes and Herbs can be abused to level up your profession skill

### ISSUE THREAD

**Issue by VFaleiro** [chromiecraft/chromiecraft#1714]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

You can level up your Mining or Herbalism by gathering the same (yellow-level or green-level) node over and over again if you do not loot everything.
You can only get 1 skill level up per node spawn though.

You can get to max-level of those professions in very little time because of this.

### Expected Blizzlike Behaviour

The first time you mine/gather a specific node, the server rolls if you will get a level up, and it won't matter how many times you spam it, if you do not get a skill level up on the first successful try, you won't get one at all (that is for that specific spawn, if someone else gathers it and it respawns or if server reset/crash, the spawn/temporary ID of the object is reset and you can again get a skill level up).

### Steps to reproduce the problem

1. Have Mining or Herbalism leveled up a bit
2. Find a yellow-level or a green-level node (green-level makes this bug more noticeable)

So, for example:
- level up your mining to 175 (which is where [Iron Deposits](https://wowgaming.altervista.org/aowow/?object=1735) becomes green-level) 
- level up your herbalism to 51 (which is where [Peacebloom](https://wowgaming.altervista.org/aowow/?object=1618) becomes green-level)

3. Right click it (make sure you have auto-loot toggled off, if you use that feature)
4. Do not pick anything or at least leave 1 item still there so the node won't despawn.
5. Close the loot window.
6. Right click it again.
7. Close loot window.

Repeat step 6 and 7 until you get a skill level up. A skill level up is RNG, so you may have to try a few times, but usually that happens before the fourth try for green-level nodes.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report, but this is a duplicate issue.
Moreover, it is a non-bug see https://github.com/chromiecraft/chromiecraft/issues/1491#issuecomment-903194332.
