### ISSUE TITLE
Plans:  Lionheart Helm not included in Eternium Lockbox loot table

### ISSUE THREAD

**Issue by jeskej** [chromiecraft/chromiecraft#1715]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Querying the item_loot_template table does not show Lionheart plans dropping.

### Expected Blizzlike Behaviour

Lionheart plans should be contained in Eternium Lockboxes and possibly drop from elite world monsters 61+

### Source

Classic/TBC wowhead show drop chance
https://classic.wowhead.com/item=12717/plans-lionheart-helm#contained-in-item
https://tbc.wowhead.com/item=12717/plans-lionheart-helm#contained-in-item

Wowpedia indicates it can also be dropped by elites 61+
https://wowpedia.fandom.com/wiki/Plans:_Lionheart_Helm

### Steps to reproduce the problem

1.  Query item loot template:
select * from item_loot_template where item = 12717;
Empty set (0.03 sec)

2.  Query creature loot template:
select Item,Chance,Comment from creature_loot_template where item = 12717;
+-------+--------+-----------------------------------------------+
| Item  | Chance | Comment                                       |
+-------+--------+-----------------------------------------------+
| 12717 |   0.02 | Blackhand Elite - Plans: Lionheart Helm       |
| 12717 |   0.02 | Blackhand Iron Guard - Plans: Lionheart Helm  |
| 12717 |   0.02 | Rage Talon Captain - Plans: Lionheart Helm    |
| 12717 |   0.02 | Thuzadin Necromancer - Plans: Lionheart Helm  |
| 12717 |   0.02 | Hakkari Shadow Hunter - Plans: Lionheart Helm |
| 12717 |   0.02 | Gurubashi Berserker - Plans: Lionheart Helm   |
| 12717 |   0.02 | Firelord - Plans: Lionheart Helm              |
| 12717 |   0.14 | Lord Kazzak - Plans: Lionheart Helm           |
| 12717 |   0.02 | Hive'Zara Wasp - Plans: Lionheart Helm        |
+-------+--------+-----------------------------------------------+

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
I'm gonna close this one as the two reports are duplicates. And this also seems to focus on the known issue.
