### ISSUE TITLE
I have the same problem, improved judgements doesnt work properly if I mix judgements in rotation.

### ISSUE THREAD

**Issue by shirutzen** [chromiecraft/chromiecraft#1718]
I have the same problem, improved judgements doesnt work properly if I mix judgements in rotation.
I think its maybe cuz the talent work as a buff, if I use certain judgement it rests 2 secs of cooldown, but just to that judgement, not the others which dont have the "2 seconds less buff", so to fix make the "buff" to apply to every judgement, or put the condition to every judgement  as this, J1c, j2c, j3c, j4c, ..., jnc = 10sec ; if imp jgmnt lvl 2 then all jdgmnt cd - 2, idk its my opinion
client: esES
OS: windows 10
backets: 10-19, 20-29
faction: alliance

_Originally posted by @shirutzen in https://github.com/chromiecraft/chromiecraft/issues/1608#issuecomment-918333335_

**Comment by gurveleg** [comment]
you should have commented on that issue instead of opening a new one :)
