### ISSUE TITLE
[NPC][Tanaris] Voidwalker Minion, Wastewander Shadow Mage's pet

### ISSUE THREAD

**Issue by Xshade** [chromiecraft/chromiecraft#1719]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Voidwalker Minions doesn't attack players until they (minions) are hit by the player but they still have aggro on the player.
https://youtu.be/m1WWtdJd6qY

~~Before most recent update Voidwalker Minions despawned once Wastewande Shadow Mage was killed and after the update they didn't and i thought it was bugged but found wowhead comment from patch 2.4.3 stating that they doesn't despawn after shadow mage is killed. After 13th September ChromieCraft update that's is fixed~~

### Expected Blizzlike Behaviour

Minions should attack once their have aggro on player or its master (wastewander shadow mage) is being attacked or start attack player.

### Steps to reproduce the problem

Teleport to this mob
Wastewander Shadow Mage .npc info
```
DB GUID: 23523, current GUID: 5212.
Faction: 16.
npcFlags: 0.
Entry: 5617.
DisplayID: 5530 (Native: 5530).
Level: 43.
EquipmentId: 1 (Original: 1).
Health (base): 1442. (max): 1442. (current): 1442.
Unit Flags: 0.
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 16.
SpawnTime: Full:5m Remain:0s
Loot: 5617 Pickpocket: 5617 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 1811
Position: -7688.852051 -4253.654785 9.466969.
AIName: SmartAI ScriptName: 
MechanicImmuneMask: 0
SpellSchoolImmuneMask: 0
```
Attack only the mage, once its pet have aggro on you kill the mage and observe combat log for attack coming from the pet
Voidwalker Minion .npc info
```
DB GUID: 0, current GUID: 32133.
Faction: 16.
npcFlags: 0.
Entry: 8996.
DisplayID: 1132 (Native: 1132).
Level: 43.
EquipmentId: 0 (Original: 0).
Health (base): 2215. (max): 2215. (current): 2215.
Unit Flags: 0.
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 16.
SpawnTime: Full:5m Remain:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 3228
Position: -7684.569824 -4250.811035 9.168447.
AIName: SmartAI ScriptName: 
MechanicImmuneMask: 0
SpellSchoolImmuneMask: 0
```

### Extra Notes

Don't attack the voidwalker, since this is the only way for it to trigger its attack versus the player character.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Ty for the report! Yes, it is a known issue with minions/pets from NPC's: https://github.com/azerothcore/azerothcore-wotlk/issues/6239

**Comment by Xshade** [comment]
ah my bad i tried to search for but i missed it probably
anyway sorry fot the double report
