### ISSUE TITLE
habilidad "Cargar" de la pet del cazador BUG.

### ISSUE THREAD

**Issue by RacsHunter** [chromiecraft/chromiecraft#1720]
### What client do you play on?

esES

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

En primer lugar, la habilidad "Cargar" de la pet esta bug, cosas que pasan:
1. La pet carga pero deja de atacar quedándose inmóvil.
2. La reutilización de la habilidad "Cargar" es instantánea con el macro : /petattack y /cast Cargar
3. Cuando el pet "Carga" al objetivo, las siguientes habilidad que se usen con la opción de "instantáneo", como por ejemplo "bofetada" o "pisotón de trueno", no son ejecutadas. Solo se ejecutan automáticamente si no se usa cargar.

### Expected Blizzlike Behaviour

La pet deberia "Cargar" y tener un cd de 25 segundos para recién después de pasado el tiempo, poder lanzar "cargar" nuevamente; la pet debería atacar continuamente y perseguir al objetivo después de usar el macro /peattack y /cast Cargar.

### Source

Fuente :
https://es.wowhead.com/spell=61685/cargar
ejemplo : 
https://www.youtube.com/watch?v=oQBr2zct8t4

### Steps to reproduce the problem

1. macros que uso : /cast Marca del cazador(Rango 2)
/petattack
/cast Cargar
2. No
3. Si

### Extra Notes

probar con cualquier  monstruo jugador dentro del juego. 
Mi nombre como jugador es : Racs , hunter level 49.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gadixsp** [comment]
Not sure the policy on non- English comments but I'll translate here if anyone needs: 

Current Behaviour
Mainly, the pet ability "charge" is bugged and this is what happens: 

The pet charges but stops attacking and doesn't move. 
"Charge" can then be reused instantly with the macro: /petattack /cast Charge
When the pet charges the target, any subsequent moves set to automatically cast, such as slap or thunder clap, are not used. They are only automatically cast if charge is not used. 

Expected Blizzlike Behaviour

The pet should charge and have a 25 sec cooldown before being able to use it again;  the pet should attack continually and follow the target after using the macro /petattack /cast Charge

Source
Source :
https://es.wowhead.com/spell=61685/cargar
Example:
https://www.youtube.com/watch?v=oQBr2zct8t4

Steps to reproduce the problem

Macros that I use: /cast Hunter's Mark(Rank 2)
/petattack
/cast Charge
No
Yes

Extra Notes

Test with any monster player [sic] in game. 
[Not sure if he left out a word or there's something I'm not understanding there] 
My player name is: Racs, hunter level 49.

**Comment by Shineslippers** [comment]
@RacsHunter I can't reproduce it on local AC with mentioned steps. Am i missing something? 

https://user-images.githubusercontent.com/85256266/142766446-dba820d8-8da4-4a48-ab54-9387995bb4eb.mp4

**Comment by acidmanifesto** [comment]
no further follow up from poster. will close. If the matter is still happening please open up a new ticket.
