### ISSUE TITLE
[Un'Goro - Ooze covered veins] Few of them not spawning inside caves (underground)

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1721]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Ooze covered veins are always spawned inside caves, underground parts.
Here some of them which I posted screenshots are on the ground level.
![WoWScrnShot_091421_174555](https://user-images.githubusercontent.com/80590226/133291040-c4683f58-1cfe-4efb-a84e-4e9a585da167.jpg)
![WoWScrnShot_091421_174534](https://user-images.githubusercontent.com/80590226/133291042-e6fce7d2-ce60-4b20-b8f4-22b27da5b742.jpg)
![WoWScrnShot_091421_174518](https://user-images.githubusercontent.com/80590226/133291047-2d48df4e-89b6-4b89-85b2-45afe5596196.jpg)
![WoWScrnShot_091421_174556](https://user-images.githubusercontent.com/80590226/133291052-92bb2414-85f8-416b-8da4-67b502162321.jpg)

### Expected Blizzlike Behaviour

Ooze covered veins should be spawned underground on same location.

### Steps to reproduce the problem

1. Get to that part of Un'Goro (The Slithering Scar location)
2. Watch veins of Ooze covered being on the ground

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. Unfortunately i didn't find any sources what saying it's should be in caves. It's bounded to insects locations.

**Comment by Elexias** [comment]
There is a reason why it is called Ooze Covered, It is always spawned INSIDE caves.
https://classic.wowhead.com/object=123848/ooze-covered-thorium-vein#mining

**Comment by Shineslippers** [comment]
Covered of Ooze. Idk how it's related to a caves. Anyway if you will find some sources would be great.

**Comment by Elexias** [comment]
https://wowpedia.fandom.com/wiki/Ooze_Covered_Thorium_Vein

"Ooze Covered Thorium Veins can be found **inside** the Slithering Scar in Un'Goro Crater.[50.0, 81.6] In Classic,"

**Comment by Shineslippers** [comment]
`Slithering Scar` It's the name of sub-zone. It's not a cave. So you can read it as `inside sub-zone`.
