### ISSUE TITLE
[STV - The Hinderlands Quest - Grim Message] Nimboya's Pike usable only in one of the villages

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1723]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Note: I found this screenshot, happened on lvl 39 and not sure if this is fixed, I did look on CLOSED issues with name Grim, Nimboya and I didn't see any bug report. 

On screenshot you can see player who already completed quest telling me how to complete it since I did try in one of the villages and it didn't work. Happens that only works when used in 1 out of 2 villages. Should be usable in both. Again sayin' I can't check it anymore as I have completed quest and not sure if it works now or not.
![WoWScrnShot_062121_171913](https://user-images.githubusercontent.com/80590226/133309075-ce4ef8d9-e252-4bba-9b4f-248aff424d35.jpg)

### Expected Blizzlike Behaviour

https://classic.wowhead.com/quest=2932/grim-message

Comment:
Even though you pick this up in STV, the quest takes place in the Hinterlands (you get there through Hillsbrad if you haven't already). Any of the Witherbark troll villiages work. If you can't find one 29,58.

### Steps to reproduce the problem

1. Take quest from Grom'Gol Base camp in STV named Grim Message
2. Kill 20 mobs, use Nimboya pike in Hiri'Watha troll villages, using in one won't work, using in 2nd will work. I'm not sure atm which one worked and which not, but someone who can test on PTR can check both locations
3. Using pike only works on one of those two, not sure which one, this was long time ago

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
I guess I can confirm this.

Just tried this quest, gathered the [20 skulls](https://wowgaming.altervista.org/aowow/?item=9320), used it with  the [provided item](https://wowgaming.altervista.org/aowow/?item=15002) to create [Nimboya's Laden Pike](https://wowgaming.altervista.org/aowow/?item=9319), but it can't be used in Zun'watha (around 23 / 58).

Tried again in Hiri'watha, it worked.
