### ISSUE TITLE
[Felwood - NPC loot] Jadefire Rogue dropping low level item

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1724]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Note: This happened when we were on beta lvl 39, not sure if this is fixed now. I did search for closed and open issues here named Jadefire, Felwood and low drop, nothing found, so maybe not fixed.

You can see level 50 mob dropping low level item. Loottable is wrong.
![WoWScrnShot_062621_211736](https://user-images.githubusercontent.com/80590226/133309853-6f020d04-6dab-4def-8654-ecd3365ab8c1.jpg)

### Expected Blizzlike Behaviour

https://classic.wowhead.com/npc=7106/jadefire-rogue

Low level items are not in his loot table

### Steps to reproduce the problem

1. Kill bunch of Jadefire Rogues or any other Jadefire mob maybe
2. Test their lootable  

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. This was fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/6610, so shouldn't be an issue on current AC installs or on Chromie any more. Closing this accordingly.
