### ISSUE TITLE
Absorbed damages doesn't stop flag capping in Arathi Bassin (PVP)

### ISSUE THREAD

**Issue by Korghan905** [chromiecraft/chromiecraft#1726]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Absorbed damages doesn't stop flag capping in Arathi Bassin (PVP)

### Expected Blizzlike Behaviour

Damages, even if absorbed by a priest shield for example, should stop capping a flag.
It makes priest very strong at capping...

### Steps to reproduce the problem

priest
shield
cap
damage
absorbed
capping not interrupted

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report.
There seems to be missing a source, but I found one from TBC [here](https://youtu.be/ZYb5SVo4dz0?t=75). But I can't find one for WOLTK, so as this would be larger change, I'd wait for someone else to confirm.
(Haven't tested whether the current behaviour occurs on a local AC)

**Comment by j-hdt** [comment]
Can only confirm from memory (and seeing this bug on many private servers).
Being hit by a direct damage spell/ability should interrupt capping. Not interrupting the capping attempt when resisting or being missed.
Also channeled spells should not interrupt, as should ground effects like the paladins consecration or the damage ticks from flamestrike
