### ISSUE TITLE
You can learn Field repair bot without being engineer

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1728]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

You can learn Field repair bot without being engineer (can craft only after being an engineer)

notice the top row (don't have a better picture as unlearning and relearning engineering removed it)
![image](https://user-images.githubusercontent.com/84640316/133336655-55d60590-fb13-4dcf-aaba-451c815c8d00.png)

### Expected Blizzlike Behaviour

you shouldn't be able to learn it. 

### Source

https://classic.wowhead.com/item=18235/schematic-field-repair-bot-74a#comments

### Steps to reproduce the problem

Make sure you are not an engineer
Go to Brd, right click the scroll on the ground
train engineering

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I visited the scroll in BRD and clicked on it, but got this:

![WoWScrnShot_091521_224942](https://user-images.githubusercontent.com/81782124/133440983-956bbbe2-4fa0-473b-bc49-1cd94ea14344.jpg)

Then went and learned Apprentice Engineering, but it didn't show up in the spellbook:

![WoWScrnShot_091521_225050](https://user-images.githubusercontent.com/81782124/133441066-5e4e4c9e-eedd-4190-985f-0c5168bbd095.jpg)

The doubled skills are ugly, but are a known issue (https://github.com/azerothcore/azerothcore-wotlk/issues/7415) But not seeing the Field Repair Bot in there, so couldn't replicate this. Had your character been an engineer and then unlearned it before accessing the scroll in BRD?

**Comment by baranzadeoglu** [comment]
>Had your character been an engineer and then unlearned it before accessing the scroll in BRD?

Yes actually this was the case a long while ago. I think I was an engineer (sub 150) at some point. 
Even if that is a trigger, there also is the issue that you shouldn't be able to learn it from scroll before 300 engi.

**Comment by Gultask** [comment]
Whatever changed it's not an issue anymore, and I can't find anything in the AC repo to find out what caused the change.

I tested it and the option to learn it is only available to 300 skill engineers.
