### ISSUE TITLE
Gathering Leather should be a skinning quest

### ISSUE THREAD

**Issue by Cosmic-Cocoa** [chromiecraft/chromiecraft#173]
##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Quest: [Gathering Leather](https://classic.wowhead.com/quest=768/gathering-leather)
NPC_Start: [Veren Tallstrider](https://classic.wowhead.com/npc=3050/veren-tallstrider)
NPC_Start: [Veren Tallstrider](https://classic.wowhead.com/npc=3050/veren-tallstrider)
This quest shouldn't be offered to non-skinners.
![Gathering Leather](https://user-images.githubusercontent.com/78349628/110269922-56003280-7f8a-11eb-9aee-6b414a70e5b2.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be required to have the skinning skill to pick up this quest.

##### CURRENT BEHAVIOUR:

This quest is offered to anyone as far as I can tell (or at the very least, to my tauren druid who is herbalist / alchemy).

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1. Teleport to Veren Tallstrider.
Step 2. See if he offers the quest to you.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by AbraKabastard** [comment]
[Source](https://github.com/TrinityCore/TrinityCore/commit/60835936c43efa5c79be60b1886b139cf6a432b5)
```-- 
DELETE FROM `quest_template_addon` WHERE `ID`=768;
INSERT INTO `quest_template_addon` (`ID`, `RequiredSkillID`, `RequiredSkillPoints`) VALUES
(768, 393, 1);
```

**Comment by Helias** [comment]
@AbraKabastard, that's it, could you create a PR on azerothcore?
Moreover, do you have Discord? could you contact me? Helias#9347

Anyway, thanks for the fix

**Comment by AbraKabastard** [comment]
I will try to familiarize myself with pull requests and get right on it.
I have sent you the friend request on Discord, I am also under the same moniker in the servers channel.

**Comment by nicoaravena** [comment]
I confirmed this on my local env just have extra confirmation.
