### ISSUE TITLE
[Battleground] Blizzard incorrectly interrupts flag capping

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1731]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Mage spell Blizzard (https://wowgaming.altervista.org/aowow/?spell=10#see-also) interrupts flag capping in AB.

https://user-images.githubusercontent.com/80769357/133420832-4d5891b5-0b9d-491d-bd66-8d04419da157.mp4

### Expected Blizzlike Behaviour

Blizzard like other AOE or DoTs without direct damage component (for example flamestrike intial hit interrupts, dot ticks don't) should not interrupt casting when capping/defending the flag. 

Bynir
<Läst Pull>
1990 posts
60 Night Elf Druid
24990
Dec '19

Normal. DoTs don’t tend to interrupt flag capping unless there is a direct damage component (eg. Moonfire) and ‘drop and forget’ abilities like Rain of Fire and Blizzard also do not interrupt flag caps.

Tuskamus
3853 posts
50 Troll Hunter
16095
Mar '20

Only direct damage interrupts a flag cap. Blizzard does not count, never has. Arcane explosion does however, use that next time.

<html><body>
<div class="comment-header">

By althras on 2006/09/13 (Patch 1.12.0) |   |  
-- | -- | --

</div><div class="text comment-body comment-high-rating" lang="en">Level
 1 Blizzard is an excellent spell to use even when you're level 60 to 
flush out rogues in your surroundings in PvP. If you're good with your 
mouse, your character can be facing one direction while you cast this 
spell all over the place around you. You can also maintain casting of 
this spell over yourself when defending nodes in BGs. Combined with the 
Permafrost and Improved Blizzard talents, this spell becomes and instant
 slowing tool.<br><br>However, Blizzard at any rank doesn't work for stopping flag turners in AB and AV, so don't bother.</div>
</body>
</html>

### Source

https://tbc.wowhead.com/spell=10/blizzard#comments

https://wowpedia.fandom.com/wiki/Blizzard

https://us.forums.blizzard.com/en/wow/t/not-stopping-flag-caps/471095
https://us.forums.blizzard.com/en/wow/t/stopping-flags-being-capped/379911

### Steps to reproduce the problem

1. Enter AB
2. Start capping a flag and have mage cast blizzard on your location
3. See it interrupts

### Extra Notes

If anyone has any info on the topic that would suggest otherwise, please do comment.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Korghan905** [comment]
I confirm, and can you link this bug with this issue #1726 as capping is bugged in general

**Comment by mdawx** [comment]
It may be interesting to compare with effect of Oil of Immolation, which creates an aura Fire Shield (https://wowgaming.altervista.org/aowow/?spell=11350). According to some comments it should interrupt capping, so it goes against the argument _Only direct damage interrupts a flag cap_.

https://www.wowhead.com/item=8956/oil-of-immolation#comments
