### ISSUE TITLE
[WSG - Flag Carrier] If flag carrier ends with debuff for overtime it doesn't go off

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1732]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

This guy was with me on Battleground, we finished battleground and we saw him have that debuff in middle of Orgrimmar. He did queue for new BG and still had debuff to take 50% more dmg.
![image](https://user-images.githubusercontent.com/80590226/133451722-6ddf2f95-5d64-40d6-98d0-7783cd9c0082.png)

### Expected Blizzlike Behaviour

https://tbc.wowhead.com/spell=46392/focused-assault
Debuff should go off after ending battleground.

### Steps to reproduce the problem

1. Try to carry flag for >5 mins in WSG and get debuff Focused Assault
2. Win/Lose that BG while having debuff
3. Check if debuff persists on character upon leaving BG or entering new BG

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
Screenshot taken from Support channel in Discord, was with him in BG can confirm.

**Comment by acidmanifesto** [comment]
First off Thank you for your report @Elexias and most of All I apologize for the delayed in having someone actually respond in the open about this. I am new to triage team and will Attempt to give some info on what is known right now on the matter.
Pretty much what you say is indeed a **Bug** and is **Confirmed** by another Triage Memeber.

As of right now, we have no had this bug reported on the azerothcore issues and i will be making a bug report to link it to give it more visiblity for it to be address. 

As of this writting there is currently no other reports of this issue in particular but also no currenty fix.

**Comment by Nefertumm** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/ab121e246e93e440cacba4b4b5e9e47a58b8a9f6
