### ISSUE TITLE
[Full Bags - No loot] Dissenchanting or getting loot in dungeon doesn't come with mail if bags are full

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1733]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Happened few times that my bags were full and that I have received multiple items from dissenchanting via button or just getting some random green/blue items on roll but not receiving them via mailbox because bags are full. 

Note that when my bags were FULL I DID RECEIVE SATCHEL at end of dungeon as MAILBOX reward, but other items not.

### Expected Blizzlike Behaviour

WOW CLASSIC AND BURNING CRUSADE CLASSIC
Unlooted items in WoW Classic and Burning Crusade Classic are not sent to your mailbox. Items that aren't looted will remain on the corpse until it despawns. Customer Support does not recover unlooted items.

Modern WoW
The Postmaster will send loot to your mailbox from the following:

Instances

https://us.battle.net/support/en/article/16387

### Steps to reproduce the problem

1. Be in dungeon group with enchanter
2. Win dissenchant roll or any item roll with having full bags
3. You won't receive items via bags

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
It's not a bug, it only works for satchels this way.

> WOW CLASSIC AND BURNING CRUSADE CLASSIC
Unlooted items in WoW Classic and Burning Crusade Classic are not sent to your mailbox. Items that aren't looted will remain on the corpse until it despawns. Customer Support does not recover unlooted items.

Yes, and it is like this for WotLK. With the term "modern WoW", they mean retail WoW (Shadowlands).
