### ISSUE TITLE
[Quest bug] Suntara Stones several issues

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#1745]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

- Dorius Stonetender, questgiver, walks too fast
- He has no RP text whatsoever - being attacked, needing to take breathers, etc.
- He stops only once, when he should stop at least 3 times, twice to "take a breather" & once to comment on the Cauldron
- He is ambushed by 2 spiders, but not also 2 Dark Iron Dwarves
- The "Singed Letter" item he is supposed to drop upon death is already on the ground, 40 yards ahead of him
- He does not emote pointing to the letter upon death

### Expected Blizzlike Behaviour

- He walks slowly (RP/quest text: he is badly injured)
- He should make a stop to look over the Cauldron & comment on his team down there
- He should ask for a breather when he stops & then gets ambushed
- He should speak when being attacked, nearing the end, etc
- He should be ambushed by two Dark Iron Dwarves at the same time as the spiders
- You should not be able to see the letter he is supposedly carrying, 40 yards ahead of you with a white question mark over it
- He should point at the letter as he dies

### Source

click on "quotes" https://tbc.wowhead.com/npc=8284/dorius-stonetender

https://tbc.wowhead.com/quest=3367/suntara-stones#comments:id=2958431

https://tbc.wowhead.com/quest=3367/suntara-stones#comments:id=2786724

https://tbc.wowhead.com/quest=3367/suntara-stones#comments:id=2786963

### Steps to reproduce the problem

TP to GUID 6823 (on Alliance character? Alliance quest)
Accept & complete quest

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Hi, thank you for this detailed report!
However, we already have an issue like this. I will add your info to the already existing issue.
