### ISSUE TITLE
Supplying the Front Blacksmith Quest bugged

### ISSUE THREAD

**Issue by Malthorian** [chromiecraft/chromiecraft#175]
##### CONTENT PHASE:
10-19

##### SMALL DESCRIPTION:

 https://www.wowhead.com/quest=1578/supplying-the-front 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should be accepted and go into the quest log normally.

##### CURRENT BEHAVIOUR:

I talked to the NPC quest giver Tormus Deepforge and accepted the quest.  However, it does not appear in the quest log.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Talk to the NPC with a blacksmith level of 35.
Step 2 Accept the quest Supplying the Front
Step 3 Check the quest log.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Malthorian

I have not been able to reproduce the Bug, for me the quest works as you can see..
What WoW Client Do You Have?
**enGB** or **enUS**?
Try clearing the game cache.
[WoW Folder]\Cache **(delete the contents of the folder and try again)**
**and do this with the Client NOT started.**

**Video Test:** [Supplying the Front Blacksmith](https://youtu.be/Jls9-kQAN6o)

**Comment by Malthorian** [comment]
I believe I resolved it.  It seems like a strange ui issue that your suggestion helped fix. Thanks for checking.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
