### ISSUE TITLE
Possibly wrong loot table for Commander Eligor Dawnbringer 

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1750]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

it has this loot table:

![image](https://user-images.githubusercontent.com/84640316/133561729-32b37ddf-09af-4c35-b801-d86b2ad0dfb1.png)

### Expected Blizzlike Behaviour

Either drops nothing or just the 2 pots here:

https://tbc.wowhead.com/npc=16115/commander-eligor-dawnbringer#drops;mode:normal

### Steps to reproduce the problem

query its loot table or check keira3

### Extra Notes

Similar discussion for guard/npcs supposedly dropping pots

https://github.com/azerothcore/azerothcore-wotlk/issues/7744 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Not quite sure on this one, can confirm the current behaviour, but not sure the source. If I understand it correctly, Wowhead gathers data from player feedback, in terms of loot. This doesn't fit well with this NPC, as I don't think it's one that has been killed a lot. So the potions could just be possible drops, that hasn't occurred.

**Comment by baranzadeoglu** [comment]
> Not quite sure on this one, can confirm the current behaviour, but not sure of the source. If I understand it correctly, Wowhead gathers data from player feedback when it comes to loot. This doesn't fit well with this NPC, as I don't think it's one that has been killed a lot. So the potions could just be possible drops, that hasn't occurred.

have you checked the discussion regarding npc drops at the extra notes section

**Comment by jamadaha** [comment]
@baranzadeoglu those are some valid points, I'll look into this again later

**Comment by baranzadeoglu** [comment]
> @baranzadeoglu those are some valid points, I'll look into this again later

have you had a chance to look into it? I am not trying to rush you but maybe it is better without the triaging in process label at this point.

**Comment by jamadaha** [comment]
Oh, sorry. Completely forgot about it.
