### ISSUE TITLE
Elixir of Dream Vision drops from 10 mobs

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1763]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

![image](https://user-images.githubusercontent.com/84640316/133572201-7deab505-803b-40f6-8304-4e28dbe826fd.png)

### Expected Blizzlike Behaviour

it shouldn't

### Source

https://tbc.wowhead.com/item=9197/elixir-of-dream-vision

### Steps to reproduce the problem

select creature_template.name, creature_loot_template.entry, creature_loot_template.chance from creature_loot_template join creature_template on creature_loot_template.Entry=creature_template.lootid where creature_loot_template.item= "9197";

### Extra Notes

See this for discussion about NPC drops

azerothcore/azerothcore-wotlk#7744

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Please keep in mind, that Wowhead is not the greatest source, when it comes to droprates. You are probably still right in a lot of cases.

**Comment by baranzadeoglu** [comment]
> Please keep in mind, that Wowhead is not the greatest source, when it comes to droprates. You are probably still right in a lot of cases.

Classic, tbc and live doesn't show any drops. It would be very odd if they didn't drop in tbc, then dropped in wotlk and stopped droping some time after. Especially considering that it makes no sense for these mobs to drop these items. 

There is a lot of 0.02% chance garbage in the loot tables. I think someone in the past interations of this db just sprinkled them along thinking it would be okay. This drop rate is consistent with a lot of other items (not just elixirs) that look really odd in their loot tables.

**Comment by IntelligentQuantum** [comment]
Confirm, But I'm not sure if the source for this patch is correct.
