### ISSUE TITLE
Many types of enemies of skull level to the player have short aggro range

### ISSUE THREAD

**Issue by InstructionSeeker** [chromiecraft/chromiecraft#177]
##### CONTENT PHASE:

Any, as long the player has noticeably lower level than the mob.

##### SMALL DESCRIPTION:

There are many, many types of mobs, who despite being a skull level, aggro as if they were green or gray. Raptors and spiders in Arathi. I can't tell whether Tanaris mobs are fine, definetely the trolls are, not sure about animals though, but it still felt too easy.
Noticeably, the stand-out mobs are the stealthed [Slivermane Stalkers](https://classic.wowhead.com/npc=2926/silvermane-stalker) in the Hinterlands, which sometimes won't aggro at all, despite still being a skull level for me. However that might belong in another issue.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mobs should aggro from amazingly great range, however I take it that **I might** confuse the aggro ranges with vanilla version if they were different that is.

##### CURRENT BEHAVIOUR:

Player can run past in skull level mobs in closer proximity than it should be allowed.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Go to Arathi or Hinterlands.
Step 2: Test how close various mobs aggro compared to the others (trolls *seem* to have correct aggro range).

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Closed
-

**Here is the explanation.**

**Video Test:** [short aggro range](https://youtu.be/84epxcR8LCM)
