### ISSUE TITLE
Unable to get lvl 20 Warrior quest The Rethban Gauntlet

### ISSUE THREAD

**Issue by TaraKaos** [chromiecraft/chromiecraft#1771]
I received the quest Yorus Barleybrew in the Exodar, went to redridge to turn it in and received no follow-up quest.

In case this helps, I am playing a gnome warrior who has only done Draenei quests, trying to get an ellek mount.

**Comment by gurveleg** [comment]
Make sure next time you fill out the form properly.

**Comment by 55Honey** [comment]
Is it a timed quest? I think i remember a case with a warrior quest which could not be accepted while the player had **any** other quest on a timer in their log.

**Comment by gurveleg** [comment]
The Rethban Gauntled is the timed quest yes, but I tested on my local AC with all the races both SW and Exodar quest, and only SW quest opened The Rethban gauntlet.

**Comment by eTzmNcbkrng** [comment]
@TaraKaos This needs to be relogged using the template.
