### ISSUE TITLE
Tirisfal Glades - Peacebloom node appears under the ground at 69.2, 54.3

### ISSUE THREAD

**Issue by CMHWoody** [chromiecraft/chromiecraft#1772]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

A Peacebloom node appears under the ground and cannot be activated by the player

### Expected Blizzlike Behaviour

The node should appear on the surface so it is accessible to activation by the player.

### Steps to reproduce the problem

Go to location listed in the title
Turn on Herbalism tracking
Node is marked but not visible or able to be activated

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
I can not find this herb. Teleported to the specified location, see screenshot, but found no peace bloom within 150.
![image](https://user-images.githubusercontent.com/53914190/133805614-5561cd97-f51b-4ed5-abc8-955a04dcb479.png)

**Comment by gurveleg** [comment]
Confirmed
![pace1](https://user-images.githubusercontent.com/80769357/133821113-f6c0b840-c638-440d-b06b-d5996f115ba6.jpg)
![pace2](https://user-images.githubusercontent.com/80769357/133821119-c6963d11-18f1-4c4a-b184-4414846b7896.jpg)
its the guid 1469 that's underground
