### ISSUE TITLE
Shadowmeld still not fixed and labeled "fixed " in previous topic

### ISSUE THREAD

**Issue by Volkyte** [chromiecraft/chromiecraft#1775]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

as per https://github.com/chromiecraft/chromiecraft/issues/153 (there are also videos and links ther) Night elf shadowmeld is not working since 1 year.

### Expected Blizzlike Behaviour

Is like rogue vanish spell (check linked topic)

### Steps to reproduce the problem

1.roll night elf
2.aggro a mob
3.use Shadowmeld

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by nicoaravena** [comment]
Shadowmeld use Stealth behaviour, not Vanish and that is a very important difference. Stealth will not refresh aggro and melee monsters will attack you if you are close enough. Vanish will clear all aggro for 3 seconds, then will enter to Stealth status.

**Comment by Azcobu** [comment]
I've removed the "Fixed" label as there seems to be a significant proportion of commenters who believe it is not. This is almost entirely symbolic as the actual issue is on the AC tracker, but may as well be accurate as we can. However, I'd also like to discourage tickets complaining about other ticket's labels, not to mention duplication of known issues, so closing this accordingly.
