### ISSUE TITLE
Visual bug when leaving battleground shapeshifted

### ISSUE THREAD

**Issue by aithdruid** [chromiecraft/chromiecraft#178]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

All

##### SMALL DESCRIPTION:

Leaving a battleground while shapeshifted will revert you to caster form mechanically but not visually.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you leave a battleground your visual and mechanical form should match

##### CURRENT BEHAVIOUR:

Leaving a battleground while shapeshifted will revert you to caster form mechanically but not visually, so you can be a cat or bear or cheetah casting spells or running around on a mount.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Enter a battleground
Step 2 Shapeshift
Step 3 Wait for battleground to end

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@aithdruid 

it is a problem on the **Client side**, not on the **Server side**, you **have to clear the Cache before entering the Game**, and in any case the **Cache can be bugged** even **(while)** **you are playing.**
Additionally, which WoW Client are you using?
**enUS** or **enGB?**
