### ISSUE TITLE
Greymist coastrunner in Darkshore has rage bar

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#1781]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When fighting a greymist coastrunner to the south of Auberdine, I found that it has rage bar.

### Expected Blizzlike Behaviour

Never aware of a mob with rage bar. Searched "wow mob rage" online and did not find anything related to any mob with rage bar. In this video (https://www.youtube.com/watch?v=tLUduGbqqNM), the player fought a few greymist coastrunners (starting from 00:48) and there was no sign of rage. Sure the video is for classic, may not be the same as wotlk.

### Steps to reproduce the problem

1. Get a char with proper level. (Mob lvl 12-13 and you don't want to one-shot the mob or be one-shot.)
2. Head south from Auberdine along the coast. There are greymist coastrunners around the first beached creature (or turtle?) you see.
3. Fight them to see the rage bar.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
I'm afraid this is not a bug.

There are quite a lot mobs that use rage, there are also a few who use energy and even runic power (not sure about focus though), though the most common are those who have no resource at all or mana.

One example are the [Fallenroot Satyrs](https://wowgaming.altervista.org/aowow/?npc=4788), at the entrance of Blackfathom Deeps.
![WoWScrnShot_091821_005530](https://user-images.githubusercontent.com/19631518/133873991-0a377e59-c347-47ed-a2dc-adc021ece0ca.jpg)

**Comment by discorder0** [comment]
@VFaleiro, is there anyway i can confirm that greymist coastrunner uses rage? maybe wait until it uses some skills and see whether its rage is consumed? BTW, is your screenshot from retail or pserver?

**Comment by gurveleg** [comment]
https://youtu.be/pa4SuHwKULM?t=1606 video from classic, shows a rage bar, tho its not actually getting any rage.

**Comment by discorder0** [comment]
@gurveleg, thanks for reply. I updated the ticket a few minutes ago showing a link to a similar youtube video. During my fight, the rage bar got filled up gradually. (I turned on status text and could also see the value increasing.)

**Comment by Azcobu** [comment]
Just had a look at these mobs, and they're casting Battle Stance when combat begins, but never doing anything with the rage it generates:

![WoWScrnShot_091921_134136](https://user-images.githubusercontent.com/81782124/133915312-93626fa1-cfca-4aea-8ca2-2b44edebabf6.jpg)
![WoWScrnShot_091921_133723](https://user-images.githubusercontent.com/81782124/133915313-db4bd9e3-476f-48af-98a9-e49a9eb2b3c5.jpg)
![WoWScrnShot_091921_134407](https://user-images.githubusercontent.com/81782124/133915316-eb4d47f4-8c34-427b-9297-36fa16609ab0.jpg)

Also had a look on Trinity, and their version of this mob has a script for fleeing to get help, but nothing in there about having Battle Stance. Same for Wowhead, and they don't have any rage-consuming abilities either. So reporting this as a scripting error giving them access to an ability they shouldn't have.

**Comment by discorder0** [comment]
@Azcobu, thank you for testing and confirming the issue. In my comment earlier I said that the mob did not cast battle stance. I double checked just now and found that it did cast battle stance. I probably did not notice it before. So, I totally agree with your assessment and thank you again.

**Comment by VFaleiro** [comment]
> @VFaleiro, is there anyway i can confirm that greymist coastrunner uses rage? maybe wait until it uses some skills and see whether its rage is consumed? BTW, is your screenshot from retail or pserver?

You can log retail or wait for someone to do just that, but it will probably take some time since there are like thousands of mobs who have rage bars in AC/ChromieCraft.

The screenshot is from ChromieCraft.

**Comment by VFaleiro** [comment]
> @VFaleiro, is there anyway i can confirm that greymist coastrunner uses rage? maybe wait until it uses some skills and see whether its rage is consumed? BTW, is your screenshot from retail or pserver?

Regarding this specific mob having rage bar, seems like you guys already found a reliable source.

Regarding all other mobs having rage bar, someone would probably have to make a list of all NPCs using rage as resource, then someone else can log retail and screenshot them to check (there are probably thousands of them, may take some time).

The screenshot is from ChromieCraft, it just served as an example of how common rage is for mobs (because I thought it common knowledge), but now I guess it's in the list of mobs that need to be checked out...

**Comment by Azcobu** [comment]
@VFaleiro thanks for the example NPC - they are actually nearly identical to the Coastrunners, but instead of casting spell 7165 Battle Stance, they cast spell 7164 Defensive Stance. Fortunately in this case, [Wowhead](https://tbc.wowhead.com/npc=4788/fallenroot-satyr#abilities) shows that's a valid ability for that NPC. Also, unlike the Coastrunners, the Satyr actually has an ability to spend rage on, as they cast spell 6713 Disarm when between 20-60% health. So they look to be working properly.
