### ISSUE TITLE
RDF Dungeon Browser Queue CD not cleared after finishing dungeon

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#1782]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When running a specific dungeon via the dungeon browser, finishing the dungeon does not clear the 15 min queuing cooldown for queuing a random dungeon.

### Expected Blizzlike Behaviour

When finishing a dungeon queued via dungeon browser the cooldown to queue again should finish.

### Steps to reproduce the problem

1. Queue specific dungeon
2. Finish dungeon within less than 15 mins
3. leave party from dungeon run
4. try to queue random dungeon - not possible cause of the cooldown still progressing down from 15 mins

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
I can't confirm it, tested on local AC (87f7ec6).
Finished the RDF in a minute or so, left the group and queued up again.

**Comment by j-hdt** [comment]
> I can't confirm it, tested on local AC (87f7ec6).
> Finished the RDF in a minute or so, left the group and queued up again.

As i wrote: queue specific, finish quickly, then try to queue random.

**Comment by baranzadeoglu** [comment]
did you finish the que with killing the emperor or the boss in the prison.

dungeon finder currently only ques for BRD-prison which technically does not recognize emperor as the final boss.

**Comment by j-hdt** [comment]
> did you finish the que with killing the emperor or the boss in the prison.
> 
> dungeon finder currently only ques for BRD-prison which technically does not recognize emperor as the final boss.

right, that sounds logical - then there shouldnt be an issue here.
