### ISSUE TITLE
Feralas Quest "Wandering Shay" is bugged.

### ISSUE THREAD

**Issue by Lomsikka** [chromiecraft/chromiecraft#1783]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

The quest "Wandering Shay" requires us to find Shay and bring her back to the questgiver's camp. It is easy to find her. Getting her back to the camp is the problem. Once you start moving and the NPC starts following you, her whole model disappears and becomes completely invisible. You can see her if you move your camera around but only at certain angles. You can target her and see that when she is "following" you, she jumps around to your location every second, never really running/walking towards you. At the end, bringing her to the camp doesn't trigger anything. No text, no completion, nothing.
![1](https://user-images.githubusercontent.com/89902163/133894426-c377e4e5-ecd8-49ce-b21d-a9ba76592708.png)
![2](https://user-images.githubusercontent.com/89902163/133894429-9918a9a3-3a2c-4506-8984-cdba3b595216.png)

### Expected Blizzlike Behaviour

I believe it is expected for the NPC to not disappear and still be visible at all times. Also for her not to jump around and actually follow you by running/walking and for the quest to be actually completed once the NPC is in the triggering zone.

### Steps to reproduce the problem

I do not have any knowledge to write comments here.

### Extra Notes

Quest - [Wandering Shay](https://wowgaming.altervista.org/aowow/?quest=2845)
Questgiver - [Rockbiter ](https://wowgaming.altervista.org/aowow/?npc=7765)
NPC to find and bring back - [Shay Leafrunner ](https://wowgaming.altervista.org/aowow/?npc=7774)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
Hello, thanks for your report but this issue has been reported before in #1083 and https://github.com/azerothcore/azerothcore-wotlk/issues/6722. There is PR commited that will fix this but wasn't merged yet, I will close this accordingly.
