### ISSUE TITLE
Brutal Assault debuff remaining after Warsong Gulch ends

### ISSUE THREAD

**Issue by aithdruid** [chromiecraft/chromiecraft#179]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

All

##### SMALL DESCRIPTION:

Spell: [Brutal Assault](https://www.wowhead.com/spell=46393/brutal-assault) will sometimes remain on the flag carrier after Warsong Gulch ends and they leave.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Brutal Assault (and Focused Assault) should be removed upon leaving Warsong Gulch

##### CURRENT BEHAVIOUR:

I had the Brutal Assault debuff after a Warsong Gulch ended and I teleported back to Orgrimmar. It ended 0-0 after 25 minutes and I was in bear form and jumping around in the area where you capture the flag when it ended.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Enter Warsong Gulch
Step 2 Have both teams hold the flag until Brutal Assault
Step 3 Wait for Warsong Gulch to end, possibly be shapeshifted, jumping, or in flag area as it ends.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
We need a video or at least a screen both as proof and to better understand the problem (possibly).

**Comment by aithdruid** [comment]
I will take a screenshot next time I see it happen

**Comment by aithdruid** [comment]
It happened again, I took a screenshot this time
![image](https://user-images.githubusercontent.com/79885209/111930922-477c4580-8a77-11eb-95b3-b9323ec3d63c.png)

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Brutal Assault Without my Fix](https://youtu.be/BB6wFEorAZE)
**Video Test:** [Brutal Assault with my Fix](https://youtu.be/sHs_AYOsZIo)
