### ISSUE TITLE
[Brewfest] Cannot obtain a "Complimentary Brewfest Sampler" using /wave on the sampler npcs

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#1798]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Using /wave on the sampler npcs does not make them throw a Complimentary Brewfest Sampler at the player.

Alliance camp
Ita Barleybrew, GUID 88851, Entry 23684
Maeve Barleybrew, GUID 88874, entry 23683
Gordok Brew Barker, GUID 88864, entry 23685

The horde camp needs checking.

### Expected Blizzlike Behaviour

> /wave at one of the NPCs in the camp who are holding 2 golden glowing mugs.
They'll throw you one of these

### Source

https://tbc.wowhead.com/item=33096/complimentary-brewfest-sampler#comments:id=162096

### Steps to reproduce the problem

Remove "Complimentary Brewfest Sampler" from your bags if you have any.
Target any of the Brewmaiden within 30y and in sight.
Do /wave

### Extra Notes

If you use a "Complimentary Brewfest Sampler" within 30y, they do properly throw another sampler.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Can confirm that /wave isn't making the barkers throw Samplers to you. However, doing some reading on this found that this may be deliberate:

> During the first Brewfest in 2007, players were shown that emoting /wave to their local Brew Barker, Brewery Barker, or Brewmaiden would have them toss you a Complimentary Brewfest Sampler, as ammunition for the Dark Iron attacks. Keeping this sampler and waving again caused a new mug to fly through the air and bonk the player in the head, bouncing off to fall within a 360° circumference of the player and disappearing through the ground. The problem: Players figured out that macroing multiple /wave emotes into a single macro would have the NPCs throw a mug for each /wave simultaneously. This created a 'beer mug fountain' effect, like water spraying outward at the top of a water foutain. While many found this highly amusing, even only a few players doing this at the same time would cause significant lag to other players with less robust internet connections. Many who realized this would stop out of courtesy to those players, but this became only one item of a list of problems with the Dark Iron attack event. This forced Blizzard to disable all components of the attack, so that it could be retooled for 2008. ([source](https://wowpedia.fandom.com/wiki/Brewfest))

Note that the TBC Wowhead [quote](https://tbc.wowhead.com/item=33096/complimentary-brewfest-sampler#comments:id=162096) you found was from 2007, before /wave was disabled. The source doesn't say what they did to change the setup from 2008 onwards though, which is annoying. But it does seem that for early Wrath at least, /wave being disabled was Blizzlike. Will leave this open for now though in case any further sources turn up.
