### ISSUE TITLE
Elwynn Forest 'Prowlers' Drop Chance

### ISSUE THREAD

**Issue by GravelordNeko** [chromiecraft/chromiecraft#18]
##### SMALL DESCRIPTION:

The Prowlers in Elwynn Forest are dropping unusually high amounts of uncommon items, at times dropping multiple uncommon items.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Prowlers and most low leveled entities, should have a lower chance of dropping uncommon items, around a 1-5% chance. This is of course to occasionally reward a player with an uncommon drop that could be used or disenchanted.

##### CURRENT BEHAVIOUR:

Prowlers currently have a seemingly high chance to drop uncommon items. Enough to fill an entire inventory within 20 minutes solely with uncommon items. As it stands I would wager that I am getting an uncommon items at least 30% of the time. There has been 4 instances where I received two uncommon items from a single Prowler and one instance where I received three uncommon items from a single Prowler. As it currently stands with the amount of uncommon magic items the Prowlers provide it could cripple the lower level enchanting economy.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find Prowlers in Elwynn Forest
2. Kill Prowlers
3. Loot uncommon item (or items) from Prowlers

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Hello, thank you for the report.

I am leaving here a screenshot that shows the current loot of this NPC.
![image](https://user-images.githubusercontent.com/519778/105616987-79f12580-5ddb-11eb-8c38-e183848ac046.png)

todo: check the reference in detail

**Comment by pangolp** [comment]
Hi, thanks for the report, is there any site where I can consult any could be the percentage of expected drop in a blizzlike way, I don't have enough experience as a player, to be able to determine if the drop is something, normal or low. Thank you.

**Comment by Hacaw** [comment]
I killed ~10 prowelers and got 1 green item, most of them didn't have any loot at all.

**Comment by FrancescoBorzi** [comment]
> I killed ~10 prowelers and got 1 green item, most of them didn't have any loot at all.

then it seems to be working as intended :)
