### ISSUE TITLE
[Brewfest] Token Redmeer does sell 3 of same items

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1801]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

NPC Blix Fixwidget, token redeemer on Brewfest sells 3 of "same" Club membership forms, so maybe there is difference between them, closer look is needed.

![WoWScrnShot_092021_072146](https://user-images.githubusercontent.com/80590226/133960830-1a7ecb8b-4498-4fd0-aba5-550d1c93ad3d.jpg)

### Expected Blizzlike Behaviour

https://wowpedia.fandom.com/wiki/Blix_Fixwidget This is link of post WOTLK expansion, but price of item https://wowpedia.fandom.com/wiki/%22Brew_of_the_Month%22_Club_Membership_Form is same, and he sells only one of those.

### Steps to reproduce the problem

1. Go to Durotar Brewfest token redemeer
2. Talk to NPC 
3. He is selling 3 of same items.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Yehonal** [comment]
Check this out: https://github.com/azerothcore/azerothcore-wotlk/pull/8029#issuecomment-968670617
