### ISSUE TITLE
[Brewfest] Mounts are missing from the drop table of Coren Direbrew

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1803]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Mounts are missing from the drop table of Coren Direbrew

Note also the drop rates should not be uniform for the epic items either.

![image](https://user-images.githubusercontent.com/84640316/133978940-ab197958-72c7-47aa-a881-6ecbc7bcb852.png)

### Expected Blizzlike Behaviour

Both should drop for both faction with <2% chance

Other items should drop at varying rates.

### Source

https://www.wowhead.com/item=33977/swift-brewfest-ram#comments
3rd comment
Link to photo:
http://i997.photobucket.com/albums/af100/Dero_chan/OMFG2inonego.png
![image](https://user-images.githubusercontent.com/84640316/133978847-8bd2611d-b397-4874-8943-c37dc2800df3.png)

### Steps to reproduce the problem

query the loot table or check keira3

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, the mounts are not part of his standard loot table, but are instead contained in item 54535, the Keg-Shaped Treasure Chest, which is the daily/RDF reward for completing quest 25483, which is the world event dungeon quest to go kill him. (Wowpedia confirms this is Blizzlike - "The  [Direbrew's Remote],  [Swift Brewfest Ram] and  [Great Brewfest Kodo] drops however, are only available via the daily drop bags." - [source](https://wowpedia.fandom.com/wiki/Coren_Direbrew?oldid=2425948)) On AC the Keg-Shaped Treasure Chest contains both of the mounts, with a 4% drop rate each. 

As for the epic drop rates, this sounds more plausible, but TBC Wowhead's data is so messed up by RDF drops, and multiple reworkings of this NPC's loot tables, that I'm not sure we have anything reliable to go on. Also note (for the little it's worth) that the [current WH drops](https://www.wowhead.com/npc=23872/coren-direbrew#drops;mode:normal) for this NPC do show an even drop distribution for his epics, although at a much lower rate than on AC.

**Comment by baranzadeoglu** [comment]
> Thanks for the report. However, the mounts are not part of his standard loot table, but are instead contained in item 54535, the Keg-Shaped Treasure Chest, which is the daily/RDF reward for completing quest 25483, which is the world event dungeon quest to go kill him. (Wowpedia confirms this is Blizzlike - "The [Direbrew's Remote], [Swift Brewfest Ram] and [Great Brewfest Kodo] drops however, are only available via the daily drop bags." - [source](https://wowpedia.fandom.com/wiki/Coren_Direbrew?oldid=2425948)) On AC the Keg-Shaped Treasure Chest contains both of the mounts, with a 4% drop rate each.

Are you sure this is the case? Current classic tbc behavior looks like they drop from the mob itself

https://www.reddit.com/r/classicwow/comments/prwrvh/so_this_happened/

**Comment by Azcobu** [comment]
That's because TBC Classic emulates TBC's behaviour, but that behaviour changed later on in Wrath. If you check the source I linked above, it says this:

>All the items that appear in the  [Keg-Shaped Treasure Chest] during the 2010 event were drops directly from Coren Direbrew during the 2009 event.
>Since normal loot rules applied to these items, in 2009 a person could 'farm' Coren for one of those drops, as long as they could continue inviting people into the group who had not started the event (IE make Coren hostile) that day. The 2010 event enforces that each character only has one chance per day to get one of the special items through the keg.

So in 3.3.5, the Keg was how the mounts were distributed. This is also noted in the September 2010 Wowpedia article, and is also mentioned in the screenshot you provided above, where players say they got mounts from the keg several times.

**Comment by baranzadeoglu** [comment]
thanks
