### ISSUE TITLE
Buccaneer's Strongbox lockpicking skill not scaling beyond lvl 101

### ISSUE THREAD

**Issue by coyote86** [chromiecraft/chromiecraft#1807]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Buccaneer's Strongboxes are located in The Barrens, more specifically, on the ship in Merchant Coast. This ship has a quest where a rogue could choose to train their lockpicking skill up to 105.

Ignoring the instant respawn timer on the lockboxes, after one reaches 101 skill, they cannot gain any more, despite the lockboxes still being green. [https://i.imgur.com/hEY0PCK.jpeg](url) 

### Expected Blizzlike Behaviour

According to Wowhead [https://classic.wowhead.com/object=123330/buccaneers-strongbox](url) the box should turn gray after 105 skill.

### Source

![hEY0PCK](https://user-images.githubusercontent.com/90635287/134063312-55108904-5f15-4eee-a325-1e899be04c10.jpeg)
[https://classic.wowhead.com/object=123330/buccaneers-strongbox](url)
[https://wotlk-twinhead.twinstar.cz/?object=123331](url)

### Steps to reproduce the problem

1. Arrive at location 65.1, 45.4
2. Locate the lockboxes
3. Use the lockpicking skill (preferably with a glyph of lockpicking)
4. Click on the lockboxes
5. Expect not to see any more scaling after 101 skill

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
I can confirm this, along with the lockboxes in redridge. It did not skill up passed 101 for me after about an hour of lock picking- Sorry, I lost count of boxes. I do believe this is blizzlike, as most of the lockpicking guides I've read say this will get you to 100. I also believe this should turn gray at that point (it does stay green)

https://youtu.be/XMKCTfAqgOg video guide from 2009

I think the extra point is a Pserver bug. I have no way to prove this and I could be completely wrong, but I want to say the extra 1 comes in because lockpicking starts at 1, not 0. So really you would have had leveled lockpicking 100 points before you stop getting gains. It makes sense to me thinking of it that way, but again, it's just speculation.

**Comment by temperrr** [comment]
IT works how it should, at 105 it becomes green, above 100 it becomes utterly low chance.
