### ISSUE TITLE
Globin Commoner NPC's have Noblegarden text during Brewfest

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#1810]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Globin Commoner NPC's have this text when you click on them:

"Hey, if people want to run around rooting in the dirt for colored eggs, who am I to judge? I still get a cut of the profits on paint, and I invested in chickens this year. "

That's from the Noblegarden event.

Also, female Globin Commoner have human female masks, I believe those are from Hallow End's event.

### Expected Blizzlike Behaviour

When you click in them it should say:

"No other holiday matches the feasting and drinking of Brewfest! "

Female NPC's shouldn't be wearing masks in Brewfest.

### Source

https://wowpedia.fandom.com/wiki/Goblin_Commoner

### Steps to reproduce the problem

1. Talk to Goblin Commoner NPC's in Booty Bay.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Current text with active event list:
![image](https://user-images.githubusercontent.com/53914190/134235364-77153ad8-ac7f-4374-af28-87d75ac9d234.png)

As can be seen, the behaviour is as described. I am, however, not certain of the source. Wowpedia isn't a primary source, while it is quite definitive on the matter, I'd still like someone else to confirm it.

**Comment by FTGCocolandia** [comment]
I should add that the Commoners in Darnassus have the correct text that I took from Wowpedia. 

I didn't know what source to check for that text, sorry, first time reporting a bug.

**Comment by jamadaha** [comment]
It's a good source, but a bit tenuous to confirm a bug on. Although, I couldn't find any other sources either, so I suppose it's the best source. (Until better source found)

**Comment by Shineslippers** [comment]
@jamadaha Same there. Wowwiki [Commoners](https://wowwiki-archive.fandom.com/wiki/Commoners?oldid=2113725)
> The racial commoners are people of all races that spawn during world events to inform players of said event. They often give a quest that tells them of where to go.

Everything is simple. They have to talking about current event. If they don't doing it - bug. You also have to check out other commoners. I saw in Darnassus same issue.
