### ISSUE TITLE
Brewfest cart is misplaced

### ISSUE THREAD

**Issue by BobsenJr** [chromiecraft/chromiecraft#1811]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

At the Brewfest camp in Dun Morogh, there is a tent that has Gordok Brew vendors. The tent is presently half-blocked by the Brewfest keg cart which has spawned ontop of the tent, blocking access to the Gordok Brew Apprentice who sells items. 

### Expected Blizzlike Behaviour

The cart should be placed elsewhere or removed entirely so that one can access the vendor. 

### Source

N/A

### Steps to reproduce the problem

1. Go to brewfest in Dun Morogh
2. Find the Gordok Brew tent
3. Observe that there is a giant cart ontop of and in the tent.
4. That's the issue. 

### Extra Notes

https://imgur.com/c9PyKTK a picture of the issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BobsenJr** [comment]
There is an additional cart that is also misplaced in the same camp.

**Comment by cachocarne** [comment]
As for 2021.09.22 it seems it's been somehow fixed (they are gone). No big carts all over the way, at least.
