### ISSUE TITLE
[Hunters pet] Attack (damage) range and speed 

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1812]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Damage range is so high that I'm getting damaged and killed while mounted (100% mount speed) vs pet with 80% speed buff. Literally cannot escape hunters pet

First screenshot, you can see pet has only 80% buff. Second screenshot you can see pet MISSING his attack on me FROM WHAT RANGE. Third screenshot you can see from really high range that pet attacks and damages me while I'm on 100% mount speed.
![WoWScrnShot_092121_204220](https://user-images.githubusercontent.com/80590226/134235471-b3c49740-472e-41f0-8cb8-a109a7579a4b.jpg)
![WoWScrnShot_092121_203918](https://user-images.githubusercontent.com/80590226/134235478-2968eedb-510d-4112-9f30-54635cdf9418.jpg)
![WoWScrnShot_092121_203917](https://user-images.githubusercontent.com/80590226/134235480-411408ba-df73-41bf-ac23-a32d36de5565.jpg)
![WoWScrnShot_092121_203915](https://user-images.githubusercontent.com/80590226/134235481-28f3f203-2426-479f-8178-1de7dad48fb0.jpg)
![WoWScrnShot_092121_203913](https://user-images.githubusercontent.com/80590226/134235483-695f7f0c-6652-46e5-b2d2-3960c1898893.jpg)
.

### Expected Blizzlike Behaviour

People who are on 100% mount cannot be chased by hunters pet lel.

### Steps to reproduce the problem

1. Enter PvP BG/Arena/Open world
2. Mount up and get damaged by this pet from hunter

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ypoptos** [comment]
As I already said at another post, due to this bug hunters abuse farming spots like Jadefire Run. They can kill within 15sec 5 or 6 lv 52-54 mobs (orange or red to them). They gather the mobs with their fast pet and kill them with fire trap and multi shot.

**Comment by Shineslippers** [comment]
Thank you for the report. I can say how it happened. Pets speed is 115% and with 80% buff it makes their pursuit speed to 207% which is slightly faster than mount speed. So far looks like this behavior is blizzlike.
