### ISSUE TITLE
[Ghost spawn point] Not appearing on close graveyard after dying in Gnomeregan

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1814]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Upon dying inside Gnomeregan dungeon, our ghost appears at Kharanos graveyard in Dun Morogh, quite far from instance entrance

### Expected Blizzlike Behaviour

Ghost should appear in the graveyard closer to the instance, in Dun Morogh at coords [35.8, 46]
![ 2021-09-22 at 09 13 01](https://user-images.githubusercontent.com/77953030/134292970-6a5000f4-d7ad-4dde-acf5-96ba6ddde3ed.png)

### Steps to reproduce the problem

1. Go to Gnomeregan
2. Die in the zone or inside the instance
3. Ghost will appear far away from entrance, at Kharanos graveyard

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Can confirm that both factions will appear at the Kharanos GY on dying in Gnomeregan. I also agree it would make sense for players to respawn at the Iceflow Lake (closer) GY instead. However, common sense has never been a very good guide in Wow, and I haven't been able to find any sources to actually confirm that the Iceflow Lake GY was used for Gnomeregan, or even when it was added.

**Comment by cachocarne** [comment]
Some "interesting" update on this.
When dying inside Gnomeregan, our spirit appears at Kharanos and it's necessary to walk all the way to Gnomeregan again. However, if we are dead at Kharanos graveyard and we decide to release corpse and get Resurrection sickness to be back alive in Kharanos, then we will appear… on the graveyard at Iceflow Lake!!! (35.8, 46.0)
![ 2021-11-22 at 22 03 01](https://user-images.githubusercontent.com/77953030/142920273-5ef850bb-74c2-421c-929f-93ef56f3e689.png)

**Comment by temperrr** [comment]
Can confirm that kharanos graveyard is correct:
