### ISSUE TITLE
Herbs in starting Area 

### ISSUE THREAD

**Issue by icynuts** [chromiecraft/chromiecraft#1820]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Hey, i'm new to the server i'm a dwarf priest i couldn't help but notice that herbs in starting areas are lacking, especially places like elwynn forest, once i traveled from Dun Moroph to ewynn i've encountered significantly less herbs like 2 or 3 of them all the way to westfall, i tried going back to elwynn to pick some but i couldn't find any near goldshire or around it, once in westfall there should be more herbs too in there but all you find there is big clumps of bruiseweed almost next to each other, and you cannot find any of lvl. 1 - 75 Herbs at all although westfall is lvl. 10 -18 area, like i said i'm new still in the server idk how much more i'll encounter in the next zones but i just had to report it.

### Expected Blizzlike Behaviour

in elwynn forest there should be silverleaf near trees, around rivers close to hills too , around the mine and fart at the bottom, around gnoll camps , peacebloom should be in open areas laying around not near anything , in westfall too, and definitely not in big clumps like in the pic below:
![WoWScrnShot_092221_185907](https://user-images.githubusercontent.com/91210100/134379774-89b60c1a-5c8c-424c-9d6b-42c27d50a14e.jpg)

(Look at the minimap)

### Steps to reproduce the problem

idk

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
The herb and mining nodes are not pooled yet in majority of the zones, which leads to situations like this.

**Comment by Azcobu** [comment]
Thanks for the report. You're correct that herbs are not working very well at the moment, but as @gurveleg says, that's largely due to a lack of node pooling. So on a retail server, a zone might have a pool of 100 herbs, but only 25 would be spawned at any one time. On AC at the moment, we would have the same 100 herb spawns, but all 100 will be spawning at once, which leads to the big clumps you noticed. There is an ongoing project to deal with these, zone by zone. I'm more surprised at the lack of herbs in Elwynn you mention, but last I heard someone was looking at importing a lot of starting zone resource node data from another project, as they were supposed to have better data. That would presumably resolve the issue. 

Anyway, as these are known issues, will close this report accordingly.
