### ISSUE TITLE
Invisible wall obstructing movement outside Wizard's Sanctum.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#1821]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

While mounting an Elekk, you can get blocked walking towards Wizard's Sanctum entrance although there's nothing in sight.

![Elekk Walking From WS](https://user-images.githubusercontent.com/91145640/134399030-4d9a329b-70bb-4e7f-a228-2c2768b57633.jpg)
![Elekk Walking To WS](https://user-images.githubusercontent.com/91145640/134399036-de20373c-efdb-4f77-b116-18f2689eb609.jpg)

In both screenshots I'm with auto run toggled, sorry for not sharing any video.

Also, if you jump specifically pointing towards this place you get stopped by something and then fall:

![Tiger Jump](https://user-images.githubusercontent.com/91145640/134399896-42364310-67c6-4a71-9bd2-4dcd3b882b36.jpg)

### Expected Blizzlike Behaviour

There's nothing there so it shouldn't obstruct the movement of the characters.

Every source I found was about Classic and not Wotlk, so it might have been fixed in TBC or Wotlk.

I should add I've never encountered this while playing other servers for many years. Might have been luck.

### Source

Might be related to this in Classic?

https://www.youtube.com/watch?v=uXf5twUsXgw

Tried to replicate and couldn't, it might have been fixed in TBC or WOTLK.

### Steps to reproduce the problem

1. Run mounting an Elekk towards Wizard's Sanctum's entrance in Mage Quarter, Stormwind.
or
2. Jump from Wizard's Sanctum entrance and you'll get stopped mid air and then fall.

### Extra Notes

Again, couldn't find any appropriate source for WotlK on this but it clearly should not be happening.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gadixsp** [comment]
I definitely remember it being there for a time in classic, though I don't remember which versions. I suspect, though, that it's an error in the Stormwind map file and therefore a client side bug instead of server side.

**Comment by Azcobu** [comment]
Thanks for the report. However, we did have a ticket for this - see https://github.com/azerothcore/azerothcore-wotlk/issues/5018 - and it was closed for the same reason @Gadixsp mentions, that it's a client-side texture problem, and thus unfortunately not something server-side that we are able to fix. Closing this accordingly.
