### ISSUE TITLE
[Silithus Rare] Grubthor has no loot

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1822]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Killing rare gives no loot. He has easy loottable can be fixed fast I guess?
![WoWScrnShot_092221_202850](https://user-images.githubusercontent.com/80590226/134403912-2136a468-3da1-4a4f-a676-17e3b153861f.jpg)
![WoWScrnShot_092221_202904](https://user-images.githubusercontent.com/80590226/134403914-08362169-14cc-41db-a535-21a0e48bc4ab.jpg)

### Expected Blizzlike Behaviour

https://tbc.wowhead.com/npc=14477/grubthor
https://classic.wowhead.com/npc=14477/grubthor

WOTLK NON BLIZZARD DB: https://wotlk.evowow.com/?npc=14477#drops

### Steps to reproduce the problem

1. Get to Silithus
2. Find Grubthor
3. Kill him and find no loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
![Screenshot_20210923_074300](https://user-images.githubusercontent.com/14080516/134453964-b42f9bf6-0e48-42db-993b-84a86584e239.png)

but it has wrong loot, I THINK

**Comment by acidmanifesto** [comment]
Currently Loot table Matches up with UDB (Universale Database) that is established for loot based on verified sniffs and not wowhead or website database scrapes.
In our table we have the following hits on the creature_loot_template:
![image](https://user-images.githubusercontent.com/16887899/148063498-f5aba188-fd22-4ff8-ad03-ba24db335399.png)
With references to reference loot tables:
24016, 24031, 24033, 24089 when it comes to groups.

Loot tables are concurrent and matching exactly to UDB.
