### ISSUE TITLE
[Silithus Rare] Setis has no loot

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1823]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Killing rare gives no loot. He has easy loottable can be fixed fast I guess?
![WoWScrnShot_092221_202727](https://user-images.githubusercontent.com/80590226/134404946-818c9c3b-9ec2-4369-89c1-c11f872e5ddb.jpg)
![WoWScrnShot_092221_202752](https://user-images.githubusercontent.com/80590226/134404949-80fed55e-8235-4ae3-8761-b09664de1e43.jpg)

### Expected Blizzlike Behaviour

https://tbc.wowhead.com/npc=14471/setis
https://classic.wowhead.com/npc=14471/setis

WOTLK NON BLIZZ DB: https://wotlkdb.com/?npc=14471#drops

### Steps to reproduce the problem

1. Get to Silithus
2. Find and kill rare Setis
3. Get no loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
![Screenshot_20210923_074900](https://user-images.githubusercontent.com/14080516/134454208-55f35b1f-c04e-43da-bb7e-712a51a63cfc.png)

but it has wrong loot, I THINK

**Comment by acidmanifesto** [comment]
Currently Loot table Matches up with UDB (Universale Database) that is established for loot based on verified sniffs and not wowhead or website database scrapes.
In our table we have the following hits on the creature_loot_template:
![image](https://user-images.githubusercontent.com/16887899/148065142-2338608d-f286-4250-919d-3530dd6f4592.png)

With references to reference loot tables:
24016, 24018, 24020, 24024, 24036 when it comes to groups.

Loot tables are concurrent and matching exactly to UDB.

I am not entirely sure what is ment by "has easy loottable can be fixed fast I guess?"
But loot tables are not 100% drop on items with every kill regardless of rarity of creature type\boss type.
