### ISSUE TITLE
[Silithus Rare] Zora has no loot 

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1824]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Killing rare gives no loot. He has easy loottable can be fixed fast I guess?
![WoWScrnShot_092221_202401](https://user-images.githubusercontent.com/80590226/134405661-ec91614a-5b0f-4397-9fa6-8659ee97082f.jpg)
![WoWScrnShot_092221_202454](https://user-images.githubusercontent.com/80590226/134405666-fba01349-dd33-4d79-9429-14a77b780596.jpg)
![WoWScrnShot_092221_202402](https://user-images.githubusercontent.com/80590226/134405670-1276c068-c3e4-42d2-a0ea-ee08146ad96a.jpg)

### Expected Blizzlike Behaviour

https://tbc.wowhead.com/npc=14474/zora
https://classic.wowhead.com/npc=14474/zora

NON BLIZZ WOTLK DB: https://wotlk.evowow.com/?npc=14474#drops

### Steps to reproduce the problem

1. Go to Silithus
2. Find rare Zora inside Hive'regal
3. Kill her and get no loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
![Screenshot_20210923_075116](https://user-images.githubusercontent.com/14080516/134454380-1ea48675-4259-4c46-b999-42ab261ee7ec.png)

but it has wrong loot, I THINK

**Comment by acidmanifesto** [comment]
Currently Loot table Matches up with UDB (Universale Database) that is established for loot based on verified sniffs and not wowhead or website database scrapes with ONE exception, we have a extra item in the loot table that should not bre present and a pr will made to remove it, item in question being the Broken Silithid Chitin.

In our table we have the following hits on the creature_loot_template (Minus the extra item being removed):
![image](https://user-images.githubusercontent.com/16887899/148065795-fb3825fa-d63d-490b-83e5-198a2700e5c9.png)

With references to reference loot tables:
24016, 24018, 24033 when it comes to groups.

Loot tables are concurrent and matching exactly to UDB.

I am not entirely sure what is ment by "has easy loottable can be fixed fast I guess?"
But loot tables are not 100% drop on items with every kill regardless of rarity of creature type\boss type.
