### ISSUE TITLE
Slagtree's Lost Tools not accessible

### ISSUE THREAD

**Issue by VFaleiro** [chromiecraft/chromiecraft#1825]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When doing the quest [Vilebranch Hooligans](https://wowgaming.altervista.org/aowow/?quest=7839) in Hinterlands, [Slagtree's Lost Tools](https://wowgaming.altervista.org/aowow/?object=179908) should be accessible/clickable/visible, but it's nowhere to be seen (likely spawned under the ground).

I know it's there because its respawn timer is 2 seconds, and I performed `.gobj near 5` to make sure I was at the right spot.
![WoWScrnShot_092221_170605](https://user-images.githubusercontent.com/19631518/134414767-5f367b3c-7d5a-4b60-a162-1be262d579ef.jpg)

Now with `.gobj near 1` (to limit the search radius even further)
![WoWScrnShot_092221_170625](https://user-images.githubusercontent.com/19631518/134415094-8fb7a319-ec04-4c23-ab9a-a38c73a6bc65.jpg)

### Expected Blizzlike Behaviour

It should be there, at the top of Skulk Rock (but I looked inside the cave anyway, it's not there).

### Source

https://www.wowhead.com/object=179908/slagtrees-lost-tools#comments:id=91930

### Steps to reproduce the problem

1. Add quest 7839;
2. Go to Skulk Rock, around 57.41 / 42.54;
3. Try to locate the object.

### Extra Notes

There is an [old issue regarding the spawns of this object](https://github.com/chromiecraft/chromiecraft/issues/1175), maybe the current problem is related to that fix?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
Invalid. I did complete that q and still have it in quest log to be handled in. It has low respawn time probably and can be split between 4 locations or even 5.
![image](https://user-images.githubusercontent.com/80590226/134416290-ad9f4248-7684-47db-aa5c-24e2cb6cba3c.png)

**Comment by VFaleiro** [comment]
> Invalid. I did complete that q and still have it in quest log to be handled in. It has low respawn time probably and can be split between 4 locations or even 5.

According to https://wowgaming.altervista.org/aowow/?object=179908 it has only 1 spawn spot and 2 seconds spawn time.
[It has been confirmed before](https://github.com/chromiecraft/chromiecraft/issues/1729#issuecomment-920086923) that it's linked to AzerothCore (but their update cycle is much slower than ChromeCraft), that's why I opened this issue.

Will check the other spawn spots listed on [TBC Wowhead](https://tbc.wowhead.com/object=179908/slagtrees-lost-tools#comments) (which may be possible because of the issue #1175 mentioned earlier).

**Comment by VFaleiro** [comment]
Yep, found it at 66.4 / 44.8.
I am closing this issue now.
