### ISSUE TITLE
[Thousand Needles - NPC wrong drop] Sparkleshell tortoise dropping high level potion

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1826]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Watch chat from screenshots, guy reported in /5 that mob lvl around 30 dropped Major Healing Potion.

![WoWScrnShot_092321_103254](https://user-images.githubusercontent.com/80590226/134477078-bad3c7d0-d005-421d-8fa8-61e263646aef.jpg)
![WoWScrnShot_092321_103307](https://user-images.githubusercontent.com/80590226/134477081-6b7a3ec2-52be-4b9e-9f49-a1cffbd19cdb.jpg)

### Expected Blizzlike Behaviour

https://classic.wowhead.com/npc=4142/sparkleshell-tortoise
https://tbc.wowhead.com/npc=4142/sparkleshell-tortoise

NON BLIZZ WOTLK DB: https://wotlk-twinhead.twinstar.cz/?npc=4142

### Steps to reproduce the problem

1. Go to 1k needles
2. Kill sparkleshell-tortoises
3. Get high level loot, probably low chance.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. You might be wondering why the report I linked is about Scorpid Reavers and not Sparkleshell Tortoises, but it turns out the person who reported it to you was mistaken about exactly which NPC dropped the potion.
