### ISSUE TITLE
[Fleeing for Assist]: NPCs in Flee status should walk when they are between 1% and 7.5% health and run between 7.6% and 15% health.

### ISSUE THREAD

**Issue by YunataSavior** [chromiecraft/chromiecraft#183]
##### ISSUE: FACTION SIDE:
BOTH

##### CONTENT PHASE:
ALL

##### SMALL DESCRIPTION:
Half the times, when you're fighting a humanoid mob that will flee at low health, once they reach the threshold, they will IMMEDIATELY take off at a very high speed, even faster than regular running, towards an enemy pack. Once they get anywhere near another mob, they will INSTANTLY pull the mob.

This is blatantly wrong, even by Classic standards.

This is really frustrating and punishing to deal with. Sure, you can say "just save your burst for when they get really low", but that's not a luxury that can always be afforded, especially by certain classes. And when that happens: death.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.youtube.com/watch?v=CuvYOo1jG1k

I don't think ALL the mobs are supposed to run at ludicrous speeds. Even for the ones that do, they seem way too fast.

What's 100% wrong is that the mobs pull way too quickly once they get to other mobs. If you're ranged, the fleeing mob can get into kissing range with the non-pulled mob, and you can still kill the fleeing mob without the other pulling. Here, not quite...

##### CURRENT BEHAVIOUR:
See "Small Description".

##### STEPS TO REPRODUCE THE PROBLEM:
Watch the video I linked above, then recreate it using a Paladin at-level with leveling gear. Notice how you get destroyed by the mobs in the cave.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by YunataSavior** [comment]
The relevant function is here:

https://github.com/azerothcore/azerothcore-wotlk/blob/28f1dc5c0cc0d3ce26bb64bfc4475329fb5166c2/src/server/game/Entities/Creature/Creature.cpp#L828

Perhaps it's an issue with "UpdateSpeed()"? I haven't tested how fast the mobs flee in TrinityCore, but from my memory, they fled way slower...

Here's the relevant function in TrinityCore:

**Comment by Stifler82** [comment]
Yes, in fact I have noticed that the NPCs that go into fear and ask for help maybe go slightly faster than normal, but it doesn't seem to me that it is such an exaggerated or frustrating thing as you claim, because anyway even if we decide to change the speed, surely we would decrease it by 0.1 or 0.2 and therefore it would change very little, and as I have already told you and as I think I have shown you in this video I made, it does not seem like an "Unplayable" thing.

**Video Test:** [runs away too fast](https://youtu.be/qkWMn5B2CG8)

**Comment by YunataSavior** [comment]
Stifler82,

Let me see you post a video of you taking any non-hunter class and soloing the blackrock cave at level without cheats

**Comment by Stifler82** [comment]
> @Stifler82,
> 
> Let me see you post a video of you taking any non-hunter class and soloing the blackrock cave at level without cheats

@YunataSavior 
what do you mean by a "non-hunter class"?

**Comment by Stifler82** [comment]
btw, [Same place without cheats!](https://youtu.be/Hv_tpgFMO1Y)

**Comment by YunataSavior** [comment]
I mean: take a level 25 ret paladin into the Blackrock cavern in Northern Redridge Mountains, and solo the cavern

**Comment by mturca** [comment]
another note on this - they seem to ignore existing slow effect on them completely - once reapplied they are slowed but from memory can't remember this behavior on different servers / retail.

**Comment by eTzmNcbkrng** [comment]
Video evidence of mob fleeing at walking speed even with a friendly NPC within range - https://www.youtube.com/watch?v=8dNMBWh2wxY

Once at 6:55 and then again at 8:10, in both of these instances the NPCs seem to flee in a random direction and NOT towards their own friendly NPCs.
Also, note at 8:10 when the NPC is pulled with Frost Bolt and thus has the slow from that spell, it still runs, but in slow motion, when the mobs are fleeing, they are walking, therefore, the slow from Frost Bolt cannot account for the massive reduction in speed.

If a mob is fleeing from combat, it should always do so at a very slow walking pace, regardless of whether it can see friendly NPCs to run to for help.

**Comment by Stifler82** [comment]
> Video evidence of mob fleeing at walking speed even with a friendly NPC within range - https://www.youtube.com/watch?v=8dNMBWh2wxY
> 
> Once at 6:55 and then again at 8:10, in both of these instances the NPCs seem to flee in a random direction and NOT towards their own friendly NPCs.
> Also, note at 8:10 when the NPC is pulled with Frost Bolt and thus has the slow from that spell, it still runs, but in slow motion, when the mobs are fleeing, they are walking, therefore, the slow from Frost Bolt cannot account for the massive reduction in speed.
> 
> If a mob is fleeing from combat, it should always do so at a very slow walking pace, regardless of whether it can see friendly NPCs to run to for help.

Wait, maybe I got it wrong, but if I got it right, I'm curious, explain to me pls: **why should a MOB that "asks for help" do it slowly?**

**Comment by JamesGent** [comment]
As a Blizzlike expert I can agree that some of the mobs are running away too fast.

From a gameplay perspective, you are trying to clear some humanoid enemies from a camp, you get one to 15% and it ZOOMS away at twice your speed to get help. I've never experienced anything like it. Usually you can catch a fleeing NPC, or at least slow it down.

Mobs such as in Scarlet Monastary are running away at 150 or 200% speed. You can't catch up to them even if they are slowed.

https://youtu.be/LgQbwKQORfE?t=959

You can see in this video of classic wow the "fleeing" enemies move at slightly slower than normal running speed. I can't find any patch notes that discuss a large increase in fleeing mob speeds, so I think this is valid evidence paired with my personal experience.

**Comment by eTzmNcbkrng** [comment]
> Wait, maybe I got it wrong, but if I got it right, I'm curious, explain to me pls: **why should a MOB that "asks for help" do it slowly?**

How is that relevant? Blizzlike is to flee from battle at a walking pace.
If we want mobs to run for help, should that not be a configuration option or a module?

Also, I don't think mobs do flee for help, they flee in a random direction, if they find help, they pause for a moment and then ~you die~ they all engage the player.

> Mobs such as in Scarlet Monastary are running away at 150 or 200% speed.

They're actually not, I did some testing of various NPCs with `/run print(GetUnitSpeed("target"))` while they were running towards me after being first engaged, fleeing to friendlies and fleeing to nothing.  
Fleeing to nothing was always a very slow walk, but fleeing to friendlies is actually only about 10% faster than their normal run, though these mobs' normal run is faster than a player's run so it *feels* much faster, and this is why you can't catch them.

>You can't catch up to them even if they are slowed.

Someone mentioned that if you slow a NPC then it flees, the `UpdateSpeed()` function that executes after the flee function ignores the slow, if you slow a NPC **after** it flees, the slow takes effect.
I did not test any of this.

**Comment by eTzmNcbkrng** [comment]
> I mean: take a level 25 ret paladin into the Blackrock cavern in Northern Redridge Mountains, and solo the cavern

Or instead of a Paladin, take a Warrior that can’t heal. **IF** you survive, cry that the majority of mobs you just killed have decayed before you had a chance to loot them so you have to do it all again to get the quest items you need.

**Comment by apav** [comment]
This is still a major issue, especially in tight spaces such as caves. Sometimes mobs flee at normal running speed, sometimes they zoom at much greater speeds than that.

**Comment by FrancescoBorzi** [comment]
@chromiecraft/bug-triaging what's the status of this?

**Comment by Shevi22** [comment]
This is still an issue, and it is very hard to play around. mobs flee at 150% of a player's movement speed. Normally mobs get reduced movement speed at lower health, but not here. You just cant put two abilities in them as a rogue before they get out of range for you and inevitably call for more allies as they flee.

**Comment by 55Honey** [comment]
> Video evidence of mob fleeing at walking speed even with a friendly NPC within range - https://www.youtube.com/watch?v=8dNMBWh2wxY
> 
> Once at 6:55 and then again at 8:10, in both of these instances the NPCs seem to flee in a random direction and NOT towards their own friendly NPCs.
> Also, note at 8:10 when the NPC is pulled with Frost Bolt and thus has the slow from that spell, it still runs, but in slow motion, when the mobs are fleeing, they are walking, therefore, the slow from Frost Bolt cannot account for the massive reduction in speed.
> 
> If a mob is fleeing from combat, it should always do so at a very slow walking pace, regardless of whether it can see friendly NPCs to run to for help.

I consider this proof enough to change the speed of fleeing humanoids from "run" to "walk"

**Comment by Stifler82** [comment]
@55Honey 
![image](https://user-images.githubusercontent.com/1884642/115150897-4a605b00-a062-11eb-8c82-591e0282063c.png)
https://github.com/azerothcore/azerothcore-wotlk/issues/5342#issuecomment-822008143

https://us.forums.blizzard.com/en/wow/t/wow-classic-%E2%80%9Cnot-a-bug%E2%80%9D-list-updated-dec-3-2020/175887

**Comment by apav** [comment]
> @55Honey
> ![image](https://user-images.githubusercontent.com/1884642/115150897-4a605b00-a062-11eb-8c82-591e0282063c.png)
> [azerothcore/azerothcore-wotlk#5342 (comment)](https://github.com/azerothcore/azerothcore-wotlk/issues/5342#issuecomment-822008143)
> 
> https://us.forums.blizzard.com/en/wow/t/wow-classic-%E2%80%9Cnot-a-bug%E2%80%9D-list-updated-dec-3-2020/175887
> 
> ![image](https://user-images.githubusercontent.com/1884642/115151084-4bde5300-a063-11eb-8d29-5e3cc3694d80.png)

Even if that's true for WotLK, what about the ones that run faster than normal running speed?

**Comment by 55Honey** [comment]
How can a Classic reference outclass a 3.3.5 retail Video? I am Not convinced.

**Comment by FrancescoBorzi** [comment]
> How can a Classic reference outclass a 3.3.5 retail Video? I am Not convinced.

@55Honey if you feel this should be reopened and further discussed I'm fine with it, but let's keep the discussion on the AC side, so more people can contribute to it: https://github.com/azerothcore/azerothcore-wotlk/issues/5342

**Comment by Jamwork** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21899

Here's a link to the trinity core hub where they explored the same issue.
