### ISSUE TITLE
[Feralas] Shay Leafrunner does not spawn

### ISSUE THREAD

**Issue by Orixim** [chromiecraft/chromiecraft#1830]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

The NPC named [Shay Leafrunner](https://classic.wowhead.com/npc=7774/shay-leafrunner) is not spawning. I've waited on her spot for a couple of hours to no avail. Without her, it is not possible to complete the [Wandering Shay quest](https://classic.wowhead.com/quest=2845/wandering-shay) that is supposed to be fixed in this [issue](https://github.com/chromiecraft/chromiecraft/issues/1083).

### Expected Blizzlike Behaviour

The NPC should spawn so players can interact with her and start the quest.

### Source

Experience and WoWHead

### Steps to reproduce the problem

1. Go to Feralas (38, 10).
2. Check that she is not there
3. Wait for as long as you want
4. Check that she is still not there.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
Tested On https://github.com/azerothcore/azerothcore-wotlk/commit/e3e76156341e0e587acc626c9076d8c96bfa3337

I dont have this issue, not confirm

**Comment by Orixim** [comment]
I went back there today and she was there. I've completed the quest without any issue. She started to wander around only once and got under the ground surface, but the bell worked just fine and she came back on track. I guess she either has a huge respawn time or the server reseted in the meantime and solved it. Regardless, I think I will close this for the time being since no one else complained.
