### ISSUE TITLE
Deadmines- Casters still casting spells while moving

### ISSUE THREAD

**Issue by Alaeria-Val** [chromiecraft/chromiecraft#1831]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Defias Evoker (https://wowgaming.altervista.org/aowow?npc=1729) was able to cast Flamestrike(https://wowgaming.altervista.org/aowow?spell=11829) whilst fleeing. This happened multiple times in the dungeon.

clip: https://medal.tv/clips/65788661/d13379GyEvLL

### Expected Blizzlike Behaviour

Expected blizzlike behavior is that mobs should be unable to hardcast spells whilst moving. 

### Steps to reproduce the problem

1. Open an instance of Deadmines
2. Weaken the mob so they flee
3. They will usually cast while fleeing, or before fleeing
4. Repeat a few times if this does not happen. 

### Extra Notes

Sometimes the mob stop casting, or just doesn't cast at all prior or during fleeing. It may take a while to reproduce. It only occurred twice during the run.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
I can confirm that this happens. When they start to flee they present two behaviors: 1) if they don't have any creature nearby, they'll walk slowly 2) if they have other creatures nearby, they'll run very fast towards them.

When situation 2) happens they seem to cast spells while running.
