### ISSUE TITLE
Lock and Load and Frost Trap

### ISSUE THREAD

**Issue by nogunk** [chromiecraft/chromiecraft#1833]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [X] 30-39
- [X] 40-49
- [X] 50-59

### Current Behaviour

Lock and Load is not proccing from frost trap if the enemy is immune to snare effects.

### Expected Blizzlike Behaviour

The Intended interaction is that Lock and Load checks for if the trap was triggered rather than if it successfully snares the target. Currently Frost Trap will trigger on enemies immune to snares which is working as intended but will not grant the lock and load effect.

### Source

https://wotlk-twinhead.twinstar.cz/?spell=56344

### Steps to reproduce the problem

Just place frost trap on a Level ?? Boss or anything immune to snares really, and You can replicate the issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vexima** [comment]
https://wowwiki-archive.fandom.com/wiki/Lock_and_Load

 Patch 3.2.0 (04-Aug-2009): Now has a 22 second cooldown. The Lock and Load effect cannot be obtained on targets immune to snare effects when Frost Trap is used.

**Comment by Nyeriah** [comment]
I need a second opinion on this. Not for the issue itself, that part is invalid - it shouldn't give players the buff if target is immune anymore, as the comment above put it.

But the behavior reported is also wrong. I tested it and you could get the buff from placing **Frost Traps** (the one with the huge snow area of effect that slows everything) under targets that are immune to snares, which shouldn't be the case anymore.

For **Frozen Traps** (the one that encases things in ice), I get the behavior described in this report, no procs happen when the target is immune.

Am I missing something?

**Comment by Nyeriah** [comment]
I'll close this as invalid as there's apparently some confusion and the report doesn't properly describe the behavior we currently experience.

https://github.com/azerothcore/azerothcore-wotlk/pull/8177 will correct the talent proc so it bevahes as it should as of patch 3.2
