### ISSUE TITLE
[Brewfest] Drill to teleport to Grim Guzzler is not inside BRD

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1836]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Drill machine is not present inside BRD

### Expected Blizzlike Behaviour

https://static.wikia.nocookie.net/wowpedia/images/0/08/Brewfest_DarkIronDwarves_Prepare.jpg/revision/latest?cb=20071007061611

Should be inside BRD (Not same as Direbrew's Remote item) as static object that you can click when you enter BRD to teleport to Grim Guzzler

### Steps to reproduce the problem

1. Enter BRD
2. Turn to right without entering any room
3. No Drill for teleport

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
I believe this changed in [patch 3.3.3](https://wowwiki-archive.fandom.com/wiki/Patch_3.3.3) Once you had to queue via the dudgeon finder there was no need for the drills, as he could not be engaged by physically walking into the instance. I tried looking for this in case of wipes but I found nothing that says they should still be there. But, we would need to find a source showing 3.3.5 like behavior. The link you provided isn't working for me.

**Comment by Elexias** [comment]
https://www.youtube.com/watch?v=PsrXzsv5NW0&ab_channel=WoWJNasty Not sure what exansion is this.

**Comment by Stump876** [comment]
That clip shows a level 109 demon hunter, and has instance maps. My guess is it's not from 3.3.5.

Looks like the mole machines were added in Cataclysm 4.0.3 
https://wowwiki-archive.fandom.com/wiki/Abandoned_Mole_Machine 
https://wowpedia.fandom.com/wiki/Abandoned_Mole_Machine
