### ISSUE TITLE
[Brewfest] Dubble Animations for the Keg throw during the Brewfest event

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1837]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Animation for getting kegs is doubled even tripled. You get one of kegs in beg but it looks so spammy on screen.

### Expected Blizzlike Behaviour

They should throw you only one keg, they actually do it, but it looks like it 's more than one when you look at animation

https://www.youtube.com/watch?v=uT4dagUe3pI&ab_channel=WoWJNasty You can see this is Cataclysm + but who cares. You can see NPCs throwing out kegs one by one. Here on our side it's 1000 kegs animation.

### Steps to reproduce the problem

1. Get to Brewfest camp
2. Wait to get to XX:00 or XX:30 server time (event happens every 30 mins)
3. Try to do achievement This One Time, When I Was Drunk... 
4. See animations for keg throwing

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Thanks for the report. I'm sorry, but I'm not quite sure what you mean. Folowing your steps to reproduce, I saw zero kegs being thrown. 

Do you mean keg, or mug? The kegs are for the ram racing and look like large barrels. I don't see any kegs in the youtube clip being thrown. I do see mugs being tossed all over the place. There was a bug where only one barker was throwing mugs. https://github.com/azerothcore/azerothcore-wotlk/issues/8027 but I see no double animation. Player drinks and is tossed one new mug.  But, I don't need to wait for the invasion to do this.

Maybe you were referring to this bug on the horde grounds of the keg animation happeneing when running though the grounds? https://github.com/azerothcore/azerothcore-wotlk/issues/7913 But, I don't need to wait for the invasion to do this either.

**Comment by Shineslippers** [comment]
Right now everything seems is working. I will close it accordingly. If you will see it next year you can leave message there or create new issue.

https://user-images.githubusercontent.com/85256266/142622396-a24d94e2-67a1-41f3-bb87-2d2b13fa8662.mp4

https://user-images.githubusercontent.com/85256266/142622533-7154fcad-f2a9-41be-b9f4-4df159ab118b.mp4
