### ISSUE TITLE
Bonfire & Mighty Blaze in Orgimmar hit twice instantly. 

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#1839]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Most of the Bonfires and Mighty Blaze around Orgimmar hit twice instantly. Some only hit once and I would assume they should all hit once. I am not sure if this is blizzlike and can not find any information about it on the web. 

Video of the issue:
https://youtu.be/LuA-LamcMZQ

### Expected Blizzlike Behaviour

One hit

### Source

I am unable to find a source that they should all hit once. 

### Steps to reproduce the problem

Stand next to Might Blaze or Bonfire in Orgimmar. 

### Extra Notes

https://wowgaming.altervista.org/aowow//?spell=7902

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Ragelezz** [comment]
Those objects hit twice because they are overspawned aka 2 spawns in one place. Confirmed.

**Comment by Ragelezz** [comment]
What you are saying its not related to this issue. This was just regarding the overspawns not missing objects. You can open a Issue with proofs where it should be a bonfire or a mighty blaze and its not spawned and we will check asap. :)
