### ISSUE TITLE
Execute does no damage 4/5 casts and eats rage regardless

### ISSUE THREAD

**Issue by warriorbugs** [chromiecraft/chromiecraft#185]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)[Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE: all of them

________________________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________________________
2) Specify the content phase where this bug belongs to, for example "1-19" or "20-29", etc...
________________________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________________________
-->

##### SMALL DESCRIPTION: Execute does no damage - but consumes rage. Combat log doesn't say it was ever casted

Spell: [Execute(https://www.wowhead.com/spell=163201/execute) 

##### EXPECTED BLIZZLIKE BEHAVIOUR: does damage when used, consumes rage only if it does damage
________________________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________________________
4) Describe how it should be working without the bug.
________________________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________________________
-->

execute should do damage and consume rage, based on how much rage you have up to 30 it should hit harder than when you have less rage

##### CURRENT BEHAVIOUR:
does no damage, and consumes rage about 4/5 casts
________________________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________________________
Describe the bug in detail, then fill in the required fields for your problem (based on the needs of your problem)
Delete the "

##### STEPS TO REPRODUCE THE PROBLEM:
use execute

Step 1 learn execute
Step 2 cast execute
Step 3 notice it does nothing but consumes rage

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Notrox1** [comment]
Encountering the same issue while farming Mobs in Scarlet monastry
Mobs are below 20% - i press execute - followed by the animation but no damage.
Its hard to see why this happens. It does not appear in Combat Log. But the Rage is gone.
By the rate i tested it I would say it happens every 10th execute.


If there is anything i can provide please let me know.

**Comment by illfated** [comment]
@Notrox1 : Consider opening a new issue ticket if you have got enough information to fill in **all** the issue ticket template fields, to make sure your issue is handled correctly. Remember to provide a screenshot and maybe a video, if that can help illustrate the issue.

**Comment by warriorbugs** [comment]
Ok - will record and post video

**Comment by Stifler82** [comment]
> Ok - will record and post video

@warriorbugs
The problem is not only the lack of "Details" such pic and video, the problem is that you have not respected the instructions of the FORM and you have confused in the post.
P.S.
Look at the other open reports of other users, and then look at yours, and you will understand what I mean if it is not clear to you.
