### ISSUE TITLE
Mails are not returned after 30 days

### ISSUE THREAD

**Issue by mdawx** [chromiecraft/chromiecraft#1857]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Mails sent from 2 accounts were deleted after 30 days instead of being returned to sender.

### Expected Blizzlike Behaviour

After the expiry period, the mail is returned to the sender.

### Source

https://wowwiki-archive.fandom.com/wiki/Mail

### Steps to reproduce the problem

1. Send mail with items from 1 character to another 
2. Check if mail is returned after expiry

### Extra Notes

I've sent multiple mails from my 2 chars on the same account (from Szachmat to Deadknight) as an _extended bank storage_. I expected them to be returned after 30 days, but they got lost. I don't know exact number of lost items, but i know for sure that i had multiple stacks of silk cloth.
I didn't check exactly after 30 days. I noticed it about 35-40 days after.
I sent mail to support hoping to verify it in logs on support channel: https://discord.com/channels/788063059926712341/788799234207252540/891060468658085900 and to Roboto.

@eTzmNcbkrng experienced probably the same issue
![obraz](https://user-images.githubusercontent.com/81375770/134773097-3fab103a-d05f-4831-ab52-3b364fc1f0d3.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Should be **deleted**:
- Mails sent by creatures
- COD payment mails
- Mails that were returned (marked as "returned")
- Read mails that got no items (marked as read && has no items)

Am I missing something?

It currently doesn't check if the mail has items before destroying it, I'm working on that.

**Comment by mdawx** [comment]
> The mail has to be read before it expires in order to reproduce it.

Mails were read, for sure.

**Comment by mdawx** [comment]
Thanks @Nyeriah 
I was able to reproduce it as on local server as you said - the trick was to read mail.
1. I sent 2 mails with items and read only one. ![2021-09-25_22-28](https://user-images.githubusercontent.com/81375770/134785478-c5057fca-c449-46c0-8c9b-20149fbcfe53.png)
2. Update expiry_time on table mail for both mails to deliver_time value +1
3. Check mail on sender ![2021-09-25_22-38](https://user-images.githubusercontent.com/81375770/134785524-74d86568-d04f-4db8-82cb-d1a199d2d431.png)
4. Read mail wasn't returned

**Comment by Nyeriah** [comment]
I think as long as they have items, they should be returned to sender, regardless of being read or not. 
As for returned mails, those get deleted regardless of having items or not, as there's nothing left to do in that case (they were already returned once)
