### ISSUE TITLE
Missing death animation for Pridewing Consort / Pridewing Patriarch / Pridewing Wyvern

### ISSUE THREAD

**Issue by qp86nau24** [chromiecraft/chromiecraft#187]
##### ISSUE: FACTION SIDE:

[Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
[Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

15-25

##### SMALL DESCRIPTION:
In Stonetalon Mountains, Pridewing Consort / Pridewing Patriarch / Pridewing Wyvern don't have a death animation.

NPC1: [Pridewing Consort](https://classic.wowhead.com/npc=4014/pridewing-consort)
NPC2: [Pridewing Patriarch](https://classic.wowhead.com/npc=4015/pridewing-patriarch)
NPC3: [Pridewing Wyvern](https://classic.wowhead.com/npc=4012/pridewing-wyvern)

Zone: [Stonetalon Mountains](https://classic.wowhead.com/stonetalon-mountains)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Pridewing Consort / Pridewing Patriarch / Pridewing Wyvern should have an animation upon their death.

##### CURRENT BEHAVIOUR:
When you kill Pridewing Consort / Pridewing Patriarch / Pridewing Wyvern there is no death animation. they stop and remain standing.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Find Pridewing Consort or Pridewing Patriarch or Pridewing Wyvern
Step 2:  Kill it

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
What WoW Client are you using?
**enGB** or **enUS**?

**and regardless of the Client you use, always clear the Cache before opening wow.exe**

**Video test:** [Missing death animation](https://youtu.be/zLg05aC-TPQ)
