### ISSUE TITLE
Quest item for quest "Ghost-o-plasm Roundup" not working.

### ISSUE THREAD

**Issue by Goro81b** [chromiecraft/chromiecraft#1870]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When you use the quest item provided to you on [this quest](https://wowgaming.altervista.org/aowow/?quest=6134), you continuously get a "Requires Dead Goliaths" error message, even if you are at the exact location the quest item is supposed to be used at, as per the comments [here](https://wowgaming.altervista.org/aowow/?quest=6134), i.e. 63,89 in Desolace (the small mound between the two huge skeletons).

### Expected Blizzlike Behaviour

[This](https://www.youtube.com/watch?v=z59WFL8OmtM) is how the quest should work. After using the quest item at 63,89 in Desolace, several [ghosts](https://classic.wowhead.com/npc=11560/magrami-spectre) should spawn, which drop the required [quest items](https://classic.wowhead.com/item=15849/ghost-o-plasm).

### Source

I've included sources from WowGaming, WoWhead Classic and Youtube on my previous comments

### Steps to reproduce the problem

Get [quest](https://wowgaming.altervista.org/aowow/?quest=6134), go to 63,89 in Desolace (small mound between the two big skeletons), use quest item.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Fedora 34

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3418
