### ISSUE TITLE
Quest mark for Thunderbrew Lager does not turn to blue question mark

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#1876]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When you finish "Thunderbrew Lager" (https://wotlkdb.com/?quest=117), you can repeat this quest by turning in more "hops x 5" to the quest NPC (Grimbooze Thunderbrew; https://wotlkdb.com/?npc=239). However, the quest mark above this NPC is still yellow "!", not blue "?"

### Expected Blizzlike Behaviour

Repeatable quest should be marked with a blue "?".

### Source

Watched a few youtube videos on this quest in (self-claimed) classic, and the quest mark all turned blue on completion for the first time. Now, sometimes the initial quest and the later repeatable version are registered as different quests. For this quest, both classic.wowhead.com and wotlkdb.com has only one quest, not two version. Yet videos for the classic quest showed blue "?", so I guess that even for this case (i.e., only one quest exist for both the initial quest and repeatable version), the repeatable version should be marked with a blue "?".

### Steps to reproduce the problem

Accept "Thunderbrew Lager" from Grimbooze Thunderbrew in Westfall, collect 5 hops, turn in to Grimbooze Thunderbrew, and see the quest mark above this dwarf.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
Repeatable quests like these do not fall in same category as daily quests, but rather are treated same as weekly/seasonal quests.
While you can do a daily quest once per day, repeatable quests can be completed unlimited amount of times.
https://classic.wowhead.com/quest=117/thunderbrew#comments here is marked yellow
https://www.wowhead.com/quest=117/thunderbrew-lager marked yellow

A real classic WoW video showing the quest remain yellow after turn in: https://youtu.be/gDfaxVPvz9A?t=166
To see if a videos is really made in classic WoW , look for the clock below minimap and voicechat icon in the chat panel. If those are not there, the video claiming to be classic was made on another private server.
