### ISSUE TITLE
Beached sea creatures and turtles messed up

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#1877]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

There are a total of 4 beached sea creatures and 5 beached sea turtles along Darkshore coast giving out a total of 4 quests called “Beached Sea Creature” and 5 quests called “Beached Sea Turtle”. However, the mapping between the beached sea creatures and turtles and the quests are currently incorrect in the game.

Comparing wowgaming database with wotlkdb and classic.wowhead.com, it seems that wowgaming are displaying wrong quest giver (beached sea creatures and turtles) locations for same Quest IDs.
 
For quest givers from north to south, wowhead and wotlk show quest ids 4727, 4725, 4723, 4722, 4728, 4730, 4731, 4732, 4733, while wowgaming show 4733, 4732, 4731, 4722, 4723, 4725, 4727, 4728, 4730.

### Expected Blizzlike Behaviour

See above.

### Steps to reproduce the problem

1. Search for quests with “beached” in their names on classic.wowhead.com, worlkdb, and wowgaming. There will be 9 on each.
2. Check for consistency between wowhead and wotlkdb and inconsistency between these two and wowgaming.
3. Don’t trust the quest ids I listed in “Current Behaviour”. Need someone careful to double check. In-game validation is also welcome.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
I am a bit confused about your statement. Do you mean that those creatures give the wrong item that start the quest? As in a plesiosaur giving turtle remains and so on? If what's wrong is indeed the "type" of remains, I think it's a very small and forgivable error.
In any case, I would like to add that all quests can be completed and the location of corpses is correct.

**Comment by discorder0** [comment]
Yes, they can be completed. What I meant was, for example, a beached sea creature that is surrounded low level murlocs may be giving out a high level “beached sea turtle” quest; while a beached sea turtle surrounded by high level murloc may be giving out a low level “beached sea creature” quest.

I don’t know what bug is “forgivable”. I just report and see whether they are valid. It is the devs’ job to prioritize the fix.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/8809
