### ISSUE TITLE
Quest bug: The Sleeper Has Awakened

### ISSUE THREAD

**Issue by evillalo985** [chromiecraft/chromiecraft#1878]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

After accepting the quest you never get The Sleeper Has Awakened so it is not possible to awake the NPC after he falls asleep.

 I tried to abandon the quest but I was not able to take it again because the NPC remained in the same position where I left him last time and he was still sleeping.

![image](https://user-images.githubusercontent.com/43247811/135003542-d399c7a0-e1c8-46da-a54b-0491f0d5bbe8.png)

### Expected Blizzlike Behaviour

You need to get the item to be able to continue with the quest. 

Horn of Awakening
![image](https://user-images.githubusercontent.com/43247811/135003114-c2c83951-648b-4476-9a51-d7d69eb9630c.png)

### Steps to reproduce the problem

1. Create an Alliance character at level 17.
2. Go to  Kerlonian Evershade in Darkshore.
3. Accept the quest The Sleeper Has Awakened. 
4. Please confirm if you get the Horn of Awakening.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by discorder0** [comment]
If I remember correctly, the horn is in a box nearby and you need to loot it by yourself.
