### ISSUE TITLE
Free Action Potion should not be purgeable/dispellable/spellstealable

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#1880]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

According to some players, priests, shamans and mages are able to remove the effect of [Free Action Potion](https://www.wowhead.com/item=5634/free-action-potion). This could happen at patch 1.7 as you can see [here](https://wowwiki-archive.fandom.com/wiki/Free_Action_Potion).

However, since patch 2.3 this shouldn't be possible, since the effect of this potion is a buff of Physical School and not magic.
https://wowwiki-archive.fandom.com/wiki/Patch_2.3.0

https://wotlk.evowow.com/?spell=6624
![ 2021-09-28 at 12 13 48](https://user-images.githubusercontent.com/77953030/135059148-4610bfde-7eea-4b68-a2ad-99cfca3c21fc.png)

Also check [this](https://github.com/ccshiro/cc-buglist/issues/1790).

### Expected Blizzlike Behaviour

The Free Action Potion effect should not be purgable in any way.

### Steps to reproduce the problem

Use Free Action Potion
Fight a Mage / Priest / Shaman
Get your buff Spellstealed / Dispelled / Purged
/Cry

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
https://wowwiki-archive.fandom.com/wiki/Patch_2.3.0
[Free Action Potion]: The buff from this potion can no longer be dispelled or taken via Spellsteal.

<html><body>
<div class="comment-header">

DELPylon on 2007/11/08 (Patch 2.2.3) |   |  
-- | -- | --


</div><div class="text comment-body comment-high-rating" lang="en">Effect is undispellable as of 2.3.</div>
</body>
</html>
https://www.wowhead.com/item=5634/free-action-potion#comments

**Comment by cachocarne** [comment]
Thanks for the specific link, @gurveleg
