### ISSUE TITLE
The npc when running away, do not show the message in English.

### ISSUE THREAD

**Issue by pangolp** [chromiecraft/chromiecraft#1887]
### What client do you play on?

esES

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic

### Current Behaviour

When the npc has little life, many times they run away from the place, and when they do it, they show an emote which is not translated to Spanish.

### Expected Blizzlike Behaviour

The text should be displayed in Spanish, if you have this game client.

### Steps to reproduce the problem

1. Attack an enemy, until he has little life left.
2. When running away, the npc will display a text in English indicating that he is running away.

### Extra Notes

None

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### Screenshot
![WoWScrnShot_092921_154651](https://user-images.githubusercontent.com/2810187/135217145-b0b2313f-a3e4-40c8-8f45-db20e34b14e5.jpg)

**Comment by pangolp** [comment]
This report is made for a video tutorial, which explains how to make reports in Spanish. Then, I will create the pull request myself, to solve this message.

```sql
UPDATE `acore_string` SET `locale_esES`="%s intenta huir con miedo", `locale_esMX`="%s intenta huir con miedo" WHERE `entry`=5030;
```

**Comment by Azcobu** [comment]
As the PR that accompanied this report has now been merged, closing this as a fixed issue.

**Comment by pangolp** [comment]
Thanks
