### ISSUE TITLE
[Issue] BG announcement spam

### ISSUE THREAD

**Issue by Snufflenose** [chromiecraft/chromiecraft#1888]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Hello,

I'm aware this isn't a bug, but rather a custom server "feature".
Still, it **bugs** me (pun intended) to no end.
I'm talking about BG announcements. I'm talking about SPAM.

This is what the chat looks like during peak times:

[BG announcement] Warsong Gulch: 1/8
[BG announcement] Warsong Gulch: 2/8
[BG announcement] Warsong Gulch: 3/8
[BG announcement] Warsong Gulch: 4/8
and so on...

I can't be the only one who gets annoyed by this - and to be honest: I would have quit the server for good if I didn't learn I can completely disable server announcements (which I don't want to, because I may now miss server announcements that are actually important).

### Expected Blizzlike Behaviour

Not blizzlike, but at least bearable (and the way it's handled on every other private server I played on):

[BG announcement] Warsong Gulch: started!

Yup, that's enough info - and since it only happens every now and then it's completely fine.

So, please - for the love of WOW - reduce the BG announcement spam.

Thank you!

### Source

Ingame chat

### Steps to reproduce the problem

Not needed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalins + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
This is the wrong place for suggestions - try Suggestions channel on discord. And the BG announcer spam will be reduced when next bracket starts on October 2nd, was said so by staff.

For the time being you can download addon that filters out the bg announcer here https://github.com/mdawx/AnnouncerFilter

**Comment by Snufflenose** [comment]
Thanks for the hint regarding the addon.
Finally, nice & quiet.

**Comment by Daedalus007** [comment]
> This is the wrong place for suggestions - try Suggestions channel on discord. And the BG announcer spam will be reduced when next bracket starts on October 2nd, was said so by staff.
> 
> For the time being you can download addon that filters out the bg announcer here https://github.com/mdawx/AnnouncerFilter

Your AnnouncerFilter link no longer works, gives a 404.

I'd like to say that this should be an option within the UI control panel on the website when logged in instead of telling players to use an addon.  I appreciate it being there for those who enjoy PvP, but it is very 'spammy' for those who are just leveling.

In addition, there doesn't seem to be any way to disable it as it seems to be a 'system' announcement rather than on any specific channel.  Haven't fully tested on my end yet.

It is already Oct 04 and the spam has only gotten more frequent instead of less frequent, FYI.
