### ISSUE TITLE
Paladin class questline "The Tome of Divinity" for ress/redemption bug

### ISSUE THREAD

**Issue by mikkelstreet** [chromiecraft/chromiecraft#1894]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When I accept the 5th part (https://classic.wowhead.com/quest=1781/the-tome-of-divinity) of the chain, I am not provided Symbol of Life (https://classic.wowhead.com/item=6866/symbol-of-life) to ress Henze Faulk (https://classic.wowhead.com/npc=6172/henze-faulk) in Elwynn Forest. 

Other people does not seem to have any trouble with it. I believe it started bugging (not providing me 'Symbol of Life') after I discarded the item accidentally, before accepting the quest again at a later time.

### Expected Blizzlike Behaviour

I should be able to get the Symbol of Life provided after I disbanded the quest and accepted it again.

### Steps to reproduce the problem

1. Accept the quest.
2. Discard the provided Symbol of Life.
3. Abandon the quest.
4. Retake/reaccept the quest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
This is now third such occurance, previously mentioned in #409 and #964 so something has to be off.

**Comment by mikkelstreet** [comment]
According to your linked threads, it definitely seems like the problem/bug only occurs if 'Symbol of Life' is destroyed during the questline, meaning that you won't be provided a new one upon accepting/reaccepting the quest.

**Comment by Daedalus007** [comment]
A very easy fix can be to make 'Symbol of Life' unable to be destroyed, only able to do so upon abandoning the quest.
