### ISSUE TITLE
(BUG) VENOM BOTTLES QUEST

### ISSUE THREAD

**Issue by Klarios22** [chromiecraft/chromiecraft#1895]
### What client do you play on?

esES

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Can not pick the bottles to start the quest.

### Expected Blizzlike Behaviour

Should be enabled pick them and the start it.

### Source

![unknown_2021 09 29-21 49_LI](https://user-images.githubusercontent.com/91663011/135425069-bfe81073-51b5-49a7-af92-ef115cfda6e0.jpg)

### Steps to reproduce the problem

1. Dont know is loot quest.

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=2938

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Correct quets: [Venom Bottles](https://wowgaming.altervista.org/aowow/?quest=2933)

**Comment by Klarios22** [comment]
> Correct quets: [Venom Bottles](https://wowgaming.altervista.org/aowow/?quest=2933). Also wrong bottle, but on my local AC everything is ok. ![WoWScrnShot_093021_141307](https://user-images.githubusercontent.com/85256266/135445113-a5261f98-1f39-46d0-a445-7c649c7c0490.jpg)

Well better for me, cause I never see the exclamation at the map or there

**Comment by cachocarne** [comment]
According to Wowhead comments, there are TWO different locations where you can get the pre-quest (a.k.a. looting the bottles). One of them is at 22,58 and the other at 31,57.

https://tbc.wowhead.com/quest=2933/venom-bottles

![ 2021-09-30 at 19 46 34](https://user-images.githubusercontent.com/77953030/135497174-80c04048-4cc5-49a5-9141-6026239bd16c.png)

**Comment by Azcobu** [comment]
> THHHHXXXX like you said i was clickn the wrong ones, thx my bad, sry for the lost time

If this is solved then I'll close it, thanks to @Shineslippers and @cachocarne for contributing.
