### ISSUE TITLE
[Scholo]The Ravenian has wrong loot table

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1898]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Drops a green or better item at 30% chance with equal chance to each.
![image](https://user-images.githubusercontent.com/84640316/135469910-40a8ade2-fd8b-462b-98cc-bfe052c6397f.png)

### Expected Blizzlike Behaviour

Should at least drop an every time. With varying drop rates.

Similar with the issues below I think we are missing a few reference loot tables that should be shared between various bosses with varying chances in scholo.

https://github.com/chromiecraft/chromiecraft/issues/1896

https://github.com/chromiecraft/chromiecraft/issues/1897

### Source

https://tbc.wowhead.com/npc=10507/the-ravenian

### Steps to reproduce the problem

keira 3 or mysql

### Extra Notes

Compare the creatures that drop these for items. They clearly should be in the same (distinct from others) reference loot table.
https://tbc.wowhead.com/item=14626/necropile-robe
https://tbc.wowhead.com/item=18683/hammer-of-the-vesper
https://tbc.wowhead.com/item=18681/burial-shawl
https://tbc.wowhead.com/item=18682/ghoul-skin-leggings

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
I'm reaching out to a dev who done something simular for his opinion on correcting this. May get a response a bit late due to the holiday week.

**Comment by acidmanifesto** [comment]
Currently Loot table Matches up with UDB (Universale Database) that is established for loot based on verified sniffs and not wowhead or website database scrapes.
In our table we have the following hits on the creature_loot_template:
![image](https://user-images.githubusercontent.com/16887899/148068039-4b2f89ae-a78c-4fae-a080-40f2da3faeb8.png)
With references to reference loot table:
35031 when it comes to groups.

As a side note: Loot tables are not 100% drop on items with every kill regardless of rarity of creature type\boss type.
