### ISSUE TITLE
[Scholo]Darkmaster Gandling has minor issues with its loot table

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1899]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Items and their drop rates
Pattern: Robe of the Void 7%
Recipe: Major Mana Potion 10%
Ace of Portals 3%
![image](https://user-images.githubusercontent.com/84640316/135472204-659ca218-6346-4a32-a64f-6cf45603eac7.png)

### Expected Blizzlike Behaviour

Pattern: Robe of the Void 9%
Recipe: Major Mana Potion 9%
Ace of Portals 5%

### Source

https://tbc.wowhead.com/npc=1853/darkmaster-gandling

### Steps to reproduce the problem

keira3 or mysql

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Same as the other ticket response. I will be reaching out to another dev who has done simular fixes to what you have described with the loot. Will most likely get a response after the holiday week

**Comment by acidmanifesto** [comment]
Currently Loot table Matches up with UDB (Universale Database) that is established for loot based on verified sniffs and not wowhead or website database scrapes.
In our table we have the following hits on the creature_loot_template:
![image](https://user-images.githubusercontent.com/16887899/148072993-9dfcfeab-e9d6-4d1e-8084-113ef211eec3.png)

Loot tables are concurrent and matching exactly to UDB.
