### ISSUE TITLE
[Bug] Troggs in Gol'Bolar Quarry randomly flee at unusual high speed when low on health

### ISSUE THREAD

**Issue by Snufflenose** [chromiecraft/chromiecraft#1903]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I did the quests at Gol'Bolar Quarry in Dun Morogh and while fighting the troggs there (some outside the cave, most inside) I noticed this unusual behaviour:

When low on health they would sometimes run at a speed which doesn't seem normal for a fleeing mob.

They were running so fast that if I hadn't stunned / bursted them I doubt I would have been able to keep up with them.

### Expected Blizzlike Behaviour

To my knowledge they shouldn't flee at this unusual high speed - especially when low on health (usually mobs are moving slower then).

### Steps to reproduce the problem

Fight the troggs at Gol'Bolar Quarry (preferably inside the cave, because the speed is particularly noticeable there).

At low health some troggs will run away at the above mentioned unusual high speed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Snufflenose** [comment]
Meanwhile I moved on to Loch Modan - and it appears like the troggs there show the exact same behaviour.

So, either all troggs are acting weird - or I'm wrong.

**Comment by Snufflenose** [comment]
Alright, further update:

It seems like on Chromiecraft several (all?) humanoids show this kind of strange behaviour - running at great speed when low on health.

Is this working as intended?

**Comment by discorder0** [comment]
Known/duplicate. Search “flee” here or on AzerothCore’s GH page and you will see lots of reports and discussions.

**Comment by Snufflenose** [comment]
Thanks for the heads-up.

Usually I check for duplicates before posting, but apparently I didn't this time.

Apologies
