### ISSUE TITLE
Hunter Volley gets interrupted by Auto-Shot when switching targets while channeling

### ISSUE THREAD

**Issue by phonkala** [chromiecraft/chromiecraft#1912]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Hunter Volley gets interrupted by Auto-Shot when switching targets while channeling the spell. Auto-Shot should not be triggering / breaking Volley cast when channeling and switching targets, no matter if you have Auto-Shot on in Interface > Combat settings.

It is possible to bypass this problem by macroing it with /stopattack before /cast Volley or just turning Auto-Shot completely off from settings but I believe it is still bug, though not game-breaking.

### Expected Blizzlike Behaviour

Switching targets should not let Auto-Shot be cast and break Volley cast while channeling. Volley should finish channeling before Auto-Shot continues.

### Source

Common sense mostly, no auto-attack should break channeling spells. Also quick search with Google found other similar reports too, for example https://github.com/dalaranwow/dalaran-wow/issues/835

### Steps to reproduce the problem

1. Set Auto-Attack / Auto-Shot on in Interface > Combat settings.
2. Start Auto-Attacking a target, for example training dummy.
3. Start channeling Volley.
4. Switch target to any other target that you are able to attack from where you are channeling.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
As far as I know, this happens because of the standard behaviour of Auto Shot/Volley on private servers:
Hunters keep auto-shooting their target while channeling Volley.

Now, I haven't done any research at all regarding this, so I don't know if this behaviour is blizz-like or if it's bugged and needs fixing, the only thing I know is that it's the same on other WotLK private servers (at least the 3 or 4 that I had a hunter character).
