### ISSUE TITLE
 [Scholo]Doctor Theolen Krastinov has wrong loot table

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1916]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Drops a green or better item at 44% chance with 14% on the gloves and remaining 30% distributed equally to chance to each other item.
![image](https://user-images.githubusercontent.com/84640316/135620034-301e3d6a-34ff-4f19-a8bf-693a9516ecce.png)

### Expected Blizzlike Behaviour

Always drops an item with varying drop rates.

In particular Magister's Gloves should drop only at 8% not 14.

Similar with the issues below I think we are missing a few reference loot tables that should be shared between various bosses with varying chances in scholo.

#1896

#1897

### Source

https://tbc.wowhead.com/npc=11261/doctor-theolen-krastinov

### Steps to reproduce the problem

keira3 or mysql.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Same as the other ticket response. I will be reaching out to another dev who has done simular fixes to what you have described with the loot. Will most likely get a response after the holiday week

**Comment by acidmanifesto** [comment]
Currently Loot table Matches up with UDB (Universale Database) that is established for loot based on verified sniffs and not wowhead or website database scrapes.
In our table we have the following hits on the creature_loot_template:
![image](https://user-images.githubusercontent.com/16887899/148071122-ecb66ad6-59d9-487e-ad33-8a8bbc10cfa1.png)
With references to reference loot table:
35031when it comes to groups.

Loot tables are concurrent and matching exactly to UDB.

Loot tables are not 100% drop on items with every kill regardless of rarity of creature type\boss type.
Reference Loot Tables were not 100% either on older wow expansions as well contrary to popular belief due to adjustments in much later expansions.
