### ISSUE TITLE
[Scholo]All bosses are missing generic zone drops

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1922]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

All scholo bosses are missing generic zone / zone boss drops such as thorium lockboxes, major mana pots, random greens, esssence of the undead etc. 
I report here, separately, this overarching issue for all zone bosses as an additional report to the ones below because the fix will involve essentially adding the same drops to all these bosses. Vectus also suffers from this problem but I can see no other issue about his table than this issue.
#1921 #1920 #1919 #1918 #1917 #1916 #1900 #1899 #1898 #1897 #1896 

### Expected Blizzlike Behaviour

All shorts of random greens, gems, lock boxes, major pots, high level random items should drop.

### Source

https://tbc.wowhead.com/npc=10432/vectus
and wowhead pages for other bosses.

### Steps to reproduce the problem

check on keira3 or mysql for the boss loot tables.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Same as the other ticket response. I will be reaching out to another dev who has done simular fixes to what you have described with the loot. Will most likely get a response after the holiday week

**Comment by acidmanifesto** [comment]
Looking into all the other linked issues it all comes down to pretty much the same thing. The Reference Loot Tables.
It is how a creature can essentially drop the same loot as other creatures in the same area.
Reference Loot Tables were not 100% either on older wow expansions as well contrary to popular belief due to adjustments in much later expansions.
Reference Loot Tables were always gaurenteed especially with their usage in 335.
