### ISSUE TITLE
Unable to connect to the server since today

### ISSUE THREAD

**Issue by Snufflenose** [chromiecraft/chromiecraft#1940]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Since I started playing on ChromieCraft some days ago I didn't encounter any kind of connection problems.
I actually last logged in this morning without any trouble.

However, when I tried to log in this afternoon / evening I was permanently stuck at the "Connected" screen.
When I hit "Cancel" it takes me to the "Realm Selection" prompt of ChromieCraft showing the number of my chars.

I repeatedly tried to log in, deleted the WDB folder, even tried to temporarily delete the WTF and Interface folders and also restarted both computer and router - to no avail.

I suspect it has to do with today's update, but ChromieCraft's server status shows normal population numbers, so I guess this isn't a general problem.

What's going on?

### Expected Blizzlike Behaviour

Well, I'd like to log in just like I did the days before...

### Steps to reproduce the problem

I try to log in, but am permanently stuck at the "Connected" screen.

I'm on macOS Catalina and play through Wine (just as ChromieCraft suggests in their Mac connection guide).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by interspheree** [comment]
same here

**Comment by JamesGent** [comment]
This is a confirmed and known issue. The staff are working on it!

**Comment by Snufflenose** [comment]
Thanks for the feedback.

Good to hear it's not an issue on my end and that you guys are already working on it.

**Comment by Snufflenose** [comment]
Seems like the issue was resolved - I was able to log in again right now.
