### ISSUE TITLE
[Razorfen Kraul, Blackfathom Deeps] Pathing broken

### ISSUE THREAD

**Issue by 7Skidoo** [chromiecraft/chromiecraft#1942]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

### Current Behaviour

The mobs aggro/shoot through solid walls, run through walls when "fleeing in fear", in RFK the room with the bats has the tendency to drop bats and the pig boss through the floor.
You can also heal/shoot through walls.

### Expected Blizzlike Behaviour

to not do that and follow proper pathing, like it has before the 50-59 update today

### Steps to reproduce the problem

Try using a low/appropriate leveled char (~25) and stand close to walls with mobs on the other side. They should aggro on to you and start attacking. Only out-ranging them will make them run (through walls) towards you so you can attack them in melee.
Let them flee in fear, chances are good they'll walk right through walls.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by 7Skidoo** [comment]
Server restart just now seems to have fixed the pathing issues in Blackfathom Deeps, can not heal through walls and mobs are behaving properly too

**Comment by gurveleg** [comment]
Thank you for report, but since you say its now fine I'll close this.
