### ISSUE TITLE
blasted lands 

### ISSUE THREAD

**Issue by ZaikoNemesis** [chromiecraft/chromiecraft#1944]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

all the monsters in blasted lands are missing the quest mark when they are part of that quest

### Expected Blizzlike Behaviour

the monsters should have the quest mark when you click on them

### Steps to reproduce the problem

just go to blast lands and accept one quest, the monster you need to kill wont have the mark of that quest when you click on it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by lokhengchau** [comment]
Have the same problem. The mobs' tooltips are missing the quest objectives.

**Comment by jamadaha** [comment]
I'm not quite sure on this one. For one, I can confirm the current behaviour described, see pictures below (Tested all the mentioned quest). However, I can not confirm that it is incorrect. Looking at different videos, all describing themselves as vanilla, the only ones expected bahaviour is those with addons. 
The quests I have tested are:
2581 - Snickerfang Jowls
![image](https://user-images.githubusercontent.com/53914190/137340203-ceb193d2-eb0a-4e88-a50f-8bb794b4407d.png)
![image](https://user-images.githubusercontent.com/53914190/137340265-a9eb6ebc-0dec-4b7e-85d0-44ca0cc6a4b6.png)
![image](https://user-images.githubusercontent.com/53914190/137340444-d8e819e7-3f69-4986-9d50-104ad763fd88.png)
2582 - Rage of Ages
2583 - A Boar's Vitality
2584 - Spirit of the Boar
2585 - The Decisive Striker
2586 - Salt of the Scorpok
2601 - The Basilisk's Bite
2602 - Infallible Mind
2603 - Vulture's Vigor
2604 - Spiritual Domination
2521 - To Serve Kum'isha
2522 - Kum'isha Endeavors
3501 - Everything Counts in Large Amounts

This comment below, and others like it, seem to indicate that those items aren't exclusive for the quest. As such I'm not sure what the correct behaviour is.
![image](https://user-images.githubusercontent.com/53914190/137350729-8f4f0836-7639-4383-a628-0d53f0f05fa3.png)

**Comment by lokhengchau** [comment]
That's interesting.

If it is indeed intended and not bugged, then the cooking quests in Westfall and Loch Modan should also not show objectives in tooltips (quest items are tradable and do not require you to have the quests), but they do.

Maybe they forgot to add to show in tooltips in retail? Perhaps if they can be added to tooltips it can be considered an improvement?

**Comment by Maelthyrr** [comment]
Hi, it's not a bug. Sometimes you don't understand blizzard but it's like this on classic (even there are many years during woltk).
