### ISSUE TITLE
[Stratholme] Mindless Undead giving more reputation than intended

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1956]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

They spawn after killing second to last boss in Stratholme, nearly 50 of em, so you get 500 rep for killing em, and they die in as second, they should give 1 reputation per kil
![WoWScrnShot_100321_125650](https://user-images.githubusercontent.com/80590226/135750762-75dff68a-1b82-4661-a23a-08a43b46d676.jpg)
![WoWScrnShot_100321_125652](https://user-images.githubusercontent.com/80590226/135750763-9ca67355-df4f-4192-b57a-5e1815c5f7eb.jpg)
l

### Expected Blizzlike Behaviour

+1 rep per kill on each mob

### Steps to reproduce the problem

1. Stratholme
2. Kill Ramstein the Gorger
3. Kill those adds

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I think you're probably right about this, but am having trouble finding a source that actually says so. Wowpedia's [Argent Dawn rep guide](https://wowpedia.fandom.com/wiki/Argent_Dawn?oldid=2384820#Reputation) lists Strath trash as giving 10 rep each, stopping at Revered:

![strath-trash-rep](https://user-images.githubusercontent.com/81782124/135799151-1028e802-180c-4419-96fa-491efbf25c95.PNG)

Wowhead's Argent Dawn NPC kill rep listing [here](https://classic.wowhead.com/faction=529/argent-dawn#npcs;100+1+10) doesn't even list Mindless Undead at all. Not sure if that's evidence they shouldn't give any rep at all.
