### ISSUE TITLE
Mage Talent "Master of Elements" restoring 90% less mana than intended

### ISSUE THREAD

**Issue by CadmannG** [chromiecraft/chromiecraft#1964]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

As of the 50-59 bracket update, the Mage talent Master of Elements restores 90% less mana than intended.

### Expected Blizzlike Behaviour

The Mage talent Master of Elements should restore 30% of a spell's base mana whenever the player critically hits. This was working correctly several months ago, during the 30-39 bracket. I did not test it during the 40-49 bracket.

### Source

Talent tooltip.

### Steps to reproduce the problem

Take the talent Master of Elements.
Cast spells until you critically hit, noting the amount of mana restored using the combat log.

### Extra Notes

I tested with 3/3 ranks of Master of Elements, at level 54 (with the highest-level spells available to me at the time). I tested Scorch, Pyroblast, Flamestrike, Frostbolt and Fire Blast, and got less than 10 points of mana back on each critical hit.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by CadmannG** [comment]
This issue seems to have resolved itself for now, and I can no longer reproduce it. I will update with more information if I see it again.

**Comment by gurveleg** [comment]
Okay, I'll close this for now then. If you encounter it again just comment here and we can reopen.
