### ISSUE TITLE
Venomhide Hatchling doesn't grow up

### ISSUE THREAD

**Issue by VFaleiro** [chromiecraft/chromiecraft#1965]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Your [Venomhide Hatchling](https://wowgaming.altervista.org/aowow/?npc=34320) doesn't grow up as you progress through his dailies. He stays baby-sized no matter how many [Venomhide Baby Tooth](https://wowgaming.altervista.org/aowow/?item=47196) you have collected.

### Expected Blizzlike Behaviour

He grows up (his model changes) throughout the quest [They Grow Up So Fast](https://wowgaming.altervista.org/aowow/?quest=13906).

He has 4 models in total (where X is the amount of Venomhide Baby Tooth you have):

- ( X < 6 ) = Baby
- ( X >= 6 and X < 11 ) = Bigger baby with reptile eyes
- ( X >= 11 and X < 16 ) = Adolescent raptor
- ( x >= 16 ) = Full-grown raptor

Some comments indicate other numbers though.

### Source

[Venomhide Hatchling from WowWiki, archived Oct/2010](https://web.archive.org/web/20101001214013/http://www.wowwiki.com:80/Venomhide_Hatchling)
> Unlike other companions (ignoring the fact that it's not a normal companion in itself) it grows as the daily quest progresses. Every five teeth you collect it changes it's model. The picture shown is the model when you first receive the quest. When the 6th tooth is received, it will more closely resemble  [Obsidian Hatchling] or any of the other raptor companions. After the 11th tooth/quest, it is the size of a hunter's raptor or a "teen" sized raptor Mob. When the 16th daily is done, it will resemble the size and shape of a fully grown raptor, and depending on your race, can actually be taller than you.

[Blackriver on 2009/08/10 (Patch 3.1.3) - Wowhead](https://www.wowhead.com/item=46362/venomhide-hatchling#comments:id=805820)
> The hatchling does indeed grow as you complete the quests. He starts as the little bug-eyed guy in the screenshot up there, and gradually grows bigger and older.

[Veph on 2009/08/15 (Patch 3.1.3) - Wowhead](https://www.wowhead.com/quest=13906/they-grow-up-so-fast#comments:id=812373)
> Aww, I love how it grows with you. ^^ Makes you feel like you're really raising this. It's going to be a special mount because you'll remember taking care of it and helping it grow up. It's not like you're just given a mount.

[Reply to Veph by darkxi on 2010/06/12 (Patch 3.3.3) - Wowhead](https://www.wowhead.com/quest=13906/they-grow-up-so-fast#comments:id=812373:reply=451986)
> I just summoned it for the quest today and it has grown! This quest is so cool!

[291891 on 2009/08/09 (Patch 3.1.3) - Wowhead](https://www.wowhead.com/item=46362/venomhide-hatchling#comments:id=805175)
> I'm not completely sure about this, but my hatchling seems to have grown in size after re-summoning him shortly after turning in my sixth daily quest. For one, he's definitely larger than the obsidian hatchling now. Perhaps the hatchling grows as you complete quests?

Also check screenshots from Wowhead pages:
- [Quest: They Grow Up So Fast](https://www.wowhead.com/quest=13906/they-grow-up-so-fast#screenshots)
- [Item: Venomhide Hatchling](https://www.wowhead.com/item=46362/venomhide-hatchling#screenshots)

### Steps to reproduce the problem

1. Add quest 13906;
2. Add 4 of item 47196;
3. Summon you hatchling;

Should be baby-sized (this is currently how he looks at any stage).

4. Dismiss him;
5. Add 3 more of item 47196 (you now have 7);
6. Summon him again;

Should be slightly bigger and have reptile eyes [like in this screenshot](https://wow.zamimg.com/uploads/screenshots/normal/141064-they-grow-up-so-fast-8-teeth-later-and-he-has-gotten-bigger.jpg).
[Stages 1 and 2 for comparison](https://wow.zamimg.com/uploads/screenshots/normal/141101-they-grow-up-so-fast.jpg).

7. Dismiss him;
8. Add 5 more of item 47196 (you now have 12);
9. Summon him again;

He is now a "teenager" and should look [like this](https://wow.zamimg.com/uploads/screenshots/normal/141296-venomhide-hatchling-venomhide-raptor-hatchling-day-11.jpg).

10. Dismiss him;
11. Add 7 more of item 47196 (you now have 19);
12. Summon him again;

This time he should look like any Venomhide Raptor in Un'Goro. [Reference screenshot](https://wow.zamimg.com/uploads/screenshots/normal/176576-venomhide-hatchling.jpg).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Ragelezz** [comment]
Confirmed.

**Comment by cachocarne** [comment]
I don't know if this issue has been fixed. The quest companion is still massive, even bigger than the raptor itself once you complete the whole process.
![ 2023-08-11 a las 14 01 42](https://github.com/chromiecraft/chromiecraft/assets/77953030/2a346b33-5e70-4921-890b-e9690917c879)
![ 2023-08-17 a las 13 39 46](https://github.com/chromiecraft/chromiecraft/assets/77953030/da7e6101-80ca-4888-a6b7-ac92d80863d6)
