### ISSUE TITLE
[Pathfinding] Mobs seem to completely ignore fences

### ISSUE THREAD

**Issue by Snufflenose** [chromiecraft/chromiecraft#1968]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I've noticed that mobs seem to completely ignore fences.

If you aggro a melee mob and jump over a fence, the mob simply follows you by either walking over the fence or clipping through it.

This means fences can't be used for LoS kiting (like trees or tents).

### Expected Blizzlike Behaviour

I expect proper pathfinding - in other words: The mob should walk around the fence.

### Steps to reproduce the problem

1. Aggro a melee mob near a fence.
2. Jump over the fence.
3. Notice that the mob won't walk around the fence, but rather directly over or through it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Daedalus007** [comment]
Pathfinding in general seems kinda busted.  Many mobs in a variety of places will shoot through walls to hit you, clip through/inside the environment to get to you, and more.  I feel a complete geodata rework & reverify may need to be done before calling Azeroth content 'stable'.

**Comment by Azcobu** [comment]
Thanks for the report. This issue with fences is a known, and unfortunately ongoing problem - see https://github.com/azerothcore/azerothcore-wotlk/issues/7072 for a longer discussion. As for pathfinding as a whole, that has its own project in https://github.com/azerothcore/azerothcore-wotlk/projects/16. Closing this as a known issue accordingly.
