### ISSUE TITLE
Unable to start quest Beer Basted Boar Ribs in Kharanos

### ISSUE THREAD

**Issue by akhial** [chromiecraft/chromiecraft#1970]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The NPC (https://wowgaming.altervista.org/aowow/?npc=1267) to start the quest Beer Basted Boar Ribs (https://wowgaming.altervista.org/aowow/?quest=384) doesn't offer the quest, there is no yellow exclamation mark over the NPC and right-clicking it does nothing.

### Expected Blizzlike Behaviour

Should be able to take the quest, the NPC should offer the quest.

### Source

https://wowgaming.altervista.org/aowow/?npc=1267
https://wowgaming.altervista.org/aowow/?quest=384
http://www.ding80.com/alliance_leveling_guide/human_guide.htm

### Steps to reproduce the problem

1. Teleport to Ragnar Thunderbrew (https://wowgaming.altervista.org/aowow/?npc=1267) in Kharanos.
2. Unable to take quest.

### Extra Notes

![Screenshot from 2021-10-04 00-18-38](https://user-images.githubusercontent.com/20596622/135775383-7bbceacf-4f82-4bda-8d09-911e476f83fe.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
This quest requires you to have the Cooking profession in order to start it.

![Skärmbild 2021-10-03 212929](https://user-images.githubusercontent.com/47818697/135778828-a062a29a-598d-4771-b7ea-0e4699a0c37f.jpg)
