### ISSUE TITLE
All mail deleted and item missing from auction house

### ISSUE THREAD

**Issue by VolcanicOoze22** [chromiecraft/chromiecraft#1974]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Posted an Eye of Shadow on Auction House for a bid, canceled the auction and let it sit in my mailbox. I then proceeded to buy potions and food and open them individually from my mail still leaving the eye of shadow in my mailbox. I go and farm for an hour and a half and had to log. I get back on and i notice there isnt mail in my mailbox. All previous reciepts from chromie or auction house are gone and nowhere to be seen as well as the eye of shadow. 

### Expected Blizzlike Behaviour

When I log off for mail to not be deleted, to stay in for 30 days.

### Steps to reproduce the problem

1. Place auction on auction house
2. cancel bid on auction house
3. log out sometime with item still inside mailbox
4. mail is deleted

### Extra Notes

Hope this can fix the issue

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
The commit hash dates before https://github.com/azerothcore/azerothcore-wotlk/commit/9330df59da60c832d7b7eff1ee14c8d765a5935a took place, it'll be hard to investigate this, but I'll check it on master to see if I can reproduce it

**Comment by Shineslippers** [comment]
I had something like this. Once i lost recipe from AH. Maybe 2 weeks ago. It was somewhere  and then appear week later.

**Comment by waiora** [comment]
Stuff i had on AH weeks ago that didnt sell appeared in mail with new bracket release, I wouldnt put too much faith in the mailbox atm

**Comment by eTzmNcbkrng** [comment]
I was playing at launch of the 50-59 bracket, checked mail and then went to vendor. A few minutes later the server crashed (this was 2-3 hours after new bracket release), when I logged back on I checked mail again and my mailbox was completely empty.

That was ~4 days ago, I've just logged on this character now and all of the mail has been returned with original expiry times.

**Comment by ypoptos** [comment]
I also lost all the mails and the items from my mailbox. This happened at 1 of my characters (Kolasi) about 2 or 3 days ago. I didn't find any gm online to report this in case he can fix it and I don't agree with your discord add on (I hate the fact that only you want to force me to give my mobile at discord).

**Comment by Nyeriah** [comment]
@ypoptos cool, thanks for your reply.

I'll close this one as several changes were applied after this issue was opened, so the bug that originated it is likely no longer valid. Let me know if it ends up happening again or if you encounter any other issues related to this.

Thanks once again
