### ISSUE TITLE
Imp's Phase Shift

### ISSUE THREAD

**Issue by Trevis77** [chromiecraft/chromiecraft#198]
##### ISSUE: FACTION SIDE:

Alliance

##### CONTENT PHASE:

level 29

##### SMALL DESCRIPTION:

Spell: [[Phase Shift]](https://classic.wowhead.com/spell=4511/phase-shift)
The imp is still unattackable after it attacked.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The imp should be attackable after it attacked.

##### CURRENT BEHAVIOUR:

The imp is still unattackable after it attacked.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 : Turn off Phase Shift auto-cast.
Step 2 : Make the imp manually attack a mob out of range.
Step 3 : While he is walking to get in range, use Phase Shift manually.
Step 4 : The imp can now cast Firebolts while staying unattackable.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Closed!
-
@Trevis77 
I don't think so..
**Video Test:** [Imp's Phase Shift](https://youtu.be/DN2As-_ae-E)

**Comment by Trevis77** [comment]
Well I just tried it again, it still works. [Here is a video to prove it.](https://www.youtube.com/watch?v=A7kBJyRyEoo) You can see my imp casting Firebolts while having the Phase Shift buff, so I take the aggro where he should.

**Comment by Stifler82** [comment]
> Well I just tried it again, it still works. [Here is a video to prove it.](https://www.youtube.com/watch?v=A7kBJyRyEoo) You can see my imp casting Firebolts while having the Phase Shift buff, so I take the aggro where he should.


@Trevis77 
What WoW Client versione are you using?
**enUS** or **enGB**?

**Comment by eTzmNcbkrng** [comment]
> 
> ## Closed!
> 
> @Trevis77
> I don't think so..
> **Video Test:** [Imp's Phase Shift](https://youtu.be/DN2As-_ae-E)

Your video has the bug in it, your imp didn't drop Phase Shift until you clicked it off.

**Comment by Trevis77** [comment]
> > Well I just tried it again, it still works. [Here is a video to prove it.](https://www.youtube.com/watch?v=A7kBJyRyEoo) You can see my imp casting Firebolts while having the Phase Shift buff, so I take the aggro where he should.
> 
> @Trevis77
> What WoW Client version are you using?
> **enUS** or **enGB**?

enGB

**Comment by Stifler82** [comment]
> > > Well I just tried it again, it still works. [Here is a video to prove it.](https://www.youtube.com/watch?v=A7kBJyRyEoo) You can see my imp casting Firebolts while having the Phase Shift buff, so I take the aggro where he should.
> > 
> > 
> > @Trevis77
> > What WoW Client version are you using?
> > **enUS** or **enGB**?
> 
> enGB

@Trevis77
Perfect!
Burnt the enGB one, and Download the enUS one!
enGB give Client Bug.

**avoid reporting bugs if you have the enGB Client! pls!!!**
-

**Comment by Stifler82** [comment]
@necropola 
Yeah, you are right, I just tested it, my bad, sorry..

**Comment by necropola** [comment]
It also happens against NPCs. Actually only against NPCs, since players have a choice whom to attack.

**Comment by Stifler82** [comment]
> In your video you are manually canceling **Phase Shift** (which should have happened automatically, that's the bug)

It is obvious that "Automatically" does not happen in my video, because the automatic was not set.
To make it happen "Automatically" you have to make the "Spell frame" flash.

And it also happens against the Players too..

https://user-images.githubusercontent.com/1884642/119960992-747c3580-bf9d-11eb-8fcd-267d805725b9.mp4

**Comment by FrancescoBorzi** [comment]
good job @Stifler82 and thanks @necropola for bringing this back, nice team work
