### ISSUE TITLE
Un'goro falling through terrain

### ISSUE THREAD

**Issue by lokhengchau** [chromiecraft/chromiecraft#1980]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Falling through the world when charging at the tar lord at 46 20.
<img width="925" alt="bug1" src="https://user-images.githubusercontent.com/37974241/135939634-d316d027-c6be-4e1c-ba77-31ff810bcec3.png">

### Expected Blizzlike Behaviour

Not falling through the world.

### Steps to reproduce the problem

1. Charge at the enemy at 46 20. (might be difficulty to do this exactly?)

### Extra Notes

Also, there was also a mass disconnects right after and when I logged back in, there was no release button. Thanks GM for resolving it in game.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
Known issue, see
https://github.com/azerothcore/azerothcore-wotlk/issues/6232
#774
#1289
#1477
#1694
#1819

**Comment by VFaleiro** [comment]
Known issue, see
https://github.com/azerothcore/azerothcore-wotlk/issues/6232
#774
#1289
#1477
#1694
#1819

**Comment by VFaleiro** [comment]
Known issue, see
https://github.com/azerothcore/azerothcore-wotlk/issues/6232
#774
#1289
#1477
#1694
#1819
