### ISSUE TITLE
 [59] [Wanted - Deathclasp, Terror of the Sands]

### ISSUE THREAD

**Issue by Md-Knox** [chromiecraft/chromiecraft#1985]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

The quest itself is fine it's trying to hand in that's the issue the NPC: Vish Kozus is not there.

### Expected Blizzlike Behaviour

Expected behaviour is to hand the NPC: Vish Kozus in his spot so you can hand in the quest.

### Source

https://classic.wowhead.com/quest=8283/wanted-deathclasp-terror-of-the-sands#comments

https://classic.wowhead.com/npc=15182/vish-kozus

### Steps to reproduce the problem

Pick up the quest go finish and try and hand in the NPC to hand in "Vish Kozus" isnt there

### Extra Notes

![image](https://user-images.githubusercontent.com/28974715/136004408-2ea99f4b-2f21-47b4-9e69-6302e81cade0.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
Already known by staff, on intention. https://github.com/chromiecraft/chromiecraft/issues/1952
My issue got closed, it's not bug, but their choice.

**Comment by gurveleg** [comment]
Indeed, this is intended so I am closing this accordingly.
