### ISSUE TITLE
Automatic logout timer after being AFK for too long not working

### ISSUE THREAD

**Issue by coyote86** [chromiecraft/chromiecraft#1990]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I was AFK for some time to get some work done and noticed when I came back that the game is trying to log me out repeatedly for being away for too long.
https://i.imgur.com/2qqkkb5.jpeg

### Expected Blizzlike Behaviour

To successfully initiate the 20 second logout timer and then eventually, log you out.

### Source

![2qqkkb5](https://user-images.githubusercontent.com/90635287/136058550-718171f8-26d2-4860-8dd8-d209c21cfee4.jpeg)

### Steps to reproduce the problem

1. Stay AFK for too long
2. Expect the bug to appear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by kuzaan** [comment]
Just wanted to chip in on this issue: 

![Annotation 2021-11-03 213447](https://user-images.githubusercontent.com/72312283/140180491-5b57e0f3-02cd-4caf-bc0d-33ddd3178846.png)

**Comment by Shineslippers** [comment]
It's intentional on CC server.

**Comment by Vishiswaz** [comment]
It may be intentional but it's really bad.

1. You're inflating population numbers by essentially including people who would be logged out on any other server

2. It's impossible to tell who is actually there vs. away from their keyboard for 10 hours.

3. It's incredibly spammy

**Comment by Shineslippers** [comment]
I understand you, but it's config flag on CC. It's not a bug so i can do nothing with this report. You have to visit Discord and leave your suggestion there https://discord.gg/A5XSegyP

**Comment by Vishiswaz** [comment]
Ah, yes. I understand.

Perhaps you can still make the error message less spammy, but otherwise nothing to change in the code.
