### ISSUE TITLE
Gathering Quest While in Party bug

### ISSUE THREAD

**Issue by Cosmic-Lattee** [chromiecraft/chromiecraft#20]
##### SMALL DESCRIPTION:
When in a party with a quest with drops shows it is lootable (see picture below) even if the corpse has nothing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Once the corpse is looted it should no longer be interactable and the cursor should be a gauntlet instead of bag.

##### CURRENT BEHAVIOUR:
The body has no sparkles but you can "loot" it which does nothing and hovering over it shows a bag instead of a gauntlet. When you loot it in this state you bend over to pick something up but nothing happens and no loot window appears.

![Unlootable but shows looting](https://user-images.githubusercontent.com/24766235/105868962-5933f600-5fbc-11eb-8df6-c103aaefeb15.png)

##### STEPS TO REPRODUCE THE PROBLEM:
I had my wife who was playing with me confirm the issue existed on her end. She is not using a UI mod. I did two quests in the BE starting area that had quest drops and they worked like above. I created a new character and the same thing happened. Seems to only happen while in a party.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pangolp** [comment]
Hello, good evening. Thanks for the report, could it be that you found yourself in a group while you were doing the mission? Because that error you mention has happened to me, but only when I was doing missions together with another friend. One person gets the item, but the second or third person gets the bag, because it's like the item is still in the body.

**Comment by Cosmic-Lattee** [comment]
Yeah that is what I meant by being in a party. It seems like the item is made for everyone but only one person can loot it. After that it stays on the body but nobody else can pick it up.

**Comment by Cosmic-Lattee** [comment]
So I ended up getting skinning for my character. If this happens with a mob that is skinnable (where the bag is there but you can't interact with it) then you cannot skin the mob.

However one way to avoid this is by setting the loot to free-for-all.

**Comment by pangolp** [comment]
> Yeah that is what I meant by being in a party. It seems like the item is made for everyone but only one person can loot it. After that it stays on the body but nobody else can pick it up.
> 
> Where as what should be happening (if I remember how wrath and quest items work) the item should be made once and after that the body shouldn't be interactable at all.

Yes, it should be. I for one, what I did once, was that it could be obtained by everyone in the group, but I was informed that it shouldn't be. Even though it is a quest item, not all players should be able to get it. Sometimes yes, sometimes no.

**Comment by pangolp** [comment]
> So I ended up getting skinning for my character. If this happens with a mob that is skinnable (where the bag is there but you can't interact with it) then you cannot skin the mob.
> 
> However one way to avoid this is by setting the loot to free-for-all, at least for mobs you kill after you change this.

If the loot is free, can only 1 of the 2 or more in the group obtain it?

**Comment by pangolp** [comment]
When it happened on my server, what I did was that all the members of the group could obtain the item in the following way, through a flag, in the normal quest items. But then I was informed that certain items would only have to be obtained by 1 of the group members, so we discarded "my solution".

```sql
UPDATE `item_template` SET `Flags`=`Flags`|2048 WHERE `class`=12 AND `subclass`=0 AND `bonding`=4 AND `Quality`=1;
```

**Comment by pangolp** [comment]
@FrancescoBorzi Yes, the error is confirmed, it happened to me before. The temporary solution I found, is the one I left above, but we had a chat at the time, where we discarded it. At least, it was not blizzlike, it was optional, for those who wanted to apply it.

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi Yes, the error is confirmed, it happened to me before.

Thanks @pangolp for confirming this. When a bug report is confirmed, we should follow the procedure explained here:

https://github.com/chromiecraft/chromiecraft#bug-reports

can you please take care of it for this one?

**Comment by pangolp** [comment]
> Thanks @pangolp for confirming this. When a bug report is confirmed, we should follow the procedure explained here:
> 
> https://github.com/chromiecraft/chromiecraft#bug-reports
> 
> can you please take care of it for this one?

Let's see, I will try to do it.

**Comment by pangolp** [comment]
Basically it would be to create a report in the repository, with the tag, and providing the data given by @Cosmic-Lattee?

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi Basically it would be to create a report in the repository, with the tag, and providing the data given by @Cosmic-Lattee?

yes, you can just copy and paste it please

**Comment by pangolp** [comment]
Yes, no problem.

**Comment by pangolp** [comment]
I do not have permissions to view the code and copy it. That is, I can't see the markdown to make it look exactly like the report. @FrancescoBorzi

**Comment by pangolp** [comment]
I had to edit the markdown myself, but I think it looks the same.

**Comment by FrancescoBorzi** [comment]
@pangolp check your email, I've invited you to the github Triagers team so you can edit issues as well

**Comment by pangolp** [comment]
> check your email, I've invited you to the github Triagers team so you can edit issues as well

Excellent, I will check it out. Thank you.

**Comment by Stifler82** [comment]
In my opinion **it is not a CORE bug**, probably **when you are in a group** (since the loot can be shared among the participants of the group), **"the information"** is loaded i**nto the client's Cache**, that is: **(the possibility of looting)** and then in the game Cache the **"animation"** of the loot **is loaded**, so **if one** of the participants **loots the body**, the other will continue to see that **"False loot"** until **"Download"** the information from the client playing the animation by looting.

**Comment by FrancescoBorzi** [comment]
The fix is now on ChromieCraft. Thanks for your report.
