### ISSUE TITLE
WoW Error after my Teammate died in WSG

### ISSUE THREAD

**Issue by Notrox1** [chromiecraft/chromiecraft#200]
##### ISSUE: FACTION SIDE: Horde (maybe Both)

!-- ![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)--
!-- ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)--

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

We played WSG for like 10 Minutes. Then my Teammate Drox died in a fight and i received a WoW Error. This came back everytime I have logged it.
After a few Minutes i got removed from BG with Deserteur and was able to log back in.
My Character: Notrox - 29 Undead Warrior - got switched to Human
Teammate: Drox - 29 Undead Warrior - got switched to Nightelf

I have recorded this BG for trying to capture another issue - if you need i can provide this video. 
I posted a screenshot - this was 1 second after my Teammate died.
https://imgur.com/a/3FPZjbh

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- WoW Error should not occur

##### CURRENT BEHAVIOUR:

WoW Error kept DC me til i was removed from BG

##### STEPS TO REPRODUCE THE PROBLEM:

I dont know how to reproduce

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
Hello, this is due to some issues with some race/class combinations of the "fake races" (the one you get transformed into when your faction is changed). So when a player with such a specific race/class combination dies, everyone around him/her gets client crash.

We have already disabled most of the faulty races, so please let us know which ones are still faulty so we will disable them.

**Comment by FrancescoBorzi** [comment]
@Notrox1 can you please indicate the race and class of the character that was causing the wow errors when dying?

**Comment by Notrox1** [comment]
So we played 2vs2
Me: Undead Warrior as Human
Drox: Undead Warrior as Nightelf (the one who died before error)

Enemys (i dont know the real race)
Tymareth as Undead Mage
Goel as Orc Shaman

Does this help you as informations?

**Comment by FrancescoBorzi** [comment]
thanks @Notrox1 , it would be fine after the next restart. If not, please leave a comment here.

Thank you for reporting this!
