### ISSUE TITLE
Possibly too high spawn rate chance for Azshir the Sleepless in Scarlet Monastery Graveyard.

### ISSUE THREAD

**Issue by InstructionSeeker** [chromiecraft/chromiecraft#201]
##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

It appears that [Azshir's](https://classic.wowhead.com/npc=6490/azshir-the-sleepless#comments) spawn as I've seen him spawn in 7 out of 7 resets I've done GY farming with someone.
Now, [one of the comments for vanilla patch mentions his spawn right should've been 40%](https://classic.wowhead.com/npc=6490/azshir-the-sleepless#comments:id=2905172), so what might've happened:
— Extreme luck, however to get 7 times in a row at 40% chance equals 0.16% chance, which is quite unlikely.
— The spawn rate could've been increased for WotLK (but I can't seem anything to support this).
— [post-edit] The dungeon might not reset their IDs/spawn rolls after instance resets. All the times we've entered the dungeon manually.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Azshir _probably_ shouldn't appear in all the Scarlet Monastery Graveyard runs. 

##### CURRENT BEHAVIOUR:

Azshir appears to be up in all graveyard runs, or just too often.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Enter Scarlet Monastery and go quite a bit into the dungeon.
Step 2: Check if he's up at the graveyard part of the dungeon.
Step 3: Go out of the dungeon, reset it and repeat.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment]
done multiple runs of GY - was up in only 2 of them. I got more runs without any Rare's at all than with him up - will test tho

**Comment by InstructionSeeker** [comment]
Additional comment: we've entered the dungeon manually, not through the dungeon finder.

**Comment by Stifler82** [comment]
to be honest from my test it turns out quite the opposite, really we should raise the% chance.
**Video Test:** [high spawn rate chance for Azshir](https://youtu.be/8kCNh3lCijY)

But daddy Stifler had an intuition, but by any chance there was some server crash between runs?
Be Honest!😂
