### ISSUE TITLE
[Dungeon Quest] - The Archivist (Stratholme) - quest objective not completing for everyone

### ISSUE THREAD

**Issue by TheRiddermark** [chromiecraft/chromiecraft#2011]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

This issue is regarding the quest [The Archivist](https://wowgaming.altervista.org/aowow/?quest=5251).
Two things must happen for the quest to be marked as complete.

1.[Archivist Galford](https://wowgaming.altervista.org/aowow/?npc=10811) slain.
2.[Archive burned](https://wowgaming.altervista.org/aowow/?object=176245)

The issue is with the 2nd. Only one person in our group managed to burn the archive.
At that point the room became full of fire (phased?) and nobody could burn it again thus leaving the quest 50% incomplete for the remaining members. (it didnt reset either)

There is also a secondary issue concerning the [Of Love and Family Quest.](https://wowgaming.altervista.org/aowow/?quest=5848). According to wowhead comments - if you burn the room before looting the picture for this quest, you lose the ability to do so (because it gets burned/phased)

### Expected Blizzlike Behaviour

When a player is burning [the archive](https://wowgaming.altervista.org/aowow/?object=176245) the room shouldn't change/phase for the other players until they burn it themselves.

[From this video](https://youtu.be/8sGRSZ_sMGk?t=453) you can see the exact moment where the player enters the room - the others are hacking at the table (burning the archive) but nothing is changing until he does it himself. Then the room is set ablaze and the quest completes for him as well.

[WowHead comments](https://classic.wowhead.com/quest=5251/the-archivist#comments)

### Source

Linked video and wowhead comments in expected behaviour.

### Steps to reproduce the problem

Go with a group all of you having the quest [The Archivist](https://wowgaming.altervista.org/aowow/?quest=5251).
Let one burn the archive and see if the room burns/phases for the rest too, making it impossible for them to complete objective.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
As i see it's already reported and fix even could be with next server update. 
https://github.com/azerothcore/azerothcore-wotlk/issues/4456
