### ISSUE TITLE
Missing event after turning in Helcular's Revenge in Hillsbrad Foothills

### ISSUE THREAD

**Issue by InstructionSeeker** [chromiecraft/chromiecraft#202]
##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Quest: [Helcular's Revenge](https://classic.wowhead.com/quest=553/helculars-revenge)
NPC_Start: [Novice Thaivand](https://classic.wowhead.com/npc=2429/novice-thaivand)
GameObject_End: [Helcular's Grave](https://classic.wowhead.com/object=1767/helculars-grave)

Additional information: the Southshore are neutral towards Horde meaning we don't get attacked, which doesn't seem correct. But that might call for another issue thread.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be a small roleplay event of the NPC rising from the grave and attacking the Southshore guards and alliance players.

##### CURRENT BEHAVIOUR:

Nothing happens after turn in.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Pick up the quest at the Novice Thaivand in Tarren Mill.
Step 2: Complete the objective.
Step 3: Turn in the quest at Southshore graveyard,

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@InstructionSeeker 
Like here? [[Helcular's Revenge 2/2] - ******(7:48 / 8:38) min******](https://youtu.be/7mhfTCPHdxw?t=468)

**Comment by InstructionSeeker** [comment]
Yeah, [and there's also a message he spawns with.](https://classic.wowhead.com/quest=553/helculars-revenge#videos:id=166863)

**Comment by Stifler82** [comment]
btw, this example of the quest like **"Video Example"** is better...

[Hercular in Southshore](https://www.youtube.com/watch?v=SxdeSFuAsBs)

**Comment by Stifler82** [comment]
Fixed!
-
@InstructionSeeker
**Video Test:** [Helcular's Revenge](https://youtu.be/uTFaIo2bw50)
