### ISSUE TITLE
Mux Manascrambler has wrong dialogue

### ISSUE THREAD

**Issue by stoudtlr** [chromiecraft/chromiecraft#2021]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Mux Manascrambler shows two dialogue options that shouldn't be there.
![image](https://user-images.githubusercontent.com/36058236/136553472-7158cce7-bbd5-42d0-aa9b-2c9340e03bb0.png)
First option is from quest "Return to Deliana"
Second option is from quest "Hunting for Ectoplasm"

### Expected Blizzlike Behaviour

Dialogue options should only be there if you have the relevant quests and lost the quest item.

### Steps to reproduce the problem

1.  .teleport gadgetzan
2.  speak with Mux
3.  you'll see both dialogue options even though you don't have either of the quests

checked on clean build of AC and issue present there as well
![image](https://user-images.githubusercontent.com/36058236/136557466-9a745a6f-0047-4be9-ac2d-c6b7550b7915.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Win10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
Dec 14 2021:
Window still contains wrong dialogue; he would talk about the items from those quests even at lower level and when not doing any of the quests.
![ 2021-10-07 at 23 18 38](https://user-images.githubusercontent.com/77953030/146130070-80b3bdb3-5fc5-4842-a575-8898fc0af0e0.png)

**Comment by Gultask** [comment]
It's fixed now. Since it was merged only 5 days before cachocarne's screenshot I would assume that the CC server hadn't updated to that commit yet.

Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9442
