### ISSUE TITLE
[Scholomance] Gandling walks through closed gate if his target was moved into the room by "Shadow Portal"

### ISSUE THREAD

**Issue by 7Skidoo** [chromiecraft/chromiecraft#2022]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Gandling will sometimes cast "Shadow Portal" targetting a random player.  The chosen player will then be teleported into a seperate room that is impossible to get in/out of until the trash mobs in the room are defeated, essentially locking out the other four party members,
If the player he choses is the tank (or whoever has aggro) Gandling will then walk through the closed gate into the room with the seperated player.

### Expected Blizzlike Behaviour

If the tank (or whoever has aggro) becomes the target of "Shadow Portal" Gandling then should stay with the other four members of the group and not walk through a solid closed gate.

I don't know who should get aggro if Gandling teleports the highest threat party member away, I assume the second highest in threat instead of an aggro reset.

### Source

Nothing good, just implications, here goes:

> https://www.icy-veins.com/wow-classic/scholomance-dungeon-guide (Classic but the best I can find)
> "6.13. Darkmaster Gandling
> Darkmaster Gandling has a unique mechanic that will occasionally teleport a party member into one of the guardian rooms, which remains locked until all the mobs inside it are killed. Players who are teleported should kill the mobs as soon as possible to return to the group and continue helping to kill Gandling. It is possible for the tank and healer to be teleported as well, and care should be taken when either of these are not present to reduce incoming damage by getting as many interrupts on Arcane Missiles Icon Arcane Missiles as possible, and decurse Improved Shadow Bolt Icon Improved Shadow Bolt from affected party members."
> 
> Strongly implies he will stay with the remaining four players but I am unable to find who he should target instead of the tank, I assume the second highest in threat, an aggro reset would be kinda odd but that'd still be an improvement

> https://youtu.be/K0hR2pEUw3k?t=291 at 04:50
> "How to reach Darkmaster Gandling (Scholomance)" from "elrania"
> Level 80 hunter that solos the boss, video uploaded in 2010, I assume this is during Wrath.
> Gandling doesn't use Shadow Portal here but the uploader says "it's a bit annoying if he does because you'll have to kill a few mobs before you can get out again".
> Implying you need to do that before you can kill the boss.

### Steps to reproduce the problem

Go to Scholo, get to Gandling, (clear all adjescent rooms to get him to spawn, 6 total).
Engage him, his "Shadow Portal" spell should be on a timer. If you kill him too fast he should not cast it at all.
Since you are the only one it should target you but having another char to take part in the fight (that Gandling could aggro on to once the highest threat player is gone) would get a more clear result.
Watch as he walks through the then closed gate into your room.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report, and for trying to find some good sources. Gandling chasing the tank instead of staying in the room to fight the rest of the party is a known issue - see https://github.com/azerothcore/azerothcore-wotlk/issues/1806, and that's what's making him run through the gates. Closing this accordingly.
