### ISSUE TITLE
Felhunter spell lock

### ISSUE THREAD

**Issue by EllieSca** [chromiecraft/chromiecraft#2026]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59

### Current Behaviour

Warlock Felhunter pet ability "Spell Lock" currently only interrupting spellcasting and not silencing the target.

### Expected Blizzlike Behaviour

"Spell Lock" should silence it's target alongside interrupting current spellcast.

Current ability tooltip: https://i.imgur.com/acd4fhB.png
Wowhead comment talking about the silence effect: https://i.imgur.com/XA9w3tV.png

### Source

https://www.wowhead.com/spell=19647/spell-lock
+in game tooltip https://i.imgur.com/acd4fhB.png

### Steps to reproduce the problem

1. Cast "Spell Lock" on any target
2. Silence effect does not appear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Artix OpenRC

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
Maybe only one rank of Spell Lock is bugged?
- [Spell Lock (Rank 1)](https://wowgaming.altervista.org/aowow/?spell=19244) requires level 36
- [Spell Lock (Rank 2)](https://wowgaming.altervista.org/aowow/?spell=19647) requires level 52
Learning rank 2 makes rank 1 unavailable I think.

**Comment by EllieSca** [comment]
Just dinged 52 and can confirm, rank 2 works as intended while rank 1 does not.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9765
