### ISSUE TITLE
[Quest]-The-Manor-Ravenholdt Bugged (premature completion)

### ISSUE THREAD

**Issue by Hemingway1970** [chromiecraft/chromiecraft#203]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

Likely 30-39 but also all

##### SMALL DESCRIPTION:

Quest: [The Manor, Ravenholdt](https://www.wowhead.com/quest=6681/the-manor-ravenholdt) 
Quest gets complete ahead of time

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The quest should only be completed upon NPC death.

##### CURRENT BEHAVIOUR:

Quest gets complete as soon as you enter the cave.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Enter cave to Ravenholdt
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Hemingway1970 
What WoW Client version do you have? **enGB** or **enUS**?

**Comment by Stifler82** [comment]
**Video Test:** [The Manor Ravenholdt](https://youtu.be/-xkpiYtMQdk)

**Comment by Stifler82** [comment]
@Hemingway1970

**Faction:** [Wowhead Link - Ravenholdt](https://classic.wowhead.com/faction=349/ravenholdt)
**Video Test:** [Manor Ravenholdt, from the right path](https://youtu.be/-rEpn_VKlUE)

![image](https://user-images.githubusercontent.com/1884642/111607321-09112d00-87d0-11eb-8443-85854e2ed91a.png)
