### ISSUE TITLE
Warrior Protection One Handed Weapon Specialisation does not work

### ISSUE THREAD

**Issue by j4rNit5ch4r** [chromiecraft/chromiecraft#2037]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

I noticed that the warrior protection skill "One handed Weapon specialisation" that increases weapon damage by 10 % and therefore should balance out the -10% damage from defencive stance does not work.
In the character sheet the weapon damage still says "... x95%" regardless the fact that i maxed this skill.

Is this a known issue or will this be fixed?

character Name: Brausi (human warrior lvl 40)

Best regards
JarNitschar

### Expected Blizzlike Behaviour

With maxed out skill "One handed Weapon specialisation" weapon damage should not be decreased when using defensive stance.

### Steps to reproduce the problem

Max out "One handed Weapon specialisation" in warrior protection talent tree 
acivate defensive stance
open character sheet
confirm that "x95%" is not visible and weapon damage is not decreased by 10% any longer through defensive stance
(the percentage amount should be lower with every talent point invested)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report.
I think it still works fine, see below. The .0.95, I think, represents the defensive stance regardless of other buffs.
See before taking the talent:
![image](https://user-images.githubusercontent.com/53914190/136663823-cf6d70c2-bd69-44ba-9b7f-224aa5988995.png)
And after:
![image](https://user-images.githubusercontent.com/53914190/136663812-4a65c641-f955-4f7a-944d-e66b9185cca5.png)
Control - Neither defensive or specialisation:
![image](https://user-images.githubusercontent.com/53914190/136664082-44a7c3aa-bd9c-40c7-a7e6-f1b51ea65949.png)

**Comment by VFaleiro** [comment]
@jamadaha
> The .0.95, I think, represents the defensive stance regardless of other buffs.

Not really, [Sayge's Dark Fortune of Damage](https://wowgaming.altervista.org/aowow/?spell=23768), for example, is properly shown in the paperdoll frame in defensive stance (or any stance for that matter).

This report is valid I guess, I'm just not sure if what's broken is the whole talent or just the visual/calculation part in the paperdoll frame (more likely I think).
I for one couldn't find any source of it not being shown calculated in the paperdoll frame.

**Comment by Daedalus007** [comment]
Test on a training dummy before using character sheet as a reference.  Many known 'blizzlike' visual bugs where it doesn't show the proper numbers.  So grab a DPS meter (recount or your choice) and show some actual numbers before/after.  You have free respecs so should be easy for you.
