### ISSUE TITLE
[Bug] Dying from fall damage when landing in Ironforge (while being alt-tabbed)

### ISSUE THREAD

**Issue by Snufflenose** [chromiecraft/chromiecraft#2038]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

This happened twice already:

I'm taking a gryphon ride to Ironforge (I think it was both times from Menethil) and alt-tab to desktop (or rather cmd-tab since I'm playing on Mac via Wine).

Once I tab back in after my char has landed, he dies from fall damage.

After clicking "release spirit" my char gets resurrected - the first time right in front of the Gates of Ironforge, the second time at the graveyard in eastern Dun Morogh.

It also says I can't log out afterwards.

![Bildschirmfoto 2021-10-09 um 15 08 40](https://user-images.githubusercontent.com/91610030/136659502-21dd2e7c-a522-412a-8ad0-6d667f63bba9.png)

![Bildschirmfoto 2021-10-09 um 15 21 38](https://user-images.githubusercontent.com/91610030/136659650-489b74ac-8e00-4130-adc8-ee85788ca46b.png)

![Bildschirmfoto 2021-10-09 um 15 35 32](https://user-images.githubusercontent.com/91610030/136660012-6e48698b-f128-45d7-a5cd-6312ec7d32b2.png)

### Expected Blizzlike Behaviour

This shouldn't happen at all.

### Steps to reproduce the problem

I have no idea if this is a recurring problem or if it happens by chance, but this is how it happened to me:

1. Take the gryphon (from Menethil) to Ironforge.
2. Alt-tab to desktop.
3. Profit... erm... die from fall damage when tabbing back in after your char has landed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ntrna** [comment]
https://github.com/chromiecraft/chromiecraft/issues/1663
