### ISSUE TITLE
Pattern: Raptor Hide Harness not learnable by alliance LW

### ISSUE THREAD

**Issue by Hemingway1970** [chromiecraft/chromiecraft#204]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:
N/A

##### SMALL DESCRIPTION:

The [Pattern Raptor Hide Harness](https://classic.wowhead.com/item=13287/pattern-raptor-hide-harness) is not learnable by alliance LW

Patten is sold by [Tunkk](https://classic.wowhead.com/npc=2819/tunkk)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Pattern should be learnable by any Leatherworker with the proper skill level. 

##### CURRENT BEHAVIOUR:
Recipe is not learnable by alliance LW and gives the error "You will never be able to use this item"

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Obtain pattern on skilled alliance Leatherworker either by in game mail or by AH
Step 2 Attempt to learn pattern
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Closed!
-
**Invalid Report** 
**Video Test:** [Pattern - Raptor Hide Harness](https://youtu.be/3WJ2hOJCJhA)

**Comment by necropola** [comment]
@Stifler82 Not so fast, please.
It's true that the [Pattern: Raptor Hide Harness](https://wotlkdb.com/?item=13287) as well as its counterpart [Pattern: Raptor Hide Belt](https://wotlkdb.com/?item=13288) fall into the category of Horde/Alliance-only recipes. But this mainly means that there is no direct source (vendor, trainer) for the opposite faction.

But unless such a pattern is **Bind on Pickup** it can be traded via the **Neutral Auction House**
* https://wow.gamepedia.com/Category:Horde-only_recipes
`This category lists recipes that are only obtainable by Horde characters through quests or faction-specific vendors. They cannot be obtained by Alliance characters except through the neutral auction house. See Category:Alliance-only recipes for a list of Alliance-only recipes.`
* https://wow.gamepedia.com/Category:Alliance-only_recipes
`This category lists recipes that are only obtainable by Alliance characters through quests or faction-specific vendors. They cannot be obtained by Horde characters except through the neutral auction house. See Category:Horde-only recipes for a list of Horde-only recipes.`

Even more interesting is the result of the following DB query on current AC. It shows that the Horde recipe (Harness) is flagged (for Horde-only) while the Alliance recipe (Belt) is not. I therefore suggest to remove the flag on the Horde recipe, too.
```
SELECT entry, name, FlagsExtra FROM item_template WHERE entry IN (13287, 13288);
+-------+------------------------------+------------+
| entry | name                         | FlagsExtra |
+-------+------------------------------+------------+
| 13287 | Pattern: Raptor Hide Harness |          1 |
| 13288 | Pattern: Raptor Hide Belt    |          0 |
+-------+------------------------------+------------+
```

**Comment by necropola** [comment]
@Stifler82 I woudl like to copy/link this issue to AC and suggest the following change. What do you think?
```
UPDATE item_template SET FlagsExtra=0 WHERE entrry=13287;
```

**Comment by nolt** [comment]
I agree, I tested also this modification and I think bug is in this flag. Recipe should be learn by both faction but not obtained as described above.

**Comment by Stifler82** [comment]
@Hemingway1970 
he should have reported what you @necropola described, not that: **"The Pattern Raptor Hide Harness is not learnable by alliance LW"**.
btw, put in these terms, the report is valid then..
Good Job @necropola and Good Job @nolt as well.
