### ISSUE TITLE
Darkmaster Gandling can, at times, run through locked gates

### ISSUE THREAD

**Issue by BobsenJr** [chromiecraft/chromiecraft#2043]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

At the end of the Scholomance dungeon, Darkmaster Gandling, the final boss, has a unique gimmick ability where he teleports one of the players into an adjoining room, which is then locked. The player will then have to fight his way out of the room by killing the mobs inside, to then rejoin the fight against Gandling. 

What happens at present is that if the person who is tanking Gandling is teleported, Gandling keeps his threat against said person, and will chase the tank into the locked room, bypassing the door if necessary. This means that a situation may arise where only the tank, the mobs and Gandling are inside the "challenge" room, while the rest of your party stands outside looking in. 

At present this is not a 100% of the time bug. I have noted in previous runs that when I was teleported, Gandling would stand outside the door, but I have also observed him run inside the room. I was a little hesitant in posting this bug, as I cannot replicate it 100%. 

### Expected Blizzlike Behaviour

Gandling is supposed to drop threat against the person that has been teleported and continue the fight against those who are still present. This is supposed to be a challenge, seeing as a tank or healer going astray could have dire consequences for the party. Instead, he simply follows the highest threat level into the other room, making the fight a lot more trivial. 

### Source

https://www.wowhead.com/npc=59080/darkmaster-gandling#comments

-- Comments seem to backup the claim that Gandling drops threat against whomever is teleported. 

### Steps to reproduce the problem

1. Enter the scholomance instance
2. Clear the dungeon appropriately to summon Gandling
3. Initiate the fight. 
4. Have the primary threat be teleported into a side-room (this may take some work, as there is no guarantee he teleports the tank) 
5. Observe Gandling either pursuing or not pursuing the tank. 

### Extra Notes

I can be contacted Bobjr#4761 or on SPQR/Optimates/Populares on the Chromiecraft Discord. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. As you say, Gandling chasing the tank all the time removes the whole point of the fight. However, this is a known issue - see https://github.com/azerothcore/azerothcore-wotlk/issues/1806 - but I've upgraded its priority in view of this and another recent report we've received. Closing this as a duplicate accordingly.
