### ISSUE TITLE
[Stormpike Guard] Rep-gated quests & rewards available w/out rep

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#2047]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I have Stormpike Insignia Rank 6, which requires Exalted reputation with the Stormpike Guard, while my reputation is at Neutral (got to friendly from doing the quests to upgrade the Insignia from Rank 1 to rank 6)

### Expected Blizzlike Behaviour

Each upgraded Rank of the Stormpike Insignia requires the next level of reputation with the Stormpike Guard

### Source

quest text. I'll source if needed

### Steps to reproduce the problem

TP to GUID 16611, Entry 13217
loot yourself https://tbc.wowhead.com/item=17849/stormpike-banner // https://www.wowhead.com/item=17849/stormpike-banner
complete quest 7162, Proving Grounds
read quest text of followup quest

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ntrna** [comment]
Also, the later quests are offered again, after they have already been complete
![WoWScrnShot_100921_235458](https://user-images.githubusercontent.com/89823720/136681485-a6b97e98-100b-44c1-855e-01ccf8333d67.jpg)
d
![WoWScrnShot_100921_235348](https://user-images.githubusercontent.com/89823720/136681493-eaf64625-32fd-49c0-b0b4-086a320c0e87.jpg)
.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9222
