### ISSUE TITLE
Golden Pearl drop rate from Big-Mouth Clam

### ISSUE THREAD

**Issue by Velomania** [chromiecraft/chromiecraft#2051]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I've been farming [Big-mouth Clam](https://wotlk.evowow.com/?item=7973) for [Golden Pearl](https://wotlk.evowow.com/?item=13926) for quite a while.  And I've opened roughly 25 stacks of clams so far. There are different drop rates of these clams on wotlk dbs, so I was wondering what the drop rate of Golden Pearls on our server is?
And some [screenshots:](https://imgur.com/a/SOjRBiK)
First, I opened 90 clams and see what I got. Then, I opened 14 stacks. Unfortunately, I didn't take a screenshot, but I got 18 black pearls and other ones, but no golden pearls!

### Expected Blizzlike Behaviour

What is a drop rate of [Golden Pearl](https://wotlk.evowow.com/?item=13926) from [Big-mouth Clams](https://wotlk.evowow.com/?item=7973) on the server?
Take a look at the different drop rates from various wotlk dbs:
1. https://wotlkdb.com/?item=13926#created-by
2. https://wotlk-twinhead.twinstar.cz/?item=13926#created-by
3. https://db.rising-gods.de/?item=13926#created-by

[Wowhead ](https://classic.wowhead.com/item=13926/golden-pearl#contained-in-item)offers 0.5% drop rate.

### Source

1. https://wotlkdb.com/?item=13926#created-by
2. https://wotlk-twinhead.twinstar.cz/?item=13926#created-by
3. https://db.rising-gods.de/?item=13926#created-by

### Steps to reproduce the problem

1. Take a look at the drop rate of Golden Pearl from Big-mouth Clams.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
As far as my understanding goes, those are the databases of different private servers.

**Comment by Steelcold** [comment]
Where did the droprate on our server come from then?

**Comment by Steelcold** [comment]
I don't think this is entirely correct given the fact that we are playing on a wotlk server, not classic one. Is it possible to slightly raise the drop rate?

**Comment by jamadaha** [comment]
It would be possible, given a source. That is unlikely tho, seeing as two of the primary sources [Wowhead](https://tbc.wowhead.com/item=13926/golden-pearl) and [Wowpedia](https://wowpedia.fandom.com/wiki/Golden_Pearl?oldid=2460450), both don't contain any information contradicting 0.5%.

**Comment by jamadaha** [comment]
That is true, and one of the reasons as to why Wowhead is not the perfect source — especially for drops. It is, however, the easiest source to check. Moreover, the fact that something "could" have changed, is not enough reason to change something. 
If you, or someone else, can find a primary source — such as sniffs from retail — that contradicts Wowhead, please add them, as that will indicate a change.
The issue is still, that private server DBs aren't a reliable source.

**Comment by Daedalus007** [comment]
Just saying, tbc.wowhead.com is closer to what WotLK has for Azeroth-related droprates. A metric-ton of changes were made between Classic and TBC almost globally whereas the difference between Azeroth drops in TBC to WotLK were a bit less.  Mostly mobs nerfed or made non-elite but not much else.
