### ISSUE TITLE
[Scholomance] Risen Aberration should take Holy Damage

### ISSUE THREAD

**Issue by LundmarkJ** [chromiecraft/chromiecraft#2052]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Risen Aberration is immune to all schools of magic damage including Holy Damage
https://streamable.com/dagfly

### Expected Blizzlike Behaviour

They should be immune to all schools but holy.

### Source

https://youtu.be/f4_de09IVBw?t=206 (Low Quality old video, show them taking Consecration damage)
https://youtu.be/cxuMNiOiXcQ?t=327 (Classic TBC, here you can see them again taking Consecration damage)

### Steps to reproduce the problem

1. ``.tele Scholomance``
2. Take an immediate right and jump off the bridge.
3. Use a Holy Spell that deals damage (`` .learn 2812`` or ``.learn 20923`` are options)
4. Mob is Immune.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
I could replicate it with the priest spells: holy fire, smite and holy nova.
![image](https://user-images.githubusercontent.com/53914190/136707927-3d139d85-67ef-43f5-8ea5-460c425750a9.png)
Also found that they are immune to the spell 2812 (Holy wrath):
![image](https://user-images.githubusercontent.com/53914190/136708049-1c0bb804-26dc-4267-bf49-7bc2edc595ac.png)
I found some mixed signals on consecration, on one hand it states that the mob is afflicted by it:
![image](https://user-images.githubusercontent.com/53914190/136708137-9a9ba0f0-0a1b-48a1-b5df-39e57328ef2c.png)
On the other it says that it is immune:
![image](https://user-images.githubusercontent.com/53914190/136708110-f30680a4-2062-4274-a067-3993f3ea1baf.png)
But I should note that I never did see them take damage from it.

Also found both [Wowpedia](https://tbc.wowhead.com/npc=10485/risen-aberration#comments) and [Wowhead](https://wowpedia.fandom.com/wiki/Risen_Aberration?oldid=2479345)(See comments) to agree that they should be vulnerable to holy.

**Comment by iEmpress** [comment]
![image](https://user-images.githubusercontent.com/82000605/136716203-9b5c0af7-229c-4781-9389-18b0955f6021.png)
Wynterknight from my guild just recently did the dungeon again.
