### ISSUE TITLE
All Absorb damage effect are gone (for any damaging skill, both melee and ranged, both from players and mob)

### ISSUE THREAD

**Issue by Lessarcy** [chromiecraft/chromiecraft#2062]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

any shield or other damage absorb effect like Soul link doesn't work whit Skill Damage (from mob and players), absorb seems that work correctly on melee white damage (from mob and players).
currently i tested soul link, void sacrifice spell, power world shield, and mana shield (whit mana shield the mage lose both mana and hp on enemy damaging skill).
i attach a screen of combat log, like you can see i take both damage and total shield pool absorb reduction
![absorb gone](https://user-images.githubusercontent.com/92327090/136826540-e2ed8b92-9a4e-497e-b400-b04d9cd1f7a1.jpg)
.

### Expected Blizzlike Behaviour

absorb must absorb damage

### Steps to reproduce the problem

just test it on a player whit a shield or any absorb effect

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Hi, this has been fixed. See [here](https://github.com/azerothcore/azerothcore-wotlk/pull/8427).

**Comment by slicplaya** [comment]
Can we get a tag when it's fixed? This is HUGEEEEEEEEEEEEEEEEEEEEEEEEEEEEE! thanks
