### ISSUE TITLE
Night Dragon's Breath in felwood

### ISSUE THREAD

**Issue by Lionseye** [chromiecraft/chromiecraft#2075]
### What client do you play on?

other

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59

### Current Behaviour

I need the flower for my +100 hp enchants, I need two of them. I simply cannot find them after 4 days. Before the 59 patch they were spawning, but I cannot verify why they're not popping up. It could be someone is grabbing them all in felwood for some reason. Or it could be they simply are taking too long to spawn. I do not know.

The spawn time is simply too long right now. It was not this long before the 50-59 patch unlocked.

I have gone 4 days and cannot get the flower.

### Expected Blizzlike Behaviour

So there's a plant called Night Dragon's Breath that spawns in felwood. It is spawning at a MUCH later time than the game. I do not know why.

### Steps to reproduce the problem

1. Go to felwood and try to find the flowers of any kind. They are not spawning at the intended time. We have MUCH less people and they're spawning much slower.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Hello,

Thanks for taking the time to report this. They'll respawn properly the next time the server is synchronized with AC.

**Comment by Shineslippers** [comment]
I hope it solved. Idk where AC report.
