### ISSUE TITLE
[Quest]-The-Missing-Diplomat 10/16 (cannot be completed)

### ISSUE THREAD

**Issue by CyberneticCC** [chromiecraft/chromiecraft#208]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Quest: [The Missing Diplomat](https://classic.wowhead.com/quest=1248/the-missing-diplomat)
NPC_Start: [Elling Trias](https://classic.wowhead.com/npc=482/elling-trias)
NPC_End: [Mikhail](https://classic.wowhead.com/npc=4963/mikhail)
Zone: [Wetlands](https://classic.wowhead.com/wetlands)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Complete the quest.

##### CURRENT BEHAVIOUR:

Unable to turn in the quest.
(https://prnt.sc/10mhmmk)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Pick up the quest from Elling Trias in Stormwind.
Step 2 Go to Mikhail in Wetlands. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nolt** [comment]
Its chain quest and it's releated 10chain.
Start from: https://classic.wowhead.com/quest=1274/the-missing-diplomat

Need to test whole chain.

**Comment by nolt** [comment]
Quest can be give back to Mikhail, then fight begins at the entrance of the inn.

**Comment by AbraKabastard** [comment]
I tried this on my own compile of AC and it works as intended. Very clearly not working for this person for whatever reason though.

**Comment by CyberneticCC** [comment]
> Quest can be give back to Mikhail, then fight begins at the entrance of the inn.

Downloaded fresh client from the ChromieCraft website, deleted the cache, retook the quest, relogged, tried everything i could think of, same issue -> https://prnt.sc/10mvskp
Abandoning the quest results in the same NPC dialog -> https://prnt.sc/10mvvhq
Quest does not count as completed and/or NPC does not reset.
My character could be bugged itself for whatever reason.

**Comment by nolt** [comment]
@CyberneticCC 
I think this is not releated to the client, because I use same client as you do.
You couldn't talk with _Mikhail_ even at once?

Second screenshot is cooldown of NPC when you abandon quest.

Here is how you should be able to proceed with this quest: https://youtu.be/1nlDIXYygio?t=464

**Comment by nolt** [comment]
Im testing reset state of Mikhail if you fail 11th part of chain. Quest ID 1249

**Comment by nolt** [comment]
NPC state did not reset after 15min so it's bug, reset state occurs only after worldserver restart.

**Comment by Stifler82** [comment]
@nolt 
What happened to this report?
has the problem been fixed or not?

And why does the report refer to Chain 10/16 and instead you linked Chain 11/16 on AC?
Can you explain to me what happened?

**Comment by nolt** [comment]
Hi, it can be closed. fixed here: https://github.com/azerothcore/azerothcore-wotlk/pull/5070
while reporting this issue we found that 11 chain is bugged not 10th.
