### ISSUE TITLE
Mount up doesn't brake Gordok Ogre Suit

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#2081]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Mount up doesn't brake [Gordok Ogre Suit](https://wowgaming.altervista.org/aowow/?item=18258#created-by) buff. Spell [ID22736](https://wowgaming.altervista.org/aowow/?spell=22736)

https://user-images.githubusercontent.com/85256266/137107597-beeff0f2-3712-43f9-b133-03fbb7e91408.mp4

### Expected Blizzlike Behaviour

Mout up shopuld break Gordok Ogre Suit.

### Source

[Wowhead](https://www.wowhead.com/item=18258/)
> By bradb on 2009/02/23 (Patch 3.0.9)
Do NOT attempt to mount up with these, purchased a suit for 14 gold because i'm stupid like that, and attempted to mount up. The ogre Buff just dissappeared.

> By 597835 on 2010/06/10 (Patch 3.3.3)
 You can cast spells while in the costume, and you can take damage. But no mounting. Nice glitch if your mounted THEN apply the suit. Enjoy, hope this helped.
Námeless

### Steps to reproduce the problem

Use ogre suit and mount up

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vexima** [comment]
douchebag
