### ISSUE TITLE
Dire Maul:North Tribute run issues.

### ISSUE THREAD

**Issue by Drugzbunneh** [chromiecraft/chromiecraft#2097]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I need Chromie points for race change kk ty.
![1](https://user-images.githubusercontent.com/86498047/137405334-7a2b08b2-e16a-4b17-9c98-d8f166d8f1b8.jpg)
![2](https://user-images.githubusercontent.com/86498047/137405349-83a4ad25-7dc4-482e-81b0-2bb083339026.jpg)
![3](https://user-images.githubusercontent.com/86498047/137405358-27c2f20d-6190-4773-a964-cb8487e84456.jpg)
I'll write everything down under this section.
So since this bracket started i've done 20-25 solo Dire Maul:North tribute runs as a hunter.
I've noticed few things that didn't seem right.
First one and most important one is pet being unable to get back to his position with pet passive (if you use pet stay on certain position, send pet to attack something, and then use pet passive it always goes back to its stay position).
Basically pet would go his route, towards bosses, attack them get feared (if other boss is priest in that run) or charged by Gordok himself, and then he bugs out.
He will stay in same place no matter what you do, unless you send him to attack one of the spirits on that platform above, and when he gets to that spirit you put it on stay again so you can start doing encounter normally, ofc that excludes old way to do encounter which is puting it on stay behind that tiny wall so Gordok is never  able to charge him.
Talking about gordok charging pet, if it happens, you can get unlucky, that he charges your pet and it falls off the platform, it will completly reset encounter.
Secound issue is, a pack of 3 hyenas that are on platform, they should always patrol around that same platform (i'm talking specificly about platform where Gordok is standing. 
I did encounter few times by killing them but then realised that they don't move *lets say u fight him for 5-10 mins max* and simply was able to ignore them totaly.
And last but not least, when you enter this same dungeon, and when you climb on that first ramp, in case that you pull one of melee ogres, they shouldnt be ever able to up to that same ramp.
You can check out those pictures i posted to give you an idea how it should look like, shouldnt do yellowish colored text but whatever.
Thanks for reading, and goodbye.

### Expected Blizzlike Behaviour

x

### Steps to reproduce the problem

x

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e
x

### Operating system

Ubuntu 20.04
x

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
This is about 3 very different issues packed in one with unclear explanation and no sources provided. If this person or someone else with the same issues is still active, please submit a properly filled report for each specific issue so they can be addressed.
