### ISSUE TITLE
You'll never guess this one, corrupted flowers of felwood...aww

### ISSUE THREAD

**Issue by Drugzbunneh** [chromiecraft/chromiecraft#2099]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I can't sleep because of them.
Even when I somehow fall asleep, I have nightmares about them.
They will haunt me for the rest of my life.
Ladies and gentlemen, corrupted flowers of Felwood.
I got them, on both of my chars.
Was it pain? Yes.
Was it fun to run trought Felwood back and forth for hours? No.
Was it fun to camp one spot for 2+ hours in hope they'll respawn there? No.
Was it fun to ddos..err I mean wait for server restarts to be able to get them? No.
Look, it really felt like you're imprisoned in Felwood and never able to leave, untill you pick those bastards up.
I don't need them anymore, thank God, but I can feel the pain of other people which are trying to pick them up for their leg and head enchants.
I see people reported certain flower, like nightdragon for example.
But all flowers are messed up.
Apparently, to TrustMeBro source and few database sites. including wowhead,wowhead classic and by comments of people on those things, they should have respawn time of 25 minutes, per spot (there's like 4-5 spots per flower in whole felwood if im not mistaken).
No, they dont spawn at random of those 4-5 spots, but on all of them.

Free Mez out of your basement Honey, hide me from Nyopaweon and thanks for reading.
Best regards,
Drugzbunny of <Pwn Patrol>

### Expected Blizzlike Behaviour

x

### Source

x

### Steps to reproduce the problem

x

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e
x

### Operating system

Ubuntu 20.04
x

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Thank you for taking the time to report this, however, this is a known issue and has already been addressed here: https://github.com/chromiecraft/chromiecraft/issues/2075

A fix for it is already underway and will be live the next time the server is synchronized with AzerothCore.
