### ISSUE TITLE
Beginning Quests Still Auto Accepting

### ISSUE THREAD

**Issue by Knewklear** [chromiecraft/chromiecraft#21]
##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
please fill out the template and explain what the problem is
