### ISSUE TITLE
Goretusk boars in Westfall dropping 6+ items

### ISSUE THREAD

**Issue by linehanbball** [chromiecraft/chromiecraft#2101]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I understand it is minor so apologize for bringing this up, but wanted to let you know the Goretusk's in Westfall are dropping upwards of 6 items per kill (normal loot table for them just a considerable amount more than they are supposed to). I know there are much more pressing issues so just wanted to make you aware of it! Have a great day! My ingame name is Daddyheals if you need to ask me about anything.

### Expected Blizzlike Behaviour

Dropping 1 maybe 2 very rarely 3 items

### Source

Common sense/game knowledge

### Steps to reproduce the problem

1. Go to westfall
2. kill the goretusk's just north east of Sentinel Hill

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Edgardiez7** [comment]
This should be  working as intended. Analysing the drop rate chance we get:

0: 1.72%
1: 11.01%
2: 25.39%
3: 30.13%
4: 20.73%
5: 8.59%
6: 2.11%
7: 0.3%
8: 0.02%
So about a 10% chance of 5 drops or greater.

**Comment by Azcobu** [comment]
Thanks for the report. To expand on the above briefly, the only detailed information we have on droprates for these NPCs is from TBC Wowhead, which obviously isn't a great source for Wrath, but it's all we have for now. However, the data there does match AC's drop rates fairly closely. It's possible that retail drops were grouped in some way, so that similar items like tusks or guts or whatnot wouldn't be able to all drop together, but if that's the case we unfortunately have no evidence of it. I think there's a reasonable chance that you're correct and these NPCs are dropping too many items, but we just don't have the sources or data to prove it.
