### ISSUE TITLE
Fishing Wrecks spawn in shallow water

### ISSUE THREAD

**Issue by Amrx2** [chromiecraft/chromiecraft#211]
##### EXPECTED BLIZZLIKE BEHAVIOUR:

Wrecks should spawn only in deep water where they can be fished

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Fishing
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
We need more information to understand and evaluate the Bug,
it would help if you make a video showing exactly the problem, thanks.

If we don't understand what the problem exactly is, we can't help you.

**Comment by AbraKabastard** [comment]
https://legacy-wow.com/fishing-guide-pools-and-wreckage/
This says otherwise. I can't find much info. Clearly one shouldn't be on land though.

**Comment by gurveleg** [comment]
here is an example of wreckage spawned in shallow water, maybe he was refering to this? It was possible to cast around this one though when I found the right spot and just hit the edge of the wreck pool to get the loot. Am yet to come across a wreckage where I couldn't cast.
![WoWScrnShot_031821_145521](https://user-images.githubusercontent.com/80769357/111637770-09beb900-87fa-11eb-84dd-000a66db51c2.jpg)
Coordinates 29.2, 37.9

**Comment by Stifler82** [comment]
@gurveleg 
You have to forgive me, but I still can't figure out what the problem is.
I have reread both your report and your comment several times, and I still can't figure out what the problem is, can you be more specific please?

**Comment by gurveleg** [comment]
Since the author of this issue didn't provide any example of a wreck that was spawned in too shallow water from which it was not possible to fish, I posted that as the only occurance of a wreck that I found that could fit that description. That specific one is in Alterac Mountains on the shore of Lordamere lake, coordinates 29.2, 37.9, but I managed to fish out of it when finding the right spot - the cast had to hit right on the edge in the deeper water, it couldn't land anywhere else in the wreck.

**Comment by Amrx2** [comment]
Apologies for the delay in responding. If you check out the following location in STV, you will see you have both fish and wrecks spawning in shallow water where they cannot be fished (tried all angles for the last 10 minutes). 26.47, 19.94

**Comment by Amrx2** [comment]
Also in the following locations in STV - 24.05, 19.01   24.60,19.36

**Comment by Stifler82** [comment]
STV?
Sack Too Vacant?
Sun Travel Voluntarily?

What it mean?
please do not use acronyms...

**Comment by Amrx2** [comment]
Stranglethorn vale? The area is more known as STV than its entire name, I don't wish to be funny but if I am going to be called up for using the more well known version of the area is going to put off so many people from actually trying to raise these issues.

**Comment by Azcobu** [comment]
Just visited the various schools in STV listed by @Amrx2 - they appear to be GUIDs 47047, 64756 and 47420. I can't find evidence that the positions of these schools have been changed, but I was able to fish from all of these without any problems:

![WoWScrnShot_110221_203404](https://user-images.githubusercontent.com/81782124/139827430-5d6ef41e-7020-4070-a9b2-9af3ce8ba924.jpg)
![WoWScrnShot_110221_203653](https://user-images.githubusercontent.com/81782124/139827459-0a753ff4-94b1-4a3a-9429-caa0310547c0.jpg)
![WoWScrnShot_110221_203725](https://user-images.githubusercontent.com/81782124/139827477-020b2b8a-d28e-4a64-9e59-992a3141515e.jpg)

Not sure what's changed to make this behave differently, but will close as being unable to reproduce, along with no other reports from STV.
