### ISSUE TITLE
[Winterspring][Quest][Drop][Winterfall Ritual Totem]

### ISSUE THREAD

**Issue by Orixim** [chromiecraft/chromiecraft#2116]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

The Winterfall Ritual Totem item does not seem to drop. I have cleared the Winterfall Village many times now and I did not drop it. I have not yet met anyone that did. This prevents players to start the associated quest.

### Expected Blizzlike Behaviour

The item should be dropped:

NPC Name | Drop rate (%)
-|-
Winterfall Den Watcher | 4 |  
Winterfall Pathfinder | 4 |  
Winterfall Totemic | 4 |  
Winterfall Runner | 4 |  
Winterfall Ursa | 3 |  
Winterfall Shaman | 3 |  
High Chief Winterfall | 1.8 | 

### Source

[Item drop rate](https://classic.wowhead.com/item=20742/winterfall-ritual-totem#dropped-by)

### Steps to reproduce the problem

1. Go to Winterfall village
2. Kill all the NPCs and loot them
3. Repeat that a couple of times
4. Check that Winterfall Ritual Totem item did not drop

### Extra Notes

I know that I might just be extremely unlucky and I am just not dropping. But the truth is, I've been asking around and I could not find anyone who stated that it dropped (only one that did was Ntrna and even then, he said he couldn't complete the quest - so I am unsure he understood what item I was talking about).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
It droped for me on live server for several characters.

**Comment by Orixim** [comment]
I admit that I am unlucky, but I honestly can't believe that explains it. I am exalted with the Timbermaw since the start of my grinding there, perhaps it does not drop if the player is already exalted? There is no mention of that on the Wiki, but it could explain it. It's really hard for me to believe I am unlucky with those drop rates.

**Comment by Shineslippers** [comment]
> I admit that I am unlucky, but I honestly can't believe that explains it. I am exalted with the Timbermaw since the start of my grinding there, perhaps it does not drop if the player is already exalted? There is no mention of that on the Wiki, but it could explain it. It's really hard for me to believe I am unlucky with those drop rates.

It does. I was exalted when got it.

**Comment by jamadaha** [comment]
Checking on local AC DB, I found the same values as mentioned, see below. It is likely just you being unlucky, as mentioned. I'm gonna close this for now, but please do open it again — or write a comment — if the problem persists. This could be a problem only for CC.

Comment | Chance
-- | --
Winterfall Totemic - Winterfall Ritual Totem | 4.0237
Winterfall Runner - Winterfall Ritual Totem | 3.2287
Winterfall Pathfinder - Winterfall Ritual Totem | 3.1781
Winterfall Den Watcher - Winterfall Ritual Totem | 3.0963
Winterfall Shaman - Winterfall Ritual Totem | 2.9301
Winterfall Ursa - Winterfall Ritual Totem | 2.7286
High Chief Winterfall - Winterfall Ritual Totem | 2.2074

Query used: 
SELECT `Comment`, `Chance` FROM `creature_loot_template` WHERE `Comment` LIKE '%Ritual Totem%' ORDER BY `Chance` DESC;

Just to check whether it was some other bug, I tried to obtain it ingame(Local AC). And I was tad lucky, getting it on the 4'th kill:
![image](https://user-images.githubusercontent.com/53914190/137597574-f6053672-727c-43f5-aac3-49f0f9e44918.png)

You also mentioned it might not drop on exalted, so tested that:
![image](https://user-images.githubusercontent.com/53914190/137597688-32b623f2-0985-4aa4-89ef-386106e442ee.png)
