### ISSUE TITLE
Dispel magic not removing multiple copies of the same debuff.

### ISSUE THREAD

**Issue by RolyNuki** [chromiecraft/chromiecraft#2122]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The priest spell Dispel Magic is not properly dispelling two debuffs at rank 2. When attempting to dispel a player with multiple copies of the same debuff, only one instance is removed. 

### Expected Blizzlike Behaviour

Expected behavior would be removing 2 debuffs per cast of the spell, even for multiple copies of the same spell.

### Source

Tooltip/mechanics of the spell, https://wowgaming.altervista.org/aowow/?spell=988

Dispel: (Magic)
Value: 2

### Steps to reproduce the problem

Reproduction is very easy, have two enemies of the same type that will cast a dispellable debuff on the player and wait to get debuffed. Then try to cast dispel magic rank 2 to remove said debuffs, only one will be removed. Enemies that I have noticed the issue with so far have been...
Constrictor vines in mara with their roots spell: https://wowgaming.altervista.org/aowow/?npc=12220
Corruptors in mara with their corruption spell: https://wowgaming.altervista.org/aowow/?npc=12217
Sandfury Shadowcaster in ZF with shadow word: pain spell: https://wowgaming.altervista.org/aowow/?npc=5648

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Same topic as was before. https://github.com/chromiecraft/chromiecraft/issues/1159
Devs wanna proofs, not just words.
