### ISSUE TITLE
Sentries in Light Hope are constantly hostile

### ISSUE THREAD

**Issue by Jfjardon** [chromiecraft/chromiecraft#2123]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I flyed to light hope, I diconnected at the middle of the flight path, relogged, back on you tube and then then i found myself dead at the arrival. I presume that another horde player did kill me. But after i check combat log, it was a sentry. My pvp was off. So i was dead at the fly arrival. Then i walked my way to my corpse. Ressed, and died again. Sentry always hostile. I found a safe spot, logged out. I logged in again, sentry was always hostile. I can not handle my quests.
I add that my reputation is not "At war" with the argent dawn. See video here : https://youtu.be/HzcsuXHiQyY

### Expected Blizzlike Behaviour

Sentries should become frienly at some point after no pvp action or relog.

### Steps to reproduce the problem

1. Fly to Light hope chapel, try to disconnect during the flight path
2. Die because of guards sentries

### Extra Notes

Video : https://youtu.be/HzcsuXHiQyY

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Related to: https://github.com/azerothcore/azerothcore-wotlk/pull/7518

**Comment by Shineslippers** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/8558
