### ISSUE TITLE
[Object] Water Barrel missing in some zones

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#2139]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

There is only **_ONE_** [Water Barrel](https://wowgaming.altervista.org/aowow/?object=186234) object  in Silvermoon City, Tirisfal Glades and Azuremyst Isle.

### Expected Blizzlike Behaviour

This zones should have **_TWO_** Water Barrel objects

### Source

1. It's required for quests Fire Training ID11361, ID11449, ID11450. Logic saying it have to be there.
2. In other zones exist two objects
3. Weak evidance. Current version of WOW has it. [Youtube](https://youtu.be/TGg9K2J9gwQ?t=40) for example
4. [WolkDB](https://wotlkdb.com/?object=186234)

### Steps to reproduce the problem

Check out places near Fire Training dummies

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/8470  Known, thanks for the confirmation

**Comment by Shineslippers** [comment]
@Stump876, What about [Jack-o'-Lantern](https://wowgaming.altervista.org/aowow/?item=33117) did you report it too? Looks like drop only from specific NPCs in Northrend a bit wrong.
