### ISSUE TITLE
3 minutes respawnable wreckages

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#214]
##### ISSUE: FACTION SIDE: 

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE: 

Generic

##### SMALL DESCRIPTION:

I know this may not be blizzlike but wreckages like waterlogged,bloodsail wreckage shouldn't spawn every 3 minutes like some do because its easily abusable to get a lot of mats with little to no effort.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Some wreckages spawn every 3 minutes after you fish them.

##### CURRENT BEHAVIOUR:

Some wreckages spawn every 3 minutes after you fish them

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 With a wreckage in water,
Step 2 fish it,
Step 3 wait for respawn.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by AbraKabastard** [comment]
Wreckage pools should be interchangeable with regular fishing pools too if not the case

**Comment by Zoidwaffle** [comment]
OK, I'm making a PR to batch-fix this...

**Comment by Zoidwaffle** [comment]
I don't know how to easily move this issue to AC as well... If it's just copy/pasta or there should be a smarter way I don't have access to or know about.

So not creating an AC issue right now.

**Comment by illfated** [comment]
I don't think it is necessary to be able to edit the main ticket comment in question, you just copy the relevant text parts and paste them into the corresponding fields in the new ticket on AC, before checking that all fields are filled in, before saving the new ticket.

**Comment by Zoidwaffle** [comment]
It has been copy/pasta'ed over to AC.

Thanks!

**Comment by FrancescoBorzi** [comment]
@Zoidwaffle don't forget to update the labels here ;)
