### ISSUE TITLE
Druid permanent armor increase - Can stack infinitely 

### ISSUE THREAD

**Issue by Rinias** [chromiecraft/chromiecraft#2143]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Linking spells at the bottom of this post and this bug only works inside of bgs. At least I havent got it to work outside of bgs with duels or world pvp. This bug breaks all PvE encounters, and make druids raid bosses in terms of dmg they can take inside of Battlegrounds.

Inside of a battleground, if a druid get their Mark of the Wild buff dispelled while in Bear Form their armor will increase permanently until the player logout and back in which reset it.
In the clip below I recorded for devs to see what it looks like.

https://streamable.com/7wuz0s

My armor is 1642 without Mark of the Wild (Rank 6), with the buff I got 1902.
2-3seconds into the clip I get Purged by the Shaman (dispelled MotW buff).
11 seconds in I enter Cat Form and now my armor is suddenly up to 1818 which means it increased by roughly 10%. The armor increase will not go away and if I would buff myself with MotW again, get it dispelled... it just keep going up.
 
Currently Druids can get above 1 million armor by doing this multiple times.
 
 
 MotW (rank 6): https://wowgaming.altervista.org/aowow/?spell=9884
 Dire Bear Form: https://wowgaming.altervista.org/aowow/?spell=9634
 Cat Form: https://wowgaming.altervista.org/aowow/?spell=768
 Purge (rank 2): https://wowgaming.altervista.org/aowow/?spell=8012
 
 Edit: I have confirmed myself that there are other ways to trigger it, since the armor gain have occured even when I play without any buff at all. Im suspecting Sunder Armor and other armor reducing spells can trigger this as well.
 

### Expected Blizzlike Behaviour

When the buff Mark of the Wild get dispelled druids should lose the amount of stats given by the buff as it currently does. But it should not increase druids total armor permanently. (until logging out, which again reset the armor value) 

### Steps to reproduce the problem

Will add the link to the video clip here as well as reference material: https://streamable.com/7wuz0s

1. Queue any BG as a druid. Talents does not matter.
2. Buff yourself with Mark of the Wild (any rank as far as I know).
3. Get MotW dispelled by the enemy while in Bear Form.
4. Armor should be increased.

### Extra Notes

If devs or anyone testing want more video material for other situations when it happends I can fix that. It happened multiple times in the same bg so can upload more if needed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
I've been trying to reproduce this on a vanilla AC server, with no success.

Base bear armour, no MotW.
![WoWScrnShot_101921_233945](https://user-images.githubusercontent.com/81782124/137924419-88a35a81-f9f9-4f16-92e7-34be72eebf9d.jpg)

MotW rank 6 cast:
![WoWScrnShot_101921_233953](https://user-images.githubusercontent.com/81782124/137924427-e1a0031a-6a54-439e-918b-9a808b13ada0.jpg)

Shaman purges MotW, armour returns to previous value:
![WoWScrnShot_101921_234150](https://user-images.githubusercontent.com/81782124/137924431-578b00be-97b5-47ea-b3fd-0f492d47a8f9.jpg)

This was inside a BG (WSG in this case.) I used the spell ranks described above, rank 6 MotW and rank 2 Purge. Any ideas on what I might be missing or doing wrong?

Will look into installing some of the CC-specific mods and see if they are affecting this somehow.
