### ISSUE TITLE
[DM - West] No Credit for killing Immol'thar

### ISSUE THREAD

**Issue by Notrox1** [chromiecraft/chromiecraft#2148]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

We killed all Arcane Mobs at the Crystals and the shield to immolthar was gone.
The Nightelf mages started fighting Immolthar and were going to win. He killed non and was at about 50% when I engaged as a tank and taunted him. Then we killed Immolthar and didnt get any loot for him

There was only 1 dead mage after we killed him

### Expected Blizzlike Behaviour

Immolthar should either kill the Mages or heal to full when you pull him

### Source

Joined DM West via random dungeon finder
https://www.youtube.com/watch?v=JJ8GDHxNkX8
At 42:00 Immolthar is oneshotting every mages and get way less damage from him then he does here.

### Steps to reproduce the problem

Enter DM West
Kill all Arcances on the crystals
Watch Immolthar fight the mages

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
> The Nightelf mages started fighting Immolthar and were going to win. He killed non and was at about 50% when I engaged as a tank and taunted him. Then we killed Immolthar and didnt get any loot for him
There was only 1 dead mage after we killed him

If i got your information right - there is no issue.  If you done to NPC less than 50% of damage when he is in fight with other NPC you can't get loot. I did some tesets and on AC it's working like this.
So, probably your engaged to Immolthar while he still was in combat with Nightelf mages. In your video tank [engaged](https://youtu.be/JJ8GDHxNkX8?t=2558) after boss came to his position with 100% HP

**Comment by Notrox1** [comment]
Okay then i seems to be blizzlike ... i have never seen this.
Ticket obsolate i guess :)
Thanks !
