### ISSUE TITLE
Trick or Tread costumes (Bat, Wisp or Ghost) BUG 

### ISSUE THREAD

**Issue by Neversong97** [chromiecraft/chromiecraft#2150]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I am able to cast any spell in bat, ghost or wisp form. For example mount up or stealth.

More info: I can do sprint, shadowstep, mount up, stealth, eating food in bat form, casting granades, vanish, I can even kill mobs with offensive abilities such as hemo, sinister strike, auto attack and so on. You can cast any spell in the bat form for example, as long as I dont take any damage. (I tested this before reporting this issue and I was in bat form outside Stormwind killing mobs with my abilities which I should not be able to use and not breaking bat form) The costume literally says If I want to cast abilities I must right click buff and disable it.

### Expected Blizzlike Behaviour

I should not be able to cast any spell, If I do it should break the costume and bring me back to normal form. 

### Source

The costume literally says I am not able to cast any spells or mount up.

### Steps to reproduce the problem

1. Go to any Inn 
2. take Trick or Tread
3. Make sure you get costume (bat ,ghost or whisp)
4. Cast spells (mount up or stealth for example)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
I came to post the exact same thing. I can confirm all described, plus it's possible to take flight routes while transformed. Quite funny and strange being a bat, hoovering over another bat and sync-flying places.

**Comment by gurveleg** [comment]
By I" am able to cast any spell in bat, ghost or wisp form. For example mount up or stealth" do you mean you can cast anything else? If so please say what abilites you are able to use.  I'm checking on local AC and I cannot use any spell or attack besides mounting up and stealthing.

**Comment by Neversong97** [comment]
> By I" am able to cast any spell in bat, ghost or wisp form. For example mount up or stealth" do you mean you can cast anything else? If so please say what abilites you are able to use. I'm checking on local AC and I cannot use any spell or attack besides mounting up and stealthing.

I can do sprint, shadowstep, mount up, stealth, eating food in bat form, casting granades, vanish, I can even kill mobs with offensive abilities such as hemo, sinister strike, auto attack and so on. You can cast any spell in the bat form for example, as long as I dont take any damage. (I tested this before reporting this issue and I was in bat form outside Stormwind killing mobs with my abilities which I should not be able to use and not breaking bat form) The costume literally says If I want to cast abilities I must right click buff and disable it.

**Comment by Salehyn** [comment]
Seems to work fine as of today. You do have a silence aura - it simply doesn't apply to most physical abilities, only spells, like any other silence effect. You can't cast spell-spells, you can't take flight paths, and if you take any damage the costume is cancelled.

**Comment by TheSCREWEDSoftware** [comment]
On AC faea1c0735f1 

At the current point none of the issues can be reproduce.

I can't use spells, physical, magical or ranged.
Mobility doesn't work
Stealth and/or forms doesn't work
You're able to interact with your inventory, which i pressume is intended. Like learning a mount.
You can't mount
You can't take a flightpath
If i dc'd or the server closed. The person with the custome iwll keep the buff and ability to not do the above but their model will be their chars model instead of the costumes, does anyone know if this part is intended?
