### ISSUE TITLE
Priest Skill: Dispel Magic Rank 2 only dispels 1 magical effect not 2

### ISSUE THREAD

**Issue by Kizkit** [chromiecraft/chromiecraft#2151]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

https://wowgaming.altervista.org/aowow/?spell=988

The priest spell, **Dispel Magic Rank 2** is explicitly only dispelling a single magical effect instead of two.

This functionality which is lacking currently is required for many later boss battles, especially in raids, where having to dispel a spam of multiple magical effects will cost twice as much mana and take twice as long, which is definitely not intended.

### Expected Blizzlike Behaviour

On the spell's description text, and on other servers, including blizzard's own, the second rank of dispel magic upgrades it to have 2 magical effects dispelled at a time. Every other status effect removing ability in the game has some sort of upgrade in this manner, such as abolish poison will remove multiple poisons at 3 second intervals.

### Source

https://wowgaming.altervista.org/aowow/?spell=988

Dispel: (Magic)
Value: 2

### Steps to reproduce the problem

1. Use a level 40+ priest and go into Maraudon's purple side.
2. Encounter many imps which spam the "corruption" spell on a party member. There will be 1-4 active at a time in many cases.
3. Use the Dispel Magic Rank 2 ability to cleanse the corruption magical status effect.
4. Verify only one instance is being removed at a time, both by checking the number of corruption debuffs before and after the cast, as well as checking the combat log.

### Extra Notes

Since this is only affecting rank 2 of the spell, and it seems to be replicating the rank 1 effect identically, there's a good chance that either the pointer to which spell is used is incorrect. It's possible that there's just a typo in the spell itself which is listing 1 instead of 2, but my guess would be that it's pointing to the wrong spell rank for effect.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Repeat of https://github.com/chromiecraft/chromiecraft/issues/1159 and https://github.com/chromiecraft/chromiecraft/issues/2122. 
https://github.com/chromiecraft/chromiecraft/issues/2122#issuecomment-946627398
>Thanks for the report. I'm open to the idea that Dispel Magic isn't behaving correctly, but the (somewhat ambiguous) skill tooltip does match the behaviour we're seeing from it. However, if you do find a source that shows AC's behaviour is incorrect, please feel free to let us know. Closing this in the meantime.
