### ISSUE TITLE
Warrior - Auto attack bug

### ISSUE THREAD

**Issue by Vertazwar** [chromiecraft/chromiecraft#2173]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Sometimes after charging a mob auto attack doesnt start (as if I have used a thrown/shoot and auto attack was on "cooldown" til next hit). Its huge bug for damage and combat of warriors. Happens only here, I tried to close addons, delete cache, remove macros. Stil happens. Sometimes its close to every charge, sometimes its once every few mobs.

https://www.youtube.com/watch?v=XonmmgsggQQ

### Expected Blizzlike Behaviour

Charge should not affect auto attack in any way.

### Source

https://www.youtube.com/watch?v=IijlbG7yrlc 3:06 time... Auto attack starts instantly after charging.

### Steps to reproduce the problem

1: target a mob
2: charge and auto attack
3: repeat til you stand in front of a mob expecting an auto attack to happen but nothing happens.

### Extra Notes

pls fix asap, huge bug...

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Vertazwar** [comment]
did you check the link? is it actual DB fix from azerothcore? it says that this issue is fixed on azerothcore.

**Comment by Shineslippers** [comment]
There is on Discrod server you can find channel "changelog-chromie". You can tracking uploaded fixes here. Anyway before uploading fixes have to be tested.

**Comment by Vertazwar** [comment]
Any news? Looking forward to trying lvl 60 arms once this issue is fixed

**Comment by Shineslippers** [comment]
This is fixed more than month ago https://github.com/azerothcore/azerothcore-wotlk/pull/8978
