### ISSUE TITLE
Lament of the Highborne book doesn't display its text correctly 

### ISSUE THREAD

**Issue by apav** [chromiecraft/chromiecraft#218]
##### ISSUE: FACTION SIDE: Horde

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

10-19

##### SMALL DESCRIPTION:

The text in the book [Lament of the Highborne](https://wotlkdb.com/?item=30632) appears bugged. It shows HTML code and it says "From, (player name)" at the bottom of each page as if it was a letter.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Shows in the content section of the above link.

##### CURRENT BEHAVIOUR:

![World Of Warcraft Screenshot 2021 03 16 - 18 34 19 96](https://user-images.githubusercontent.com/8137930/111389259-0d7dfe80-8687-11eb-9be1-822a53c81e3a.png)
![World Of Warcraft Screenshot 2021 03 16 - 18 34 22 20](https://user-images.githubusercontent.com/8137930/111389262-0f47c200-8687-11eb-8758-afb5c0ba6d91.png)
![World Of Warcraft Screenshot 2021 03 16 - 18 34 26 55](https://user-images.githubusercontent.com/8137930/111389264-1078ef00-8687-11eb-9d1c-7f73998db77e.png)
![World Of Warcraft Screenshot 2021 03 16 - 18 34 29 41](https://user-images.githubusercontent.com/8137930/111389267-11118580-8687-11eb-9795-bb38b3bbfe58.png)
![World Of Warcraft Screenshot 2021 03 16 - 18 34 31 61](https://user-images.githubusercontent.com/8137930/111389270-1242b280-8687-11eb-8f7c-a5d13bbd008a.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Complete quest [Journey to the Undercity](https://wotlkdb.com/?quest=9180).
2. After you complete the quest, NPC Ambassador Sunsorrow will ask you to speak with him. When you do there is a dialogue option to receive the lyrics to the song Sylvannas is singing in the form of a book.
3. When you open the book to read it, this is what appears.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
Likely game client bug, see issue ticket **Lament of the Highborne book includes html text** #110 for details.

**Comment by apav** [comment]
> Likely game client bug, see issue ticket **Lament of the Highborne book includes html text** #110 for details.

Ah thanks. It didn't come up in search likely because I was searching open issues.

**Comment by nolt** [comment]
Item added to inv, shows normal.
![LofH](https://user-images.githubusercontent.com/6367933/111394062-3a97d480-86ba-11eb-909c-8bf7a60eb3b3.png)

**Comment by nolt** [comment]
**Closed!**

**Comment by apav** [comment]
> Item added to inv, shows normal.
> ![LofH](https://user-images.githubusercontent.com/6367933/111394062-3a97d480-86ba-11eb-909c-8bf7a60eb3b3.png)

So because my install is from 2014, I decided to download the client linked on the Chromiecraft website on a computer that has never installed WoW before. I didn't copy my addons or WTF folder over, I left it completely fresh before logging in. Still getting the same bug. But you tested it and it's fine for you, do you have any idea how that's possible?

**Comment by illfated** [comment]
By the way: this is very much reproducible on logon.chromiecraft.com, but not on TrinityCore or any other source. The test server seems to be running buggy code, but not if you make your own server or use other source code.

AzerothCore rev. 8bacb39d5334 2021-03-20 18:26:35 +0100 (master branch) (Unix, RelWithDebInfo)
Connected players: 182. Characters in world: 174.
Connection peak: 186.
Server uptime: 17 hour(s) 5 minute(s) 33 second(s).
Update time diff: 10ms, average: 10ms.

@FrancescoBorzi : Could you or @Helias find some way to flag the server as not useful as bug reporting source?

**Comment by FrancescoBorzi** [comment]
@illfated there is no "test server", ChromieCraft is a live server with real players that report bugs that they find here. Also it's a pretty clean AzerothCore (which we update more or less every week to the latest version) with only a bunch of minor modules added. The bug reports should be check and reproduced in a local AzerothCore by contributors.

**Comment by eTzmNcbkrng** [comment]
> 
> 
> > Item added to inv, shows normal.
> > ![LofH](https://user-images.githubusercontent.com/6367933/111394062-3a97d480-86ba-11eb-909c-8bf7a60eb3b3.png)
> 
> > make sure you use the enUS client (do not use enGB) and disable all addons
> 
> My client is enUS. But because I've used the same installation for almost a decade, I wanted to be absolutely certain it wasn't on my end. So I downloaded and ran the client linked on the Chromiecraft website on a computer that has never installed WoW before. I didn't copy my addons or WTF folder over, I left it completely fresh before logging in. Still getting the same bug. But you tested it and it's fine for you, do you have any idea how that's possible?

https://github.com/chromiecraft/chromiecraft/issues/302#issuecomment-819139667
