### ISSUE TITLE
[Warlock pet] Felguard doesn't perform autocast abilities after charge

### ISSUE THREAD

**Issue by vexima** [chromiecraft/chromiecraft#2187]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Generally felguard has no problem casting Anguish and Cleave on cooldown after being sent to attack enemy, but if he charges prior to attack, those abilities aren't being cast if set on autocast, although can be cast manually still.

### Expected Blizzlike Behaviour

Felguard should always cast abilities set on autocast either he did charge or not.

### Steps to reproduce the problem

1. Summon Felguard.
2. Set Anguish and Cleave on autocast.
3. Send pet to attack an enemy.
4. Use Charge.
5. Anguish and Cleave are never used despite being on autocast.

### Extra Notes

Moreover, if warlock pulls an agro off felguard and enemy moves towards warlock, felguard stays in place and does not pursue its target unless another "Attack" command issued on him.

However, if "Attack" command issued manually on pet right after charge lands, autocast starts working again. Felguard visibly repositions himself slightly closer towards the target, so it might be some positioning issue triggered after charge.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Fixed.
