### ISSUE TITLE
Quest "Mission Accomplished!" is repeatable

### ISSUE THREAD

**Issue by mitchman97** [chromiecraft/chromiecraft#2189]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

High Executioner Derrington at the Bulwark offered quest "Mission Accomplished!" after I had already completed it (evidenced by Valiant Shortsword equipped). Chose to complete quest to see if it would actually go through, and it did. Received reputation, gold, not sure of XP because I was at level cap, and duplicates of quest reward items.

I don't remember exactly when I completed this quest the first time or what I may have done to reset my eligibility to accept/complete it. 

![InkedWoWScrnShot_102421_172657_LI](https://user-images.githubusercontent.com/1653264/138615943-b418f9e5-ff86-4853-9ca8-39ad8e66b3ab.jpg)

![InkedWoWScrnShot_102421_172724_LI](https://user-images.githubusercontent.com/1653264/138615947-8fe819e2-ece1-4b19-a10c-3cd11611b47e.jpg)

Could have something to do with putting Argent Dawn Commission in bank, since quest "Argent Dawn Commission" is also available again.

### Expected Blizzlike Behaviour

Have not ever played this content in retail, but nothing I can research nor intuition make me think it should be completable more than once.

### Steps to reproduce the problem

1. Complete quest
2. ? Complete EPL quests, raise Argent Dawn Rep. level ?
or
2. Place Argent Dawn Commission Trinket in bank
3. Go to Bulwark and see if High Executioner Derrington offers quest

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

All used AddOns:
Recount
AtlasLoot
Bagnon
Grid

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
They are not repeatable, that happened because the Alliance and Horde versions were switched.
You are Horde, you first completed the Alliance version.
Then they fixed it and now you completed the right version.

See
#1976
#2125
#2182
