### ISSUE TITLE
The Chromiecraft Issue Tracker Template is too Complex (Fix Included)

### ISSUE THREAD

**Issue by JamesGent** [chromiecraft/chromiecraft#219]
ChromieCraft Issue Creator: 500 words, 8000 characters.

AzerothCore Issue Creator: 400 words, 2600 characters.

My Suggestion Below: 200 words, 2000 characters.

Chromie Tracker is for noobs. It shouldn't be 4x more complex then AzerothCores, it should be smaller and simpler.

Below is my suggested PR for a new template. It reduces the template complexity, messiness, and size greatly.

---------------------------

##### CURRENT BEHAVIOUR:

Type here.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nolt** [comment]
You're right it only helps us (contributors) to create issue in AC repo but for regular user is very complex.

**Comment by FrancescoBorzi** [comment]
now live, thanks
