### ISSUE TITLE
Wretched Tap from Unstable Mana Crystals

### ISSUE THREAD

**Issue by Cosmic-Lattee** [chromiecraft/chromiecraft#22]
##### SMALL DESCRIPTION:
A dummy spell is being cast by the player when it seems like it should be cast by a object or it is happening long after it is supposed to have happened.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
There are these crates you are supposed to loot during the [Unstable Mana Crystals](https://wotlkdb.com/?quest=8463) Quest. What I think is supposed to happen is as you open the [Unstable Mana Crystal Crate](https://80.wowfan.net/en/?object=180600) a trap ([Battered Crate Trap](https://80.wowfan.net/en/?object=181584)) on the chest is activated. 

Now It is hard to figure out what happens next, what I imagine is supposed to happen is that the trap uses the spell [Wretched Tap](https://80.wowfan.net/en/?spell=29420) on the player which seems to be a dummy spell that only does creates a visible effect. There is very little to no information about it however.

It could be that me casting it is correct, but in that case I imagine it is supposed to happen immediately after using the box instead of some time afterwards.

##### CURRENT BEHAVIOUR:
I noticed that my character would on the quest cast a spell randomly that looked like lightning shield. Looking at the logs for it I seem to be casting a spell called Wretched Tap (see picture below).

![image](https://user-images.githubusercontent.com/24766235/106360634-36b51c00-62df-11eb-8e8e-c7f9c99db723.png)

The odd thing about it is seems to happened at random moments long after I had looted the box when I imagine the box is supposed to cast it at me or I am supposed to cast it as I first pick up the item.

##### STEPS TO REPRODUCE THE PROBLEM:
Create a character who has never taken this quest, and loot these boxes. It seems almost random when the effect happens. I would just notice a little while later that I cast the the spell after I have looted the item.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Could you send a video with the retail behavior? I looked around but I can't find a video that shows what you say.

**Comment by Cosmic-Lattee** [comment]
So looking into this some the videos for this quest that I could find online do not show the Unstable Mana Crystal Crate doing anything when they are looted (as see in these videos: [1](https://www.youtube.com/watch?v=b5fljoJAZXQ) [2](https://www.youtube.com/watch?v=gdMZ41hRe84) [3](https://www.youtube.com/watch?v=D_0DXKIb-1k)). All of these are of course from several years after TBC came out. So it might just be that this quest was changed to no longer perform the Wretched Tap "trap." 

However I found one video that wasn't like the ones above.

A very overly dramatic video from Twinstar which is another private server. This video can be seen [here](https://youtu.be/Enq3zdZuS-Q?t=23). When I saw this I realized that I might have been mistaken on when this effect was supposed to happen. So it looks like when you get close to the crates this trap goes off. 

I went ahead and made a new character to look at this a bit more closely. How it works is like this:

- Move within a few yards of the crate.
- Your character casts Wretched Tap which is a channeled spell that lasts for about a second or so.
- This spell looks like you are casting lightening shield, but otherwise does nothing.

Interesting enough you don't even have to be on the quest for the box to trigger the behavior. Now I am not sure if that is how it would have worked on retail but honestly I don't think there is much chance of being able to test that particular theory. Here is a picture showing the effect in motion, and my quest log so you can see that it happens even if you don't have the quest.

![image](https://user-images.githubusercontent.com/24766235/106402441-16748280-63ef-11eb-9328-966866dab3da.png)

### Conclusion
So it actually looks like this is working as intended at least as far as I can tell. Since it is based off of _proximity_ I think what happened is I got close to a box which made the Wretched Tap happen and assumed it was belated effect because of opening a earlier box. 

I think that this can safely be closed. Hopefully I didn't waste anyone's time with this!

**Comment by FrancescoBorzi** [comment]
thanks @Cosmic-Lattee for your feedback! we appreciate

**Comment by Helias** [comment]
Thanks a lot @Cosmic-Lattee
