### ISSUE TITLE
Blackfathom Deeps final event bug

### ISSUE THREAD

**Issue by miky1093** [chromiecraft/chromiecraft#220]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

A wipe in the final event with the 4 goblets activated will lead to a bugged door, that will stay closed. Mobs also disappear which i think is not normal: i think that mobs should stay there so you can kill them back and let the door opens

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs stay alive if a wipe occurs. Killing them opens the door.

##### CURRENT BEHAVIOUR:

After a wipe mobs disappear, door stay closed

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by miky1093** [comment]
A wipe in the final event with the 4 goblets activated will lead to a bugged door, that will stay closed. Mobs also disappear which i think is not normal: i think that mobs should stay there so you can kill them back and let the door opens

**Comment by miky1093** [comment]
sorry but i don't understand how to post correctly the bug report...

**Comment by Si1ker** [comment]
@FrancescoBorzi @55Honey

**Comment by 55Honey** [comment]
Fixed as far as possible in a Phone :-)

**Comment by Stifler82** [comment]
I may not have understood the problem well, but as you can see from my video I have not been able to reproduce the bug you claim to have had.

**Video Test:** [Blackfathom Deeps](https://youtu.be/xgVKFQIBJq0)

**Comment by 55Honey** [comment]
You need to let your character die. If you die during the fight against the adds spawned by the braziers, the door stays locked.

I don't know if the braziers should respawn and how its blizzlike tho.

**Comment by Stifler82** [comment]
> You need to let your character die. If you die during the fight against the adds spawned by the braziers, the door stays locked.
> 
> I don't know if the braziers should respawn and how its blizzlike tho.

Yeah, ok, but theoretically, if i remember right, an wipe, is a wipe.
So, if you wipe against a boss or event "boss"(like the doors) you should do: reset the dungeon and do it again..
but i'm not sure 100% maybe it work like this only in Instance and not in Dungeon, idr exactly at moment..

**Comment by 55Honey** [comment]
Let's keep it closed then for now.
@miky1093 if you have a source which indicates that it is currently wrong, please link it. We will happily reopen and work on the issue then.

**Comment by eTzmNcbkrng** [comment]
Nothing here indicates it was ever the case that wiping on this event caused the dungeon to need to be reset.
https://wowpedia.fandom.com/wiki/Blackfathom_Deeps#Patch_changes
https://wowwiki-archive.fandom.com/wiki/Blackfathom_Deeps#Patches_changes

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Comment by necropola** [comment]
[This video from Classic WoW](https://youtu.be/G18a3St6P0c?t=5862) posted in https://github.com/chromiecraft/chromiecraft/issues/972#issuecomment-866815144 by @temperr clearly shows that the mobs do not despawn and you have another try to kill them after you wiped. 

This is enough evidence for me.
