### ISSUE TITLE
Transpolyporter no longer works

### ISSUE THREAD

**Issue by VFaleiro** [chromiecraft/chromiecraft#2216]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The Transpolyporter, which is the teleporter between Booty Bay and Gnomeregan, no longer works. Currently it does nothing at all.

### Expected Blizzlike Behaviour

When you step up on the teleporter in Booty Bay, while having [Goblin Transponder](https://wowgaming.altervista.org/aowow/?item=9173) in your inventory, you get teleported to Gnomeregan.

Also, you can travel back and forth, just step on the Gnomeregan one and you should get teleported to Booty Bay. I have not tested this one though.

### Source

Scooty's speech on the quest:
>As long as you have the transponder in your possession, all you need to do is step on the pad and you'll be teleported to Gnomeregan.
>
>You may experience some unusual side effects, but none of those should be permanent... anymore.
>
>I almost forgot the most important part - getting back. When you're ready to come back, just step on the transpolyporter pad in Gnomeregan!
>
>Now to calibrate the transponder to your size and weight.

From:
- [Wowhead](https://www.wowhead.com/quest=2843/gnomer-gooooone);
- [Wowgaming/Aowow](https://wowgaming.altervista.org/aowow/?quest=2843);
- [Wowwiki, archived Sep/2010](https://web.archive.org/web/20100928183530/http://www.wowwiki.com/Quest:Gnomer-gooooone!#Description).

### Steps to reproduce the problem

1. Go to [Scooty](https://wowgaming.altervista.org/aowow/?npc=7853), in Booty Bay;
DB GUID: 2, current GUID: 174
Not sure which one you guys need to be able to teleport to him.

2. Add quest [2843](https://wowgaming.altervista.org/aowow/?quest=2843);

3. Speak to Scooty and turn it in to receive your [Goblin Transponder](https://wowgaming.altervista.org/aowow/?item=9173), after this quest he can give you a new one should you lose yours;

4. Step on the teleporter and observe.

### Extra Notes

Not sure if it's [this object](https://wowgaming.altervista.org/aowow/?object=143230) or [this one](https://wowgaming.altervista.org/aowow/?object=142172).
`.gobj near 2` ingame indicates the former, but maybe the later should be there as well?

Have not tested the Gnomeregan counterparts ([this object](https://wowgaming.altervista.org/aowow/?object=142175) and [this object](https://wowgaming.altervista.org/aowow/?object=142176) I guess).

Also, I am 100% sure it worked (both ways) during the 40-49 bracket.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ciscam** [comment]
It's still broken (or again?)
