### ISSUE TITLE
[Error on Quest marker] - The Madness Within (7461)

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#2226]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Upon completing quest [The Madness Within](https://classic.wowhead.com/quest=7461/the-madness-within) we are instructed to turn it in at the Shen'dralar Ancient. If we choose to show the map where to turn quest, we are clearly pointed to a spot in Dalaran Crater, at Alterac Mountains. Not only the marker is wrong, but even the description on it is obviously mistaken.

![ 2021-11-01 at 10 03 25](https://user-images.githubusercontent.com/77953030/139634805-de752990-ead4-40b7-8b81-0d9d77b16849.png)
![ 2021-11-01 at 10 03 38](https://user-images.githubusercontent.com/77953030/139634842-355e9a2e-4431-4897-9cb3-902cc844402f.png)

### Expected Blizzlike Behaviour

When choosing "show map" or opening map ingame, the "?" should NOT appear in Dalaran Crater at Alterac Mountains.

### Source

https://wowwiki-archive.fandom.com/wiki/Quest:The_Madness_Within
https://classic.wowhead.com/quest=7461/the-madness-within

### Steps to reproduce the problem

Have a player of at least lvl 56
Get and complete quest [The Madness Within](https://classic.wowhead.com/quest=7461/the-madness-within) 7461)
Choose to "Show map" or open map by yourself at Alterac Mountains and observe.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Hmmm ... I'm a bit split on this, as on one hand this appears to be blizzlike (See notes in this [link](https://wowpedia.fandom.com/wiki/The_Madness_Within?oldid=2476360)), but as the source, and common sense, suggests this is obviously wrong.

**Comment by Shineslippers** [comment]
Usually we leaving Blizzard mistakes, but i guess we need @Azcobu opinion in this case.

**Comment by Azcobu** [comment]
My understanding is that if something is clearly buggy/broken, we'll fix it anyway, Blizz-like or not. Two sources for this: one a comment by Shin on the Engineering Department's Discord server:

![shin-blizzbug](https://user-images.githubusercontent.com/81782124/139683839-d474c984-f1fa-4920-bda2-8229bfe7b40c.PNG)

The other a comment by Helias [here](https://github.com/azerothcore/azerothcore-wotlk/issues/5055#issuecomment-812936232).

This isn't the time or place to go into a long discussion on this, and I know there are staff members who disagree with this position, but I believe this is the current policy. So on that basis you're justified in making a report on AC for this.

**Comment by VFaleiro** [comment]
But, by that same logic, wouldn't that mean [Demon's Blood](https://wowgaming.altervista.org/aowow/?item=10779) should be fixed as well? Since it was clearly a blizz-like bug (they fixed it on 4.0.1, readding its stats back).

**Comment by Azcobu** [comment]
True enough, will go back to the relevant issue with this policy in mind.
