### ISSUE TITLE
Silithyst - Infinite Turn In

### ISSUE THREAD

**Issue by SirRakdos** [chromiecraft/chromiecraft#2227]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I tried to turn in the silithyst into the extractor, but when i did, i didnt lose the silithyst and the horde counter went up by 1.
I tried then to go back and forth like 10 times and it remained attached to me, gaining always a +1.
Logging out and coming back solves the problem about consuming the silithyst.
So, unless u log out, with just 1 silithyst u can do infinite turn ins.

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=nI6VATVpN8Y&ab_channel=rangercolts

After a turn in, silithyst should disappear.

### Source

![WoWScrnShot_110121_111920](https://user-images.githubusercontent.com/86595566/139657543-2229eacd-07b3-42f9-9432-649b716db371.jpg)
![WoWScrnShot_110121_111928](https://user-images.githubusercontent.com/86595566/139657574-dd8f67c8-5a46-45ad-8078-fa0dbfc34107.jpg)

### Steps to reproduce the problem

1. Go to Silithus
2. Find a Silithyst Geyser in the desert
3. Go to your faction camp and step into the extractor

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Ntrglhf** [comment]
The same problem is on the side of the alliance. Only in an attempt to record a video of a bug, you can get banned for an unknown amount of time.
