### ISSUE TITLE
Razorfen Downs entry level lower than 35

### ISSUE THREAD

**Issue by Sajgon66** [chromiecraft/chromiecraft#2228]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

You can enter Razorfen Downs at lvl 30 which shouldn't be possible according to wowhead classic. 

### Expected Blizzlike Behaviour

Portal shouldn't allow you to enter and communicate player that you need at least lvl 35

### Source

https://classic.wowhead.com/guides/classic-dungeons-overview

### Steps to reproduce the problem

I tested on character 30lvl so any character at lvl 30 can enter Razorfen Downs.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Opensuse 

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
Thanks for the report. 
I can't find any conclusive sources on this, looking the provided [source](https://classic.wowhead.com/guides/classic-dungeons-overview) it states required level of 35, but looking [Wowhead TBC](https://tbc.wowhead.com/razorfen-downs) it states required level 33. This is even more confusing, as [Wowpedia](https://wowpedia.fandom.com/wiki/Razorfen_Downs?oldid=3365129) states a required level of 35, tho that is from 2014.
This comment from Wowhead, even states that 25 is correct:
![image](https://user-images.githubusercontent.com/53914190/139712704-adbc0cc9-be90-437a-b2f7-751cb4aba3f0.png)
Which I'd like to add, is what it currently is on local AC.
Another comment stating the same:
![image](https://user-images.githubusercontent.com/53914190/139712913-dfacc456-aa84-4fad-a6a0-0cd5c4e89cb5.png)

So I'd say there is inconclusive evidence for a change.

**Comment by Shineslippers** [comment]
There is exist wowwiki [Instances by level](https://wowwiki-archive.fandom.com/wiki/Instances_by_level?oldid=2308259) page. Due to RDF level enter level was lovered to 25. I'm not sure should it affect walk in.

**Comment by gurveleg** [comment]
World of Warcraft: Cataclysm Patch 4.0.3a (2010-11-23): Level range increased to 40 - 50.
World of Warcraft: The Burning Crusade Patch 2.3.0 (13-Nov-2007): Level range lowered from 35 - 42

<html><body>
<div class="comment-header">

By vkez on 2010/11/29 (Patch 4.0.3) |   |  
-- | -- | --


</div><div class="text comment-body" lang="en">Since the cataclysm, it now requires a minimum of level 35 to enter.</div>
</body>
</html>

From this we can conclude that with level change in patch 2.3 the minimum level required ot enter was 25, which then hold true through out the Wotlk expansion and it wasnt until Cataclysm tha tit got changed to level 35.

**Comment by gurveleg** [comment]
Atlasloot addon for wotlk also puts the minimum level to enter at 25

**Comment by j-hdt** [comment]
Classic level requirements have been changed with Wotlk allowing/restricting access to some dungeons at different levels, too.
