### ISSUE TITLE
Druid Shapeshift not removing movement imparing effects

### ISSUE THREAD

**Issue by Alaeria-Val** [chromiecraft/chromiecraft#223]
##### CURRENT BEHAVIOUR:

When being dazed, a way to counter this is to exit your form, heal, and re-enter. According to the site provided by the format, as well as the ingame tooltip: "The act of shapeshifting frees the caster of Polymorph and Movement Impairing effects." When I did this to remove daze, it was not removed and was simply dazed again attempting it.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The act of entering the form, such as travel form, should remove daze or any other imparing effects.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Fight a mob and get dazed while in a form, ex: travel form
2. Exit Travel Form
3. Enter Travel Form
4. Notice you are still dazed

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by AbraKabastard** [comment]
I cannot confirm at least on my own compile. Being in travel form, getting dazed, going out of travel form and then back in removes the daze. Tested using Harvest Watchers and Harvest Golems in Westfall.

**Comment by necropola** [comment]
It's definitely not a general bug with this druid feature. I've played my druid today and it works, i. e. shape-shifting removes any kind of movement impairing effect. Maybe you just have been dazed again after shape-shifting removed the first application? 

We need more info to reproduce this maybe very specific case (Where does it happen? Which NPCs are involved?). Having the combat log for such an incident would help a lot.

**Comment by Alaeria-Val** [comment]
I was in duskwood fighting the skeletons for gravemoss when i tried fleeing, exiting, and reentering my daze cd was still going down. When I entered my daze duration was still at 1 second.

**Comment by necropola** [comment]
I assume that you have been using shapeshift to get out of CC since level 10 (when you got bear form) and so far it worked, right? Which would mean this is some very rare occurence.

Can you try to reproduce it and then either copy (I think you need an Addon like "Prat" to do this) or screenshot the relevant part of the combat log and post it here?

**Comment by Stifler82** [comment]
@Alaeria-Val 

What you need to do is:
- Delete the contents of the "Cache" folder inside the WoW directory.
- **(If)** you have the **WoW enGB Client (delete it)** and **download the enUS Client!**

The wow enGB Client is full of errors that create a lot of **"Visual" Bugs**, so if you have the enGB version **delete it!**

**Comment by Alaeria-Val** [comment]
I went back to herbing and was unable to reproduce it. Ill close it since it seemed to be a one off occurrance. Sorry for the wasted time

**Comment by AbraKabastard** [comment]
Please re-open. NPC ID: 3821 performs a Daze on me I cannot dispel with shapeshift

**Comment by Stifler82** [comment]
> Please re-open. NPC ID: 3821 performs a Daze on me I cannot dispel with shapeshift

@AbraKabastard 
first, I have to take a look at this NPC, if you are right, I will reopen this issue..
I'll do it as soon as possible, right now, I can't..

**Comment by necropola** [comment]
https://wow.gamepedia.com/Druid_shapeshift_forms
>Shapeshifting also breaks all movement-impairing effects (like  [Slow] or  [Hamstring]) and roots ( [Frost Nova] or  [Entangling Roots]) **except the 3-second daze** that can proc when one is attacked from behind by a melee attack.

Dunno why I thought myself that it would break daze, too. Maybe it broke the Daze from the front spell we had as a bug for a while until @Stifler82 fixed it.

**Comment by Stifler82** [comment]
> https://wow.gamepedia.com/Druid_shapeshift_forms
> 
> > Shapeshifting also breaks all movement-impairing effects (like  [Slow] or  [Hamstring]) and roots ( [Frost Nova] or  [Entangling Roots]) **except the 3-second daze** that can proc when one is attacked from behind by a melee attack.
> 
> Dunno why I thought myself that it would break daze, too. Maybe it broke the Daze from the front spell we had as a bug for a while until @Stifler82 fixed it.

I have to take a look, because probably that "Daze" is another ID and has nothing to do with the Daze Fix that I made, because it is impossible that it is related to this issue: https://github.com/chromiecraft/chromiecraft/issues/61

**Comment by necropola** [comment]
This is the code that applies daze (spell=1604) at a base proc chance of 20% when one is attacked (by any creature) from behind in melee: https://github.com/necropola/azerothcore-wotlk/blob/b7aa1f301a99f5c0e12bf82654e458182d1812e0/src/server/game/Entities/Unit/Unit.cpp#L1553
```C++
    // If this is a creature and it attacks from behind it has a probability to daze it's victim
    if (damageInfo->damage && ((damageInfo->hitOutCome == MELEE_HIT_CRIT || damageInfo->hitOutCome == MELEE_HIT_CRUSHING || damageInfo->hitOutCome == MELEE_HIT_NORMAL || damageInfo->hitOutCome == MELEE_HIT_GLANCING) &&
                               GetTypeId() != TYPEID_PLAYER && !ToCreature()->IsControlledByPlayer() && !victim->HasInArc(M_PI, this)
                               && (victim->GetTypeId() == TYPEID_PLAYER || !victim->ToCreature()->isWorldBoss()) && !victim->IsVehicle()))
    {
        // -probability is between 0% and 40%
        // 20% base chance
        float Probability = 20.0f;

        // there is a newbie protection, at level 10 just 7% base chance; assuming linear function
        if (victim->getLevel() < 30)
            Probability = 0.65f * victim->getLevel() + 0.5f;

        uint32 VictimDefense = victim->GetDefenseSkillValue();
        uint32 AttackerMeleeSkill = GetUnitMeleeSkill();

        // xinef: fix daze mechanics
        Probability -= ((float)VictimDefense - AttackerMeleeSkill) * 0.1428f;

        if (Probability > 40.0f)
            Probability = 40.0f;

        if (roll_chance_f(std::max(0.0f, Probability)))
            CastSpell(victim, 1604, true);
    }
```

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Druid Shapeshift](https://youtu.be/S6cMSDpnxKk)

**Comment by necropola** [comment]
@Stifler82 You are basically overriding a client-side SpellInfo record (Spell.dbc) with an additional entry in the Database (spell_dbc) to fix something that doesn't need to be fixed.
