### ISSUE TITLE
[NPC bug] - Southsea Swashbucklers - Missing weapon

### ISSUE THREAD

**Issue by TheRiddermark** [chromiecraft/chromiecraft#2240]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

The [Southsea Swashbucklers](https://wowgaming.altervista.org/aowow/?npc=7858) in Tanaris have a small buckler equipped instead of the proper sword. They are basically unarmed. On first glance the other NPCs look fine but it's possible there are more discrepancies.

[Screenshot](https://pasteboard.co/j8yR0CLIlNvE.jpg)

### Expected Blizzlike Behaviour

The [Southsea Swashbucklers](https://wowgaming.altervista.org/aowow/?npc=7858) should have a sword. Don't know how to find out the proper one but below you can find links to the exact look.

[Wowhead page](https://classic.wowhead.com/npc=7858/southsea-swashbuckler#comments) of how they should look.

You can clearly see what NPC should have what weapon [in this long video](https://www.youtube.com/watch?v=cX2Cuu8EZ6E) of the [quest](https://wowgaming.altervista.org/aowow/?quest=8366).

### Steps to reproduce the problem

Take up the quest [Southsea Shakedown](https://wowgaming.altervista.org/aowow/?quest=8366) and check the quest region for the NPCs. (You don't need to take the quest but easier to navigate to the spot).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/8913
