### ISSUE TITLE
[Quest] Screecher Spirits - incorrect behaviour

### ISSUE THREAD

**Issue by TheRiddermark** [chromiecraft/chromiecraft#2242]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

In relation to the [last post](https://github.com/chromiecraft/chromiecraft/issues/1154) in the previous, now closed report, I'm opening this issue again. There are several issues with the quest.

1. The quest item [Yeh'kinya's Bramble](https://wowgaming.altervista.org/aowow/?item=10699) can be used on ANY mob.
2. Doesn't matter if the mob is alive or dead - [Screecher Spirit](https://wowgaming.altervista.org/aowow/?npc=8612) appears.
3. When used on a living [Vale Screecher](https://wowgaming.altervista.org/aowow/?npc=5307) it **despawns** the npc in addittion to summoning the [Screecher Spirit](https://wowgaming.altervista.org/aowow/?npc=8612)

[Clumsy footage](https://streamable.com/uiqqcp) of me using it on a wolf.
[Screenshot](https://pasteboard.co/C4C2LlOde8gS.jpg) of the moment I despawned the Vale Screecher and the ghost appeared.

### Expected Blizzlike Behaviour

It should work as simple as this.

1.Kill [Vale Screecher](https://wowgaming.altervista.org/aowow/?npc=5307)
2.Use item on the corpse of [Vale Screecher](https://wowgaming.altervista.org/aowow/?npc=5307) (usable only on this)
3.Talk to summoned [Screecher Spirit](https://wowgaming.altervista.org/aowow/?npc=8612)
4.Receive quest credit (1/3, 2/3, 3/3 etc.)

[Video of how it works.](https://youtu.be/EHQIVcdnSqY?t=145)

### Steps to reproduce the problem

[Pick up the quest](https://wowgaming.altervista.org/aowow/?quest=3520) and use [the quest item](https://wowgaming.altervista.org/aowow/?item=10699) on any mob. (Have not tested it on mobs outside Feralas or in dungeons)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Arystor** [comment]
I confirm, already at the time the issue was closed without having solved it. The mission can be completed in Tanaris, any npc will do. Alive or dead.

`https://www.youtube.com/watch?v=LXF747jRFX0`

**Comment by cirosantos0** [comment]
Still working incorrectly as described in the issue on chromiecraft as of 06/06/2022 (rev. c352d2e278be)
