### ISSUE TITLE
Ruga Ragetotem won't allow you take quest Trial at the Field of Giants

### ISSUE THREAD

**Issue by Trululu567** [chromiecraft/chromiecraft#2246]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When your warrior reaches level 20 (whichever horde race) a warrior trainer NPC on one of the capital cities, excluding Silvermoon, will give you the quest "Speak with Ruga" (quest=1823), for which you have to go turn it at Camp Taurajo. You can talk there to Ruga Ragetotem (npc=6394) and turn the quest. However, you cannot take the following quest called "Trial at the Field of Giants" (quest=1824), even though the quest available sign shows on top of said NPC. When you interact with Ruga Ragetotem he just opens his usual dialogue window, but you cannot take the quest.

### Expected Blizzlike Behaviour

You should be able to take the quest.

### Steps to reproduce the problem

1. Take the quest=1823 "Speak with Ruga" from either NPCS: npc=3041, npc=3354, npc=4595.
2. Teleport to npc=6394 "Ruga Ragetotem".
3. Complete the quest=1823.
4. Quest available sign should pop up on top of the NPC, but won't be able to take it. Quest should be quest=1824 "Trial at the Field of Giants".

### Extra Notes

https://classic.wowhead.com/npc=6394/ruga-ragetotem
https://classic.wowhead.com/quest=1824/trial-at-the-field-of-giants

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for report, but on local AC everything is good. Trial at the Field of Giants is time-limited quest you can't get it if you have another time-limited quest. Probably you have [Apothecary Zamah](https://wowgaming.altervista.org/aowow/?quest=853) in your Quest Log
![WoWScrnShot_110221_225832](https://user-images.githubusercontent.com/85256266/139943423-36a3b1f3-ee30-4921-814c-f1f140066bfe.jpg)
