### ISSUE TITLE
Cleanse Spirit - Failure to Cleanse One Effect of Each Applicable Type

### ISSUE THREAD

**Issue by Ithiloneth** [chromiecraft/chromiecraft#2248]
### What client do you play on?

enUS

### Faction

- [x] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59

### Current Behaviour

https://wowgaming.altervista.org/aowow/?spell=51886
Cleanse Spirit cures one instance, of one type. If the target is affected by one Poison and one Curse, one of these is removed per cast.

### Expected Blizzlike Behaviour

Cleanse Spirit should cure one Poison, one Disease, and one Curse, curing up to a total of three effects per cast.

### Source

I am afraid I could find no source beyond the tooltip, see the spell:
https://wowgaming.altervista.org/aowow/?spell=51886

### Steps to reproduce the problem

1. Have a Shaman with Cleanse Spirit known.
2. Have a target friendly to that Shaman which is afflicted with at least two separate effects, e.g one Curse and one Poison.
3. Cast Cleanse Spirit on the friendly target.
4. Observer whether the spell cures one, or more effects.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheRiddermark** [comment]
If it's any help I managed to dug out [this post](https://forum.rpg.net/index.php?threads/wow-shaman-class-changes-preview-irwin-x-jesus-christ-people.508624/) that references WoW changes in Cataclysm. The specific quote that relates to this case is:

_* We're making changes to which classes and specs are able to dispel magic, diseases, curses, and poison, largely for PvP purposes. Shaman will have Cleanse Spirit as a baseline ability, but it will only remove curses. Restoration shaman will have a talent that will improve Cleanse Spirit so that it also removes magic. Shaman will no longer be able to remove poison._

**Comment by Shineslippers** [comment]
Thank you for report, but on local AC everything is working correct. I have to close report accordingly.
https://user-images.githubusercontent.com/85256266/140077543-df19d6d3-ae2e-40b0-b311-850cb229433d.mp4

**Comment by Ithiloneth** [comment]
I have since had more experience using the talent; it does seem to be working here as well. The explanation seems to be that a dispel can be resisted on a per effect basis; hence it can appear as if only one effect was targeted by when in fact several were.

Sorry for the mistaken report!
