### ISSUE TITLE
NPC "Dark Iron Rifleman" not dropping [Steelarrow Crossbow] / Loot table bug

### ISSUE THREAD

**Issue by Hanzemon** [chromiecraft/chromiecraft#225]
##### CURRENT BEHAVIOUR:

The NPC [Dark Iron Rifleman](wowgaming.altervista.org/aowow/?npc=6523) is not dropping item [Steelarrow Crossbow](https://wowgaming.altervista.org/aowow/?item=6315).

The Item  [Steelarrow Crossbow](https://wowgaming.altervista.org/aowow/?item=6315) is a unique drop from this NPC.

Evidence for this claim:
![image](https://user-images.githubusercontent.com/32701428/111427036-ded64700-86cb-11eb-8ef3-98ccd30b9920.png)
[(Steelarrow Crossbow page in Wow Gamepedia)](https://wow.gamepedia.com/Steelarrow_Crossbow)

![image](https://user-images.githubusercontent.com/32701428/111427124-ff9e9c80-86cb-11eb-910f-0baa8a037da2.png)
[(Dark Iron Rifleman page in Wow Gamepedia)](https://wow.gamepedia.com/Dark_Iron_Rifleman)

----------------------------------------------------------------------------------------------------------------------------------------------

It appears that the chance to drop, is itself the bug. Archived webpages for both the Item and the NPC from back in 2011 and Classic wowhead shows that the droprate for this item should be anywhere between 3% and 7%.

Evidence to support this claim:
![image](https://user-images.githubusercontent.com/32701428/111429023-bef45280-86ce-11eb-997c-1aa58a427a5f.png)
[(wowhead page for Dark Iron Rifleman as of Dec. 7, 2011)](https://web.archive.org/web/20111207084244/http://www.wowhead.com/npc=6523)

![image](https://user-images.githubusercontent.com/32701428/111429976-1cd56a00-86d0-11eb-9029-a7e3f7243f4a.png)
[(wowhead page for Steelarrow Crossbow as of July 15, 2011)](https://web.archive.org/web/20110715152444/http://www.wowhead.com:80/item=6315)

![image](https://user-images.githubusercontent.com/32701428/111429363-4b067a00-86cf-11eb-9015-07a823a22de4.png)
[(classic wowhead page for Dark Iron Rifleman)](https://classic.wowhead.com/npc=6523/dark-iron-rifleman)

![image](https://user-images.githubusercontent.com/32701428/111429314-36c27d00-86cf-11eb-8f47-66d7d27085e5.png)
[(Classic Wowhead page for Steelarrow Crossbow)](https://classic.wowhead.com/item=6315/steelarrow-crossbow)

----------------------------------------------------------------------------------------------------------------------------------------------

After doing some research in the database files from [Chromiecraft Azerothcore database files](https://github.com/chromiecraft/azerothcore-wotlk). I with the help of @GiatEMINaGOR#6462 from discord, found that the item  [Steelarrow Crossbow](https://wowgaming.altervista.org/aowow/?item=6315) is in fact in the [loot table](https://github.com/chromiecraft/azerothcore-wotlk/blob/master/data/sql/base/db_world/creature_loot_template.sql), only not as a direct drop from [Dark Iron Rifleman](wowgaming.altervista.org/aowow/?npc=6523) (as should otherwise be, given that it is supposed to be a unique item dropped ONLY by this NPC); but, in a [reference loot table entry](https://github.com/chromiecraft/azerothcore-wotlk/blob/master/data/sql/base/db_world/reference_loot_template.sql), specifically 24066, which contains loot that is shared amongst 440 other NPCs and in a pool of 88 other Items. Making it near-impossible to obtain.

Citing: @GiatEMINaGOR#6462
![image](https://user-images.githubusercontent.com/32701428/111437378-64142880-86d9-11eb-878a-4eec92af8550.png)

After knowing this information, it was obvious that in the current database this item is being treated as a World Drop.

Quoting Wow Gamepedia's [Article on Wold Drops](https://wow.gamepedia.com/Category:World_drops):

![image](https://user-images.githubusercontent.com/32701428/111435505-40e87980-86d7-11eb-9771-54d03bf4f261.png)

----------------------------------------------------------------------------------------------------------------------------------------------

This is clearly not the case for our Item [Steelarrow Crossbow](https://wowgaming.altervista.org/aowow/?item=6315), for which there is very well documented evidence that up to it's removal in patch 4.0.3a, it only ever dropped from [Dark Iron Rifleman](wowgaming.altervista.org/aowow/?npc=6523).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Item Steelarrow Crossbow is a Unique drop from NPC Dark Iron Rifleman in Wetlands. With a dropchance between 3% and 7%. NOT a World Drop with a 0.5% shared amongst 88 other Items and 440 other NPCs.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Spend 16 hours killing only Dark Iron Rifleman
2. Confirm that it is statistically impossible not having it drop after  _hundreds_ of attempts if the droprate were blizz-like.

##### EXTRA NOTES:

I would also like to mention that I spent around 15-17 hours (11 to 12 hours in between march 15th and march 16th, plus 4 to 5 hours between march 16th and march 17th) attempting to obtain this item by killing only Dark Iron Riflemen and ocassionally Dark Iron Dwarves that would pull near them accidentally. I leveled from lvl 22 to lvl 28 in this manner. I started this grind with around 4 gold in my bags.

I occasionally flew to Ironforge to train new abilities. 
I managed to max out First Aid at 225 using only the cloth dropped by these NPCs (excluding the linen I obtained while leveling from 1-22).

These NPC more often than not leave **no loot**, despite this, I've been able to acquire several blue items and ended up with 32 gold only from selling Green/White/Grey quality items dropped by these NPCs.

I have also obtained several blue Items from these NPCs, Including but not limited to these:
![image](https://user-images.githubusercontent.com/32701428/111435102-bef85080-86d6-11eb-950d-6f63ff85dbe7.png)

As a gesture from the Chromiecraft team, I would like to ask: Were this bug to be confirmed, I be rewarded with a [Steelarrow Crossbow](https://wowgaming.altervista.org/aowow/?item=6315). It's simply all I ask, If there were anything else that could be rewarded to a player for succesfully reporting a bug, I would like it to go to @GiatEMINaGOR#6462. Without his knowledge in reading database files and the inner workings of such files it would have been impossible for me alone to get to the bottom of this issue.

Thanks for reading. Kind Regards, Hanzemon.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
>If there were anything else that could be rewarded to a player for succesfully reporting a bug, I would like it to go to @GiatEMINaGOR#6462. Without his knowledge in reading database files and the inner workings of such files it would have been impossible for me alone to get to the bottom of this issue.

Aw shucks.

Unfortunately I started looking at other items in the 24066 Reference Table and the first few I checked all appear to drop from Unique NPCs.
There's a lot of work to tidy this up :(

**Comment by Hanzemon** [comment]
> Also, it raises the question as to what the drop rate should be, the archive from Wrath era has 7% but a tiny sample size, and we don't if the 3% drop rate from Classic would still be accurate for Wrath

Well, I believe it is safe to assume the loot table from old world mobs wasn't touched for open world NPCs. Purely from a common sense perspective, why would a developer go back into the database and start changing stuff for content that is no longer relevant. When widely this hasn't been the case and the droprates for most items was untouched in the Vanilla-Wrath period. Apart from few exceptions that were always noted in the patch notes. Like Rivendare's Deathcharger.

Low level vanilla content stood untouched from 2006 to 2010 with the exception of patch 2.3 when many open world elites were changed into normal mobs. Almost nothing changed and it only makes sense. Also as a reminder, classic wow data is the same data as vanilla wow from 2006... remember one of the developers working in retail still had all the data stored on a hard drive, so yeah, classic wow is a reliable source for vanilla wow content, since it is being emulated from vanilla wow data.

**Comment by eTzmNcbkrng** [comment]
@Hanzemon 
I completely agree and would lean heavily towards the 3% number, however, is it only 3% because of the sample size? Is it more likely to be 5% but Wowhead only shows 3% because of probability variances.

Also, a complicating issue is that the Dark Iron Rifleman was in fact Elite in Vanilla and changed to a normal mob in 2.3 as you mentioned.

Honestly, I think this is going to be a best guess scenario until TBC Classic releases and we get some better numbers.

**Comment by 55Honey** [comment]
Why did we close this? There are decent references with drop rates, no?

**Comment by Stifler82** [comment]
> Why did we close this? There are decent references with drop rates, no?

Yes, now I remember, sorry I did it last night and I didn't remember, if you see I put the WFMD label.
So it means the issue (it's closed for now) but when Wowhead puts the TBC on, I'll reopen the issue. 🙂
it is just not to keep an issue open that (currently) we can't do anything about because we don't have enough "DATA" to work on..

**Comment by 55Honey** [comment]
Perfect, thanks!
