### ISSUE TITLE
[Enchanting] Echant does not appear on item when enchanting an unequipable item in bag

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2255]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When enchanting an item in your bag that you cannot equip due to level or armor type restrictions, the enchant does not appear visually on the item. After you relog or move the item in your bag, the enchant visually appears. Closing and opening the bag does not help in this case.

Enchanting an item in your bag that you can equip immediately displays the enchant.

I discovered this behaviour during an enchanting levling session on my level 25 priest while crafting a low level shield enchant on Aegis of Stormwind. But reproduced the problem with other items matching the mentioned criteria.

### Expected Blizzlike Behaviour

The enchant always has to appear visually on an item after the item was enchanted without any restrictions.

### Steps to reproduce the problem

1. Learn enchanting profession.
2. Get an item that you cannot equipt, f.e. due to level restrictions.
3. Put an enchant on the item.
4. The enchant does not appear on the item.
5. Relog or move the item in your bag. The enchant will be displayed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Ragelezz** [comment]
Can't reproduce.

**Comment by jamadaha** [comment]
Just tried it on local server, and found that it works fine. Are you using any addons? They can be cause of interface related bugs.

**Comment by VFaleiro** [comment]
I did this on live ChromieCraft a few days ago (I'm leveling an alt with enchanting) and I enchanted a white shield I bought from a vendor. It worked as it should, I saw the enchant applied right after doing that.

I believe you should follow jamadaha's suggestion and disable all AddOns and try again to see if problem persists.
If it does it's one of your AddOns causing it, you can try enabling one by one to find it out.
