### ISSUE TITLE
Character Face Skin Entered The Void

### ISSUE THREAD

**Issue by DarcusAngelus** [chromiecraft/chromiecraft#2257]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Face is now completely black.
![](https://cdn.discordapp.com/attachments/865324572957474826/905600854655115285/unknown.png)
All my other characters looks fine.

### Expected Blizzlike Behaviour

Looking normal in anyway.

### Steps to reproduce the problem

Not sure how to reproduce the problem. It just logged in like this today.
I have deleted the WTF and it has remained like this when i relog.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df
Not sure what this means.

### Operating system

Edition: Windows 10 Pro
Version: 21H1
OS build 19043.1288

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
What about your head item? mAybe this is something with textures.

**Comment by DarcusAngelus** [comment]
I have equiped and unequipped my headgear. It has done nothing. Still the same.

**Comment by DarcusAngelus** [comment]
The issue was first found in game. Logged out to the character selection to see this. I created a new headgear to wear so i zoomed in before switching. Found the problem before changing headgear and was hoping changing headgear would fix this visual bug. But it didnt lol.

**Comment by DarcusAngelus** [comment]
![image](https://user-images.githubusercontent.com/93688365/140243543-ef1fb61b-8336-4ffb-a340-9f692a6e75c8.png)
![image](https://user-images.githubusercontent.com/93688365/140243628-221127a5-0ccc-441a-b6a7-c7f91573341f.png)

**Comment by DarcusAngelus** [comment]
i havent tried any holloween transformations. I didnt check very carefully then. Could any of that cause it. Like Pumpkin Head or Masks?

**Comment by gurveleg** [comment]
do you use the HD character pack by any chance?

**Comment by DarcusAngelus** [comment]
Yes, i am using the HD packs as per recommended by Chromie. Should i try removing them?

**Comment by DarcusAngelus** [comment]
Ok it looks normal now. I believe it was Patch-H. Not sure what was the conflicting file. But once i removed it, face was normal. And when i add it. Goes back to the Face of Darkness lol.

**Comment by DarcusAngelus** [comment]
For now i will just remove patch H and play without till later notice lol

**Comment by gurveleg** [comment]
You can try hiding the headgear first, if that doesnt help, then removing the characters HD pack until a solution can be found.

**Comment by Azcobu** [comment]
Glad it's easily resolved, will close this as a client-side graphics/texture issue.
