### ISSUE TITLE
3 minutes respawnable wreckages

### ISSUE THREAD

**Issue by Zoidwaffle** [chromiecraft/chromiecraft#226]
From: https://github.com/chromiecraft/chromiecraft/issues/214

 ##### ISSUE: FACTION SIDE: Both
 ##### CONTENT PHASE: 1-80
 ##### SMALL DESCRIPTION:I know this may not be blizzlike but wreckages like waterlogged,bloodsail wreckage shouldn't spawn every 3 minutes like some do because its easily abusable to get a lot of mats with little to no effort.
 ##### EXPECTED BLIZZLIKE BEHAVIOUR:Some wreckages spawn every 3 minutes after you fish them.
 ##### CURRENT BEHAVIOUR:Some wreckages spawn every 3 minutes after you fish them
 ##### STEPS TO REPRODUCE THE PROBLEM:With a wreckage in water,fish it,wait for respawn.
 Step 1
 Step 2
 Step 3
 
 ##### AC HASH/COMMIT:
 [chromiecraft/azerothcore-wotlk@a323107](https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493)
 
 ##### OPERATING SYSTEM:
 Ubuntu 20.04
 
 ##### MODULES:
 * [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
 * [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
 * [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
 * [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
 * [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
 * [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
 
##### OTHER CUSTOMIZATIONS:
None.
 
##### SERVER:
ChromieCraft

**Comment by Zoidwaffle** [comment]
OK, so I don't know how to easily copy the ChromieCraft issues over... So this is what happened.

**Comment by FrancescoBorzi** [comment]
> OK, so I don't know how to easily copy the ChromieCraft issues over... So this is what happened.

just click on "Edit" an existing issue, copy the raw text, paste it to AC

**Comment by Zoidwaffle** [comment]
@FrancescoBorzi : But I cannot press edit on something that I didn't create - I guess I lack rights for that kinda thing :eyes:

**Comment by FrancescoBorzi** [comment]
@Zoidwaffle I've added you to the Bug Triaging team, please accept: https://github.com/chromiecraft
