### ISSUE TITLE
[Quest] Repeatable quests of Mangletooth in The Barrens are acceptable

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2263]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The NPC Mangletooth in The Barrens provides repeatable quests after completion of the quest "Blood Shards of Agamaggan". Immediately after completing this pre-quest you can accept the freshly unlocked repeatable quests. These quest appear afterwards in the quest log (see picture). List of repeatable quest are listed below.

![WoWScrnShot_110521_092921](https://user-images.githubusercontent.com/62797536/140482345-f478e683-f9de-4b50-a6cb-12fa80de27ac.jpg)
Repeatable quests appear in the quest log.

![WoWScrnShot_110521_093706](https://user-images.githubusercontent.com/62797536/140482634-759d729d-0dfe-4a02-bd2f-b278f79317cf.jpg)
Mangletooth shows that you can finish quests even if there are no Blood Shards in your bag to complete these.

### Expected Blizzlike Behaviour

The repeatable quests of Mangletooth should always be non-acceptable.

### Source

Video with expected behaviour: https://www.youtube.com/watch?v=mRVPX4pyj1w&ab_channel=Blizzplanet

### Steps to reproduce the problem

1. Go to Mangletooth in The Barrens.
2. Complete the pre-quest "Blood Shards of Agamaggan".
3. Do NOT close the NPCs dialog.
4. Now you can accept quests that are repeatable and they show up in the quest log.

### Extra Notes

Mangletooth:
https://wowgaming.altervista.org/aowow/?npc=3430

Pre-quest:
https://wowgaming.altervista.org/aowow/?quest=5052

Repeatable quests:
https://wowgaming.altervista.org/aowow/?quest=889
https://wowgaming.altervista.org/aowow/?quest=5042
https://wowgaming.altervista.org/aowow/?quest=5043
https://wowgaming.altervista.org/aowow/?quest=5044
https://wowgaming.altervista.org/aowow/?quest=5045
https://wowgaming.altervista.org/aowow/?quest=5046

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Cant' reproduce it on local AC. You saying `Do NOT close the NPCs dialog`, but it's disapear after pressing "complete"

**Comment by ishidinho** [comment]
May be you want to have a look on another issue, where I discovered a similar bug with turn-in quests: https://github.com/chromiecraft/chromiecraft/issues/2313

**Comment by Shineslippers** [comment]
@ishidinho yes with relog there is exist bug. But with Steps what you meantion in issue with blood shard i can't reproduce it. Is there same relog bug or different one?
