### ISSUE TITLE
BG crash after Nightelf Rogue died

### ISSUE THREAD

**Issue by Notrox1** [chromiecraft/chromiecraft#227]
##### CURRENT BEHAVIOUR:

Horde Player Soryn (bloodelf Rogue) was switched for BG to alliance Nightelf Rogue
After he died the game crash for everyone

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Game should not crash

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Issue with crossfaction BG races

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by AbraKabastard** [comment]
Related to wisp form maybe

**Comment by Helias** [comment]
This issue should be fixed in the next update, unfortunately we need to remove the night elf race even for the druid tauren

fix https://github.com/azerothcore/mod-cfbg/pull/37

**Comment by FrancescoBorzi** [comment]
should be live now
