### ISSUE TITLE
Stormpike Insignia quest chain 

### ISSUE THREAD

**Issue by DarylBlake21** [chromiecraft/chromiecraft#2272]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

When you finish the quest (https://wowgaming.altervista.org/aowow?quest=7162) to get the Stormpike Insignia rank 1 (https://wowgaming.altervista.org/aowow?item=17691) you can immediately complete the next quests to get the rank 2 (https://wowgaming.altervista.org/aowow?item=17900), rank 3 (https://wowgaming.altervista.org/aowow?item=17901), rank 4 (https://wowgaming.altervista.org/aowow?item=17902), rank 5 (https://wowgaming.altervista.org/aowow?item=17903) and rank 6 insignias (https://wowgaming.altervista.org/aowow?item=17904).

![imagen_2021-11-06_112649](https://user-images.githubusercontent.com/74146346/140616719-a1714754-81f6-495a-8f64-1c3cbe3cede8.png)

### Expected Blizzlike Behaviour

You should get the quest and the opportunity to upgrade your trinket once you reach a reputation bracket.
Friendly - Stormpike Insignia Rank 2
Honored - Stormpike Insignia Rank 3
Revered - Stormpike Insignia Rank 4
Exalted - Stormpike Insignia Rank 5
Exalted 999/1000 - Stormpike Insignia Rank 6

### Steps to reproduce the problem

1. Complete the quest Proving Grounds (https://wowgaming.altervista.org/aowow?quest=7162)
2. Deliver the quest and get Stormpike Insignia Rank 1 (https://wowgaming.altervista.org/aowow?item=17691)
3. Deliver the insignia to get the upgrade

### Extra Notes

As an additional comment, this could be happening also in the horde side with the Frostwolf Insignia quest chain too. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
Known issue, see https://github.com/azerothcore/azerothcore-wotlk/issues/8395
