### ISSUE TITLE
Bugged Quests from Alterac Valley

### ISSUE THREAD

**Issue by DarylBlake21** [chromiecraft/chromiecraft#2273]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

To get the Stormpike Insignia trinkets, you have to complete quests from Lieutenant Haggerdin (https://wowgaming.altervista.org/aowow?npc=13841), the bug appears once you deliver the Stormpike Insignia Rank 3. The quests Earning Reverence (https://wowgaming.altervista.org/aowow?quest=7170), Legendary Heroes (https://wowgaming.altervista.org/aowow?quest=7171) and The Eye of Command (https://wowgaming.altervista.org/aowow?quest=7172) keep appearing even if you finished those quests.

![image](https://user-images.githubusercontent.com/74146346/140617308-2f93d4aa-a7d2-4999-b7db-5a3b8eeff1f1.png)

### Expected Blizzlike Behaviour

Once you finish the quest and deliver the trinket to upgrade it to a higher rank, the quest should no longer appear as available.

### Steps to reproduce the problem

1. Go to the entrance of Alterac Valley at the Headlands and take the starting quest Proving Grounds (https://wowgaming.altervista.org/aowow?quest=7172) from Lieutenant Haggerdin (https://wowgaming.altervista.org/aowow?npc=13841)
2. Finsh the quests Proving Grounds, Rise and Be Recognized (https://wowgaming.altervista.org/aowow?quest=7168), and Honored Amongst the Guard (https://wowgaming.altervista.org/aowow?quest=7169)
3. After you finished Earning Reverence (https://wowgaming.altervista.org/aowow?quest=7170), the quest is still appearing, the same with Legendary Heroes (https://wowgaming.altervista.org/aowow?quest=7171) and The Eye of Command respectively.

### Extra Notes

As an additional comment, this could be also happening in the horde side with the Frostwolf Insignia quest chain too.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
Hey, thanks for the report, but this is a know issue already reported in https://github.com/azerothcore/azerothcore-wotlk/issues/8395
