### ISSUE TITLE
Stuck in Levitate state

### ISSUE THREAD

**Issue by Scrawnyon** [chromiecraft/chromiecraft#2286]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Casting and quickly removing the Levitate buff right before you land causes player to be stuck in a floating Levitate-state, without actually having the buff. The effect doesn't cause slow fall, lasts forever, and doesn't get removed when mounting or taking damage, but does prevent jumping and causes janky behaviour when running down steep hills. Re-casting and removing Levitate returns player to normal state

### Expected Blizzlike Behaviour

Removing Levitate buff returns player to normal state

### Steps to reproduce the problem

1. Jump in the air or fall from a ledge
2. Cast Levitate right before you hit the ground
3. Remove the Levitate buff immediately

### Extra Notes

Video: [Link](https://www.youtube.com/watch?v=_1DTnAJlYTw)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
When exactly i have to remove levitation? Can't reproduce it on local AC.

https://user-images.githubusercontent.com/85256266/140726024-ca63cad4-3c4d-4f35-a87a-8cb8faf5997b.mp4

**Comment by Scrawnyon** [comment]
> When exactly i have to remove levitation? Can't reproduce it on local AC.
> 
>  2021-11-08.13-26-36.mp4

It's a little tricky, you have to cast and remove it just before you land (either from falling or jumping). You can check the video in the 'Extra Notes' section and keep an eye on the buff icon in the top left corner
