### ISSUE TITLE
Grizzled Black Bear Appears as "Unknown'

### ISSUE THREAD

**Issue by seancallaway** [chromiecraft/chromiecraft#229]
##### CURRENT BEHAVIOUR:

A [Grizzled Black Bear](https://wowgaming.altervista.org/aowow/?npc=1188) in Loch Modan appears as "Unknown."

![image](https://user-images.githubusercontent.com/1229384/111495442-9b480100-86fc-11eb-82be-4dc2c6bf22b3.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Bear should appear with the proper name/title.

##### STEPS TO REPRODUCE THE PROBLEM:

I have only noticed this once, but believe that it just happens to random bears in Loch Modan.

##### EXTRA NOTES:

N/A

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Checked the 23 available mobs and none of them had that name.
What are the cords? or map shot?

**Comment by seancallaway** [comment]
It was dead at the time of the creation of this issue, but it was right in here.

![Screen Shot 2021-03-17 at 9 29 16 AM](https://user-images.githubusercontent.com/1229384/111502747-5ecbd380-8703-11eb-82ca-6b6ad95a96ab.png)

**Comment by Si1ker** [comment]
Nothing to found.
Probably it was your client.

Use "/console reloadui"  whenever you see stuff like that, usually happens randomly, another example of this behaviour:

![image](https://user-images.githubusercontent.com/61223313/111505907-b7ed3480-870e-11eb-8f22-914bcf8e73f0.png)

**Comment by seancallaway** [comment]
Yeah, quite possible, but thought it was worth reporting just in case. Feel free to close.

**Comment by illfated** [comment]
@seancallaway : Don't know if this comment helps, but you can rest assured that (almost) everyone will experience this kind of missing information about some NPC or Player Pet sometimes. This usually happens because of unexpected lag between the game client and the server, making it pretty random when the issue occurs, while also not being an issue at all to other players at the same time, even within close proximity to the player experiencing this game client bug.
