### ISSUE TITLE
[Warlock Ability] - Drain Soul (1120) - Incorrect behavior

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#2292]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [X] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Drain Soul is currently making warlocks gain a Soul Shard every single time enemy dies, even when enemy is so low that doesn't yield any experience or honor.
As you can clearly see on these images, I can obtain Soul Shards from mobs that are 8 levels and more below me and which give no experience. This is working all the time, on every mob, even 10+ levels lower.
![ 2021-11-09 at 14 04 48](https://user-images.githubusercontent.com/77953030/140913175-025992e6-ccbe-444d-b09e-5cfac67ec607.png)
![ 2021-11-09 at 14 04 53](https://user-images.githubusercontent.com/77953030/140913213-a8a31c0c-b144-4576-9340-5bf7e5ff1e62.png)

### Expected Blizzlike Behaviour

As well described on ability: "If the target dies while being drained, and yields experience or honor, the caster gains a Soul Shard". Prior to 3.1.0, it was impossible to obtain Soul Shards from grey mobs, but it was later fixed so there is A CHANCE to generate a shard, which means enemies that don't yield experience or honor should RARELY grant a Soul Shard. I think it's necessary to review the % chance for this to happen.

Patch 1.5.0 (2005-06-07): Honorable kills will now generate a Soul Shard when Drain Soul is used.
Patch 3.1.0 (14-Apr-2009): Each time Drain Soul deals damage to a target which can grant experience, it now has a chance to generate a Soul Shard.

### Source

[Drain Soul (Rank 1)](https://wotlk-twinhead.twinstar.cz/?spell=1120) (10)
[Drain Soul (Rank 2)](https://wotlk-twinhead.twinstar.cz/?spell=8288) (24)
[Drain Soul (Rank 3)](https://wotlk-twinhead.twinstar.cz/?spell=8289) (38)
[Drain Soul (Rank 4)](https://wotlk-twinhead.twinstar.cz/?spell=11675) (52)
[Drain Soul (Rank 5)](https://wotlk-twinhead.twinstar.cz/?spell=27217) (67)
[Drain Soul (Rank 6)](https://wotlk-twinhead.twinstar.cz/?spell=47855) (77)

### Steps to reproduce the problem

Create a warlock and lvl up to lvl 10 so you can learn Drain Soul (1120).
Use Drain Soul to finish and kill a mob of any level, even 7+ levels lower and who won't grant you any experience or honor.
Try with different mobs and see that you obtain a Soul Shard every single time.

Test with new ranks of Drain Soul, obtained at levels 24, 38 and 52.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
I would like to give an update. I tested it on several mobs and even creatures lvl 1-3 such as sheeps and rams are giving Soul Shards. This should not work like this.

**Comment by Shineslippers** [comment]
Most funny thing it worked as it should some monthes ago https://github.com/azerothcore/azerothcore-wotlk/issues/5935

**Comment by gurveleg** [comment]
Might be linked to https://github.com/azerothcore/azerothcore-wotlk/issues/8904 in some matter, since the spell should work on mobs that yield xp or honor

**Comment by patou01** [comment]
I think someone broke the spell scripts. Part of the script isn't used it seems. I'm having a look at it

**Comment by Venom0fGod** [comment]
I was coming to report this, I just noticed Destruction spell Shadowburn is having exact same result on grey mobs, still awarding shards when it should not. Can confirm both Drain and Burn are still awarding shards from grey mobs, Even without the Drain Soul glyph.
