### ISSUE TITLE
Tome of Divinity

### ISSUE THREAD

**Issue by Clanggedon7777** [chromiecraft/chromiecraft#2295]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

after turning in a relay quest from a paladin trainer to go see Tiza Battleforge, she gives you a book to study.  This book is the tome of divinity.  Its an item that starts a quest.  The level requirement on the book is level 12 which my toon is.  I checked that it hasn't been mistakenly put low as my previous pally was 17 and still no luck and I saw other human pallies with rez!  My problem is when I try to click the book (Tome of Divinity) the quest is not starting its says over and over that I don't meet the requirements for that quest.  My previous pally and this one both named Clanggedon are dwarfs.  

### Expected Blizzlike Behaviour

So long as the toon meets the requirements which in this case is level 12 it should start a quest
https://www.youtube.com/watch?v=WoVF5GPsQzM

### Source

The only source of the bug I know of is the 2 times I've tried with both my dwarf palladins, the first I leveled to level 17 and still couldn't click it, my current palladin is level 12 to full fill the requirement
https://www.youtube.com/watch?v=WoVF5GPsQzM

### Steps to reproduce the problem

Create a male dwarf palladin
Level to level 12
Accept the trainer quest from any palladin trainer displaying !
Turn quest in at Tiza Battleforge
Accept next quest and recieve book Tome of Divinity
Click on the book in your inventory (Tome of Divinity) and it should start the quest but doesn't

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
We aware about this issue. you have to ask GM to help you with this issue in Discord. In case leave your ingame name please.
