### ISSUE TITLE
Mmmrrrggglll not fearing Murlocs on Death

### ISSUE THREAD

**Issue by Cosmic-Lattee** [chromiecraft/chromiecraft#23]
##### SMALL DESCRIPTION:
[Mmmrrrggglll ](https://www.wowhead.com/npc=15937/mmmrrrggglll) doesn't cause his little murloc friends to run around in fear when he dies.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When Mmmrrrggglll dies he is supposed to cause nearby Murlocs to flee in fear. If you filter the comments to patch 3.0.9 in the above page you will see mention that killing him causes nearby murlocs to fear.

##### CURRENT BEHAVIOUR:
They don't run away when he dies, and when you kill certain Murlocs (It was either the [Grimscale Foragers](https://www.wowhead.com/npc=15670/grimscale-forager) or [Grimscale Murlocs](https://www.wowhead.com/npc=15668/grimscale-murloc) or rather when you almost kill them they seem to become feared like when Mmmrrrgglll dies. The caster types ([oracles](https://www.wowhead.com/npc=15669/grimscale-oracle) and [seers](https://www.wowhead.com/npc=15950/grimscale-seer)) don't seem to do this.

##### STEPS TO REPRODUCE THE PROBLEM:
Kill Mmmrrrgglll to see if they cause the other little murlocs to become affected by fear. Also kill Foragers or Murlocs (seers and Oracles don't) to see them become feared when they are near death.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Fixed, will be in the server soon!

**Comment by FrancescoBorzi** [comment]
The fix is now on ChromieCraft. Thanks for your report.
