### ISSUE TITLE
Mining nodes are not x1 blizzlike rate

### ISSUE THREAD

**Issue by CyberneticCC** [chromiecraft/chromiecraft#230]
##### CURRENT BEHAVIOUR:

Mining nodes in the entire game are respawning every 3 minutes. Proof: https://prnt.sc/10ob2xg
Zone: [Redrige Mountains](https://classic.wowhead.com/redridge-mountains)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

15-20min or 30-60min. Unable to find the exact info on the internet.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to location as pointed out with coordinates in the screenshot.
2. Mine every 3 minutes.
3. Go to another location anywhere in the game.
4. Mine every 3 minutes.
5. ???
6. Profit.

##### EXTRA NOTES:

I could've sworn when I played WotlK on retail back in 2008 the respawn timer on nodes was going from 30 to 60 minutes per single node, some people say it's 15 to 20, I honestly have no idea anymore. Been a decade since I touched the game but I am absolutely sure that 3 min is not a x1 rate.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
The fact that it is NOT Blizz-Like does not mean that it is a Bug, only bugs are reported here.
As for some "Mechanics" we have made some arbitrary choices because the population here is not the same as in Blizzard-Retail, so some things have to be "Proportionate" to the current population.
