### ISSUE TITLE
Shaman's Elemental Focus procs on critical heals

### ISSUE THREAD

**Issue by Volldip** [chromiecraft/chromiecraft#2301]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

![WoWScrnShot_111021_224849](https://user-images.githubusercontent.com/89858776/141199042-d06bb84e-a0c7-40fc-8bf1-ec5242966eb8.jpg)

Shaman's Elemental Focus procs on critical heals

### Expected Blizzlike Behaviour

![Screenshot 2021-11-10 225048](https://user-images.githubusercontent.com/89858776/141199293-21ca9e46-df9d-4e7c-ba65-e757c2d196e6.png)

Should only proc on damage spells

### Steps to reproduce the problem

specc into elemental focus, get a critical heal

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
[Healing Wave](https://wowgaming.altervista.org/aowow/?spell=331), [Lesser Healing Wave](https://wowgaming.altervista.org/aowow/?spell=8004), [Chain Heal](https://wowgaming.altervista.org/aowow/?spell=1064), [Riptide](https://wowgaming.altervista.org/aowow/?spell=61295) it's all Nature spells. Druids healing spells also is nature. Paladains and priest has holy school of healing. Thank for report, but i have to close it accordingly.

**Comment by Nyeriah** [comment]
"Elemental Focus (Elemental): Now also can proc off Lesser Healing Wave and Healing Wave, and can be used on all healing spells."
https://wowwiki-archive.fandom.com/wiki/Patch_3.0.2#Shaman

**Comment by Plasmashield** [comment]
It says "damage spell" 
idk about wowwiki, but wowhead's comments says its shouldnt
https://youtu.be/940E7SSAyz0?t=205

**Comment by Nyeriah** [comment]
> It says "damage spell" idk about wowwiki, but wowhead's comments says it wasnt https://youtu.be/940E7SSAyz0?t=205

The patch notes I pasted specifically mention **Lesser Healing Wave** and **Healing Wave** and says it can be used on all healing spells. I'm not sure, is there something I am missing?

**Comment by Stump876** [comment]
Wowhead patchnotes say the same thing. https://www.wowhead.com/patchnotes=3.0.2 
![image](https://user-images.githubusercontent.com/68164076/141713788-fde1b37b-11da-45bb-9c1b-f787969b98c2.png)
I can find nothing after this saying anything different. Unless there is a source saying otherwise, this remains invalid.

**Comment by Plasmashield** [comment]
WoWhead comments say the opposite. I link the video and this is clearly a significant argument. There may be an inaccuracy in the patch note. In that patch, they added a cost reduction for not only damaging spells, but also healing spells. But the proc never came from healing spells. It's only affects them

**Comment by Shineslippers** [comment]
Fun thing it was fixed alredy a while ago https://github.com/azerothcore/azerothcore-wotlk/issues/3859

**Comment by Plasmashield** [comment]
@Shineslippers
https://web.archive.org/web/20110730072059/https://www.wowhead.com/spell=16164

**Comment by Ithiloneth** [comment]
Wanted to stop by and say I'm sad to see this change go through.
Been playing around this talent on other servers which had implemented the patch notes as written.

The video does appear legitimate though - if impossible to verify as such? I have not found any other samples which even claim to be from live that showcase usage of the talent in conjunction with LHW or HW.

Must say that the patch notes are making a very unexpected error indeed to list two specific healing spells as compatible with the talent if they are not - it's a little too specific to be this easily labeled a mistake in my opinion. But I _am_ biased, so.

**Comment by Nyeriah** [comment]
Yes, thanks for all the feedback you guys have been giving on this. It does seem like the patch notes are bogus, I'll revert this soon.

**Comment by Shineslippers** [comment]
Yes, that's all weird. At the start those words from wiki bought me, but tbh that's all what we have. Against it talent description, video(looks like valid one), archive wowhead page and alot of words about this talents that never mentioning HW or LHW. At the end: words from wiki or whole internet against it?

**Comment by Ithiloneth** [comment]
I know - just very sad to see it go this way.
Only sources I have of people talking about using this talent with LHW/HW are from non-live forums and such; not proper proof.
