### ISSUE TITLE
[Spell] Dispel Magic (Rank 2) only dispels one debuff from friendly targets

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2303]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Dispel Magic (Rank 2) only dispels one magic debuff when cast on friendly targets.

Discovered this while doing some RDF on my Level 40 priest.

### Expected Blizzlike Behaviour

Tooltip says that Dispel Magic (Rank 2) "remov[es] 2 harmful spells from a friend".

### Steps to reproduce the problem

1. Go to a RDF dungeon with other players.
2. Wait until a player get two magic debuffs.
3. Use Dispel Magic (Rank 2).

### Extra Notes

Dispel Magic (Rank 2): https://wowgaming.altervista.org/aowow/?spell=988

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Here we go again https://github.com/chromiecraft/chromiecraft/issues/2151, https://github.com/chromiecraft/chromiecraft/issues/2122, https://github.com/chromiecraft/chromiecraft/issues/1159

**Comment by Azcobu** [comment]
Yep, closing this accordingly. As always, if you have any sources that show current behaviour is incorrect, feel free to let us know.
