### ISSUE TITLE
Collectable quest "Iverron's Antitode" items keep sparkling after collecting the requirement

### ISSUE THREAD

**Issue by BrodieSinn** [chromiecraft/chromiecraft#231]
##### CURRENT BEHAVIOUR:

After collecting the required amount of items for the quest "Iverron's Antitode" the items in the world keep sparkling as if saying you need to collect more.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After collecting the required amount the in world items should cease sparkling.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Collect 4 Moonpetal Lily's
2. Look at Moonpetal Lily's in the game world
3. 
4.

##### EXTRA NOTES:

![Screenshot 2021-03-17 133929](https://user-images.githubusercontent.com/77343625/111520618-4620e500-8726-11eb-810d-6dbbb77a8937.png)

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@BrodieSinn thanks for your report, however please look for duplicates before opening a new issue:

https://github.com/chromiecraft/chromiecraft/issues?q=is%3Aissue+Iverron+is%3Aclosed
