### ISSUE TITLE
[Warlock Ability] - Eye of Kilrogg (126) - Unable to attack

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#2312]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Warlock ability "Eye of Kilrogg" seems to be a bit bugged.
At the moment the Eye is summonable and movement and behavior are normal. Aggro radius is pretty small (probably like it was on retail) but **it's unable to attack**.

It also has quite some HP. I couldn't find any source for the right values but it was possible to stand quite a lot of hits.

### Expected Blizzlike Behaviour

Eye should be able to attack when summoned/controlled.

### Source

https://wowwiki-archive.fandom.com/wiki/Eye_of_Kilrogg
https://wotlk-twinhead.twinstar.cz/?spell=126
https://www.wowhead.com/spell=126/eye-of-kilrogg

### Steps to reproduce the problem

Get a warlock to lvl 22 and learn skill Eye of Kilrogg
Cast Eye on Kilrogg and approach a mob
Try attacking an enemy or neutral mob (won't be aggroed anyway)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Yes it's can't attack. That's true. Regarding to HP. Wiki saying ` The eye only has a single point of health` while on AC it has 428.

**Comment by Azcobu** [comment]
I didn't find anything definitive on EoK health, but there's [this video](https://youtu.be/rRcg6TI86oM?t=65) from September 2010 showing it taking multiple hits and with clearly more than 1 HP,

**Comment by Shineslippers** [comment]
Good one. Is there any way to find source of current HP? 428 HP. That's specific number. https://wotlk-twinhead.twinstar.cz/?npc=4277 there is for example x10 more, but this is same number.
