### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Jochem90** [chromiecraft/chromiecraft#2314]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Using a flight path from Moonglade to Tanaris, bought at Faustron <Wind Rider Master>. Around Azshara the game crashes by freezing up, showing a red screen en restrating mine pc ( mac ).
When I restart the game everything works fine, selecting other characters adjusting quality settings etc. But as soon as I select the above mentioned character the game loads for a second and then crashes again.

### Expected Blizzlike Behaviour

After using the flight path from Moonglade to Tanaris, arriving in Tanaris and continue playing this blast from the pas again.

### Source

[2021-11-12 23.49.01.00 Error.txt](https://github.com/chromiecraft/chromiecraft/files/7530997/2021-11-12.23.49.01.00.Error.txt)

### Steps to reproduce the problem

Talk to Faustron <Wind Rider Master>
buy a flight to Tanaris

### Extra Notes

I'm falling in love all over again with this game, thank you guys so mutch for al the hard work you guys have been doing!

I would really love the continue mine journey on this character. 

Thank you.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/9e3332dc208215f60d62b6eef3c9e804464708da
none

### Operating system

Ubuntu 20.04
MacOS 10.14.6

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Hello. This is something related to you. It could be addon that loading upon zone change. Also you can try to clear Cache folder in your WoW directory. If you still can't log in ask gm in game or in Discord to teleport you.

**Comment by Jochem90** [comment]
Hi, 

thanks for the help.

I already have disabled my add-ons and tried running it in the lowest setting possible.

I'll try to contact a GM.

How do i remove the HD patch ?

Kind Regards,

**Comment by Jochem90** [comment]
Update,

clearing the Cache folder dind't do the trick.

**Comment by Shineslippers** [comment]
I'm sure you have some free space on your laptop. Instead of remove pathc(because i don't know tbh how to do it) you can download one more client from https://www.chromiecraft.com/ and just move your `Interface` and `WTF` folders to the new WoW client.
