### ISSUE TITLE
More than 10 ppl on one team in WSG... again

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#2316]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

In chat pane, you can see healers confirming via their raid panes. You can also confirm by mousing over the zone map, although that would require a video to submit as proof.

![WoWScrnShot_111321_060025](https://user-images.githubusercontent.com/89823720/141626074-ca3d23a7-3b37-4a26-aa1e-edcf09e37200.jpg)

### Expected Blizzlike Behaviour

10 max per team in WSG 

### Source

common knowledge of wow mechanics

### Steps to reproduce the problem

Do whatever you guys did the first time you fixed this, ngl really feels like our efforts cheapened when this can just crop right back up

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/9e3332dc208215f60d62b6eef3c9e804464708da

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by j-hdt** [comment]
see
[https://github.com/chromiecraft/chromiecraft/issues/2183](https://github.com/chromiecraft/chromiecraft/issues/2183)

discussions in the PvP channel and suggestion channel so far have been ignored.

**Comment by Shineslippers** [comment]
No, that's a bug, Atleast this report. It's huge unbalance, but noone kno where it from comming.

**Comment by cachocarne** [comment]
I actually thought they were testing a new system for WSG. Yesterday I saw HUGE groups, way more than 10v10. Never saw so many people in such small map. Inspecting raid frames (Grid) also showed me as part of a team with 11-14 people sometimes.

**Comment by Orixim** [comment]
I have been doing plenty of WSG this weekend and most of them with huge raid groups, far more than 10. I had no clue that was not suppose to happen though.
