### ISSUE TITLE
Fps downgrade

### ISSUE THREAD

**Issue by Beglar56** [chromiecraft/chromiecraft#2317]
Hello there everyone, 

Im posting this cause while playing i do have a several fps downgrade that makes the game unplayable, i've tried to re-install the game, using diferents sources, change the graphic setting, i've also tried the game without the hd texture pack, and without the spanish leanguage pack too, even wipe the computer yet stills does not work. So im here as my last try cause i dont know what to do 
Please help!

**Comment by temperrr** [comment]
Hi, this is not the place for this kind of support. You can try #support channel on discord.  https://discord.gg/MYpCAZRE
You can try disabling hardware cursor in video settings, see if that solves your problem.
