### ISSUE TITLE
Naga at the Zoram Strand quest

### ISSUE THREAD

**Issue by O1dD0g** [chromiecraft/chromiecraft#2318]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

This quest  Naga at the Zoram Strand requires 20 Wrathtail Heads and I seem to be stuck on 19 of them. I've been trying for over two hours and can not get the 20th head to drop. I've tried it on two different days with numerous logouts. The client was downloaded from ChromieCraft web stie. Thank you.

### Expected Blizzlike Behaviour

The 20th head should drop from the Naga to complete the quest.

### Steps to reproduce the problem

Start the quest and the heads drop very quickly except the 20th head does not drop to complete the quest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/9e3332dc208215f60d62b6eef3c9e804464708da

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for report. On local AC everything is ok. Have you stored quest heads in bank? There is exist issue with it. Best way to solve the issue is abandon quest and do it again. It will destroy quest items anywhere and allow you to complete quest.
![WoWScrnShot_111321_180025](https://user-images.githubusercontent.com/85256266/141648575-33e82715-3482-4485-b9b5-07d7a96455bc.jpg)
.

**Comment by O1dD0g** [comment]
Thank you for your fast response. Heads were not stored in the bank but I will abandon quest and restart. GREAT server!

----- Original Message -----
From: Totori ***@***.***>
To: chromiecraft/chromiecraft ***@***.***>
Cc: O1dD0g ***@***.***>,  Author ***@***.***>
Date: Sat, 13 Nov 2021 07:04:09 -0800
Subject: Re: [chromiecraft/chromiecraft] Naga at the Zoram Strand quest (Issue #2318)
