### ISSUE TITLE
[Lower Blackrock Spire] Urok Doomhowl summoned boss NPCs has pathing issues

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2324]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

NPCs spawned before boss run to the wall or below ground for a little amount of time

![WoWScrnShot_111421_155721](https://user-images.githubusercontent.com/80590226/141687034-6617c601-f68b-4a8b-bf9f-f440ad3c2065.jpg)
![WoWScrnShot_111421_155708](https://user-images.githubusercontent.com/80590226/141687037-e8c276a8-c496-432e-b99c-5efc6b5048ee.jpg)
![WoWScrnShot_111421_155644](https://user-images.githubusercontent.com/80590226/141687038-695dcde7-677a-49c8-b674-89c18fef1ff9.jpg)
![WoWScrnShot_111421_155747](https://user-images.githubusercontent.com/80590226/141687039-d2ed067e-8bdf-415d-b39c-d396ca2f9ee1.jpg)
![WoWScrnShot_111421_155730](https://user-images.githubusercontent.com/80590226/141687041-c4bbefa5-c44b-4d84-862a-b1179b17062b.jpg)

### Expected Blizzlike Behaviour

Should spawn and not walk to the wall or through floor

### Steps to reproduce the problem

1. Get to Urok Doomhowl summoning ring
2. Use quest items combined to start encounter
3. Mobs will have bad pathing

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Don't even know. Should i reopen https://github.com/azerothcore/azerothcore-wotlk/issues/9023 or create new report.

If player not near NPCs they are running to the wall. There was big work on this event=\ 

https://user-images.githubusercontent.com/85256266/141690072-74759a05-0d2c-46f1-bf98-7ac60844c990.mp4

**Comment by Azcobu** [comment]
@Shineslippers - I'd make a new issue for this if it's still occurring - the other Urok issue is already pretty heavily commented and deals with a few other problems, so starting a new ticket seems fine. I just tried it then and it worked correctly, but perhaps that was just luck or me not doing whatever was needed to break it.

For anyone else trying, the GUID of the tribute pile object is 99791.
