### ISSUE TITLE
Warrior rage gain with damage dampening.

### ISSUE THREAD

**Issue by immersionnn** [chromiecraft/chromiecraft#2326]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Not a bug but a balance issue.
I know you have some hidden rage aura, but it's still not 100% accurate and it ends up in a pretty 'miserable' experience.
Keep in mind that i only tested it as arms so i don't know how accurate it's for prot or fury. 
Did LBRS via dungeon finder (to not get the damage dampening) and against a level 59 elite i would get about 13-15 rage for a white hit(no crit) and about 28-30 for a white crit.

After this did and UBRS run (with damage dampening ofc) and white hits(no crit) are about 10-11 rage while white crits are 20-21 rage. The difference for white hits isn't that big, but it adds up for every auto attack, but for crits it's very noticeable.
Keep in mind that the numbers might not be 100% accurate as i did limited testings and sometimes was hard to track my rage gain when tacking damage, but the difference is there.

You'll have an easier time testing in yourself with gm commands i guess, give yourself invincibility and just hit a level 59 or 60 elite without damage dampening. See your rage generation, both normal and crit hits. Do the same, but this time inside UBRS so you have damage dampening and adjust the rage aura. Dunno if you can make it 100% accurate, if you can't, just drop the damage dampening when it comes to raids and just give bosses more hp.

### Expected Blizzlike Behaviour

The rage gain should be the same.

### Source

-

### Steps to reproduce the problem

Hit mobs without damage dampening, then do UBRS or LBRS walk in and see the difference between rage gains.

### Extra Notes

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I can confirm this is being looked at, and warrior/bear rage generation is being increased in light of further testing to address this problem. The current numbers are that it's being increased to 25%, up from 15%. I'd also recommend the CC Discord's suggestions channel for further discussion of this sort of thing, as that's probably a better place for it. Hope that helps - closing this accordingly.
