### ISSUE TITLE
Quest: "The Final Tablets" (LBRS)

### ISSUE THREAD

**Issue by Josarth** [chromiecraft/chromiecraft#2327]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

https://wowgaming.altervista.org/aowow/?quest=4788

The quest item "Sixth Mosh'aru Tablet" is behind the boss Shadow Hunter Vosh'gajin in LBRS. But the tablet isn't looteable

### Expected Blizzlike Behaviour

Should be looteable

### Steps to reproduce the problem

Kill boss Shadow Hunter Vosh'gajin in LBRS
Can't loot the tablet behind her

### Extra Notes

Quest: https://wowgaming.altervista.org/aowow/?quest=4788
Boss in LBRS: https://wowgaming.altervista.org/aowow/?npc=9236
Quest Item behind the boss: https://wowgaming.altervista.org/aowow/?item=12741#contained-in-object

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)
- 

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
On local AC everything is ok. This quest has `dungeon` mark. There could be issue if you're in raid group. 
![WoWScrnShot_111421_231430](https://user-images.githubusercontent.com/85256266/141697113-d2de70d9-0473-4b48-9ce3-bfd786f556c4.jpg)
![WoWScrnShot_111421_231536](https://user-images.githubusercontent.com/85256266/141697117-4fd295e1-d3b4-415d-a6fd-7766563dd508.jpg)

**Comment by Josarth** [comment]
ahh ok.. mb sorry!
