### ISSUE TITLE
Poisoned Water quest missing

### ISSUE THREAD

**Issue by Reilith** [chromiecraft/chromiecraft#2330]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

The quest Poisoned Water (https://classic.wowhead.com/quest=6804/poisoned-water) should be given by Duke Hydraxis (NPC ID: 10849  https://classic.wowhead.com/npc=13278/duke-hydraxis) but the only quest he gives is Stormers and Rumblers (https://classic.wowhead.com/quest=6805/stormers-and-rumblers)

### Expected Blizzlike Behaviour

He should give both Poisoned Water and Stormers and Rumblers together which are prerequisites for Eye of the Emberseer (https://classic.wowhead.com/quest=6821/eye-of-the-emberseer)

### Steps to reproduce the problem

1. Go up to the duke in azshara
2. Stare at his majestic Water elemental appearance

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Orixim** [comment]
I have also notice this quest is missing. I did not open an issue because I though it was related to the reputation standing, but it seems like I guessed wrong.

**Comment by Stump876** [comment]
Hi Reilith, Thanks for the report. However it looks like this was removed in 3.0.8. https://www.wowhead.com/quest=6804/poisoned-water#comments:id=578979
https://wowwiki-archive.fandom.com/wiki/Patch_3.0.8_(undocumented_changes)
![image](https://user-images.githubusercontent.com/68164076/141716400-390ef150-e92e-419a-9518-476052ce7ea8.png)
