### ISSUE TITLE
[Battleground][Buff] Spirit Heal not reducing mana cost

### ISSUE THREAD

**Issue by Orixim** [chromiecraft/chromiecraft#2331]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

After you ressurect from Spirit Healer in a Battleground, you have a 5 seconds buff called Spirit Heal which reduces spell cost by 100%. That seems to work fine with all my skills except the Mark of the Wild / Gift of the Wild. These two skills still consume my mana.

### Expected Blizzlike Behaviour

The casting of those skills while bearing that buff should cost no mana.

### Source

From my experience using the skill while bearing the buff and from the [buff information](https://wowgaming.altervista.org/aowow/?spell=44535) and tooltip.

### Steps to reproduce the problem

0. Use a Druid character
1. Enter a Battleground
2. Die
3. Ressurect at Spirit Healer
4. Check you have the Spirit Heal buff
5. Use Mark of the Wild / Gift of the Wild
6. Check you have spend mana on its usage

### Extra Notes

I am not sure if it is related or not (but I suspect it is), but I'm using the **Glyph of the Wild**, which reduces the mana cost by 50% of both those skills. Peharps they are messing each other up? I am not able to test this without the Glyph (I would have to remove it) to see if it makes a difference.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I just tried reproducing this in WSG and AB, but in both cases the Spirit Heal buff worked correctly for both glyphed and unglyphed Mark and Gift of the Wild. 

A possible explanation for the issue may be that MotW buffs your intellect, which increases your maximum mana total. So when you cast it with Spirit Heal active, while your current mana total is unchanged, the maximum mana suddenly increases, which makes a gap appear in the mana bar. The gives the perception of the spell costing mana, when it's actually your total mana increasing. Does that explain what you're seeing, or are you actually seeing your current mana total go down when you cast the buff?

**Comment by Orixim** [comment]
That does sound like a logical explanation. I decided to give it a try and pay special attention to that and you right. The buff is so short I never had much time to examine it. Sorry for the inconvenience, I guess this can be descoped.
