### ISSUE TITLE
Herb node spawned in tree 

### ISSUE THREAD

**Issue by AbraKabastard** [chromiecraft/chromiecraft#234]
GUID: 1456

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

node spawned in tree

##### EXPECTED BLIZZLIKE BEHAVIOUR:

node not in tree

##### STEPS TO REPRODUCE THE PROBLEM:

1.  go to this node
2.  see its in tree
3. 
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@AbraKabastard as you are a contributor: https://github.com/chromiecraft/chromiecraft#report

> If you find a bug yourself, you can report it directly to the AC issue tracker. You can copy-paste this template and simply fill in the bug description.

**Comment by nolt** [comment]
Redridge mountains, confirmed

**Comment by AbraKabastard** [comment]
Duplicate of #261
Please close.
