### ISSUE TITLE
[Quest] Fiery Plate Gauntlets, Lootable Gauntlets does not give Q item.

### ISSUE THREAD

**Issue by Bardo89** [chromiecraft/chromiecraft#2343]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

This is regarding a Quest in Blackrock Spire. 

For the Quest "Fiery Plate Gauntlets" you should be able to loot the "Unfired Plate Gauntlets"  **IF** you are a blacksmith.
Currently, blacksmith or not, when you try loot Gauntles, it remains empty and it despawns after half a second. 

### Expected Blizzlike Behaviour

Only if you are a blacksmith, you should be able to look the "Unfired Plate Gauntlets".   
When you are not,  when you try to loot it, it remains empty. 

### Source

![empty](https://user-images.githubusercontent.com/94481370/142048280-92ead3fd-771d-4558-93b1-8c1644bf3dc1.png)

### Steps to reproduce the problem

1. Click Gauntlet.
2. It opens a bag like storage but remains empty.
3. Gauntlet despawns. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report, but unfortunatelly it's blizzlike. Everyone around can use object, but only player with quest able to loot quest item. Wowhead [Unfired Plate Gauntlets](https://www.wowhead.com/object=176089/unfired-plate-gauntlets#comments)
> By 84722 on 2009/05/01 (Patch 3.1.1)
Successfully looted without having the quest in my log.

> By 150927 on 2009/02/11 (Patch 3.0.9) 
If you are a blacksmith, do not loot the gauntlets until you accept the quest from the human remains, or you will not get the associated item.

![image](https://user-images.githubusercontent.com/85256266/142052645-b8d5da6c-563a-4d25-b582-1d3ed477c605.png)

Can we count this as blizzlike bug what we can fix?

**Comment by Bardo89** [comment]
I have the Quest but i am still unable to loot the "Unfired Plate Gauntlet".
![1](https://user-images.githubusercontent.com/94481370/142062919-f2f11ff8-3842-4542-86f4-564786352ffd.png)
![2](https://user-images.githubusercontent.com/94481370/142062928-44c569c3-cc8d-4143-8d8e-d2381c7a1adf.png)

**Comment by Shineslippers** [comment]
Are you in raid?

**Comment by Bardo89** [comment]
No, I just went in solo.

**Comment by Shineslippers** [comment]
Just checked it again. Can loot it.
![image](https://user-images.githubusercontent.com/85256266/142064860-bc5fabdc-64e4-4052-9de4-35ed9641bd0f.png)

**Comment by Bardo89** [comment]
I've tried dropping and looting it, didn't work.  To regain the Quest i had to go to Everlook.

**Comment by Bardo89** [comment]
ok finally after a few tries of going in and out i was able to loot it.

**Comment by Shineslippers** [comment]
Can we count pissibility to loot object without quest as blizzlike bug? We can fix it.

**Comment by realbluerabit** [comment]
I am also unable to loot the gauntlets.  I have abandoned and retaken the quest a few times, I have tried multiple times in the same  dungeon and separate dungeons.  Always empty.  Do I just keep trying or is there a trick to make them lootable?

**Comment by Shineslippers** [comment]
Is your object has glow effect?
![image](https://user-images.githubusercontent.com/85256266/142289286-e190dd73-3a74-484c-b3b5-8bc987718de5.png)

**Comment by realbluerabit** [comment]
I do not have the loot sparkles.  Is there an armor specialization requirement that isnt made clear?

**Comment by Shineslippers** [comment]
Quest doesn't have any requirements. I'm able to do it without BS at all. You need it only for pre-quest. No sparkles - no loot. Can't find any restrictions. You should have quest that's it.

**Comment by Bardo89** [comment]
> I do not have the loot sparkles. Is there an armor specialization requirement that isnt made clear?

Hi Realbluerabit, i think, before i dropped the Quest myself, the "Unfired Plate Gauntlets" did not have any sparkles. 
After i dropped the Quest and went to Everlook again to get it, i was able to loot them. 

As for armor specialization, that is not required.

**Comment by Gultask** [comment]
>Successfully looted [Fiery Plate Gauntlets](https://www.wowhead.com/?item=12812) without having the quest in my log.
Was previously bugged.([source](https://www.wowhead.com/quest=5124/fiery-plate-gauntlets#comments:id=700130))

>I'm guessing that this quest is only available to blacksmiths as the required [Unfired Plate Gauntlets](https://www.wowhead.com/item=12812) can only be looted by a blacksmith (3.3.5)
>Yep. Just tried to pick them up as my druid (ench/tailoring) and couldn't loot them. They disappeared after I clicked them.

>Post-shattering, that [object](https://www.wowhead.com/object=176089) is still lootable by blacksmiths, but there's really no point, because that [item](https://www.wowhead.com/item=12812) was only used in this quest, which is no longer obtainable. (4.2.2)

>The quest has been removed, but you can still pick up the Unfired Plate Gauntlets.(5.3.0)

From at least 3.1.1 onwards, it seems that the quest item can be looted only by blacksmiths without needing to have any quest as a pre-requisite.
