### ISSUE TITLE
General Drakkisath pull abuse to reset adds

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#2350]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Pulling [General Drakkisath](https://db.rising-gods.de/?npc=10363) in UBRS following either Feign Death from a Hunter or Shadowmelt from a Nightelf allows to reset the adds while keeping Drakkisath infight. Thus, the fight can be done without the adds involved.

This is a bug actively abused right now on Chromiecraft.

### Expected Blizzlike Behaviour

In case of Feign Death other people in the group should get aggro'ed bei Drakkisath and the adds because the pull of the dungeon/raid boss should bring every player in that dungeon/raid infight.
In case of Shadowmelt, the threat shouldnt be dropped but the person shouldnt get outfight as Drakkisaths pull should bring all players in the dungeon infight with both him and the adds

### Source

As can be seen in the following youtube video, when pulled by a different party member, also the streaming player is getting infight (see character image at the top left)
[https://youtu.be/0aBgtzK0Bnk?t=500](https://youtu.be/0aBgtzK0Bnk?t=500)

### Steps to reproduce the problem

pull drakkisath and have a 2nd person attack Drakkisath only (thus, no Threat generated at the adds e.g. by healing) and then feign death or shadowmelt

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Appreciate for the report, but this is known issue. Fix ready and will be uploaded to CC soon<sup>tm</sup> https://github.com/chromiecraft/chromiecraft/issues/2342
