### ISSUE TITLE
[Quest] Shadow Priestess Vandis buffs you a second Power Word: Fortitude after completing cauldron quests in Western Plaguelands

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2353]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Each time you return to Shadow Priestess Vandis at The Bulwark in Tirisfal after completing a cauldron quest in Western Plaguelands, Shadow Priestess Vandis buffs you with Power Word: Fortitude after completing any of the "Return to the Bulwark" quests.
If you have buffed yourself with Power Word: Fortitude, you get a second Power Word: Fortitude buff after completing the quests.
![WoWScrnShot_111821_100452](https://user-images.githubusercontent.com/62797536/142470283-40b17f06-5f66-4f44-af99-e91bffe6a8c2.jpg)

### Expected Blizzlike Behaviour

If you get buffed with Power Word: Fortitude by Shadow Priestess Vandis, your existing Power Word: Fortitude gets refreshed.

### Steps to reproduce the problem

1. Buff yourself with Power Word: Fortitude
2. Finish a "Return to the Bulwark" quest

### Extra Notes

Shadow Priestess Vandis: https://wowgaming.altervista.org/aowow/?npc=11055

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9537
