### ISSUE TITLE
RDF death bug

### ISSUE THREAD

**Issue by thom4466** [chromiecraft/chromiecraft#2358]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

If everyone dies in the RDF and someone leaves the party while corpse running you will respawn outside dungeon.

### Expected Blizzlike Behaviour

Should not ress you and should allow you to just run back into the dungeon

### Steps to reproduce the problem

1. Queue RDF
2. Wipe the group
3. Have everyone release
4. Start running back but before you event have 1 person leave group

### Extra Notes
Dont know if relevant but it happend to me in Diremaul East

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
And all in your party was released outside dungeon? Have person who leave was alive or also spirit?

**Comment by thom4466** [comment]
Dont know about all but people I ran with yes. Didnt see the guy that left the group so he might have been sent back.

**Comment by Shineslippers** [comment]
Did some tests and there is something specific:
- Leave group when was spirit
- Leave group when was alive
- Tried before leave `reset all instances` or `convert to raid`

**Comment by thom4466** [comment]
What do you mean by "there is something specific"? did you recreate? also 3rd bullet point wouldnt be possible in RDF.

**Comment by Shineslippers** [comment]
That's mean you can't just leave and reproduce this bug. Not so easy. Don't worry. This is info more for someone who will test it after me. It could be related to crossfaction or something what you didn't mentioned. I guess you able finish instance and still was in RDF group(green eye near minimap was available).
