### ISSUE TITLE
Banned?

### ISSUE THREAD

**Issue by chaossonic** [chromiecraft/chromiecraft#2359]
Hi,

Not completely sure why I was banned.

I've been experiencing stuttering which has lead me to trying different Config layouts.  The RMB has been functioning abnormally.  Trying different camera settings, mouse settings, or anything else I can try to find a cure.  If I try to adjust any graphic setting in game, it just locks up.  So I know I've been relogging trying different setups to fix what appears to be 2 different problems. 

For the most part I've given up on the RMB, there are no solutions I can find.  Updating the drivers, changing the reporting rate, and the DPI; rolling back to older drivers, and etc.

As for the general framerate, I was knee deep into isolating a fix to see if one of the Compatibility Modes might yield better results.

Tried to log in after one of my adjustments and find myself banned.  I know that I sometimes get silly and ask, "Where are my fucking tacos?"  But I only do this to add humor to the game, and do not do it to troll people.

**Comment by Shineslippers** [comment]
I'm sorry but this is place for ChromieCraft reports of bugs. If you wanna receive answer from GM you have to visit our Discord. Support channel or ticket there. I can't help you. Atleast leave character name. https://discord.gg/63qHRzny
