### ISSUE TITLE
Despawn timer too low (in some cases)

### ISSUE THREAD

**Issue by magicevil83** [chromiecraft/chromiecraft#236]
##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When playing in solo, farming leather as hunter, I can kill a pack of beasts and skin them, but it happens very few times that I don't have enough time to loot them all that some despawn with loot and unskinned leather, and this is frustrating. Many times, still  playing in world, so even in instances, it happens that corpses are un-lootable because game tell that there is loot on it that must be looted first, but there is not. This happened to me a lot on duskwood on warewolfs, still in solo. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Longest despawn timer to allow loot and skin. Maybe consider that sometimes you're death and need to run back to your corpse and a short despawn time for beasts and enemies means losing loot and resources...

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill a pack of raptors in STV
2. Wait a couple of seconds between each loot and skin
3. You'll see that last two or three cannot be looted because they just despawn faster
4. Enjoy

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@magicevil83 thanks for your report, however we need numbers. And sources.

For example:

- the current despawn time is X seconds
- the expected (blizz-like) despawn time is Y seconds (LINK_TO_A_SOURCE)

we can't just blindly change values according to what it "feels" right. Otherwise tomorrow someone will open a new bug report saying "Despawn timer too high" and we will not know what to do.

Please take some time to do some research and provide us actual numbers.

**Comment by Zoidwaffle** [comment]
The same issue was also discussed here:

https://github.com/chromiecraft/chromiecraft/issues/195

Some more info here: https://gaming.stackexchange.com/questions/78923/how-long-do-corpses-remain

In TC they use 300s, which is only mentioned as a reference, not saying it's correct. 

I also happen to think 1 minute isn't much time at all - if the link above is right, the proper numbers should be around:

```
Corpse.Decay.NORMAL    = 300
Rate.Corpse.Decay.Looted = 0.4
```

But there's no way to have a lower decay for skinnable creatures, as it seems like there should be? Perhaps this should be a feature request?

I'm also aware that a longer decay will also increase the respawn rate, which might be a nasty side-effect (which could be handled by lowering the respawn rates or perhaps another feature suggestion where some logic is rewritten so the respawn timer starts counting from death and not from decay).

Woah, did I just make up 2 feature requests? :grin:

**Comment by magicevil83** [comment]
Seems enough to me. 

300s = 5m (maybe even too much) but at the moment looted corpse get this decay:

ChromieCraft

- unlooted: 60s
- looted: 30s
- skinned: istant

Can't verify on an offy client at the moment, somebody can verify?

**Comment by Zoidwaffle** [comment]
@magicevil83 : those are the default AC values indeed.

Skinned instant is correct, I meant... if a creature can be skinned, then it should stay around for longer than a creature that can't be skinned. I remember that well from Classic where I was often skinning creatures killed by others since the corpses stayed around for a while.

**Comment by magicevil83** [comment]
![image](https://user-images.githubusercontent.com/57961114/111762026-d08d5400-88a0-11eb-8b91-5737e6fac921.png)

The problem about unlootable/unskinnable corpses remains: example 79.00/36.00 (Badlands)

**Comment by Zoidwaffle** [comment]
You are mixing issues now. The missing ability to skin should, as I understand, be solved by https://github.com/azerothcore/azerothcore-wotlk/pull/4842 and isn't related to despawning corpses.

**Comment by magicevil83** [comment]
You're right, pardon about that.

**Comment by Stifler82** [comment]
@magicevil83 


Your report is incorrect because the current MOBS Despawn is:
60 seconds looted
60 seconds unlooted
as you can see from my video test:
**Video Test:** [Despawn timer](https://youtu.be/AbXPt1v0Vdw)

**1 min is enough** to loot MOBS
The actual server rates are these:
```
#
#    Corpse.Decay.NORMAL
#    Corpse.Decay.RARE
#    Corpse.Decay.ELITE
#    Corpse.Decay.RAREELITE
#    Corpse.Decay.WORLDBOSS
#        Description: Time (in seconds) until creature corpse will decay if not looted or skinned.
#        Default:     60   - (1 Minute, Corpse.Decay.NORMAL)
#                     300  - (5 Minutes, Corpse.Decay.RARE)
#                     300  - (5 Minutes, Corpse.Decay.ELITE)
#                     300  - (5 Minutes, Corpse.Decay.RAREELITE)
#                     3600 - (1 Hour, Corpse.Decay.WORLDBOSS)

Corpse.Decay.NORMAL    = 60
Corpse.Decay.RARE      = 300
Corpse.Decay.ELITE     = 300
Corpse.Decay.RAREELITE = 300
Corpse.Decay.WORLDBOSS = 3600

#
#    Rate.Corpse.Decay.Looted
#        Description: Multiplier for Corpse.Decay.* to configure how long creature corpses stay
#                     after they have been looted.
#         Default:    0.5

Rate.Corpse.Decay.Looted = 0.5
```
