### ISSUE TITLE
[Error on level requirement] - Portal: Theramore (49360) requires level 40

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#2363]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Portal trainer at Theramore is not allowing us to get the spell Portal: Theramore until level 40.
![ 2021-11-21 at 16 07 52](https://user-images.githubusercontent.com/77953030/142763299-62b3c711-a5e7-4633-b009-33540c65b1f8.png)

### Expected Blizzlike Behaviour

Ability [Portal: Theramore](https://wotlk.evowow.com/?spell=49360) should be trainable at 35.

As mentioned on another post:
35 - Portal: Theramore / Stonard (1g 50s)
40 - Portal: Stormwind / Ironforge / Exodar / Orgimmar / Undercity / Silvermoon (1g 50s)
50 - Portal: Darnassus / Thunder Bluff (3g 20)
65 - Portal: Shattrath (15g)
74 - Portal: Dalaran (10g)

### Source

https://tbc.wowhead.com/spell=49360/portal-theramore
https://wotlk-twinhead.twinstar.cz/?spell=49360
https://wotlk.evowow.com/?spell=49360

### Steps to reproduce the problem

Get an alliance mage to lvl 35
Visit [Ysuria](https://wotlk.evowow.com/?npc=27703), Portal Trainer at Theramore Isle
Observe how she requires you to be 40 to learn it, but it should be available at 35.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9277
