### ISSUE TITLE
[NPC Spawn error] - Salt Flats Vulture (4158) - Missing on most of the map

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#2364]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The Mob Salt Flats Vulture (4158) should possible spawn in many different locations in the lower half of the Shimmering Flats in  Thousand Needles. This creature drops the Hollow Vulture Bone, item needed for [Load Lightening](https://classic.wowhead.com/quest=1176/load-lightening). We can find the other mob that drops the bones, the [Salt Flats Scavenger](https://classic.wowhead.com/npc=4154/salt-flats-scavenger) exactly where they should (on the East bones and some more in the north), but is quite scarce and takes some time for them to respawn.

When inspecting POI for quest in the map, we can clearly see different spots that match with bones and corpses from different creatures. Nevertheless, only the north spots have vultures around them. The turtle skeleton in the south, for example, doesn't have any vultures of any type around it.

East corpse with vultures:
![83268-load-lightening](https://user-images.githubusercontent.com/77953030/142770953-6cce3b8d-532d-457a-9e34-9eec9663611e.jpg)

South corpse with no vultures of any type:
![ 2021-11-21 at 19 34 26](https://user-images.githubusercontent.com/77953030/142771010-d38338a2-0346-463a-a663-59198ddc737f.png)

I have tested on different characters and at different times. It's not that vultures were dead and had yet to spawn or anything like that. They NEVER appear there, not at the turtle and not all over the place in the south part of the map. I could find a couple at the southernmost, where the basilisks and the water ponds, but for the most part the map is empty. And when killed, they spawn again on the very same spot.

### Expected Blizzlike Behaviour

According to database, this npc could spawn in many more places. Also, it makes sense that there are vultures around the bones of the turtle in south, for example.

Wowhead classic map shows possible spawning points:
![ 2021-11-21 at 19 45 28](https://user-images.githubusercontent.com/77953030/142771110-3ba438c4-4620-4330-a1ea-0c4878ca3734.png)

There should be many more of these Vultures in the area southwest and southeast of the Mirage Raceway node.

### Source

Scavenger (spawn points seem correct):
https://classic.wowhead.com/npc=4154/salt-flats-scavenger
https://wotlkdb.com/?npc=4154
![ 2021-11-21 at 19 53 13](https://user-images.githubusercontent.com/77953030/142771412-8f4bc830-c8c4-48f2-a0dc-45a03d21cdfd.png)

Vulture (mostly missing):
https://classic.wowhead.com/quest=1176/load-lightening
https://wotlkdb.com/?npc=4158
https://wotlk.evowow.com/?npc=4158
https://mmo4ever.com/wow/creature.php?id=4158
![ 2021-11-21 at 19 54 42](https://user-images.githubusercontent.com/77953030/142771467-5bf459cf-88a8-4223-b9be-aa7d70569363.png)

### Steps to reproduce the problem

Get a character to lvl 29
Take quest 1176 - Load Lightening
Inspect map and POI for the quest
Realize there are no vultures or scavengers where marked, but rather very few Scavengers and almost no vultures at all.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
I'm very sorry, I just found that there was a report on this –although not in Chromiecraft–.
Maybe they could be merged or complemented somehow.

https://github.com/azerothcore/azerothcore-wotlk/issues/4934

**Comment by Azcobu** [comment]
Thanks for the report. By mentioning the AC issue you've created a link between it and this one, so the information you've helpfully provided here will not be lost.
