### ISSUE TITLE
tribal leatherworking

### ISSUE THREAD

**Issue by zatherin** [chromiecraft/chromiecraft#2365]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

i cant go any farther in tribal leatherworking or see any training that i can do

### Expected Blizzlike Behaviour

be able to train in leatherworking

### Steps to reproduce the problem

1. go to trainer

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for report, but i don't understand your issue. Specialization trainers doesn't offer common LW recipes. If you learned all recipes from trainer there is nothing more. If you doesn't know where to get Tribal LW you ahve to visit [Caryssia Moonhunter](https://wowgaming.altervista.org/aowow/?npc=7870) and take quest there. It will open Specialization recipes.

**Comment by zatherin** [comment]
I'm not receiving any patterns to learn and it says I get feathered chest
at 250 skill and I'm at 260

**Comment by Shineslippers** [comment]
Everything is ok on my local AC. You have to be more precise. Where are your issue?
![image](https://user-images.githubusercontent.com/85256266/142816023-02826d67-6a7f-4fd2-b6af-64509013f827.png)

**Comment by zatherin** [comment]
this is all i get

**Comment by Shineslippers** [comment]
There is nothing more.

**Comment by zatherin** [comment]
i still dont have any tribal leatherworking patterns it wont let me train
them

**Comment by Shineslippers** [comment]
I'm still don't understand your issue. Is list of patterns empty or what? Once again. Make atleast screenshot. For me everything is ok.

**Comment by zatherin** [comment]
as this screenshot shows i cant even open up the training menu to learn any
recipes even though i have tribal leatherworking

**Comment by Shineslippers** [comment]
Still no screenshot. NPC should something saying to you. Is it your 1`st specialization? Have you changed it? Have you done quest for specialization?

**Comment by zatherin** [comment]
Apparently my screenshots are not going through I talk to her and all she
says is the forest tells of your coming and that's it I did all the quest
it's my first specialization it shows in my abilities page tribal
leatherworking I just don't get the training menu

**Comment by Shineslippers** [comment]
You have not enought skill to see the patterns. It have to be 250

**Comment by zatherin** [comment]
im at 265 skill

**Comment by Shineslippers** [comment]
Idk what's the deal there. I can open issue about LW requirements it should be 225 - same as quest require. But why you don't see it i have no idea atm.

**Comment by Punbearabledruidferal** [comment]
I have the same issue as Elemental Leatherworker. my skill is 260 and I have done the quests which is only opens at lvl 40 with 225 skill. 
![image](https://user-images.githubusercontent.com/95151692/143724430-1f989d11-3d72-44bf-9795-23f467bc3d7e.png)

**Comment by Punbearabledruidferal** [comment]
![image](https://user-images.githubusercontent.com/95151692/143724502-ac1025de-20c5-4585-af7c-69a41675b7df.png)

**Comment by Punbearabledruidferal** [comment]
So I did lvl my LW up to 300, but nothing happens

![image](https://user-images.githubusercontent.com/95151692/143726019-c37a1345-ac06-495e-bd72-0321a5300618.png)

**Comment by Shineslippers** [comment]
Still can not reproduce it on local AC. It may be related to CC rollback. So until next update there is could be issues with it. Let me know if after next server update issue will be still in game. Check out version of core you can find after loading:
![WoWScrnShot_112821_141731](https://user-images.githubusercontent.com/85256266/143765640-26534318-50dc-47ef-88c1-b958f022161f.jpg)

**Comment by Punbearabledruidferal** [comment]
![image](https://user-images.githubusercontent.com/95151692/143782147-c14ead6d-7b99-4e7a-9dca-5d02b9e197b6.png)

**Comment by Shineslippers** [comment]
My bad. I mean will change from 18/11/21 to higher one. Probably it will happen on wednesday

**Comment by Punbearabledruidferal** [comment]
Yeah, dont forget to do this on both Horde and Alliance Elemental LW, Tribal LW and the third one which I didnt remember

**Comment by Shineslippers** [comment]
@zatherin @Punbearabledruidferal Issue resolved after update?

**Comment by Shineslippers** [comment]
Found issue.
