### ISSUE TITLE
skill requirement for mining truesilver is too low

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#2366]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Able to mine truesilver with mining skill at 205

### Expected Blizzlike Behaviour

Requirement should be 230

### Source

Check comments on https://classic.wowhead.com/object=2047/truesilver-deposit#comments

Also, talk to any mining trainer in the game to see that it takes 230 to learn to smelt truesilver, and the skill to mine should be the same.

### Steps to reproduce the problem

get a char, set mining skill to 204; find a truesilver deposit; try to mine; get error msg saying need skill of 205; set skill to 205, mine, go to a trainer to see that unable to learn smelt truesilver until 230.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by thom4466** [comment]
It was changed to 205 in Wrath, dont follow what is stated on classic wowhead as it was very little to do with Wrath.

**Comment by Shineslippers** [comment]
Thank for the report, but as said above mining requirement changed in Wrath. For other deposits too, Can't find patch where it stated. Live version of wowhead page anyway has several comments like [this](https://www.wowhead.com/object=2047/truesilver-deposit#comments:id=935587):
> By seitori on 2010/01/03 (Patch 3.3.0)
Not sure exactly when this happened as it isn't in patch notes (it wasn't before 3.0), but the requirement to mine this has been lowered to a much more reasonable 205. Smelting still requires 230.
