### ISSUE TITLE
Redemption quest for my dwarf paladin

### ISSUE THREAD

**Issue by Luneburger** [chromiecraft/chromiecraft#2367]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Wouldnt let me complete Redemption Quest for my dwarf (the name is Bolin). I had to abandon the quest and it wouldn't let me pick it back up again 

### Expected Blizzlike Behaviour

the questline should work

### Steps to reproduce the problem

the dwarf paladin trainers

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04
Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. There is exist one issue with this quest line. Need to know which quest exactly you abandon. Who gave it to you? Tiza Battleforge?

**Comment by Luneburger** [comment]
hey, it's the quest where I got the book, but it wouldn't let me start the next quest. You get the book from Tiza. It's the actual book that seems to be broken, when you try and use it to accept the quest - it just says "you do not meet the requirements to do this".

I tried contacting a GM but they said to report it here. thanks!

**Comment by Shineslippers** [comment]
Good to know it's an old issue. Ways to solve issue:
1. Book don't deleted. Fix is ready, but not uploaded to CC server. You can just wait  for update of server and book let you accept quest.
2. Book don't deleted. Contact to GM again. They aware about this issue atleast some of them. There is need to remove quests 2997, 2999 and 3000. It will let you accept quest from book.
3. Book is deleted. Step 2 and also need remove quest 1645 to get possibility obtain book again from Tiza. In this case you also have to take quest from trainer that send you to Tiza, but not turn in it. take quest for book and abandon `sending to Tiza` quest.

If you will contact to a GM you can link to them this comment.
