### ISSUE TITLE
Mark of the Dragon Lord ring's buff doesn't give mana regen

### ISSUE THREAD

**Issue by Lanakh187** [chromiecraft/chromiecraft#2368]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

After using Mark of the Dragon Lord item, the 30 Minutes buff doesn't give the mana regen.
https://wowgaming.altervista.org/aowow/?item=13143
https://wowgaming.altervista.org/aowow/?spell=17252

### Expected Blizzlike Behaviour

The 22 mana per 5 sec should be shown on character panel.
https://wowgaming.altervista.org/aowow/?spell=17252

### Source

![WoWScrnShot_112221_113930](https://user-images.githubusercontent.com/79023522/142847265-ff57af6c-8a22-4f45-ab85-ab54e10f31d3.jpg)
![WoWScrnShot_112221_114001](https://user-images.githubusercontent.com/79023522/142847272-790c3c10-9f6d-4a58-b23e-251dbb6a4ff3.jpg)
![WoWScrnShot_112221_113956](https://user-images.githubusercontent.com/79023522/142847274-cf1e1230-676f-402d-a438-4ef27b80a721.jpg)
![WoWScrnShot_112221_113944](https://user-images.githubusercontent.com/79023522/142847275-5ce95483-eb26-4520-ad54-5ba8eeed90eb.jpg)
![WoWScrnShot_112221_113944](https://user-images.githubusercontent.com/79023522/142847290-2f8bfb4b-4e2e-436e-a84a-f0a331f1803b.jpg)
![WoWScrnShot_112221_113930](https://user-images.githubusercontent.com/79023522/142847294-9ef0c0a8-f0da-4227-a1b0-d7fc9c3512b1.jpg)
![WoWScrnShot_112221_114001](https://user-images.githubusercontent.com/79023522/142847297-457f135b-4ceb-4df5-b0c3-0219c52fd17a.jpg)
![WoWScrnShot_112221_113956](https://user-images.githubusercontent.com/79023522/142847299-5eaca633-97bd-4ac6-87cb-5b46fd0cfe3a.jpg)
![WoWScrnShot_112221_113956](https://user-images.githubusercontent.com/79023522/142847312-87e05729-11b6-4a78-97e3-e5abbc619148.jpg)
![WoWScrnShot_112221_113944](https://user-images.githubusercontent.com/79023522/142847317-a3212a70-fa1a-4460-9dd2-ed832b48dee5.jpg)
![WoWScrnShot_112221_113930](https://user-images.githubusercontent.com/79023522/142847321-5b22ce01-62d1-402a-9eef-eff45e4ce37d.jpg)
![WoWScrnShot_112221_114001](https://user-images.githubusercontent.com/79023522/142847323-986bed48-7c6f-423a-92d2-956a8f9756b3.jpg)
![WoWScrnShot_112221_114001](https://user-images.githubusercontent.com/79023522/142847328-dc7623db-7fd5-41f3-8e61-7b72b687ff79.jpg)
![WoWScrnShot_112221_113956](https://user-images.githubusercontent.com/79023522/142847332-7763a795-f0a6-4a77-a5cb-7157cfac2ac7.jpg)
![WoWScrnShot_112221_113944](https://user-images.githubusercontent.com/79023522/142847333-649c4c20-6457-4cf1-8a1e-f1dfc156de47.jpg)
![WoWScrnShot_112221_113930](https://user-images.githubusercontent.com/79023522/142847334-e2cd85ce-b28a-47bc-a67b-e5a8912a28a4.jpg)

### Steps to reproduce the problem

Obtain the ring
Put it on
Check your mana per 5 sec
Use the ring
Check if buff is up
Check your mana regen again

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=17252

" Apply Aura: Periodically Give Power (Mana)
Value: 22
Interval: 5 seconds "

" Apply Aura: Mod Absorb School Damage (Physical, Holy, Fire, Nature, Frost, Shadow, Arcane)
Value: 500 "

![motdl](https://user-images.githubusercontent.com/79023522/142848183-78e819b5-56e9-46cc-ae88-2dc5098b029c.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. The mana regen is actually working, at least according to the combat log:

![WoWScrnShot_112221_224411](https://user-images.githubusercontent.com/81782124/142860183-d1a776bf-4bfc-4ebf-946c-ad489caec4d3.jpg)

However, it doesn't show in the character sheet for the reasons Nyeriah explained above, rather than because of an error. Closing this issue accordingly.
