### ISSUE TITLE
Pet turned into bones in Scholomance

### ISSUE THREAD

**Issue by kirkj89** [chromiecraft/chromiecraft#2372]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Pet was turned into pile of bones in Scholomance. Pet was able to attack and use all abilities but appeared as a pile of bones.

### Expected Blizzlike Behaviour

Not appear as a pile of bones.

### Source

![WoWScrnShot_112221_161447](https://user-images.githubusercontent.com/46739628/142951121-371dc57c-bb24-483b-8f72-efafaefde89e.jpg)
![WoWScrnShot_112221_161447](https://user-images.githubusercontent.com/46739628/142951135-ad22c2b5-2833-41ed-a8fc-9b2e94f09d1d.jpg)

### Steps to reproduce the problem

Go into scholomance with a hunter and pet (I had a wolf). Pet appeared as bones for seemingly no reason

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
I'm not sure about this. Found video https://www.youtube.com/watch?v=t-r8sdvUg8I. Able to repeat. Using Eyes of the Beast in one of scholomance's room. I'm not strong in chinees idk what is deal there.

**Comment by Azcobu** [comment]
I don't think it's Blizzlike, as the Youtube video you found says it was shot on Warmane. Didn't find any other sources referencing it either, although since we'd fix it in any case, Blizz-like bug or not, it's probably a moot point.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9712
