### ISSUE TITLE
[Dungeon] You can glitch out in LBRS endboss room

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2375]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

![WoWScrnShot_112221_194741](https://user-images.githubusercontent.com/62797536/143000233-cfda0e4a-211a-4275-8abf-4997cd3cea80.jpg)
A warrior can glitch out when charging over the marked edge in the picture. He falls out of the world and dies. This yesterday happened two times to our tank.

### Expected Blizzlike Behaviour

You do not glitch through that edge when charging over it.

### Steps to reproduce the problem

1. Be a warrior.
2. Go to LBRS endboss room.
3. Charge a enemy over that marked edge.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
@ishidinho  Am i doing something wrong?

https://user-images.githubusercontent.com/85256266/143005464-e37a66a0-127b-475d-81e7-495879018771.mp4

**Comment by ishidinho** [comment]
@Shineslippers 

Hmm, your first charge on the Chromatic Dragonspawn is close to one charge that glitched our tank. Strange that this happened two times.

Our tank was a male Orc warrior. Maybe you can test it with a male Orc model just to be sure that this is not related to different character models.

**Comment by Azcobu** [comment]
I've just tried this with a male orc warrior, and although I didn't ever fall through the world, one of the charges gave me a brief glimpse through the geometry for an instant, so I have no doubt this is possible.

https://user-images.githubusercontent.com/81782124/143218775-c1c8f7ac-f4cc-4993-8048-ad7d30a8daa9.mp4

However, we do already have an open issue for warrior/druid charges clipping through the world in https://github.com/azerothcore/azerothcore-wotlk/issues/6232, so will close this as a known issue while noting the location for testing. There's actually a fix for this issue in active development too, looks like it's due to be ported across to our PTR fairly shortly.
