### ISSUE TITLE
Alcohol stamina bonuses remove Food stamina bonuses and vice versa

### ISSUE THREAD

**Issue by CyberneticCC** [chromiecraft/chromiecraft#238]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [x] 1-19
- [x] 20-29
- [x] 30-39

##### CURRENT BEHAVIOUR:

[Rumsey Rum Light](https://classic.wowhead.com/item=20709/rumsey-rum-light)
[Rumsey Rum](https://classic.wowhead.com/item=17048/rumsey-rum)
[Rumsey Rum Black Label](https://classic.wowhead.com/item=21151/rumsey-rum-black-label)
doesn't stack with any well fed bonuses for example
[Lean Wolf Steak](https://classic.wowhead.com/item=12209/lean-wolf-steak)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Well fed stats should stack with alcohol (stamina) stats.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get any of the above drinks and food that gives well fed bonus.
2. Use any of them first and then use the other.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by dole555** [comment]
Working as intended.

In patch 2.1 all kinds of drinks that gave you +Stamina stopped stacking with the "Well Fed" buff that's gotten from food items.
" [Rumsey Rum], [Rumsey Rum Light], [Rumsey Rum Dark], [Rumsey Rum Black Label], [Halaani Whiskey], [Gordok Green Grog], [Raptor Punch], [Stormstout], [Trogg Ale], and [Keg of Thunderbrew Lager]: The stat bonuses from these drinks no longer stacks with stamina bonuses from other foods." from https://wow.gamepedia.com/Patch_2.1.0

**Comment by FrancescoBorzi** [comment]
> Working as intended.
> 
> In patch 2.1 all kinds of drinks that gave you +Stamina stopped stacking with the "Well Fed" buff that's gotten from food items.
> " [Rumsey Rum], [Rumsey Rum Light], [Rumsey Rum Dark], [Rumsey Rum Black Label], [Halaani Whiskey], [Gordok Green Grog], [Raptor Punch], [Stormstout], [Trogg Ale], and [Keg of Thunderbrew Lager]: The stat bonuses from these drinks no longer stacks with stamina bonuses from other foods." from https://wow.gamepedia.com/Patch_2.1.0

thanks @dole555 for your feedback. Also thanks @CyberneticCC for your effort.
