### ISSUE TITLE
[WSG] You can fear enemies inside line-of-sight objects

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2381]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

![WoWScrnShot_112321_155235](https://user-images.githubusercontent.com/62797536/143048037-ab797f5d-b7cb-4135-b116-eca76d16f6df.jpg)

In Warsong Gulch battleground you can fear an enemy inside the line-of-sight object in the middle of the battleground.

### Expected Blizzlike Behaviour

It must not be possible to fear an enemy inside the line-of-sight object in the middle of the Warsong Gulch battleground.

### Steps to reproduce the problem

1. Join WSG battleground
2. Fear an enemy next to the line-of-sight object in the middle of the battleground

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, I haven't been able to replicate it yet. I tried with a lock rather than a spriest, but don't think that would make any difference.

https://user-images.githubusercontent.com/81782124/143226542-fffb39a7-4af6-4d4f-80d5-26933dd09388.mp4

We've had issues like this before - see https://github.com/azerothcore/azerothcore-wotlk/issues/5980 and closed issue https://github.com/azerothcore/azerothcore-wotlk/issues/4769 - so that along with your screenshot means I'll keep trying. Did this happen just the once, or have you seen it multiple times? Has anyone else noticed this behaviour?

**Comment by ishidinho** [comment]
If I remember correctly, my enemy was trying to hide there. He/she stood in some kind of corner.
Sorry, should have saying that.

![image](https://user-images.githubusercontent.com/62797536/143232395-6b624879-2536-46e1-aa01-0ec9983db399.png)

**Comment by Azcobu** [comment]
That did the trick, cheers.
