### ISSUE TITLE
Dimensional Ripper - Everlook not working

### ISSUE THREAD

**Issue by abcjinzhu** [chromiecraft/chromiecraft#2383]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Dimensional Ripper - Everlook not working. I cant click on it, it always says "this item cannot be equipped"

### Expected Blizzlike Behaviour

Should teleport me to everlook when i click on it in my bag?

### Steps to reproduce the problem

click the item and check?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

MAC

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. On loca AC everything is working. `Right click` on item to use it. Try to do it without addons. 
![WoWScrnShot_112321_214325](https://user-images.githubusercontent.com/85256266/143085156-4072feef-564f-43f6-81b1-c2f70fb2751d.jpg)

**Comment by cachocarne** [comment]
I have the same issue with the Transporter to Gadgeztan. I am gnomish Engineer and I got the recipe. Crafted it but I cannot use it. When I click on it, it tries to equip it as if it was gear. Of course, I get the "this item cannot be equipped" message. It will not "use" it.
![ 2021-11-29 at 13 48 56](https://user-images.githubusercontent.com/77953030/143854700-cc2791f3-85d9-4367-a111-67d1918fe3e2.png)

**Comment by Shineslippers** [comment]
@cachocarne let wait for CC server update. When core will changed from 18/11 to something else. Hope this wednesday

**Comment by Orixim** [comment]
I am a gnomish engineer as well and so far I had no trouble using the teleporter. I'm also a druid and I've been using it in cat form. It works just fine. I get the "Evil Twin" debuff and all.

**Comment by Shineslippers** [comment]
@cachocarne is issue with teleport resolved after update?

**Comment by cachocarne** [comment]
No, bug still present. I deleted cache several times since then, tried removing all addons. Item is still unbound in my bag, it won't let me use it. It keeps on saying "item cannot be equipped" and if I type /use Ultrasafe Transporter: Gatgetzan" it tells me "You must equip that item to use it"
![ 2022-02-11 at 14 05 59](https://user-images.githubusercontent.com/77953030/153605533-f0c48a4c-3444-4a9a-ad55-5b91833b1e9f.png)
![ 2022-02-11 at 12 41 30](https://user-images.githubusercontent.com/77953030/153605554-9dfa9df4-4e3b-404d-b73f-99db4bc341f4.png)

**Comment by Gultask** [comment]
@abcjinzhu cachocarne was able to fix their issue by updating their game client with the one provided by the CC website. Did you try that as well?

**Comment by cachocarne** [comment]
Actually just the executable file, no need to download again the MPQs

**Comment by Rorschach91** [comment]
This issue is in waiting for more feedback for 3 years.
I think that it can be closed at this point.
It can be re-opened if needed.
