### ISSUE TITLE
[Quest] Cannot finish "Wanted - Deathclasp, Terror of the Sands" / NPC Vish Kozus missing

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2388]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

You cannot finish the quest "Wanted - Deathclasp, Terror of the Sands" because NPC Vish Kozus in Cenarion Hold is missing.

![WoWScrnShot_112421_114018](https://user-images.githubusercontent.com/62797536/143248714-1b4fc5c5-b84f-4f1d-8f26-d4c0160de773.jpg)

Notes:
* Quest text says to meet Vish Kozus in at the top of the Canarion Hold Watchtower. No NPC is there.
* No quest marker on mini map.
* You cannot find NPC with `/tar Vish Kozus`.

### Expected Blizzlike Behaviour

* You should be able to finish the quest.
* Vish Kozus is at the top of the Canarion Hold Watchtower.

### Source

Quest: https://wowgaming.altervista.org/aowow/?quest=8283
Vish Kozus: https://wowgaming.altervista.org/aowow/?npc=15182

### Steps to reproduce the problem

1. Accept quest "Wanted - Deathclasp, Terror of the Sands".
2. Get the required quest item.
3. Try to finish quest at Cenarion Hold .

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thanks for the report. These NPCs have been deliberately removed for the time being - see https://github.com/chromiecraft/chromiecraft/issues/1952. I believe (though can't confirm) that as server progression continues they will eventually be restored.
