### ISSUE TITLE
Requeueing for RDF mid-dungeon after people have left doesn't match you with others queing 

### ISSUE THREAD

**Issue by kbloss90** [chromiecraft/chromiecraft#2395]
what the title says. I was in an rdf and two bosses in, two people left, and we attempted to search for  replacements. I messaged a friend that wasnt in the group to queue for rdf and he did and he says the queue popped but that the three roles that were in the dungeon had declined the queue but on my end all I heard was the queue popping noise but no one joining and got a message that said "internal LFG failed"

**Comment by j-hdt** [comment]
1) issue here is people are not properly removed - thus the dungeon is full with 5 people causing the error
2) close your ticket and use the form instead of overwriting it

**Comment by Shineslippers** [comment]
Thank you for the report i guess we finally found the issue.
