### ISSUE TITLE
Quest: Going, Going, Guano! has wrong Quest Tracker Location

### ISSUE THREAD

**Issue by Rittmeister39** [chromiecraft/chromiecraft#240]
##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

The Questlocation is according to the Text: Razorfen Kraul in Zone Durotar (south), instead the Tracker points to some weird location of a Spidernest in western Tirisfall Glades, or even further West. Since I am a total WOW newb, I was searching the Web for wtf I should do. It is totally confusing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I picked up Quest in Zone The Barrens at Crossroads from the Apothecary guy. after I was sent there, probably for another quest.
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nolt** [comment]
Confirmed, default quest tracker shows quest at non accessible area.
![Zrzut ekranu z 2021-03-22 23-34-47](https://user-images.githubusercontent.com/6367933/112066798-4d515400-8b67-11eb-8fa6-f3d408dc8f6c.png)

**Comment by Stifler82** [comment]
Fixed!
-
https://user-images.githubusercontent.com/1884642/119477488-e73fa380-bd46-11eb-9270-9f50bad6ec14.mp4
