### ISSUE TITLE
Buff/debuff and flag visibility in bg isn't constant [battleground] [phase system?]

### ISSUE THREAD

**Issue by Lessarcy** [chromiecraft/chromiecraft#2403]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Noted inside warsong gulch, but apparently it affects players in istance too
It happens casually and, apparently without any cause, that you can't see any buff/debuff on ally and enemy players.
This affect the graphical effect on the characters, as an example the flag carrier appears without the flag and the ally rogue in stealth appear without the 'transparent/spectral' effect.
Also some buff/debuff can persist and you see a character with mounted-ground run animation or someone alive but with death debuff and death effect on.
This isn't a client side problem, infact seems casual, like a problem on sincronization of auras ( i don't know exactly).
Also appears to affect players out bg too
I have some suspect that is connected to the phase system of players

### Expected Blizzlike Behaviour

Just dispaly buff/debuff and effect correctly

### Steps to reproduce the problem

Join and play some bgs

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank for the report. It's issue not with server or something, but with crossfaction module for BG.

**Comment by Lessarcy** [comment]
> Thank for the report. It's issue not with server or something, but with crossfaction module for BG.

Some players report this problem in df.
I had problems to see buff in Stormwind (after a bg)

**Comment by Shineslippers** [comment]
DF is also crossfaction. Can you explain a bit more about `buff` you mentioned.

**Comment by Lessarcy** [comment]
> DF is also crossfaction. Can you explain a bit more about `buff in stormwind` you mentioned.

Sure, 
I think that was some sort of delay of cossfaction mechanism, anyway i cannot seen the mount buff, warlock whit felguard had no buff on, and some ppl had some buff and debuff whit residual duration permanently locked at 0

This thing of permanent duaration locked at 0 is also common in bg

**Comment by Lessarcy** [comment]
> > DF is also crossfaction. Can you explain a bit more about `buff in stormwind` you mentioned.
> 
> Sure, I think that was some sort of delay of cossfaction mechanism, anyway i cannot seen the mount buff, warlock whit felguard had no buff on, and some ppl had some buff and debuff whit residual duration permanently locked at 0
> 
> This thing of permanent duaration locked at 0 is also common in bg

Only now i realized that could be the case that the players encontered at storm with buff debuff bugged could have been some player that was playing my same bg
