### ISSUE TITLE
Prowl CD

### ISSUE THREAD

**Issue by Shpageti** [chromiecraft/chromiecraft#2405]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Under some circumstances Prowl triggers its cooldown upon entering in stealth

### Expected Blizzlike Behaviour

cooldown should always and only trigger upon breaking/leaving stealth(prowl aura)

### Steps to reproduce the problem

while in cat form this is kinda tricky, as it looks like this sometimes works as it should, but many times it just doesnt.
however it will always show up while shifting from another form into a cat, followed by entering stealth. >this is the moment when the cooldown strats, when it should be upon losing Prowl aura.

as im sure you understand, this is critical to playing druids efficiently, especially in pvp, but its huge in pve too. pls fix asap <3

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. You have clarify stepps to reproduce. I can not repeat it on local AC.
Seems `always show up while shifting from another form into a cat, followed by entering stealth` doesn't work.

https://user-images.githubusercontent.com/85256266/143618095-057884cf-f818-44b0-9cec-5a655af3eed5.mp4

**Comment by Shpageti** [comment]
yes it is very tricky to reproduce it on demand. it seems like sometimes it works as it should and other times it doesnt. i rly dont get it either.
i thought it will always go wrong if you shift in cat and enter stealth, as that was the case when i tested it last time. 
but now it doesnt seems so. it appears to be completely random, which further makes things worse.
when i try to reproduce it, at first it worked as it should but then i killed some stuff, done some shifting and it went bad again triggering cd upon entering stealth.
on second thought could it be that my shift/prowl macros are messing with this? although they were tested elsewhere and worked properly.

**Comment by Shpageti** [comment]
from further testing(messing with my macros) it looks like the problem arises when stealth is being spammed immediately after entering cat form. something that a macro would do.
so in order to replicate could i ask you to try the following macro and put it on the mouse scroll! 
as this will allow you to spam it real fast.
also pls be patient as the problem may or may not show up right away. usually it takes some 
fiddling before it pops up. 

/use [form:0/1/2/4]!Cat Form
/cast !Prowl

**Comment by Shineslippers** [comment]
It's visual bug. Not affecting actual CD. Not sure is it client side bug or server

https://user-images.githubusercontent.com/85256266/143677848-c78e82b2-cb3a-4161-883b-243fb979c891.mp4

.

**Comment by Shpageti** [comment]
you're right! it is a visual bug. however it is very inconvenient, as it totally messes with my perception of possibilities. can we hope for a possible fix?

**Comment by Shineslippers** [comment]
I asked devs. If it's client side bug we can't do nothing. You will see update on this report when situation will be clarified

**Comment by Gultask** [comment]
Bug still exists, not only on druids but on rogues too. I've found it easiest to replicate by spam-clicking the stealth button.

**Comment by Salehyn** [comment]
An important detail is missing here: is this a visual issue or is the spell cooldown really ticking after you entered stealth/prowl? Does it allow you to exit stealth without triggering the cooldown on exit again, and if so, you are able to re-enter stealth/prowl within 1-2seconds of exiting it?

**Comment by FrancescoBorzi** [comment]
> Bug still exists, not only on druids but on rogues too. I've found it easiest to replicate by spam-clicking the stealth button.

can @Gultask or @Shineslippers or anyone else who was able to reproduce it link to to AC?

**Comment by TheSCREWEDSoftware** [comment]
> > Bug still exists, not only on druids but on rogues too. I've found it easiest to replicate by spam-clicking the stealth button.
> 
> can @Gultask or @Shineslippers or anyone else who was able to reproduce it link to to AC?

@FrancescoBorzi from what i understand it's a client visual bug don't think is much on our end i think

**Comment by heyitsbench** [comment]
I doubt this is a client bug myself.

**Comment by Cythisiax** [comment]
Attempted to replicate this for a little bit, but was unable to. Also attempted using PTR GM commands to force it, and wasn't able to have it enter the CD as prowl was already engaged.

https://streamable.com/hzuyto
