### ISSUE TITLE
Warsong Scout Update

### ISSUE THREAD

**Issue by rudydejager** [chromiecraft/chromiecraft#2406]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

- [ ] 40-49
- [ ] 50-59

### Current Behaviour

https://wowgaming.altervista.org/aowow/?quest=6547

The quest NPC near Splintertree Post still has a question mark and is still clickable after handing in the que
![Warsong Scout Update](https://user-images.githubusercontent.com/25206167/143596174-c110bda4-0779-41b7-b502-b392fd18fe78.png)
st
![Warsong Runner Update](https://user-images.githubusercontent.com/25206167/143597097-99a97f02-4c32-4c39-beb1-6eafeb904102.png)

### Expected Blizzlike Behaviour

After Completing the quest the NPC should not be able to open the quest when clicking on it

### Steps to reproduce the problem

Complete the quest and go to Warsong Scout near Splintertree post
she will still have a question mark and be clickable 
(i have not gone to the other 2 NPC from the quest) 
*edit* The Warsong Runner also still have the quest but with an exclamation mark 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank for the report. It's blizzlike behavior and those quests are marked as repetable. Anyway you can't do it again by mistake because quest item is `unique`. It doesn't let you have one more. Wowhead [Warsong Outrider Update](https://www.wowhead.com/quest=6545/warsong-runner-update#comments:id=948899)
> By Jerakth on 2010/01/16 (Patch 3.3.0)
All of the report quest turn ins are considered repeatable in case you abandon the Warsong Reports Quest http://www.wowhead.com/?quest=6543. You cannot complete them so just exclude them from the quest list. They are also uncounted for Loremaster because of this.
