### ISSUE TITLE
Aspect of cheetah, pack, druid talent feral swiftness

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#2414]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Aspect of cheetah, aspect of pack (group speed up), and druid talent feral swiftness does not affect walking speed.

### Expected Blizzlike Behaviour

No where in the tooltip suggests that these three abilities only work for running, not walking. A quick Google search returns no results suggesting they should not affect walking. So, my best guess is this is a bug. Let me know if they are intended to work like this.

I'm not sure whether they should affect swimming speed. Did not test either.

### Steps to reproduce the problem

Get a hunter, walk with aspect of cheetah on and off, see no change in speed. Similarly test aspect of pack, see no change in speed. Get a druid with feral swiftness talent, walk in human and cat forms, see no difference in speed. Possibly find a player or NPC who is known to walk in normal speed. Then walk with him/her/it for the test, to make the (lack of) speed difference more evident.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment]
its not supposed to affect walking speed or swimming speed only running speed

**Comment by Shineslippers** [comment]
Thank you for the report. In spell descriptions you can see that `Apply Aura: Increase **_Run_** Speed %`. It's specified there. In settings you can toggle run/walk. That's lead to conclusion Blizzard did it in a purpose.
![WoWScrnShot_112821_170923](https://user-images.githubusercontent.com/85256266/143771407-688d99f0-4493-479a-8aa1-bee5da9e9425.jpg)
.

**Comment by discorder0** [comment]
@Shineslippers When I said “no where in the tooltips” I was referring to the ability description in the game. Anyway, thank you for handling this report.

**Comment by Shineslippers** [comment]
@discorder0 Sure, i understand. In game is enought not clear descriptions. I'm just pointed to DataBase where you can read what ability gives. And same effect ability has on wowhead for example.

**Comment by discorder0** [comment]
OK. Thank you.
