### ISSUE TITLE
They're Alive! Maybe... quest in Bloodmyst Isle does not register freed Expedition Researches if a pet "kills" the cocoon.

### ISSUE THREAD

**Issue by CMHWoody** [chromiecraft/chromiecraft#2428]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

https://wotlkdb.com/?quest=9670

As a hunter, if I send my pet to attack the cocoons that hold the Expedition Researchers, if the pet "breaks" the cocoon and an Expedition Research appears, it will not count towards quest progress.

### Expected Blizzlike Behaviour

I would expect that quest progress based off damage to an in-game object should register for the character even for the pets of classes with pets.

### Source

I'm not clear what a "Source" is in this context.  Apologize for not providing this, though with clarification, I'd be perfectly willing to provide this for future bugs.

### Steps to reproduce the problem

1. Teleport to Researcher Cornelius in Bloodmyst Isle.  (https://wotlkdb.com/?npc=17686).
2. Begin quest as Hunter class with a pet.
3. Send pet to attack nearby cocoons and when a researcher appears, after the pet has broken the cocoon, progress is not registered on the quest.
4. Now break a cocoon with ranged attack by your main character and quest progresses normally.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Heitortadeu** [comment]
This quest doesn't start, it's received, but it doesn't leave the npc. Apparently this is a bug!
