### ISSUE TITLE
Hand of Justice doesn't proc from spells that use a melee weapon.

### ISSUE THREAD

**Issue by immersionnn** [chromiecraft/chromiecraft#2433]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

https://imgur.com/a/zrtGUGP

You can see from the pics that i posted that it doesn't proc if you just spam crusader strike without auto attacking. Only tested on paladin, feel free to test on warriors and rogues too. If you think it's just rng because i got only 2 procs autoattacking, it's not the first time i spammed crusader to see if it procs.

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=6O6dcPX_IPA

This is on classic. Only MH weapon is equipped and you can clearly see the HoJ animation after the first sinister strike and a white hit right after.

### Source

See video above.

### Steps to reproduce the problem

1. Just auto attack and you'll see the trinket proccing.
2. Make a stopattack macro for an ability (/cast crusader strike /stopattack) so you don't auto attack. You'll see the trinket not proccing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by jeskej** [comment]
I tested this on my shaman and it does not proc off windfury, stormstrike, or lava lash, it appears to only proc off white hits.

**Comment by Brylezor** [comment]
Can confirm, this issue still persists with one of the more iconic trinket in the classic era :S
