### ISSUE TITLE
AOE farming no loot

### ISSUE THREAD

**Issue by Awkakelen** [chromiecraft/chromiecraft#244]
##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When I try to aoe farm from +5 mobs almost no mob give me any loot, it's strange because majority of farmed mobs by me are humanoids and they should have even cash

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should have normal loot tables despite of farming them one by one or farming them AOE style

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a 29 mage
2. aoe cleave one spot (i.e. Roland's Doom at Duskwood)
3. see that you have no loot at all, only from like 1 or 2 mobs
4. cry because it should have dropped more

##### EXTRA NOTES:

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
It's not just AOE farming, Killing mobs 1 by 1 also frequently drop no loot. I suspect that if mobs don't drop any item and just have money, they are unlootable, because every single mob that can be looted has something else in the loot besides cash. I don't remember I ever looted a mob that droped copper/silver only.

**Comment by Stifler82** [comment]
This report is impossible, for the simple fact that a Fix (which was needed for another type of issue) has been merged since last week that forces mobs to loot, and it works because it has been multiple tested.
