### ISSUE TITLE
(AGGRO/Threat bug)"Glyph of sunder armor" interaction with "Devastate" 

### ISSUE THREAD

**Issue by rutter28** [chromiecraft/chromiecraft#2441]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
**with the glyph of sunder armor**
When youu apply "Devastate" in your first objetive, the second dont get **ANY AGRRO/THREAT.** , Even after applying the 5 stacks.
With the help of Omen :

**With "DEVASTATE"**--------------------------1test  ------- 2test

First objetive with 5 stacks: ----------------**<7.6k>** --  **<5,8k>**
Second objetive with also 5 stacks:--------**<575>**  --  **<667>** 
**<1>**
![be6fedbf-d860-408a-8dad-5f458a304554 (1)](https://user-images.githubusercontent.com/87255892/144095101-6e0f240d-28ef-4ad1-835f-ea58e24a6abf.jpg)
![caddbb9c-5d96-46e1-ad84-4fcc522ffb95](https://user-images.githubusercontent.com/87255892/144095134-6ba4aafe-e19b-4245-806e-a6e46f9d5206.jpg)
**<2>**
![fb19c13d-feb6-4d0d-b07f-e2a0f097b702](https://user-images.githubusercontent.com/87255892/144095566-c8bd800b-2487-4c35-bb94-d1be5eadd2c7.jpg)
![919cf78c-622d-4af7-bc58-31568daf8d41](https://user-images.githubusercontent.com/87255892/144095595-4738d528-2948-4753-98fe-bbe5320aaa35.jpg)

(since sunder doesn't affect at all the agro of the second objetive, the agro scale by my "Throns" of "Damage Shield" warrior talent, so its not proportional to the first objetive agro)

**With "SUNDER ARMOR"**-------------------1test ---------- 2test
                                                                            
First objetive with 5 stacks:----------------- **<5.3k>** -- **<9,0k>**
Second objetive with also 5 stacks:-------- **<2.5k>**  -- **<4,6k>**
**<1>**
![58b7c6f8-5379-428c-a050-2dccbe58cee0](https://user-images.githubusercontent.com/87255892/144096103-2d6f55fd-48e4-4704-b26d-f42a0d81139c.jpg)
![32f80270-a15d-47ff-b1be-b792867aecfd](https://user-images.githubusercontent.com/87255892/144096157-535166a0-3eef-4230-b984-89f6b92bd3fc.jpg)

**<2>**
![f0d766c1-6081-499d-97b9-108a5b7ed73d](https://user-images.githubusercontent.com/87255892/144095817-00975c64-8737-4d93-8b14-f3c99a85196f.jpg)
![2aef85de-8596-4d77-9b1f-8bff5eaf86ba](https://user-images.githubusercontent.com/87255892/144095832-d5f51060-df38-4791-9681-75b0142f0ca2.jpg)

PD: This is NOT the previus bug that got "Glyph of sunder armor" with "Devastate" (The one when you use "Devastate" and the second target just get 1 apply of Sunder Armor) (since it was already fixed)
PD2: pls fix it , since warriors are bullied for dont holding agro in big packs :(

 - with love , by Iamnotbald 

### Expected Blizzlike Behaviour

"Devastate" with "Glyph of sunder armor" should generate agro in both targets not just one of them.

### Source

trust me bro

### Steps to reproduce the problem

1. Download Omen, or any addon that show u threat/agro .
2. Get in combat with 2 ads (maily elites so they dont die too fast)
3. apply "devastate" and compare the agro in the first target with the second one
4. THEN in other 2 ADS, apply the normal "sunder armor" and compare how it generates agro in both , the second will dont generate that much agro as the first , but NOT that insignificant like with devastate.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank for the report. To do screenshots on your PC you can use button `PrtSc` or on MacOS `Command-Shift-3`. 
Threat applying to 2nd target is correct. It should redirect threat only of sunder effect without damage part. And this is happend with glyph. More important question that i have: why devastate has so small damage from thunder armor effect. This is need more research about threat values of devastate.
