### ISSUE TITLE
(Creature): Venture Co. Operator SmartAI

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#2444]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

1. They cast Trash
2. Running the query to find the drop chance on Azerothcore for item `Super Reaper 6000 Blueprints` shows a 100% drop chance for this item:
``` sql
SELECT creature_loot_template.Chance, item_template.name , item_template.entry
FROM creature_loot_template 
INNER JOIN item_template ON creature_loot_template.item = item_template.entry
WHERE item IN (5734);
```

### Expected Blizzlike Behaviour

They don't cast Trash according to Classic Sniffs.

Compared to VMangos `Super Reaper 6000 Blueprints`  should have 15%. You can check with query
```sql
SELECT creature_loot_template.ChanceOrQuestChance, item_template.name , item_template.entry
FROM creature_loot_template 
INNER JOIN item_template ON creature_loot_template.item = item_template.entry
WHERE item IN (5734);
```

### Source

VMangos Database and Brotalnia's sniffs on classic.

### Steps to reproduce the problem

1. .q a 1093
2. .go c id 3988
3. The creature casts Thrash at start of the fight
4. They drop the item with a 100% drop rate.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
There is exist report about thrash https://github.com/azerothcore/azerothcore-wotlk/issues/6118

**Comment by claudiodfc** [comment]
This should be closed, the drop rate is the most important factor here. Thrash can be done via major overhaul.
