### ISSUE TITLE
Mux Manascrambler does not offer a quest item

### ISSUE THREAD

**Issue by zdzihu** [chromiecraft/chromiecraft#2448]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Hi, I'm trying to complete quest The Challenge (quest=9015), but I cannot speak to invisible/ghost questgiver Anthion Harmon (npc=16016) because I miss an item named Extra-Dimensional Ghost Revealer (item=22115). Usually when this item is lost/missing, one can get a replacements from NPC Mux Manascrambler (npc=16014) in Gadgetzan. But while I can talk to this NPC and they offer me this item in dialogue, it doesn't appear in my inventory. This prevents player from completing T0.5 upgrade quest.

### Expected Blizzlike Behaviour

NPC Mux Manascrambler (npc=16014) should give an item Extra-Dimensional Ghost Revealer (item=22115) to a player.

### Steps to reproduce the problem

1. Talk to the Mux Manascrambler (npc=16014) to get an item Extra-Dimensional Ghost Revealer (item=22115)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/tree/master

### Operating system

Windows 10 Pro x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report, It's known issue. unfortunatelly i can't say when it will be fixed. i will try to rise up this issue.
