### ISSUE TITLE
Warrior intercept doesn't work properly

### ISSUE THREAD

**Issue by creativemonkeyz** [chromiecraft/chromiecraft#2449]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

If an warrior Intercept a druid that have  Nature's grasp  on him, warrior is rooted BEFORE reaching the druid.
This is also happening with frost mage. If Frostbite activate in the moment that warrior press Charge/Intercept warrior freeze in initial place.

### Expected Blizzlike Behaviour

If an warrior Intercept a druid that have  Nature's grasp  on him, warrior MUST be rooted AFTER warrior reach the druid.
If Frostbite activate in the moment that warrior press Charge/Intercept warrior MUST freeze AFTER he reach mage.

https://wowgaming.altervista.org/aowow/?spell=20252

### Steps to reproduce the problem

1. Your druid target must have Nature's Grasp active on him
2. Use berserk stance and use INTERCEPT
3. Warrior don't reach druid, he's being rooted on initial place
4. Also with mage is harder to reproduce, mage must cast frostbolt on you and when warrior charge/intercept and frostbolt reach warrior and Frostbite is activated warrior remain in the place when frostbite activated instead of reaching the mage.
5. I think second issue will be solved with first one, because seems to be the same mechanics and be a charge/intercept issue

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by creativemonkeyz** [comment]
The mechanics for  Frostbite can be tested with other spell,. Try this scenario:
1. Charge/Intercept target
2. WHILE charging/intercepting use one of the following: Frost nova, intercept from felguard, paladin stun, charge/intercept from another warrior.
3. You will see that in the moment that step 2 is realized, the warrior will remain still instead of reach target and then be affected by step 2.

**Comment by Spook9** [comment]
This can also be recreated with Charge and Frostbite if the warrior is using a startattack macro like this:
"
#showtooltip Charge
/startattack
/cast Charge
"
The bug is produced when the warriors autoattack hits the target before the warrior is in autoattack range. 

As of AB weekend December 2021 this is still a thing.

**Comment by creativemonkeyz** [comment]
Hello,
Why is it issue closed? the problem is not fixed and you can't tell me that it should work like this cuz it s not suppose to.. check on every server you want and beside this, warrior is ZERO vs hunter with this bug, also ZERO vs druid, i can never reach him so please reopen this issue and do something ..
Thank you
