### ISSUE TITLE
No Copper Ore in Elwynn Forest

### ISSUE THREAD

**Issue by Swordsmith928** [chromiecraft/chromiecraft#2458]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

No Copper Ore is spawning in Elwynn Forest today. It was spawning fine yesterday, today I haven't seen any. Restarting the game didn't fix it.

### Expected Blizzlike Behaviour

Copper Ore should spawn, and then respawn at regular intervals after being mined.

### Source

Personal Experience

### Steps to reproduce the problem

1. Go to where a Copper Ore Vein should spawn in Elwynn Forest
2. See whether ir nit it is there, if it isn't wait out the respawn timer, if it doesn't respawn, you have reproduced the bug.

### Extra Notes

Restarting the game didn't fix the bug. Sorry for the lesss than useful answers below, I have no idea what the AC rev thing is and I haven't installed anything but the server itself. No mods/add-ons etc if thats what your asking.

### AC rev. hash/commit

No idea what this is, Sorry.

### Operating system

Windows 11 Home Single Language
Version 21H2
OS Build 22000.318
Windows Feature Experience Pack 1000.22000.318.0

### Modules

I haven't manually installed any, so whatever comes with the download on your website?

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
> No idea what this is, Sorry.

`AC rev. hash/commit` is generating automatically when you're creating report. You should not remove it. Anyway thank you for the report, but i can't reproduce it on local AC either on CC
![WoWScrnShot_120321_172349](https://user-images.githubusercontent.com/85256266/144619021-3ee95c08-1471-482b-983c-f4a0ab2d36d9.jpg)
![WoWScrnShot_120321_172425](https://user-images.githubusercontent.com/85256266/144619038-7a395775-122e-4d46-9b0e-085ae200ca3d.jpg)
