### ISSUE TITLE
[Upper Blackrock Spire] Pillar doesn't interact like wall but can be passed through it

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2461]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

![WoWScrnShot_120321_230644](https://user-images.githubusercontent.com/80590226/144679322-fdbdab82-9dec-49bd-926d-bcf6e2009793.jpg)
![WoWScrnShot_120321_230643](https://user-images.githubusercontent.com/80590226/144679325-3575f988-b5e5-48dc-9220-e666c6630a16.jpg)
![WoWScrnShot_120321_230639](https://user-images.githubusercontent.com/80590226/144679327-96318f94-36c7-44d4-8fc8-1b161a0c31ce.jpg)

After killing last boss, you can jump to room after first boss, there you can walk into pillar.

### Expected Blizzlike Behaviour

Shouldn't be able to walk through pillar

### Steps to reproduce the problem

1. After last boss
2. Jump to the point where this pillar is
3. Walk into pillar

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Looks like a client glitch to me, doubt anything can be done about this

**Comment by Azcobu** [comment]
Closing as per above.
