### ISSUE TITLE
Druid Clearcasting procing off accepting talent points. 

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#2462]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I placed a talent point in [Living Seed] and accepted my talents, and clearcasting proced. 

Video: https://youtu.be/2Jw8bqarLew

### Expected Blizzlike Behaviour

Any procing with talents should not happen I would think. It just doesn't make sense. 

### Steps to reproduce the problem

Have a talent point available, and place it in living seed, then accept. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Bizarre as it sounds, this appears to be Blizzlike:

>By 52390 on 2009/04/17 (Patch 3.1.0) |   |  
Even pressing the "Learn" button on my talents proc'd Omen of Clarity! ([source](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=680908))

There's also qute a few people commenting on talent switches proccing it as well:

>Omen of Clarity can also proc when switching talent sets. ([source](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=756418))

> As people have mentioned, this (and other "on spell cast" procs) will proc off of professions, talent switches, and other non-combat abilities. It does this because everything in wow that has a cast time (and a few things that don't) is considered a spell... ([source](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=867604))

As this appears to be expected behaviour, will close this issue.
