### ISSUE TITLE
[Quests] Multiple - Quest dialog window does not close on any quest that completes on an object

### ISSUE THREAD

**Issue by CMHWoody** [chromiecraft/chromiecraft#2463]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

For any multi-step quest that involves completion and acceptance of the next quest upon using an object, the quest complete sound plays, however, the quest dialog remains up, with the quest text and Complete button still displayed, though the button won't do anything. You must X the window entirely and re-use the object to pick up the next step of the quest.

### Expected Blizzlike Behaviour

In retail, you would complete the quest you were on, that quest dialog would close and the quest window would immediately display the next quest with the Accept button. The sticky completed quest does not occur, and there is no need to x and click the object a second time.

### Steps to reproduce the problem

This seems to occur on any quest with this object mechanic (I confirmed on the Captain Sanders' Hidden Treasure series in Westfall), but to duplicate:

Teleport to Chief Engineer Hinderweir VII in Loch Modan
Accept A Dark Threat Looms (Part 1)
Go to the Suspicious Barrel at the other side of the dam.
When clicking on the barrel, and given quest dialog window, click Complete and you'll see the window sticks and does not go away, nor is the window refreshed with the Part 2 quest to accept.
You must then X the quest dialog window, then click the suspicious barrel again and accept the new quest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report, but with newest build of the Azeroth Core i can't reproduce it. Let me know if after Cromie Craft server update there will be issue. Version of the Core you can see on loading.

![WoWScrnShot_120521_062440](https://user-images.githubusercontent.com/85256266/144732197-434887b3-87c8-4de0-84ac-db6b5f4740c5.jpg)

https://user-images.githubusercontent.com/85256266/144732038-8e156def-efa3-4546-86ca-b2688c808214.mp4

**Comment by ridai260** [comment]
I too could not replicate this on the latest core. Probably already fixed.

![2021-12-07_12-23](https://user-images.githubusercontent.com/22999645/145028658-3cf1d6d3-3c5e-4e08-8b3c-12e6ee27f061.png)


https://user-images.githubusercontent.com/22999645/145029223-6f4c4f44-3b6f-413a-8607-bfc7b9a9b553.mp4

**Comment by Shineslippers** [comment]
Should work after last update.
![Capture](https://user-images.githubusercontent.com/85256266/146189217-fe57fd0e-0732-4b54-be30-acd18babd99d.PNG)
