### ISSUE TITLE
[Quest] POI sparkles for quest "New Life" are too large

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2467]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Gaea Dirt Mounds are the POIs for completing the quest "New Life" in Stonetalon Mountains. They are indicated by sparkles that are too large, resulting in whole sparkling zone in The Charred Vale.

![gaea_dirt_mound](https://user-images.githubusercontent.com/62797536/144710244-e42a85f2-6d54-477d-83d8-0f70c23aea77.jpg)
Screenshot is not the best, but you get an idea.

### Expected Blizzlike Behaviour

POI sparkles of Gaea Dirt Mounds should have a significant smaller size.

### Steps to reproduce the problem

1. Accept the quest "New Life" in Stonetalon Mountain
2. Go to The Charred Vale zone

### Extra Notes

Quest: https://wowgaming.altervista.org/aowow/?quest=6381
Gaea Dirt Mound: https://wowgaming.altervista.org/aowow/?object=177929

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Wowhead comment pointing to blizzlike state of this issue. Need to ask devs is particles area could be ajusted from server side.
> By 384791 on 2009/06/07 (Patch 3.1.3) The nodes for the soil appear to be bugged at the moment. The "glitter" around them is huge!
