### ISSUE TITLE
[Quest] Final evolution of Venomhide is too large for undead players

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2473]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

During the quest "They Grow Up So Fast" your Venomhide Hatchling grows based on the numbers of [Venomhide Baby Tooth] in your inventory. After having 16 baby tooths in your inventory, the hatchling gets his final growth "and depending on your race, can actually be taller than you." (source: https://wowpedia.fandom.com/wiki/Venomhide_Hatchling)

But the size of the last form is way too large for undead players.

![venomhide_too_large](https://user-images.githubusercontent.com/62797536/144711780-a6d0807a-b98b-4abd-b4c6-0c0d239f24bc.jpg)

### Expected Blizzlike Behaviour

While in the middle sized form the raptor is slightly smaller than a male undead. I found this picture on the internet showing a slightly larger raptor. This should be the size of the final form.

https://wow.zamimg.com/uploads/screenshots/normal/176576-venomhide-hatchling.jpg

### Steps to reproduce the problem

1. Be a male undead player
2. Accept quest "They Grow Up So Fast" in Ungoro Crater
2. Acquire 16 [Venomhide Baby Tooth]
3. Summon [Venomhide Hatchling] the next day

### Extra Notes

Quest: https://wowgaming.altervista.org/aowow/?quest=13906
Item [Venomhide Baby Tooth]: https://wowgaming.altervista.org/aowow/?item=47196
Item [Venomhide Hatchling]: https://wowgaming.altervista.org/aowow/?item=46362#objective-of-quest

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
I think the scaling is not only wrong for Undead; I have seen other HUGE raptors on other horde classes. The link you provided is the correct size, they should end up being "mount size", which is relative to each race but never looking like damn Devilsaurs.
