### ISSUE TITLE
Quest: "More Dense Grinding Stones" (Darkmoon Faire)

### ISSUE THREAD

**Issue by Josarth** [chromiecraft/chromiecraft#2477]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I already completed all the quest from DMF except this one.

I have the [Dense Grinding Stone]x8 in my bag, but i'm stuck on "continue"

### Expected Blizzlike Behaviour

Able to press button continue

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
Maybe your reputation is higher than it should be. Some quests get's unavailable after some chekpoints of reputation

**Comment by Elexias** [comment]
![image](https://user-images.githubusercontent.com/80590226/144738182-861f32b2-9554-45d2-8e02-72952f03768f.png)

Truth doesn't work no matter of reputation of mine is lower

**Comment by Elexias** [comment]
Doesn't let me turn in.

**Comment by rhowell** [comment]
I am having the same issue as a level 59 with 2500/6000 friendly rep.  According to the guide on classic wowhead [here](https://classic.wowhead.com/quest=7939/more-dense-grinding-stones), this should be doable as a 'tier 5' turn in, and the quest should be provided by Kerri Hicks, not Chronos.

**Comment by cachocarne** [comment]
Dense Grinding Stones correspond to Tier 5 and should be usable at any point, since it doesn't stop working after any rep level.
"The highest level quests (tier 5) remain available, although they are implemented as two sets of quests, one set that gives reputation that does cut off and is replaced by another set that does not give reputation and does not cut off."

**Comment by Shineslippers** [comment]
Yea, that's known issue about incorrect Questgiver NPC. This quest was working a while ago. Something new broke it.

**Comment by Si1ker** [comment]
https://www.azerothcore.org/wiki/creature_questender
https://www.azerothcore.org/wiki/creature_queststarter

can anybody just put [Kerri Hicks](https://classic.wowhead.com/npc=14832/kerri-hicks) instead of [Chronos](https://classic.wowhead.com/npc=14833/chronos) for [More Dense Grinding Stones](https://classic.wowhead.com/quest=7939/more-dense-grinding-stones) in those tables? ty

**Comment by Si1ker** [comment]
### == Issue ==
**(14833, 7939)** on **creature_queststarter**
14833 = npc = [Chronos](https://classic.wowhead.com/npc=14833/chronos)
7939 = quest = [More Dense Grinding Stones](https://classic.wowhead.com/quest=7939/more-dense-grinding-stones)

### == Fix ==
```sql
UPDATE `creature_queststarter` SET `id`=14832 WHERE `quest`=7939;
```

cc @FrancescoBorzi @temperrr

**Comment by Josarth** [comment]
![WoWScrnShot_040622_110049](https://user-images.githubusercontent.com/74470790/161992411-d22f934e-34d4-40c6-88ec-e110db197648.jpg)

**Isn't FIX**

**Comment by acidmanifesto** [comment]
Of course, it isn't. They guy needs to do a pr, and we can't just steal his fix claiming it as our own.
