### ISSUE TITLE
Wrong RDF rewards from satchels

### ISSUE THREAD

**Issue by Awkakelen** [chromiecraft/chromiecraft#248]
##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

As a mage when I finish random dungeon, when I open a sachel i get items with strength+agi

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I should be only getting items with proper stats like "of the Invoker" etc.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Join random dungeon
2. Finish random dungeon
3. Open a satchel
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
> I should be only getting items with proper stats like "of the Invoker" etc.

@Awkakelen please link some sources that prove this would be the correct blizz-like (3.3.5a) behaviour

**Comment by mturca** [comment]
Not sure if you will accept the source but https://wotlk.evowow.com/?item=51999#contains the suffix is randomly generated

**Comment by Stifler82** [comment]
> Not sure if you will accept the source but https://wotlk.evowow.com/?item=51999#contains the suffix is randomly generated

@mturca 
How many times has this happened to you?

**Comment by mturca** [comment]
The randomness - for example i farmed ~ 2 days to get the good gloves so to speak might be worse for others - at least for the 10-19 back - farmed for more than a week to get the proper Cloak.

The main issue here that would make people think that it is a bug is that the longer a phase lasts, the more people will notice it, In normal gameplay progression you usually get a better one from a mob drop or quest either in the same day or the next day when you move to a higher tier dungeon

**Comment by eTzmNcbkrng** [comment]
https://www.wowhead.com/item=51999/satchel-of-helpful-goods#comments:id=911912

Looks like Blizzlike behaviour is to give armour type-appropriate stats, but it’s still possible to get a shitty suffix within that arm or type.

**Comment by JanEbbing** [comment]
I got a mail item as lv 35 hunter from the satchel though hunters cannot wear this until lv 40.
![WoWScrnShot_071221_190520](https://user-images.githubusercontent.com/5873110/125339454-366a8380-e349-11eb-87aa-436558492fce.jpg)

**Comment by eTzmNcbkrng** [comment]
> 
> 
> I got a mail item as lv 35 hunter from the satchel though hunters cannot wear this until lv 40.
> ![WoWScrnShot_071221_190520](https://user-images.githubusercontent.com/5873110/125339454-366a8380-e349-11eb-87aa-436558492fce.jpg)

I think this is because the level of the satchel that is awarded is based on the dungeon you do, not the player's level. So you must have done a dungeon with a recommended level of at least 40.
Do you recall what dungeon you got this from?

**Comment by da-stealth** [comment]
This is the most accurate representation I can find of what the Satchel of Helpful Goods should give out https://wowwiki-archive.fandom.com/wiki/Satchel_of_Helpful_Goods
As a mage, unless it is a non-cloth item (finger, neck or back), as far as I can see, the items should never have str or agi.

**Comment by da-stealth** [comment]
> I got a mail item as lv 35 hunter from the satchel though hunters cannot wear this until lv 40.
> ![WoWScrnShot_071221_190520](https://user-images.githubusercontent.com/5873110/125339454-366a8380-e349-11eb-87aa-436558492fce.jpg)

So long as the dungeon was a 36-45 dungeon this is expected behaviour. See the Source section - https://wowwiki-archive.fandom.com/wiki/Satchel_of_Helpful_Goods_(level_45)

**Comment by acidmanifesto** [comment]
So looking back, all i can confirm is the following. Loot and Reference loop entries are matching and consisitent with the UDB. 
What I can say from personal experience, i have recieved loot at a higher level then I was when hitting RDF on current retail, but not wotlk retail, i started retail play at MOP, however the stats and item being higher then my character has been reduced some in much later and current expansions. At this point unless we have other sources to further elaborate this via personal sniffs durning the wotlk this issue will remain sitting at this point. As a side not, comparing to our counter part Trinitycore, the issue is the same there but not a reported problem currently. Although that does not mean it may not be a issue, just may not be a reported issue currently.

**Comment by EdyGlockenspiel** [comment]
Back in the day the only thing that was confirmed was to be of your armor type, so you couldn't loot cloth as a palli from the bag or plate as a mage. But you could 100% get a piece of plate as a warrior with int on it, or a piece of cloth with STR on it. This was not changed until much later. In 3.3.5 the stats on the items are working as intended.

**Comment by Salehyn** [comment]
As per the gathered evidence, on 3.3.5a your class only determines which type of armor (cloth,leather etc) you receive. The enchantment depends on armor type, so i.eg. cloth items can never have STR or AGI. Items without an armor type (i.eg. necklaces) can have any stat, regardless of your class.

Tests made on CC PTR show this is working as intended. As a mage, if you receive a cloth item, it never has melee stats.
