### ISSUE TITLE
The Barrens Herb Nodes

### ISSUE THREAD

**Issue by Cosmic-Cocoa** [chromiecraft/chromiecraft#249]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

These are some double spawn nodes I came across in The Barrens so far.

Doublespawn Herbs - 
585 & 13573 - Silverleaf
775 & 13585 - Silverleaf
928 & 13577 - Silverleaf
983 & 2094 - Silverleaf / Mageroyal
1234 & 13586 - Silverleaf
2141 & 13687 - Mageroyal
2435 & 13358 - Mageroyal
2620 & 65123 - Briarthorn

Possibly Concerning (not quite literally right on top of each other):
2347 & 2350 - Mageroyal
3050 & 86281 - Bruiseweed
4294 & 13372 - Kingsblood

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should only be one herb at the above locations.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to the game object and see if it is double spawned.

##### EXTRA NOTES:

I'm not sure if you guys are concerned with nodes that are spawning within a yard or two of each other, hence the second smaller group of herbs I listed. I'll base what I include on future reports on if you guys want those or not.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Cosmic-Cocoa** [comment]
Another one:

2762 & 63431 - Briarthorn double spawn.

**Comment by Cosmic-Cocoa** [comment]
And another:

998 & 13578 silverleaf

**Comment by Cosmic-Cocoa** [comment]
And another:

1606 & 31976 peacebloom doublespawn

**Comment by InstructionSeeker** [comment]
![WoW_HUAENn50KZ](https://user-images.githubusercontent.com/60620452/111871750-1d018e00-898c-11eb-99b7-c714155d1a07.png)
![lnrbhiVJFi](https://user-images.githubusercontent.com/60620452/111871766-2ab71380-898c-11eb-885e-77e3e2ab9c0b.png)
![WoW_ebYSr2W8IL](https://user-images.githubusercontent.com/60620452/111871793-402c3d80-898c-11eb-8c4b-86a57b0f6434.png)
![WoW_qHkki6Isyq](https://user-images.githubusercontent.com/60620452/111871804-491d0f00-898c-11eb-8f57-cda945b86fe2.png)
![WoW_7rWnaGM5Yo](https://user-images.githubusercontent.com/60620452/111871809-50441d00-898c-11eb-8ac9-c7b7f38b3dca.png)
![wbI9mQbRrl](https://user-images.githubusercontent.com/60620452/111871823-5d610c00-898c-11eb-847d-d087c39eb26f.png)
![WoW_wkkJ7N86rh](https://user-images.githubusercontent.com/60620452/111871829-6651dd80-898c-11eb-9afe-7439f4655d23.png)
![7vJu0PLZLA](https://user-images.githubusercontent.com/60620452/111871843-6e118200-898c-11eb-9b69-956a5316b1b6.png)
![hD0G3uszMW](https://user-images.githubusercontent.com/60620452/111871851-7669bd00-898c-11eb-80c2-cd0aebccdbcb.png)

**Comment by Cosmic-Cocoa** [comment]
Some more:

2625 & 14459 - Briarthorn
795 & 63424 - Silverleaf
1255 & 13589 - Silverleaf
520 & 13571 - Silverleaf  --Also a Briarthorn right next to those two: 14201

**Comment by InstructionSeeker** [comment]
One more duplicate spawn:
![6xMfdbNOkP](https://user-images.githubusercontent.com/60620452/112291868-d2845800-8c90-11eb-9c58-23f685ab2aa1.png)

**Comment by nolt** [comment]
928 & 13577
go to this guid causes fall into texture
