### ISSUE TITLE
[Quest] "A Donation of ..." quests also award reputation with the other capital cities

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2493]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When you donate cloth in one of the capital cities you gain reputation with the corresponding faction and 1/4 of the reputation value for the other factions.

This behaviour is blizzlike for "normal" quests in the world but not for cloth donation quests.

![WoWScrnShot_120621_200515](https://user-images.githubusercontent.com/62797536/144906962-cde4b264-9788-45af-a816-39a3961d5d46.jpg)

![WoWScrnShot_120621_200522](https://user-images.githubusercontent.com/62797536/144906991-1887bcbb-2238-4072-82eb-e2b0e248aebd.jpg)

### Expected Blizzlike Behaviour

Cloth donation quests in the capital cities only award reputation for the corresponding faction.

### Steps to reproduce the problem

1. Finish any of the "A Donation of ..." quests in the capital cities.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Have sense, but can't find sources to confirm it.

**Comment by ishidinho** [comment]
@Shineslippers I logged into offical TBC Classic yesterday and tested it: No reputation for the other factions. Is this evidence enough? I can deliver screens, if you need.

**Comment by Shineslippers** [comment]
@ishidinho yes, sure. Sniffs from classic for most of cases is good proofs.

**Comment by Azcobu** [comment]
There's some sort of TBC factsheet on these quests here: http://www.giddygamer.com/wow/content/reputation/cloth_quests.pdf

It says "Reputation gains are only for the faction of the questgiver; eg. you have to go to Darnassus to get Darnassus rep."

**Comment by ishidinho** [comment]
As promissed, screenshots from TBC Classic.

![WoWScrnShot_120721_134044](https://user-images.githubusercontent.com/62797536/145031016-cab1646b-07ba-4353-a964-4751f7684783.jpg)

![WoWScrnShot_120721_134059](https://user-images.githubusercontent.com/62797536/145031031-e01a5cab-00a6-48b8-9cef-dd5c21ecd515.jpg)

**Comment by theo1143** [comment]
No sniffs from classic are not proof, classic is retail changed to fit the bill.
Back in wotlk you are supose to get rep while at max level because you get alliance rep (or horde)
The 350 wil go to your main rep but you also get a little bit towards all the other reps which fall under your flag.

**Comment by theo1143** [comment]
Stop changing things that are supose to be like this!
