### ISSUE TITLE
Earth Sapta quest missing condition

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#2494]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The quest is available to be taken all the time, missing the condition on player having the item.

### Expected Blizzlike Behaviour

Only be able to take the quest when player doesn't have the item.

### Steps to reproduce the problem

Take quest Earth Sapta

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report, but i can't confirm it. Quests `Earth Sapta` only available while you're doing `Call of Earth` quests. They require to see elementals. NPCs doesn't offer those quests not before accept `Call of Earth` not after complete of it. Wowhead comment describing same behavior:
> By GibbleFenwick on 2020/06/01 (Classic)
I noticed this quest was available when I handed in  Call of Earth.
But then it disappeared. I was puzzled, so I came to consult the wowhead oracle.
Based on the completion text, this quest is a recovery mechanism in case something goes wrong between the previous quest in the chain  Call of Earth and the final quest completion. If you lose or discard the quest item, you can still get another  Earth Sapta to do the quest.

![WoWScrnShot_120721_141715](https://user-images.githubusercontent.com/85256266/145020703-ccf588e4-a30b-4f10-a457-7256c8d1d96f.jpg)
![WoWScrnShot_120721_142129](https://user-images.githubusercontent.com/85256266/145020716-c8f78a46-2a45-4de7-814b-a3de89b6505e.jpg)

.
