### ISSUE TITLE
Quest Auto Accepting

### ISSUE THREAD

**Issue by Knewklear** [chromiecraft/chromiecraft#25]
##### SMALL DESCRIPTION:

Quests are automatically being accepted instead of allowing the player to hit accept. This happens in every starter zone (level 1-5/6)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Players have to hit accept at the bottom of the quest description in order to begin the quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Continue accepting quests from any starter zone.
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
hello, thanks for your report however this behaviour is intended and it's related to the client, not the server.

You can change it in your own client by changing the settings.
