### ISSUE TITLE
Bride of the Embalmer Quest bugged

### ISSUE THREAD

**Issue by Varr05** [chromiecraft/chromiecraft#2503]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

WHen completing the quest, no item is collected, and the quest's ! remains in place, text in the chat window confirms quest complete, but in the log it does not update.

### Expected Blizzlike Behaviour

Recieve item: Embalmers Heart

### Steps to reproduce the problem

Get to the quest Bride of the Embalmer and try to complete the quest at the grave site.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

HD Texture pack (from your website)

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I've just run through this quest, and it seems to be working fine. What you might have missed is that when you click on the grave and then click the Complete Quest button on the quest log, Eliza spawns nearby, and you get the quest item by killing her.

![WoWScrnShot_120821_214617](https://user-images.githubusercontent.com/81782124/145199457-048258ba-c2c7-40fa-aaad-f2bbcc62cdf8.jpg)
![WoWScrnShot_120821_214623](https://user-images.githubusercontent.com/81782124/145199473-9e4bd087-1a5f-4333-9b1d-ca8aefbf2024.jpg)
![WoWScrnShot_120821_214631](https://user-images.githubusercontent.com/81782124/145199481-99e2194e-8ef0-487c-a858-6d4720bf3ed6.jpg)

Hope that helps. Will close this issue as it seems to be working fine.

**Comment by Shineslippers** [comment]
Maybe also it's issue with update of the script loader. Probably it doesn't summon Eliza that drops quest item. It will be fixed soon.

**Comment by TooTall54** [comment]
I am having the same problem.  Eliza does not appear at all.

**Comment by Shineslippers** [comment]
@TooTall54 This is issue with scrits loader that i mentioned above. It's not about quest itself. There is no other way than waiting for devs solution.
