### ISSUE TITLE
Sound EFX Looping in Valley of Trails

### ISSUE THREAD

**Issue by jburkettstudio** [chromiecraft/chromiecraft#2507]
Hello

I have just now joined the chromiecraft server and hope to have a lasting WoW experience with its community. 

After creating an orc warrior and entering the Valley of Trials, I have been annoyingly bombarded with what sounds like, "Work. Work." over and over. If I remember correctly, I think this is the lazy peons' dialogue. However, I have even left the zone yet still hear this repeating sound effect in intervals of a few seconds. 

Thanks in advance for what chromiecraft is developing. I appreciate everyone's time and consideration.

**Comment by Azcobu** [comment]
Thanks for the report. Fortunately this has been previously reported and has just now been fixed - see PR https://github.com/azerothcore/azerothcore-wotlk/pull/9525, though I don't think it's had time to make it across to Chromie just yet. However, that should happen in the next few days, which should resolve this. Closing this accordingly.
