### ISSUE TITLE
CC progression: Not all PvP Vendors adjusted

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#2515]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

CC staff decided to introduce non-blizzlike adjustments to the PvP Vendors for Warsong Gulch, Arathi Basin and Alterac Valley factions.

But, for Alterac Valley Factions, only 1 of 2 vendors per faction got adjusted. Thus, right now there is one vendor selling a restricted amount of items for an increased price (in the open world / capital city) and one blizzlike vendor within Alterac Valley per faction.

### Expected Blizzlike Behaviour

The 4 vendors should sell their factions respective items for the same price and offer the same items.

### Source

Every non-adjusted database

cmp. for affected vendors:
[https://db.rising-gods.de/?item=19323#sold-by-npc](https://db.rising-gods.de/?item=19323#sold-by-npc)

### Steps to reproduce the problem

Check AV vendor in SW / OG (which are originally supposed to stand in Hillsbrad / Alterac Mountains only.
Then compare both vendors accessible within the battleground AV.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Lucika77** [comment]
Also the vendors sell faction specific mounts and when you get crossfactioned as alliance player to horde, you have there Frostwolf Howler for purchase. I'm not sure if you can buy it and then use it, but would be also nice to check this too, because Frostwolf Howler should be only horde mount and Stormpike Battle Charger should be only alliance mount.

**Comment by j-hdt** [comment]
i think this issue has been solved.
