### ISSUE TITLE
Darkmoon Faire disappeared

### ISSUE THREAD

**Issue by Them0k** [chromiecraft/chromiecraft#2538]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

The Darkmoon Faire dissapeard after the Server restart at 4:30 am servertime. I dont know if this was before the restart, i noticed it after the restart.
![Chromiecraft_3 3 5a Screenshot 2021 12 10 - 06 35 25 58](https://user-images.githubusercontent.com/93892486/145523894-91629775-90fa-4678-9fd1-3e11eb6f5c93.png)
.

### Expected Blizzlike Behaviour

``Darkmoon Faire appears each month, rotating between Elwynn Forest just south of Goldshire, and Mulgore, southwest of Thunder Bluff. The Faire only sets up in one place at a time.
Arrives on the first Friday of every month and begins setup.
Sets up over the weekend
Opens on Monday
Closes the following Sunday
During the Friday-Monday setup period, you will see the work in progress, but none of the vendors, games, or quest NPCs will be available.´´

### Source

https://classic.wowhead.com/guides/classic-darkmoon-faire

### Steps to reproduce the problem

1. Go to Goldshire and look at the Darkmoon Faire spot (42, 67)
2. Thats it. :D

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report it's known issue, but still no progress on it https://github.com/azerothcore/azerothcore-wotlk/issues/6345
