### ISSUE TITLE
Caster mobs do not approach the player

### ISSUE THREAD

**Issue by ScubaV** [chromiecraft/chromiecraft#254]
##### FACTION

- [X] Alliance
- [x] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:
Certain caster mobs, such as the kobold geomancers near Jasperlode mine in Elwynn will not approach the player.  If you deny them line of sight, they just move around in a circumferential pattern, but do not run toward the player.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Caster mobs should move toward the player until line of sight is established or use melee attacks if out of mana.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Aggro Kobold Geomancers near Jasperlode mine.
2.  Break line of sight using a tree.
3.  Observe.

##### EXTRA NOTES:

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
Can you provide any footage for this?
"It feels wrong" and "I am sure it's wrong" isn't something the devs will accept as a reason.

**Comment by ScubaV** [comment]
Sure: https://youtu.be/ut5S4A1a_eU?t=554

I'm sure the devs would know it's wrong if they've ever played WoW, but I can understand the need for proof.  I'm actually surprised Azeroth core has it wrong since it's pretty fundamental gameplay.

**Comment by 55Honey** [comment]
Please note that as much as not every player is a dev, not all devs are also players ;-)

I get your point, but when i went into WC and RDF, the mobs could be pulled around corners just fine.
So one would need to try it with the jasperlode Mine Kobolds specifically.
Any other mobs to add to the list?

**Comment by Stifler82** [comment]
> Sure: https://youtu.be/ut5S4A1a_eU?t=554
> 
> I'm sure the devs would know it's wrong if they've ever played WoW, but I can understand the need for proof. I'm actually surprised Azeroth core has it wrong since it's pretty fundamental gameplay.

**Video Test:** [Caster mobs](https://youtu.be/mgBbelvs6_E)

**Comment by 55Honey** [comment]
https://www.reddit.com/r/classicwow/comments/at2c03/was_hiding_behind_trees_to_break_los_a_thing_in/

Trees don't break LOS.

**Comment by 55Honey** [comment]
> Break line of sight using a tree.

Trees dont break los.

@Stifler82  The report says you need to move away from the mob so it can not see you. Hide behind a corner or a rock as in map element or gameobject.

**Comment by Stifler82** [comment]
> The report says you need to move away from the mob so it can not see you. Hide behind a corner or a rock as in map element or gameobject.

@55Honey 
In the video there is not this scene, but before entering the cave I had already tried to get behind a tree, and the mob approached me and as soon as it came in line with me it cast the fireball to me.
btw, I'll make really fast a new video with what you are asking for.. ❤😜

**Comment by Stifler82** [comment]
@55Honey 
**Video Test 2:** [Caster mobs2](https://youtu.be/lf6cE3nBvlk)

**Comment by Stifler82** [comment]
@55Honey 
I hope the question of why I closed this issue and why I will close all issues like this is clear now.

**Comment by 55Honey** [comment]
It makes sense to me.

**Comment by CameronWoof** [comment]
So vmaps/pathfinding not working correctly is a known issue? Has it been reported already?

**Comment by 55Honey** [comment]
There was a commit about it recently and there is still work on it done.
https://github.com/azerothcore/azerothcore-wotlk/issues/4435
This one is a maps/pathfinding issue for example.

**Comment by ScubaV** [comment]
> @55Honey
> **Video Test 2:** [Caster mobs2](https://youtu.be/lf6cE3nBvlk)

This video actually perfectly demonstrates the incorrect behavior as reported.  Mobs are not supposed to move laterally to attempt to gain line of sight.  Otherwise they can be infinitely kited at range using objects with no risk to the player and no movement abilities required.  As per the video I uploaded demonstrating the correct behavior, once aggroed mobs should move toward the player (not laterally) until line of sight is established.  This allows for line of sight pulls of ranged mobs in dungeons and also requires the player to use skill rather than peakaboo when doing kites in the exterior world.

**Comment by 55Honey** [comment]
There is already an issue regarding that behaviour. I've references this issue in the in on Azerothcore. What else do you expect?
An issue being closed does not mean that the reporter did a bad job or that it's wrong necessaryly. In this case it's already on the To-Do list.

**Comment by Stifler82** [comment]
> > @55Honey
> > **Video Test 2:** [Caster mobs2](https://youtu.be/lf6cE3nBvlk)
> 
> This video actually perfectly demonstrates the incorrect behavior as reported. Mobs are not supposed to move laterally to attempt to gain line of sight. Otherwise they can be infinitely kited at range using objects with no risk to the player and no movement abilities required. As per the video I linked demonstrating the correct behavior, once aggroed mobs should move toward the player (not laterally) until line of sight is established. This allows for line of sight pulls of ranged mobs in dungeons and also requires the player to use skill rather than peakaboo when doing kites in the exterior world.


@ScubaV
- So, (joking aside), in the first video "Caster mobs", it was an "Ironic" video I didn't intend to ridicule anyone or offend..
- In the second video, on the other hand, I explained what it is (The real problem).

The (current) behavior of MOBS is correct, you will obviously ask yourself: **"How is it correct? Do you take drugs?".**

No I do not take drugs, or at least not recently, if recently we are not talking about 3 days ago and if for drugs we are not talking about weed. **(I'm joking)**

Actually the behavior of the MOBS is altered by the ***"Pathfinding and Vmaps" System*** as they are badly scripted, in fact if you noticed the NPC always turned in a direction that: **(counterclockwise)** this is because the script that controls the behavior of the MOBS **(which should be correct, if I'm not wrong)**, it is **"Altered"** by others Scripts which are the one that commands the Pathfinding and the Vmaps System that mess up with a lot of game mechanics.

So this is the reason why I closed your post, because your report ***IS NOT THE PROBLEM***, but **it is the CONSEQUENCE** instead, you know what I mean?

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303
