### ISSUE TITLE
Shaman totem tooltips do not show the correct values when boosted by talents

### ISSUE THREAD

**Issue by DemonBurger** [chromiecraft/chromiecraft#2540]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When having points in talents like [Enhancing Totems](https://wowgaming.altervista.org/aowow?spell=52456) or [Improved Windfury Totem](https://wowgaming.altervista.org/aowow?spell=29193), the buff tooltips from the actual totems show the original unbuffed values. The increase in character stats is correct though.

### Expected Blizzlike Behaviour

The buff tooltip should show the actual amount of str/agi/SP/haste that is increased, with the talents taken into consideration.

### Steps to reproduce the problem

1. Take any talent that enhances a stat totem. (example  [Enhancing Totems](https://wowgaming.altervista.org/aowow?spell=52456))
2. Put down a stat increasing totem. (Strenght of Earth, Flametongue, etc.)
3. Notice the difference between the spell tooltip and the buff tooltip, and the amount of stat increase in the character panel.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. It's `Game Client Bug` issue. All ingame tooltips doesn't updates when it's improved by something. For example Stamina buff with improved talent:

https://user-images.githubusercontent.com/85256266/145580249-eb3cba33-214b-4061-8a52-abd5d9ff6682.mp4
