### ISSUE TITLE
Faerie Fire High Threat Level

### ISSUE THREAD

**Issue by overflowz** [chromiecraft/chromiecraft#2549]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When I was playing with a feral druid (tank) at level ~20-25, using faerie fire in bear form felt like a permanent taunt (threat). I tested it multiple times and every time I used faerie fire on a mob (usually in dungeons), I never lost any aggro even though I was not attacking them (was just running further to pull more mobs, while party members killed them).

### Expected Blizzlike Behaviour

This needs confirmation because I'm not sure if this is the expected behaviour, it just does not feel right to me.

### Steps to reproduce the problem

1. Make Night Elf Druid
2. Use talent tree as such https://wotlkdb.com/?talent#0ZxuGoz
3. Buff yourself with Thorns & Mark of the Wild
4. Go to the Shadowfang Keep dungeon (for example) with 4 other players.
5. Use Faerie Fire on a mob(s), don't do anything, and let others kill the mob (you should not lose the threat).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by jhuerta13** [comment]
I have no wotlk retail experience but ive played on a few other servers on 3.3.5 (warmane, dalaran, tauri) and they all seem to behave the same way. At early levels FF throws like 1-3 k threat per cast.

**Comment by Never6** [comment]
Not bugged

**Comment by Shineslippers** [comment]
@overflowz FF has huge amount of base threat. As you mentioned at level 25 it's 2k threat. That is amount same as HP of elites NPCs in dungeons. So you simply can'n overagro it before killing. Anyway efficient of FF going down with higher levels. At level 50 it's 2,5k threat. This is 3 times less than HP of elites NPCs in dungeons. Without any sources i can't say there is exist issue.

**Comment by overflowz** [comment]
Thank you all for the explanation.
