### ISSUE TITLE
Camera clipping inside structure on Blackrock Stronghold

### ISSUE THREAD

**Issue by Scapulla** [chromiecraft/chromiecraft#2552]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

When in a certain spot inside Blackrock Hold, the camera clips and shows you the insides of the building and the space outdoors.

### Expected Blizzlike Behaviour

keep the camera showing the area around you

### Steps to reproduce the problem

go to Blackrock Stronghold in Burning Steppes on the location shown in the printscreens, and move the camera around laterally a few times 360º.
![WoWScrnShot_121121_033438](https://user-images.githubusercontent.com/85845643/145681569-125d2c44-eafa-4874-8697-89bc66f2637f.jpg)
![WoWScrnShot_121121_033414](https://user-images.githubusercontent.com/85845643/145681589-76be9b1a-ba6b-49c3-abc6-dbae73425860.jpg)

### Extra Notes

You can see that both the screenshots have the same coordinates, it's a matter of camera positioning.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Scapulla** [comment]
Bug also happens in other location inside stronghold
![WoWScrnShot_121121_121944](https://user-images.githubusercontent.com/85845643/145681797-e611eb4c-48fd-4d9c-bb14-eb0c9ce4abf6.jpg)

**Comment by Shineslippers** [comment]
Thank you for the report, but there is nothing we can do about it. This is a Blizzard issue that exists here and there.
