### ISSUE TITLE
Quest: A New Plague seems unaccomplished 

### ISSUE THREAD

**Issue by m0ll3art** [chromiecraft/chromiecraft#2553]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The Quest _A New Plague_ seems not to be implemented according to retail. 

Indeed, the quest implies to collect 5 Vials of Darkhound Blood. I use Carbonite 3.34 and the area for collecting such Vials  is pretty large. On other 3.3.5. servers, like sindragosa (ex Sunwell, Warmane) the area seems to match with the carbonite region proposed by Carbonite. 

But here it seems that the region is very restricted to only a small certain portion of the map Carbonite proposes for this quest. Furthermore, the drop rate is pretty rare and you will have to kill numerous darhounds to retrieve those 5 Vials. 

### Expected Blizzlike Behaviour

Once the quest is accepted the drop rate should be close to 70%-80%   if not 100%  on the darkhounds. 

The region should match to 90% at least with the Carbonite proposed region for the quest. This should be reached if all darkhounds, which are, by the way,  correctly dispatched in the carbonite region, are assigned the quest and propose to drop those vials .. 

### Source

https://www.wowhead.com/quest=369/a-new-plague

### Steps to reproduce the problem

1. accept the quest Start: Apothecary Johaan in Brill 
2. try to collect vials when questing (north) east of Brill  

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
POI regions are sniffed for the most part, so it's correct. As for the drop chance there are no sources to confirm otherwise and most early level drop rates have been sniffed so far.
