### ISSUE TITLE
Unclickable Dark Iron Nodes in Searing Gorge

### ISSUE THREAD

**Issue by Scapulla** [chromiecraft/chromiecraft#2554]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Nodes are unclickable, can't be mined, and don't appear while tracking minerals.
![WoWScrnShot_121121_123549](https://user-images.githubusercontent.com/85845643/145682545-eab40938-647c-4290-b001-872eab1b9db4.jpg)

### Expected Blizzlike Behaviour

Nodes should be able to be mined and tracked.

### Steps to reproduce the problem

Go to the coordinates on the screenshot, and try to mine or even just move cursor over nodes.

### Extra Notes

Already deleted my cache and restarted the game, they're still there. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by The-Eyeful** [comment]
These are not actual Dark Iron nodes, but cosmetic nodes that have been in the game since vanilla. 

https://youtu.be/kkNo2PlqJbA?t=875

Here is a quick vid I just googled, showing at the time mark 14:35 that even during classic wow, they were cosmetic nodes.

**Comment by Shineslippers** [comment]
Thank you for the report. As mentioned above this is not a `dark iron deposits`. It should not be mineable. Also as you can see it's a bit bigger than normal deposits. For now i would say there is no issue.
![WoWScrnShot_121321_172349](https://user-images.githubusercontent.com/85256266/145831236-4971cd74-7895-4aeb-904f-40f8fa525bec.jpg)
