### ISSUE TITLE
black lotus in eastern plaguelands

### ISSUE THREAD

**Issue by ingerash4ever** [chromiecraft/chromiecraft#2555]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

there is a black lotus node appearing under an object
![Uploading Untitled.png…]()

### Expected Blizzlike Behaviour

i think is to be gathered

### Steps to reproduce the problem

move that node to a  nearer spot on open

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ingerash4ever** [comment]
![Untitled](https://user-images.githubusercontent.com/95382911/145693783-b5fed038-3b97-48c1-a3d0-21e77dddcaae.png)

**Comment by Shineslippers** [comment]
Thank you for the report. This spawn point is not inside or under object. As you can see on my screenshot it's in different place where is staying my character. Command `.gobject near` shows objects near you on distance radius. In your case it's behinde you.

![WoWScrnShot_121321_232306](https://user-images.githubusercontent.com/85256266/145883209-28d93819-a0b4-4cab-9b59-01e854217ab5.jpg)
.

**Comment by ingerash4ever** [comment]
Having herbalism been moving all around and no shining object or coursor
turninf to gather mode and minimap was pointing me at that cauldron. Gonna
try again to gather it

**Comment by Shineslippers** [comment]
Command `.gobject near` can show not spawned nodes. It doesn't mean Black Lotus or some other node should be there right now.

**Comment by ingerash4ever** [comment]
I see it on minimap while looking for herbs i will send a screen when i get
back in game
