### ISSUE TITLE
Warlock succubus quest problem "DEVOURER OF SOULS" 

### ISSUE THREAD

**Issue by Fierce78** [chromiecraft/chromiecraft#2556]
### What client do you play on?

other

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Hi, I have a problem .... I have a level 31 warlock and I still can't take the succubus demon ....I also saw it on you tube and I asked other players ..... both of them send me to an NPG who should give me this quest and not give it ....... I searched for both ogrimmar and uc but it doesn't give me the quest. what should I do? I'm afraid the quest is bugged....by all accounts the quest should give it level 20, I'm level 31, he gave me all the quests except this one ...... Thank you

### Expected Blizzlike Behaviour

LPG at orgrimmar or ad undercity should give me a quest to get the succubus demon. A usual thing to have every demon

### Steps to reproduce the problem

get to level 20 and go to the NPG where the worlock trainer is in Under city or Ogrimmar ..... he should give them a quest to take the succubus demon

### Extra Notes

Quest " DEVOURER OF SOULS "

client wotlk 3.3.5

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Windows 10 64bit

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank for the report. On local AC both NPCs offer those quests. Probably you already started the chain and abandon it somewhere on quest line. Otherwise i can't explain current behavior. What class do you have?

![WoWScrnShot_121321_230936](https://user-images.githubusercontent.com/85256266/145881682-8952b1f4-6919-4160-a306-bc13ae212b1a.jpg)
![WoWScrnShot_121321_231029](https://user-images.githubusercontent.com/85256266/145881697-3219b4a0-f464-4bdd-8aca-dfdf62dff594.jpg)

**Comment by Fierce78** [comment]
i'm Undead Orda.....strange ... I have not abandoned any series of quests for the warlock ... I can not take and I have none in the inventory to do ..... I do not know how to solve it honestly

**Comment by Shineslippers** [comment]
I mean not this NPC, maybe you abandon on of followed quests. Anyway in this case you can ask GM. Maybe he can remove https://wowgaming.altervista.org/aowow/?quest=1472 or https://wowgaming.altervista.org/aowow/?quest=1507. Maybe he can say what quest you did from this chains

**Comment by Shineslippers** [comment]
@Fierce78 is there any progress? Did you get Succubus?

**Comment by Fierce78** [comment]
> @Fierce78 ci sono progressi? Hai preso Succube? C'era prima un rapporto simile #2215

unfortunately no .... i don't know how to do it ..... i asked about discord and i was told to ask other players .... but other players got it, what should they tell me?

**Comment by Shineslippers** [comment]
Tell me please ingame name of your warlock. Where you did quest for Void? Orgrimmar or Undercity? Are you sure you didn't start `Devourer` quest in Orgrimmar?

**Comment by Fierce78** [comment]
> Dimmi per favore il nome in gioco del tuo stregone. Dove hai cercato Void? Orgrimmar o Sepulcra? Sei sicuro di non aver iniziato la `Devourer`missione a Orgrimmar?

No no .... I didn't start the mission, I looked for it in uc and ogrimmar. My sorcerer is called Fierce

**Comment by Fierce78** [comment]
> Tell me please ingame name of your warlock. Where you did quest for Void? Orgrimmar or Undercity? Are you sure you didn't start `Devourer` quest in Orgrimmar?

No no .... I didn't start the mission, I looked for it in uc and ogrimmar. My sorcerer is called Fierce

**Comment by Shineslippers** [comment]
I will try to look at it

**Comment by Fierce78** [comment]
> proverò a dargli un'occhiata

Thank you very much

**Comment by Shineslippers** [comment]
I asked GM and as i can see you started this quest in Orgrimmar, but didn't finish it. Last completed quest by you [News of Dogran](https://wowgaming.altervista.org/aowow/?quest=1510). You have to visit [Ken'zigla](https://wowgaming.altervista.org/aowow/?npc=4197) to pick up [Ken'zigla's Draught](https://wowgaming.altervista.org/aowow/?quest=1511)
![unknown](https://user-images.githubusercontent.com/85256266/147382228-b60a2ac6-3a53-4756-bb5d-96989dee81b7.png)

**Comment by Fierce78** [comment]
> I asked GM and as i can see you started this quest in Orgrimmar, but didn't finish it. Last completed quest by you [News of Dogran](https://wowgaming.altervista.org/aowow/?quest=1510). You have to visit [Ken'zigla](https://wowgaming.altervista.org/aowow/?npc=4197) to pick up [Ken'zigla's Draught](https://wowgaming.altervista.org/aowow/?quest=1511)
> 
> ![unknown](https://user-images.githubusercontent.com/85256266/147382228-b60a2ac6-3a53-4756-bb5d-96989dee81b7.png)

sorry and what's the name of the quest to finish? I don't seem to have it

**Comment by Shineslippers** [comment]
Once again. You have to visit [Ken'zigla](https://wowgaming.altervista.org/aowow/?npc=4197) to pick up [Ken'zigla's Draught](https://wowgaming.altervista.org/aowow/?quest=1511) quest. use links to see the map.

**Comment by Fierce78** [comment]
> Once again. You have to visit [Ken'zigla](https://wowgaming.altervista.org/aowow/?npc=4197) to pick up [Ken'zigla's Draught](https://wowgaming.altervista.org/aowow/?quest=1511) quest. Use links to see the map.

ok thanks, I'll go now and let you know.

**Comment by Fierce78** [comment]
> Once again. You have to visit [Ken'zigla](https://wowgaming.altervista.org/aowow/?npc=4197) to pick up [Ken'zigla's Draught](https://wowgaming.altervista.org/aowow/?quest=1511) quest. Use links to see the map.

THANK YOU VERY MUCH !!!!! YOU WERE GREAT .... YOU SOLVED A PROBLEM THAT ALONE I WOULD NEVER SOLVE ..... THANK YOU THANK YOU THANK YOU

**Comment by Shineslippers** [comment]
Cool! Good news. Wish you the best.
