### ISSUE TITLE
The Missing Diplomat - QUEST - ALLIANCE

### ISSUE THREAD

**Issue by Awkakelen** [chromiecraft/chromiecraft#256]
##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

https://wotlk.evowow.com/?quest=1249
After failing the quest, it can't be taken again.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should, the NPC should have a quest for me again.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get "The Missing Diplomat Quest"
2. Fail it on purpose
3. Done

##### EXTRA NOTES:

https://wotlk.evowow.com/?quest=1249

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by CyberneticCC** [comment]
It's a known issue, npc restarts after server restart https://github.com/chromiecraft/chromiecraft/issues/208

**Comment by warscraft360** [comment]
how we supposed to fail it ? its just a walk and speak basic quest and the quest perfectly work 
i try to abandon it and i was perfectly able to re start the quest

**Comment by CyberneticCC** [comment]
> how we supposed to fail it ? its just a walk and speak basic quest and the quest perfectly work
> i try to abandon it and i was perfectly able to re start the quest

after you complete that quest, pick up the next quest and fight slim, if you fail couple times, the npc locks and doesn't restart at all, until server restarts.

**Comment by nolt** [comment]
Duplicated, issue is reported.
