### ISSUE TITLE
Hunter pet clipping through walls and getting aggro in wailing caverns entrance cave

### ISSUE THREAD

**Issue by Scapulla** [chromiecraft/chromiecraft#2562]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When trying to get inside the Right Eye cave to get quests for Waliing caverns, if you have a pet (in my case a raptor), as you are walking up a wall behind the cave to get on top of it to drop and get in, your pet clips through the walls and aggroes monsters that are inside the cave that is under your feet. 
If you walk slowly, your pet goes along with you, clipping a bit through the ground but getting above it after some time, but if you just walk through, the pet gets stuck underground on the cave entrance and pulls aggro.

![WoWScrnShot_121321_005558](https://user-images.githubusercontent.com/85845643/145750428-c6e02c08-982a-44b8-ac8a-4bbc05012507.jpg)
This is the bugged wall

### Expected Blizzlike Behaviour

Pet should stay above ground 

### Steps to reproduce the problem

Go to the location on the screenshot with a hunter and a pet, and walk normally up that wall to get to the Wailing caverns Right Eye cave.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. It's known issue. https://github.com/azerothcore/azerothcore-wotlk/issues/9254
