### ISSUE TITLE
Earth shield 

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#2563]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

The passive heal from earth shield https://wowgaming.altervista.org/aowow/?spell=974 can proc earthliving weapon https://wowgaming.altervista.org/aowow/?spell=51993

### Expected Blizzlike Behaviour

Earthliving weapon can only proc from direct healing spells 

### Source

https://www.youtube.com/watch?v=qc3Ieqo1CQo&t=2068s&ab_channel=RadoMilchev at 33:35 "earthliving is a hot that has a 20% chance to proc from your direct healing spells."

### Steps to reproduce the problem

Make Shaman
Level to 50
Cast earth shield on yourself or another person
has a chance to proc earthliving when struck

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report, but i can't use random video from youtube as source. Patch notes, videos from Wrath era, forums and etc. Something like this could be used as source.

**Comment by Voxstrasza** [comment]
> I would understand that if this video wasnt made by teamy. He is an expert on resto shaman and has done all the theory crafting for resto shaman. If anyone knows resto shaman its him

yes, but that's a private server.  we need evidence from between november 2008 - october 2010.

**Comment by Never6** [comment]
Please tell me you are trolling
its a guide made by a player who has retail and private server experience who has done all the theory crafting for resto shaman he knows the class better than you but continue saying he is wrong lol

**Comment by Shineslippers** [comment]
Well for me he is guy from youtube. As i said before, maybe he is right, but we can't do adjustments based only on his words. I'm sorry.

**Comment by acidmanifesto** [comment]
> Please tell me you are trolling its a guide made by a player who has retail and private server experience who has done all the theory crafting for resto shaman he knows the class better than you but continue saying he is wrong lol

The video uploader even states on his video the terms blizzlike and theorycrafting.
![image](https://user-images.githubusercontent.com/16887899/146224600-99931d10-0279-4df1-ae4c-a3ad845fd32c.png)

I will look at a few other references dealing in terms of sniffs and official blizz documentation to see if there is a way we can validate the issue or not.

**Comment by acidmanifesto** [comment]
Unless there is any other further evidence to actually back up this issue. This issue is not valid.

EarthLiving does not proc from Earth Shield especially because this spelll was changed during Cataclysm and completely removed in  Patch 6.0.2 (2014-10-14).

The spell was added in Patch 3.0.2 (2008-10-14): https://wowpedia.fandom.com/wiki/Patch_3.0.2

It was later changed in  Patch 4.0.3a (2010-11-23): Now only has 25% of its full chance to proc from a single hop of Chain Heal: https://wowpedia.fandom.com/wiki/Patch_4.0.3a.

And was hotifxed in  Hotfix (2013-03-27): Earthliving Weapon now heals for 20% more. https://worldofwarcraft.com/en-us/news/8953693/patch-52-hotfixes-may-10

But essentially we came down to the same conclusion as TC did with a simular report: https://github.com/TrinityCore/TrinityCore/issues/16697

Earthliving Weapon (51940 and related 51945) does **NOT** have the spell attribute SPELL_ATTR3_CAN_PROC_FROM_PROCS                   = 0x04000000, // TITLE Can trigger from triggered spells.
With Earth Shield heal (56451) being a triggered cast, this means Earth Shield will never trigger Eearthliving Weapon.

**Comment by acidmanifesto** [comment]
If any supporting Facts can be provided, i will be more then happy to revisit and reopen this issue.
Facts being, Officail Play video of the expansion, DB2 referenced client files, Sniffs of the expansions with the spell being utilized, and thing deemed authorized in terms of Officially licensed material such as Game Guides.

**Comment by Never6** [comment]
> 
> But essentially we came down to the same conclusion as TC did with a simular report: [TrinityCore/TrinityCore#16697](https://github.com/TrinityCore/TrinityCore/issues/16697)
> 
> Earthliving Weapon (51940 and related 51945) does **NOT** have the spell attribute SPELL_ATTR3_CAN_PROC_FROM_PROCS = 0x04000000, // TITLE Can trigger from triggered spells. With Earth Shield heal (56451) being a triggered cast, this means Earth Shield will never trigger Eearthliving Weapon.

Yes exactly that is what is bugged with it. It looks like to me that you didnt even read what my report says. 
Earth shield should never proc earthliving weapon which is what i stated in my bug report but yet you seem to think i said the opposite
https://youtu.be/PxOllZgxQ8g 
as you can see earth shield procs earthliving weapon so once again it is bugged on this server

**Comment by jeskej** [comment]
I think the underlying issue is the earth shield procs are being considered as spell casts.  They also trigger the bonus on the shaman dungeon set, "Chance on spell cast to increase your spell power by 95 for 10 sec".

**Comment by Never6** [comment]
https://www.youtube.com/watch?v=zHTklnfm9vU&ab_channel=vladoportos
found this hard video from 2010 hard to tell because this guys UI sucks lol but it looks like earthliving is never procced after an earth shield proc is consumed except for One instance where chain heal landed right as a charge was consumed so its safe to assume that it proc'd from chain heal not earth shield
