### ISSUE TITLE
Boat in Ironforge Tram

### ISSUE THREAD

**Issue by diablokelso** [chromiecraft/chromiecraft#2564]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I arrived in Ironforge via the tram from Stormwind. Upon arrival I was pushed off of the tram by a boat that should be in the harbor of Stormwind I believe. The boat is sitting from North to South, blocking the tram closest to the entrance. It physically appears to be there as it cannot be walked through. 
![Boat](https://user-images.githubusercontent.com/96079386/145869012-fa22d68b-3bff-4e40-9678-a713e65315ce.png)

### Expected Blizzlike Behaviour

There should not be a boat in this area. 

### Steps to reproduce the problem

Randomly arrived in Ironforge via tram.
Leaving and entering made the boat disappear. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Windows

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. That's hilarious issue. Can't reproduce something like this on AC. Can you add more info? Have you used boats before this happend? Have you used hearthstone? Maybe something else?

**Comment by diablokelso** [comment]
I have not been on any boat yet! This was a level 12 human male mage. I had
gone from IF to Stormwind to do the level 10 mage quest, turn in hogger
claw, and the gold pick up schedule. Did the collector and mage quest,
turned them in, then went to IF via tram from SW and it occurred at that
point.

I stayed for a few minutes, then left and reentered and it was gone.

**Comment by Stump876** [comment]
This is actually a common thing across many of the servers I've been on. Sometimes it's a zepplin. I'm not sure what causes it, or how to reproduce it. I want to say it's something to do with camera angles, and where the tram is.

**Comment by cachocarne** [comment]
Seen this hilarious bug in other pservers. I always thought it was due to a corrupted texture/model file. I got a clean version and never had that again. Perhaps next time you find a boat/zep you could ask other players to go there and check if they see it too?

**Comment by Stump876** [comment]
> Seen this hilarious bug in other pservers. I always thought it was due to a corrupted texture/model file. I got a clean version and never had that again. Perhaps next time you find a boat/zep you could ask other players to go there and check if they see it too?

If you look at the chat in the first screen shot, the gnome can see it while the human can't. That was the reason for the screenshot.  The solution just confirms this is a client side issue.
