### ISSUE TITLE
[Herbalism][Badlands] Multiple faulty herb nodes present in Badlands at different coordinates

### ISSUE THREAD

**Issue by mturca** [chromiecraft/chromiecraft#257]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

 Purple Lotus Herb Node spawn inside texture making it unreachable.
 
 11477 (Entry:142140) - [Purple Lotus X:-6068.040039 Y:-3239.810059 Z:259.058990 MapId:0]     
 15792 (Entry:142140) - [Purple Lotus X:-6103.000000 Y:-3212.000000 Z:257.062988 MapId:0]  

For the Purple Lotus nodes - not sure if the cave entrance that can be seen in front leads to them and they are actually inside the cave :( to low level to test.

Fadeleaf multiple nodes present in a small area, 2 nodes appear on the minimap - running the object command shows an extra one in the same range.

7693 (Entry: 2042) - [Fadeleaf X:-6637.000000 Y:-3680.000000 Z:256.833008 MapId:0]
7641 (Entry: 2042) - [Fadeleaf X:-6632.000000 Y:-3681.000000 Z:256.833008 MapId:0]
7711 (Entry: 2042) - [Fadeleaf X:-6618.000000 Y:-3691.000000 Z:256.833001 MapId:0]

Khadgar's Whisker - multiple nodes present in a small area, not sure if they should share the pool with the other 2 herb node found in proximity (check minimap in Khadgar Whisker attachment) but definitely should not be so many herbs in the same area

8114 (Entry: 2043) - [Khadgar's Whisker X:-7024.000000 Y: -2931.000000 Z:241.677994 MapId:0]
7927 (Entry: 2043) - [Khadgar's Whisker X:-7018.000000 Y: -2918.000000 Z:241.667007 MapId:0]

Firebloom / Goldthorn should be sharing spawn pool but they are all up

12275 (Entry:2866) - [Firebloom X:-6659.000000 Y: -2623.000000 Z:247.929001 MapId:0]
9003 (Entry:2046) - [Goldthorn X:-6649.000000 Y: -2645.000000 Z:248.714996 MapId:0]
9130 (Entry:2046) - [Goldthorn X:-6641.549805 Y: -2623.449951 Z:256.691986 MapId:0]

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Herb node should not be spawn underground in an unreachable location and pools should share spawn not be all up at the same time.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Advance to Badlands at the above mentioned node coordinates
2.  Notice the spawn behavior of the mentioned Herb node pools

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment]
![Firebloom](https://user-images.githubusercontent.com/47978220/111868708-24bd3480-8984-11eb-80cd-c283700ef64f.jpg)
![Khadgar Whisker](https://user-images.githubusercontent.com/47978220/111868709-25ee6180-8984-11eb-9198-183e2de55b55.jpg)
![Fadeleaf](https://user-images.githubusercontent.com/47978220/111868710-2686f800-8984-11eb-8171-d23968dbce1a.jpg)
![Purple Lotus ](https://user-images.githubusercontent.com/47978220/111868711-271f8e80-8984-11eb-975e-75a048539d23.jpg)

Picture with the location / coordinates and how it shows on the minimap added

**Comment by nolt** [comment]
11477 (Entry:142140) - [Purple Lotus X:-6068.040039 Y:-3239.810059 Z:259.058990 MapId:0] - fixed
15792 (Entry:142140) - [Purple Lotus X:-6103.000000 Y:-3212.000000 Z:257.062988 MapId:0] - it spawns in poper place

**Comment by nolt** [comment]
Fadeleaf spawns in three places randomaly - its not a bug

**Comment by nolt** [comment]
Firebloom / Goldthorn share same pool. On 5 ws restart only 1 time they came up all of them. But while Goldthorn are too close to each other, one of them is removed.
