### ISSUE TITLE
[Quest item display error] - Crudely-written Log (12842) - (Minor interface bug)

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#2570]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

When killing the [Winterfall High Chief](https://classic.wowhead.com/npc=10738/high-chief-winterfall) -required for "[High Chief Winterfall](https://classic.wowhead.com/quest=5121/high-chief-winterfall)"– we get also the [Crudely-written Log](https://classic.wowhead.com/item=12842/crudely-written-log) item dropping, which starts a quest and therefore appears with an exclamation mark on its icon. 

We take this item to Donova Snowden, who then gives us a new quest, "[Words of the High Chief](https://classic.wowhead.com/quest=5128/words-of-the-high-chief)".
It is then when the item, which should be a "normal quest item" in our inventory shows an interface bug, because it shows the "!" mark as if it was a quest that we can start. 

![ 2021-12-14 at 10 58 47](https://user-images.githubusercontent.com/77953030/145957695-57f58167-985b-4a14-952d-3dffebdf35b6.png)

### Expected Blizzlike Behaviour

Once we accept "Words of the High Chief" and receive the item from Donova Snowden to bring it to Felwood, it should not show any exclamation symbol indicating that we can start a quest. 

### Steps to reproduce the problem

Have an Alliance character of at least level 52
Get item [ 12842 ] to start quest
Start quest [The Final Piece](https://classic.wowhead.com/quest=5123/the-final-piece) (5123)
Complete quest at [Donova Snowden](https://classic.wowhead.com/npc=9298/donova-snowden) (9298)
Receive next quest [Words of the High Chief](https://classic.wowhead.com/quest=5128/words-of-the-high-chief) (5128) from Donova Snowden and get the item in your inventory
Observe item still has "!" symbol

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
I do understand the issue and can confirm it. There is need some research about this behavior. Other items with same mechnic or maybe this is even blizzlike.
![WoWScrnShot_121621_163723](https://user-images.githubusercontent.com/85256266/146382045-922e6788-89a4-4e49-af24-741dab6bee62.jpg)

**Comment by temperrr** [comment]
This video shows its the same on wow classic:
https://youtu.be/cx1iAcNgaZg?t=6

This seems to be the correct behaviour
