### ISSUE TITLE
Rogue Vanish - Bugged

### ISSUE THREAD

**Issue by Lac-lol** [chromiecraft/chromiecraft#2574]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

As of now it seems random when Vanish works like it's supposed to and when it don't.

When Vanish doesn't work: 
Mage casts frostbolt on you --> You Vanish when frostbolt is mid-air --> You get hit by frostbolt

### Expected Blizzlike Behaviour

Vanish is supposed to "Vanish" spells cast mid-air.
This can be found in almost every 3.3.5 rogue PvP video and is known as a common mechanic of this spell.

When Vanish works like it should:
Mage casts frostbolt on you --> You Vanish when frostbolt is mid-air --> You "Vanish" the enemy casted projectile and stay in vanish.

### Source

I'm not sure what to write here. The issue is known.

### Steps to reproduce the problem

1. Make rogue --> Learn Vanish
2. Make a test were enemy players cast projectiles onto you
3. Try to Vanish when the projectiles are mid-air and see if they hit or not
4. I'm not into bug-fixing, so I'm not sure what more to add.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Windows - Generic / Don't matter

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Lac-lol, Thanks for the report. The purpose of the source is to have objective evidence (preferable from 3.3.5 era) of how it should work, or where you're getting your information from. While I do believe you, "It's known" doesn't hold up as a reliable source when we send the issue over to the devs.  If you can you find one of the PVP videos of a rogue doing it from 3.3.5, that would work.

**Comment by Lac-lol** [comment]
Hey,
It's quite challenging to find actual footage from 2008-2009/2010 on this specific topic, but here is what I found so far:

Rogue Vanish patch 3.3 (Wotlk / Retail).
https://www.youtube.com/watch?v=srwTw3BoU3s

This video is actually from a private server I played on personally back in 2012: Light of Chaos 3.3.5 level 60.
This shows Vanish used to dodge out Death Coil from a warlock.
https://www.youtube.com/watch?v=8zi2fitKQnA

Vanish has also worked this way on Blizzard's "Retail WoW" pretty much forever and the issue is only found on a few private servers, were we now are and hopefully can get fixed! <3
https://www.youtube.com/watch?v=HygrNfilUmE

Thanks

Lac,

**Comment by Shineslippers** [comment]
Thank you for the report. After some test what i can say:

1. Immunity to spells does work and lasted some time after vanish cast
2. Due to `1` if you pressed Vanish too early immunity window will close

So do not press it too early to prevent it.

https://user-images.githubusercontent.com/85256266/146401913-35622fa8-b35d-4e2e-a97b-f6251a7ce595.mp4
