### ISSUE TITLE
(Quests) Proving Allegiance  /  The Dormand Shade 

### ISSUE THREAD

**Issue by SolidWolf89** [chromiecraft/chromiecraft#2575]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

CHAIN OF QUEST:
Quests:
https://wowgaming.altervista.org/aowow/?quest=409
https://wowgaming.altervista.org/aowow/?quest=410

NPC Bug:  Lillith Nefara
https://wowgaming.altervista.org/aowow/?npc=1946

This NPC of the quest "Proving Allegiance" she should be able to be summoned with "Candle of Beckoning" (https://wowgaming.altervista.org/aowow/?item=3080) in the object "Lillith's Dinner Table" (https://wowgaming.altervista.org/aowow/?object=1557) completing the mission "The Dormant Shade" (https://wowgaming.altervista.org/aowow/?quest=410). When completing this last task with the candle, what should happen is that the NPC Lillith Nefara (https://wowgaming.altervista.org/aowow/?npc=1946) is summoned for 3 minutes (which does not happen).

### Expected Blizzlike Behaviour

Search: Proving Allegiance Quest WoW Classic

https://www.youtube.com/watch?v=C56qIn3IBME&ab_channel=WoWQuests

### Source

Sources: wowhead and wowgaming.altervista.org
Quests:
https://wowgaming.altervista.org/aowow/?quest=409
https://wowgaming.altervista.org/aowow/?quest=410
NPC Bug:  Lillith Nefara
https://wowgaming.altervista.org/aowow/?npc=1946
Link to video:
https://www.youtube.com/watch?v=C56qIn3IBME&ab_channel=WoWQuests

### Steps to reproduce the problem

Only by doing the mission it is seen that the NPC that should appear (be summoned by completing the mission) after delivering the candle never appears.

44782 / (Entry: 1557)

### Extra Notes

All the link is up! ;)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

I have a windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. Sorry about this inconvenience, but it's known issue. Hope it will get fix soon. Update of the script loader going not like it planned.
