### ISSUE TITLE
[Quest] Locked Away - Farmer Dalson does not spawn

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#2578]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

When turning in the quest "Locked Away" at the Outhouse, Farmer Dalson does not emerge from the ground. This makes completing a nearby quest impossible, as Farmer Dalson drops a required quest item.
https://wowgaming.altervista.org/aowow/?quest=5059
https://wowgaming.altervista.org/aowow/?npc=10836

### Expected Blizzlike Behaviour

When turning in the quest at the Outhouse, Farmer Dalson should emerge from the ground as seen in this video from retail WoW Classic: https://youtu.be/ncBbzUc73TM?t=738

### Source

https://classic.wowhead.com/quest=5059/locked-away#comments

### Steps to reproduce the problem

1. Go to Dalson's Tears (field) in Western Plaguelands.
2. Complete quest 5058
3. Obtain Dalson Outhouse Key (12738) from Wandering Skeleton nearby
4. Turn in quest at the Outhouse near the barn and house

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. Sorry about this inconvenience, but it's known issue. Hope it will get fix soon. Update of the script loader going not like it planned.
.
