### ISSUE TITLE
[Silithus Quest missing] Huum Wildmane that starts quest chain for Duke summoning is missing

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2583]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

NPC that starts quests in order to summon DUKES is missing still https://classic.wowhead.com/npc=15270/huum-wildmane
https://classic.wowhead.com/quest=8331/aurel-goldleaf

### Expected Blizzlike Behaviour
https://classic.wowhead.com/npc=15270/huum-wildmane
https://classic.wowhead.com/quest=8331/aurel-goldleaf

### Steps to reproduce the problem

1. Get to Cenarion Hold
2. https://classic.wowhead.com/npc=15270/huum-wildmane Missing he starts chains to talk to Aurel for dukes
2. No NPC that can give you quest to continue summoning higher level mobs (DUKES)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
He is staying in a different place
![WoWScrnShot_121521_182953](https://user-images.githubusercontent.com/85256266/146215535-515ff795-06df-49f4-a29e-272df1f51c33.jpg)

**Comment by Elexias** [comment]
Literally you're making me make 0 reports for this. You're making me look like moron in front of others.
NPC was not implemented at the time, maybe you were sleeping when staff decided to run lvl 60. Report was made the moment he wasn't implemented.

**Comment by Shineslippers** [comment]
Well. NPC wasn't there before because of progression mod. With launch of 60 bracket he is present. Don't understand how it makes you moron, but report anyway by mentioned above reasons invalid. Doesn't see anything bad.

**Comment by Elexias** [comment]
No, NPC wasn't with launch of 60 bracket. He was implemented 2 hours after launch. Check with other staff members.

**Comment by Shineslippers** [comment]
Ok, maybe, but what i'm doing wrong?

**Comment by Elexias** [comment]
Give me credit for report, since he is implemented after my report.

**Comment by Hacki95** [comment]
No reason to get heated here.

He was indeed missing after the restart in the evening. I temp respawned him and on the next restart he should be back at his normal spawn.
