### ISSUE TITLE
[Silithus - Templar] Crimson Templar doesn't drop Abyssal Crest properly should be 100%

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2584]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

![image](https://user-images.githubusercontent.com/80590226/146186441-4b5f1c3a-460b-41ef-b078-9258449ced95.png)

Didn't drop Abyssal Crest and it should be 100%

### Expected Blizzlike Behaviour

Didn't drop Abyssal Crest and it should be 100%

### Steps to reproduce the problem

1. Summon Templar in Silithus
2. Have a chance of not getting crest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Drop rate of is high, but not 100%. If you have any source that can help i will be appreciate.

| name | entry | Item | chance | 
| --- | ---: | ---: | ---: | 
| Crimson Templar | 15209 | 20513 | 83,7314 | 
| Azure Templar | 15211 | 20513 | 83,5982 | 
| Hoary Templar | 15212 | 20513 | 83,8428 | 
| Earthen Templar | 15307 | 20513 | 83,9362 |

**Comment by godnesso** [comment]
It is common knowledge that Templars/Dukes/Lords drop a Crest/Signet/Scepter guaranteed, while everything else they drop is not. These templars are the only source of Abyssal Crests and virtually no guide involving Abyssal Summonings on the internet suggests that the drop rate is below 100% (example is total mats required to summon Abyssal Lords where a chance of not dropping crest is never mentioned, see https://classic.wowhead.com/item=20515/abyssal-scepter#comments:id=2657861).
If you want anecdotal evidence, I've killed hundreds of these on Classic and they always drop the items in question. You will find  it is impossible to find proof of these items not dropping. I assert that the incorrect %chance used here was transferred from database like wowhead where these user errors often occur when info is submitted

**Comment by j-hdt** [comment]
can confirm the issue
see also
[https://db.rising-gods.de/?item=20513](https://db.rising-gods.de/?item=20513)

**Comment by godnesso** [comment]
Any news on this? I can link dozens of videos where Crest/Signet/Scepter will drop because it is 100% drop rate - it's the main reason to kill these summoned bosses and these items are "proof" that you kill them. I don't really understand how more research needs to be put into this

**Comment by Elexias** [comment]
They expect some kind of source while they don't want to buy account from Blizzard and kill a templar there.
