### ISSUE TITLE
[Dire Maul East] Warpwood Pods spawning tons of mobs when passing near them

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2585]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

We did DME on level 60, we wiped multiple times because Warpwood Pod kept spawning mobs when we pass near it, it should dissapear once it summons them

### Expected Blizzlike Behaviour

https://classic.wowhead.com/object=179526/warpwood-pod#comments

These little green pods are found all over DM East and do one of the following randomly when you open them/approach them:

1) Spawn little 5-6 little mobs (https://classic.wowhead.com/?npc=13022)
2) Poisons you (a nature DoT)
3) Yields either Runn Tum Tuber (https://classic.wowhead.com/?item=18255), used in the recipe Runn Tum Tuber Surprise (https://classic.wowhead.com/?spell=22761) and/or Thornling Seeds (https://classic.wowhead.com/?item=18297)
4) Does nothing at all

### Steps to reproduce the problem

1. Get to DME
2. Get near Pods

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report, but it's known issue https://github.com/azerothcore/azerothcore-wotlk/issues/8929 . I have to close this report accordingly.
