### ISSUE TITLE
[Dungeon Set Quest]  [The Left Piece of Lord Valthalak's Amulet]

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2587]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Quest line from Dungeon Tier 2 
https://classic.wowhead.com/guides/dungeon-sets-1-2-quests-wow-classic#part-4-helm-and-chest
Part to summon and kill 
 The Left Piece of Lord Valthalak's Amulet: Stratholme Live.
You'll need to kill Jarien and Sothos.
These two are summoned using the  Brazier of Beckoning in Balnazzars room.
Killed them no loot of Left Piece of Amulet
![WoWScrnShot_121521_145805](https://user-images.githubusercontent.com/80590226/146200058-75dad0cf-d9f9-4908-b9c0-4d455b46e8d3.jpg)
![WoWScrnShot_121521_145717](https://user-images.githubusercontent.com/80590226/146200061-fbd9c3a4-48ec-4407-86bc-ace8dac3c5fd.jpg)
![WoWScrnShot_121521_145635](https://user-images.githubusercontent.com/80590226/146200062-11ba0476-13b0-4c41-a35d-1cdcd8b15479.jpg)
![WoWScrnShot_121521_145605](https://user-images.githubusercontent.com/80590226/146200066-c1f235d7-0c72-4afe-9217-0848306a7e37.jpg)

### Expected Blizzlike Behaviour

Point of quest is to get 100% from them, you summon once you kill you get quest item.

### Steps to reproduce the problem

1. Summon those mobs with proper item after killing Balnazzar
2. No quest item loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
https://wowgaming.altervista.org/aowow/?npc=16101#drops

**Comment by Elexias** [comment]
![WoWScrnShot_121521_151952](https://user-images.githubusercontent.com/80590226/146203488-da4b145b-b2cd-469b-b616-5d818f2898af.jpg)
![WoWScrnShot_121521_151921](https://user-images.githubusercontent.com/80590226/146203492-abe0a1a9-614b-45c9-a946-80275294bb43.jpg)
![WoWScrnShot_121521_152034](https://user-images.githubusercontent.com/80590226/146203497-385cead2-4101-483e-b166-23c76cc59cf1.jpg)

**Comment by Elexias** [comment]
Tried once again.
No loot.

**Comment by Shineslippers** [comment]
Yea, thank you for the report. We're trying figure out what's going on.

**Comment by Elexias** [comment]
Edit. As issue not related to this quest or NPCs and we have some other reports. I have to close it as duplicate. We found that causing it and working on a fix.

Give me the link of those issues, you keep closing my issues, I wanna see it.

**Comment by Shineslippers** [comment]
I don't understand why you see something personal in my decisions.
https://github.com/chromiecraft/chromiecraft/issues/2581
https://github.com/chromiecraft/chromiecraft/issues/2582
