### ISSUE TITLE
Pet talents bugged on Devilsaur

### ISSUE THREAD

**Issue by Reilith** [chromiecraft/chromiecraft#2588]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Can't use pet talents after getting the 60 talent Beast Mastery. Haven't tested with other exotic pets but currently Devilsaur isn't working. 

### Expected Blizzlike Behaviour

Press the talent and it applies

### Steps to reproduce the problem

Try to click on the talents
It doesn't work

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report, but i can't reproduce it on local AC. Can you please add some screenshots? Did repog solve the issue? What does `Press the talent and it applies` exacly mean

https://user-images.githubusercontent.com/85256266/146248918-9890998a-7d6c-45f1-b075-043fd4260df9.mp4

.

**Comment by Reilith** [comment]
https://youtu.be/IXuXC6SCaIU i made a video showcasing what i'm experiencing. I'll try to abandon and recapture one and see if that does anything.

**Comment by Shineslippers** [comment]
I will keep close it for now. If we will get other reports about this issue maybe we can find out roots. Also i see you're using HD-patch. You can try delete cache folder, remove patch and disable addons. Launch clean client and check out result without Prview talent.
