### ISSUE TITLE
Problem with Dungeon 2 Quest in Silithus

### ISSUE THREAD

**Issue by DougInTheBox** [chromiecraft/chromiecraft#2591]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

We're trying to complete the Duke of Cynders part of the dungeon 2 quest in Silithus. Aurel Goldleaf is not offering the quest. Wowhead says we need a quest from Huum Wildmane first, but we can't find this NPC in Cenarion Hold. Also, we are friendly with Cenarion Hold. It seems there are people further along in the quest line now. Is is possible this was broken after the update an hour or two ago? Thanks!

### Expected Blizzlike Behaviour

Huum Wildmane should be in Cenarion Hold, and give us the quest to talk to Aurel Goldleaf, which let's us continue the dungeon 2 quest line.

### Steps to reproduce the problem

1. Go To Cenarion Hold in Silithus
2. Try to find Huum Wildmane 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. He is staying in a different place. You can use command `/target huum` and place mark to see him better. To take quest you need `friendly` reputation with cenarion circle.
![WoWScrnShot_121521_182953](https://user-images.githubusercontent.com/85256266/146215535-515ff795-06df-49f4-a29e-272df1f51c33.jpg)

**Comment by DougInTheBox** [comment]
Thanks, I was using "/target Huum" and riding all over Cenarion Hold, but just couldn't find him.

**Comment by DougInTheBox** [comment]
Odd, I could have swore he was not there earlier. Oh well, thanks again!
