### ISSUE TITLE
[Upper Blackrock Spire] Blackhand Assasins not stealthed again

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2592]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

They're again broken, they were fixed for whole UBRS on lvl 59 phase, but now in raid grp they're all seen.
![image](https://user-images.githubusercontent.com/80590226/146248256-c69ef3f6-4f04-4ff2-9a20-e89d8d6bde5d.png)

### Expected Blizzlike Behaviour

They should be stealthed, and revealed upon attacking mobs near, or using aoe abilities near them

### Steps to reproduce the problem

1. Enter UBRS
2. Get to rooms of Assasins
3. See them unstealthed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
![image](https://user-images.githubusercontent.com/80590226/146248437-83c01e8e-a2f3-45f8-9eec-a22f1c6854c4.png)

**Comment by ishidinho** [comment]
Thank you for the report, Elexias.

Do you have any evidence that they really should be stealthed?

I checked some Classic WoW videos on YouTube where I did not saw them stealthed.
For example: https://youtu.be/awPyUAF2yU8?t=1344 (Blackhand Assasin is marked with skull)

On the other hand, the NPCs SmartAI indicates that they cast [Sneak](https://wowgaming.altervista.org/aowow/?spell=22766) on themselves when out of combat.
https://wowgaming.altervista.org/aowow/?npc=10318#abilities
