### ISSUE TITLE
.beta activate shortly prior server crash removes exp Bar

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#2594]
Character: Catrala

Used .beta activate about a minute before latest server crash. 
Once server was back online the exp bar was gone. 
New attempts to .beta activate said :"You are already a beta tester"

**Comment by Shineslippers** [comment]
You can try to do `.xp off` >>> `.xp on`. Anyway this is a place for report bugs. In your case better way to ask GM or visit our Discord's support channel https://discord.gg/zGfxEs5a
