### ISSUE TITLE
Empty Firewater Flask not dropping

### ISSUE THREAD

**Issue by N3rfherd3r** [chromiecraft/chromiecraft#2595]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Unable to obtain "Empty Firewater Flask" (https://wowgaming.altervista.org/aowow/?item=12771) to start "Winterfall Firewater" (https://wowgaming.altervista.org/aowow/?quest=5083) quest line. My character name is Nerfherder, level 60 Priest. 

### Expected Blizzlike Behaviour

According to https://wowgaming.altervista.org/aowow/?item=12771#dropped-by it has a 10% drop rate, however I have killed approximately 100 NPCs without the item dropping.  

### Steps to reproduce the problem

Kill any of the following NPCs:

Winterfall Den Watcher
Winterfall Pathfinder
Winterfall Runner
Winterfall Shaman
Winterfall Totemic 
Winterfall Ursa

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. You're just pretty unlucky. Tested it on local AC and got 2 of it from ~50 kills. I can confirm drop rate and NPCs, but anyway have to close this report.

| name | entry | Item | chance | 
| --- | ---: | ---: | ---: | 
| Winterfall Ursa | 7438 | 12771 | 10 | 
| Winterfall Shaman | 7439 | 12771 | 10 | 
| Winterfall Den Watcher | 7440 | 12771 | 10 | 
| Winterfall Totemic | 7441 | 12771 | 10 | 
| Winterfall Pathfinder | 7442 | 12771 | 10 | 
| Winterfall Runner | 10916 | 12771 | 10 | 

![WoWScrnShot_121621_001656](https://user-images.githubusercontent.com/85256266/146266249-6691815a-65eb-4437-a160-4f9128068541.jpg)

**Comment by N3rfherd3r** [comment]
Could it be that it's dropped for me earlier in the game and I've destroyed the item, and it won't drop twice?

**Comment by Shineslippers** [comment]
> Could it be that it's dropped for me earlier in the game and I've destroyed the item, and it won't drop twice? 

Only way if you did quest from item. Destroy can't broke it. You don't even need reputation.

**Comment by N3rfherd3r** [comment]
Ok what if it doesn't drop after 200 or 500 kills?

**Comment by Shineslippers** [comment]
I got this item several times on live server. Don't think it will happend. Anyway in this case we can ask GM to check it on CC. That's not hard so i can try tomorrow get it for my alt.

**Comment by N3rfherd3r** [comment]
I still haven't managed to obtain this item, is it possible to have this
issue looked into further? Without this quest I cannot obtain the trinket I
need as a BiS item.

Kind regards,

*L. Artley*



*Lt Luke Artley BSc (Hons) IEng MIET CMgr MCMI GCGI RITTech MBCS RN*

**Comment by Shineslippers** [comment]
I do understand your issue, but idk what i can do else. Investigation is possible when you have something to investigate. I can not reproduce your issue. I have no objective of investigation. Item dropped to me without any quests and with unfriendly reputation.
Are you sure you didn't get it before? You can download addon `EveryQuest` for example. It can show completed quests by you. Maybe you will find some of quests from Empty Firewater Flask line https://wowgaming.altervista.org/aowow/?quest=5083 line.
