### ISSUE TITLE
Shaman: Cleansing Totem

### ISSUE THREAD

**Issue by Hidehugo** [chromiecraft/chromiecraft#2597]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Cleansing Totem removes no poisons/diseases on placing the totem

### Expected Blizzlike Behaviour

Placing Cleansing totem should tick its periodic effect on placing the totem, e.g. a poison is being applied on the group and the shaman presses the cleansing totem once to remove it from the whole group instantly.

### Source

I've found PVP content of wotlk season 6, where placing the totem removes a wound poison off of a teammate at 2:29 into the video (source: https://www.youtube.com/watch?v=dwJwSdj5OOg). I've researched the patch notes of "Cleansing Totem" and where it is listed and the only entry there is from 3.1.0 where it is said that the previous Disease Cleansing Totem and Poison Cleansing Totems are merged and the pulse time is reduced (https://wowwiki-archive.fandom.com/wiki/Cleansing_Totem_(shaman_ability)). Since the behaviour of the "dispelling when placed" is/was implemented that way in Vanilla as well as TBC and there is no changelog mentioning any changes + the video evidence, i think that this is wrongly implemented. If you have sources otherwise i am happy to be proven otherwise :)

### Steps to reproduce the problem

1. be a shaman with Cleansing Totem
2. go to an area where mobs cast a Poison effect on you, e.g. Duskwood's Pygmy Venom Web Spider or disease by Black Widow Hatchling
3. put Cleansing Totem down
4. watch it only dispel the poison/disease after 3 secs and not on placing

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Windows 10

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment]
it doesnt work instantly same with tremor
it pulses every 3 seconds just like tremor

**Comment by Hidehugo** [comment]
> it doesnt work instantly same with tremor it pulses every 3 seconds just like tremor

Incorrect. Any shaman player from vanilla, classic, wotlk will tell you otherwise since the totem would be considered worthless for pvp then.
Proof: https://wowwiki-archive.fandom.com/wiki/Tremor_Totem    - Section "Tips" , 3rd paragraph: "This totem will immediately remove any applicable ailments when it is first down, ..."
Video proof of arena tournament server working that way: https://www.youtube.com/watch?v=uat_L7iHvhI&t=1s  - at 18:47 the shaman of the Warrior/Paladin/Shaman team trinkets the physic scream to put down tremor in order to remove the fear from the paladin. But honestly i think everybody who ever played shaman knows that by now and i am 100% sure you can find tons of evidence on tremor working like that so i have no clue where your comment comes from or wether it is a troll comment.

I found another example of the cleansing totem working as i expected it to work in the video first video of Kollektiv at 7:20 (Shaman has 2 wound and crippling poison up, drops totem and one of the totems gets dispelled instantly) and at 8:50 (shaman going out of ghost wolf to replace totem for the instant cleansing effect on crippling poison) or 14:43 (shaman spamming the cleansing totem to get both poisons off)

**Comment by Hidehugo** [comment]
Are we watching the same video? Apart from the first clip and the clip from 7:35 to 8:11 which seemed to be pre 3.1 (where the merging of poison cleanse and disease cleanse took place) the player is using cleansing totem and the timestamps prove that the totem behaved like the totems before: cleanse on drop and then periodically cleanse on the pulse timer.
IF there were a change to the totem behavior, don't you think there would be a patch note/comment on it on the archives?

Is this forum full of trolls who say "i don't think so despite the evidence and i have no way of disproving your thesis so i say: no proof" or will somebody actually put out some conclusive information like i did to disprove me?

**Comment by Plasmashield** [comment]
First video. He never used a cleansing totem. By the fact that this is before patch 3.1, this is season 5

**Comment by Plasmashield** [comment]
https://youtu.be/z782OeoK7BQ
5:34 He placed totems. Still 3 poisons on priest.
5:37 dispelled one.
5:40 another one.
But you can still try to find proof

**Comment by Hidehugo** [comment]
The Icon of Cleansing Totem is the same as of Disease cleansing totem and only in 2 of the > 10 clips in the video he has to use poison cleansing totem because it seems to be pre 3.1. The fact that his "G"-buttoned macro is called "clean..." as a modifier macro should give it away, otherwise it was called "LS FRT" for a modifier macro with cleansing and fire resistance totem as well as lightning shield. 
I can't see how you can write "He never used a cleansing totem" when it is clearly placed. If your assumption were correct and this was before 3.1 and the totem he dropped was the disease cleansing totem (as you can see on the totem bar below the player bar), then the player in the video (who clearly knows what he's doing) would be using a useless totem that in turn should not be able to cleanse anything except diseases. 
It being season 5 is not really a thing either except for the clips that i stated ( first one and 7:35 to 8:11) because the tournament that the video is about (arena tournament 2009) was in august of 2009, so it was 4 months after season 5 has ended (12/2008 to 4/2009, where Patch 3.1 was released and the totems were merged). My guess to the two clips is: either they were taken while the regular season or the totems on the tournament server were fucked up since they reverted to values of season 5 to make the tournament even (as they did lateron as well for some tournaments afaik) but this is speculative. It is still only 2 clips out of more than 10, where i have timestamped the normal behavior of the totem dispelling when dropped.

To your video: The totem placement not dispelling any poison doesn't really say anything to the matter though because most of the classes have a dispel protection talent like rogues with their "Vile poisons" talent, giving them 30% chance to resist the dispel on deadly poison which in turn then kind of "covers" the other poisons from being dispelled. So your video doesn't disprove nor prove anything unfortunately.

To the matter of tremor not removing fear on totem drop: 
https://www.youtube.com/watch?v=GiDCzWfr4Qg - season 7
6:55 dispelling fear with tremor totem 

I'm not gonna search out for more clips now if there is not some proper answer to the matter, else you can live with the totem being wrongly implemented, making shaman just a shadow of what it is supposed to be since i've given enough evidence to have at least reasonable doubt about the implementation and even an argumentation for it to be changed to the way i remember it from my playing back then
Cheers

**Comment by Plasmashield** [comment]
I don't understand wtf are you talking about. Shaman used Disease Cleansing Totem against shadow priest and manually dispel poisons. After 3.1 only one totem left - Cleansing Totem. When u see Poison Cleansing Totem - this is before the patch 3.1. Also he used s5 weapon.

**Comment by Hidehugo** [comment]
As i wrote in the first bug report: at 2:28 a cleansing totem is dropped which removes the wound poison on the rogue teammate of his. 
I think what you're not seeing is that i did not reference onto the clips where there is still a Poison Cleansing totem but yet you just bring it up like it has anything to do with the discussion of the mechanic of the totem being different in the video in comparison to the implementation on the server. As i said, either show me that chromiecraft has it implemented right by showing why my footage is wrong or stop arguing about formalities. The point is about the totems not dispelling on being cast and nothing more

**Comment by jeskej** [comment]
I thought it was also weird cleansing didn't remove poison/disease on placement, but I did find this site:

https://www.engadget.com/2009-09-24-totem-talk-patch-3-2-2-and-you-if-youre-a-shaman.html

That mentions it was changed in 3.2.2 - _Cleansing Totem: No longer pulses instantly when dropped._

I couldn't find it on the wow wiki patch notes site, but Wowhead also had it listed:

https://www.wowhead.com/patchnotes=3.2.2

**Comment by Hidehugo** [comment]
All clear, thanks for clearing it up man :) 
even on the pages that you posted my browser only shows me "#spell8170" which is cleansing totem, so no wonder my search didn't find that. Ok so they just drive-by destroyed cleansing totem in a side-patch, nice, didn't remember

Anyways, can close the topic now, cheers
