### ISSUE TITLE
[Upper Blackrock Spire] Blackhand Veteran dropping lower level item than intended

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2599]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

![WoWScrnShot_121621_095201](https://user-images.githubusercontent.com/80590226/146339309-d91caf11-6d4f-4867-988e-1043dc60917c.jpg)

Item for level 47 dropping from level 60 elite. Not in loottable even from Vanilla/WoTLK databasse

### Expected Blizzlike Behaviour

https://classic.wowhead.com/item=14673/pridelord-cape#dropped-by;0+3-10-9+1
https://wowgaming.altervista.org/aowow/?item=14673

### Steps to reproduce the problem

1. Get to UBRS
2. Blackhand again having bad loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
We are currently doing more research on this subject. What i will say is the loot is in our reference loot template and does match up with the UDB exactly so there is no inaccuracy dealing with loot tables dealing with item. It is however will be a topic for us to research and figure out if item scaling or bonus ids are to be applied based on player or party size.

**Comment by acidmanifesto** [comment]
@Nyeriah What could be done with this issue we have with the item levels?

**Comment by FrancescoBorzi** [comment]
> he loot is in our reference loot template and does match up with the UDB exactly so there is no inaccuracy dealing with loot tables dealing with item

closing as I don't think we are going to do much about this specifically
