### ISSUE TITLE
Quest Turn-in Icon on Elders (Lunar Festival)

### ISSUE THREAD

**Issue by Knewklear** [chromiecraft/chromiecraft#26]
##### SMALL DESCRIPTION:

The quest turn-in icon is still on the NPC after turning in their quest. The particular mob in question is Elder Goldwell in Kharanos but it's safe to assume this problem goes for all elders.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once you turn in the quest, the turn-in icon should disappear from the top of the NPC.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
The fix is now on ChromieCraft. Thanks for your report.
