### ISSUE TITLE
Kobold named Unknown in Fargodeep Mine

### ISSUE THREAD

**Issue by BrodieSinn** [chromiecraft/chromiecraft#260]
##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

A kobold in the Fargodeep Mine is named Unknown, it does not have the silver portrait of a rare mob, it just is named Unknown. The rest of the kobolds in the mine were named normally. Screenshot attached.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I assume it should have a normal name of some type and not be "Unknown"

##### STEPS TO REPRODUCE THE PROBLEM:

1. Goto Fargodeep Mine and look for a kobold named "Unknown"
![kobold](https://user-images.githubusercontent.com/77343625/111874816-dc424e80-8964-11eb-95e9-573a83a792b1.png)
![map](https://user-images.githubusercontent.com/77343625/111874829-e95f3d80-8964-11eb-96a2-b8e30459b8c3.png)

2. 
3. 
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
In the DataBase does not exist an NPC in the database with the name "Unknown", probably it was a temporary bug for load/connection issues, if you encounter it again post a comment

**Comment by illfated** [comment]
"Unknown" as NPC name or player/pet name is a game client bug 99% of the time (communication lag between server & game client).

**Comment by Stifler82** [comment]
or just delete cache folder..
