### ISSUE TITLE
Skining mobs issue

### ISSUE THREAD

**Issue by Szudro718** [chromiecraft/chromiecraft#2611]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Observed weird thing about skining beasts at the moment when killed dozens of them in barrens this morning to increase skill in skining. The point is some mobs which probably dont drop loot cannot be skinned. This is my and other players who whispered me theory.
![WoWScrnShot_121721_115554](https://user-images.githubusercontent.com/25100993/146539544-cae2e63c-fb55-4d42-b68e-1a8884cfd664.jpg)
![WoWScrnShot_121721_115600](https://user-images.githubusercontent.com/25100993/146539550-a9f3b83e-7d85-4cf5-a6e4-df42a0d2c60d.jpg)
![WoWScrnShot_121721_120143](https://user-images.githubusercontent.com/25100993/146539559-60468cb3-208b-4d47-a16e-b357e2ca8b5a.jpg)
 

### Expected Blizzlike Behaviour

Make lootless uniteractive corpses of skinnable creatures actaully skinnable.

### Steps to reproduce the problem

Currently can see that on last screen there is 3 raptors i killed and can't skin any of them. Maybe they really have no loot in corpse and that's the issue because corpse is uninteractive at this moment, but should still be skinnable for players with skining profession.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by hesperis17** [comment]
I have the same issue. Some beasts both in Tirisfal Glades and Durotar can't be skinned.
![Screenshot at 2021-12-19 16-47-04](https://user-images.githubusercontent.com/96421031/146759272-0db9859e-1124-45ac-b603-e2f6e9436dfd.png)
