### ISSUE TITLE
Double ore spawns (Silver and Tin) in Loch Modan

### ISSUE THREAD

**Issue by CMHWoody** [chromiecraft/chromiecraft#2613]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Entering this zone I found that every single tin/silver node, had both ore types spawned on top of each other and there were LOTS of these all over, allowing players to accumulate way too much silver and gems (which drop more frequently from silver). 

See this brief video of the double nodes (and I even saw one with copper, tin, and silver all stacked):

https://www.screencast.com/t/8Cm7Gem0lj

Additionally, it appears that many normally Copper nodes spawn as tin and silver as well. The zone is dominated by ludicrous amounts of silver.   Using data from gathermate, and displaying this data in Carbonite map, it seems to confirm that normally copper nodes are incorrectly spawning tin/silver.  There are some copper nodes, but not many.

### Expected Blizzlike Behaviour

I would expect these ore types to share a pool with only one spawning at at time, and tin to be far more common with silver being rare.  I would also expect copper to be much more common, but it's very uncommon throughout the zone.

### Steps to reproduce the problem

Nothing required to duplicate but enter the zone and see all the ore spawns

### Extra Notes

I found this fix for similar issues reported earlier this year:

https://github.com/azerothcore/azerothcore-wotlk/pull/7430

However, the notes on that issue indicate that many ore nodes through the game were fixed, however, I see no mention of nodes in Loch Modan and those appear to still be a problem.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by chaossonic** [comment]
Can confirm, almost all ore nodes in Loch Modan are double spawning.  Typically Tin/Silver or Copper/Tin or Silver.
