### ISSUE TITLE
Bugged in combat after mind control

### ISSUE THREAD

**Issue by Kike457** [chromiecraft/chromiecraft#2614]
### What client do you play on?

esES

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

After I mind control a mob in a fight, I stay in combat when it ends

### Expected Blizzlike Behaviour

I should not stay in combat

### Steps to reproduce the problem

Mind control a mob and kill it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Thank you for the report, Kike457.

Do you have any sources to prove your theory?

After some research I am pretty sure that the named behavior is intended.

> Mobs within aggro range of an MCed target will regard it as hostile - they have no qualms over beating up a unit that was a trusted ally only moments before, so you can mind control something and let the surrounding 'linked' NPCs kill it. Note, however, that if the MCed target is freed from your control, they will once again regard it as a friend and will immediately seek another hostile target to attack - which may be you.
Source: https://vanilla-wow-archive.fandom.com/wiki/Mind_Control

Which means, if the MC breaks (either by end of casting or death), infight enemy will attack you. You can see this behavior [here](https://youtu.be/aZHiciTRwyo?t=157).

Furthermore, I think there is a simple logical reason for this behavior. If enemies do not start attacking you after your MCed target dies, it will give you the possibility to solo whole raids to farm the trash, e.g. Zul'Gurub.

**Comment by Shineslippers** [comment]
Previous behavior of Mind Control where it not granting combat was fixed in https://github.com/azerothcore/azerothcore-wotlk/issues/8938 Now it works as intended
