### ISSUE TITLE
Silithus - Abyssal Council various issues

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#2619]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Abyssal Council summoned boss does not automatically engage in combat with summoner.

Abyssal Council summons (Templars, Dukes, Lords) are not automatically tagged for the summoner and his group, which enables outside players to steal the tag and waste summoner's materials.

Abyssal Council summons do not despawn when a wipe occurs (mob resets by being kited too far or because group dies).

### Expected Blizzlike Behaviour

When a player summons a templar, duke or lord via Wind Stone in Silithus, the summoned boss should automatically engage in combat with the summoner after his short RP.

The summoned boss should be automatically tagged for the summoner (and his group) when boss engages in combat.

When the summoned boss resets, the boss should immediately despawn - players only get one chance to defeat it.

### Source

Tested on retail TBC Classic, behaviour will be the same all throughout the game versions. I have video proof but don't want to put my char name in here with video, idk how to edit this

### Steps to reproduce the problem

Get Twilight Cultist set and test on a Lesser Wind Stone in Silithus, you need 2 players not in the same group to test tag issue. You will also see that boss does not engage when summoner is further away and boss does not despawn after wipe/reset.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
If you have a video you can send link to me in discrod. I;m not sure i can confirm everything without your sources. Despawn of boss huge change.

**Comment by godnesso** [comment]
Proof that summoner is targeted when combat starts (hand mouseover icon turns to sword), from long range and mob is greyed out with 100% hp (tagged for summoner)
![proofs0](https://user-images.githubusercontent.com/65633456/146686494-178d0de5-b27c-463c-b79d-1e482f042406.JPG)
![proofs1](https://user-images.githubusercontent.com/65633456/146686513-afd8cd05-5e24-47be-a0ea-933cf9d55816.JPG)
![proofs2](https://user-images.githubusercontent.com/65633456/146686524-bbe945c0-06d6-432c-8356-ececbcb7820f.JPG)

**Comment by godnesso** [comment]
hard to tell from here, but mob despawns when reset (kited too far from leash, mob drops target in 2nd pic, despawn in 3rd)
i can record despawn on death but at this point i hope it isnt necessary
![proofs3](https://user-images.githubusercontent.com/65633456/146686938-2010a3a9-9af0-40e9-8242-a746992503c0.JPG)
![proofs4](https://user-images.githubusercontent.com/65633456/146686941-66b3234e-2844-43c1-818b-edc997356f5c.JPG)
![proofs5](https://user-images.githubusercontent.com/65633456/146686944-c307115f-b309-4421-9f09-efa70d61c6de.JPG)

**Comment by Shineslippers** [comment]
Thank you for the additional info i will add it to report when will get some time
