### ISSUE TITLE
Lack of herb and mining nodes in Eversong Woods and Ghostlands

### ISSUE THREAD

**Issue by InstructionSeeker** [chromiecraft/chromiecraft#262]
##### FACTION

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Few herb and mining nodes in Eversong Woods. The only rich area in herbs is East from Silvermoon City.
Especially very few mining nodes in Ghostlands, there are only some around the Gnoll area to the West from Tranquillien.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Eversong Woods should be probably rich in low level nodes,
For Ghostlands there should be more mining nodes.

##### EXTRA NOTES:

This report is made both on my personal feeling as when I leveled up a character with mining throughout the Ghostlands being at the times the only person in the zone, as well as with the concern of the world chat being in doubt of so only few herb/mining nodes there.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
**I just checked, the Zone don't need any Nodes Fix.**
So, I Close the report.

Herbs Nodes
-
![Herb Nodes](https://user-images.githubusercontent.com/1884642/119639864-eb83c380-be0f-11eb-971f-4d6c1e4f44d2.png)
Mining Nodes
-
![Mining Nodes](https://user-images.githubusercontent.com/1884642/119639870-ed4d8700-be0f-11eb-867f-19497b95f3a1.png)
