### ISSUE TITLE
Templars in Silithus still broadcasting text with $

### ISSUE THREAD

**Issue by Luckdemon2** [chromiecraft/chromiecraft#2622]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The Templars in Silithus are still broadcasting text with $.
The previous issue on AC that I see mentioning this was closed.
https://github.com/azerothcore/azerothcore-wotlk/issues/9347

### Expected Blizzlike Behaviour

They shouldn't be using $ in their text.

### Steps to reproduce the problem

1. Equip the Twilight Cultist set.
2. Summon a templar at a lesser windstone.
3. Watch the chat.

### Extra Notes

![2021-12-19 13_58_14-Window](https://user-images.githubusercontent.com/14365383/146687578-a7a65dd0-aed3-4c59-ab97-6e879a3ab07a.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by godnesso** [comment]
Race/class should refer to the player that initiated the summon

**Comment by j-hdt** [comment]
issue is based on the npc not targeting the summoner
