### ISSUE TITLE
Humanoids not dropping loot or are unlootable.

### ISSUE THREAD

**Issue by Wankleburr** [chromiecraft/chromiecraft#263]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

 After testing, Humanoid mobs will not drop loot which includes cloth, coin and other drops in their loot tables. After testing alot of different areas and different mobs (all humanoid) bellow

outside Scarlet Monastery, Alterac mountains, Hillsbrad foothills, Thousand needles and Ashenvale i can confirm that they have around a 50-70% chance of dropping any loot or coin. some hardly ever drop anything but that could be my bad RNG.

This can be really noticeable when you have drops from humanoids that are Quest drops and it makes the grind...more so of a grind.

these range in levels and it seems that all humanoids have this issue. it seems like either they have their chance at dropping anything 20-34 level range.

list of the mobs i have farmed there might be more in there but these were the ones i could repeat the experiment. 

https://wotlkdb.com/?npc=2252
https://wotlkdb.com/?npc=2249
https://wotlkdb.com/?npc=2345
https://wotlkdb.com/?npc=2346
https://wotlkdb.com/?npc=4283
https://wotlkdb.com/?npc=4281
https://wotlkdb.com/?npc=4280
https://wotlkdb.com/?npc=4093
https://wotlkdb.com/?npc=4096
https://wotlkdb.com/?npc=4094

##### EXPECTED BLIZZLIKE BEHAVIOUR:

In retail 3.3.5 i remember all humanoids would at least drop coin this drop rate needs to be looked at.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  kill any of the same Humanoid at any level. 
2. record how many times you get loot to not getting loot from the same mob type and you will notice its around 50-70%
3. 

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by tstuver2000** [comment]
I'm not a contributor, but I just wanted to say that I agree on this being an issue. It was very rare for a humanoid to not have _any_ loot at all, if not just a little bit of coin or a grey item. I'm seeing fairly high rates of humanoids not being lootable or having zero loot, which is not blizzlike. This is going to be kind of hard to pin down, though.

**Comment by AbraKabastard** [comment]
This should have been resolved by https://github.com/chromiecraft/azerothcore-wotlk/commit/e4aa9be1f764dadc0765d37ca382dc8392d7659d

**Comment by Stifler82** [comment]
it's solved, i close.
