### ISSUE TITLE
Riptide bonus healing effect on chainheal to low

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#2631]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Riptide buff on target is consumed by Chain Heal cast, but increase to chain heal is below 25%

### Expected Blizzlike Behaviour

Riptide buff on target should increase Chain heal by 25%

### Source

[https://db.rising-gods.de/?search=riptide#abilities](https://db.rising-gods.de/?search=riptide#abilities)

### Steps to reproduce the problem

Cast riptide on self, cast chain heal on self

### Extra Notes

It seems Riptide bonus effect is only considering base amount healed, not scaling with other talents (and maybe spellpower) increasing the amount healed

[https://db.rising-gods.de/?search=chain+heal#abilities](https://db.rising-gods.de/?search=chain+heal#abilities)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. I do not see the issue with spell. Spell description saying `increase the amount of the Chain Heal by 25%`. 25% of chain heal not riptide.
Without items:
![Capture1](https://user-images.githubusercontent.com/85256266/146769394-5d3ec408-a5df-40d8-b9fa-6659b4fdf933.PNG)
![Capture2](https://user-images.githubusercontent.com/85256266/146769383-47c5a2ad-599a-4674-9483-fb47b5309c3d.PNG)
With items:
![Capture3](https://user-images.githubusercontent.com/85256266/146769861-31a27d80-fdc7-4fae-8418-41c5987fcdd8.PNG)
![Capture4](https://user-images.githubusercontent.com/85256266/146769829-4af38db5-ae99-4150-abff-04221d6990ad.PNG)
With items and talents:
![Capture5](https://user-images.githubusercontent.com/85256266/146770472-70d4ed6c-65a7-44da-9dc8-d7fdfac47463.PNG)
![Capture6](https://user-images.githubusercontent.com/85256266/146770475-8e1b0c5a-37c6-4cb4-ac4a-15db055d8bca.PNG)
.
