### ISSUE TITLE
Warlock Talent Backdraft not affecting all destruction spells

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#2633]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Talent [Backdraft](https://db.rising-gods.de/?search=backdraft) (3/3) does not reduce the cast time of destruction spells [Rain of Fire](https://db.rising-gods.de/?search=rain+of+fire) or [Hellfire](https://db.rising-gods.de/?search=hellfire#abilities)

### Expected Blizzlike Behaviour

Talent states the reduction of cast time for all destruction spells, but does not affect Rain of Fire or Hellfire

### Source

Description of talent

### Steps to reproduce the problem

find a dummy and cast Immolate -> Conflag while spec'ed into backdraft talent. Afterwards cast Rain of Fire and Hellfire and see the stacks not being consumed and the cast time not being reduced

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Thank you, @j-hdt. But after some research this is blizzlike behavior. Rain of Fire and Hellfire are _channeling_ spell, that is why only spell with _cast time_ are affected the talent, as stated in the talents description.

See [this MMO-Champion post](https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire) from 2009:
> Yeah...backdraft has never affected chanelled spells, if you'll notice they don't even consume a charge.
