### ISSUE TITLE
[Azshara] Seeping Corruption Quest Item Missing

### ISSUE THREAD

**Issue by eayildiz** [chromiecraft/chromiecraft#2639]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

I was trying to do Seeing Corruption. The chest which contains vials had #1 vial I guess. After that I tried to loot everything in the box but I only looted #2 vial. First one is missing and I have to abandon probably which is frustrating. I would like you to check this issue. Thanks in advance.

### Expected Blizzlike Behaviour

Quest item should not disappear.

### Steps to reproduce the problem

1. Open container which contains quest items.
2. Try to loot every item in the container.
3. First vial is missing while you can loot the second. The third one and 4th one is in the container which cannot be looted.

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=3568

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. Did check this quest on local AC and can't find issue with looting this vials. In this case i can ask you to disable addon, delete looted vials, abandond quests and take it again.

![WoWScrnShot_122121_181100](https://user-images.githubusercontent.com/85256266/146953070-40791554-51ab-48a3-b0a8-d933c4866fca.jpg)
![WoWScrnShot_122121_180814](https://user-images.githubusercontent.com/85256266/146953040-6fac1cef-be1d-4d54-9b71-7bc08957d229.jpg)

**Comment by godnesso** [comment]
Something that happened to me twice in the past was that the amount of each unique vial in the box was more than 1 for a vial and since the vials are unique item I was unable to loot it and had to abandon to get

**Comment by Shineslippers** [comment]
I need more info. Screenshot of inventory or something else. Because there is missing some condition.

**Comment by Salehyn** [comment]
I've tested on CC PTR and it works fine. Every time there is a single copy of each vial in the box, no issues looting them. Perhaps some loot addon interference could cause the above described problems.
