### ISSUE TITLE
DB/Creature: Wretched Captive (16916) incorrect rotation

### ISSUE THREAD

**Issue by illfated** [chromiecraft/chromiecraft#264]
##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

The static NPC "Wretched Captive" (16916) is 90°-100° rotated away from its correct orientation (could be set to 0 (zero) in the DB?) instead of facing Sergeant Kan'ren.

![WoWScrnShot_032021_172211](https://user-images.githubusercontent.com/38162891/111877375-66a9a300-89a3-11eb-9efc-162ef3ab6165.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

"Wretched Captive" (16916) should be facing Sergeant Kan'ren permanently.
- https://wow.zamimg.com/uploads/screenshots/normal/831336-wretched-captive.jpg

![](https://wow.zamimg.com/uploads/screenshots/normal/831336-wretched-captive.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create any character (preferably horde, easiest with blood elf, shortest travel time).
2. Tele FalconwingSquare (or run to Falconwing Square from Sunstrider Isle).
3. Make your player character face the same way as the NPC.
4. Notice that you are facing due north on the minimap (close to rotation value 0).

##### EXTRA NOTES:

- https://wow.gamepedia.com/Wretched_Captive
- https://www.wowhead.com/npc=16916/wretched-captive
- https://wow.gamepedia.com/Falconwing_Square

##### AC HASH/COMMIT:

AzerothCore rev. 68fab5c9cb5f+ 2021-03-16 21:30:12 +0100 (UltraNix-FearImprovement branch) (Unix, RelWithDebInfo)
Connected players: 164. Characters in world: 152.
Connection peak: 164.
Server uptime: 2 day(s) 16 hour(s) 39 minute(s) 18 second(s).
Update time diff: 10ms, average: 10ms.

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
Hmm, I did not expect that your "official" AzerothCore server would be using a non-recognizable hash.
Anyway, I copy-pasted the core rev. hash verbatim from the game client while connected to Logon.chromiecraft.com .

**Comment by FrancescoBorzi** [comment]
hey @illfated , have you managed to install an AC server on your machine?

**Comment by illfated** [comment]
Thank you for asking, but the above was only from playing on your online server, Logon.chromiecraft.com .

**Comment by illfated** [comment]
By the way, are you suggesting that the online server should not be used for reporting issues in ChromieCraft & AzerothCore?

**Comment by FrancescoBorzi** [comment]
@illfated the process is the following:

- players report bugs at [chromiecraft/chromiecraft](https://github.com/chromiecraft/chromiecraft)
- contributors triage the reports reported at [chromiecraft/chromiecraft](https://github.com/chromiecraft/chromiecraft) and try to reproduce the issue in an AC server running locally, then bring the good reports to [azerothcore/azerothcore-wotlk](https://github.com/azerothcore/azerothcore-wotlk)

This is explained here, please have a look: https://github.com/chromiecraft/chromiecraft#chromiecraftcom-bug-tracker

if you have any questions just ask me ;)

**Comment by illfated** [comment]
> * contributors triage the reports reported at https://github.com/chromiecraft/chromiecraft and try to reproduce the issue in an AC server running locally

OK, now I get it. I should install AC on my computer and try to recreate the issue locally, before reporting the issue. Fair enough. Closing the issue until I got things ready.

**Comment by FrancescoBorzi** [comment]
@illfated yes since you are a contributor you can just do that and then open the issue on the AC side
