### ISSUE TITLE
[Inscription] Mysterious Tarot dropping one of cards with lower chance

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2641]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I'm haunting for Insane title and made tons of Mysterious tarot decks for reputation farm. I've noticed having more Ace and Three deck procs when making, and having so low amount of Two of Rogues. Should be 1/3 for any of them to drop but now it looks like 40% Ace 40% Three 20% Two. I was like Just having bad luck, but talking to Agonist from Chromie Homies he had same notice and he was also low on Two of Rogues. It ends like having 40 of Ace and 40 of Three in my bags while 0 of Two atm. Missing Two of Rogues

### Expected Blizzlike Behaviour

Each of them should have 33,33% chance to drop.

### Steps to reproduce the problem

1. Make Mysterious Tarot 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. There was no changes regarding to loot from Inscription cards. This is normal behavior. Today it's giving to you more `aces`, tommorow more `two` cards

DB is showing equal drop rate that is indicating by `Chance 0`
![Capture](https://user-images.githubusercontent.com/85256266/147001368-cd546db5-14f8-490c-a7bf-82070a4f5c91.PNG)

Ingame test is showing the same. I got more `Aces` than other cards. `Two` and `Three` was on same amount.
![WoWScrnShot_122221_003801](https://user-images.githubusercontent.com/85256266/147001371-8fa458e0-6648-4e70-973a-248f9944c54f.jpg)

**Comment by Elexias** [comment]
After nearly each day of making cards I'm on same conclusion 62 Aces, 79 Thirds, 0 Two.
![image](https://user-images.githubusercontent.com/80590226/147856909-f91ce03c-de57-4e62-a54d-e1d352016bc4.png)

Do you really believe in this statistics? That I always miss Two?

**Comment by Shineslippers** [comment]
Well, that is not what i can help you with. Just did it on live server from 111 [Mysterious Tarot](https://wowgaming.altervista.org/aowow/?item=37168) got same amount of two and three. Idk you can try to ask GM, but probably he will say same.
![123](https://user-images.githubusercontent.com/85256266/147858948-7415c7b4-006c-4f61-a434-8b6835f514f7.jpg)
![132](https://user-images.githubusercontent.com/85256266/147858949-6b639a84-271e-48df-8be4-1230d345e79e.jpg)
