### ISSUE TITLE
Hunter Spell - Detterence

### ISSUE THREAD

**Issue by Rinias** [chromiecraft/chromiecraft#2646]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Currently when a Hunter use Deterrence, the parry/dodge is octagonal. Which means attacks which are usable when behind such as Ferals Shred and Rogues Backstab get parried/dodged for the whole duration of Deterrence. 

I have not tested if this apply for Rogues as well, but since currently Deterrence seems octagal with parry/dodge I simply believe they are in the same boat as ferals with Shred, which I have tested.

Deterrence: https://wowgaming.altervista.org/aowow/?spell=19263
Shred: https://wowgaming.altervista.org/aowow/?spell=9830
Backstab: https://wowgaming.altervista.org/aowow/?spell=11281

### Expected Blizzlike Behaviour

For the duration of Deterrence Ferals should be able to Shred and Rogues should be able to Backstab from behind.

### Source

https://www.wowhead.com/spell=19263/deterrence#comments

By 310456 on 2009/06/25 (Patch 3.1.3)
Something like a mage's Ice Block, with the difference that while deterrence is active you can move, but during Ice Block you cannot. Really useful when carrying flags in Warsong Gulch. Also, Ice Block protects you more, because it protects you from all attacks. **Deterrence only protects you from melee attacks and spells that are done from your FRONT. Any attacks made from the rear, holy attacks or ranged attacks will not be dodged.**
Last edited by 310456 on 2009/06/25 (Patch 3.1.3)

### Steps to reproduce the problem

1. Hunter use Deterrence.
2. Druid in Cat form or Rogue try to attack from behind, use Shred or Backstab.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. [Patch 3.2.0](https://wowpedia.fandom.com/wiki/Patch_3.2.0#Hunter) changed this behavior. Now you can parry attacks from any side.
>  [Deterrence]: This ability now allows the hunter to parry spells and attacks from behind as well as in front. Now has a new visual spell effect.

**Comment by Rinias** [comment]
Deterrence is the only time you can parry things that are behind you, but it will not stop:
dots from ticking
Overpower 
Rune Strike 
Backstab
Ambush
Cheap Shot
Shred
Ravage
Pounce

I might have missed couple. But will update tomorrow with more proper information. The quote I did use was a rly bad confirmation of bug, and auto attacks should still be parried from behind correct.

**Comment by Shineslippers** [comment]
Deterrence is not a paladin's bubble. It's blocking incoming spells, but doesn't remove presenting effects
1. That why it shoudl not stop dots from ticking
2. Overpower, Rune Strike, Cheap Shot, Ravage, Pounce, Ambush cannot be blocked, dodged or parried. That is in description of spell or it has special flag. 
3. Shred and Backstab are blocking by Deterrence

**Comment by Rinias** [comment]
https://www.mmo-champion.com/threads/856886-so-no-more-shredding-thru-Deterrence
In this link you see posts from when Cataclysm arrived, and it is very clear how it was possible to Shred through Deterrence

**Comment by Shineslippers** [comment]
I found couple more comments, but if you will find some video would be great.

**Comment by Rinias** [comment]
I have 1 video from 11 years ago. Be aware it is in 240p and the link will start from when the hunter use Deterrence. Shows white dmg getting parried and yellow hits goes through. 1 low tick dmg I believe is a bleed tick possibly Rake. The higher is Shred. Hunter will be showing his back and its possible to see the druid spam clicking Shred icon. 
https://youtu.be/PD4QxgnFXJc?t=461

**Comment by slicplaya** [comment]
I went through this with Warmane for years. Deterrence parries everything including spells unless it specifies like the above skills listed. Also Chaos Bolt goes right through it as well. Deterrence will also not parry spells or abilities that have already been cast and are in midair towards you. It has to be deterrenced before the skill is completed.

Overpower
Rune Strike
Backstab
Ambush
Cheap Shot
Shred
Ravage
Pounce
Chaos Bolt
any existing dots(blocks dots from applying to you during deterrence)

**Comment by Gultask** [comment]
I can confirm. I also tested with everything slicplaya mentioned and only Shred and Backstab did not bypass Deterrence.
Also, for future reference, Heroic Throw also bypasses Deterrence.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/11644
