### ISSUE TITLE
[Items/Priest] Glyph of Inner Fire

### ISSUE THREAD

**Issue by Greyminder** [chromiecraft/chromiecraft#2649]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

This glyph apply any stats changes.

### Expected Blizzlike Behaviour

This glyph does increase armor buff of  Inner Fire (priest spell) by 50%.

### Source

Source Item : https://wowpedia.fandom.com/wiki/Glyph_of_Inner_Fire
                      https://wotlkdb.com/?spell=56168
Spell cible : https://classic.wowhead.com/spell=588/inner-fire

### Steps to reproduce the problem

1. Create a priest
2. Level up to 12 or more, and learn "Inner Fire"
3. Look armor buff
4. Apply this glyph (ID = 56168, source woltkdb)
5. Look the stats again

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Thank you for the report, @Greyminder.

I cannot reproduce your problem neither on ChromieCraft nor on local AC.
Just an idea: Have you buffed your character with Inner FIre again after you learned the glyph?

**Screenshots from ChromieCraft**

![WoWScrnShot_122321_104600](https://user-images.githubusercontent.com/62797536/147223266-79b11015-dfea-4881-9838-f7698c8b5110.jpg)
Without glyph.

![WoWScrnShot_122321_104618](https://user-images.githubusercontent.com/62797536/147223310-b4b4d003-3f2b-4df1-a846-4f30bc2bb809.jpg)
With glyph.

**Screenshots from local AC**

![WoWScrnShot_122321_105234](https://user-images.githubusercontent.com/62797536/147223379-d43bb2aa-16be-4ee8-8072-be2c1aed8305.jpg)
Without glyph.

![WoWScrnShot_122321_105354](https://user-images.githubusercontent.com/62797536/147223399-31874fa5-8cfb-475c-859c-952718e14605.jpg)
With glyph.
