### ISSUE TITLE
Winter Veil quests are now repeatable ad nauseum

### ISSUE THREAD

**Issue by Gethsemane2** [chromiecraft/chromiecraft#2653]
Can redo all the quests over & over

**Comment by Orixim** [comment]
I can confirm I was able to redo quests that I had previously done. However, they did not award experience (they did award reputation).

**Comment by Shineslippers** [comment]
Thank you for the report.

**Comment by Gethsemane2** [comment]
I believe not all the WV quests were functioning as designed yesterday. The quests "The reason for the season" and "The feast of Winter Veil" were both repeatable. Today they are not. I still have them in one of my characters quest log, but today they are uncompletable. The historian no longer gives the book, and the king can't finish the quest without it.

**Comment by Shineslippers** [comment]
The quests "The reason for the season" and "The feast of Winter Veil"  should not be repetable. Anyway if you already did it no reason to do it again.

**Comment by Gethsemane2** [comment]
Just letting you know, I'll delete them from my log.
