### ISSUE TITLE
[Seasons] Selected quests from Winter Veil event have been reset and can be continuously repeated for rewards

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#2657]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Selected quests from Winter Veil event (checked only Alliance side):
- 'Greatfather Winter is Here!' https://wowgaming.altervista.org/aowow/?quest=7022 / https://wowgaming.altervista.org/aowow/?quest=7023
- 'Stolen Winter Veil Treats' https://wowgaming.altervista.org/aowow/?quest=7042
- 'You're a Mean One...' https://wowgaming.altervista.org/aowow/?quest=7043
- 'A Smokywood Pastures'' Thank You! https://wowgaming.altervista.org/aowow/?quest=7045
- 'The Reason for the Season' https://wowgaming.altervista.org/aowow/?quest=7062
- 'The Feast of Winter Veil' https://wowgaming.altervista.org/aowow/?quest=7063
- 'Treats for Greatfather Winter' https://wowgaming.altervista.org/aowow/?quest=7025

have been reset and are enabled to be completed again (if some done them before).

Moreover, if player completes them again, logs out, and logs in again, they are added again to player's quest log and can be continuously repeated for rewards from 'Smokywood Pastures Special Gift' https://wowgaming.altervista.org/aowow/?item=17726 and for 250 reputation with Steamwheedle Cartel without moving out from quest hub (Ironforge for Alliance).

Depending on the order of turning in quests, player can keep rewards from 'Smokywood Pastures Special Gift' https://wowgaming.altervista.org/aowow/?item=17726. If order is incorrect, they will disappear from inventory upon log out.

### Expected Blizzlike Behaviour

Quests from Winter Veil event are allowed to be completed only once per year, without additional repeats in the same year.

### Steps to reproduce the problem

1. Prepare character with at least level 30
2. Travel to Ironforge, to Winter Veil quests hub before the Bank (coords 32 66)
3. Get quests 'Stolen Winter Veil Treats', 'The Reason for the Season', 'Treats for Greatfather Winter'
4. Continue the quest till they are all complete
5. Once all quests are turned in, log out
6. Log in again to the same character
7. Open quest log
8. Pay attention to the quests in quest log
9. Try to turn in again quests with 'Complete' status

### Extra Notes

Issue mentioned in https://github.com/chromiecraft/chromiecraft/issues/2653, added more details and kept the bug form.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Maybe further information on this issue can be found in duplicate ticket https://github.com/chromiecraft/chromiecraft/issues/2659.

**Comment by Shineslippers** [comment]
That's related to https://github.com/azerothcore/azerothcore-wotlk/issues/9630
