### ISSUE TITLE
Tower of Althelaxx (part 4) Npc Minions not Engaging

### ISSUE THREAD

**Issue by AtaraxiaDX** [chromiecraft/chromiecraft#266]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

**Quest:** [The Tower of Althalaxx (part 4)](https://wowgaming.altervista.org/aowow/?quest=970)
**Npcs:**
[Dark Strand Cultist](https://wowgaming.altervista.org/aowow/?npc=3725)
[Dark Strand Adept](https://wowgaming.altervista.org/aowow/?npc=3728)
While Killing mobs for quest. When PC attacks from a distance, the NPCs Minion does not attack PC.
![Screenshot from 2021-03-20 15-11-52](https://user-images.githubusercontent.com/81044968/111883688-4eca2300-8993-11eb-9965-d3bcabbc18ff.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC minions should assist NPCs even if PC is attacking from a distance.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Attack [Dark Strand Cultist](https://wowgaming.altervista.org/aowow/?npc=3725) and [Dark Strand Adept](https://wowgaming.altervista.org/aowow/?npc=3728) from outside of aggro range
2. Do not engage minion.
3. Kill [Dark Strand Cultist](https://wowgaming.altervista.org/aowow/?npc=3725) and [Dark Strand Adept](https://wowgaming.altervista.org/aowow/?npc=3728)
4. Minion despawns without engaging.

##### EXTRA NOTES:

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Npc Minions not Engaging](https://youtu.be/wXh_WH4I4PA)

**Comment by cachocarne** [comment]
I would like to give an update on these npcs. They are still bugged, but in a different way. Some of them attack you, but when you run away, the warlocks will eventually stop chasing you and go back. The minions, however, keep on chasing you wherever you go, staying on melee range BUT NOT ATTACKING YOU until you actually attack them again.

As you can see on these images, I was running away from the tower, even all the way to the beach, and they were still on me. Funny enough, I am out of combat so I could still regenerate hp/mana and even mount again.

![ 2021-08-20 at 16 41 13](https://user-images.githubusercontent.com/77953030/130251586-43462152-c858-4ab3-a120-4ce26103979a.png)
![ 2021-08-20 at 16 41 39](https://user-images.githubusercontent.com/77953030/130251607-ba15a236-cabe-469b-ad1c-57385f9b7a9a.png)

**Comment by FrancescoBorzi** [comment]
> I would like to give an update on these npcs. They are still bugged, but in a different way.

@cachocarne thanks for your update, however in cases like this it's better to just open a new issue. Thanks for your cooperation
