### ISSUE TITLE
Rigglefuzz got no quests available (flash bomb recipe)

### ISSUE THREAD

**Issue by melosat** [chromiecraft/chromiecraft#2660]
Hi!

Rigglefuzz in Badlands is supposed to give 4 quests - where the flash bomb recipe one is of greatest importance.

NPC: 
https://wotlkdb.com/?npc=2817

Wowhead comment: 
https://www.wowhead.com/npc=2817/rigglefuzz#comments

"By Cydonian212 on 2011/08/02 (Patch 4.1.0) | 
He no longer exists in Cataclysm and neither do his quests."

This recipe is of great significance for PvPers in he 60 bracket. 

Best Regards

**Comment by ishidinho** [comment]
Thank you for the report @melosat.

Can you please fill in the bug report form? This is really important for our triaging work.

**Comment by Shineslippers** [comment]
For the quest for Flash bomd recipe need to do pre-quest. This was fixed a while ago https://github.com/azerothcore/azerothcore-wotlk/issues/9185
