### ISSUE TITLE
Rigglefuzz no longer give his pre-quest - Pearl Diving

### ISSUE THREAD

**Issue by melosat** [chromiecraft/chromiecraft#2663]
You can no longer interract with the NPC Rigglefuzz in Badlands. 

Unfourtunately the bug-tracker-form didnt let me complete the appeal for some reason.

So, the background story to this is that I originally created this appeal:
https://github.com/chromiecraft/chromiecraft/issues/2660

And got the answer from shineslippers that this was fixed a while back - where the bug at the time was that he didn't require a pre-quest:
https://github.com/azerothcore/azerothcore-wotlk/issues/9185

Although something must've gone wrong with that fix - because now he gives zero quests.
[cant interact.pdf](https://github.com/chromiecraft/chromiecraft/files/7768868/cant.interact.pdf)

He's supposed to give the prequest "Pearl Diving". Check:
https://github.com/azerothcore/azerothcore-wotlk/issues/9185

https://wowgaming.altervista.org/aowow/?quest=705

which in turn leads to:

https://wowgaming.altervista.org/aowow/?quest=1559

Best regards

**Comment by Shineslippers** [comment]
Once again please use `Get started` button. Sorru for inconvenience we aware about this issue. https://github.com/chromiecraft/chromiecraft/issues/2662
