### ISSUE TITLE
Vorrel's Revenge [33 H]

### ISSUE THREAD

**Issue by blackcrowX** [chromiecraft/chromiecraft#267]
##### FACTION

- [ ] Alliance
- **[ X ] Horde**

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- **[ X ] 30-39**

##### CURRENT BEHAVIOUR:

**[Nancy Vishas] tells a joke residing on the dock and moves to another very close spot on the dock.**

(https://classic.wowhead.com/quest=1051/vorrels-revenge#comments)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

**[Nancy Vishas] tells [Grandpa Vishas] a joke residing in the House with him and then procedes to move to the spot on the docks.**

From ThottbotBy Kentaal on 2006/09/11 (Patch 1.12.0) |
-- | 

Subject: "Get Nancy Alone"What makes tackling Nancy (for the Vorrel's Revenge Quest) tough isn't that she's much of a fight... it's that under normal certunstances you have to fight her (33 Elite) and Grandpa (34 Elite) at the same time since they're both in the cottage together.

Ah - but forture shines on the patient!

After you arrive at the cottage, sit on the dock and chill for a few minutes... eventuatlly Nancy will walk from the cottage to the dock, but Grandpa will stay in the house! Now - it's a piece of cake.

And delicious cake, at that!
Top comment - https://classic.wowhead.com/npc=3984/nancy-vishas#comments)

##### STEPS TO REPRODUCE THE PROBLEM:

**1. Accept Quest from [Vorrel Sengutz].  (https://classic.wowhead.com/npc=3981/vorrel-sengutz)**
**2. Procede to [Nancy Vishas]. (https://classic.wowhead.com/npc=3984/nancy-vishas)**
**3. WAIT.**
**4. Experience [Nancy Vishas] moving from Spot A to Spot B.**

##### EXTRA NOTES:

**https://wowgaming.altervista.org/aowow/?quest=1051**

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by blackcrowX** [comment]
![WoWScrnShot_032121_041250](https://user-images.githubusercontent.com/79520609/111892820-034d5e80-89ff-11eb-8060-24a1ada6b8e9.jpg)
![WoWScrnShot_032121_041320](https://user-images.githubusercontent.com/79520609/111892825-07797c00-89ff-11eb-883c-0f79e54b7f58.jpg)

**Comment by blackcrowX** [comment]
Please Delete. Didnt realise this is the third repost.

Sorry.

**Comment by FrancescoBorzi** [comment]
no worries and thanks for your effort @blackcrowX
