### ISSUE TITLE
[WSG - Fail Charge Warrior] Charge from high terrain led me to underground

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2670]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

![WoWScrnShot_122421_131512](https://user-images.githubusercontent.com/80590226/147352172-509ad8e0-3480-45d3-bac0-a9b0ec1d2b4c.jpg)
![WoWScrnShot_122421_132009](https://user-images.githubusercontent.com/80590226/147352175-ce3c3132-70a7-4f7f-bdca-8eebcd14958d.jpg)

Charged from high hill as were I did screenshot to downhill and let me to underground charge

### Expected Blizzlike Behaviour

Should charge properly at the target.

### Steps to reproduce the problem

1. Get on top of hill in horde WSG side
2. Charge on lower part of hill
3. Get underground

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Where was your enemy? Can't find the issue

**Comment by Elexias** [comment]
![image](https://user-images.githubusercontent.com/80590226/147356694-82d1e905-8228-4200-95b0-c0a54b649c89.png)

**Comment by Shineslippers** [comment]
Thank you. However, we do already have an open issue for warrior/druid charges clipping through the world in https://github.com/azerothcore/azerothcore-wotlk/issues/6232, so will close this as a known issue while noting the location for testing. There's actually a fix for this issue in active development too, looks like it's due to be ported across to our PTR fairly shortly.
