### ISSUE TITLE
Giant Yeti has aura from Totem

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#2673]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Giant yeti and other NPCs that I can't recall, have a buff called from a Shaman totem.

### Expected Blizzlike Behaviour

According to sniffs, they only cast Frost Breath.

### Source

https://wotlkdb.com/?spell=3131#see-also

Brotalnia's sniffs

### Steps to reproduce the problem

.go c id 2251
Check his buffs

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi claudiodfc. Thanks for the report. I was unable to verify this on a local server. I checked on CC as well and saw no buff. Do you happen to have a screenshot?

**Comment by acidmanifesto** [comment]
@claudiodfc do you have a npc id for the creature for me to check on my end? Or are you able to link it ot a sniff that was submitted?

**Comment by Shineslippers** [comment]
Idk what he is mean by `have buff`. Don't see anything on local or live server. Frost resistance is ok to this creature.

![image](https://user-images.githubusercontent.com/85256266/147770400-a3cd448f-25e9-45b9-8253-c18b5b42eb15.png)

![image](https://user-images.githubusercontent.com/85256266/147770463-386f47b9-7978-4465-b892-c239479a6908.png)
