### ISSUE TITLE
[UBRS - D2 Summon] Lord Valthalak not using abilities if killed within first attempt

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2678]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

If you summon Lord Valthalak and kill him within first attempt, he won't summon adds nor do AOE spell.
If you wipe however and try it again he will be using all spells properly.
No screen unfortunately but could be reproduced easily

### Expected Blizzlike Behaviour

Should always use same spells no matter what try it is. Not sure how summon affects that

### Steps to reproduce the problem

1. Summon Lord Valthalak and check his abilities as raid group (missing adds and aoe)
2. Wipe
3. Come next time and see that he is using all abilities after wipe

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/33673bc1c2864cf9dd86209bd915d4529ec83f00

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
That's actually not so easy. Unable to reproduce. Did try with quest o without. Different braziers.

https://user-images.githubusercontent.com/85256266/147958024-937f68f4-c03f-4793-aff8-b0afd5cf7c14.mp4

.

**Comment by Scapulla** [comment]
Just did an UBRS, he did use chain and adds on the first try. Don't have screenshots because I only saw the issue now, but haven't had this bug happen to me. He sometimes doesnt spawn adds, but the spawns feel kinda random so might just be luck on my part, or raid kills them too fast for me to notice.
