### ISSUE TITLE
[Shaman Trinket] Enamored Water Spirit not giving bonus mana regen

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2682]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Guildie reported that he doesn't get bonus mana when use this class trinket

"kaya — Today at 4:23 PM
Elexias could you pls also ask for making work Enamored Water Spirit Shaman Trinket. it is not giving mana. might try to use it."

### Expected Blizzlike Behaviour

https://wowgaming.altervista.org/aowow/?item=20503
https://classic.wowhead.com/item=20503/enamored-water-spirit#comments

### Steps to reproduce the problem

1. Use trinket
2. Don't get bonus mana regen

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/33673bc1c2864cf9dd86209bd915d4529ec83f00

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by jeskej** [comment]
This appears to be working as far as I can tell.  I tested by using all my mana and timing how long it took to regen without using the trinket.  Then I timed how long it took to regen with the trinket and it was much faster.  Based on the description of the trinket, it should give about 9 MP5.  I switched gear around to test 10 MP5 regen and this was slightly slower than using the enamored water spirit.  I looked at my log and noticed I was getting 32 mana on each tick because of the improved totems talent (which is also working as expected).  That translates to just over 10 MP5 so it checks out.

![image](https://user-images.githubusercontent.com/19175013/147786760-ec0f330a-c685-4fd3-8502-7c19064d5b6f.png)

**Comment by Shineslippers** [comment]
Thank you or the report. I've tested it without party and with and it's working as intended. [Enamored Water Spirit](https://wowgaming.altervista.org/aowow/?item=20503) has same effect as [Innervate](https://wowgaming.altervista.org/aowow/?spell=29166) `Apply Area Aura - Party: Periodically Give Power (Mana)`. This type of buff shouldn't be displayed in Character Pane, but you can see it in combat log.

![WoWScrnShot_010122_195352](https://user-images.githubusercontent.com/85256266/147855776-682faf82-edb9-4e76-a0b2-f6c6b03a3955.jpg)
![WoWScrnShot_010122_194759](https://user-images.githubusercontent.com/85256266/147855774-d4831a9b-5072-45f1-b913-39d5a1fa8d5d.jpg)
.

**Comment by Elexias** [comment]
Not sure @Shineslippers but I've seen multiple people after my report telling me that it doesn't work. Same as HoJ trinket from Emperor.

**Comment by Shineslippers** [comment]
I'm open to suggestions. If those people can provide some screenshots or video where it doesn't working just send to them link to this report. 300 mana is not a significant amount of mana. One, two casts.

**Comment by Nyeriah** [comment]
If the combat log shows energy gains then it's working as it should. As mentioned previously, this isn't a "mp5" mechanic so nothing shows on character sheet.
