### ISSUE TITLE
Mind Control (I explained it wrong before)

### ISSUE THREAD

**Issue by Kike457** [chromiecraft/chromiecraft#2683]
### What client do you play on?

esES

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

So, when you mind control a mob and it, and any other involved mob in the fight, dies (basically, when the battle is over) you keep the combat state, you can’t drink or get on the mount
And the battle is over there’s no other mob attacking you

### Expected Blizzlike Behaviour

As in any other fight, after every mob is dead, you should be able to mount, drink or something

### Steps to reproduce the problem

Get a lvl 40 priest
Go to Elwynn forest
Mind control a bandit
Cancel the mc and kill it
Congratulations, now you can’t get on the mount :D

### Extra Notes

I tried to explain it better on this post, next time, I will upload a video or something 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/33673bc1c2864cf9dd86209bd915d4529ec83f00

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

Cc texture mods

### Server

ChromieCraft

**Comment by ishidinho** [comment]
For tester: Kike457 is refering to https://github.com/chromiecraft/chromiecraft/issues/2614.

**Comment by KCorruption** [comment]
This affects far more than just combat bugging. Seems like mob AI and even Player AI in pvp situations override mind control.
