### ISSUE TITLE
Can't get Dragonkin Menace (for Drakefire Amulet) quest

### ISSUE THREAD

**Issue by dumikachromiecraft** [chromiecraft/chromiecraft#2687]
I am trying to pick up Dragonkin Menace (https://wowgaming.altervista.org/aowow/?quest=4182), which is the starter quest for the Drakefire Amulet (alliance side), however, the mob does not give me the quest. It is in the aowow database, I don't see any indications whether it was removed from the game, or not.

The horde side can get the amulet just fine, which is a big advantage for them, since it is the best fire resist amulet in the game by a good margin. 

Can you take a gander at it?

**Comment by Stump876** [comment]
Hi dumikachromiecraft. Please don't delete the template. If you believe this is a bug, you will need to open a new issue and fill out the fields properly. If you have a suggestion please bring it up in the suggestions channel on discord. This was removed from the game in patch 3.0.2. The NPC's for the RP in stormwind were also removed.
