### ISSUE TITLE
[BRD - The Lyceum] Shadowforge Flame Keeper not dropping torches

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2698]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

![image](https://user-images.githubusercontent.com/80590226/147700168-83361c47-415f-4667-94ec-34f001725f4b.png)

Shadowforge Flame Keeper not dropping torches, killed 3 of them, none of them dropped it. Drop chance is nearly 100% and it never happened to anyone,  this is clearly a bug.

### Expected Blizzlike Behaviour

Should drop torches when killed.

### Steps to reproduce the problem

1. Go to BRD
2. Enter The Lyceum Room
3. Kill Shadowforge Flame Keeper no loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/33673bc1c2864cf9dd86209bd915d4529ec83f00

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Elexias. Thanks for the report. I agree that they should drop torches and I can see you didn't have them drop. But I can't reproduce this on my local. I ran it 3 times and torches dropped each time. I'm assuming you ran this through RDF? I'm going to leave this open for someone else to take a look.

**Comment by acidmanifesto** [comment]
Working as intended. % is currently set to 94.3506 for drop and it matches UDB and consolidated sniffs obtained thru verified retail sources. Unfortunately 94.3506% is not 100% so you will have times where you are on the bad end of the stick and not get a drop.
