### ISSUE TITLE
[BRD - Last Boss] Pulling Emperor Dagran does not pull whole room like intented

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2699]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

![image](https://user-images.githubusercontent.com/80590226/147700715-5536f6b5-243f-4e1f-a6e0-29f1b1ab7511.png)

This was bugged on lvl 49 and was fixed, pulling last boss should pull everyone in the room.

### Expected Blizzlike Behaviour

This was bugged on lvl 49 and was fixed, pulling last boss should pull everyone in the room.

### Steps to reproduce the problem

1. Get to last boss in BRD
2. Pull him, as lvl 60, we tried,
3. Adds stayed on top

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/33673bc1c2864cf9dd86209bd915d4529ec83f00

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Elexias. Thanks for the report. You are correct. However, I can't reproduce this on my local server. I marked a few mobs far off and pulled the boss. He called for aid, and they all ran in. I'll leave it open for someone else to take a look.

I assume this is a different run from the other report since you can't open the door without the torches? Was this through RDF?

![image](https://user-images.githubusercontent.com/68164076/147807054-40fcb521-6106-4689-a7f3-5d64943d6b58.png)

![image](https://user-images.githubusercontent.com/68164076/147806714-808b9ff9-b03f-4b19-b764-995f0f31af91.png)

**Comment by Shineslippers** [comment]
Have you done it by Hunter's FD. Need more info.

**Comment by Elexias** [comment]
No sorry, can't help you more. I misspulled as rogue by going near adds we were killing, it ended up only pulling boss and not adds. Had nothing to do with tricks.

**Comment by Shineslippers** [comment]
I have able to reproduce it with vanish/FD. Can't find the way without tricks

**Comment by Elexias** [comment]
@Shineslippers Can you try to copy our situation, clear all mobs on left and right sides beside the ones on top. Just to copy paste same issue. Bring 5 man party to test.

Don't get me wrong but sometimes tests on that realm is not same as live server, you have more people in group, mora factors that contribute situation, that is really a lot different than situation you're trying. As I've already told you, I have screenshots of these things, they happened, not my imagination, unable to reproduce something is not same as it is not truth, but maybe you need more factors inside to make it not work. Not sure how to explain you but, being in real grp vs solo pulling boss is not same.

**Comment by Brylezor** [comment]
in my experience in BRD at 49, there was a way that if you kill the left group (facing emperor) and leaving one of the non elite adds alive, when he is low he will run to Emperor and cause him to aggro, we have done this a couple of times at 49 and it always caused the emperor to be pulled without aggro`ing the room, if i recall correctly this has stopped working at some point and we considered it fixed or a bug we cannot re produce, if someone can attempt it and confirm we will have an answer

**Comment by Salehyn** [comment]
Can't reproduce this in any shape or form. Tried clearing the adds on the ground floor, asspulling Moira in the position you would be while fighting the left group, ranged pull, charge pull, nothing made a difference, Emperor shouted for aid every time.
The only thing that did bug out, sort of, is that 2 out of the gazillion adds chose to reset when I sat on the Emperor's throne. I'm not sure how viable it is to abuse that when you need to clear the rest of the room anyway.
