### ISSUE TITLE
Bag swapping

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#2702]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

[See video below]
Swapping bags then moving items into the new bag causing the items to disappear. The items are still there but can not be picked up. I was not sure if this was a client side problem.
/reload does not help
logging in and out is the only fix that I know of. 
https://youtu.be/HEI7ZmNlZJo

### Expected Blizzlike Behaviour

The items should not disappear when moving to the new bag. 

### Steps to reproduce the problem

1. Empty the bag.
2. Swap the bag with another.
3. Move items into the new bag.
4. try /reload
5. Log in and out

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/33673bc1c2864cf9dd86209bd915d4529ec83f00

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
This is something I noticed myself a while ago. Mainly from bags taken from a guild bank. Self crafted bags, or bags bought from the Chromie shop do not have the issue. I believe it is client related. As you noticed, the items are still there they just can't be seen and a relog will fix it. Sorry to say I can't remember how I stopped it, maybe a cache clear, but I did get it to stop.

This will also mess with your crafting if you have the crafting screen open 
https://user-images.githubusercontent.com/68164076/147803990-218d3725-4e80-4c69-8b2e-800dae4455ff.mp4
