### ISSUE TITLE
[PVP][WSG]Polymorph players in specific location will take them OOB automatically killing them

### ISSUE THREAD

**Issue by mturca** [chromiecraft/chromiecraft#271]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Polymorph players in specific location will take them OOB automatically killing them. 

Issue encountered mostly in PVP in Warsong Flag room at the entrance from the tunnel - both Alliance and Horde side 

On the Alliance side the it's easier to reproduce as the main culprit seems to be the Wooden beam texture as seen in the below video.

https://user-images.githubusercontent.com/47978220/111924210-fd618700-8aab-11eb-8b18-83aca41c8ac5.mp4

On the Horde side although it's harder to reproduce it still happens as shown in the below video.

https://user-images.githubusercontent.com/47978220/111924228-1702ce80-8aac-11eb-915b-74b46cb80963.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Polymorphing someone should not send him OOB

##### STEPS TO REPRODUCE THE PROBLEM:

1. Join Warsong Gluch 
2. Reach any of the flag rooms at the presented in the video
3. Find a willing or unwilling target to cast polymorph on
4. Notice the effects 

##### EXTRA NOTES:

Although it has a very rare occurrence it might happen on any uneven surface 

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
@JamesGent https://gist.github.com/UltraNix/772f14a2085014ce36dffcebe16b0182 Try this one and give me your feedback.

**Comment by FrancescoBorzi** [comment]
@UltraNix it would be better if you could provide a PR with it so contributors can easily test it

**Comment by UltraNix** [comment]
@FrancescoBorzi I'm not sure about it, that's why I asked @JamesGent to test. If everything's gonna be okay, I will make a PR.

**Comment by Stifler82** [comment]
@FrancescoBorzi @UltraNix @JamesGent is it fixed or not?
Because i'm seeing a merged PR about it, so.. is it fixed?

**Comment by UltraNix** [comment]
No, it's not fixed.

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303
