### ISSUE TITLE
Mobs Not Hostile - Start Area for Tauren (Mulgore)

### ISSUE THREAD

**Issue by Apachemoo** [chromiecraft/chromiecraft#2711]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

4 mobs are not hostile in Mulgore.

### Expected Blizzlike Behaviour

Mobs should be hostile.
https://classic.wowhead.com/npc=2954/bristleback-battleboar
https://classic.wowhead.com/npc=2952/bristleback-quilboar
https://classic.wowhead.com/npc=2953/bristleback-shaman
https://classic.wowhead.com/npc=8554/chief-sharptusk-thornmantle

### Source

![bristleback boars](https://user-images.githubusercontent.com/96935018/147861966-eb418c9a-6aec-4c56-85f5-338b04692651.PNG)
![bristleback quilboar shaman and chief sharptusk thornmantle](https://user-images.githubusercontent.com/96935018/147861967-0964bfae-7d1f-4355-8b4f-eaf1db738575.PNG)

### Steps to reproduce the problem

1. Go to npc=8554 (GUID: 9217) Chief Sharptusk Thornmantle.
2. Confirm nearby mobs are not hostile.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. This changes was introduced in WotLK and all start areas has neutral NPC. As is see it's [Patch 3.3.0 (undocumented changes)](https://wowwiki-archive.fandom.com/wiki/Patch_3.3.0_(undocumented_changes)#World_environment)
> Level 3-5 starting zone mobs are now neutral by default.
