### ISSUE TITLE
Jandice Barov body disappeared after kill/ 2nd time no loot from kill

### ISSUE THREAD

**Issue by abcjinzhu** [chromiecraft/chromiecraft#2717]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Jandice Barov from Scholo body disappeared after kill, so I cant loot to complete my quest / the 2nd time there no loot drop from boss kill

### Expected Blizzlike Behaviour

Body should appear after kill, so I can complete my boss, also body should drop loot as well.

### Steps to reproduce the problem

pls try kill jandice barov in scholomance, kill her after she splitted into shadow clones and see if the same bug appears

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. Unfortunately i can't reproduce it on local AC. Can you provide more info? Is it still an issue? Was it RDF?

https://user-images.githubusercontent.com/85256266/147937628-c01c0012-6e41-4006-bea1-ea06cae8685d.mp4

**Comment by abcjinzhu** [comment]
Hi Chromiecraft/Chromiecraft

I will kill jandice again and see.. so far the two times I killed jandice,
no drop and no body

**Comment by Shineslippers** [comment]
There was similar issue, but it's not related to Scholomance. Will wait for your message. If it will something unusual in your actions let me know.

**Comment by heyitsbench** [comment]
@abcjinzhu Any update on this?

**Comment by Salehyn** [comment]
Can't reproduce it on CC PTR. Whether I kill the clones before her or kill her without touching the clones, same behavior: clone bodies disappear, real Janice remains with loot.
