### ISSUE TITLE
"Find minerals", "smelting"  and "toughness" stays in spellbook after unlearning Mining

### ISSUE THREAD

**Issue by Bredley** [chromiecraft/chromiecraft#2718]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I have unleardned mining and "find minerals", "smelting"  and "toughness" is still in spellbook.

### Expected Blizzlike Behaviour

Those should be unlearned.

### Steps to reproduce the problem

- Have mining 
- Unlearn it
- Check spell book for "find minerals", "smelting"  and "toughness"

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. Unfortunately i can't reproduce it on local AC. Can you provide more info? What was skill of mining? Maybe something else?
![WoWScrnShot_010322_170612](https://user-images.githubusercontent.com/85256266/147940104-a4acf873-82a7-4271-b9c6-05b86219229b.jpg)

**Comment by Bredley** [comment]
![image](https://user-images.githubusercontent.com/29784358/147942649-607391aa-1055-413d-b918-570e4a2e16df.png)
Hey, i was 300/300
Sending screen that i have now BS, ENG and in spellbook i still do have mining spells

**Comment by Shineslippers** [comment]
Hm, have you unlearned it by button. Was there crash/restart? Was there unlearned message?
![Capture](https://user-images.githubusercontent.com/85256266/147944936-80401acf-5a83-429f-9727-36e7afbe6aca.PNG)

**Comment by Bredley** [comment]
Yes, i've unlearned it the same way as you showed on picture. 
No crash/restart. 
Since it was like week and half ago im not sure about unlearned messages - i think there was You have unlearned Mining (expert.. or whatever the rank is called)

**Comment by Shineslippers** [comment]
Appreciate for the info. Will try to find out what's going on.

**Comment by Stump876** [comment]
Hi @Bredley. Can you still use them, or is it just the icon is still there?

**Comment by Bredley** [comment]
Hi @Stump876 yes i can still use them - can be tracking minerals, and i can open smelting (but the numbers are weird)
![image](https://user-images.githubusercontent.com/29784358/148348079-0e922e83-e2f9-4272-a8b8-4b2e663b86c8.png)

**Comment by Bredley** [comment]
@Stump876 only thing i can smelt is the copper and tried it - it works 
![image](https://user-images.githubusercontent.com/29784358/148349055-a60df022-4734-4b78-93dd-4d98106b9ee6.png)

**Comment by Elexias** [comment]
What staff/testers doesn't understand is that Local AC has nothing to do with real situation, that is what I learned after > 100 reports here. They think that their local testing is AMIN or let's say 100% true, while it doesn't affect real situation that happens in our game, sometimes zillions things are combined together in game that lead to bug, on local AC you're solo testing something without having other reasons that can cause a problem.

**Comment by ridai260** [comment]
The main reason is that a local AC server doesn't come with the Chromiecraft modules, so better test with them enabled for the closest possible result. But note that Shine said "i can't reproduce it on local AC or **live CC server**", so we may need to see if anyone else can confirm on live CC server.

I noticed in the last screenshots the mining rank states "11310/0" in the profession pane window title, bizarre.

**Comment by Salehyn** [comment]
Tested on CC PTR. Mining spells are properly removed with unlearning the skill. This fellow gotten lucky somehow.
