### ISSUE TITLE
[Azuremyst Isle] Undermap "Greater Timberstrider"

### ISSUE THREAD

**Issue by Vladimirjov** [chromiecraft/chromiecraft#2719]
Hello team

I use the enUS client with HD-patches. On Azuremyst Isle i found a "Greater Timberstrider" who is underground. With the help of the screenshots i think you'll be able to find him easily.

Thanks for fixing!

![WoWScrnShot_010322_181000](https://user-images.githubusercontent.com/81888445/147959796-8da2a1d2-0488-4e59-b0f0-320a419f82a8.jpg)

![WoWScrnShot_010322_181006](https://user-images.githubusercontent.com/81888445/147959810-051bba68-0fef-4736-96bc-6c26a08046eb.jpg)

**Comment by Shineslippers** [comment]
Thank you for report. Please do not use `Open a blank issue` link anymore, but green `Get started` button. Also for players is available command `.npc info` and some other command that you can find by type in chat `.help`. It's saving your and our time
![Capture](https://user-images.githubusercontent.com/85256266/147961190-0608a210-be4b-4c53-bc9d-5f6f1dfb91ad.PNG)
.
