### ISSUE TITLE
Herbalism Nodes: Alterac Mountains multiple cluser/double spawns

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#272]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Herbs are spawned in clusters/doubles and they respawn same way.

8638, 8639, 9190 - Goldthorn - triple spawn
32194, 8926 - Goldthorn - double spawn
8197, 32203 - Wintersbite - double spawn
8974, 33141 - Goldthorn - double spawn
9141, 8624, 35390 - Goldthorn - triple spawn
3435, 3545 - Bruisweed - double spawn
8062, 8063 - Khadgar's Wisker - double spawn
7716, 7691 - Fadeleaf - Double Spawn
7822, 35379 - Fadeleaf - Double Spawn
3609, 3332 -  Bruiseweed - double spawn
8989, 8988, 9004, 9171 - Goldthorn quadruple spawn
32221, 8172 - Khadgars Wisker - double spawn
7831, 7832 - Khadgars wisker - double spawn
33140, 8927 -  Goldthorn - double spawn
8055, 7841 - Khadgars wisker - double spawn
9057, 8990 - Goldthorn - double spawn
8771, 8769 - Goldthorn - double spawn
7575, 7576, 7773, 7732, 7731 - Fadeleaf - should be 2 nodes
7436, 7407, 7423, 7408, 7420 - Liferoot quintuple spawn - should be 2 nodes
7415, 7551 - Liferoot - double spawn
7549, 7548, 7550, 7515 - Liferoot - quadruple spawn
7512, 7510 - Liferoot - double spawn
7474, 7529, 7511 - Liferoot - triple spawn
7696, 7697 - Fadeleaf - double spawn
7621, 32693 - Fadeleaf - double spawn

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The doubles should be spawned 1 at a time, clusters of 3 or more should be reduced to 1-2 nodes

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have herbalism and find herbs on
2. Go to Alterac mountains and fly around or teleport to game object

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by InstructionSeeker** [comment]
For Liferoot:
These 2 WotLK databases support that many spawns of Liferoot in the Alterac Mountains.
https://wotlkdb.com/?object=2041
https://legacy-wotlk.com/?object=2041
Vanilla and Classic showcase the same spawns:
https://vanillawowdb.com/?object=2041
https://classicdb.ch/?object=2041

While [wowhead classic database (link 1)](https://classic.wowhead.com/object=2041/liferoot), [as well as wayback machine record for vanilla (link 2)](https://web.archive.org/web/20100713145254/https://www.wowhead.com/object=2041/liferoot) is showing just singular spawn locations.

The possibilities:

- Cluster spawn location could be perhaps data for dynamic spawns and so possibly there should be just one, or two herbs within the spawn cluster (just my guess, I don't know if that's how dynamic spawns work, but that idea just popped in my head),
- It might be a WotLK thing; we have just few gatherers to farm these herbs and so it *might* feel like there is overwhelming amount of herbs.

**Comment by gurveleg** [comment]
I aggre that it then could be spawn points for dymanic spawns, but it should not be more than 1 or maximum 2 of them every spawned in those clusters. If you look at Arathi Mountains herb spawns it seems that every possible node in clusters is spawned at the same time all the time, whole Alterac Mountains zone its packed with x2, x3 amount of herbs that other zones normally spawn, even tho the number of total herb nodes s smaller for example.

**Comment by nolt** [comment]
Duplicated spawn will be deleted. If there double spawn of two different herbs near each other, they should spawn and despawn in a roll. But i.e. this 8638, 8639, 9190 is bug.

**Comment by nolt** [comment]
32221, 8172 - Khadgars Wisker - double spawn
should be
32211, 8172 - Khadgars Wisker - double spawn
