### ISSUE TITLE
Minor - Packs of Bonepaw Hyenas and Kodos that usually wander the map are all stuck in fixed locations and do not path

### ISSUE THREAD

**Issue by CMHWoody** [chromiecraft/chromiecraft#2720]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Several packs of animals that should path around the map do not and just stand in one spot.  Please see this brief video showing an example of a bonepaw hyena pack that is doing this:

https://www.screencast.com/t/LrgNpuFzsz9m

This seems to effect all packs of hyenas and kodos

I did verify this over multiple days, so it does not appear to be something that is corrected by normal server restarts.

### Expected Blizzlike Behaviour

I would expect these animals to follow a path around the map instead of standing in a fixed location.

### Steps to reproduce the problem

Go to 36.4 ,  72.2 in Desolace and you will see the pack of bonepaw hyenas just standing in a fixed location instead of pathing around the map.

A second pack of hyenas exhibits the same fixed behavior at 53,6 , 45.8.

A third pack of hyenas exhibits the same fixed behavior at 46.9 , 29.4

The first pack of kodos is at 56.8 , 82.6 and just fixed in one location instead of wandering.

Another pack of kodos is at 49.4 , 40.8

There could be other examples of packs that I missed when running around the map.

### Extra Notes

This Wowhead classic link has comments that seem to confirm they *should* be pathing:

https://classic.wowhead.com/npc=4688/bonepaw-hyena#comments

Also, everything moves a little, even if just a few meters around their area and these stand out as they do not move at all other than their animations.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. We already have some other reports about it: https://github.com/chromiecraft/chromiecraft/issues/445 https://github.com/chromiecraft/chromiecraft/issues/630 https://github.com/chromiecraft/chromiecraft/issues/1776 Anyway appreciate for reminder. This report i have to close accordingly.
To make your and our job a bit easier for players available chat command `.npc info`. You can choose creature(one enought for packs), do screenshot like below and it will save a lot of time for everyone. Cheers.
![WoWScrnShot_010422_141229](https://user-images.githubusercontent.com/85256266/148050946-a13ae0fb-fc13-42cf-aa22-ae3468a34dba.jpg)
.

**Comment by CMHWoody** [comment]
Thank you for the tip on .npc info.  I'm frustrated by myself for logging a duplicate as I take great steps to make sure I don't log duplicates. I even make sure to search all issues not just open as in the example. 

If you have time to help, can you explain why these filters would not have found the other issues you listed:

is:issue bonepaws in:titlle, body
is:issue hyena in:titlle, body 
is:issue kodo in:titlle, body 

https://github.com/chromiecraft/chromiecraft/issues/445 this issue has bonepaws right in the title so, theoretically, should have been found with the first above filter for issues. I'd like to understand why it did not so I can improve my search and eliminate duplicates.

I also tried:

is:issue Desolace in:titlle, body 

And this returns 2 results (so I know the search is working),  neither of which is issue https://github.com/chromiecraft/chromiecraft/issues/1776 which has Desolace right in the title.

It seems my searches are somehow bad, or maybe issues are not indexed properly?

**Comment by CMHWoody** [comment]
Ok, I think I figured this out.  My searches have a space after the comma between title and body and when I remove the space, the searches work as expected.  Well THAT should help me not log duplicates. :)

**Comment by Shineslippers** [comment]
> Ok, I think I figured this out. My searches have a space after the comma between title and body and when I remove the space, the searches work as expected. Well THAT should help me not log duplicates. :)

Don't worry duplicates is around on github. That's not a big deal. You figirued out it correct. Space between `in:title, body` make guthub think body is not a command, but word for search.

Tbh i don't think you neeed this command at all. By default search is looking everywhere. Sometimes players don't mention relevant to issues details in `body`. For example `is:issue kodo in:title, body` and `is:issue kodo` has almost the same output. Anyway wish to all of who is reporting to Github use search.... well life is more complicated. Appreciate for your intentions.
