### ISSUE TITLE
Bloodfang 8 piece bonus issue

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#2721]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The rogue T2 set Bloodfang 8 piece bonus is not hitting the correct amount per the description. 
It's  currently hitting for 179-200 but the description says 283-317. 

![Bloodfang](https://user-images.githubusercontent.com/62799885/148007969-237a3bd4-c537-4513-990d-3d6d80892d79.png)

### Expected Blizzlike Behaviour

I am not sure which value is blizzlike but I would assume it should hit for what it says. 

### Source

Bloodfang Spell: https://wowgaming.altervista.org/aowow/?spell=23581

### Steps to reproduce the problem

1. Go to a target dummy
2. Equip all 8 pieces of Bloodfang
3. Hit the dummy for 5 mins. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report, but i have to close it. As you can see from screenshot below regardless of shown damage Auto Attack doing less damage to dummy. That's because physical damage to dummy is reduced by armor. Same is going on for rogue's  [Bloodfang](https://wowgaming.altervista.org/aowow/?spell=23581) set bonus. It has `School | Physical`. It's doing description amount of damage to targets with 0 armor. 

![WoWScrnShot_010422_142803](https://user-images.githubusercontent.com/85256266/148052859-b556f47a-abe2-4c05-b5f0-06a07ec8ea0e.jpg)
