### ISSUE TITLE
[NPC] Spirit of Lord Valthalak on Alcaz Island

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2724]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

During the quest "I see Alcaz Island in Your Future..." a NPC called Spirit of Lord Valthalak appeared on Alcaz Island.

![WoWScrnShot_010422_140448](https://user-images.githubusercontent.com/62797536/148093397-0bd5415e-41fc-4e08-b334-d265cdbf829e.jpg)

### Expected Blizzlike Behaviour

Spirit of Lord Valthalak should only appear after killing Lord Valthalak in UBRS.

### Source

[Lord Valthalak on Wowpedia](https://wowpedia.fandom.com/wiki/Lord_Valthalak)
[Spirit of Lord Valthalak on Wowpedia](https://wowpedia.fandom.com/wiki/Spirit_of_Lord_Valthalak)

### Steps to reproduce the problem

1. Accept quest "I see Alcaz Island in Your Future..." (note: I just guess you need it)
2. Go to the shown spot on Alcaz Island

### Extra Notes

NPC: https://wowgaming.altervista.org/aowow/?npc=16073
Quest: https://wowgaming.altervista.org/aowow/?quest=8970

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. It's known issue https://github.com/azerothcore/azerothcore-wotlk/issues/9152
