### ISSUE TITLE
[Quest] I see Alcaz Island in Your Future... - Strashaz Myrmidons not dropping Bloodkelp

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2725]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

During the quest "I see Alcaz Island in Your Future..." on Alcaz Island it does seem that Strashaz Myrmidons are not dropping [Bloodkelp].
During the quest not a single one dropped the quest item. The reason for that can be that the drop chances are quite low in the expected blizzlike way. But the tooltip indicates no drops as well.

![WoWScrnShot_010422_140937](https://user-images.githubusercontent.com/62797536/148095156-f2a4202e-6b37-47d0-bb44-7e49d60f7128.jpg)

### Expected Blizzlike Behaviour

During the quest "I see Alcaz Island in Your Future..." on Alcaz Island Strashaz Myrmidons should drop [Bloodkelp].

### Source

[[Bloodkelp] on wowgaming DB](https://wowgaming.altervista.org/aowow/?item=22094#dropped-by) shows that it is not in loot table for Strashaz Myrmidon, but [Classic WoWHead DB](https://classic.wowhead.com/item=22094/bloodkelp#dropped-by) does.

> Also drops from the nagafighters and myrmidons... but very rare.
(source: [comment on WoWHead](https://classic.wowhead.com/item=22094/bloodkelp#comments:id=2634749))

### Steps to reproduce the problem

1. Accept quest "I see Alcaz Island in Your Future..."
2. Go to Alcaz Island
3. Check tooltip of Strashaz Myrmidons

### Extra Notes

Quest: https://wowgaming.altervista.org/aowow/?quest=8970
Quest item: https://wowgaming.altervista.org/aowow/?item=22094
Strashaz Myrmidon: https://wowgaming.altervista.org/aowow/?npc=4368

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
@acidmanifesto 

``
SELECT * FROM creature_loot_template WHERE item = "22094";
``
![image](https://user-images.githubusercontent.com/62797536/148097087-e648d60e-a5f5-4e6c-a31f-3ea8a252094a.png)

**Comment by acidmanifesto** [comment]
Not a issue, but a very bad example of wowhead's unverified comment section and dilute loot datamining meathod.
NPC never possessed the Bloodkelp, and was never a a objective for the bloodkelp quest.
https://github.com/azerothcore/azerothcore-wotlk/pull/9873
