### ISSUE TITLE
Kyle's Gone Missing! (Mulgore - Lvl 7 quest)

### ISSUE THREAD

**Issue by Apachemoo** [chromiecraft/chromiecraft#2727]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Quest is not completed after feeding Kyle.

### Expected Blizzlike Behaviour

Quest is suppose to become complete and be able to be turned in.

### Source

https://tbc.wowhead.com/quest=11129/kyles-gone-missing

### Steps to reproduce the problem

![id](https://user-images.githubusercontent.com/96935018/148143602-9460e08e-030d-440d-8d4c-174dac6efc97.PNG)
![dance](https://user-images.githubusercontent.com/96935018/148143607-16eacc3d-43c6-4d30-8d47-13f1c92ef5ed.PNG)
1. Go to npc=23618/ahab-wheathoof.
2. Accept quest Kyle's Gone Missing! (requires lvl 5).
3. Kill nearby npc=2956/adult-plainstrider for item=33009/tender-strider-meat.
4. Go near npc=23616/kyle-the-frenzied and right click tender-strider-meat. Can also be seen running around Bloodhoof Village.
5. Kyle-the-frenzied will eat, then dance, and disappear, leaving quest not complete.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Apachemoo. Thanks for the report. However, I wasn't able to reproduce the issue. I tried a couple times and it completed both times. It did take me 2 tries to feed him on my first try. He just ran right passed me.
![image](https://user-images.githubusercontent.com/68164076/148150181-d7f84791-170b-4d50-951e-5362acd75ced.png)
![image](https://user-images.githubusercontent.com/68164076/148150434-68e672b9-2d32-46ee-a350-0f150c4332ab.png)

**Comment by Apachemoo** [comment]
Strange I went back to try it again and this time it was completed. Not sure why it worked this time.
![1](https://user-images.githubusercontent.com/96935018/148155576-0c3ab60e-adb5-46d7-af2f-1d445bb1ec1b.PNG)
![2](https://user-images.githubusercontent.com/96935018/148155582-68512f50-031b-44f9-94d7-9b3ff418a4a9.PNG)
![3](https://user-images.githubusercontent.com/96935018/148155586-e3a223cb-5b94-4de2-8b2f-18c5645e74a3.PNG)
.

**Comment by Stump876** [comment]
Thanks for double checking. I'm going to close it then. It might have just been a hiccup. We can always reopen if it becomes repeatable.

**Comment by Shineslippers** [comment]
Found issue. Not sure it's real issue, but dev may do something with it

**Comment by Nefertumm** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/commit/a7d91afe37fb3ce69e72233d243393bc45eb2550
