### ISSUE TITLE
Rite of Vision (Mulgore - Lvl 7 quest)

### ISSUE THREAD

**Issue by Apachemoo** [chromiecraft/chromiecraft#2728]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Quest can be completed without using item=4823/water-of-the-seers and just by walking and turning in the quest to npc=2984/seer-wiserunner.

### Expected Blizzlike Behaviour

You need to use item=4823/water-of-the-seers (Inducing Vision) for npc=2983/the-plains-vision to appear and to follow to npc=2984/seer-wiserunner.

### Source

https://classic.wowhead.com/quest=772/rite-of-vision

### Steps to reproduce the problem

1. Go to npc=3054/zarlman-two-moons.
2. Accept quest=772/rite-of-vision and see turn in quest (complete) on map.
3. Go to npc=2984/seer-wiserunner and turn in without using item=4823/water-of-the-seers

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Apachemoo. I can confirm this behavior, but I believe this is blizzlike. Consuming the water doesn't look to be a condition of completing the quest. That is just what causes the vision to spawn and direct you to the next step of the quest, and looking at the comments in the link you provided, you do not need to follow the vision ghost wolf.  In some cases the wolf doesn't even spawn but you can still turn the quest in. https://classic.wowhead.com/quest=772/rite-of-vision#comments:id=2762285  I'll leave this open in case someone else can find a source that warrants a change.
