### ISSUE TITLE
Skinning bug Red Cloud Mesa - Tauren

### ISSUE THREAD

**Issue by elmejicanoloco** [chromiecraft/chromiecraft#2733]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

**Good day,**
in "Red Cloud Mesa" there is an inconsistency in the skinning since the beasts of low level are granting skins of higher rank in a very high average as it can be seen in the images each beast of a level of 1-5 droping medium leather in advance.

![WoWScrnShot_010522_114118](https://user-images.githubusercontent.com/97181697/148249025-f359813e-90b9-4a81-ac2e-dfc150f12e13.jpg)
![WoWScrnShot_010522_114242](https://user-images.githubusercontent.com/97181697/148249031-aaaf737c-35da-45a1-9df1-ed2dc517f840.jpg)
![WoWScrnShot_010522_114441](https://user-images.githubusercontent.com/97181697/148249033-c1655a5a-0f18-4f9e-8888-084509c80134.jpg)
![WoWScrnShot_010522_114514](https://user-images.githubusercontent.com/97181697/148249035-3ceeb70d-a3d5-4535-87ed-e311202d90e6.jpg)
![WoWScrnShot_010522_114937](https://user-images.githubusercontent.com/97181697/148249041-5bcbb37a-a91a-4dae-b7bb-13a8d4ba261e.jpg)
![WoWScrnShot_010522_115122](https://user-images.githubusercontent.com/97181697/148249042-c59b0b3e-c19a-4867-bafd-de7516932752.jpg)

### Expected Blizzlike Behaviour

As far as I know this should be leveled and they should be giving maximum light leather or leather scraps

### Steps to reproduce the problem

no action is needed just go to the tauren inital zone and start skinning

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

-Diabolic UI

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. We aware about this issue and it's already repoted here https://github.com/azerothcore/azerothcore-wotlk/issues/6250 Howewer it's still not fixed due to more importaant issue. Keep your eyes opena nd let us know if you will find some other issues. This report i have to close accordingly.
