### ISSUE TITLE
[Molten Core] Doused fires are still glowing, should be extinguished

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2735]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Fires that are shut down should be seen without fire.

### Expected Blizzlike Behaviour

Fires that are shut down should be seen without fire.

### Steps to reproduce the problem

1. Kill boss
2. Douse a fire
3. Place looks like it is on fire still

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Thank you for the report, @Elexias. 

We need some further investigations with the runes, I think. On my local AC I was not able to use a quintessence on the runes.

![image](https://user-images.githubusercontent.com/62797536/148360268-a42dccd5-3b95-4189-b51b-8aeec77717db.png)
Maybe there is an issue with the runes fire. After killing a boss the fire around the runes disappears for a short amount of time and respawns after few seconds. I think, they should completely disappear.

**Comment by Shineslippers** [comment]
Can't reproduce on local AC

https://user-images.githubusercontent.com/85256266/148370469-edf98342-c50b-4440-bbc1-b2c56a778ebd.mp4

**Comment by Elexias** [comment]
Local AC is not same as our server then, can't explain it other way. No guild had it not glowing after using Quintessence but only on your local AC>

**Comment by Shineslippers** [comment]
It's the same. Don't worry. Do you mean fire around or rune glow like on screenshot below
![image](https://user-images.githubusercontent.com/85256266/148374354-92cfb55d-39bf-4deb-9dd3-38363bee3e3e.png)

**Comment by Elexias** [comment]
I mean fire around, we did extinguish all but fire was there, ofc it worked but fire animation wasn't gone.
