### ISSUE TITLE
[Molten Core] Molten Destroyer not chain pulling with Molten Giant

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2737]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

![WoWScrnShot_010522_182943](https://user-images.githubusercontent.com/80590226/148275854-a5fa2a8d-3e29-4e31-95d8-8e5771353036.jpg)

Pulling Giant or Destroyer should pull other partner. On Screenshot you can see that we pulled Giant without Destroyer

### Expected Blizzlike Behaviour

Should be chain pulled

### Steps to reproduce the problem

1. Pull carefully one of them
2. You wont pull second one

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Thank you for the report, @Elexias.

Actually, I was not able to reproduce the issue on my local AC.

![WoWScrnShot_010622_093309](https://user-images.githubusercontent.com/62797536/148353775-71131cc6-1a23-4285-a146-7522cd27fb32.jpg)
I tried several pulls. Taunted skull and chain-pulled square everytime. And the other way around.

**Comment by Elexias** [comment]
@ishidinho I suggest you to test as level 60 and when you test to maximum try to replicate of what I reported.

**Comment by ishidinho** [comment]
@Elexias I tested with level 80 and level 60. Tested several pulls via spells and body pulls.

**Comment by Hyperbearr** [comment]
We've been able to replicate this issue pretty consistently on the live Chromiecraft variant of the core. I've seen footage of multiple guilds (ChromieHomies, Synergy) suffering from this same issue. There's clearly some variance between the local AC you're on and the live core we're using.
