### ISSUE TITLE
Can't deliver The Swarm Grows

### ISSUE THREAD

**Issue by henriquephil** [chromiecraft/chromiecraft#2742]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The required quest item is in inventory, the quest is marked as completed, but I can't interact with the NPC to finish deliver it.

![image](https://user-images.githubusercontent.com/6570379/148584971-f5c7bbf1-482b-472d-8c85-ba4939847c7a.png)

### Expected Blizzlike Behaviour

The player should be able to interact with the NPC to finish the quest.

### Source

https://wowgaming.altervista.org/aowow/?quest=1145

### Steps to reproduce the problem

1. With a Horde character of at least level 30, go to Crossroads and pick the quest with Korran
2. Travel to Orgrimmar and go to Belgrom Rockmaul in Valley of Honor

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. Can't reproduce it on live or local server. You have to try abandon quest and get it again. Maybe delete cache folder from your WoW directory.

![WoWScrnShot_010722_211935](https://user-images.githubusercontent.com/85256266/148589053-61b58d12-0a30-4f20-b44b-170d8a2ecab0.jpg)
![WoWScrnShot_010722_212239](https://user-images.githubusercontent.com/85256266/148589196-fd4099a2-a6a4-477c-ac17-902d3dcb7ce6.jpg)

**Comment by Salehyn** [comment]
Still working as intended in 2023. I can't reproduce any problems here.
