### ISSUE TITLE
Adds on Gehennas and Lucifron

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#2745]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The Flamewalker Protectors on Lucifron and Flamewalker Elites on Gehennas are currently immune to bleeds despite being labeled in game as humanoids  

### Expected Blizzlike Behaviour

They should not be immune to bleeds (deep wounds rend rip etc) 

### Source

https://www.youtube.com/watch?v=21UVptdxQsI&t=2006s&ab_channel=RikhardEriksson 
Yes this video is from vanilla but they are labeled as humanoids in vanilla and they are  in wrath too
33:09 is the start of Lucifron 
53:20 is the start of Gehennas 

### Steps to reproduce the problem

Fight either Lucifron or Gehennas
use rend or any bleed
target is immune 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report. Flamewalkers on Gehennas are not immune to bleed effect. you can check `ImmuneMask` by command `.npc info`. It's available to players
```
[20:44]MechanicImmuneMask: 646135647
[20:44]MECHANIC_CHARM
[20:44]MECHANIC_DISORIENTED
[20:44]MECHANIC_DISARM
[20:44]MECHANIC_DISTRACT
[20:44]MECHANIC_FEAR
[20:44]MECHANIC_ROOT
[20:44]MECHANIC_SILENCE
[20:44]MECHANIC_SLEEP
[20:44]MECHANIC_SNARE
[20:44]MECHANIC_STUN
[20:44]MECHANIC_FREEZE
[20:44]MECHANIC_KNOCKOUT
[20:44]MECHANIC_POLYMORPH
[20:44]MECHANIC_BANISH
[20:44]MECHANIC_HORROR
[20:44]MECHANIC_INTERRUPT
[20:44]MECHANIC_DAZE
[20:44]MECHANIC_SAPPED
[20:44]SpellSchoolImmuneMask: 0
```
![WoWScrnShot_010822_204241](https://user-images.githubusercontent.com/85256266/148654240-76464f62-079e-4f94-8c79-99f70f7afa55.jpg)
