### ISSUE TITLE
Quest: Body and Heart - it miss the "Completation POI"

### ISSUE THREAD

**Issue by Chumanoyasha** [chromiecraft/chromiecraft#275]
##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Quest: [**Body and Heart**](https://wowgaming.altervista.org/aowow/?quest=6002) 
[It has wrong QuestPOI position](https://media.discordapp.net/attachments/766767499987386402/823539916218564658/Wow_zdt40XkHcQ.jpg?width=1202&height=676) bugs all POI icons, no matter addons / client version (enGB,enUS).
[On this video](https://youtu.be/aKK8RWYbg98) you see how it behaves. First time its ok, but if you reopen your map, [you get Lua Error](https://pastebin.com/v2UiAAgV) and don't see any quest on map anymore, untill relog.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

POIs shouldn't be bugged. I tried to abandon this quest (Body and Heart) and it was all fine without it, no bugs, no lua errors.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Take any quests that are done in Mulgore, just so you see them bug on map as well.
2. Accept this quest (it's a chain) : [Body and Heart ](https://wowgaming.altervista.org/aowow/?quest=6002)5/5
3. Open world map, then close it, then again open and see if you get a Lua Error or if Quest POIs of Body and Heart is bugged, or any other quest in this zone. ( You can see how it behaves for me [on my video](https://www.youtube.com/watch?v=aKK8RWYbg98), it bugged on 3 different wow clients for me.)

##### EXTRA NOTES:

Lua Error: https://pastebin.com/v2UiAAgV
Video of bug: https://www.youtube.com/watch?v=aKK8RWYbg98
Quest: https://wowgaming.altervista.org/aowow/?quest=6002

In every client, even enGB client - lua error shown me that if i had this addon:
```
  BlizRuntimeLib_enUS v3.3.5.30300 <logon.chromiecraft.com>
  (ck=62)
```
  I only had Swatter on me, so i wonder, is it some kind of server-side addon, that is buggy? Because i see some people complain about wrong POI quest positions on ChromieCraft overall, i saw one or 2 more quests in Mulgore with that issue. However they didn't bug whole POI system like Body and Heart quest does. Thank you!

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Disable "Lua Error" from the game interface.
And delete Swatter is a useless addon..
Delete the enGB Client because it is full of visual bugs and meaningless LUA ERROR..

**Comment by Chumanoyasha** [comment]
Sorry may be i said something wrong. Issue seems to be server-side. I play on enUS client and problem is not about Lua error, i activated swatter just so you see what's going wrong. 
Problem is: i can't see my quests on my world map. Even on clean Chromie Craft client, IF i have quest with wrong POI positions which is called: Body and Heart.
Quest: https://wowgaming.altervista.org/aowow/?quest=6002

**Comment by Stifler82** [comment]
> Sorry may be i said something wrong. Issue seems to be server-side. I play on enUS client and problem is not about Lua error, i activated swatter just so you see what's going wrong.
> Problem is: i can't see my quests on my world map. Even on clean Chromie Craft client, IF i have quest with wrong POI positions which is called: Body and Heart.
> Quest: https://wowgaming.altervista.org/aowow/?quest=6002

@Chumanoyasha 
Ok sorry, my bad, now i got what you meant..
I didn't get the point of your report.
btw..

Yeah, you was right, it miss the "Completation POI"

**Comment by Stifler82** [comment]
> Sorry may be i said something wrong. Issue seems to be server-side. I play on enUS client and problem is not about Lua error, i activated swatter just so you see what's going wrong.
> Problem is: i can't see my quests on my world map. Even on clean Chromie Craft client, IF i have quest with wrong POI positions which is called: Body and Heart.
> Quest: https://wowgaming.altervista.org/aowow/?quest=6002

Do you use **"Carbonite"** Addon for quest?

**Comment by Stifler82** [comment]
@Chumanoyasha
So, i checked the quest several time and pretty deep into the problem.
The quest is "FIxed" (Server Side), the Bug is **"Client Side"** and unfortunately i'm not able tu fix it by patch, it's a Blizzard's Client Bug..
