### ISSUE TITLE
[Wailing Caverns] (npc=5756/deviate-venomwing glitched in a bush)

### ISSUE THREAD

**Issue by Apachemoo** [chromiecraft/chromiecraft#2751]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

npc=5756/deviate-venomwing stuck in bush in Wailing Caverns. Initially able to be targeted with ranged spells but then not able to cast spells (as if far away). We did not take damage and we skipped the mob.

### Expected Blizzlike Behaviour

Suppose to attack.

### Source

![sgsg](https://user-images.githubusercontent.com/96935018/148647798-26b9c79a-25e1-478c-b1d4-9a8addb46b59.PNG)
![ssdad](https://user-images.githubusercontent.com/96935018/148647799-7ba9e1ca-6f79-460b-ac2d-1d3366a7fd34.PNG)

### Steps to reproduce the problem

1. Go to Wailing Caverns
2. Go to npc=3674/skum and walk north
3. DB GUID: 87134, current GUID:166
4. See trash mob stuck in bush. 
5. See if you can melee attack or attack from range until the target is too far away.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Apachemoo** [comment]
Did another run
![sdas](https://user-images.githubusercontent.com/96935018/148653546-0d63360a-6e8b-4d81-9963-82e3e0b41090.PNG)
.

**Comment by Shineslippers** [comment]
Thank you for the report. I can confirm that this npc has issue on live server, but on local server he is ok. For now i will keep this report open, but probably issue should be fixed after next server update.
