### ISSUE TITLE
[Druid - Tranquillity] T1 8 pieces + Talents leads to 0 CD on Tranquility

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2754]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

8 Pieces of T1 reduce CD of Tranquility by 50%, druid talent Improved Tranquility reduces Cooldown from 8 mins to 4 mins, if combined with 8 pieces of T1 it gives 0 sec CD instead 50% of 4 mins = 2 mins. So when you have talent and 8 pieces of T1 you get 0 sec CD instead 2 min CD.

![image](https://user-images.githubusercontent.com/80590226/148683756-074f466d-d0c9-4873-a523-26af15f81921.png)

### Expected Blizzlike Behaviour

8 Pieces of T1 reduce CD of Tranquility by 50%, druid talent Improved Tranquility reduces Cooldown from 8 mins to 4 mins, if combined with 8 pieces of T1 it gives 0 sec CD instead 50% of 4 mins = 2 mins. So when you have talent and 8 pieces of T1 you get 0 sec CD instead 2 min CD.

### Steps to reproduce the problem

1. Get talent in Resto for reduce CD on Tranquility
2. Get 8 pieces of T1
3. Have no CD on Tranq

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/6461#issuecomment-999064487
> It's not a bug. Spell mods (with a few excpetions) should be additive, not multiplicative. Changing this will result many gamebreaking bugs.
