### ISSUE TITLE
[Molten Core, ZG, AQ] Deposit and potentially herbs respawn within Raid IDs

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#2757]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Dark Iron Ore Deposits within Molten Core respawn.

### Expected Blizzlike Behaviour

Deposits and also herbs shouldn't respawn in a dungeon or raid.

### Steps to reproduce the problem

Get a Molten Core id
Mine a deposite
wait for it to respawn

### Extra Notes

A) as with the deposits in Molten Core, likely deposits in ZG and AQ will be affected to
B) same rule applies and is likely to affect herbs in ZG
C) Dungeons might be affected, too. Possible dungeon to test is Dire Maul East, there are 2 or 3 Thorium Deposits after the final boss. they might respawn after 45 mins / 60 mins, too.

[https://classic.wowhead.com/object=165658/dark-iron-deposit#comments](https://classic.wowhead.com/object=165658/dark-iron-deposit#comments)
[https://classic.wowhead.com/zulgurub#objects](https://classic.wowhead.com/zulgurub#objects) -> filter for herbs and mining nodes
[https://classic.wowhead.com/ruins-of-ahnqiraj#objects](https://classic.wowhead.com/ruins-of-ahnqiraj#objects)
[https://classic.wowhead.com/ahnqiraj#objects](https://classic.wowhead.com/ahnqiraj#objects)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by j-hdt** [comment]
ZG and AQ herbs / deposits might not be affected cause they are dungeon specific versions without respawn timer.
But Molten Core uses the generic Dark Iron Ore Deposits, sharing the regular respawn timer.

**Comment by acidmanifesto** [comment]
i am putting this as Bug Under Evaluation for a couple of reasons.
Need to confirm if the node is apart of the pooling system
Need to confirm if it is not apart of the pooling system, what their timers should be.
Confirm we do not have a respawn problem with the node.

**Comment by acidmanifesto** [comment]
@chromiecraft/developers can we get confirmation if the node issue is apart of pooling in the instance in this case?
@temperrr can you see if any testers can verify if these nodes do not respawn back?
