### ISSUE TITLE
Raid reset currently scheduled for Tuesday mornings

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#2758]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Molten Core raid ids are expiring on tuesday mornings.

### Expected Blizzlike Behaviour

On European Servers, regular server maintenance and Raid resets take/took place on Wednesday mornings.

### Steps to reproduce the problem

Aquire a MC id and check the expiry in the character menu

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi @j-hdt. Thans for the report. I believe this is a server setting. I'll double check with the Admins, but I do not believe this is a bug.

Playing on a US server, ours would reset super early on Tuesday's, which was also when our maintenance was.

**Comment by j-hdt** [comment]
> Hi @j-hdt. Thans for the report. I believe this is a server setting. I'll double check with the Admins, but I do not believe this is a bug.
> 
> Playing on a US server, ours would reset super early on Tuesday's, which was also when our maintenance was.

please consider this:
[https://www.chromiecraft.com/information-on-upcoming-raids/](https://www.chromiecraft.com/information-on-upcoming-raids/)

**Comment by Shineslippers** [comment]
That's definitely not blizzlike

**Comment by Stump876** [comment]
Actually it is. https://us.forums.blizzard.com/en/wow/t/how-does-raid-reset-work/665499/2
But speaking with the Admins they do intend making it on Wednesday per EU raid schedule.

**Comment by Nyeriah** [comment]
Wasn't this fixed last week? Is it still a problem? Please check in-game on the live server (not AC, no intententions of changing it there)

**Comment by j-hdt** [comment]
it got fixed on CC in the meanwhile - no clue about AZ

**Comment by balleny** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/10111
already closed.
