### ISSUE TITLE
Bad language and behaviour from a player

### ISSUE THREAD

**Issue by Varr05** [chromiecraft/chromiecraft#2759]
Apologies I know this isn't really your guy's issue - I have blocked the player. This was not aimed at me but at someone else in the party

See screenshot for undesirable language and attitude from "Suddendeath"
![Snag_19820e5](https://user-images.githubusercontent.com/95713206/148702686-3e33660d-9f76-47ef-82e7-0bbfa49922ea.png)

**Comment by Shineslippers** [comment]
Hello. Guthub is place where you can report bugs. We're not related to our GMs team. Don't have even possibility to do something on live server. I can't help with this. You have to create ticket on Discord server or find out GM online in game.
