### ISSUE TITLE
The Beast - Loot Table

### ISSUE THREAD

**Issue by veloxic76** [chromiecraft/chromiecraft#2760]
### What client do you play on?

frFR

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Since some days The Beast in UBRS give always the same loot :

https://wowgaming.altervista.org/aowow/?item=12963
https://wowgaming.altervista.org/aowow/?item=12964
https://wowgaming.altervista.org/aowow/?item=12709

Every runs the loot are the 2 legs or 1 legs and the dagger. I try to have the lightforge spaulders for finish my t0.5 quest but they never drop. I asked some guys and same loot happen.

### Expected Blizzlike Behaviour

The Beast should give all loot from the table not only the 3 items

### Steps to reproduce the problem

1. The Beast
2. No
3. No
4. SQL Database for The Beast
5. No

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
Wow, I had same loots for more than 3 times :D

**Comment by nolt** [comment]
Test performed on AC rev b2df4aa

Drop and loot is just fine:
https://wowgaming.altervista.org/aowow/?npc=10430#drops
![Zrzut ekranu z 2022-01-12 20-27-54](https://user-images.githubusercontent.com/6367933/149208486-63c8195f-2563-4b93-bfc1-c61227da87eb.png)
