### ISSUE TITLE
Quest: 'Seeing What Happens' Problem

### ISSUE THREAD

**Issue by 15414h** [chromiecraft/chromiecraft#2766]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

I got a Problem with this quest 'Seeing What happens'.
I don't know if this is Blizzlike or not, but I inserted the 'Miniature Platinum Discs' into the Pedestal and finished the quest without talking all the way through with the Hologram. So I did not get the follow-up quest, and the Discs were stuck inside the Pedestal.
I deleted the quest then, but I cant pick it up again. So the whole questline is stuck, and I cant finish it.

I don't know if this is a 'bug'. It's definitely bad for anyone who does the same by accident, cause the questline cant be resumed then.

### Expected Blizzlike Behaviour

might be bugged on original server too. no idea.

### Source

https://classic.wowhead.com/quest=2946/seeing-what-happens
https://classic.wowhead.com/item=6064/miniature-platinum-discs

### Steps to reproduce the problem

do the quest with the miniature discs, and dont talk to the hologram but click on the pedestal, then the questline gets stuck apparently and cant be resumed...

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by 15414h** [comment]
UPDATE:
I just went to the Pedestal again to see if by chance I can get the quest ... and Indeed, the Hologram was standing there above the Pedestal. I dont know if I missed that before, or if it just re-appeared after a while... anyway. I got my quest update now and I think I can finish it.

**Comment by ishidinho** [comment]
Hey @15414h. Thank you for the report.

So, your problem is gone now?

> I just went to the Pedestal again to see if by chance I can get the quest ...

Did you left the dungeon or just tried it again?

**Comment by 15414h** [comment]
The Pedestal is in Tanaris. Yes, The problem is gone now. I could finish the quest. I dont know if I was just blind, too much zoomed in, or if the Hologram was actually gone when I did the quest first. But I went back there and the hologram was there with the question mark above the head. maybe the quest had a time out after i deleted it, and I just had to wait.
You can close this ticket I guess. thanks.

**Comment by Shineslippers** [comment]
Reports is valid, but it's already reported https://github.com/chromiecraft/chromiecraft/issues/2475 Issue is exist.
