### ISSUE TITLE
Cannot douse Fires after coming back to MC day[s] later

### ISSUE THREAD

**Issue by Jonny727272** [chromiecraft/chromiecraft#2767]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Since it has only been out a week, this may need more testing. We cleared MC up to Shazz (6/10) on the first night of raiding. When we came back for the 2nd night, we killed the next two and then went to get our douses from Duke Hydraxis. We weren't able to douse any of the runes from the first 6 bosses, but could douse the final two, which caused Domo to spawn. 
There was no cog icon showing up, and even clicking the douse in the bag and hovering the hand icon over the rune did nothing.

I would want to test this more to see if it was a one-off, or something else.

Raid times are in EST:
First day - Thursday 9pm to 12am
Second day - Sunday 9pm to 12am

### Expected Blizzlike Behaviour

We should be able to douse any rune at any time once a boss has been defeated.

### Source

Don't really have a source on this one, other than playing the game for a long time.

### Steps to reproduce the problem

Kill boss.

Wait a day/server restart will probably work.

Go back into MC and try to douse rune

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04
Unless this was auto-generated by my other PC, I was playing on Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Thank you for the report.

1. There is exist issue with rune animation. If you doused a rune it will light up again after 5m. It doesn't affect summon of Majordomo, but you can't click on it again.
2. There is exist indended feature: if restarts or crashes happen, to minimize the bother caused to players when those unfortunate events happen during a run it's dousing a runes automatically. Usualy server doing restart at 6 a.m. That's why you able to summon Majordomo

From you description i can say there is no unplanned/unknown issues. This report i have to close accordingly.
