### ISSUE TITLE
Character creation disconnections

### ISSUE THREAD

**Issue by Amrx2** [chromiecraft/chromiecraft#2769]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Multiple players reporting of people being unable to create characters on Chromiecraft / getting disconnected after less than a minute spent on the character creation screen. This appears to be affecting players from all around the world (had reports in of players from NA, SEA & EU all affected). Confirmed on both the 'clean' chromie client as well as clients provided by other private server realms. 

GM accounts also affected as confirmed by Elise in #support channel on CC discord.

### Expected Blizzlike Behaviour

Should not be disconnected until at least 30 minutes or so in the character creation screen. 

### Source

N/A

### Steps to reproduce the problem

Log in to Chromiecraft
Create a new toon
Wait to be disconnected

### Extra Notes

A few players have produced these ping reports, provided in the attached .txt files
[connection.log](https://github.com/chromiecraft/chromiecraft/files/7850309/connection.log)
[connection (1).log](https://github.com/chromiecraft/chromiecraft/files/7850310/connection.1.log)
.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
Players with this issue making a new account also get kicked out pretty quickly

**Comment by davegrier** [comment]
I'm experiencing this issue and also, within the last 2 days or so, ~10% disconnection rate when switching characters while already logged in. I switch the character quickly, but the progress bar hangs at 100% and disconnects after a minute or two (possibly the same interval as the character creation disconnect.)

**Comment by temperrr** [comment]
> How long is the approximate wait?

Between 10-30 seconds is what I heard

**Comment by TheNax2** [comment]
Seems to be possible to create a char if you randomize your name, but choosing your own name will cause DC

**Comment by Amrx2** [comment]
> > How long is the approximate wait?
> 
> Between 10-30 seconds is what I heard

Anywhere between 10 seconds up to under 3 minutes. This was from a user on discord who recorded the times they were disconnected:

'Entering character creation and tabbing out disconnect times:
1:17
:48
1:15
1:16
2:26'

**Comment by dbosco051394** [comment]
I also have the same problem, as do 3 others that I know that all recently started playing. We all downloaded the torrent.

My friend does not have the issue, and his distinct difference is that he patched his existing WoW rather than torrenting it all.

I also timed my disconnects and they match Amrx2's times pretty closely.

Hope this helps!

**Comment by temperrr** [comment]
GIrlfriend had this issue on her account, however when I logged in from my network and her account, it worked just fine.

**Comment by nolt** [comment]
I just tested this on local AC and CC using same game client which is ChromieCraft (Linux)

- on AC I didn't noticed such an issue
- on CC I spent more than 10mins on creating a character - no DC (tried few times)
- issue occurs occurs when I created a character, log in, log out and then game client was not responding to any clicks @ character creation screen
- issue occurs also when I created a character, log in, log out delete created character and tried create character with same name

in both cases in terminal but it's rather wine output
````
open_http_connection create_netconn failed: 12029
```

**Comment by KCorruption** [comment]
I am also having this issue with increasing severity over the past few weeks. Initial connection seems fine, log out and stay in character screen / log an alt, and will get dc'd less than 2 minutes later. Client was downloaded from the CC website. EnUS client.

**Comment by mosthatedx** [comment]
This also happens in character creation of a "Change Faction" as well.  A big problem when money is donated for this function and does not work.

**Comment by mosthatedx** [comment]
> Marking as Bug Under Evaluation due to the devs being aware of it and are currently assessing the issue.

It says "closed" and 9 tasks accomplished.  However, i am still unable to change character faction.

**Comment by FrancescoBorzi** [comment]
This bug is confirmed, but it's not clear how we can reproduce it. In order to fix it, we need to understand which conditions are causing the bug.

**Comment by Winfidonarleyan** [comment]
@Amrx2 What is your ping to server's?

**Comment by Winfidonarleyan** [comment]
There is a small chance that because of the asynchronous auction sessions do not have time to update and therefore the client is disconnected

**Comment by temperrr** [comment]
This issue seems to be resolved. If you still have this issue, feel free to make a new report.
