### ISSUE TITLE
Moonfire positional requirement bug

### ISSUE THREAD

**Issue by xChaosityx** [chromiecraft/chromiecraft#2770]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Druid Moonfire ability only able to be casted when facing the target, Currently it has a normal 90 degree casting positional requirement.

### Expected Blizzlike Behaviour

Druid moonfire ability should have no directional casting requirements 

### Source

https://youtu.be/zpgOvqP_470?t=311
https://youtu.be/zpgOvqP_470?t=88
https://youtu.be/zzLaos13gYM?t=99
https://youtu.be/zzLaos13gYM?t=450

### Steps to reproduce the problem

1. Target mob
2. Face away from mob at more than a 90 degree angle
3. Try to cast moonfire

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Windows 10 21H1 Build 19043.1315

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hi @xChaosityx. Thank you for the report.

I see no problem with the spell. The spell behaves as expected in my eyes. The Moonfires target should stand in a 180 degree in front of you. I watched your linked videos (with 0.25 speed). They confirm my expectations.

In other words: You should not be able to cast Moonfire on targets standing behind your character.

Please correct my if I misunderstood something.

WoW Classic:

![WoWScrnShot_011222_095705](https://user-images.githubusercontent.com/62797536/149102620-822375e8-dfac-4080-9e46-ce8e4b8312d1.jpg)

![WoWScrnShot_011222_095900](https://user-images.githubusercontent.com/62797536/149102651-bd860e41-24fc-4395-9964-d7da6ba24c4e.jpg)

Local AC:

![WoWScrnShot_011222_101850](https://user-images.githubusercontent.com/62797536/149102312-32a35e2f-6323-4b68-aad2-5de7dfbb7f17.jpg)

![WoWScrnShot_011222_101907](https://user-images.githubusercontent.com/62797536/149102422-977f107a-6c9e-4561-be03-4c2a5fbb0a25.jpg)
