### ISSUE TITLE
Lorekeeper Lydros is not in Dire Maul dungeon

### ISSUE THREAD

**Issue by fabiolete** [chromiecraft/chromiecraft#2776]
The npc Lorekeeper Lydros miss in Dire Maul dungeon, and for this reason players can´t get the enchants.
Thanks for your attention.

**Comment by Shineslippers** [comment]
Thank you for the report. Please use button `Get Started` when you creating a reports. Regarding to issue. [Lorekeeper Lydros](https://wowgaming.altervista.org/aowow/?npc=14368) is staying on his usual place in Dire Maul Librarynce. you can get there from DM:N or DM:E.
![Capture](https://user-images.githubusercontent.com/85256266/149295686-c4c3b4c7-eb10-481f-80e0-6a8e21d4c5ad.PNG)
![WoWScrnShot_011322_113947](https://user-images.githubusercontent.com/85256266/149295697-32c645c1-f3ec-4520-a576-72bee677cfe3.jpg)
