### ISSUE TITLE
Deep Freeze deals damage vs "temporarily" Immune Players (PVP)

### ISSUE THREAD

**Issue by Anthimaa** [chromiecraft/chromiecraft#2779]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Hi, i tested Frost Mage with Fingers of Frost proc. Using Deep freeze on "Temporarily" Immune targets (during Warsong Gulch, that means --> PVP context) :
These targets immune to CC, but not immune to spell damage (Warriors during BLADESTORM,  Hunter Beastmaster with BESTIAL WRATH up, ecc....) receive 4-5k spell damage from Deep Freeze and istantly die.

### Expected Blizzlike Behaviour

Deep freeze stuns the target for 5 sec. Only usable on Frozen targets (i usually use it on Finger of Frost Proc vs those targets). Deals 1469 to 1741 damage to targets "PERMANENTLY IMMUNE" to stuns.

### Steps to reproduce the problem

1. MAGE FROST with Finger of Frost Proc (just cast Frostbolt until it procs)  and WARRIOR ARMS with Bladestorm
2. Cast Deep freeze (Mage) on Bladestorm
3. Combat Log---> Damage dealt on PVP target (BUG).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Anthimaa. Thank you for the report.

This issue is already known. https://github.com/chromiecraft/chromiecraft/issues/2714
