### ISSUE TITLE
[NPC][Durotar] Burning Blade Cultist at the wrong place

### ISSUE THREAD

**Issue by wowdecision** [chromiecraft/chromiecraft#278]
##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

An npc is spawned a bit off of the place where it should be. Burning blade cultist came at me out of nowhere at the place where only harpies are supposed to be in durotar. 
I guess it fell through the ground as there is a cave above.
![image](https://user-images.githubusercontent.com/1884642/112246454-962e0900-8c4a-11eb-8a89-f3f65b0f2448.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The npc shouldn't be there.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Durotar @ 53.1, 25.0

##### EXTRA NOTES:

[The npc](https://wowgaming.altervista.org/aowow/?npc=3199)

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
@wowdecision Please target the npc and use .npc info,  so the person to fix it has the exact unique guid of the affected npc. This way we don't know which one is misplaced.

**Comment by eTzmNcbkrng** [comment]
There are 7 GUIDs for this NPC, I checked them all on a local server and they are spawned correctly.
Also, I've done this quest on ChromieCraft on Orc Warlock, Orc Rogue, Troll Shaman and Troll Hunter and never did not come across this issue.
Maybe VMaps Issue?

Can't troubleshoot any more without further details.

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303
