### ISSUE TITLE
Hunter - Agility wrong conversion to Attack Power

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#2782]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Currently, I have 270 Agility acording to the displayed base stats. When I hover it, it tells me I get 260 Attack power. According to our expansion hunters should get 1 ranged attack power per point of agility, so I should be getting 270 attack power.

### Expected Blizzlike Behaviour

1 Point of agility should convert to 1 point of Attack power, and I'm not getting the full value of agility.

### Source

https://wowpedia.fandom.com/wiki/Agility_equivalence_points

### Steps to reproduce the problem

My gear is as follows:

- Swift Flight Bracers ( +7 Intellect )
- Black Dragonscale Leggings
- Black Dragonscale shoulders
- Black Dragonscale Breastplate ( +3 Stats )
- Beaststalker's Cap
- Beaststalker's Gloves ( +7 Agility )
- Beaststalker's Belt
- Beaststalker's Boots
- Cape of the Black Baron (+3 Agility)
- Mark of Fordring
- Tarnished Elven Ring
- Blackstone Ring
- Blackhand's Breadth
- Strength of the High Chief
- Barbarous Blade ( +25 Agility )
- Carapace Spine Crossbow

My Specialization
https://wotlkdb.com/?talent#cZceVoohzGIsxhVo:f0Zzm

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @claudiodfc. Thank you for the report.

There is no problem with the ranges attack power calculation. But I understand that the tooltip can be confusion, so let me explain.

The calculation for ranged attack power for hunters is the following.

> `Ranged Attack Power = (Char.Level * 2) + Agility - 10`
(source: https://wowwiki-archive.fandom.com/wiki/Attack_power#Attack_power_table)

The tricky thing here is, that the `Agility - 10` part is shown in the tooltip in your character info. You will always see a attack power value that is your agility minus ten.

My test character as a example. He is level 60 and has 123 agility. You can see that the ranged attack power value is calculated correctly with 233.

`233 = (60 * 2) + 123 - 10`

![image](https://user-images.githubusercontent.com/62797536/149518617-e3e4d8e4-9feb-465c-9cc5-d3570d12e527.png)

![image](https://user-images.githubusercontent.com/62797536/149519254-db25e2e8-73d4-4af0-bf1f-3cf033f04dde.png)

**Comment by claudiodfc** [comment]
Thank you @Ishidinho I found out today this as well sorry for the report. However I think i found another issue for both Intellect and Agility.

If you get the talent Combat Experience in Marksman tree, your Intellect and Attack power isn't increased by 4%.

Check out this Spreadsheet for my calculation:

https://docs.google.com/spreadsheets/d/197o8sEQ3qDQ--tsxlbHLF8zo5lMppvNPrDG3J3wqatE/edit?usp=sharing

If you check the Attack Power, I should have more Intellect and Agility than what I currently have. Can you give a look?

**Comment by ishidinho** [comment]
@claudiodfc Sure. I will have a look the next time I am on my PC.
I keep this ticket closed. If there is a problem with he talent, we open a new one.
