### ISSUE TITLE
[Molten Core] Ragnaros faces pet during RP and casts lava burst

### ISSUE THREAD

**Issue by Clusterfonk** [chromiecraft/chromiecraft#2783]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Ragnaros will faces the pet (in meele range) and starts casting lava burst. The raid will be in combat because of this and Ragnaros will also say lines like BY FIRE BE PURGED during RP.

https://streamable.com/atcexn

### Expected Blizzlike Behaviour

Ragnaros should face his designated direction, Raid shouldnt be in combat and lava burst isn't cast during Ragnaros RP

### Source

https://www.youtube.com/watch?v=bxjFjYX1N9w

### Steps to reproduce the problem

1. tame a pet
2. go to molten core
3. kill all bosses except ragnaros
4. position pet in range of ragnaros
5. talk with majordomo 
6. start encounter

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

local azerothcore-woltk

**Comment by Clusterfonk** [comment]
The thing is that happend on live chromiecraft aswell and after the raid I went on my local server to reproduce it

**Comment by ishidinho** [comment]
@Clusterfonk Okay. We will have a look on that. Next time, please provide some screenshots and list ChromieCraft in "Server" section.
