### ISSUE TITLE
[Blackfathom Deeps] Mobs stand still and in place

### ISSUE THREAD

**Issue by Apachemoo** [chromiecraft/chromiecraft#2793]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Mobs stand still (maybe only in shallow water which you can run on) and in place and won't run and attack players. They might target you and cast a spell but then they lose agro.

### Expected Blizzlike Behaviour

Mobs should be hostile and attack and run towards players.

### Source

![123](https://user-images.githubusercontent.com/96935018/149551481-4408afb2-3c0d-4ca2-aa61-32ae99a29abc.PNG)

https://classic.wowhead.com/blackfathom-deeps

### Steps to reproduce the problem

1. Go to blackfathom-deeps dungeon.
2. Look at npc=4805/blackfathom-sea-witch or npc=4807/blackfathom-myrmidon or npc=4819/blindlight-muckdweller or npc=4818/blindlight-murloc.
3. In places where there is water on the ground such as going in the direction of npc=6243/gelihast. You will just be able to run past and skip mobs. They might target you for a few seconds and then lose agro.

### Extra Notes

It seems like there are issues with mobs in water.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
@Apachemoo 

We updated the server today, can you see if it s still the case?
