### ISSUE TITLE
DC from server and stuck at reconnecting for 3-5 mins

### ISSUE THREAD

**Issue by thegreatestviz** [chromiecraft/chromiecraft#2795]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

This is not an ingame issue but rather a connection issue, every 30-40 mins the game kicks me and my wife out of the game( same IP not more than 3 accounts - 2 of mine 1 of wife)

When trying to reconnect the game is stuck or held up at connecting and does not let us login for atleast 3-5 mins. most of the times we keep trying to close the game client and login and it lets us atleast after 3-5 mins.

### Expected Blizzlike Behaviour

To not kick us out of CC every 30-40 mins ( sometimes even lesser)

### Source

i've recorded the issue happening and uploaded an unlisted video on YT

https://youtu.be/55X18_Eue5s

Please note the timer move to 14.00 to see the issue occurring

### Steps to reproduce the problem

There is no definite quest that helps reproduce the issue, in a spam of 3 hours of gaming it kicked us out like 5 times, i feel a bit dissappointed to introduce her to wow and she is experiencing such an issue

### Extra Notes

Issue also happens when changing accounts. 

Kindly note that this issue was not happening till yesterday and only today i've encountered it.

Not sure if it will occur tomorrow but I will update this is possible

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Win 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @thegreatestviz. Thank you for the report.

Actually, this issue is difficult to reproduce. I have no problems on both ChromieCraft and local AC.

Can you exclude all non-wow-related issues (short internet connection loss, VPNs, etc.)?
Have tried a complete clean WoW installation with no addons?

**Comment by Salehyn** [comment]
This belongs to the support channel on discord, if they still experience problems.
