### ISSUE TITLE
Ranged weapon wrong Attack Speed

### ISSUE THREAD

**Issue by hanabi5** [chromiecraft/chromiecraft#2796]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Currently, If you create a new Hunter and check your character's weapon speed, it's lower than what the weapon speed displays. I haven't read anywhere of stats increasing weapon speed and at level 1 we don't even have haste.

For example, equipping `Carapace Spine Crossbow` You get `2.87` Attack speed, instead of `3.3`

##### (Img.1 - Weapon stats)
![image](https://user-images.githubusercontent.com/54484196/149567908-140a6046-a819-49f2-9143-b8c17cfbfe74.png)

##### (Img.2 - Attack speed with starting bow at level 60)
![image](https://user-images.githubusercontent.com/54484196/149567939-63946543-b538-4db1-b2c6-a7477f013f31.png)

##### (Img.3 - Attack speed with starting bow at level 1)
![image](https://user-images.githubusercontent.com/54484196/149568220-ecc3dbb0-cb3f-4de8-aedf-90576d0d7f3f.png)

### Expected Blizzlike Behaviour

Weapon speed should be the current weapon's speed.

### Steps to reproduce the problem

New character
Check weapon speed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @claudiodfc. Thank you for the report.

I can confirm that for hunters the ranged attack speed is lowered. I tested the starter bow with a level 1 warrior. Ranged attack speed here is the same as on the weapon.

![image](https://user-images.githubusercontent.com/62797536/150108323-d3eb91fe-65f8-4d66-820d-05759408dca0.png)

But I am not confident enough in ranged/hunter calculations to confirm that there is an issue. Sadly, I did not find any proof on the internet. So, we need a source or a more experienced second opinion here.

**Comment by Gultask** [comment]
The modified attack speed is due to hunters having an inherent 15% ranged haste built into their class since patch 3.1.

[The patch notes are as follows](https://wowwiki-archive.fandom.com/wiki/Patch_3.1.0#Hunters):
>Ammunition: All types of gun and bow ammunition now stack to 1000. All quivers and ammo pouches no longer provide haste. **15% ranged haste is now built into the hunter's Auto Shot.**

[The calculation for attack speed is](https://wowwiki-archive.fandom.com/wiki/Attack_speed?oldid=2374994): Attack_speed = "current attack speed" / (("Percent increase or decrease" / 100) + 1 )
So: 2.3/1.15 = 2.00
For another example, using my own character using Bloodseeker (3.3) with 0 haste: 3.3/1.15 => when rounded is 2.87
