### ISSUE TITLE
Can't click on the NPC to complete the quest "Alliance Trauma"

### ISSUE THREAD

**Issue by Sinthalos** [chromiecraft/chromiecraft#2798]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I need to speak to the NPC "Doctor Gustaf VanHowzen" to complete the quest but I'm unable to click on him.

### Expected Blizzlike Behaviour

Should be able to normally complete the quest.

### Source

![NPC bug](https://user-images.githubusercontent.com/97765273/149590193-36303b14-adb0-477a-8d80-d1a25e0a13e5.jpg)

### Steps to reproduce the problem

Need to be at least level 35 with a minimal First Aid skill of 225.
Take the quest in Ironforge from Nissa Firestone.
Go to Doctor Gustaf VanHowzen to try to complete it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Sinthalos. Thank you for the report.

Unfortunately, I am not able to reproduce the problem on local AC.

* `.go creature 33780`
* `.quest add 6625`

![image](https://user-images.githubusercontent.com/62797536/149617825-1725d2bd-830e-47a5-9451-6d5a7dadd900.png)

Can you please try it again after the next server start?
Maybe it helps to clear your "Cache" folder in the CC installation folder.

**Comment by Sinthalos** [comment]
Yes it worked now indeed ! Thanks for the quick answer.
