### ISSUE TITLE
Permanant combat bug

### ISSUE THREAD

**Issue by xChaosityx** [chromiecraft/chromiecraft#2799]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

During the Blackfathom deeps/Stockades dungeon in RDF, Randomly only the tank (Paladin level 26) and myself (Paladin level 27)  would be permanently stuck in combat even with no mobs anywhere that are agroed, and the only fix was to teleport out/into the dungeon.

### Expected Blizzlike Behaviour

Not to be stuck in combat when theres no mobs in combat with you.

### Source

I don't believe theres any need for a Source for this.

### Steps to reproduce the problem

1. Queue up in RDF for Blackfathom deeps/stockades
2. Do the dungeon like normal

### Extra Notes

All the other party members didn't have this issue, only the paladin tank and myself the paladin healer would be effected.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Windows 10 21H1 19043.1415

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @xChaosityx. Thank you for the report.

I was not able to reproduce the problem under your stated circumstances.
I made two palas queue RDF, run through the dungeon, killing mobs - always got outfight after combat.

**Comment by xChaosityx** [comment]
Hmm, It only seemed to happen sometimes because I ran it about 5 times total and only 2 runs it was broken and both times the tank was also a paladin and had the same bug at the same time, Maybe it was something regarding my new macros? I added /startattack to my healing/damage macros so I was constantly dealing damage, It did seem to occur the most often when we were dealing with the non kill-able mobs in water locations. But that report someone mentioned they might of fixed the water bug? so I'll check it out again and see if its still an issue

**Comment by HasieEST** [comment]
From experience, this bug could occur, when mob runs to get another into combat, who isn't able to combat you. Good examples are the thrashers that shouldn't be able to come on land, therefore being in combat with players until end of the dungeon.

**Comment by Nyeriah** [comment]
Type .debug hostile and post here what it shows when it happens
