### ISSUE TITLE
Deadmines: Mr. Smite fight - additional pirates from the ship join the fight

### ISSUE THREAD

**Issue by Buggyswires** [chromiecraft/chromiecraft#280]
##### FACTION

- [X] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

If you pull Mr Smite and his two stealth adds in the deadmines some pirates from the ship also join the fight 
(a problem on every WotLK server i tried up to now)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You pull the two adds and Mr. Smite joins the fight. 
No additional pirates from the ship should aggro

Example: https://www.youtube.com/watch?v=PY7frfcqvvw

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Deadmines: Pull the adds from Mr. Smite
2.  Two or even more pirates from the ship add too
3. 
4.

##### EXTRA NOTES:

NPC ID 646
https://wowgaming.altervista.org/aowow/?npc=646

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
Exists on AC master:
https://github.com/azerothcore/azerothcore-wotlk/issues/4945

**Comment by FrancescoBorzi** [comment]
@55Honey then it's linked :)

**Comment by nicklashbrook** [comment]
This isn't fixed, same thing just happened to my RDF part.
