### ISSUE TITLE
Water breaking mobs

### ISSUE THREAD

**Issue by xChaosityx** [chromiecraft/chromiecraft#2801]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

If mobs are located in any amount of water (The ocean, a small puddle) It can sometimes cause their pathing to break and refuse to move, This happens quite often in the Blackfathom deeps murloc section. During this if your in a party you need to commonly stack on the mob or its unkillable, I believe whoever has aggro has to be super close.

### Expected Blizzlike Behaviour

For mobs to not have pathing break, Or become unkillable and only become killable when stood on mob.

### Source

I don't believe this needs a source

### Steps to reproduce the problem

1. Agro mobs that are inside, or walking inside a body of water
2. Try to attack mob at range

### Extra Notes

It seems to only happen sometimes, so to get accurate results of verifying the bug it might take a little bit of time, Also during a dungeon group while we experienced this bug the other members recalled having the same water bug issue in various different places while playing/leveling, So I don't think its just this dungeon.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Windows 10 21H1 19043.1415

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
We updated the server today, can you see if this is still the case?

@xChaosityx

**Comment by xChaosityx** [comment]
Did some questing in some shallow and very deep water, as well as did the dungeon again and it worked perfectly! It seems fixed :)
