### ISSUE TITLE
creature entry 417 drops DM recipes

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#2802]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

![image](https://user-images.githubusercontent.com/84640316/149617492-e881f160-a467-4bb4-96a9-eb4346b052c4.png)

### Expected Blizzlike Behaviour

these should only drop from the cache in DM. Not from a random lvl 80 mob.

### Source

https://tbc.wowhead.com/item=18519/pattern-shifting-cloak

### Steps to reproduce the problem

keira 3 or mysql.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nolt** [comment]
Output you included is all loot that can be found in "Knot Thimblejack's Cache".
Knot Thimblejack's Cache contains:
https://wowgaming.altervista.org/aowow/?object=179501

Pattern drop/loot
https://wowgaming.altervista.org/aowow/?item=18519

What mob dropped Pattern: Shifting Cloak; Felhunter?

**Comment by baranzadeoglu** [comment]
> What mob dropped Pattern: Shifting Cloak; Felhunter?

no mob is supposed to drop it. It is from Knot Thimblejack's Cache. Its table is mixed up with felhunter (entry=417). Felhunter shouldn't drop these.

**Comment by nolt** [comment]
I checked all creatures in game only Felhunter drops:

```
+-------+-------+--------+-------------------------------------+
| entry | Item  | Chance | Comment                             |
+-------+-------+--------+-------------------------------------+
|   417 | 18519 |   0.02 | Felhunter - Pattern: Shifting Cloak |
+-------+-------+--------+-------------------------------------+
```
