### ISSUE TITLE
Rokaro - Horde Is not working with Champion of the Horde Quest 

### ISSUE THREAD

**Issue by Jpizzle31** [chromiecraft/chromiecraft#2808]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Reporting a bug - Holyshield is toon in-game Horde side. 

I have completed all quests for the Onixya quest line up to champion of the Horde.  After I spoke with thrall I should have been given the quest and sent to  “Description
Rexxar, one of my most loyal champions, has discovered a way into the lair of the dragon. However, he has left Azeroth to join our expedition into Outland. However, he left his companion, Rokaro, in Shadowprey Village with this information. You are to seek him out.” 

However, I did not receive this quest and Rokaro is blank when I speak with him. 

I know this quest is still active because I have guildies who are currently completing it today Jan 16th. I’m not sure what the issue is but I’m carton I might need the quest reset for myself in-game. I have the Trinket from the questline before so I know I have someplace the items up to this point. Thank you for the help and appreciate it. 

### Expected Blizzlike Behaviour

One I am done speaking with Thrall I would travel to Rokaro in Shadowprey Village and get the next part of the quest. 

### Source

https://wotlkdb.com/?quest=6566

### Steps to reproduce the problem

Speak with Thrall then Nothing happens. Should receive next quest to Rokaro however, goes nowhere and Rokaro is blank. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Jpizzle31** [comment]
Figurte it out

**Comment by Stump876** [comment]
@Jpizzle31 Just curious, what was the solution?
