### ISSUE TITLE
[Quest]: Libram of Focus

### ISSUE THREAD

**Issue by Drugadu** [chromiecraft/chromiecraft#2809]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

In Dire Maul North in The Athenaeum the NPC Lorekeeper Lydros dont give me the option to do the quest even i have all the items that the quest need it to be complete.
 
 I try bringing other book for the Arcanum of velocity and still happens the same.
![bug2](https://user-images.githubusercontent.com/95693449/149674608-14c40c54-bd8d-47e7-9b13-42cf5829ad61.jpg)
 

### Expected Blizzlike Behaviour

You have to bring to Lorekeeper Lydros in The Athenaeum any libram of Dire Maul to get some echants depending on your class. If you bring the libram of focus or libram of velocity you will able to do the quest to quet the arcanum echants for head and legs.

### Source

https://classic.wowhead.com/quest=7484/libram-of-focus

https://www.youtube.com/watch?v=mwUkjUmTZGs&ab_channel=BullCorn

### Steps to reproduce the problem

1. Got any libram for Dire Maul enchants.
2. Get Crescent key
3. Bring the items that the quest requieres
4. Get the Arcanum of Focus or Velocity (on my case)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Windows 10 Home

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Hihilist** [comment]
Have you completed https://wowgaming.altervista.org/aowow/?quest=7481 / https://wowgaming.altervista.org/aowow/?quest=7482 before trying to exchange materials for the enchant?
It serves as a prequest.

**Comment by Drugadu** [comment]
Im rlly sure that i did these pre-quest because as u see on this picture that i attached, i could did one time for my legs, was the second time that i went didn't let me do it...
![image](https://user-images.githubusercontent.com/95693449/149795558-3a6730c7-6433-41e8-abc3-04f9dcd830be.png)

**Comment by Drugadu** [comment]
Finally i'll check on feralas and the pre-quest that you said and i saw that i didn't did, so this was the problem... I'll never undertood how i could do the first time with out pre-quest. Thanks for help and coments, i close this issue
