### ISSUE TITLE
Wailing Caverns Disciple of Naralex doesn't stop in fights

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#281]
##### FACTION
Horde

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:
1-19

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Disciple of Naralex doesn't stop in fights to help and keeps going,giving you not enough time to kill all the mobs and get overwhelmed at the end.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Disciple of Naralex should stop in fights and help you kill the mobs but all the times.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Wailing Caverns
2. Kill all bosses
3. Go to disciple of Naralex
4.Tell him you're ready

##### EXTRA NOTES:

Please fix.
After last boss,the adds spawn almost all at once making it impossible to clear them all in time.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
Can you provide any footage for this?
"It feels wrong" and "I am sure it's wrong" isn't something the devs will accept as a reason.

**Comment by Narixel** [comment]
I didn't record but this is the behaviour I got,party wiped 3 times because of times.

**Comment by 55Honey** [comment]
By footage i mean something from live servers. Youtube videos from 2010. A guide on a respectable site which hints that the NPC behaves this way. Anything which can be considered proof, that the current behaviour is wrong, the expected behaviour is right.

You can just re-open / comment on this issue, if you have anything that helps. Thank you!

**Comment by tabakisp** [comment]
Additional info: Didn't find proof that the Disciple helps or stops in fights between his 1st stop and outside the boss chamber, but I found [this](https://www.youtube.com/watch?v=1yAUsI88lWc) video from 2011 that clearly shows that he helps in the 1st spawns and that the adds in boss chamber don't spawn all together but one by one, looks like a timer between each spawn.

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Disciple of Naralax](https://youtu.be/3wcq2qeFucE)
