### ISSUE TITLE
Witch Doctor Zum'rah not dropping loot at all

### ISSUE THREAD

**Issue by DJFoxtrot** [chromiecraft/chromiecraft#2811]
Linked Azerothcore issue: https://github.com/azerothcore/azerothcore-wotlk/issues/10262

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

after 6 runs in a row nothing has dropped from him what so ever only thing that is dropped is the chest but it doesnt contain any gear just cloth

### Expected Blizzlike Behaviour

should act like every other dungeon boss and at least drop something every kill 

### Steps to reproduce the problem

Fix his loot table

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
NPC info: https://tbc.wowhead.com/npc=7271/witch-doctor-zumrah
As of current All i can say is our loot for this npc is matching with the Universal Database for Loot (UDB) which is based on consolidated sniffs. However wowhead's loot and loot drop is collected thru datamining thru a addon that does get diluted pretty bad from repack and pserver players.
However that is all I can confirm. Now if there are more loot that drops at a different chance that may not of been sniffed I will welcome a second opinion and research of the matter.
![image](https://user-images.githubusercontent.com/16887899/150349617-5d8a906d-6047-4ec8-be25-5c6d460b1922.png)

**Comment by UltraNix** [comment]
https://classic.wowhead.com/npc=7271/witch-doctor-zumrah#comments:id=3126114
