### ISSUE TITLE
Buff of "Glyph of Totem of Wrath" not removed if clear/replace Glyph

### ISSUE THREAD

**Issue by Santaria94** [chromiecraft/chromiecraft#2815]
### What client do you play on?

ruRU

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Buff of "Glyph of Totem of Wrath" not removed if clear/replace Glyph.
Before the start of the battle, you can use "Glyph of Totem of Wrath" to get a buff for 5 minutes from it. Then replace with another glyph, so de facto there will be 1 more of them

### Expected Blizzlike Behaviour

The buff should automatically be removed if the Glyph is removed.

### Source

Obvious bug. I don't think any proof is needed here

### Steps to reproduce the problem

1. Use "Glyph of Totem of Wrath"
2. Use "Totem of Wrath"
3. Remove/Replace "Glyph of Totem of Wrath"
4. Look at the list of buffs and the saved spell power from it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Santaria94. Thank you for the report. Actually, proof is always needed. Bugs can be blizzlike.

I was not able to find any information about to blizzlike behavior. More opinions are needed here.

**Comment by Santaria94** [comment]
1) Azerothcore's policy is to fix obvious bugs, even if they blizzlike
2) Even hard blizzlike projects first fix such errors, and only then roll back if someone managed to prove that this was the case on official servers. I doubt that anyone will be able to find at least one comment from 2009-2010 about a similar fraud described in the report
