### ISSUE TITLE
Jarien and Sothos aggroing pet before their conversation ends.

### ISSUE THREAD

**Issue by Scapulla** [chromiecraft/chromiecraft#2829]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Jarien and Sothos, when summoned, aggroed Warlock's Pet, a Felhunter, before they finished their conversation and aggroed the players.

### Expected Blizzlike Behaviour

Jarien and Sothos should only start the fight after they finished their conversation, as stated in this comment from 2006
<html>
<body>
<div class="comment-header" style="outline: none; max-height: 1e+06px; color: rgb(187, 187, 187); font-size: 13px; margin: 0px; padding: 0px 0px 0px 10px; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 36, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

From AllakhazamBy Raiye on 2006/04/15 (Patch 1.9.4) |   |  
-- | -- | --

</div><div class="text comment-body comment-high-rating" lang="en" style="outline: none; max-height: 1e+06px; overflow: auto; padding: 10px; color: rgb(204, 204, 204); line-height: 1.4; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 36, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="comment-imported-subject" style="outline: none; max-height: 1e+06px; margin: 0px 0px 10px; color: rgb(187, 187, 187); display: block; opacity: 0.65;">Subject:<span> </span><span style="outline: none; max-height: 1e+06px; font-style: italic;">"Beating Jarien and Sothos"</span></span>This special Dungeon 2 boss fight is summoned in Lord Dorothan (Balnazzar)'s chamber in SC Stratholme.<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">Jarien and Sothos is an interesting fight. After you summon them, they will come out and chat with each other for a few seconds, and then they will attack you together. When you kill one of them, their spirit will appear and will help you fight the other one (but the spirit is weak and will die quickly).<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">Jarien and Sothos are Undead. I recommend killing Sothos first.<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">-Abilities-<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">Jarien: The only two abilities I caught Jarien using were Sinister Strike and Cleave. Jarien hits very, very hard, and his cleave HURTS. He isn't as bad as Sothos though.<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">Sothos: She is a caster (with a shield), and has three abilities to watch out for. She has an instant-cast Shadowbolt Volley spell, which does 700-800 Shadow damage. She can cast a mass fear effect. She also has a Shield Charge move, and will randomly charge ranged people and send them flying.<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">It's good to have two tanks for this fight. A priest or paladin will be a huge boon for shadow resistance buffs; a dwarf priest would be optimal (Fear Ward). They are undead so a paladin can tank them fairly well. Have the tougher tank keep Jarien away from the party while the DPS takes down Sothos. Then consentrate on Jarien (being careful of the Cleave).<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">After both have fallen, you can loot your amulet piece from one of their bodies, and your BOP loot will appear in a chest in the center of the room.<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">Good luck in defeating Jarien and Sothos!</div>
</body>
</html>

There are no comments from 3.3.5, that's the most data i could find, but i doubt their RP interaction would change for any reason.

### Source

First Comment, most voted.
https://classic.wowhead.com/npc=16101/jarien#comments

### Steps to reproduce the problem

Go into Lord Dorothan's chamber in Stratholm Living side, and summon the bosses while a warlock has a pet summoned. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Scapulla. Thank you for the report.

I can confirm the issue.
