### ISSUE TITLE
[Minor] Portal trainers in Exodar and Darnassus have wrong dialogue for Mages

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#2834]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Portal Trainers [Elissa Dumas](https://wowgaming.altervista.org/aowow/?npc=4165) and [Lunaraa](https://wowgaming.altervista.org/aowow/?npc=16755) have incorrect dialogue when speaking with a Mage class player.

Current message is the one present for non-mage classes:
_"I do not believe you posses the mental acuity to grasp the nature of portal magic"_
![WoWScrnShot_012022_043832](https://user-images.githubusercontent.com/79346412/150270460-43f9063a-f283-4116-8fcc-1f77d937c2a3.jpg)
![WoWScrnShot_012022_044046](https://user-images.githubusercontent.com/79346412/150270466-f8eb93ff-9511-49ed-b34f-be6a4490dbbd.jpg)

### Expected Blizzlike Behaviour

The dialogue should be:
_"As a mage, you are one of a select group that can conjure a portal to transport you back to this very place. I can teach you if you are ready"_

### Source

The correct dialogue other portal trainers have:

![WoWScrnShot_012022_045053](https://user-images.githubusercontent.com/79346412/150270515-cb08d578-96bb-4588-a269-36bfceb6a863.jpg)
![WoWScrnShot_012022_044108](https://user-images.githubusercontent.com/79346412/150270526-34138269-bf81-47b4-9403-252a184707d5.jpg)

### Steps to reproduce the problem

_1. Get a mage.
2. Toss a mage into Darnassus or Exodar's Portal Trainer.
3. Tell the mage to check what dialogue Trainer has._

### Extra Notes

_(Darnassus) Elissa Dumas_ 
DB GUID: **46320** Entry: **4165**

_(Exodar) Lunaraa_ 
DB GUID: **57746** Entry: **16755**

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Sathrenor. Thank you for the report.

I can the confirm the issue for some Horde portal trainers as well.

**Comment by Sathrenor** [comment]
### Update:
Only [Milstaff Stormeye](https://wowgaming.altervista.org/aowow/?npc=2489) _(DB GUID: **1771** Entry: **2489**)_  seems to have a correct tooltip. 
[Larimaine Purdue](https://wowgaming.altervista.org/aowow/?npc=2485) _(DB GUID: **90441** Entry **2485**)_ has a dialogue for mages even when playing other class:

![WoWScrnShot_012022_183205](https://user-images.githubusercontent.com/79346412/150392564-4b39630d-b556-48ad-97ff-f0d936f11ebc.jpg)
