### ISSUE TITLE
The Great Moongraze Hunt

### ISSUE THREAD

**Issue by mandris36** [chromiecraft/chromiecraft#2838]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The [Moongraze Stags](https://wowgaming.altervista.org/aowow/?npc=17200) are'nt shown as target of the [quest](https://wowgaming.altervista.org/aowow/?quest=9454).

### Expected Blizzlike Behaviour

They should be shown as targets.

### Steps to reproduce the problem

Teleport to NPC [Acteon](https://wowgaming.altervista.org/aowow/?npc=17110)
Get the [quest](https://wowgaming.altervista.org/aowow/?quest=9454).
Go to a [Moongraze Stag](https://wowgaming.altervista.org/aowow/?npc=17200).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Win10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @mandris36. Thank you for the report.

I am not 100% sure, what you mean. They show up as quest objectives.

![image](https://user-images.githubusercontent.com/62797536/150427893-e004cddf-0bc4-4079-a8a1-2aef45ecc5af.png)

Or do you mean the quest NPCs tooltip on mouseover?

![image](https://user-images.githubusercontent.com/62797536/150428091-c173a826-f75f-47da-810b-b01cd92d6b8e.png)

If you mean that, i think that this behavior is blizzlike, since if I remember correctly crafting reagents that are required for quest are usually not shown in the tooltip.

Do you maybe have evidence for the expected behavior you described?

**Comment by acidmanifesto** [comment]
@mandris36 Second opinon.
Do we need it to show up like this? Is that what you mean?
![image](https://user-images.githubusercontent.com/16887899/150430693-1287fe5a-9143-4603-bb06-a46482c43ec1.png)
