### ISSUE TITLE
Battered Junkboxes no loot

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#284]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Battered Junkboxes are empty,opened about 10 and none had any loot.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Battered Junkboxes should have loot.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a Battered Junkbox
2. Open it
3. See there is no loot
4.Do it again

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Confirmed!
-
Looting should be this: [Battered Junkbox - Contains](https://wotlkdb.com/?item=16882#contains)

**Video Test:** [Battered Junkboxes](https://youtu.be/KAfwXM6RUrI)
I havent checked yet the loot of this item, but probably either some items are missing, or they have a very low drop rate..

**Comment by Narixel** [comment]
Thanks for confirming this,it seems much lower than intented.

**Comment by Stifler82** [comment]
> Thanks for confirming this,it seems much lower than intented.

You don't have to say thank you, if a report is valid, it is valid.
If it is not valid, it is not valid, I do not do "Favors" I always try to be objective.

btw, you're welcome!

**Comment by Stifler82** [comment]
@Narixel 

So.. these are the exact same "Drop Chance" we have (Currently) on the server, so I would say there is nothing to fix..
[Battered Junkbox - Contains](https://wotlkdb.com/?item=16882#contains:0+14-2)

BUT!
As a matter of **"Common sense"**, I made a little custom Correction, doing a **"Flat-Rate" drop**, now the items dropped from this chest have a Drop Rate, more **"Honest"**.
I attach a demonstration video..

**Video Test Fixed Rates:** [Battered Junkboxes Fixed](https://youtu.be/mZkSN4ChL5E)
