### ISSUE TITLE
Rabid Thistle Bears

### ISSUE THREAD

**Issue by imp2001** [chromiecraft/chromiecraft#2840]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

In Darkshore, several bears west of Ameth'aran are alive with the dead animation.  When they move the dead animation appears to slides across the ground.

### Expected Blizzlike Behaviour

The mobs should be using the correct animation.

### Steps to reproduce the problem

I just noticed them when exploring.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
I am just testing on my local and not seeing the issue, however i seen this issue mentioned to other players who have mention a relog fixes it or cache clearing fixes the issue as well. but at this moment i just can not confirm this issue at the moment and will have to opt for a second opinion.  So far .go creature 37284 sends me to the area, i see nothing dead, i kill them all and waited for them to respawn and saw no issues. i kill them all and then tele else where and waited for about 10 minutes then tele backed and see there is no issue.

@Nyeriah any input will be helpful

**Comment by xChaosityx** [comment]
I was leveling a 15 druid there the other day and saw a few bears like that as well, They were sorta randomly all over the map stuck in dead animations until killed.

**Comment by ShadowWhoWalks** [comment]
Met a couple of them (for a moment I thought it was a bizarre symptom of the infection). Found it again and captured footage:
https://streamable.com/4z2v5e

For testing, a rapid bear with broken animation consistently spawns in the spot with the red circle on the map:
https://imgur.com/a/UTvhBaD

Though I can't confirm if it is just this bear or more of the rapid bear mobs are bugged.

**Comment by xChaosityx** [comment]
I found some myself again haha 
![image](https://user-images.githubusercontent.com/62197109/151272241-4d333bb5-e1e7-49ee-84b7-f385cf77d214.png)

**Comment by ohkasdasf** [comment]
Can confirm that at least seven Rabid Thistle Bears are having this behavior, checked this with two accounts. The sleeping animation persisted through combat. After killing one it respawned in the same location with the same bug. So it might be connected to the specific spawn point. It wasn't fixed after deleting cache/WDB and relogging. Locations where I found this behavior: ~ 38, 53 / 38, 54 / 39, 58 / 40, 59 / 39, 60 / 47, 34 / 51, 31. All other Rabid Thistle Bears that I found are walking normal though so it might not always be triggered. I checked the spawn locations from here: https://wotlkdb.com/?npc=2164

**Comment by Vladimirjov** [comment]
any news on this bug? i found another Rabid Thistle Bear with the same isue west of Ameth'aran. They seem to have the same issue as the mob in hinterlands (which got fixed) at the altar where you get the [Mallet of Zul'Farrak] onehand mace weapon.


![WoWScrnShot_040323_171802](https://user-images.githubusercontent.com/81888445/229575173-20a23ca9-29a6-4a07-90ac-d268f61d3345.jpg)
![WoWScrnShot_040323_171758](https://user-images.githubusercontent.com/81888445/229575182-010859d9-d18b-4072-8a68-4b3c96c9e6d6.jpg)

**Comment by The-GhostRider** [comment]
I believe the issue is no longer an issue, probably something was fixed that automatically fixed this problem, I checked all the spawns of this NPC and didn't find this problem, so I don't think this report is reliable anymore currently.

**Comment by heyitsbench** [comment]
This still seems to be an issue, as reported by boniface_8436 in the CC Discord.

**Comment by Salehyn** [comment]
Seems to be some client issue, i cannot reproduce it.

**Comment by SilviusT** [comment]
I've encountered this bug aswell today. I saw two of them while passing thru Darkshore. My client is taken from CC downloads and is pretty new (2 days old), no visual patches/changes. I've also tested it by logging with a fresh client with no addons (from CC downloads aswell) and another older 3.3.5a client I have from an older server. The bears were bugged on all 3 clients. I also checked to see if the client (older one) gets this bug on a different server and everything was fine there. I don't think this is a client issue. One thing I did not test is whether it might be related to the "Plagued Lands" quest which requires players to capture the rabid bears (https://www.wowhead.com/wotlk/quest=2118/plagued-lands).

**Comment by Gultask** [comment]
Found it!
The bug happens due to the quest Plagued Lands given by NPC entry 3701. After completion a spell will be cast on the bear, which sets StandState to DEAD (7), since the State is never changed back, the bear persists in a dead state.
