### ISSUE TITLE
[Molten Core] Shaman T1 trash droprate mismatch

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#2843]
AC issue linked: https://github.com/azerothcore/azerothcore-wotlk/issues/10309

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Shaman T1 belt (16838) and bracer (16840) droprates are a lot lower compared to droprates of the other classes.

### Expected Blizzlike Behaviour

Droprates should be about equal per class.

### Steps to reproduce the problem

Reference creature_loot_template.sql

<html>
<body>

Item | Comment_Arr[1] | Ancient Core Hound+Min*(Chance) | Firelord+Min*(Chance) | Firewalker+Min*(Chance) | Flameguard+Min*(Chance) | Flamewaker+Min*(Chance) | Flamewaker Elite+Min*(Chance) | Flamewaker Healer+Min*(Chance) | Flamewaker Priest+Min*(Chance) | Flamewaker Protector+Min*(Chance) | Lava Annihilator+Min*(Chance) | Lava Elemental+Min*(Chance) | Lava Reaver+Min*(Chance) | Lava Surger+Min*(Chance) | Molten Destroyer+Min*(Chance) | Molten Giant+Min*(Chance)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
16838 | Earthfury Belt | 0.18 | 0.14 | 0.16 | 0.08 | 0.08 | 0.08 | 0.02 | 0.22 | 0.26 | 0.06 | 0.08 | 0.14 | 0.1 | 0.28 | 0.14
16840 | Earthfury Bracers | 0.12 | 0.12 | 0.2 | 0.08 | 0.24 | 0.2 | 0.03 | 0.12 | 0.07 | 0.05 | 0.08 | 0.12 | 0.08 | 0.16 | 0.14
16799 | Arcanist Bindings | 0.42 | 0.34 | 0.32 | 0.38 | 0.24 | 0.38 | 0.16 | 0.3 | 0.26 | 0.11 | 0.18 | 0.34 | 0.22 | 0.36 | 0.44
16802 | Arcanist Belt | 0.3 | 0.3 | 0.32 | 0.34 | 0.28 | 0.2 | 0.24 | 0.56 | 0.42 | 0.11 | 0.26 | 0.32 | 0.24 | 0.58 | 0.38
16804 | Felheart Bracers | 0.46 | 0.32 | 0.3 | 0.42 | 0.56 | 0.38 | 0.24 | 0.26 | 0.46 | 0.13 | 0.24 | 0.24 | 0.28 | 0.46 | 0.4
16806 | Felheart Belt | 0.34 | 0.32 | 0.5 | 0.46 | 0.42 | 0.24 | 0.24 | 0.56 | 0.42 | 0.12 | 0.2 | 0.48 | 0.36 | 0.58 | 0.46
16817 | Girdle of Prophecy | 0.34 | 0.4 | 0.38 | 0.3 | 0.38 | 0.54 | 0.36 | 0.32 | 0.18 | 0.13 | 0.2 | 0.3 | 0.24 | 0.44 | 0.44
16819 | Vambraces of Prophecy | 0.34 | 0.28 | 0.26 | 1.2 | 0.42 | 0.44 | 0.38 | 0.4 | 0.34 | 0.1 | 0.24 | 0.28 | 0.24 | 0.28 | 0.38
16825 | Nightslayer Bracelets | 0.38 | 0.34 | 0.46 | 0.26 | 0.32 | 0.3 | 0.3 | 0.26 | 0.34 | 0.13 | 0.28 | 0.34 | 0.2 | 0.46 | 0.4
16827 | Nightslayer Belt | 0.36 | 0.3 | 0.3 | 0.38 | 0.32 | 0.42 | 0.22 | 0.48 | 0.64 | 0.11 | 0.2 | 0.3 | 0.28 | 0.32 | 0.3
16828 | Cenarion Belt | 0.3 | 0.38 | 0.34 | 0.26 | 0.24 | 0.34 | 0.14 | 0.22 | 0.3 | 0.12 | 0.28 | 0.32 | 0.3 | 0.38 | 0.38
16830 | Cenarion Bracers | 0.26 | 0.32 | 0.44 | 0.24 | 0.38 | 0.42 | 0.3 | 0.22 | 0.38 | 0.15 | 0.2 | 0.4 | 0.32 | 0.44 | 0.44
16850 | Giantstalker's Bracers | 0.4 | 0.42 | 0.38 | 0.36 | 0.38 | 0.32 | 0.24 | 0.4 | 0.3 | 0.14 | 0.26 | 0.32 | 0.28 | 0.38 | 0.46
16851 | Giantstalker's Belt | 0.32 | 0.32 | 0.3 | 0.58 | 0.38 | 0.5 | 0.18 | 0.3 | 0.26 | 0.14 | 0.26 | 0.28 | 0.22 | 0.46 | 0.34
16857 | Lawbringer Bracers | 0.24 | 0.3 | 0.18 | 0.2 | 0.18 | 0.22 | 0.3 | 0.18 | 0.38 | 0.1 | 0.16 | 0.18 | 0.14 | 0.32 | 0.3
16858 | Lawbringer Belt | 0.24 | 0.18 | 0.14 | 0.3 | 0.18 | 0.2 | 0.1 | 0.14 | 0.34 | 0.08 | 0.1 | 0.18 | 0.2 | 0.26 | 0.32
16861 | Bracers of Might | 0.36 | 0.34 | 0.22 | 0.32 | 0.25 | 0.6 | 0.36 | 0.18 | 0.34 | 0.13 | 0.2 | 0.28 | 0.24 | 0.3 | 0.38
16864 | Belt of Might | 0.32 | 0.32 | 0.56 | 0.32 | 0.15 | 0.38 | 0.3 | 0.23 | 0.26 | 0.15 | 0.2 | 0.36 | 0.2 | 0.3 | 0.32

</body>
</html>

### Extra Notes

The misalignment can likely be attributed to web-scraping of drop rates from old sources, maybe even back to pre-tbc when shamans and also paladins weren't present on both factions.

Current drop rates are partially lower by a factor of 4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
My research on the matter per UDB (Universale Database for loot) matching is that Azerothcore DB Loot matches exactly with the UDB with zero deviation. At this point i will have to call on a second opinion for further discussion and research.
@Nyeriah @temperrr @55Honey can you provide second opinions when available?

Azerothcore
![image](https://user-images.githubusercontent.com/16887899/150648712-e3cfb47d-ad2b-48cc-a290-ec062f65f5f2.png)
![image](https://user-images.githubusercontent.com/16887899/150648728-ca336ad9-14be-4b57-a345-683bd02ff66e.png)

UDB 
![image](https://user-images.githubusercontent.com/16887899/150648736-165a93f5-4fb0-491b-82f5-b606941c535c.png)
![image](https://user-images.githubusercontent.com/16887899/150648751-6e89b5ce-065b-4ea4-8ead-cfd240fcbaf9.png)

**Comment by 55Honey** [comment]
> The misalignment can likely be attributed to web-scraping of drop rates from old sources, maybe even back to pre-tbc when shamans and also paladins weren't present on both factions.

I think that concern is viable. I'm not sure how to gain better numbers tho. Back in the days of vanilla, your faction decided, if there was pally to shaman loot. That might have borked the UDB drop rates. I'd check e.g. TBC wowhead for more references.

**Comment by temperrr** [comment]
That's a fair assessment honey makes

**Comment by j-hdt** [comment]
needing a second opinion etc. nice and well - but can we apply reasonable goodwill and equalize the dropchances in the meantime? its getting kinda silly having all setpieces but not even seeing the trash items drop

**Comment by 55Honey** [comment]
Are the drop chances for the other classes identic already?

If so, i think we should do the same for shamans and paladins. If we can't fix it on AC, it should Go to the progression module.

**Comment by j-hdt** [comment]
the other classes droprates seem just fine. some are droppin more often (rogue, hunter, priest) but nothing irregular there. its only shaman items that partially have a drop chance thats only 25% of the other items, making it e.g. not 1 in 200 mobs, but 1 in 800 or 1 in 1000 mob kills

**Comment by 55Honey** [comment]
"Should be" is not how droprates are determined. We need cold, hard proof to change a rate.

That shaman rates however seem scuffed from the UDB data, too. But that's just my opinion.

**Comment by j-hdt** [comment]
https://classic.wowhead.com/item=16840/earthfury-bracers
https://classic.wowhead.com/item=16838/earthfury-belt

those are the vanilla drop rates, up to 10 times higher - feel free to use those for adjustment (although i expect that we will swim in those pieces then, instead of rogue pieces)

**Comment by j-hdt** [comment]
SQL Statement to update both shaman boe items based on classic.wowhead.com

```SQL
UPDATE creature_loot_template 
SET Chance 
= CASE Entry 
WHEN 11673 THEN Round(100 * Cast(600 as float) / Cast(69095 as float), 2)
WHEN 11668 THEN Round(100 * Cast(438 as float) / Cast(115317 as float), 2)
WHEN 11666 THEN Round(100 * Cast(164 as float) / Cast(75412 as float), 2)
WHEN 11667 THEN Round(100 * Cast(195 as float) / Cast(79929 as float), 2)
WHEN 11661 THEN Round(100 * Cast(25 as float) / Cast( 4962 as float), 2)
WHEN 11664 THEN Round(100 * Cast(120 as float) / Cast(14824 as float), 2) 
WHEN 11663 THEN Round(100 * Cast(54 as float) / Cast(10949 as float), 2)
WHEN 11662 THEN Round(100 * Cast(73 as float) / Cast( 9802 as float), 2)
WHEN 12119 THEN Round(100 * Cast(43 as float) / Cast( 6364 as float), 2) 
WHEN 11665 THEN Round(100 * Cast(470 as float) / Cast(160080 as float), 2)
WHEN 12076 THEN Round(100 * Cast(332 as float) / Cast(121977 as float), 2)
WHEN 12100 THEN Round(100 * Cast(176 as float) / Cast(62084 as float), 2)
WHEN 12101 THEN Round(100 * Cast(341 as float) / Cast(94330 as float), 2)
WHEN 11659 THEN Round(100 * Cast(293 as float) / Cast(83855 as float), 2)
WHEN 11658 THEN Round(100 * Cast(409 as float) / Cast(62760 as float), 2)
ELSE Chance 
END 
WHERE Item = 16838;


UPDATE creature_loot_template 
SET Chance 
= CASE Entry 
WHEN 11673 THEN Round(100 * Cast(608 as float) / Cast(69095 as float), 2)
WHEN 11668 THEN Round(100 * Cast(399 as float) / Cast(115317 as float), 2)
WHEN 11666 THEN Round(100 * Cast(205 as float) / Cast(75412 as float), 2)
WHEN 11667 THEN Round(100 * Cast(236 as float) / Cast(79929 as float), 2)
WHEN 11661 THEN Round(100 * Cast(39 as float) / Cast( 4962 as float), 2)
WHEN 11664 THEN Round(100 * Cast(113 as float) / Cast(14824 as float), 2) 
WHEN 11663 THEN Round(100 * Cast(54 as float) / Cast(10949 as float), 2)
WHEN 11662 THEN Round(100 * Cast(77 as float) / Cast( 9802 as float), 2)
WHEN 12119 THEN Round(100 * Cast(46 as float) / Cast( 6364 as float), 2) 
WHEN 11665 THEN Round(100 * Cast(496 as float) / Cast(160080 as float), 2)
WHEN 12076 THEN Round(100 * Cast(292 as float) / Cast(121977 as float), 2)
WHEN 12100 THEN Round(100 * Cast(224 as float) / Cast(62084 as float), 2)
WHEN 12101 THEN Round(100 * Cast(392 as float) / Cast(94330 as float), 2)
WHEN 11659 THEN Round(100 * Cast(334 as float) / Cast(83855 as float), 2)
WHEN 11658 THEN Round(100 * Cast(393 as float) / Cast(62760 as float), 2)
ELSE Chance 
END 
WHERE Item = 16840;
```

**Comment by vvelkovski** [comment]
While raiding with Alliance chars only, I've never seen an Earthfury BOE drop in all MC runs I've done with all of the 3 chars I have since the raid was opened. On the other side I've seen roughly equal distribution of other class BOEs.

If a Horde player can confirm the same behavior for paladin BOEs, maybe the bug ca be tracked with the classes not being there back in classic.

**Comment by j-hdt** [comment]
> While raiding with Alliance chars only, I've never seen an Earthfury BOE drop in all MC runs I've done with all of the 3 chars I have since the raid was opened. On the other hand I've seen roughly equal distribution of all other class BOEs.
> 
> If a Horde player can confirm the same behavior for paladin BOEs, maybe the bug ca be tracked with the classes not being there back in classic.

Its not faction related any more. But, the baseline dropchance for items is based on old logs, coming mostly from alliance side. Thus, the overall drop chance for shaman BOEs have been lower than they logically are supposed to be.

**Comment by KarazhanSucks** [comment]
Correct fix but not really provable:

http://forums.elitistjerks.com/topic/16858-thesis-how-the-loot-tables-work/ (dead link)

Create a loot pool for all belt and bracers.
Chance to hit loot pool on each trash mob is sum of loot chances of each individual item. (From classic Wowhead e.g.)
Alliance and horde unique items are not relevant anymore due to classes becoming available for both factions. (Could make it like Ony heads but that would screw over Horde pallies and Alliance shamans.)

Chances are absolute (0.30 = 30%)

Ancient Core Hound
.30 Chance to hit pool
Firelord
.12 Chance to hit pool
Firewalker
.08 Chance to hit pool
Flameguard
.08 Chance to hit pool
Flamewaker
.30 Chance to hit pool
Flamewaker Elite
.30 Chance to hit pool
Flamewaker Healer
.20 Chance to hit pool
Flamewaker Priest
.30 Chance to hit pool
Flamewaker Protector
.30 Chance to hit pool
Lava Annihilator
.12 Chance to hit pool
Lava Elemental
.08 Chance to hit pool
Lava Reaver
.08 Chance to hit pool
Lava Surger
.12 Chance to hit pool
Molten Destroyer
.12 Chance to hit pool
Molten Giant
.20 Chance to hit pool

Only way to disprove this theory is actual screenshots of retail with:
**bracer and belt drop from same mob** - Still possible that instead of one big pool, bracer and belt pool are different pools (with half the chance of hitting)
**double bracer or belt drop** - Loot pools do not exist
**double same bracer or same belt drop** - Will never happen

I'd rather put the burden of proof on disproving the loot pool theory. If the event of double trash loot drop occurred there will be a screenshot of it out there somewhere (thanks Reddit!). If there are no screenshots of the event it didn't happen.

**Comment by j-hdt** [comment]
Any plans for intermediate solutions @55Honey ?
e.g. making a trade-in, bringing all 8 other boe bracers, to trade them in for the shaman ones?
not blizzlike, but neither is the current drop rate and I dont see any progress happening here... and it wouldnt be the first "custom" trade-in solution, to make items available.

**Comment by 55Honey** [comment]
I'm certainly the wrong person to tag since I am not involved in both, blizz-like development as well as triaging.
About your suggestion:
The existing custom trade-ins are to make things available that were used in vanilla but aren't accessible anymore in 3.3.5 at all. The subject of this issue is different from things being removed/made unavailable, it's a potential drop rate mismatch.
