### ISSUE TITLE
NPC "Fenros" not dropping [Tribal Worg Helm] / Loot Table bug

### ISSUE THREAD

**Issue by Hanzemon** [chromiecraft/chromiecraft#285]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

The Rare NPC [Fenros](https://wowgaming.altervista.org/aowow/?npc=507#drops) is not dropping Item [[Tribal Worg Helm]](https://wowgaming.altervista.org/aowow/?item=6204). It is supposed to have around a 33% dropchance. I have personally killed it 5 times and everytime it just drops [[Ravenwood Bow]](https://wowgaming.altervista.org/aowow/?item=4474).

After getting frustrated, I went and checked the database file noticed that it has a whooping 0% chance to drop. This item is also not found in any reference loot table, so it's virtually impossible to obtain right now.

![0%](https://user-images.githubusercontent.com/32701428/112361086-67934b00-8ca9-11eb-8406-f6a4165fac15.PNG)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Item drops from Fenros 33% of the time.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill Fenros many times.
2. Notice it never drops Tribal Worg Helm.
3. Go check or download the creature_loot_template.sql at chromiecraft azerothcore database.
4. Notice it has a 0 on the entry for drop chance.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
32% not 33%
![image](https://user-images.githubusercontent.com/1884642/112375654-6c70f280-8cdb-11eb-82e3-71ddf4940fb2.png)

**Comment by Hanzemon** [comment]
> 32% not 33%
> ![image](https://user-images.githubusercontent.com/1884642/112375654-6c70f280-8cdb-11eb-82e3-71ddf4940fb2.png)

https://user-images.githubusercontent.com/32701428/112381190-ada7d900-8cc0-11eb-8327-ab30cac16c25.mp4

Glad it caught your attention.

**Comment by Stifler82** [comment]
> > 32% not 33%
> > ![image](https://user-images.githubusercontent.com/1884642/112375654-6c70f280-8cdb-11eb-82e3-71ddf4940fb2.png)
> 
>  You.re.goddamn.right.mp4 
> Glad it caught your attention.

i try..

**Comment by Stifler82** [comment]
@Hanzemon 

It seems to works to me..
So for me the report is Invalid..
As I believe you can also notice from my video:
**Video Test:** [Tribal Worg Helm](https://youtu.be/gpXNzH219EE)

Maybe you were just **"Very Unlucky"**

**Comment by Hanzemon** [comment]
> @Hanzemon
> 
> It seems to works to me..
> So for me the report is Invalid..
> As I believe you can also notice from my video:
> **Video Test:** [Tribal Worg Helm](https://youtu.be/gpXNzH219EE)
> 
> Maybe you were just **"Very Unlucky"**

Where can you reliably see the drop chance of items reflected in the server files?
