### ISSUE TITLE
[Lunar Festival] Elder Bladesing missing in Silithus (Cenarion Hold)

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2851]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Elder Bladesing missing in Silithus probably due to disable content in there.

### Expected Blizzlike Behaviour

Should allow us to have him, he has nothing to do with raid unlocking and tiers.

### Steps to reproduce the problem

1. Find him in Cenarion Hold
2. Get Coin and Achievement.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
Not a core problem, needs to be resolved in the progression module.

NPC id is 15599

https://github.com/azerothcore/mod-progression-system/blob/main/src/Bracket_50_59_A/sql/world/progression_50_59_a_delete_npc_location.sql
https://github.com/azerothcore/mod-progression-system/blob/869a11f013682a7153e1624930375de200d4d4c3/src/Bracket_70_4/sql/world/progression_70_4_restore_npc_location.sql#L10

**Comment by ishidinho** [comment]
Hey @Elexias. Thank you for the report.

I was able to find Elder Bladesing in Cenarion Hold.

![image](https://user-images.githubusercontent.com/62797536/150784727-1496f1ba-3931-4e6b-8d1b-ea9ffadfabaa.png)

I do not know what happened yesterday, but the issue seems to be not present anymore. Just check it again.

**Comment by Elexias** [comment]
@ishidinho GM's summoned NPC at his original location, but I report at the point when he wasn't present. Shouldn't It get confirmed label and get points for it? Not? Keep closing my issues dw :D

**Comment by ishidinho** [comment]
Hey @Elexias. That would have been a great information to have. How should I know? I was not there when the GM summoned the NPC. ;)

I ask the bosses how to handle this case.

**Comment by ishidinho** [comment]
@Elexias 

Good news: We clarified how to handle this issue.
Better news: You will get your well deserved Chromie Points! ;)

Thanks again.

I will create an AC ticket tomorrow.
