### ISSUE TITLE
Deep Freeze not consuming Fingers of Frost buff

### ISSUE THREAD

**Issue by Mikel0ke** [chromiecraft/chromiecraft#2853]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Deep Freeze doesn't consume the Fingers of Frost buff, allowing 4 spells benefit from a single proc.

### Expected Blizzlike Behaviour

Deep Freeze should consume Fingers of Frost when used.

### Steps to reproduce the problem

Get both Fingers of Frost and Deep Freeze talents on a frost mage, get a proc and cast frostbolt deep freeze cold snap frostbolt deep freeze.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Hihilist** [comment]
Can you look if this report https://github.com/chromiecraft/chromiecraft/issues/2537 covers your findings?

**Comment by Mikel0ke** [comment]
no, its not the same issue, deep freeze is not consuming the proc on cast
neither on hit.

**Comment by ishidinho** [comment]
Hey @Mikel0ke. Thank you for the report.

Sadly, I am not able to reproduce the issue on local AC.

https://user-images.githubusercontent.com/62797536/150789153-3b8d3e4e-cc02-46f7-9ada-bc47fe6dd2ad.mp4

Is this issue still present? Can you provide more detailed information?

**Comment by Mikel0ke** [comment]
i think the issue is with stun inmune mobs, because i have done it both in
dungeon and raid bosses, ill try to find a stun inmune mob to test it

**Comment by Mikel0ke** [comment]
https://www.youtube.com/watch?v=ot3CVTGLRRA

**Comment by ishidinho** [comment]
Hey @Mikel0ke. Many thanks for your further investigation.

I can confirmed now, that there are some issues with Deep Freeze and Fingers of Frost.

**Comment by Mikel0ke** [comment]
npnp
