### ISSUE TITLE
Majordomo walks through the wall when starting Ragnaros fight before he can arrive at the correct location

### ISSUE THREAD

**Issue by Luckdemon** [chromiecraft/chromiecraft#2859]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Immediately after defeating the Majordomo encounter, if you talk to him and initiate the Ragnaros summoning dialog, he will slowly proceed to air-walk in a straight line through walls, directly towards his normal spot in front of Ragnaros.

### Expected Blizzlike Behaviour

His dialog should not be available until he gets to the Ragnaros summoning spot.

### Steps to reproduce the problem

1. Defeat the Majordomo encounter
2. Proceed to start dialog with him before he can disappear to go to the Ragnaros location
3. Watch as he clip-fly-walks in a straight line to where he is supposed to be
4. Watch as he starts the Ragnaros fight immediately

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @luckdemon. Thank you for the report.

Sadly, I cannot reproduce the problem on local AC.

No dialog:

![WoWScrnShot_012422_161543](https://user-images.githubusercontent.com/62797536/150812049-fac05c3c-5dd8-4e41-b9a8-daa8b93aa2b9.jpg)

He teleports as I would expect him to do:

https://user-images.githubusercontent.com/62797536/150812218-635b90ea-ceb7-4a65-9218-7e874a73c815.mp4

Can you provide data (screenshots or clips) for the actual behavior on CC where we can see the problem appear?
I think, if there is a problem, it is not that crucial. So, we can wait until the next CC id reset. I will have a look in my raid as well.

**Comment by Greyminder** [comment]
Hi, with my guild (Booty Bay Beach Boy), we had the same issue this night. We don't know how, but the event have started before than we arrive to ragnaros.

![WoWScrnShot_020122_205713](https://user-images.githubusercontent.com/90478089/152061190-f0c25b63-5c70-483c-8f55-d10be53da37a.jpg)

![WoWScrnShot_020122_205802](https://user-images.githubusercontent.com/90478089/152061250-30d8412d-77e7-4553-a10e-4049e7f3f7eb.jpg)
.

**Comment by Luckdemon** [comment]
Forgot that I had reported this a while back, and it looks like it hasn't been dealt with yet. Just updating the tags and linking it because it just happened again today and also reproduced on PTR.

Key points in reproducing it are talking to domo immediately after his fight is over, before he has a chance to yell his dialog and teleport. Especially while he is walking back to his chest.
