### ISSUE TITLE
Specific Drops and Zone Drops behaving like World Drops.

### ISSUE THREAD

**Issue by Hanzemon** [chromiecraft/chromiecraft#286]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Items that should be very specific Zone Drops and Drops from specific NPCS are in World Drop Loot Tables, also know as: "reference_loot_template.sql" in the database.

Some examples that I've gathered are 
[[Humbert's Helm]](https://wowgaming.altervista.org/aowow/?item=4724) (Dropped off Undead mobs in Duskwood // Should be dropping from Dun'Garok Riflemen in Dun Garok)
[[Blackrock Champion's Axe]](https://wowgaming.altervista.org/aowow/?item=1455) (Dropped off undead mobs in Duskwood // Should be dropping from Blackrock Champion in Redridge)

Other Items that I haven't personally encountered myself but are behaving like World Drops right now and should not:
[[Robes of the Shadowcaster]](https://wowgaming.altervista.org/aowow/?item=1297)
[[Nightwalker Armor]](https://wowgaming.altervista.org/aowow/?item=2234)
[[Cloak of Rot]](https://wowgaming.altervista.org/aowow/?item=4462)

And so many many more... This have to be looked into in-depth.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Zone Drops and Specific Drops from a Specific mob should be dropping from said Zones/Drops respectively.

##### STEPS TO REPRODUCE THE PROBLEM:

1. play the game
2. get drops that don't belong to the area/mob

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
This report is Valid..
