### ISSUE TITLE
Can't speak to Lady Katrana Prestor to finish quest True Masters

### ISSUE THREAD

**Issue by Zosina** [chromiecraft/chromiecraft#2863]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

Unable to open a dialog box with [Lady Katrana Prestor](https://wowgaming.altervista.org/aowow?npc=1749) in the Stormwind Keep in order to advance the quest [The True Masters](https://wowgaming.altervista.org/aowow?quest=4185).

### Expected Blizzlike Behaviour

You should be able to speak to Lady Katrana Prestor and then turn in the quest to Bolvar.

### Source

https://wowgaming.altervista.org/aowow?quest=4185

### Steps to reproduce the problem

Accept quest from Bolvar.
Attempt to speak to Lady Prestor.
No profit.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Hey,
Do you know if there was an event running when you tried talking to her? If there was, the npcs become inaccessible during it

**Comment by Zosina** [comment]
There wasn't an event running the entire time i tried to talk to Lady Prestor. Saw someone start and finish The Great Masquerade which would mean the quest was working at some point. Talked to another player who claimed he'd waited for an hour without being able to talk to Lady Prestor.

**Comment by Nyeriah** [comment]
I've just checked this and all the times she wasn't offering the gossip someone was doing the escort quest. There are just too many players doing the escort quest right now. I'll see what can be done about it, so players are not locked out of the gossip quest.

**Comment by Zosina** [comment]
Yes confirmed working as intended.
