### ISSUE TITLE
[Class quest][Druid] 10 - Body and Heart (Alliance) - Error on quest markers

### ISSUE THREAD

**Issue by OA350** [chromiecraft/chromiecraft#2871]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Body and Heart quest (https://wowgaming.altervista.org/aowow/?quest=6001) markers are bugged and also break other markers. 
When you get the quest, it points you to the initial location where you got it, with a 0/1 and text.
In addition, it breaks other quest markers, making them dissappear or rarely appear in the wrong location -> log out & log in fixes that for a short while, but after opening the map & closing it & opening again the markers are broken.

After killing the lunaclaw, the other quest markers on map are shown correctly, however NPCs had no ?! hovering over their heads anymore. The decsription of the quest disappears (top right corner):
![image](https://user-images.githubusercontent.com/76611816/151015041-e6d6801b-2558-42b6-8eb7-78d2d7df8999.png)

### Expected Blizzlike Behaviour

The other quest markers shouldn't break on map, and the quest itself should also be displayer correctly

### Steps to reproduce the problem

 1. Create Nightelf Druid
 2. Level up and get the Body and heart quest
 3. Get some other quests, open & close map by pressing M

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)
- Atlas Loot 5.11
- GatherMate
- GearScoreLite3x04
- MonkeySpeed 3.0.5
- RangeDisplay 3.8.2

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @OA350. Thank you for the report.

Some days ago I had the same problem with the horde version of the quest: [Body and Heart (6002)](https://wowgaming.altervista.org/aowow/?quest=6002). There I observed the same quest log glitches.

Unfortunately, I was not able to reproduce the problem on my local AC. Your named steps to reproduce the problem did not result in our problem.

Do you maybe can give a more detailed description to force the issue to happen?

**Comment by OA350** [comment]
Hi, unfortunately not, i tried describing everything as best as I can. But since I already finished the quest, there's not much I can do :(
