### ISSUE TITLE
Lost in battle [4921]

### ISSUE THREAD

**Issue by Noodlesxx** [chromiecraft/chromiecraft#2872]
A window should appear to complete the quest to recognize the corpse of Mankrik's wife, and in this case you cannot interact with the corpse
![WoWScrnShot_012522_211135](https://user-images.githubusercontent.com/98425481/151052439-87ee2789-d10f-448e-b2a8-a3717f3e4c8a.jpg)

**Comment by IntelligentQuantum** [comment]
Please fill in all fields.

https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&template=bug_report.yml
