### ISSUE TITLE
Night Elf Warrior Quest - Smith Mathiel - ? does not go when quest is handed in. 

### ISSUE THREAD

**Issue by KaelangWoW** [chromiecraft/chromiecraft#288]
Alliance Night Elf 
1-19 Bracket

After completing the quest 'Smith Mathiel' you recieve a Warrior specific weapon. However the NPC does not lose the '?' above his head. After talking to him again he has no chat box so you can't receive multiple rewards - but this trigger should go upon completion. 

NPC Entry: 6142

![image](https://user-images.githubusercontent.com/81334674/112395151-c7174800-8cf5-11eb-8e58-e980456446f2.png)

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
This Bug happened to you for 2 possible reasons or a combination of both:
- **You are using a WoW enGB Client instead of the enUS Client (Recommended by us).**
- **You do not delete the Cache folder which is inside the WoW directory before opening the game.**

**Video Test:** [Quest - Smith Mathiel](https://youtu.be/nAjOAyOtjoE)

**Comment by KaelangWoW** [comment]
What's interesting here is the video you highlighted does not actually show the quest I handed in. As you can see from my screenshot, the quest reward was a weapon. The quest rewarded a selection of 4x Items, I chose the Sword.

In the video you provided, you was given a cache, and not offered the choice of the 4 weapons. Suggesting this was either an earlier line in the quest - or there's definitely something wrong here. 

As a side note, I am using the ChromieCraft client downloaded directly from the website - but yes I did not delete my cache, however I have only played on CC for the duration I've had the client. 

I still can't work out how the Cache would show me a different end quest reward option than yours. I still think there's something wrong here?
