### ISSUE TITLE
Grimclaw incorrect pathing

### ISSUE THREAD

**Issue by nueschts** [chromiecraft/chromiecraft#2882]
AC Issue Link: https://github.com/azerothcore/azerothcore-wotlk/issues/10925
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

NPC [Grimclaw](https://wowgaming.altervista.org/aowow/?npc=3695) in Darkshore is "flying" instead of walking on the ground.

NPC was also accompanied/chased? by 2 other mobs, one of wich can be seen in the screenshot.

### Expected Blizzlike Behaviour

Should be walking on the ground.

### Source

![WoWScrnShot_012622_171956](https://user-images.githubusercontent.com/61170874/151297119-45382030-8cf6-43cf-8dfd-31a5faa47d33.jpg)

### Steps to reproduce the problem

Just ride along the main north-south path in Darkshore, saw it on 2 seperate occasions.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @nueschts. Thank you for the report.

I cannot reproduce the problem on my local AC. Grimclaw is just standing where I would expect him.

![WoWScrnShot_012822_135304](https://user-images.githubusercontent.com/62797536/151550453-4dc536ff-78b7-4b1a-924f-98811d110565.jpg)

For later evaluation:
* `.go creature 37101`

**Comment by ShadowWhoWalks** [comment]
Encountered this multiple times. Maybe there is a trigger that makes Grimclaw start pathing, such as a player travelling south from  Auberdine.

Caught demonstration footage of the bug, alongside the Rapid Thistle Bear in #2840 
https://streamable.com/z4kmmu

**Comment by OkiFedora** [comment]
Confirmed this is a problem. Grimclaw seems to stay in his proper place until you give a /wave command while he is targeted. This is what you're told to do in the quest description. As soon as you enter /wave, Grimclaw takes off running north and he paths in the air, not on the ground as he should. I saw Grimclaw arrive in Auberdine and then phase out. I rode south and found him in his spot, targeted Grimclaw and then entered /wave. That's when he took off, literally!

**Comment by ishidinho** [comment]
Thank you for the input, @OkiFedora.

We will have a look on it again.

**Comment by acidmanifesto** [comment]
I am personally confirming this issue and tryin to figure why it is acting like this. i am digging further into the issue

**Comment by acidmanifesto** [comment]
Fix will be up next update
