### ISSUE TITLE
Zapped GDeep Strider falling through floor underwater

### ISSUE THREAD

**Issue by BeefSteaker** [chromiecraft/chromiecraft#2884]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Deep striders falling through map when zapped in water for https://wowgaming.altervista.org/aowow/?quest=7003 
non zapped giants also constantly in falling animation around 45.6, 61.8 feralas

### Expected Blizzlike Behaviour

Presumably not falling through the floor

### Steps to reproduce the problem

1. goto ~45.6, 61.8
2. shrink giant near ground and/or in falling animation
3. if they dont fall through the floor already, kill them
4. corpse falls through floor

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=7003

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Noobsdie4eva. Thank you for the report.

Sadly, I cannot reproduce the problem. I see no falling shrinked striders or corpses.

![WoWScrnShot_012822_133847](https://user-images.githubusercontent.com/62797536/151549656-48bcc90b-e9bd-4b57-82c5-5cf79cc84ecf.jpg)

![WoWScrnShot_012822_133951](https://user-images.githubusercontent.com/62797536/151549658-01fbc795-0a33-4f6d-9e4a-f0116e3e760e.jpg)

![WoWScrnShot_012822_134441](https://user-images.githubusercontent.com/62797536/151549659-30886a75-6b2d-4167-b016-a4ce4fb20873.jpg)
