### ISSUE TITLE
The screen freezes when entering RDF.

### ISSUE THREAD

**Issue by Matias-Salvador** [chromiecraft/chromiecraft#2885]
Hello, I wanted to ask about an error when entering dungeons, it has happened to me with several characters and I don't know if it only happens to me or if it is a known and solvable error. When entering through the RDF, half of the time it happens that the game freezes on the loading screen of the dungeon; I fix it by exiting the game and re-entering, but there is loss of data (for example, if I create a macro, it is deleted and I have to recreate it). Sorry for the inconvenience, best regards.

**Comment by IntelligentQuantum** [comment]
@Matias-Salvador I tested this several times it works fine for me.

Please delete your cache folder,  if there is a problem again, reopen this issue.
