### ISSUE TITLE
Lucky Rocket Cluster doesnt give Lunar Fortune Buff

### ISSUE THREAD

**Issue by ohkasdasf** [chromiecraft/chromiecraft#2886]
### What client do you play on?

deDE

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When using the Lucky Rocket Cluster from the Lunar Festival usually one gets a buff called Lunar Fortune that gives +250 HP. This worked with a rogue night elf character but not with a human paladin character, tested both on the same client in the same area (Ironforge) multiple times even after removing other buffs to prevent them from stacking.

### Expected Blizzlike Behaviour

Usually Lunar Fortune is given to any player that uses Lucky Rocket Cluster with 100% chance of occuring as far as people comment on WoWHead.
https://classic.wowhead.com/item=21744/lucky-rocket-cluster#comments

### Steps to reproduce the problem

1. Obtain a Lucky Rocket Cluster from the event with a human paladin.
2. Stand in Ironforge near a Rocket Launcher and use it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
Tested works fine

**Comment by ohkasdasf** [comment]
Tested again, no buff (no health increase and no buff shown). Could it be an account issue? Since the other character I tested it on is on another account? I can't imagine it is a client issue since there is absolutely no health increase. (Human Paladin, tested in IF and SW multiple times, with and without buffs, no effect at all).
