### ISSUE TITLE
Changefaction during dungeon set quest chain locks you out from completing.

### ISSUE THREAD

**Issue by Dobutsu1** [chromiecraft/chromiecraft#2890]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [x] 60

### Current Behaviour

Before moving to alliance i was on the 9th step of this quest "In Search of Anthion" since i have the darkmantle gloves that are the improved ones just by the previous quest (8th quest).

I decided to move to alliance without ending this questline, for my surprise the quest got reseted and i had to start all over again. 

I picked the first quest again and completed it and for my surprise again the 2nd quest didnt appear so im stuck at completing the first quest and i cannot obtain my dungeon 2 set.

Can i get moved to the 9th step as I was before changing to alliance or can I get the dungeon set any other way? I cannot do anything right now.

### Expected Blizzlike Behaviour

Quest should be working as intended, everybody has the dungeon 2 set but I guess they didnt change faction as I did

### Steps to reproduce the problem

no idea

### Extra Notes

No idea how to solve this

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Corrected content phase and AC rev. hash.

**Comment by ishidinho** [comment]
Hey @Dobutsu1. Thank you for the report.

Unfortunately, we cannot help you here. But I think a GM shoul be able to move you to your current quest line step.
I would like to advise you to open a support ticket in the #support-ticket channel on Discord to get in contact with a GM.

Please tell us here, if you got help there.

**Comment by Dobutsu1** [comment]
yes im waiting for an answer, posted the issue 2 times now.

I'll keep u updated!!

**Comment by 55Honey** [comment]
@ishidinho 
Hi, thanks for forwarding the issue. Could you please try and reproduce it, so we can consider it a valid bug and grant the quest states?
Thank you!

**Comment by temperrr** [comment]
Confirmed

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/10646
