### ISSUE TITLE
DM: East Warpwood Pods Not Despawning After Clicking

### ISSUE THREAD

**Issue by Soulex23** [chromiecraft/chromiecraft#2892]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

When you click on a Warpwood Pod in Dire Maul East, it unravels but immediately (or shortly after) spawns in again, this time being unclickable yet still applying the root/poison/spawn Whip Lashers on the player. 

### Expected Blizzlike Behaviour

Clicking on a pod should have it despawn without placing another.

### Source

https://tbc.wowhead.com/object=179526/warpwood-pod#comments

(Green comment from skyoverheaven):
These little green pods are found all over DM East and do one of the following randomly when you open them/approach them:

1) Spawn little 5-6 little mobs (https://tbc.wowhead.com/?npc=13022)
2) Poisons you (a nature DoT)
3) Yields either Runn Tum Tuber (https://tbc.wowhead.com/?item=18255), used in the recipe Runn Tum Tuber Surprise (https://tbc.wowhead.com/?spell=22761) and/or Thornling Seeds (https://tbc.wowhead.com/?item=18297)
4) Does nothing at all

### Steps to reproduce the problem

1. Head to Dire Maul: East
2. Wander up to one of the pods and click it so that it stops its effect
3. Either wait a few moments, or see that there's a second pod inside the first that cannot be clicked
4. Remain tangled/poisoned/swarmed by Whip Lashers (if you can't blink away from the roots/poison or feign death to de-aggro the Lashers)

### Extra Notes

According to one of the dungeon buddies I was running with, this has been an issue for months, if not since Dire Maul released, though after checking I think it's mainly because no one's made a bug report on here until now. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Soulex23. Thank you for the report.

This is a known issue https://github.com/azerothcore/azerothcore-wotlk/issues/8929.
