### ISSUE TITLE
Princess must die! - Elwynn Forest

### ISSUE THREAD

**Issue by claymore147** [chromiecraft/chromiecraft#29]
##### SMALL DESCRIPTION:

Found some issues with quest objective NPC - Princess

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should walk around with its companion NPCs - Porcine Entourage.
Porcine Entourages and Princess should all enter combat, when some of them is attacked.

##### CURRENT BEHAVIOUR:

Both NPCs are standing on same place. If you attack one of them, others will not join the fight, they must be attacked too to do so.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I recommend teleporting to the Princess NPC in Elwynn Forest and watching it for a while. It will not move from place.
2. I recommend attacking Princess NPC or Porcine Entourage to identify the bug.
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Fixed, it will be in the server soon.

**Comment by FrancescoBorzi** [comment]
The fix is now on ChromieCraft. Thanks for your report.
