### ISSUE TITLE
Lunar Festival quests are available again after completion

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#2904]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

You can complete the Elder quests again, I believe this shouldn't be possible.
![WoWScrnShot_013122_065042](https://user-images.githubusercontent.com/91145640/151772362-84c3ca57-6927-47d8-8c86-6765659e4583.jpg)

### Expected Blizzlike Behaviour

I believe the quests shouldn't be repeatable as said in WoWHead:

![Lunar psd](https://user-images.githubusercontent.com/91145640/151773114-61880a72-6417-40ba-a948-c535fe5e70b3.png)

### Source

• https://classic.wowhead.com/guides/lunar-festival-wow-classic#the-lunar-festival-quests-getting-to-moonglade

### Steps to reproduce the problem

1. Go to any Elder.
2. The quest is available.

### Extra Notes

Might reset after a week? I'm not sure about this.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d6724e448f35ea981d64aff868ce700ab0cbde3

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @FTGCocolandia. Thank you for the report.

I have been told that this is a known issue with world events in generel. The devs are already working on it.
