### ISSUE TITLE
[Frostmane Hold] Quest is unable to be completed

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#2905]
Azerothcore Issue Posted: https://github.com/azerothcore/azerothcore-wotlk/issues/10681
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Can't explore the cave.

### Expected Blizzlike Behaviour

Cave Explored

### Steps to reproduce the problem

Run around the cave and try to get credit from areatrigger.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d6724e448f35ea981d64aff868ce700ab0cbde3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @claudiodfc.

Please take the time and add at least a link to the quest. ;)

**Comment by acidmanifesto** [comment]
Quest
https://classic.wowhead.com/quest=287/frostmane-hold

**Comment by UltraNix** [comment]
Works okay.

**Comment by jw48165** [comment]
Still broken 3/26/22 - verified broken on two different toons, ran around the whole cave in addition to standing at 21,51 and relogging, no joy no matter what we did.

**Comment by jw48165** [comment]
Ahhh, coords are off.  All the quest trackers list 21.0, 51.0.  I see if you go to where the screener shows above, it completes it, but those don't match my quest tracker.  Other sources on the web show 22,52.  SO, for anyone reading this, go to 22,52.  May want to just update it to complete it at 21,51 as well.
