### ISSUE TITLE
Missing items after relog.

### ISSUE THREAD

**Issue by Floriskunst** [chromiecraft/chromiecraft#2910]
Three items of mine disappeared during a relog in Gadgetztan while I was doing Ancestry Coins gathering. My deathmist gloves&boots and my nifty stopwatch trinket. I had all of them for a while now and there's nothing in my mail.

My character is named Shale.

**Comment by Nyeriah** [comment]
Thanks for the report, but please open a ticket at Discord so we can look into your character :)
