### ISSUE TITLE
Clamlette Magnifique triggers 1 minute cooldown on all drinking items

### ISSUE THREAD

**Issue by vexima** [chromiecraft/chromiecraft#2911]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Consuming Clamlette Magnifique (item id 33004) causes all drinking items to go on 1 minute cooldown.

### Expected Blizzlike Behaviour

No cooldown should be triggered apart from a regular 1 second cooldown shared with other consumables. Corresponding Wowhead page says "Cooldown: 1 second."  No 1 minute cooldown mentioned in any wow database. 

### Source

https://www.wowhead.com/item=33004/clamlette-magnifique
https://wowpedia.fandom.com/wiki/Clamlette_Magnifique

### Steps to reproduce the problem

1. Consume Clamlette Magnifique (item id 33004)
2. 1 minute cooldown is placed immediately on any water item.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d6724e448f35ea981d64aff868ce700ab0cbde3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @vexima. Thank you for the report.

I can confirm the issue for all conjured mage water. Is that what you meant with "any water item" or did you found more? I experienced no shared cooldowns with other consumables.

**Comment by vexima** [comment]
I bought several different water tiers from vendor and consuming Clamlette did trigger cooldown on vendor water as well.

**Comment by rdallastra** [comment]
I can confirm the same happens whenever my character (Troll Hunter) consumes Clamlette, with Morning Glory Dew (item 8766) getting a 1-min CD.

**Comment by ishidinho** [comment]
Thank you very much, @vexima and @rdallastra.
I added your comments to the AC ticket.

**Comment by UltraNix** [comment]
https://www.wowhead.com/wotlk/item=33004/clamlette-magnifique#shared-cooldown

**Comment by vexima** [comment]
it says "Cooldown: 1 second" on the page you linked, not 1 minute. consider re-evalute this issue.

**Comment by vexima** [comment]
@UltraNix please revert your close, this is still a valid issue.
