### ISSUE TITLE
Quest All Along the Watchtowers

### ISSUE THREAD

**Issue by Lhezver** [chromiecraft/chromiecraft#2914]
### What client do you play on?

esES

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

https://wowgaming.altervista.org/aowow/?quest=5098

I marked the first three watchtowers, when I want to mark watchtower number 4 the torch disappears from my inventory.

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Lhezver. Thank you for the report.

Sadly, I was not able to reproduce the problem on my local AC. Quest worked as expected.

![WoWScrnShot_021322_175024](https://user-images.githubusercontent.com/62797536/153765615-413d973e-66d5-4b53-943b-7157798bfa0f.jpg)

I also did this quest some days ago an ChromieCraft, too. No issues there.

Can you provide more data or information to reproduce the problem?

**Comment by Lhezver** [comment]
Sorry, it was my mistake. The mission gives you 5 torches, I spent them all and had to restart the mission. There is no mistake, the mistake was mine.
