### ISSUE TITLE
Earth Shield 

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#2917]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

The shaman spell Earth shield has a chance to proc earthliving weapon 

### Expected Blizzlike Behaviour

Earthliving weapon can only proc off direct heals

### Source

https://github.com/chromiecraft/chromiecraft/issues/2563#issuecomment-994980165
 
"Earthliving Weapon (51940 and related 51945) does NOT have the spell attribute SPELL_ATTR3_CAN_PROC_FROM_PROCS = 0x04000000, // TITLE Can trigger from triggered spells.
With Earth Shield heal (56451) being a triggered cast, this means Earth Shield will never trigger Eearthliving Weapon."

https://www.youtube.com/watch?v=PxOllZgxQ8g&ab_channel=TheNever

### Steps to reproduce the problem

Cast earth shield on a target
the heal has a chance to proc earthliving 

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/2563

m'dic mentioned that "Earthliving Weapon (51940 and related 51945) does NOT have the spell attribute SPELL_ATTR3_CAN_PROC_FROM_PROCS = 0x04000000, // TITLE Can trigger from triggered spells." but maybe on this server it does

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Never6. Thank you for the report, but I do not understand, why you report the same issue again.

Duplicate https://github.com/chromiecraft/chromiecraft/issues/2917.

**Comment by Never6** [comment]
cause its been 3 months and its still not confirmed even when i have staff saying that that is how the ability works

**Comment by ishidinho** [comment]
Okay, but please do not re-post issues..
