### ISSUE TITLE
[Hunter Skill] Invigoration talent is generating aggro on nearby mobs

### ISSUE THREAD

**Issue by rdallastra** [chromiecraft/chromiecraft#2918]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Hunter Serpent Sting (spell 25295) is generating threat on nearby mobs (besides the mob in which it was applied) when used.

### Expected Blizzlike Behaviour

Serpent Sting should only generate threat on the target it was applied on.

### Source

Sadly, I could not find any source, but in CC up until November SS did not generate threat on nearby mobs.

### Steps to reproduce the problem

1. Send pet (I use a wolf, no aoe skills) to attack any group (2+) of mobs.
2. Fire Serpent Sting (skill 25295) on pet target
3. Check threat on nearby mob (they usually drop my pet and assume my toon as target). It is not a big amount of threat, but since the pet threat is zeroed, the slightest amount of threat will cause my hunter to go to top of threat table.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UnicornManure** [comment]
Hey, i could not reproduce the problem. Tried with various group sizes applying the spell to all but the chosen mob, also had skada & details and none of the addons showed any threat generating on the mob.

What items & talents where you using, maybe something else was procing & generating threat?

**Comment by IntelligentQuantum** [comment]
@rdallastra

**Comment by rdallastra** [comment]
I tried it again this week, and managed to cause it to happen once more, but it did not happen due to serpent sting. My spec is [BM](https://wowgaming.altervista.org/aowow/?talent#ctbMzxtRiu0xst:zfZMz) and I have a [wolf](https://wowgaming.altervista.org/aowow/?petcalc#0Md00sc00hoo). I had not used serpent sting, but one of the mobs had a threat value of 4 towards me, while it had 0 towards my pet (since the pet aggroed it in first place, it went to him, but shortly after it came to attack me). Not sure if it has something to do with [Spirit Bond](https://wowgaming.altervista.org/aowow/?spell=19578) ticks, or some other talent. I'll try to reproduce it again and will post results.

**Comment by acidmanifesto** [comment]
Is there a way to reproduce the issue consistently. I can not seem to get it to occur. @rdallastra

**Comment by rdallastra** [comment]
@acidmanifesto I have found no way to consistently reproduce it, but from time to time it happens to me. Last time I was in BRD, sent the pet to attack one of the fire elementals near Incendius, and another elemental went to the pet due to proximity. After a few seconds the second elemental came to attack the hunter, its aggro table (according to Omen) showed 4 for the hunter and 0 for the pet. I was only auto attacking and using Arcane Shot and/or Steady Shot at the time. Unfortunately I don't know if I can get a log of what happens, since I do not attack the monster for it to generate threat towards the hunter.

**Comment by rdallastra** [comment]
@acidmanifesto 
I went to BRD and tried my luck on the elementals that are in pairs just before incendius, and managed to reproduce it. I aggro with my pet one of them and send the pet to the other one, then start attacking the second one. In one of the pairs, I put 50 threat points (whatever it is called) in one of the mobs, and in two other pairs I put 4 threat points, on the last pair I managed to avoid hitting the first mob with my pet (by sending him to the second one before the pet hit the first one, just proximity aggroing it) so when I put 4 TP on it it came to attack me. I used Arcane, Serpent and auto-attack on the second mob, and managed to aggro the first one without attacking it. Did not use Mend Pet, which could explain aggro generation in an area around the pet.

![WoWScrnShot_030422_192732](https://user-images.githubusercontent.com/45319286/156858178-26e114f6-f66c-4c34-a512-8816c99d8835.jpg)
![WoWScrnShot_030422_194625](https://user-images.githubusercontent.com/45319286/156858180-fcfb3029-3aef-474a-a00b-34cb83e90cf1.jpg)
![WoWScrnShot_030422_195045](https://user-images.githubusercontent.com/45319286/156858182-50af3a9f-121e-48a9-838e-346be0e0cdfb.jpg)

**Comment by slicplaya** [comment]
I wonder if you had a mend pet tick or if somehow magically spirit bond heal was/is generating threat towards you somehow.

**Comment by rdallastra** [comment]
> I wonder if you had a mend pet tick or if somehow magically spirit bond heal was/is generating threat towards you somehow.

@slicplaya no mend pet cast, but could be from spirit bond, as my hunter is speced for that.

**Comment by Gultask** [comment]
[Spirit Bond](https://wowgaming.altervista.org/aowow/?spell=20895) generates no threat so it's impossible to be that.
I've not been able to reproduce, either. Does it still happen?

**Comment by Salehyn** [comment]
https://www.wowhead.com/wotlk/spell=53253/invigoration seems to be the culprit. The procs generate threat on all nearby mobs even if you are full mana and gain none (not sure they should generate threat at all), but it does steadily pull every mob off the pet that the pet didn't hit or AOE.

**Comment by Salehyn** [comment]
Confirmed on wotlk classic the ticks should generate threat when the hunter gains mana from it (but not at full mana)
So this is intended to some degree and the only way to prevent the aggro issue is to make sure the pet hits every target before the hunter starts spending mana (after fix)
Right now it's bugged in a manner that it always gives threat, even if the hunter hasn't spent any mana.

Tests courtesy of Kerrik:
https://www.youtube.com/watch?v=GHodjmOhPhw (0:29 invigoration proc generates 7 threat)
https://www.youtube.com/watch?v=xVndTkj_P8s no threat with full mana

There is one interesting thing about these tests though: the 7 threat points generated in the first test happen with only 1 out of the original 3 mobs in the pull still alive, which means the expected threat caused is the full 50% of the mana gain of 44 = 22. However the threat still seems to be split in 3, regardless of the other mobs being dead. This could be a blizz-bug, or a mechanic specific to this spell, since normally the threat should no longer be split with dead units.
