### ISSUE TITLE
[PTR] Lord Kazzak - Missing mechanic: Mark of Kazzak

### ISSUE THREAD

**Issue by Hyperbearr** [chromiecraft/chromiecraft#2929]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Lord Kazzak on the PTR doesn't apply Mark of Kazzak, thus removing the mechanic that causes players to explode at 0 mana/manage their mana. 

### Expected Blizzlike Behaviour

Kazzak should apply a removable debuff to casters called Mark of Kazzak that then causes them to explode upon reaching 0 mana, dealing significant damage to them and nearby allies. 

### Source

https://classic.wowhead.com/spell=21056/mark-of-kazzak

### Steps to reproduce the problem

Pull Kazzak
Afk for several mintues with multiple mana users in combat
Notice you never get the debuff

### Extra Notes

PTR Tested 3rd Feb 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Were you by yourself when you tested this? Because he'll never cast this on his tank

**Comment by temperrr** [comment]
It applies it, but it doesnt cause the explode.

**Comment by Hyperbearr** [comment]
> It applies it, but it doesnt cause the explode.

It was no applying and it was correctly causing a 3800 damage explosion on the PTR last night at 1:38am server time when I was fucking around with it, but as identified by Luckdemon, the mana drain portion of the spell appears to be draining inconsistently (between 1 and 250 mana per tick).
