### ISSUE TITLE
[Hunter] Feign Death not dropping combat properly in PVP

### ISSUE THREAD

**Issue by Scrublettt** [chromiecraft/chromiecraft#2934]
Azerothcore issue linked: https://github.com/azerothcore/azerothcore-wotlk/issues/10683

### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Currently when you feign death in PVP (with macro, so you can /stoppattack /petpassive too), it drops combat, but then immediately you enter combat again, without doing anything or being attacked and u have to wait up to 10 seconds to leave combat again.

This seems to be related with - [Hunter] Dropping combat takes way too long when pet is active #2928 as without Pet, Feign Death is dropping combat properly.

### Expected Blizzlike Behaviour

Feign Death should drop combat and not reenter combat automatically again, if there isnt anything attacking you or you attacking anything. You should be able to mount up right away after FD, for example.

### Steps to reproduce the problem

1. Create a hunter with pet
2. Enter BG
3. Attack a player with both pet and your character
4. Call pet back and Feign Death

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by slicplaya** [comment]
I haven't been able to replicate this problem at all. Is the pet passive? Every time I've used FD in or after combat(still in combat) it's worked fine and dropped combat 100% PvE and PvP.

**Comment by slicplaya** [comment]
I now have this bug as well. I can also confirm, and also add, using Feign Death drops combat, then immediately re enters. Even if doing so twice, and even if using shadowmeld with pet on passive. Any dot on the pet also keeps the player in combat until the ENTIRE duration is gone. Even if it's a debuff from say a shadow priest adding shadow dmg etc.

**Comment by slicplaya** [comment]
Tried this with multiple pets, and the same issue persists.

**Comment by slicplaya** [comment]
Can we get some action on this Class skill/pet issue bug? It's pretty demoralizing in PvP
