### ISSUE TITLE
Lord Kazzak Loot Table

### ISSUE THREAD

**Issue by Icebeam666** [chromiecraft/chromiecraft#2936]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Lord Kazzak often drops 0 epics, as shown on the screenshot, one time he dropped 4 epics.
![WoWScrnShot_020322_191611](https://user-images.githubusercontent.com/65196200/152405281-f0cb2278-2fc9-4400-865e-9d4f2de9d27a.jpg)

### Expected Blizzlike Behaviour

Kazzak should always drop some of the epics from his loot table like all other raid/world bosses do. I believe 2 epics with a chance of Eye of Shadow on top of that (like in the sources I linked) but not 100% sure about this.

### Source

Example of loot from Kazzak kill (13:52):
https://www.youtube.com/watch?v=ArwsQ9yVO2M&ab_channel=Soysauges
Another example (3:24):
https://www.youtube.com/watch?v=5f8hCyuW0nI&ab_channel=DeezNuts

### Steps to reproduce the problem

Go to kazzak location
Spawn him with .respawn
Kill him
Loot him

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Hyperbearr** [comment]
Issue already open here: https://github.com/chromiecraft/chromiecraft/issues/2932

**Comment by ishidinho** [comment]
Hey @Icebeam666. As @Hyperbearr mentioned, this has already beem reported.
