### ISSUE TITLE
[LBRS] There's a Smolderthorn Berserker that doesn't attack.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#2938]
Linked azerothcore issue: https://github.com/azerothcore/azerothcore-wotlk/issues/10782
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

The mob won't attack, even if you attack it.

![WoWScrnShot_020322_200204](https://user-images.githubusercontent.com/91145640/152443921-5ec6cac8-d3f5-426a-a88d-c944066ab4e9.jpg)
![WoWScrnShot_020322_200211](https://user-images.githubusercontent.com/91145640/152443927-965ee1bb-6ef3-4c74-a32f-f30d5e1da3cc.jpg)
![WoWScrnShot_020322_200217](https://user-images.githubusercontent.com/91145640/152443930-c80b5066-2a28-4f60-91ed-35482b4e0f3d.jpg)

### Expected Blizzlike Behaviour

It should attack.

### Steps to reproduce the problem

1. Go to the end of the dungeon Lower Blackrock Spire.
2. Move past the mob, or attack it.

### Extra Notes

GUID in the screen captures above.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Not entirely certain if it was a issue with just that session, are you still having this issue? @FTGCocolandia

**Comment by FTGCocolandia** [comment]
There we go:

https://user-images.githubusercontent.com/91145640/154166412-dfc9c151-4c5f-4b17-956b-f178e4d81060.mp4
