### ISSUE TITLE
[PTR BWL] Chromaggus Elemental Vulnerability

### ISSUE THREAD

**Issue by Hyperbearr** [chromiecraft/chromiecraft#2954]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Chromagus' Elemental Vulnerability (tied to Shimmer) seems to have an abnormally high chance of picking the same element multiple times in a row. Across 20 pulls and 45 minutes of combat I was frequently seeing the same element rolling back to back to back 3 or even 4 times in a row. It was occurring often enough that the variation from the expected pattern (assuming it were true random) is statistically significant. 

### Expected Blizzlike Behaviour

Rolls a new RANDOM element every 30 seconds with the new element not being influenced at all by the last

### Steps to reproduce the problem

Sit in combat with chromaggus for nearly an hour, record all of the elemental vulnerabilities and notice the trends. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
Do you have a source for this>?

**Comment by acidmanifesto** [comment]
this is being marked as under evaulation as it is being debated interally. hopefully a answer will be provided eventually.

**Comment by temperrr** [comment]
Hey I have been looking into this for a while now. I think the issue resides in that it should switch a lot more often. I checked the code and it does have an equal chance in rolling every vulnerability. Your videos also show about 12-24 seconds between vulnerabilities.
