### ISSUE TITLE
The world drops are all over the place

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#296]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

World mobs drop items they shouldn't drop,just like mobs from sm entrance drop items like Humbert Pants,or werewolves in duskwood drop lv 40 blues like Sheepshear Mantle.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should never have a chance to drop any of those items.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just go kill sm mobs and werewolves in duskwood,and probably a lot more mobs that have a whacky item drops.
2. 
3. 
4.

##### EXTRA NOTES:

Honestly the world drops are so bugged it feels like literally every mob can drop anything,I once got a lv40 blue shoulders from werewolves in duskwood??

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Narixel** [comment]
why close this?
also proof 
https://i.postimg.cc/R0yL1Rpr/ifdgdfgndex.png

**Comment by FrancescoBorzi** [comment]
@Narixel because we need more details. We need to know which NPCs (give names, links, etc...) and which items they are dropping too frequently and they shouldn't.

Please take some time and write proper reports.

**Comment by FrancescoBorzi** [comment]
![image](https://user-images.githubusercontent.com/75517/112662886-7e2bd480-8e58-11eb-9b99-4f7836566c96.png)

**Comment by Narixel** [comment]
The report seems clear and good enough,this will only discourage other people to write reports if they have no submit perfect clean sheet ones.

**Comment by FrancescoBorzi** [comment]
@Narixel example of a **good** bug report:

- Killing the NPC "Name of The NPC" (link of the NPC from [wowgaming](https://wowgaming.altervista.org/aowow/) or similar websites) X times has dropped Y times the item "Name of the item" (link of the item from [wowgaming](https://wowgaming.altervista.org/aowow/) or similar websites).
- According to _link_of_some_reliable_source_ this item should not be dropped so many times

even if your report was not properly filled I still want to thank you for your contribution efforts and I hope you understand my point
