### ISSUE TITLE
Ele Shaman: Losing a charge of Water shield spends a charge of Clearcasting

### ISSUE THREAD

**Issue by kulkan1** [chromiecraft/chromiecraft#2960]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Being hit while using [Water Shield](https://wowgaming.altervista.org/aowow/?spell=52134) removes a charge of [Clearcasting](https://wowgaming.altervista.org/aowow/?spell=16246) from the talent [Elemental Focus](https://wowgaming.altervista.org/aowow/?spell=16164) when the hit triggers Water Shield.

### Expected Blizzlike Behaviour

Clearcasting should only spend charges when you cast a damage or healing spell. Water Shield neither damages or heals, nor does it cost any mana to cast (neither when cast or triggered).

### Source

https://www.youtube.com/watch?v=voeAGBBoXnI
5:44 (watch in slow-mo)

You see that the shaman goes from 3 to 2 charges on Water Shield, while Clearcasting does not lose a charge.

### Steps to reproduce the problem

1. Be Elemental shaman
2. Be buffed with Water Shield
3. Proc Elemental Focus (Clearcasting)
4. Be hit and lose a charge of Water Shield

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Luckdemon** [comment]
Can confirm that Water Shield popping and also being reapplied both consume stacks of clearcasting.
