### ISSUE TITLE
Ragnaros no loot after killing him between phase shifting (from phase 2 to phase 1)

### ISSUE THREAD

**Issue by lovelord83** [chromiecraft/chromiecraft#2969]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Instance ID 946

Master looter enabled on Notmymain.

Ragnaros has been killed by dots and debuffs few seconds before submerge phase. 
"Sons of flames" went up and Ragnaros died. 
"Sons of flames" despawned and Ragnaros' hammer dropped down, shining on the ground with loot on it.

No loot available to anyone. Master looter can't click on hammer and nobody view the sachel icon on it. 

Tried to logout and relog: no result.
Tried to switch loot type: no result.
Tried to teleport out and back: no result.
Passed ML to another player: no result.

### Expected Blizzlike Behaviour

Boss down. Loot.

### Steps to reproduce the problem

Instance ID 946

Master looter enabled on Notmymain.

Ragnaros has been killed by dots and debuffs few seconds before submerge phase. 
"Sons of flames" went up and Ragnaros died. 
"Sons of flames" despawned and Ragnaros' hammer dropped down, shining on the ground with loot on it.

No loot available to anyone. Master looter can't click on hammer and nobody view the sachel icon on it. 

Tried to logout and relog: no result.
Tried to switch loot type: no result.
Tried to teleport out and back: no result.
Passed ML to another player: no result.

### Extra Notes

We have recorded a video AFTER the boss fight, when bug has been noticed.

This is the link: https://youtu.be/Sffyhq7vPU4

You can notice that loot is there, but even if I try to click on hammer in multiple manner there's no loot at all, even if hammer is shining on ground.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by 55Honey** [comment]
The issue exists confirmed.

When he dies while submerged, there's no loot.
Steps to reproduce:
- Pull Ragnaros
- Bring him down to less than 7k hp
- Wait 2:15 minutes after he starts melee
- Cast Curse of Doom 3 on him
- He will die while submerged, flicker, but not yield loot. No bag cursor, too.
