### ISSUE TITLE
 Wailing Caverns Disciple of Naralex moves too fast

### ISSUE THREAD

**Issue by eTzmNcbkrng** [chromiecraft/chromiecraft#297]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Disciple of Naralex in Wailing Caverns moves too fast.
Using the macro `/run print(GetUnitSpeed("target"))` his walking speed is observed to be slightly above 3.5

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Disciple of Naralex' movement speed should be slightly slower than a player's walking speed.
Citation:
>This guy might be the slowest walking escort in the game. He's the only one I've noticed that you can actually pass at walking speed.
https://www.wowhead.com/npc=3678/muyoh#comments:id=657945

His movement speed should be less than 2.5, which is what a player's walking speed is.

##### STEPS TO REPRODUCE THE PROBLEM:
In order to start the event which makes Disciple of Naralex start walking, you must kill the 4 Leaders of the Fang
They can be found here:
`.go creature 27380`
`.go creature 27366`
`.go creature 87107`
`.go creature 38148`

Once they are dead go to the Disciple of Naralex:
`.go creature 18675`

Talk to him and select the gossip option "Let the event begin!"
He will begin to walk away.
Observe his movement speed with `/run print(GetUnitSpeed("target"))` is about ~3.5

##### EXTRA NOTES:

This is NOT a duplicate of #281 which addresses the NPC not stopping to help with combat and mentions nothing about movement speed.
The video on that ticket is post-cata when Disciple of Naralex received a MASSIVE increase to his movement speed.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
![image](https://user-images.githubusercontent.com/1884642/112635142-5c6c2680-8e33-11eb-8a26-85d5d7edbf5a.png)
that's the problem
