### ISSUE TITLE
[Feralas] OOX-22/FE runs underground and flies during escort quest.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#2980]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

During the escort quest the NPC flies for a bit, and then, when getting to the main road will get underground before dissapearing.

EDIT: Proof:

https://www.youtube.com/playlist?list=PLcQgZPpn1TlDwjCuBuSHVfTxpCdqvweK0

The first time I completed the quest the chicken went underground before doing the animation and dissapeared. I was unable to get it recorded.

### Expected Blizzlike Behaviour

It shouldn't fly towards the road during the quest, and it shouldn't go underground after finishing it.

I can't find if it should do this animation:  https://youtu.be/hlfyVbT86T4?t=115 / https://youtu.be/0AX47_v-cak?t=112 or if it only has to dissapear as in Classic: https://youtu.be/pcPlaBFVys4?t=493

For sure doesn't have to go underground though.

### Steps to reproduce the problem

1. In feralas do the escort quest: https://wowgaming.altervista.org/aowow/?quest=2767
2. The NPC flies for a bit during the quest.
3. The NPC will go underground after reaching the main road.

### Extra Notes

I didn't get to record as I was doing the quest, might try with another character later.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Luckdemon** [comment]
Could not reproduce this bug on the PTR.
The escort was changed in wotlk to be shorter and end where it currently does shortly after reaching the main road.

Perhaps try again on another character and record the pathing issue?

**Comment by FTGCocolandia** [comment]
@Luckdemon Hey. Ok, so I tried a couple times: https://www.youtube.com/playlist?list=PLcQgZPpn1TlDwjCuBuSHVfTxpCdqvweK0

As you can see the chicken flies and goes underground sometimes.

The first time I did the quest the chicken went underground when it reached the main road and It didn't do the whole animation thing at the end. I had it marked with a star and it didn't move, it just fell until it dissapeared.

**Comment by ishidinho** [comment]
Hey @FTGCocolandia. Thank you for the report.

I was not able to reproduce the problem on local after doing the quest three times.

**Comment by Sathrenor** [comment]
@ishidinho @FTGCocolandia 
Requesting to reopen, this issue is still present in the live server (and I see no reason to make a new report)

You can see the chicken actually flying inside a cave or in the halfway of escort, as well as collapsing under textures at the very end.
Also it seems to trigger an engage dialogue when the quest is inactive, but cannot confirm if it's blizzlike or not.
https://www.youtube.com/watch?v=p0N9_4Zt5OA&feature=youtu.be

_Side note:_
_DB Guid: **50381** Entry **7807**_
_Also #1125 just for the link_
