### ISSUE TITLE
[Dun Morogh] Unguarded Thunder Ale Barrel and Guarded Thunder Ale Barrel overlap.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#2981]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The two barrels are over eachother.

https://user-images.githubusercontent.com/91145640/152694806-d4dde572-3208-433f-9e15-b367b4b95e20.mp4

### Expected Blizzlike Behaviour

It should be only the Guarded Barrel until the NPC gets distracted. Then it should be replaced by the Unguarded one as seen here: https://youtu.be/EElKpo1mu6U?t=175

### Steps to reproduce the problem

1. Go to the Thunderbrew Distillery.
2. Hover over the barrels.

1037 (Entry: 269) - [Guarded Thunder Ale Barrel X:-5607.240234 Y:-547.934021 Z:392.984985 MapId:0] 
[15:09:26] 35875 (Entry: 270) - [Unguarded Thunder Ale Barrel X:-5607.240234 Y:-547.934021 Z:392.984985 MapId:0] 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by FTGCocolandia** [comment]
Still happening:

https://user-images.githubusercontent.com/91145640/153966087-3a4cbe3f-95ea-4a2b-b976-a092e109abc0.mp4

1037 (Entry: 269) - [Guarded Thunder Ale Barrel X:-5607.240234 Y:-547.934021 Z:392.984985 MapId:0] 
35875 (Entry: 270) - [Unguarded Thunder Ale Barrel X:-5607.240234 Y:-547.934021 Z:392.984985 MapId:0]

**Comment by Luckdemon** [comment]
It appears that the guarded barrel does not despawn when Jarven leaves the basement and the unguarded barrel appears, so there is one of each. When Jarven comes back downstairs a new guarded barrel spawns without despawning the previous guarded and unguarded barrels.

Issue confirmed on PTR.

**Comment by ishidinho** [comment]
Hey @FTGCocolandia. Thank you for the report.

I can confirm the issue.
For future bug report, please tell us at least the quest you are on. ;)

@Luckdemon Please try to reproduce the issues on a local AC. PTR is not a valid source.
