### ISSUE TITLE
Heroic Training Dummy (Boss Mechanical) from Ironforge

### ISSUE THREAD

**Issue by Josarth** [chromiecraft/chromiecraft#2985]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Hi, i was trying to improve my rotation with my frost mage on the "Heroic Training Dummy" (Boss Mechanical) from Ironforge but i saw i loss combat after 4 sec if i fail one attack. Also i was trying to see my damage with new trinkets using the Deep Freeze ability, but it doesn't damage to it and i guess it shouldn't be happening because it's a Boss Mechanical.

### Expected Blizzlike Behaviour

I guess the combat should be a bit more longer and the Deep Freeze should do damage like on the raid bosses.

### Steps to reproduce the problem

I started attacking the Boss Dummy
Failed one frostbolt and i lost the combat and my debuff on the dummy automaticly dissapear
When i'm trying to use Deep Freeze ability after Finger of Frost talent pops i stun the Dummy when it should be doing damage (or that i guess, cause is the "Boss Dummy".

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Jackomighty** [comment]
You should get out of combat with training dummies after 4 seconds from not attacking it, source: https://www.youtube.com/watch?v=nRJRfMlWmns
Deep Freeze deals damage to targets permanently immune to stuns, source: https://wowpedia.fandom.com/wiki/Deep_Freeze?oldid=2328162
