### ISSUE TITLE
While turning in quests the NPC's prioritize the wrong marker.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#2989]
Original AC issue linked: https://github.com/azerothcore/azerothcore-wotlk/issues/11237

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I've seen this many times now, the quest givers have the new quest marker above their head instead of the turn in one.

https://user-images.githubusercontent.com/91145640/152796914-8c164760-a055-4bc0-97a3-a38ad37b962f.mp4

You can see the map shows the correct one, the minimap does not.
![imagen](https://user-images.githubusercontent.com/91145640/152796486-cf71e1ff-c753-4046-9036-0f40395c1be2.png)

### Expected Blizzlike Behaviour

I'm pretty sure NPC's should always show the turn in quest marker above their head (?) if there's a quest to be delivered even if it can deliver a new quest (!).

Also, the turn in quest marker should appear in the minimap.

### Steps to reproduce the problem

For this particular example:

1. Don't do the quest "The First and the Last".
2. Complete the quest "A Gift for The King of Stormwind".
3. Turn in "A Gift..." 

### Extra Notes

I've seen it happen with many quests.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Josarth** [comment]
already done that quest without problems too at the first time when the event begun and today as a daily

**Comment by cachocarne** [comment]
I noticed the same issue. I don't think it's about showing the "new quest available" marker, the thing is that it shows the marker corresponding to whatever question is first on his list. So, in your example, he has a low lvl quest before the one from the event, so it shows "!" for the available quest.

On my image you can see I had two quests from this npc in Tanaris. The first one was not complete yet, the second was completed. Instead of showing the golden "?", it shows the silver one.
![ 2022-02-14 at 16 28 49 2](https://user-images.githubusercontent.com/77953030/154150045-d8c1662c-86c2-4134-9bcf-8a30bd1e8ae0.png)
Hope it helps.

**Comment by FTGCocolandia** [comment]
@cachocarne I believe you might be right.

**Comment by acidmanifesto** [comment]
Just a follow up, i am requesting some more information of this issue with the devs so hopefully i will be able to follow up with something soon.

**Comment by Kosiak** [comment]
If i remember correctly it was always like that. All the servers even official ones does it like that. As cachpcarne said it's probably  a priority low / high level. Not a bug really
