### ISSUE TITLE
Gunpowder door in Deadmines did not open correctly, remained impassable

### ISSUE THREAD

**Issue by typhirz** [chromiecraft/chromiecraft#299]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

The final door in Deadmines, the one that can be lockpicked or blown up with the gunpowder, will reshut if both lockpicking and gunpowder are used and they fire off at the same time. Visually, it will blow up, open up, then immediately close again. The door is then uninteractable, and there is no more gunpowder to attempt to re-open the door.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The door should open up even if both ways of opening the door fire at the same time.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the final door of Deadmines with two players, one being a rogue
2. Have the non-rogue grab the gunpowder
3. Have the rogue start lockpicking the door
4. When the rogue is nearly finished with lockpicking, have the player with the gunpowder use the cannon, so that they finish at almost the same time.

##### EXTRA NOTES:

This happened one time, so it's possible that the reason the door reclosed is something else, or that it might be hard to reproduce.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
This bug won't be fixed as you can read in this closed issue a month ago https://github.com/chromiecraft/chromiecraft/issues/69#issuecomment-777623308
