### ISSUE TITLE
[Love is in the Air] Possible incorrect behavior 

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#3002]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The NPC Edgar Boatwrighte currently attacks you when you spray him with https://wowgaming.altervista.org/aowow/?item=49669

Addiotionally he also doesnt get thehttps://wowgaming.altervista.org/aowow/?spell=69438 debuff when sprayed allowing him to be sprayed over and over again

### Expected Blizzlike Behaviour

This npc isnt in any official blizzard server so this can be considered a matter of opinion but he shouldnt attack you when sprayed because I do not know of any npc that attacks you when you spray them

Additionally he should also get debuff when sprayed 

### Steps to reproduce the problem

get https://wowgaming.altervista.org/aowow/?item=49669
spray NPC edgar Boatwrighte with said item
Attacks you and doesnt get debuff

### Extra Notes
First Edit: He gets the debuff when you gain combat with him but after dropping combat he loses the debuff 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by r-o-b-o-t-o** [comment]
Note for triagers & devs: this NPC comes from [chromiecraft/script-pvp-arena](https://github.com/chromiecraft/script-pvp-arena).
@Never6 I suppose the behaviour is the same with Hayley Boatwrighte?

**Comment by Never6** [comment]
i assume it would be the same but i have not tested it myself as im not a dirty alliance player :P

**Comment by r-o-b-o-t-o** [comment]
It's also Edgar in Stormwind (ubiquity ftw), Hayley is the NPC in the arena zone when you get teleported by Edgar 😆

**Comment by ishidinho** [comment]
@r-o-b-o-t-o 

I cannot open your link for triaging.

**Comment by acidmanifesto** [comment]
I do not have access to that script either, however issue is confirmed as a problem and will be marked as appropiate

**Comment by r-o-b-o-t-o** [comment]
Fixed by https://github.com/chromiecraft/script-pvp-arena/commit/1052cb2c1d879c79121ac2d6a6c455b779c88e31
