### ISSUE TITLE
Ship in Deeprun Tunnel

### ISSUE THREAD

**Issue by OA350** [chromiecraft/chromiecraft#3003]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Theres a ship in Deeprun Tram station in Ironforge

### Expected Blizzlike Behaviour

There should be no ship in the tram station

### Source

![image](https://user-images.githubusercontent.com/76611816/153013468-7330b2e9-1bc3-4aa2-99e0-58e31845ba0d.png)

### Steps to reproduce the problem

1. Go to the Deprun tram in Stormwind
2. Drive to Ironforge
3. With a little luck you can find a ship there, it doesn't always appear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @OA350. Thank you for the report.

Sadly, I did not experienced this issue in 30 minutes of waiting.

"it doesn't always appear" is hard to reproduce.

Can you provide more information?
Did the issue occured again?
Do you have any modification patches (`*.mpq`) installed in your ChromieCraft installation directory?

**Comment by cachocarne** [comment]
I think this was already reported, and not only on this server. I believe it's due to a client with some messed up models. I would recommend you to find a new one for 3.3.5 (12340a) from a good source.
Good luck!
(anyway I find it quite funny)

**Comment by OA350** [comment]
No, I couldn't reproduce it ever again. (Sorry for late answer). But cachocarne is right, i have seen this once before on a different server. I think we can close this issue

**Comment by 55Honey** [comment]
I've been there when a player reported it and only they we're able to see it. They ran against the ship on their Screen and into an invisible wall on mine.
