### ISSUE TITLE
[Molten Core] Ragnaros - Wrath of Ragnaros

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#3005]
### What client do you play on?

ruRU

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

[Wrath of Ragnaros](https://wowgaming.altervista.org/aowow/?spell=20566)
Doesn't wipe threat

### Expected Blizzlike Behaviour

Wrath of Ragnaros must wipe all threat

### Source

https://youtu.be/J6nE7eopMuY
https://youtu.be/ivaIy6eh5YI

### Steps to reproduce the problem

123

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Hyperbearr** [comment]
Just tacking a comment on this to say that the threat reset whilst bugged shouldn't be introduced until 
https://github.com/chromiecraft/chromiecraft/issues/2857 is addressed. 

Currently it'd cause an insane number of wipes as a result of the trash mechanic being bugged.

**Comment by Plasmashield** [comment]
> Just tacking a comment on this to say that the threat reset whilst bugged shouldn't be introduced until #2857 is addressed.
> 
> Currently it'd cause an insane number of wipes as a result of the trash mechanic being bugged.

Yes, I also faced this problem. Maybe I'm wrong, but I think the problem is elsewhere. Ragnaros tries to cast [Elemental Fire](https://classic.wowhead.com/spell=20564/elemental-fire) on last target or something like that. But puts it on the current tank and since the debuff doesn't appear on the intended target, he repeats this every GCD. As a result tank just melts. So maybe this can solve both problems
