### ISSUE TITLE
[Minor] Renn McGill's dialogue does nothing (and global dialogues bug)

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3015]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

_Two issues here:_

1. Renn McGill _[DB Guid: **18595** Entry: **23569**]_ dialogue option is available even if You don't have a related quest [Recover the Cargo!](https://wowgaming.altervista.org/aowow/?quest=11140), and even if player has the quest, he does not give a replacement diving helm.

2. (UI bug) Clicking a dialogue option prevents a player from choosing the other options (like picking up the quest), forcing him(/-er) to close and reopen the dialogue window. Also the same lock happened to me in the past after I exceeded a certain time reading the text page. (CC client) 
_(^This issue needs more testing and a separate ticket, but I post here for a future references.^)_

[Video as a proof here](https://www.youtube.com/watch?v=bOG-sDuYhd0)

### Expected Blizzlike Behaviour

1. Renn McGill's dialogue should give an replacement helm by casting **[spell=42670](https://wowgaming.altervista.org/aowow/?spell=42670#.)** whether the original gets destroyed or expired.

2. Choosing dialogue option should not block other options from being selected.

### Source

1. [_"Talk to Renn if you run out of time to get another."_](https://wowpedia.fandom.com/wiki/Recover_the_Cargo!) ~Wowpedia quote

2. In case of the second issue, I can't find any, nor confirm whether it's a blizzlike issue or not.

### Steps to reproduce the problem

1. To to Dustwallow Marsh (63,7, 17)
2. Talk to Renn without [Recover the Cargo!](https://wowgaming.altervista.org/aowow/?quest=11140) quest
2,1. Or do it during the quest and don't get a new helmet.

### Extra Notes

Quest: [Recover the Cargo!](https://wowgaming.altervista.org/aowow/?quest=11140)
NPC: [Renn McGill](https://wowgaming.altervista.org/aowow/?npc=23569) _[DB Guid: **18595** Entry: **23569**]_
Spell: **[spell=42670](https://wowgaming.altervista.org/aowow/?spell=42670#.)**

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ZhengPeiRu21** [comment]
Thank you for the detailed report! Providing the correct spell ID made this very easy to fix.

**Comment by Gultask** [comment]
Closed via above
