### ISSUE TITLE
Elemental shaman problems

### ISSUE THREAD

**Issue by Oglis** [chromiecraft/chromiecraft#3017]
### What client do you play on?

other

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

when u cast elemental mastery, any first spell that i cast uses the instant cast provided by elemental mastery, flame shock, water shield etc.. even stormbound tome is using the instant cast of elemental mastery
AND the mana reduction of Elemental Focus is being used by free spells, such as Thunderstorm and water shield

### Expected Blizzlike Behaviour

the correct behavior of elemental mastery instant cast is to be only used on the spells that are in the tooltip of Elemental mastery
and Elemental focus mana cost reduction should only be consumed by spells that have mana cost, like healing wave

### Steps to reproduce the problem

have any of the procs, Elemental mastery of elemental focus, and cast a spell that are not suposed to be used by it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thank you for your report, Oglis.
This issue has already been confirmed as a bug, see: #2960

**Comment by Chobungus** [comment]
All shock spells consume the instant cast potion of the spell. Is this intended?

**Comment by Gultask** [comment]
@Chobungus Thanks for pointing out that this is still an issue. Could you open another report? Just follow the template provided when clicking the 'New Issue' button.

**Comment by Gultask** [comment]
I'm very sorry about this, @Oglis
I had made a mistake and did not notice that the other report only mentioned part of yours. I'll mark this one as confirmed and linked.
