### ISSUE TITLE
you can evade the chocolate 

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#3018]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

you can evade the chocolate from the event "love is in the air"
![WoWScrnShot_021022_095919](https://user-images.githubusercontent.com/84640316/153373199-d4bea2dc-3f81-40c4-bd11-0ee576a309c1.jpg)
![WoWScrnShot_021022_095925](https://user-images.githubusercontent.com/84640316/153373207-02be9f1d-80f8-4088-afb7-2f85a7ca21ad.jpg)

### Expected Blizzlike Behaviour

you can't evade (probably)

### Steps to reproduce the problem

throw the chocolate from the daily.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by luckdemon** [comment]
It appears that all players are evading when being targeted by the Love is in the Air chocolate samples.
https://wowgaming.altervista.org/aowow/?item=49670
https://wowgaming.altervista.org/aowow/?spell=69489
NPCs do not evade and are given the debuff as normal.
Players that evade still give quest credit and can be targeted 10x in a row to complete the quest.

**Comment by FTGCocolandia** [comment]
Can confirm:

https://user-images.githubusercontent.com/91145640/153734394-6a6f43cb-bc25-4011-8aea-5b7d41e3f0e1.mp4

**Comment by ishidinho** [comment]
Thank you, @FTGCocolandia.

I can confirm the issue.
