### ISSUE TITLE
[NPC] Shatterspear Trolls Respawn

### ISSUE THREAD

**Issue by Boovisdoodoo** [chromiecraft/chromiecraft#3019]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

The trolls that were reported to have an "incredibly fast respawn timer" in Github #2824, were changed from the original respawn timer to a 5-7 minute respawn. They are and always have been the correct 2-3 minute respawn timer since vanilla well through 3.3.5. While it may be considered a fast respawn rate, the drops and silver do not equate to anything that isn't farmable in other areas. I will attach multiple videos, wow-wiki, and original 2006 Warcraft movies, from different expansions showing their respawn rates and expected "Blizzlike Behaviour".

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=0I4o4aLk-QY
https://www.youtube.com/watch?v=cFxbcbK-DaM
https://www.youtube.com/watch?v=88HxIzabPq4
https://wowwiki-archive.fandom.com/wiki/Shatterspear_Vale
https://www.warcraftmovies.com/movieview.php?id=17030

### Source

In the Warcraft Movies link it is commented below the video that "Works as of patch 3.5".

### Steps to reproduce the problem

1. Return the Shatterspear Trolls to the original and correct respawn timer.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 2010.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ZhengPeiRu21** [comment]
The current respawn timer of 5 minutes is consistent with Vmangos. However, the video does appear to be 2-3 minutes. I think we need a sniffer to check this for sure.

**Comment by Boovisdoodoo** [comment]
I appreciate the quick response! I can send more examples if needed. 
What is a sniffer?

**Comment by ZhengPeiRu21** [comment]
> I appreciate the quick response! I can send more examples if needed. What is a sniffer?

A sniffer is someone who will log in to a Retail server and use a special program like this one (https://github.com/Anubisss/SzimatSzatyor) to save the data the game is send to the client. That way we can see what the true data is coming from official source.

However, I am not sure if respawn time is included in the sniffer saved data. If not, the best we can do is review video and live data to make our best guess! If you have more sources available, please share them and we can review together. Thank you for your support!

**Comment by Boovisdoodoo** [comment]
Good Morning! 
Are there any updates?
Happy Valentines Day!

**Comment by ishidinho** [comment]
Hey @Boovisdoodoo.

> https://www.youtube.com/watch?v=TqFOIe2UOhk -Shows Respawn Rate

I do not see the respawn rates there. Am I missing something? At which timestamps should I look?

**Comment by Gultask** [comment]
Finally managed to park a character in the Valley. I'll try to sniff the respawn timers :)

**Comment by Gultask** [comment]
I can confirm. The respawn timer seems to be around 2:30 to 3:30 minutes.
