### ISSUE TITLE
Book has incorrectly formatted HTML text

### ISSUE THREAD

**Issue by eTzmNcbkrng** [chromiecraft/chromiecraft#302]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When reading the book Lament of the Highborne, the text is displayed as HTML and not human readable.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Book should be legible by a human.

##### STEPS TO REPRODUCE THE PROBLEM:

~~`.additem 30632`~~ Edit: False report, my bad :(

Be at least Level 15
Go to [Sylvanas](https://wotlkdb.com/?npc=10181): `.go cr 32039`
Accept the first [quest](https://wotlkdb.com/?quest=9175) from the [item](https://wotlkdb.com/?item=22597) that starts the chain: `.additem 22597`
Turnin the quest: `.quest reward 9175`
Add the followup [quest](https://wotlkdb.com/?quest=9180): `.quest add 9180`
Turnin the quest at Sylvanas
Talk to [Ambassador Sunsorrow](https://wotlkdb.com/?npc=16287) (standing to Sylvanas' Right) to get the book.

Here is a video of me reproducing the bug on a local install showing that book obtained from GM command is fine, but the book from the quest is broken.
https://www.youtube.com/watch?v=XyUjCNjXFMY

##### EXTRA NOTES:

Looks like it might have been a straight copy-pasta from Wowhead without checking how it displayed in game.
Might be worth checking the database for other books that have HTML tags in them, I have no idea what the SQL for that might be though.

![image](https://user-images.githubusercontent.com/26512802/112716634-5c137e80-8f4c-11eb-8566-c0e591697ef5.png)
![image](https://user-images.githubusercontent.com/26512802/112716639-62a1f600-8f4c-11eb-9f90-a102e52c42b7.png)
![image](https://user-images.githubusercontent.com/26512802/112716642-66357d00-8f4c-11eb-9181-be3729506262.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
https://user-images.githubusercontent.com/1884642/112717209-0787e900-8ee3-11eb-9582-64516c0538ad.mp4

I think 3 reports for the same INVALID reason are sufficient for this year.

**Comment by eTzmNcbkrng** [comment]
Using all exactly the same settings, this book displays correctly on my local AzerothCore install.
I am unable to test on ChromieCraft as I have vendored the book, is your test performed on your own install or on ChromieCraft?

Does it display correctly on ChromieCraft?

**Comment by eTzmNcbkrng** [comment]
I have finally managed to reproduce this bug!
It does not present when a gm uses the command `.additem 30632`
It only happens when a player receives the book from Ambassador Sunsorrow

Original bug report has been updated above.

**Comment by Stifler82** [comment]
> I have finally managed to reproduce this bug!
> It does not present when a gm uses the command `.additem 30632`
> It only happens when a player receives the book from Ambassador Sunsorrow
> 
> Original bug report has been updated above.

Ok, this might make sense..
In fact, I have seen this kind of "transitive bug" other times, however I'm pretty sure that the error is not in the item, probably the problem is the NPC.

Meanwhile, I reopen the issue because this new information changes everything..
I will investigate this issue as soon as possible, at this time I cannot because I am busy with more urgent FIxes..

thank you for your cooperation and dedication, we appreciate it.

**Comment by eTzmNcbkrng** [comment]
No rush, it's understandably low priority.

**Comment by Yehonal** [comment]
It's just a hypothesis but there could be some difference in the way an item is stored into the database when it's rewarded by a quest or by using the command.

For instance: when you add it by the gm command that string is not sanitized/normalized therefore the HTML is stored in a "raw" way, hence correctly displayed. Meanwhile, the core runs certain string normalization when the item is rewarded by a quest.

We can take a look at the difference between these 2 methods to understand what happens. But definitely, it's something to report on AC asap.

Thanks for the feedback
