### ISSUE TITLE
Mobs using Thrash melee swinging from any range

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#3021]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Due to recent fix related to Thrash, many creatures now cast the Thrash spell 3391 directly instead of applying aura that grants them a chance on melee hit to proc Thrash. This causes them to do two melee hits from any range every few seconds.

### Expected Blizzlike Behaviour

Thrash should only occur as a proc on melee swings, not as a direct cast. (see spells like 3417, 8876)

### Source

https://wowwiki-archive.fandom.com/wiki/Thrash

### Steps to reproduce the problem

Pull a creature that uses Thrash and build some distance (,mod speed 3), for example Riverpaw Outrunner in Elwynn Forest (npc id 478) and observe in combat log how you receive melee outside melee range.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
@Jpizzle31, you said that this ticket is associated with the issue of https://github.com/chromiecraft/chromiecraft/issues/3119.

Does that mean you expect both ticket to be solved by the same fix?

**Comment by ishidinho** [comment]
Hey @godnesso. Thank you for the report.

There is already a fix https://github.com/azerothcore/azerothcore-wotlk/pull/9746 in the pipeline that solves this issue by removing Thrash from the NPCs ability list.
