### ISSUE TITLE
[Achievements] Script for Feats of Strength related to already unlocked legacy PvP titles is not working properly and consistently

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#3022]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

With recent re-enabling Feats of Strength achievements for legacy PvP titles, it has been observed that script for rewarding them to eligible players works inconsistently and improperly.

Observed inconsistency:
- only selected at random players receive appropriate achievement for the PvP title, they have already unlocked; relogging to the game multiple times and in random circumstances + clearing cache seem to not affecting the work of the script; changing titles or increasing own Honorable Kills counter also do not resolve the issue of missing achievement.

Observed impropriety:
- it seems like script is only giving achievement for the highest PvP title the player has already unlocked, instead of rewarding achievements per each unlocked title.

### Expected Blizzlike Behaviour

Players who already have unlocked any legacy PvP title should be rewarded retroactively with appropriate Feats of Strength achievement for that title.
Having unlocked more than one title should mark player to be eligible for receiving the according number of Feats of Strength achievements.

### Steps to reproduce the problem

1. Prepare a character with already unlocked one or more legacy PvP titles
2. Try to reloging, earning Honorable Kills, changing the titles and clearing content of cache folder in World of Warcraft installation directory to see if FoS achievement is earned

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Thank you for the report, @Hihilist. 

I linked the issue to the [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles) repository.

**Comment by sudlud** [comment]
this should be fixed with azerothcore/azerothcore-wotlk#17180

The feats of strength achievements should now always be granted correctly when the pvp title is beeing granted.

But it is important to mention that after updating with the patch mentioned above, the achievements for EXISTING titles will only be granted after either:
- the player receives ANY new title
- .achievevement checkall
