### ISSUE TITLE
PvP gear wont get the corresponding pieces after faction change

### ISSUE THREAD

**Issue by oterfesk** [chromiecraft/chromiecraft#3023]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

PvP gear didnt get the corresponding pieces when i transfered from Horde to Alliance. I imagine it is the same vice versa also

Legionnaire's Silk Robes and Champion's Silk Shoulderpads stayed the same 

### Expected Blizzlike Behaviour

Legionnaire's Silk Robes should be converted to Knight-Captain's SIlk Raiment
and Champion's Silk Shoulderpads should be converted to Lieutenant Commander's Silk Spaulders

### Source

![image](https://user-images.githubusercontent.com/84633953/153594158-1fc43a86-ab35-49c1-9ad1-513c13327a42.png)
![image](https://user-images.githubusercontent.com/84633953/153594187-022327cb-018a-48a3-9c2f-c1c0d4abd0e9.png)

### Steps to reproduce the problem

1. Buy PvP Pieces as Horde
2. Transfer to Alliance through ChromieCraft cashshop

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment]
The gear that doesn't change over is the level 58 Blue gear.  I have the entire set and i can't use any of it But i only have the level 60 legs and those worked.
