### ISSUE TITLE
[The Exodar] Seer Skaltesh doesn't give you Elemental Sapta.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#3024]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When you talk to him nothing happens.

https://user-images.githubusercontent.com/91145640/153645852-9b04195e-d115-4169-85b0-553b526bdfdf.mp4

### Expected Blizzlike Behaviour

He should give you one Elemental Sapta.

### Source

https://tbc.wowhead.com/npc=18985/seer-skaltesh#comments
https://wowpedia.fandom.com/wiki/Seer_Skaltesh
https://tbc.wowhead.com/item=27317/elemental-sapta

### Steps to reproduce the problem

1. Talk to Seer Skaltesh.

GUID:
DB GUID: 84094, current GUID: 2500.
Current Entry: 18985 of (18985, 0, 0).
DisplayID: 18418 (Native: 18418).
Faction: 1638.
npcFlags: 1.
Level: 60.
EquipmentId: 0 (Original: 0).
Health (base): 3484. (max): 3484. (current): 3484.
Unit Flags: 32768.
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 1638.
SpawnTime: Full:5m Remain:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 3025
Position: -3836.510010 -11479.000000 -138.694000.
AIName:  ScriptName: 
* has gossip (1)
MechanicImmuneMask: 0
SpellSchoolImmuneMask: 0

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ZhengPeiRu21** [comment]
Thank you for the report! I have created PR to fix this issue.
