### ISSUE TITLE
[The Exodar] Wrong text when talking to the Tailoring Trainer.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#3025]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When you talk to Refik it says:

![imagen](https://user-images.githubusercontent.com/91145640/153648060-766aef19-efb7-4317-9bc6-d8587799a1a8.png)

That doesn't make any sense because it's not the profession of my character.

### Expected Blizzlike Behaviour

I might be wrong but I believe it should say: "I can instruct you in tailoring. Interested?" as do the other trainers in The Exodar.

### Source

https://www.wow-freakz.com/npc_finder.php?npc=16729

### Steps to reproduce the problem

GUID: 
DB GUID: 57711, current GUID: 2253.
Current Entry: 16729 of (16729, 0, 0).
DisplayID: 17507 (Native: 17507).
Faction: 1638.
npcFlags: 81.
Level: 30.
EquipmentId: 0 (Original: 0).
Health (base): 811. (max): 811. (current): 811.
Unit Flags: 512.
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 1638.
SpawnTime: Full:5m Remain:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 1178
Position: -4095.780029 -11747.000000 -139.578003.
AIName:  ScriptName: 
* has gossip (1)
* is trainer (16)
* is profession trainer(64)
MechanicImmuneMask: 0
SpellSchoolImmuneMask: 0

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @FTGCocolandia. Thank you for the report, but we need clear evidence for the correct gossip. I was not able to find any source for that.

**Comment by Kosiak** [comment]
https://wowpedia.fandom.com/wiki/Refik this should only be displayed when skill is too high. Some info online says when over 200. But gossips so hard to track and it's really annoying.

**Comment by heyitsbench** [comment]
[Here is what he says with no tailoring trained at all.](https://github.com/chromiecraft/chromiecraft/assets/38561765/78348e01-bef6-4cfa-8c18-d2771ed81f18)

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
