### ISSUE TITLE
Glyph of Rejuvenation are nerfed for a second time after the source heal is already affected by said nerf

### ISSUE THREAD

**Issue by Santaria94** [chromiecraft/chromiecraft#3027]
### What client do you play on?

ruRU

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Recently this change was made to some healing spells: 'Nyeriah: - Beacon of Light, Swiftmend and Ancestral Awakening should no longer be affected by the healing nerf, because the source of their healing is already affected'.

This problem is still present for the Glyph of Rejuvenation. It works as a standalone spell when the target's health is less than 50%. Healing depends on the main Rejuvenation and should not be nerfed

### Expected Blizzlike Behaviour

Healing depends on the main Rejuvenation and should not be nerfed

### Steps to reproduce the problem

1. Be a druid with the Glyph of Rejuvenation
2. .tele MC
3. Use Rejuvenation and check healing from the glyph. Your HP must be below 50%

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by fendwe** [comment]
Can confirm this on PTR.
[Glyph of Rejuvenation](https://wowgaming.altervista.org/aowow/?item=40913) -> Should heal 70, but is 35.
![WoWScrnShot_032322_205125](https://user-images.githubusercontent.com/61170874/159784213-48948480-25cd-4f8d-9cc6-a248c2037e94.jpg)

As shown in the screenshot, [Swiftmend ](https://wowgaming.altervista.org/aowow/?spell=18562) is working properly (amount equal to 4 Rejuvenation ticks).
The same is true for [Ancestral Awakening](https://wowgaming.altervista.org/aowow/?spell=51558) (30% of amount healed).
![WoWScrnShot_032322_202929](https://user-images.githubusercontent.com/61170874/159785148-cc28758a-d613-4049-abee-d992c907e7e4.jpg)

**Comment by Nyeriah** [comment]
Hey,

The issue with glyph of rejuvenation/swiftmend is that they're calculated based on the **total healing** output of the spell, we never nerf that value, we only nerf the ticks, so the nerf is correct to me as it is, no double dip.

Regards
