### ISSUE TITLE
[Summary Report]: Vmaps/Mmaps/Pathfinding (or LOS event in general)

### ISSUE THREAD

**Issue by Stifler82** [chromiecraft/chromiecraft#303]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ x] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

**Since there are different Reports that all converge on the same problem, I am opening a (UNIQUE) Report.
Where I will link all related issues and close the others.
This is because when we fix the "Main" problem all of these reported problems will "Auto-Fix" themselves.**

##### EXPECTED BLIZZLIKE BEHAVIOUR:

**Vmaps/Mmaps/Pathfinding(or LOS event in general) System should work fine and not have all these side problems.**

##### STEPS TO REPRODUCE THE PROBLEM:

1. Null
2. Null
3. Null
4. Null

##### EXTRA NOTES:

Linked Issues: https://github.com/chromiecraft/chromiecraft/issues?q=label%3AVmaps%2FMmaps%2FPathfinding+

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Didn't triage, came in through support discord channel  https://github.com/chromiecraft/chromiecraft/issues/1263

**Comment by FrancescoBorzi** [comment]
I guess we can close this, the original author is no longer around

**Comment by temperrr** [comment]
Ok. ~Closed

**Comment by JamesHoffer** [comment]
You closed it, but the path finding and NPC LOS mechanics are all messed up from level 1 all the way through the entire leveling process. Does Chromiecraft use MMaps?

**Comment by FrancescoBorzi** [comment]
> You closed it, but the path finding and NPC LOS mechanics are all messed up from level 1 all the way through the entire leveling process. Does Chromiecraft use MMaps?

@JamesHoffer please open a new report per every specific issue and we'll do our best to fix it

cc @Yehonal @UltraNix

**Comment by UltraNix** [comment]
@JamesHoffer More details and info.
