### ISSUE TITLE
Insignia of the Horde can't buy as Horde Paladin 

### ISSUE THREAD

**Issue by miky1093** [chromiecraft/chromiecraft#304]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Insignia of the Horde doesn't show up at the correct NPC Brave Stonehide in OG, but i bought in another account with a priest alt, i tried to disable all addons and sort of, but nothing changes.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Insignia of the Horde possible to buy at Brave Stonehide in OG

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go og
2.  talk to Brave Stonehide in pvp hall
3. go 2nd page
4. buy trinket

##### EXTRA NOTES:

Nothing else

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
Works on stock AC so I guess it fell victim to the vendor pruning on CC.

**Comment by FrancescoBorzi** [comment]
thanks @necropola 

can anyone reproduce this issue?

**Comment by necropola** [comment]
@FrancescoBorzi I think that @55Honey already checked and it looks like the Horde Paladin version of the trinket (29592) has been accidently removed on CC (when pruning the honor vendors). She's on it and there is obviously no need to copy this issue to AC since it only affects CC.

**Comment by FrancescoBorzi** [comment]
@Stifler82 is there an AC issue?

**Comment by Stifler82** [comment]
> @Stifler82 is there an AC issue?

no

**Comment by FrancescoBorzi** [comment]
ah right, this was a chromie-only issue, I got confused

**Comment by miky1093** [comment]
fixed, thanks. 
Lanathel
