### ISSUE TITLE
Hit rating for pvp on lvl 60

### ISSUE THREAD

**Issue by Steelcold** [chromiecraft/chromiecraft#3042]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

I play priest and I keep missing my spells now and then when pvping. I've got [Flashlight ](https://wowgaming.altervista.org/aowow/?item=45631) and [Diana's Pearl Necklace](https://wowgaming.altervista.org/aowow/?item=22403) equipped and [got precisely 4% hit. ](https://imgur.com/a/p3CMWFs)

I ran some tests on a level 60 dummy, but no misses were observed.
Though, during BGs, I often keep missing my SW:P, dispels and other spells as well.

I'd be glad if someone could explain how hit rating is working and how much rating I need atm.

### Expected Blizzlike Behaviour

I'm not good at WoW theorycraft, but I know that you need 4% hit rating for pvp in order not to miss spells. 
["Base chance to hit is based on level difference between caster and target, starting at 96% for equal levels, and going up or down from there, capping at a maximum 100%".
](https://wowwiki-archive.fandom.com/wiki/Spell_hit#Calculation)

I also stumbled upon [this article](https://wowwiki-archive.fandom.com/wiki/Hit#Hit_rating_cap) saying that Hit Rating Required Per 1% on Level 60	is 9.38 which means I need 37.52 hit rating (not 32 as of now) to be capped.

### Source

1. https://wowwiki-archive.fandom.com/wiki/Portal:Main
2. https://wowgaming.altervista.org/aowow/

### Steps to reproduce the problem

1. Сheck the links above
2. Explain how much rating is needed in order not to miss spells for pvp? :)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Steelcold. Thank you for the report.
I see no valid problem here. In my eyes, everythign works as expected.

But let me explain.

First of all, there is a difference in [Hit Rating](https://wowwiki-archive.fandom.com/wiki/Hit#Hit_rating_cap) and [Spell Hit Rating](https://wowwiki-archive.fandom.com/wiki/Spell_hit#Hit_rating_chart).

> 8.00 hit rating per 1% spell hit at level 60
(source: https://wowwiki-archive.fandom.com/wiki/Spell_hit)

Why can your spells still be resisted?

> Spell resistance was the second of two rolls to determine whether or not a spell was resisted. ([Spell hit](https://wowwiki-archive.fandom.com/wiki/Spell_hit) was the first roll.)
(source: https://wowwiki-archive.fandom.com/wiki/Resistance)

Furthermore, just a tip, you can skill Spell Hit in your Shadow talent tree, making Spell Hit on gear nearly not needed in PvP.

**Comment by Steelcold** [comment]
@ishidinho thanks. Just to make it clear. If blood elves have got Magic Resistance reducing their chance to be hit by spells by 2%, it means that I, having 4% spell hit, have a 2% chance to miss anyway? I'm asking because I think this happened to me when I was fighting a blood elf.

I'm playing disc atm so no shadow tree talents :) Thanks for the answers anyway!

**Comment by ishidinho** [comment]
@Steelcold Yes. This is also mentioned in the Resistance Wiki page I linked. ;)
