### ISSUE TITLE
Lock and Load doesn't proc with Black Arrow / Immolation Trap / Explosive Trap

### ISSUE THREAD

**Issue by dumikachromiecraft** [chromiecraft/chromiecraft#3043]
I have spent around 20 minute trying to get a proc of Lock and Load from the spells mentioned in the title, but I had no luck. It has a 6% proc rate according to talents:

![image](https://user-images.githubusercontent.com/36760053/153835663-cd2f7418-7475-411a-9df5-e8dd5f664642.png)

I tested it on the training dummies in Orgrimmar. Proc works perfectly with Freeze and Frost Traps.

**Comment by ishidinho** [comment]
Hey @dumikachromiecraft. Thank you for the report.

Please do never open blank issues. Use the [template](https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&template=bug_report.yml). We need this for our work.

**Comment by dumikachromiecraft** [comment]
Hi

Reopened another ticket, sorry.

**Comment by ishidinho** [comment]
Reopened: https://github.com/chromiecraft/chromiecraft/issues/3044
