### ISSUE TITLE
Tough Love event - Some players not receiving Heart Shaped Loot Boxes

### ISSUE THREAD

**Issue by RestoCC** [chromiecraft/chromiecraft#3045]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

![WoWScrnShot_021422_174551](https://user-images.githubusercontent.com/97218609/153846140-74b5e5ed-4554-4ca5-97eb-b2f15a020281.jpg)
![WoWScrnShot_021422_174554](https://user-images.githubusercontent.com/97218609/153846151-3b35d0d2-e44d-4c5a-b058-14751f30f7ec.jpg)

Upon finishing the Tough Love Holiday event for the first time of the day- some players (myself included) are not receiving their loot box.

This has happened on both days of the reset since the event went live and on 2 of my characters.

### Expected Blizzlike Behaviour

Every player receives 1 loot box per daily with a chance at goodies including a super rare mount. You are always guranteed a box assuming it is the first event of the daily.

https://www.wowhead.com/achievement=4624/tough-love#comments

https://www.youtube.com/watch?v=l2Dgt_q7Uls&ab_channel=WoWJNasty

### Source

His drops are epic ilvl 226 items, identical copies of badge gear, just like Coren Direbrew dropped:
Heartbreak Charm ->> [Evoker's Charm](https://www.wowhead.com/?item=45822).
Choker of the Pure Heart ->> [Spiked Battleguard Choker](https://www.wowhead.com/?item=45819)
He also drops some rare blue items (not every time):
[Toxic Wasteling](https://www.wowhead.com/?spell=71840) (an Oozeling pet).
Forever-Lovely Rose, a head slot item that makes you hold a rose in your mouth.
And a teeny-tiny chance to drop the Pink Rocket mount, just like the coveted Direbrew Ram/Kodo or the Headless Horseman's Reins.

Patch 3.3.2

### Steps to reproduce the problem

Queue with a group of 5 60s
Defeat the encounter
Check if all 5 players received a box - in all my groups 4/5 received theirs, not sure if coincidence or not?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by j-hdt** [comment]
did 3 kills in 3 consecutive days on 2 chars and everytime received a box. Also dead players received it in the kills so far.

**Comment by temperrr** [comment]
Should've been fixed during the event.
