### ISSUE TITLE
Guild Bank Tab Disappeared

### ISSUE THREAD

**Issue by ThunderAleBrewingCo** [chromiecraft/chromiecraft#3046]
Player Name: Nevertwenty (guildmaster)
Guild Name: Never Twenty

Yesterday I spent 100g on the first guild bank tab and put 4-5 low-level items (twink guild) in the bank along with 5-6 gold. Today I logged-in and the bank tab is gone and has been replaced with the, "Do you want to buy a guild bank tab? 100g" notice.

I'm not worried about the 100g or the items lost with the tab. I just don't want to spend another 100g and have it happen again.

**Comment by leroythered** [comment]
Same issue here.  Guild Name: Honour and Glory

**Comment by acidmanifesto** [comment]
Please fill out the form propperly so we can access the issue propperly.
