### ISSUE TITLE
Call of water - Draenei Shaman lvl 20 quest

### ISSUE THREAD

**Issue by damik1134** [chromiecraft/chromiecraft#3049]
I am having issues completing this [quest](https://tbc.wowhead.com/quest=9508/call-of-water). When I summon the spirits, they do nothing. In addition Tel'athion, the mob I need to kill, start casting a spell after the other and I can't do nothing but heal myself and it's not enough. Also, he is always 100% on mana.

Is it a bug or I am doing something wrong?

Thanks in advance,
Damik

**Comment by ishidinho** [comment]
Thank you @damik1134 for using the form.

Closed https://github.com/chromiecraft/chromiecraft/issues/3052.
