### ISSUE TITLE
Molten Core - Gehennas loot table adjustment

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#3063]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Gehennas in Molten Core has a loot table that differs from the retail version.
Pieces of gear can drop in combinations that would be impossible in the retail version (an example of such impossible combination would be Gloves of Prophecy and Nightslayer Gloves).

### Expected Blizzlike Behaviour

When reviewing videos of boss kills from both current WoW Classic and old WotLK, you can make the observation that the loot from Gehennas appears to be separated into two different groups, as seen below:
![gehennas](https://user-images.githubusercontent.com/65633456/154192909-3bd9b711-009f-4d5b-8ee9-0f3ee2edc671.JPG)
Shared Loot (Flamewakers) refers to the shared pieces of gear that can drop from all 4 Flamewaker bosses (Lucifron, Gehennas, Shazzrah and Sulfuron Harbinger), such as Sorcerous Dagger.
Gehennas drops two pieces of gear, one chosen from each group.
It appears to be impossible that loot from one group will be seen twice (e.g. you will never see Sabatons of Might and Giantstalker's Boots simultaneously).
While it is impossible to know the exact numbers, the chances for loot to drop in G1 appear to be roughly equal, while in G2 there appears to be a higher chance for shared items.
There appear to be no differences between Classic and WotLK in how the loot tables are set up, aside from the fact that Horde players are now able to see Paladin armor and Alliance Shaman armor.
I propose that drop rates in G1 should be equal (25% each). In G2, there should be a 25% for Sabatons of Might, 25% for Giantstalker's Boots and 50% for a shared item.

### Source

https://classic.wowhead.com/npc=12259/gehennas
https://www.wowhead.com/npc=12259/gehennas

I am currently searching through videos and gathering data.
classic
https://www.youtube.com/watch?v=DXGNkNwtOVg
https://www.youtube.com/watch?v=E7_yKr6vZxU (no garr, domo, rag)
https://www.youtube.com/watch?v=gG_FA0Towjw (no domo, rag)
https://www.youtube.com/watch?v=21UVptdxQsI (no domo)
https://www.youtube.com/watch?v=U1ACQN0wXe0 (no harbinger)
https://www.youtube.com/watch?v=ub7O-Aj48wk
https://www.youtube.com/watch?v=gn6WBh-F2ak (only magmadar, geddon, shazz, golemagg, rag)
https://www.youtube.com/watch?v=UEY86N7h0Gk (no gehennas, garr, geddon, domo)
https://www.youtube.com/watch?v=cU4u_IUn99s (only magmadar, rag)
https://www.youtube.com/watch?v=dQjTibN6UKs

wotlk
https://www.youtube.com/watch?v=DPeBsf72PAI (luci to garr)
https://www.youtube.com/watch?v=UElS1NoKhGY (geddon to domo)
https://www.youtube.com/watch?v=ecCXHeGZZWU (gehennas only)
https://www.youtube.com/watch?v=BtlMC3F_gKA (shazzrah only)
https://www.youtube.com/watch?v=HSNj7cajXac (garr only)
https://www.youtube.com/watch?v=g1ceI12e57o (luci to garr)
https://www.youtube.com/watch?v=_BOL1lJqVJI (geddon to golemagg)
https://www.youtube.com/watch?v=9N1pArEunJU (no domo, only rag)
https://www.youtube.com/watch?v=F5NW-MYFY6E (geddon only)
https://www.youtube.com/watch?v=Q7kX_nbDXE0 (golemagg only)
https://www.youtube.com/watch?v=b-i8hUjec3s (domo only)
https://www.youtube.com/watch?v=VCJ18ifbzhE (geddon only)
https://www.youtube.com/watch?v=JsTHCEnunwY (luci only)
https://www.youtube.com/watch?v=ruYKnBBsAFw (gehennas only)
https://www.youtube.com/watch?v=E9N-alMy9l0 (only rag)
https://www.youtube.com/watch?v=j8eJ_DEUPHM (luci and mag)
https://www.youtube.com/watch?v=u7DAUBeBJh4 (luci to geddon)
https://www.youtube.com/watch?v=SJWGA_dReMc (shazz to rag) (domo trash can drop boes) (same t2)
https://www.youtube.com/watch?v=LQ03Uf58TcE (only shazz)
https://www.youtube.com/watch?v=tA295C48TPw (only luci) (attune without quest) (corehound not skinnable)
https://www.youtube.com/watch?v=3kw5xF8wozc (mag to geddon)
https://www.youtube.com/watch?v=DxLGP9tWGWA (shazz to harbinger)
https://www.youtube.com/watch?v=LifbskEXzVY (golemagg to domo)
https://www.youtube.com/watch?v=zEMEc3USCqs (rag) (weapon drop)
https://www.youtube.com/watch?v=rtMHUArs_mk (gehennas, garr)

### Steps to reproduce the problem

.tele mc
Go to Gehennas and kill repeatedly.

### Extra Notes

Molten Core bosses have very unique loot tables, most certainly because of the many additions and changes to the loot done.

https://wowgaming.altervista.org/aowow/?npc=12118

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by KarazhanSucks** [comment]
http://forums.elitistjerks.com/topic/16858-thesis-how-the-loot-tables-work/ (dead link)

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

Gehennas
https://classic.wowhead.com/npc=12259/gehennas

Pool A --- Chance 1
16812 "Gloves of Prophecy"
16826 "Nightslayer Gloves"
16839 "Earthfury Gauntlets" *H*
16860 "Lawbringer Gauntlets" *A*

Pool B1 --- Chance 0.5
16862 "Sabatons of Might"
16849 "Giantstalker's Boots"
Pool B2 --- Chance 0.5 (1-B1)
Shared Gehennas/Magmadar/Lucifron/Garr/BaronGeddon/Shazzrah/SulfuronHarbinger/GolemaggtheIncinerator
18861 "Flamewaker Legplates"
Shared Gehennas/Lucifron/Shazzrah/SulfuronHarbinger
19147 "Ring of Spell Power"
18875 "Salamander Scale Pants"
19146 "Wristguards of Stability"
18870 "Helm of the Lifegiver"
18878 "Sorcerous Dagger"
17077 "Crimson Shocker"
18879 "Heavy Dark Iron Ring"
18872 "Manastorm Leggings"
Shared Gehennas/Lucifron/SulfuronHarbinger
19145 "Robe of Volatile Power"

Recipe Pool --- Chance 0.1
18252 "Pattern: Core Armor Kit"
18265 "Pattern: Flarecore Wraps"
18264 "Plans: Elemental Sharpening Stone"
18257 "Recipe: Major Rejuvenation Potion"
18290 "Schematic: Biznicks 247x128 Accurascope"
18291 "Schematic: Force Reactive Disk"
18259 "Formula: Enchant Weapon - Spell Power"
21371 "Pattern: Core Felcloth Bag"
18292 "Schematic: Core Marksman Rifle"
18260 "Formula: Enchant Weapon - Healing Power"
