### ISSUE TITLE
Molten Core - Garr loot table adjustment

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#3064]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Garr in Molten Core has a loot table that differs from the retail version.
Pieces of gear can drop in combinations that would be impossible in the retail version (an example of such impossible combination would be Cenarion Helm, Arcanist Crown and Drillborer Disk).
Loot that drops only from Garr, such as Aurastone Hammer, drops less frequently than intended.

### Expected Blizzlike Behaviour

When reviewing videos of boss kills from both current WoW Classic and old WotLK, you can make the observation that the loot from Garr appears to be separated into three different groups, as seen below:
![garr](https://user-images.githubusercontent.com/65633456/154197677-49b818f5-6405-4b5b-ab55-c15e900f87e7.JPG)
Shared Loot (Fire Creatures) refers to the shared pieces of gear that can drop from all 4 Fire creature bosses (Magmadar, Garr, Geddon, Golemagg), such as Mana Igniting Cord.
Garr drops three pieces of gear, one chosen from each group.
It appears to be impossible that loot from one group will be seen twice (e.g. you will never see Cenarion Helm and Giantstalker's Helmet simultaneously).
While it is impossible to know the exact numbers, the chances for loot to drop appear to be roughly equal in G1 and G2, while unique items in G3 appear to have the same chance to drop as items in G1 and G2.
There appear to be no differences between Classic and WotLK in how the loot tables are set up, aside from the fact that Horde players are now able to see Paladin armor and Alliance Shaman armor.
I propose that drop rates in G1 and G2 should be equal (16,67% and 20% respectively). Drop rates in G3 should be 20% for Aurastone Hammer, 20% for Brutality Blade and 60% for one of the shared items.

### Source

https://classic.wowhead.com/npc=12057/garr
https://www.wowhead.com/npc=12057/garr

I am currently searching through videos and gathering data.
classic
https://www.youtube.com/watch?v=DXGNkNwtOVg
https://www.youtube.com/watch?v=E7_yKr6vZxU (no garr, domo, rag)
https://www.youtube.com/watch?v=gG_FA0Towjw (no domo, rag)
https://www.youtube.com/watch?v=21UVptdxQsI (no domo)
https://www.youtube.com/watch?v=U1ACQN0wXe0 (no harbinger)
https://www.youtube.com/watch?v=ub7O-Aj48wk
https://www.youtube.com/watch?v=gn6WBh-F2ak (only magmadar, geddon, shazz, golemagg, rag)
https://www.youtube.com/watch?v=UEY86N7h0Gk (no gehennas, garr, geddon, domo)
https://www.youtube.com/watch?v=cU4u_IUn99s (only magmadar, rag)
https://www.youtube.com/watch?v=dQjTibN6UKs

wotlk
https://www.youtube.com/watch?v=DPeBsf72PAI (luci to garr)
https://www.youtube.com/watch?v=UElS1NoKhGY (geddon to domo)
https://www.youtube.com/watch?v=ecCXHeGZZWU (gehennas only)
https://www.youtube.com/watch?v=BtlMC3F_gKA (shazzrah only)
https://www.youtube.com/watch?v=HSNj7cajXac (garr only)
https://www.youtube.com/watch?v=g1ceI12e57o (luci to garr)
https://www.youtube.com/watch?v=_BOL1lJqVJI (geddon to golemagg)
https://www.youtube.com/watch?v=9N1pArEunJU (no domo, only rag)
https://www.youtube.com/watch?v=F5NW-MYFY6E (geddon only)
https://www.youtube.com/watch?v=Q7kX_nbDXE0 (golemagg only)
https://www.youtube.com/watch?v=b-i8hUjec3s (domo only)
https://www.youtube.com/watch?v=VCJ18ifbzhE (geddon only)
https://www.youtube.com/watch?v=JsTHCEnunwY (luci only)
https://www.youtube.com/watch?v=ruYKnBBsAFw (gehennas only)
https://www.youtube.com/watch?v=E9N-alMy9l0 (only rag)
https://www.youtube.com/watch?v=j8eJ_DEUPHM (luci and mag)
https://www.youtube.com/watch?v=u7DAUBeBJh4 (luci to geddon)
https://www.youtube.com/watch?v=SJWGA_dReMc (shazz to rag) (domo trash can drop boes) (same t2)
https://www.youtube.com/watch?v=LQ03Uf58TcE (only shazz)
https://www.youtube.com/watch?v=tA295C48TPw (only luci) (attune without quest) (corehound not skinnable)
https://www.youtube.com/watch?v=3kw5xF8wozc (mag to geddon)
https://www.youtube.com/watch?v=DxLGP9tWGWA (shazz to harbinger)
https://www.youtube.com/watch?v=LifbskEXzVY (golemagg to domo)
https://www.youtube.com/watch?v=zEMEc3USCqs (rag) (weapon drop)
https://www.youtube.com/watch?v=rtMHUArs_mk (gehennas, garr)

### Steps to reproduce the problem

.tele mc
Go to Garr and kill repeatedly.

### Extra Notes

Molten Core bosses have very unique loot tables, most certainly because of the many additions and changes to the loot done.

https://wowgaming.altervista.org/aowow/?npc=12057

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by KarazhanSucks** [comment]
http://forums.elitistjerks.com/topic/16858-thesis-how-the-loot-tables-work/ (dead link)

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

Garr
https://classic.wowhead.com/npc=12057/garr

Pool A --- Chance 1
17066 "Drillborer Disk"
16834 "Cenarion Helm"
16866 "Helm of Might"
16821 "Nightslayer Cover"
16854 "Lawbringer Helm" *A*
16842 "Earthfury Helmet" *H*
16846 "Giantstalker's Helmet"

Pool B --- Chance 1
17071 "Gutgore Ripper"
16808 "Felheart Horns"
16813 "Circlet of Prophecy"
16795 "Arcanist Crown"

Pool C1 --- Chance 0.4
18832 "Brutality Blade"
17105 "Aurastone Hammer"
Pool C2 --- Chance 0.6 (1-C1)
Shared Gehennas/Magmadar/Lucifron/Garr/BaronGeddon/Shazzrah/SulfuronHarbinger/GolemaggtheIncinerator
18861 "Flamewaker Legplates" 1x
Shared Magmadar/Garr/BaronGeddon/GolemaggtheIncinerator
18823 "Aged Core Leather Gloves" 2x
19143 "Flameguard Gauntlets" 2x
19136 "Mana Igniting Cord" 2x
18821 "Quick Strike Ring" 2x
18820 "Talisman of Ephemeral Power" 2x
19142 "Fire Runed Grimoire" 2x
18822 "Obsidian Edged Blade" 2x
18829 "Deep Earth Spaulders" 1x
18824 "Magma Tempered Boots" 1x
19144 "Sabatons of the Flamewalker" 1x
