### ISSUE TITLE
[Dustwallow Marsh] Theramore Guards give the location of Elder Bronzebeard.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#3066]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Interacting with Theramore Guards for the quest "Discrediting the Deserters" will flash the dialog of the Elders when asked the location of Elder Bronzebeard.

https://user-images.githubusercontent.com/91145640/154249357-5a3ef265-5dda-42d1-84fa-b54a818b1fd4.mp4

Screenshot:

![imagen](https://user-images.githubusercontent.com/91145640/154249819-e83d57be-87d6-4f3f-ac41-b6cbb4fe13e1.png)

### Expected Blizzlike Behaviour

The interaction tab should be closed, no changes in text.

The text displayed is the one that appears when interacting with an Elder during the Lunar Festival event.

### Steps to reproduce the problem

1. Accept the quest "Discrediting the Deserters" https://wowgaming.altervista.org/aowow/?quest=11133
2. Talk to a Theramore Guard. 

I have to add that some guards don't have this error.

GUID of video example:

DB GUID: 30635, current GUID: 7943.
Current Entry: 4979 of (4979, 0, 0).
DisplayID: 2978 (Native: 2978).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @FTGCocolandia. Thank you for the report.

As you can see, a fix is already incoming.
