### ISSUE TITLE
Lv11 Mage Quest: Control is bugged

### ISSUE THREAD

**Issue by Rittmeister39** [chromiecraft/chromiecraft#307]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

already killed like 50-70 Morlocs, Magewraith does not spawn!
also, every damn Morloc drops the same lv35 Blacksmithing recipe, so annoying.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Magewraith should spawn way more often when people have the Mage quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. lv11 mage quest giver. https://www.wowhead.com/quest=9595/control
![WoWScrnShot_032721_202847](https://user-images.githubusercontent.com/78271326/112732744-1353c980-8f3c-11eb-9177-426489e1eeb0.jpg)

2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Rittmeister39** [comment]
![WoWScrnShot_032821_105841](https://user-images.githubusercontent.com/78271326/112747307-d0820800-8fb4-11eb-9fc8-3f856f1a4fe8.jpg)

I went back today to try my luck and check if it's really a bug or just a rare spawn...
killed lots of Murlocs, and then I saw this Mage guy walking around in the green instead of the beach. Maybe that's how it's intended after all and I just assumed he would spawn on the beach in place of a dead Murloc.
guess you can close the ticket. thanks.

**Comment by FrancescoBorzi** [comment]
thanks for letting us know @Rittmeister39
