### ISSUE TITLE
Rallying Cry of the Dragonslayer

### ISSUE THREAD

**Issue by Hyperbearr** [chromiecraft/chromiecraft#3073]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Upon handing in the Head of Onyxia for the final step that grants the trinket/neck/ring, the head doesn't appear above Major Mattingly, he doesn't perform his RP/yell and he doesn't drop Rallying Cry of the Dragon Slayer on players in Stormwind.

Our guild mate also relayed that his buff didn't occur on horde side either. 

### Expected Blizzlike Behaviour

He should yell out his flavour text.
The head should be mounted in the arch. 
Players should receive Rallying Cry of the Dragonslayer. 

### Steps to reproduce the problem

Complete head of onyxia quest chain.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nueschts** [comment]
[PTR]
Can confirm on PTR.
No severed Onyxia heads and no dialogs on either Horde or Alliance side.
Same result when handing in the lvl 80 head.

![image](https://user-images.githubusercontent.com/61170874/159169376-bc6a36f5-e114-4162-b84f-39de39f4bb34.png)
![image](https://user-images.githubusercontent.com/61170874/159169613-e07a94c3-5a01-44c9-a731-3da83f30fa2b.png)
