### ISSUE TITLE
[Dustwallow Marsh / Quest: What's Haunting Witch Hill] You don't get progress if a pet kills the NPC's.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#3077]
Azerothcore core issue posted:
https://github.com/azerothcore/azerothcore-wotlk/issues/10784

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

If a pet kills the NPC's you won't get progress in the quest.

https://user-images.githubusercontent.com/91145640/154377801-1a4b31a8-5ef9-49f2-899c-24e4457e4eba.mp4

### Expected Blizzlike Behaviour

This bug also happened in the official servers, you can read how people complained about this in Wowhead.

Now, you should get progress in the quest if you, your pet, or a group member kills the NPC's.

### Source

https://www.wowhead.com/quest=27188/whats-haunting-witch-hill

### Steps to reproduce the problem

1. Accept the quest "What's Haunting Witch Hill?" https://wowgaming.altervista.org/aowow/?quest=11180
2. Last hit the NPC's with your pet. (No progress)
3. Last hit the NPC's yourself. (Progress)

### Extra Notes

Similar to: https://github.com/chromiecraft/chromiecraft/issues/3078

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Closed via above.
