### ISSUE TITLE
Aquatic form aquirable before finishing quest

### ISSUE THREAD

**Issue by matisskeiris** [chromiecraft/chromiecraft#308]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [xx] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

As a Druid At level 16 I recieved [Aquatic Form](https://vanillawowdb.com/?spell=1446) ability and a quest in Moonglade. After reading about the quest series noticed, that the ability should be a reward from this [quest](https://vanillawowdb.com/?quest=31)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As a Druid, I should not be able to aquire [Aquatic Form](https://vanillawowdb.com/?spell=1446) without completing [Aquatic Form](https://vanillawowdb.com/?quest=31) quest

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be a Druid
2. Get level 16
3. Go to Druid Trainer in Thunderbluff
4. Pay to learn Aquatic Form

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
> World of Warcraft: Wrath of the Lich King Patch 3.0.8 (2009-01-20): Aquatic Form is now available from druid trainers at level 16. **Completing the quests is not needed,** but does net some easy experience.

source: https://wowwiki-archive.fandom.com/wiki/Aquatic_Form

**Comment by necropola** [comment]
Invalid issue. That's just how it was changed in WotLK.

**Comment by FrancescoBorzi** [comment]
thanks @mdawx @necropola for your feedback

thanks @matisskeiris for your efforts
