### ISSUE TITLE
[BWL] Mindcontoll Debuff spell on Razorgore not working as inteded.

### ISSUE THREAD

**Issue by lellalex** [chromiecraft/chromiecraft#3085]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When you Loose the Mind controll,  you get a debuff for 60 secound and will not be able to use the Orb again for 60 secounds.

### Expected Blizzlike Behaviour

When you press the orb to start the Mind control you get a debuff for 10secound and will not be able to use the orb for 10 secounds.  Debuff starts when you PRESS the orb.  Not when the Mind control is ending/interuped.

### Source

![image](https://user-images.githubusercontent.com/99510060/154555578-a477387b-6b95-43f0-b6b2-8be60e73cbdf.png)

### Steps to reproduce the problem

.tele bwl
Use the Orb on Razorgore.   First boss in BWL.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by lellalex** [comment]
Wowhead is wrong..... 

https://youtu.be/i5Ot-5eHrD8

**Comment by lellalex** [comment]
![image](https://user-images.githubusercontent.com/99510060/154776042-5b7b40d3-6d04-424a-96b5-296695e5ddb3.png)

**Comment by Gultask** [comment]
Thanks for the report. As Mind Exhaustion being applied when the orb is pressed is already implemented, I'd like to address the claim that the debuff only lasts 10 seconds.
[This video from early Cataclysm shows the debuff lasting 60s](https://www.youtube.com/watch?v=Z7cB5xQoEsI)
[While this video from Mists of Pandaria shows 10s
](https://www.youtube.com/watch?v=UJnJw5rBUSo)And I might be wrong but the icon on the side action bar shows a [Flask of Enhancement](https://wowpedia.fandom.com/wiki/Flask_of_Enhancement), which would mean that your source is also from Cataclysm or later.
