### ISSUE TITLE
[BWL] Razorgore the Untamed Not working as intended.

### ISSUE THREAD

**Issue by lellalex** [chromiecraft/chromiecraft#3086]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

1.  Phase 2 starts before all eggs are broken.

2. Razorgores Cooldown on Conflaguate is to low,  Razorgore can use the spell before the first Conflag is over,  making the tank 100% stunned, Atleast together with his other spell Stun.

3. CD on fireball also have no CD, he "spam" it sometimes. 

4. the two mobs together with Gothek the Controller do not respawn when fight reset.  Nither do he starts controlling Razorgore again as he should  ( Lazergun across the room )

5. PPL who is behind the door when the fight starts also gets into combat with the boss fight.

### Expected Blizzlike Behaviour

1. Phase 2 should starts when all eggs are destroyed.

2. Expects little more CD on spells to actuality make it possible to tank it and hold aggro,  there is Noway atm since ure 100% stunned.

3. need proof how it was back, but now he is using it asoon as he dont use any other spell... suspect.

4. should respawn when combat ends,  Gothek should start "control" razor gore again with the lazer thing across the room.

5. Players behind the closed door should not be in combat.  have done 40man bwl 2000times and there is Always one spectator behind the bars cheering on the rest cuz he was AFK on pull timer ^^   -  trying to find proof.

### Steps to reproduce the problem

1. Engage the first boss in BWL 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
These got all fixed recently. Thanks for your report. Please next time make reports per issue so its easier to confirm or deny.
