### ISSUE TITLE
Onyxia's Lair requires level 60 to enter

### ISSUE THREAD

**Issue by Luckdemon** [chromiecraft/chromiecraft#3088]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

Onyxia's Lair currently requires level 60 to enter.

### Expected Blizzlike Behaviour

It should only require level 50 to enter. (And the amulet)

### Steps to reproduce the problem

1. Attempt entering Onyxia's lair below level 60.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Luckdemon. Thank you for the report.

I can confirm the issue.

> To no surprise it told me I wasn’t a high enough level to enter, but what was surprising was when it said I had to be level 50.
(source: https://us.forums.blizzard.com/en/wow/t/onyxia-at-level-50/317064)

We are now discussing how to handle it, since Onyxia 60 is a custom encounter on WotLK-AC.

**Comment by ishidinho** [comment]
Level 60 Onyxia is a custom encounter that was added for ChromieCrafts progression system.
Since this custom encounter is not part of the `azerothcore-wotlk` project (it is replaced by the level 80 Onyxia), we are not going to fix this issue.

**Comment by heyitsbench** [comment]
Question: Now that CC's progression system has somewhat transitioned to more of a whole emulation of progression rather than a more general gate on content, would a change like this be more in line with the current progression goal?

**Comment by Nyeriah** [comment]
Generally speaking I don’t see an issue with this
