### ISSUE TITLE
Elwynn Forest - Wolves howling constantly

### ISSUE THREAD

**Issue by o-possum** [chromiecraft/chromiecraft#3092]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Every 10-20 seconds the wolf howling sound effect plays. Sometimes more than one at a time. This happens more in on the eastern side of the map. It's very annoying and indicates to new Human players that the server might be buggy.

### Expected Blizzlike Behaviour

I'm not sure how often they actually howl on official servers, but it is far less often. 

### Steps to reproduce the problem

1. Turn on sound
2. Go to Elwynn Forest
3. Follow the road east from Goldshire
4. Listen

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Toniculus** [comment]
Yes can confrim,its on all wolves , once u get into their distance to see them (25-40 yards) they start howling ..... they should start howling in that situation but not everytime  ...atm they overdo it

**Comment by o-possum** [comment]
https://www.youtube.com/watch?v=QKfjJdp8TkM

On my own AzerothCore with no changes I've found that standing around (71, 65) after the server has been up for a while really makes them go nuts. As I type this they are howling worse than in that recording. Sometimes two or three of them at the same time.

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10813
