### ISSUE TITLE
Warlock ritual of doom

### ISSUE THREAD

**Issue by Toniculus** [chromiecraft/chromiecraft#3098]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Ritual of Doom (warlock ability that u get at 60 after a quest chain) it does low dmg to the party memeber when u summon the Doomguard
It should do around 15k shadow dmg to a party member 

### Expected Blizzlike Behaviour

IT should kill the targeted (any class and spec) party member at 60 and kill low hp party members at 70

### Source

https://www.youtube.com/watch?v=_VVokjwR-5w

### Steps to reproduce the problem

Get 4 members and a lock for ritual of doom

### Extra Notes

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

-

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Hello, Toniculus. You are indeed correct about the Classic/Vanilla version of the spell. However, the spell went through some significant changes throughout the end of TBC/WOTLK to be the spell that we are currently familiar with/ are using in WOTLK. 
As you can see in the video I will link below, changes have been highlighted, Doomguard no longer needs to be Enslaved in WOTLK, and summoning no longer kills a player, but deals damage equivalent to your version of Curse of Doom spell, so it depends on how much spell power you have and rank. In the video, the spell did around 3000 damage in the ritual while summoning, considering the players who were summoning were between level 70-80, I would say it is pretty safe to assume this spell does no longer kill 1 summoner, and rather does some trivial damage instead and summons a pre-Enslaved Doomguard.

Source: https://www.youtube.com/watch?v=TyUQnchK3ok
