### ISSUE TITLE
Lazy Peons - Durotar

### ISSUE THREAD

**Issue by bonfax4** [chromiecraft/chromiecraft#31]
##### SMALL DESCRIPTION:
Issues with quest Lazy Peons

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Mobs should eventually reset to their "sleeping state" where you can reuse the item.

##### CURRENT BEHAVIOUR:
After using the quest item the [npc's](https://wotlk.evowow.com/?npc=10556) don't reset to the state where you can use the item again (or they do be but on a really long cooldown timer).At the moment the quest is only doable to the person that does it first, before a server restart I'd assume.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Lazy Peon (10556)
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
Can't confirm. During a quick walk aroung the valley of trials, i've seen peons get up and lay to sleep at least multiple times in just a few minutes. Seems to be working as intended.
