### ISSUE TITLE
[Paladin] Judgement of Light/Wisdom proc stops mana regen.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#3100]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When you attack a target affected by Judgement of Light or Judgement of Wisdom your mana stops regenerating. 

Proc might be considered a cast so if you don't have mana regen while casting you don't get any while the healing (or proc from Judgement of Wisdom) happens.

Judgement of Light:

https://user-images.githubusercontent.com/91145640/154801597-4f442d3a-57d7-4eec-9d99-823e95401c44.mp4

Judgement of Wisdom:

https://user-images.githubusercontent.com/91145640/154801776-e3c2d36e-e527-4d85-bbf2-72f18a8be634.mp4

### Expected Blizzlike Behaviour

Mana regeneration shouldn't stop.

### Steps to reproduce the problem

1. Use Judgement of Light/Wisdom without any MP5.
2. Check mana.

### Extra Notes

Bug found by Omniknight.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by FTGCocolandia** [comment]
I should add that the mana regen. also stops for party/raid members who attack the NPC affected by Judgement of Light/Wisdom.

**Comment by Dejanos** [comment]
Hello, Cocolandia. As you can see when using Judgment of Light on the dummy and hover on mana regen tab, it does say you will be getting 0 mana while casting, well, while JoL is not actually a cast, it is an instant cast, and therefore you will stop getting mana for a few seconds because you casted an instant cast spell, therefore it is working as intended. Also you are getting significantly less mana while in combat or casting any spells due to possibly having any spirit, and human racial passive, lowering our mana regeneration in combat even further. Just tested it on my Holy Paladin and I am indeed certain it works as inteded, as it lowers my mana while casting, even instant cast spells as intended for a few seconds.

**Comment by FTGCocolandia** [comment]
Hi @Dejanos Yeah, the report wasn't about the initial cast, the problem is the proc of the JoL/JoW effect.

Anyway, thank you for confirming it!
