### ISSUE TITLE
[Molten Core] Duke Hydraxis not giving out Eternal Quintessence

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#3109]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

[Duke Hydraxis](https://db.rising-gods.de/?npc=13278) does not give you the [Eternal Quintessence](https://db.rising-gods.de/?item=22754)

### Expected Blizzlike Behaviour

If you did the chain and reached atleast revered with Hydraxian Waterlords, Duke Hydraxis should give you an Eternal Quintessence.

### Steps to reproduce the problem

1. Finish questline up to [https://db.rising-gods.de/?quest=6824](https://db.rising-gods.de/?quest=6824)
2. Get revered reputation with Hydraxian Waterlords
3. Talk with Lord Hydraxian, click the 2nd gossip menu
4. dont receive the item

### Extra Notes

- The gossip menu is available and clickable, but has no effect
- reputation and questline had be done and there was no other (eternal) quintessence in the inventory or bank

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Spook9** [comment]
Can confirm, did not work for me either on 2 different chars both Revered with the waterlords

**Comment by ishidinho** [comment]
Hey @j-hdt and @Spook9.

I am sorry to hear your problems. I got the Essence myself on CC with no problems. In fact, you are the first I hear that from.

Can you provide more detailed information about your characters?
Race?
Class?
Are all quest fromord Hydraxis done? Please compare with this list: https://classic.wowhead.com/npc=13278/duke-hydraxis#starts
Have your characters done a faction change before?

In the meanwhile, I think, you can create ticket in the #support channel on Discord. Maybe a GM can hand out the Essence for you.

**Comment by Spook9** [comment]
> I am sorry to hear your problems. I got the Essence myself on CC with no problems. In fact, you are the first I hear that from.
Several others have gotten the eternal earlier it broke at the time of the post. Not sure if its linked to the disarm issues and mobs losing their weapons with one of the updates or a separate issue.
 
> Can you provide more detailed information about your characters? Race? Class? Are all quest fromord Hydraxis done? Please compare with this list: https://classic.wowhead.com/npc=13278/duke-hydraxis#starts Have your characters done a faction change before?
Human Warrior and Orc Shaman both have done all quests, just above revered and no they have not done faction changes.

> In the meanwhile, I think, you can create ticket in the #support channel on Discord. Maybe a GM can hand out the Essence for you.

It's not that big of a deal for me, ill just wait and when its fixed grab my eternal

**Comment by chickenandtunasalad** [comment]
Have the same issue Night Elf Hunter I have changed fractions.
Revered and quest line done

**Comment by j-hdt** [comment]
> Hey @j-hdt and @Spook9.
> 
> I am sorry to hear your problems. I got the Essence myself on CC with no problems. In fact, you are the first I hear that from.
> 
> Can you provide more detailed information about your characters? Race? Class? Are all quest fromord Hydraxis done? Please compare with this list: https://classic.wowhead.com/npc=13278/duke-hydraxis#starts Have your characters done a faction change before?
> 
> In the meanwhile, I think, you can create ticket in the #support channel on Discord. Maybe a GM can hand out the Essence for you.

try deleting your essence and getting a new one from the duke, you are likely to run into the same issue.

**Comment by heftyjefty** [comment]
I am having the same issue. Orc Rogue, quest line complete, revered. Same exact issue, I click the chat option and nothing happens.

**Comment by j-hdt** [comment]
I suppose there is enough evidence now.

**Comment by fputs** [comment]
I am also experiencing this exact issue. Just hit revered, turned in the hands quest, and now I can't get an eternal essence
![2022-03-13-214551_2560x1440_scrot](https://user-images.githubusercontent.com/88896491/158106628-6b833611-0859-46e2-a52f-4fa416e8662e.png)

**Comment by ishidinho** [comment]
@fputs Just to be sure, you turned the hands quest in AFTER you hit revered?

**Comment by fputs** [comment]
> @fputs Just to be sure, you turned the hands quest in AFTER you hit revered?

Correct. I made sure I hit all the requirements before going to Hydraxis. The steps were:

- Be on hand quest, collect hands while in MC
- Hit revered during the MC run
- Travel to Hydraxis
- Turn in hands quest
- Pick up and turn in reward quest
- Attempt to receive Eternal Quintessence, but fail

I had to have a GM send me one in the mail

**Comment by nJDOA** [comment]
Same Problem here. Got the reputation, but when i click "I desire this eternal quintessence, Duke Hydraxis"... nothing happens.

**Comment by fendwe** [comment]
This seems to be working correctly now.
