### ISSUE TITLE
Issues with the range of Penance and Dispel Magic since Ony release 

### ISSUE THREAD

**Issue by NoodlestheNoble** [chromiecraft/chromiecraft#3110]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The range of the spells Penance and Dispel Magic when used on a friendly target is only 30yd not the 40yd it should be when used on friendly targets. The spell will show as castable but when you try to cast it it brings up the out of range message. I tested this with a friend and other Priest's in my Guild have the same issue. 

### Expected Blizzlike Behaviour

When used on a friendly target Dispel Magic and Penance have a 40yd range, and a 30yd range when used on enemy targets.

### Source

![Screenshot_320](https://user-images.githubusercontent.com/100084970/154863706-d79e15fd-0679-41a6-afad-98b50049f844.png)
![Screenshot_321](https://user-images.githubusercontent.com/100084970/154863713-6cb7c439-a73d-4779-a78a-267900616640.png)

Both are currently only working at 30yd range on a friendly target.

### Steps to reproduce the problem

1. Log a Disc Priest and grab a friend.
2. Position yourself 40yd range from them, note that the Penance spell is not shown as red as though it is out of range.
3. Try to cast Penance.
4. Move to 30yd range, cast again.

Extra: We noticed this (Myself and the other Priests in my Guild) only during the raids we did this weekend AFTER the Ony release, previous to this the spells were both working as intended.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @NoodlestheNoble. Thank you for the report.

We are already aware of the issue. But no worries, you will get you CC points since you posted it first. ;)
