### ISSUE TITLE
Can't talking with Squire Rowe

### ISSUE THREAD

**Issue by lovemelovely** [chromiecraft/chromiecraft#3117]
### What client do you play on?

ruRU

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When i do quest "Stormwind Rendezvous" I Can't talking with Squire Rowe (may be someone is doing the Windsor quest). 
I waiting 30 minute more for return him.

### Expected Blizzlike Behaviour

If someone else is doing the Windsor quest that Squire Rowe starts, you'll get the following text from Rowe:

"Marshal Windsor has been expecting you, <name>. Unfortunately, he is currently indisposed. He should be returning shortly."

### Source

https://ru.classic.wowhead.com/quest=6402/%D0%B2%D1%81%D1%82%D1%80%D0%B5%D1%87%D0%B0-%D0%B2-%D1%88%D1%82%D0%BE%D1%80%D0%BC%D0%B3%D1%80%D0%B0%D0%B4%D0%B5#english-comments

### Steps to reproduce the problem

1. Take quest "Stormwind Rendezvous"
2. Go to Squire Rowe
3. Try to talk with him

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Jackomighty** [comment]
Duplicate: https://github.com/chromiecraft/chromiecraft/issues/2959
