### ISSUE TITLE
During Curing the Sick, killing the deer after curing it counts towards quest completion

### ISSUE THREAD

**Issue by apav** [chromiecraft/chromiecraft#312]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

During the quest [Curing the Sick](https://wotlkdb.com/?quest=6124), you use a [quest item](https://wotlkdb.com/?item=15826) on [Sickly Deer](https://wotlkdb.com/?npc=12298), which awards one completion point per deer cured. However, if you kill them after they are cured, that will reward an additional point. 

![Curing the Sick](https://user-images.githubusercontent.com/8137930/112764711-e81eb800-8fd7-11eb-86f9-d0fde501c48c.png)

Note that this doesn't work if you kill the deer before you cure them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Killing the deer after you cure it should not reward a point towards quest completion. 

##### STEPS TO REPRODUCE THE PROBLEM:

1.  While on the quest, find a Sickly Deer in Darkshore and use the Curative Animal Salve on it. This will reward one point towards the quest.
2.  Kill the Cured Deer immediately after, this will reward a second point.

##### EXTRA NOTES:

I don't have a Horde Druid to test it on, but the same bug might occur on the [Horde equivalent quest](https://wotlkdb.com/?quest=6129).

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
There has been a long-standing bug on Blizzard servers with this quest, I don’t know if it’s present on ChromieCraft.
If you cast Entangling Roots on these Deer, then cure them, you get x1 credit for the cure and then a second credit when the deer dies to the Entangling Roots.
@apav doesn’t note how he killed this deer, but it might be a reproduction of a Blizzlike bug.

**Comment by apav** [comment]
> There has been a long-standing bug on Blizzard servers with this quest, I don’t know if it’s present on ChromieCraft.
> If you cast Entangling Roots on these Deer, then cure them, you get x1 credit for the cure and then a second credit when the deer dies to the Entangling Roots.
> @apav doesn’t note how he killed this deer, but it might be a reproduction of a Blizzlike bug.
> 
> There are comments that better describe the process, I’m linking this one for the date which shows it was still present in 3.3.5 - https://www.wowhead.com/quest=6129/curing-the-sick#comments:id=299378:reply=172305
> Latest I can find on Alliance version is for 3.3.3 - https://www.wowhead.com/quest=6124/curing-the-sick#comments:id=1006100

In my experience it doesn't matter how you killed them. I Moonfired one, and hit another with my melee attack and they both awarded credit. I did not cast Entangling Roots.

**Comment by eTzmNcbkrng** [comment]
>In my experience it didn't matter how you killed them. I Moonfired one and hit another with my melee attack, and they both awarded credit. I did not cast Entangling Roots.

Are you talking about in AC or Blizz servers?
As far as I'm aware, on Blizz servers you have to Entangling Roots them, then Cure.

The question is, do be want to stay true to Blizzard so much that we reproduce a bug they have not fixed since 2004?

**Comment by Stifler82** [comment]
Fixed!
-
https://user-images.githubusercontent.com/1884642/119499781-f6cae680-bd5e-11eb-9441-40def2e910c2.mp4
