### ISSUE TITLE
Not all loot is being added to my bag

### ISSUE THREAD

**Issue by MrFox96** [chromiecraft/chromiecraft#3120]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Was playing on my Warrior through Elwynd Forest. Notice that some of the loot from treasure chests, mining nodes and mobs weren't all being added to my bag. Only some of it.

### Expected Blizzlike Behaviour

Should have all the loot that was listed.

### Steps to reproduce the problem

Open treasure chest, loot dead mobs.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @MrFox96. Thank you for the report.

I was not able to experience any of that while tryng to reproduce it on my local AC. No loot issues at all.

Can you please provide more information?
Screenshots? Or better videos?
Do you use any AddOns?

**Comment by Sathrenor** [comment]
Can confirm, happened to me in the Winterspring. I could not loot a certain green item from a chest even with free bag slots. Tried to disable addons, manual loot, autoloot. Nothing worked.


Video: https://www.youtube.com/watch?v=jUPJULfF-qs
___
**Chest:**
_**85802** (Entry: **153454**)_

 _[Solid Chest X:6617.370117 Y:-4081.399902 Z:662.525024 MapId:1]_

**Comment by The-GhostRider** [comment]
I don't think it's a real bug, and by "real bug" I mean a bug that comes from the server.
Sometimes it happens that the "Client" interacts badly with the Server, this is due to various factors, from the Client's Cache, to the latency of its Internet line at that moment, and in any case the 2 things are not mutually exclusive, in the sense that sometimes it can also be a combination of both, the cause.
Therefore, due to an erroneous packet transfer interaction between the Client and the Server, these "Rare Cases" of bad interaction can occur, which can also be defined as Bugs, but in reality they are not, they are exceptional cases, and this is the reason why this "Bug" is so difficult to reproduce..

For this reason, I close the report.
