### ISSUE TITLE
[Mage][Talent] Finger of Frost / Frostbite / Ghost charge (FoF shatter combo)

### ISSUE THREAD

**Issue by bonfax4** [chromiecraft/chromiecraft#3123]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

- Ghost charge not working.

- FoF and Frostbite talent shouldn't have separate chances to proc, they be on the same "roll".

### Expected Blizzlike Behaviour

- Should be able to weave in a 3rd spell on a FoF proc which you can clearly see on this [video](https://youtu.be/8ET2Ct9_Ma8?t=117), slow it down to 0.5 and watch the mage do fb (proc) > fb > fb > deep freeze combo on a single proc. Mentioned this on my previous post #2537 . I Think the way to make it work is to add a small delay to both the proc and consume which seems to be the case if you pay attention to the video ( This might be how procs worked in retaiI in general or this could all be purely a latency thing but I see this same "delay" as well when [Arcane concentration](https://wowgaming.altervista.org/aowow/?spell=12577) procs in other videos). Either way adding like a 300-500ms delay to both the proc and consume should fix this while also preventing issues like a consecutive FoF charge being consumed because of this "delay". It just has to be less than 1 second so you don't run into rare high haste occasion where ppl can weave in 2 abilities in that gap.

- Fingers and Frostbite should be on the same roll, meaning when one procs the other should as well if both talents are fully maxed out (15% / 15%). Although they behave like this it doesn't mean both talents are fully linked , as Frostbite can actually proc by itself if procced by an ability that deals no damage like [Ice armor](https://wowgaming.altervista.org/aowow/?spell=43008) snare. Not exactly sure how they'd behave if they're not maxed but I'd assume it's something like FoF had a 15% chance and Frostbite 5%, Frostbite would have a 5/15 or @ 33% chance if a FoF proc were to occur. To note that Frostbite still procs on spell hit and not on cast like Fingers but a fingers proc will pretty guarantee that freeze on the target. Can be seen [here](https://youtu.be/otdlbEUUkPE?t=136) if you slow the video down to 0.25.

### Source

https://www.mmo-champion.com/threads/641024-FrostBite-Fingers-of-Frost-question

> Yes, the proc chances are indeed related, in such a way that you can't proc Frostbite on a frost damage spell without also proccing FoF. However, you can proc FoF without proccing Frostbite if the target is immune to the Frostbite effect. In addition, you can proc Frostbite without proccing FoF if the Frostbite proc is caused by a non-damage spell such as Ice Armor.
Also, if you have FoF, you can actually cast 2 Frostbolts, the last one followed up with an Ice Lance - because that casting the Ice Lance instantaneously after the Frostbolt, you can practically achieve the shatter bonus three times, creating a "third" FoF charge.

> No, the charge is consumed on spell cast. The reason you can fit an Ice Lance in is network lag.
The FoF Shatter is basically a bug, as it goes directly against the talent tooltip that clearly states "your next 2 spells cast".
A normal Shatter combo relies on travel time, a game mechanic, to work, but this one can be impossible to pull to a player with the wrong amount of latency. Hence, if Blizzard intends for our DPS to be balanced around this, they have to make it more clear. The people over at EJ (Lhivera especially) are considerably vocal against this mechanic.

https://www.mmo-champion.com/threads/710176-Ghost-fingers-of-frost

>It works the same way as queueing spells, you get a FoF proc, frostbolt, frostbolt->ice lance. It actually works better on frostbite/novas, as you can FB-IL-IL if you have enough haste and are far enough away. It's pretty cute.
The idea is to cast it while you still have the buff or they still have the debuff. Latency is a factor, but you don't need particularly low latency, just not like, 800.

https://www.youtube.com/watch?v=8ET2Ct9_Ma8 Throughout this video you can see examples of everything I described happening including Frostbite always proccing with FoF. This is noticeable because every time you see the "Deep Freeze" yellow text (which represents a FoF proc) you also see an "immune" on the boss since you can't freeze bosses.

### Steps to reproduce the problem

1. Get to a dummie and try to use the ghost charge either with deep freeze, Ice Lance or Brain Freeze proc. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Can confirm and reproduce both issues on the PTR with an average of 250ms. The ghost charge is currently unusable/nonexistent and the same has been reported by other people in the Discord as well.
https://discord.com/channels/788063059926712341/825732076975554571/958418345265340447
https://discord.com/channels/788063059926712341/825732076975554571/958502106191503450
https://discord.com/channels/788063059926712341/825732076975554571/958413698047807598


[One more source on the existence of the ghost charge in 3.3.5](https://wowpedia.fandom.com/wiki/Fingers_of_Frost?oldid=2301949)
2 video sources were provided by the last Discord link posted above: [1](https://www.youtube.com/watch?v=4X-GB9GB7Ic) and [2](https://www.youtube.com/watch?v=lr-ghl-CEL8)
[Another Post](https://www.mmo-champion.com/threads/704461-3-3-3-Mage-PvE-Guide-to-Frost-Basics):
>What ghosting FoF means is you can use an instant cast directly after using the second charge of your FoF proc, effectively applying 3 charges to your spells. Doing so will increase the crit chance of all spells cast by 50% and allow for you to use DF, your 30 second atomic bomb.

Also, it seems that it was rather well established that the Shatter bonus is applied on-cast rather than on-hit, given the numerous guides explaining "Shatter Combos" in PvP, where they'll focus on having the target be rooted during the cast and not necessarily during the hit, such as [this video](https://www.youtube.com/watch?v=VJ9fy9DYRWI)




Can also confirm that Frostbite can currently proc independently from Fingers of Frost, which goes against several additional sources I've also found.
> [From what I've gathered Frostbite and Fingers of Frost have the same proc roll and if fully speced into both they will always proc together, ok got that](https://www.wowhead.com/forums/topic/frostbite-and-fingers-of-frost-92604)

> [It will also always proc along with Fingers of Frost if both are fully talented.](https://wowwiki-archive.fandom.com/wiki/Frostbite_(mage_talent))

**Comment by bonfax4** [comment]
Spell batching guy you linked in discord made me do a little research and I think this might be an overall issue rather than just fingers itself. **Spell queue** which was introduced in tbc https://girlmeetswow.blogspot.com/2007/10/stopcasting-in-23-return-to-button.html . I believe this problem should be fixed once this is implemented. I had the idea this was added in cata but in cata they just added the ability to control to queue window rather than having a default value. I remember having to deal with the spell queue window interaction with instant casts to fully optimize boomkin gameplay in cata in order to make better use of eclipses and the behavior would make sense if you apply the same logic to fingers. You can read about it [here](https://web.archive.org/web/20110923151831/http://elitistjerks.com/f73/t110353-balance_cataclysm_4_2_a/#Advanced_Techniques) @ Advanced techniques section.

I believe warmane actually made it possible to where you could control this window via a command i think but i can't test fingers on there since its bugged and procs on-hit sadly.

**Comment by Gultask** [comment]
I think you can post that [in the linked Azerothcore github](https://github.com/azerothcore/azerothcore-wotlk/issues/11338), it could help the devs.
