### ISSUE TITLE
Paladin Holy Shock friendly target range 

### ISSUE THREAD

**Issue by silvidruid** [chromiecraft/chromiecraft#3128]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Casting any rank of the paladins holy spec talent ability Holy Shock (https://wowgaming.altervista.org/aowow/?spell=20930#see-also) only works at 20 yards even when being cast on friendly targets.

### Expected Blizzlike Behaviour

Tooltip states ranges as: 20yd enemy and 40yd friendly. Should be castable at 40 yards on friendly targets.

### Source

All wiki entries on the ability state the range as 20yd enemy and 40yd friendly.
https://wowgaming.altervista.org/aowow/?spell=20930#see-also
https://wotlk.evowow.com/?spell=20930
ingame tooltip states the same.

### Steps to reproduce the problem

1.get friendly target such as another player
2. max range another heal like flash of light(range 40yd)
3. attempt to cast holy shock at the same range
4. if not castable move closer until it is 
5. find yourself at 20 yards

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Jpizzle31** [comment]
Thanks for Report. I was able to confirm the issue.

**Comment by thom4466** [comment]
Pretty sure this was already known or no?

**Comment by silvidruid** [comment]
> Pretty sure this was already known or no?

People know about a lot of bugs most of them aren't reported, I did not find any mentioning this issue.

**Comment by fendwe** [comment]
This seems to be working correctly now.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/10906
