### ISSUE TITLE
Scroll of enchant shield - Vitality not working

### ISSUE THREAD

**Issue by Rubadubscrub** [chromiecraft/chromiecraft#3131]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

https://wowgaming.altervista.org/aowow/?item=38860

_Scroll of enchant shield - Vitality_  doesnt work and comes up with the error "nothing to attack" or "you cannot attack that target when attempted to be used.

when targeting a hostile creature it says "can only be used at night" 
![image](https://user-images.githubusercontent.com/11332559/155562478-ec5c314e-6142-4a9d-82be-3132ddbfc125.png)

and at night "can only be used in the day" 
![image](https://user-images.githubusercontent.com/11332559/155650546-abbe95f7-b895-4204-954a-dc537e805863.png)

### Expected Blizzlike Behaviour

Sould be usable like any other enchantment scroll

### Source

Every other enchanting scroll in game

### Steps to reproduce the problem

buy Scroll of enchant shield - Vitality  on auction house (dont have enchant to test a fresh one)
right click scroll
right click scroll while targeting hostile

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Rubadubscrub** [comment]
Enchant Shield - Vitality also shows up in my spellbook 
![image](https://user-images.githubusercontent.com/11332559/155581455-4eb38701-7d63-4933-8f31-d92100024a29.png)

**Comment by ZhengPeiRu21** [comment]
I am unable to reproduce this issue. The scroll works correctly with hostile target and no target. You may have bad cached data. If you clear your cache, does this issue still happening?

**Comment by Rubadubscrub** [comment]
Deleted cache and it still happens.
Checked on a different computer and i still have the enchant in my spellbook and the same casting errors

**Comment by ishidinho** [comment]
Hey @Rubadubscrub. I was not able to reproduce the issue on local AC, too.

![WoWScrnShot_022622_102516](https://user-images.githubusercontent.com/62797536/155838248-a2a5fee7-1254-4b82-9855-7879ae15bfd1.jpg)
