### ISSUE TITLE
Weapon Skills sometimes go up 2 Points at once

### ISSUE THREAD

**Issue by Hacki95** [chromiecraft/chromiecraft#314]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

I saw that my Sword Skill sometimes goes up by 2 Points instead of one.

![WoWScrnShot_032921_115140](https://user-images.githubusercontent.com/62942638/112820184-ac422c00-9085-11eb-8b18-6c6a504017c8.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Your Skills should only increase by 1.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Equip a Weapon which you can still skill up with
2. Fight a few mobs
3. Watch your skill increase

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Hacki95 https://github.com/chromiecraft/chromiecraft#report

as you are a contributor, no need to report here. Just reproduce the issue locally in your AC and report directly to the AC bugtracker ;)

the [chromiecraft/chromiecraft](https://github.com/chromiecraft/chromiecraft) bugtracker is just to collect the reports from players

**Comment by Hacki95** [comment]
Mainly added this to keep track :) I also found this while playing on CC not my local server so I thought I will report it here first before checking it later on AC when I am done leveling my paladin.

**Comment by Stifler82** [comment]
> Mainly added this to keep track :) I also found this while playing on CC not my local server so I thought I will report it here first before checking it later on AC when I am done leveling my paladin.

@Hacki95 
Question: Do you have the weapon or an ability / talent / spell / effect that allows you to do an **"extra attack"**?

**Comment by Hacki95** [comment]
> 
> 
> > Mainly added this to keep track :) I also found this while playing on CC not my local server so I thought I will report it here first before checking it later on AC when I am done leveling my paladin.
> 
> @Hacki95
> **Question:** Do you have the weapon or an ability / talent / spell / effect that allows you to do an **"extra attack"**?

I was around level 11 or 12 when I made this screenshot. So my talents where like this: https://wotlkdb.com/?talent#sZc

About the item I am not sure tbh, I sadly don't have the sword anymore but it must have been some level 5-10 green sword. 

I also don't think Paladins already have a spell at that level that makes them double attack.

I have not been able to reproduce it on my local machine so far but I only quickly tested it with a warrior at level 10 and no weapon skills.

**Comment by Stifler82** [comment]
@Hacki95 
so if you unable to reproduce now, probably it got fix, can we close this report?

**Comment by Hacki95** [comment]
Nothing with the weapon level system got changed, there must be something that triggered this behaviour, I just haven't been able to find out wat it was yet. If its okay then let it stay open for a few more days, I will try a few things and if I am not able to reproduce it I will close it.

**Comment by Stifler82** [comment]
@Hacki95 any news?

**Comment by Hacki95** [comment]
My fault, I forgot. I will close this one, sadly I am not able to reproduce it.
