### ISSUE TITLE
[Arathi Basin] Quest The Battle for Arathi Basin is repeatable

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#3140]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [X] 30-39
- [X] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

The quests for Battle of Arathi Basin can be repeated.

### Expected Blizzlike Behaviour

It is supposed to be one quest available, depending on the players level. Turning in the quest once, should end the quest chain.
Players should NOT be able to accept the quest again.

### Steps to reproduce the problem

1. Move to [Field Marshal Oslight](https://db.rising-gods.de/?npc=14983) or [Deathmaster Dwire](https://db.rising-gods.de/?npc=15021)
2. Accept the quest
3. Join Arathi Basin and complete the quest
4. Turn in the quest
5. Accept the quest again (shouldnt be possible)

### Extra Notes

[the battle for arathi basin!](https://db.rising-gods.de/?search=The+Battle+for+Arathi+Basin%21)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment]
Someone put wrong SpecialFlag in quest_template_addon. Quest is repeatable but only per level bracket not per quest. 20 30 40 50 each got their own quest with unique ID.

> UPDATE quest_template_addon SET SpecialFlags = 0 WHERE ID = 8166;
UPDATE quest_template_addon SET SpecialFlags = 0 WHERE ID = 8167;
UPDATE quest_template_addon SET SpecialFlags = 0 WHERE ID = 8168;
UPDATE quest_template_addon SET SpecialFlags = 0 WHERE ID = 8169;
UPDATE quest_template_addon SET SpecialFlags = 0 WHERE ID = 8170;
UPDATE quest_template_addon SET SpecialFlags = 0 WHERE ID = 8171;
UPDATE quest_template_addon SET SpecialFlags = 0 WHERE ID = 8105;
UPDATE quest_template_addon SET SpecialFlags = 0 WHERE ID = 8120;

This should fix the issue.
