### ISSUE TITLE
Incorrect Quest giver

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#3149]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Highlord Bolvar Fordragon currently gives the quest https://wowgaming.altervista.org/aowow/?quest=7496

### Expected Blizzlike Behaviour

This quest is supposed to be given out by https://wowgaming.altervista.org/aowow/?npc=29611 as Bolvar was moved into northrend at the start of wrath of the lich king.
It wasn't just this quest though https://wowgaming.altervista.org/aowow/?quest=7781 and https://wowgaming.altervista.org/aowow/?quest=4184 follow the same criteria 
bolvar in vanilla was the npc you turned these respective quests into but since he move to northrend they replaced him with varian

### Source

the wrathgate
the quests that you do in game that no longer require you to turn them into bolvar because he is not supposed to be in stormwind
he is instead in northrend

### Steps to reproduce the problem

Grab ony head
do first part of quest
2nd part is given by bolvar which is incorrect

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ZhengPeiRu21** [comment]
Hello Never6. Thank you for the report. I believe the current behavior is correct. Quest 7496 is Vanilla period Onyxia quest, so Bolvar is correct quest starter for most of the game's history.
King Wrynn did give this quest during period between 3.0 and 3.2.2 when Vanilla Onyxia is removed, however, so there was a time period when that is accurate. In accurate Blizz-like 3.3.5, this quest is not obtainable because all vanilla Onyxia content is remove, so there is no "Blizz-like" answer. The only question is if ChromieCraft progression is trying to emulate Vanilla period or 3.0 period.

**Comment by ishidinho** [comment]
As this quest being part of the Onyxia Level 60 custom boss, this is a "Won't fix" for AzerothCore.
