### ISSUE TITLE
Backstab can be cast from the side when phasing into mobs.

### ISSUE THREAD

**Issue by tabakisp** [chromiecraft/chromiecraft#315]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Backstab is a Rogue's spell cast strictly from behind. Phasing into a mob and spamming backstab actually succeeds.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You must be behind the target in order to be able to cast it. It should never allow you to cast it successfully, as the monster will always be facing you except conditions (running away from you etc).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find a monster and gain aggro. Spam backstab while phasing into the mob will eventually succeed. 
2. -
3. -
4. -

##### EXTRA NOTES:

Backstab [Spell link](https://wowgaming.altervista.org/aowow/?spell=48657).  
Own [Video](https://streamable.com/udb5fu) showing that you can *frontstab*.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacki95** [comment]
Interesting discussion about this topic: https://www.reddit.com/r/classicwow/comments/be80u8/front_stabbing/

**Comment by Helias** [comment]
Yep, probably it was also in retail
![image](https://user-images.githubusercontent.com/519778/113488013-adc38800-94bb-11eb-968c-2b8101d5e899.png)

**Comment by Hacki95** [comment]
> 
> 
> Yep, probably it was also in retail
> ![image](https://user-images.githubusercontent.com/519778/113488013-adc38800-94bb-11eb-968c-2b8101d5e899.png)

Problem is you see one half of the people saying it was possible, and other half swears it wasn't. Really hard to say who remembers it right.

**Comment by ohsiros** [comment]
Except the comment that IchBinMann refers to is proof that its not a bug and that it is blizzlike behaviour, making this an invalid bug report.

**Comment by Stifler82** [comment]
Case Closed!
-
**Video Test:** [Backstab](https://youtu.be/vyR-DTBcTUo)
