### ISSUE TITLE
Quest - Amani Encroachment wrong level

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#3170]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

**Amani Encroachment** is a quest taken from [Lieutenant Dawnrunner](https://wowwiki-archive.fandom.com/wiki/Lieutenant_Dawnrunner) at the [Farstrider Retreat](https://wowwiki-archive.fandom.com/wiki/Farstrider_Retreat) in [Eversong Woods](https://wowwiki-archive.fandom.com/wiki/Eversong_Woods) wants you to kill 5 Amani Berserkers and 5 Amani Axe Throwers.

According to Joana's guides and wowwiki, this quest isn't able to be picked at the correct level.

### Expected Blizzlike Behaviour

The level that players are able to take this quest is **7** according to Wowwiki

### Source

![image](https://user-images.githubusercontent.com/54484196/156899404-032bfd01-b465-42ba-bdf1-e34e641977ba.png)

![image](https://user-images.githubusercontent.com/54484196/156899431-88118462-4133-4b4b-b5e4-892786724b4d.png)

### Steps to reproduce the problem

1. .go creature 55355
2. .character level 8 can't take quest **Amani Encroachment**

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment]
U need to complete quest chain till u get to  [Farstrider Retreat](https://tbc.wowhead.com/quest=9359/farstrider-retreat) which requires Level 8 to start. [Farstrider Retreat] is first quest in chain to get u [Amani Encroachment](https://classic.wowhead.com/quest=8476/amani-encroachment)

**Comment by claudiodfc** [comment]
If you follow Joana's quest guide for this zone, which is free, you will see that he doesn't have the pre requesite and still tells players to get the quest

**Comment by Kosiak** [comment]
Then the guide is wrong or outdated. The quest is 2nd in the chain. And without first one it wont work.
![Screenshot_20220310-004239_Chrome](https://user-images.githubusercontent.com/791788/157564544-260d4752-ee03-4eb0-a033-b19db2c9f8f7.jpg)
