### ISSUE TITLE
Molten Core - Baron Geddon loot table adjustment

### ISSUE THREAD

**Issue by KarazhanSucks** [chromiecraft/chromiecraft#3174]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [x] 60

### Current Behaviour

Loot pooling for all MC bosses seems to be incorrect.

### Expected Blizzlike Behaviour

https://web.archive.org/web/20080302200946/http://elitistjerks.com/f33/t16988-thesis_how_loot_tables_work/

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

Baron Geddon
https://classic.wowhead.com/npc=12056/baron-geddon

Pool A --- Chance 1
16797 "Arcanist Mantle"
16807 "Felheart Shoulder Pads"
17110 "Seal of the Archmagus"

Pool B1 --- Chance 0.6
16856 "Lawbringer Spaulders" *A*
16844 "Earthfury Epaulets" *H*
16836 "Cenarion Spaulders"
Pool B2 --- Chance 0.4 (1-B1)
Shared Gehennas/Magmadar/Lucifron/Garr/BaronGeddon/Shazzrah/SulfuronHarbinger/GolemaggtheIncinerator
18861 "Flamewaker Legplates" 1x
Shared Magmadar/Garr/BaronGeddon/GolemaggtheIncinerator
18823 "Aged Core Leather Gloves" 2x
19143 "Flameguard Gauntlets" 2x
19136 "Mana Igniting Cord" 2x
18821 "Quick Strike Ring" 2x
18820 "Talisman of Ephemeral Power" 2x
19142 "Fire Runed Grimoire" 2x
18822 "Obsidian Edged Blade" 2x
18829 "Deep Earth Spaulders" 1x
18824 "Magma Tempered Boots" 1x
19144 "Sabatons of the Flamewalker" 1x

Recipe Pool --- Chance 0.1
18252 "Pattern: Core Armor Kit"
18265 "Pattern: Flarecore Wraps"
18264 "Plans: Elemental Sharpening Stone"
18257 "Recipe: Major Rejuvenation Potion"
18290 "Schematic: Biznicks 247x128 Accurascope"
18291 "Schematic: Force Reactive Disk"
18259 "Formula: Enchant Weapon - Spell Power"
21371 "Pattern: Core Felcloth Bag"
18292 "Schematic: Core Marksman Rifle"
18260 "Formula: Enchant Weapon - Healing Power"

### Source

https://web.archive.org/web/20080302200946/http://elitistjerks.com/f33/t16988-thesis_how_loot_tables_work/

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

### Steps to reproduce the problem

1. Kill Baron Geddon
2. Check if items are exclusive. Always should drop one item from pool A, one item from pool B* and .1 chance for recipe.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by godnesso** [comment]
can confirm loot pools stated above
