### ISSUE TITLE
Molten Core - Sulfuron Harbinger loot table adjustment

### ISSUE THREAD

**Issue by KarazhanSucks** [chromiecraft/chromiecraft#3175]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Loot pooling for all MC bosses seems to be incorrect.

### Expected Blizzlike Behaviour

Sulfuron Harbinger
https://classic.wowhead.com/npc=12098/sulfuron-harbinger

https://web.archive.org/web/20080302200946/http://elitistjerks.com/f33/t16988-thesis_how_loot_tables_work/

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

Pool A --- Chance 1
16816 "Mantle of Prophecy"
16848 "Giantstalker's Epaulets"
17074 "Shadowstrike"

Pool B1 --- Chance 0.66
16868 "Pauldrons of Might"
16823 "Nightslayer Shoulder Pads"
Pool B2 --- Chance 0.33 (1-B1)
Shared Gehennas/Magmadar/Lucifron/Garr/BaronGeddon/Shazzrah/SulfuronHarbinger/GolemaggtheIncinerator
18861 "Flamewaker Legplates"
Shared Gehennas/Lucifron/Shazzrah/SulfuronHarbinger
19147 "Ring of Spell Power"
18875 "Salamander Scale Pants"
19146 "Wristguards of Stability"
18870 "Helm of the Lifegiver" *H*
18878 "Sorcerous Dagger"
17077 "Crimson Shocker"
18879 "Heavy Dark Iron Ring"
18872 "Manastorm Leggings"
Shared Gehennas/Lucifron/SulfuronHarbinger
19145 "Robe of Volatile Power"

### Source

https://web.archive.org/web/20080302200946/http://elitistjerks.com/f33/t16988-thesis_how_loot_tables_work/

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

### Steps to reproduce the problem

1. Kill Sulfuron Harbinger
2. Check if items are exclusive. Always should drop one item from pool A and one item from pool B*.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by godnesso** [comment]
can confirm loot pools above
