### ISSUE TITLE
Molten Core - Majordomo Executus loot table adjustment

### ISSUE THREAD

**Issue by KarazhanSucks** [chromiecraft/chromiecraft#3176]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Loot pooling for all MC bosses seems to be incorrect.

### Expected Blizzlike Behaviour

https://web.archive.org/web/20080302200946/http://elitistjerks.com/f33/t16988-thesis_how_loot_tables_work/

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

Majordomo Executus
https://classic.wowhead.com/npc=12018/majordomo-executus

Pool A --- Chance 1
19139 "Fireguard Shoulders"
18805 "Core Hound Tooth"
18808 "Gloves of the Hypnotic Flame"
18811 "Fireproof Cloak"
18803 "Finkle's Lava Dredger"

Pool B --- Chance 1
18809 "Sash of Whispered Secrets"
18810 "Wild Growth Spaulders"
19140 "Cauterizing Band"
18812 "Wristguards of True Flight"
18806 "Core Forged Greaves"

Pool C --- Chance 1
18703 "Ancient Petrified Leaf"
18646 "The Eye of Divinity"

### Source

https://web.archive.org/web/20080302200946/http://elitistjerks.com/f33/t16988-thesis_how_loot_tables_work/

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

### Steps to reproduce the problem

1. Kill the Majordomo's adds.
2. Check if items are exclusive. Always should drop one item from pool A, one item from pool B and one item from pool C.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by godnesso** [comment]
can confirm loot pools above
