### ISSUE TITLE
Molten Core - Ragnaros loot table adjustment

### ISSUE THREAD

**Issue by KarazhanSucks** [chromiecraft/chromiecraft#3177]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Loot pooling for all MC bosses seems to be incorrect.

### Expected Blizzlike Behaviour

https://web.archive.org/web/20080302200946/http://elitistjerks.com/f33/t16988-thesis_how_loot_tables_work/

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

Ragnaros
https://classic.wowhead.com/npc=11502/ragnaros

Pool A
16922 "Leggings of Transcendence"
16915 "Netherwind Pants"
16930 "Nemesis Leggings"
16909 "Bloodfang Pants"
16901 "Stormrage Legguards"
16938 "Dragonstalker's Legguards"
16962 "Legplates of Wrath"
16954 "Judgement Legplates" *A*
16946 "Legplates of Ten Storms" *H*

Pool B
16922 "Leggings of Transcendence"
16915 "Netherwind Pants"
16930 "Nemesis Leggings"
16909 "Bloodfang Pants"
16901 "Stormrage Legguards"
16938 "Dragonstalker's Legguards"
16962 "Legplates of Wrath"
16954 "Judgement Legplates" *A*
16946 "Legplates of Ten Storms" *H*

Pool C
18816 "Perdition's Blade"
18814 "Choker of the Fire Lord"
18815 "Essence of the Pure Flame"
18817 "Crown of Destruction"
19138 "Band of Sulfuras"

Pool D
19137 "Onslaught Girdle"
17063 "Band of Accuria"
17106 "Malistar's Defender"
17102 "Cloak of the Shrouded Mists"
17107 "Dragon's Blood Cape"
17104 "Spinal Reaper"

Pool E
17076 "Bonereaver's Edge"
17082 "Shard of the Flame"
17204 "Eye of Sulfuras"
13123 "Dreamwalker Armor"
13075 "Direwing Legguards"
13113 "Feathermoon Headdress"
5267 "Scarlet Kris"
6622 "Sword of Zeal"
13107 "Magiskull Cuffs"
13000 "Staff of Hale Magefire"
13006 "Mass of McGowan"
13116 "Spaulders of the Unseen"
13133 "Drakesfire Epaulets"
13015 "Serathil"
13072 "Stonegrip Gauntlets"
9402 "Earthborn Kilt"
13060 "The Needler"
13001 "Maiden's Circle"
13053 "Doombringer"

Pool F
13008 "Dalewind Trousers"
13111 "Sandals of the Insurgent"
2564 "Elven Spirit Claws"
13007 "Mageflame Cloak"
13040 "Heartseeking Crossbow"
13003 "Lord Alexander's Battle Axe"
13120 "Deepfury Bracers"
13125 "Elven Chain Boots"
13066 "Wyrmslayer Spaulders"
13009 "Cow King's Hide"
13073 "Mugthol's Helm"
13144 "Serenity Belt"
13126 "Battlecaller Gauntlets"
13067 "Hydralick Armor"
1203 "Aegis of Stormwind"
13004 "Torch of Austen"
13013 "Elder Wizard's Mantle"
13135 "Lordly Armguards"
13130 "Windrunner Legguards"
13047 "Twig of the World Tree"
13146 "Shell Launcher Shotgun"
13036 "Assassination Blade
13077 "Girdle of Uther"
13118 "Serpentine Sash"
13002 "Lady Alizabeth's Pendant"
13070 "Sapphiron's Scale Boots"

Pool A and B are exact copies from each other the blue items in pools E and F are more guesswork than other ones.
Ragnaros also still has the possibility to get an extra drop from world epic and world rare tables as well.

### Source

https://web.archive.org/web/20080302200946/http://elitistjerks.com/f33/t16988-thesis_how_loot_tables_work/

MC Boss exclusivities and pools derived from https://www.docdroid.net/jnwaC38/lootid-mastersheet-v2-xlsx

Internal logic of shared loot pools cannot be derived sadly.

### Steps to reproduce the problem

1. Clear MC upto Ragnaros
2. Kill Ragnaros
3. Check if items are exclusive. Always should drop one item from pool A, one item from pool B, one item from pool C, one item from pool D, one item from pool E and one item from pool F.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by godnesso** [comment]
While the loot needs to be adjusted, the pools suggested above are incorrect and can be easily disproven with classic footage.

The correct pools are as follows:
Pool A (any of the Tier 2 leggings)
Pool B (any of the Tier 2 leggings)
**Pool C (Choker of the Fire Lord, Essence of Pure Flame, Perdition's Blade, Crown of Destruction, Band of Sulfuras)**
**Pool D (Cloak of Shrouded Mists, Malistar's Defender, Dragon's Blood Cape, Band of Accuria, Onslaught Girdle)**
**Pool E (Bonereaver's Edge, Spinal Reaper, Shard of the Flame, Eye of Sulfuras)**
Pool F (one of the blue items that are already on Rag loot table)
Pool G (one of the blue items that are already on Rag loot table)

Can post video footage of Pool E existing if desired.

**Comment by ishidinho** [comment]
@godnesso We take everything you have. ;)

**Comment by ishidinho** [comment]
Hey @KarazhanSucks. Thank you for all your hard work collection the loot tables.
As you can see, @Nefertumm implemented a fix for all your reports.

Again, many thanks!
