### ISSUE TITLE
The shattered hand Rogue quest gamon does not drop the item and subsequent tries end up not being able to loot gamon!

### ISSUE THREAD

**Issue by almosthuxley** [chromiecraft/chromiecraft#318]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

While doing "the shattered hand" rogue quest. When killing Gamon item does not drop when I killed gamon again and again I could not able to loot.I could not even click on the corpse

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When Gamon killed we should be able to loot the item

##### STEPS TO REPRODUCE THE PROBLEM:

1. be a rogue 
2. start the quest kill tazan and take the second quest
3. go to gamon kill him 
4.try to loot

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
This quest is working correctly.
You just haven't figured out how to get the item you need to complete the quest.

Close Issue; not a bug.

**Comment by almosthuxley** [comment]
Oh dear If I known I’d be treated like this I would not even try to help here. What type of words are those. You are talking to another person. You do not have to be a dickhead to get your point across . Big big ashole you are. Dear god that cynic tone and everything! To make honest mistake is something to scold some fot this another all I wsh you in devastation in your troubles
