### ISSUE TITLE
[BWL] Raorgore - Link of control should be visible during the player use orb

### ISSUE THREAD

**Issue by Lynethris** [chromiecraft/chromiecraft#3181]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When the player use orb for control the boss, any link (like before the fight with Grethok ) is visible.

### Expected Blizzlike Behaviour

When the player use orb for control the boss, a link should be visible between the boss and the orb.

### Source

https://www.youtube.com/watch?v=_QKtLCV2dfU&ab_channel=GeoffJones (2:41min)

### Steps to reproduce the problem

Use orb for control the boss

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Lynethris** [comment]
> Hey @Lynethris.
> 
> This issue has already been reported in ticket #3095.
> 
> A fix [azerothcore/azerothcore-wotlk#10832](https://github.com/azerothcore/azerothcore-wotlk/pull/10832) for this is already in the pipeline.

It's not the same issue. This PR fix the blue lazer between Grethok and the boss before the fight. But it's not persist if the player use orb. 

![WoWScrnShot_030822_164504](https://user-images.githubusercontent.com/100411212/157273405-d93f1f2f-77ac-4a90-bf7a-4ba4e11ceaf3.jpg)

**Comment by ishidinho** [comment]
Ticket https://github.com/chromiecraft/chromiecraft/issues/3095 says "Mindcontroll spell not showing (blue lightening between the orb and Razorgore. )". In my eyes, this affects Grethok using the orb as well as the player.

**Comment by ishidinho** [comment]
Or have you tested again with the current `azerothcore:master` which has https://github.com/azerothcore/azerothcore-wotlk/pull/10832 in it?

@Lynethris

**Comment by Lynethris** [comment]
This issue was observed with the current master branch. 

Hhonestly, when I tested the fix, I have only check the temper ticket (cited: "Grethok the Controller should "controll" Razorgore before entring combat on first boss. the blue lazer thing across the room is missing."). 
And never having this raid before, I didn't know that it also concerned the control by the player.
