### ISSUE TITLE
Guild Ranks and Perms revert to Default

### ISSUE THREAD

**Issue by pkleader** [chromiecraft/chromiecraft#3183]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

At some point between 07 MAR 2022 11pm EST and 08 MAR 2022 9am EST, all of my guild's customized ranks and their permissions reverted back to default.

I had even added additional custom ranks which were removed and some members of the guild were left without a rank at all.

My guild bank and Tabard do not appear to have been affected.

### Expected Blizzlike Behaviour

Guild ranks without profanity or without words that would have action taken against them would be expected to remain in place.

### Source

<img width="317" alt="bbb" src="https://user-images.githubusercontent.com/64566296/157255869-0c3529df-aa12-47c6-a825-e1b51d25a78c.PNG">

### Steps to reproduce the problem

Logged out last night and all was fine. No changes made.
Logged in this morning and issue existed.
I do not believe there is a way to reliably reproduce this issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Windows 10 19043.1526

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Winfidonarleyan** [comment]
@pkleader Did you use the symbol `|` in the name of the rank?

**Comment by The-GhostRider** [comment]
In my experience, sometimes guilds get bugged, sometimes it doesn't take much, even a wrong character in the names of the guilds or in the names of the ranks, sometimes you don't need to do anything.
And unfortunately it's a difficult thing to "Fix" the only thing that can be done in such cases is something simpler: **Disband the Guild and recreate it again.**
it's a nuisance I know.. but it's the quickest and safest thing you can do, it's very difficult for a Guild to bug again twice, a bit like Lightning that doesn't fall twice in the same spot, let's say..
Avoid putting "Special Characters" in names.

I close the report..
