### ISSUE TITLE
Quest "Messenger to Stormwind"

### ISSUE THREAD

**Issue by Nogarevi** [chromiecraft/chromiecraft#3184]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The Quest "https://wowgaming.altervista.org/aowow/?quest=120" works fine until I arrived at Stormwind in front of "General Marcus Jonathan; https://wowgaming.altervista.org/aowow/?npc=466", which is the turn-in npc to finish the quest. He doesn't has a question mark above his head and interacts with the player, **with** the completed quest, the **same** way he does with players **without** the quest active.

### Expected Blizzlike Behaviour

The npc opens the completion window of the quest after rightclicking him and shows a question mark above his head.

### Source

https://wowgaming.altervista.org/aowow/?quest=120

### Steps to reproduce the problem

1. Accept the quest "Messenger to Stormwind" at "Lakeshire; https://wowgaming.altervista.org/aowow/?object=114" in the "Redridge Mountains; https://wowgaming.altervista.org/aowow/?zone=44"

2. Go to "Stormwind; https://wowgaming.altervista.org/aowow/?zone=1519" to the npc "General Marcus Jonathan; https://wowgaming.altervista.org/aowow/?npc=466"

3. Question Mark above the head is missing and quest can't be turned in at this npc.

### Extra Notes

The item "https://wowgaming.altervista.org/aowow/?item=1293" is needed to turn in the quest and is provided by the start npc.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment]
This quest is tricky :) U need to turn in quest to General Marcus when he is on the horse. If he's kneeling u can't turn in quest until he de-spawns and respawn on horse. Could be 20 to 30 min wait. it's just how quest works.
![marcus](https://user-images.githubusercontent.com/791788/157338207-5879ff15-5d24-4f8b-992b-7a4d3f5e83dd.png)

**Comment by Nogarevi** [comment]
Okay, thanks for your time and quick response! :D
