### ISSUE TITLE
Quest "Blackrock Bounty" 

### ISSUE THREAD

**Issue by Nogarevi** [chromiecraft/chromiecraft#3185]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The Quest can be accepted and completed but the End-npc "Guard Howe; https://wowgaming.altervista.org/aowow/?npc=903"
won't let you turn in the quest and the question mark above his head is missing.

### Expected Blizzlike Behaviour

The Quest can be turned in at the npc "Guard Howe; https://wowgaming.altervista.org/aowow/?npc=903" while he is having a question mark above his head.

### Source

https://wowgaming.altervista.org/aowow/?quest=128

### Steps to reproduce the problem

1. **Start** the **quest** "Blackrock Bounty; https://wowgaming.altervista.org/aowow/?quest=128" in the **zone** "Redridge Mountains; https://wowgaming.altervista.org/aowow/?zone=44" at the **npc** "Guard Howe; https://wowgaming.altervista.org/aowow/?npc=903"

2. **Complete** the quest by killing 15 "Blackrock Champions; https://wowgaming.altervista.org/aowow/?npc=435" in the "Redridge Mountains; https://wowgaming.altervista.org/aowow/?zone=44"

3. **Return** to the **npc** "Guard Howe; https://wowgaming.altervista.org/aowow/?npc=903" and try to turn in the quest

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment]
Can't confirm mark appears on quest accept and works fine when quest finished. Try to clear your cache maybe?
![marcus](https://user-images.githubusercontent.com/791788/157339364-c66f378a-9f8e-443b-96b6-e61c48fa6e24.png)

**Comment by Nogarevi** [comment]
Cleaned cache and restarted quest, it worked fine. Thanks for your time and quick response :D
