### ISSUE TITLE
Hunter Bug Abuser

### ISSUE THREAD

**Issue by Sfaccim** [chromiecraft/chromiecraft#3187]
PLS adjust the range of the pet he literally send the pet from roma to kim jon hung the pet doesent have a range and i think is not nerfed inside the bgs

**Comment by Never6** [comment]
rofl

**Comment by ishidinho** [comment]
Hey @Sfaccim. Honestly, I have no idea what you are talking about.

Please use the ticket template to create a proper ticket we can work with.
