### ISSUE TITLE
Being alt-tab before reaching Stormwind flight point will clip my character in the textures.

### ISSUE THREAD

**Issue by Soseta27** [chromiecraft/chromiecraft#319]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Type here.
I noticed that if I am alt tabbed while flying to Stormwind when I get back into the game I will clip through the textures and go under the city. I will attach a video of it.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
Not clipping.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I used the flight from Westfall to Stormwind. Did not notice this happening from other places.
2. 
3. 
4.

##### EXTRA NOTES:

Type here. 
Link to video : https://youtu.be/tRMQy6Q6M4s

The skip in the video is me being alt tabbed. No idea why that part was not recorded.
 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Beastmasterwow** [comment]
Confirmed

**Comment by Stifler82** [comment]
Yes, I too confirm that: YOU SHOULD NOT DO **"ALT + TAB"** when you are in flight because you are moving around the map and the CLIENT gets messed up and it is not a very smart move! yes, I agree with you.. 👍
