### ISSUE TITLE
Onyxia's visual bug

### ISSUE THREAD

**Issue by Josarth** [chromiecraft/chromiecraft#3193]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Sadly i forgot take a screenshot during the battle, but happened on the two raids of my guild from last night. Basicly the visual bug was Onyxia doing a flying animation when she was on phase 1 and phase 3.

### Expected Blizzlike Behaviour

She should be with her claws over the ground attacking the tank without the flying animation from phase 2

### Steps to reproduce the problem

I was with my guild on Onyxia's Lair and when the tank pulled the boss, she started doing the animation like she was flying on phase 2.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0e35b681fb74045953b0babae5273f121dcaa05f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Hello, Josarth, I did my best to trying to triage the issue you were reporting, I recorded a video on the triage issue here: https://github.com/azerothcore/azerothcore-wotlk/issues/10998

Can you say is the issue you were having similar to the one I had during this testing encounter with Onyxia?

**Comment by Josarth** [comment]
> Hello, Josarth, I did my best to trying to triage the issue you were reporting, I recorded a video on the triage issue here: [azerothcore/azerothcore-wotlk#10998](https://github.com/azerothcore/azerothcore-wotlk/issues/10998)
> 
> I had a similar issue while fighting Onyxia with my guild this week. Can you say is the issue you were having is similar to the one I had during this testing encounter with Onyxia?

Hello, Dejanos. Yeah, thats the same issue. I'll raid with my guild again on next wednesday i hope it got fixed with any restart of the server!
