### ISSUE TITLE
Quest : [The Restless Souls]

### ISSUE THREAD

**Issue by Serakh90** [chromiecraft/chromiecraft#3194]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

The quest "[The Restless Souls](https://wowgaming.altervista.org/aowow/?quest=5282)" (part 2, the Egan's Blaster one) does not increment/complete the quest objective "Souls freed 0/15", despite the Blaster correctly spawning the [Restless Souls](https://wowgaming.altervista.org/aowow/?npc=11122) from Ghostly/Spectral Citizens and then transforming it into a Freed Soul.

I am not familiar with the SmartAI as is listed in the Database for the Restless Soul, but the Events 0-4 are working as far as I can tell (Transform to Freed Soul, follows PC around, despawns after 30 seconds), but event 5 and 6 seem to not happen. There is no emote playing at all, I assume it should be the Freed Soul saying one of [these](https://wowgaming.altervista.org/aowow/?npc=11136) quotes, and the "kill" is not credited.

### Expected Blizzlike Behaviour

I have no hard sources for this, but the objective counter should increment either right when the Restless Soul transforms to a Freed Soul, or possibly when the Freed Soul despawns. Obviously, it has to increase at some point for the quest to be completeable. Since I found no other Bug Report on this, I would expect that this had been working correctly at some point on CC, and broke again.

### Steps to reproduce the problem

This should be easy to replicate by just trying to complete the quest as intended, using the Blaster on either Spectral or Ghostly Citizen seems to make no difference.
1. Accept the Quest "[The Restless Souls](https://wowgaming.altervista.org/aowow/?quest=5282)" (part 2, the Egan's Blaster one)
2. Enter Stratholme and use Egan's Blaster on Ghostly Citizen and/or Spectral Citizen
3. Use Egan's Blaster on the spawned Restless Soul

### Extra Notes

Since I found no other Bug Report on this, I would expect that this had been working correctly at some point on CC, and broke again.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0e35b681fb74045953b0babae5273f121dcaa05f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment]
Somebody put wrong link and id order.  But i can't see why it's not saying anything on respawn. Someone needs to look into that. I will try again when I got time.
Fix:

> UPDATE `acore_world`.`smart_scripts` SET `id` = 0 WHERE `entryorguid` = 11122 AND `action_type` = 11;
UPDATE `acore_world`.`smart_scripts` SET `link` = 1 WHERE `entryorguid` = 11122 AND `action_type` = 11;
UPDATE `acore_world`.`smart_scripts` SET `id` = 1 WHERE `entryorguid` = 11122 AND `action_type` = 36;
UPDATE `acore_world`.`smart_scripts` SET `link` = 2 WHERE `entryorguid` = 11122 AND `action_type` = 36;
UPDATE `acore_world`.`smart_scripts` SET `id` = 2 WHERE `entryorguid` = 11122 AND `action_type` = 29;
UPDATE `acore_world`.`smart_scripts` SET `link` = 3 WHERE `entryorguid` = 11122 AND `action_type` = 29;
UPDATE `acore_world`.`smart_scripts` SET `id` = 3 WHERE `entryorguid` = 11122 AND `action_type` = 41;
UPDATE `acore_world`.`smart_scripts` SET `link` = 4 WHERE `entryorguid` = 11122 AND `action_type` = 41;
UPDATE `acore_world`.`smart_scripts` SET `id` = 4 WHERE `entryorguid` = 11122 AND `action_type` = 33;
UPDATE `acore_world`.`smart_scripts` SET `link` = 0 WHERE `entryorguid` = 11122 AND `action_type` = 33;
![stratho](https://user-images.githubusercontent.com/791788/158003002-5ffb2c2f-5dfb-401f-9fae-fc0ab6a83752.png)

**Comment by ishidinho** [comment]
Hey @Serakh90. Thank you for the report.

As you can see, a fix is already in the pipeline.

**Comment by ishidinho** [comment]
It will be closed automatically after the fix has been built into the project.

Stay tuned! :)

**Comment by fabi1010** [comment]
it doesnt work again :(
