### ISSUE TITLE
Permanent rain in Arathi Highlands

### ISSUE THREAD

**Issue by IcemanHHW** [chromiecraft/chromiecraft#3197]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Been leveling in Arathi Highlands these past week and it's been non stop raining while I'm there. No matter what time I log in it's raining there.

### Expected Blizzlike Behaviour

Normal weather cycle between rain and sun.

### Source

https://wowpedia.fandom.com/wiki/Weather_effects

### Steps to reproduce the problem

1. Go to Arathi Highlands
2. Experience non stop rain while walking around the zone.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a775ddcb5b935be3358644be27df282fc29a9936

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by TauraqRekt** [comment]
"Instead, each sub-zone among the 11 where weather is currently available is now linked to a set of variables that allow for the possibility of precipitation. The variables have been set to make the potential weather appropriate, meaning heavy showers are more likely in one region and drizzles in another. As Kaplan described it, the zone is practically asking itself whether there will be weather. "It's sort of randomly picking: 'I'm ready to rain but do I want to rain?' " he said. Duration will be chosen based on an automated system as well, with enough variables to make things unpredictable. "We didn't want it to be such a mathematical formula that somebody could literally sit with a stopwatch, log in, go to a zone and go, 'OK in two, one, go — it's going to rain.' "[[2]](https://wowpedia.fandom.com/wiki/Weather_effects#cite_note-mtvInterview-2)

As said by Kaplan. The AzerothCore source code may be different, but it also has a sort of randomness to it. Regardless, I have levelled loads of times in Arathi Highlands without rain. Can you perhaps back the issue up with some more details?

**Comment by IcemanHHW** [comment]
It could be related to the time I log in if you didn't experience rain each time. The times I logged in was between 19:00 and 22:00 GMT+1 and for a 2/3 hour play session it would be raining non stop. It could be that maybe I was just unlucky or it is time related because when I zone in now it isn't raining. So I'll close this issue for now and might open it again in the future depending on how the weather goes.
