### ISSUE TITLE
Entering and Leaving Combat | Trisfal Glades

### ISSUE THREAD

**Issue by Cromisaid** [chromiecraft/chromiecraft#32]
(https://youtu.be/Q7fGJsJYFM8) 

##### SMALL DESCRIPTION:
If you try to slay this NPC in Trisfal Glades, it won't be able to be attacked becouse of Entering & Leaving Combat issue.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should be damaged without entering and leaving combat (watch the video linked)

##### CURRENT BEHAVIOUR:
NPC ID 1538 [SCARLET FRIAR]
If you try to attack this npc it won't be able to take damages cuz of Entering and Leaving Combat issue, this is probably linked to the field in that area becouse the npc cannot attack you too.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to trisfal Glades
2. Take the quest (At war with the scarlet crusade)
3. Reach the same npc of the attached video
4. Try to hit him with spells from distance
(https://youtu.be/Q7fGJsJYFM8) 
##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by FrancescoBorzi** [comment]
what's the status of this?
