### ISSUE TITLE
Ban injustamente de cuenta 

### ISSUE THREAD

**Issue by caritnaegra** [chromiecraft/chromiecraft#3203]
Hello, good afternoon, it is the 10th day that I have closed my Fabian account.
Nairoby lvl 60 and macfly lvl 40 an administrator told me that VAT to review my account because it is not fair that they have closed it of course jahkers in theory ami (nairoby) was helping Carmen who was using pirate Addons in which he He apologized for whatsapp group
Then the administrator said that it's not fair that I get the sentence of permanent ban ah nairoby, I look forward to lifting the ban thank you very much

**Comment by ishidinho** [comment]
Hey @caritnaegra. We are only addressing game issues here at Github.

Please open a ticket in the #support channel at the ChromieCraft Discord.
