### ISSUE TITLE
Darkmantle energy regeneration procs on abilities

### ISSUE THREAD

**Issue by Icebeam666** [chromiecraft/chromiecraft#3210]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Darkmantle/Shadowcraft energy regeneration has a chance to proc on abilities such as Sinister Strike. 

### Expected Blizzlike Behaviour

Darkmantle/Shadowcraft energy regeneration should NOT be able to proc on abilities.

### Source

Taken from https://github.com/chromiecraft/chromiecraft/issues/2901 sources.
It seems only the ppm was fixed, not the chance to proc on abilities.

https://classic.wowhead.com/spell=27787/rogue-armor-energize#comments
By wingo667 on 2019/12/21 (Classic)
Proc rate was determined to be around 1 PPM per weapon, but it doesn't proc on yellow attacks (so weapon speed effectively doesn't matter). With Slice'n Dice and a bit of hit gear or talents, it should restore >72 energy per minute, for >12% more yellow DPS.

https://www.wowhead.com/spell=27787/rogue-armor-energize#comments
By 43387 on 2009/04/14 (Patch 3.1.0)
I got proc range somewhere between 2% and 4% so I can't say how good is that, and clearly relentles strikes seem way more relayable source of energy returns.

### Steps to reproduce the problem

Equip 4 pieces of Darkmantle gear as a rogue and test on dummy.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nueschts** [comment]
[PTR]
What abilities are you referring to in particular?
I was spamming the following macro and got not a single [Rogue Armor Energize], which is the set proc.
Use copius amounts of Thistle Tea ofc.

/targetenemy
/castsequence Sinister Strike,Eviscerate
/stopattack
/stopattack
/stopattack
/cleartarget
.cooldown

![WoWScrnShot_031722_234916](https://user-images.githubusercontent.com/61170874/158908918-f1d4664f-5d9a-4ad2-baaa-3d6aaba3eea1.jpg)

In contrast, only 1min of just melee swings was giving me some of the standard energy pocs you would expect.

![WoWScrnShot_031722_235044](https://user-images.githubusercontent.com/61170874/158909071-82846a23-6df7-421a-87ca-9ca9cb46492b.jpg)
