### ISSUE TITLE
[MC Loot] Majordomo

### ISSUE THREAD

**Issue by Hyperbearr** [chromiecraft/chromiecraft#3212]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Sometimes when we kill majordomo he only drops one item from the cache of the firelord in addition to the leaf/eye. 

### Expected Blizzlike Behaviour

He should always drop two items in addition to the eye/leaf. 

### Steps to reproduce the problem

Have been unable to verify the cause of this behaviour. Suspect that its tied to a bug where when the adds drop the belt/bracers and that causes the item reduction but have been unable to verify based on logs/vods/ptr testing. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nueschts** [comment]
[PTR]
Cannot reproduce this behavior.
Even with 2 boe from the adds i get normal chest loot.
![image](https://user-images.githubusercontent.com/61170874/159013263-5fa53bd4-49c7-46f8-bff6-ecb0a050a666.png)

**Comment by godnesso** [comment]
Adds dropping trash loot is correct (i have video proof) and has nothing to do with chest loot, however it happened to me today that we only received two items instead of three from chest (only priest quest item and cloth belt)

**Comment by ishidinho** [comment]
Hey @Hyperbearr. Thank you for the report.

There is a fix for adjusting the MC loot tables in the pipeline: https://github.com/azerothcore/azerothcore-wotlk/pull/11080.
This fix should cover your issues.

I will mark this report as valid.
