### ISSUE TITLE
[Quest] Escape Through Force: Can't turn it in

### ISSUE THREAD

**Issue by phonkala** [chromiecraft/chromiecraft#3216]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

https://wowgaming.altervista.org/aowow/?quest=994

Was doing full set of Darkshore quests. Can complete the quests but can't turn it in, Terenthis does not interact.

![volcor](https://user-images.githubusercontent.com/43609330/158949751-177225b9-a559-47ff-bdfa-5bad2d3199b2.jpg)

### Expected Blizzlike Behaviour

Should be able to turn in completed quests.

### Steps to reproduce the problem

Just complete the quest and try to turn it in.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment]
Can u try cleaning your cache? As alot simmilar issues posted here before is just cache issue. Thank you

**Comment by nueschts** [comment]
I encountered a similar issue while trying to follow this quest line on the PTR (and yes, i have cleared the cache and it didnt help :)).
This all starts at the npc [Terenthis](https://wowgaming.altervista.org/aowow/?npc=3693), where i only could get the quest [How Big a Threat?](https://wowgaming.altervista.org/aowow/?quest=984), which according to https://www.wowhead.com/quest=986/a-lost-master#comments:id=143152 is thought to be a prerequisite for OP's quest line.
After completing [How Big a Threat?](https://wowgaming.altervista.org/aowow/?quest=984) i was offered 2 more quests, the follow-up https://wowgaming.altervista.org/aowow/?quest=985 and [Thundris Windweaver](https://wowgaming.altervista.org/aowow/?quest=4761). However, after completing the second [How Big a Threat?](https://wowgaming.altervista.org/aowow/?quest=985), the npc somehow has no quests at all to offer.
![image](https://user-images.githubusercontent.com/61170874/159003297-33cc5d2b-9e9b-49b4-9a44-4e8557dbffc9.png)

Really seems to be related to earlier mentioned issues. Maybe some database references got mixed up. #3188

**Comment by nueschts** [comment]
Even after manually adding the follow-up [A Lost Master](https://wowgaming.altervista.org/aowow/?quest=986) and collecting the quest items, the npc remains unresponsive.
![image](https://user-images.githubusercontent.com/61170874/159004728-9b93f59d-280c-422a-a808-b811d6510c55.png)

**Comment by nueschts** [comment]
[PTR]
Killing Terentis and respawning him restored his responsiveness.
![image](https://user-images.githubusercontent.com/61170874/159007863-d26cc0db-5052-4339-bf7c-ce64fffc30da.png)

**Comment by nueschts** [comment]
Possilble connection to #3188 #452 #447

**Comment by Kosiak** [comment]
It was fixed already but some other changes was made that's questionable. Im looking into it now as i dont want to change anything without reason. Will update later.

**Comment by Kosiak** [comment]
The problem with this and other related to this npc is that Grimclaw is broken and he constantly running and doing its rp event. This breaks the events thats should happen with Terentis. I spoke with dev and they maybe able to sniff some data to see how it should work blizzlike. For now If u cant hand in or quests not available u need to wait Grimclaw to arrive and finish rp event.

**Comment by Dejanos** [comment]
> I encountered a similar issue while trying to follow this quest line on the PTR (and yes, i have cleared the cache and it didnt help :)). This all starts at the npc [Terenthis](https://wowgaming.altervista.org/aowow/?npc=3693), where i only could get the quest [How Big a Threat?](https://wowgaming.altervista.org/aowow/?quest=984), which according to https://www.wowhead.com/quest=986/a-lost-master#comments:id=143152 is thought to be a prerequisite for OP's quest line. After completing [How Big a Threat?](https://wowgaming.altervista.org/aowow/?quest=984) i was offered 2 more quests, the follow-up https://wowgaming.altervista.org/aowow/?quest=985 and [Thundris Windweaver](https://wowgaming.altervista.org/aowow/?quest=4761). However, after completing the second [How Big a Threat?](https://wowgaming.altervista.org/aowow/?quest=985), the npc somehow has no quests at all to offer. ![image](https://user-images.githubusercontent.com/61170874/159003297-33cc5d2b-9e9b-49b4-9a44-4e8557dbffc9.png)
> 
> Really seems to be related to earlier mentioned issues. Maybe some database references got mixed up. #3188

I can also confirm I am unable to take the follow up quest after completing How Big A Threat 1/2 and 2/2
![WoWScrnShot_040622_171550](https://user-images.githubusercontent.com/100415626/162008734-33a28acb-1350-44f2-8dcc-21a54a315aaa.jpg)

**Comment by ishidinho** [comment]
I was not able to reproduce the problem.

@Dejanos, since you were able to. Can you please create an AC report with your steps to reproduce the problem?

**Comment by phonkala** [comment]
Re-checked this quest few minutes ago and it worked correctly (on live), was able to complete right away. Wondering if server restarts etc could "reset" the npc, or maybe it's just fixed?

**Comment by Dejanos** [comment]
> I was not able to reproduce the problem.
> 
> @Dejanos, since you were able to. Can you please create an AC report with your steps to reproduce the problem?

I think the issue would be if someone after you or before you completed the quest and started the RP with Grimclaw, that could confuse the script and sometimes spawn double Grimclaws and not make the quest able to be completed in an interval of 15-20 minutes because of couple of Grimclaws RP-ing and spawning, there are at least 3-4 same issues like these reported here on the bug tracker from the past 10-15 days. Kosiak has the details.

**Comment by Gultask** [comment]
Not fixed yet as far as I know since someone else had the same problem just a few days ago. Killing Therentis or a server restart will fix the issue.
Unfortunately I do not know exactly what bugs out Terenthis, otherwise I would've opened an AC report myself. It seems to me that there's more than one trigger for it.

**Comment by Gultask** [comment]
Alright that's it. The culprit is definitely Grimclaw.
Here they are, on a local AC server, spawning without any triggers:
![WoWScrnShot_041222_003024](https://user-images.githubusercontent.com/100873791/162875062-85b90314-a1a6-4244-a2e5-ed5d48add4f1.jpg)
