### ISSUE TITLE
Molten Core - Golemagg loot table adjustment

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#3218]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Golemagg the Incinerator in Molten Core has a loot table that differs from the retail version.
Pieces of gear can drop in combinations that would be impossible in the retail version (mainly concerning Tier 1 chest armor).
Items that are unique to Golemagg's loot table, such as Azuresong Mageblade and Staff of Domination, drop less frequently than intended.

### Expected Blizzlike Behaviour

When reviewing videos of boss kills from both current WoW Classic and old WotLK, you can make the observation that the loot from Gehennas appears to be seperated into three different groups, as seen below:
![golemagg](https://user-images.githubusercontent.com/65633456/159104902-4d3769f3-c8ce-4f33-969c-64d9991dc353.JPG)
Shared Loot (Fire Creatures) refers to the shared pieces of gear that can drop from all 4 Fire creature bosses (Magmadar, Garr, Geddon, Golemagg), such as Mana Igniting Cord.
Golemagg drops three pieces of gear, one chosen from each group.
It appears to be impossible that loot from one group will be seen twice (e.g. you will never see Giantstalker and Cenarion chest armor simultaneously).
While it is impossible to know exact numbers, the chances for loot to drop appear to be roughly equal in G1 and G2, while unique items in G3 (Azuresong Mageblade for example) have a higher chance to drop.
There appear to be no differences between Classic and WotLK in how the loot tables are set up, aside from the fact that Horde players are now able to see Paladin armor and Alliance shaman armor.
I propose that drop rates in G1 and G2 should be roughly equal (20% and 25% respectively). Drop rates in G3 should be 25% for Azuresong Mageblade, 25% for Staff of Dominance, 25% for Blastershot Launcher and 25% for one of the shared items.

### Source

https://classic.wowhead.com/npc=11988/golemagg-the-incinerator

I am currently searching through videos and gathering data.
classic
https://www.youtube.com/watch?v=DXGNkNwtOVg
https://www.youtube.com/watch?v=E7_yKr6vZxU (no garr, domo, rag)
https://www.youtube.com/watch?v=gG_FA0Towjw (no domo, rag)
https://www.youtube.com/watch?v=21UVptdxQsI (no domo)
https://www.youtube.com/watch?v=U1ACQN0wXe0 (no harbinger)
https://www.youtube.com/watch?v=ub7O-Aj48wk
https://www.youtube.com/watch?v=gn6WBh-F2ak (only magmadar, geddon, shazz, golemagg, rag)
https://www.youtube.com/watch?v=dQjTibN6UKs

wotlk
https://www.youtube.com/watch?v=UElS1NoKhGY (geddon to domo)
https://www.youtube.com/watch?v=_BOL1lJqVJI (geddon to golemagg)
https://www.youtube.com/watch?v=Q7kX_nbDXE0 (golemagg only)
https://www.youtube.com/watch?v=SJWGA_dReMc (shazz to rag) (domo trash can drop boes) (same t2)
https://www.youtube.com/watch?v=LifbskEXzVY (golemagg to domo)

### Steps to reproduce the problem

.tele mc
Go to Golemagg and kill repeatedly.

### Extra Notes

Molten Core bosses have very unique loot tables, most certainly because of the many additions and changes to the loot done.

https://wowgaming.altervista.org/aowow/?npc=11988

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @godnesso. Thank you for all your hard work collection the loot tables.
As you can see, @Nefertumm implemented a fix for all your reports.

Again, many thanks!
