### ISSUE TITLE
Tab targeting when using a wand is not Blizzlike.

### ISSUE THREAD

**Issue by Kaiji-Kun** [chromiecraft/chromiecraft#322]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Tab targeting when using a wand works incorrectly. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

On Blizzard servers (I played from Vanilla to WotLK), it works as follows:

1. Target a unit
2. cast "shoot"
3. Wand attacks targeted unit
4. Press TAB
5. Wand switches to attacking the newly targeted unit

On Chromiecraft, tabbing to another unit while wanding leaves the wand still attacking the original unit.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Target a unit
2. Cast "shoot"
3. TAB to another target. Wand will continue attacking the originally targeted unity, when it should start attacking the newly targeted unit.

##### EXTRA NOTES:

I unfortunately couldn't find any references to the original way tab targeting worked from Vanilla-WotLK, but I am 100% certain after playing many casters that this was how it worked.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
I'm 100% certain this is not the way it worked.

**Comment by brumbles** [comment]
I've noticed similar issues with other spells too. Paladin tanking im used to pulling with Exorcism, mid cast i switch to another target to taunt/judge and I switch back to first target after exorcism cast. Therefore wasting taunt.

**Comment by Kaiji-Kun** [comment]
> 
> 
> I'm 100% certain this is not the way it worked.

Then what do you believe happened when you tabbed from one target to another while wanding? Do you believe the way it's currently implemented on Chromiecraft is correct? That if you want to attack another target while wanding you have to manually stop wanding and then start again on the other target?

I have never seen any other wand tabbing behaviour than what I described on any WoW server - official or private - apart from Chromiecraft.

**Comment by eTzmNcbkrng** [comment]
> 
> 
> I've noticed similar issues with other spells too. Paladin tanking im used to pulling with Exorcism, mid cast i switch to another target to taunt/judge and I switch back to first target after exorcism cast. Therefore wasting taunt.

@brumbles
This macro will prioritise your mouseover target to cast Righteous Defense if it is a friendly or Hand of Reckoning if it is an enemy.
In the scenario you describe, you could cast Exorcism on your primary target, mouseover a secondary NPC and pop off a Hand of Reckoning without switching your target.
```
#showtooltip
/use [@mouseover,help,nodead][help]Righteous Defense;[@mouseover,harm,nodead][]Hand of Reckoning
```


Same for Judgement which incorporates using a modifier to cast an alternate Judgement:
```
#showtooltip
/use [@mouseover,harm,nodead,mod][mod]Judgement of Justice;[@mouseover,harm,nodead][]Judgement of Light
```
