### ISSUE TITLE
[Warrior] Sword Specilization

### ISSUE THREAD

**Issue by The-Eyeful** [chromiecraft/chromiecraft#3221]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Currently Sword Specialization (https://wotlkdb.com/?spell=12815) does not grant the extra white swing when it procs from a damaging spell.  It only grants the extra swing on white attacks, or attacks that replace your next swing. 

<a href="https://imgur.com/ZL7UAAn"><img src="https://i.imgur.com/ZL7UAAn.png" title="source: imgur.com" /></a>

### Expected Blizzlike Behaviour

Any damaging spell a warrior does should proc the ability, and grant an extra white swing. 

### Source

https://wowwiki-archive.fandom.com/wiki/Sword_Specialization_(warrior_talent)?oldid=2501528

Under the notes section :
_It is a common misconception that Sword Specialization can only proc off of normal (white) swings. This is not the case and is likely confusion over [Windfury Totem]. Windfury only procs off of normal (white) swings. Sword Specialization procs from all damaging attacks, including special attacks. The extra attack is normal melee swing (white attack) and is always done by the weapon in the main hand._
_It counts [Whirlwind] as a single attack for chance of proc._

Granted that this info seems to be more direct towards vanilla, but the mechanic wasn't changed over the patches (outside the CD added). 

### Steps to reproduce the problem

1. Equip a sword or 2h sword on a warrior
2. Enable Sword Specialization in the talents
3. Use abilities on a target dummy
4. When you get a proc, go to combat log and check damaging spell procs

### Extra Notes

This issue seems to almost be identical to the issues Hand of Justice is experiencing. Bug report for that item (https://github.com/chromiecraft/chromiecraft/issues/2433) has been logged and known since early November of last year. Both of these would be greatly appreciated if they were fixed, more so the trinket, as it is a core trinket for basically every melee class to start of TBC. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by fendwe** [comment]
Could partly confirm this on the PTR.

Slam -> no proc
![WoWScrnShot_032322_231129](https://user-images.githubusercontent.com/61170874/159807124-32b3169b-c48f-48e4-9c48-040e3703f32b.jpg)

Rend -> no proc, only the following white swing procs the talent
![image](https://user-images.githubusercontent.com/61170874/159811169-2a32589d-3278-4f7e-a9db-a80bfd638c1e.png)

Cleave -> does proc
![image](https://user-images.githubusercontent.com/61170874/159809738-384b34b7-e12e-4129-94bd-fb72106038d6.png)

Mortal Strike -> no proc, only the following white swing procs the talent
![image](https://user-images.githubusercontent.com/61170874/159812054-297cc22c-dc80-4cae-8875-186b00d267f3.png)

Heroic Strike -> does proc
![image](https://user-images.githubusercontent.com/61170874/159812832-3e8c2f5a-fdb8-48d5-9c14-00c8b53ec733.png)

I noticed somthing strange though (or i'm too unfamiliar with warriors to know better).
When i had the warrior spamming [Slam](https://wowgaming.altervista.org/aowow/?spell=11605) on a target for almost 2min without initiating autoattack, [Sword Specialization](https://wowgaming.altervista.org/aowow/?spell=12815) would not proc at all.
![image](https://user-images.githubusercontent.com/61170874/159806442-04b56c04-870c-416f-ada0-8c926459463c.png)

Looks to me, as if only those abilities proc the extra attack, that replace the normal (white) swing.

**Comment by vvranceanu** [comment]
This was not fixed or the fix was somehow reverted. can we please reopen it?
