### ISSUE TITLE
Cant turn in the quest Gnogaine.

### ISSUE THREAD

**Issue by raltasha** [chromiecraft/chromiecraft#3224]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Pick up the quest @npc, run to Gnomeregan to turn item 1 into item 2 with the help of monster and run back to turn it in at @npc. Cannot turn it in.

Questid: 2926
Npc: 1268
item 1: 9283
item 2: 9284
monsternpc: 6213

### Expected Blizzlike Behaviour

You should be able to turn it in.

### Steps to reproduce the problem

Pick up the quest: 2926 from npc: 1268
In front of the Gnomeregan Entrance use Item 1: 9283 to get item 2: 9284
Go back to npc: 1268 and turn it in.

### Extra Notes

Npc: https://wowgaming.altervista.org/aowow/?npc=1268
Quest: https://wowgaming.altervista.org/aowow/?quest=2926
Item 1: https://wowgaming.altervista.org/aowow/?item=9283
Item 2: https://wowgaming.altervista.org/aowow/?item=9284
Monsternpc: https://wowgaming.altervista.org/aowow/?npc=6213

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nueschts** [comment]
[PTR]
Had no trouble completing the quest on the PTR.

![image](https://user-images.githubusercontent.com/61170874/159269165-1d255dec-53fa-425c-910f-c5e2ad3926a6.png)

The complete quest chain worked properly.

**Comment by raltasha** [comment]
After you wrote this i went there again and was able to finish it. There is literally nothing i did different. No redoing or whatever, He simply was there and i was able to turn it in. Sorry for causing trouble.
