### ISSUE TITLE
Molten Core - Firesworn immune to bleed

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#3225]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Firesworn, the adds from Garr, are immune to bleed.

### Expected Blizzlike Behaviour

Should be susceptible to bleed effects.

### Source

https://www.youtube.com/watch?v=wrSd5Qy1zR8 video from 3.3, you can see multiple Deep Wounds ticks at once from using Whirlwind on Garr adds

### Steps to reproduce the problem

Go to Garr in MC and try to apply and bleed effect on Firesworn adds (e.g. warrior's Rend)

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=12099

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nueschts** [comment]
In OP's linked video i was not able to make out the bleed debuff from the scrolling combat text. 
The only multi-target damage i could identify was [Cleave](https://wowgaming.altervista.org/aowow/?spell=845) and the Shadowmourne proc ([Soul Fragment](https://www.wowhead.com/spell=71905/soul-fragment) > [Chaos Bane](https://www.wowhead.com/spell=71904/chaos-bane#comments)).

However, i was able to find a video that clearly shows the [Deep Wounds](https://wowgaming.altervista.org/aowow/?spell=12834) debuff on multiple targets - at least in the combat text.
This is from a german client, so the text says Tiefe Wunden.
 source: https://www.youtube.com/watch?v=LXa5rAerdw0

**Comment by temperrr** [comment]
@fendwe I wish to talk with you. Can you contact me on discord (temper) :)
