### ISSUE TITLE
Molten Core - bleed immunity on elemental trash mobs

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#3226]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Several Molten Core trash mobs are immune to bleed effects.

### Expected Blizzlike Behaviour

Elementals should no longer be bleed immune in general, as an undocumented change appears to have removed these immunities somewhere in WotLK. Bosses like Ragnaros and Baron Geddon have already been fixed, but trash mobs are still immune to bleed. Going by logic, based on my source, I propose that all elementals in Molten Core should no longer be immune to bleeds.

### Source

Lava Spawn in this video with timestamp (https://youtu.be/gbs7hSVPYxI?t=223) from WotLK is affected by hunter pet bleed (cat Rake). Lava Annihilator gets Rake debuff at 3:30. Another moment when Lava Surger gets affected by Rake again at 4:33.

### Steps to reproduce the problem

Go test bleed (e.g. warrior Rend) on elemental Molten Core trash mob

### Extra Notes

affected npc ids
12265
12101
12100
12076
11665
11667
11669
11666
11668
also 12099 but this is already reported in #3225 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nueschts** [comment]
I have noticed myself that the elementals (excluding bosses) are immune to bleeding effects.
With regards to #3225, the only hint as to what has changed betwen the TBC immune and the WotlK bleedability, is the Patch 2.4 change to elementals.

>Non-corporeal [Undead](https://wowwiki-archive.fandom.com/wiki/Undead) and [Mechanical](https://wowwiki-archive.fandom.com/wiki/Mechanical) creatures are now susceptible to [bleed](https://wowwiki-archive.fandom.com/wiki/Bleed) effects.
[Elemental](https://wowwiki-archive.fandom.com/wiki/Elemental) creatures are no longer explicitly immune to poison and disease effects. Elementals with nature school immunities will still be immune to nature-based poisons, however.
(source: https://wowwiki-archive.fandom.com/wiki/Patch_2.4.0#Dungeons_and_raids)

It does not mention bleed effects, but i would guess that it might have been included there.
See also this comment, though it is prob more speculation than fact, as it is pre-2.4.

> Usualy Mechanical and Elemental bosses are immune to bleed and poison
Once 2.4 hit, all bosses wont be immune to bleed and only nature immune bosses will be immune to poison
(source: https://www.wowhead.com/forums/topic/what-raid-bosses-are-poison-immune-17280)

Could find a video though, that shows bleed effects on some other elemental mobs in MC:

[Firelord](https://youtu.be/eZYE5MVwALs?t=152)
[Firesworn?](https://youtu.be/eZYE5MVwALs?t=175)
[Lava Annihilator](https://youtu.be/eZYE5MVwALs?t=238)

**Comment by nueschts** [comment]
Possible connection to #579

**Comment by Dejanos** [comment]
I just tested and all Elemental mobs are bleed immune, went back and looked a lot of vanilla footage, and indeed all elementals were bleed immune Now also, I could not find a specific patch note where it says that has changed, unlike Undead and Mechanical. It all comes down to the devs right now what do they want to do with it, since we already have Onyxia who is not fire immune like her classic counterpart.

**Comment by godnesso** [comment]
do not review vanilla footage for this because in wotlk you can clearly see mobs being susceptible to bleed

**Comment by fendwe** [comment]
See also https://github.com/azerothcore/azerothcore-wotlk/issues/5915
