### ISSUE TITLE
Queuing specific dungeon does not give deserter upon leaving, and can instantly requeue

### ISSUE THREAD

**Issue by Contrubius** [chromiecraft/chromiecraft#3230]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When queuing for any specific dungeon using the RDF tool, a player does not get Deserter debuff upong leaving the party, leaving the current system vulnerable to people who farm for specific item in a specific dungeon on a particular boss, and leaving before dungeon is complete if the desired item does not drop. This can be particularly painful if the said person is a healer or a tank, which makes them almost irreplaceable.

### Expected Blizzlike Behaviour

Wowhead Blizzlike comment stating that  you do get a Deserter debuff even if you leave a specific dungeon group.

![Blizzlike RDF](https://user-images.githubusercontent.com/100415626/159671150-5ff0b45f-2cfb-4102-b388-4039af7ca095.png)

### Source

https://www.wowhead.com/spell=71041/dungeon-deserter#comments

### Steps to reproduce the problem

1. Queue for any specific dungeon.
2. Leave when you get inside.
3. See you did not get a Deserter debuff.

### Extra Notes

I discovered this the first time when I was in a hurry to join an UBRS group before finishing my specific dungeon RDF. Tested again on PTR.

Video detailing the issue: https://streamable.com/hher3z

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
Thanks for your bug report. I can confirm this issue.

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12763
