### ISSUE TITLE
Shaman - Elemental Focus - Wrong triggers

### ISSUE THREAD

**Issue by OA350** [chromiecraft/chromiecraft#3241]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

If you level as Elemental Shaman and pick the skill "Elemental Focus" https://wowgaming.altervista.org/aowow/?spell=16164
You sometimes get a buff for the next 2 spell casts to reduce mana cost.
This works well. 
However, lets say you have lightning shield enabled (or water shield) with 3 charges. And you attack a mob with a shock spell. You land a critical hit. You get the elemental focus buff with 2 charges. The mob attacks you, triggering a shield (either lightning or water, probably also goes for the other). You loose 1 charge of the shield, AND one charge of the elemental focus.

This means, a charge of elemental shield, even though its not a spell cast per se and doesnt cost mana, still consumes the elemental focus. Since this happens all the time, the elemental focus becomes nearly useless. Especially since you do not control when the shields trigger.

The casting of the shield itself also consumes the elemental focus. But this is a minor issue since you control when you cast it.

### Expected Blizzlike Behaviour

The shield charges should NOT consume the elemental focus. However I do not know about the casting of the shield

### Steps to reproduce the problem

1. Make Shaman (In my case Orc)
2. Get Elemental focus in the elemental tree
3. Cast lightning shield on yourself
4. Make a critical hit with a spell to trigger Elemental focus
5. Let a mob hit you
6. See how the elemental focus gets consumed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccb6d3e5a1401df8c9e99a384b9a5eead62441a1

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Was able to reproduce on the PTR. Expending a Lightning Shield charge consumes one charge of Clearcasting.

https://user-images.githubusercontent.com/100873791/161404188-3a732efe-e672-4ced-8c3d-11ae40e7468e.mp4
