### ISSUE TITLE
Ridge Huntress (ID:2732) on Badlands

### ISSUE THREAD

**Issue by Josarth** [chromiecraft/chromiecraft#3244]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

![WoWScrnShot_032522_120401](https://user-images.githubusercontent.com/74470790/160147534-ad51c751-a8f0-4599-874d-0cb25b5f1a99.jpg)

**Coordinates: 36.55 - 49.28**

Hi, Ishidinho. Sorry i thought was enough with the screenshot. Basically there is a npc with the 80% of his body levitating next to the rock. (But just i want to add i'm using the HD graph patch from the CC website and maybe the problem be there and not happening on a client with the original graph from wotlk)

### Expected Blizzlike Behaviour

I guess the body of the npc should be on the rock (but maybe is a problem on the HD graph patch)

### Steps to reproduce the problem

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccb6d3e5a1401df8c9e99a384b9a5eead62441a1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Josarth, please take a minute and add a short description what‘s wrong.

**Comment by acidmanifesto** [comment]
Does the npc move around or is it stationary in that spot? @Josarth

**Comment by Gultask** [comment]
This is the NPC. It does not move around like the other mobs on the ground.
It can be pulled and removed from that spot, and when the mob loses aggro, it will climb up the hill in several short 'teleports' until it eventually returns to its usual spot.

![WoWScrnShot_040422_014439](https://user-images.githubusercontent.com/100873791/161475549-3d8ddf0a-63a1-4693-b14a-9b84567e3851.jpg)

**Comment by Gultask** [comment]
Surpringsingly, this is Blizz-like behaviour, or at least it is in ClassicWoW.
Source: https://youtu.be/8viClKbvwgQ?t=1456
It may be hard to see, but the Ridge Huntress is in fact floating midair facing the hillside.
