### ISSUE TITLE
Incorrect respawn timer for the restauration buff in Battlegrounds

### ISSUE THREAD

**Issue by waowplayer** [chromiecraft/chromiecraft#325]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Restauration buff respawn timer in battlegrounds is several minutes.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Restauration buff respawn timer in battlegrounds should be 20 seconds.

evidence link from wowhead:
https://classic.wowhead.com/guides/classic-wow-warsong-gulch-advanced-intro-rules-timers-wsg

tl;dr screenshot of the relevant part from the evidence link above:
https://i.gyazo.com/0b52b1922f39bec5afeefd3eade914f0.png

##### STEPS TO REPRODUCE THE PROBLEM:

1. Join a battleground (for example, Warsong Gulch)
2. Take a restauration buff (for exemple, inside the hut in Warsong Gulch)
3. Notice how the respawn of the restauration buff takes several minutes instead of the expected 20 seconds.

##### EXTRA NOTES:

Spellid link for the restauration buff: 

https://classic.wowhead.com/spell=23493/restoration

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by JamesGent** [comment]
Can confirm. The evidence seems to suggest clearly what the timers were in vanilla, and there's no reason to believe they were changed in tbc or wotlk.
