### ISSUE TITLE
"Kim'jael's "Missing" Equipment" can't be turned in without relogging.

### ISSUE THREAD

**Issue by Satasataman** [chromiecraft/chromiecraft#3252]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Wasn't able to turn in the quest before relogging with the quest item in my inventory https://wowgaming.altervista.org/aowow/?quest=5534

### Expected Blizzlike Behaviour

I should be able to turn in the completed quest without relogging.

### Source
Before the relog
![1](https://user-images.githubusercontent.com/102460858/160274359-b55f1a90-a495-4f87-986f-fa6315b88fd2.png)

### Steps to reproduce the problem

1. Accept the quest https://wowgaming.altervista.org/aowow/?quest=5534
2. Get the quest item https://wowgaming.altervista.org/aowow/?item=13815
3. See the absence of question mark above the npc
4. Relog
5. See the regular completed quest behavior 
NPC DB GUID: 36158, current GUID: 22329
The quest npc: https://wowgaming.altervista.org/aowow/?npc=8420

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccb6d3e5a1401df8c9e99a384b9a5eead62441a1

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Was unable to replicate in the PTR.
The issue with missing quest markers & being unable to receive/complete the quest if the NPC has no gossip is not uncommon. A simple relog serves as a workaround.

![WoWScrnShot_040422_005554](https://user-images.githubusercontent.com/100873791/161471319-08ca0aa4-96e1-46f9-a9d3-9e7b399f3a38.jpg)

**Comment by Evelmike** [comment]
Using the /reload command in chat is also often successful as a workaround.

**Comment by IntelligentQuantum** [comment]
![Screenshot_20220407_100623](https://user-images.githubusercontent.com/14080516/162127693-143313ee-6242-483b-bd5f-9f654516697e.png)
