### ISSUE TITLE
Portal Seeker in Blasted Lands

### ISSUE THREAD

**Issue by Drundain** [chromiecraft/chromiecraft#3253]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Portal Seeker, a mob in blasted lands, does not spawn. I camped the area several times and never found him.

### Expected Blizzlike Behaviour

https://it.classic.wowhead.com/npc=5981/portal-seeker

He should walk in Kum Isha area a bit, I was looking for him because of a LW recipe he drops

![Untitled](https://user-images.githubusercontent.com/102469209/160281815-61338a91-63c9-4046-bc2a-288311de5afe.jpg)
.

### Source

https://it.classic.wowhead.com/npc=5981/portal-seeker

### Steps to reproduce the problem

Scout the area.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccb6d3e5a1401df8c9e99a384b9a5eead62441a1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Could not find Portal Seeker on the PTR either. More info:
Both [aowow](https://wowgaming.altervista.org/aowow/?npc=5981) and [wotlkdb](https://wotlkdb.com/?npc=5981) list them as "The location of this NPC is unknown." although [wowpedia](https://wowpedia.fandom.com/wiki/Portal_Seeker?so=search) claims that they were only removed from the game in patch 4.0.3

**Comment by Dejanos** [comment]
Mob has been definitely removed some time during TBC.
![Missing mob](https://user-images.githubusercontent.com/100415626/162075499-65089980-1387-4c30-81c2-637b593c4480.png)

**Comment by Drundain** [comment]
thank you all, i'm gonna obliterate a bunch of thugs in search of said pattern and closing the issue. Thanks again!
