### ISSUE TITLE
Quest - Excelsior - Elderly crocolisk is already spawned

### ISSUE THREAD

**Issue by OA350** [chromiecraft/chromiecraft#3265]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

https://wowgaming.altervista.org/aowow/?quest=628
When you get the quest, you go to the beach in the North west, and there is the elder crocolisk wandering around.

I waited after killing, and he respawned like a normal mob

### Expected Blizzlike Behaviour

You go there and kill normal Saltwater Crocolisk, until an Elder attacks you out of nowhere.

### Steps to reproduce the problem

1. Go to booty bay, finish the first two corcolisk quests
2. Get the Excelsior quest
3. Go to the northwest
4. Find the Elder Crocolisk already pre-spawned

### Extra Notes

![image](https://user-images.githubusercontent.com/76611816/160679334-93ca718a-edf8-42fc-bdbd-fe3c3ea47654.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccb6d3e5a1401df8c9e99a384b9a5eead62441a1

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by godnesso** [comment]
https://classic.wowhead.com/quest=628/excelsior#comments
_By Arashear on 2019/09/21 (Classic)
Contrary to the quest text, Elder Saltwater Crocolisk spawn normally north of Grom'Gol Base Camp (north-east of the island with elementals)._

Working as intended, not a bug.
