### ISSUE TITLE
[Quest] The Hunt Completed (ID=247) unavailable.

### ISSUE THREAD

**Issue by Zelfie** [chromiecraft/chromiecraft#3274]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

After completing the three hunting quests "Shadumbra's Head"(24), "Sharptalon's Claw"(2), "Ursangous's Paw"(23), Senani Thunderheart (NPC=12696) should offer the quest "The Hunt Completed"(247), but does not.

### Expected Blizzlike Behaviour

The Hunt Completed quest becomes available after completing all 3 hunting quests.

### Source

https://wowgaming.altervista.org/aowow/?quest=247
https://wotlkdb.com/?quest=247

https://classic.wowhead.com/quest=247/the-hunt-completed (Vanilla version the same)

### Steps to reproduce the problem

1. Complete quest 24 Shadumbra's Head 
2. Complete quest 2 Sharptalon's Claw
3. Complete quest 23 Ursangous's Paw
4. Npc=12696 Senani Thunderheart should now offer quest 247 The Hunt Completed, but fails to do so.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/856aed6fc6ad34fd07f1aa9df2a39c710ffd5b33

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Tried twice but I haven't been able to reproduce the issue in the PTR. And I'm fairly sure I had completed that quest during my casual playthrough in the main realm.


![hunt](https://user-images.githubusercontent.com/100873791/161394922-9eb7e33b-69ed-46ca-b128-b6c6a33d94ab.png)

**Comment by Zelfie** [comment]
Found the proper command to check, I had done this quest and my tracking addon had just failed to collect it.
Ignore this report.
Thanks  :)
