### ISSUE TITLE
Dabyrie Laborer's gains 2 extra attacks through Trash

### ISSUE THREAD

**Issue by orfaze** [chromiecraft/chromiecraft#328]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

https://wowgaming.altervista.org/aowow/?npc=2582
NPC gain some kind of windfurry, the 2 extra attacks can trigger more extra attacks resulting in crazy damage taken

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should not get "2 extra attacks"
Ability : https://wowgaming.altervista.org/aowow/?search=Thrash#npc-abilities
NPC in question does not appear in the "used by"

##### STEPS TO REPRODUCE THE PROBLEM:

1. ID npc = 2582
2. Getting hit by Dabyrie Laborer

##### EXTRA NOTES:

![Capture d’écran (12)](https://user-images.githubusercontent.com/81832274/113463194-cb91de00-9424-11eb-85c5-f255841ec094.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Confirmed, received 7 attacks in 1   : D

![image](https://user-images.githubusercontent.com/61223313/113663505-624ddd00-9667-11eb-98be-1016b9ff3297.png)

**Comment by Helias** [comment]
Hello S1ilker, when you triage an issue of ChromieCraft make a copy to AzerothCore of the issue and put it in the projects 1-19, 20-29, 30-39 or ChromeiCraft Generic to take track of the CC contributions progress please 🙏
