### ISSUE TITLE
Glowing Shard Quest

### ISSUE THREAD

**Issue by jivetolkein** [chromiecraft/chromiecraft#3286]
After killing all 4 bosses in WC you can get a glowing shard ... 1st step of quest is to travel to Ratchet where Sputtervalve should direct you on - when tried, he acknowledges the quest (you have the option to talk about the shard) but nothing happens - you aren't sent on to the next quest leg.

Just going to go there anyway and see if it works....

**Comment by Dejanos** [comment]
Hello jivetolkien, I have just talked to Sputtervale, after picking the option to talk more about the shard, I got the quest complete and on map I am directed to turn in quest on that mountain in the middle of Barrens. 
![WoWScrnShot_040422_140844](https://user-images.githubusercontent.com/100415626/161540940-517ac7c4-158a-4dc0-8042-37b981f40bc0.jpg)

If you cannot see this option I would suggest to:
1. Exit game, log back in and try to speak to Sputtervale again. If that does not work:
2.  Delete cache and try retaking the quest from the Glowing Shard.
