### ISSUE TITLE
Quest "More Dense Grinding" not working

### ISSUE THREAD

**Issue by lovemelovely** [chromiecraft/chromiecraft#3287]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Can't continue the quest "More Dense Grinding Stones". https://wotlkdb.com/?quest=7939 . I have reputation for this quest, and have mats, But not reaction to button "Continue".
My char name: Emili

### Expected Blizzlike Behaviour

To return Dense Grinding Stones for rep, complete quest Rituals of Strength until 2000+ of friendly, this one appears only after that, giving no further reputation.

### Source

https://wotlkdb.com/?quest=7939

### Steps to reproduce the problem

1. Have Friendly rep.
2. Go to Chronos NPC https://wotlkdb.com/?npc=14833
3. Choose quest More Dense Grinding
4. click on the button Continue . Nothing reaction

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/856aed6fc6ad34fd07f1aa9df2a39c710ffd5b33

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by lovemelovely** [comment]
Comment from resourse: "Although you can continue giving the Dense Grinding Stones you stop gaining reputation after friendly"

**Comment by Dejanos** [comment]
> Comment from resourse: "Although you can continue giving the Dense Grinding Stones you stop gaining reputation after friendly"

Hello lovemelovely, I have also read the comments on WoWHead regarding the quest, it seems it stops giving reputation after 2000 Friendly as expected, but player should still be able to turn in Dense Grinding Stones for the Faire Tickets. My character is also stuck on turning in quest and unable to get past the Continue button, which should not be happening. Also, as I have read, only players who have Blacksmithing profession of at least 1 should be the only ones to see this quest. So I would need a second opinion on this as it seems it is not working as expected in more than one way.

![WoWScrnShot_040422_142923](https://user-images.githubusercontent.com/100415626/161544061-cec7ad64-e7d8-46fb-9893-43b379600638.jpg)

**Comment by lovemelovely** [comment]
> Hello lovemelovely, I have also read the comments on WoWHead regarding the quest, it seems it stops giving reputation after 2000 Friendly as expected, but player should still be able to turn in Dense Grinding Stones for the Faire Tickets. My character is also stuck on turning in quest and unable to get past the Continue button, which should not be happening. Also, as I have read, only players who have Blacksmithing profession of at least 1 should be the only ones to see this quest. So I would need a second opinion on this as it seems it is not working as expected in more than one way.
> 

there is no any professions in the quest requirements

**Comment by Dejanos** [comment]
> there is no any professions in the quest requirements

You are probably right, but I have read some comments on WoWHead but they are still pretty vague about the whole profession thing. Anyway, the quest should not be stuck on continue, and should be only still rewarding Faire Tickets alone instead of rep after Friendly 2000. As for profession alone I am not sure, that is why I labeled it as in need of a second opinion.

![wowhead](https://user-images.githubusercontent.com/100415626/161551587-1de8d0e5-e459-4243-9517-21aee59e5def.png)

**Comment by Gultask** [comment]
This is the same issue as https://github.com/chromiecraft/chromiecraft/issues/2477, no?

**Comment by Dejanos** [comment]
> This issue has already been reported and confirmed by the dev team. See: #2477

You are right, they have also stated that the wrong NPC is handing out the quest, I was a little bit confused taking one part of the quest from 1 npc, and the next part of it from other, and he welcomed me like we did 50 quests together already.
