### ISSUE TITLE
Honor cap

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#329]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS (assumption)
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:
Honor cap should be 75k. A player reported in world chat that they exceeded 75k honor.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Honor cap should be 75k. 

##### STEPS TO REPRODUCE THE PROBLEM:
reach past 75k honor, e.g. using 
https://db.rising-gods.de/?item=44115

##### EXTRA NOTES:
sources:
- https://wowwiki-archive.fandom.com/wiki/Honor_point_(pre-4.0.1)#Honor_Cap
- https://www.mmo-champion.com/threads/640625-Honor-cap (indirect source, based on past discussions on retail)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
We decided to increase it, so it's not a bug.

**Comment by j-hdt** [comment]
ok, but what part about it is blizzlike?

**Comment by FrancescoBorzi** [comment]
> hm - is there a rule of thumb or some guidelines when to expect blizzlike behavior and when not?

usually we expect blizzlike, in some rare cases like this we do some minor customisations in order to improve the QoL of the player.

Thanks for your contribution efforts!
