### ISSUE TITLE
(creature_queststarter): Quest "More Dense Grinding Stones" given by wrong NPC

### ISSUE THREAD

**Issue by Si1ker** [chromiecraft/chromiecraft#3294]
Reported by **Silkarx**

### What client do you play on?

esES

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The quest [More Dense Grinding Stones](https://classic.wowhead.com/quest=7939/more-dense-grinding-stones) is being given by [Chronos](https://classic.wowhead.com/npc=14833/chronos)

* As the quest is given by the incorrect NPC, this makes the quest not completable at all.

![image](https://user-images.githubusercontent.com/61223313/161616777-26ed1722-533d-42bd-bd90-f9f06fb44628.png)

![image](https://user-images.githubusercontent.com/61223313/161616754-105b8e71-528e-43eb-bc45-bc8130fc33ae.png)

### Expected Blizzlike Behaviour

The quest [More Dense Grinding Stones](https://classic.wowhead.com/quest=7939/more-dense-grinding-stones) should be given by [Kerri Hicks](https://classic.wowhead.com/npc=14832/kerri-hicks)

### Source

[WoW Classic Guide to Darkmoon Faire](https://classic.wowhead.com/guides/classic-darkmoon-faire)

### Steps to reproduce the problem

Not required, see evidence above.

### Extra Notes

![image](https://user-images.githubusercontent.com/61223313/161616678-d264ffd5-0a3b-4266-b8b0-a09323c9638c.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/856aed6fc6ad34fd07f1aa9df2a39c710ffd5b33

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Issue is already known and has been confirmed by the dev team. See: https://github.com/chromiecraft/chromiecraft/issues/2477

**Comment by Si1ker** [comment]
Duplicate of #2477
