### ISSUE TITLE
Grimclaw spawns twice

### ISSUE THREAD

**Issue by OA350** [chromiecraft/chromiecraft#3296]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Grimclaw doublespawn

### Expected Blizzlike Behaviour

Grimclaw shouldnt exist twice

### Source

https://user-images.githubusercontent.com/76611816/161744682-13a4e1c3-2e43-4366-a879-0b3f4b28922a.mp4

### Steps to reproduce the problem

1. Go to ashenvale
2. Find grimclaw

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/856aed6fc6ad34fd07f1aa9df2a39c710ffd5b33

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Hello OA350, in steps to reproduce the problem, do you mean go to Darkshore to reproduce it, and not Ashenvale by any chance? Also, to what quest is this issue related to? Does it have anything to do with issues: 
#3188 or #3216 ?

**Comment by OA350** [comment]
Hi, yes you are right, It was darkshore. I think the linked issues makes it interesting. 
I wrote Ashenvale, since i was running from ashenvale to darkshore and saw the grimclaws quite early in Darkshore.

It seems to me, that for the linked quest, those bears spawn very far away in darkshore (south, close to ashenvale), and then have to run through all of darkshore, to complete the RP event? I was following them up to Terenthis where they then disappeared

**Comment by Kosiak** [comment]
Short version: Grimclaw is broken at the moment. I wont go explaining in here again. U can check my comments in #3188 and #3216.

**Comment by Dejanos** [comment]
> Short version: Grimclaw is broken at the moment. I wont go explaining in here again. U can check my comments in #3188 and #3216.

I guess since you are already on this and several linked issues that have been known and reported, this issue can be closed?

**Comment by Kosiak** [comment]
> > Short version: Grimclaw is broken at the moment. I wont go explaining in here again. U can check my comments in #3188 and #3216.
> 
> I guess since you are already on this and several linked issues that have been known and reported, this issue can be closed?

Im not on this unfortunately as i can't understand how this waypoints is right. I believe that they sniffed right. But then we need to understand how to utilise Grimclaw which shouldnt move from his position. So many questions and not enough answers.

**Comment by OA350** [comment]
Yeah #3188 seems to be the better issue with all the information. But poor grimclaw, running through all of ashenvale back and forth
