### ISSUE TITLE
Loot chests spawning issue

### ISSUE THREAD

**Issue by claymore147** [chromiecraft/chromiecraft#33]
##### SMALL DESCRIPTION:

During leveling in Elwynn Forest I have found issue with spawning of Battered chest, the world object. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be present only one chest per sub-location at a same time. 
For example: Elwynn Forest/Forest's Edge - there are given 3 coordinates where chest could spawn according to database. Game algorithm should decide which location select to spawn a chest. 

##### CURRENT BEHAVIOUR:

Coordinates
Actually, I have found 3 Battered chests present at same time in Elwynn forest/Forest's Edge at those coordinates:
24.4, 93.5
26.0, 92.1
27.8, 88.3

Coordinates corresponds with database: https://wotlk.evowow.com/?object=106318#contains
Coordinates of Battered chests for Elwynn's starting location: https://wotlk.evowow.com/?object=2843

##### STEPS TO REPRODUCE THE PROBLEM:

1. I have noticed same issue for every sub-location Elwynn Forest. Deducing from it, this issue applies overall for every location. So you could find root cause probably in this world's object code rather than in location's code section.
2. You can always teleport to coords I have stated or to different coords found in attached links to decide if my theory is true.
3. Bonus invention: In current Blizz version of wow, there is an additional rule - "Opening a chest without looting it will make it disappear after 5 minutes." This rule is made due to players with low bag space, that looted only valuable things from chests and in result they left half-empty chests with only junk containing for other players. Players finding only junk instead of treasure have been disapointed about developer's reward system before this invention.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by claymore147** [comment]
It seems to be applying for every world object supposed to spawn randomly across selected coordinates, look at this mine:
![WoWScrnShot_020321_095510](https://user-images.githubusercontent.com/78303208/106723020-f4554d00-6606-11eb-843d-d08f3b6d9533.jpg)

**Comment by FrancescoBorzi** [comment]
The fix is now on ChromieCraft. Thanks for your report.
