### ISSUE TITLE
Warsong flag not capping directly if standing on flag basement on flag return

### ISSUE THREAD

**Issue by orfaze** [chromiecraft/chromiecraft#330]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

If the flag carrier is standing on the flag basement when the flag is returned, the flag won't cap directly.
The FC must move away from the flag basement (usually near the center of the flag room) and get back on it to cap.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As soon as the flag is returned, the flag should be capped directly if standing on flag basement.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have both team capture the flag
2. One flag carrier stand on their flag basement
3. Return the team flag of the said flag carrier
4. Flag won't cap until fc moves away from the flag basement and returns to it

##### EXTRA NOTES:

This happened both on me (troll on alliance side) and on a warrior tauren, forgot the name (horde side)
https://youtu.be/UNA1Qkad-dY?t=775        from MOP
https://youtu.be/8hNn-193EVk?t=261         from cataclysm
This is also how it works on classic retail, I'm not playing SL sorry :( 
From my wow experience this is a bug I only encountered on private server

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Closed!
-
Video Test: [Warsong flag not capping](https://youtu.be/2LO7MDufaic)

**Comment by orfaze** [comment]
The blood elf should stand in the cap area (the red glowing light and stay there when the horde flag return to the base)
What will happen is : score will stay 0 / 0 because the flag won't cap
What should happen : horde should cap and get 1 / 0 without moving from that said glowing area

**Comment by H4Xx0R-PC** [comment]
Yeah, this is a bug on almost every private server regardless of the expansion. Not sure why this issue is closed with an invalid tag citing that video as evidence because it doesn't mean anything in the context of this bugreport.

**Comment by Stifler82** [comment]
> Yeah, this is a bug on almost every private server regardless of the expansion. Not sure why this issue is closed with an invalid tag citing that video as evidence because it doesn't mean anything in the context of this bugreport.

well, since you argue that the video I put in doesn't prove anything because it's not relevant to the issue.
I must deduce that then I did not understand the meaning of the report, so I think it is more productive to explain what I did not understand than to criticize my decision, don't you think?
since you seem to have understood the problem, would you be so kind to explain it to me better?  thank you..

**Comment by H4Xx0R-PC** [comment]
> 
> 
> > Yeah, this is a bug on almost every private server regardless of the expansion. Not sure why this issue is closed with an invalid tag citing that video as evidence because it doesn't mean anything in the context of this bugreport.
> 
> well, since you argue that the video I put in doesn't prove anything because it's not relevant to the issue.
> I must deduce that then I did not understand the meaning of the report, so I think it is more productive to explain what I did not understand than to criticize my decision, don't you think?
> since you seem to have understood the problem, would you be so kind to explain it to me better? thank you..

The current behavior is that when you carry the opposing team's flag, stand on the capture point of your own base and one of your team members returns your team's flag, the point for capturing the flag won't be gained. You would have to walk off the capture point and walk on it again to capture the flag. This is a bug and how it is supposed to work is that the flag should get captured instantly when a team member returns your flag while you're carrying the opponents while standing on top of the capture point of your own base.
