### ISSUE TITLE
Rogue Talent -Cheat Death bugged / Not working properly

### ISSUE THREAD

**Issue by Lac-lol** [chromiecraft/chromiecraft#3309]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

At this very moment, you seem to not gain/be reduced to 10% HP, considering the images I have linked below which clearly shows that sometimes you die from even the tiniest of dmg numbers a millisecond after Cheat Death proc.

### Expected Blizzlike Behaviour

"You have a 100% chance that an attack which would otherwise kill you will instead reduce you to 10% of your maximum health.
In addition, all damage taken will be reduced by up to 90% for 3 sec (modified by resilience). This effect cannot occur more than once per minute."

For example if you have a normal 4000 HP at level 60 as a rogue, when Cheat Death proc you will be reduced to 10% HP which is 400 HP.

### Source

Cheat Death - (death example)
https://imgur.com/a/eXnYqEC

Cheat Death - (death example)
https://imgur.com/a/Bc48Qbm

### Steps to reproduce the problem

1. Choose the Cheat Death talent and set your hp to anywhere between the normal 60 rogue 3000-4000 HP.
2. Get killed by another player, maybe try with different spells or abilities and watch the Cheat Death proc.
3. Check Combat Log and see (hopefully) the same results as I've been finding.

### Extra Notes

I am fully willing to test with you guys in order to show more in detail, if needed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Lac-lol** [comment]
+ Note:

I am not sure how much % reduced damage you are supposed to take considering it says "Up to 90% reduce and scaled by Resilience".
But I am sure that the "Reduce to 10% HP" is bugged, considering I keep testing and dyeing from as little as 40-50 damage after Cheat Death proc.

**Comment by Gultask** [comment]
Hello Lac-lol, thanks for your report!
I've tested numerous scenarios involving Cheat Death now, and it seems to be working as intended. Killing blows when above 10% were absorbed as much as needed for the rogue to reach 10% HP while Killing Blows dealt when below 10% were completely absorbed.

[Patch notes 2.4.3 are as follows](https://www.wowhead.com/patchnotes=2.4.3):
>Killing blows are no longer 100% absorbed. If the Rogue is below 10% health, the killing blow is still completely absorbed; if the Rogue is over 10% health, enough damage will be absorbed to reduce the Rogue’s health down to 10%. For the following 3 seconds, damage is not always reduced by 90%; it is now reduced by a maximum of 90%, depending on how much resilience the Rogue has. The damage reduction will be four times the damage reduction resilience causes against critical strikes.

[And Wowiki claims that](https://wowwiki-archive.fandom.com/wiki/Cheat_Death_(rogue_talent)?oldid=2294192):
>The [resilience](https://wowpedia.fandom.com/wiki/Resilience) required to reach the 90% damage reduction cap is 22.5% critical strike damage reduction, or 444 resilience.

This leads me to believe that with 0 resilience, the damage reduction shall be 0%, which is currently the case.

A couple more sources:
https://www.engadget.com/2008-06-18-understanding-the-cheat-death-nerf.html
> And the post-proc absorption has been changed to be resilience-dependent -- for every percent of resilience, you'll get 8% less damage when Cheat Death procs. (Resilience reduces damage by 2% from crits, times four, equals 8%.)

https://us.forums.blizzard.com/en/wow/t/cheat-death-bugged/984416/2
>Interesting, so it does nothing without resilience other than the initial absorb

>Yep, other than the initial absorb. Can be useful against big hitters to stop death then quickly vanish, but it basically does nothing considering 10% HP at 60 is like 400-450HP.

**Comment by Lac-lol** [comment]
Thank you for testing. I didn't know resilience played such a big role in this.
