### ISSUE TITLE
[Environment/Boats] Arrival sound for Boats is missing

### ISSUE THREAD

**Issue by Talthos** [chromiecraft/chromiecraft#3314]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Alliance boats currently lack an 'arrival noise' (docking bells) to broadcast that they've arrived.

### Expected Blizzlike Behaviour

When a boat arrives at a dock, it should use its docking bell to announce its arrival.

The sound file that gets used is "BoatDockedWarning.wav"

### Source

[Patch 2.1.0 (undocumented changes)](https://wowpedia.fandom.com/wiki/Patch_2.1.0_(undocumented_changes))

```Some boats now have a bell that they ring when they arrive at the dock.```

### Steps to reproduce the problem

Wait at any dock where a boat regularly arrives and departs.

Wait for a boat to arrive at the dock, and notice that it lacks a docking bell sound to announce its arrival.

### Extra Notes

[Here's a video example for the Stormwind boat to Borean Tundra. Yes, it's from the Cataclysm Beta, but I won't be able to record TBC Classic footage until I have spare cash to re-activate my TBC Classic subscription.](https://www.youtube.com/watch?v=RfZiQLiV4l0)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
[Found a video from October 2010 that shows the bell sound effect existing in the boat that connects Auberdine and Stormwind City](https://youtu.be/DNiJ9oPJdLk?t=404)

**Comment by Talthos** [comment]
> 

That was the video I was searching for, actually. Had it bookmarked, but lost track of it. Thanks!

**Comment by Dejanos** [comment]
Found this video as well that could be referencing the boat was giving a Bell sound when departing from the port as well: 
https://www.youtube.com/watch?v=yqGbpNZDt0Y

**Comment by Gultask** [comment]
I always forget when patch 4.0.1 dropped. Oct 12, 2010 gotta hammer that into my head.
I'll also add the video you linked, Dejanos, I've heard 2 bells at around 0:30 and 1:00 which are the bells for Northrend boat and the Auberdine boat, respectively.

**Comment by Talthos** [comment]
> 

Judging by the upload date of that video, that footage probably came from the Wrath closed Beta test.

Or perhaps one of the PTR versions.

**Comment by heyitsbench** [comment]
Can confirm boats are giving arrival bells on Wrath Classic beta.
