### ISSUE TITLE
“A Dip In the Moonwell” cannot be completed

### ISSUE THREAD

**Issue by sileniusmike** [chromiecraft/chromiecraft#332]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Controlling the robot near the moonwell and entering the moonwell and clicking “collect water” does not trigger anything. Relogging, retrying did not work. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Your quest should advance saying “Moonwell water collected 1/1” or similar.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be Horde and lvl 24
2. Get quest in 1k needles.
3. Control robot near Thalanaar
4. Enter Moonwell and try to collect water

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:
WINDOWS 10

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Cannot confirm, the quest works as expected
![image](https://user-images.githubusercontent.com/519778/113489195-12ceac00-94c3-11eb-8ff0-ee920624b6e7.png)

**Comment by Artanidos** [comment]
I have got the same problem. Pressing key "2" (for collecting water) the robot starts to attack.
