### ISSUE TITLE
Tiny Emerald Whelpling drop rate

### ISSUE THREAD

**Issue by Awkakelen** [chromiecraft/chromiecraft#3328]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

After 12 hours of farming Dreaming and Adolescent Whelps in Swamp of Sorrows (Southeastern part where the little dragons are), no Tiny Emerald Whelpling (BoE Companion) dropped. It's strange because similar time of farming would be okay if I was farming blue or red counterpart. It's also strange because after talking to my friends it seems like there were no Tiny Emerald Whelpling ever on auction house so far!

### Expected Blizzlike Behaviour

I'd check the loot tables for them if they are really dropping them. Also, the Tiny Emerald Whelpling SINCE patch 3.1 can also drop from Adolescent Whelps, which is strange because on some wotlkdbs it is shown that only Dreaming Whelps drop them.

### Source

https://www.wowhead.com/patchnotes=3.1.0

"Tiny Emerald Whelplings: May now (very rarely) drop from [Adolescent Whelps](https://www.wowhead.com/npc=740) in the [Swamp of Sorrows](https://www.wowhead.com/zone=8)."

### Steps to reproduce the problem

1. Go to Swamp of Sorrows
2. Farm Tiny Dragons for x hours
3. Get no dragon
5. Get sad
6. There were no 4th step.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Talthos** [comment]
[RisingGods database link.](https://db.rising-gods.de/?item=8498)

Droprate listed as 0.1%, which is a 1/1000 chance of dropping.

[AoWoW database link.](https://wowgaming.altervista.org/aowow/?item=8498)

Droprate also listed as 0.1%. Which, again, is a 1/1000 chance of dropping.

[Wowpedia's article on the Emerald Whelpling, which includes some helpful math to grasp how long it may take before seeing even a single drop.](https://wowpedia.fandom.com/wiki/Emerald_Whelpling)

![emerald whelpling drop probabilities](https://user-images.githubusercontent.com/5449068/162767541-3a5be59e-d075-4fae-8fd1-ae8fa9df1b69.PNG)

**Comment by Drundain** [comment]
but can someone looks into Adolescent Whelps loot table too? Wowpedia says: " [Adolescent Whelps] now drop this pet, in addition to [Dreaming Whelps]. " it was added in 3.1.0

**Comment by Gultask** [comment]
Using Keira3 I looked at the loot tables of both Whelps and found that they do drop the pet, although at a 0.1% chance.

**Comment by Drundain** [comment]
> Using Keira3 I found that the loot tables of both Whelps did contain the pet at a 0.1% drop chance.

great, i'll keep trying and post here the results. With a 6.30 minute respawn is it possibile to farm around 70 per hour. Lets say Awkakelen did 50 per hour, he killed about 600 whelps with no drop, which seems a reasonable amount since the drop is 1/1000.
I'll keep you posted

**Comment by Gultask** [comment]
Ok. I'll close the issue for now but everyone can still comment, and I'll reopen if needed.

**Comment by Drundain** [comment]
I got mine few minutes ago! I started counting 520 kills ago, but I definitely farmed for the same, or more, amount previously. I'm ballparking around 1000 kills for this. So no bugs at all, it is 0,1% indeed.
