### ISSUE TITLE
Can't go into Window Mode

### ISSUE THREAD

**Issue by Alfredorh** [chromiecraft/chromiecraft#333]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When trying to go into window mode the screen goes black, I can still hear the sound effects but the screen is black and the only way to get out from that black screen is hitting the ESC button but it will remain in the full screen mode... in other words it can't go into window mode.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It goes into window mode

##### STEPS TO REPRODUCE THE PROBLEM:

1. hit ESC to prompt the menu.
2. then select video 
3. then select Window mode

##### EXTRA NOTES:

none

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
it's not an issue of the server, you should try to edit the Config.wtf file in the `WoW/WTF/` directory
