### ISSUE TITLE
Latency Issue not present till a few weeks ago

### ISSUE THREAD

**Issue by Wubinski** [chromiecraft/chromiecraft#3335]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Not 100% sure if this is a bug but I was told to report it as such as well as open a ticket in discord, which I have.

I have an issue where my latency will spike super high, for a few seconds up to usually around 10 seconds. It jumps from my usual 163ms so anwhere between 500ms to 1000+. It comes and goes but happens pretty frequently, generally a few times every 5 minutes. It mostly happens in raids but it has randomly happened in cities, just out and about questing and whatnot.

I have tried verifying that it is my internet except I have excellent internet and have checked the status many times to make sure it isn't randomly dropping in speed. Also, this issue doesn't seem to happen with any other private server. I understand your host location is most likely different than the other private servers but this is an issue to ONLY Chromiecraft.

Someone suggested it could be a bug with region locking for internet possibly? I have no clue at this point. But I am located on the west coast US so, who knows. I've played Chromiecraft since the max was level 39 and have never had this issue up until a few weeks ago. Any input as to what could possibly be going on? I appreciate any feedback. Thanks!

### Expected Blizzlike Behaviour

Hopefully a stable connection? :(

### Steps to reproduce the problem

I could reproduce it just be logging in for longer than a few minutes. Like I said in my original answer it happens mostly in raids but also in cities as well as just randomly alone.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Lynethris** [comment]
Can you check some situation ? Have you deleted your cache ? Disable all addons? Is it specific to a char ? Is it specific to some regions or action ?

**Comment by The-GhostRider** [comment]
This bug is invalid, the reason is:
_That when the Latency is given by the Server, it is "Latency for everyone".
Instead, when the Latency is linked to the Individual and/or Individuals, (which means to an exclusive circle of people), the reasons are often related to: "your Internet line, Router, PC Hardware, Problems with your OS, WoW Addons, Broken WoW Client."_

So from what you have described, this is a problem limited to yourself and not with the whole server, for this reason I close the report.
