### ISSUE TITLE
Infinite Defias spawn in The Deadmines.

### ISSUE THREAD

**Issue by Bobbyxs** [chromiecraft/chromiecraft#3338]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

If you already have a Defias Gunpowder in your inventory when trying to pick up the barrel that contains the Defias Gunpowder (It is used to shoot the Defias cannon to open the doors) It will spawn a Defias enemy. You can spam click the barrel and it will indefinitly spawn enemies
![InkedWoWScrnShot_041122_085604_LI](https://user-images.githubusercontent.com/103505379/162953697-d69496a2-d1b7-45de-9866-eae33337b38d.jpg)
![WoWScrnShot_041122_085654](https://user-images.githubusercontent.com/103505379/162953858-6c1da262-e341-4024-af80-2bb667575310.jpg)
![WoWScrnShot_041122_085710](https://user-images.githubusercontent.com/103505379/162953962-73bfb51a-0a38-41a8-922c-639e55a1bf32.jpg)
.

### Expected Blizzlike Behaviour

I cannot find any instance of the barrel staying after being looted but i would imagine the barrel would simply dissapear or would no long spawn enemies after the first pickup.

### Source

I am sorry, I do not have any sources.

### Steps to reproduce the problem

1. Have a Defias Gunpowder in your inventory.
2. Spam right-click the Barrel.

### Extra Notes

https://wowgaming.altervista.org/aowow/?item=5397

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
I haven't been able to reproduce the issue, maybe it could be exclusive to RDF.
The barrel disappears on my side.

https://user-images.githubusercontent.com/100873791/162969994-cbed5bb3-8ee9-4965-8d4b-99e04644f33d.mp4

**Comment by fputs** [comment]
Tested, I was only able to get the barrel to be infinite and spawn repeated mobs while GM Mode was turned on. As soon as I turned GM Mode off the barrel worked exactly as expected. Not sure what that means, but it may help explain the behavior

**Comment by Gultask** [comment]
Was able to reproduce the issue now. You don't even need to be in RDF, just 2 people in the same instance is enough to make the barrel not despawn when interacted with.

https://user-images.githubusercontent.com/100873791/164451082-54d5dcb5-1b61-435a-b18f-2e64034b2095.mp4

.

**Comment by Gultask** [comment]
> I was only able to repeat the issue when GM Mode was turned on. As soon as I turned GM Mode off the barrel worked exactly as expected. Not sure what that means, but it may help explain the behavior

@fputs I had found this while searching for how to start world events in a local AC:
>When testing respawn times of gameobjects on your local AC server you need to have .gm off. Otherwise everything you gather , e. g. herbs, respawns immediately.
