### ISSUE TITLE
Enemy NPC faction opening door in Shadowfang keep

### ISSUE THREAD

**Issue by Bobbyxs** [chromiecraft/chromiecraft#3339]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The NPC Sorcerer Ashcrombie (Male Human) in Shadowfang Keep is friendly with me (Blood elf Female)
![WoWScrnShot_041222_083930](https://user-images.githubusercontent.com/103505379/162965568-0d20a659-10f8-483d-af46-359b1457aa99.jpg)
![WoWScrnShot_041222_084010](https://user-images.githubusercontent.com/103505379/162965596-a0c1e959-673b-420c-821f-83c9a58cb2e0.jpg)
.

### Expected Blizzlike Behaviour

Sorcerer Ashcrombie should not be friendly with the horde. He should be attackable and has a loot table.
https://wotlkdb.com/?npc=3850
There is a video of a group from Warmane going through and killing this same npc.
https://youtu.be/M_uUZqHehkQ?t=153

### Steps to reproduce the problem

1. Go into Shadowfang keep as a horde player.
2. Kill up to the first boss.
3. Talk to Sorcerer Ashcrombie instead of killing him.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Entering the dungeon normally as Horde will have Sorcerer Ashcrombie set as hostile. He's probably only friendly because you used RDF, which is modded to be cross-faction in Chromiecraft.

**Comment by Bobbyxs** [comment]
I see, That makes sense. Thank you.

**Comment by Gultask** [comment]
It's no problem. It takes way longer for you to open an issue than it takes for me to test it. Thanks for the report! ^^
