### ISSUE TITLE
Lesser Arcanum of Rumination "The item was not found"

### ISSUE THREAD

**Issue by HMalalita** [chromiecraft/chromiecraft#3341]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Zone: Burning Steppes, Flame Crest
NPC: Mathredis Firestar
Quest: Libram of Rumination

Bug: So I was trying to get the enchant of +150 mana (Lesser Arcanum of Rumination) which is the reward from the mision "Libram of Rumination". In order to complete the quest you need 4 items (Black Diamond, Black Blood of the Tormented, Gizzard Gum and the Libram of Rumination). I had all 4 items in my bag but when I was about to complete the quest a message appeared in my screen saying that the item does not exist or it can not be found (I don't remember the exact words because I can no longer complete the quest since the complete buttons shows in grey and you can not click it). I tried to relog and reload many times but the bug persists. I hope we can help each other. If you need more information feel free to contact me.
I hope you have a great day!

### Expected Blizzlike Behaviour

The expected behaviour should be the normal functioning of the quest. I should be able to recieve the reward of the quest.

### Source

Zone: Burning Steppes, Flame Crest
NPC: Mathredis Firestar
Quest: Libram of Rumination
![Bug WoW](https://user-images.githubusercontent.com/103541096/163075472-9d39d469-4007-496e-a7fd-6acb2ff7c6ac.png)

Game version: 3.3.5a

### Steps to reproduce the problem

1. Collect all items necessary to complete the quest (Black Diamond, Black Blood of the Tormented, Gizzard Gum and the Libram of Rumination)
2. Travel to Burning Steppes, Flame Crest
3. Speak to Mathredis Firestar to turn in the quest

### Extra Notes

My character: Elf Paladin (Horde)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Windows 10 Home, Sistema operativo de 64 bits, procesador basado en x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, HMalalita, thanks for your report! I hope you have a great day as well!

Could you take a screenshot with all of your bags open so that we can see all of the items you're holding? Just to make sure.

**Comment by HMalalita** [comment]
![image](https://user-images.githubusercontent.com/103541096/163077049-aae5fe18-4f60-4d9a-ba42-c77f3b1809b3.png)
U can see the 4 items in the middle of my bag. 
Thank you!

**Comment by Gultask** [comment]
The quest is working fine in the Test Realm.
Try closing down your game and clearing your cache, just delete the cache folder in your WoW installation folder. And then try to complete the quest again.

If that doesn't work I'd recommend you to open a ticket in the Discord under #support-ticket and 'Request help with your account/character' so you can get the enchant while we take a closer look at the issue.

![cache](https://user-images.githubusercontent.com/100873791/163078625-2cf493a6-0307-4479-b180-84e35af65e68.png)

**Comment by HMalalita** [comment]
Ty for the reply. I deleted the folder but It happens the same thing. I will try to get some help in the discord, ty anyways!

**Comment by phonkala** [comment]
I tested this too on PTR quickly and seems to work fine. You might wanna double-check you have the items in your inventory (and not accidentally in bank) and visit the npc again. Some addons at least show you have the items even if you got the actually stored in bank.
