### ISSUE TITLE
[Core] Armor Penetration Calculations Are Using Wrong Ratios/Values

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#3343]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Currently at level 60, it is requiring 4.27 rating to gain 1% ArP. 

### Expected Blizzlike Behaviour

According to the source provided (wiki dating Aug 2010; patch 3.3.5 released June 2010) the correct value for a level 60 character to gain 1% Armor Penetration on their character pane is 3.75 rating. 

### Source

https://wowwiki-archive.fandom.com/wiki/Armor_penetration?oldid=2351119

Under Armor penetration rating : 

ArP Rating required to ignore 1% armor
- **_Level 60 - 3.75_**
- Level 70 - 5.92
- Level 80 - 13.99

The source for the website data in the image is wotlkdb.com. It uses the same values as the DB provided by cromie, which is [Here](https://wowgaming.altervista.org/aowow/?item=17076). I'm not fully sure where this rating was pulled from, or how any website arrived to think this was the correct rating conversion. Cromie, and I assume a fair share of Wotlk Pservers, all seem to be using this ratio. 

<a href="https://imgur.com/3Ru26M3"><img src="https://i.imgur.com/3Ru26M3.png" title="source: imgur.com" /></a>

### Steps to reproduce the problem

1. Create a level 60 character on the PTR (pref plate user)
2. Equip a item(s) with ArP (thorium BS crafts have some)
3. Check the character under hit rating, ArP is listed there
4. It will return 4.27 rating per 1% (boots are 9 rating, and return 2.11%)

### Extra Notes

If the source is to be accepted as proof the values are incorrect, I have also prepared a data table to the correct scaling values for ArP per level. They are as follows : 

		lvl 60 = 3.75 / 1%
		lvl 70 = 5.92 / 1%
		lvl 80 = 13.99 / 1%
		
		lvl 60 to 70 rating = (5.92-3.75)/10
					= 0.217 rating per level for 1%
			61 = 3.967
			62 = 4.184
			63 = 4.401
			64 = 4.618
			65 = 4.835
			66 = 5.052
			67 = 5.269
			68 = 5.486
			69 = 5.703
			70 = 5.92
			
		lvl 70 to 80 rating = (13.99-5.92)/10
					= 0.807 rating per lvl for 1%
	        71 = 6.727				
            72 = 7.534
            73 = 8.341
            74 = 9.148
            75 = 9.955
            76 = 10.762
            77 = 11.569
            78 = 12.376
            79 = 13.183
            80 = 13.99

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by phonkala** [comment]
Checked the history of that wiki too, and there after launch of 3.0.0, I see percentual ArP changes in patches 3.1.0 (+25%) and 3.2.2 (-12%).

History page before the release of patch 3.1 (2 March 2009: https://wowwiki-archive.fandom.com/wiki/Armor_penetration?oldid=1793026) states that at level 60, 4.69 ArP rating is required to gain 1%.

So, before patch 3.1.0 one rating gives 1/4.69 ~= 0,2132 (%)

With the change in 3.1.0, ArP rating should give 25% more benefit:
1.25 * (1/4.69) ~= 0,2665 (%)
-> 1% requires: 1 / (1.25 * (1/4.69)) = 3.752 rating

And change in 3.2.2 reduces that again by 12 %:
0.88 * 1.25 * (1/4.69) ~= 0.2345 (%)
-> 1% requires: 1 / ( 0.88 * 1.25 * (1/4.69) ) ~= 4.2636 rating

So to me, current ArP values seem to be calculated correctly.

**Comment by Cooties-cc** [comment]
Very interesting. From your sources, yes the 4.26 seems to be the correct values, and the wiki was just never updated on the 3.2.2 changes. Looking here, https://wowwiki-archive.fandom.com/wiki/Armor_penetration?oldid=2062421 , this would be the 1st page past the 3.2.2 -12% change (September 22, 2009 is the patch, wiki page is October 1, 2009). Any page past Sept 22nd has not changed the values to the corrected ratios up to cata. What is even weirder is that using the math : 1 / ( 0.88 * 1.25 * (1/15.39) ) does in fact come out to the 13.99 cap for level 80 they posted on the wiki. It just seems that no one ever edited the prior values, and only focused/cared about the max level values. 

I'll go ahead and close the ticket with this new information.
