### ISSUE TITLE
Hunter pet aggro range for stealthed targets

### ISSUE THREAD

**Issue by Swindellite** [chromiecraft/chromiecraft#3344]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Hunter pets in aggressive stance find stealthed targets from very far away (The target is lv 60 stealthed with stealth talents and other stealth bonuses). The aggro range in pve has been increased (if I'm not mistaken) way back ago (spire, BRD phase), so if this applies to pets, that would explain the bug. This is quite abusable in pvp.

### Expected Blizzlike Behaviour

The pets in aggressive stance would not find stealthed targets from nearly as far away as they do now.

### Steps to reproduce the problem

Test with a lv 60 hunter and a lv 60 rogue with stealth talents, set the pet stance to aggressive and check how easily it finds the stealthed target.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, Swindellite, thanks for the report!

I tested in the PTR and it seems that un-instanced areas are fine. I'll try it in a battleground and will report what I find.

**Comment by Gultask** [comment]
Hello, Swindellite, thanks for the report!

I wasn't able to reproduce the issue, but I never PvP so I'm both not used to BG mechanics and the current PvP situation.
Here's how close I got to a pet set to Aggressive. I got the same results with a Subtlety-specced rogue.
![WoWScrnShot_041322_172950](https://user-images.githubusercontent.com/100873791/163265829-53fb4001-2e70-4e5e-a5d3-39f99f9bc008.jpg)

And out of stealth they were auto-aggroing at a reasonable distance, not unlike any other mob of a equal level.

But of course, this type of controlled testing isn't representative of an average battleground. So this issue could be due to a number of factors, some not even related to aggro range, so I'll let more people with PvP experience pitch in.

**Comment by TarekMadara** [comment]
The pet can aggro at a bigger distance than usual if the hunter is using [Track Hidden],

**Comment by Gultask** [comment]
Ahhh. Thanks, Tarek.

Here's my test:

https://user-images.githubusercontent.com/100873791/163844391-7fb89795-1f55-4054-a84d-ce49767f4da1.mp4

I'll try to see if this is intended behaviour or not

**Comment by TarekMadara** [comment]
Yes, and in my opinion it's a normal behaviour.

**Comment by Gultask** [comment]
@Swindellite is the video above representative of the stealth detection range you've experienced? Or was it farther than that?
