### ISSUE TITLE
10+ players in warsong per faction

### ISSUE THREAD

**Issue by orfaze** [chromiecraft/chromiecraft#335]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

10+ players in warsong.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Max players per faction is 10.

##### EXTRA NOTES:

Not sure how this happened.
Happen for both faction.

![Capture d’écran (13)](https://user-images.githubusercontent.com/81832274/113492126-db1d2f80-94d5-11eb-873e-715d121af435.png)
![Capture d’écran (14)](https://user-images.githubusercontent.com/81832274/113492131-dce6f300-94d5-11eb-81f8-f60c89455b5b.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
This is not a Bug, it is simply an "Exception".
Surely it happened that someone who was (already) inside the BG crashed, and in the meantime that he re-logged you remained in (19 total), then someone else joined the BG and you were 20 again, then the one crashed to re-log and you were 21, no bugs, just a coincidence..

**Comment by orfaze** [comment]
This kind of population in warsong is not uncommon during peak time
![Capture d’écran (22)](https://user-images.githubusercontent.com/81832274/114274916-d5b56d00-9a20-11eb-9e80-8d2a402196fa.png)

**Comment by Stifler82** [comment]
OK, it happened again, so there's a problem..
Thanks for your report.

**Comment by H4Xx0R-PC** [comment]
> 
> Surely it happened that someone who was (already) inside the BG crashed, and in the meantime that he re-logged you remained in (19 total), then someone else joined the BG and you were 20 again, then the one crashed to re-log and you were 21, no bugs, just a coincidence..

You can't be serious right?

**Comment by Yehonal** [comment]
@Helias maybe something to do with the CFBG, could you take a look and report on that module please?

**Comment by Yehonal** [comment]
> > Surely it happened that someone who was (already) inside the BG crashed, and in the meantime that he re-logged you remained in (19 total), then someone else joined the BG and you were 20 again, then the one crashed to re-log and you were 21, no bugs, just a coincidence..
> 
> You can't be serious right? You're literally describing a bug, even though that's not what happened in this issue, making that statement is just totally wrong.

yes he was wrong, he said it later in the other comment. Let's fix this bug

**Comment by Helias** [comment]
I'll have a look

**Comment by Yehonal** [comment]
![image](https://user-images.githubusercontent.com/147092/114928490-f1f74680-9e32-11eb-9fea-a2b531eac2f2.png)

@Helias you can look at this string in the code. It's from chromiecraft logs

**Comment by Helias** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/c49f687668a19ff6c7ecf38012d0085d4f6b1475/src/server/game/Entities/Unit/Unit.cpp#L13001-L13006

https://github.com/azerothcore/azerothcore-wotlk/blob/33aeadf8b623bbe8b33ed016c92463d35a4e863e/

**Comment by Helias** [comment]
the log is generated here, that indeed point that we overcome the max player per team

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Battlegrounds/BattlegroundMgr.cpp#L366

**Comment by iEmpress** [comment]
https://cdn.discordapp.com/attachments/863829480904982590/863829607446347796/unknown.png|

Confirmed it happened again today.
