### ISSUE TITLE
[Holiday Event/Noblegarden] Brightly Colored Egg

### ISSUE THREAD

**Issue by Talthos** [chromiecraft/chromiecraft#3351]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Looting a Brightly Colored Egg does not occasionally apply the Noblegarden Bunny transformation effect.

[AoWoW database link to the Noblegarden Bunny buff itself.](https://wowgaming.altervista.org/aowow/?spell=61734)

[AoWoW database link to a list of object entries for the "Brightly Colored Egg" world object; (aka, what you click on to loot the egg; there was more than one entry, so I'm listing all of them)](https://wowgaming.altervista.org/aowow/?search=brightly+colored+egg#objects)

### Expected Blizzlike Behaviour

Looting a Brightly Colored Egg should have a chance to apply the Noblegarden Bunny transformation effect on the player that looted it.

### Source

[Youtube video guide for the Noblegarden event, showing a player looting a Brightly Colored Egg and getting hit with the Noblegarden Bunny transformation effect.](https://www.youtube.com/watch?v=A0RQ0gGInC4&t=148s)

Video is dated as April 4th, 2010, which likely means it's from Patch 3.3.3a (just 3 patches away from the last WotLK patch).

### Steps to reproduce the problem

1. Search for Brightly Colored Eggs during the Noblegarden event.
2. Loot Brightly Colored Eggs during the Noblegarden event.
3. Observe how the Noblegarden Bunny transformation effect is _never_ applied to the player, no matter how many Brightly Colored Eggs are looted.

### Extra Notes
Tested in Kharanos.

[Also, footage of the Noblegarden Bunny transformation effect from the Patch 3.1 PTR in 2009.](https://www.youtube.com/watch?v=voLiNkLp6rQ)

Including this as supplementary evidence.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4ac565699fcb7b88fcc15db97ec9f14a0894f331

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @Talthos. I did the event on CC as well. In the end, I looted around 650 eggs and got the transformation several times.
So, I cannot confirm the issue that it _never_ applies.
