### ISSUE TITLE
Options not saving

### ISSUE THREAD

**Issue by tjbernal** [chromiecraft/chromiecraft#336]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Whenever I close the game it wipes and saved options I have throughout the whole game. Video/sound/keybind/addon charges are all gone and I can't figure out how to fix it

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All my saved options would be saving.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
this is a problem related to the client not to the server

**Comment by Helias** [comment]
Write me a specific way to reproduce this, I can bind any key, restart the client and can't see my key binded?

**Comment by tjbernal** [comment]
Yea with literally anything I change it gets reset when I log out of the
client. If I turn off the sound or change the resolution. Change a normal
build it interface option in the client it resets.

**Comment by Helias** [comment]
I've just tested it, I can't reproduce the problem.
Are you sure is not a problem of Addon / custom client?

**Comment by tjbernal** [comment]
It's just the client that I downloaded from the link on the website and I
don't have any add-ons, but I don't know how that would affect the built in
sound and video options. I'll try to do a fresh download and install again
and see if that works.

**Comment by eTzmNcbkrng** [comment]
Did you fix this?

**Comment by Stifler82** [comment]
@tjbernal 
Any news?

**Comment by mturca** [comment]
Check that the path where you saved the files is where your current windows user has full access. 
Also check for the files inside the wow folder so that they are not read only - the described behavior would be explain by that.
