### ISSUE TITLE
Head of Onyxia quest bugged after faction change

### ISSUE THREAD

**Issue by axweel** [chromiecraft/chromiecraft#3360]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Background information which might affect: Character previously was a Horde character. Faction changed to Alliance and recieved the Head of Onyxia (https://wowgaming.altervista.org/aowow/?item=49644).

Started the quest Victory for the Alliance (https://wowgaming.altervista.org/aowow/?quest=7495) but didn't receive the follow up quest Celebrating Good Times (https://wowgaming.altervista.org/aowow/?quest=7496) from Highlord Bolvar Fordragon (https://wowgaming.altervista.org/aowow/?npc=1748) as I am unable to see the NPC. I have confirmed with other alliance players that he is not available for me while they are able to see and interact with him.

### Expected Blizzlike Behaviour

After turning in Victory for the Alliance (https://wowgaming.altervista.org/aowow/?quest=7495) the next quest  Celebrating Good Times (https://wowgaming.altervista.org/aowow/?quest=7496) should be available to pick up from Highlord Bolvar Fordragon (https://wowgaming.altervista.org/aowow/?npc=1748) according to https://github.com/chromiecraft/chromiecraft/issues/3149.
### Source

According to https://wowgaming.altervista.org/aowow/?quest=7496 this quest is a series of 2 quests where you need to finish Victory for the Alliance (https://wowgaming.altervista.org/aowow/?quest=7495) before being able to start Celebrating Good Times (https://wowgaming.altervista.org/aowow/?quest=7496).

And according to https://github.com/chromiecraft/chromiecraft/issues/3149 the quest is supposed to start at Highlord Bolvar Fordragon (https://wowgaming.altervista.org/aowow/?npc=1748).

### Steps to reproduce the problem

1. Level a character 60 on the Horde side.
2. Finish the Onyxia attunement chain quest starting with Warlord's Command (https://wowgaming.altervista.org/aowow/?quest=4903) and ending with Blood of the Black Dragon Champion (https://wowgaming.altervista.org/aowow/?quest=6602)
3. Faction change over to the Alliance side.
4. Enter Onyxia's Lair and kill her.
5. Aquire Head of Onyxa (https://wowgaming.altervista.org/aowow/?item=49644#dropped-by)
6. Start the quest Victory for the Alliance (https://wowgaming.altervista.org/aowow/?quest=7495) by right clicking the item.
7. Turn the quest Victory for the Alliance (https://wowgaming.altervista.org/aowow/?quest=7495) at King Varian Wrynn <King of Stormwind> (https://wowgaming.altervista.org/aowow/?npc=29611).
8. Observe that you are unable to see Highlord Bolvar Fordragon and therefore can not pick up the quest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Hey,

The horde doesn't doesn't get converted to alliance on faction change. Doing the first quest in the chain (Dragon Menace) is enough to make the NPCs visible to you

Regards

**Comment by ishidinho** [comment]
Hey @axweel. Thank you for the very detailed report.

You will be able to see Fordragon after finishing the first quest of the Onyxia quest line „Dragon Menace“. See https://github.com/azerothcore/mod-progression-system/issues/150.
