### ISSUE TITLE
[BWL] Ebonroc timers

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#3364]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Shadowflame is cast 10 seconds after pull
https://github.com/azerothcore/azerothcore-wotlk/blob/49978883ce335c90b345a35e0ca6fc4a70e95cff/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_ebonroc.cpp#L64

and casted again every 10 seconds.
https://github.com/azerothcore/azerothcore-wotlk/blob/49978883ce335c90b345a35e0ca6fc4a70e95cff/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_ebonroc.cpp#L85

Wing Buffet is cast 30 seconds after pull
https://github.com/azerothcore/azerothcore-wotlk/blob/49978883ce335c90b345a35e0ca6fc4a70e95cff/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_ebonroc.cpp#L65

### Expected Blizzlike Behaviour

Shadowflame should be cast 18 seconds after pull and every 14 seconds after
Wing Buffet should be cast first after 31 seconds.

### Source

Timers documented in the latest DBM addon version of WoW Classic before the release of Season of Mastery.
https://www.curseforge.com/wow/addons/deadly-boss-mods/download/3483230

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Lynethris** [comment]
For wing buffet, unable to see this.

For shadowflame: first cast 0:26, 2nd cast at 0:44 (so it's done 18sec CC), 3th 1:06 (it's done 22sec CC), 4th 1:22 (it's done 16sec CC), 5th 1:45 (it's done 23sec)... The cooldown is random.

https://youtu.be/Ij4UV3daECs?t=29

**Comment by Lynethris** [comment]
> Source: https://youtu.be/Ij4UV3daECs?t=29
> 
> For wing buffet, unable to see the difference.
> 
> For shadowflame: first cast 0:26, 2nd cast at 0:44 (so CC is 18sec), 3th 1:06 (CC 22sec), 4th 1:22 (CC16sec), 5th 1:45 (CC 23sec)... The cooldown is random (maybe except for the first cast. Need to check more videos).

**Comment by Lynethris** [comment]
I have find more sources with BDM changelogs:

- Wing buffet seems to be 30sec (hard code in start combat). So all is good with CC.
- First cast of shadowflame seems to be after 18sec (hardcoded in dbm)

![Screenshot 2022-04-17 125746](https://user-images.githubusercontent.com/100411212/163711612-435c4b78-085d-40ed-8aaa-fe4258d20fe1.png)

**Comment by balleny** [comment]
be careful not to confuse cast_start and cast_success as the spell as 2 seconds cast time.
looking here:
https://vanilla.warcraftlogs.com/reports/qdtTQfNmYZGF1b6y#type=damage-taken&fight=18&ability=23339&options=4098&by=target
you can see Wing Buffet hitting at 0:33 secs infight - which means first cast starts at 0:31 secs infight.
second cast hits at 1:05, which means 1:03 start and is exactly 0:33 + 30 secs.

for shadowflame
https://vanilla.warcraftlogs.com/reports/qdtTQfNmYZGF1b6y#type=damage-taken&fight=18&ability=22539&options=4098&by=target
or
https://vanilla.warcraftlogs.com/reports/qdtTQfNmYZGF1b6y#type=damage-taken&fight=31&options=4098&by=target&ability=22539&view=timeline

actually point towards a not fixed delay between casts but some randomness in.
But, the minimum delay between casts still seems to be higher than 10 seconds
