### ISSUE TITLE
Drop rates screwed over in "The Rustmaul Dig Site"

### ISSUE THREAD

**Issue by kaisa1977** [chromiecraft/chromiecraft#337]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

So, yesterday I discovered this really nice farming spot on The Shimmering Flats, called "Rustmaul Dig Site". It's full of level 32-35 shilitids. I started farming there yesterday and got some decent raw gold, mithril from the near veins, and some blues. I got around 7 blue items in an hour and a half of farming. I went to sleep, I wake up, I log in...and the droprates are completely screwed. Been farming for almost the same time and have barely managed to fill my bags. Even the gray items the mobs have a high droprate% on, like "delicate insect wing" or "husk fragment" are dropping much less oftenly. I am dissapointed because I really found some hope to make gold by permafarming this place. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should be dropping as much as yesterday, that's it.

##### STEPS TO REPRODUCE THE PROBLEM:

Just go there (?)
I really want to know if the gms noticed I got too much gold and decided to nerf the droprates. 

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Hey, no, we didn't notice this, probably you were lucky that day.
Anyways, usually the players report when the drop rates are too high not when they are low, because the blizzlike behavior is not having easily blue items at once, so I think that you were really lucky, there should be not bug here.

Thanks for this report, next time when you report something, please, put some names or IDs of the NPCs that you want to mention
