### ISSUE TITLE
Warrior Quest Chain for lvl20+ Gear Cannot Be Completed

### ISSUE THREAD

**Issue by CollaredLioness** [chromiecraft/chromiecraft#3372]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Completing the Fire Hardened Mail quest (https://wowgaming.altervista.org/aowow/?quest=1701) is supposed to open four additional quests:
Grimand Elmore: https://wowgaming.altervista.org/aowow/?quest=1700
Mathiel: https://wowgaming.altervista.org/aowow/?quest=1703
Klockmort Spannerspan: https://wowgaming.altervista.org/aowow/?quest=1704
Furen's Armor: https://wowgaming.altervista.org/aowow/?quest=1782

Completing Fire Hardened Mail successfully opened the quest Furen's Armor, which I turned in and completed. However, it did NOT open the other three quests. I have completed the troubleshooting steps requested by the support team and still the quests do not populate.

Character: Cyonä (ä is created using alt code 0228)
Race|Faction: Draenei | Alliance
Level: 25
Level Required to Accept Quests: 20
Pre-Requisite: Fire Hardened Mail (Completed - This was also confirmed by support member Honey)

### Expected Blizzlike Behaviour

After turning in Fire Hardened Mail and Furen's Armor the other quests should populate so you can accept them from Furen. An example can be seen towards the end of this video taken from WoW Classic: https://www.youtube.com/watch?v=YijaFBfc5uQ

### Steps to reproduce the problem

1. On a Warrior complete the Level 20 Quest Chain until you reach Fire Hardened Mail.
2. Upon turning in Fire Hardened Mail you will then be offered the quest Furen's Armor which gives you the chest piece you were working on.
3. After clicking "Complete Quest" on Furen's Armor, he should then offer the next three quests to get the head, hands, and pants. Bug occurs here when the quests do not populate.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Ubuntu 20.04
Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by 55Honey** [comment]
Completed confirmed: https://wowgaming.altervista.org/aowow/?quest=1701

**Comment by Gultask** [comment]
Thanks for the report, CollaredLioness!

I can confirm, and it seems that the entire questline has problems which I think are related to race restrictions. I tried with all the alliance races. All of them unlock Furen's Armor, NE unlocks Mathiel, Dwarf and Gnome unlock Klockmort Spannerspan, Humans unlock Grimand Elmore and Draenei unlock none at all except Furen's Armor.

**Comment by CollaredLioness** [comment]
None of the guides created during Classic seem to touch upon the gear being race exclusive.

I tried going directly to a few of those involved in the quests and none of them offer the quests for the gear. It seems to only trigger if you get the initial quest from Furen himself. Whether it's supposed to be that way or how this private server functions, I'm unsure.

**Comment by Gultask** [comment]
May be an oversight of the guides, maybe. You can see in the source you posted that only 1 quest unlocked, and it's the quest that is available only to night elves.
It's still listed as race-exclusive in WoWhead for TBC Classic.

**Comment by Tebec** [comment]
According to Wowhead (main vs classic/TBC) comments the quests to go to the NPC but the quests can be gotten at the specific NPC, it's the second comment, I don't know how to link to specific comments. 
https://www.wowhead.com/quest=1701/fire-hardened-mail

**Comment by neifion-00000000** [comment]
![image](https://user-images.githubusercontent.com/91289495/173171295-d6a3cff0-415b-407f-b133-f0abb1f6927d.png)
Putting this here so it doesn't get lost, but in researching this I found something else wrong, these should drop 1-2 1x not 1-2x

**Comment by neifion-00000000** [comment]
(also confirmed Draenei can pick up the followups)

**Comment by Gultask** [comment]
Neifion confirms that the other equipment quests get unlocked as soon as Fire Hardened Mail is completed. Also, thanks @Tebec, when I was triaging this I had forgotten about that comment.
