### ISSUE TITLE
Baroness Anastari in Stratholme UD bugging out (Being invincible, group stuck in combat, then just ends)

### ISSUE THREAD

**Issue by slashbored** [chromiecraft/chromiecraft#3374]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

We fought Baroness Anastari when our tank (me) got MCed. After being MCed, the fight bugged out, making the baroness invincible and not attacking, so the whole team was stuck in combat for a good while, until she just dispawned and opened the door to the ziggurat.

### Expected Blizzlike Behaviour

It's been a while since I played strat, but afaik one member of the group should be able to get mindcontrolled and the fight shouldn't bug out afterwards.

### Source

Source is, I guess, my playthrough of Stratholme with some other people.

### Steps to reproduce the problem

1. Enter Stratholme (Undead)
2. Start the run.
3. Go to baroness (https://de.classic.wowhead.com/npc=10436/baroness-anastari) and fight her aloingside  a pack next to her.
4. Get mindcontrolled.
5. It resets/bugs out.

### Extra Notes

This only happened once so far for me.
I don't know that many technical details, about what happened, sorry!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Windows 11 (me playing, don't know about the server)

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by slashbored** [comment]
Hey, thanks for taking care. Ye, it could've been, that I didn't have aggro the entire time, some hunter pet? Idk. Like I said, it only happened once so far in a lot of Strat runs.

**Comment by Gultask** [comment]
Maybe if it MCs the pet, then? I'll try it out sometime when I get my local AC running again.

**Comment by temperrr** [comment]
Sadly, I am also unable to reproduce this issue. If you have more information, feel free to make a new report.
