### ISSUE TITLE
[Minor] Fraggar Thundermantle's gossip

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3379]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

[Fraggar Thundermantle](https://wowgaming.altervista.org/aowow/?npc=7884) is missing a gossip
____________________________________________________________________________
![WoWScrnShot_041922_222344](https://user-images.githubusercontent.com/79346412/164089474-2d388931-5321-4ace-ab88-a4712f6c0ce6.jpg)

### Expected Blizzlike Behaviour

He should welcome player with:
_"The spirits o' this land won't tolerate this dark magic and vicious sacrifice any longer._

_The Vilebranch have got to go!"_

### Source

https://wowpedia.fandom.com/wiki/Fraggar_Thundermantle

### Steps to reproduce the problem

1. Go to The Hinterlands > Wildhammer Keep
2. Speak with Fraggar

### Extra Notes

DB GUID: **92851** 
Entry: **7884**

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, Sathrenor!

[That info in wowpedia](https://wowpedia.fandom.com/wiki/Fraggar_Thundermantle?oldid=5374479) was only added in 16 February 2019, which was after Fraggar was relocated to Jintha'Alor, the Vilebranch Tribe main settlement, which would give the context for the gossip.
I tried to look for some videos of WoW Classic that showed his gossip but the only one I found had it obscured :/
I'll see if I can find any sources, if not, someone with a Classic subscription can check his gossip.

**Comment by Sathrenor** [comment]
My apologises then, didn't notice this detail.
And also didn't find anything related to him from before 2012, except one [video](https://www.youtube.com/watch?v=YcfG2oxaHOk) from 2016 where his gossip is a default:
 _"Greetings < name >"_, but cannot even state if it's from official WoW or private server.

**Comment by Gultask** [comment]
It's no big deal, don't worry about it ^^
I took a look at the comments and I'm pretty sure that video is from a private server.

**Comment by neifion-00000000** [comment]
![image](https://user-images.githubusercontent.com/91289495/173169233-23a81bc6-5a04-4bc1-a391-1f387c14c505.png)
Looks removed, when 44036 is retired a sniff related to this will be uploaded to the sniff collective but the sniff doesn't have anything to use obviously

**Comment by Gultask** [comment]
So it's blizzlike, then.
Thanks, Neifion!
