### ISSUE TITLE
[The Hinterlands] Rhapsody's Kalimdor Kocktail missing "on completion" dialogue

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3381]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

[Rhapsody Shindigger](https://wowgaming.altervista.org/aowow/?npc=5634) during the [Rhapsody's Kalimdor Kocktail](https://wowgaming.altervista.org/aowow/?quest=1452) quest do not start the drinking event.
___
![WoWScrnShot_042022_052720](https://user-images.githubusercontent.com/79346412/164145495-ed1b24db-a6bc-4402-afe8-070f8faf2f63.jpg)

### Expected Blizzlike Behaviour

Shindigger should start the following dialogue event after turning the quest:

_Rhapsody Shindigger says: Time to brew up a Kalimdor Kocktail! Hiccup!_
_Rhapsody Shindigger says: That should do it! Hiccup!_
_Rhapsody Shindigger chugs his drink._
_Rhapsody falls down._
_Rhapsody Shindigger says: Hiccup!_
_Rhapsody Shindigger says: Ok, who pushed me down? Was it you, <name>? Someone turn the lights back on. Hiccup!_
_Rhapsody gets back up and walks back to his keg._
_Rhapsody Shindigger says: One more sip of the ol' fire water and I'll be ready to talk. Hiccup! Cheers!_
_Rhapsody Shindigger says: So, Kalamah, I'm ready to tell you what happened in the Swamp of Sorrows. Hiccup!_

### Source

https://wowpedia.fandom.com/wiki/Rhapsody%27s_Kalimdor_Kocktail?diff=1569356&oldid=1569287
_Revision from 11 August 2008_

### Steps to reproduce the problem

1. Go to the Stormwind
2. Start the quest [In Search of The Temple](https://wowgaming.altervista.org/aowow/?quest=1448)
3. Follow the chain up to [Rhapsody's Kalimdor Kocktail](https://wowgaming.altervista.org/aowow/?quest=1452)
4. Turn the above quest
5. Observe the reaction (Or more like it's lack)

### Extra Notes

Rhapsody Shindigger:
_DB GUID:_ **92848** 
_Entry:_ **5634**

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
When you typed Arathi Highlands, I'm pretty sure you meant The Hinterlands? Anyway, I can confirm Rhapsody does not start the Roleplay after quest completion. 

![WoWScrnShot_042022_132344](https://user-images.githubusercontent.com/100415626/164220456-e8a9ce93-d742-4806-958f-81d0830d429e.jpg)


[Found this quest completion on Classic WoW as additional resource and proof of the behavior.](https://youtu.be/TZ6sz5sxo4Q?t=1616)

**Comment by avarishd** [comment]
fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/11654
