### ISSUE TITLE
Level range of Dungeonfinder incorrect

### ISSUE THREAD

**Issue by Monkizero** [chromiecraft/chromiecraft#3384]
What client do you play on?
enUS

Faction
Alliance

Content Phase:
all

Current Behaviour

I have noticed that it happens quite often, that you exceed the level of the Dungeon you were put in by the RDF.
Example:
As a lvl 24 Mage I was put into a Deadmines run. Most mobs were grey, only a few at the end were green. 
The WoW Wiki says that character range for Deadmines is ranged 15-21, yet the Ingame RDF tool says 15-25. 25 is way too high and should be reduced. On no other server I encountered similar problems. All Dungeons had appropiate levels for your character. Sure some mobs might be grey, but not the majority of them. So I think this is a bug and should be looked at.
At lvl 24 I overlevel the range by 3 levels. 2/3 of the mobs being grey is neither fun, nor beneficial to your character.

Expected Blizzlike Behaviour

All dungeons in RDF should have suitable level range for your character.
Reduce the max level per dungeon by 3, or take the values of the Wiki

No response

Join RDF at medium level. Be put in a dungeon below your level, with mostly grey mobs

Server:
Chromiecraft RP

**Comment by Gultask** [comment]
Hello, Monkizero.

Please use the templates provided when opening an issue: https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&template=bug_report.yml

As for your report, Chromiecraft and Azerothcore attempts to create an authentic experience of the 3.3.5 patch. So we follow what was the standard at the time, even if it sometimes doesn't make much sense or if it seems like a bug.
Here's the list of Dungeon Finder dungeons and their level ranges during patch 3.3.5: https://wowwiki-archive.fandom.com/wiki/Dungeon_Finder?oldid=2404648

If you want to make a suggestion regarding Chromiecraft, there is also a dedicated channel for it if you were unaware: https://github.com/chromiecraft/chromiecraft/discussions/categories/suggestions

Don't be discouraged from making any future reports or opening issues! We appreciate that you took time to create a github account to contribute to the project! ^^
