### ISSUE TITLE
Most open world humanoid mobs run away too fast

### ISSUE THREAD

**Issue by christiansonk1** [chromiecraft/chromiecraft#3387]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Most open world humanoid mobs run away at 100% speed when at low health, but in blizzlike they move slower. This has been observed in humanoid mobs in Mulgore, Hillsbrad Foothills etc. 

A good example is the mobs in Hillsbrad Fields, such as [Hillsbrad Peasant](https://wowgaming.altervista.org/aowow/?npc=2267), which will pull many mobs if you don't have a snare/slow available, making questing a pain there.

However, it seems not all mobs are subject to this bug. [Galak Marauder](https://wowgaming.altervista.org/aowow/?npc=4099) seems to walk away as per blizzlike behavior. Note that despite what the database shows, these guys are found in Thousand Needles. 

### Expected Blizzlike Behaviour

Humanoid mobs should walk away at a slower speed when at low health, though I do not know the exact value. From blizzlike experience, I believe this is about 50%. An observational estimate: whatever speed the Galak Marauder is at seems like the correct value. 

There are some discussions when googling this issue such as this [reddit thread](https://www.reddit.com/r/wowservers/comments/52p5pe/humanoid_fleeing_behaviour/), but I reiterate that I'm not sure what the exact speed values are. 

### Steps to reproduce the problem

1. Go to Hillsbrad Fields, damage a humanoid mob to low health. 
2. Observe that the mobs flee at 100% speed. 
3. Go to blizzlike classic, damage a humanoid mob to low health.
4. Observe that the mobs flee at X% speed (perhaps 50%?)
5. (Optional) Go to Thousand Needles, damage a Galak Marauder to low health.
6. Observe that the mob flees at X% speed. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, Christian, thanks for the report!

The fleeing mechanics in Azerothcore and, consequently, Chromiecraft, were implemented as 1.666% reduced speed per 1% health below 30% HP, up to a total 50% reduction at 1% health. You can see this behaviour in the Hillbrad Peasants too.

https://user-images.githubusercontent.com/100873791/164558443-d1f190a6-43d8-4433-973b-ff1b752299de.mp4

So the issue would rather be that they may be running away too early. The Hillsbrad NPCs currently flees at 30% HP (and I'm pretty sure that's correct), while the Galak Marauder flees at 15% HP, thus giving one a speed reduction while the other flees at full speed.

You can see at what health percentage they currently should flee at here: https://wowgaming.altervista.org/aowow/?npc=2267 & https://wowgaming.altervista.org/aowow/?npc=4099

**Comment by Gultask** [comment]
Thanks again for the report! I'll be closing the issue but don't let this discourage you.
If you find any mobs that are fleeing at an incorrect percentage of their health, please let us know!
