### ISSUE TITLE
Lake Elrendar Enemy NPC's dont enter in combat

### ISSUE THREAD

**Issue by GJDM99** [chromiecraft/chromiecraft#3388]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When attacking Enemy NPC's under Lake Elrendar (Ghostlands), they dont fight back. They just stay in place and reset with full HP, basically making them invulnerable and making the following quests imposible to complete:

1. Spirits of the Drowned
2. Vanquishing Aquantion

### Expected Blizzlike Behaviour

All Enemy NPC's in lake elrendar should be able to fight back and enter in combat normally under the water.

### Steps to reproduce the problem

1. Go to Lake Elrendar, in Ghostlands
2. Attack any Enemy NPC's under the lake Elrendar

### Extra Notes

1. https://wowgaming.altervista.org/aowow/?quest=9174
2. https://wowgaming.altervista.org/aowow/?quest=9274

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thank you for your report, GJDM99!

I can confirm.

**Comment by christiansonk1** [comment]
Interesting, I was able to complete this quest last week. Sometimes, the mobs didn't engage in combat underwater. I've seen this behavior with the Scalding Elementals in Thousand Needles.

**Comment by Gultask** [comment]
Yeah me too, seems to be quite a recent bug. Thanks a lot for reporting it so that the devs can take a look before the double xp weekend starts.
