### ISSUE TITLE
Hunter's pet - Cunning type - Cornered RELOG bug

### ISSUE THREAD

**Issue by lovelord83** [chromiecraft/chromiecraft#3390]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [X] 1-19
- [X] 20-29
- [X] 30-39
- [X] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

Hello all, 

I've noticed that there is something pretty weird with hunter's pets (cunning types) after unlearning all talents, assign new talents until Cornered talent, than relogging. 
I've tried to dps meter what happens and as you can see the Cornered talent effect, after relogging seems to be applied ALWAYS to target, even if pet is not under 35% life its attacks are a lot more powerfull than before (+25/30% than before) passing from 140-150 base white damage agains a lvl 60 dummy to 250-260 on the same target!

### Expected Blizzlike Behaviour

Cornered talent : https://www.wowhead.com/spell=53497

### Steps to reproduce the problem

I've recorded a full video review where I'm testing:

1) pet attack vs lvl 60 dummy with no talents
2) pet attack vs lvl 60 dummy with cornered talent
3) same test than before, but after relogging (not touching talents or other stuff)

Proof below

https://youtu.be/VVjjJavQBOo

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thank you very much for this report, lovelord.

I can confirm it.

**Comment by lovelord83** [comment]
I'm an hunter, but really can't conceive those player abusing about a bug, it is simply unfair. I'm playing a warlock too and playing in bg is like a pain against hunters. Now I can understand why a lot of them has the same pet... 
I'm proud I've done the right thing.

**Comment by Gultask** [comment]
Cornered is a fairly common talent to pick as BM and for PvP most hunters choose Cunning pets because they were simply made for it, so probably the vast majority of hunters that were benefiting from this bug were unaware of it.

Regardless, this was a very important issue and I thank you for bringing it forward.

**Comment by lovelord83** [comment]
Even after bug fixing seems that someone is still benefiting of it. I've noticed that playing in pvp against a specific player, once I've reached X damage (white one, base) from its pet and few games later, looking at combat logs, it was more and more higher than before. I noticed this more than once since bug fix pull request. I don't know how to reproduce it again, while I'm trying on dummy it seems to be solved, but maybe you can verify more in deep.

**Comment by Gultask** [comment]
I'll try messing around with it and see if I can find anything. If you find any way to reproduce it, open another issue and then I'll link it.
