### ISSUE TITLE
Most open world rare mobs don't drop Uncommons

### ISSUE THREAD

**Issue by christiansonk1** [chromiecraft/chromiecraft#3391]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Rare mobs in the open world don't drop uncommons most of the time. Recent rare mobs killed that did this are [Stonearm](https://wowgaming.altervista.org/aowow/?npc=5837), [Snort the Heckler](https://wowgaming.altervista.org/aowow/?npc=5829), [Thunderstomp](https://wowgaming.altervista.org/aowow/?npc=5832), [Vengeful Ancient](https://wowgaming.altervista.org/aowow/?npc=4030), and [Sister Riven](https://wowgaming.altervista.org/aowow/?npc=5930). 

I have not been able to test rare mobs that have a specific drop such as [Trigore the Lasher](https://wowgaming.altervista.org/aowow/?npc=3652#drops). 

This is a very minor issue, as ChromieCraft is generous with its BoE green and blue from regular mobs, allowing you to gear your character with ease - but it may break immersion for players who hunt rare mobs for gear or fun. 

### Expected Blizzlike Behaviour

As per [wowwiki ](https://vanilla-wow-archive.fandom.com/wiki/Rare_mob) and retail classic experience, most rare mobs (without unique drops) should drop an item from the uncommon table. 

Of course, there are many exception to this like [Sludge Beast](https://wowgaming.altervista.org/aowow/?npc=3295) who is known to drop two greens at a time, and the aforementioned unique dropping rare mobs.

### Steps to reproduce the problem

1. Visit and kill the NPCs that I mentioned above. 
2. Observe that an uncommon item is not dropped in the loot. 
3. (Optional) continue testing any other rare mobs, including ones with unique drops. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello again, christiansonk, thanks for the report!

Not getting loot from rares is certainly unsatisfying, but unless the rare in question has a specific 100% chance to drop a particular item (such as the rare elite in the entrance to Uldaman, for example) there won't be any changes to their loot tables.

You can see the stance the devs have on loot drops from rares here: https://github.com/chromiecraft/chromiecraft/issues/1893#issuecomment-995219427 and here https://github.com/chromiecraft/chromiecraft/issues/583

If you find any rares that should have a 100% drop rate of a particular item, don't hesitate to open another report for it.
