### ISSUE TITLE
[Minor][Felwood] Arko'narin's gossip

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3393]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Without completing the [Rescue From Jaedenar](https://wowgaming.altervista.org/aowow/?quest=5203), [Captured Arko'narin](https://wowgaming.altervista.org/aowow/?quest=5203)'s _(Warning: Dead link. Her other version [here](https://wowgaming.altervista.org/aowow/?npc=11018))_ dialogue is: 

_You've already done me a great service, . For that I thank you._ [...]
___
![WoWScrnShot_042222_123137](https://user-images.githubusercontent.com/79346412/164703165-86833ee0-871d-4475-8b8e-afb28ce3e63d.jpg)
![WoWScrnShot_042222_122527](https://user-images.githubusercontent.com/79346412/164703177-d99ec334-975b-40a2-b6b4-5bfb91b6cf76.jpg)

### Expected Blizzlike Behaviour

She should have 3 gossips

1.**When captured**:
_So cold... and hungry._

_My poor friend, I hope you've found peace. I can't stand to think about what they could have done to you._

_You! You there! Please, you have to help me escape. One of them has a key, can you find it? I know they have it. If you get it, you can help me get out of here. Trey is probably already dead, but there's still time! Please, can you help me?_ 

2.**After rescuing her, but before turning _(?)_ the quest _(which?)_:**

_You've already done me a great service, <name>. For that I thank you._

_The least I can do now is tell you what brought me here: My long time friend Trey Lightforge and I came to Jaedenar to investigate the Shadow Council when they caught us unprepared. They took Trey deeper into Shadow Hold and put me in here after taking all of our equipment... I can still hear his screams from below, . They were... inhuman. I don't know what they've done to him, but they will pay for it._

3.**When player returns to Shadow Hold after completing the [Rescue From Jaedenar](https://wowgaming.altervista.org/aowow/?quest=5203):**
_As you inspect the cage and the Night elf inside, you get an odd sense of deja vu. For some reason she does not make eye contact with you — it is almost as if you are not there to her._

### Source

_Character is no longer present after 4.0.3_

https://wowpedia.fandom.com/wiki/Arko%27narin

https://www.wowhead.com/npc=11016/captured-arkonarin#comments

### Steps to reproduce the problem

1. Go to Felwood, Shadow Hold
2. Speak with NPC before proceeding with the quest

### Extra Notes

**DB Guid:** 40428
**Entry**: 11016

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Confirmed, added some quest images from youtube for reference.

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/11622
