### ISSUE TITLE
[Felwood] Alshirr Banebreath's pathing

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3394]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

[Alshirr Banebreath](https://wowgaming.altervista.org/aowow/?npc=14340) goes through and under the textures of tree and ground while routing.
__
![WoWScrnShot_042222_123639](https://user-images.githubusercontent.com/79346412/164703989-bf59a422-8a36-4548-9a6e-ce16b1ef13f1.jpg)
![WoWScrnShot_042222_123643](https://user-images.githubusercontent.com/79346412/164703997-13847cfd-7f73-423b-8f54-72df401f944e.jpg)
_

### Expected Blizzlike Behaviour

Not certain the exact pathing, but I'm pretty sure he shouldn't even head off that far outside the camp. Or at least route following the actual path (the dirt one).
Unfortunately, all the references I found showed him more or less in place walking around.

### Source

https://youtu.be/XWUkkRXzJbo?t=291
https://www.youtube.com/watch?v=oJ8hInlmUoE

### Steps to reproduce the problem

1. Go to the rare mob's spawn location
2. Observe his movement

### Extra Notes

**DB Guid**: 51894
**Entry**: 14340

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, Sathrenor. 

I can confirm.

**Comment by Gultask** [comment]
Thanks for the report, Sathrenor.

I'm afraid that this issue has been reported already all the way back in October 2021 in https://github.com/chromiecraft/chromiecraft/issues/1914

Although I'd like to thank you for adding more sources.
