### ISSUE TITLE
Quest "book of the ancients" is bugged

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#3398]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Serpent statue does not summon the quest mob

### Expected Blizzlike Behaviour

it should

### Steps to reproduce the problem

try to do the quest. Statue does not summon the boss.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, [baranzadeoglu](https://github.com/baranzadeoglu)!

Quest is working fine on my end. Can you provide any more details so we can try to reproduce the bug?

https://user-images.githubusercontent.com/100873791/164801222-29429b27-84fb-4199-af44-81a61e2f3c41.mp4

**Comment by baranzadeoglu** [comment]
> Thanks for the report, [baranzadeoglu](https://github.com/baranzadeoglu)!
> 
> Quest is working fine on my end. Can you provide any more details so we can try to reproduce the bug?
> ancientbook.mp4

did exactly the same thing you did (maybe moved around a bit after clicking). Didn't work for some reason. Is this the live server?

**Comment by Gultask** [comment]
It was in the PTR and I just tested it in a local server as well and it's working fine.

Did the statue glow but the boss not spawn, or did nothing happen at all? Or was the statue not interactable?

**Comment by baranzadeoglu** [comment]
> It was in the PTR and I just tested it in a local server as well and it's working fine.
> 
> Did the statue glow but the boss not spawn, or did nothing happen at all? Or was the statue not interactable?

statue glowed, it was interractable. I tried a few times. Boss didn't spawn at all. Maybe something is wrong with my character. If a GM is willing to teleport me there I can check.

**Comment by freepizzas-dev** [comment]
I did this quest today, seemed to work OK on live ChromieCraft for me.

**Comment by CMHWoody** [comment]
I know this is old, but this happened to me as described below:

1. Killed an oracle to receive the quest drop.
2. Used the gem on the statue, which generated sound and a glowing holy beam into the sky.  No NPC appeared. Statue was not interactable.
3. Came here to find this bug logged.
4. Alt tabbed back to find the statue had reset (probably 5 minutes), and used the oracle gem again, and this time the NPC appeared (directly on the statue) and i was able to kill him and complete. So there is still a problem here, but not every time.  Maybe after someone completes it doesn't quite reset, so an every other time?
