### ISSUE TITLE
Lay on hands cannot be used in combat

### ISSUE THREAD

**Issue by Bolondpali** [chromiecraft/chromiecraft#3401]
### What client do you play on?

other

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

selecting no friendly targets or targeting enemies myself->lay on hands should be cast on self
what happens: using an ability causes a stutter like when u try to dispell someone out of range or line of sight, and the spell doesnt go off/ goes on CD but effect doesnt happen

### Expected Blizzlike Behaviour

Lay on hands goes off as intended

### Steps to reproduce the problem

Be in combat
Im usually tanking many mobs
Using lay on hands gets,,interrupted"?
the spell doesnt go off/goes on CD without effect

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Hello, Bolondpali, are you sure you didn't have Forbearance debuff on yourself when you tried casting Lay on Hands on yourself? It prevents you from casting LoH on yourself for the duration of the debuff.

**Comment by Gultask** [comment]
It could have been a latency issue as well if you were waiting to use it at the last second.
It's working fine in the PTR from what I've seen.

https://user-images.githubusercontent.com/100873791/164912768-de09c6ae-82b7-446b-804e-2201b219a704.mp4

**Comment by The-GhostRider** [comment]
As in Gultask video, I am also unable to reproduce this supposed Bug, plus if this problem was real, from: Apr-23-2022 (when this post was created) until today, Jun-7-2023 there there would be other reports about this issue, and there aren't, so I assume it doesn't exist, since there aren't others complaining about the issue, I believe as Contrubius suggested, you probably had a Debuff preventing the Lay on Hands effect, and you didn't notice it.
So for this reason, I close the Report.
