### ISSUE TITLE
Open world items after leaving the dungeon

### ISSUE THREAD

**Issue by pangolp** [chromiecraft/chromiecraft#3402]
### What client do you play on?

esES

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I was doing a dungeon, and when I finished the dungeon, I used the search engine to leave without leaving the group. I was ready to continue doing a mission in which I was, I killed 2 npc, and when I wanted to get the loot that they left, I noticed that it did not let me with the legend: "I do not like to steal". When I looked and although it said that the loot was mine, I realized that they were still in a group, so I dismantled the group, and then, when I killed the next npc, the loot was normalized.

### Expected Blizzlike Behaviour

When returning to the open world map, even if I am in a group, if my group mates are not near my position, the loot should be mine. I understand that if they are close, there could be a situation that if we have group loot, the objects do not touch me, but if we are in different maps or areas, the loot should be able to get it.

### Source

As a source, I can provide a fragment of the video, where I record what happened. The video is longer, but I will put the exact moment where the problem occurred. https://youtu.be/Cy5ALdmJzNE?t=1721

### Steps to reproduce the problem

1. Enter a dungeon through the search engine.
2. Finish it or not (I don't know if it always works).
3. Leave the group while killing enemies. (see video).
4. Continue with an open world quest.
**And possibly do not let you strip the items.**

### Extra Notes

None

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by pangolp** [comment]
Reviewing the video, I realized that in reality, the error occurs when you are in combat, within the group and then, you leave it. In the video you can reproduce the situation well.

**Comment by Gultask** [comment]
Hey, Stevej, thanks for the report!

I asked one of the devs about this and they said that the loot would be indeed tied to group after you tagged the creature, so if you left the group you would no longer be able to access the creature drop window, resulting in that error message. So this should be intended.

**Comment by pangolp** [comment]
I don't know if I explained myself in the right way, but I don't think it's right that after leaving a dungeon, if you continue in a group, the items still belong to the group, since they are not people you are playing with. They are random people. It would be different if they were people you were playing with before you entered the dungeon, that would be considered normal. But well, if you think it works well, then it will stay that way. I still insist that it should not be that way, and in fact, I attach the video, because I was really struck by the way it happened.

Greetings.

**Comment by Gultask** [comment]
I understood you with no problem 😄. And I know, it sounds wrong to me as well, but from what I understood this was only changed when personal loot was introduced and mob tagging was removed.
The issue here, from what I understand, is exactly what you said in the comment, this happened because you left the group mid-fight when the mob was already tagged, so the loot "belongs" to the RDF group.

**Comment by pangolp** [comment]
Exactly, that's the problem. You leave the instance / dungeon, and without realizing it, you are still in a group, which means that the next npc you kill in the open world does not allow you to get the loot. You would have to make the player leave the group when leaving the instance if the instance was finished (maybe). Not if he leaves without finishing, because that would cause him to get a deserter. But if it is finished, that is, you get the loot or something, you would have to see if you can't get something. Because if not, you are forced to leave the instance and in turn, to check if you are still in a group or not, before continuing with the rest of the missions. (It sounds strange to me, that the logic works that way, but the truth is, I have no more information).
