### ISSUE TITLE
AV alliance mine leader Aggi Rumplestomp can't be attacked as horde (crossfaction?)

### ISSUE THREAD

**Issue by DaviddOrs** [chromiecraft/chromiecraft#3403]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

After taking Coldtooth mine, this was attacked by alliance. 
I am currently playing as alliance (crossfaction bg as horde). 
They killed the NPC leader of the mine from our faction and I was unable to attack the Allied one (Aggi Rumplestomp).
Other NPCs were red and therefore attackable, but not this guy.
I have uploaded a screenshot here for your reference:https://imgur.com/a/9bw0c2A

### Expected Blizzlike Behaviour

Enemy NPC should be "hostile" and not appear as friendy when crossfactioning.

https://imgur.com/a/9bw0c2A

### Source

wowhead

### Steps to reproduce the problem

1. Assault mine while crossfactioned
2. Have a friendly NPC spawned
3. When this friendly NPC is killed, the new one can't be attacked (friendly) nor attacks.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, DaviddOrs!

I can confirm. The issue doesn't extend to his Horde counterpart, Masha. Only Aggi seems bugged.
The Irondeep Mine doesn't have an issue.

In short: Horde players cross-factioned into Alliance see Aggi as an hostile npc, while Alliance players cross-factioned into Horde see Aggi as friendly.

Aggi:
![WoWScrnShot_042322_164459](https://user-images.githubusercontent.com/100873791/164944140-a17d2b27-84d5-4aaf-b878-a9334c60b156.jpg)
![WoWScrnShot_042322_164504](https://user-images.githubusercontent.com/100873791/164944144-910f93cb-1d9b-49c4-954d-8492b626585a.jpg)

Aggi's counterpart, Masha
![WoWScrnShot_042322_164515](https://user-images.githubusercontent.com/100873791/164944158-2cdc8de8-7950-4bdb-bb67-53852ccb300e.jpg)
![WoWScrnShot_042322_164512](https://user-images.githubusercontent.com/100873791/164944162-bb727566-e4fb-438f-b130-21e2abba0ad7.jpg)

Killing Aggi as a cross-factioned Horde -> Alliance can lock Coldtooth Mine as alliance until he respawns.
![WoWScrnShot_042322_164536](https://user-images.githubusercontent.com/100873791/164944200-aa9f016f-0aa6-42a3-95ac-b38f15e1241a.jpg)
