### ISSUE TITLE
Warlock spells vanished

### ISSUE THREAD

**Issue by Kaiji-Kun** [chromiecraft/chromiecraft#341]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Type here.

Hit level 24. Blood pact and Sacrifice have both disappeared from my Imp and Voidwalker's pet bars.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

These spells shouldn't disappear.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Hit level 24 on a Warlock
2. Check pet bars

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Cannot reproduce, anyways if you open the spellbook you can easily restore them.
If this disappearing happens continuously, leave a comment here.

**Comment by FrancescoBorzi** [comment]
@Helias don't forge the labels ;)

**Comment by j-hdt** [comment]
Can confirm this issue - had it once for each pet that the spells where removed from the pets bar.
Unfortunately, cannot reproduce it. But, I can confirm the issue

**Comment by Stifler82** [comment]
> Can confirm this issue - had it once for each pet that the spells where removed from the pets bar.
> Unfortunately, cannot reproduce it. But, I can confirm the issue @Stifler82


@j-hdt 
If you would be so kind enough to open a new issue (but done well, with NPC / SPELL ID and "NAMES", "SURNAMES", "HOUSE NUMBERS", etc ..) you would do me a great courtesy, I would appreciate it very much.

You don't need to make a Long report, we just need a concise but detailed report.
Thank you.
