### ISSUE TITLE
Item drop chance from Satchel of Helpful Goods depends on armor type

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#3412]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

A Satchel of Helpful Goods (id 52001, the RDF bonus bag for level 35-45) contains either a ring or a shoulder. Right now the ratio between ring and shoulder depends on armor type, which does not make sense.

I first saw a bug report on AC's GH: https://github.com/azerothcore/azerothcore-wotlk/issues/10498. This guy seemed to have done some code reading to understand the cause of the issue and the problem was quite generic (meaning it does not only affect one RDF bonus bag) and concerning for an online lottery game. However this bug report has not been picked up since being posted 2.5 months ago. So I reproduced it today on CC's PTR and posted it here to see whether it gets some attention.

### Expected Blizzlike Behaviour

Ring/shoulder ratio should be 1:1 regardless of armor type.

### Steps to reproduce the problem

1. Create a warrior and get some bag space by ".additem 23162 4".
2. Add 100 satchels ".additem 52001 100"
3. Open them all. (You can write "/use Satchel of Helpful Goods" into a macro to speed it up.)
4. In my test I got 5 rings and 95 plate shoulders.
5. Repeat with a hunter, I got 13 rings and 87 mail shoulders.
6. Repeat with a rogue, I got 26 rings and 74 leather shoulders.
7. Repeat with a priest, I got 49 rings and 51 cloth shoulders, which is finally close enough to a 1:1 ratio.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, and for linking the AC issue. I've notified the devs.
