### ISSUE TITLE
[R:#3120] Occasionally unlootable items

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3418]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

_Few words before we start:_
_This bug appears to be **EXTREMELY** rare and it's reproduction seems to be hard, if not close to impossible to reproduce on purpose._
_This report originally was an response to https://github.com/chromiecraft/chromiecraft/issues/3120#issue-1147105372, but I decided it will be better to create a new one and put all the details I have found._
___

Occasionally certain items _may_ end up being unlootable for some reason and that's what happened to me in winterspirng. Here is all what I've found:
1. There was no red message error (Like _"this item does not belong to you"_)
2. It's not addons issue, disabling them all didn't work
3. It's not individual or faction issue, since I asked nearby (Horde) player to loot it with no results
4. Neither manual or autoloot worked
5. The item was a world drop green [Chieftain's Breastplate of Intellect](https://wowgaming.altervista.org/aowow/?item=9950)
6. Returning to the chest after it respawned did not reproduce this issue

Video here: https://www.youtube.com/watch?v=jUPJULfF-qs

### Expected Blizzlike Behaviour

All items should be lootable.

### Source

_Not needed I guess?_

### Steps to reproduce the problem

1. Mind Your own business (preferably in Winterspring?)
2. Loot everything You can
3. Pray to RNGesus for a blessing
4. Go insane while trying to reproduce the problem

### Extra Notes

Chest:
85802 (Entry: 153454)

[Solid Chest X:6617.370117 Y:-4081.399902 Z:662.525024 MapId:1]

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
Hey, I have never encountered this issue, so it's very hard indeed to confirm it for you.

**Comment by The-GhostRider** [comment]
I don't think it's a real bug, and by "real bug" I mean a bug that comes from the server.
Sometimes it happens that the "Client" interacts badly with the Server, this is due to various factors, from the Client's Cache, to the latency of its Internet line at that moment, and in any case the 2 things are not mutually exclusive, in the sense that sometimes it can also be a combination of both, the cause.
Therefore, due to an erroneous packet transfer interaction between the Client and the Server, these "Rare Cases" of bad interaction can occur, which can also be defined as Bugs, but in reality they are not, they are exceptional cases, and this is the reason why this "Bug" is so difficult to reproduce..

For this reason, I close the report.
