### ISSUE TITLE
[Minor][PvP][CC's Crossfaction] Invisible player model (Draenei) on Swift Hawkstrider mount

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3420]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

Self-explanatory I guess :smile: 
_(Yes, I use Chromiecraft client)_
![WoWScrnShot_042522_192558](https://user-images.githubusercontent.com/79346412/165499344-24aba83b-d423-411f-a008-b5eaa7edd2ba.jpg)

### Expected Blizzlike Behaviour

Hard to call it _Blizzlike_, but I think the model should be visible.

### Steps to reproduce the problem

1. Get queued into BG as Alliance 
2. Try to find a Blood Elf on Hawkstrider transformed into Draenei

### Extra Notes

Just all mounts from database
https://wowgaming.altervista.org/aowow/?search=Swift+hawkstrider

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, Sathrenor!

Draenei models on Hawkstriders work fine. I'll try it using the cross-faction feature later today and see if I can find anything.

![WoWScrnShot_042722_113603](https://user-images.githubusercontent.com/100873791/165543948-f444030d-bfb1-45a5-bfff-409e7c1e7fda.jpg)

I thought it was a pretty funny bug though 😆

**Comment by Gultask** [comment]
Hmmm, no dice. Are you using a modified client? Did you download it from CC's website or another place?

![WoWScrnShot_042722_135518](https://user-images.githubusercontent.com/100873791/165579217-6a43c035-7822-44ac-be66-a51b843da2af.jpg)

**Comment by Sathrenor** [comment]
Yep, this is a client downloaded from Chromiecraft and with no modification. Also I don't have addons that (I think) would collide.
Maybe it's a live server thing and/or rarer case?
Maybe item/transmog was a reason? 

But I agree, odd indeed.

**Comment by Stump876** [comment]
I haven't been able to duplicate either.  I'm a bit late on this, but could it possibly be in combination with your computer? I run CC on an older computer. I've seen something similar when taking the zepplin or boat and zoning in or loading an area. I will see a player (or myself) begin to mount, then just the mount appears. It will usually correct itself after a few seconds, but no longer than a minute. I don't run a lot of BG, so I can't say that I've seen it happen there. Has it happened since this report?

**Comment by Sathrenor** [comment]
@Stump876 I highly doubt it's a client/computer related since I have never encountered it in the past on other servers with cross faction in the past (although the client I'm using is for CC only).
Also can't say I encountered it again since I don't play that much (let alone BGs)

But if normal attempts to reproduce it failed, then I would bet it could've been either a temporary server glitch or something specifically related to a certain visual option (face/hair/skin/etc type and/or a gear item) that failed to get recreated for the opposing faction.

In any case, this case may require a particular set of condition to confirm, and since it's not game breaking, I think this issue can be closed for now until it happen again.
Thank You for Your effort anyway <3
