### ISSUE TITLE
Aggroing Thule Ravenclaw yet hes not attacking me expect one Immolate

### ISSUE THREAD

**Issue by slashbored** [chromiecraft/chromiecraft#3422]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Aggroed a Rothide Save, which attacked me, afterwards, another one came, took both down. I was then still stuck in combat with Thule Ravenclaw (https://classic.wowhead.com/quest=446/thule-ravenclaw), who targeted me, but did not follow nor attack me, even though I ran around the corner again (see screenshot), back into his sight. The only thing he did was cast 1 Immolate with me later on, shortly before he died. He also started to "glitch" a bit into the floor while being attacked.

### Expected Blizzlike Behaviour

I guess he should run around the corner due to line-of-sight-breaking? Or cast at least autoattacks or something when I'm in his sight.

### Source

Killed him as part of a quest I have/had.
![WoWScrnShot_042722_165050](https://user-images.githubusercontent.com/6837840/165548552-1dc2b2e2-3f32-4e5f-a99b-0ae9b9dddee6.jpg)

### Steps to reproduce the problem

Go onto his island (Fenris Isle) in Silverpine Forest
Fight through to the boss room in the castle.
Attack a Rothide Savage (casted Fireball on one).
Line-of-sight-break them around the corner. 
Kill both out of sight of Thule Ravenclaw.
Go back into his sight.
Wonder, why he doesn't attack execept one Immolate later on.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Windows 11 x 64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, /bored!

I can confirm.

**Comment by ishidinho** [comment]
Fixed labels. 

@Gultask Labels Confirmed and Linked [AC] indicate valid reports. But Duplicates aren‘t.
