### ISSUE TITLE
Dragon's Breath disorient effect not working 90% of the time

### ISSUE THREAD

**Issue by haebawari** [chromiecraft/chromiecraft#3424]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Mage's Dragon's Breath talent spell's disorient is working incorrectly 90% of the time (correct behaviour happened a couple of times). The spell effect is applied, the target is slowed and the damage is made however the disorient effect does not happen: 
- the target keeps attacking the player
- the target's spell casting is not interrupted

### Expected Blizzlike Behaviour

Disorient should prevent the target from taking any action for a certain period of time. Disorient causes the target to wander about in a confused fashion for the duration of the effect.

### Source

https://wowwiki-archive.fandom.com/wiki/Disorient

### Steps to reproduce the problem

1. Use Dragon's Breath (currently level 2) on a target
2. The target will almost certainly not be disoriented

### Extra Notes

So far tested on mobs only.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, haebawari, thanks for the report!

Could you specify which mob it was? And was it in an instance/dungeon? By trying it out on random mobs around level 55+ and level 60 players it seems to work fine. It could be specific to a mob type or even one particular mob.

**Comment by haebawari** [comment]
So I've been testing it for at least 1 hour on various mobs throughout Easter Plaguelands and I'd say the percentage holds. It works correctly only 10-15% of the time. I am level 57. 
Also worth noting I guess is that I took a 6 month break from playing, resuming only couple days ago.

**Comment by haebawari** [comment]
update: in the last 10 minutes the bug only occured once in 10 tries.

**Comment by Gultask** [comment]
I think I found a couple of mobs that work the way you described. Is the visual effect above the mob's head visible to you?

**Comment by haebawari** [comment]
The visual disorient effect, spell icon, slow and damage all are visible/applied.

**Comment by Gultask** [comment]
Hmmm... Thanks, I'll take a look and get back to you soon.

**Comment by Gultask** [comment]
Ok I think I found what's wrong. Skeletons, ghosts and such are immune to Disorient (I tested using Blind and they were immune). However, the Dragon's Breath debuff was applied but did not work because they are immune to disorient. I'll take a look and see if I can find any sources claiming that Dragon's Breath affects targets immune to other Disorient spells.

**Comment by haebawari** [comment]
That would make sense, thank you. Did not know this, and it's interesting that it is specifically skeletons and ghosts and not ghoul, nerubian or humanoid undeads that are immune.

**Comment by Strudelz** [comment]
Weird thing about this is there are no "immune" reports like in cases of trying to fear undead or freeze elemental etc. The target is afflictedin combat log but he actually isn't, Whether it's a bug or blizzard's mistake I can't tell for sure, but it sure is off putting
![dbreath](https://user-images.githubusercontent.com/104530093/166151044-59cb6968-a220-4b25-8ef9-9930a784d4e4.jpg)
.

**Comment by Strudelz** [comment]
I will add 2 more screenshots in comparison.

On 1st SS you can see normal mob without any immunities being "afflicted" by both frost nova and dragon's breath, normal stuff.
On 2nd SS you can see Elemental that is not reporting "immune" to fnova and dbreath, but is not "afflicted" by them either. Interestingly enough it reports immunity to Impact.

So there is an inconsistency at least in combat log where some undead/ghostlike mobs (not all of them!) are "afflicted" by dbreath while they actually aren't afflicted. I am not sure what "afflicted" in combat log actually means from technical point of view, just thought it might be interesting to point out.
![novamob](https://user-images.githubusercontent.com/104530093/166152696-b034fa60-6414-4f2f-9e79-776732db8cd2.jpg)
![novabreathelemental](https://user-images.githubusercontent.com/104530093/166152706-c9c3fddf-08d6-415f-b6e1-ce87c2e22758.jpg)

**Comment by Gultask** [comment]
@Strudelz what's interesting to note is that both rock elementals have the exact same immune flags too.

Thanks for all the info, everyone. I'll link the issue.

**Comment by temperrr** [comment]
![image](https://user-images.githubusercontent.com/20357406/183465009-e82ec889-ea50-4876-a871-c552f1125dbd.png)

**Comment by temperrr** [comment]
![image](https://user-images.githubusercontent.com/20357406/183465882-41cb037a-f2b7-45ff-b11d-6e570bb054fc.png)

**Comment by temperrr** [comment]
![image](https://user-images.githubusercontent.com/20357406/183466030-3039efa5-90f0-47ff-9eba-f17ec8fa6650.png)

**Comment by Gultask** [comment]
As temperrr has shown, these creature are not supposed to be immune to Disorient. And it only took me several months to remember about this issue, sorry!
😵
