### ISSUE TITLE
Transmogging Armour Fufilling Set Bonuses

### ISSUE THREAD

**Issue by Snektopus** [chromiecraft/chromiecraft#3430]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

On character have another chest piece that is transmogged to appear as Shadowcraft Tunic, Putting on Shadowcraft Pants fufills the 2/8 Set bonus +200 Armour, Armour increase shows on character sheet, is removed with the Transmogged item

### Expected Blizzlike Behaviour

Transmogging should not provide set bonuses aligning with the aesthetic armour

### Source

Transmog Mechanic

### Steps to reproduce the problem

Transmog Set Piece of Gear appearance on non set item
Equip and equip an un mogged piece of the same set
Note any set bonus being fulfilled

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hi Snek! o/
I didn't realize that it was you in the last 2 reports 😅 

This is a client visual bug that can't be fixed. The set bonuses still work/don't work as they should. That particular situation, however, got me confused, but it just so happens that the legs have 150 armor and 25 agi, totalling 200 armor, which is the same from the set bonus. To make sure I tested an armor set that gave expertise rating (Embrace of the Viper set) and it was working correctly, as in, the expertise rating bonus was not applied.

There is more info here: https://github.com/chromiecraft/chromiecraft/issues/3301 and in the link Nyeriah posted.

If adding the pants was giving you 400 armor, however, post a screenshot here and I'll forward it to the devs.

**Comment by Snektopus** [comment]
Ok my issue not searching properly,  I'll try more key words next time
