### ISSUE TITLE
Chimera Shot - Scorpid and Chimera Shot - Viper are not working

### ISSUE THREAD

**Issue by nesh1905** [chromiecraft/chromiecraft#3432]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Chimera Shot's Scorpid Sting and Viper Sting effects are not working, while Serpent Sting effect works.

"Scorpid Sting - Attempts to Disarm the target for 10 sec. This effect cannot occur more than once per 1 minute" - The Hunter hits the target with Scorpid Sting and then with Chimera Shot, a "disarmed" debuff appears but target can still use their weapons

in this video it is shown on a Hunter but I've hit a Warrior with it in BG and still got hit
https://www.youtube.com/watch?v=LvwKyibmjf0&ab_channel=nesh

"Viper Sting - Instantly restores mana to you equal to 60% of the total amount drained by your Viper Sting" - The Hunter hits the target with Viper Sting and then with Chimera Shot but no mana is restored by it
video - https://www.youtube.com/watch?v=8s4w0i6_Ew0&ab_channel=nesh

### Expected Blizzlike Behaviour

Target should not be able to use their weapon while having the Disarmed debuff on them from Chimera shot - Scorpid
60% of Viper drain should be restored instantly when hitting a target that has Viper Sting on them with Chimera Shot

### Source

tooltip

### Steps to reproduce the problem

Hit the target with Scorpid Sting and then hit them with Chimera Shot
Have the target attack you with their weapon

Lose a major amount of your mana, use Viper Sting on a target that has mana and then hit them with Chimera Shot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Nesh, thanks for the report!

I tested it in the PTR and it is working as intended.

The Scorpid Disarm does not work on ranged weapons ([source](https://www.mmo-champion.com/threads/653814-Hunter-Disarm-bugged))

And the Viper Sting effect is very weak and can be seen in the video you posted. Viper Sting ticks drains a small amount and restores 300% of each tick, and the Chimera Shot effect only restores 60% of the amount drained, not the total restored.

**Comment by Gultask** [comment]
I did not completely forget to test the disarm on melee weapons and only noticed it when you posted it on the Discord 😬

Anyway, it's working fine from what I've seen, sorry for forgetting that!
