### ISSUE TITLE
[Mage] T2 (Netherwind Regalia) 3/8 set bonus causing negative threat.

### ISSUE THREAD

**Issue by Gultask** [chromiecraft/chromiecraft#3435]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When wearing 3+/8 pieces of Netherwind Regalia, casting one of the spells included in its effects will cause negative threat on the target.

https://user-images.githubusercontent.com/100873791/165916003-24aafade-737e-4d1c-ae66-3906a6242823.mp4

### Expected Blizzlike Behaviour

The threat reduction should not be negative.

### Source

>The way threat reduction works is that fireballs get 20 threat redux on the initial fireball, then 20 off of each tick. AM gets 20 taken off per bolt.
>
>Now lets make it over time and see how it works:
>
>Fireball, 40 redux per 3 seconds, assuming you refresh your fireball DoT
Frostbolt, 100 redux per 2.5 seconds
Scorch, 100 redux per 1.5 seconds
AM, 100 redux per 5 seconds
Fireball = 13.3 redux per second
Frostbolt = 40 redux per second
Scorch = 66.7 redux per second
AM = 20 redux per second, however, AM doesnt need it as much because of Arcane Subtlety. ([source](https://www.wowhead.com/item-set=210/netherwind-regalia#comments:id=2350))

### Steps to reproduce the problem

1. have some way of monitoring threat
2. create a mage
3. `.additemset 210` or `.additem 16914` `.additem 16915` `.additem 16916`
4. equip at least 3 set pieces
5. cast any of the affected spells

### Extra Notes

Also seen by other people in the CC Discord but it was not reported (or at least I didn't find it.)
https://discord.com/channels/788063059926712341/825732076975554571/969303647915741194

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
I think this is an issue with Omen and not something on CC side?

**Comment by Dejanos** [comment]
Edit: Upon testing it, seems like Omen is right, after equipping 3 pieces of set and casting any other spells that are not mentioned in the set bonus, I can take threat easily after doing more damage than the one who has the aggro, but after casting Frostbolt or any other spell mentioned in the set bonus, aggro goes negative and Mage loses it, therefore even if doing 50k more damage than the person who has the aggro will make the Mage not get threat. (Skada does not even calculate threat below 0 so it doesn't even show when I cast Frostbolt or any other set bonus affected spell).

Took aggro easily with spells not included in set bonus.
![WoWScrnShot_042922_152109](https://user-images.githubusercontent.com/100415626/165953430-de1c97ce-62ed-4530-8dec-51c9b866a7e1.jpg)

Can never take aggro even if I do way more damage than the current threat target, even if I throw in lots of spells that are not affected by the set bonus in between, the spells affected by the set bonus just overrule all aggro and bring it to negative.
![WoWScrnShot_042922_152309](https://user-images.githubusercontent.com/100415626/165953493-219e4922-f6c2-43b6-8048-f1aa9cc39f31.jpg)

**Comment by Gultask** [comment]
Ah, thanks, I hadn't found the spell ID for the set bonus. But something must be wrong, this kind of bug wouldn't get past WoW Classic unnoticed, I'll try it later with other threat meters, but losing aggro after casting spells must be wrong.
There was [this thread](https://eu.forums.blizzard.com/en/wow/t/threat-reduction-from-netherwind-regalia/131995) in the WoW Classic forums that was trying to figure out the reduction and it seems like such a minor decrease in threat.
