### ISSUE TITLE
Volley still allows hunter Auto Shots

### ISSUE THREAD

**Issue by slicplaya** [chromiecraft/chromiecraft#3437]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

While channeling Volley, Auto Shots continue to fire during the channel.

### Expected Blizzlike Behaviour

Auto Shot should pause while Volley is channeling. All skills that require the hunter to channel, should Queue up the shot timer for Auto Shot, but not release the shot until channeling is finished.

### Steps to reproduce the problem

Volley a mob with Auto Shot active ie /startattack. witness Auto Shot casting during the channel.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, slic, thanks for the report!

Auto-shot while channeling volley was reported July last year and was ruled as Blizz-like. I think it might be due to attributes that came with the Blizzard files.
See: https://github.com/chromiecraft/chromiecraft/issues/1257 and its linked issue.

**Comment by slicplaya** [comment]
It's definitely not Blizz-like and > SPELL_ATTR2_NOT_RESET_AUTO_ACTIONS is correct. It does NOT reset Auto Shots, the timer still continues while channeling, but while channeling volley it should pause(lock) all other actions including Auto Shot. I've looked at multiple videos, including the one provided in the previous issue, and have not seen one Auto Shot cast while channeling. Multiple other private servers have had the issue reports as well and had them "fixed". I also do not remember it ever casting Auto Shots while channeling volley, but I do remember Auto Shot  or any other spell/skill, cancelling the channel of Volley if it was attempted during channeling.
I guess it might be an Azeroth Core thing, because Trinity has SPELL_ATTR2_DO_NOT_RESET_COMBAT_TIMERS tag on Volley and it locks/pauses Auto Shot but still allows the timer to continue. Oh well /shrug

**Comment by Gultask** [comment]
I'll ask the devs about this. I found [this video](https://youtu.be/FYziN8llxh0?t=300) that seems to comfirm it. The trouble is that in most videos the player does not even start auto-shot before casting volley so it wouldn't be valid evidence.
If you can find more evidence, could you post it here? It'd help out a lot.

**Comment by slicplaya** [comment]
I've had a #showtooltip Volley
/stopcasting
/cast !Volley

Macro that I've had since 2009 in a bindings file that I still use to this day. I had to change it to /startattack because of here. xD
If I get any more info I'll def post here.

**Comment by Gultask** [comment]
I've found a bunch of videos: https://youtu.be/L1BoDfyij2A?t=178 https://youtu.be/YHtsRRj8VoU?t=116 https://youtu.be/8LwN82kribA?t=167 https://youtu.be/3mIl31Vlvj4?t=143 
It's a shame that all the videos I've seen with a auto-shot timer don't have any AoE in them.

The problem really is that most videos have the hunters not auto-attacking before Volley (and manually clicking the spell 😭) so it wouldn't count either way. I'd like some written evidence but I've found nothing.

**Comment by Cooties-cc** [comment]
https://www.warcraftmovies.com/movieview.php?id=123709
Ony solo vid from patch 3.2.2, so not quite 3.3 or 3.3.5, but about as close as I can find

Around 3:12 mark they cast a spell, which enacts auto shots. As they are still targeting ony, they cast volley, which stops all actions besides volley. Another mark at 4:05, they cast auto shot, and instantly after cast volley. You'll notice autos are suspended during volley channel time.

**Comment by slicplaya** [comment]
Swapping any target or initiating any spell/shot traditionally cancels the volley channel, and pre queued/toggled auto shots are suspended/paused/locked during the channel, and immediately resume after, in all of these videos, as it should be.

**Comment by Gultask** [comment]
Sorry for the delay! I'll link the issue since we gathered a lot of evidence.
