### ISSUE TITLE
you cannot interact with private Hendel For the mission the missing diplomat

### ISSUE THREAD

**Issue by Storkell** [chromiecraft/chromiecraft#3442]
### What client do you play on?

esMX

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Private Hendel appears with his name grayed out, and I can't interact with him to turn in the Missing Diplomat's quest.
![image](https://user-images.githubusercontent.com/104691712/166116408-0a758010-8a71-4161-a801-f3f9d6dd0058.png)

### Expected Blizzlike Behaviour

your name should be green to interact with it

### Steps to reproduce the problem

The NPC must be green to be able to interact with it, and thus be able to deliver the mission

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, Storkell, thanks for the report!

Have you tried relogging and clearing your Cache? It might fix a couple of issues related to quest turn-ins.

- To relog you just log out and log back in.
- To clear your cache you must delete the 'Cache' folder in your WoW installation folder, and then restart your client.

**Comment by Storkell** [comment]
i Tried, but not worked 
![image](https://user-images.githubusercontent.com/104691712/166124131-4b2283db-d0e5-4a85-ba30-f400cb2f4db7.png)

**Comment by Gultask** [comment]
He might be stuck in a RP event that did not complete, then. I think I know which.
I'll see if I can reproduce it.

**Comment by Storkell** [comment]
hi, im the and the NPC stay stuck, a Horde player tried to kill him, but not worked

**Comment by Buggyswires** [comment]
I can confirm the problem: it is linked to the issue meantioned above.
If you fight him and his guards he doesnt get subdued and switches to the follow-up quest
He is friendly but i am still in combat
![WoWScrnShot_050422_100901](https://user-images.githubusercontent.com/43603807/166644606-411861b9-b58f-4b59-96d4-850cef083c89.jpg)

**Comment by Gultask** [comment]
@Buggyswires thanks, I was busy that day and forgot to test it. I did it right now and you're right. It seems that this quest is broken now.

**Comment by SLS20** [comment]
It also happened to me today, private Hendal isn't interactable.

**Comment by CollaredLioness** [comment]
I also had this issue. Hendel remains non-interactable so I'm unable to complete the quest chain at this time.

**Comment by Gultask** [comment]
> I also had this issue. Hendel remains non-interactable so I'm unable to complete the quest chain at this time.

Hey, @CollaredLioness could you tell me which quest it was and explain what happened with more detail?
A fixed was released for Private Hendel recently but since he in involved in more than one quest I cannot say for sure if it fixed everything.

**Comment by RacerXx** [comment]
I can confirm Private Hendel is broken as well his name is grey and there is nothing you can do with him thus this long chain quest  can not continue. Windows 11 https://prnt.sc/X-0ptjOGj7iv  addons used: https://prnt.sc/j0YCragRfy9y

**Comment by anjxed** [comment]
When will this get fixed?

**Comment by thurimar** [comment]
I can confirm - quest still not working. Cache delete / relog did not help.

It is specifically this phase of quest: https://www.wowhead.com/wotlk/quest=1266/the-missing-diplomat

FYI - in this phase it was not possible to speak to Commander Samaul, relog however worked https://www.wowhead.com/quest=1264/the-missing-diplomat

**Comment by Lludara** [comment]
Hendel is still not able to be interacted with. Cannot turn in the quest to trigger his fight
