### ISSUE TITLE
Sunder armor Threatgen 10x VS Devastate

### ISSUE THREAD

**Issue by Spook9** [chromiecraft/chromiecraft#3448]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Warrior ability "Sunder Armor" creates around 80-90k threat a swing. Compared this to Devastate that creates around 10k-15k threat.

Both spells share same text with Devastate, just having an addition. 

Both pictures taken after 10x of spells cast:

Picture 1 Sunder armor
![image](https://user-images.githubusercontent.com/58770211/166157972-e52ba89f-5cd7-4b57-996d-732f82e5b9ca.png)

Picture 2 Devastate:
![image](https://user-images.githubusercontent.com/58770211/166158036-2e892955-c804-4e9e-9130-998b5c7a536c.png)

### Expected Blizzlike Behaviour

Both items share the same text in regards of function:
Devastate has the damage addition*
![image](https://user-images.githubusercontent.com/58770211/166158092-2dd981b8-8627-4b8d-a4de-febf011a03fb.png)

![image](https://user-images.githubusercontent.com/58770211/166158110-65b135ca-91d7-4596-925c-dc07c1184ec7.png)

### Steps to reproduce the problem

1. Cast Devastate/Sunder Armor
2. Use threat AddOn of choice to determine gain
3. ????
4. Profit

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04
Win 10 pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Spook9** [comment]
Linked/same issue: https://github.com/chromiecraft/chromiecraft/issues/3449

**Comment by Spook9** [comment]
With new foundings this might be due to hitting a training dummy. Hitting hostile mobs seem to have the threat values fixed.

**Comment by Gultask** [comment]
Hey, Spook, thanks for making a report!

I'll be addressing this in the other issue, but thanks for contributing!
