### ISSUE TITLE
Devastate isn't gaining the threat associated with Sunder Armor

### ISSUE THREAD

**Issue by KaneoHunter** [chromiecraft/chromiecraft#3449]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Sunder is currently generating about 85k threat, while Devastate generates around 10k, from testing on my live warrior w/ TinyThreat

### Expected Blizzlike Behaviour

![image](https://user-images.githubusercontent.com/15280301/166158252-be090be8-cea5-4229-8d09-79495e8ac767.png)

Elitist Jerks breakdown, check the Devastate section for intended 3.3.5 behaviour.

### Source

[Elitist Jerks Guide](https://forum.warmane.com/showthread.php?t=271757)
TinyThreat tests on Live ChromieCraft

### Steps to reproduce the problem

Use the below macro on a dummy

```
#showtooltip  
/cast Sunder Amor  
/stopattack```

Check threat on your meter

```
#showtooltip
/cast Devastate
/stopattack```

Check threat again, Devastate should be higher than Sunder, as it's the same effect in addition to damage.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by KaneoHunter** [comment]
Testing again on PTR w/  `.debug threat`

![image](https://user-images.githubusercontent.com/15280301/166162397-b98cdc22-93c5-4ef2-938d-943abbb6019c.png)

Each Sunder stack is about 1000 threat.

![image](https://user-images.githubusercontent.com/15280301/166162441-dbd7f5d5-2a78-4b8c-87c1-4a13f68a0eff.png)

Each devastate is adding expected numbers, the bigger jumps are crits. Would it be safe to say this is an addon issue?

**Comment by KaneoHunter** [comment]
Okay, I think this might just be an issue on the training dummy, Went out in the world to hit some mobs on Live w/ TinyThreat

2x Sunder
![image](https://user-images.githubusercontent.com/15280301/166163193-b34f4345-8671-41b9-84fe-fbc6cc62b4f8.png)

..2x devastate on top of that
![image](https://user-images.githubusercontent.com/15280301/166163208-d67e5624-8732-4eb8-9eb1-85b6c27343f6.png)

Seems to be correct going by eye.

**Comment by Gultask** [comment]
Thanks for the report, Kaneo!

Yes I've been testing it out in some random boss NPCs and it seems fine. I could only see it in the dummies as well.
A low damage Devastate will generate way less threat than a simple Sunder but as soon as the damage picks up, so will the threat.
It's a shame though, since this is a very well-written issue 😄

Well, if you find anything else wrong with it don't hesitate to comment here or open another issue!
