### ISSUE TITLE
Occasionally unable to pick up Berserking buff in Warsong Gulch

### ISSUE THREAD

**Issue by haebawari** [chromiecraft/chromiecraft#3456]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The Warsong Gulch Berserking buff located in two of the four houses sometimes fails to grant the buff upon interaction. Might be just the Alliance side, don't remember if it happened on the Horde side or not (might be coincidence). Occurred at least 3 times in like 2 days.
I've been playing a lot 6 months ago and never had this issue back then.

### Expected Blizzlike Behaviour

Buff applying

### Steps to reproduce the problem

describing the latest occurence:
1. Get into WG in the middle of the game
2. Go to the buff, it is visible.
3. Upon interaction, buff animation in the house disappears but no buff is applied. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Win 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by lellalex** [comment]
Happend few times for me aswell!

**Comment by haebawari** [comment]
Going to add that it's not limited to warsong and berserking, happened with restoration on arathi as well.

**Comment by haebawari** [comment]
It just got way worse after latest update. Was unable to pick up like 9 buffs in a row.

**Comment by Gultask** [comment]
Yup. I'm gessing it's related to a recent LoS change in the core. I'll link the issue ASAP.

**Comment by haebawari** [comment]
It's definitely not completely fixed. Just failed to pick up Berserking at LM in Arathi.

**Comment by Gultask** [comment]
@haebawari ChromieCraft Live server hasn't updated yet to the latest AC. The last update was 2 days ago. When it updates you will be able to see it in the Discord in #changelog-chromie :)

**Comment by haebawari** [comment]
oh ok, my bad. saw the issue was closed and assumed the fix is live.

**Comment by haebawari** [comment]
not working again. regen and berserking failed at LM in Arathi.
