### ISSUE TITLE
Crimson Guardsman aggro is not working

### ISSUE THREAD

**Issue by DarylBlake21** [chromiecraft/chromiecraft#3459]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

When you pull (taunt) other mobs like Crimson Iniciate (https://wowgaming.altervista.org/aowow/?npc=10420) or Crimson Conjuror (https://wowgaming.altervista.org/aowow/?npc=10419) at Stratholme Living Side, the Crimson Guardsmans (https://wowgaming.altervista.org/aowow/?npc=10418) along side them doesn't get pulled. 

### Expected Blizzlike Behaviour

When you taunt one mob of this pack of Scarlet Crusade NPCs at Stratholme Undead, every mob on that pack should be pulled too. Aggro is not working well on that mob.

### Steps to reproduce the problem

1. Go to Stratholme Living Side and enter the Scarlet Crusade part of the dungeon
2. Find a pack of mobs with at least one Crimson Guardsman alongside them
3. Taunt one of the other mobs that are with them, either Crimson Iniciate o Crimson Conjuror
4. Try to get away while you're taunting so you won't pull Crimson Guardsman by mistake
5. Even if those mobs are close, if you managed to hide in time while you used taunt on either of the mentioned mobs, Crimson Guardsman won't get aggro.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, Daryl!

I can confirm.

**Comment by Gultask** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/12979
