### ISSUE TITLE
Warrior Charge does not start auto attack

### ISSUE THREAD

**Issue by dlloyd1** [chromiecraft/chromiecraft#3460]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Tab targeting (or left-click targeting) a mob and using charge (rank 1) results in your character stood in melee range of the mob, doing nothing. (Note: if auto attack is enabled with right-click prior to charging, charge does not turn it off)
Not tested with higher ranks of charge.

### Expected Blizzlike Behaviour

Charge should start your auto attack.

### Steps to reproduce the problem

Use charge on a mob with auto attack off (or without right-clicking it first)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, dlloyd, thanks for the report!

In the future, you can use the Template provided for Bug Reports when creating an issue, it helps keeping things tidy and organized.

As for your bug report, I couldn't find a good source regarding charge/intercept starting auto-attacks.
There were, however, several previous reports that involved similar situations. See: https://github.com/chromiecraft/chromiecraft/issues/1078 and https://github.com/chromiecraft/chromiecraft/issues/2867

**Comment by dlloyd1** [comment]
Hi Gultask, sorry about not using the template correctly.
As for a source, I'm not sure if it's good enough, but the wowhead spell link has the tag "Attack on Charge to Unit",  link: https://www.wowhead.com/spell=100/charge

**Comment by Gultask** [comment]
>Hi Gultask, sorry about not using the template correctly.

It's no problem! Just keep it in mind for any future reports 😄 

Taking another look at the links I've posted, it seems that you may be correct and I interpreted them wrong. Plus, I've found a couple of videos that could serve as a source too.
I'll record some videos of the current behaviour to the devs and then I'll link the issue later. Thanks again for the bug report!
