### ISSUE TITLE
Bug with Seal of Ascension Quest

### ISSUE THREAD

**Issue by Charys01** [chromiecraft/chromiecraft#3466]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Hi there, actually ive a problem with  [Seal of Ascension] quest, i died once and [Orb of Draconic Energy], item provided from the quest, is telling me that i already used and isnt working anymore.
I tired to delete items and quest, and i took it again, but still dosent work. 

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=8fehRCl_Jx4&ab_channel=TipsOut

After min. 2:32

### Steps to reproduce the problem

Actually i dont know what answer in any point.

Just the Npc is Emberstrife.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hi, Charys, thanks for the report!

I haven't been able to reproduce the problem, I can spend all 5 charges of both items, regardless if I died or not.
Did you lower Emberstrife's health before using the Orb? You can't use it if he isn't at low health.

**Comment by Gultask** [comment]
If you're really stuck in the quest, I'd recommend you to open a #support-ticket in Discord if you haven't already. Here's the link: https://discord.com/channels/788063059926712341/888194705505017926

Also, it might be a long shot but I've seen some problems with items from people with modified game clients. The optimal choice would be to use the links provided in the CC website.

**Comment by Charys01** [comment]
Yep i did it when he was lower than 10%, and it said something like "u already used that for charming, you cant use anymore"

Already did tonight about discord.

Any way ill try out with CC Client.

Ahanks.

**Comment by Charys01** [comment]
Oki i've found out problem, it was my ghost wolfs.

It said "You already control a summoned creature" and it was my Wolfs.

So if u got a Summoned something that is helping you, it wont work propelly.

Cheers!

**Comment by Gultask** [comment]
Ahh, I see. That makes sense.

I'm happy it worked out, then 😄 .
Have fun!
