### ISSUE TITLE
Lord Melenas is not respawning.

### ISSUE THREAD

**Issue by remonrh** [chromiecraft/chromiecraft#3468]
### What client do you play on?

esES

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I've been waiting a long time for lord melenas to respawn but it is not respawning.

### Expected Blizzlike Behaviour

It should respawn.

### Source

![WoWScrnShot_050622_100349](https://user-images.githubusercontent.com/105065417/167160156-3b64720d-15a2-49a8-91e7-4b59601c95ff.jpg)

### Steps to reproduce the problem

Go to the coords 51,49 in the cave
I did /tar melenas, didnt work

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273

### Operating system

windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

Hd models
but didnt find it without them

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, remonrh, thanks for the report.

Lord Melenas has 3 spawn points, try seeing if he's in one of those 3.

![WoWScrnShot_050622_143309](https://user-images.githubusercontent.com/100873791/167183558-8a458ba9-dc65-40a9-a095-95c56c6bea9c.jpg)
![WoWScrnShot_050622_143319](https://user-images.githubusercontent.com/100873791/167183561-25365c89-cc70-4101-9a0e-23f340284f73.jpg)
![WoWScrnShot_050622_143259](https://user-images.githubusercontent.com/100873791/167183565-75a9232f-c488-479b-9cbf-906f7b169c5c.jpg)
