### ISSUE TITLE
[Cenarion Circle Reputation] Items Vanish using equipment manager set swap

### ISSUE THREAD

**Issue by Hogofogo1** [chromiecraft/chromiecraft#3478]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

While grinding Dukes in Silithus and you switch to any set that changes neck/shoulder/head/chest you loose the Cultist set parts most of the time.

### Expected Blizzlike Behaviour

There is no reason for the items to disapear unless they were destroyed while summoning not when changing gear.

### Source

As stated in expected behaviour

### Steps to reproduce the problem

Equip full Twilight Cultist set
Summon Templars/Dukes at Wind Stones
Right after the summon or after the kill equip your normal set
You might loose one of the Twilight set parts while switching

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Hogo, thanks for the report!

I couldn't reproduce the issue, but that's to be expected from what I've understood from the issue. I always lost the expected amount of items, not any more than what it takes to summon the Templars.
Could you provide any screenshots of this happening?

**Comment by Dejanos** [comment]
Collecting my reputation with Cenarion Hold, I have used more than 200 sets summoning Lords, Dukes and Templars, I must say I never experienced this issue. Could it be possible you thought part of your sets are disappearing because simply parts of the set got pushed to different parts in bag once the used set gets consumed, or you are certain the set literally disappears from your inventory before usage?

**Comment by Hogofogo1** [comment]
After further testing its working as intended - the items are consumed. However It can be items equipped or in the bags
Meaning - you can have equipped shoulders destroyed and chest and head destroyed in the bags.
Screenshots: https://imgur.com/a/Dyu9Kkt

**Comment by balleny** [comment]
if you have a set equiped and summon, the items in the inventory are consumed first.

**Comment by Hogofogo1** [comment]
Evereything is working as intended then.
Thank you

**Comment by Gultask** [comment]
All good then. Don't hesitate to open up another bug report in the future @Hogofogo1 😄
