### ISSUE TITLE
Stone Watcher Norgannon

### ISSUE THREAD

**Issue by Hanzemon** [chromiecraft/chromiecraft#3483]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Interacting with the Uldum Pedestal will spawn multiple Stone Watcher Norgannon.

### Expected Blizzlike Behaviour

Uldum Pedestal should only summon 1 Stone Watcher Norgannon at a time.

### Source

self evident

### Steps to reproduce the problem

click uldum pedestal
observe

### Extra Notes

sorry for not finding a source
![WoWScrnShot_050322_202616](https://user-images.githubusercontent.com/32701428/167321053-150b1cd5-30f1-4f41-a1ad-261a199cff87.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Hanzemon, thanks for the report!

Did you spawn 2 of them by yourself or was one already spawned beforehand?

**Comment by Hanzemon** [comment]
> Hey, Hanzemon, thanks for the report!
> 
> Did you spawn 2 of them by yourself or was one already spawned beforehand?

I there were atleast 3. I don't remember this was like a week ago. But I screenshoted it because I knew in that moment that it was bad.

**Comment by Gultask** [comment]
Ok. When I wake up I'll try some things to see if I can make the Watcher be summoned twice by a single person.
I'll just save this here so I don't forget:
>If you abandon the quest, and then click the pedestal, you will get the quest again, and the hologram will appear. Talk to him! Keep talking until you're done, then click the pedestal again to turn it in. Then one more time to get the next quest. *phew* ([source](https://tbc.wowhead.com/quest=2954/the-stone-watcher#comments:id=44384:reply=27114))

**Comment by DaviddOrs** [comment]
Did the quest last week - no duplicated NPCs were visible when I arrived, they seem to appear during the "conversation" you have with the NPC prior to quest's completion.
Other than this visual bug, the quest is perfectly doable and working :)

**Comment by Gultask** [comment]
@DaviddOrs I have only been able to reproduce the bug when more than 1 character completes the quest that summons the Watcher in a short time, since it despawns in about 5 minutes. The other problem is that the quest giver is wrong, since the Watcher should not start any quests at all, especially because once he despawns, the quest is rendered impossible to complete, which is what happened to me once.

**Comment by Orixim** [comment]
I am currently experiencing what @Gultask  mentioned. I've deliver the quest on the pedestal and started the Stone Watcher from the hologram. I was reading the dialog when it suddenly stopped working and I could not advance to the next dialog. I've abandoned the quest and restarted it. Did not work. I've abandoned it again and waited sometime to see if it would fix it. The hologram despawned and now I can't do the quest! :(

**Comment by whipowill** [comment]
I have this bug.  When I arrived at the platform, the Watcher was already visible.  When I turned in the quest a duplicate appeared.  I was then unable to continue the quest line bc I am not able to engage him in dialogue to discover "the purpose of the Stone Watcher."
