### ISSUE TITLE
Feed Pet stops you from drinking while drinking

### ISSUE THREAD

**Issue by slicplaya** [chromiecraft/chromiecraft#3484]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When feeding your pet with Feed Pet, the hunter stops drinking and eating food.

### Expected Blizzlike Behaviour

When attempting Feed Pet while drinking/eating, the hunter should not stop these actions.

### Steps to reproduce the problem

drink/eat a timed item, and attempt to feed pet.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, slic, thanks for the report!

Could you please provide a source for your claim? I couldn't find anything about this.

**Comment by Gultask** [comment]
Hmmm. [According to Wowpedia](https://wowpedia.fandom.com/wiki/Feed_Pet) the throwing animation was only implemented in 3.2.2 so I don't know if that would interfere with anything or not.

**Comment by slicplaya** [comment]
> Hmmm. [According to Wowpedia](https://wowpedia.fandom.com/wiki/Feed_Pet) the throwing animation was only implemented in 3.2.2 so I don't know if that would interfere with anything or not.
> 
> Edit: Oh, and it's not that I don't believe you @slicplaya, it's just that we must be skeptical when researching blizz-like behaviour.

Yea I get it. Pics or it didn't happen. Maybe there's possibly some type of listed cancel drinking/channeling etc script command tied to Feed Pet on Chromie.

**Comment by Gultask** [comment]
If we can't find a video then it should be pretty easy to confirm or not this issue in WotLK Classic once it comes out.

**Comment by Gultask** [comment]
I swore to myself that this was going to be the first thing I was going to check when WotLK Classic came out. The PTR went live today and I can, indeed, confirm that Feed Pet should not cancel eating/drinking 🥳

**Comment by slicplaya** [comment]
Did I forget to mention I bug test/fix on multiple servers? xD
