### ISSUE TITLE
Silithus lords loot table

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#3485]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

1. Chance to loot gear is very low on live, higher on PTR.
2. Can get both epic and rare (purple and blue) gear items from single kill of a boss (both live and PTR).

Details:

I've been farming silithus lords for a while. In my last 24-27 boss kills, I only got 1 (at most 2) epic gear items, while statistically there should be 6-8. So I went to PTR, summoned 1 greater wind stone, kill the boss, loot, then .respawn the corpse of the boss and repeat. Then move another greater wind stone and repeat. At both greater wind stones, I summoned Prince Skaldrenox (the flamewaker guy). At the first greater wind stone, I killed it 25 times (actually did not count but I got 25 abyssal scepters), got 11 elemental focus bands, 5 rare shoulders, 7 rare wrists; at the second greater wind stone, I killed it for another 25 times, got 10 elemental focus bands, 5 rare shoulders, 7 rare wrists. This is way higher than what I had on live, given that the chances to get epic from all lords are comparable. Sure one may say I was just unlucky, but then what I had on live had to be a super unlikely event.

On PTR, I noticed that for some kills I can get all 3 gear items (elemental focus bands, rare shoulder, and rare wrist) from 1 kill. (Don't know how to attach a screeshot.) Then I recalled that this also happened on live. (I got earthen guard and a cloth hit shoulder from one of my recent kill of the rock giant boss.) I wonder whether it means the drop rate of the three items are independent on each other and whether this is blizzlike.

### Expected Blizzlike Behaviour

The drop rate I experienced on PTR (40% for elemental focus band) is closer to what I found on wotlkdb and wowgaming (both saying 34%). What I had on live is way too low.

### Steps to reproduce the problem

On PTR:
1. Find a greater wind stone, summon boss, .damage 99999999, loot
2. Select the corpse of the boss, .repsawn, repeat
3. Observe the loot behavior.

On live: Farm mats for hours and hours and hours and compete with other players for greater wind stones?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
did 10 summons recently, got 6 epics.

**Comment by Dejanos** [comment]
Hello, discorder0. In this case, the PTR is probably wrong because it is Blizzlike that there is only around 10% depending on the Abyssal Lord and epic item in question, the chance is probably increased on Chromie because all epic and blue items have increased drop chance, but it should be marginal by 4-8%.

[Wavefront Necklace](https://classic.wowhead.com/item=20685/wavefront-necklace) is around 14% according to WoWHead.
[Elemental Focus Band](https://classic.wowhead.com/item=20682/elemental-focus-band) 15%
[Earthern Guard](https://classic.wowhead.com/item=20688/earthen-guard) 6%
[Windshear Cape](https://classic.wowhead.com/item=20691/windshear-cape) 17%.

Source: WoWHead.

**Comment by Gultask** [comment]
In case you're wondering, this is the loot table for Prince Skaldrenox in Azerothcore.
The reference tables are common blues and greens.

![prince](https://user-images.githubusercontent.com/100873791/167507115-b7a0feb4-2446-4b14-8abf-65b30bc01049.png)
