### ISSUE TITLE
Stoneform Shoulders

### ISSUE THREAD

**Issue by Arisatheus** [chromiecraft/chromiecraft#3488]
It says 14.73% and it has one of the highest chances to drop from Kirtonos yet I made 35 Scholomance run in 1 week and no drop. I saw at least 6x  Valor boots and Gravestone War Axe, which are the rarest ones. I might be unlucky but this is weird and I had to post this after seeing loot bugs posts on discord.

**Comment by Gultask** [comment]
Hello, Arisatheus, please use the templates provided when opening up an issue, it helps keeping things tidy and organized.

As for your issue, I tested it in a local AC server and saw no problems regarding drop chances and I got the expected amount of drops.
The current loot tables comes from verified sniffs that are more reliable than Wowhead numbers.

The current loot table is:

![image](https://user-images.githubusercontent.com/100873791/167685887-981fddd5-eeba-4432-950d-4f38292d0ee9.png)

Note that the 0 chance means that all related items have the same chance to drop, which would be 11,1% and the chance of not getting 1 item in particular in 35 runs would then be (100%-11%)^35 which is 1,7%. It's a low chance but it's not impossible, so chances are that you unfortunately just got unlucky in this case.

**Comment by Arisatheus** [comment]
First of all I'm sorry I'm not really familiar with GitHub and reporting
bugs and I thank you very much for sharing this information with me. I
guess all I can do is to cry at my luck. Good luck and thank you again for
your hard work!

10 May 2022 Sal 20:21 tarihinde Gultask ***@***.***> şunu
yazdı:

**Comment by Gultask** [comment]
@Arisatheus Don't worry about it! And thank you for making a report! Don't hesitate to open another issue in the future!
