### ISSUE TITLE
 Pendant of the Agate Shield Buff isn't removed on swapping neck if you relog after using buff

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#349]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

If you equip Pendant of the Agate Shield (https://wowgaming.altervista.org/aowow/?item=20950) and use the buff it has(https://wowgaming.altervista.org/aowow/?spell=25606) then relog, it doesn't remove the buff after switching the neck item/unequiping Pendant
![img3](https://user-images.githubusercontent.com/80769357/113612092-aaf99c00-964f-11eb-8ecb-215bdda59c00.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When switching necklace or unequiping the Pendant the aura buff should be removed.
https://tbc.wowhead.com/item=20950/pendant-of-the-agate-shield#comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be level 26+
2. Equip Pendant of the Agate Shield and use its buff
3. Relog
4. Swap the necklace for something else
5. See the buff stay

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Reproduced this on my test server. Equipped and used Pendant, relogged, changed necklace and the buff remained.

Also note the buff from testing the Amulet of the Moon a minute before also remained.

Server is local, AzerothCore rev. c0cb2eae38dc+ 2021-04-06 03:52:40 +0000 (master branch) 

![WoWScrnShot_040721_192418](https://user-images.githubusercontent.com/81782124/113848370-8e886b80-97d7-11eb-9ab9-668bacc76617.jpg)

**Comment by Stifler82** [comment]
So, I confirm the report in the sense that the spell behaves as explained in the report.

But the comment you reported is a report from (Patch 2.3.3)
So maybe in WOTLK the spell might have changed.

In addition, the item has 10 charges, after which it is not possible to use it more times.
So I assume it was done on purpose to avoid "losing" the charge used.
The charge is not lost because when you "Log-out" the Server "Registers" the aura you have, in fact if you remove the item before logging out the charge is lost..

**Comment by gurveleg** [comment]
I think you missed the main point. Its not the problem that the buff is staying after relogging - that part works as it should, you have the pendant equiped and buff active so the aura is saved, the problem is buff not being removed after removing the pendant if you reloged with the buff active and pendant equiped.
Pendant has 10 charges yes, because it applies party wide aura buff (40 yards) while its active, it's one of the items that Jewelcrafters can use to make gold, because its one of the best twinking items early brackets.

**Comment by gurveleg** [comment]
Okay, I watched a few retail WotlK raiding videos (firsts kills and what not) and I have not seen anyone using Pendant of the Agate Shield buff. Were it to work like it is now (buff staying when you remove Pendant from Necklace slot if you reloged before) every raid would have 1 person with that for free +10 stamina because it stacks with other stamina buffs - they would use buff, relog, and then equip their epic lvl 80 necklace and kept on giving the raid 10 stamina buff from pendant. Tanks were minmaxing with JC because it gave 3 more stamina than other professions, or even farming some https://wowgaming.altervista.org/aowow/?item=23985 for that 5 stamina, yet no one ever uses this. It isnt mentioned in any comments or any of the raid buff guides either.

So it is safe to assume that the buff not being removed at any point when person is not wearing Pendant of the Agate Shield is a bug.
