### ISSUE TITLE
Amulet of the Moon Buff isn't removed on swapping neck if you relog after using buff

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#350]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

If you equip Amulet of the Moon (https://wowgaming.altervista.org/aowow/?item=20830) and use the buff (https://wowgaming.altervista.org/aowow/?spell=25207) then relog, It doesn't remove the buff after switching necklace/unequiping Amulet
![img](https://user-images.githubusercontent.com/80769357/113613298-4fc8a900-9651-11eb-95c1-ad1b5fbe474b.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When switching necklace or unequiping the Amulet the aura buff should be removed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be level 25+
2. Equip Amulet of Moon and use its buff
3. Relog
4. Swap the neckalce or unequip Amulet
5. See the buff stay

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Reproduced this on my test server. Equipped and used Amulet, relogged, changed necklace and the buff remained.

Server is local, AzerothCore rev. c0cb2eae38dc+ 2021-04-06 03:52:40 +0000 (master branch) 

![WoWScrnShot_040721_192210](https://user-images.githubusercontent.com/81782124/113848226-67ca3500-97d7-11eb-8570-a8d7ebd8e205.jpg)

**Comment by Stifler82** [comment]
SAME
https://github.com/chromiecraft/chromiecraft/issues/349#issuecomment-817081404
