### ISSUE TITLE
Bloodrage pulls enemies.

### ISSUE THREAD

**Issue by Hanzemon** [chromiecraft/chromiecraft#3500]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Bloodrage causes neutral or non aggroed enemies to aggro you.
I am not 100% certain but I believe it happens more when you target them and then use bloodrage.
I Know there are some weird conditions for it to happen, I am not sure but has happened serveral times. Further testing is needed.

### Expected Blizzlike Behaviour

bloodrage does not cause enemies to attack you if you are not in their aggro list.
I am not sure if this ability is even supposed to generate threat, that's why I phrase it like that.

### Steps to reproduce the problem

Target a neutral or hostile enemy that is not attacking you or anyone else
Use bloodrage
Notice how it inmediately starts combat
Onyxia wipes the raid

### Extra Notes

50 DKP minus
(he is roasting me)
![WoWScrnShot_051422_013426](https://user-images.githubusercontent.com/32701428/168412243-cf37b31d-e8c0-4f63-87c3-8a8eb646cc3e.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Hanzemon, thanks for the report!

I can't reproduce it, but that wouldn't be a surprise since like you said, it isn't a certainty that it'll work like that. Perhaps there are some elements that I'm missing as well like a raid group or some buffs/auras. Some power-restoring abilities do generate threat, although I don't know if that's the case for Bloodrage.

![WoWScrnShot_051422_034020](https://user-images.githubusercontent.com/100873791/168414358-56508f27-fe2c-40a6-b55f-8884edfc6d5b.jpg)
![WoWScrnShot_051422_034243](https://user-images.githubusercontent.com/100873791/168414361-e7492c09-300a-4b24-8207-b7e4c4c49be2.jpg)
