### ISSUE TITLE
The Great Masquerade - Windsor movement bug

### ISSUE THREAD

**Issue by DarylBlake21** [chromiecraft/chromiecraft#3502]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [] 50-59
- [X] 60

### Current Behaviour

When I started the quest The Great Masquerade (https://wowgaming.altervista.org/aowow?quest=6403), everything was fine until Reginald Windsor started to move. It was like he was bugged on the terrain and he started to fly very fast to Stormwind Keep traspassing walls. 

### Expected Blizzlike Behaviour

It's supposed to walk to Stormwind Keep without traspassing any wall and moving with a regular speed.

### Steps to reproduce the problem

1. Start The Great Masquerade quest (https://wowgaming.altervista.org/aowow?quest=6403)
2. Wait until all the dialog is over
3. Windsor start to move and it looks like he's falling, but he's stuck floating.
4. Windsor starts to "fly" all the way to the Stormwind Keep without walking through the streets, but traspassing walls with a very fast speed movement.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Hello there, DarylBlake21. Are you using the HD Patch by any chance, it has been a known problem it can cause issues with Windsor walking inside the ground and have awkward movements as in issue #3312 for example.

**Comment by Nyeriah** [comment]
The escort starts by picking up the quest. If you select the gossip (the one that starts the castle part), he'll just follow to the first castle way point. Drop the quest and pick it up again if you failed the escort.

**Comment by Gultask** [comment]
I've seen that before, for it to work properly you need to turn in 'Stormwind Rendezvous' to Squire Rowe instead of Marshal Windor, otherwise he'll go directly to the Keep RP by going that way.

**Comment by DarylBlake21** [comment]
No Dejanos, I'm not using the HD Patch. I was helping a friend with the escorting quest and all this happened. I did this quest many times and it's the first time I've seen this. The rest of the quest was working like it's supposed to work, the only issue i found is this bug, he goes straight to the Stormwind Keep passing through walls at the Valley of Heroes and through buildings at the Old Town.

**Comment by temperrr** [comment]
This happens if you incorrectly start the gossip, as nyeriah said. Since it's a  "custom" quest, we will not further adress resources to this.
