### ISSUE TITLE
Lost the ability to teleport into bwl using the Orb of Command

### ISSUE THREAD

**Issue by Creepyy0** [chromiecraft/chromiecraft#3506]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Lost the ability to teleport into bwl using the orb(I cant see the line/clickable line to teleport)
![WoWScrnShot_051522_185842](https://user-images.githubusercontent.com/104941233/168500593-d0c92a38-3bfa-4300-87e2-06d68ef88e8c.jpg)

### Expected Blizzlike Behaviour

The orb's markings match the brand on your hand.

  Place my hand on the orb.

### Steps to reproduce the problem

This is a bit iffy cus I have no clue what made it break this way.

I got into bwl fine the first time my raid had a wipe on vaelastrasz and when I ran back to the orb I simply could not teleport 

### Extra Notes

So I this bug has been on me for 3 weeks bth I don't really  expect a fix since I can't point to what broke.
It works fine on my 2 other toons

The toon's name is Ambushb

Creepy #5515 on discord if you need anything specified from me

### Operating system

Windows 10

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Hey @Creepyy0 

Have you changed faction recently?

**Comment by Creepyy0** [comment]
no

**Comment by temperrr** [comment]
Sadly, we are unable to reproduce this issue. If you have more information on how to reproduce, please make a new issue.
