### ISSUE TITLE
Client disconnecting when skinning, looting or interacting with objects too fast.

### ISSUE THREAD

**Issue by Icebeam666** [chromiecraft/chromiecraft#3508]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Interacting too fast with an object / enemy NPC consecutively will disconnect you
https://www.youtube.com/watch?v=3bVj9fOqttM&ab_channel=latampunisher
Video shows skinning attempts but it happens in all the cases I mentioned above

### Expected Blizzlike Behaviour

It should not disconnect you

### Source

From Blizzard Classic TBC
https://www.youtube.com/watch?v=2vSvDerxKo4&ab_channel=latampunisher

### Steps to reproduce the problem

Interact fast with object / enemy NPC consecutively

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Icebeam, thanks for the report!

Could you try disabling all of your addons and then reproducing the issue?

**Comment by Icebeam666** [comment]
Hey here is video with no addons, still disconnect
https://www.youtube.com/watch?v=6pba2IXl7Hg&ab_channel=latampunisher

**Comment by Gultask** [comment]
Sorry for the delay.

What's your average latency? In ms.

**Comment by Icebeam666** [comment]
Average latency 38 ms. I never have connection issues. Only this bug makes me disconnect.

**Comment by Icebeam666** [comment]
ps i noticed this behaviour during 49 bracket and have been disconnected by it many times

**Comment by Gultask** [comment]
@Icebeam666 It might be a long shot, but you could try re-downloading the client. It could be due to file corruption.

**Comment by Icebeam666** [comment]
So I tried changing realmlist to another private server. I am still using the same client only realmlist is changed. On here I do not get disconnected when doing this. So I think it is specific to azerothcore only. Do I still need to try another client?

**Comment by Gultask** [comment]
I had forwarded your report to the devs, thing is that this isn't a very easy problem to fix 😅 

A corrupted client *could* be the cause and it's good to check everything possible. I couldn't replicate it on a local sever, but then again, Chromiecraft has a lot of modules that could affect it.

**Comment by Icebeam666** [comment]
Would like to make a correction that the disconnect does not occur when interacting with enemy NPCs, only when skinning, looting and interacting with objects

**Comment by Hyperbearr** [comment]
Typically this kind of disconnect and behaviour is a result of anti-cheat. Afaik CC recently updated its anti-cheat (as per comments from the dev team in discord) and so if this is a recent issue, its likely driven by this recent update.

**Comment by Icebeam666** [comment]
Tried downloading a different client, the one from chromiecraft website and it still happens

**Comment by Gultask** [comment]
@Icebeam666 Are you playing via Wireless or a Wired connection?
If you're playing through a wireless connection then can you try switching to a wired? It's to rule out any wi-fi card or driver issues

**Comment by Icebeam666** [comment]
I am already using wired connection

**Comment by Gultask** [comment]
Unfortunately we're not sure what else to recommend at this point, sorry 😕 

Is anyone else having this problem?

**Comment by Icebeam666** [comment]
Final thing I wanted to add. In case it is not clear in the video, while I am skinning I am continuing to interact with the mob very fast. When you did the test, are you sure you interacted with the mob/object fast enough? Did a quick test and using autoclicker set to 1 millisecond interval was not fast enough to trigger DC.

**Comment by Gultask** [comment]
I tried it several times but it was in a local server without any modules so it'd be very different from testing in the CC PTR or any other pserver. And my latency wouldn't allow me to test it in the PTR as it sits around 250ms.

But it's clear in the video, thank you for posting both of them and for continuing to provide feedback.

**Comment by temperrr** [comment]
I can also sadly not replicate this issue, and therefore we cannot confirm this issue. If you do have any more ways for replicating this, or anyone else, feel free to open a new issue.
