### ISSUE TITLE
Rogue - T2 3pc set bonus - Improved Poisons

### ISSUE THREAD

**Issue by KarazhanSucks** [chromiecraft/chromiecraft#3509]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

3 pc T2 bonus should be added as a flat 5% bonus rather than the currently implemented 1.05 multiplier.
(If it's implemented correctly please guide me to the code or resource that shows the set bonus behavior.)

Deadly Poison Chance now without bonus and without talents: 0.3
Perceived Deadly Poison Chance now with bonus and without talents: 0.315

It also does some weird things when 3pc t2 bonus is worn while applying the poison but then taken off. (Seemingly drops to .25ish while it should be .30, could be scuffed rng though.)

### Expected Blizzlike Behaviour

Deadly Poison Proc rate should be increased by a flat 0.05 with the set bonus similar to how Improved Poisons talent works.

![image](https://user-images.githubusercontent.com/37310746/168672170-fddc8e52-a0f7-45e3-b918-ca432387e19a.png)
![image](https://user-images.githubusercontent.com/37310746/168672250-d41c1010-045c-4177-8d29-6a85d8f0517a.png)

Deadly Poison Chance without bonus and without talents: 0.3
Deadly Poison Chance with bonus and without talents: 0.35

Same should be checked for Instant Poison, Wound Poison and other PPM based poisons, except logic should follow:
Fixed PPM (IP can be boosted by talent) -> Conversion to % chance using Weapon Speed -> add 0.05 Chance
e.g. Instant Poison untalented but with t2 3pc set bonus;
8.5 ppm -> 2.9 WS: 41.08 % chance -> 46.08% final chance

Adding the chance multiplicative rather than additive makes this set bonus laughingly bad.

### Source

https://wotlkdb.com/?spell=14113
https://wotlkdb.com/?spell=21881
Difficult to find literal sources as poisons were reworked a few times since Bloodfang was relevant. (Another server implemented this correctly so looking for sources there, will update if found)

### Steps to reproduce the problem

1. .additem 20844 20
2. .additem 871 2
3. Apply poisons to two weapons
4. Equip a lot of hit/exp gear
5. Set up a system to track debuff application 25349 (e.g. proculas)
6. Hit thing many times
7. Calculate chance of debuffs applied / (hits+crits+glancing blows)
8. Similar for other Poisons

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Karazhan, thanks for the report!

I've been running AFK tests for a while and got these results using Recount and Instant Poison VI

Without Improved Poisons, refreshed poisons: 4465 hits, 1000 procs: 22,4%
With Improved Poisons, refreshed poisons: 3743 hits, 1001 procs: 26,7%
Without Improved Poisons, without refreshing poisons: 4693 hits, 1022 procs: 21,8%

I'm not a developer so I can't make any conclusions on these findings but I'll try to find the code behind the set bonus and see if that clears things up a bit.

**Comment by KarazhanSucks** [comment]
Hello Gultask, thanks for looking into this!

Which weapons did you use for the test, as this is important to calculate the proc chances.

With 'Improved Poisons', do you mean the talent or the set bonus, as this can get quite confusing.

Just in case:
This is not really about the talent 'Improved Poisons' but about the 3 pc tier 2 bonus (which annoyingly has the same name).
![image](https://user-images.githubusercontent.com/37310746/169101358-2838855f-9660-4851-8fd5-226568641e93.png)

**Comment by Gultask** [comment]
Oh yes, sorry for not providing all the info!
The Improved Poisons tier set bonus is an aura that is applied to the player when the set items are equipped. In this case it's this aura: https://wowgaming.altervista.org/aowow/?spell=21881
And you can add the aura to the player character by using the command `.aura 21881`
I also used the starting 1.6s daggers from rogues and just used various frenzy auras to increase attack speed and a couple of [these auras](https://wowgaming.altervista.org/aowow/?search=hit#spells) to increase hit chance to reach its cap.

Unfortunately I didn't manage to get Proculas to work in my client and also did not find the aura in any of the files I looked at.

**Comment by bonfax4** [comment]
isn't there a way to modify the value ? Make it add 100%  and see if it procs every hit and not 2x(current proc chance) ?

**Comment by Gultask** [comment]
@bonfax4 Maybe, I'm not sure, but it'd require to mess with the DB or the scripts and I don't know how.
Sorry for the late responses @KarazhanSucks, I've been busy IRL lately and have not found much time to test this.

**Comment by temperrr** [comment]
![image](https://user-images.githubusercontent.com/20357406/179666328-e885ccf6-dbc8-4967-9f7f-82fb4abe4307.png)
Adds a flat 5% atm. So should work correctly.
