### ISSUE TITLE
Surf Crawler Evasion Bug

### ISSUE THREAD

**Issue by Bigf00t117** [chromiecraft/chromiecraft#3510]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Issues involving the mob Surf Crawler (https://classic.wowhead.com/npc=3107/surf-crawler#drops). The bug caused by this mob makes them constantly evade any form of attack outside of water, once you go into the water to attack them, your attacks (magic, melee, ranged) will no longer hit the target and the Surf Crawler will still aggro and deal damage to you. When leaving the water the Surf Crawler will be aggro'd until you move far enough, however your attacks will no longer work on any other mob you encounter unless you log out or die to a mob. You will be stuck in a melee readying animation and cannot put away your weapon.

It seems also that there are some Surf Crawlers that don't behave like this, but the majority appears to be affected if they are in the water.

### Expected Blizzlike Behaviour

The expected behavior of this enemy is to aggro when provoked like any other neutral mob that you encounter. No comments on WoWHeadClassic report this issue, same with the retail WoWHead (although the location for Surf Crawlers have changed in retail).

I will be providing the comments from both classic/vanilla and retail wow:
Retail: https://www.wowhead.com/npc=3106/surf-crawler#comments
Classic/Vanilla: https://classic.wowhead.com/npc=3107/surf-crawler#comments

### Steps to reproduce the problem

1. Head to the Echo Isles (abundance of Surf Crawler mobs)
2. First check to see if ranged attacks or magic hit the mob from the outside of the water on the shoreline. (if it evades after gaining threat go into the water to see if melee works as well)
3. When in melee range attack the Surf Crawler, you will then notice you aren't using your weapon/fists to hit the mob. Proceed to leave the water and lose threat.
4. Once out of the water you will begin to see your character stuck in an animation with the melee weapon in hand as if you are in combat. Run over to a separate mob to find that you can't attack at all.
5. Either die or log out (exit is faster) and rez/log back in to see that your character has been fixed.

- Not sure if console needs to be on or not in order to see the actions of the mob. Coding experience isn't that high but I am learning.

Video of bug recorded on my channel: https://youtu.be/3H7Tfjm6fLY

### Extra Notes

Surf Crawler: https://classic.wowhead.com/npc=3107/surf-crawler#drops

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Bigf00t117** [comment]
If needed my account on ChromieCraft is Bigf00t.

**Comment by Gultask** [comment]
Thanks for the report, Bigf00t!

We're looking into it.
