### ISSUE TITLE
Loot window and looting items

### ISSUE THREAD

**Issue by Saikur0n** [chromiecraft/chromiecraft#3516]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Loot window shows two separate entries for the same item that is dropped in quantity more than one from creatures.
I am not sure if this is problem of starting areas mobs or not, I have checked this only in three starting areas of Night Elves, Human, Blood Elfs. May be this wrong behavior is on the whole server and Azeroth world.
Check the screenshots.

### Expected Blizzlike Behaviour

Loot window should show one entry for the same item that is dropped in quantity more than one from creatures and indicate its quantity on the bottom right corner of the item icon.

### Source

<details>
<summary>Screenshots wrong behavior</summary>

![Screenshot 2022-05-18 170506](https://user-images.githubusercontent.com/72514237/169060084-544a1597-e83c-41e1-a094-b27180193239.png)

![Screenshot 2022-05-18 171507](https://user-images.githubusercontent.com/72514237/169060171-8285c1a8-565e-484d-bbe3-4b622d726f32.png)

![Screenshot 2022-05-18 172425](https://user-images.githubusercontent.com/72514237/169060339-2d12cda4-3fd5-4a8b-9fc0-caceab6b00da.png)

![Screenshot 2022-05-18 173821](https://user-images.githubusercontent.com/72514237/169060490-398ef102-90aa-423d-94c7-8fbc04d0f026.png)

![Screenshot 2022-05-18 174735](https://user-images.githubusercontent.com/72514237/169060531-ba63d898-a720-4159-bbc1-03bf12b9c35f.png)

</details>

<details>
<summary>Screenshot right behavior</summary>

![Screenshot 2022-05-18 181137](https://user-images.githubusercontent.com/72514237/169060846-04efc1c1-a457-4acc-a2d6-9b4cf8cec0e1.png)

![Screenshot 2022-05-18 181209](https://user-images.githubusercontent.com/72514237/169060891-3e69c1de-79ab-4f4e-8cb5-d32f369196f0.png)

</details>

### Steps to reproduce the problem

1.Create any character (preferably Night elves)
2. Start to kill mobs around
3. Check the loot window when an item is dropped in quantity more than one.

### Extra Notes

Loot window:
[https://wowpedia.fandom.com/wiki/Loot_Window](url)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Windows 11 21H2 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Saikur0n, thanks for the report!

Just to make things clearer, are those screenshots showcasing the right behaviour from retail servers or a private server?

**Comment by Saikur0n** [comment]
> Hey, Saikur0n, thanks for the report!
> 
> Just to make things clearer, are those screenshots showcasing the right behaviour from retail servers or a private server?

Screenshots indicated as wrong behavior is from chromiecraft live server. Screenshots indicated as right behavior is from warmane server. I am so sorry about that.... I just confused. :-( I used to play a bit on retail server of wow classic and leveled up there. Later I decided to stop subscription because it doesn't worse to pay monthly for old game then switched to Warmane. I played there a lot, but then I saw ChromieCraft opensource server to which I can contribute at least with bug reports and decided to play here. But in my memory I mixed everything. :D I get used to loot window of Warmane and thought that was correct behavior, but It was mistake.
Here you can check retail behavior:
[https://youtu.be/NsyLRaUTUX0?list=PLV2pwP80QXZIEDUuxHOTSWcHLY0UZ3yHx&t=403](url)

**Comment by Gultask** [comment]
It's no problem! Thanks for contributing! 😄 

By the way, if you didn't know, you can get chromie points for valid bug reports every month!
