### ISSUE TITLE
[Teldrassil] NPC Lord Melenas (ID:2038) Spawn points

### ISSUE THREAD

**Issue by Saikur0n** [chromiecraft/chromiecraft#3517]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I have checked several times that NPC Lord Melenas spawns at the bottom floor (part) of the cave at 51,51. 

### Expected Blizzlike Behaviour

This NPC should spawn in three points. First one is at the bottom floor (part) of the cave at 51,51 (current behavior on ChromieCraft), second one on top of the ledge that is above first spawn point. The 3rd, on ledge overlooking the central cavern, also from the North.

"Entrance to his cave is 55,53. you need to take the trail starting 54,54and head north. He spawns on the buttom floor at 51,51 or on top of the ledge."

### Source

Here is the first spawn point on the bottom of the cave.
[https://youtu.be/6MxgQ2zZnQo?t=668](url)

Here you can check second spawn point on the ledge in the cave.
[https://youtu.be/TNJr75Ao7TI?list=PLV2pwP80QXZIEDUuxHOTSWcHLY0UZ3yHx&t=1265](url)

Here you can check third spawn point on the ledge in the cave overlooking central cavern.
[https://youtu.be/5tjr5LjbC7I](url)
[https://www.youtube.com/watch?v=zcHaomiA3gg](url)

### Steps to reproduce the problem

1. Go to the entrance of his cave on 55,53 (Teldrassil) near Dolaanar
2. Check the spawn points that I indicated in the problem

### Extra Notes

Here is comments from users about his spawn points.

[https://classic.wowhead.com/npc=2038/lord-melenas#comments](url)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Windows 11 21H2 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, Saikur0n, thanks for the report!

I had checked Lord Melenas before in another report and he's working fine as far as I can tell. His 3 spawn points are listed here:

![melenas](https://user-images.githubusercontent.com/100873791/169115343-d114a2e4-681d-42dc-921b-a4161fb9cf06.png)

And when I teleported there just now he was at the spawn point located on the ledge.

**Comment by Saikur0n** [comment]
> Hello, Saikur0n, thanks for the report!
> 
> I had checked Lord Melenas before in another report and he's working fine as far as I can tell. His 3 spawn points are listed here:
> 
> ![melenas](https://user-images.githubusercontent.com/100873791/169115343-d114a2e4-681d-42dc-921b-a4161fb9cf06.png)
> 
> And when I teleported there just now he was at the spawn point located on the ledge.

Oh, then I was unlucky to see similar spawn points. :) Anyway thank you for cheking. I just want to see working chromiecraft and AC as close as possible to retail.
