### ISSUE TITLE
Unexpected Results quest in Eversong Woods glitch

### ISSUE THREAD

**Issue by Nargemn** [chromiecraft/chromiecraft#352]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

https://www.wowhead.com/quest=8488/unexpected-results The quest Unexpected Results is supposed to cause several enemy mobs to spawn in the nearby area and move to attack her. The goal of the quest is to defend her from these mobs. Unfortunately, these mobs do not spawn, and the only way to currently complete the quest is to kite a different mob to her for her to attack, which you subsequently defeat.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://www.wowhead.com/quest=8488/unexpected-results

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to Apprentice Mirveda (https://www.wowhead.com/npc=15402/apprentice-mirveda) in Eversong Woods at the East Sanctum.
2. Accept the quest Unexpected Results (https://www.wowhead.com/quest=8488/unexpected-results). This requires two former quests to first be completed. These are The Wayward Apprentice (https://www.wowhead.com/quest=9254/the-wayward-apprentice) given by Magistrix Landra Dawnstrider (https://www.wowhead.com/npc=16210/magistrix-landra-dawnstrider) in Fairbreeze Village in Eversong Woods. Then you must collect dirt samples for Apprentice Mirveda by completing Corrupted Soil (https://www.wowhead.com/quest=8487/corrupted-soil)
3. The quest begins, but no enemies spawn.
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Duplicate
https://github.com/chromiecraft/chromiecraft/issues/213
And FIxed!
https://github.com/azerothcore/azerothcore-wotlk/pull/5072
