### ISSUE TITLE
Improved Blink Causes Battleground Buffs to Miss

### ISSUE THREAD

**Issue by gewmi** [chromiecraft/chromiecraft#3522]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Improved Blink (https://wowgaming.altervista.org/aowow/?spell=31570) reduces your chance to obtain the buffs from battleground chests e.g. Berserking (https://wowgaming.altervista.org/aowow/?spell=23505)

### Expected Blizzlike Behaviour

You should always be able to pick up the buff and reducing your chance to be hit shouldn't reduce your chance to get the buff

### Steps to reproduce the problem

1. Blink with the talent Improved Blink
2. While you have Improved Blink buff try to pick up a battleground buff
3. There is a 30% chance you will not receive the buff

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by gewmi** [comment]
I should have mentioned that this may just be a chance with anything that gives a chance for a PHYSICAL hit to miss on you as the buff application is physical

**Comment by Gultask** [comment]
Hi, gewmi, thanks for the report!

I think this problem might be related to this issue: https://github.com/chromiecraft/chromiecraft/issues/3456
The problem is that I've not been able to reproduce it. I've tried with a local AC and the CC PTR, with Horde characters, Alliance character and even cross-factioned characters and I've not seen the issue happening again.

Looking at the [Berserking](https://wowgaming.altervista.org/aowow/?spell=23505) and [Restoration](https://wowgaming.altervista.org/aowow/?spell=23493) it shows that they currently have "[Chance to miss](https://wowgaming.altervista.org/aowow/?spells&filter=cr=35;crs=1;crv=0)" flag, but I've not seen a single miss in at least 40 tries with the Improved Blink buff active.

**Comment by haebawari** [comment]
this was my first thought (also mage), however buffs also fail to pick up without arcane spec or even blinking.

**Comment by Gultask** [comment]
It does and I'm sure I've seen it before but I can't reproduce the issue now 😕

**Comment by Pyromanihack** [comment]
I tested it several times and could not reproduce the issue. I think the bug it's because of something else and not the Improved Blink
