### ISSUE TITLE
Horde Trauma NPC Gregory Victor not clickable

### ISSUE THREAD

**Issue by Skahabeg** [chromiecraft/chromiecraft#3531]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Received the quest Horde Trauma in OG. Travel to Hammerfall. NPC has yellow "?" but is not targetable or clickable.
Quest can't be turned in, follow up quest not be done.

### Expected Blizzlike Behaviour

click NPC, do quest

### Steps to reproduce the problem

Doctor Gregory Victor can't be targeted or clicked. commands  .npc info / .gobject near dont work on him

### Extra Notes

I did the quest with different characters using the same client.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, Skahabeg, thanks for the report!

Was there someone else in the location? While the event from the quest Triage is underway the quest giver becomes uninteractable until it's over.

**Comment by Skahabeg** [comment]
﻿Hi Gultask,

I dont recall any other player doing the quest or being in Hammerfall.
I ran around the place and picked a few herbs and re- logged because I tought maybe it’s just temporary.

**Comment by Gultask** [comment]
Ok. Thanks for the feedback.

I'll see if I can manage to reproduce the issue.

**Comment by Skahabeg** [comment]
I appreciate your feedback, but I still can’t click him. No other players around. I’ll try relog with out any addons…

Kind regards,

Skahabeg

**Comment by Gultask** [comment]
Wait, he's **still** like that?

In that case you could open a #support-ticket to get a GM to help you by maybe resetting him. His ID is 12920, you can put that in the ticket to help them.

**Comment by Skahabeg** [comment]
This worked. Thank you very much!

**Comment by Skahabeg** [comment]
Thank you, Temper killed him off and now he behaves. Love you guys!

Kind regards,

Skahabeg
