### ISSUE TITLE
Unable to obtain Paladin's Redemption spell

### ISSUE THREAD

**Issue by MagiTHEcanon** [chromiecraft/chromiecraft#3532]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Started the dwarvern quest to get the paladin res spell. However unable to use the item (tome of divinity/6916) to complete the quest line for the spell.

### Expected Blizzlike Behaviour

clicking the item should continue the quest line.

### Steps to reproduce the problem

Honestly idk, i have the spell on four other paladin in my box group, but the paladin on my main account does not.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hi, Magi, thanks for contributing!

Could you give us more information so that we can reproduce or find the issue?
What's the error message that the item is giving, if any?
Did you already start the chain?
Are you already in a quest that's part of the chain? If so, which one?
Did you use the race change service during the questline?

**Comment by MagiTHEcanon** [comment]
Ill answer what I can, but as i have 4 other pallys' (not dwarf tho, there are daenei)) with the spell, I dont know how to replicate it.
When I try to use the tome in my bag all the chat says is "You don't meet the requirements for that quest"
I currently have no quest, the last quest I did was the one before i receive the tome.
Yes ive deleted the tome many times, and reobtained it. Each saying the same thing. 
I've been unable to do any further quest in the chain at this point, on this character (Paladyn)
I've never used the race change feature on any chare as of yet, so no.

**Comment by Gultask** [comment]
Hm. The quest is working fine for me. There were some changes done to the questline that could have messed with this at some point, but that was a few months ago.
I'd suggest you to open a ticket in #support-ticket and request that the quest 1646 ([this one](https://wowgaming.altervista.org/aowow/?quest=1646)) is added to you, if it's already been completed then quest [1647](https://wowgaming.altervista.org/aowow/?quest=1647) would be your best bet.

**Comment by MagiTHEcanon** [comment]
Will do, thanks.
