### ISSUE TITLE
Explore Eastern Plaguelands achievement unachievable due to Crown Guard Tower/The Infectis Scar objectives not tracking

### ISSUE THREAD

**Issue by MarcAnthonyFanfan** [chromiecraft/chromiecraft#3533]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Explore Eastern Plaguelands achievement [https://wowgaming.altervista.org/aowow/?achievement=771] does not seem achievable due to two objectives never triggering: Crown Guard Tower and The Infectis Scar. I have explored the entire map including these locations but the achievement does not trigger for completion.

### Expected Blizzlike Behaviour

Upon exploring Crown Guard Tower and The Infectis Scar, their objectives on the Explore Eastern Plaguelands achievement should become checked off allowing completion of the Explore Eastern Plaguelands achievement.

### Steps to reproduce the problem

Navigate to the Crown Guard Tower in Eastern Plaguelands. Navigate to The Infectis Scar in Eastern Plaguelands. Observe how your Explore Eastern Plaguelands achievement does not update for either location.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by MarcAnthonyFanfan** [comment]
Screenshots of me being at the Crown Guard Tower and Infectis Scar and my achievement objectives not updating:
![Screenshot 2022-05-23 160754](https://user-images.githubusercontent.com/56124184/169899284-2a6ed887-ed55-42f0-91e2-4269590bfe61.png)
![Screenshot 2022-05-23 160918](https://user-images.githubusercontent.com/56124184/169899286-2de28054-39f2-4cbb-bb6c-f9751a550f25.png)

**Comment by Gultask** [comment]
Hello, MarcAnthonyFanfan, thanks for contributing!

I've seen this issue before, here: https://github.com/chromiecraft/chromiecraft/issues/2833 and in its linked issue. However, it was not reproduceable and any possibly related bugs have been fixed already.
Going to those places in-game has registered it for me. Is the problem still present for you? Maybe restarting your client could fix it.

**Comment by MarcAnthonyFanfan** [comment]
Hi Gultask. I initially ran into the issue a few months ago when I was trying to map every zone for the Explore Eastern Kingdoms achievement. I gave it another try today and ran into the same issue of being unable to map it. Unfortunately, restarting my client hasn't helped. I think it has something to do with the fact that I mapped this area already. So even if the issue has since been fixed, because my character has already "discovered" the location, it won't discover it again in order to check off the achievement.

**Comment by Gultask** [comment]
Ah, sorry, I misread the issue at first. If that's the case I'd suggest opening up a ticket in the #support-ticket channel with screenshots of your world map (without any addons) and your achievement progress, and then the GMs should be able to help you.
I can ask the devs about this bug too, if it's a game client issue or a server issue.

**Comment by MarcAnthonyFanfan** [comment]
Thanks, I will try opening a ticket!

**Comment by Gultask** [comment]
`.achievement checkall` should fix it. (Thanks, Roboto!)
