### ISSUE TITLE
Lesser Bloodstone Deposit

### ISSUE THREAD

**Issue by Storkell** [chromiecraft/chromiecraft#3540]
### What client do you play on?

esMX

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

There is no Lesser Bloodstone Deposit to complete the quest A favor to Krazek, when I arrived I only found gold, tin and iron ore
![image](https://user-images.githubusercontent.com/104691712/170382402-5553e283-ca52-4524-8af4-2fbe03346091.png)

### Expected Blizzlike Behaviour

There should be Lesser Bloodstone Deposits in Dry Mustache Canyon Cave in Arathi Highlands

### Source

https://tbc.wowhead.com/object=2653/lesser-bloodstone-deposit

### Steps to reproduce the problem

I'm going to the dry mustache canyon
lower bloodstone deposits do not appear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, Storkell, thanks for the report!

The Drywhisker Gulch contains several spawn points for ore nodes. Where one could contain any one of the ores you mentioned such as tin, gold, silver and mithril. Lesser Bloodstone is also a possible spawn but is not guaranteed one will spawn.

One Wowhead user says as much:
>There are veins of Iron, Mithril, Truesilver, Gold, and of course Lesser Bloodstone. ([source](https://tbc.wowhead.com/quest=627/favor-for-krazek#comments:id=2751800))

If you go back there after a while it's possible one might've spawned, especially if you've mined the other nodes in the same cave.

I'll close the issue for now, but if you need any more help don't hesitate to comment here and if there's confirmation of a bug I can reopen it right away.
