### ISSUE TITLE
[Mage][Talent] Finger of Frost proccing more often than it should

### ISSUE THREAD

**Issue by bonfax4** [chromiecraft/chromiecraft#3542]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Fingers of Frost is currently proccing on-hit and on-cast, making it proc more often than it should.

### Expected Blizzlike Behaviour

Should only proc on cast only. It used to be a on-hit only trigger until patch 3.3. Was finding it weird how often it was proccing. 

### Source

You can use https://github.com/chromiecraft/chromiecraft/issues/3123 if you need sources that it procs on cast.

### Steps to reproduce the problem

Spam frostbolt on a dummy.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by bonfax4** [comment]
There might be some exceptions to how it should trigger with aoe spells. https://youtu.be/kZ89nMP-uFM?t=5 possible its triggering per wave with blizzard considering the buff is not permanently up.

**Comment by Gultask** [comment]
Arcane Concentration had a similar problem: https://github.com/azerothcore/azerothcore-wotlk/issues/7677
From everything I've gathered from that and another issue I investigated recently it looked like it should have a chance to proc every tick, but independently of how many mobs it hits.
I can confirm from experience that it currently procs all the time because it's taking every single mob hit into consideration.

I've been a bit busy this week, so I'll take another look at this when I can. Thanks for the report, bonfax!

**Comment by bonfax4** [comment]
This post was mainly for single target spells btw like Frostbollt and possible frostfire bolt later.
The aoe interaction not exactly sure but it doesnt feel like its per wave like concentration since it procs way more often. Could be wrong tho.

**Comment by Gultask** [comment]
It's probably per-wave and per-mob-hit because it procs constantly if there's enough mobs in the area.

But I don't remember seeing it proc on-hit. It was proccing like that before it was changed in a PR some time ago that changed it to on-cast. Shouldn't be too hard to test/reproduce.

**Comment by bonfax4** [comment]
oh its also possible blizzard is currently working as it should but the way FoF is being consumed is bugged. It's another issue i'll make a post soon about but the interaction of aoe with buffs with stacks should be different. Buffs with stacks should be consumed per target hit, while still affecting the whole wave of damage. This is the case with warrior's recklessness (proof [here](https://wowwiki-archive.fandom.com/wiki/Recklessness?oldid=2378891) and [here](https://www.mmo-champion.com/threads/780263-fury-and-recklessness?highlight=recklessness))  and there's proof frost nova consumes 2 charges on 1 cast here aswell  : https://www.warcraftmovies.com/movieview.php?id=157699 @ 5:38 (Fostbolt (FoF procs) > Frost nova consumes 2 stacks). 

Only tested nova and its only consuming 1 stack regardless of number of targets so its bugged. Someone should test warrior's Recklessness, i don't play one.

**Comment by bonfax4** [comment]
On-cast requirement for fingers might be restricted to  chill spells with travel time i guess (Frostbolt/Frostfire bolt) , while cone of cold blizzard should still be per target hit. The wording on the patch note makes me believe so "Fingers of Frost: This talent now triggers immediately on casting a spell rather than being delayed until the spell strikes the target."

**Comment by bonfax4** [comment]
Maybe its easier if you aggregate all this info into a single post on Azerothcore git when you get to test this, including https://github.com/chromiecraft/chromiecraft/issues/3541

**Comment by Gultask** [comment]
>while cone of cold blizzard should still be per target hit.

Huh. The exact same happens to Arcane Concentration. Arcane Explosion *should* proc it constantly because it's per target hit.

>Maybe its easier if you aggregate all this info into a single post on Azerothcore git when you get to test this

Maybe, I just go by intuition if I should group it or not 😶 

Anyway, I got some time now, so I'll get around to it after I re-compile my local

**Comment by Gultask** [comment]
Hm. I don't know if Blizzard's FoF proc rate is incorrect.
In the video you've shown, with 5 enemies you have a ~56% chance to proc if it's per-target-hit.

In these videos:
https://www.youtube.com/watch?v=n0S3o2vaMxY
https://youtu.be/mQWWAYX3vb4?t=35
https://youtu.be/n0S3o2vaMxY?t=301

It's proccing a LOT. But it is also being consumed really fast. In CC a Blizzard tick will only consume 1 charge of FoF, while in the videos it consumes both.

**Comment by Gultask** [comment]
> oh its also possible blizzard is currently working as it should but the way FoF is being consumed is bugged. It's another issue i'll make a post soon about but the interaction of aoe with buffs with stacks should be different. Buffs with stacks should be consumed per target hit, while still affecting the whole wave of damage. This is the case with warrior's recklessness (proof [here](https://wowwiki-archive.fandom.com/wiki/Recklessness?oldid=2378891) and [here](https://www.mmo-champion.com/threads/780263-fury-and-recklessness?highlight=recklessness)) and there's proof frost nova consumes 2 charges on 1 cast here aswell : https://www.warcraftmovies.com/movieview.php?id=157699 @ 5:38 (Fostbolt (FoF procs) > Frost nova consumes 2 stacks). Someone mentioning 1 AE consuming all charges [here](https://www.mmo-champion.com/threads/621069-Shatter-in-Raiding/page3)
> 
> Only tested nova and its only consuming 1 stack regardless of number of targets so its bugged. Someone should test warrior's Recklessness, i don't play one.

I think you should open another issue for this one, since it's not about proccing, but rather consuming charges.
