### ISSUE TITLE
Talisman of Ascendance is not working correctly

### ISSUE THREAD

**Issue by haebawari** [chromiecraft/chromiecraft#3545]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The trinket applies +spell power buff on any spell cast instead of only on damage or healing spells.

### Expected Blizzlike Behaviour

Description: Use: [Your next 5 **damage or healing spells** cast within 20 seconds will grant a bonus of 40 spell power, stacking up to 5 times. Expires after 6 **damage or healing spells** or 20 seconds, whichever occurs first.](https://wotlkdb.com/?spell=28200) (1 minute cooldown)

### Steps to reproduce the problem

1. Activate trinket
2. Use any non-damage or healing spells
3. The stacks are applying.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Win 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Thank you for your report, haebawari. The talisman also procs off of auto attacks, which was fixed during original Vanilla days and should not be the case.

**Comment by haebawari** [comment]
is this gonna get fixed or am I stuck with an item that doesn't work?

**Comment by Dejanos** [comment]
I am failing to see how it does not work, you are even having and advantage with it right now. The issue was made aware for the devs to see and it will be taken care of when more dire needs have been dealt with. Considering this was reported today, it always depends on developer's current occupation and how much work to do they have already. Rest assured it will be dealth with.

**Comment by haebawari** [comment]
Consider average PvP situation: you might have to apply Mana Shield, cast Slow, Blink and the buff would be almost gone. Instead of casting 5 damage spells with increased spell power you would be able to maybe have 2 at most. There is no advantage. 

> Considering this was reported today

https://github.com/chromiecraft/chromiecraft/issues/2164#issue-1032753144
Apparently the issue was reported months and months ago. I guess that's a lesson for me too check the bug tracker before spending time farming exalted and quest stuff for items that might not work.
