### ISSUE TITLE
RDF bag gave 3x items, All of them are same.

### ISSUE THREAD

**Issue by Jermuwolf** [chromiecraft/chromiecraft#3551]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I recieved my RFD bag at mail trough postmaster, opened bag and it gave me 3x Stalwarth shouderpads of stamina. 
Each item was exacltly the same.

### Expected Blizzlike Behaviour

1 item per bag.

### Steps to reproduce the problem

Do dungeon..
Inv full.
Get bag. 
Open bag.

Once recieved 3 items.
Never been able to get this happen again, not with any char.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Jermuwolf** [comment]
![image](https://user-images.githubusercontent.com/105287176/170696772-21f7ff7b-859a-4cf3-ad76-ea63a843cb99.png)
![image](https://user-images.githubusercontent.com/105287176/170696789-6defce5b-984f-44a0-a52b-18a8b455b569.png)

**Comment by Gultask** [comment]
Hello, Jermuwolf, thanks for the report!

Can you tell me your class, which dungeon and/or what level were you at the time?
And from the Steps to Reproduce, did you have your inventory full at the time you completed the dungeon? As in, did the satchel arrive by mail afterwards?

**Comment by Jermuwolf** [comment]
Paladin, Cant remember instance due it been there for a while. 
32lvl. 
Inventory full. Arrived by mail.

**Comment by Gultask** [comment]
Thanks! I'll see if I can reproduce it.

**Comment by temperrr** [comment]
Sadly, I am also unable to reproduce this issue. If you have more information, please open a new issue.
