### ISSUE TITLE
[Mage][Talent] Finger of Frost wrong behaviour with aoe spells

### ISSUE THREAD

**Issue by bonfax4** [chromiecraft/chromiecraft#3553]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Aoe spells are currently consuming only one 1/2 stacks per instance of damage. Tested with Frost Nova, Arcane Explosion, Cone of cold and Blizzard.

### Expected Blizzlike Behaviour

Aoe spells should consume per target hit, but the consume should affect the whole "wave" of damage. Crit buffs with stacks should be consumed per target hit, while still affecting the whole wave of damage. 

This is also the case with warrior's recklessness (proof [here](https://wowpedia.fandom.com/wiki/Recklessness_(original)?oldid=2409689) and [here](https://www.mmo-champion.com/threads/780263-fury-and-recklessness?highlight=recklessness)). "(But 1 remaining charge is enough to have all attacks of a whirlwind against 4 targets while dual-wielding (total of 8 attacks) crit)"

### Source

https://www.youtube.com/watch?v=n0S3o2vaMxY Throughout this video you can see blizzard does not keep the buff up 100% of the time lie kit currently does

https://www.warcraftmovies.com/movieview.php?id=157699 @ 5:38 (Fostbolt (FoF procs) > Frost nova consumes 2 stacks)

https://www.mmo-champion.com/threads/621069-Shatter-in-Raiding/page3

https://youtu.be/n0S3o2vaMxY?t=492 (Cone of cold (FoF procs) > Arcane explosion consuming 2 stacks )

### Steps to reproduce the problem

Proc the talent the ncast any aoe spell on a large number of targets

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=44545

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by bonfax4** [comment]
Warrior Recklessness and BM Hunter's Cobra strikes should also be tested.

**Comment by Gultask** [comment]
At first I didn't get why it would consume both stacks but apply the bonus to every attack, but then I remembered that the Shatter combo relied on using "ghost" charges, or using more charges than it is consumed so it does make sense 👍 
I'll link it in a moment.

**Comment by bonfax4** [comment]
I believe you can see arcane explosion critting alott on one of the videos. When fingers is up

**Comment by bonfax4** [comment]
Also seeing how recklessness behaves the same way and it's a spell that buffs crit on next number of attacks

**Comment by Gultask** [comment]
Oh! By just doing `.aura 44544` (Fingers of Frost) and casting Blizzard in a empty area you can see that the first cast and every tick of damage consumes exactly one charge, regardless if it hits anything or not.

**Comment by bonfax4** [comment]
So either the consume should happenvon hit or the wave consume should take all charges. Matter of trying both out and see if you can replicate what happens on those retail videos

**Comment by Gultask** [comment]
I think it could be due to how FoF was changed earlier to be consumed on-cast rather than on-hit. But yeah, the miss not consuming a charge should probably be in effect here as well but it isn't.

**Comment by Gultask** [comment]
Also, **thank you** for providing these sources. I don't know how you can find all those Warcraft Movies videos 😄

**Comment by bonfax4** [comment]
Had a little help on this one from a bug report and n another project. Warcraft movies is a nightmare to navigate honestly

**Comment by bonfax4** [comment]
There is a way to filter to wotlk videos if you edit the link on there btw Wich makes it easier. Once you pick class and set date to all time you can the edit the last no and change expansion=0 to =3

**Comment by Gultask** [comment]
Thanks, I'll keep that in mind!

For google I use 'before:2011' to search WotLK stuff, and with Youtube I just sort by upload date and scroll down for a few seconds, haha.
