### ISSUE TITLE
Verog the Dervish

### ISSUE THREAD

**Issue by Vlvaldl** [chromiecraft/chromiecraft#3572]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

 I ve been searching for this guy for 1h (i know becouse i had to aply my weap enh twice ) 

### Expected Blizzlike Behaviour

 - he dosent spawn - killed all the groups many times over - he dosent spawn

### Steps to reproduce the problem

dosent spawn

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04
W10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Could be connected to the report #2229 
The triager claims there is 2% chance Dervish appears on each centaur kill near the tent, I will look into that, thank you for the report.

**Comment by Dejanos** [comment]
Seems like Verog is definitely being able to be summoned, after consulting the issue with Temper, the chance right now is 3%.
![summoned](https://user-images.githubusercontent.com/100415626/171616385-b6de35bd-e6f7-4e5d-911f-c58ad2772d4c.png)

![summoned 2](https://user-images.githubusercontent.com/100415626/171616393-794c4c05-af24-4487-ba4a-cadb552bcee6.png)


 I was unable to find Blizzlike chance of summoning Verog, but there were a lot of complains on official Blizzard pages of Verog being hard to summong, such as:
![quest 1](https://user-images.githubusercontent.com/100415626/171616333-581f70f3-79a5-4490-a7c4-ceb30addd921.png)
![quest 2](https://user-images.githubusercontent.com/100415626/171616344-9ac5b1d4-9627-4dd3-b076-7b992a2da495.png)

![quest 3](https://user-images.githubusercontent.com/100415626/171616353-63ea20b6-e9ca-4aa1-9724-034e6e10182d.png)

![quest 4](https://user-images.githubusercontent.com/100415626/171616360-24a6bbe6-0df6-40d9-982d-5c9a087273f0.png)

If you end up finding Blizzlike summon chances anywhere, or have further issues with this quest, feel free to reopen the issue or contact me or anyone in the Support section on the CC Discord, for now, I think it is safe to close this issue.
