### ISSUE TITLE
[Dungeon] [NPC]Drakkisath guards ignore sleep.

### ISSUE THREAD

**Issue by KCorruption** [chromiecraft/chromiecraft#3575]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

https://wowgaming.altervista.org/aowow?npc=10814 [Chromatic Elite Guard]
Ignores sleep effect from the following item:
https://wowgaming.altervista.org/aowow?item=2091 [Magic Dust]

[https://youtu.be/YJMTzyz7Ux4](url)

### Expected Blizzlike Behaviour

Ideally, the Chromatic Elite Guards should respect being debuffed with sleep, and not continue pursuit/attacking the party.

### Steps to reproduce the problem

1. Enter Upper Blackrock Spire.
2. Reach General Drakkisath.
3. Attempt to use magic dust item on one of his guards.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2de12c79374bdb77396e60b2c44975ed69d8acec

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by KCorruption** [comment]
If that's the case, then the debuff applied needs to not be applied, and instead replaced with the immune or resist text, no?

**Comment by Gultask** [comment]
It seems to be a problem with the item Magic Dust in particular, causing the debuff and animation to be applied to creatures that are immune, even though they'll still move and attack.

**Comment by Gultask** [comment]
Turns out the item might've been nerfed in late WotLK and should no longer function on higher level creatures:

>Very disappointed. This stuff is officially worthless now, at level 80 i tried to use this on a 78 non-elite in crystalsong forest and it fizzeled something like 100 times in a row, I decided it just wasnt going to work and proceeding to one shot the stupid satyr. I got it to work against a lvl 6 defias cutpurse though... oh and also a rat by the auction house... and after only 5 fizzles! ([source](https://web.archive.org/web/20120407065341/http://www.wowhead.com:80/item=2091/magic-dust#comments:id=1126599))

>As a 39, I was able to get the dust to work once out of every 8 or 9 times on a level 7 mob in Dun Morogh. Each time the dust fizzled, it did not get consumed. When the dust finally worked, it did get consumed. ([source](https://web.archive.org/web/20120407065341/http://www.wowhead.com:80/item=2091/magic-dust#comments:id=1110734))
