### ISSUE TITLE
NPC Ruul Snowhoof Teleporting Through Cage

### ISSUE THREAD

**Issue by Azcobu** [chromiecraft/chromiecraft#358]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

The tauren NPC Ruul Snowhoof (DB GUID 32333) is found inside Thistlefur Hold in Ashenvale at coords 41, 34. He is supposed to be trapped inside a cage, and offers a quest to free him. However, even before you begin the quest, if a hostile NPC like a Thistlefur comes within aggro range of him, he runs through the cage bars and attacks them.

The quest he begins is called Freedom to Ruul (https://wotlkdb.com/?quest=6482) but this behaviour occurs before the quest is accepted.

Should also note this seems pretty low priority, it doesn't cause any gameplay problems, it just looks weird.

![WoWScrnShot_040721_104240](https://user-images.githubusercontent.com/81782124/113796748-2150e800-978f-11eb-8d00-497ce7b1cbf2.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be stuck in the cage until you open the cage by beginning his quest. Admittedly, I can't prove this isn't Blizzlike behaviour as the two videos I found of people interacting with this NPC both started after the quest was accepted.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Command: .go creature 32333
2. Run around and aggro a Thistlefur, and pull it within aggro range of Ruul.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Two more issues I found about this NPC/Quest

1- He's always a bear since the beginning
2- He does not say any line when he goes out of the cage, the only time he speaks is at the end of the quest

Sources? Check the two videos in wowhead.
https://es.classic.wowhead.com/quest=6482/liberar-a-ruul#videos-english

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Ruul Snowhoof](https://youtu.be/40Ez3370f_w)
