### ISSUE TITLE
Hillsbrad Foothills: Inaccessible Nodes

### ISSUE THREAD

**Issue by Wendersnaven** [chromiecraft/chromiecraft#3582]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

In Hillsbrad Foothills, between Azureload Mine and Hillsbrad Field, just off the main road, there are a set of inaccessible nodes. Mini map shows they are on the surface rather than underground. There is no underground area in that section.
![WoWScrnShot_060522_012427](https://user-images.githubusercontent.com/106900565/172039254-2b07b367-603a-41f2-a07a-1a0a50105582.jpg)

### Expected Blizzlike Behaviour

Visible nodes should be accessible; should not be layered underneath the surface without caves or mines.

### Source

![WoWScrnShot_060522_012443](https://user-images.githubusercontent.com/106900565/172039315-8c3a56b4-5997-4e07-9c15-23aae9878882.jpg)
No addons used, otherwise coordinates would be provided.

### Steps to reproduce the problem

To ensure this set of nodes was not mistakenly underground, yet close enough to the surface to appear that way on the mini-map, I quickly farmed all nodes within the Azureload Mine, then proceeded to coordinates where the mini-map displays several nodes. There are no visible nodes or path to them. They are confirmed not not be part of the Azureload Mine or any other underground area.
![WoWScrnShot_060522_012644](https://user-images.githubusercontent.com/106900565/172039386-9b95328b-6dd7-4856-9b7f-8244aea9e569.jpg)
![WoWScrnShot_060522_013100](https://user-images.githubusercontent.com/106900565/172039414-9a50f186-56e4-4512-aa9d-dd5bbbe89f5e.jpg)

### Extra Notes

One copper, one silver, one tin, stacked on or near each other. Directly north of the mines, and south of Hillsbrad Fields, near the main road.
![WoWScrnShot_060522_013132](https://user-images.githubusercontent.com/106900565/172039446-9121d546-e08a-456c-8d2d-96483f6cfef5.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2de12c79374bdb77396e60b2c44975ed69d8acec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, Wendersnaven!

I can confirm.
