### ISSUE TITLE
Repeatable Tips for Beginners Tutorial in each login

### ISSUE THREAD

**Issue by Saikur0n** [chromiecraft/chromiecraft#3589]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Players need to complete beginner tutorials every time they log in to the game even if they already completed them.

### Expected Blizzlike Behaviour

Tutorials completed by players at least on one character in the account should no longer appear after new login or creating new character.

### Steps to reproduce the problem

1. Create new account
2. Login to the game
3. Create new character
4. Enter the world
5. Complete several tutorial tips while leveling
6. Logout from the game
7. Login again to the account
8. Enter to the world with your character
9. See tutorial tips that repeats itself.

### Extra Notes

This issue is open on azerothcore repository.
https://github.com/azerothcore/azerothcore-wotlk/issues/11974#issue-1262600217

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Windows 11 x64 21H2

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Hello, [Saikur0n](https://github.com/Saikur0n). When I clicked your link for the Azerothcore Repository, I got no issues found. One way you can make sure tutorials do not appear is by going Interface> Help and uncheck Tutorials and Beginner Tooltips, meanwhile, I will check if tutorials keep repeating for all new accounts, as if it's Blizzlike.

**Comment by Santaria94** [comment]
This is more like an individual problem with the game client. Right click on the game folder and check the "Readonly" attribute. Disable it if it is enabled.

**Comment by Saikur0n** [comment]
> Hello, [Saikur0n](https://github.com/Saikur0n). When I clicked your link for the Azerothcore Repository, I got no issues found. One way you can make sure tutorials do not appear is by going Interface> Help and uncheck Tutorials and Beginner Tooltips, meanwhile, I will check if tutorials keep repeating for all new accounts, as if it's Blizzlike.

Yeah, I know this, that tutorials can be disabled. But anyway it behaves incorrectly and should be fixed. On warmane server such bug doesn't exist.

**Comment by Gultask** [comment]
I couldn't reproduce it with a new account on a local server. As far as I know the tutorials should be disabled in the Warcraft Text Files (WTF) folder.
There can also be a couple of problem if you install your client in the windows 'ProgramFiles' folder, is that your case? Read-only folders would also make it impossible for the client to write new values in WTF, causing settings like those to disappear. As for it not appearing in other Private Servers it could be due to a number of things, such as settings being saved to the other realm only or it being disabled in the other server.

**Comment by Saikur0n** [comment]
> I couldn't reproduce it with a new account on a local server. As far as I know the tutorials should be disabled in the Warcraft Text Files (WTF) folder. There can also be a couple of problem if you install your client in the windows 'ProgramFiles' folder, is that your case? Read-only folders would also make it impossible for the client to write new values in WTF, causing settings like those to disappear. As for it not appearing in other Private Servers it could be due to a number of things, such as settings being saved to the other realm only or it being disabled in the other server.

Thank you for trying to reproduce it. May be I described problem unclear. I don't mean that when I disable beginners tutorial and re-login to the game they appear again. I know that game settings save files to WTF as well as Account folder. ^ ^ My game folder located in User - Downloads folder and WTF file is not read only all games settings saved there successfully.

The problem is when I play game with beginners tutorials enabled and accomplishing them during questing with new character, for example Night Elf, then completely log out from the game (exit) then log in again to my account and enter world with this character the tutorial tips pops out again and repeats itself with loop. Just try to enable tutorial tips, create new character, accomplish several of them, like Combat Mode, Looting, Bags, Full Bags etc... After that completely exit game, log in again to the same character and you should see this tutorials looping. By the way first of all if you don't see tutorials on new character try to reset them from settings. This is bug on chromiecraft live server. Try to do this on warmane for example.

How it should be:
Beginners tutorials that has been read should not re-appear again after each log in to the game.

**Comment by Saikur0n** [comment]
@Gultask You can read replies in this thread. I don't know if this problem happens only with our accounts.
Reply 1: https://github.com/azerothcore/azerothcore-wotlk/issues/11974#issuecomment-1153336584
Reply 2: https://github.com/azerothcore/azerothcore-wotlk/issues/11974#issuecomment-1153379831

**Comment by Stump876** [comment]
I'm confused, If the issue is already over on AC, why bring it up here? We confirm the problems picked up from CC and send them over to AC to get fixed. If it's already over there, there's not much we can do about it here.

**Comment by cjl3230** [comment]
@Saikur0n Has the problem been solved

**Comment by Saikur0n** [comment]
> @Saikur0n Has the problem been solved?

@cjl3230 Last week I checked, problem hasn't been solved. Now I don't have time to check it. I wanted to ask you this. ) I closed issue here, because we have main thread on AC repo.

**Comment by cjl3230** [comment]
> 

Ok, I'm also waiting for the official AC to deal with it

**Comment by cjl3230** [comment]
> > @Saikur0n Has the problem been solved?
> 
> @cjl3230 Last week I checked, problem hasn't been solved. Now I don't have time to check it. I wanted to ask you this. ) I closed issue here, because we have main thread on AC repo.

Ok, I'm also waiting for the official AC to deal with it
