### ISSUE TITLE
Alterac Valley NPCs still friendly when cross faction queued

### ISSUE THREAD

**Issue by Scapulla** [chromiecraft/chromiecraft#3591]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Some NPC's aren't hostile when you join AV when "crossfactioned". 

### Expected Blizzlike Behaviour

No crossfaction pvp in blizz, so no idea what to expect. 

### Steps to reproduce the problem

Go into AV as an alliance character but queuing in as horde because of crossfaction. Athramanis and the gnome next to her are untargetable as foes. Lana could still be killed, but the others weren't.
![WoWScrnShot_060622_204434](https://user-images.githubusercontent.com/85845643/172977193-d6eb99c2-8fcd-41c1-a5ec-4e57a4ca9cd1.jpg)
![WoWScrnShot_060622_204509](https://user-images.githubusercontent.com/85845643/172977197-ef1db642-a51f-4cac-879e-7a6b7e0cf76f.jpg)
 

### Extra Notes

I have seen some other issues opened but the problem was the other way, npcs were marked as hostile when they shouldn't be (I.E.https://github.com/azerothcore/mod-cfbg/issues/76)  . I don't know if this issue is a different one, but i guess the behavior is slightly different so worth noting.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Tebec** [comment]
It is probably specific to those NPCs, as horde queueing in those are still hostile if it sets you to ally, but I don't remember seeing any friendly ones in the horde base. I'd marked it up as the nature of trying to force cross faction BGs.  Related horde can not do turn-ins if they got in as ally.

**Comment by Gultask** [comment]
Alliance to Horde and Horde to Alliance x-faction respectively

![WoWScrnShot_061022_141202](https://user-images.githubusercontent.com/100873791/173117685-f45aa5ae-9905-456f-bcb2-88556f4585b1.jpg)

![WoWScrnShot_061022_141209](https://user-images.githubusercontent.com/100873791/173117695-3add9dfe-49bc-4dc3-99ef-84225b9937ff.jpg)
