### ISSUE TITLE
Wrong dialogue from horde first aid trainer

### ISSUE THREAD

**Issue by Loukaz** [chromiecraft/chromiecraft#36]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### SMALL DESCRIPTION:
The dialog of the horde doctor at hammerfell is the one from the alliance doctor

##### EXPECTED BLIZZLIKE BEHAVIOUR:
the horde doctor at hammerfell must use his own dialogue and so must do the alliance doctor at theramore wich i should suggest to investigate too

##### CURRENT BEHAVIOUR:
https://wotlk.evowow.com/?npc=12920

##### STEPS TO REPRODUCE THE PROBLEM:
 - Talk to gregory victor and see his dialogue is not his own. he is presenting himself differently

[https://cdn.discordapp.com/attachments/806916563810385970/806918959382396968/Wow_JVNhb9gWuz.jpg](https://cdn.discordapp.com/attachments/806916563810385970/806918959382396968/Wow_JVNhb9gWuz.jpg

)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacaw** [comment]
Confirmed for the horde-side.
The [https://wotlk.evowow.com/?npc=12939](Doctor Gustaf VanHowzen) aliance trainer is fine.

**Comment by Si1ker** [comment]
fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/5032
