### ISSUE TITLE
[Eversong Woods] (Fairbreeze Village) Springpaw Stalker walking through a solid tree

### ISSUE THREAD

**Issue by Vladimirjov** [chromiecraft/chromiecraft#3600]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

See screenshots attached. There is a Springpaw Stalker that is able to walk through a solid tree. See steps below how to find the monster in question.

PS: Sorry for reporting minor bugs like this. But I think it's necessary to make the server quality as good as possible. Thanks a lot for fixing
![WoWScrnShot_061122_195849](https://user-images.githubusercontent.com/81888445/173199838-d334a73d-a900-462c-8833-070c8c898845.jpg)
![WoWScrnShot_061122_195727](https://user-images.githubusercontent.com/81888445/173199849-9bcbba8c-66ad-45d1-916a-7ef4c703b03c.jpg)
!

### Expected Blizzlike Behaviour

I don't play the retail version so i can't check what is blizzlike. But I think mobs walking through solid trees shouldn't be possible. 

### Steps to reproduce the problem

1. Go to the Fairbreeze Village, look straight out of the back entrance. Compare it to the screenshot. It's the tree in the middle of the screenshot.
2. Walk towards the tree until you find the Springpaw Stalker.
3. Observe it until it walks right into a solid object.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello again, Vladimirjov, thanks for the report!

That Springpaw Stalker (GUID: 55960) is set to wander randomly in a radius of 5y from its spawn point. And it will not go where it can't move, if it sees a wall, it stops.
However, I saw that he can climb the sides of the tree near him and clip into it, only to leave after more wandering.

I think this case is due to NPC movement and mmaps, but I'm not sure. I'm not very knowledgeable in this so I'll leave it to the others to figure out if this is an isolated case or a more generic issue that would require tweaking.

If you happen to find any more like this or any problem in general while questing please let us know :)

**Comment by Stump876** [comment]
Unsure if it's related, but I've seen several similar issues in badlands 
.go c 6910
![image](https://user-images.githubusercontent.com/68164076/174492985-2cdf25fd-ed38-46a4-9b8f-54dcd4af2f09.png)

.go c 6900
![image](https://user-images.githubusercontent.com/68164076/174493004-b9238870-82a4-4c7b-b459-9734c7c945e5.png)

**Comment by temperrr** [comment]
The ones in badlands is actually blizzlike

**Comment by temperrr** [comment]
This is indeed a pathing issue with maps, and not something we can solve on a case by case basis. Thanks for the report, though!
