### ISSUE TITLE
[Minor][Stranglethorn Vale] Gazban's missing dialogue

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3605]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

[Gazban](https://wowgaming.altervista.org/aowow/?npc=2624) is missing the dialogue after being summoned from the altar (summoned and killed him twice).

![WoWScrnShot_061222_084547](https://user-images.githubusercontent.com/79346412/173221236-4dc56efc-3fb0-453c-bdd3-c05eb02aa085.jpg)
![WoWScrnShot_061222_084653](https://user-images.githubusercontent.com/79346412/173221239-e7517727-03c2-43b1-be85-a5f588476462.jpg)

### Expected Blizzlike Behaviour

He should have this dialogue after spawning:

    Gazban yells: What is happening? What force draws me to the Altar of the Tides!
    Gazban says: Oh now you've gone and angered me! Time to see the true force of the Stone of Tides!

### Source

AoWoW DB

### Steps to reproduce the problem

1. Follow the SV Alliance storyline up to [The Curse of Tides](https://wowgaming.altervista.org/aowow/?quest=611)
2. Summon Gazban at the altar
3. Observe the lack of dialogue

### Extra Notes

[Gazban](https://wowgaming.altervista.org/aowow/?npc=2624)'s data:

- DB GUID: **0** (current GUID: **197962**), Entry: **2624**

[Altar of the Tides](https://wowgaming.altervista.org/aowow/?object=2576)
 - 64 (Entry: **2576**)
 
 [The Curse of Tides](https://wowgaming.altervista.org/aowow/?quest=611)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by benjymansy123** [comment]
Been cross-reported here: https://github.com/azerothcore/azerothcore-wotlk/issues/12059
