### ISSUE TITLE
Impossible to target "Kroshius" in "Kroshius' infernal core" quest

### ISSUE THREAD

**Issue by ArkaNoum** [chromiecraft/chromiecraft#3611]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

It was impossible to target Kroshius. I called a GM, he could target him while I still could not, even trying to respawn.
I also tried to type "/target Kro" if I was missclicking or anything.
I deleted my cache AND disabled my add ons, nothing was working.

### Expected Blizzlike Behaviour

I should simply be able to target his corpse. I saw physicaly it, but couldn't target to use my item.

### Steps to reproduce the problem

Just grabbed the quest with a human warlock, I did nothing special, even played the game "vanilla" to see if any add on or cache was in conflict.

### Extra Notes

At least the GM was able to see Krosius.
https://gyazo.com/43b75b8ff7ebeb5aa646aab1ba253906
https://gyazo.com/1b4805d6ec0fde8029a87fd53a597300
https://gyazo.com/4113d6de8a50508d7930036700fff14d

Different screenshots of the issue

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ArkaNoum** [comment]
This is the quest 
=> https://classic.wowhead.com/quest=7603/kroshius-infernal-core

This is how it should've work https://youtu.be/SGuvxeucCj0

**Comment by Stump876** [comment]
I can confrim he can't be targeted. But you should still be able to summon him just standing on his corpse. Did you try just clicking on your fel fire in the pile of rubble?
![image](https://user-images.githubusercontent.com/68164076/173277947-8a43757c-c311-4b9a-b50b-b39eef6ae6ae.png)

**Comment by ArkaNoum** [comment]
I tried to use the item. Maybe I wasn't on the exact good spot.
=> https://gyazo.com/1b4805d6ec0fde8029a87fd53a597300

On this screen, you can see "requires Kroshius' remain" when I tried to use the item
