### ISSUE TITLE
Onyxia is considered a Lich King 10-player raid boss in statistics.

### ISSUE THREAD

**Issue by benjymansy123** [chromiecraft/chromiecraft#3614]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Dying to Onyxia in the current version of CC (Vanilla) counts as the Lich King version in statistics.
![image](https://user-images.githubusercontent.com/38561765/173297848-bda55e83-5d25-4210-aaec-5ddf0e54c6c2.png)

### Expected Blizzlike Behaviour

Onyxia should not be considered for this statistic and it should be `--` as it is for the other statistics.

### Source

Common sense

### Steps to reproduce the problem

1. Die to Onyxia as she is with the progression module.
2. Observe that she is considered the deadliest Lich King 10-player raid boss you've encountered.

### Extra Notes

Obviously a minor issue, but it is an issue nonetheless.

EDIT: This statistic is stored in `characters.character_achievement_progress` where the criteria is 13276 (Killed by creature: Onyxia.) I could see a solution for this issue looking something like not allowing that criteria to be saved in the DB until you reach the progression bracket where Onyxia becomes available in her level 80 form.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi benjymansy123   This is due to the custom content, I don't think this is an AC bug. Trying it on my local, it is an 80 raid.

True blizzlike behavior- Onyxia is not supposed to be open to level 60's in 3.3.5. It's registering the kill and assuming it's the 80 version, because that is the only version that should be available in 3.3.5. I would say the root cause of this is the 60 version of Onyxia, not the achievement system.

**Comment by benjymansy123** [comment]
> This is due to the custom content, I don't think this is an AC bug.

I know it's not an AC bug, that's why I'm not making an issue on AC's repo. In my opinion, if this issue is to be linked to another repo, it would be to the mod-progression-system repo, but that's not my call. I'm opening the issue here because it *is* an issue, again a small one, but an issue nonetheless. If this isn't something people want to deal with, then so be it; close the issue. But I feel that this issue, like the cross-faction battleground crash issue, is one that should be reported here at the minimum.
