### ISSUE TITLE
Fishing Skill Does Not Level Up Correctly

### ISSUE THREAD

**Issue by Slysam** [chromiecraft/chromiecraft#3619]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Currently the way that fishing works in AC is that only successful "fish" catches can level up your skill, catching junk does not ever level up your skill, making it impossible to level up your fishing by catching junk in areas that are too high level for you.

### Expected Blizzlike Behaviour

In WotLK after patch 3.1.0, Fishing was significantly reworked and allowed you to catch 'junk' anywhere that you could fish, though you would only actually catch 'fish' if your skill was high enough for where you were fishing. So you could, for example, level fishing from 1-450 without ever leaving Dalaran, even though as it works in AC currently, you would never be able to level up by catching junk or coins in the fountain.

### Source

https://wowpedia.fandom.com/wiki/Fishing

Wrath of the Lich King [Patch 3.1.0](https://wowpedia.fandom.com/wiki/Patch_3.1.0) (2009-04-14): Fishing has undergone significant changes.
There is no longer a minimum skill requirement to fish in any zone. Every catch has the potential for fishing skill gains, but you are likely to catch worthless junk in areas that are too difficult for your skill.
The time to catch fish has been reduced to 17 seconds, down from 22.
Fish can no longer get away.
It is no longer required to complete [Nat Pagle, Angler Extreme](https://wowpedia.fandom.com/wiki/Nat_Pagle,_Angler_Extreme) to gain Artisan Fishing.
You no longer need to learn fishing from books. The trainers have finally done their reading and are able to teach you the same thing.

### Steps to reproduce the problem

1. Have a fishing skill of 1. Attempt to go anywhere with a 'high level' of fishing. Winterspring, Wintergrasp, Dalaran, Silithus, etc.
2. Attempt to catch fish.
3. Catch only junk.
4. Observe that you do not gain skillups.

### Extra Notes

It took me a long time to even realize that this was a problem because you can still leveling fishing 'normally' by just fishing from 1-300 on CC in SW/Org, but if you try to fish anywhere else and catch junk, you don't get skillups. And this isn't just "Well skillups from catching junk are rare"(which they shouldn't be at low levels anyway), it's that you cannot get skillups from junk fishing at all. I attempted to fish in Tanaris for over an hour and got 0 skillups from catching junk, but as soon as I fished in a fishing node and successfully caught a fish, I gained a skillpoint(Since you always have a chance of catching fish from a node even without the proper fishing skill), which shows that you -CAN- still get fishing skillpoints when you're below the level of the area you're in, just not from junk.

You can even find guides for fishing from back in WotLK that just tell you "fish wherever" because you can get fishing skill from catching junk and could go from 1-450 in Dalaran's fountain catching coins if you wanted to, which is currently impossible.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36f0a7757bde9573262f298aa1eaf6765af8295e

### Operating system

Ubuntu 20.04
Win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello Slysam. Thanks for the report. I can confirm this does not level correctly.
![image](https://user-images.githubusercontent.com/68164076/174492476-83dca5eb-c7fe-4c9f-9a89-2799db0aa5fa.png)
