### ISSUE TITLE
Wastewander mobs in Tanaris higher chance of dropping Tough Scorpid Recipes

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#362]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39

##### CURRENT BEHAVIOUR:

Wastewander Bandit,Rogue,Thief have higher chance of dropping Pattern: Tough Scorpid Helm,Gloves,Leggins,Boots,Breastplate,Bracers.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The chance of the mentioned mobs dropping said recipes should be much lower.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Tanaris.
2. Kill Wastewander Bandit,Thief or Rogue.
3. You will see a lot of of said recipes drop.
4.Repeat.

##### EXTRA NOTES:

Wastewander mobs links:
https://wotlkdb.com/?npc=5618
https://wotlkdb.com/?npc=5616
https://wotlkdb.com/?npc=5615
Recipes Links:
https://wotlkdb.com/?item=8402
https://wotlkdb.com/?item=8401
https://wotlkdb.com/?item=8397
https://wotlkdb.com/?item=8400
https://wotlkdb.com/?item=8399
https://wotlkdb.com/?item=8398
https://wotlkdb.com/?item=8395

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
![image](https://user-images.githubusercontent.com/1884642/114259890-43ce4580-99c9-11eb-91c0-4b03cb2147b9.png)
Drops rate are correct

**Comment by Narixel** [comment]
Are you sure?Because it happened to me to kill 3 mobs and get 3 tough scorpid recipes in a row.

**Comment by Stifler82** [comment]
> Are you sure?Because it happened to me to kill 3 mobs and get 3 tough scorpid recipes in a row.

I also showed you the loot chance in the image.
