### ISSUE TITLE
[PTR] [ZG] Edge of Madness - Renataki constantly casting Thousand blades

### ISSUE THREAD

**Issue by fendwe** [chromiecraft/chromiecraft#3629]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

shortly after combat start, boss is stuck in loop casting thousand blades and occasionally gouge until he vanishes

as a side note, boss is also not using ambush when getting out of stealth

### Expected Blizzlike Behaviour

attacks should have abit more variety? would at least expect some regular melee swings

> His special ability is to use [vanish](https://wowwiki-archive.fandom.com/wiki/Vanish) and he will randomly appear and ambush someone which can do quite a bit of damage.

Source: https://wowwiki-archive.fandom.com/wiki/Renataki_(original)#Strategy

### Source

.

### Steps to reproduce the problem

1. engage boss
2. wait for a few seconds
3. observe boss casting thousand blades non-stop while not in stealth

### Extra Notes

![WoWScrnShot_061722_191048](https://user-images.githubusercontent.com/61170874/174402257-da910fd3-3325-4308-8763-011e06ffee0b.jpg)

i also found this video of renataki, which seems to show some sort of scripted event for his summoning?
https://www.youtube.com/watch?v=z_RATFD--xk

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36f0a7757bde9573262f298aa1eaf6765af8295e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Yes the summoning event hasn't been implemented yet.

Does he cast it constantly or does he cast it like 2-5 times? because casting it several times back-to-back is blizzlike: https://youtu.be/urX62TDf1gM?t=125

**Comment by fendwe** [comment]
Combat Log between 2 Vanishes
![image](https://user-images.githubusercontent.com/61170874/174416541-0a11903a-bfc9-401b-849f-746d8ce517ac.png)

**Comment by Gultask** [comment]
Yeah I was busy with Mandokir, but I saw that right away when I spawned Renataki. Thanks for the heads up and the screenshot, I'll put it in the report. Renataki's a pain, honestly.
