### ISSUE TITLE
Stuck "in combat" during dungeons

### ISSUE THREAD

**Issue by NidaleeLiadrin** [chromiecraft/chromiecraft#363]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x ] 1-19
- [x ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Type here.
While progressing through the dungeon **Blackfathom Deeps** (https://wowgaming.altervista.org/aowow/?zone=719), at a certain moment I got stuck in the stat of " in combat", 2 other players had the same problem. We couldn't use our food/drinks nor get our potion's cooldown to start . We went back to check if there is any mob left on agro and killed few but didn't solve problem. We had to suicide then revive to solve the issue, which re-appeared again after progressing a bit further and couldn't get ride of it until exiting dungeon.
Spots in which the problem started occurring :
1: After defeating boss **Ghamoora** (https://wowgaming.altervista.org/aowow/?npc=4887)
2: Before facing **Twilight Lord Kelris** (https://wowgaming.altervista.org/aowow/?npc=4832)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

 ( i switched to another fresh/clean client to play on making sure it's not client-side/addons problem ) Couldn't reproduce it intentionally but happened again after few hours at dungeon " Wailing Caverns " ( only me ) for a duration of approx. 6mins then got out of combat. ( one of my party members suspected that somehow a mob holds agro and doesn't act like it is )

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by NidaleeLiadrin** [comment]
Happened again to me and another guy in the dungeon Blackfathom Deeps. After clearing the last boss. we went back to check which mob is causing the problem.
In our case it was an underwater Deep Pool Threshfin. it did hold agro despite not being near us, not chasing us or even attacking us. once killed , problem solved.
EXTRA :
https://classic.wowhead.com/npc=4827/deep-pool-threshfin
Player selected NPC
DB GUID: 27390, current GUID: 3431147.
Faction: 16.
npcFlags: 0.
Entry: 4827.
DisplayID: 2836 (Native: 2836).
Level: 23.
EquipmentId: 0 (Original: 0).
Health (base): 1815. (max): 1815. (current): 348.
Unit Flags: 557120.
Unit Flags 2: 2048.
Dynamic Flags: 4.
Faction Template: 16.
SpawnTime: Full:1d Remain:0s
Loot: 4827 Pickpocket: 0 Skinning: 100007
InstanceID: 603
Phasemask: 1
Armor: 940
Position: -763.394409 -77.895645 -33.168270.
AIName: SmartAI ScriptName: 
MechanicImmuneMask: 0

**Comment by NidaleeLiadrin** [comment]
Tested 5 times. Every time its the Deep Pool Threshfin (https://wotlkdb.com/?npc=4827) . Usually in this spot :

![WoWScrnShot_040821_065134](https://user-images.githubusercontent.com/81931212/114039974-08504180-9838-11eb-88d2-0edded6929cf.jpg)

**Comment by Stifler82** [comment]
For me the Bug is not there, but it is also true that we recently passed a Fix that solves similar problems, so probably the problem has been solved..
So I close.
If the problem recurs, DO NOT OPEN another report, comment on this report and I will open it again.
**Video Test:** [Stuck in combat](https://youtu.be/zt42jBt2Kyc)
