### ISSUE TITLE
Warrior Charge/Intercept mechanics doesn't work properly

### ISSUE THREAD

**Issue by creativemonkeyz** [chromiecraft/chromiecraft#3638]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

If an warrior Intercept a druid that have Nature's grasp on him, warrior is be rooted BEFORE warrior reach the druid.
If Frostbite activate in the moment that warrior press Charge/Intercept warrior freeze BEFORE he reach mage.
If an warrior have a freezing trap between him and the hunter, warrior  first FREEZE and he never reach hunter.
This issue was FIXED but now appeared again that's why I open another bug report because this is a big downgrade to warriors.

### Expected Blizzlike Behaviour

If an warrior Intercept a druid that have Nature's grasp on him, warrior MUST be rooted AFTER warrior reach the druid.
If Frostbite activate in the moment that warrior press Charge/Intercept warrior MUST freeze AFTER he reach mage.
If an warrior have a freezing trap between him and the hunter, warrior should first REACH hunter then freeze.

### Steps to reproduce the problem

1. Your druid target must have Nature's Grasp active on him
2. Use berserk stance and use INTERCEPT
3. Warrior don't reach druid, he's being rooted on initial place
4. Also with mage is harder to reproduce, mage must cast frostbolt on you and when warrior charge/intercept and frostbolt reach warrior and Frostbite is activated warrior remain in the place when frostbite activated instead of reaching the mage.
I think second issue will be solved with first one, because seems to be the same mechanics and be a charge/intercept issue
Also with a hunter:
put freezing trap between you and the warrior
warrior charge and it s freeze where freezing trap is BUT hunter see him near himself
when warrior is out of trap hunter see him teleported back
Also with hunter:

hunter put freezing trap between me and him, and at his position he put Fire trap.
warrior charge --> first time i'm frozen before i reach him BUT then the Fire trap is activated. even if i m not there

### Extra Notes

Thank you for your time :)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, creativemonkeyz, can you see if this bug still exists? and if it does, could you provide a video?

I can't seem to reproduce it in a local. Either with Freezing Trap or Nature's Grasp.

https://user-images.githubusercontent.com/100873791/175779734-548fec13-688b-446d-900f-1d38d6371b96.mp4

**Comment by Gultask** [comment]
This should've been fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/10192 back in January
