### ISSUE TITLE
Shaman Spirit Wolves have independent cooldowns that they use

### ISSUE THREAD

**Issue by Luckdemon** [chromiecraft/chromiecraft#3642]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Shaman's Ability Spirit Wolves (Spell ID 51533) summons Spirit wolves under the command of the Shaman.
These wolves have abilities:
Bash spellid: 58861 with 45 second cooldown
Spirit Walk spellid: 58875 with 32 second cooldown and 15 second duration
Spirit Wolf Leap spellid: 58867 with 20 second cooldown
Twin Howl spellid: 58857 with 15 second cooldown and 6 second duration

Currently if the spells are clicked or activates from the player's hotbar, the ability goes on cooldown, but if the spells are set on auto-cast, each wolf has its own unique cooldown.

Effects of this:
Wolves Bash twice in a row.
They can individually jump after targets depending on their range.
Spirit walk is autocast twice and extends the duration by overwriting itself by around a second.
Howl is cast from each wolf after the other wolf's howl falls off, leading to a 12 second uptime and a 3 second downtime overall.

To abuse this, a player may toggle autocast on and off very quickly to only allow one wolf to autocast his ability.
Effects of this:
Bash can be triggered 2x in the cooldown as necessary for interrupts.
Spirit walk can last 30 seconds with only a 2 second downtime for the entire duration of spirit wolves.

Additionally, when autocast is turned off and the abilities are clicked by the player, it consumes both wolf's bash/howl/sprint/leap at the same time.

### Expected Blizzlike Behaviour

Wolves cooldowns should be shared between them, so you cannot abuse near 100% uptime in their abilities.
I do think the jumps should work independently, but the other abilities definitely should not be.
Consensus on the cooldowns and use of abilities seems to be unclear according to comments on Wowhead.
https://www.wowhead.com/spell=51533/feral-spirit#comments
Comments mention 2 bashes, but not 2 sprints etc.

### Steps to reproduce the problem

1. Summon wolves
2. Set wolves to passive
3. Turn off auto-cast on abilities
4. Set wolves to attack target dummy
5. Click abilities individually or toggle autocast on and off VERY quickly to only use one

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by leandro2000vieira** [comment]
yeah, when I am doing pvp and I use spirit wolves and spirit walk fast, near one enemy. Only one wolve use it and I can save another spirit walk.
I thinks the big problem with wolves is spirit wolve leap. Each time we call wolves they reset to angry and set auto-cast on bash and spirit wolve leap.
So, if you do spirit wolve leap with spirit walk it gonna happen
do that : 
/cast [nopet] Feral Spirit
/cast [@target] Spirit Wolf Leap
/cast [@player] Spirit Walk 
and only one wolve gonna use a spirit walk

**Comment by Cythisiax** [comment]
Not replicating this behavior for current build CC PTR https://streamable.com/eyavcg , with provided instructions at least. Macro test as well, https://streamable.com/o28dzy
