### ISSUE TITLE
https://classic.wowhead.com/quest=2954/the-stone-watcher

### ISSUE THREAD

**Issue by anjxed** [chromiecraft/chromiecraft#3646]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When I get to Tanaris the stone watcher appears. I can complete the Stone watcher quest and then I have to listen to the story. I cannot proceed since either the quest thingy conversation is bugged. I abandoned the quest and retook it several times to see if I can proceed with the conversion/story. However, after abandoning and retaking 3 times. Norganon disappears and I cannot get the quest to listen to the story.

### Expected Blizzlike Behaviour

https://classic.wowhead.com/quest=2954/the-stone-watcher
and
https://classic.wowhead.com/quest=2946/seeing-what-happens

I should be able to hear the stone watcher's story and complete the quest

### Steps to reproduce the problem

1. Accept quest to go to Tanaris Valley of watchers
2. Talk to the stone watcher to complete quest and accept another quest
3. talk to stone watcher to listen to his story to complete. (No option to proceed with quest)
4. Abandon quest and retake several times.
5. Norganon will disappear and cannot accept the quest or continue with questline

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello Thanks for the report However I'm unable to duplicate this on my local server, or on the CC PTR. I see all steps of the conversation.
![image](https://user-images.githubusercontent.com/68164076/175753672-524a3f43-f9b9-4f32-8a93-340e3e55240e.png)
![image](https://user-images.githubusercontent.com/68164076/175753686-83e6e212-9c2d-4c1e-85a8-402e5b60fc6d.png)
![image](https://user-images.githubusercontent.com/68164076/175753693-04babe98-5f38-4477-a04c-30fc0083c4be.png)
![image](https://user-images.githubusercontent.com/68164076/175753719-fc2bc1e9-0449-4305-84a0-aca5ffec01c2.png)
![image](https://user-images.githubusercontent.com/68164076/175753737-cee78af0-825f-48c6-9cd0-88b201c3b08b.png)
![image](https://user-images.githubusercontent.com/68164076/175753750-9008dac2-be34-414d-811f-c452fca9633e.png)
![image](https://user-images.githubusercontent.com/68164076/175753768-b6de6818-bbc3-4032-a1b4-e20593a98300.png)

**Comment by Gultask** [comment]
There IS the problem of being unable to pick up the quest again if you abandon it, since it is assigned to the wrong quest giver.

https://github.com/azerothcore/azerothcore-wotlk/issues/11700

**Comment by anjxed** [comment]
@Gultask is there a workaround? like going through uldum again?

**Comment by Gultask** [comment]
@anjxed unfortunately that won't fix it. I don't think the quest is shareable, either. I was looking for a way to fix the quest myself but I'm still taking baby steps in SQL :P 
You'll be able to see if a fix comes out by checking the Discord where they publish the changelog. Your email works as well since you're a participant in this conversation, so you'll be notified when this closes. That's the best I can offer for now, sorry.
