### ISSUE TITLE
[Midsummer] "Torch Catching" quest doesn't appear after "Torch Tossing" quest

### ISSUE THREAD

**Issue by JustVityok** [chromiecraft/chromiecraft#3649]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I've completed "Torch tossing" quest (https://wowgaming.altervista.org/aowow?quest=11922) in the Undercity, taking it from Master Flame Eater (https://wowgaming.altervista.org/aowow?npc=26113). After completion (hitting 8 braziers with a torch) he says "Well done! You'll be a fire juggler faster than the fuse on a ground flower! Now gird yourself! The next test is when things really heat up..." and gives me 5 Burning Blossoms and... that's all.

### Expected Blizzlike Behaviour

After "Torch Tossing", logically the "Torch Catching" (https://wowgaming.altervista.org/aowow?quest=11923) and "More Torch Tossing" (https://wowgaming.altervista.org/aowow/?quest=11926) should be given by this NPC.

### Source

![Screenshot_2](https://user-images.githubusercontent.com/93767462/174783493-70faa29f-1093-4ff5-92ce-0679fa45092a.png)
That's all he talks to me. According to WOTLK DBs and my previous experience with 3.3.5a servers, it shouldn't be like that at all (at least until I complete "More Torch..." repeatable dailies).

### Steps to reproduce the problem

1. Interact with "Master Flame Eater" in Undercity with character that never completed this quest.
2. Complete the "Torch Tossing" quest
3. Check if "Torch Catching" appears, if not, you've had successfully reproduced this problem.

### Extra Notes

"Torch tossing" quest (https://wowgaming.altervista.org/aowow?quest=11922)
Master Flame Eater NPC (https://wowgaming.altervista.org/aowow?npc=26113)
"Torch Catching" (https://wowgaming.altervista.org/aowow?quest=11923)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Windows 7 SP1

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi JustVityok. Thanks for the report. Sorry you're having trouble. Unfortunately I'm unable to duplicate this on my local server. Not much can be done if it can't be duplicated. Have you tried clearing your cashe? (Make sure to log out of the game first.)
![image](https://user-images.githubusercontent.com/68164076/174920285-bcc7732f-5e20-4528-b438-380e0f32e385.png)
![image](https://user-images.githubusercontent.com/68164076/174920332-f51db980-3def-4999-9225-820768942519.png)

**Comment by Sathrenor** [comment]
Can confirm similar case with Alliance counterparts [Master Fire Eater](https://wowgaming.altervista.org/aowow/?npc=25975) and [More Torch Tossing](https://wowgaming.altervista.org/aowow/?quest=11921) at least in Teldrassil. 
The issue might be missing [Torch Catching](https://wowgaming.altervista.org/aowow/?quest=11657) quests from the NPC which is stated as required to start the follow ups

___
![WoWScrnShot_062222_032617](https://user-images.githubusercontent.com/79346412/174924633-5d0f3040-5c71-4b43-82ef-1a9ff16e3dc8.jpg)
![WoWScrnShot_062222_030412](https://user-images.githubusercontent.com/79346412/174924650-b65054e5-f7f9-48af-8c85-f76df7d1ead1.jpg)

**Comment by Stump876** [comment]
So this appears to be a CC specific issue. I checked on CC and it doesn't work for me there.
