### ISSUE TITLE
RDF cancel bug

### ISSUE THREAD

**Issue by H4Xx0R-PC** [chromiecraft/chromiecraft#365]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

After someone leaves a RDF group, the game allows you to search for a replacement. This puts you in a new queue. However when you then cancel that queue, the game will think you're not in a RDF group anymore. So the eye from the minimap would be missing and if you would walk out of the instance you would be at the actual dungeon's entrance instead of the location where you entered the dungeon from through the popup.

This means when you kill the final boss you won't get a satchel or the completionist xp. Also you would have to hearthstone because you end up in the middle of nowhere. Another odd thing is that the RDF buff persists throughout the dungeon.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to cancel the replacement queue and requeue for a replacement again.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Queue for RDF and get in a dungeon.
2. Have someone leave the group.
3. Queue for a replacement.
4. Cancel the queue.
5. No completion XP or satchel, have to hearthstone because the teleport function isn't working and when you leave the dungeon your location will be that dungeon's entrance.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by H4Xx0R-PC** [comment]
Having someone leave the group while you're in queue for a replacement also triggers the bug

**Comment by mdawx** [comment]
I tried to reproduce it, but it looks different in my local environment. I recorded only first test 
1. Queue for RDF and get in a dungeon.
2. Have someone leave the group.
3. Queue for a replacement.
4. Cancel the queue.
5. Could not requeue, system message was "One or more dungeon was not valid".

Check this: https://youtu.be/vGboU-2Xua0

I made second test, but didn't record it:
1. Queue for RDF and get in a dungeon.
2. Have someone leave the group.
3. Queue for a replacement.
4. Cancel the queue.
5. I finished dungeon and no one got reward.

**Comment by Stifler82** [comment]
I could not understand well.
Can anyone explain well?

**Comment by vmensik** [comment]
The random dungeon finder group should be able to requeue to find replacements. The problem is that once this repeated queue is cancelled or someone leaves while the group is in queue for a replacement, the group stops being treated as a dungeon finder group, rather a normal one. 

Therefore the players are losing the saved state of their previous location where they should be teleported after leaving/finishing or teleporting out of the dungeon. This also means that if you leave the group, you get teleported to the nearest graveyard instead of to your previous location.

**Comment by jamadaha** [comment]
The exact same thing occurred for me today in the Scarlet Monastery - Library.
Was in the dungeon, someone left. We then searched for a replacement, someone left while searching. We could no longer teleport out; the teleport button was missing.
