### ISSUE TITLE
[Midsummer] Commoner NPC's are missing in Alliance capitals

### ISSUE THREAD

**Issue by anhility** [chromiecraft/chromiecraft#3650]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

- There are supposed to be Midsummer Commoner NPC's that start a breadcrumb quest ([The Master of Summer Lore](https://wowgaming.altervista.org/aowow/?quest=11970)) in all Alliance capitals.
- They are currently missing.
- Might be the same issue on Horde side, but I've no Horde character so haven't checked.

### Expected Blizzlike Behaviour

They should be present during the Midsummer world event.

### Source

https://wowgaming.altervista.org/aowow/?quest=11970

### Steps to reproduce the problem

1. Go to an Alliance capital, they are supposed to stand close to the banks.
    - Stormwind: Trade District
    - Ironforge: The Commons (dwarf) & The Great Forge (gnome)
    - Darnassus: The Temple Gardens
    - Exodar: Seat of the Naaru
2. No NPC's at their supposed spawn locations.

### Extra Notes

- [Human Commoner](https://wowgaming.altervista.org/aowow/?npc=18927)
- [Dwarf Commoner](https://wowgaming.altervista.org/aowow/?npc=19148)
- [Gnome Commoner](https://wowgaming.altervista.org/aowow/?npc=19172)
- [Night Elf Commoner](https://wowgaming.altervista.org/aowow/?npc=19173)
- [Draenei Commoner](https://wowgaming.altervista.org/aowow/?npc=19171)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi anhilly. Thanks for the report. I can confirm. Not only are they missing in Alliance capitals, but they are missing in every city.
