### ISSUE TITLE
[Minor] Thunderbluff's Elevators

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3655]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Thunder Bluff's both elevators (on Northeastern and Southwestern sides) are ascending simultaneously 

https://youtu.be/SEj5RqWav6k

### Expected Blizzlike Behaviour

When one elevator's cabin ascends, its twin part should descent 

### Source

https://www.youtube.com/watch?v=Veo_es0Qa0Q
Video from 2008

### Steps to reproduce the problem

1. Go to Thunder Bluff
2. Enjoy watching the peaceful landscape while jolly riding the elevator

### Extra Notes

_NE_:
**20640** (Entry: **47297**) 
**20639** (Entry: **47296**)
___
_SW:_
**18435** (Entry: **4171**)
**18298** (Entry: **4170**)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Sath, thanks for the report!

When looked at with a fresh local server, they start off just like you described. So the issue might be server-side, maybe like how grids become inactive if a player is far away.

![WoWScrnShot_062622_005946](https://user-images.githubusercontent.com/100873791/175798834-eb6ea1c5-fc33-4d61-bacd-3f58b27f85e7.jpg)

**Comment by Stump876** [comment]
It looks like one moves slightly faster than the other. Eventually the will synchonize, and as time goes on, the faster one will get ahead, eventually syncronizing again. This is blizzlike https://www.bluetracker.gg/wow/topic/eu-en/13817044543-thunder-bluff-off-sync-elevators/
