### ISSUE TITLE
[Midsummer] Bonfires have dialogue option (Also sorry for breaking the 666 issues number :>)

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3657]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Certain bonfires have a "Stamp out the Horde bonfire" which I assume is just a script check that should be hidden from player..
The ones I remember are in Badlands and Stonetalon Mountains, but listing them all would be far too much effort for a regular player, sorry :d

Edit: Also Hinterlands
___
![WoWScrnShot_062222_082750](https://user-images.githubusercontent.com/79346412/174961768-39f37391-936d-4074-90f6-b2be29124bd2.jpg)

### Expected Blizzlike Behaviour

This dialogue should not be visible, given how other bonfires don't have it

### Steps to reproduce the problem

1. Go to Stonetalon / Badlands Bonfire as Alliance
2. Interact with it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello Sathrenor. Thanks for the report. However, I can't duplicate the problem on either my local of the CC PTR.
![image](https://user-images.githubusercontent.com/68164076/175755406-edc2e281-62e0-4b3a-982c-3f71ef7d5b11.png)
![image](https://user-images.githubusercontent.com/68164076/175755368-eabb8e31-0566-45e6-9c27-4e1d7dda04ec.png)
![image](https://user-images.githubusercontent.com/68164076/175755388-5e3b16cb-32d0-4b28-ab4d-43a01313ffd6.png)

**Comment by Sathrenor** [comment]
For me this bug is still present (I use CC client enUS and cleared catche recently), so I'm afraid an investigation on a live server may be required
___
![WoWScrnShot_062522_050551](https://user-images.githubusercontent.com/79346412/175755894-08c1c9c7-c2c2-4491-8ab1-3567785a1d23.jpg)

**Comment by Stump876** [comment]
Also tested on CC. It's still open. Let's wait and see if someone else can duplicate it. Right now I got nothing.
![image](https://user-images.githubusercontent.com/68164076/175758427-2e3be182-2f3d-403b-91c9-29ffea9bd038.png)

I believe the bubble is intended after you've completed the "Desecrate this fire" quest. you should be able to stomp out fires as may times as you want. But you only get the reward for the inital quest. 
https://tbc.wowhead.com/quest=11580/desecrate-this-fire#comments:id=316501:reply=38013

**Comment by Sathrenor** [comment]
Either way, there is no consistency for me, since some of them have a bubble (regardless of the quest), and some not.
But thank You for testing, it's kinda odd...

**Comment by temperrr** [comment]
I also cannot replicate this.

**Comment by The-GhostRider** [comment]
I too tried to reproduce the Bug, I also tried with a Night Elf Druid like your, in case the bug was Class or Race related, but I can't reproduce the same issue.

![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/e4dd5de0-0e96-4318-aa6d-17a652d6b195)


For this reason I close the report.
