### ISSUE TITLE
Hillsbrad Foothills NPC not displayed correctly

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#367]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

NPC George Candarte ( https://wowgaming.altervista.org/aowow/?npc=2698 ) in Hillsbrad Foothills (coord: 91.9 ; 38.2) is invisible ; only his dagger and vial are visible.
NPC is still clickable, but not sure if you can interract with him as I am Alliance.
![WoWScrnShot_040721_175101](https://user-images.githubusercontent.com/81818678/113896221-0780c680-97ca-11eb-99ae-4bf459f9f9cf.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should be fully visible : https://classic.wowhead.com/npc=2698/george-candarte

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Hillsbrad Foothills near the northenmost part of Thoradin's Wall, coords 91.9 ; 38.2
2. See the NPC

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by orfaze** [comment]
Can confirm with USclient from chromiecraft
![Capture d’écran (17)](https://user-images.githubusercontent.com/81832274/113897797-89bdba80-97cb-11eb-9364-e1f906bac983.png)

**Comment by Helias** [comment]
I cannot confirm it :(
if you encounter this, try to log in and log out again to see if the problem is permanent or restart the client deleting the Cache, may it's an issue of connection
![image](https://user-images.githubusercontent.com/519778/114057213-a8d34f80-9892-11eb-8682-c7a11e312c01.png)

**Comment by Synful-Syn** [comment]
Also have the same issue.
Deleted my cache and he also only have a floatting dagger and bottle.
Playing on an enUS client, no HD patch.
Realmlist is `set realmlist logon.chromiecraft.com`

**Comment by pop-pig** [comment]
I still have the issue, after deleting cache.
No HD patch, enUS client
![WoWScrnShot_060621_160537](https://user-images.githubusercontent.com/81818678/120927619-c467a480-c6e1-11eb-9438-568abed6b3f6.jpg)

**Comment by pop-pig** [comment]
Using the client from ChromieCraft website, no addons:
![WoWScrnShot_060621_172058](https://user-images.githubusercontent.com/81818678/120930055-f2ea7d00-c6eb-11eb-9f2d-8e54957d7630.jpg)

**Comment by Stump876** [comment]
I can also confirm this on my local server, and on CC on both horde and alliance. I can also say this was not like this before. I've visited this guy several times while questing to vendor. I'm not quite sure what or when it happened. I tried changing settings, logging and clearing cache. Problem persists.
![image](https://user-images.githubusercontent.com/68164076/120934776-928c1900-c6b4-11eb-89ff-7d6ff521af75.png)
![image](https://user-images.githubusercontent.com/68164076/120934891-0e866100-c6b5-11eb-8ab9-94fec835fb36.png)

I also tried on another server I know runs AC and he's visible. 
![image](https://user-images.githubusercontent.com/68164076/120935759-22cc5d00-c6b9-11eb-8bdc-13b88da35aa0.png)

**Comment by eTzmNcbkrng** [comment]
`.go cr 11200`
Deleted `Cache`, using enUS client, NPC does not show correctly for me on ChromieCraft
![image](https://user-images.githubusercontent.com/26512802/120945032-96d73580-c78b-11eb-8cff-a712bb647395.png)
Also not displaying correctly on the ChromieCraft GM PTR after deleting `Cache` again.
![image](https://user-images.githubusercontent.com/26512802/120945076-d140d280-c78b-11eb-9fce-442b92046e0c.png)

**Comment by Stump876** [comment]
Going back to the server that was just now updated he is invisible. Something in the most recent update caused him to vanish.
![image](https://user-images.githubusercontent.com/68164076/120935759-22cc5d00-c6b9-11eb-8bdc-13b88da35aa0.png)
![image](https://user-images.githubusercontent.com/68164076/120961981-b3d02200-c713-11eb-983f-a97a26ab30b4.png)

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/121019169-77e29e80-c79f-11eb-9a42-b95e179a0b0e.png)
Something must have broken him recently, like the other comments already stated. Pre 3.0 AC revisions do not have this issue.
