### ISSUE TITLE
Midsummer braziers stacking on top of eachother in capital cities

### ISSUE THREAD

**Issue by Spook9** [chromiecraft/chromiecraft#3677]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

![image](https://user-images.githubusercontent.com/58770211/175660372-9db122af-870d-44f9-9136-c9d34dca62e7.png)
Bonfire in Stormwind seems to have multiple bonfires spawned on the same spot. Maybe some interaction like blossom or a quest is spawning a new one again and again.

### Expected Blizzlike Behaviour

Only one bonfire should be up.

### Steps to reproduce the problem

1. Check capital city bonfire when server is not freshly restarted
2. ????
3. Profit

### Extra Notes

Sometimes cannot see bonfires (the part with the wood) in the world. Might be because of my HD texture pack not sure, probably unrelated. The invisible wood doesnt affect gameplay, can still douse and complete quests etc.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04
Win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
I can confirm this issue on CC, but it appears to be specific to CC. I can't reproduce it on my local. You can see by screenshots in this issue as well. https://github.com/chromiecraft/chromiecraft/issues/3649  on my local server the fires are single and blue.
![unknown](https://user-images.githubusercontent.com/68164076/175665638-f6ffaee5-f258-420a-b0c3-83f39c924c51.png)

**Comment by Stump876** [comment]
Looks like stealing the flame spawns a new fire.

**Comment by sudlud** [comment]
AC linked issue azerothcore/azerothcore-wotlk#12303 closed with c0bbb52
