### ISSUE TITLE
Almost no weapon skill points for mobs > lvl 50 

### ISSUE THREAD

**Issue by Artanidos** [chromiecraft/chromiecraft#3687]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

I have skilled to shoot a gun from skill 1 to 300.
When I killed a mob level 50 or below I almost get a skill point for every shoot.
When I killed mobs above level 50 I seldom get skill points at all.

### Expected Blizzlike Behaviour

I think you should get a skill point for every hit regardless of the mobs level.

### Steps to reproduce the problem

1. Go to Un`Goro to the cove with the apes.
2. Equip a gun while skill is below 300.
3. Shoot mobs level 50 and 51.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello Artanidos Thanks for the report.  There's not much info on weapon how skill-ups work. [Expected Blizzlike behavior](https://classic.wowhead.com/guides/classic-wow-weapon-skills#leveling-weapon-skill) or [Another here](https://wowwiki-archive.fandom.com/wiki/Weapon_skill) `Each attack that is not evaded has a chance to increase weapon skill (evading enemies will not increase weapon skill, unfortunately). With lower weapon skill, the skill gain rate is at or near 100%, however the skill gain change begins to sharply decrease once the weapon skill cap is approached. At 10% away from the cap, the skill gain is roughly 50%, and gaining the final skill points can take some time (at which point your attacks should not be missing nearly as often).`

A skill point after every hit when you are close to max level is not blizzlike. The last points to the cap should take a long time to get. It looks like what you're noticing is a sweet spot in the code. See Necropola's comment https://github.com/chromiecraft/chromiecraft/issues/507 I can't find if it's blizzlike or not. It just says a _chance_. Similar to the chance of a skill up on a green crafting pattern. But without a source showing this is incorrect, there's not much that can be done. If someone finds more info on this I'm very intrested in it, this is something that has been bothering me for a while.

**Comment by temperrr** [comment]
Like Stump says, the closer you are to cap, the slower it goes.
