### ISSUE TITLE
Freedom for all Creatures

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#3693]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The freed Sprite Darters one by one fly to -4505.759766 798.408997 61.731499
Kindal Moonweaver stays with you after you have gotten the quest credit and stays until the timer has run out, commenting that you failed the quest

### Expected Blizzlike Behaviour

The Sprite Darters spread out in all directions

When the quest credit is given, Kindal Moonweaver stands still for a moment and says "We've done it! Meet me back by Jer'kai above the Grim Trappers camp.
She then despawns and respawns at her quest giver location

### Source

https://youtu.be/GV64q-i420o?t=28

### Steps to reproduce the problem

Do the quest

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=2969
https://wowgaming.altervista.org/aowow/?npc=7956
https://wowgaming.altervista.org/aowow/?npc=7997

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Tereneckla. Thanks for the report. However I can't confirm the behavior. I did the quest and had no issues with it. 
![image](https://user-images.githubusercontent.com/68164076/176813242-44e412c8-d9b9-4a41-846e-146bc1e6588e.png)
![image](https://user-images.githubusercontent.com/68164076/176813284-1b7bdcb2-7b0e-42de-a5f4-440ffdb39da7.png)
![image](https://user-images.githubusercontent.com/68164076/176813372-2c50a1e6-196f-4f94-93ba-13c418c4cbfc.png)

 I can confirm that the darters do not go into different directions, but this is a known issue https://github.com/chromiecraft/chromiecraft/issues/3118
