### ISSUE TITLE
[Sunken Temple] Double Spawn of Hakkar and missing patroling ooze

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3697]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Occasionally, Sunken Temple may spawn double rare mob [Spawn of Hakkar](https://wowgaming.altervista.org/aowow/?npc=5708#abilities). 
_(The other mob did not drop anything, but I would presume it was just drop, not anything bugged. Though, a look into loot tables would be appreciated_

Also I read a [Wowhead comment from 2006](https://classic.wowhead.com/npc=5708/spawn-of-hakkar#comments) mentioning an ooze that should be patrolling the exact route as Spawn of Hakkar (but not next to him), which I have never encountered so far.
_"There's an ooze patrolling spawn of hakkari's route and therefore you must choose exactly right time to strike."_

I could presume the other spawn has been placed instead of the ooze, but that's just a theory. Moreover, a research would be required to find out what ooze it was.
___
![WoWScrnShot_062722_110759](https://user-images.githubusercontent.com/79346412/175913578-4dbfe47c-c85b-4c2c-a9c5-d30401fd09be.jpg)
![WoWScrnShot_062722_111256](https://user-images.githubusercontent.com/79346412/175913613-79203c0a-3e45-4c7e-8778-1f036023f97a.jpg)
![WoWScrnShot_062722_111105](https://user-images.githubusercontent.com/79346412/175913629-29110ee8-34b9-4f93-b1c6-6aa487db0462.jpg)
![WoWScrnShot_062722_111036](https://user-images.githubusercontent.com/79346412/175913650-ba500c73-64ca-44bc-a163-b061bc508444.jpg)

### Expected Blizzlike Behaviour

There should be only one Hakkar spawning and there also should be an ooze patrolling the lower circle (on the floor with statues)

### Source

There isn't a single mention on both wiki and wowhead about a double spawn, so I presume that should not be a case
https://wowpedia.fandom.com/wiki/Spawn_of_Hakkar
https://classic.wowhead.com/npc=5708/spawn-of-hakkar#comments

### Steps to reproduce the problem

1. Go to the Temple of Atal'Hakkar
2. Head to the lower circle with statues
3. Reset the dung shall the issue not appear

### Extra Notes

DB Guid: **33621** Entry: **5708** (the one with loot)
DB Guid: **34520** Entry: **5708** (the one without)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Sorry for the (very) late response! I can confirm. It's due to a lack of pooling.
