### ISSUE TITLE
Rocklance is hiding below the world.

### ISSUE THREAD

**Issue by Cosmic-Cocoa** [chromiecraft/chromiecraft#37]
##### SMALL DESCRIPTION:
Level 17 silver elite centaur, Rocklance, is hiding under the ground and clips through when you get too close.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Rocklance should be visible above ground before engaging.

##### CURRENT BEHAVIOUR:
From a distance the oasis looks clear, but when I approach suddenly Rocklance comes up out of the ground and aggros me.

From a distance: 
![No mob in sight](https://user-images.githubusercontent.com/78349628/106941692-c7796680-66e8-11eb-91fa-fb13637334d1.png)

As I enter the oasis:
![Rocklance appears through the earth](https://user-images.githubusercontent.com/78349628/106941715-d06a3800-66e8-11eb-8689-ffff2d377920.png)

##### STEPS TO REPRODUCE THE PROBLEM:
1. I suppose you could either teleport to Rocklance himself, or to the Stagnant Oasis and then run southeast.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Could you verify it without the HD patch?

**Comment by Hacaw** [comment]
I reproduced this, he clipped through the map and when I used the command it got me under the map.

Could it be related to https://github.com/chromiecraft/chromiecraft/issues/39 ?

##### STEPS TO REPRODUCE THE PROBLEM:
1. go c id 5841

##### AC HASH/COMMIT: 
[adcf3f7a](https://github.com/azerothcore/azerothcore-wotlk/commit/adcf3f7a)

##### DATABASE VERSION: 
WORLD: 2021_02_01_00
AUTH: 2021_01_25_00
CHARACTERS: 2021_01_25_00

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
Chromie-Client (Downloaded from 10-01-2021)
DBC & Maps - v9 - 1-12-2020

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Stifler82** [comment]
> I reproduced this, he clipped through the map and when I used the command it got me under the map.
> 
> Could it be related to #39 ?
> 

@Hacaw
Yes, but i think it is like that issue, wrong coordinate spawn point.
