### ISSUE TITLE
[Minor][Feralas] "Feathermoon Ferry" ship stutter for a second in a specific point

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3707]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

[Feathermoon Ferry](https://wowgaming.altervista.org/aowow/?object=177233) gets stuck for 1 sec and resets at the same, specific point.

https://youtu.be/zOA1uBQjNw0?t=210

### Expected Blizzlike Behaviour

The voyage should be smooth, without any stuttering

### Source

_Sorry, I couldn't find anyone who would bother record the ship voyage, especially pre 2010 :c_

### Steps to reproduce the problem

1. Go to the Feathermoon Stronghold in Feralas
2. Take a ship to the shore
3. Observe carefully

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ZhengPeiRu21** [comment]
Transport moving coordinates are loaded from DBC files, which are from the client so we are sure they are correct. Unless someone is can help find a good source to show that this did not also happen on official server, it is probably a Blizz-like behavior.

**Comment by temperrr** [comment]
@ZhengPeiRu21 

it is blizzlike to have a stutter there

It is not blizzlike to it slowing down completely (tested on WOTLK Retail PTR) 
Do you think this is something we can potentially fix?

**Comment by ZhengPeiRu21** [comment]
> @ZhengPeiRu21
> 
> it is blizzlike to have a stutter there
> 
> It is not blizzlike to it slowing down completely (tested on WOTLK Retail PTR) Do you think this is something we can potentially fix?

It is probably a core issue of how pathing is handle, which can be very difficult to properly identify and fix. There was one recent change that impact taxi movement handling; I do not know if that would impact this but they are related: https://github.com/azerothcore/azerothcore-wotlk/commit/572a680c16c75e136fdfc593affa7cc3beaa0e2a

Is this issue still occur after that commit?

**Comment by Sathrenor** [comment]
@ZhengPeiRu21 
> 
> Is this issue still occur after that commit?

I just checked and yes, it stops, resets like a few yards back, and starts a new route.

**Comment by ZhengPeiRu21** [comment]
> @ZhengPeiRu21
> 
> > Is this issue still occur after that commit?
> 
> I just checked and yes, it stops, resets like a few yards back, and starts a new route.

Thank you for check. This must be a core issue with processing transport routes somehow then.

**Comment by The-GhostRider** [comment]
This is not a bug, or at least not a bug intended as NOT Blizzlike behavior, this is a bug that also exists in the ratail.

For this reason I close the report.
