### ISSUE TITLE
Tiny Crimson Whelpling has too high chance to drop

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#371]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Tiny Crimson Whelpling (https://wowgaming.altervista.org/aowow/?item=8499) that drops from Whelps in Wetlands (https://wowgaming.altervista.org/aowow/?npc=1069, https://wowgaming.altervista.org/aowow/?npc=1044, https://wowgaming.altervista.org/aowow/?npc=1042) has too high chance to drop. I got 4 drops(even 2 in a row) in 15 minutes  from 25-30 mobs killed
![inarow](https://user-images.githubusercontent.com/80769357/113914776-33a64280-97de-11eb-831d-f5c0b24a7098.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The drop rate chance should be much much lower : https://www.wowhead.com/item=8499/tiny-crimson-whelpling#comments
Even in wotlk databases ( like https://wowgaming.altervista.org/aowow/?item=8499) chance is listed as 1%, 0.5% and 0.25% for the 3 whelps.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Wetlands and start killing https://wowgaming.altervista.org/aowow/?npc=1069, https://wowgaming.altervista.org/aowow/?npc=1044, https://wowgaming.altervista.org/aowow/?npc=1042
2. See how many Tiny Crimson Whelpling drops you get

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
![image](https://user-images.githubusercontent.com/1884642/114261991-5a7a9980-99d5-11eb-9638-786f47233e45.png)
![image](https://user-images.githubusercontent.com/1884642/114262023-8433c080-99d5-11eb-85a3-0726beea4b74.png)
![image](https://user-images.githubusercontent.com/1884642/114262044-a7f70680-99d5-11eb-9fa3-3ac839784fd7.png)
