### ISSUE TITLE
[Quest Description] A Meal Served Cold has different description than it is intended

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#3715]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

You can see that there is different description of where I should turn my quest, the quest log is correct one.

![image](https://user-images.githubusercontent.com/80590226/176990526-04c90e70-28ef-46ba-b728-bfd9fbf8094d.png)

### Expected Blizzlike Behaviour

Place for quests bellow minimap should show same description as quest log.

### Steps to reproduce the problem

1. Take quest
2. Complete it
3. Check difference

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
Thank you, but that description in the quest log usually never change and I cannot find any information that this one should.

**Comment by Stump876** [comment]
Elexias, do you have a source for how it should work?

**Comment by Elexias** [comment]
Basically it should just have correct text. On the right tab it says to turn it to Elwynn Forest, but it should actually be turned to Stormwind.
https://wowgaming.altervista.org/aowow/?quest=212
@Stump876

**Comment by Tereneckla** [comment]
He asks for a proof, which in this case would be a screenshot from a retail server

**Comment by Elexias** [comment]
There is no need for a proof. I've been playing on retail server for 14+ years, and quest description is always correct. This one is not.

**Comment by Stump876** [comment]
It's clearly not correct, that much is obvious. But we do need a blizzlike example of how it should work. Unfortunatly, memory is not an acceptable source. We need some form of objective evidence to make a correction. It could be a screenshot, or wowhead comment or youtube video. Preferably from the 3.3.5 era or earlier. Blizard's Classic and TBC servers are also accepted, provided it wasn't patched in Wrath. Just not from other private servers. Which in this case say the same thing as pictured above. 

I suggest looking around to see what you can find. I'll do the same, but so far the only video I've found is from wow maina.

**Comment by heyitsbench** [comment]
Sniffed from WotLK Classic PTR:
```LogTitle: A Meal Served Cold
LogDescription: Kill a Cold Eye Basilisk, get a Chilled Basilisk Haunch, and return it to Angus Stern in the Blue Recluse.
QuestDescription: One of my most famous dishes is Chilled Basilisk in Lime Vinaigrette.  But the problem is... the meat is impossible to keep fresh, and I must serve the dish tonight for a noble's birthday!$B$BSo if you can bring me a Chilled Basilisk Haunch from a freshly-killed Cold Eye Basilisk, quickly, then I will owe you a king's feast!$B$BCold Eye Basilisks are known to roam along the beach dunes of northwestern Stranglethorn, so you have much traveling to do.  And be swift!
AreaDescription: 
PortraitGiverText: 
PortraitGiverName: 
PortraitTurnInText: 
PortraitTurnInName: 
QuestCompletionLog: Return to Angus Stern at Mirror Lake in Elwynn Forest.

**Comment by heyitsbench** [comment]
From what I can see, this is blizzlike and should be closed.
