### ISSUE TITLE
Magic Dust not working

### ISSUE THREAD

**Issue by nesh1905** [chromiecraft/chromiecraft#3717]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

when Magic Dust is used on a player it usually doesn't apply the sleep effect
it applies the debuff, visual effect of sleep, but no sleep effect - no cc
in rare occasions it works

### Expected Blizzlike Behaviour

target hit should be sleeping for the duration of the sleep debuff

### Steps to reproduce the problem

additem 2091
use on player
see visual sleep effect but target is free to act

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, nesh, thanks for the report!

I can't reproduce the visual effect, it just doesn't do anything for me.

As for it not working on players or even mobs that's intended. It's unreliable past level 30:

All comments from: https://web.archive.org/web/20110904104113/http://www.wowhead.com:80/item=2091

>Very disappointed. This stuff is officially worthless now, at level 80 i tried to use this on a 78 non-elite in crystalsong forest and it fizzeled something like 100 times in a row, I decided it just wasnt going to work and proceeding to one shot the stupid satyr. I got it to work against a lvl 6 defias cutpurse though... oh and also a rat by the auction house... and after only 5 fizzles! (3.3.5)

>As a 39, I was able to get the dust to work once out of every 8 or 9 times on a level 7 mob in Dun Morogh. Each time the dust fizzled, it did not get consumed. When the dust finally worked, it did get consumed. (3.3.5)

>This dust has been nerfed further and now has a 100% chance to Fizzle (not work) as a level 80 character using this against another level 80 player. (3.2.0) (I think that's hyperbole)

>I just tried using this on a lvl 18 elite in Wailing Caverns, and it kept fizzling forever, making it officially useless. (3.2.0)

>Opened a petition and asked a GM about it. He said it is now 'Working as intended'. (3.2.0)

>Upon opening my own GM petition, i received a form letter indicating the item is known to bugged at this point in time, and should NOT be fizzling against mobs. (3.3.2)

There are some kinks still to fix in Magic Dust but I think it's best to wait for WotLK Classic to make sure which error effects should play, and how it should be handled.
