### ISSUE TITLE
[Shadowfang Keep] Deathstalker Vincent keeps players in combat.

### ISSUE THREAD

**Issue by FTGCocolandia** [chromiecraft/chromiecraft#3720]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

In Shadowfang Keep the NPC kept all the party in combat.

![SFKBugReport](https://user-images.githubusercontent.com/91145640/177017964-5b67cb0e-d689-484c-a2d5-e7e3ce910a38.jpg)

I believe this happened after I completed the quest [Deathstalkers in Shadowfang](https://www.wowhead.com/wotlk/quest=1098/deathstalkers-in-shadowfang).

### Expected Blizzlike Behaviour

It shouldn't get anyone in combat.

### Steps to reproduce the problem

1. Complete the quest [Deathstalkers in Shadowfang](https://www.wowhead.com/wotlk/quest=1098/deathstalkers-in-shadowfang).

### Extra Notes

Maybe a crossfaction problem. 

I should add, I went back to the NPC and he was an ally (I was horde) and wasn't focusing anyone but the debug tool marked him as the one attacking.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi FTGCocolandia. Thanks for the report. Sounds like this might have something to do with the cross faction. He should be friendly to horde and yellow to Alliance, and unable to be killed. Unfortunately I was unable to confirm the behavior above. As horde I could turn in the quest with no problem. As alliance I was able to attack him. 

However, I was able to kill him which is not correct. I thought was fixed https://github.com/azerothcore/azerothcore-wotlk/pull/9404 it must have reverted at some point.
![image](https://user-images.githubusercontent.com/68164076/187049609-6da07553-50de-49df-8e72-85659030aadb.png)
