### ISSUE TITLE
Rare Spawn "Ghok Bashguud" (LBRS) Not Spawning After 100+ Resets

### ISSUE THREAD

**Issue by BeckerSource** [chromiecraft/chromiecraft#3722]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I'm trying to farm Ghok Bashguud (LBRS) (#9718) and have yet to get an instance with him after 100+ resets.

I did see him on my paladin 2-3 months ago.  "/tar ghok" is possible from by zone entrance with Ornate Spyglass (longsight).

To help with testing, I am doing resets on my alt accounts as well.  I have been testing on PTR and experiencing the same results.

I am entering the dungeon normally (without RDF).  I have asked around in guild, world chat, and on CC discord about Ghok sightings and haven't gotten a confirmed sighting as of my time trying to farm.

### Expected Blizzlike Behaviour

I don't know the expected spawn rate average in comparison to instance resets but I would assume it should be like the other rares in the zone (Jed, Bannok, etc), which I see perhaps once in five instances.  Not seeing Ghok after 100+ resets seems incorrect?

### Steps to reproduce the problem

1. Enter LBRS
2. Go into first right corner before first main room with Scarshield mobs.  Similar procedure for fishing Jed but other side/direction.
3. Use Ornate Spyglass and do "/tar ghok" in direction of Ghok spawn location (see attached screenshot).  To create Ornate Spyglass: ".additem 5507"
![map](https://user-images.githubusercontent.com/3980470/177030955-5897a960-95b0-4c35-86f6-22f5fb0db023.jpg)

### Extra Notes

https://wotlkdb.com/?npc=9718

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft (Live & PTR)

**Comment by BeefSteaker** [comment]
Hi, thanks for the report.
spawn rate appears to be accurate, i found 2 spawns in 10 resets, so considering the 10% ish spawn chance i found from sources thats not bad

old issue so it may have been fixed by something else in the meantime

**Comment by BeefSteaker** [comment]
![image](https://user-images.githubusercontent.com/11332559/221409863-d7b4d0c0-1105-4bdc-8abb-c765cdea9967.png)
ghok is up until next reset presumably if you stil need him
