### ISSUE TITLE
[Midsummer Festival] Torches hitting the ground without anyone tossing 

### ISSUE THREAD

**Issue by djobf** [chromiecraft/chromiecraft#3726]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The blast effect from failing to catch the torches kept happening randomly after I completed the quest even when no one was around the bonfire. It can reach places it shouldn't (tinker town), it even stun locked me to death once lol

### Expected Blizzlike Behaviour

Pretty sure it doesn't happen at all

### Source

[More Torch Catching](https://youtu.be/SxhAD4T7Uys)

### Steps to reproduce the problem

1. Pick up the quest "More torch catching]
2. Complete it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
I haven't been able to reproduce this. Truth be told I'm terrible at the torch catching. I can't even complete it. So maybe someone better skilled at this than I can confirm it.

**Comment by The-GhostRider** [comment]
>Truth be told I'm terrible at the torch catching. I can't even complete it. So maybe someone better skilled at this than I can confirm it.

`.cheat cooldown`

**Comment by The-GhostRider** [comment]
I couldn't reproduce the bug even by abusing the spell of the item through the GM `.cheat cooldown` command, I don't think this is a current bug anymore, it's likely that it has been fixed through other Fixes..

For this reason, I close the report.

[![Anteprima video](https://github.com/chromiecraft/chromiecraft/assets/1884642/c94f2b2e-16e5-4b96-aae7-5334f02bee1d)](https://www.youtube.com/embed/jEe14dw4Y_I)
