### ISSUE TITLE
Priest Skill "Inner Fire" Rank 3 is not working correctly

### ISSUE THREAD

**Issue by Vladimirjov** [chromiecraft/chromiecraft#373]
![WoWScrnShot_040821_004630](https://user-images.githubusercontent.com/81888445/113944232-82ff6980-9804-11eb-94cc-0d02e4c2e2a5.jpg)
![WoWScrnShot_040821_004634](https://user-images.githubusercontent.com/81888445/113944237-84c92d00-9804-11eb-8eaf-105955026e5f.jpg)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:
Hello Chromiecraft Team

Look at the pictures. In the "Spellbook" the skill description says that Inner Fire (Rank 3) is giving 717 armor. But when i activate it, i only get 495. Please fix! 717 should be the correct one.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
I don't know what is exactly Blizzlike, but i believe 717 is true.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make a Priest level 20
2. Learn "Inner Fire" Rank 3
3. Compare Skill Description in the Spellbook /  vs. actual Buff (right top screen)
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by ohsiros** [comment]
1. Screenshot shows rank 2
2. Buffs doesnt use the updated tooltip, this is blizzlike.

Double check your armor value in the character sheet and you’ll see that you probably have 717 bonus armor.

**Comment by Stifler82** [comment]
Delete Cache
**Video Test:** [Inner Fire](https://youtu.be/w3oLO58VmAE)
