### ISSUE TITLE
Supreme Defender Achievement not adding kills

### ISSUE THREAD

**Issue by chickenforce** [chromiecraft/chromiecraft#3748]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Currently my achievement tracker for "supreme defender" in WSG is stuck at 93/100 kills and whenever I kill the EFC it does not go up. This includes KB's and simply having been part of the kill combat. I have tested both types of kills with other players in low pop matches so I to limit any perceived cheating as cheating is not my intent. I just don't know how else to test it.  I have also done /reset, restarted the client, fully shut down my computer/restarts. This has been going on for 2 weeks now THAT I HAVE NOTICED. So it may have started a long time ago. I've been around since the 39 bracket. I have attempted all those troubleshoots throughout those 2 weeks.

### Expected Blizzlike Behaviour

I believe it should register the killing blow as +1 to the achievement counter.

### Source

Achievement description in-game.

### Steps to reproduce the problem

1. Kill an EFC in WSG and monitor the Supreme Defender achievement tracker. 
2. Assess any code that didn't register that should have if the counter did not increase by (1).
3. If it did increase, assess any areas that may cause it to not increase and then implement them... however that's done. I have no idea, wish I could help. :(

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
@chickenforce 

I am unable to replicate this issue. What is your in-game name?

**Comment by chickenforce** [comment]
So I opened this ticket on July 9th.. I just checked my achievements and I finished the Achievement, the next day on July 10th. I thought that was because ya'll had fixed the issue super fast to some degree. I say 'to some degree' because I was tracking it with each kill of the efc. I probably killed 20-25 efc's in the time it took to actually credit me the final 7. So it seemed like it was still an issue and having trouble "registering" most kills.

My in-game name is for the character in question is Chickenstorm.

**Comment by temperrr** [comment]
Sorry for not reaching you sooner, we are working on getting to all the old bug reports. I am glad it got resolved for you, and since nobody else had this issue, I think it may have just be something with your character. If someone else has this issue, feel free to open a new bug report!
