### ISSUE TITLE
[PTR][AQ20] Buru problems in addition to reported ones at AC

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#3758]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Mob: https://wowgaming.altervista.org/aowow/?npc=15370
1. No animation at Phase 2 - Exposed Carapace.
2. At p2 boss continues to apply Dismember  instead of reeping Creeping Plague.
3. Eggs still alive after boss death.

### Expected Blizzlike Behaviour

1.It should be dedicated animation for Exposed Carapace.
2. Boss should cast Creeping Plague at P2.
3. Eggs should dispawn after boss death.

### Source

1. https://www.youtube.com/watch?v=vZ78PHwMMpE - 28:25
2. https://classic.wowhead.com/guides/buru-the-gorger-ruins-of-ahnqiraj-strategy - "Phase 2 - Exposed Carapace
Once Buru's carapace is shattered, she will have a normal aggro table. However, she does not deal a lot of melee damage, so traditional tanks are not necessary (although you do want her hitting your Plate wearers preferably). She also loses her Dismember ability from Phase 1.

Buru's most dangerous ability in Phase 2 is Creeping Plague - Creeping Plague is applied to the entire raid, dealing increasing damage every second. The damage starts at 80 per second and doubles every 3 seconds (from 80 to 160 to 240, etc). Because of Creeping Plague, your raid has approximately 30 seconds to bring Buru from 20% to dead, so use and abuse your cooldowns to do so"

3. https://www.youtube.com/watch?v=vZ78PHwMMpE - 28:56

### Steps to reproduce the problem

For 1 and 2:
1. Go to AQ20 at PTR.
2. Reduce Buru HP  below 20%.
3. Encounter described problems.

For 3:
1. Go to AQ20 at PTR.
2. Engage boss and kill him.
3. Observe that eggs still not despawned.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR -  AzerothCore rev. 1d6dc750fa37 2022-07-09 21:38:58 +0000 (master branch) (Unix, Debug, Static)

**Comment by Gultask** [comment]
Thanks for the report, Kerrik!

Issues 2 and 3 have been already worked on. While issue 1 is still present.
