### ISSUE TITLE
Aggro'd monsters wait for you in front of instance portal

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#376]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Currently, if you aggro monsters from the open world and run into a dungeon instance portal, the monsters will stay in front of the instance portal and if you come back through said portal, they will attack you again.
The same behaviour happens if you aggro monsters from a dungeon and run out through the instance portal. If you go back into the dungeon, the monsters from the dungeon will be there waiting and attack you again.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Instance portals should be some sort of "safe space" that makes monsters reset to their original location and wiping threat tables. It should be this way both for both ways (if you're in the open world and go into a dungeon, or if you're in a dungeon and go out).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go near an instance portal with monsters around (ex: BFD)
2. Aggro monsters from the open world outside instance portal
3. Run into the instance portal
4. Wait a few minutes, go out the instance portal and get attacked

Same steps can be done from inside the instance (aggro a mob in BFD, go out into the open world).

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
- Enter or Exit
- Log-out
- Log-In
- Aggro lost
