### ISSUE TITLE
[PTR][AQ20] Ossirian the Unscarred problems

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#3763]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Mob: https://wowgaming.altervista.org/aowow/?npc=15339
1. Boss aggro radius is small.
2. There is no animation of the lifting Ossirian Crystal while interacting - it's stays on the ground and then suddenly appears in full length and casts Weakness.
3. Ossirian Crystals spawn time is too long.

### Expected Blizzlike Behaviour

1. Boss aggro radius should be significantly bigger, otherwhise it will be oneshot for tank (13k average hit).
2. It should be full animantion of Ossirian Crystal lifting up while interacted.
3. Ossirian Crystals should spawned again at 17-20 seconds.

### Source

1. https://www.youtube.com/watch?v=vZ78PHwMMpE - 01:07:28
3. https://www.youtube.com/watch?v=vZ78PHwMMpE - 51:39 - 52:13

### Steps to reproduce the problem

For 1:
1. Go to AQ20 at PTR.
2. Engage the boss.
3. Observe incorrect small aggro radius.

For 2 and 3:
1. Go to AQ20 at PTR.
2. Engage the boss.
3. Use Ossirian Crystal.
4. Observe incorrect behavior.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR -  AzerothCore rev. 1d6dc750fa37 2022-07-09 21:38:58 +0000 (master branch) (Unix, Debug, Static)

**Comment by Maelthyrr** [comment]
Hi, I'm sorry but could you next create a issue for each point ? Thanks, I'm looking into your issue.

**Comment by Gultask** [comment]
Oh me too x)

I'll leave it to Maelthyrr, I hadn't seen his comment.

Something to add:

- [ ] The Crystal's spells affect everyone, including itself, and not just the boss

**Comment by Gultask** [comment]
Maybe someone can sniff the crystal respawn timer and conditions since I've seen conflicting evidence to that video.

>You pull Ossirian with a hunter, they feign death, then the crystal in the middle resets. Pull him again and the crystal respawns instantly after being used, allowing you to spam weakness on him of all types and never have to kite him around. ([source](https://www.reddit.com/r/classicwow/comments/ipwhpc/aq20_ossirian_cheese/))

Other videos show that 20s is not enough and there's probably more nuance/conditions to it.

**Comment by kerricsson** [comment]
Hello, 

I've made some information search and found following data that can be probably useful:

1. https://lostinsauce.shivtr.com/forum_threads/2669241 - 
![изображение](https://user-images.githubusercontent.com/104144379/180607619-c22561ab-f886-4b6b-9c13-5d7d995c1c80.png) -map of multiple crystal locations + data that crystal spawn is not random but occurs clockwise or counterclockwise.

2. https://www.reddit.com/r/lightshope/comments/7rs5k5/darrowshire_fixed_ossirian_cystals_still_arent/ - also some statements from here - "On Retail: Triggering the first crystal at the base of the steps randomly spawns two of the three nearest crystals. After that, crystal spawns are no longer random. Triggering a crystal spawns the next nearest crystal in a rough counterclockwise circle around the room. A tank or scouter can memorize the spawn locations and do the whole fight "blind," no scouting for crystals required. Inexperienced groups still need a scouter, but the scouter starts from the crystal that was just popped and can see the next one within a short distance. (Either it's immediately visible or it's around a corner - never far enough to out of draw distance.) At no point are you ever required to run Ossirian all the way across the room." 

3. At AC discord at#sniff-public channel, guy Uberhax#1193 said that he has a lot of sniffs from Retail. So probably it will be possible to ask him to sniff AQ20 crystal spawn data since AQ20 wasn't changed since Vanilla regarding mechanics.

**Comment by Gultask** [comment]
Thanks! I'll test out the theories presented in your links. From what I remember I was trying to search for a pattern in the spawns but couldn't find one. I'll take another deeper look.
