### ISSUE TITLE
[Quest] Inoculation

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#3775]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Template change of moonkin plays levelup animation
Inoculated Nestlewood Moonkin are friendly to the player (green)

### Expected Blizzlike Behaviour

Template change of moonkin doesn't play levelup animation
Inoculated Nestlewood Moonkin are neutral to the player (yellow)

### Source

https://youtu.be/g3Qz_liqHR0

### Steps to reproduce the problem

Take the quest
Use the questitem on some moonkin

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=9303
https://wowgaming.altervista.org/aowow/?npc=16518

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by pangolp** [comment]
Confirmed. The NPC plays the animation, as if it had gained a level, and in turn, is friendly with the player.
https://github.com/azerothcore/azerothcore-wotlk/commit/02fa20b6380b991634198de9a295abac11152d60

```
.list c 16518
.go c 75965
```

![WoWScrnShot_071522_092558](https://user-images.githubusercontent.com/2810187/179222872-4db9c658-f66c-417b-969b-4d445279456c.jpg)

**Comment by pangolp** [comment]
I have been testing a solution that I believe meets the requirements you mention in the report description. That way, it no longer executes the level increase effect, gives the credit and remains neutral, since it doesn't change the npc template.
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=1651800 AND `source_type`=9;

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(1651800, 9, 0, 0, 0, 0, 100, 0, 3000, 3000, 0, 0, 0, 66, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Nestlewood Owlkin - On Script - Set Orientation Invoker'),
(1651800, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Nestlewood Owlkin - On Script - Say Line 0'),
(1651800, 9, 2, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 18, 33024, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Nestlewood Owlkin - On Script - Set Flag Immune To Players'),
(1651800, 9, 3, 0, 0, 0, 100, 0, 300, 300, 0, 0, 0, 33, 16534, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Nestlewood Owlkin - On Script - Quest Credit \'Inoculation\''),
(1651800, 9, 4, 0, 0, 0, 100, 0, 500, 500, 0, 0, 0, 89, 15, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Nestlewood Owlkin - On Script - Start Random Movement'),
(1651800, 9, 5, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 19, 256, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Nestlewood Owlkin - On Script - Remove Flag Immune To Players'),
(1651800, 9, 6, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 41, 10000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Nestlewood Owlkin - On Script - Despawn Instant');
```

**Comment by pangolp** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/12391

**Comment by Tereneckla** [comment]
That's just a hackfix though

**Comment by pangolp** [comment]
> That's just a hackfix though

Why would it be deficient? Maybe I misunderstood the problem, since I need a translator to write in English. My native language is Spanish. I apologize, if you can give me more information about it, maybe I can better understand what you meant when you made the report.

**Comment by Tereneckla** [comment]
It is a general problem that changing the template of a creature causes a levelup animation.
Fixing just this one issue (in a different way than intended) means it's a hackfix and not good style

**Comment by pangolp** [comment]
> It is a general problem that changing the template of a creature causes a levelup animation.
> Fixing just this one issue (in a different way than intended) means it's a hackfix and not good style

It's just that, what I'm doing, is not changing the template. That's the part I deleted. Because in the other template, the npc is friendly. On the other hand, by not updating it, it doesn't change the template, and it is still neutral. Besides, it does not affect the animation of change. Actually, modifying the `creature_template` is generally not recommended. Because it is assumed that these values are correct. So assuming that the other template makes the npc friendly is what leads me to think that the template should not be updated. I hope that with this explanation, I understand better, why I eliminated those lines.

**Comment by Tereneckla** [comment]
Does your fix change the name of the creature?

**Comment by pangolp** [comment]
> Does your fix change the name of the creature?

I didn't try it, but I'll check it out right away.

**Comment by pangolp** [comment]
No, it does not.

![WoWScrnShot_071622_040308](https://user-images.githubusercontent.com/2810187/179344181-2e645c7a-ac13-467a-839a-2334efa317e2.jpg)

**Comment by pangolp** [comment]
Reviewing the video, I see that the name should change, then the template, indeed I was watching, the problem then if this in the creature_template, which apparently, changes the faction of the npc surely. I will see if I can find out something about it, I had not noticed that change.

**Comment by pangolp** [comment]
- Name: [Inoculated Nestlewood Owlkin](https://tbc.wowhead.com/npc=16534/inoculated-nestlewood-owlkin)
- Quick Facts
- Type: Humanoid
- Added in patch 2.5.1.38043
- Source: tbc.wowhead.com

- Name: [Inoculated Nestlewood Owlkin](https://wowgaming.altervista.org/aowow/?npc=16534)
- Quick Facts
- Level: 3 - 4
- React: A H
- Faction: Friendly
- Source: wowgaming

**Comment by pangolp** [comment]
https://www.youtube.com/watch?v=a_qx4WRD27U

In that video, the theme of npc neutrality is maintained. But if the effect of level change / animation occurs. Maybe the person who made the fix, was guided by that video.

**Comment by pangolp** [comment]
![image](https://user-images.githubusercontent.com/2810187/179344852-d6c272e3-6f74-42dd-9bac-4e1dda5dd88a.png)
Perhaps, what may be wrong, is the script of the second npc.

**Comment by Tereneckla** [comment]
> https://www.youtube.com/watch?v=a_qx4WRD27U
> 
> In that video, the theme of npc neutrality is maintained. But if the effect of level change / animation occurs. Maybe the person who made the fix, was guided by that video.

Bue does videos on private servers

**Comment by pangolp** [comment]
> > https://www.youtube.com/watch?v=a_qx4WRD27U
> > In that video, the theme of npc neutrality is maintained. But if the effect of level change / animation occurs. Maybe the person who made the fix, was guided by that video.
> 
> Bue does videos on private servers

How do you know that is a private server and not a video from the official tbc server?

**Comment by pangolp** [comment]
The truth is that I don't know the person who made the video, but well, we will continue investigating until we find the cause of the problem, if there is one. At the moment, we have 2 things confirmed. The first one, that the template, has to be changed, because the npc, must change the name and the second one, that it must remain in neutral.

**Comment by Tereneckla** [comment]
> > > https://www.youtube.com/watch?v=a_qx4WRD27U
> > > In that video, the theme of npc neutrality is maintained. But if the effect of level change / animation occurs. Maybe the person who made the fix, was guided by that video.
> > 
> > 
> > Bue does videos on private servers
> 
> How do you know that is a private server and not a video from the official tbc server?

Made in 2020 with good quality
It doesn't have the tbc classic client visuals (button above the chatbox, has a number for the real id friends now)

**Comment by pangolp** [comment]
You are probably right in that respect. However, I then need to find out more details about it.

**Comment by pangolp** [comment]
Sorry for the delay, but in the end, it seems that we were able to find a solution to the problem.

https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/b2cf2047-eb99-4c13-864e-a66e3bccb30f
