### ISSUE TITLE
Uldaman Drop Tables (pre-report)

### ISSUE THREAD

**Issue by JamesGent** [chromiecraft/chromiecraft#378]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39

##### CURRENT BEHAVIOUR:

The staff should take a brief moment to pre-check the droptables in Uldaman.

Uldaman contains the best gear in the game for 39 characters, but certain items like Shadowforge Bushmaster have a 0.01% droprate.

The drop tables are definitely wrong in some places before (e.g captains key was 85% instead of 0.01%) so we want to make sure it's correct in advance, so the economy isn't flooded before it can be fixed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://classic.wowhead.com/item=9422/shadowforge-bushmaster

https://www.reddit.com/r/woweconomy/comments/9pu7oh/loot_from_1500_uldaman_runs/

##### STEPS TO REPRODUCE THE PROBLEM:

1. Open Uldaman droptables / NPC droptables.
2. Verify integrity of droptables.
3. Cross-compare to above sources/classic wowhead.

##### EXTRA NOTES:
--

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
unless someone is already working on this, @Hacki95 can pick this up

**Comment by Hacki95** [comment]
So these are all the droprates of those 7 ultra rare binding on equip blues: 
![grafik](https://user-images.githubusercontent.com/62942638/114303595-38654200-9acf-11eb-89b2-58d192db50c5.png)

You can see they pretty much have a 0,02% droprate everywhere except a few outliers. Those values seem to come from vanillawowdb.com as they are exactly the same.

The 0.2% dropchance for Miner's Hat of the Deep on the Shadowforge Archaeologist looks a bit weird too me, but there are only 2 of those spawned in Uldaman afterall.

One thing I didn't check yet are the rare recipes.

Some epic world drops seem to have a bit of a high chance to drop. For example Fiery War Axe has a chance of 0.1% as has Staff of Jordan.

I am not exactly sure though where we can get much more accurate numbers but atleast they don't seem to be off by a huge margin.

**Comment by JamesGent** [comment]
@Hacki95 It's off-topic but because you asked;

Captains Key is a 10% from Pirate's Footlocker, which is an 8% from various NPCs. 10% x 8% is 0.8%.

Before my report, Captains Key was a 80+% droprate from any pirate in Tanaris.

https://github.com/azerothcore/azerothcore-wotlk/issues/5129

**Comment by FrancescoBorzi** [comment]
closing this, if there is a problem with the loot please open a new issue
