### ISSUE TITLE
XP rate doubled

### ISSUE THREAD

**Issue by Aaron-of-Hungary** [chromiecraft/chromiecraft#3788]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I just joined the server. And get double XP for every quest.
Eg. the Quest log says I should get 220 xp, but instead I get 440.
See attached video.

Likely I get double xp for mobkills also, but I can't track that, as I don't know exactly how much xp I should get for a mobkill, so I cannot compare it with what I do get

https://user-images.githubusercontent.com/99685841/179314547-17df2f04-64ba-4a1b-a849-6a4eda3e60a2.mp4

.

### Expected Blizzlike Behaviour

I should get the amount of xp specified by the quest log, instead of double the amount.

### Steps to reproduce the problem

1. Complete a quest

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hi, Aaron, thanks for opening a report!

This feature comes from the module [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp), meaning that every other weekend the quest xp rate is multiplied by 2.

To turn this off you just need to input `.weekendxp rate 1` in the chat.

As for the mob xp you might be using the Recruit-a-Friend feature, that gives you permanent rested xp (200% mob xp). If you are, and do not want the extra xp, you can un-link your account from the recruiter.

Welcome to ChromieCraft! 😉

**Comment by Aaron-of-Hungary** [comment]
Hey @Gultask.
Thanks for the quick - and I mean lightning quick - reply. 
Cool feature, double xp every other weekend.
Thanks for the info.

**Comment by Gultask** [comment]
No problem! It was actually just coincidence that I saw your report, though 😛
