### ISSUE TITLE
[Live][ZG] Players can be feared through textures at 2 places

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#3794]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Yesterday we encountered 2 occasions in ZG at following places were players were feared under textures, fall down and almost died.

Location 1: https://ibb.co/GPt1rsn
Location 2: https://ibb.co/CtVFnNc

### Expected Blizzlike Behaviour

They should not feared to textures.

### Source

'---

### Steps to reproduce the problem

1. Go to ZG raid.
2. Go to locations at screenshots.
3. Check geodata/vmaps with special dev tools.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft Live - AzerothCore rev. 02fa20b6380b+ 2022-07-13 20:54:01 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Maelthyrr** [comment]
Hi, I'm sorry but I can't load the image. Could you give the coord?

**Comment by kerricsson** [comment]
Hello and sorry for the delay with answer:
I've tried to uploaded images to visible inside ticket:
![изображение](https://user-images.githubusercontent.com/104144379/180607841-bf4aeceb-8ba0-41aa-890f-28b297b96515.png)
![изображение](https://user-images.githubusercontent.com/104144379/180607915-d0b8cc5d-0d0d-4292-8485-e02bae37012f.png)

Let me know if they will still not visible, I'll add other related information.

**Comment by temperrr** [comment]
I have tried to get feared through the texture there, but I couldnt get it to happen.

**Comment by kerricsson** [comment]
Hello. thanks for answer. TBH I don't know how to find more proofs about that - we don't record videos during our raids, but people still feared through the ground/wall at these places each second run. I'll ask for more feedback or even evidences at CC discords.

**Comment by Cooties-cc** [comment]
I had recorded an experience, but diff spot (outside panth boss)

https://user-images.githubusercontent.com/62584589/185251010-f6c3fc38-60da-4c06-9688-0ca483320adc.mp4

**Comment by The-GhostRider** [comment]
If this problem existed when this Report was created, it probably no longer exists or alternatively it has become really rare, because in the video I made it is clear that the problem is no longer reproducible.

[![Anteprima video](https://user-images.githubusercontent.com/1884642/246633329-b6c490a9-79db-4f81-b5fc-29bc978de3a0.png)](https://www.youtube.com/embed/A5BEFSvWh3c)

For this reason I close the report.
