### ISSUE TITLE
npc is absolutely bugged out

### ISSUE THREAD

**Issue by Shevi22** [chromiecraft/chromiecraft#380]
Kel'gash the Wicked in ghostlands does not follow you when you line of sight him with a column, just stays still, unsure of the pathing. He also shoots instant chain lightnings WHILE casting lightning bolt. Chain Lightning is definitely a spell with cast time. I am suspicious that this npc is bugged.
1. It should follow me when it cant cast because of line of sight
2. it should not be throwing random chain lightnings whenever he feels like it.

~Sapish

**Comment by Shevi22** [comment]
![feba3ae4ddbc00e85a3a3d531384c000](https://user-images.githubusercontent.com/39674406/114037578-67867400-9881-11eb-836e-d28dd99c2bf4.jpg)

**Comment by Shevi22** [comment]
we have been chilling for minutes!

**Comment by Shevi22** [comment]
I have a strong suspicion that all caster mobs are bugged in this very same way. In fact, if a caster mob has two spells to cast, they will interrupt their own cast time to start casting another spell instead, which is NOT how it should happen.

**Comment by ohsiros** [comment]
Te chain lightning Kel’gash uses is instant. See https://wotlk.evowow.com/?spell=28900#used-by-npc 

LoS seems bugged though.

**Comment by markvetx** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3740

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303
https://github.com/azerothcore/azerothcore-wotlk/issues/5022

**Comment by markvetx** [comment]
Could this be related to SAI?

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/8672
