### ISSUE TITLE
[Live][ZG] Ohgan HP should be tuned do not die too fast before Bloodlord Mandokir

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#3802]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=14988
Now Ohgan has 45950 HP (source - https://legacyplayers.com/viewer/31697/base?history_state=5) and, while tanking separatly in accordance with tactics he can be easily killed by single T2 geared tank that will cause Bloodlord's enrage for 1 minute, severely increasing his damage done. So proposal is to tune his HP to 100000 (he has 600k on PTR) to prevent his fast death and raid wipe.

### Expected Blizzlike Behaviour

Ohgan HP should be tuned accordingly to prevent sudden death and unplanned enrage from Bloodlord Mandokir. 

### Source

'---

### Steps to reproduce the problem

1. Go to ZG raid.
2. Assign 1 skilled and T2 geared tank to Oghan.
3. See results - raptor will be killed early just by this tank.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft Live - AzerothCore rev. 02fa20b6380b+ 2022-07-13 20:54:01 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Maelthyrr** [comment]
@temperrr

**Comment by temperrr** [comment]
Hey, 

His health is intentionally tuned down to increase the difficulty of the fight.

**Comment by kerricsson** [comment]
Ok, thanks for answer, Can you please advise what should be done next? Should I collect more feedback  from other guilds/create suggestion or do some other actions?

**Comment by temperrr** [comment]
Feel free to make a suggestion instead over at the discussion board and get others involved

**Comment by kerricsson** [comment]
Ok, will do. Please do not close the issue.

**Comment by kerricsson** [comment]
Hello. After multiple raids and some feedback from raiders I came to conclusion that Ohgan tuning is ok. Please close this issue.
