### ISSUE TITLE
[PTR][AQ40] Kandrostrasz <Brood of Alexstrasza> do not have exclamation mark after doing first Mortal Champions quest

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#3807]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=15503
Kandrostrasz <Brood of Alexstrasza> do not have exclamation mark after doing first Mortal Champions quest (https://wowgaming.altervista.org/aowow/?quest=8595). Screenshot: https://ibb.co/2NmtBBm
Probably next repeatable Mortal Champions quest (https://wowgaming.altervista.org/aowow/?quest=8595) in progress state cause this behavior.

### Expected Blizzlike Behaviour

Kandrostrasz <Brood of Alexstrasza>  should have exclamation mark when he has multiple quests available.

### Source

https://www.youtube.com/watch?v=ZVlG3hfFzrE - 01:30

### Steps to reproduce the problem

1. Go to PTR.
2. Enter AQ40.
3. Do initial Mortal Champions quest (https://wowgaming.altervista.org/aowow/?quest=8595). Observe that exclamation mark dissapeared when next repeatable Mortal Champions is in progress and other quests for T 2.5 are available .

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. cc52712ac12e 2022-07-15 16:11:49 +0200 (master branch) (Unix, Debug, Static)

**Comment by Stump876** [comment]
I haven't had a chance to check this issue specifically, but for whoever does, I think it's an issue with quest `!` popping up while you're looking at the quest giver. I think this might be a client issue.
For example, at level 35, reach cooking to 225 **while in the Gadgetzen Inn** and notice the `!` doesn't appear for the clamlette suprise quest. Zone out and back in, or reload UI, and it will be there.

**Comment by Sneften** [comment]
I just tested this on the PTR and can't reproduce. Might be a client issue as Stump mentioned and can be closed? @Gultask 

https://user-images.githubusercontent.com/103856689/208646604-31b3e8a7-3cf5-4954-b353-4c613a099f04.mp4

`.go c 87529`
`.additem 21229 5`

**Comment by Gultask** [comment]
Most likely a client/cache issue, yes.
