### ISSUE TITLE
[PTR][AQ40] Battleguard Sartura encounter problems - part 1

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#3809]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

NPC:  https://wowgaming.altervista.org/aowow/?npc=15516
https://wowgaming.altervista.org/aowow/?npc=15984
1. Boss have small aggro radius.
2. Boss do not use Sundering Cleave ability. 
3. Sartura's Royal Guards no not use Knockback ability. 

### Expected Blizzlike Behaviour

1. Boss should have an extremely long aggro range
2. Boss should use Sundering Cleave ability immediately following her Whirlwind.
3. Sartura's Royal Guard should use Knockback ability

### Source

Overall fight - https://www.youtube.com/watch?v=-tNMCO7_LiY 23:30

1. https://classic.wowhead.com/guides/battleguard-sartura-temple-of-ahnqiraj-strategy - Additionally, the boss has an extremely long aggro range and will be "body-pulled" from a great distance, so when mounted up and running in, Warriors need to be leading the group towards the boss.
2. https://classic.wowhead.com/guides/battleguard-sartura-temple-of-ahnqiraj-strategy -  Sundering Cleave goes out immediately following Battleguard Sartura's Whirlwind. This is also an AOE effect, doing direct damage and lowering armor on all those hit with the effect. As the spell mentions, this can stack up to 3 times, so hopefully, only the tanks are being hit by this Sundering Cleave, as any cloth wearing ranged players might have their armor reduced to a very low amount, and if they are hit by a single whirlwind, they could go down!
3. https://classic.wowhead.com/guides/battleguard-sartura-temple-of-ahnqiraj-strategy - Knockback is unique to the Royal Guards and add plenty of chaos to the fight. As you can see, the primary mechanic is to keep the adds and the boss under control and prevent them from running through the raid, cleaving the raid down. The tanks that are assigned to the Royal Guards need to keep their backs to the wall in the room, away from the raid, in the event they are knocked back. If a tank is knocked through the raid, the raid needs to re-position itself to avoid getting whirlwinded by the add.

### Steps to reproduce the problem

1. Go to PTR.
2. Enter AQ40.
3. Engage Battleguard Sartura.
4. Observe small aggro radius.
5. Observe boss mechanics.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. cc52712ac12e 2022-07-15 16:11:49 +0200 (master branch) (Unix, Debug, Static)

**Comment by Nyeriah** [comment]
About 1) she engages as soon as you enter room (I've already scripted this about a month ago), so whoever triages this please check it out (try entering the room normally, no teleport)

**Comment by Maelthyrr** [comment]
Hi, I confirm the issue with aggro range but for spells issue, it was probably with https://github.com/azerothcore/azerothcore-wotlk/pull/12577/files. Thanks you for the repport.
