### ISSUE TITLE
Auction house deposit incorrectly displayed

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#381]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When posting an auction at the auction house, the deposit displayed seems amazingly high. But when the auction is created, the deposit that is actually "paid" is way smaller and more appropriate.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The actually "paid" deposit (smaller amount) should be displayed in the AH window when posting an auction.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to AH.
2. Post an item that has actual vendor value, no matter what it is (say a stack of Silk Cloth).
3. Watch the very high displayed deposit and write down current gold in your bag.
4. Post the auction and pay the deposit, write down gold after paying deposit.
5. Do the maths and see that it doesn't check out with the deposit displayed at step 3.

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by dole555** [comment]
It's working as intended, the deposit is actually only 10% of what is shown.

**Comment by pop-pig** [comment]
> 
> 
> It's working as intended, the deposit is actually only 10% of what is shown.

I don't know how it was in "retail WotLK" back in the day, but on Classic WoW it displays the "actual deposit" that is being paid. I also remember Vanilla Wow to be like that, haven't really played TBC and later expansions.
It just seems weird no?

**Comment by dole555** [comment]
> > It's working as intended, the deposit is actually only 10% of what is shown.
> 
> I don't know how it was in "retail WotLK" back in the day, but on Classic WoW it displays the "actual deposit" that is being paid. I also remember Vanilla Wow (2004-2006) to be like that, haven't really played TBC and later expansions.
> It just seems weird no?

Hey,

Yes, it's weird. They have reduced the deposit value to 10% to encourage growth, but the devs said on discord that they can't modify the displayed amount because that's client-side and it would require a patch to the client.

Weird that they don't write it on the website though under the modified rates section.

**Comment by pop-pig** [comment]
Okay, thanks for your reply. It seems like the deposit should be 60% of vendor price for 24hrs (2.5% per hour). It seemed really high to me but looks like it's the correct amount.

Maybe we can close this issue, sorry :)
