### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by Grimreefa** [chromiecraft/chromiecraft#3818]

**Comment by pangolp** [comment]
Greetings. Please, if you can provide some links. As for example, the one of the spell and the glyph you mention, you can do it in this page: https://wowgaming.altervista.org/aowow/.

I found the glyph, but not the talent.
- https://wotlkdb.com/?spell=56542
- https://wotlkdb.com/?item=42735

Thanks.

**Comment by pangolp** [comment]
What happened to this? @Grimreefa

**Comment by pangolp** [comment]
> Probably realized that this is invalid as those things increase the critical damage bonus and not the critical hit damage
> aka a 25% increase of the damage bonus means a crit now deals 162.5% damage instead of 150%

When the report is not valid, or you consider that it was not necessary to do so, feel free to close it.

**Comment by pangolp** [comment]
> I would if I could

Do you want me to close it?

**Comment by Tereneckla** [comment]
> > I would if I could
> 
> Do you want me to close it?

Do what you want, it's not my report

**Comment by pangolp** [comment]
> > > I would if I could
> > 
> > 
> > Do you want me to close it?
> 
> Do what you want, it's not my report

I didn't realize they were 2 different people. I wanted to talk to the owner of the report, not you, but since you wrote later, I thought it was the same person.

**Comment by pangolp** [comment]
@temperrr Please close this topic, as the message was edited and the information was not completed. Thank you.  If the problem persists, another report can be created later.
