### ISSUE TITLE
Glyphs from mainspec can work in second spec

### ISSUE THREAD

**Issue by oterfesk** [chromiecraft/chromiecraft#3837]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

I got Glyph of Eternal Water on my main spec (frost) and after respeccing to fire (secondary spec) the water elemental will still spawn when dismounting as you can see on this screenshot. it happened in Arathi Basin, even when i dismissed it, it respawned when exiting the battleground so it could have something to do with instance switching idk

![WoWScrnShot_072022_224213](https://user-images.githubusercontent.com/84633953/180079366-18192a95-2125-4f0c-b81e-a593bfc0e450.jpg)

### Expected Blizzlike Behaviour

Glyphs that are in main spec should not bleed through too secondary spec

### Steps to reproduce the problem

1. make a mage with dualspec, grab glyph of eternal water
2. respec to another spec and join an instance (it happened in arathi basin)
3. mount and dismount and the elemental should spawn

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/757375f982429c60b17e9b1f559ed86cb22abbc4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
I can not confirm recreating it on ptr, but it definitely happens on live and people are abusing it

**Comment by temperrr** [comment]
@oterfesk 

I cannot reproduce this issue on the PTR. Do you have any steps to reproduce it better?

**Comment by oterfesk** [comment]
> 

i've found that it only appears after dying and respawning, other than that i dont really know of anything else that could narrow it down :( 

the switching to second spec happens immediately before joining BG but i dont think that has anything to do with it
