### ISSUE TITLE
Ending There World Quest won't complete

### ISSUE THREAD

**Issue by gavinlfab93** [chromiecraft/chromiecraft#3845]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

Ending There World last quest in a chain, tried to complete in a party with a warrior, I am a paladin, originally I started it and npc walked off but warrior hadn't then waiting for him to start the quest both went through and killed elites, blew up the structures and killed the elite at end, but my quest didn't update, tried going back to npc nothing, I abandoned the quest and went to sleep, picked quest up again today and did by myself, when blowing up the structure there was no notification to say this was updated on the quest but the npc kept going and i then killed the elite at end, again no update but the npc still did all the dialog as it is in my chat logs, tried going to npc still nothing, also went to the blood watch which is where it is stated you go by the npc and the "?" is still greyed out as it hasnt been completed not sure why the milestones aren't working on this quest.  

### Expected Blizzlike Behaviour

Well I completed the milestones expected in the quest and should have the quest rewards, also in the case of being in a party with a warrior he should have had a pop up to ask about joining me on the quest when I first started the quest but that never happened. 

### Steps to reproduce the problem

I am unsure myself why it didnt work but try completing the quest Ending There World . Which is last chain quest of killing blood elfs in the bloodmyst isle. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/757375f982429c60b17e9b1f559ed86cb22abbc4

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi gavinlfab93. Thanks for the report. I can confirm the game does not give credit for this quest upon completion.

**Comment by temperrr** [comment]
closed by https://github.com/azerothcore/azerothcore-wotlk/pull/12489
