### ISSUE TITLE
Unable to attack a mob

### ISSUE THREAD

**Issue by PrimaIVoid** [chromiecraft/chromiecraft#3849]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

20-29

### Current Behaviour
While in Ashenvale in Feral Druid form, i'm unable to hit this particular mob, or initiate a fight with it
Approaching the mob from all angles or trying to hit it with abilities or autoattack does nothing
The mob ignores me entirely, does not move, and i receive this message: "Out of range" "You are too far away"
To note this mob has probably spawn on top of this structure that might cause its weird behaviour

![cantattack](https://user-images.githubusercontent.com/62378967/180768478-82dc5baa-337b-4c13-97f1-8884f1dc8d45.png)
----
Edit 1: Changing form to Human-Druid and using any ranged abilities correctly hit the mob and initiate a fight as usual
Edit 2: After killing the mob, it respawned exactly on the same location, still with the same bugged behaviour

### Expected Blizzlike Behaviour

Expectt to initiate a fight with the mob and hit it / being hit by it

### Steps to reproduce the problem

Location: West of Ashenvale
DB GUID: 34977
current GUID: 20661
DisplayID: 802

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/757375f982429c60b17e9b1f559ed86cb22abbc4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, PrimalVoid 🙂
