### ISSUE TITLE
[Quest] Ending Their World - No completion credit

### ISSUE THREAD

**Issue by cryosomnium** [chromiecraft/chromiecraft#3852]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

After you assist NPC [Demolitionist Legoso](https://www.wowhead.com/npc=17982/demolitionist-legoso) in setting up explosive charges and killing Sironas, you get no credit for the quest, Legoso makes his speech and disappears (as he should), but no credit. Hence it's impossible to complete it. Done 3 times, fruitlessly.

### Expected Blizzlike Behaviour

After Sironas is killed you should get the credit for the quest that it's completed, while Legoso is saying "I can't believe it's over..."

### Source

The player gets credit for the quest while Legoso is making his speech - https://www.youtube.com/watch?v=lARzK9CLu24&t=579s (9:27)
https://www.youtube.com/watch?v=uE0vSRGYaUI (15:04)

### Steps to reproduce the problem

1. Go to the traveling companion [Demolitionist Legoso](https://www.wowhead.com/npc=17982/demolitionist-legoso).
2. Start the quest (Draenei only) and see it through, assisting him to kill Sironas in the end.
3. Wait until he's done with the speech and disappears.

### Operating system

MS Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by cryosomnium** [comment]
Oh, it was actually reported just 3 days ago - https://github.com/chromiecraft/chromiecraft/issues/3845

**Comment by temperrr** [comment]
Thanks for your report anyway!
