### ISSUE TITLE
Forsake Courier + Guards clipping underground.

### ISSUE THREAD

**Issue by brandonclyon** [chromiecraft/chromiecraft#3859]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

30-39

### Current Behaviour

When running along the road in Arathi looking for the Courier for "Hints of a New Plague?" the mob group names appeared underground and could not be targetted. I ran back and forth on the road twice more to see if they respawned elsewhere but did not.

### Expected Blizzlike Behaviour

Mobs walk along road, not under it.

### Steps to reproduce the problem

1. Walk along road.
2. See name tags under the ground.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3ea74e26190e3a62b76128298cac98f83ae5ba34

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by brandonclyon** [comment]
After running back and forth a few more times they finally appeared on the road near Go'Shek Farm

**Comment by Gultask** [comment]
Hey, brandon, thanks for the report!

Do you remember the approximate location you found them under the ground, by any chance? Looking at their waypoints and watching them move seems fine to me.
I believe this could've been caused by a player killing the courier but not the guards, making it so that they move directly to the newly-spawned Courier, ignoring the terrain most of the time.

**Comment by brandonclyon** [comment]
Ah that could have been it. I saw them almost dead center of their path in
Arathi Highlands.

**Comment by Gultask** [comment]
Thanks! I'll re-check the waypoints when I get the chance to :)

**Comment by Gultask** [comment]
It seems to be an issue with them trying to catch up with the newly spawned courier after it died.
