### ISSUE TITLE
Mind flay does not refresh Shadow Word: Pain during Nefarian's Paladin class call

### ISSUE THREAD

**Issue by ICarebear** [chromiecraft/chromiecraft#3862]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

Whenever Nefarian has a Paladin class call; During said call, Mind Flay does not refresh the duration of Shadow Word: Pain despite there being 100% chance to do so

### Expected Blizzlike Behaviour

Shadow Word: Pain should refresh as long as Mind Flay deals damage to an enemy

### Steps to reproduce the problem

Enter Blackwing Lair and start fighting Nefarian
Apply Shadow Word: Pain and keep it applied
Wait until Paladin class call
Mind flay and check the duration of Shadow Word: Pain

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3ea74e26190e3a62b76128298cac98f83ae5ba34

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
likely same issue as #3462
ability is flagged as physical, not magical, wrongly

**Comment by Sneften** [comment]
Yes this has been fixed with https://github.com/azerothcore/azerothcore-wotlk/pull/11678.
Tested on the ptr and Mind Flay successfully refreshes Shadow Word: Pain.
