### ISSUE TITLE
Statue in BRD Magmus' room starts following the Warlock's pet after the fight

### ISSUE THREAD

**Issue by TheSlumbering** [chromiecraft/chromiecraft#3865]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

50-59

### Current Behaviour

After defeating Magmus in BRD and moving into the next room with a Warlock in a party, one of the statues from previous room "wakes up" and follows Warlock's pet (specifically Felhunter) while casting Fiery Burst until either the pet is dismissed or the warlock is dead. The statue then stays in that spot indefinetely. It has no animations and can't be targeted or AOE'd.
![Снимок экрана (30)](https://user-images.githubusercontent.com/47646688/181850539-f2ae5d5a-b36c-4926-8890-2d42afeb7d73.png)
.

### Expected Blizzlike Behaviour

Statues should stay in place

### Source

[https://www.wowhead.com/wotlk/npc=9938/magmus](url)

### Steps to reproduce the problem

1. Go to BRD
2. Kill Magmus as a Warlock with Felhunter pet (don't know if it happens with other pets)
3. Go to the next room

### Extra Notes

The boss was always killed and looted near the doors to the next room. I also have no idea if it happens with other warlock pets, or even hunter pets.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d580ca4f316c66893ec76282c8dd3e0762d3f662

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by anjachan** [comment]
I tried reproducing the problem and I couldn't. Did that happen in one run or more? I tried 3-4 times and still couldn't do it with the given steps.
My reproduction: https://studio.youtube.com/video/tfrKFwfo3QM/edit

**Comment by TheSlumbering** [comment]
Thank you for testing. This happened to me during 3 separate runs. We always had a warlock in the party with felhunter pet. 
Also, the issue has something to do with one of the fire breathing statues in Magmus' room (as seen in the screenshot, there is a statue that followed us outside its room). Sorry for leaving out that info, as i didn't realize that the first time.

**Comment by TheSlumbering** [comment]
Looks like someone ran into the same issue before, but not much info to get there. #3544

**Comment by anjachan** [comment]
So, to make it clear. You were killing Magmus at the door leading into the next room and one of the statues started following you? Did the statue start following you when you pulled the boss? (If so, from where did you pull the boss) Or did it start moving after/while killing the boss?

**Comment by TheSlumbering** [comment]
We pulled the boss from where it usually spawns in his room. We then led the boss to the door to next room (the door is closed, so we never left Magmus' room) and started killing him. Right after we killed the boss and entered the next room, one of the statues started following and attacking us (it looked like it was aggroed to our warlock with felhunter)

**Comment by valery445** [comment]
I've successfully provoked the bug on PTR 3 times on recording, and 3-4 without it.
The bug can be encountered without killing Magmus, though the golem is active even after boss death.
Also warlock imp is able to cause the bug too.

Video 1: https://youtu.be/tWb_v4P4xTI
Video 2: https://youtu.be/psCjEjE44lU
Video 3: https://youtu.be/3GtIAonEjUI

The steps I took:
1. Create a warlock
2. `.character level 60` `.learn 688` (Imp)
3. Enter BRD with `.tele brd`
4. `.additem 11000`, skip all bosses up to Magmus
5. Enter the Lyceum, get 2 Shadowforge Torches `.additem 11885 2` and use them on braziers to open gates to Magmus
6. Summon Imp before pulling Magmus
7. Go into the boss room, pull the boss
8. Go straight to the gates to last boss room. Then kite the boss to the gates at the start
9. Repeat step 8 until golem starts attacking imp

**Comment by DPComputer** [comment]
CAn confirm, happened in two different runs on regular server.
Once with hunter pet aggroing the golem, the other with warlock pet.
