### ISSUE TITLE
Priest Dispersion Spell fails to reduce damage

### ISSUE THREAD

**Issue by Amber-Haze** [chromiecraft/chromiecraft#3897]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Shadow Priest spell Dispersion fails to reduce incoming damage as it should when cast close to the incoming damage skill going out
https://wowgaming.altervista.org/aowow/?spell=47585

Combat log shows it failing while the aura is still active (dissipates after death)
they're in spanish.

![20220804_112805](https://user-images.githubusercontent.com/86187541/183301495-7a111656-ff9e-48cc-a0e0-a2346aabc5dc.jpg)
![20220804_113017](https://user-images.githubusercontent.com/86187541/183301514-733e0244-a71d-4b63-887c-60007fe77554.jpg)

### Expected Blizzlike Behaviour

It should reduce incoming damage as stated in the description.

### Source

https://www.wowhead.com/wotlk/spell=47585/dispersion#comments

It states that certain boss mechanics and fall damage bypass it, but nothing else should.

### Steps to reproduce the problem

Get a priest with Dispersion (capstone talent on shadow tree)
Cast Dispersion right before the enemy strikes (or when a spell is in mid air)
Damage will fail to reduce, it shows in combat log

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Amber, thanks for the report!

Currently spells like Dispersion and Deterrence have no effect if the incoming spell is already mid-flight. Which  is in line with current WotLK Classic it turns out.
But I'm not certain if that should be the case.

For example: [this video](https://youtu.be/umetTVtTb2A?t=65) shows a Hunter deflecting a Lava Burst **after** it's already been cast.
[more info](https://github.com/TrinityCore/TrinityCore/issues/577)

Posting this now as a reminder for myself and others if they wish to pitch in on this issue.

**Comment by Vitusin** [comment]
Can We already got fixed this is ?!

**Comment by Gultask** [comment]
It needs more research to be Confirmed. Basically what we need is evidence that mid-flight spells are affected by Dispersion/Deterrence or any other defensive auras.

**Comment by Pyromanihack** [comment]
I tested the issue in the PTR against [Deathshadow Warlock](https://wowgaming.altervista.org/aowow/?npc=22363) and I noticed that a spell already cast (like Shadow Bolt) it's immune to dispersion and I take the entire amount of damage, all the spells against me, after I cast Dispersion, have reduced damage.
So I think that this dynamic it's Blizz-like
