### ISSUE TITLE
Amani Berserker Inside of Tree

### ISSUE THREAD

**Issue by Cosmic-Lattee** [chromiecraft/chromiecraft#39]
##### SMALL DESCRIPTION:

Troll NPC (Amani Berserker) moving through a large tree.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC's shouldn't spawn or be able to go inside of objects like this. 

##### CURRENT BEHAVIOUR:

Below is a picture of the NPC, he will walk around the tree and sort of phase out of it though he doesn't leave the "tree."
You could melee him but ranged attacks generate LOS errors.

![image](https://user-images.githubusercontent.com/24766235/106949863-2e9c1880-66f3-11eb-95f8-6ca8283e82d7.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to this location (see Current Behavior for location)
2. Wait for this NPC to spawn to see if he is spawning inside of the tree or somehow going inside of it.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
this might be already solved with the big pathfinding improvements we are working on (not yet on chromiecraft)

**Comment by Helias** [comment]
the HD patch can affect this, try without it.

**Comment by Cosmic-Lattee** [comment]
I am using a stock 3.3.5 client. Also I was in a party with my wife and she also saw this troll in the tree.

**Comment by Helias** [comment]
Ok, thank you 👍

**Comment by Hacaw** [comment]
Found the location.
.go 8581.577148 -7865.790039 155.361542

##### AC HASH/COMMIT: 
[adcf3f7a](https://github.com/azerothcore/azerothcore-wotlk/commit/adcf3f7a)

##### DATABASE VERSION: 
WORLD: 2021_02_01_00
AUTH: 2021_01_25_00
CHARACTERS: 2021_01_25_00

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
Chromie-Client (Downloaded from 10-01-2021)
DBC & Maps - v9 - 1-12-2020

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Stifler82** [comment]
I confirm, the MOB is spawned inside the tree texture.

**Comment by Stifler82** [comment]
Fixed
-
https://user-images.githubusercontent.com/1884642/108254980-87d46500-7153-11eb-89d6-111ceee261ca.mp4
