### ISSUE TITLE
Guild Announcements Not Working! :(

### ISSUE THREAD

**Issue by mouthcrime** [chromiecraft/chromiecraft#390]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Type here.

Custom guild announcements using the calendar do not work. (Not talking about the message of the day.) They do not show up at all! Which is super sad because I was trying to get my guild together for a GUILD BANK GIVEAWAY EXTRAVAGANZA!

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

I would just like the messages to show up in guild chat when they're scheduled to do so! :D

##### STEPS TO REPRODUCE THE PROBLEM:

1. make guild announcement for X time using the calendar
2.  wait for X time to appear
3. ?????
4. announcement does not appear when it's time

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
Confirmed:

Creating event:
![image](https://user-images.githubusercontent.com/81375770/114282152-897b2480-9a42-11eb-841e-e1966c09168d.png)

Nothing happened:
![image](https://user-images.githubusercontent.com/81375770/114282174-ab74a700-9a42-11eb-834e-fb46c0bd702c.png)
