### ISSUE TITLE
[Silithus - Quests] Armaments of War should be class specific

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#3910]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

I finished whole quest line of https://wowgaming.altervista.org/aowow/?quest=8315, and Armaments of War questline should appear for class specific, for example for rogue should appear https://wowgaming.altervista.org/aowow/?quest=8378. But I got other versions of it, cloth or mail ones, or even leather for spellpower one.

![image](https://user-images.githubusercontent.com/80590226/184006927-711e434f-abba-4d72-8342-2a8e1957e228.png)

### Expected Blizzlike Behaviour

I finished whole quest line of https://wowgaming.altervista.org/aowow/?quest=8315, and Armaments of War questline should appear for class specific, for example for rogue should appear https://wowgaming.altervista.org/aowow/?quest=8378. But I got other versions of it, cloth or mail ones..

### Source

https://wowgaming.altervista.org/aowow/?quest=8315
https://wowgaming.altervista.org/aowow/?quest=8378

### Steps to reproduce the problem

1. Do whole questline of The Calling
2. Try which Armaments of War will open for you after you finish 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by anhility** [comment]
Seems like four of her quests aren't tagged with a class.

**AoWoW:**
![image](https://user-images.githubusercontent.com/7052334/184037464-b4bf100c-d70a-4b23-90e0-685f1761fd3d.png)

**WotlkDB:**
![image](https://user-images.githubusercontent.com/7052334/184037518-7e576d9d-59fa-4a47-bf9f-8c9299883493.png)

**Comment by temperrr** [comment]
Thanks for your report. :)
