### ISSUE TITLE
[PTR][AQ20] General Rajaxx wave timing

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#3919]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

General Rajaxx wave timing is not in a 3 min intervall.

### Expected Blizzlike Behaviour

the next wave should always come latest after 3 mins, or with the death of the previous one.

### Source

https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy

https://wowwiki-archive.fandom.com/wiki/General_Rajaxx

### Steps to reproduce the problem

bossfight, pull first wave, dont kill the mobs and stop the time

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
>Note: Patch 1.11 shortened the time between waves.

and the following can be seen in retail:

https://user-images.githubusercontent.com/100873791/184550254-b5848eaf-d7ae-4fbe-a09f-08f33a4c379c.mp4

But I get what you mean, I've been trying to make the the waves last 3 minutes with no success in Retail but I've seen people claim it was 3 minutes in retail as well and I trust them a lot as well. It seems that there's some hidden mechanic I'm missing here.
It's also hard to find concrete video evidence of it, especially post patch 1.11

**Comment by Gultask** [comment]
Closed due to inactivity.

If anyone manages to find a source, feel free to ping me :)
