### ISSUE TITLE
[PTR][AQ20] General Rajaxx Thundercrash min damage to high

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#3921]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Thundercrash does half the players hp as damage, but at least 200 damage

### Expected Blizzlike Behaviour

minimum damage caused should be 100 damage

### Source

https://wowwiki-archive.fandom.com/wiki/General_Rajaxx

https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy

### Steps to reproduce the problem

https://github.com/azerothcore/azerothcore-wotlk/blob/3771a7120d962bbe7cca70a1c1440b4acba440a5/src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_rajaxx.cpp#L114

```
void HandleDamageCalc(SpellEffIndex /*effIndex*/)
    {
        int32 damage = GetHitUnit()->GetHealth() / 2;
        if (damage < 200)
        {
            damage = 200;
        }

        SetHitDamage(damage);
    }
```

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
The links you posted contradict themselves, wowwiki says 200 min while wowhead says 100 min, must be some Classic change

**Comment by balleny** [comment]
> The links you posted contradict themselves, wowwiki says 200 min while wowhead says 100 min, must be some Classic change

not necessarily contradict.
both state an initial wave timer of 3 mins

wowwiki:
![image](https://user-images.githubusercontent.com/12682004/184645842-9b62311e-8066-4eee-85df-367ade2ea2a8.png)

classic.wowhead
![image](https://user-images.githubusercontent.com/12682004/184645936-9538cad0-1b4f-40e9-b4a7-cba12bdc5e2f.png)

time between waves was decreased later on, because the health of the mobs was also decreased (see patchnotes 1.11)
![image](https://user-images.githubusercontent.com/12682004/184646133-45023dd8-308c-4e66-96ea-003b8e9298fb.png)

**Comment by balleny** [comment]
> The links you posted contradict themselves, wowwiki says 200 min while wowhead says 100 min, must be some Classic change

i dont see a contradiction here and would take the number mentioned in both as the correct one.

wowwiki:
![image](https://user-images.githubusercontent.com/12682004/184646543-9b911572-1b8f-46d2-a808-c6870f39a4dc.png)

wowhead:
![image](https://user-images.githubusercontent.com/12682004/184646655-d0664b7b-6c3e-4dfc-a92a-4db974f27188.png)

**Comment by Nyeriah** [comment]
![image](https://user-images.githubusercontent.com/47818697/184650010-ccaa28f2-bd14-4125-a41b-c871bbaabe52.png)
https://wowwiki-archive.fandom.com/wiki/General_Rajaxx

**Comment by balleny** [comment]
yes, wow wiki is stating both values, once at the top and once in the text.
as the 100 is also the value listed in wowhead, i would assume the 200 to be incorrect.

**Comment by avarishd** [comment]
> Keeping the NPCs alive should be the only thing healers should focus on, as anyone who is not tanking Rajaxx and is over 100 HP is safe.

https://www.wowhead.com/wotlk/npc=15341/general-rajaxx#comments:id=2805102:reply=1194026

> Although the raid will be constantly at low health during Rajaxx himself, you do not need to panic heal the entire raid - Thundercrash deals a minimum of 100 damage, so you only need to keep everyone but the tanks above 100 health.

https://www.wowhead.com/classic/guide/general-rajaxx-ruins-of-ahnqiraj-strategy#healers

**Comment by Nyeriah** [comment]
Ok, will take it
