### ISSUE TITLE
[Arathi Highlands] Inaccessible herb node and double spawns

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#394]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Wild Steelbloom (GUID 4214) is spawned too high on a hill making it impossible to reach.

Golthorn GUID 9150, 8871 this is double spawn, should be 1 node at this location.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Herb node should be spawned in reachable location. Herb nodes are not supposed to be spawned in tight clusters (of 2 or more)  simultaneously

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 4214 (spawn it if its not spawn)
2. Go down and try reaching it to harvest
3.  Teleport to GUID 9150 or 8871
4. See the clustered spawn

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Agree with the second part of this, but not the first.

For the first, I teleported to the spot in Arathi (.go o 4214) and then, while standing there, spawned a temporary herb (.gobject add temp 1623). I had no problems running away and then coming back and picking that herb. Maybe being a big tauren helped, or did I do something wrong when respawning it so it wasn't exactly where you saw it?

Screenshot showing tauren able to pick the wild steebloom:
![WoWScrnShot_041121_135824](https://user-images.githubusercontent.com/81782124/114292598-c260db00-9ace-11eb-9685-da97054fa1f7.jpg)

**Comment by mdawx** [comment]
First part is also correct:
![image](https://user-images.githubusercontent.com/81375770/114302848-3a2d0680-9acb-11eb-9668-26d6dfb12e35.png)

**Comment by Helias** [comment]
fixed, it will be live soon, thanks for the report
