### ISSUE TITLE
[Silithus] Logistics Assignment - Wrong Item Data

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#3940]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

60

### Current Behaviour

Currently when you open the Logistics Assignment (not the follow up), it contains IV, VI, VII, X, and II. 

### Expected Blizzlike Behaviour

Logistics Assignment are suppose to contain : IV, VI, VII, X, and V. 
https://wowgaming.altervista.org/aowow/?item=21266#contains
https://www.wowhead.com/wotlk/item=21266/logistics-assignment#contains;0+1+16-19
https://wowpedia.fandom.com/wiki/Logistics_Assignment?oldid=2036295

Logistics Task Briefing II is suppose to only come from the follow up assignments, not the basic assignments from Field Duty quest. 

### Source

https://user-images.githubusercontent.com/62584589/185041599-7dff6610-27a6-42b6-a9fc-c4cc11751edf.mp4

This was taken from the live server, not PTR. 

### Steps to reproduce the problem

1. Accept and complete Field Duty quest [8731]
2. Select Logistics Assignment
3. Repeat until you see it give Logistics Task Briefing II

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
Forgot to add that this may just be another horde side problem, as we've already had one with the same items (more or less)
_"Followup Tactical/Logistical/Field assignments should now also contain the follow up quest items for Horde characters"_
An alliance player in the same guild said they got one from their normal logistics assignment, not the follow up, so I know its working in some part. I spent a good hour, running back and forth, and never saw a V from the normal assignments. Only a couple times from the follow up ones.

**Comment by ishidinho** [comment]
Hey @Cooties-cc. Thank you for the report.

There is a fix for this issue in the pipeline https://github.com/azerothcore/azerothcore-wotlk/pull/12760.
