### ISSUE TITLE
Unable to Kick DC'd RDF Member several minutes after Loot Roll Ends. 

### ISSUE THREAD

**Issue by shewlace** [chromiecraft/chromiecraft#3945]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

RDF Group member DC'd (during combat).  Mobs were looted and items were rolled on.  After 3-5mins of waiting, group attempted to kick DC'd member, but the error comes up saying that a group member may not be kicked while an item is being rolled on.  All item rolls ended at the time. 

Contacted GM Linedara who said there was a 2min grace period after a roll.  We waited another 3-5mins.  Same error message for all group member when trying to kick.  
Group members were Uddermethis (me), Kozz, Honeita, Frozenjudge, and Peluchoso (The member that DC'd) is that is at all helpful. 

### Expected Blizzlike Behaviour

Member should have been kickable when no items were being actively rolled on. 

### Source

na

### Steps to reproduce the problem

Possible be in an RDF group, have a member Alt F4 while in combat and attempt to kick the member after items are rolled on. 

### Extra Notes

I've had this happen before in UBRS specifically. It also happened coincidently at the groups before Drekk just like this time.  That time around we were able to 4man Drekk.  This time, we were unable to and had to abandon the group. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @shewlace. Thank you for the report.

This issue has already been reported.

Duplicate https://github.com/chromiecraft/chromiecraft/issues/3723.
