### ISSUE TITLE
[WSG] Warsong Gulch is 'popping' with 4 players and closing in 5 minutes due to insufficient players.

### ISSUE THREAD

**Issue by Lag21** [chromiecraft/chromiecraft#3949]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

1-19

### Current Behaviour

While the announcer states that 6 people are needed for Warsong Gulch to start, it is currently starting when there are only 4 people in the queue. Once the battle begins with 4 players, the battleground announces that it will be closed due to insufficient number of players inside.

### Expected Blizzlike Behaviour

Either the battleground should not start with less than 6 people or it should not close if there are only 4 players inside.

### Source

Own experience. Seems to be a pretty clear bug, not sure if further source is needed.

### Steps to reproduce the problem

1. Queue to Warsong Gulch 10-19 with 4 players, it will prompt the box to enter the battleground.
2. Wait for battle to start.
3. Announcer will start closing the battleground.

### Extra Notes

![WoWScrnShot_081822_122305](https://user-images.githubusercontent.com/19967787/185384553-e6e292f9-4504-49b7-9bdf-302c0ac38da9.jpg)
![WoWScrnShot_081822_122450](https://user-images.githubusercontent.com/19967787/185384626-503e535e-f19f-48f5-afeb-584c340e7fd8.jpg)

As you can see in the first screenshot, I requested one person to join the queue. After s/he joined, the BG Queue Announcer reported 3/6 players in the queue. I then asked an additional player to join, which triggered the battleground to begin. 

There's an additional screenshot after the battleground began with the message that it will close in 5 minutes with only 4 players, as expected.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Fixed with the new cfbg PRs, but I'll mark your report as valid since that was the case back then.

Sorry for the (very) late response
