### ISSUE TITLE
[PTR][AQ20] Buru the Gorger - Full Speed

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#3950]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

[Full speed](https://wowgaming.altervista.org/aowow/?spell=1557) used by timer 60 seconds after the start of the fight. Full speed and [Gathering Speed](https://wowgaming.altervista.org/aowow/?spell=1834) also causes a boss speed bug where it starts to accelerate much earlier than it should after the egg explodes.

### Expected Blizzlike Behaviour

[Full speed](https://wowgaming.altervista.org/aowow/?spell=1557) shouldn't be used on the 1st phase. It should only be used in the 2nd phase, about 10-12 seconds after it starts to protect the boss from kiting in this phase.

### Source

https://vanilla.warcraftlogs.com/reports/cQ3ZrFGg1KqxnWCm#fight=22&hostility=1&type=casts&view=events - more than 60s between explosions
https://vanilla.warcraftlogs.com/reports/zKLbC79rPthgJ42B#fight=27&hostility=1&view=events&type=casts
https://vanilla.warcraftlogs.com/reports/bgyM3rB9cCQdKzVA#fight=25&hostility=1&type=casts&view=events

### Steps to reproduce the problem

1. Pull the boss
2. Wait >60s

3. Also after 60s try to destroy some egg
4. See how fast it accelerates after this

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report! It seems that the current implementation is indeed wrong. Full Speed should only be cast during phase 2. And up to 20 stacks of Gathering Speed could be applied.
