### ISSUE TITLE
[Blasted Lands][Swamp of Sorrows] Fingat patrolling Blasted Lands. Under textures. r:#1453

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3957]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

50-59

### Current Behaviour

Fingat is clipping under the textures in the Northwestern Blasted Lands

https://www.youtube.com/watch?v=Q_kFmYBTu_M

Probably the fix from #1453 has gone kind of wrong :>

_Moreover, the GUID seems to be different than the one in the report above. A misplaced clone?_
![WoWScrnShot_081922_231718](https://user-images.githubusercontent.com/79346412/185708577-e34183f9-2443-4f38-bc86-f6925644262a.jpg)

___
_Also opening a new ticket cause the old ones hardly ever get reviewed_

### Expected Blizzlike Behaviour

[Fingat](https://wowgaming.altervista.org/aowow/?npc=14446) probably shouldn't even be in the Blasted Lands to begin with, but inside the cave in Swamps of Sorrow. 

He also doesn't have a [Flawless Draenethyst Sphere](https://wowgaming.altervista.org/aowow/?item=8244) like most of BL rares does, so I would take that as an argument.

### Source

[AoWoW](https://classic.wowhead.com/npc=14446/fingat)
[Wowhead](https://wowgaming.altervista.org/aowow/?npc=14446)
[Already Confirmed Ticket Regarding This Mob](https://github.com/chromiecraft/chromiecraft/issues/1453)

### Steps to reproduce the problem

1. Wait for this fishy gnome to spawn
2. Search for him in the video's area (Preferably with the _Silver Dragon_ addon or just /target)
3. Observe that reality denying bastard

### Extra Notes

DB Guid: **134237** 
(Current: **112730**) 
Entry: **14446**

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report, Sathrenor! And nice catch!
There was a typo in the waypoints that was sending the poor murloc all the way to Blasted Lands :)

The Guid difference is because there are 7 possible spawns for Fingat, each one with their own waypoints. Every single possibility has its unique GUID and is added to a pool that only allows 1 spawn at a time.
