### ISSUE TITLE
[BG Queue] Person outleveled queue which he queued and got warning after he couldn't accept

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#3959]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

There was person in world chat saying that he queued for BG while he was 38, and he waited 4 hours to pop queue, he meanwhile got lvl 41, and queue popped, but he was in queue for 31-39 and when he tried to accept it wrote to him like warning when you don't accept queue.
![image](https://user-images.githubusercontent.com/80590226/185740124-b0af181b-802c-4227-993a-65d997c07b1f.png)

### Expected Blizzlike Behaviour

Should probably make him into new queue automatically for 40-49, I forgot how it was on retail.

### Source

Not sure how it worked on Blizzlike :( But I Think it did transfer to new queue level.

### Steps to reproduce the problem

1. Queue up for battleground for lower level tier, since queue is long
2. Get few levels up for example queue as 38, get to 41 and wait for queue to pop
3. You won't be able to enter as you queued for 30-39 and now are 42..

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
Comment of player on screenshot.

**Comment by bojan112** [comment]
you are removed from queue after 1.5h

**Comment by BeefSteaker** [comment]
unable to reproduce this on ptr or local, presumably a visual/rare bug,
without more info from their side its hard to know
