### ISSUE TITLE
[BWL - Nefarian] Blue sack of gems picked by whole raid

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#3965]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

![image](https://user-images.githubusercontent.com/80590226/185805797-e979f132-5ad6-4aae-b214-4bf176c359be.png)

Blue sack of gems dropped for whole raid, picked by 25 of us.

### Expected Blizzlike Behaviour

Should be like before, pickable my ML or only by 1 person.

### Source

https://wowgaming.altervista.org/aowow/?item=17962#contains

### Steps to reproduce the problem

1. Be in raid group
2. Kill Nefarian with GL or ML or FFA loot
3. Everyone can pick Blue Sack of Gems which wasn't possible until this week.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Plasmashield** [comment]
Same problem with world bosses. Because of this, we can't even skin them

**Comment by BeefSteaker** [comment]
Hi, thanks for the report, tried to replicate this on the ptr, but after a dozen attempts ive been unable to replicate.
also run BWL every week and havent noticed getting a sack of gems recently.

Presumably this has been fixed by some other changes

**Comment by Elexias** [comment]
@BeefSteaker Sadly, happened 2 days ago to our guild raid again :)

**Comment by BeefSteaker** [comment]
Do you have a video/screenshot of that?
Its not happening on the PTR as far as can tell so it could be chromie specific.

I've got 3x BWL & WB sets this week so I'll keep an eye out on live

**Comment by BeefSteaker** [comment]
happened on my raid tonight
