### ISSUE TITLE
[PTR][AQ20] General Rajaxx - Kaldorei Elite

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#3966]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Four [Kaldorei Elite](https://wowgaming.altervista.org/aowow/?npc=15473) didn't engage in fight with waves

### Expected Blizzlike Behaviour

Kaldorei Elite should stay with [Lieutenant General Andorov](https://wowgaming.altervista.org/aowow/?npc=15471) and help with waves

### Source

https://youtu.be/Sg_BlR_F2hk

### Steps to reproduce the problem

1. Start the event
2. Цait for mobs

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Hey I am unable to recreate it. 
The Kaldorei Elites aid me alongside General Andorov the whole event. 

short clip of testing:

https://user-images.githubusercontent.com/103856689/186109767-085aac01-b795-47b7-a57d-8e3095979dad.mp4

**Comment by Plasmashield** [comment]
@Sneften 


https://user-images.githubusercontent.com/27493763/186132559-4818dc42-4d0f-4a42-a8f5-5170efd5e96c.mp4

**Comment by Maelthyrr** [comment]
@Plasmashield since one mounth, did it happen again?

**Comment by Gultask** [comment]
Was probably fixed in the last Rajaxx PRs, sorry for the late response.
