### ISSUE TITLE
[PTR][AQ20] General Rajaxx - Lieutenant General Andorov

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#3967]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour
[Lieutenant General Andorov](https://classic.wowhead.com/npc=15471/lieutenant-general-andorov)
Stuns everything (including the boss) almost all the time. So the boss is stunned for the whole fight. Also, I think he uses other abilities too often.

### Expected Blizzlike Behaviour

Lieutenant General Andorov shouldn't stun that often.

### Source

https://vanilla.warcraftlogs.com/reports/pa3W8d4zxrfPhQnv#fight=11&type=auras&hostility=1&spells=debuffs&ability=25515
https://vanilla.warcraftlogs.com/reports/7MhtQjD6GBRvgrHy#fight=6&type=auras&hostility=1&spells=debuffs&ability=25515
https://vanilla.warcraftlogs.com/reports/J3Fq1gNPVwyATmcb#fight=20&type=auras&spells=debuffs&hostility=1&ability=25515&source=81&target=65&view=events
https://vanilla.warcraftlogs.com/reports/kpYjJnAGLzQv7hdV#fight=22&type=auras&hostility=1&spells=debuffs&ability=25515

### Steps to reproduce the problem

1. Start event
2. Wait for boss

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Can confirm Rajaxx was stuned throughout the whole encounter pretty much.

https://user-images.githubusercontent.com/103856689/186123573-52cd3e04-0bb4-4223-a8f4-72c2d21db43f.mp4

**Comment by Nyeriah** [comment]
Thanks for the report 👍
