### ISSUE TITLE
[QUEST] Cannot start Gurf's dignity before turning in "Murlocs... Why Here? Why Now?"

### ISSUE THREAD

**Issue by anglerf1sh** [chromiecraft/chromiecraft#397]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

As of right now it is not possible to start the Quest Gurf's Dignity before turning in Murlocs... Why Here? Why Now? The quest can be started from an item (https://www.wowhead.com/item=23850/gurfs-dignity) dropped by Murgurgula (https://www.wowhead.com/npc=17475/murgurgula GUID 62989)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should be possible to start the Quest before turning in "Murlocs... Why Here? Why Now?" (see https://www.wowhead.com/quest=9564/gurfs-dignity#comments:id=2869772)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Complete the entire Questline required to understand furbolg language (see https://www.wowhead.com/quest=9538/learning-the-language)
2. Go to Gurf after turning in the last Quest in the Questline and accept "Murlocs... Why Here? Why Now?"
3. Go to Murloc infested shore west of Stillpine Hold (Azuremyst Isle) 
4. Kill Murgurgula 
5. Get Questitem, quest cannot be started until you turned in "Murlocs... Why Here? Why Now?"

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
You are referring to comment written by moneybiz on 2019/02/04 (Patch 8.1.0). According to other sources it requires "Murlocs... Why Here? Why Now?" quest done:

- https://wowpedia.fandom.com/wiki/Gurf%27s_Dignity_(quest)
- https://wotlkdb.com/?quest=9564
- https://wotlk.evowow.com/?quest=9564

**Comment by anglerf1sh** [comment]
The comment I posted was too new, I missed that sorry:

Comment speculating that the totem quest is required
https://www.wowhead.com/quest=9564/gurfs-dignity#comments:id=787174:reply=140086

Comment noting that totem questline is required: (from TBC)
https://www.wowhead.com/quest=9564/gurfs-dignity#comments:id=226947
