### ISSUE TITLE
[PTR][AQ20] Ayamiss the Hunter - Paralyze 

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#3975]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Currently used every 15 seconds

### Expected Blizzlike Behaviour

Should be used less often. Time between casts should be random. 
Also, perhaps, the timer should be reset when entering the second phase.

### Source

https://vanilla.warcraftlogs.com/reports/ThQf2rxGHPkJjNRa#fight=47&type=casts&hostility=1&source=69&ability=25725
https://vanilla.warcraftlogs.com/reports/T9mxvJGdnANHhFtC#fight=54&type=casts&hostility=1&source=77&ability=25725
https://vanilla.warcraftlogs.com/reports/QyYGXqrjWFVvKRbw#fight=last&type=casts&hostility=1&source=77&ability=25725
https://vanilla.warcraftlogs.com/reports/cZ7J8L3RkTBytKgh#fight=last&hostility=1&source=80&type=casts&ability=25725
https://vanilla.warcraftlogs.com/reports/G731TdvYz8Fpa2Kb#fight=last&hostility=1&source=40&type=casts&ability=25725
https://vanilla.warcraftlogs.com/reports/wnJKpjxT4Aym8v6N#fight=last&hostility=1&type=casts&source=92&ability=25725
https://vanilla.warcraftlogs.com/reports/DaQnpB4wfvNxjkcK#fight=last&hostility=1&type=casts&source=73&ability=25725

### Steps to reproduce the problem

1. Pull boss
2. Watch how often she uses the ability

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/pull/13048
