### ISSUE TITLE
[PTR][AQ20] Ayamiss the Hunter - Thrash

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#3976]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Thrash has wrong, fixed timer

### Expected Blizzlike Behaviour

Time between casts should be random.
I think something like 10-30s

### Source

https://vanilla.warcraftlogs.com/reports/ThQf2rxGHPkJjNRa#fight=47&type=casts&hostility=1&source=69&ability=3391
https://vanilla.warcraftlogs.com/reports/T9mxvJGdnANHhFtC#fight=54&type=casts&hostility=1&source=77&ability=3391
https://vanilla.warcraftlogs.com/reports/cZ7J8L3RkTBytKgh#fight=last&hostility=1&source=80&type=casts&ability=3391
https://vanilla.warcraftlogs.com/reports/wnJKpjxT4Aym8v6N#fight=last&hostility=1&type=casts&source=92&ability=3391
https://vanilla.warcraftlogs.com/reports/DaQnpB4wfvNxjkcK#fight=last&hostility=1&type=casts&source=73&ability=3391
https://vanilla.warcraftlogs.com/reports/dpB2kb8JLPVzCajA#fight=60&type=casts&hostility=1&source=81&ability=3391
https://vanilla.warcraftlogs.com/reports/RFmW23L6rjzVXHZ1#fight=last&type=casts&hostility=1&source=76&ability=3391
https://vanilla.warcraftlogs.com/reports/1nFBPGYHjzN6JMtr#fight=last&type=casts&hostility=1&source=84&ability=3391
https://vanilla.warcraftlogs.com/reports/81LfKaVP69mRQ3Tx#fight=last&type=casts&hostility=1&source=99&ability=3391
https://vanilla.warcraftlogs.com/reports/VWGpQxMJjqdH743g#fight=last&type=casts&hostility=1&source=70&ability=3391
https://vanilla.warcraftlogs.com/reports/zRCLjJdYfb6WgN2A#fight=last&type=casts&hostility=1&source=78&ability=3391
https://vanilla.warcraftlogs.com/reports/Rv1KXjf9YDy47qgC#fight=last&type=casts&hostility=1&source=73&ability=3391
https://vanilla.warcraftlogs.com/reports/tFPRvGYaMzLAm4cD#fight=63&type=casts&hostility=1&source=76&ability=3391

### Steps to reproduce the problem

Pull boss and go to 2nd phase

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Si1ker** [comment]
Changed in https://github.com/azerothcore/azerothcore-wotlk/pull/12738
