### ISSUE TITLE
[AQ20] Ayamiss the Hunter is not coming down at 70%

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#3988]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

![image](https://user-images.githubusercontent.com/80590226/186488036-cdba8b31-1693-419d-bdba-72fbc8d282d9.png)

Boss should come down and be attackable by melees

### Expected Blizzlike Behaviour

Boss should come down and be attackable by melees

### Source

https://www.youtube.com/watch?v=-iVRscJqTq0&ab_channel=PlatinumWoW

### Steps to reproduce the problem

1. Pull the boss and dps him below 70% and he stays on top still

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e0b7c7d0d3b1ea65860439add2c676b3e18f8f8b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Elexias, thanks for the report!

We aren't able to reproduce the issue in any way. Do you happen to remember how long was the encounter? As in, how fast did you kill Ayamiss?

**Comment by Elexias** [comment]
Wasnt that fast, as melee cannot damage him, whole fight he was in air.

**Comment by Elexias** [comment]
![WoWScrnShot_082922_205921](https://user-images.githubusercontent.com/80590226/187278053-3bcba69f-6cf7-424d-a507-bc22068bf5ee.jpg)
![WoWScrnShot_082922_210004](https://user-images.githubusercontent.com/80590226/187278057-b8a96f6f-5792-4076-ab5c-faa74da64659.jpg)
![WoWScrnShot_082922_205951](https://user-images.githubusercontent.com/80590226/187278063-8b51a301-66bc-427b-b35c-be273184a430.jpg)
![WoWScrnShot_082922_205933](https://user-images.githubusercontent.com/80590226/187278064-cf5b3268-f03c-491d-93e6-55c6edbdf0db.jpg)

@Gultask Proof again, was slow killing, took so long.

**Comment by Gultask** [comment]
Found a way to consistently reproduce it. Maybe with this fix it'll work better now :)

**Comment by Nefertumm** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/pull/13048
