### ISSUE TITLE
Silverpine forest high level mobs

### ISSUE THREAD

**Issue by CaptainCoolFace** [chromiecraft/chromiecraft#400]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ X] Horde

##### CONTENT PHASE:

- [X ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

There is a high-level (55) mob in silverpine forest that is supposed to only be in western plaguelands. It appears in Fenris Isle in the eastern murlock camp.
![image](https://user-images.githubusercontent.com/82292678/114286436-92083680-9a13-11eb-9962-6e4230298825.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This enemy npc should only appear in western plaguelands.

##### STEPS TO REPRODUCE THE PROBLEM:

1. GUID 52542
2. Position 869, 68, 32
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Confirmed on local test server, AzerothCore rev. c0cb2eae38dc+ 2021-04-06 03:52:40 +0000 (master branch) (Unix, Release)

However, the WotlkDB page for this mob at https://wotlkdb.com/?npc=1787 actually does list one in Silverpine Forest at this location. So do three other Wrath database sites, though it's likely they're all using the same copied data anyway. Wowhead Classic does not mention this mob in Silverpine. So either this is a bug that shows up in a lot of data sites, or it was actually part of Wrath, added some time after Classic. Given that murlocs and Scourge don't have any reason to hang out, it does seem more likely to be a bug though.

![WoWScrnShot_041121_132532](https://user-images.githubusercontent.com/81782124/114292169-bcb5c600-9acb-11eb-85ca-9b276e12956d.jpg)

**Comment by mdawx** [comment]
Thanks @Azcobu. According to https://wowpedia.fandom.com/wiki/Skeletal_Executioner these mobs should be located in Ruins of Andorhal only. Other sorce: https://vanilla-twinhead.twinstar.cz/?npc=1787

**Comment by FrancescoBorzi** [comment]
thanks @Azcobu for helping triaging the issues. When you are able to confirm and reproduce an issue on your local AC server, please complete the procedure and copy the report to the AC bug tracker.

The entire process is explained here: https://github.com/chromiecraft/chromiecraft#for-contributors-how-to-triagereport-bugs

**Comment by Helias** [comment]
fixed by @Raelorasz, thanks for the report

**Comment by Azcobu** [comment]
> thanks @Azcobufor helping triaging the issues. When you are able to confirm
> and reproduce an issue on your local AC server, please complete the procedure
> and copy the report to the AC bug tracker.
> The entire process is explained here:
> https://github.com/chromiecraft/chromiecraft#for-contributors-how-to-triagereport-bugs

Thanks for the link. However, I'm not a contributor to CC (in the formal
sense), so I can't change labels or close issues as the link suggests. All I can
usefully do is reproduce issues. And to be fair, I'm still new and making
mistakes, so I probably shouldn't have those abilities just yet in any case.
