### ISSUE TITLE
Demonic Runes should have 15 min cooldown shared with Dark runes

### ISSUE THREAD

**Issue by mcts-cc** [chromiecraft/chromiecraft#4011]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

When I use items in the following order: Demonic Rune, then Dark Rune, both cooldowns are displayed properly. But if I use Dark Rune first I'm able to use Demonic Rune in about 2 minutes.

![obraz](https://user-images.githubusercontent.com/112405137/187222343-8c4d2d46-5632-4792-a007-e9dd8eb2d549.png)
![obraz](https://user-images.githubusercontent.com/112405137/187222453-e569aed6-8cc2-471c-8a3c-fb2f316c3279.png)
![obraz](https://user-images.githubusercontent.com/112405137/187222492-73614306-a76a-4b4d-99a5-b055a83e4558.png)

### Expected Blizzlike Behaviour

Both items should trigger the same cooldown - 15 min.

### Source

* [Demonic rune](https://wowgaming.altervista.org/aowow/?item=12662)
* [Dark rune](https://wowgaming.altervista.org/aowow/?item=20520)

### Steps to reproduce the problem

1. Use Dark Rune
2. Observe cooldown on Dark Rune and Demonic Rune
3. Use Demonic Rune after 2 min
4. Observe both cooldown are 15 min.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Hi mcts-cc! I can confirm the issue.

**Comment by Nefertumm** [comment]
Fixed https://github.com/azerothcore/azerothcore-wotlk/pull/12921
