### ISSUE TITLE
[War Effort] Questline for Opening Gates of AQ should be available before War Effort is complete

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4013]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

As Staff mentioned and since no1 else is answering. Not sure if this is planned but it shouldn't work as you've type don announcement.

![image](https://user-images.githubusercontent.com/80590226/187268571-45f1cf73-ef3e-4e06-9440-ff52cfa9f454.png)

Quoting:
"2. Ending the Quest Chain
Once you manage to get all three of the shards, Anachronos will only grant you the Scepter once "we" are prepared. In order to become prepared, we will need to finish gathering supplies for the War Effort and the final assault on [C'Thun](https://classic.wowhead.com/npc=15727).

2.1. The War Effort
The War Effort is a server-wide effort that every player on a realm can contribute to. It is only available once a guild has managed to reach this stage and started the progression through the War Effort. Any player can then contribute materials to the effort to further its completion.

Once the supplies have been collected, a 7-day timer will start while NPCs move to Silithus. When this timer starts, players that are eligible to receive a Scepter will be given one, but they can only ring the gong to open the gates once the timer is done.

The ringing of the gong signals the beginning of a 10 hour war upon the opening of the gates. Once this is finished, players can finally finish their quest chain and enter [AQ20](https://www.icy-veins.com/wow-classic/ruins-of-ahn-qiraj-aq20-raid-guides) and [AQ40](https://www.icy-veins.com/wow-classic/temple-of-ahn-qiraj-aq40-raid-guides)."

### Expected Blizzlike Behaviour

https://www.icy-veins.com/wow-classic/quest-line-guide-for-the-scepter-of-the-shifting-sands-mount-and-the-scarab-lord-title

We should be able to do whole chain before last part before War Effort is done, and not picking first part of it AFTER War Effort is done.

### Source

https://www.icy-veins.com/wow-classic/quest-line-guide-for-the-scepter-of-the-shifting-sands-mount-and-the-scarab-lord-title

### Steps to reproduce the problem

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UnicornManure** [comment]
To add some more links, https://classic.wowhead.com/guides/ahnqiraj-war-effort & https://wowpedia.fandom.com/wiki/Gates_of_Ahn%27Qiraj say the same

**Comment by BeefSteaker** [comment]
This is being changed https://discord.com/channels/788063059926712341/794247581763895316/1014170011922866226
![image](https://user-images.githubusercontent.com/11332559/187513713-66e27ac4-40a0-453a-8834-b1f0f7455902.png)
