### ISSUE TITLE
[AQ40] Some issues with boss pull and combat mode

### ISSUE THREAD

**Issue by Santaria94** [chromiecraft/chromiecraft#4016]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

1. Players do not enter combat mode after pulling a Bug trio and Princess Huhuran. Also on this bosses and Imperator twins, players can enter the raid during an active battle.
2. After pulling other bosses, players get a combat mode, but only at a certain distance (looks like the visibility range of the boss?). If the player is in a raid, but at a great distance from the boss, then he will not get a combat mode.
3. It looks like players do not enter combat mode if they were resurrected through the druid battle res.
4. Sarture can be pulled without his adds via hunters FD
5. If the twin emperors are evading, then one of the emperors can be pulled until the second reaches his position.
6. Bosses do not currently have evade zones. With them you can walk around the raid. They can also be bugged, if the first player on the aggro list runs too far from the boss, then he stops chasing him and just stands still

### Expected Blizzlike Behaviour

1. After the pull boss, all raid members must be in combat mode, no matter what position they are in the raid zone. Also players should get the combat mode after battle res
2. Sarture's adds obviously should join the fight with him and don't evade if Sarture continues the fight.
3. Players should not be able to enter the raid zone if there is a fight going on at the moment.
4. I can't 100% confirm that bosses should have evade zones. But in all the videos I've watched, the boss fights were in their rooms. This is also hinted at by the closing door on the twin emperors.

### Source

----

### Steps to reproduce the problem

1. Try pull Bug trio, Huhuran with one character and see if the other characters that didn't attack the boss got a combat mode
2. Try pull Bug trio, Huhuran, Emperor Twins with one character and try to enter the raid area with an outside character
3. Try to pull any boss and walk with him throughout the raid. Also try to run far away from the boss, having the first place in the aggro list and see with another character what the boss will do.
4. Try to kill one of the characters during the boss fight and resurrect him with a druid via battle res. See if he enters combat mode automatically upon resurrection

Sarture and her adds:
1. Hunter pull Sarture without AoE
2. His pet or another player attacks Sarture without AoE
3. After that, the hunter uses Feign Death.

Imperor Twins. I used hunter for testing
1) Boss pull
2) Feign Death
3) Pull again one of the bosses before the second one reaches his position

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by kerricsson** [comment]
Hello. Can anyone from triages have a look on it? Or it is already fixed on AC and is irrelevant now? Thanks in advance for your answer.

**Comment by kerricsson** [comment]
Good day, Any update to triage this issue?

**Comment by Nyeriah** [comment]
Those issues are not related to each other with difficulties the triaging/development process

**Comment by kerricsson** [comment]
What do you recommend to do than? Split this issue to multiple issues?
