### ISSUE TITLE
Only one may rise quest (broodlord head)

### ISSUE THREAD

**Issue by Frodhi** [chromiecraft/chromiecraft#4019]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

The head is lootable only once, and not for everyone who's on the quest as it should be, at least on the wrath client.

### Expected Blizzlike Behaviour

Everyone who has the quest, should be able to loot the head, without having to decide beforehand who will loot it.

### Source

![Screenshot_20220831-102213_Chrome](https://user-images.githubusercontent.com/107235442/187618880-59ce6304-e835-47b3-8f01-4e2001ab6cde.jpg)

This is a comment on wowhead for the quest item 

### Steps to reproduce the problem

Kill Broodlord in a raid
Loot the head (assuming you're on the quest)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Can confirm this does apply to https://github.com/azerothcore/azerothcore-wotlk/commit/9724c07528ab2746bd8e38fdc9a062f4854d788c.
There are a few other Wowhead comments that support the claim that the head became raid-wide lootable in TBC, as well as [this archived Wowpedia page](https://wowpedia.fandom.com/wiki/Head_of_the_Broodlord_Lashlayer?oldid=798684).

**Comment by heyitsbench** [comment]
Can no longer confirm the issue, appears to be dropping for each player in the raid as is blizzlike.

**Comment by BeefSteaker** [comment]
either fixed or invalid
