### ISSUE TITLE
Glorious Shield item drop

### ISSUE THREAD

**Issue by VMecko** [chromiecraft/chromiecraft#402]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Could you check loot table of NPC Gamon in Orgrimmar? Today it dropped Glorious Shield of Strength (ID 14973) https://classic.wowhead.com/item=14973/glorious-shield#dropped-by which is not correct if you check dropped by section. Item sells for almost 3g, which might cause economic flaws at this level.

![image](https://user-images.githubusercontent.com/9343102/114298303-fed40d00-9ab5-11eb-8259-73bb011cf33e.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Glorious Shield < of ... > should not drop from npc Gamon (see drop table for reference).

##### STEPS TO REPRODUCE THE PROBLEM:

Since it's not 100% drop rate i guess the fastest way is to look at loot tables if such thing exists for this npc.

Sincerely,

Trazzy (Murlock IGN)
Trazzy#3314

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
Glorious Shield of Strength (ID 14973) is not in Gamon's loot table.
SELECT * FROM `creature_loot_template` WHERE (`Entry` = 6466);
