### ISSUE TITLE
[War Effort] - Ahn'Qiraj War Effort Supplies Boxes (minor)

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4023]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

60

### Current Behaviour

When you open a Ahn'Qiraj War Effort Supplies, sometimes it will contain zero items. It also doesn't contain any scroll buffs. 

### Expected Blizzlike Behaviour

These boxes should contain an item on every open, which is normally some scrolls. Scroll amounts are varied by minimum 1, up to 19 (depending on type of scroll). Level ranks of scrolls are designated by rank of box, as well as are the other drops in the table. 

### Source

https://wowpedia.fandom.com/wiki/Ahn%27Qiraj_War_Effort_Supplies?oldid=2448029
![image](https://user-images.githubusercontent.com/62584589/187829069-a1984016-cdc3-42d1-85e3-5ee206e224c7.png)
(note the box green lvl is for the lvl 50 box)

wowhead wotlk links :
[lvl 10 box loot](https://www.wowhead.com/wotlk/item=21509/ahnqiraj-war-effort-supplies#contains)
[level 20 box](https://www.wowhead.com/wotlk/item=21510/ahnqiraj-war-effort-supplies#contains)
[level 30](https://www.wowhead.com/wotlk/item=21511/ahnqiraj-war-effort-supplies#contains)
[level 40](https://www.wowhead.com/wotlk/item=21512/ahnqiraj-war-effort-supplies#contains)
[level 50](https://www.wowhead.com/wotlk/item=21513/ahnqiraj-war-effort-supplies#contains)

### Steps to reproduce the problem

1. Go to any of the war effort quest givers and get a Ahn'Qiraj War Effort Supplies (or .additem)
2. Open multiple boxes
3. Note how none of them contain scrolls, and are sometimes just empty

### Extra Notes

Also this isn't an issue about more loot dropping from the boxes. The boxes are never meant to be empty, which is why the baseline loot is a scroll(s). 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by valery445** [comment]
Happened to me as well with [Alliance Iron Bar quest](https://classic.wowhead.com/quest=8494/the-alliance-needs-iron-bars). Turned in 5 stacks of Iron, opened 5 boxes - all were empty.

**Comment by Gultask** [comment]
Thanks for the report!
