### ISSUE TITLE
[Scepter of the Shifting Sands QL] The Nightmare's Corruption fragments dropped from mobs should have 100% chance according to WotLK databases.

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4030]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Should have 100% drop chance from mobs

### Expected Blizzlike Behaviour

Should have 100% drop chance from mobs

### Source

https://www.icy-veins.com/wow-classic/quest-line-guide-for-the-scepter-of-the-shifting-sands-mount-and-the-scarab-lord-title

### Steps to reproduce the problem

1. Pick quest https://classic.wowhead.com/quest=8735
2. Kill mobs for quest
3. See that they don't drop it with 100% but less

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Dropped for me with the quest:

![image](https://user-images.githubusercontent.com/100873791/188280492-036f5e66-ea56-46a3-9f98-cf51709e86e7.png)

And the DB has it set to 100%:

![image](https://user-images.githubusercontent.com/100873791/188280515-0dee1185-69b5-48eb-bafd-fbbab98a7878.png)

Do you have any more details that might help? Faction, class, race, anything helps.

**Comment by EdyGlockenspiel** [comment]
But this is wrath, so it should be 100%. https://www.wowhead.com/wotlk/quest=8735/the-nightmares-corruption top comment here stats that fact.
