### ISSUE TITLE
[Scepter of the Shifting Sands QL] The Nightmare's Corruption - Jademir Boughguard knockback infinite range

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4043]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

This mobs https://wowgaming.altervista.org/aowow/?npc=5320 are cleaving every raid member with infinite range, and you cannot basically tank them normally. They knocked our tank for 10000 yd away while he wasnt even near them. I took screenshots while I BLINDED and even HIBERNATED them and they still kept knocking my rogue away while I was tons of yds away from them.
![WoWScrnShot_090722_165844](https://user-images.githubusercontent.com/80590226/188911882-9ca53a3b-89fa-454e-ace3-a1ed7540e24c.jpg)
![WoWScrnShot_090722_165911](https://user-images.githubusercontent.com/80590226/188911894-35ae9cbb-784f-4cd3-9a60-bbbe5af36010.jpg)
![WoWScrnShot_090722_165904](https://user-images.githubusercontent.com/80590226/188911899-74a60942-0bbc-4d63-8ad2-01b141216677.jpg)
![WoWScrnShot_090722_165858](https://user-images.githubusercontent.com/80590226/188911904-ca619a59-4dc2-41fa-abf8-3a8a3146a276.jpg)
![WoWScrnShot_090722_165851](https://user-images.githubusercontent.com/80590226/188911911-e788fda2-4283-4ea2-a6db-903091df358c.jpg)

### Expected Blizzlike Behaviour

Normal cleave and knockback but not knockback with range that you cannot even attack the mob.

### Source

https://wowgaming.altervista.org/aowow/?spell=20666#see-also

### Steps to reproduce the problem

1. Go to Jademir Lake in Feralas
2. Pull Boughguard and check his attack cleave knockback range

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by anhility** [comment]
Same issue with Emeraldon Boughguard (Ashenvale). Flying all over the place.
https://wowgaming.altervista.org/aowow/?npc=12474

The Boughguards in Hinterlands works as intended though, just a normal cleave without flying 30-40 yards back.
