### ISSUE TITLE
[Minor] Un'goro's Crystal Pylons' dialogue bubble

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#4045]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

_Branched from https://github.com/chromiecraft/chromiecraft/issues/3997_

___

Clicking on the bubble in any of the three pylons in the following quest after [Crystals of Power](https://wowgaming.altervista.org/aowow/?quest=4284) gives only a quest credit, but does not close the NPC window

https://www.youtube.com/watch?v=lK5gk5hgaZ8

### Expected Blizzlike Behaviour

I'm uncertain whether it should JUST end, or there should be a follow up, but *at least* it should've close the window

(Blizzard was lazy with its cashgrab and it doesn't even have gossip, meanwhile the only other source of pylons are from cataclysm and probably have a different script)

### Source

Cataclysm source (for a brief second there is an advancement in dialogue):
https://youtu.be/IURD28cIqN0?t=109

_The chat dialogue issue is far too generic issue related to far too often skipped feature to find any reliable one_

### Steps to reproduce the problem

1. Do the mentioned quest and follow the steps in the video.

### Extra Notes

Pylons:
North: **17598** (Entry: **164955**)
West: **17599** (Entry: **164956**)
East: **17600** (Entry: **164957**)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by The-GhostRider** [comment]
- Video Test: [[Fix-Report] - Un'goro's Crystal Pylons](https://youtu.be/OULpkAXSs1Q)

<img src="https://github.com/chromiecraft/chromiecraft/assets/1884642/ec362c64-7d6c-4139-9c81-34d5903cad10" width="300">
