### ISSUE TITLE
BRD upper city RDF ports to start of BRD

### ISSUE THREAD

**Issue by BeefSteaker** [chromiecraft/chromiecraft#4054]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

50-59

### Current Behaviour

when porting into BRD upper city via RDF, you instead get ported the the very start of BRD

https://user-images.githubusercontent.com/11332559/189370013-67985b73-d941-4764-9e02-c14661278f04.mp4

### Expected Blizzlike Behaviour

RDF should port you to just past grim guzzler for this dungeon

### Source

how it used to work on chromie

### Steps to reproduce the problem

queue brd upper city via RDF
accept invite to dungeon

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/97ec08dc36394b2bc23f26f484ef0a60f81f6c7e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Valarious1** [comment]
Same thing happened to me the 2 seperate times I queued for Upper City yesterday

**Comment by heyitsbench** [comment]
Possibly related to https://github.com/azerothcore/azerothcore-wotlk/pull/12763?

**Comment by Santaria94** [comment]
On 3.3.5, the Prison and the Upper city had the same starting point. This is blizzlike behavior. Perhaps it has been fixed? Although I agree that the teleport to the Grim Guzzler looks more logical and convenient

https://www.wowhead.com/wotlk/blackrock-depths#comments
>By 136348 on 2010/03/08 (Patch 3.3.2)		
If you are in the mid-50's level range, it is likely that your random dungeon will be the Upper City section of BRD. If this is the case, and you go ahead and clear the prison block (killing High Interrogator Gerstahn) first, you will not get your sack of spoils for completing the dungeon, no matter if you kill all the bosses of the entire BRD instance.
I am to understand this is a bug in-and-of itself, but I found this post that was helpful.
So it appears that if you end up getting Upper City for you random, and you do not have a party member with the shadowforge key, or a rogue with at least 250 lockpicking skill / blacksmithing keys / seaforium charges, then it appears that you can not complete the random dungeon requirements, as you will not even be able to reach Emperor Thaurissan
So for the random requirements, if you are high 40's low 50's and que'd for the Prison, you need to only kill High Interrogator Gerstahn. Mid-50's players qued for Upper City need to kill Emperor Thaurissan.

**Comment by heyitsbench** [comment]
According to [this Wowhead comment](https://www.wowhead.com/wotlk/blackrock-depths#comments:id=1049907), blizzlike behavior is not getting the satchel if you kill Gerstahn. According to other Wowhead comments, the blizzlike spawn is the same for both the prison block and upper city as Santaria94 said. Don't know if this would be considered a "blizzlike bug" or conscious design choice.

**Comment by BeefSteaker** [comment]
So yeah, looks like they weren't split until around 2014. 
I had assumed because that's how it was on chromie up until this point that it was blizzlike
