### ISSUE TITLE
Pet dash does not increase movement speed.

### ISSUE THREAD

**Issue by lambxrt** [chromiecraft/chromiecraft#406]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x ] Horde

##### CONTENT PHASE:

- [ x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Pet's dash ability (https://wowgaming.altervista.org/aowow/?spell=61684) does not increase movement speed by 80%. I can run alongside my pet when it is active, and mobs can outrun him. My pet is a wolf, level 29.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

80% is a considerable speed boost and mobs shouldnt be able to out-run my pet when I am kiting them.

##### STEPS TO REPRODUCE THE PROBLEM:

1. cast pet dash and /petattack at a distance from target
2. run along side pet and you'll see for yourself :)
3. 
4.

##### EXTRA NOTES:

n/a

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Confirmed, it does not happen always, only when the pet is not in combat I see.
The problem is not related to the spell Dash to the PetAI
