### ISSUE TITLE
[NPC] Bolvar Fordragon missing in Stormwind Castle

### ISSUE THREAD

**Issue by SgtRumpsteak** [chromiecraft/chromiecraft#4071]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

On my Nightelf Priest I can't see Bolvar Fordragon next to Varian's Throne.
I delivered the Head of Onyxia but can't get the followup quest now.
Can see him on all other chars,
![WoWScrnShot_091122_134911](https://user-images.githubusercontent.com/88026991/189694771-3a82ae9b-cba5-40e6-9175-dae44233bda3.jpg)
![WoWScrnShot_091122_134926](https://user-images.githubusercontent.com/88026991/189694779-fcc234a7-f197-4414-ad40-3e5fdd94724f.jpg)
![WoWScrnShot_091122_135534](https://user-images.githubusercontent.com/88026991/189694790-56ce0233-5ad4-43b6-adb6-a6395dadb911.jpg)

### Expected Blizzlike Behaviour

He should stay next to Varian and give me the followup quest. Usually attunement would've been required but not on Wrath content or at least not anymore due to the fact that the attunement was scratched as requirement for Onyxia.

### Source

Can't find a source on any site that states the exact behavior he should show.
But also discussed this with CC staff and the agreed that it is actually a bug.
![image](https://user-images.githubusercontent.com/88026991/189693937-da1a2eab-ecf0-433a-8c14-7f45564a0f00.png)

### Steps to reproduce the problem

Get the head of Onyxia, turn it in and check, if Fordragon is there to give you the followup quest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/97ec08dc36394b2bc23f26f484ef0a60f81f6c7e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by gettheboom** [comment]
Had the same bug a few months ago...

**Comment by Nyeriah** [comment]
> Had the same bug a few months ago...

A few months ago the Onyxia quest line was required in order to see the NPCs, it is no longer the case since the attunements were removed from the game with our latest release.

**Comment by Stump876** [comment]
Nye, does that mean this is no longer applicable since it was removed?

**Comment by Nyeriah** [comment]
Correct, we've moved past this progression stage, thanks for the reminder
