### ISSUE TITLE
Some npcs that should not drop loot and/or be skinnable

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#4074]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

These are skinnable:
https://wowgaming.altervista.org/aowow/?npc=14750
https://wowgaming.altervista.org/aowow/?npc=12435
https://wowgaming.altervista.org/aowow/?npc=13020
https://wowgaming.altervista.org/aowow/?npc=12017
https://wowgaming.altervista.org/aowow/?npc=14024
https://wowgaming.altervista.org/aowow/?npc=14023
https://wowgaming.altervista.org/aowow/?npc=14025
https://wowgaming.altervista.org/aowow/?npc=14022

These are lootable:
https://wowgaming.altervista.org/aowow/?npc=12420
https://wowgaming.altervista.org/aowow/?npc=12416
https://wowgaming.altervista.org/aowow/?npc=14456

These are both:
https://wowgaming.altervista.org/aowow/?npc=10161
https://wowgaming.altervista.org/aowow/?npc=14988
https://wowgaming.altervista.org/aowow/?npc=12422

### Expected Blizzlike Behaviour

First block should not be skinnable
Second should not have loot
Third should have neither

### Source

Should not be skinnable
https://www.wowhead.com/wotlk/npc=15220
https://www.wowhead.com/wotlk/npc=14750
https://www.wowhead.com/wotlk/npc=12435
https://www.wowhead.com/wotlk/npc=13020
https://www.wowhead.com/wotlk/npc=12017
https://www.wowhead.com/wotlk/npc=14024
https://www.wowhead.com/wotlk/npc=14023
https://www.wowhead.com/wotlk/npc=14025
https://www.wowhead.com/wotlk/npc=14022
 
 
Should not have loot
https://www.wowhead.com/wotlk/npc=12420
https://www.wowhead.com/wotlk/npc=12416
https://www.wowhead.com/wotlk/npc=14456
 
 
Should not be skinnable or drop loot
https://www.wowhead.com/wotlk/npc=10161
https://www.wowhead.com/wotlk/npc=14988
https://www.wowhead.com/wotlk/npc=12422

### Steps to reproduce the problem

Go to the various creatures, kill them, try to loot/skin them
.go c 15220
.go c 14750
.go c 12435
.go c 13020
.go c 12017
.go c 14024
.go c 14023
.go c 14025
.go c 14022
 
.go c 12420
.go c 12416
.go c 14456
 
.go c 10161
.go c 14988
.go c 12422

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/97ec08dc36394b2bc23f26f484ef0a60f81f6c7e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report! I can confirm.
