### ISSUE TITLE
Baristolth of the Shifting Sands cannot provide you an additional Agent of Nozdormu badge.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#4075]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

If you delete the [Agent of Nozdormu](https://www.wowhead.com/wotlk/item=20402) item after receiving it from [Baristolth of the Shifting Sands](https://www.wowhead.com/wotlk/npc=15180), you will not be able to get another from him.

### Expected Blizzlike Behaviour

After deleting the item, you should be able to talk to Baristolth and he should cast [a spell](https://www.wowhead.com/wotlk/spell=24727) on the player to give them another item.

### Source

[Wowhead comment](https://www.wowhead.com/wotlk/item=20402/agent-of-nozdormu#comments:id=654487).

### Steps to reproduce the problem

1. `.tele cenarionhold`
2. `.quest add 8301`
3. `.quest complete 8301`
4. `.quest reward 8301`
5. Delete the [Agent of Nozdormu](https://www.wowhead.com/wotlk/quest=8301) badge.
6. Talk to [Baristolth of the Shifting Sands](https://www.wowhead.com/wotlk/npc=15180).
7. Observe the issue.

### Extra Notes

Originally reported by Andov#8174 on ChromieCraft Discord.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/97ec08dc36394b2bc23f26f484ef0a60f81f6c7e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
You can abandon and restart the carapace quest to get another
https://user-images.githubusercontent.com/11332559/190999456-8fe00787-9cdb-439b-abe3-4c9b2d17d725.mp4

**Comment by BeefSteaker** [comment]
yeah this probably should be how it works, just wanted it visible that there was a workaround

**Comment by heyitsbench** [comment]
The gossip option [`Baristolth, I have lost my badge and require a replacement.`](https://user-images.githubusercontent.com/38561765/192083204-927dcbce-f1e2-4296-8f06-9e46aba56685.png) only becomes available after completion of the initial [The Path of the Righteous](https://www.wowhead.com/wotlk/quest=8301) quest.

Source: WotLK Classic.
