### ISSUE TITLE
Faction change didn't transfer faction versions of quest Elven Legends required for head/pants enchants

### ISSUE THREAD

**Issue by mcts-cc** [chromiecraft/chromiecraft#4076]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

I've done Horde's version of quest Elven Legends (https://wotlkdb.com/?quest=7481). After faction change, Alliance version of quest is not completed (https://wotlkdb.com/?quest=7482). I cannot  take quest for enchants for example (https://wotlkdb.com/?quest=7484)### 

### Expected Blizzlike Behaviour

These quests should be transfered as completed after faction change. They are required to get enchants quests.

### Source

https://wotlkdb.com/?quest=7484
![obraz](https://user-images.githubusercontent.com/112405137/189772808-9d37af3e-0e35-4868-8f7b-f88c6f274e79.png)

### Steps to reproduce the problem

1. Create horde character
2. take and complete 7481
3. change faction to alliance
4. [Lorekeeper Lydros](https://wotlkdb.com/?npc=14368) do not offer enchant quests

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/97ec08dc36394b2bc23f26f484ef0a60f81f6c7e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @mcts-cc. This is not a valid issue.

There are three types of quests - horde, alliance and cross-faction. Just cross-factions quests stay completed. There is no mapping between horde and alliance quests.

In your case there is a horde and an alliance version of "Elven Legends". So, you have to do the quest again.

> If you do a faction change you have to repeat this quest for the other faction before you are able to turn in librams... 
(source: https://www.wowhead.com/quest=7481/elven-legends#comments:id=640095:reply=167551)

**Comment by mcts-cc** [comment]
@ishidinho Fine, but Librams quests should be available if any of these is completed. I opened as new issue https://github.com/chromiecraft/chromiecraft/issues/4081)
