### ISSUE TITLE
Faction change didn't transfer Molten Core attunement despite of Attunement to the Core is done.

### ISSUE THREAD

**Issue by mcts-cc** [chromiecraft/chromiecraft#4078]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

I've done Horde version of MC attunement. I switched to Alliance and now I'm not MC Attuned anymore, can't transfer to MC using ability of Lothos Riftwaker.

### Expected Blizzlike Behaviour

Completing quest Attunement to the Core should allow to transfer to MC talking to Lothos Riftwaker

### Source

* [Attunement to the Core - Alliance](https://wotlkdb.com/?quest=7848)
* [Attunement to the Core - Horde](https://wotlkdb.com/?quest=7847)

### Steps to reproduce the problem

1. Create Horde character
2. complete 7847
3. check that Lothos Riftwaker can transfer to MC
4. change faction to Alliance
5. Lothos Riftwaker have no option to tranfer to MC anymore

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/97ec08dc36394b2bc23f26f484ef0a60f81f6c7e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment]
Hey @mcts-cc. This is not a valid issue.

There are three types of quests - horde, alliance and cross-faction. Just cross-factions quests stay completed. There is no mapping between horde and alliance quests.

In your case there is a horde and an alliance version of "Attunement to the Core". So, you have to do the quest again.

https://wowgaming.altervista.org/aowow/?search=Attunement+to+the#quests

**Comment by mcts-cc** [comment]
@ishidinho Quests are different, but both quests have the same reward:

> [Completion]
> I am now able to transport you to the Molten Core. Ask and it shall be done.

When player change faction is still completed, right? Issue was that npc doesn't have option to transfer to Molten Core.

**Comment by mcts-cc** [comment]
Exact reward is [spell casted on character](https://wowgaming.altervista.org/aowow/?spell=22877)
![obraz](https://user-images.githubusercontent.com/112405137/190354746-194a09af-96fb-4c13-969d-8fcab7f70225.png)
