### ISSUE TITLE
quest: Quell the Uprising - wrong Location tracker

### ISSUE THREAD

**Issue by Rittmeister39** [chromiecraft/chromiecraft#408]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

the location tracker points to the Harbor, but afaik it should point to the Keep in Stormwind where the Stockade Prison is. I dont know 4 sure cause I never played original WoW, but makes sense. No big deal anyway...

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Rittmeister39** [comment]
![WoWScrnShot_041121_185555](https://user-images.githubusercontent.com/78271326/114313908-d3264680-9af8-11eb-9b14-5fd1cd9126e7.jpg)

**Comment by mdawx** [comment]
Where should it points to? (1), (2) or somewhere else?

![image](https://user-images.githubusercontent.com/81375770/114321388-e2b68700-9b1a-11eb-8caf-7cf27dc79b88.png)

**Comment by Rittmeister39** [comment]
![aaaaaaaaa](https://user-images.githubusercontent.com/78271326/114329553-ef010b00-9b3f-11eb-9ec6-26be3329b1c3.png)
how about the Keep, where the Stockade actually is? I have no idea what is Blizzlike tho. maybe they point to the harbor .

**Comment by mdawx** [comment]
I'm going to check other dungeon quests.

**Comment by mdawx** [comment]
Location tracker for quest "Quell The Uprising" (id 387) should point to dungeon entrance, just like quest "The Color of Blood" (id 388).

![image](https://user-images.githubusercontent.com/81375770/114447168-61223000-9bd2-11eb-9967-824b29819374.png)
