### ISSUE TITLE
Librams quests are not available when player finishes Elven Legends for different faction

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#4081]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Librams quests:
* Libram of Focus
* Libram of Protection
* Libram of Rapidity

are not available when player finishes Elven Legends for different faction.

### Expected Blizzlike Behaviour

If player completes one of the following quests:
* https://wotlkdb.com/?quest=7481
* https://wotlkdb.com/?quest=7482

Libram of Focus, Libram of Protection, Libram of Rapidit should be available

### Source

* https://wotlkdb.com/?quest=7483
* https://wotlkdb.com/?quest=7484
* https://wotlkdb.com/?quest=7485

![obraz](https://user-images.githubusercontent.com/112405137/190342383-89173df9-0d5e-49ae-b13a-1912d03567f7.png)

### Steps to reproduce the problem

* Create horde character
* take and complete 7481
* change faction to alliance
* [Lorekeeper Lydros](https://wotlkdb.com/?npc=14368) do not offer Libram quests

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi ghost. this is working as intended. the "any one of these" statement just means that it doesnt matter which factions quest you complete to gain access to the cross faction quest. without that the libram quests would need to be duplicated

you can re gain access to the libram quests by completing the elven legends quest again for your new faction
