### ISSUE TITLE
Ahn'Qiraj War Effort Supplies have a large chance of not wielding any loot whatsoever.

### ISSUE THREAD

**Issue by Blackpeixera** [chromiecraft/chromiecraft#4084]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

The War Effort supply boxes several times come without any loot whatsoever. The box either stays there empty or if you have autoloot on, they simply disappear.

### Expected Blizzlike Behaviour

The expected behaviour as i gathered from WoWhead Classic links is that the boxes should wield all sorts of greens, and sometimes even scrolls. They also have a low chance for blues and maybe purples.

------------------------

> "Subject: "World event reward"
You get this box with some random BOE greens, and scrolls.
and a recognition signet. : https://classic.wowhead.com/item=52384 for alliance.

The box comes as lvl 10-20-30-40-50 Item level. probably 60 as well.
This quest item will only be available during the AQ world event gathering."

-----------------------

They also scale with the item being turned on:

>"From ThottbotBy justread [on 2005/12/28](https://classic.wowhead.com/item=21509/ahnqiraj-war-effort-supplies#comments:id=2676373) (Patch 1.8.4)		
Subject: "Scales with items turned in"
After turning materials in on 3 different toons, it certainly appears that though the boxes are named identically, the contents of the boxes are proportional to the level of the goods you turned in.

For instance, from turning in copper bars you'll get something along the lines of a first tier scroll and a level 9-12 green.  For turning in thorium bars, you'll get one or two 3rd or 4th tier scrolls along with a level 50-52 green.  Same goes for linen vs. runecloth, etc.

As far as exchanging tokes for boxes, turn-ins of 30 tokens has always resulted in a box much like the "high-end" material turn in; ie. on par with the thorium/runecloth turn in."

### Source

https://classic.wowhead.com/item=21509/ahnqiraj-war-effort-supplies#comments

### Steps to reproduce the problem

You simply open the boxes.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thank you for the report! I can confirm the issue.
