### ISSUE TITLE
Duskwood - Skeletal Horror fear spam bug 

### ISSUE THREAD

**Issue by hnkowned4** [chromiecraft/chromiecraft#4086]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

20-29

### Current Behaviour

In Duskwood, next to Darkshire there are these Skeletal Horror mobs who uses a Terror or Fear ability... Well, they spam it, they fear you into other mobs and then its just nonstop fears until you end up dead. Pretty sad not enjoyable. ( constant 3 second fears )

Please fix this issue if possible. Thank you for taking the time reading this report. 

Kind regards,
Loathe (ingame name)

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=63FZAZBSboU&ab_channel=LuisRodriguez
Not sure to be fair but in this video for example they not even fearing. Once I got feared and 2 mobs on me, literally you cannot escape because almost non stop fears going on sadly.

### Source

My own feedback on the mobs, I am a warrior and it's unplayable. :/

### Steps to reproduce the problem

Skeletal Horror - Near Darkshire
Pull in 2-3 mobs and you will see you will get constantly feared. 
Either remove the mobs spell or reduce the effect so you're not feared for 3 seconds / cast

### Extra Notes

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, hnkowned, thanks for the report.

The aim for chromiecraft is to be as close to how Wotlk was back in the day. These mobs behavior seems to be accurate to that.
In my testing, the fear mechanic seems to be working at the intended frequency.

Fear and flee mechanics can be annoying, i would advise pulling mobs away to a safe distance and killing one at a time when possible.

**Comment by hnkowned4** [comment]
Hello there,

Thank you for your help, I thought it’s a bug - just wanted to help.

Have a lovely weekend
