### ISSUE TITLE
[Quest] Paladin Quest line "The Tome of Divinity" bugged if quest item "Symbol of Life" is destroyed.

### ISSUE THREAD

**Issue by Prixms** [chromiecraft/chromiecraft#409]
Paladin Quest line "The Tome of Divinity" bugged if quest item "Symbol of Life" is destroyed.

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

During the Paladin Quest "The Tome of Divinity", grabbed from "Gazin Tenorm", if you destroy the quest item "Symbol of Life", it is impossible to get another one, resulting in the inability to finish the quest for Resurrection skill. I have tried clearing cache, resetting the quest, re logging, and none have replaced the missing item.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://classic.wowhead.com/quest=1790/the-symbol-of-life   As stated here, the quest giver should be give you another "Symbol of life" if the first fails or is destroyed. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just accept the quest "The tome of divinity" and destroy the quest item "Symbol of Life" and then you are unable to complete the quest, and unable to retrieve another, even after re accepting the quest. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
As you can see on my video, I can't reproduce it on my environment.

https://youtu.be/jvPp-VflaNI
