### ISSUE TITLE
Fireworks at Saltheril's Haven

### ISSUE THREAD

**Issue by Cosmic-Lattee** [chromiecraft/chromiecraft#41]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### SMALL DESCRIPTION:
Firework launchers aren't launching fireworks at Saltheril's Haven.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They are supposed to be launching fireworks seemingly at random intervals. This first video is likely from a private server ([Link](https://www.youtube.com/watch?v=FDB7cxRS-no)) but this video ([Link](https://www.youtube.com/watch?v=xnEq6Y5N4eM&t=1s)) from 2010 shows the fireworks going off in the background and seems to be from live wow. 

##### CURRENT BEHAVIOUR:
Currently the firework launchers do nothing.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to Saltheril's Haven and see the fireworks not launch.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Fixed
-
**Video Test:** [Fireworks at Saltheril's Haven](https://youtu.be/9cxXAPc_7W8)
