### ISSUE TITLE
[AQ40] Viscidus Shatter

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4101]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

60

### Current Behaviour

Currently when you shatter Viscidus, the globs that spawn do not rush back to the center, and instead move very slow towards players. They also do not form a "figure 8" formation at the end.

Viscidus is also not present in the middle of the room at his "weakened state". 

_I can't seem to upload a webm or mp4 currently, as I think github is having issues. Will try in comments after report is made._

### Expected Blizzlike Behaviour

When Viscidus shatters, he sends out 1-20 globs (each based on 5% of remaining hp) that all run to center of map trying to reform his body. They are also moving at a quickened pace, and end in a formation of a "figure 8". The boss is also supposed to be present while they are running to "reform" his body. It marks the center of the blob run essetnially.

### Source

https://youtu.be/RbveUsRfeLM?t=49
I can't find a solo level 80 or raid done during 3.3.5, but here is a classic video that illustrates how the boss works after a shatter. Notice that Viscidus is present in the middle of the blob formation, the blobs run back to Viscidus (do not follow or attack players at all), and as they run back they start forming and ending in a "figure 8" formation. 

https://youtu.be/YPl6d5eraW8?t=288
Here is another overhead representation of how the globs are suppose to explode outwards, and when they move back towards boss in center, reform in a "figure 8". 

### Steps to reproduce the problem

1. Enter AQ40 at perform 200 frost attacks on Viscidus
2. Perform an additional 75 physical attacks to shatter him
3. Watch as globs shoot out, but run very slow and try to attack player(s)

### Extra Notes

I'm not sure if it's possible to 100% recreate how it really works, with emulation limitations perhaps. At most I would say a generally accepted fix would to be of the following : 

1. Do not allow blobs to follow or attack players
2. Increase blob return speed
3. Have Viscidus present in middle of room (to show where blobs are running to)

I don't think the figure 8 thing can be achieved really, but if it can, that'd be awesome.  

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
[working_as_intended.webm](https://user-images.githubusercontent.com/62584589/191370162-d0cf22d1-a935-41ea-80dc-b1a8ebcedab5.webm)
This is how it is currently performing, which is quite wrong.

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12956

**Comment by Cooties-cc** [comment]
![smiling-face-with-smiling-eyes-and-three-hearts_1f970](https://user-images.githubusercontent.com/62584589/191393123-74f249fa-aa6a-4a11-be38-4b9232df3440.png)

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12956
