### ISSUE TITLE
[Brewfest] There are no "There and back again!" daily quest

### ISSUE THREAD

**Issue by ozgurkuren** [chromiecraft/chromiecraft#4102]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

There is no "there and back again!" repeatable quest given by the npc.

### Expected Blizzlike Behaviour

The "there and back again!" quest from the npc [Neill Ramstein] should be repeatable daily.

### Source

https://www.wowhead.com/wotlk/guides/brewfest-event-achievements#repeatable-quests

### Steps to reproduce the problem

1. Go to brewfest zone outside IF.
2. Talk to the [Neill Ramstein].
3. If you have done the quest previously, he should give you a repeatable quest making you do the same thing again as the original quest.
4.  Observe that he does not give a quest.

### Extra Notes

https://www.wowhead.com/wotlk/quest=11122/there-and-back-again
![neil rammstein](https://user-images.githubusercontent.com/114054530/191436269-883acfc8-eea0-4706-976e-ba52b9c7770b.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by KiritoXvXKillMeNow** [comment]
I would like to state that the horde are having the same problem. I was thinking that it should have been available yesterday, but figured my memory was faulty. Turns out my memory wasn't faulty.

**Comment by hofik19** [comment]
Can confirm that Horde have the same problem, "Ram Master Ray" NPC does not give repeatable quest

**Comment by cachocarne** [comment]
I've been doing this quest daily on my characters. However, today (Oct 2nd 2023) I am not able to do it again. NPC Neill Ramstein doesn't offer the option to do it anymore, at least on one of my toons.
