### ISSUE TITLE
[Brewfest] Conjured Complimentary Brewfest Sampler item does not remove aura on logout

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#4103]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

Click complimentary mugs on tables, npc throws you a mug back, it's conjured, if you log out after getting it, the aura is not removed from the player despite the item being deleted from inventory with the conjured item removal, which causes the mug to stay on the player visually as an aura

### Expected Blizzlike Behaviour

Aura removed when conjured item disappears even if player is offline

### Source

![brewfest_stein_bug_thingy](https://user-images.githubusercontent.com/113958411/191455121-da0ff68d-4902-4562-bec3-365b4e715137.png)
![brewfest_stein_bug_thingy2](https://user-images.githubusercontent.com/113958411/191455129-a44401fb-b7df-4563-b2fc-9a40884c1c84.png)

### Steps to reproduce the problem

.go xyz -5178.089355 -617.030334 397.176849 0 2.189320
Click a Complimentary Brewfest Sampler
Logout for 15m for the item to expire on its conjured timeout.
Log back in, aura will be on without the item in inventory 

### Extra Notes

Aura was removed on the player in the screenshot by having them go back to a brewfest stein and clicking on it then deleting the item from inventory.

(Thanks Honey on discord for telling me how to list auras on the PTR)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft
+ ChromieCraft PTR

**Comment by The-GhostRider** [comment]
### I can confirm the Bug, as my video shows:
[![Anteprima](https://user-images.githubusercontent.com/1884642/260227734-e8252682-22e8-4121-bdd2-34c355f044ed.png)](https://www.youtube.com/embed/CsrdXFsePbE)
