### ISSUE TITLE
Quest : Badlands Reagent Run (Alliance)

### ISSUE THREAD

**Issue by Narvet** [chromiecraft/chromiecraft#4114]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

30-39

### Current Behaviour

Buzzard Gizzard (https://wowgaming.altervista.org/aowow/?item=7847) doesn't drop after relog

After the relog, I did a first run where I killed all of them in the badlands, thought I was unlucky, so did a second run, but none dropped
Also, went to the quest turn in NPC (https://wowgaming.altervista.org/aowow/?npc=1470), and he would indicate that the quest is done even without all the buzzard gizzard (also had the question mark on the minimap that confirms that), but the quest can't be turned in

Finally deleted the items, and even without logging off / back in they dropped again

### Expected Blizzlike Behaviour

The items should drop

### Source

wut ?

### Steps to reproduce the problem

1. Pick up the quest and get some Buzzard Gizzard (I had 3)
2. log off, log back in
3. Kill any buzzard (https://wowgaming.altervista.org/aowow/?npc=2830, https://wowgaming.altervista.org/aowow/?npc=2831, https://wowgaming.altervista.org/aowow/?npc=2829) and see for yourself

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/23f432c6b502c55c2e32749cd2b607d3eb752366

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi Narvet, i was unable to reproduce this on both live and ptr. prehaps it was a visial bug (you actually had all 5 but they werent shown)
