### ISSUE TITLE
[Shaman] Totems threat are to the totem itself instead of the shaman

### ISSUE THREAD

**Issue by Selhkna-ChromieCraft** [chromiecraft/chromiecraft#4117]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

Totems have individual threat like healing steam totem. When they pulse and aoe heal they have a large amount of threat, and usually pull mobs off a tank and die before mobs being pulled by the tank go and begin attacking group members at random. 

### Expected Blizzlike Behaviour

I think the only time a totem would be attacked on retail was if it was in the path of a NPC and wasn't pulsing a heal or taunt, otherwise the shaman who casted the totems was receiving it's threat when it did pulse. Stoneclaw totem had it's own threat, too. Also some spells like Fire Nova caused threat to go the shaman, and not the fire totem (This works as it should on CC).

### Source

https://www.mmo-champion.com/threads/688657-Totem-threat

### Steps to reproduce the problem

Have a tank pull stuff
Anything the tank doesn't have threat on will be removed by a healing stream totem
The totem will be targeted by the pulled NPC

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/23f432c6b502c55c2e32749cd2b607d3eb752366

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, Selhkna
i believe totems getting aggro is the intended behavior. anyone who played shaman in TBC will remember how much of a pain Fire nova totem was before it became a spell in wrath. Even the source you linked has people arguing both sides.

shamans have always had to be careful during pulls, thankfully in wrath we have Totemic Recall
