### ISSUE TITLE
Immolate damage bugged

### ISSUE THREAD

**Issue by caloides** [chromiecraft/chromiecraft#4118]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

Immolate damage is very low as of 23.09.2022. This was tested both on a warlock with the glyph of immolate and also without.
Also tested in both battlegrounds and also out on a target dummy.

### Expected Blizzlike Behaviour

It should be doing more damage but I don't know exactly how much. Usually it's one of my top 3 damaging abilities, now it's on par with corruption.

### Source

Past experience from playing with the spell both in pvp and pve with a destruction spec.

### Steps to reproduce the problem

Have a warlock cast immolate to a target dummy, damage will be lower than normal.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/23f432c6b502c55c2e32749cd2b607d3eb752366

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, thanks for the report!
Could you tell me the rank of the Immolate spell?

**Comment by Gultask** [comment]
Nevermind. I see the issue and compared it to WotLK Classic. The DoT is not scaling with SP. I'll link the report soon, thanks again!

**Comment by caloides** [comment]
Many thanks! It's rank 8

**Comment by caloides** [comment]
From what I can see this fix is only addressing the dot effect, but the immolate spell itself is doing lower damage than expected I think

**Comment by Gultask** [comment]
The initial damage is the same as WotLK Classic from what I can see. If anything I'd say that the fact it was higher before was a bug that has now been fixed. This was the case with several other spells which now should be more blizzlike.
But don't get me wrong, I get you. A "nerf" is never a good feeling.
