### ISSUE TITLE
Shred 

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#4119]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Shred https://wowgaming.altervista.org/aowow/?spell=5221 is currently being dodged in pvp  

https://cdn.discordapp.com/attachments/801844176416276500/1022894395114143784/WoWScrnShot_092322_113614.jpg

### Expected Blizzlike Behaviour

Players in pvp cannot dodge or parry from behind and since shred can only be used from behind you cannot dodge shred

### Source

In game tips state players cannot dodge or parry attacks from behind and pvp has always been like that

### Steps to reproduce the problem

Make a druid/rogue
duel someone
use shred/backstab
has a chance to be dodged

### Extra Notes

This happend in a bg so it could only be bg specific, still a bug but may be related to bg changes
since shred and backstab work the same way i would guess that if one is bugged both are

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/23f432c6b502c55c2e32749cd2b607d3eb752366

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Lemonadez** [comment]
This is where you are wrong.
Shred does not have Flags - [Cannot be dodged, parried or blocked] and Even in Retail, Shred can be dodge :)

**Comment by Never6** [comment]
not against players it cant

**Comment by Never6** [comment]
> This is where you are wrong. Shred does not have Flags - [Cannot be dodged, parried or blocked] and Even in Retail, Shred can be dodge :)

in pvp players cannot dodge block or parry from behind. and pvp has always been like this
im not talking about pve.

**Comment by Lemonadez** [comment]
> 

You can always dodge from behind but you should not be able to parry. Did you really play Retail?

**Comment by Never6** [comment]
> > 
> 
> You can always dodge from behind but you should not be able to parry. Did you really play Retail? Maybe because I play Rogue and Prot War on retail. But I can Dodge Shred in PVP from behind.

ok ill bite

idk what benefit you get from lying on this situation but you are just clearly wrong. Whatever bugs classic wow has doesnt apply to how 3.3.5 or any expansion is supposed to work. But don't just take my word for it https://us.forums.blizzard.com/en/wow/t/players-still-dodge-and-parry-attacks-from-behind-and-while-mounted/618309/4

https://www.wowhead.com/forums/topic/do-i-need-expertise-for-pvp-186018

The fact that you are talking out of your ass on this is really strange. It took no time at all to look up these sources. If players can dodge from behind then why do rogues step kidney. Why does shred go through evasion then. If players could dodge from behind that would make evasion super strong. You are either a really good troll or just an idiot who doesnt understand basic knowledge about the game. 
Im done talking about this. If you truly believe that its not a bug give me a reputable source that players are dodging from behind and give me the patchnotes where they changed that. Otherwise dont even bother

**Comment by Mikel0ke** [comment]
mez madge

**Comment by Gultask** [comment]
Let's keep things civil, please.

As for the report. I can't reproduce. It could be a passing bug that could exist only in the current revision of Chromiecraft, and if so, it'll go away next update. Otherwise it's something else we're missing to reproduce.

![image](https://user-images.githubusercontent.com/100873791/192170243-2be41e8e-c711-4821-829a-0ffec234fa98.png)

**Comment by Never6** [comment]
> Let's keep things civil, please.
> 
> As for the report. I can't reproduce. It could be a passing bug that could exist only in the current revision of Chromiecraft, and if so, it'll go away next update. Otherwise it's something else we're missing to reproduce.
> 
> ![image](https://user-images.githubusercontent.com/100873791/192170243-2be41e8e-c711-4821-829a-0ffec234fa98.png)
> 
> I tested using Evasion rank 2 on the target at all times.

just did another bg and had shred dodged again try testing vs a hunter with deterrence that might be the issue

**Comment by heyitsbench** [comment]
Related to https://github.com/azerothcore/azerothcore-wotlk/issues/11459 and https://github.com/chromiecraft/chromiecraft/issues/2646 in that case 😛

**Comment by BeefSteaker** [comment]
Deterrence lets you dodge from behind, could it be that?
![image](https://user-images.githubusercontent.com/11332559/193466363-5ecf6b1c-3318-4a4a-aa31-e59035515563.png)
https://wowpedia.fandom.com/wiki/Deterrence

**Comment by Gultask** [comment]
Shred bypasses Deterrence, as does some other spells.

**Comment by Gultask** [comment]
I was able to reproduce it :P 
![image](https://user-images.githubusercontent.com/100873791/193466536-fd563695-6878-49a8-a309-8bcc16e3c313.png)

Thanks for the follow-up. I'll investigate it further

**Comment by Mikel0ke** [comment]
fix mezzo spec 
![imagen](https://user-images.githubusercontent.com/83586527/198679636-65cd00f2-1e29-403e-94e0-2d698d80bb1f.png)
