### ISSUE TITLE
[RDF] Level 60 are getting into Blackrock Depths - Prison queue 

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4122]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Level 60 are somehow getting into Blackrock Depths - Prison queue (47-57), happened twice today. After killing first and last boss in that queue, yo udon't get dungeon reward nor satchel. Not sure how they're grouped with us nor why no reward.
![WoWScrnShot_092322_100646](https://user-images.githubusercontent.com/80590226/192040698-dbb9b489-df18-4b51-9409-7a9174330cfb.jpg)
![WoWScrnShot_092322_210411](https://user-images.githubusercontent.com/80590226/192040702-3b871ac9-0165-4731-8801-ee1a70aed06f.jpg)

### Expected Blizzlike Behaviour

Not sure how they're grouped with us nor why no reward. Lvl 60 shouldn't be able to queue with us nor get it via RDF

### Source

-

### Steps to reproduce the problem

1. Be from lvl 47 to 57
2. Queue RDF and get PRISON with lvl 60 people :O.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/23f432c6b502c55c2e32749cd2b607d3eb752366

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey Elexias, are you sure it's not BRD - Upper City?

Starting at the same location as BRD - Prison is blizzlike, although to be frank I don't know what caused that change in Chromiecraft.

>When you start Upper City, the only way to tell it isn't Lower City is by being high enough level or by killing the interrogator (if she doesn't give the satchel, it is Upper city). Also no one in my group had the key, **you start at the same place for both**, ([source](https://www.mmo-champion.com/threads/688600-Blackrock-Depths-Upper-City?p=7170209&viewfull=1#post7170209))

**Comment by Elexias** [comment]
@Gultask Isnt starting location for Upper City past that Brewfest boss and has been on CC and on WotLK for all time?

**Comment by Gultask** [comment]
For CC yes, but it was changed recently.

In WotLK, some sources like the one I posted above say that Upper City has the same starting location as Prison.

**Comment by Elexias** [comment]
@Gultask If you have real source of WotLK can be, I kinda forgot, had been long time since real wotlk was on. If it was like that or is it like that nowdays on retail wotlk then I agree with you 🗡️

**Comment by Gultask** [comment]
It is unfortunate, I agree :C
