### ISSUE TITLE
[War Efforts] Wrong display of goods

### ISSUE THREAD

**Issue by Frodhi** [chromiecraft/chromiecraft#4125]
When you talk to the war marshal he displays the wrong amount of rainbow fishes.
I assume it displays the stacks instead of the actual amount of fish

**Comment by BeefSteaker** [comment]
hi frodhi, it appears to be correct on my end. can you clarify the issue?
![image](https://user-images.githubusercontent.com/11332559/192152241-44f9292d-2eeb-4671-a882-0f0e7b8da72c.png)
![image](https://user-images.githubusercontent.com/11332559/192152262-78d2d716-c4fc-423a-8bdc-18bb90d9f27e.png)
