### ISSUE TITLE
2min insignia change for more balanced pvp

### ISSUE THREAD

**Issue by Chobungus** [chromiecraft/chromiecraft#4126]
### Discussed in https://github.com/chromiecraft/chromiecraft/discussions/3523

<div type='discussions-op-text'>

<sup>Originally posted by **Vitusin** May 20, 2022</sup>
There is one thing that is not talked about much and that is the imbalance in insignia 5min for nonhumans VS human racial 2min. I think the time difference speaks for itself. I'd love it if pvp active players would speak up and give their opinion here.  I'm obviously up for a 2min change. Thanks everyone for the replies.</div>

**Comment by caloides** [comment]
This was also purposed by Victus in the past and the vast majority (albeit all playing human characters) were against it!
I think 2 min insignia would be a good change for pvp and would help in dealing with some of the imbalance right now in the form of stuns.

**Comment by BeefSteaker** [comment]
Hi, thanks for the report but this is not a bug.
You should use the original discussion or use the suggestion section
