### ISSUE TITLE
[Warrior] - Execute Dodges Don't Proc Overpower

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4129]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

60

### Current Behaviour

Currently, when Execute is dodged, it does not activate Overpower. 

https://user-images.githubusercontent.com/62584589/192122516-ea1b583f-eed3-4e48-9d6b-3b18a0ec1414.mp4

### Expected Blizzlike Behaviour

Any attack made by the warrior that is dodged will activate Overpower. 

### Source

https://wowgaming.altervista.org/aowow/?spell=7384

**_Only useable after the target dodges._**

### Steps to reproduce the problem

1. Spec into sudden death, or fight a low HP mob
2. Cast Execute until it is dodged
3. Overpower will not activate

### Extra Notes

There are also claims that Victory Rush dodges are not procing Overpower either. This was a bit harder to test, and I hadn't done any self testing to get solid proof. If others could post/research it, could add to this ticket or make a new one. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, ive been unable to replicate this one. do you have the combat log for this?

that looks like MSBT, so theres a chance it incorrectly read a miss or otherwise as a dodge

**Comment by Cooties-cc** [comment]
MSBT doesn't give errors, as it's data is directly taken from combat logs. The only thing it does differently is that there is a slight delay to broadcasting the logs. I've used other videos from wotlk retail showing MSBT data to fix bugs and it's been accepted.


https://user-images.githubusercontent.com/62584589/195661143-ad2b7d4e-b521-4c5e-89d0-d6ac743c1cee.mp4


 
Here's another video taken showing the logs as well, and you can see, MSBT has a delay to the combat log data, but both still read the Execute dodge not activating Overpower.

**Comment by Cooties-cc** [comment]
Has there been any updated review on this matter? I've provided what I think is sufficient proof that overpower is not activating on a dodge from execute. This is a moderate issue to the arms tree since it's affecting the primary spells the spec uses. This is a negative impact on how well the class performs, and will continue to be an issue into the end of the games content in both pve and pvp.

**Comment by Cooties-cc** [comment]
![image](https://user-images.githubusercontent.com/62584589/208288845-451b85bd-c12d-4957-9f25-5fb6627bce10.png)

Core mechanic of a class still not addressed. 
Pls send help.
I beg you.

**Comment by Pyromanihack** [comment]
I tried for a while, but I can't be able to reproduce it: every time Execute was dodged, it instantly activate Overpower
(https://user-images.githubusercontent.com/82369562/209695717-1d8a3852-6071-4491-8bf0-3d4ae376b748.webm)


![combat log](https://user-images.githubusercontent.com/82369562/209695744-c7214a64-8ec6-4417-bcdc-a7be9c4c6abe.png)
