### ISSUE TITLE
Ironfoe gives 3 extra swings not 2

### ISSUE THREAD

**Issue by Mikel0ke** [chromiecraft/chromiecraft#4130]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Ironfoe gives 3 extra swings instead of 2.

### Expected Blizzlike Behaviour

It should give 2 extra swings.

### Source

![WoWScrnShot_092522_145150](https://user-images.githubusercontent.com/83586527/192144549-14bd9a49-5bec-4ecf-9177-abdfacb28683.jpg)

![screenshot](https://user-images.githubusercontent.com/83586527/192144672-cc156c44-15af-42f9-95d1-3b5769371a37.jpg)

### Steps to reproduce the problem

equip ironfoe and swing until you get the extra swings.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Dont seem to be able to replicate on PTR. are you sure that the 3rd extra attack wasnt a subsequent autoattack?
![image](https://user-images.githubusercontent.com/11332559/192148172-b82d159e-1178-4144-b349-a91ac37d980e.png)

**Comment by Mikel0ke** [comment]
Thats why i sent details screenshot all 4 autos hit at 2.2s its impossible to be a normal hit.

**Comment by bojan112** [comment]
hand of justice trinket can proc extra attacks

**Comment by Mikel0ke** [comment]
it would show up on combat log

**Comment by BeefSteaker** [comment]
yeah it shows up on combat log so couldnt be that 
![image](https://user-images.githubusercontent.com/11332559/192161787-d70eda54-2c28-4b36-a700-fd6dbf224c0f.png)

**Comment by The-GhostRider** [comment]
Hi @Mikel0ke, as clearly demonstrated by my Video, the Bug is not reproducible because it doesn't exist.
**Video Test:** [Ironfoe NOT gives 3 extra swings](https://youtu.be/NtAwUshnBQs)


For this reason I close the Report.

**Comment by The-GhostRider** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/c0475f73-d43f-41ef-a4ed-0c0920b83291)
