### ISSUE TITLE
Conflagrate delay after casting Immolate

### ISSUE THREAD

**Issue by Icebeam666** [chromiecraft/chromiecraft#4136]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

After casting immolate, there is a delay before you can cast conflagrate
Here is video
https://www.youtube.com/watch?v=Tj1wUk2UGu8&ab_channel=latampunisher

### Expected Blizzlike Behaviour

You should be able to cast conflagrate instantly after immolate

### Source

WOTLK Classic
https://www.youtube.com/watch?v=RfNnD7c2DYI&ab_channel=latampunisher

### Steps to reproduce the problem

Cast Immolate
Cast Conflagrate

### Extra Notes

This bug is a noticeable dps loss for destro in pve and a big deal in pvp because priest/pala can ALWAYS dispell immolate before you have the chance to cast conflagrate

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, while seemingly not how it works in classic, this is indeed blizzlike 
https://www.youtube.com/watch?v=yq3N1fP3a24&t=194s
https://www.youtube.com/watch?v=KUizH_eVcuA&t=209s

**Comment by Alethrion** [comment]
https://youtu.be/gM_cpfa3EJE?si=_YhLkVOYpKFFZB35&t=55
This timestamp is a strong example of the instant immolation and a few frames after conflagrate.
What I find odd is that even in one of the proof videos used, conflagrate is activatable only 3frames after the immolate debuff is applied, which does not account for the .5-1.5 seconds seen on AC (at most, assuming 30fps, it would be .1 seconds):
https://youtu.be/KUizH_eVcuA?t=209

**Comment by heyitsbench** [comment]
> (at most, assuming 30fps, it would be .1 seconds)

Don't need to assume for the record, if you right click a YouTube video and turn on "Stats for Nerds", it'll show you the framerate of the video, in this case 25, thus 0.12 seconds (by my math).
