### ISSUE TITLE
[Hillsbrad Foothils] Tin and Silver Vein spawns at same spot in same time on multiple occasions 

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4137]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

![WoWScrnShot_092722_180752](https://user-images.githubusercontent.com/80590226/192618632-c5ec996b-5fa6-41b8-88e9-6caa06792204.jpg)
![WoWScrnShot_092722_181007](https://user-images.githubusercontent.com/80590226/192618635-b9963901-8a69-48fa-beba-c47c979fa0ab.jpg)
![WoWScrnShot_092722_180933](https://user-images.githubusercontent.com/80590226/192618636-b1d624f2-d704-4244-ba16-7b97fb45b0ec.jpg)
![WoWScrnShot_092722_180754](https://user-images.githubusercontent.com/80590226/192618640-c97184b2-3c7c-48ec-acc1-81370fe40831.jpg)
![WoWScrnShot_092722_180753](https://user-images.githubusercontent.com/80590226/192618644-3f7e9782-81ed-45ab-a46e-11d2a21203ec.jpg)

All around Hillsbrad they should share spot but be present either one of them and not both at the same time

### Expected Blizzlike Behaviour

All around Hillsbrad they should share spot but be present either one of them and not both at the same time

### Source

https://wowgaming.altervista.org/aowow/?object=103711
https://wowgaming.altervista.org/aowow/?object=1733

### Steps to reproduce the problem

1. Mine them

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Thanks for the report. this is already a known issue https://github.com/chromiecraft/chromiecraft/issues/2881
