### ISSUE TITLE
Creación de Tinte de Medianoche

### ISSUE THREAD

**Issue by CrisalSc** [chromiecraft/chromiecraft#4139]
### What client do you play on?

esES

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Cuando quiero crear un Tinte de Medianoche me sale que me falta un Pigmento Oscuro que no es necesario para la receta, y no se como seguir con la profesión. ¿Alguna idea? 

### Expected Blizzlike Behaviour

Simplemente no puedo crear un tinte para el cual tengo materiales porque me pide un Pigmento Oscuro que no está en la receta.

### Source

![image](https://user-images.githubusercontent.com/95115236/192653540-a13eb8db-1487-4fbc-a6c5-6f712a8c0df2.png)

### Steps to reproduce the problem

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hola, la receta correcta son dos pigmentos Dusky.
parece que su cliente puede estar dañado. intente deshabilitar cualquier complemento, y si eso no funciona, descargue el juego nuevamente
![image](https://user-images.githubusercontent.com/11332559/192741084-ea563c63-a6ac-46d2-9aae-d5df02728ee1.png)

> Hi, the correct recipie is two Dusky pigment. 
it appears your client may be corrupted. try disabling any addons, and if that doesnt work Download the game again
![image](https://user-images.githubusercontent.com/11332559/192741084-ea563c63-a6ac-46d2-9aae-d5df02728ee1.png)
