### ISSUE TITLE
Reference to reference loot tables are not working correctly

### ISSUE THREAD

**Issue by Caishen-cc** [chromiecraft/chromiecraft#414]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Here is the current loot table for `Elder Stranglethorn Tiger`. SQL Query is:
```sql
select clt.* from creature_loot_template clt
where clt.Comment like '%Elder Str%'
```

```csv
Entry,Item,Reference,Chance,QuestRequired,LootMode,GroupId,MinCount,MaxCount,Comment
1085,1686,0,45,0,1,2,1,1,Elder Stranglethorn Tiger - Bristly Whisker
1085,1687,0,13,0,1,3,1,1,Elder Stranglethorn Tiger - Retractable Claw
1085,5637,0,5,0,1,0,1,1,Elder Stranglethorn Tiger - Large Fang
1085,8146,0,2,0,1,3,1,1,Elder Stranglethorn Tiger - Wicked Claw
1085,12202,0,55,0,1,2,1,1,Elder Stranglethorn Tiger - Tiger Meat
1085,24112,24112,98,0,1,1,1,1,Elder Stranglethorn Tiger - (ReferenceTable)
1085,24157,24157,2,0,1,1,1,1,Elder Stranglethorn Tiger - (ReferenceTable)
1085,24734,24734,1,0,1,0,1,1,Elder Stranglethorn Tiger - (ReferenceTable)
```

For  `Item` = 24112 the Chance is set to `98`. This seems to be extremely high. However, the loot for that Item never drops. The reference table for it looks like:
```sql
select * from reference_loot_template where Entry = 24112
```

```csv
Entry,Item,Reference,Chance,QuestRequired,LootMode,GroupId,MinCount,MaxCount,Comment
24112,24050,24050,25,0,1,1,1,1,(ReferenceTable)
24112,24052,24052,50,0,1,1,1,1,(ReferenceTable)
24112,24054,24054,25,0,1,1,1,1,(ReferenceTable)
```

As you can see, the loot template items for this entry are actually also references. This means, that the `24112` ReferenceTable contains 3 sets of items (24050, 24052, 24054) with explicitly set chances for each set. 

The expected behaviour in such case would be that whenever `24112` rolls positively one item from one of those sets (with set chances) is added to the loot. However, this does not happen because the code of LootMgr does not comprehend the ReferenceTable of ReferenceTables.

After debugging the code, I think the `24112` item is being filtered out in this line of code: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Loot/LootMgr.cpp#L1321
The ReferenceTable is never added to Groups (as it has a nonnull reference) and hence is ignored when the loot is generated. 

This can easily be tested by removing all other items from the `Elder Stranglethorn Tiger` loot table keeping only the `24112` on. Then, when you kill a tiger, it will never drop anything. 

Please note, the `Elder Stranglethorn Tiger` is just an example, I believe there are roughly 200 rows in the `reference_loot_template` table that are also references to references, and I believe they all do not work as intended.  

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Reference to reference tables to be working as intended, giving the juicy loot. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill `Elder Stranglethorn Tiger`
2. Verify it never drops any of the items from `24050`, `24052`, `24054` sets of items.

##### EXTRA NOTES:

I was attempting to fix it myself, by modifying `void LootTemplate::AddEntry(LootStoreItem* item)` but I got confused by `ExplicitlyChanced` field. I am unsure how exactly it must be used. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
> Entry,Item,Reference,Chance,QuestRequired,LootMode,GroupId,MinCount,MaxCount,Comment
> 24112,24050,24050,25,0,1,1,1,1,(ReferenceTable)
> 24112,24052,24052,50,0,1,1,1,1,(ReferenceTable)
> 24112,24054,24054,25,0,1,1,1,1,(ReferenceTable)

These are also reference table. All items in these tables have 0 chance to drop. If you feel a chance should be changed to non 0 make a suggestion.

**Comment by eTzmNcbkrng** [comment]
> > Entry,Item,Reference,Chance,QuestRequired,LootMode,GroupId,MinCount,MaxCount,Comment
> 
> > 24112,24050,24050,25,0,1,1,1,1,(ReferenceTable)
> 
> > 24112,24052,24052,50,0,1,1,1,1,(ReferenceTable)
> 
> > 24112,24054,24054,25,0,1,1,1,1,(ReferenceTable)
> 
> 
> 
> These are also reference table. All items in these tables have 0 chance to drop. If you feel a chance should be changed to non 0 make a suggestion.

I don't understand why you closed this, assuming the submission is true. If I understand your statement correctly, you're saying that items with a 0 chance, correctly have a 0% chance to drop, but this i snot what the Wiki says.
| A group may consists of explicitly-chanced (having non-zero Chance) and equal-chanced (Chance = 0) entries. Every equal-chanced entry of a group is considered having such a chance that:

all equal-chanced entries have the same chance

*group chance (sum of chances of all entries) is 100%

https://www.azerothcore.org/wiki/loot_template#groupid

Items in a table whose chance is 0 all have the same chance, in this case we have 3 so each one should be 1/3 = 33.33%.
The reference table itself has a 98% chance to be called, so that gives the chance of any one of these reference tables 98/100 * 1/3 = 32.67%

**Comment by mdawx** [comment]
@eTzmNcbkrng we agreed that @Caishen-cc will open issue at AC (check discord channel chromiecraft-room). I didn't know about reference table nuance, thanks for pointing out.
