### ISSUE TITLE
[Warrior] - Recklessness & Juggernaut 

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4141]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

60

### Current Behaviour

https://user-images.githubusercontent.com/62584589/192864351-40487d17-babb-43c5-b06d-7daaea1c86fe.mp4

Currently when you use Recklessness, and then charge a unit to gain Juggernaut, your Mortal Strike or Slam if _crit_, will consume 1 stack of Recklessness _and_ the Juggernaut buff. 

### Expected Blizzlike Behaviour

If you have Recklessness up, then charge a unit to gain Juggernaut, the next Mortal Strike or Slam _crit_ should only consume the Juggernaut buff. 

https://user-images.githubusercontent.com/62584589/192864544-dfd1ddc0-078b-4299-833b-87a307d79900.mp4

Notice here that Juggernaut is working correctly, as I have Recklessness up at 3 stacks, charge, gain Juggernaut, and cast slam. The slam however _was not a crit_, so the Juggernaut buff was correctly consumed, and Recklessness stays at 3 charges. 

### Source

No links on hand to show since this was a non-issue on retail servers. 

### Steps to reproduce the problem

1. Cast Recklessness
2. Charge a unit to gain Juggernaut
3. Cast Slam or Mortal Strike
4. Crits will consume both buffs

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, @Cooties-cc , what's your video from? I checked out the WotLK Classic PTR and it has the same behaviour as AC 😮 

https://user-images.githubusercontent.com/100873791/193467882-d348e46b-4b9a-44cf-b77d-0d6f81485a61.mp4

**Comment by Cooties-cc** [comment]
It was done on the chromie PTR as all my testing is. That's strange that the classic PTR is doing it too, maybe not fixed? Did you test out a non-crit and get the same result as my 2nd video? Cause if it doesn't crit, and only eats the Juggernaut buff, that shouldn't be possible if Recklessness gives 100% crit chance on specials (125% with jugg). This to me means that the 1st Mortal Strike or Slam cast should be rolling with the Juggernaut buff, then Recklessness is used for spells past that (or prior if not using slam/ms on 1st 3 casts).

**Comment by Gultask** [comment]
Sorry for the delayed response, you're right! https://youtu.be/Vc0O1-hAwvM?t=25

You're right in both counts. If it doesn't crit (not sure if that's possible) it'll consume only Juggernaut and not Recklessness.

**Comment by bonfax4** [comment]
Retail video you linked shows the exact same behaviour or am I seeing something wrong ? Both got consumed on 1 single mortal strike.
