### ISSUE TITLE
Noblegarden egg looting on spawn makes the item unlootable.

### ISSUE THREAD

**Issue by tabakisp** [chromiecraft/chromiecraft#415]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When you try to loot an easter egg while on the noblegarden event just as it spawns you get trapped in an endless loot animation without loot window.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When the egg spawns and you are permitted to loot it you should be able to loot it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get the quest  A Tisket, a Tasket, a Noblegarden Basket.
2. Equip your basket you just got from the quest.
3. Loot an egg and wait for it to respawn.
4. As soon as it spawns try to loot it.

##### EXTRA NOTES:

[[A Tisket, a Tasket, a Noblegarden Basket]](https://wowgaming.altervista.org/aowow/?quest=13503) quest.

[Video](https://streamable.com/wif3tr) showing the bug.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
I cannot reproduce it. Maybe it is a client bug?

https://user-images.githubusercontent.com/81375770/114618109-4373ca00-9ca9-11eb-8204-4ecb34d93690.mp4

**Comment by tabakisp** [comment]
@mdawx tried it with a new client no addons maybe it's Mulgore's eggs? Will try to other areas too.

**Comment by suprsokr** [comment]
Also happening to me in Azurewatch just now. Different steps though:
- I opened an egg and looted with autoloot
- another player appeared to try and open an egg right after I did
- egg despawns
- egg respawns and begins blinking, "that is already being used"
- Some time passes, and I can loot the egg again.

**Comment by mdawx** [comment]
@tabakisp Ok, i will try in Mulgore and with autoloot enabled.

**Comment by mdawx** [comment]
@tabakisp How often does it happen to you? Can you loot it at all?

**Comment by mdawx** [comment]
Sorry, still can't reproduce:

https://www.youtube.com/watch?v=k_Ekh36FyvY

**Comment by mdawx** [comment]
I have an idea, i will try to add some input and output latency to my server. It might be a case that respawned object is not the same you are trying to loot. If it works we may increase respawn time for eggs to resolve issue.

**Comment by 99dsimonp** [comment]
Very frequently occurring in Brill. Whenever an egg respawns you cannot loot it immediately but instead have to wait a bit.

**Comment by mdawx** [comment]
I deployed server on different location, still couldn't reproduce it. I can only reproduce it on ChromieCraft in Brill.

**Comment by FrancescoBorzi** [comment]
> I deployed server on different location, still couldn't reproduce it. I can only reproduce it on ChromieCraft in Brill.

That means it might be fixed on a more recent AC. Let's wait until the next server update then.

If someone will still reproduce this on ChromieCraft in future, we can reopen it and investigate.
