### ISSUE TITLE
[Class] Rogue [Talent] Master of Subtlety [Spell] Rupture

### ISSUE THREAD

**Issue by NightwindOI** [chromiecraft/chromiecraft#4155]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

At max rank, ''Master of Subtlety'' suppose to increase any dmg by 10% for a given time. It doesn't for Rupture
https://www.wowhead.com/spell=31223/master-of-subtlety#comments
https://www.wowhead.com/spell=1943/rupture

### Expected Blizzlike Behaviour

Once you go out of stealth and use Rupture it suppose to increase the DoT dmg until the Master of Subtlety effect fades away.
https://www.wowhead.com/spell=31223/master-of-subtlety#comments:id=137775

### Source

https://www.wowhead.com/spell=31223/master-of-subtlety#comments:id=137775
https://www.wowhead.com/spell=1943/rupture#comments:id=380805

### Steps to reproduce the problem

Make Rogue
Speck Master of Subtlety
Go Stealth and attack something
Cast Rupture

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, thanks for the report. im unable to reproduce this as damage appears to be increased as expected.

buff correctly snapshots when applied, which is blizzlike


https://user-images.githubusercontent.com/11332559/195394549-8838424f-6038-4c79-92a7-be689edb6bf8.mp4

https://user-images.githubusercontent.com/11332559/195394555-a50a6e6a-9c28-4b1b-8784-d20e986ef87d.mp4

(more than 10% but general testing shows the buff as working)
