### ISSUE TITLE
Warsong: Visibility of flag carrior on the map

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4158]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Once someone picks up the flag in warsong, the position of the flag is directly visible to both teams on the map.

### Expected Blizzlike Behaviour

There was a recent hotfix for classic wotlk causing the flag carrier to become visible on the map for the enemy team after 45 seconds. Before the hotfix, the flag carrier wasnt visible on the map at all.

This allows the conclusion that indeed the own flag shouldnt be visible on the map until 45s have past.

### Source

https://www.wowhead.com/wotlk/news/wrath-classic-hotfixes-honor-gear-reduced-talent-fixes-pvp-329185

### Steps to reproduce the problem

.

### Extra Notes

I assume this is also open to discussion, therefore opening this issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, thanks for the report. 
current behavior is that the flag carriers are immediately visibible, with a delayed location.
this is accurate to how it used to be in wrath, see https://www.youtube.com/watch?v=47d4GUBTwK4

if you wanted to suggest a custom change, you should put it under suggestions rather than game bugs

**Comment by balleny** [comment]
Skimmed through that video but didnt saw a moment when the flag wasnt already 45 seconds picked up and the map was shown.
further, relevant patch notes:
https://wowwiki-archive.fandom.com/wiki/Patch_2.4.0#Warsong_Gulch

which seem to make this even more being the case considering blizzard applied this (once again) on classic wotlk.

**Comment by BeefSteaker** [comment]
I'll reopen it as there's been some discussion on the discord

**Comment by Samsequel** [comment]
@BeefSteaker 

What is the end result of this?

**Comment by BeefSteaker** [comment]
I don't believe there was a consensus on it

**Comment by FrancescoBorzi** [comment]
> being the case considering blizzard applied this (once again) on classic wotlk.

> I don't believe there was a consensus on it

this is rather a feature request and not a bug report. Feel free to bring it up again, but in [our forum](https://github.com/orgs/chromiecraft/discussions) and not here as this is not a bug but the way it was originally intended in the game.
