### ISSUE TITLE
Iron Node Double Spawn in Tanaris

### ISSUE THREAD

**Issue by Azcobu** [chromiecraft/chromiecraft#416]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [X] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

A pair of iron ore nodes spawn very close together in Tanaris. Their Guids are 6494 and 17453. This is on AzerothCore rev. c0cb2eae38dc+ 2021-04-06 03:52:40 +0000 (master branch) (Unix, Release).

![WoWScrnShot_041321_195655](https://user-images.githubusercontent.com/81782124/114540118-5203b680-9c94-11eb-82ee-287b09a77718.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Ore should be spaced more evenly, and not overlapping.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go o 6494
2. Observe undesirable proximity.

##### EXTRA NOTES:

I do have a related query about how close nodes can be allowed to spawn. If you look at these two screenshots, are nodes like these okay, or should they be reported too? How about herbs, with their much smaller footprint?

![WoWScrnShot_041321_195804](https://user-images.githubusercontent.com/81782124/114540833-28975a80-9c95-11eb-957a-b9b844b7d1f2.jpg)
![WoWScrnShot_041321_195528](https://user-images.githubusercontent.com/81782124/114540857-2f25d200-9c95-11eb-8f5c-f4ebeff1435a.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
1. Your revision is outdated and issue might be already resolved. You are behind 83 commits (chromiecraft is only 12 commits behind)
git rev-list c0cb2eae...HEAD | wc -l
83

2. If you report issues using local server you can use AC repo. It would avoid double checking.

3. How close nodes can be allowed to spawn?
This comment might be helpful: Check this comment https://github.com/azerothcore/azerothcore-wotlk/issues/5242#issuecomment-817359163, so I assume that 2 veins in that range is ok, 3 might be too many.

4. I confirm that there are still overlapping iron veins on current revision.
git log -1 --oneline
c49f6876 (HEAD -> master, upstream/master) chore(DB): import pending SQL update file

**Comment by FrancescoBorzi** [comment]
@mdawx  about the revision, that's automatically included from:

https://github.com/chromiecraft/chromiecraft/blob/main/issue_template.md

which contains the current AC version of ChromieCraft

**Comment by mdawx** [comment]
@FrancescoBorzi My point was that @Azcobu tested it on his own server and his revision was a bit old, I should have written it in private actually.

**Comment by heyitsbench** [comment]
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/25797238026ca87a9a3906add11ebfc9cc9802d4.
