### ISSUE TITLE
Under Stormwind City

### ISSUE THREAD

**Issue by DPComputer** [chromiecraft/chromiecraft#4160]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

![WoWScrnShot_100622_190457](https://user-images.githubusercontent.com/95505176/194380307-3386291a-3891-45f6-bdee-c385d0d8f326.jpg)
![WoWScrnShot_100622_190515](https://user-images.githubusercontent.com/95505176/194380312-2c977922-ee4b-442d-8dd2-45fb710c52be.jpg)
![WoWScrnShot_100622_190518](https://user-images.githubusercontent.com/95505176/194380316-f21f0df1-4cde-4590-b973-9797cccc75ba.jpg)

I took the flight from sentinell hills, westfall, then alt-tabbed, did some web browsing and when i alt-tabbed back it was like this.

I managed to get out towards the main gate.

### Expected Blizzlike Behaviour

I son't know.

### Source

.

### Steps to reproduce the problem

1. take the flight from sentinel hill - westfall
2. alt-tab out of the game
3. browse internet 
4. lose connection to the server
5. relog when you know you have arrived at destination

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702
.

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, are you able to replicate this? 
ive tried it a couple different times in different ways and dont seem to be able to replicate.

could be a weird very rare bug

**Comment by DPComputer** [comment]
Unfortunately no, and i think it's more of a client bug.
Probably cache messed up after the disconnect, while alt-tabbed.

**Comment by Gultask** [comment]
Happens because of packet loss. Most of the time it happens when the user is alt-tabbed. Not much we can do afaik.
