### ISSUE TITLE
spider coccoon "Webbed Creature" contained a boss

### ISSUE THREAD

**Issue by Shevi22** [chromiecraft/chromiecraft#417]
In Bloodmyst Isle, killing a Webbed Creature contained Tel'athion the Impure. He ran away after something triggered him elsewhere, saying something about wanting to kill a meddlesome shaman. So I did not have to fight him as he ran all the way.
~Sapish

**Comment by Shevi22** [comment]
It contains just about anything on the map. I keep meeting random bosses from the spider eggs.

**Comment by FrancescoBorzi** [comment]
@Shevi22 please fill the bug report template.

>
