### ISSUE TITLE
[AQ40] Viscidus: certain type of frost effects shouldnt count

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4178]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

not verified yet.

### Expected Blizzlike Behaviour

Only Frostdamage from Abilities (frostmage), Oil (Frost Oil) and On-Hit effects should count towards the frost counter.

Weapons, besides wands, that have an additional "as frostdamage" part, must not count.

### Source

https://www.icy-veins.com/wow-classic/viscidus-guide-strategy-abilities-loot

> In order to make things as easy as possible, players in your raid want to wear Nature resistance gear / consumables that allow them to deal frost damage with their attacks, such as Frost damage wands, Frost proc weapons, such as [Coldrage Dagger](https://classic.wowhead.com/item=10761) Icon Coldrage Dagger ([Iceblade Hacker](https://classic.wowhead.com/item=13952) Icon Iceblade Hacker and similar weapons will not [work](https://us.forums.blizzard.com/en/wow/t/weapons-with-frost-damage-or-any-other-school-dont-work/569190/7) ), and [Frost Oil](https://classic.wowhead.com/item=3829) Icon Frost Oil.

### Steps to reproduce the problem

.

### Extra Notes

these items should not count towards the freezing:
https://wotlkdb.com/?items=2&filter=cr=35:36;crs=4:1;crv=0:0;ty=15:13:0:4:7:6:10:1:5:8:2:18:3:16:20:14;maxle=70

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
see also:
https://classic.wowhead.com/item=13952/iceblade-hacker#comments:id=3215934

**Comment by BeefSteaker** [comment]
Confirmed on the ptr and my local that these weapons dont count towards the frost counter
