### ISSUE TITLE
Dungeon Finder: RDF is not properly matchmaking groups

### ISSUE THREAD

**Issue by QuitoPR** [chromiecraft/chromiecraft#420]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Random Dungeon Finder is creating groups of disparate level ranges. There are low level players ending up in dungeons outside of their available dungeons in the Specific Dungeons list of Group Finder

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Players should only be grouped for non-grey dungeons appearing in their respective Specific Dungeons list as these are the ones deemed appropriate for that level range.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Queue into Random Dungeon Finder with a pool of large level ranges
- Ex: Queue as level 15 and level 29s
2. Get into a dungeon together
- I suppose if level 29s are the majority, the dungeon finder will start a dungeon appropriate for their level but with the low level player still present.

- It seems to happen the other way too: high level players into low level

##### EXTRA NOTES:

Apologies for poor steps, may not be exact to reproduce scenario, but there are others experiencing this: 
![image](https://user-images.githubusercontent.com/7005291/114621757-60aa9780-9cad-11eb-95ca-60885a9f7bf9.png)

Myself @ Level 18 and a level 15 in Gnomeragan via RDF
![image](https://user-images.githubusercontent.com/7005291/114621867-8768ce00-9cad-11eb-80eb-9e160781f3f3.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
I think problem will be solved by this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/5277

**Comment by 55Honey** [comment]
This has been solved already.
