### ISSUE TITLE
People detect from 10 yards  rouge [Stealth] pretty easy

### ISSUE THREAD

**Issue by tarshel** [chromiecraft/chromiecraft#421]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [- ] enUS
- [ ] other (specify)

##### FACTION

- [- ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [- ] 1-19
- [- ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.

Rouge spell  [Stealth] is easy seen by player in pvp even with 3/3[Master of Deception] With witch reduce the chace enemise to detect you... Is not playable people to see you at 10+ yards. Every time i use  [Sap] on 10 yards people easy target me and put dots.. ect..

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
without the bug 5-7 yards is death zone witch people can see you not like 10 yards the class become unplayeble

##### STEPS TO REPRODUCE THE PROBLEM:

1. reduce people range to detect [Stealth]
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by orfaze** [comment]
Maybe because of the voidwalker buff?
Spotting a rogue is actually really hard without it or stealth tracking from hunter

**Comment by mdawx** [comment]
First rogue has +3 Master of Deception and he can second one.
![image](https://user-images.githubusercontent.com/81375770/114936337-992cab80-9e3c-11eb-80af-814fa46496eb.png)

Second one can't see first within range < 5y
![image](https://user-images.githubusercontent.com/81375770/114936365-a21d7d00-9e3c-11eb-91b8-f3f412308d74.png)

I tested also human paladin with Perception and he could see rogue betweend 5-6 y

![image](https://user-images.githubusercontent.com/81375770/114936822-3b4c9380-9e3d-11eb-8191-183a6fd2f55c.png)

![image](https://user-images.githubusercontent.com/81375770/114936834-40114780-9e3d-11eb-8f20-eb9fe80dec69.png)
