### ISSUE TITLE
Desolace Kodo Spawns

### ISSUE THREAD

**Issue by c-tapp** [chromiecraft/chromiecraft#4210]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

All Kodo mobs in Desolace's Kodo Graveyard zone, [Aged Kodo](https://wowgaming.altervista.org/aowow/?npc=4700), [Dying Kodo](https://wowgaming.altervista.org/aowow/?npc=4701) and [Ancient Kodo](https://wowgaming.altervista.org/aowow/?npc=4702) are spawned as mob [Tamed Kodo](https://wowgaming.altervista.org/aowow/?npc=11627). The tamed kodo mobs are friendly and unable to interact with making the quest [Kodo Roundup](https://wowgaming.altervista.org/aowow/?quest=5561) incompletable. 
Watched for >30mins while submitting bug report and no forced respawns.

### Expected Blizzlike Behaviour

Assuming this wasn't done by another player (Tamed Kodo mobs can only be 'tamed' one at a time and follow the player until turned in) the mobs are spawning as the wrong NPC. 
If this was done by another player the Tamed Kodo mobs shouldn't be able to unleash from that player or should convert back to their original NPC when they do.

### Source

Not really sure what kind of source you're looking for here, I guess here's a comment from WoWhead that supports my claim?
![Kodo1](https://user-images.githubusercontent.com/77695884/195906485-d7263712-f573-4716-85e6-12ed01c00391.PNG)

Here's another for good measure, User Slayergnome comments "This quest is SOOOO FUUUUNNNN" which would be true if it was not bugged :-(
![image](https://user-images.githubusercontent.com/77695884/195907011-15bc5c42-1f9d-4f4e-9a22-c5be80486a1a.png)

### Steps to reproduce the problem

1. Travel to Kodo Graveyard, Desolace

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Win 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
hi, thanks for the report. 
plenty of different kodo present on PTR. Im guessing they were tamed and this bug occured https://github.com/chromiecraft/chromiecraft/issues/833


https://user-images.githubusercontent.com/11332559/195990621-cb7f8dbf-5f45-49ed-9127-0cdcb099aa1a.mp4
