### ISSUE TITLE
Paladin seal proccing twice

### ISSUE THREAD

**Issue by Mikel0ke** [chromiecraft/chromiecraft#4211]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Paladin seal procs 2x per attack.

### Expected Blizzlike Behaviour

It should only proc once per attack.

### Source

![imagen](https://user-images.githubusercontent.com/83586527/195948413-1eb9e4e6-20f5-4497-8e5c-4c68b8c73129.png)

### Steps to reproduce the problem

Use a seal and attack a dummy until it procs.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Unable to reproduce this one, could you share your equipment/talents 

works as expected on live/ptr for me
https://user-images.githubusercontent.com/11332559/195989915-92ff569e-4d74-466d-8cbc-49c0e9bc4373.mp4

**Comment by Mikel0ke** [comment]
i wasnt doing it, it was a pala i found in bg i dont know if he was using a weird build or something

**Comment by The-GhostRider** [comment]
Hi @Mikel0ke, Thanks for your Report and your time.
I was unable to reproduce the Bug and from my VIDEO, you too can see that the Paladin's "Seal" ability works well.

**Video Test:** [Paladin seal DOESN'T proccing twice](https://youtu.be/_PxLdjQeUjI)

For this reason I close the Report.
