### ISSUE TITLE
Mobs can keep attacking while stealthed

### ISSUE THREAD

**Issue by djobf** [chromiecraft/chromiecraft#4212]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Hive'Ashi Sandstalker is able to attack and stay in stealth, making it virtually impossible to hit if offensive CDs are down and even impossible to escape if all CDs are down. [Video Proof](https://youtu.be/KIgKFUtzYbk) (please disregard the song, I forgot to mute on OBS lol)
The other stealthed units in the Silithus hives have the same behavior, and I remember a satyr in Felwood doing that too.

### Expected Blizzlike Behaviour

Mobs shouldn't (according to veteran players) be able to hit players and stay in stealth.

### Source

I couldn't find anything online going in the sense or against this behavior but other players told me it was a bug and I can't imagine this being intended, I don't have a Wow account to test it on Classic.

### Steps to reproduce the problem

1. Go to Hive'Ashi
2. Aggro one of these mobs
3. Get attacked while mob stays invisible

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Unable to replicate on PTR or Live. Hive'Ashi Sandstalker and other stealthed mobs correctly break stealth when attacking.
Maybe a visual bug on your end?

https://user-images.githubusercontent.com/11332559/195989271-330efff8-5053-4274-aa9c-9344d126bc22.mp4

https://user-images.githubusercontent.com/11332559/195989293-d1b16b44-ab94-4bd8-a0dd-dc7f7e9ca5be.mp4
