### ISSUE TITLE
[PTR][AQ40] Spawn of Fankriss does very low dmg before berserk

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#4219]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=15630
Spawn of Fankriss does very low dmg before berserk ability.  Screenshot - ![изображение](https://user-images.githubusercontent.com/104144379/195993746-dadc3a33-86df-4ae6-a0b8-d4bfe3a629a0.png).

### Expected Blizzlike Behaviour

At random times during the fight, one to three yellow-colored level 63 Elite worms called Spawn of Fankriss will spawn in a random location. Spawn of Fankriss hit for around 2000 on cloth. They will also enrage after 20 seconds if they are not killed. Enraged worms deal 10-20k per hit, one-shotting anybody they're on. They are by far the most important part of the fight, as they must be killed immediately. They can be stunned, so all is not lost if they enrage just before they die.

### Source

https://wowwiki-archive.fandom.com/wiki/Fankriss_the_Unyielding - Attacks and Abilities part.

### Steps to reproduce the problem

1. Enter to AQ40.
2. Go to  Fankriss the Unyielding.
3. Wait till he will summon Spawns of Fankriss.
4. Observe his damage before berserk.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Win10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. 2e6f6e26da8f 2022-10-12 14:39:02 -0400 (master branch) (Unix, Debug, Static)

**Comment by Gultask** [comment]
Will be fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/13408
