### ISSUE TITLE
quest: Hidden Enemies - wrong Location tracker

### ISSUE THREAD

**Issue by Rittmeister39** [chromiecraft/chromiecraft#422]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

the location is the cave east of Orgrimmar, but the map shows wrong location. see screenshot.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

location should be where my mouse points to in the image

##### STEPS TO REPRODUCE THE PROBLEM:

1. take quest from Thrall in Orgrimmar
![WoWScrnShot_041321_233128](https://user-images.githubusercontent.com/78271326/114624395-e845d580-9cb0-11eb-898b-797617c38dd5.jpg)

2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
You can also find insignia there
![image](https://user-images.githubusercontent.com/81375770/114624772-7ae67480-9cb1-11eb-8c74-3c4d08097b85.png)

https://wotlkdb.com/?quest=5726
