### ISSUE TITLE
[PTR][AQ40] C'Thun giant eye tentacle can be spawned in his stomach

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#4224]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=15727
NPC: https://wowgaming.altervista.org/aowow/?npc=15334
 CThun giant eye tentacle can be spawned in his stomach:
![изображение](https://user-images.githubusercontent.com/104144379/195994225-13705492-e8fc-4617-adb4-2ab118427f63.png)

### Expected Blizzlike Behaviour

There is no any mention in any guides that other tentackel except Flesh Tentacles should spawned ay C'thun stomach.

### Source

---

### Steps to reproduce the problem

1. Enter to AQ40.
2. Go to C'thun.
3. Transition boss to p2.
4. Fight for long time periond to monitor Giant eye tentackle spawn at stomach.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Win10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. 2e6f6e26da8f 2022-10-12 14:39:02 -0400 (master branch) (Unix, Debug, Static)

**Comment by Gultask** [comment]
It shouldn't target players in the stomach, and I haven't seen that happen, myself but we'll keep an eye out.

If someone can reproduce please let us know!

**Comment by IskrenPlashkov** [comment]
Hijacking this issue in order not to open a very similar ticket:
It is also possible for giant eye tentacle laser coming from the surface to hit players in the stomach. 
Dont have a screenshot or video as none of the players recording were in the stomach when it happend.

**Comment by Synful-Syn** [comment]
A guildie posted this during our run.
AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7 2022-11-02 11:07:49 +0000 (master branch) (Unix, RelWithDebInfo, Static)

![image](https://user-images.githubusercontent.com/22718174/200196213-5396fefb-85dc-44be-81a5-d50c26edf178.png)

**Comment by Gultask** [comment]
I wonder how could this have happened. I *think* that it never spawns on top of characters that are afflicted by Digestive Acid.

**Comment by enzospin360** [comment]
![WoWScrnShot_110622_133714](https://user-images.githubusercontent.com/90984733/200196914-fde2e680-5cc8-4cc5-ac7f-11fca565d368.jpg)

**Comment by davegrier** [comment]
![image](https://user-images.githubusercontent.com/14080595/200197751-c2f0603c-3bd4-4194-b18e-5b56fc7396bd.png)

**Comment by HasieEST** [comment]
Couple of clips and something that might suggest a reasoning..
https://clips.twitch.tv/PrettiestPhilanthropicPistachioBCouch-JJI9XXYMxzQKEcSE
https://clips.twitch.tv/IcyGiantRhinocerosBleedPurple-e_PsuUKnEq0VEtrL
https://clips.twitch.tv/BelovedRespectfulTomatoDerp-wnRJffbc47xcbVSY
https://clips.twitch.tv/DifficultBlitheSquirrelGivePLZ--gP44aG4t6Amn2R1
Added bonus:
https://clips.twitch.tv/CrunchyNimbleDootFreakinStinkin-SWIoXQGNh3iEgGTD

**Comment by davegrier** [comment]
> I wonder how could this have happened. I _think_ that it never spawns on top of characters that are afflicted by Digestive Acid. Same goes for Eye Beam.

is Digestive Acid cleared before or after the animation to leave the stomach? This issue seemed to most commonly happen right on the exit, if the debuff is cleared as the player starts the long exit animation they may become an eligible target for add spawn before they finish getting out. Enzospins's screenshot has the add spawn in the ceiling above the exit; when the player is exiting the stomach they fly directly up through that gap, so it appears the add spawned on a player while they were midair and exiting the stomach area. 

And as Hasie shows in the first clip above, sometimes players do not get the Digestive Acid debuff at all.

**Comment by Nyeriah** [comment]
Digestive Acid prevents tentacles from spawning inside the stomach as well as players being targeted by the eye beams. There seems to be an issue with Digestive Acid not being applied to players.

Digestive Acid is removed after the players teleport to the upper room (outside the stomach).

**Comment by Gultask** [comment]
Digestive Acid can be resisted, apparently.
Spells that increase miss chance i.e. Cloak of Shadows / Improved Blink can cause this.
