### ISSUE TITLE
[PTR][AQ40] Obsidian Eradicator mana burn

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#4227]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Uses the wrong ability for mana burn
https://wowgaming.altervista.org/aowow/?spell=25671
(should be used by Obsidian Nullifier)

### Expected Blizzlike Behaviour

Obsidian Eradicator should drain mana from up to 11 players per tick
Spell: https://wowgaming.altervista.org/aowow/?spell=25755
Also looks like shouldn't be able to resist. Because we've seen mana drained less than 500 when in the logs you can always see the value exactly 250

### Source

https://vanilla.warcraftlogs.com/reports/3HhvjzxTcGqFpNXC#fight=2&view=events&hostility=1&source=55&type=summary

### Steps to reproduce the problem

123

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
I can confirm. The spell that should be used is:

```
ServerToClient: SMSG_SPELL_GO (0x2C39) Length: 152 ConnIdx: 1 Time: 08/01/2022 18:16:11.673 Number: 1556
(Cast) CasterGUID: Full: 0x2030F842600EE7800005370000E84230 Creature/0 R3134/S1335 Map: 531 Entry: 15262 Low: 15221296
(Cast) CasterUnit: Full: 0x2030F842600EE7800005370000E84230 Creature/0 R3134/S1335 Map: 531 Entry: 15262 Low: 15221296
(Cast) CastID: Full: 0xBC30F842601926C3000537000168429C Cast/3 R3134/S1335 Map: 531 Low: 23610012
(Cast) OriginalCastID: Full: 0xBC30F8426019D6430005370000E8429C Cast/3 R3134/S1335 Map: 531 Low: 15221404
(Cast) SpellID: 25755 (25755)
```
