### ISSUE TITLE
Mithril Bound Trunk disappearing without giving loot 

### ISSUE THREAD

**Issue by whit4512** [chromiecraft/chromiecraft#423]
BEFORE you fill out an issue, make these checks:

- make sure you use an enUS client. We will just close your issue if you use enGB.
- close wow, clear your cache by deleting the CACHE folder in you wow directory, try to reproduce the bug
- if you have a suggestion, like increasing despawn timers, this is not an issue. Tell us in #suggestions on discord instead.

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- 

- [ ] Alliance

- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[https://classic.wowhead.com/item=21228/mithril-bound-trunk#comments](url) The trunks you fish up from gathering nodes are supposed to give items, and afterward will leave the trunk in your inventory after the items have been looted. I found that this happened to me in Tanaris near Steamwheedle Port.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should have a random assortment of items as shown in the link above, and leave a trunk in your inventory after looting.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Fish from gathering nodes in Tanaris and obtain a Mithril Bound Trunk
2. Open and see if Trunk disappears without any loot
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
I see nothing strange. I recorded video opening 100 Trunks.
https://www.youtube.com/watch?v=xL-HWh6v1cU

Sometimes they are empty, but every item has separate chance to be rolled, so IMO nothing special.

You wrote:
> It should have a random assortment of items as shown in the link above, and **leave a trunk in your inventory after looting**.

Do you have any proof that empty trunk shouldn't disappear?

**Comment by whit4512** [comment]
I thought they always have something, and it happened no little that I
thought it was an inconsistency

**Comment by Helias** [comment]
considering this, do you think guys that we can close this?

**Comment by mdawx** [comment]
I think so. I'm closing.

**Comment by mdawx** [comment]
I remember few days ago i paid a rogue tip for opening Ironbound Locked Chest. It turned out empty.
