### ISSUE TITLE
[AQ40] Princess Huhuran - Wyvern Sting

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#4233]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

[Wyvern Sting](https://classic.wowhead.com/spell=26180) hit 10 random targets

### Expected Blizzlike Behaviour

[Wyvern Sting](https://classic.wowhead.com/spell=26180) should hit only 10 CLOSEST targets

And probably it should also hit pets and summons:
- Hit pets
- Hit summons, but they immune to the effect
![yhksdgfnfnfg](https://user-images.githubusercontent.com/27493763/196047726-ad737a91-fe93-4b3a-911b-730b27ae32f0.png)

### Source

https://vanilla.warcraftlogs.com/reports/G8A1JF2PnhwHyDLf#fight=43&view=events&eventstart=6288247
https://vanilla.warcraftlogs.com/reports/6HFCjh2G4aRzVdrx#fight=last&type=summary&view=events&eventstart=7610369

### Steps to reproduce the problem

1. go to Huhuran with more than 11+ ppl
2. stay farther than the other 10 players
3. you should never be hit with Wyvern Sting

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/13468
