### ISSUE TITLE
[Quest] Falrin's Vendetta

### ISSUE THREAD

**Issue by Peti321** [chromiecraft/chromiecraft#4234]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

After collecting 25 Ogre Warbeads in Dire Maul the quest says:
"Return to Falrin Treeshaper at Dalaran Crater in Alterac Mountains."
It even shows it in the map. However the NPC is not there.

### Expected Blizzlike Behaviour

The quest text should not tell you to go to Alterac Mountains because the NPC is not there.
This whole quest takes place in Dire Maul.
https://www.wowhead.com/classic/quest=8949/falrins-vendetta
The NPC is in Dire Maul because he is the one who gave it to me. I think only the text and the question mark on the map is the bug.

### Source

https://www.wowhead.com/classic/quest=8949/falrins-vendetta
The text should say:
"Return to [Falrin Treeshaper] inside the Athenaeum in [Dire Maul]."

### Steps to reproduce the problem

1. Take the questline
2. Reach the quest Falrin's Vendetta
3. Get 25 Ogre Warbeads in Dire Maul
4. Check the quest text and map to see what it shows.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
hi, thanks for the report.
unfortunately while the text is incorrect, it is blizzlike
![image](https://user-images.githubusercontent.com/11332559/196059974-2fefa274-305b-481c-bd8e-9a436e38b965.png)
