### ISSUE TITLE
[Cow King's Hide]

### ISSUE THREAD

**Issue by gokdrak** [chromiecraft/chromiecraft#4249]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

[Cow King's Hide] don`t boost my fire and nature resistance
![WoWScrnShot_101922_090459](https://user-images.githubusercontent.com/86462263/196620544-60c8cf98-558c-483d-868a-f2fe30c577a7.jpg)
![WoWScrnShot_101922_090520](https://user-images.githubusercontent.com/86462263/196620551-c018b522-1f52-4584-a425-b2b74b0464b5.jpg)

### Expected Blizzlike Behaviour

[Cow King's Hide] 
ChestLeather148 Armor+10 Stamina+10 Arcane Resistance+10 Fire Resistance+10 Nature Resistance+10 Frost Resistance+10 Shadow Resistance

### Source

https://wotlk.evowow.com/?item=13009

### Steps to reproduce the problem

That is only on my char that I know

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
invalid.
your bloodfang chestpiece has +10 FR and +10 NR.
thus, you shouldnt see an increase switching between Bloodfang chestpiece and Cow Kings Hide

**Comment by BeefSteaker** [comment]
> invalid. your bloodfang chestpiece has +10 FR and +10 NR. thus, you shouldnt see an increase switching between Bloodfang chestpiece and Cow Kings Hide

thanks for the report 
this appears to be correct, notice how your nature resistance doesnt change either.
