### ISSUE TITLE
Druid Caster Form replaced with Cat Form model

### ISSUE THREAD

**Issue by fivepointfiveb** [chromiecraft/chromiecraft#425]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [ X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I play a druid and sometimes after a while my humanoid form disappears and my cat form replaces my humanoid form. Means i can cast nature spells while im still in cat form (just visually though i am not really in cat form)
 or when riding mounts its just my cat form on top of my mount. Here are some pictures to better Visualize. 
![download](https://user-images.githubusercontent.com/82536162/114758222-036e1f00-9d5d-11eb-90bd-a79648876c0a.png)
![download](https://user-images.githubusercontent.com/82536162/114758439-429c7000-9d5d-11eb-9377-7ddef883c627.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Well, you should get back into caster form after leaving get form. I dont think any Evidence is needed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I am not 100% sure but i think it happens after i return from a Battleground. (i will look into this further and see if i can specificely say if it happens after a BG)
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Notrox1** [comment]
This happend to me several times when the BG ends and you are shapeshifted in this moment. 
Only a relog helps to remove.
Happened in Bear/Cat and Travel Form

**Comment by mdawx** [comment]
I tried 6-7 times without success so far.

**Comment by Azcobu** [comment]
No luck replicating this either. Tried WSG mostly, though checked AB, and tried on both Horde and Ally chars. Was wondering if it needed a condition like being in combat when the BG ended to trigger. 

When it happens, do other players see you in cat/bear form as well, or are you in humanoid form to them?

**Comment by Stifler82** [comment]
> When it happens, do other players see you in cat/bear form as well, or are you in humanoid form to them?

Great question @Azcobu, I was just about to ask the same thing..

Can you answer this question @fivepointfiveb, pls?

**Comment by fivepointfiveb** [comment]
Hey sorry for the late response, yes other players see the same thing, so its not just from my side. To be honest this bug hasnt appeared in the last 2-3 days despite the fact that before that i literally got it everyday. I also need to mention that im not 100% sure that it appeared after a bg, but since @Notrox1 confirmed it. it might be. I will look into it and provide further information once i encounter the bug again.

**Comment by fivepointfiveb** [comment]
Update: it just happened again, i was in stealth and cat form when the BG ended. But my theory is, it having something to do with crossfaction BG, i was on Horde side when it happened (im Alliance). Almost 99% Sure it has something to do with crossfaction BGs.

**Comment by mdawx** [comment]
I've seen one druid being cat on a mount.
![image](https://user-images.githubusercontent.com/81375770/115465890-914f7b80-a22f-11eb-9557-f832a190e5da.png)

![image](https://user-images.githubusercontent.com/81375770/115465788-6bc27200-a22f-11eb-869d-747c2b4fdac1.png)
![image](https://user-images.githubusercontent.com/81375770/115465845-7f6dd880-a22f-11eb-8491-4e88af833d69.png)

**Comment by mdawx** [comment]
https://user-images.githubusercontent.com/81375770/115478870-5c4f2300-a247-11eb-8e29-bd1b2ae6f863.mp4

**Comment by mdawx** [comment]
Thanks @NidaleeLiadrin for help!

**Comment by Helias** [comment]
it has been fixed, it will be live soon
