### ISSUE TITLE
[AQ40] C'thun Eye Tentacle issues

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4251]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Eye Tentacles dont engage combat with the raid, only proximity based engage.
Eye tentacles arent spawning at the end of Dark Glare

### Expected Blizzlike Behaviour

Eye Tentacles should engage and attack the full raid.

Eye Tentacles should spawn a few seconds before Dark Glare (working) and after Dark Glare Ends

### Source

vanilla
https://www.youtube.com/watch?v=34ba7rg0gdc

classic
https://www.youtube.com/watch?v=ZbC21q203oQ

### Steps to reproduce the problem

engage cthun, wait and kill first set of eye tentacles

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Keep in mind eye tentacles never beam the same player, so you need at least 8 players for all of them to engage

**Comment by balleny** [comment]
indeed, but if they engage combat with 1 person only, wouldnt this mean that one eye would focus and recast their mindflay on that one person only (if other people wouldnt heal / engage / get close, too)

**Comment by Nyeriah** [comment]
> indeed, but if they engage combat with 1 person only, wouldnt this mean that one eye would focus and recast their mindflay on that one person only (if other people wouldnt heal / engage / get close, too)

They're in combat with everyone, it's just that you will never have two tentacles mind flaying the same player

**Comment by balleny** [comment]
> > indeed, but if they engage combat with 1 person only, wouldnt this mean that one eye would focus and recast their mindflay on that one person only (if other people wouldnt heal / engage / get close, too)
> 
> They're in combat with everyone, it's just that you will never have two tentacles mind flaying the same player

and that was exactly my bug report. They are NOT in combat with everyone. might even stay fully out of combat, if there are not enough targets to cast an initial mind flay on.

**Comment by elthehablo** [comment]
Issue does seem to be correct
