### ISSUE TITLE
[AQ40] Battleguard Sartura royal guards issues

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#4252]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

The combination of the following 3 add abilities makes the fight basically impossible without some solid cheese:

While spinning adds are immune to taunt or any CC;
While spinning adds are over trice as fast as any player and kiting is impossible for the primary target and extremely difficult for players who are nearby;
Unlike retail, add WW does 1700-2k dmg per tick on cloth.

In summary when adds begin spinning the selected target is guaranteed to die unless they use invulnerability of some sort. Nearby players will also almost certainly die as you have less than 2 seconds to react. Losing multiple raiders repeatedly makes killing the boss later impossible.

### Expected Blizzlike Behaviour

CC and taunt immunity is correct;
Speed while WW also seems correct, however its impossible to track and prove.
Add WW dmg is 700-1k on cloth.

### Source

https://www.youtube.com/watch?v=W8DfhK_4MH8 1:22 into the video.

### Steps to reproduce the problem

Engage Battleguard Sartura.

### Extra Notes

The WW is over 2.5 times more than on retail, turning the mechanic from major source of dmg to guaranteed and unavoidable deaths, dooming the fight to wipe.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

All.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by IskrenPlashkov** [comment]
Yes, when adds are not spinning they are tauntable, as they should be. The issue here comes from the fact that while they spin they are completely out of control while doing too much dmg, making avoiding deaths impossible.

**Comment by Gultask** [comment]
Hey, Iskren, thanks for reaching out.

All of those mechanics are intentional to some extent. The spell used is the correct one (26038) and the extra damage comes from raid tuning that increases damage taken globally. Speed is also correct, it is taken directly from sniffed values or the spell effects.

Since it's related to tuning, could you make a post in the discussion page instead?
