### ISSUE TITLE
[AQ40] Twin Emps Uppercut does too much damage and is followed by a melee hit

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#4260]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Vek'nilash's Uppercut ability is scaled too high, hitting leather for over 5.5k and plate for roughly 3.7k. IF the target survives they also get hit by a melee attack.

### Expected Blizzlike Behaviour

Uppercut should still hit a random target in melee range, but for significantly less dmg (subject to scaling of course)
There should be no follow up melee swing on said target.
Hit target should also be knocked back.

### Source

https://www.youtube.com/watch?v=U0nYW425Tb8 1:43 of video

### Steps to reproduce the problem

Engage twin emperors.
Have more than 1 player in melee range.

### Extra Notes

With the current implementation of the mechanic and its scaling raid is guaranteed to lose 1 melee dps pet uppercut, unless it barely survives the initial dmg and then avoids the follow up basic attack.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by IskrenPlashkov** [comment]
After looking at the game code a bit we suspect that his double attack has 50% chance of procing and additional hit from all his basic attacks and abilities, including the double attack procing on itself. With the current scaling this could cause 1 shot combos, even on full bis/buffed/consumables tanks.

**Comment by IskrenPlashkov** [comment]
Some extra examples of abilities followed by double attack procs, this time on fully buffed Bis bear tank:
![image](https://user-images.githubusercontent.com/96207326/197163129-64f242e7-1a07-4754-bbe1-5956b4dd9cd0.png)
![image](https://user-images.githubusercontent.com/96207326/197163171-06d8862a-4cb9-46e4-bf4c-2ab45fbf466a.png)
All these attacks happed simultaneously with no chance of counter reaction.

**Comment by BeefSteaker** [comment]
Confirmed. Will be fixed by [13482](https://github.com/azerothcore/azerothcore-wotlk/pull/13482)
