### ISSUE TITLE
[Quest] Baristolth of the Shifting Sands disapear from Silithus

### ISSUE THREAD

**Issue by Drugadu** [chromiecraft/chromiecraft#4261]
### What client do you play on?

esES

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

I took the quest "What Tomorrow Brings" some weeks ago and yesterday when i came to Silithus after visiting Caverns of Time in Tanaris the NPC Baristolth of the Shifting Sands desapears so i can't star the reputation for Brood of Nozdormu to take AQ40 tier.
![Baristolth of the Shifting Sands desapears](https://user-images.githubusercontent.com/95693449/197061746-ba8027ba-ebb4-4efd-9c26-7f89485c0c42.png)

### Expected Blizzlike Behaviour

When you take the quest you must go to Tanaris to discover the Caverns of Time you have to back to Silithus to complete the quest "What Tomorrow Brings" talking with Baristolth of the Shifting Sands desapears.

https://www.wowhead.com/classic/quest=8286/what-tomorrow-brings

### Source

https://www.wowhead.com/classic/npc=15180/baristolth-of-the-shifting-sands
https://www.wowhead.com/classic/quest=8286/what-tomorrow-brings
![image](https://user-images.githubusercontent.com/95693449/197061928-85f8f195-1373-402e-9603-35d55f846cdc.png)

### Steps to reproduce the problem

Back Baristolth of the Shifting Sands

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Windows 10 Home 21H2

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hes present now on live, do you still have the issue?
![image](https://user-images.githubusercontent.com/11332559/198347616-30b35350-4076-4ae2-b40d-3b87a8392787.png)

**Comment by Drugadu** [comment]
Yeah sry i already saw few days ago. I forgot to check e-mail and close the issue before.

Thx for all!
