### ISSUE TITLE
[Live][AQ40] Greater Nature Protection Pot at AQ40 absorb about half of the tooltip value

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#4263]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

Item: https://wowgaming.altervista.org/aowow/?item=13458
In accordance with today's raid and testing at PTR (10+ tries), seems like GNPP absorb only half of total value. We tested it not only with addon but also just with absorb messages on screen than math to calculate total value. Screenshot 1: 
![изображение](https://user-images.githubusercontent.com/104144379/197068195-e7ce0d72-7291-43dd-b454-ac4a6dda6ec0.png)
Screenshot 2: 
![изображение](https://user-images.githubusercontent.com/104144379/197068244-c985b9a9-0345-4417-878c-1b42deda934b.png)

You can see at both screenshots that absorb value is lower that min value at tooltip (1950).

### Expected Blizzlike Behaviour

GNPP should asorbs 1950 to 3250 nature damage. 

### Source

'https://wowgaming.altervista.org/aowow/?item=13458 - tooltip

### Steps to reproduce the problem

1. Go to AQ40.
2. Engage Huhuran.
3. Drink GNPP and observe absorb value.
4. Do some tries to confrm that low absorb value wasn't just a bad RNG.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Win10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft Live and PTR (same version rn) - AzerothCore rev. b427e8e18cb6+ 2022-10-17 04:28:24 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by 55Honey** [comment]
It is an absorb effect, which is affected by the applied tuning for heals and absorbs.

**Comment by kerricsson** [comment]
Thanks for answer. Any other developer opinions about that?

**Comment by Salehyn** [comment]
Consumables weren't tuned up with wrath the way player healing spells were. There is no sense in custom healing nerf screwing up absorb pots. It also shouldn't apply to anything like Health stones.
Can someone confirm if this issue was resolved yet?

**Comment by FrancescoBorzi** [comment]
> Can someone confirm if this issue was resolved yet?

no confirmation for a long time. Closing this. Feel free to reopen it in the future if you think it still makes sense.
