### ISSUE TITLE
Warlock and Mage Minions don't regenerate mana after respawn in BGs

### ISSUE THREAD

**Issue by EternitysEnd** [chromiecraft/chromiecraft#4272]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

After you've been killed in BG, you respawn with full Mana and HP, but your pet/minion does not. It respawns with the same amount of mana it had before it died.

### Expected Blizzlike Behaviour

The pet/minion should respawn with full Mana like it respawns with full HP.

### Source

https://wowpedia.fandom.com/wiki/Battleground

Graveyards

One of the key differences between battlegrounds and arena is that in battlegrounds, players can die any number of times without penalty. Upon death, players can choose to release from their corpses, at which point their ghost appears at a nearby graveyard. There a Spirit Guide resurrects all nearby players on a regular cycle, with a dialog box displaying the time until resurrection. **_Unlike Spirit Healers found in the rest of the world, players resurrected by Spirit Guides are restored to full health and mana, as are any pets or minions_**. Resurrected players also gain a "Preparation" buff similar to that granted before the beginning of the match, reducing power costs of all spells and abilities to zero for a few seconds.

### Steps to reproduce the problem

1. Enter a BG
2. Use up some of your pet's Mana
3. Die
4. Mana isn't recovered

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Related: https://github.com/TrinityCore/TrinityCore/issues/873

**Comment by Salehyn** [comment]
Confirmed. On CC the pet doesn't recover mana at all. 
1) If the player dies with the pet alive, pet will spawn with the mana it had when the player died. 
2) If the pet dies before the player, the pet will spawn with 0 mana.
![WoWScrnShot_091623_021712](https://github.com/chromiecraft/chromiecraft/assets/134880284/fe377898-e265-4bad-818c-a2e3d0366b1d)

Intended behavior: pet spawns with base health/mana values and then gets healed to 100% mana and health 1second later.
As shown here from classic: https://www.youtube.com/watch?v=Fpw1dJU1CNg at 30:15

**Comment by Salehyn** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/15894 already known issue on AC
