### ISSUE TITLE
Stacked mining nodes in Duskwood

### ISSUE THREAD

**Issue by evelynparenteau** [chromiecraft/chromiecraft#4296]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Several instances of stacked mining nodes in Duskwood.

<img width="559" alt="Screenshot 2022-10-25 at 9 55 33 AM" src="https://user-images.githubusercontent.com/97715535/197838070-66267530-7416-4168-968e-c828daade89d.png">

<img width="548" alt="Screenshot 2022-10-25 at 9 57 04 AM" src="https://user-images.githubusercontent.com/97715535/197838117-155ae10b-f8bc-4a12-86c4-0f8135fe158b.png">

There also looked to be several instances of stacked nodes inside the nearby cave (subzone Roland's Doom), but I was not high enough level to go in and confirmed.

### Expected Blizzlike Behaviour

At most 1 node spawned in each location at a time, which may be one of:

- Copper Vein
- Tin Vein
- Silver Vein
- Gold Vein
- Iron Deposit

### Source

Copper Vein: https://wowgaming.altervista.org/aowow/?object=1731
Tin Vein: https://wowgaming.altervista.org/aowow/?object=1732
Silver Vein: https://wowgaming.altervista.org/aowow/?object=1733
Gold Vein: https://wowgaming.altervista.org/aowow/?object=1734
Iron Deposit: https://wowgaming.altervista.org/aowow/?object=1735

### Steps to reproduce the problem

No player action necessary - they were spawned like this when I found them.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, thanks for the report.
 this is a known issue with nodes in general and is being worked on https://github.com/chromiecraft/chromiecraft/issues/2881
