### ISSUE TITLE
MINING BUG!

### ISSUE THREAD

**Issue by bierbs** [chromiecraft/chromiecraft#43]
![WoWScrnShot_020521_151354](https://user-images.githubusercontent.com/78600676/107039989-4a70ee80-67c7-11eb-84e9-f0a6240386fb.jpg)

**Comment by bierbs** [comment]
cant learn smelt tin

**Comment by FrancescoBorzi** [comment]
@bierbs hello, please open a new issue and fill the template with the requested information. Thank you.

![image](https://user-images.githubusercontent.com/75517/107050075-1e576c80-67cb-11eb-94a2-63c244026247.png)
