### ISSUE TITLE
[AQ40] Twin Emporers Blizzard frequency

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4312]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Blizzard is cast every 5 to 12 seconds.

### Expected Blizzlike Behaviour

Watching some videos, it seems that blizzard is casted a max of twice between teleports, usually just once.
Unfortunately, it is only tracked in public combatlogs if people are affected by the debuff or take damage (being affected by the debuff should be sufficient tho for tracking)

a random cast frequency between 10 to 20 seconds seems more reasonable.

### Source

e.g.
https://www.youtube.com/watch?v=4CmadeEllDk
https://vanilla.warcraftlogs.com/reports/RyYpF9arvbf7XZCm#fight=31&type=auras&view=events&spells=debuffs&ability=26607
https://vanilla.warcraftlogs.com/reports/2MDX7whKZg8PCb6d#fight=42&view=events&type=auras&spells=debuffs&ability=26607

Logs are a bit tricky, cause 1) people may run into it after it has been cast already (esp. considering that it is no real threat in classic)

### Steps to reproduce the problem

see code.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
and as blizzard lasts 8 or 10 seconds, I would also thing is not supposed to have 2 active blizzards at a given time.

**Comment by Contrubius** [comment]
From my testing on PTR, Vek'Lor casts Blizzard every 8 seconds frequently, since Blizzards last for 10 seconds (as on Classic), for 2 seconds there are 2 Blizzards active at a given time, and that happens frequently also. 

From my review of of Classic video encounters, Blizzard cast from Vek'lor can go up to 1 minute without being cast, but I have also seen one instance of it being cast back to back (after 1 Blizzard, 10 seconds after another one was cast on a different location) but it is nowhere nearly as frequent as currently on the PTR and Live.

Videos observed: https://www.youtube.com/watch?v=4CmadeEllDk
https://www.youtube.com/watch?v=WXOSBlws4nM
