### ISSUE TITLE
A Solvent Spirit combat issues with water based enemies

### ISSUE THREAD

**Issue by VampguyN** [chromiecraft/chromiecraft#4321]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

1-19

### Current Behaviour

So I've had this issue work differently on two different toons. My orc shaman tried to cast from range, and they evade and reset hp, so I swim into them, they properly aggro and let me melee dps them down for quest items..  on my troll hunter, i can not melee dps them, I swim to them, get aggrod, they attack me while i sit their frozen in combat unable to strike or use attacks from range or melee. I get stuck with arm out holding weapon until I flee to sen'jin village log off and back on. The enemies are Crawlers and Makura Clackers giving me an issue. My hunter can't get through the quest swimming to them and staying on the surface or deep down on the ocean floor. But that fixes it for my orc shaman and he could complete the quest. My hunter can not complete this quest at all. 

### Expected Blizzlike Behaviour

Attacks to cause the enemies to move towards me and I expect attacks to go off at least and be attempted.

### Source

DB GUID 7392 Surfcrawler
DB Guid 7392 Makura Clacker

### Steps to reproduce the problem

1) Senjin village and south east to the shore in durotar
2) ranged attack surf crawler and makura clacker by bow
3) they evade and stay full health and motionless
4) swim up to melee
5) sometimes the melee weapon stays out but there is no attack or animation of an attack. And I just sit there motionless while the makura and surfcrawler begin to attack me. 
6) I lost 80% of my health not attacking back, before I fled back to Sen'jin village. 
7) dagger was stuck in arm out. So a log off and on returned me to non combat regular stance.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by VampguyN** [comment]
https://user-images.githubusercontent.com/116185642/198388919-419d3861-4c2b-491e-a920-44bf6840a606.mp4

The reproduce on the PTR

**Comment by Pyromanihack** [comment]
Duplicate from https://github.com/azerothcore/azerothcore-wotlk/issues/6784
