### ISSUE TITLE
[Swing timer] Dual wield Bug

### ISSUE THREAD

**Issue by Hogofogo1** [chromiecraft/chromiecraft#4325]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

When I melee a dummy and have weapon at 2.9 (Deathbringer) and 2.8 (Empyrean Demolisher) it never happens that the Empyrean gets in front of the Deathbringer.
Also when I use Weakauras swing timer at some point WA gets confused because it expects the faster weapon to go ahead of the slower one. They hit at the same time as the MH finishes the swing while MH is leading.
Seems to be an issue with how the [UNIT_ATTACK_SPEED] is calculated.

### Expected Blizzlike Behaviour

Faster weapon should get ahead of the slower one eventually.

### Source

Live nad PTR

### Steps to reproduce the problem

1. Equip MH Deathbringer, OH Empyrean Demolisher
2. Set WA swing timer for MH and OH
3. check combat log and see that the faster weapon is still behind the slower one
4. WA expects the faster weapon to go ahead of the slower one and yet they still hit at the same time with MH leading

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Hogofogo1** [comment]
Tested some more with MH 2.3 and OH 2.1 weapon, the OH never gets ahead of the MH, thats why WA swing timer is confused.
On screenshot Top swing is MH and bottom OH and in combat log that goes from bottom to top the MH leads and OH follows - Meaning they switched position as WA expects the Oh to get ahead of the MH. They hit at the same time as the MH finishes the swing while MH is leading.
![WoWScrnShot_102822_133210](https://user-images.githubusercontent.com/97225391/198579085-7aa5570c-f453-4052-8b2a-dd5b8b5787e8.jpg)

**Comment by davegrier** [comment]
Tested OPs setup (2.9s Deathbringer mainhand and 2.8s Empyrean Demolisher offhand) using the ElvUI Swing Timer plugin. There are some visual stutters when procs occur, but the faster offhand catches up to and syncs with the slower mainhand after 29 offhand swings, which is expected since it's 0.1s faster each swing. Repeated the test with a 2.6s MH and a 2.8s OH, and the MH overtook and synced up with the OH after 14 swings, as expected.

Dual wield swing timing appears to be working correctly.  

https://user-images.githubusercontent.com/14080595/202348035-f5e072c2-de11-42be-a702-4578b462cc26.mp4

**Comment by Hogofogo1** [comment]
When you compare the swing timer to combat log then after around 20s of autoattacking you reach a state where you hit with both weapons at the same time (as in combat log) but in swing timer it looks like you are ignoring the Main hand and hit the target at the exact moment your Off hand lands.
Swing timer says Main hands lands first, but combat log says off hand lands first
At this stage you hit with both weapons at the same time the moment off-hand finishes in your swing timer
Image
Image
This somehow plays a role in why Main and Offhand switch position in Weak auras
