### ISSUE TITLE
[Report]: Hallow's End Treats for Jesper's - "Sub Quests" Still Available After Main-Q Complete

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#4327]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### The Quest **(Main)**:
- [Hallow's End Treats for Jesper!](https://www.wowhead.com/quest=8311/hallows-end-treats-for-jesper)
is the [Hallow's End](https://www.wowhead.com/event=324/hallows-end) Event Quest.

To complete this Quest, you need to finish 4 additional Sub-Quests that provide you with the Quest Items required by the Main Quest.
### [SUBs]:
- [Flexing for Nougat](https://www.wowhead.com/quest=8356/flexing-for-nougat#comments:id=2774071)
- [Incoming Gumdrop](https://www.wowhead.com/quest=8355/incoming-gumdrop)
- [Chicken Clucking for a Mint](https://www.wowhead.com/quest=8353/chicken-clucking-for-a-mint)
- [Dancing for Marzipan](https://www.wowhead.com/quest=8357/dancing-for-marzipan)

Theoretically, once the Main Quest [Hallow's End Treats for Jesper!](https://www.wowhead.com/quest=8311/hallows-end-treats-for-jesper) is completed, the other quests should disappear and should no longer be repeatable. However, they continue to remain available.

### In the video below, I demonstrate the bug.
[![Anteprima](https://user-images.githubusercontent.com/1884642/261620185-4cda2168-77ad-4799-a7cb-996fffbb735e.png)](https://www.youtube.com/embed/M_v7YmvemEk)

### Expected Blizzlike Behaviour

The Sub Quests of "Hallow's End Treats for Jesper!" shouldn't be repeatable once "Hallow's End Treats for Jesper!" has been completed.

### Steps to reproduce the problem

.quest add 8311
.quest complete 8311
.go c 86169
Deliver the quest to the NPC: [Jesper](https://www.wowhead.com/npc=15310/jesper)
Visit the other 4 NPCs and you will see that the Sub-Quests are still available.
- [Innkeeper Allison](https://www.wowhead.com/npc=6740/innkeeper-allison)
- [Talvash del Kissel](https://www.wowhead.com/npc=6826/talvash-del-kissel)
- [Innkeeper Firebrew](https://www.wowhead.com/npc=5111/innkeeper-firebrew)
- [Dancing for Marzipan](https://www.wowhead.com/quest=8357/dancing-for-marzipan)

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=8356
https://wowgaming.altervista.org/aowow/?quest=8311

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by The-GhostRider** [comment]
**Thanks for your Report and your Time, but it's a Visual Client Bug as demonstrated by my VIDEO:**
[![Anteprima](https://user-images.githubusercontent.com/1884642/251302735-976bc2b8-ee0e-461f-b952-ced5544e081d.png)](https://www.youtube.com/embed/V9YQBc-Sw4k)


**For this reason I close the Report.**

**Comment by The-GhostRider** [comment]
> Thank you for taking some time looking at this issue, but you have not understood the issue at hand and your video displays the issue.
> 
> The quest Flexing for Nougat should not be there when you are not on the quest Hallow's End Treats The blue question mark is not the issue at hand and was just part of the screenshot to demonstrate the quest being available

And so, I need you to explain to me in real detail what the problem is.
Because at this point it seems obvious to me that there is something obvious to you that isn't obvious to me. (excuse the pun)
So I need more details to understand what your point is, thanks.

**Comment by The-GhostRider** [comment]
> Just follow the steps I have posted

Are you kidding me or didn't you read my last message to the end and also didn't even see my last video?

If you watch the video you will see that the Flexing for Nougat quest can not be taken until you complete Hallow's End Treats, so there is no Bug and the report can be closed..

**Comment by Tereneckla** [comment]
I saw your video where you didn't even pick up the quest Hallow's End Treats
My report is about Flexing for Nougat staying available **AFTER** you completed Hallow's End Treats

**Comment by The-GhostRider** [comment]
> I saw your video where you didn't even pick up the quest Hallow's End Treats 

![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/ba85b082-45ba-44df-92ac-0d4f62ae59f3)

**Comment by Tereneckla** [comment]
Ok, I wrote that part too fast. Now read the second sentence again and/or follow the instructions

Complete Hallow's End Treats for Jesper and then return to the Innkeeper

**Comment by The-GhostRider** [comment]
> Flexing for Nougat staying available AFTER you completed Hallow's End Treats

I really can't understand what you mean..
To me what you say doesn't make sense, unless you're mis-explaining the problem or offsetting the result via GM commands.

Because the "Flexing for Nougat" quest doesn't appear until you complete the "Hallow's End Treats" quest, so when you tell me: "Flexing for Nougat staying available AFTER you completed Hallow's End Treats" it makes no sense to me..

**Comment by The-GhostRider** [comment]
> Flexing for Nougat gives you a quest item for Hallow's End Treats It becomes available after accepting Hallow's End Treats and should not be available after turning in Hallow's End Treats

@Tereneckla 
![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/4e9fc388-689a-4ec5-8d69-afc3327d1352)


Question: Do you know how often Quest: **"Flexing for Nougat"** is repeatable?
I mean.. it's repeatable:
- Once a year?
- 1 time in the character's life?
- Once a week?
- 1 time per day?

**Comment by The-GhostRider** [comment]
@Tereneckla 
I have modified your Report.
In this way, written like this, it is an "UNDERSTANDABLE" Report.

You have to think that not everyone can have "Clear" or "Obvious" some nuances or details on a certain dynamic, so it is essential that the Report is not clear, but "Very clear".

Because whoever does the Triaging must understand what you are talking about, the nature of the Bug, the NPCs, Quests, GOs, etc..etc.. interested.. and everything there is to know about it.
