### ISSUE TITLE
Pilgrim's Bounty calendar

### ISSUE THREAD

**Issue by bojan112** [chromiecraft/chromiecraft#4328]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Pilgrim's Bounty not showing on calendar

### Expected Blizzlike Behaviour

both start and end date should be shown

### Source

![WoWScrnShot_102822_220719](https://user-images.githubusercontent.com/14837349/198723723-eab19025-38c0-4232-b82f-2bab0cfc6327.jpg)

### Steps to reproduce the problem

open calendar
switch to novemeber
have active holidays active
no pilgrims bounty

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Its weird, but i dont think it was on the calendar in 2010 when 3.3.5a was current, perhaps due to it being only introduced in 3.2.0

using the waybackmachine you can see that pilgrims bounty was on the 22-28 of november
https://web.archive.org/web/20101107211939mp_/http://www.worldofwarcraft.com/info/events/pilgrimsbounty/

on this website its not visible on the 28th
![image](https://user-images.githubusercontent.com/11332559/198899683-8fe70a8f-b5b1-43e2-966e-b1d1cc301f84.png)
https://www.engadget.com/2008-11-06-blizzard-calendar-vs-group-calendar.html

**Comment by BeefSteaker** [comment]
Thanks for the report, pilgrims bounty is disabled on chromiecraft and so doesn't show up on the In game calendar.
