### ISSUE TITLE
Shaman Flametounge Enchantment with dungeon finder loot

### ISSUE THREAD

**Issue by fractalWizard** [chromiecraft/chromiecraft#433]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When you have a weapon that is tradeable (for a window) from dungeon finder [ie, when it says "this item is tradeable to other eligible members for X amount of hrs minutes seconds in light blue text on the tooltip] and you use an ability such as "Flametounge Weapon", every time you use it, the "Are you sure? this will make the item untradeable" dialog will pop up, even if you had hit yes before. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

An action that was described as making something untradeable should make it untradeable when you press yes on the dialog the first time.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Receive loot from a loot roll that will remain tradeable with other dungeon members for 2 hours. (in this case, it was a blue mace from the first boss of Deadmines.)
2. Use flametounge weapon (either in or out of instance party, the bug works as long as the blue text is there)
3. Press yes on "Are you sure?" dialog
4. Use flametounge weapon again.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@fractalWizard 

Thank you for your report, unfortunately this information is not enough, because: you have described the problem very well, but to test it, we need to know more information.
For example:
- What weapon was that? (please put a link)
- What dungeon were you in?
- Does this problem only arise with the shaman's enchants?

**Comment by Excelsus90** [comment]
Had the same issue with https://wowgaming.altervista.org/aowow/?item=5201 and the flametounge enchant. Did not try something else.

**Comment by Azcobu** [comment]
I think this was resolved in https://github.com/azerothcore/azerothcore-wotlk/pull/7160, closing accordingly.
