### ISSUE TITLE
Blazerunner infinite knock back #2

### ISSUE THREAD

**Issue by Joy-ccraft** [chromiecraft/chromiecraft#4333]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Please see baranzadeoglu's original bug report: https://github.com/chromiecraft/chromiecraft/issues/1387

### Expected Blizzlike Behaviour

Please see baranzadeoglu's original bug report: https://github.com/chromiecraft/chromiecraft/issues/1387

### Source

Please see baranzadeoglu's original bug report: https://github.com/chromiecraft/chromiecraft/issues/1387

### Steps to reproduce the problem

Go to Ungoro
49.6 49.6
Engage Blazerunner
Observe

### Extra Notes

I do not understand why this bug was declared invalid. ChromieCraft should acquire a Classic account for the sake of seeing Blizzard’s intent. Having originally done this quest, not using the quest item to remove Blazerunner’s aura, I remember our tank taking a few knockbacks but nothing like this.

The only videos available involve fights where the aura has been dispelled, however, we can think about how such abilities are generally modulated in the rest of the game, where I cannot think of any NPC who is not subject to a proc rate or a cooldown.

The level design involves a lava lake with patrolling adds near the mouth of a cavern and an elite NPC given a knockback ability. However, in my experience the lava never even came into play - Blazerunner kicked me out before I could take damage.

To illustrate the absurdity of the current state, my lvl 60 druid engaged Blazerunner from the cave opening and was promptly kicked off the volcano, down into the valley and beyond aggro range. 

The most comedic experience, however, was casting Force of Nature into Blazerunner’s lair: my poor treants went bouncing off the cavern walls like popcorn sizzling in a boiling pot.

In summary, what I recall most about Blizzard’s Blazerunner was how relatively easy he was, despite of the quest descriptions ominous warnings. The knockback proc was not especially high, maybe 25%, probably less. More concerning to lower level players was likely the damage reduction.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
knockback doesnt seem to bad on the ptr at least, knoks you back 10 or so feet.
do you have any footage of how it should act without the item that disables it?

**Comment by Joy-ccraft** [comment]
May I kindly and respectfully suggest to actually read the bug reports, please? 

This bug pertains to the frequency of the knockback: frequency means how often the knockback effect may trigger.

This is why I long stopped reporting bugs; it is simply too time consuming and too exasperating.

**Comment by The-GhostRider** [comment]
> May I kindly and respectfully suggest to actually read the bug reports, please?
This bug pertains to the frequency of the knockback: frequency means how often the knockback effect may trigger.
This is why I long stopped reporting bugs; it is simply too time consuming and too exasperating.

Hi @Joy-ccraft, thank you for your report and for your time.
The bug that you believe is a bug is actually an intentional game mechanic because this is how the quest is designed to work.

You linked this Report in your report as reference: https://github.com/chromiecraft/chromiecraft/issues/1387
But did you also read the comment from the contributor who closed that report? https://github.com/chromiecraft/chromiecraft/issues/1387#issuecomment-897614067
![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/ecb7b8dd-f654-4447-abee-3da4064e704a)

### **If you need more details, check out this video I made especially for you.:**
[![Anteprima](https://user-images.githubusercontent.com/1884642/251310614-d9b09eff-1711-4f47-9acf-0b51a994ac5f.png)](https://www.youtube.com/embed/ltq7OsBjjS0)


**For this reason I close the Report.**
