### ISSUE TITLE
[Zangarmarsh] Incorrect factions for some quests

### ISSUE THREAD

**Issue by Santaria94** [chromiecraft/chromiecraft#4351]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Incorrect factions for some quests. In general, these quests seem to be impossible to get for the opposite faction, since the faction of questgivers is indicated correctly. But for a web database it can be useful.

I found this information with a fix on TrinityCore and it seems to be relevant for AzerothCore.
https://github.com/TrinityCore/TrinityCore/issues/23151

### Expected Blizzlike Behaviour

See list here:
https://github.com/TrinityCore/TrinityCore/issues/23151

### Source

https://github.com/TrinityCore/TrinityCore/issues/23151

### Steps to reproduce the problem

Check the quests from the list above in the database

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
I checked several quests from https://github.com/TrinityCore/TrinityCore/issues/23151 and seems that the DB it's a bit strange:
![zanga](https://user-images.githubusercontent.com/82369562/210059247-206c4016-5f0e-4dbb-b1ec-d9dabfe43472.png)
In the quest template, the "Allowable races" is 0 (in this way nobody can take it) but in my local server everything is ok (in this particular quest alliance can take it, while horde can't

**Comment by Pyromanihack** [comment]
@Santaria94 do you remember which quests, in particular, seem to have problems?

**Comment by FrancescoBorzi** [comment]
closing as not enough info. Feel free to bring this up again and we will reopen it.
