### ISSUE TITLE
Auction House post about sell not disappearing after gold arrival

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#436]
#### WHAT CLIENT DO YOU PLAY ON?

- [x] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When an auction you inserted into the auction house is bought, you receive a in-game mail. One hour later you receive the gold reduced by the costs. The notification mail for the sell does not disappear.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

when receiving the mail containing the gold, the notification mail should disappear from the inbox.

##### STEPS TO REPRODUCE THE PROBLEM:

1. insert auction into auction house
2. buy item from a different account
3. see the first mail arrive
4. one hour later when the gold arrives, the first mail should disappear

##### EXTRA NOTES:

There might be different behavior if you are online during the sell or the 1h period - or open the mail.
but in general those notification mails could be flagged with a 1h disappearing timer instead of 30 days.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by fivepointfiveb** [comment]
can confirm, the other mail does not disappear.

**Comment by FrancescoBorzi** [comment]
@chromiecraft/bug-triaging anyone can triage this, please?

**Comment by necropola** [comment]
From my experience the **Pending Mail** stays longer in the mailbox than it takes for the money to arrive but it disappears (expires) withing significantly less than a day.

The **Money Mail**  is delayed (I've tested it) by `MailDeliveryDelay` from `worldserver.conf` (default: 3600 seconds = 1 hour) and the **Pending Mail** arrives immediately on sale of an item.

It looks like the **Pending Mail** is supposed to have exactly the expiration time that the **Money Mail** is delayed for, but this is obviously not what happens, i. e. you have them both in your mailbox, At least for a while. Need to dig deeper ...
https://github.com/azerothcore/azerothcore-wotlk/blob/0ca8692592bf000d90cf09351b1ad231a2aa0ebc/src/server/game/Mails/Mail.cpp#L193-L195

**Comment by j-hdt** [comment]
issue was solved mid/end last year and re-appeared about a month ago

**Comment by UltraNix** [comment]
Broken by #8065
