### ISSUE TITLE
Zul'Farrak door not opening

### ISSUE THREAD

**Issue by deadhill** [chromiecraft/chromiecraft#4365]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

After sending the goblin to blow open the door, he placed the explosive next to his starting bomb and ran away without going to the door

### Expected Blizzlike Behaviour

The gobling should go to the door, place an explosive and blow open the door

### Source

![image](https://user-images.githubusercontent.com/109695669/199249155-9a5dc457-a424-443e-8a6f-a93cbccdcfd7.png)

### Steps to reproduce the problem

1. go inside ZF
2. do the stairs event
3. talk with the goblin

### Extra Notes

The position where my character is standing at is where the goblin placed the explosive

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
event works fine on my end
https://user-images.githubusercontent.com/11332559/199769152-fbe19e25-876d-4978-a334-08de7c3fc86c.mp4

**Comment by deadhill** [comment]
This seems to not happen always, but some other people have said that it has happened to them aswell
![image](https://user-images.githubusercontent.com/109695669/199988071-7da6abc0-b4b2-4fa5-a3a6-e9afaec44cd3.png)
as you can see these people werent in my group. Only other thing that might help in the bug happening is if you talk to the goblin as fast as possible after the stair event ends
