### ISSUE TITLE
[Azuremyst Isle] Cheerful Draenei Spirit does not give [The Grateful Dead] quest

### ISSUE THREAD

**Issue by jadziaaa** [chromiecraft/chromiecraft#4371]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

For the Day of the Dead event, when you visit the [Azure Watch](https://wowgaming.altervista.org/aowow/?object=181693) graveyard as a Draenei, you can use the marigolds to make spirits visible, but the [Cheerful Draenei Spirit](https://wowgaming.altervista.org/aowow/?npc=34484) does not give the quest [The Grateful Dead](https://wowgaming.altervista.org/aowow/?quest=14169). As a result, Draenei players cannot get the [Macabre Marionette](https://wowgaming.altervista.org/aowow/?item=46831). Tried /reload, no change. Partied up with another Draenei player, no change.
![Draenei_DooD_quest_broken](https://user-images.githubusercontent.com/117219990/199330712-bf415ac9-0464-4872-9c3d-71905e6dce19.jpg)

### Expected Blizzlike Behaviour

[Cheerful Draenei Spirit](https://wowgaming.altervista.org/aowow/?npc=34484) in the [Azure Watch](https://wowgaming.altervista.org/aowow/?object=181693) graveyard should give [The Grateful Dead](https://wowgaming.altervista.org/aowow/?quest=14169) quest, which upon completion should reward [Macabre Marionette](https://wowgaming.altervista.org/aowow/?item=46831).

### Source

https://youtu.be/jpHekY08jwQ?t=69 (this video takes place in Dalaran, but it's the only version of the quest I could find on YouTube. as you might imagine, the name of the quest makes it rather difficult...)

### Steps to reproduce the problem

be a Draenei who has not already completed [The Grateful Dead](https://wowgaming.altervista.org/aowow/?quest=14169)
.go 120103 (current GUID; if not working try .go 240273)
use [Bouquet of Orange Marigolds](https://wowgaming.altervista.org/aowow/?item=46861)
talk to [Cheerful Draenei Spirit](https://wowgaming.altervista.org/aowow/?npc=34484)
look at screen
quest [The Grateful Dead](https://wowgaming.altervista.org/aowow/?quest=14169) does not appear and cannot be completed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Bassbone11** [comment]
![Screenshot (47)](https://user-images.githubusercontent.com/112593065/199331511-d21b9a94-3e26-4451-926c-46924df1eb01.png)
Its definitely not an isolated problem

**Comment by BeefSteaker** [comment]
Yeah, not working on my local either, ive confirmed it
