### ISSUE TITLE
Bugged Barrens Kodo

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#439]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

A Barrens kodo is currently displayed as "Unknown".
![WoWScrnShot_041821_192702](https://user-images.githubusercontent.com/81818678/115154678-68d35000-a07c-11eb-81af-06cbbb82a03a.jpg)
DB GUID: 15135, current GUID: 15135
The other two kodos are "regular" Barrens Kodos.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The "Unknown" Kodo should be a regular Barrens Kodo.

##### STEPS TO REPRODUCE THE PROBLEM:

As the kodos roam accross the Barrens, it's not easy to find them...

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by r-o-b-o-t-o** [comment]
Hello, this was most likely a problem with your client (see https://github.com/chromiecraft/chromiecraft/issues/229#issuecomment-801313664).
A `/reload` or emptying your game cache and restarting the game would have probably fixed it, it's probably not a server-side issue.

**Comment by Helias** [comment]
I agree with @r-o-b-o-t-o, it could also be a connection issue
