### ISSUE TITLE
[AQ40] Ouro doesn't use any abilities when no one is in melee range

### ISSUE THREAD

**Issue by mctscc** [chromiecraft/chromiecraft#4391]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Ouro stops using any abilities when there is no one in melee range.

### Expected Blizzlike Behaviour

He should throw rocks at the raid if no melee is in range.

### Source

https://www.wowhead.com/classic/npc=15517/ouro

![obraz](https://user-images.githubusercontent.com/117408687/199845279-77206a5c-4205-4ff7-af5f-b797f5a3ef17.png)

### Steps to reproduce the problem

1. .go xyz -9109.23437 2093.418459 -61.778175 531
2. go to distance to get combat
3. move away

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, mctscc, thanks for reaching out!

While not enraged (Phase 1) if there's no one in melee range Ouro will submerge after 10-13s
Boulder is cast only during Enrage phase, after reaching low health, Ouro will not submerge anymore and will cast Boulder if there's no one in melee range. The current implementation is correct.

**Comment by mctscc** [comment]
It is not. One dps can kill Ouro.

**Comment by Gultask** [comment]
What do you mean?

**Comment by mctscc** [comment]
I wrote an issue, spent some time. Didn't have to do that. You didn't even reproduced it and closed in 5 minutes. I felt disrespected. Watch it. Ouro is a new target dummy.

https://www.youtube.com/watch?v=1Jqg-yKhBzU

**Comment by Gultask** [comment]
It looks like it isn't submerging then. Weird, I've never seen it before. I'll take a look when I can, sorry about that.

**Comment by Gultask** [comment]
I'll keep trying, but for now this is what I'm getting:

https://user-images.githubusercontent.com/100873791/199852565-52438397-2d42-47e9-abc5-908772cd3029.mp4

**Comment by mctscc** [comment]
The trick is to never get to melee to reproduce it every time. 
We had raid this night and Ouro bugged on enrage phase (about 8% hp left). All died except few range dps. They finished it off because of this bug.

**Comment by mctscc** [comment]
I made few tries. When i get close to him at pull he **targets** me and it works like you said. 

![obraz](https://user-images.githubusercontent.com/117408687/199854292-271e6258-065d-4917-886f-7546f8a37954.png)


But when i pull from max distance and move immediately he has no targets

![obraz](https://user-images.githubusercontent.com/117408687/199854195-b6d628fb-dccf-484a-9784-0d028b9da438.png)

**Comment by Gultask** [comment]
Thank you! I've been able to reproduce it now!
