### ISSUE TITLE
Hunter pet disappeared in Dire Maul North

### ISSUE THREAD

**Issue by pewpewgit** [chromiecraft/chromiecraft#4392]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

- In combat, on ledge above door to library.
- Casted eyes of the beast and agroed mobs under the right arches.
- While in eyes of the beast with the mobs agroed, run toward ledge.
- Pet gets knocked up in the air a few times while running to ledge.
- With eyes of the beast, have pet jump off the ledge . Not sure if I cancelled eyes of the beast in midair or not. Pet also might have been cced when eyes of the beast was cancelled.
- Send pet to attack [Guard Mol'dar]. (not sure at this point if the pet is still there)
- I feign death. (pet could still have existed before feign) (after feign 100% gone)
- Pet is gone. Seems like there was no pet at all.
- No pet in current pet stable slot.
- Pet actions (call pet, dismiss pet, revive pet) respond as if no pet exists. ("You do not have a pet", "You do not have a pet to summon", etc).

### Expected Blizzlike Behaviour

- After cancelling Eyes of the Beast, the pet should still exist.
- Not sure how to source this. Any clip of eyes of the beast I suppose. Couldn't find one on confirmed 3.3.5.

### Source

https://wowgaming.altervista.org/aowow/?spell=1002

### Steps to reproduce the problem

1. In combat with first orge dude inside DMN.
2. Run around ledge until you reach the wood scaffolding looking thing.
3. Cast eyes of the beast, agro the mob pack under the right arch.
4. While in eyes of the beast, run toward the ledge, (pet was knocked up at least twice during this, not sure how you could replicate that)
5. While in eyes of the beast, jump off the ledge.
6. While in eyes of the beast, either in mid air, or right after hitting the ground (not sure if also cced) cancel eyes of the beast.
7. Send pet to attack the guard in the courtyard with /petattack. (at this point pet could have already been gone)
8. Feign death (at this point pet could already be gone)
9. As result of feign death, leave combat. (Pet is 100% gone at this point)

### Extra Notes

- Going to the stable master shows no pet in the current slot. It is as if the pet never existed.
- No further options to recover the pet after selecting "I'm looking for a lost companion."

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by The-GhostRider** [comment]
Hi @pewpewgit, thank you for your report and for your time.
While reading your report, the dynamics of how the issue occurred made me laugh a lot because I could imagine the scene. I've seen all sorts of funny and bizarre things happen with Hunter pets, whether on a Retail or Private server.

That being said, I tried to reproduce the bug, but I couldn't succeed. I have come to the conclusion that the most obvious explanation for what happened is that your pet was "Unhappy." Perhaps you didn't have time to feed it, and during the dungeon fight, the pet must have reached maximum unhappiness. When the pet was launched in the air and separated from you, it was dismissed, and since it was unhappy, you lost it. This is a normal mechanic for Hunter pets (losing them if they are unhappy).

So since the Bug is not reproducible, and it's very likely you lost it because the Pet was Unhappy, I think this is a classic case of **"Occam's Razor"**

https://simple.wikipedia.org/wiki/Occam%27s_razor
![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/bf5f5945-a8a0-4ce3-9059-1e756469b611)

For this reason I close the Report.
