### ISSUE TITLE
Defias Messenger sometimes does not respawn

### ISSUE THREAD

**Issue by Stradivarius0** [chromiecraft/chromiecraft#44]
##### SMALL DESCRIPTION:
https://classic.wowhead.com/npc=550/defias-messenger
A server restart may fix it but that doesn't help to find what situation is glitching him.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
He should respawn in front of Moonbrok's blacksmith 5 minutes after he disappears in the mine, confirmed that he actually does this on another compiled AC.

##### CURRENT BEHAVIOUR:
He has not respawned in the last 12 hours in chromiecraft, we checked on different times with multiple people spamming /tar Messenger, I personally camped his only spawnpoint for 1 hour.
![WoWScrnShot_020521_115940](https://user-images.githubusercontent.com/78606641/107052288-3d92d180-67ac-11eb-871e-47d7daeecb82.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:
.go c 550 in chromiecraft before we have a server restart

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
.go c 550 will send you to Captain Hecklebury Smotts in Booty Bay. You should use .go c 45525.

**Comment by Stifler82** [comment]
I just checked this NPC: [Defias Messenger](https://classic.wowhead.com/npc=550/defias-messenger)
he reappears exactly 5 minutes after his disappearance.
So the Bug is non-existent.

The reason you didn't find it is because the NPC has a very long path.

[Defias Messenger](https://youtu.be/XwPDGjD5Sx4)

**Comment by Stradivarius0** [comment]
Thank you for taking the time to review it but I'm afraid I mentioned that this has been already tested on a local AC server and we could not reproduce the issue (It worked just like in the video you've shared).

This issue was meant to be reviewed specifically on chromiecraft and  before a server restart occured because a restart would likely reset him and make him work properly again.

As you can see in the screenshot I posted from chromiecraft I waited 1 hour straight at his spawnpoint, clearly there's an inconsistency between the times we are experiencing on both your local server and mine and the times that me and other few people experienced on chromiecraft (from the last 24hrs previous to the issue submission)

However I'm not going to reopen the issue because I'm under the impression this is one of those bugs that may happen once in a thousand times hence making it extremely hard to detect and analyze. Also I'm unaware whether there's been a restart.

Anyway Thank you again for your time!
