### ISSUE TITLE
Copper Ore Node is impossible to mine

### ISSUE THREAD

**Issue by sileniusmike** [chromiecraft/chromiecraft#440]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

This Copper Ore Node is impossible to obtain on its angle.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Shouldn't spawn here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find this copper node and try to mine it
2. 
3. 
4.

##### EXTRA NOTES:

Type here.
![WoWScrnShot_041821_122335](https://user-images.githubusercontent.com/3758326/115156430-83d49e80-a041-11eb-88bd-e22f63760a78.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
@sileniusmike thanks for the report.
Whilst the screenshot is appreciated, if you see things like this in future can you type `.gobj near` in chat and then paste the output in here. That gives us very exact data to deal with.

If you find you can't get close enough for that command to work (the range with no arguments is 10 yeards), you can extend it's range like so: `gobj near 20`

**Comment by jendryk** [comment]
![WoWScrnShot_051821_203206](https://user-images.githubusercontent.com/7814954/118705253-4d449c00-b818-11eb-9670-6376f602a5d3.jpg)
I believe this is the same Copper Vein

**Comment by Stifler82** [comment]
Fixed!
-
![image](https://user-images.githubusercontent.com/1884642/119563379-5fd24e80-bd9f-11eb-8c06-a8c56aebc123.png)
