### ISSUE TITLE
Hunter's Mark won't show right amount of AP + overwrite

### ISSUE THREAD

**Issue by Drundain** [chromiecraft/chromiecraft#4416]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

Hunter's Mark attack power not shown correctly on the debuff icon when talents points are spent in "Improved Hunter's Mark" or the glyph of Hunter's Mark is used. The value stays the same.
Also, the spell is always overwritten even if you use the improved or glyphed version.

### Expected Blizzlike Behaviour

the correct value should be shown correctly on the debuff and it should be non possibile to overwrite by a lesser version of Hunter's Mark.

### Source

game experience

### Steps to reproduce the problem

1. use the improved or glyphed Hunter's Mark on a mob and look at the debuff icon for value
2. try to use the base version of Hunter's Mark to replace an improved or glyphed one

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
Buffs/Debuffs only show the talented, etc values in Cataclysm+

**Comment by Gultask** [comment]
Yes, unfortunately tooltips are linked to the client and can't be modified on our end.

**Comment by Gultask** [comment]
Overwrite is due to it having a lower duration. I'll try to check in Classic if it's the case. Is there a written/visual source for it from Retail-era WotLK? It'd help.

**Comment by Drundain** [comment]
> Overwrite is due to it having a lower duration. I'll try to check in Classic if it's the case. Is there a written/visual source for it from Retail-era WotLK? It'd help.

what do you mean by lower duration? It should be 5 minutes in any case, the talents just improved the ranged AP and decrease the mana cost.

**Comment by Gultask** [comment]
Sorry, I meant it refreshes the duration. Also, I'd like to apologise for not reading it thoroughly and closing early. I've done that more than I'd like :p 
I'll reopen until we get information on priorities. I'll try to get it later today.

**Comment by Drundain** [comment]
no problem at all!
I get the refreshing part, but it should say something like "a more powerful spell is active" etc i think.

**Comment by slicplaya** [comment]
> no problem at all! I get the refreshing part, but it should say something like "a more powerful spell is active" etc i think.

Hunter Marks have always over written each other no matter how powerful or weak they are. It's just one of those things you have to communicate with other hunters to let the person with the buffed one mark every time.

**Comment by Gultask** [comment]
So I finally managed to reinstall the PTR on my laptop and dualbox it.
Here's the results:

- A lower rank of Hunter's Mark cannot overwrite a higher rank, regardless of time left.
- An unglyphed Hunter's Mark can overwrite a glyphed Hunter's Mark.
- An unglyphed and untalented Hunter's Mark can overwrite a talented and glyphed Hunter's Mark.

So, unfortunately, (and understand that I was a hunter main in ChromieCraft) this is blizzlike. 😔
