### ISSUE TITLE
[Hellfire Ramparts] Watchkeeper Gargolmar casts retaliation too early

### ISSUE THREAD

**Issue by clovaek** [chromiecraft/chromiecraft#4431]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

[Watchkeeper Gargolmar](https://wowgaming.altervista.org/aowow/?npc=17306) casts [Retaliation](https://wowgaming.altervista.org/aowow/?spell=22857) at 30%

### Expected Blizzlike Behaviour

Watchkeeper Gargolmar should cast retaliation at 10-20% health (exact figure is difficult due to source material)

### Source

fight in 2008 wotlk:
https://youtu.be/oOCVydMtJ2U?t=333

Fight shows the boss being lower than 30% and has not cast retaliation. When he dips to 10-20% you can see the buff on him.

### Steps to reproduce the problem

.go xyz -1355.391602 1639.706055 68.545120 543 1.054617
.go creature 202692
damage the boss to 29% health
observe him casting retaliation

### Extra Notes

aowow:
https://wowgaming.altervista.org/aowow/?npc=17306
wowhead:
https://www.wowhead.com/wotlk/npc=17306/

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Samsequel** [comment]
Its already set at 20% 
![image](https://user-images.githubusercontent.com/20357406/208313314-6b96871b-5659-43a2-80c7-c1fe9ba4f27d.png)
