### ISSUE TITLE
Mithril Bound Trunk stays in inventory after opening

### ISSUE THREAD

**Issue by suprsokr** [chromiecraft/chromiecraft#444]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

https://wowgaming.altervista.org/aowow/?item=21228

Below screenshot should show:

1. I opened mithril bound trunk (see chat and bolt of runecloth i recieved)
2. Mithril bound trunk is still in my inventory

![image](https://user-images.githubusercontent.com/68826689/115258515-49750b00-a0ee-11eb-87de-532df59be04f.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Mithril bound trunk should disappear on use

##### STEPS TO REPRODUCE THE PROBLEM:
1. Fish up mithril bound trunk (from Booty Bay oil blackmouth fishing pool, if it matters)
2. Open mithril bound trunk

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by ImJustAB3ar** [comment]
I agree this i bugged

**Comment by necropola** [comment]
This can also happen with the lower level chests caught when fishing and is a bug introduced rather recently. I'd say around 2 weeks ago, if I had to guess.

**Comment by mdawx** [comment]
I can't reproduce it. Could you provide some detail? I tested with and without autoloot:

https://user-images.githubusercontent.com/81375770/115312422-964df580-a171-11eb-97bd-78fa9e138749.mp4



And second video i recorded few days ago:
https://www.youtube.com/watch?v=xL-HWh6v1cU

**Comment by necropola** [comment]
I could reproduce it on ym local AC using "Tightly Sealed Trunks (20708)".
It took 100-200 chests to trigger the bug. I think sometimes (rarely) thoses chests are just empty and **before the bug was introduced** they just did not give any loot when opened and **now** those empty chests stay in your inventory after not giving any loot.

**Comment by necropola** [comment]
Confirmed! (see above)

**Comment by mdawx** [comment]
@necropola, tremendous finding! Thanks. 

https://user-images.githubusercontent.com/81375770/115385074-fe372700-a1d7-11eb-81d3-b5da77b3ba75.mp4

**Comment by j-hdt** [comment]
it must also been a regression from a recent change because until recently (2 weeks ago) you received the Find Fishing Pools book from the boxes
