### ISSUE TITLE
Proxy of Nozdormu doesn't works

### ISSUE THREAD

**Issue by unitscan** [chromiecraft/chromiecraft#4448]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

60

### Current Behaviour

Proxy of Nozdormu can't be casted on myself or another friendly target

### Expected Blizzlike Behaviour

Use: Target a friendly player to deputize them as an Agent of Nozdormu. As an Agent of Nozdormu, only you and your deputies may take the Silithid Carapace Fragments from the corpses of the silithid. Keep your badge in your pack at all times.

### Source

The Hand of the Righteous: https://www.wowhead.com/classic/quest=8302/the-hand-of-the-righteous
Proxy of Nozdormu: https://www.wowhead.com/classic/item=20403/proxy-of-nozdormu
Baristolth of the Shifting Sands; https://www.wowhead.com/classic/npc=15180/baristolth-of-the-shifting-sands

### Steps to reproduce the problem

1. Get a Proxy of Nozdormu by completing The Hand of the Righteous quest given by Baristolth of the Shifting Sands on Silithus;
2. Try to cast Proxy of Nozdormu on a friendly target or on hitself.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
worked fine to cast it on a group member 5 days ago

**Comment by Cooties-cc** [comment]
[token.webm](https://user-images.githubusercontent.com/62584589/201227651-a822cd1b-57fb-40f0-8c50-0d438ace609e.webm)
Works just fine. Two things I can think of that might be a problem for you
1. You cannot deputize yourself. 
2. The Agent of Nozdormu is unique, so only 1 per character (they may have in bags already or in bank)

You will need to provide further proof showing it's a problem past these and more unique to the account.

**Comment by heyitsbench** [comment]
Almost 100% sure there is no issue here. If your targeted friendly player has an [Agent of Nozdormu badge](https://www.wowhead.com/wotlk/item=20402), it can't give them another one. Also blizzlike for the Proxy to not be able to target the player casting. The method for the player getting another badge if they've lost/deleted the one they originally acquired is another issue, specifically https://github.com/chromiecraft/chromiecraft/issues/4075.

**Comment by Nyeriah** [comment]
There doesn't seem to be an issue with this, closing.
