### ISSUE TITLE
Seal of vengeance - Seal of Corruption at different lvls

### ISSUE THREAD

**Issue by Tituspullo666** [chromiecraft/chromiecraft#4454]
Seal of vengeance(lvl 64 for alliance) - Seal of Corruption(lvl 66 for horde) at different lvls. Should be same lvl and same name.

**Comment by BeefSteaker** [comment]
This is a custom change for tbc & wrath classic, Seal of vengeance/Corruption having different levels is blizzlike for wrath retail.

![image](https://user-images.githubusercontent.com/11332559/201416110-f5eba03e-6834-49cc-be05-7d594e7e3d8f.png)
https://wowpedia.fandom.com/wiki/Seal_of_Vengeance?oldid=2050117

it might be worth posting this in suggestions as a progression change
