### ISSUE TITLE
[TBC] Primal Nether Drop Rates in Normal Mode Dungeons too high

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4461]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Drop Rates for Primal Nether vary between 5 to 7 percent for normal modes (for those bosses that are supposed to drop it at all)

### Expected Blizzlike Behaviour

Drop rate should be between 2.5 and 5% in normal modes (for those bosses that are supposed to drop it at all)

### Source

https://wowpedia.fandom.com/wiki/Primal_Nether

### Steps to reproduce the problem

Extract from creature_loot_template.sql

<html>
<body>

Entry | Item | Reference | Chance | Comment
-- | -- | -- | -- | --
17881 | 23572 | 0 | 7.0 | Aeonus - Primal Nether
20912 | 23572 | 0 | 7.0 | Harbinger Skyriss - Primal Nether
16808 | 23572 | 0 | 5.0 | Warchief Kargath Bladefist - Primal Nether
17798 | 23572 | 0 | 5.0 | Warlord Kalithresh - Primal Nether
17977 | 23572 | 0 | 5.0 | Warp Splinter - Primal Nether
18473 | 23572 | 0 | 5.0 | Talon King Ikiss - Primal Nether
18708 | 23572 | 0 | 5.0 | Murmur - Primal Nether
19220 | 23572 | 0 | 5.0 | Pathaleon the Calculator - Primal Nether
24664 | 23572 | 0 | 5.0 | Kael'thas Sunstrider - Primal Nether

</body>
</html>

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by slicplaya** [comment]
Actually, it's 5-7%.
