### ISSUE TITLE
Copper Ore gives too much Rough Stone

### ISSUE THREAD

**Issue by Landaz2** [chromiecraft/chromiecraft#448]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The [Copper Ore](https://wowgaming.altervista.org/aowow/?object=1731) loot table seems to pull the [Rough Stone](https://wowgaming.altervista.org/aowow/?item=2835) twice, resulting in 2-12 instead of 1-6 rough stone. See the screenshot after aprox. 40 mined ores in Mulgore:

![WoWScrnShot_042021_122144](https://user-images.githubusercontent.com/81629712/115383933-b237b280-a1d6-11eb-878e-efc7f836cb48.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

According to the database of [Copper Ore](https://wowgaming.altervista.org/aowow/?object=1731), only 1-6 Rough Stone should be looted by mining one vein.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Mine several Copper Nodes
2. Keep close attention to the amount of looted Rough Stone

##### EXTRA NOTES:

Was already reported once in Issue #163, but dropped as it could not be recreated and only occured once. The screenshot above shows several occurences.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Landaz2** [comment]
I did another mining round, this time in the Barrens, both copper and tin.
While copper behaved as expected here, tin veins have a strong lack of coarse stone. See Issue #383. Below is a screenshot, notice the roughly equal copper/stone ratio in comparison to the skewed tin/stone ratio. There were two rare occasions of high output, once givin 9 tin ore (max before was 6) and once giving 9 Coarse stone.
![Collage](https://user-images.githubusercontent.com/81629712/115456166-2304bc00-a223-11eb-9ba6-6cc2bded4893.jpg)

**Comment by Tachtzehn** [comment]
I have to agree that the low acquisition rate of Coarse Stone from tin nodes is definitely not blizzlike. The game even implies that Stones should be relatively easy to collect compared to other mining materials (ore/gems), as professions that source from mining frequently have recipes using Stones as the first recipes learned for each new tier of material.
Examples:
- Blacksmithing: sharpening stones/weightstones
- Engineering: blasting powder
- Jewelcrafting: stone statues

**Comment by Tachtzehn** [comment]
Here's 10 tin samples from Underlight Mines in the Ghostlands. I wasn't really thinking to include the copper in the screens until it was too late, but notice the frequency of stones acquired every time a copper node is mined vs. the tin only getting stones 1 out of 10 times. Copper highlighted in yellow, tin in orange.
![coarse stone sample](https://user-images.githubusercontent.com/83389835/116967183-5f023d00-ac77-11eb-8783-f4f069a4af9b.jpg)

**Comment by Hacki95** [comment]
Thanks for your work! Fix in the works.
