### ISSUE TITLE
[The Barrens] (The Stagnant Oasis) Sunscale Screecher stuck inside ground

### ISSUE THREAD

**Issue by Vladimirjov** [chromiecraft/chromiecraft#4480]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

See on screenshot, there is a Sunscale Screecher stuck inside the ground. Thank you for fixing!
![WoWScrnShot_111822_101312](https://user-images.githubusercontent.com/81888445/202666854-59d2f034-4c9b-414c-8709-99dffaf70e88.jpg)
![WoWScrnShot_111822_101319](https://user-images.githubusercontent.com/81888445/202666861-b3270fb4-9c6b-46ee-a880-e9ef9dc20fd8.jpg)

### Expected Blizzlike Behaviour

The mob should not be inside the ground obviously :D

### Source

common sense

### Steps to reproduce the problem

1. Go to The Barrens.
2. Go to The Stagnant Oasis
3. Look for a Sunscale Screecher inside the ground at a small mountain

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ece089dad721ef5310621e4b60db2533a6db5204

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
I was unable to find any Sunscale Screecher in that specific location

![TheStagnantOasis](https://user-images.githubusercontent.com/82369562/210564662-6306cbfd-6cef-41ca-8603-b09f1c3955f5.jpg)
