### ISSUE TITLE
[Flight Paths][Shattered Sun Stagin Area] Can fly to the Sunwell Plateau on live server.

### ISSUE THREAD

**Issue by SgtRumpsteak** [chromiecraft/chromiecraft#4481]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

I just noticed I can fly to the Sunwell Plateau on my Alliance Druid. Seems to be possible from every flight master, so not just a problem in Iron Forge where I made that screenshot.
No idea why that is or since when.
Can't do that on other chars. The only "difference" that comes to my mind is, that I faction-changed that druid from Horde to Alliance after which I automatically had all the alliance flight points.
Only thing though: That faction change already happened last year, I never really paid attention to the flight paths so I have no idea, if I just never noticed or a server update brought that flight path in recently.
Also I can't simply test this on other characters since I would have to pay money for a faction change.

![WoWScrnShot_111822_120410](https://user-images.githubusercontent.com/88026991/202692209-0e0820af-5967-420e-a46a-d745891b9680.jpg)

### Expected Blizzlike Behaviour

Not having a flight point I never visited.

### Source

I guess source here is general game behavior?
You shouldn't have a flight point in an area you never visited.

### Steps to reproduce the problem

I have no idea. Probably try a faction change and check, if the flight path is available.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ece089dad721ef5310621e4b60db2533a6db5204

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, thanks this should already be fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/9729. if you faction changed before the fix went live youll have it.

For anyone looking into this, please dont actually use the flight point, youll keep disconnecting and will have to get staff to unstuck you
