### ISSUE TITLE
Ghaz'ans Acid spit hits all party members instead of one party member

### ISSUE THREAD

**Issue by Tituspullo666** [chromiecraft/chromiecraft#4482]
Ghaz'ans(Underbog Boss) Acid Spit ability(https://wotlkdb.com/?spell=34290) hits all party members (around 2k dmg), independent of location or range, instead of one party member as intended. 
Tail sweep ability (https://wotlkdb.com/?spell=34267) 
did not knock me back either during the fight while behind the boss.

**Comment by Stump876** [comment]
If this is stil an issue, please reopen and use the provided template for new issues. It containes server and module information that is needed, along with the info we require to triage.
