### ISSUE TITLE
[TBC] Stormchops Do Not Proc Deep Wounds

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4484]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

[chop crits.webm](https://user-images.githubusercontent.com/62584589/202875514-1d3381d1-6f4c-4af2-8f7c-5f4a570d806d.webm)

Currently when having the buff up from [Stormchops](https://wowgaming.altervista.org/aowow/?item=33866), the crits from the food buff are not granting [Deep Wounds](https://wowgaming.altervista.org/aowow/?spell=12867). 

### Expected Blizzlike Behaviour

Referencing the ticket [[Deep wounds behavior](https://github.com/chromiecraft/chromiecraft/issues/4226)] about **confirming** spells cast by warriors with the talents Deep Wounds, it states that any crit generated by the warrior of any source, shall incite a Deep Wounds proc. It also includes the item, Stormchops. 

The ticket was closed, and [a fix was applied](https://github.com/azerothcore/azerothcore-wotlk/pull/13494), however, my webm shows that Stormchops are still not working correctly. 

### Source

Original ticket citing Stormchops : https://github.com/chromiecraft/chromiecraft/issues/4226
Confirmed, closed, and "fixed" : https://github.com/azerothcore/azerothcore-wotlk/pull/13494

Wowhead comment from 3.0.9 : 
![image](https://user-images.githubusercontent.com/62584589/202875729-c35b035d-5e82-43a4-8d5b-0b8fc03d0286.png)

### Steps to reproduce the problem

1. Create a warrior, and spec into Deep Wounds
2. ` .additem 33866`
3. Apply the food buff, and strike or be struck
4. None of the spell crits apply Deep Wounds

### Extra Notes

This one might have slipped by, since it is I think considered a damage shield, even when striking a target. This means it might be under a different spell aura application from what I saw changed in the fixed files. Though I don't know how to code, just a guess as to why it may not work. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ece089dad721ef5310621e4b60db2533a6db5204

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by bonfax4** [comment]
Proc chance on that item seems to be messed up tho. Look how often it procs on [classic tbc](https://youtu.be/UINlbxRbUGk). It either has an ICD or a lower proc chance.

**Comment by bonfax4** [comment]
Also Stormchops should only strike 2 targets ( chain lightning to a second target ) at most with an 8 sec ICD. In your video you seem to be proccing twice instantly in one target. Proc can only target 1 enemy and chain to a second enemy, evidenced by https://youtu.be/gdxv-WF9OPc and https://www.wowhead.com/tbc/item=33866/stormchops#comments

**Comment by Cooties-cc** [comment]
To prevent derailing, this is not about proc chance of stormchops, it is about spell crits not procing deep wounds for warriors. If you would like to open a ticket for that subject, you may, but please don't change the subject of this ticket. I want to also say that if you do open a ticket about the item not being correct, at least use the correct version of the game for evidence, since this is not Classic TBC Retail.

**Comment by bonfax4** [comment]
Dunno man seems more logical to me to fix the bugged item first, rather than a non intended interaction, which also happens to not be confirmed by anything non classic aside from one comment from an old wotlk patch. Also the item did not change behaviour from one xpac to another, if anything all they did was nerf ppm on alot of old stuff from old xpacs. Look I even went out of my way to check the official classic warrior discord and stormchops is listed with 100% proc chance with 10sec ICD rather than 8 secs that was shown on that  non-classic retail tbc comment i mentioned. Do show me one log or a reliable discussion that shows Deep Wounds behaving that way retail wotlk

**Comment by Cooties-cc** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/13494
Devs agree and apply fix to spell crits allowing deep wounds. Items talked about included Stormchops.

https://github.com/azerothcore/azerothcore-wotlk/issues/13431
Original ticket laying all the ground work for how the spell code is suppose to interact. Includes stormchops being tested and working, however currently it's not (something might have broke again). 

It's not my job to do your research, nor is it polite to try and derail a ticket. Make your own ticket about stormchops having a broken proc rate. This ticket is about crits and deep wounds interactions.

**Comment by bonfax4** [comment]
You're under the wrong impression I didn't check that post before commenting.

Anyway, "derailing" would imply what I said has in no way connection to what you're attempting to "fix" here but whatever. Item is bugged, therefore fixing the non I tended interaction before the item itself which would make it insanely broken is idiotic and I honestly doubt you didn't research that item behaviour before posting this. You're mad I'm ruining your fun it seems.

**Comment by Tereneckla** [comment]
Actually fixed, but never was linked
