### ISSUE TITLE
[Spell] Thunder Clap Weapon Interactions

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4485]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

60

### Current Behaviour

This bug is somewhat hard to really prove/disprove. It's more than likely going to be a dev decision over factual change. 

Currently, when equipping items that _add_ damage to your melee attacks, thunder clap is not taking them into account when casting the spell. 

[clap 1.webm](https://user-images.githubusercontent.com/62584589/202878194-e477974e-3c48-463b-8289-60cf755a2cb3.webm)
Here I equip the [Fiery Retributer](https://wowgaming.altervista.org/aowow/?item=19968), which adds 2 fire damage to your melee attacks. Thunder clap doesn't proc it, but when I swing, it does. 

[clap 2.webm](https://user-images.githubusercontent.com/62584589/202878318-cb2e81d8-9642-4e1f-a393-b06766c8e60a.webm)
In this webm I use [Fiery Plate Gauntlets](https://wowgaming.altervista.org/aowow/?item=12631) & [Blazefury Medallion](https://wowgaming.altervista.org/aowow/?item=17111). Both add additional damage to your melee attacks, but thunder clap doesn't proc either. 

### Expected Blizzlike Behaviour

I want to be clear on some things. 

1. These attacks are not bonus damage added to the weapon. They do not function the same as an item like [Iceblade Hacker](https://wowgaming.altervista.org/aowow/?item=13952)
2. Thunder clap can proc enchants from weapons, as well as chance on hit items/weapons
3. Thunder clap however can be cast with or without a weapon

With that said, I want to argue the idea that thunder claps should include the bonus damage applied to melee attacks, since going by the logic of how the spell currently functions, it doesn't make sense not to include them if a weapon is being used as the spell is cast. This should add the damage to any target hit by thunder clap while a weapon is wielded. 

### Source

I don't have any direct sources to support my claim, outside of how the logic and function of thunder clap is behaving currently. If thunder clap was not suppose to proc any weapon or items, but it is currently, then the exclusion of weapon bonus damage items doesn't make sense. It should be an all or nothing logic. 

### Steps to reproduce the problem

1. Create a warrior
2. Learn Thunder Clap `.learn 6343` (rank 1)
3. Get any of the 3 items; `.additem 19968` (sword), `.additem 17111` (neck), `.additem 12631` (gloves)
4. Cast Thunder Clap with any item equipped and with a weapon in hand
5. No Thunder Clap cast will generate the extra weapon damage

### Extra Notes

There's probably going to be more spell interactions with warriors in the future due to spell crits allowing deep wounds. I would other wise probably not even look into matters like this if that wasn't fixed :D

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ece089dad721ef5310621e4b60db2533a6db5204

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
I believe this is intended. TC is a really fucked up ability.

Prior to 3.3.3 it used to be a spell with all its properties, then it got changed to classify as a ranged attack:
[Patch 3.3.3](https://wowpedia.fandom.com/wiki/Patch_3.3.3) (2010-03-23): This ability now counts as a ranged attack, granting it double damage on critical strikes instead of 150% and ranged miss chance, and still cannot be dodged or parried.

Because of this, it mostly behaves as a ranged attack (and procs ranged weapon procs such as [Hurricane](https://www.wowhead.com/classic/item=2824/hurricane)), and this is also why it doesn't proc damage bonuses that are added specifically to melee attacks, which is the topic of this report. Unlike, for example Judgement, which remained classified as a melee attack that cannot be dodged/parried/blocked.

However, it remained a spell in a way that it can be silenced, probably related to this blue post reply https://us.forums.blizzard.com/en/wow/t/proc-weapons-and-the-gcd/592642/40 
_"After reading a few responses I did want to clarify one minor thing; a spell’s “School” is not the same thing as its Defense Category. There are spells with the school of holy/shadow/frost/etc. that have a defense category of melee/physical, and spells with a school of physical that have a defense category of magical.

…and before it’s asked; no, we are not going to post a full list of which spells are in which spell school or defense categories :slight_smile:"_

The only questionable part are the melee weapon procs, tbh. All sources that speak of Crusader proccing off TC are cataclysm and onwards, i couldn't find any evidence that it should proc anything from melee weapons on 3.3.5a. I'll need to confirm this with somebody on wotlk classic because it was either hacked into the spell or is bugged.

**Comment by FrancescoBorzi** [comment]
> I believe this is intended. TC is a really fucked up ability.
> 
> Prior to 3.3.3 it used to be a spell with all its properties, then it got changed to classify as a ranged attack: [Patch 3.3.3](https://wowpedia.fandom.com/wiki/Patch_3.3.3) (2010-03-23): This ability now counts as a ranged attack, granting it double damage on critical strikes instead of 150% and ranged miss chance, and still cannot be dodged or parried.
> 
> Because of this, it mostly behaves as a ranged attack (and procs ranged weapon procs such as [Hurricane](https://www.wowhead.com/classic/item=2824/hurricane)), and this is also why it doesn't proc damage bonuses that are added specifically to melee attacks, which is the topic of this report. Unlike, for example Judgement, which remained classified as a melee attack that cannot be dodged/parried/blocked.
> 
> However, TC remained a spell in a way that it can be silenced, probably related to this blue post reply https://us.forums.blizzard.com/en/wow/t/proc-weapons-and-the-gcd/592642/40 _"After reading a few responses I did want to clarify one minor thing; a spell’s “School” is not the same thing as its Defense Category. There are spells with the school of holy/shadow/frost/etc. that have a defense category of melee/physical, and spells with a school of physical that have a defense category of magical.
> 
> …and before it’s asked; no, we are not going to post a full list of which spells are in which spell school or defense categories :slight_smile:"_
> 
> The only questionable part are the melee weapon procs, tbh. All sources that speak of Crusader proccing off TC are cataclysm and onwards, i couldn't find any evidence that it should proc anything from melee weapons on 3.3.5a. I'll need to confirm this with somebody on wotlk classic because it was either hacked into the spell or is bugged.

Closing as not enough evidence to proceed with confirming this. If anyone can provide such evidence, feel free to post it here and we will reopen the issue.
