### ISSUE TITLE
[Engineering] Evil Twin debuff earned by teleporting via Engineering gadget gets you unsummonable

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4489]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

When you have Evil Twin debuff, summoning by warlock stone won't get you button to accept summon.

### Expected Blizzlike Behaviour

Effects
The debuff does absolutely nothing.

Should be able to be summoned

### Source

https://wowpedia.fandom.com/wiki/Evil_Twin

### Steps to reproduce the problem

1. Use [[Ultrasafe Transporter: Gadgetzan]](https://wowpedia.fandom.com/wiki/Ultrasafe_Transporter:_Gadgetzan)
2. And make warlock summon you via stone
3. No button to accept

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ece089dad721ef5310621e4b60db2533a6db5204

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by djobf** [comment]
It's intended, at least according to wowhead at the time : [You cannot be summoned by warlocks](https://www.wowhead.com/spell=23445/evil-twin#comments)

**Comment by BeefSteaker** [comment]
> It's intended, at least according to wowhead at the time : ["You cannot be summoned by warlocks"](https://www.wowhead.com/spell=23445/evil-twin#comments)

Yeah, this is correct afaik. 
![image](https://user-images.githubusercontent.com/11332559/203075773-39659727-4b0d-4c6e-a7b3-af86517b0601.png)

also appears in older revisions of the wiki https://wowpedia.fandom.com/wiki/Evil_Twin?oldid=343928
