### ISSUE TITLE
Old Hillsbrad Foothills. Thrall bugs.

### ISSUE THREAD

**Issue by Tituspullo666** [chromiecraft/chromiecraft#4493]
**What client do you play on?**

enUS
**Faction**

Horde
**Content Phase:**

60-64
**Current Behaviour**

Once you start the event to rescue Thrall runs into walls during the first fight in the castle. Thrall does not heal himself during the whole event and kills his horse after dismounting in Tarren Mill. 

**Expected Blizzlike Behaviour**

Thrall should not run into walls during the first fight in the castle. Thrall should heal himself during the whole event and not kill his horse after dismounting in Tarren Mill. 

**Source**

.
**Steps to reproduce the problem**

Start the rescue Thrall quest in Old Hillsbrad Foothills.

**Comment by AcetylGer** [comment]
Any progress on fixing this?

**Comment by HasieEST** [comment]
> Any progress on fixing this?

Given that it is not even looked at yet, I'd argue no? Unless there is a duplicate report.

**Comment by Samsequel** [comment]
This seems to be working correctly now.
