### ISSUE TITLE
You can invite people to join your guild crossfaction if you do it during a Battleground when you are on the same team.

### ISSUE THREAD

**Issue by JamesGent** [chromiecraft/chromiecraft#45]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### SMALL DESCRIPTION:

You can invite people to join your guild crossfaction if you do it during a Battleground when you are on the same team.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No crossfaction guilds.

##### CURRENT BEHAVIOUR:

If you're on the same BG team you can invite anyone to your guild, as the screenshot shows I could invite a Horde Orc to <The Alliance> guild whilst playing Lanaya and being put on the Horde side.

I also could not invite Alliance characters in this time.

![image](https://user-images.githubusercontent.com/61194190/107060049-6e83fe00-67ce-11eb-9512-9404ef247d37.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Join BG as Alliance Guildmember
2. Be assigned horde
3. Invite horde chars to guild

I discovered this entirely by accident when an alliance character asked me alliance guild leader for a ginvite and it errored "wrong faction" when I tried. I logically took the step to try to invite a horde and it worked.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
Linked https://github.com/azerothcore/mod-cfbg/issues/19

**Comment by r-o-b-o-t-o** [comment]
Since https://github.com/azerothcore/azerothcore-wotlk/pull/5519 is merged, this one can be closed

**Comment by Helias** [comment]
thanks @r-o-b-o-t-o, I am closing it
