### ISSUE TITLE
[AQ40] Cthun fight P1 stops casting after a few seconds

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4503]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Cthun does stop all casts and interactions after an Eye Beam kills a target

### Expected Blizzlike Behaviour

cthun should continue casting

### Source

.

### Steps to reproduce the problem

engage cthun and wait

### Extra Notes

boss seems to be stuck in a loop caused by the last changes
https://github.com/chromiecraft/azerothcore-wotlk/commit/888f9bb0bb3825ef8cfa1a8b33ed4dba032a9d73#diff-7b359873a2ad1b4d2830ea8118b5d775e7e6397aa6b310c04643b8f196f8a367

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4a2964e10a03a2b6ba2077e6b362b8a6ba6675fb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by mctscc** [comment]
I clipped the moment it bugged. 3 people died from eye beam and c'thun stopped casting anything.
https://clips.twitch.tv/PricklyWimpyDinosaurMrDestructoid-KIG9nGTluANUQN24

It reminds bug with Ouro, when he lost target: https://github.com/azerothcore/azerothcore-wotlk/issues/13684

**Comment by BeefSteaker** [comment]
Can confirm this happened in the Rum Rage raid yesterday too. 
seems to have been caused by a fix with how the eye targets that has now been reverted https://github.com/chromiecraft/azerothcore-wotlk/compare/4a2964e10a03...55957fbb6e24

Can anyone confirm if this is still happening after the revert?

**Comment by balleny** [comment]
was reversed and didnt happen today
