### ISSUE TITLE
Mobs killed only by Totem or Spirit Wolf damage can't be looted/ skinned.

### ISSUE THREAD

**Issue by Scapulla** [chromiecraft/chromiecraft#4516]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

When mobs are killed by only totem (magma or searing) or Spirit wolves damage, they aren't lootable or skinnable by player.

### Expected Blizzlike Behaviour

Enemies should be lootable and skinnable by the player who tagged and killed them.

### Source

Mobs should be lootable and skinnable by player who killed them, as are enemies killed only by the hunter pet, if one chooses to send only pet to kill something.

### Steps to reproduce the problem

Spirit wolf kill only https://youtu.be/0JuZVOHF-cI

Totem-only kill https://youtu.be/cPtdFUbLtgQ

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4a2964e10a03a2b6ba2077e6b362b8a6ba6675fb

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Santaria94** [comment]
https://us.forums.blizzard.com/en/wow/t/when-pet-kills-mob-you-cannot-loot-it/973194/2

**Comment by BeefSteaker** [comment]
this is correct behavior for wrath. its to avoid afk farming with pets/totems

got changed some time around legion for retail https://wowpedia.fandom.com/wiki/Patch_7.0.3_(undocumented_changes)
