### ISSUE TITLE
If you abandon Raene's Cleansing (Part 10) you lock yourself out of completing the chain

### ISSUE THREAD

**Issue by T-Lorentzen** [chromiecraft/chromiecraft#4532]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

20-29

### Current Behaviour

If you pick up the [quest](https://wowpedia.fandom.com/wiki/Raene%27s_Cleansing_(10)) from the furbolg Krolg, and abandon it, your Dartol's Rod of Transformation is destroyed. This leaves you unable to transform back into a furbolg, and therefore also unable to reacquire the quest from Krolg after the transformation expires.

### Expected Blizzlike Behaviour

~~I couldn't find any information to what Blizzlike would be, but i expect one of the following options:~~

~~- The rod is not destroyed when you abandon this quest~~
~~- GMs would restore the rod for characters that abandon this quest~~

Seems i was wrong on this part. To get this blizzlike there should be a gossip option to reobtain the rod from Raene Wolfrunner. Credits to [heyitsbench](https://github.com/heyitsbench)

### Source

-

### Steps to reproduce the problem

1. Complete the quest chain Raene's Cleansing until you get the part given by Krolg
2. Abandon the quest and remove the transformation buff given by the rod
3. Krolg is now aggresive and there is no way to reobtain the rod

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11530ecb95a35f66a2c220781172c57e0749ac48

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Haha, this one's cute.
So I tested on Wrath Classic PTR, upon abandoning the [quest](https://www.wowhead.com/wotlk/quest=1045) (and dispelling the [furbolg aura](https://www.wowhead.com/wotlk/spell=6405)) the [rod](https://www.wowhead.com/wotlk/item=5462) does indeed get deleted, and [Krolg](https://www.wowhead.com/wotlk/npc=3897) remains hostile. Coming back to [Raene Wolfrunner](https://www.wowhead.com/wotlk/npc=3691), she now has a [new gossip option](https://user-images.githubusercontent.com/38561765/206750161-e5c7950a-d0c0-4287-9df4-514174006549.png)! Upon selecting it, she also has [specific text for this circumstance](https://user-images.githubusercontent.com/38561765/206750524-46e3e4b8-d7b9-4a18-a1de-05a3a090aaf6.png).

**Comment by T-Lorentzen** [comment]
That's pretty cool! I've updated the issue with the correct blizzlike behaviour. I've visited Raene (and every other quest giver in the chain) on the character were i experienced this, and none of them offer to replace the rod.

**Comment by heyitsbench** [comment]
> That's pretty cool! I've updated the issue with the correct blizzlike behaviour. I've visited Raene (and every other quest giver in the chain) on the character were i experienced this, and none of them offer to replace the rod.

I'll take a look at this later today and see if I can't get it working, since I recently addressed a similar issue with Baristolth.
