### ISSUE TITLE
Gear rolled back 

### ISSUE THREAD

**Issue by finalmortal** [chromiecraft/chromiecraft#4537]
My bracers of might rolled back to my bracer of valor which i sold to a vendor when the server went offline.
Any idea how this happened?  

The character name is Ssheila

**Comment by BeefSteaker** [comment]
Some stuff can get rolled back on server crash/shutdown. you can use the .save command to save your character, and it will also be saved when you log out.

your best bet is to either make a support ticket on the discord, or if you can do the quest to obtain the item again
