### ISSUE TITLE
[Vorsha the Lasher] Quest-NPC doesn't attack Vorsha upon spawn

### ISSUE THREAD

**Issue by Vladimirjov** [chromiecraft/chromiecraft#4539]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

20-29

### Current Behaviour

See screenshot. After deactivating the fire, Vorsha spawns but doesn't attack automatically, neither does Muglash attack him automatically.

I was standing there taking a screenshot of Vorsha while he wasn't doing anything. At some point i just decided to attack him, but it seems that Muglash couldn't help me because the monster didn't leave the water at all (pathing issue? generic?)

![WoWScrnShot_120722_230525](https://user-images.githubusercontent.com/81888445/206308748-03bbf6c1-5b00-48d2-b34b-967700c9c9a5.jpg)

### Expected Blizzlike Behaviour

See in the sources. Both the Quest-NPC (Muglash) and the monster Vorsha should attack each other upon spawn. It seems that they are scripted to immediately attack each other. After Vorsha dies the dialog should happen where Muglash tells that he is going to patrol.

PS: After i decided to attack Vorsha, i had the Quest-NPC (Muglash) behind my back and i didn't pay attention on what he was doing anymore. Unfortunately i can't tell, if he at least tried to help me and ran around in a weird way (due to pathing issue between land and water?) After i killed Vorsha, i looked back and the dialog already happened and he was gone. 

Thank you for fixing!

### Source

Youtube-Video with the whole quest:

https://www.youtube.com/watch?v=Hua5mdj0vT0

Wowhead WOTLK with more videos:

https://www.wowhead.com/wotlk/quest=6641/vorsha-the-lasher#videos

### Steps to reproduce the problem

1. Go to Zoram Strand (Ashenvale) as a horde.
2. Accept the quest [Vorsha the Lasher] and escort Muglash to the fire that has to be extinguished
3. Extinguish the fire and kill the mob waves until Vorsha spawns.
4. Vorsha just stays in the water and doesn't attack, neither does Muglash attack him (Video shows both of them attacking each other immediately while spawning)

Thank you!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c29927b8e9aaf03429e04c7a751be8337b56879d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
I just tested on my local, seems like it works fine: Vorsha the Lasher came towards us normally
