### ISSUE TITLE
Quest:Treasure_of_the_Timeless_One locked

### ISSUE THREAD

**Issue by mile1992** [chromiecraft/chromiecraft#4541]
1.
![sc](https://user-images.githubusercontent.com/120108579/206457723-218c0652-98d2-4988-97aa-fcb1425a2186.png)
The mentioned quest is not showing to players who have completed the scepter questline. According to wowwiki, it should be avaliable to anyone who has completed the chain and has scepter in their inventory whether or not they banged the gong.

https://wowwiki-archive.fandom.com/wiki/Quest:Treasure_of_the_Timeless_One

**Comment by heyitsbench** [comment]
Cannot reproduce. At level 60, with reputation set to honored, and [The Might of Kalimdor](https://www.wowhead.com/wotlk/quest=8742) completed, I have access to the quest.

**Comment by Stump876** [comment]
Please use the template when opening a reports. I have no idea what version of the core this is, or what modules are loaded. If this is still an issue, please re-open using the template.
