### ISSUE TITLE
Demoralizing/Challenging Roar does not affect critters.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#4543]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

1-19

### Current Behaviour

Currently critters (such as [sheep](https://www.wowhead.com/wotlk/npc=1933), [rabbit](https://www.wowhead.com/wotlk/npc=721), or [deer](https://www.wowhead.com/wotlk/npc=883)) will have the aura applied from [demoralizing](https://www.wowhead.com/wotlk/npc=99)/[challenging](https://www.wowhead.com/wotlk/npc=5209) roar.

### Expected Blizzlike Behaviour

These critters (perhaps all critters, might be some exceptions, not sure) should have the aura applied from the roar, but also run away from the caster.

### Source

Wrath Classic Live/PTR.

### Steps to reproduce the problem

1. `.learn 5487`, `.learn 99`/`.learn 5209`, `.learn 5229`
2. `.tele stormwind`
3. Leave Stormwind through the southeast gates and go to the critters in the area surrounding area.
4. Either cast enrage or use `.modify rage (sufficiently high number)`
5. Cast roar of your choice while in range of critters.
6. Observe the issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c29927b8e9aaf03429e04c7a751be8337b56879d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Heya Bench! I can confirm.
Critters with a none dmg debuff will continue their usual pathing on CC.

In wotlk classic critters who are affected by a none damage debuff will start to run away in fear and then return to the place they recived the debuff, ones its no longer active. 

https://user-images.githubusercontent.com/103856689/207561509-8ed30695-1e94-4f0e-983a-344e34fcb8ee.mp4
