### ISSUE TITLE
All absorb shields doesn't allow for mage proccs.

### ISSUE THREAD

**Issue by melosat** [chromiecraft/chromiecraft#4545]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

If you as a mage have an absorb effect from: Mana Shield/Ice Barrier/Power word shield/Arena Grand master etc. this as of now prevents proccs from the  Slow effect from Ice Armor, aswell as frostbite/fiery payback/Blazing speed etc. 

This creates many different problems, one of them being that they make frost talents completely unviable for PvP. 

### Expected Blizzlike Behaviour

Even if an absorb effect is active, this should not prevent these proccs from happening (frostbite/fiery payback/Blazing). 

Note that i havent tried power word shield with other classes that have similar proccs, so you might want to test this further. 

### Source

https://www.youtube.com/watch?v=8-XPZmceCgU

At 0:39 you can clearly see an ambush go off and the shields not braking - but still triggering both slow and frostbite on the attacker. Im aware that this is an old clip from the TBC prepatch but its such a clear example that i had to include it. 

https://www.youtube.com/watch?v=LvYxWiJZQQw

At 3:43 when the feral charges the mage, you can clearly see that the frost armor proccs, even though ice barrier is up. 

### Steps to reproduce the problem

1. Create a mage and put talents into frost
2. Apply Ice Armor
3. Go to any mob that hits with melee
4. Get hit (and see the procc from ice armor)
5. Now apply ice barrier/mana shield and get hit again (And notify that no slow effect gets applied)
6. (Do the same thing but with power word shield from a priest or an item like Arena Grand Master/Burrower's shell/Scarab Brooch)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c29927b8e9aaf03429e04c7a751be8337b56879d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Hey Melosat! I can confirm its not applying the slow debuff. 
I also tried it on wotlk classic server, and it works as you describe it. 

https://user-images.githubusercontent.com/103856689/207548723-6779cf4d-a963-46a2-b6fd-4d5970cf793a.mp4

**Comment by sassouiabd** [comment]
I confirm the issue (ivarxx). Any work in progress to solve or updates for this issue ?
It makes frost spec unplayable..
