### ISSUE TITLE
[AQ40] Visual and Combatlog range

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4546]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Visual and combatlog is too small.
Addons that rely on combat log events like DBM, recount and skada arent able to pick up combatlog events, scan for debuffs at group members or their targets, when they are within the stomach of Cthun.

### Expected Blizzlike Behaviour

Both visual range and combat log events should mutually accessible.
Players in Cthuns stomach should still receive combat log events from players not in the stomach and vice versa.

### Source

practically all implementations of addons etc.
further, its a common private server thing that view / event range is lower compared to retail

### Steps to reproduce the problem

have one char inside cthuns stomach and one person not.
healing spells cast by the person in the stomach should still be logged in the combat log of the char not in the stomach

### Extra Notes

potentially, it is possible to increase the viewing distance for this raid only?

the range already seems to the rather close, as the flesh tentacles can be targeted from outside the stomach, but party members cannot be processed directly (likely a small increase could be sufficient already as the flesh tentacles are in sufficient range)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c29927b8e9aaf03429e04c7a751be8337b56879d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Heya Balleny! I can confirm that heals for example are not showing up in the combat log for the player in the stomach and vice versa.

https://user-images.githubusercontent.com/103856689/207543999-a6a581c9-2972-4026-8e0d-ddec2925d41d.mp4
