### ISSUE TITLE
[Balance Druid] Nature's Grace talent procs before actual hit

### ISSUE THREAD

**Issue by aradiuk** [chromiecraft/chromiecraft#4547]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

I have maxed out [this talent](https://wowgaming.altervista.org/aowow/?spell=16880), so it has 100% chance to increase cast time by 20%.

The spell to test this on should be one with travel time, like [Wrath](https://wowgaming.altervista.org/aowow/?spell=48461).

Actual behaviour: whenever I cast Wrath that is going to critically hit - I get the effect of Nature's Grace **before** the spell actually hits a target and I see damage number. So basically I can understand whether this cast is going to crit or not **immediately** after finishing my cast.

Here is a video of me reproducing the bug on ChromieCraft (keep an eye on the Combat Log): 

https://user-images.githubusercontent.com/26429847/206864896-a8538891-24a8-4e66-8d05-44dcabef51b7.mp4

### Expected Blizzlike Behaviour

Expected behaviour: whenever I cast Wrath and I see that it critically hits a target (bigger yellow number appears) - the talent procs and I get an appropriate buff for the next 3 seconds.

I've only been able to find [this video](https://youtu.be/7yHF7M-epxg?t=198), where you can more or less see how it procs. Sadly, no useful comments on wowhead or anywhere else.

### Source

A video, supposedly from WotLK Classic.

### Steps to reproduce the problem

1. As a druid learn [this talent](https://wowgaming.altervista.org/aowow/?spell=16880).
2. Stand in front of an enemy (dummy is better as it won't be moving).
3. Cast a spell with travel time, like  [Wrath](https://wowgaming.altervista.org/aowow/?spell=48461).
4. Repeat step 3 until you get a buff from the talent mentioned in step 1.
5. Observe that the buff appears **before** the spell reaches an enemy.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c29927b8e9aaf03429e04c7a751be8337b56879d

### Operating system

Windows 10.

### Customizations

None

### Server

ChromieCraft

**Comment by Santaria94** [comment]
1. If I'm not mistaken, beta testing of Wrath Classic didn't even start 8 months ago
2. This doesn't seem to be a bug. https://youtu.be/LDLRLpIfZQs?t=6 - 0:07

**Comment by aradiuk** [comment]
@Santaria94 I might be mistaken. Did not manage to find a video that would show it clearly.

**Comment by aradiuk** [comment]
Found a few messages on some forum. Looks like it works as expected. 
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/41508706
