### ISSUE TITLE
Progression Changes for the 61-64 Bracket

### ISSUE THREAD

**Issue by Gultask** [chromiecraft/chromiecraft#4552]
This is a list of all changes in the progression system that will be applied to ChromieCraft, as well as some custom changes not in the progression system.
Follow https://www.chromiecraft.com/en/progression/ for releases.
Check out https://github.com/azerothcore/mod-progression-system for **all** changes.

This list is subject to changes.

## Custom ChromieCraft changes:

- Disabled Khorium spawned inside instances.
- Disabled the Windy Clouds (Gas Clouds) in Nagrand that are inaccessible until flying. Only the ground-level ones will be available.
- Paladin Seals that were locked at level 66 will be available at level 64.
- Druids' Normal Flight Form will be locked until level 70.
- There's a new NPC in several spots around Outland that will teleport you to areas unreachable without flight.

## Releases

- TBC 🥳 
- Normal modes of The Blood Furnace, Hellfire Ramparts, The Underbog, The Slave Pens and Mana-Tombs

## Removals

- The old version of Kazzak is removed from the DB.
- Arena Vendors in TBC disabled.
- Disabled the BT attunement quest 'The Secret Compromised'.
- Ogri'la Quests disabled, including 'Ogre Heaven' and up.
- Sha'tari Skyguard reputation gain from killing mobs and quests like 'To Skettis!' and up disabled.
- Removed the Engineering Goggles recipes from trainers and 'Bulwark of the Ancient Kings'
- Removed all items from the Heroic Badge vendor G'eras.
- Disabled Zul'Aman quests like 'Oooh, Shinies!' and up.
- Removes the following NPCs from Shattrath City:
Exarch Naasun, Anwehu (Badge Vendor), Ontuvo (Jewelcrafting Vendor), Whirligig Wafflefry, Commander Steele, General Tiras'alan, Lord Torvos, Emissary Mordin.
- Removes the Isle of Quel'Danas Portal and the Sunwell Plateau map below A'dal.
- Removes Shattered Sun Offensive quests and dailies.
- Removed Shadow Dust drops in Skettis.

## Changes

- ~~New: Swamp Gas now drops Mote of Life instead of Mote of Water~~ Change Reverted
- New: Nightmare Vine now drops Nightmare Seeds
- Honor, Arena and Heroic Gems will be BoP and Unique-Equipped.
- Primal Vortex and Nether Vortex will be BoP.
- World Boss loot will be BoP.
- Moved G'eras to more closely reflect his original position.
- Changed Grand Anchorite Almonen and Harbinger Haronem Faction to Aldor from Shattered Sun Offensive.
- Changed Shattered Sun Marksman to Veteran Vindicator or Aldor Marksman.
- Changed Shattered Sun Trainee to Aldor Neophyte.
- Changed Shattered Sun Veteran to Seasoned Vindicator.
- Changed Shattered Sun Cleric to Aldor Marksman.
- Changed Shattered Sun Magi to Aldor Anchorite.
- Changed Captain Dranarus to Seasoned Vindicator.

**Comment by Gultask** [comment]
Locations of the teleporter NPC:

![image](https://user-images.githubusercontent.com/100873791/211528264-02063b1e-8f09-4b4c-b00b-554a7c032320.png)

**Comment by TheSCREWEDSoftware** [comment]
Closing this issue
