### ISSUE TITLE
Winter Revelers use wrong modelID.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#4561]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

For some reason, a [Winter Reveler](https://user-images.githubusercontent.com/38561765/207926924-1946dd1f-f76b-43bf-a0e7-5c853443a7ae.png) in Ironforge uses the wrong model ID. Could not reproduce on the PTR.

### Expected Blizzlike Behaviour

This model should *never* show up in-game.

### Source

Assumption.

### Steps to reproduce the problem

1. `.tele ironforge`
2. Go see the Winter Revelers in The Stonefire Tavern.
3. Observe possible bad model.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
![image](https://user-images.githubusercontent.com/38561765/207928493-8387f3fa-dd3c-4d81-9fed-409a2ba6c176.png)
Not just in Ironforge it looks like.

**Comment by yoreei** [comment]
![image](https://user-images.githubusercontent.com/5225386/208081643-a234b8ff-a121-4b65-927d-4e55b4222123.png)
Also in Thunder Bluff

**Comment by heyitsbench** [comment]
[This is apparently how cmangos fixed the issue](https://github.com/cmangos/tbc-db/commit/fcef33fa559013bb5718c7fe83a460108f1031b6).

**Comment by daemonhart** [comment]
Likewise in Booty Bay inn.

![](https://i.imgur.com/x4bNji1.png)

**Comment by Stump876** [comment]
Org too 
![image](https://user-images.githubusercontent.com/68164076/209457301-4ad8a62d-d1f1-4ab5-af38-0d832aa8f038.png)
