### ISSUE TITLE
Someone Else's Hard Work -Escort Quest in Mana Tombs not giving credit at end

### ISSUE THREAD

**Issue by slicplaya** [chromiecraft/chromiecraft#4566]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

After killing the mini boss with 98k hp during the escort, the quest NPC rests, then says "let's go," Then runs 2 steps and disappears instead of running to the entrance and moving to the spot where completion is yielded. I've attempted it 5 times standing directly on the quest NPC, ahead, side, and behind. It doesn't yield completion. Yes I removed and restarted the quest each time. Apparently, after reading through forums and blizz reports, if someone dies, they possibly won't get credit. I'm a hunter, so it's possible that using shadowmeld or Feign Death is bugging it from giving credit. I will attempt the quest again without using the skills once I convince a group to run it again :(

### Expected Blizzlike Behaviour

The NPC should continue to entrance where completion can happen.

### Source

https://us.battle.net/support/en/article/289339 This was also a problem on classic TBC a year ago.

### Steps to reproduce the problem

1. Start the escort quest inside Mana Tombs called, "Someone Else's Hard Work."
2. Traverse through the various mob fights up until the last mob(mini boss).
3. Kill mini boss, and watch/read quest NPC monologue. NPC moves on 2 steps after saying let's go and disappears.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Hey slicplaya. I was unable to recreate your problem. I got credit for the quest with or without using Feign Death/Shadowmeld.

**Comment by slicplaya** [comment]
> Hey slicplaya. I was unable to recreate your problem. I got credit for the quest with or without using Feign Death/Shadowmeld.

Then what could I possibly be doing wrong? I've tried staying on the npc the entire time, tried staying 10-15 yards in front, on side of, behind etc. I cannot gain credit it seems. I've tried 13 times now. Where are you standing when he says let's go? Directly on the npc?

**Comment by Gultask** [comment]
> > Hey slicplaya. I was unable to recreate your problem. I got credit for the quest with or without using Feign Death/Shadowmeld.
> 
> Then what could I possibly be doing wrong? I've tried staying on the npc the entire time, tried staying 10-15 yards in front, on side of, behind etc. I cannot gain credit it seems. I've tried 13 times now. Where are you standing when he says let's go? Directly on the npc?

The issue is that the targeting method for the script is incorrect, making it so that only one player can get credit. We're working on a fix.

**Comment by Buggyswires** [comment]
Bug confirmed. i just did the escort with a group and didn' get credit at the end
