### ISSUE TITLE
[Hellfire Peninsula] [NPC] Corporal Ironridge wrong model and location

### ISSUE THREAD

**Issue by ohkasdasf** [chromiecraft/chromiecraft#4568]
### What client do you play on?

deDE

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

![grafik](https://user-images.githubusercontent.com/84076297/208018287-cb5ffcf6-4a70-4732-becc-bb75adac73b4.png)

Corporal Ironridge's location is wrong in 70,65 instead of 71, 62 as the NPC attacks random mobs in the area. Also Ironridge has the wrong model, should be a male human as you can see from the wowhead sources, maybe accidentally used the wrong model of a Honor Hold Defender? Please check the links in sources.

### Expected Blizzlike Behaviour

Check sources. Am unsure about aggroing mobs, maybe has behavior of Honor Hold Defender? I don't think Ironridge should attack any mobs from the sources I have seen.

### Source

- Ironridge: https://www.wowhead.com/tbc/npc=21133/corporal-ironridge
- Honor Hold Defender: https://www.wowhead.com/tbc/npc=16842/honor-hold-defender
- https://www.youtube.com/watch?v=gTMz-ukkV6U&t

### Steps to reproduce the problem

1. Go to 71, 62.
2. Go to 70, 65.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report!
It seems like the NPC can get stuck there after being pulled by another player, but I can't reproduce it how it happened.
