### ISSUE TITLE
[Gurubashi Arena Event] Arena chest spawns quickly two times after each other

### ISSUE THREAD

**Issue by ohkasdasf** [chromiecraft/chromiecraft#4572]
### What client do you play on?

deDE

### Faction

Alliance

### Content Phase:

30-39

### Current Behaviour

When entering the Gurubashi Arena at ~5:55 AM ST there was a chest spawned in the middle and Short John Mithril was just walking back to his initial position which lead me to believe he just spawned the chest but I had not seen any /yell message from him in the chat.

After that I looted the chest and waited for the full hour, at 6 AM ST he did the normal procedure (/yell, walking in the middle, spawning the chest) and another chest was lootable.

A friend of mine reported that this happened to them once as well. I sadly don't have any screenshots or more information on this.

Also see issue: https://github.com/chromiecraft/chromiecraft/issues/4165 (don't know if this is the same issue and counted as duplicate or a different bug).

### Expected Blizzlike Behaviour

Only one chest every 3 hours should spawn (3, 6, 9, 12/0 AM/PM).

### Source

- https://www.wowhead.com/wotlk/object=179697/arena-treasure-chest#comments
- https://wowwiki-archive.fandom.com/wiki/Patch_1.4.0#Gurubashi_Arena_event
- https://wowwiki-archive.fandom.com/wiki/Gurubashi_Arena

### Steps to reproduce the problem

1. Head to the Gurubashi Arena 15 minutes before any of the normal times start (3, 6, 9, 12/0 PM/AM).
2. See if he spawns a chest before the normal time and if he does wait for him to spawn another at the full hour.

### Extra Notes

Also see issue: https://github.com/chromiecraft/chromiecraft/issues/4165

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
Yes, that is exactly the issue you linked

**Comment by ohkasdasf** [comment]
> Yes, that is exactly the issue you linked

Yeah, it might be, I will close this for now, unless someone has more information on this.

In my reported cases it was some time before the full hour, I don't think it was always exactly the same, ~10-15 minutes before the full hour. In the linked issue it is in both cases past the full hour.
