### ISSUE TITLE
Primed Key Mold drops of a mob

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#4576]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

It drops

### Expected Blizzlike Behaviour

It shouldn't

### Source

https://www.wowhead.com/item=31245/primed-key-mold

### Steps to reproduce the problem

Kill mob/look at db

### Extra Notes

https://wowgaming.altervista.org/aowow/?item=31245

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, do you remember which mob it dropped off?

**Comment by Tereneckla** [comment]
I did not loot it
I assume it was the one listed on aowow
Can just remove it from all drops as it should not drop anyways

**Comment by bojan112** [comment]
![WoWScrnShot_121822_041749](https://user-images.githubusercontent.com/14837349/208279730-3dd02d2f-f28b-40f4-83f7-468f9c313493.jpg)
i got it from rare in Zangarmarsh, but i can not start q, its just wasting inventory space

**Comment by Hihilist** [comment]
Please note that dropped https://wowgaming.altervista.org/aowow/?item=31245 is different than the actual one item https://wowgaming.altervista.org/aowow/?item=31239 starting quest.

The one (31245) that drops right now should be rewarded to the player after bringing the proper one (31239) to quest starter. The one we have right now (31245) is the objective of the quest, followed by the mats gathering quest [Fel Iron Bar (4), Arcane Dust (2), Mote of Fire (4)]

**Comment by dieing4me** [comment]
Can confirm, same item just dropped off the same rare for me too.

**Comment by Stump876** [comment]
I think the loot table for the Coildfang Emissary is wrong. But I can confirm, I killed her twice on CC and once on my local and each time she dropped this key mold, and no blue item. No matter what the root cause of the problem is, this item should not be dropped at all as it is item 31245 and not the quest item, as was stated above.
