### ISSUE TITLE
[TBC] [NPC] - Missing or wrong spawn loc on some rare spawns?

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4591]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

I have gone onto PTR and found every rare spawn in TBC. However there are a few missing or not found. Of the few, I captured one bugging out when it spawned. When coming into view of the player, it fell through the map. This leads me to think that some of the missing rare spawns are "ingame" but currently under the map unreachable. 

Here is the webm of a rare spawn falling under the map
[bugged spawn.webm](https://user-images.githubusercontent.com/62584589/208285455-4f743ae3-de38-4af1-b76c-60b272a61603.webm)

The following rare spawns I think are having this issue are:
Crippler - https://wowgaming.altervista.org/aowow/?npc=18689
Bro'Gaz the Clanless - https://wowgaming.altervista.org/aowow/?npc=18684
Hemathion - https://wowgaming.altervista.org/aowow/?npc=18692

### Expected Blizzlike Behaviour

While I know some rare spawns currently are having pathing issues, it would be nice to have these at least stay on the map and spawn. 

### Source

Pserver DB locs:
Crippler - https://wowgaming.altervista.org/aowow/?npc=18689
Bro'Gaz the Clanless - https://wowgaming.altervista.org/aowow/?npc=18684
Hemathion - https://wowgaming.altervista.org/aowow/?npc=18692

wotlk classic wowhead locs:
Crippler - https://www.wowhead.com/wotlk/npc=18689/crippler
Bro'Gaz the Clanless - https://www.wowhead.com/wotlk/npc=18684/brogaz-the-clanless
Hemathion - https://www.wowhead.com/wotlk/npc=18692/hemathion

### Steps to reproduce the problem

1. Go to each zone where rares spawn
2. Check to see if they are spawned ingame
3. Kill them if they are (mainly Hemathion currently) and .respawn the mob

### Extra Notes

Might be known or in the works to be fixed. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
![image](https://user-images.githubusercontent.com/62584589/208285691-9a9870cd-73be-4a46-b5ab-4b984a573d9c.png)

Screen cap from webm if you didn't see/understand it. Was a little quick and wasn't expecting it myself.

**Comment by Gultask** [comment]
One was missing entirely, the others had movement problems.

Thanks for the report!
