### ISSUE TITLE
[TBC Progression] Item - Nightmare Seed

### ISSUE THREAD

**Issue by Santaria94** [chromiecraft/chromiecraft#4592]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Now they probably don't drop from Nightmare Vine. 
Just in case, need to clarify in the database, if they are dropping now, then this needs a report on the AC.

### Expected Blizzlike Behaviour

Nightmare Seed drops from Nightmare Vine during the TBC era and their drop was removed with the release of Wotlk.
Since we now have TBC, the suggestion is to return them as part of the progression module.

https://www.wowhead.com/tbc/news/ten-things-to-do-before-wrath-of-the-lich-king-classic-releases-326926
>Collect Nightmare Seeds
 Nightmare Seed will no longer be obtainable in the Pre-Patch for Wrath of the Lich King, removed in Patch 3.0.2. When fully talented by a Warlock in Wrath Classic, Healthstones will restore 5,136 health and will likely be the preferred choice in end game content for Tanks.
For that reason,  Nightmare Seed might not be an end game consumable for tanks in Wrath Classic, but it can be very valuable while leveling up as a tank spamming Dungeons. If you are looking to spam dungeons as a Tank in Wrath Classic launch, it could be a good idea to stock up on Nightmare Seeds before they are completely removed.

### Source

https://www.wowhead.com/tbc/item=22797/nightmare-seed
https://www.wowhead.com/tbc/news/ten-things-to-do-before-wrath-of-the-lich-king-classic-releases-326926

### Steps to reproduce the problem

Check the database for Nightmare Seed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the suggestion!
