### ISSUE TITLE
[Quest - Hellfire Peninsula] Fel Guard Hound that you get from quest Shizz Work is following me after I've finished quest

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4595]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Quest mob that you get fom Shizz Work quest is following me whole time. Should dissappear after quest is done.
![WoWScrnShot_121622_173733](https://user-images.githubusercontent.com/80590226/208287197-e437c090-df9c-4e9a-b0d7-f9e94fabd245.jpg)

### Expected Blizzlike Behaviour

Should dissappear after quest is done.

### Source

https://wowpedia.fandom.com/wiki/Fel_Guard_Hound

### Steps to reproduce the problem

1. Pick quest
2. Summon him
3. Finish quest
4. and play for next 10 hours he will follow you

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Santaria94** [comment]
It is blizzlike

https://www.wowhead.com/npc=21847/fel-guard-hound#comments
>By sno4270 (8,132 – 3·20·92) on 2012/02/26 (Patch 4.3.2)		
So I finished the poo quest, finished the follow up killing the guy in the cave quest, and now I'm back in Thrallmar...and this guy is still with me. Granted, he does nothing other than following me after the poo quest...no eating, no assisting, etc. But I guess free companion pet until he goes away.

>By iDeus (2,571 – 1·14·22) on 2012/04/06 (Patch 4.3.3)		
I had this little fellow following me all over Hellfire as I quested, decided to log out for an hour came back and there he was! I then decided to see if he would follow me over to Azeroth but soon as I went through the portal he went on his happy little way, I came back through the portal to Outlands and he was gone for good. He followed me around for a good 3 hours after turning in the quest so the only way to get rid of this little guy that I know of is leave Outlands.

**Comment by Sneften** [comment]
> It is blizzlike
> 
> https://www.wowhead.com/npc=21847/fel-guard-hound#comments
> 
> > By sno4270 (8,132 – 3·20·92) on 2012/02/26 (Patch 4.3.2)
> > So I finished the poo quest, finished the follow up killing the guy in the cave quest, and now I'm back in Thrallmar...and this guy is still with me. Granted, he does nothing other than following me after the poo quest...no eating, no assisting, etc. But I guess free companion pet until he goes away.
> 
> > By iDeus (2,571 – 1·14·22) on 2012/04/06 (Patch 4.3.3)
> > I had this little fellow following me all over Hellfire as I quested, decided to log out for an hour came back and there he was! I then decided to see if he would follow me over to Azeroth but soon as I went through the portal he went on his happy little way, I came back through the portal to Outlands and he was gone for good. He followed me around for a good 3 hours after turning in the quest so the only way to get rid of this little guy that I know of is leave Outlands.

Hi Sataria, as of right now in Wotlk Classic which is probably one of the best sources we got the Fel Guard Hound do disappear when you complete the quest.
