### ISSUE TITLE
Stun DR from mobs

### ISSUE THREAD

**Issue by Jinteki01** [chromiecraft/chromiecraft#4599]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Currently no mobs on the server have diminishing returns on their stuns to players. They also spam their stuns one right after the other. This can lead to a character being perma-stunned. By time the last one is done, the first mob is doing their stun again.

### Expected Blizzlike Behaviour

There should be diminishing returns on stuns from mobs. And the mobs shouldn't just all spam their stuns as evidenced from the videos below.

### Source

All of these are timestamped from different class tanks as well, so not just a class specific thing. There a most likely more examples within each specific video as well.

This is from TBC Classic and timestamped where you can see the stun debuff showing a full and half duration stun.  
https://www.youtube.com/watch?v=mz-MIqorKr8&t=985s

This one is from original Wrath showing the same thing in the same dungeon (The Blood Furance)
https://youtu.be/z6v6LD5uXn0?t=158

Another example from original Wrath in the same dungeon.
https://youtu.be/WD54MiZFE0U?t=758

Here are some examples from an early dungeon as this is not just a TBC mobs/dungeon specific issue. It applies to all mobs in Wrath at least.

This one is from classic wow. It's vanilla classic even I believe from the date, so not just a Wrath thing. 
https://youtu.be/Q45HLimJ2IQ?t=6

And this one is from original Wrath. 
https://youtu.be/dvP08MdGwVw?t=388

### Steps to reproduce the problem

1. Get stunned by one mob for the full duration.
2. Another mob immediately stuns you again for the full duartion.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by pangolp** [comment]
@ChromieCraftServer That report needs to be untagged, because it already has a pull request associated with it.
