### ISSUE TITLE
Mail visual bug

### ISSUE THREAD

**Issue by Hemingway1970** [chromiecraft/chromiecraft#46]
##### SMALL DESCRIPTION:

Items in mail do not display enchants

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Item should display enchant

##### CURRENT BEHAVIOUR:

When displayed in inbox item does not display enchant. When taken out of mail item does have enchant displayed. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enchant an item 
2. Sent to alt
3. View before and after taking item out of mail. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
Might be a client limitation, have you seen this working on retail or other servers?

**Comment by Stifler82** [comment]
I confirm, the items enchanted and sent via Game Mail, until they enter the bag, the enchant inside the item is not visible.

https://user-images.githubusercontent.com/1884642/107156942-205f2e00-6979-11eb-8e2a-f92ac2bc1e2e.mp4

**Comment by 55Honey** [comment]
I could see enchantments with yesterdays compiled core in the mail. Did we miss the fix? Can someone confirm?

**Comment by claudiodfc** [comment]
@55Honey Fixed with this commit https://github.com/azerothcore/azerothcore-wotlk/pull/4872
