### ISSUE TITLE
[Mob] Scarlet Smith is not dropping Blacksmithing pattern Plans: Runic Plate Leggings

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#4604]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

50-59

### Current Behaviour

Mob Scarlet Smith (https://wowgaming.altervista.org/aowow/?npc=1885) which spawns only in one spot in the Hearthglen location, from Western Plaguelands area, should have 100% drop chance for pattern Plans: Runic Plate Leggings (https://wowgaming.altervista.org/aowow/?item=12719). This is marked in their possible loot table in the database (https://wowgaming.altervista.org/aowow/?npc=1885#drops).
However, when the aforementioned mob is killed by the player, the mob does not drop the pattern with suggested values.

### Expected Blizzlike Behaviour

When killed, mob Scarlet Smith drops pattern Plans: Runic Plate Leggings with 100% drop chance. 

### Source

https://www.wowhead.com/wotlk/npc=1885/scarlet-smith

### Steps to reproduce the problem

1. Go to Hearthglen location, in the Western Plaguelands zone (a spot with cords 43.6 12.8) [or use commands .list c 1885 and .go c 61634]
2. Verify if mob Scarlet Smith has spawned
3. Kill the aforementioned mob
4. Pay attention to dropped loot, if the pattern Plans: Runic Plate Leggings

### Extra Notes

Please note that there should be no other way to get this Blacksmithing pattern and combined with respawn timer of the mob (20 hours according to the Database) this issue is visibly affecting Collector-type players.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Hihilist, thanks for the report!

Does your character have the Blacksmithing skill? They're set to only drop if the player has at least 1 rank in the Blacksmithing skill.

**Comment by Hihilist** [comment]
Hey,
Just checked with the character having the Blacksmithing skill and it really drops. I could not find any hint that the profession is required to see the pattern.
Report can be closed then.
