### ISSUE TITLE
[Object] Windy Cloud and Swamp Gas can still spawn in areas requiring flying/extensive parkour

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#4607]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Swamp Gas (https://wotlkdb.com/?npc=17378) and Windy Cloud (https://wotlkdb.com/?npc=24222) can spawn in certain locations in Zangarmarsh and Nagrand, respectively, even requiring players to use a combination of certain skills (usually Slow Fall) and parkour, later in the game flying mount.
According to https://github.com/chromiecraft/chromiecraft/issues/4552 "Disabled the Windy Clouds (Gas Clouds) in Nagrand that are inaccessible until flying. Only the ground-level ones will be available." should limit their spawn locations to only reachable areas since flying mounts have been disabled.
However, there can be still found not only Windy Cloud but also Swamp Gas objects that cannot be reached until players have access to a flying mount or are able to perform extensive movements. Without proper distance, the player is not able to use their Zapthrottle Mote Extractor (https://wowgaming.altervista.org/aowow/?item=23821) to gather the gas objects.

Examples of "bugged" clouds:
![WoWScrnShot_121622_163226](https://user-images.githubusercontent.com/71841180/208318266-3a31ed5c-d0fa-411f-b8da-6c85b12b39ca.jpg)
![WoWScrnShot_121622_163439](https://user-images.githubusercontent.com/71841180/208318267-40b7412e-e198-4d6a-8dfa-4b87f5dee51a.jpg)
![WoWScrnShot_121722_163916](https://user-images.githubusercontent.com/71841180/208318268-13e7f562-7f03-4906-8a19-5d2f72c43da4.jpg)

### Expected Blizzlike Behaviour

Only ground-level Gas Clouds are available. Gas Clouds that are inaccessible until flying is, are disabled.

### Source

https://github.com/chromiecraft/chromiecraft/issues/4552

### Steps to reproduce the problem

1. Prepare a character with Engineering skill enough to use Zapthrottle More Extractor, with Extractor crafted
2. Go to one of these locations:
- Nagrand 54, 72
- Nagrand 56, 66
- Zangarmarsh 80, 66
3. Pay attention if Windy Cloud (Nagrand) or Swamp Gas (Zangarmarsh) object has spawned
4. Try to reach the cloud and use Extractor to drain the object

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Hihilist, is this the PTR or the Live ChromieCraft server?

**Comment by Hihilist** [comment]
Both. Spotted all three on Live and was able to confirm those two Windy ones on PTR as well.

**Comment by Gultask** [comment]
The PTR doesn't have the patch for the Windy Clouds to not spawn at a certain height, only Live does. Maybe the height I used definitely wasn't enough.
The Swamp Gas I definitely missed, although it looks like it's only one of them that's up there, looking at the DB spawns.
I'll look into it and add to my to-do but it might take a while.

Thanks for the report!

**Comment by Gultask** [comment]
Will be fixed in next restart. They were about 7 of them.
