### ISSUE TITLE
[Spell] Turbo-Charged Flying Machine still usable after forgetting Engineering profession

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#4608]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Turbo-Charged Flying Machine Control (https://wowgaming.altervista.org/aowow/?item=34061) created by Engineering teaches you the mount of the same name (https://wowgaming.altervista.org/aowow/?spell=44151) which is exclusive to owners of the Engineering profession. Even more, the usage of the mount is blocked if the character is not at the level of 375 Engineering, which is indicated in the mount's tooltip.
Currently, you can still use the mount after forgetting the Engineering profession, which is against the mount's requirements.
![WoWScrnShot_121822_220048](https://user-images.githubusercontent.com/71841180/208319857-d8e20a42-b3fa-4854-9fd5-59f1b0ce55db.jpg)

### Expected Blizzlike Behaviour

Turbo-Charged Flying Machine Control mount can be only used if the character is at the level of 375 Engineering, according to the mount's tooltip.

### Source

https://www.wowhead.com/wotlk/spell=44151/turbo-charged-flying-machine
https://wowwiki-archive.fandom.com/wiki/Turbo-Charged_Flying_Machine_Control

### Steps to reproduce the problem

1. Prepare the character with Engineering skill of 375
2. Learn how to craft Turbo-Charged Flying Machine Control item
3. Learn mount from the created item
4. Use the mount
5. Dismount
6. Unlearn the Engineering profession from the Skills tab in the Character panel
7. Try to use again the mount

### Extra Notes

Please note that Flying Machine Control https://wowgaming.altervista.org/aowow/?item=34060 giving mount https://wowgaming.altervista.org/aowow/?spell=44153 works properly and cannot be used when character unlearns Engineering profession.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
Everything seems to be working normally

![WoWScrnShot_010823_112005](https://user-images.githubusercontent.com/82369562/211190835-1c65dca5-649e-466c-a8d0-2adc86988b8f.jpg)
