### ISSUE TITLE
Arzeth The Merciless Quest

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#4619]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Arzeth the Merciless is currently standing in 1 spot in front of the stairs without moving.

I think his abilities might be missing too (mortal strike and shadowbolt volley)

### Expected Blizzlike Behaviour

He is supposed to path down the road as shown here:

https://wotlkdb.com/?npc=19354 and SPELLS

### Source

https://wotlkdb.com/?npc=19354 

https://www.youtube.com/watch?v=7Vjug-aByEM casting his spell

### Steps to reproduce the problem

1. Teleport to mob.
2. Check if he is moving.
3. Check abilities.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by HasieEST** [comment]
Hi,
as of time of writing, I have checked open PTR to see, if bug exists. Currently it doesnt not seem that Arzeth can't move.  It also can does cast spells and mortal strikes. What is apparent though is that once quest item has been used on him, Arzeth will become rooted to one place and root isnt removed from him once he is killed.  Will be adding WEBM files once conversions have been done.

**Comment by HasieEST** [comment]
Additional note, found this funny thing: 
![image](https://user-images.githubusercontent.com/25981761/208617470-af29bcd6-8d1e-4a09-a139-84374329ff1d.png)
**** Unsure why Mob has remaining time to respawn for 10 min while fulltime is stated to be 5 min. Might not understand something though.

**Comment by HasieEST** [comment]
[](https://youtu.be/LlAMrAY-kTc)[](https://youtu.be/2nRT0ueC4R4)

**Comment by HasieEST** [comment]
https://youtu.be/2nRT0ueC4R4
https://youtu.be/LlAMrAY-kTc

**Comment by Paradigmxd** [comment]
That's incorrect. I have leveled 2 characters and Arzeth is NOT pathing whatsoever....

**Comment by Paradigmxd** [comment]
I did notice he does cast shadowbolt volley and Mortal strike, but HE IS NOT moving. He is always in front of the stairs lol.

**Comment by HasieEST** [comment]
> I did notice he does cast shadowbolt volley and Mortal strike, but HE IS NOT moving. He is always in front of the stairs lol.

I'll reiterate again. Pathing is there, but rooting that is caused by quest item isn't cleared once mob is killed or effect wears off.

**Comment by BeefSteaker** [comment]
So it seems like if you enter combat and then run away he does path when he drops aggro.

snuck past him to get the the quest guy in the hut and he started pathing up and down

**Comment by Paradigmxd** [comment]
> So it seems like if you enter combat and then run away he does path when he drops aggro.
> 
> snuck past him to get the the quest guy in the hut and he started pathing up and down

Yes, but the problem is that if you kill him, he will respawn and never PATH Again...that's the whole point. He is broken. I have leveled 5 chars to 64 now and if you run away he will stat pathing until killed.

**Comment by BeefSteaker** [comment]
Oh yeah, not saying he's fixed, just info for anyone who tries to fix. 

It means he has pathing, but it's not trkggering

**Comment by Paradigmxd** [comment]
Ye, I agree Beef, thanks for the further info though! hopefully it gets resolved.

**Comment by Paradigmxd** [comment]
As of 22.APRIL.23 this is still bugged 

IF respawned he does not begin pathing

**Comment by Vyperhand** [comment]
Still bugged as of 7/11/23

**Comment by FrodoFragginz** [comment]
Still bugged 3/18/24
