### ISSUE TITLE
Aggem Thorncurse pet has wrong model

### ISSUE THREAD

**Issue by vmensik** [chromiecraft/chromiecraft#462]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Aggem Thorncurse summons a pet via spell https://wowgaming.altervista.org/aowow/?spell=8286 and the pet has a wrong model (small squirrel/rabbit). 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mob should have a model as seen on wowhead: https://classic.wowhead.com/npc=6021/boar-spirit

##### STEPS TO REPRODUCE THE PROBLEM:

1. Pull Aggem Thorncurse in RFK
2. Wait for summon

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Couldn't reproduce this:

![WoWScrnShot_042521_135159](https://user-images.githubusercontent.com/81782124/115980662-96188480-a5cd-11eb-8e5d-ba6dbd1ba997.jpg)

Are you using any custom patches for things like WoD models? They seem to move model IDs around and might cause something like this.

**Comment by Helias** [comment]
@vmensik be sure that you do not have any custom patches, if you don't and you still encounter this error reopen the issue
