### ISSUE TITLE
[Terokkar][Quest] Hai'shulud deals too much damage

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#4631]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

![image](https://user-images.githubusercontent.com/50233983/208750918-857ad590-b3de-4767-b65f-dce9c870a479.png)
Deals 1200 damage to a bear tank with normally 12k armor (yes, I know he reduces armor by 50%)

### Expected Blizzlike Behaviour

Various comments of soloing him

https://www.wowhead.com/npc=22038/haishulud#comments:id=1074618
https://www.wowhead.com/npc=22038/haishulud#comments:id=971923
https://www.wowhead.com/npc=22038/haishulud#comments:id=546350

### Source

Various comments of soloing him

https://www.wowhead.com/npc=22038/haishulud#comments:id=1074618
https://www.wowhead.com/npc=22038/haishulud#comments:id=971923
https://www.wowhead.com/npc=22038/haishulud#comments:id=546350

### Steps to reproduce the problem

.q add 10930
.go c 22105
Kill clefthoof
Use provided item to hopefully summon Hai'shulud

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=10930
https://wowgaming.altervista.org/aowow/?npc=22038

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
From PTR with 64 prot warrior
![image](https://user-images.githubusercontent.com/103856689/208984929-75c2f782-1d35-452d-86bf-aacb6a7e5805.png)
From Classic 67 Blood DK
![image](https://user-images.githubusercontent.com/103856689/208987061-00b6ddee-748a-47c0-8d57-c62abb739d22.png)
My first thoughts are that the posion damage need a buff on CC.
In many off the comments you link they use some cheesy strat or pop all CD's.

**Comment by Tereneckla** [comment]
Well, he despawned in the middle of me trying a cheesy strat

**Comment by Sneften** [comment]
> Well, he despawned in the middle of me trying a cheesy strat

Alright, seems like a different issue. I will try to look into that! Thanks for all the reports :)
