### ISSUE TITLE
[Item] Pendant of the Agate Shield

### ISSUE THREAD

**Issue by Testbaby02** [chromiecraft/chromiecraft#464]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Pendant of the Agate Shield (crafter Jewelcrafting item, skill 120) sells for 1 copper.
![image](https://user-images.githubusercontent.com/83083464/116003232-6da87e80-a5fd-11eb-827f-73c76e09b162.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normal sale price as mentioned on both [wowhead](https://www.wowhead.com/item=20950/pendant-of-the-agate-shield) and [wotlkdb](https://wotlkdb.com/?item=20950) is 15s 35c.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Obtain a Pendant of the Agate Shield
2. Check vendor price

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
See https://github.com/azerothcore/azerothcore-wotlk/issues/4902

"It vendors for the correct amount, it just SHOWS the wrong amount. It can only be fixed by a client side patch."

Closed because it's not a server issue.
