### ISSUE TITLE
Halaa Issues

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#4642]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

1. Able to capture Halaa with guards alive
2. Fire Bomb dot does not work

I have put these issues together as it would be impossible to capture Halaa if the 1st point is fixed before the 2nd

### Expected Blizzlike Behaviour

Alive guards lock capturing Halaa
Fire Bombs leave a dot that deals 1% of the targets damage per second

### Source

https://wowpedia.fandom.com/wiki/Halaa
> Once all 15 NPC defenders are dead, a LocalDefense/WorldDefense message "Halaa is defenseless!" signifies that Halaa may be captured by having more players than the opposing faction on the plateau itself. 

Bomb text itself
![image](https://user-images.githubusercontent.com/50233983/208964498-d8eeccec-d704-490f-865b-b17044290b47.png)

### Steps to reproduce the problem

.go object 182298
Cap the Roost
Take a wyvern and attack guards with bombs

Fly to the center of Halaa to cap it

### Extra Notes

https://wowgaming.altervista.org/aowow/?item=24538

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Tereneckla. Thanks for the report. I can confirm this. Halaa is not operating as it should 

On a side note `.go object` is not a GM command. There is `.go gameobject` that number can be found by using `.gobject near` and adding a distance, I typically use 50
![image](https://user-images.githubusercontent.com/68164076/209405733-f4f1d4b1-d6a4-4e08-8ac3-2cf2400eee90.png)
`.go gameobject 100342` will put me right at the bomb wagon. Or you could just `.tele halaa` to get into the ballpark.
