### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by Puddleglumn** [chromiecraft/chromiecraft#4651]
When fishing the raw longjaw mud snapper is not going into my bag.  It is giving me credit and giving me the point for the catch, but it doesnt go into your bag.  (gnome rogue - level 64)

**Comment by farrellmp3** [comment]
in many locations there are such fish

**Comment by Puddleglumn** [comment]
I could care less about the fish.  I was in ironforge fishing it.  The point is the bug.

**Comment by Stump876** [comment]
Please reopen this issue, and fill out the template when creating a bug report so we can also gather the general information as well as the specifics. What client you use, what modules and addons, and what version of the core is currently running. It's the reason we have it. 
![image](https://user-images.githubusercontent.com/68164076/209274134-874db934-4979-449a-a7e7-1227defffc7e.png)
