### ISSUE TITLE
Isla Starmane's Cage does not close on respawn

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#4657]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

![image](https://user-images.githubusercontent.com/50233983/209356768-6d62b021-4470-44cf-bb76-bb2c1a6adec9.png)

### Expected Blizzlike Behaviour

Cage is closed on respawn

### Source

There's a reason she has a cage

### Steps to reproduce the problem

.go c 18760
Do the quest/fail the quest/kill her on the quest
Wait

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=18760

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Tereneckla. Thanks for the report. I can confrim this on my local.

However .go c 18760 puts me at a snake in Zangarmarsh.
![image](https://user-images.githubusercontent.com/68164076/209376042-e8e739f1-540a-46ff-b236-a03aac35d0b8.png)
![image](https://user-images.githubusercontent.com/68164076/209376306-5949c077-c3d4-43e1-a7ba-a1659a666f57.png)

**Comment by Tereneckla** [comment]
Oh, have I been doing the wrong command the whole time
What is the command to a creature by their entry ID?

**Comment by Stump876** [comment]
I mix them up all the time. That number is used by wowhead for NPC IDs. TBH I have no idea what it's used for in game.  `.go gameobject 18760` puts me at a bench in the deeprun tram /shrug. The DB GUID number works for `.go creature` commands. But even if it's wrong, you always give pleanty of info to figure it out. A quest, or name of the NPC is usually all we have to go on. `.go c` is a bonus and makes the triager's life a bit easier.

**Comment by oysterdestroyer** [comment]
It seems she's also hostile to the NPCs upon spawning without starting the quest, risking her getting killed by NPCs on spawn.
