### ISSUE TITLE
Engineering explosives share a cd with Flamestrike

### ISSUE THREAD

**Issue by orfaze** [chromiecraft/chromiecraft#466]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When a dynamite/bomb is used, flamestrike will share a cooldown with them (1min)
The cd is not shown on flamestrike;
You'll see "Spell is not ready yet"

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Flamestrike should not share a cd with these

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use a dynamite/bomb from Engineering
2. Use Flamestrike

##### EXTRA NOTES:

Spell/bomb used in my test (probably all explosive are affected) : 

Solid Dynamite : 10507
Big Iron Bomb : 4394
Flamestrike rank 1 :  2120
https://wowgaming.altervista.org/aowow/?search=flamestrike

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by DobleInfery** [comment]
Sure got that problem also, plz take a look guys

**Comment by FrancescoBorzi** [comment]
@DobleInfery this issue is closed, if you think there is still a problem then please open a new issue
