### ISSUE TITLE
Scryer Firewing Signets rep quest not appearing

### ISSUE THREAD

**Issue by andreepic** [chromiecraft/chromiecraft#4660]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

My race is a draenei (lvl 64) and I finished the quest "Allegiance to the Scryers".
I went to the Scryer area and there were no quests there. Especially not at the NPC (Magistrix Fyalenn) which should give the repeatable rep quests.

I tried deleting my cache as advised and turning on "low-level quests", but nothing changes.

### Expected Blizzlike Behaviour

There should be a quest at Magister Fyalenn called "Firewing Signets". For me there is no quest at all.
According to WoWhead TBC there should be a difference in that Draenei start at lower rep, however I started at 0/3000 rep for neutral. I am not sure if this racial difference was removed in WOTLK

### Source

https://www.wowhead.com/tbc/quest=10412/firewing-signets 

https://www.wowhead.com/tbc/guide/the-scryers-reputation-rewards-burning-crusade-classic-wow

https://www.wowhead.com/tbc/npc=18531/magistrix-fyalenn

### Steps to reproduce the problem

- Have Draenei at lvl 64
- complete "Allegiance to the Scryers" quest
- check reputation of Scryers (mine was 0/3000 neutral)
- Go to NPC "Magister Fyalenn" to see whether any quest appears (For me nothing appeared)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by andreepic** [comment]
Thank you for checking. So I started at 0/3000 rep for neutral. I checked the PTR and as soon as I have 1/3000 rep I was able to access the quest. I solved this issue on my character by doing one quest for scryers after which I was around 200/3000 neutral rep. Then I was able to access the firewing signet quest.

I am not sure if this is as intended, but it seems like if you are able to provide 1 additional rep after the Allegiance to the Scryers rep to prevent this issue.

**Comment by cachocarne** [comment]
There's definitely something not ok with these values, reputations and requirements. The quests to turn in tokens should ONLY be available after completing the "Allegiance to the…" quest. However, now it's available even without completing that one. As Draenei or Blood Elf you will be unfriendly with either Scryers or Aldor and you simply need to turn in Basilisk eyes or Spider guts until you reach Neutral. However, that's also not working as it should, since even if you are at 0/3000 Neutral, you can still turn in these items (should only be available during Unfriendly). Big review needed.
