### ISSUE TITLE
Tasty Snapper - Murlocs dont follow you out of the water and evade

### ISSUE THREAD

**Issue by MasterPooBaa** [chromiecraft/chromiecraft#4663]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

When you spawn the murlocs by netting the tasty snapper fish pools, the murlocs should chase you out of the water.  They do not.  They simple stand in the water and evade ranged attacks.
[EDIT] This behavior seems to be common for many (all?) mobs that patrol in or around coastlines.
Murlocs in Bloodmyst, Murlocs south of Southshore, Turtles in Alterac on the banks of Lordamere lake.  Anywhere where mobs alternate between deep (swimming) water and wading water or land.

### Expected Blizzlike Behaviour

Murlocs should follow you out the water and not evade.

### Source

Quest: https://www.wowhead.com/wotlk/quest=9452/red-snapper-very-tasty
ver 3.3.5a

### Steps to reproduce the problem

1. Run into water.
2. Net fish school.
3. Murloc spawns and starts attacking.
4. Run to land.
5. Murloc doesnt follow.
6. Murloc evades ranged attacks.

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=9452

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi MasterPooBaa. Thanks for the report. I can't seem to reproduce this right now. I believe the water issues were fixed with the most recent updates. However I do believe it was a valid problem at the time of the report, just part of a larger issue.
