### ISSUE TITLE
Bael'dun Foreman never engages if attacked from afar

### ISSUE THREAD

**Issue by dengreven** [chromiecraft/chromiecraft#4665]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

20-29

### Current Behaviour

The Bael'dun Foreman (id 3375) in Bael'Modan/Southern Barrens does not attack in any way if engaged from afar (for example, as priest using shadow word: pain and the wand). The NPC just stands there and gets itself killed.

### Expected Blizzlike Behaviour

The Bael'dun Foreman should run close enough to toss it's torch and then engage in close combat with the player when attacked.

### Source

Do I really need to provide a source to prove that an enemy shouldn't just get itself killed without counterattacking?

### Steps to reproduce the problem

Go to Bael'Modan.
Clear any Bal'dun Excavators in the way, if any, keep distance to Bael'dun Foremans.
Engage Bael'dun Foreman from max range.
Bael'dun Foreman will visibly go into aggro mode, but not engage and just stand there until killed.
This also works if aggroing more than one Foreman from distance.

### Extra Notes

The mob is an objective of Gann's Reclamation, quest id 843.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
I tried to attack them with Fireball and [Bael'dun Foreman](https://www.wowhead.com/wotlk/npc=3375/baeldun-foreman) comes to me normally

[bael.webm](https://user-images.githubusercontent.com/82369562/211819299-33d856ce-df2d-4629-808a-efd703113394.webm)
