### ISSUE TITLE
Consortium monthly gem bag [Unmarked Bag of Gems] empty.

### ISSUE THREAD

**Issue by Zelfie** [chromiecraft/chromiecraft#4666]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Currently at honored reputation, went to Nagrand to complete quest=9884 [Membership Benefits], looted item=25419 [Unmarked Bag of Gems], opened bag.
Empty.
Consortium Christmas is ruined.

### Expected Blizzlike Behaviour

Bag should contain a random selection of gems, definintely more than zero.

### Source

https://www.wowhead.com/wotlk/quest=9886/membership-benefits#comments

Comments about a lot of things, none mention bags ever being empty.

### Steps to reproduce the problem

Complete quest=9884
or open item=25419

Behold your chance of nothing :(

### Extra Notes

I was a horde troll mage, doubt it makes a difference, but that's the info.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
![Screenshot_20221227_102833](https://user-images.githubusercontent.com/14080516/209625486-1e22bcd3-51e6-4bfe-bcbf-6c2f96566e6a.png)

**Comment by Zelfie** [comment]
![sad bag](https://user-images.githubusercontent.com/45595651/209852774-e31a1a0a-00b6-4a51-a149-75fe667f4788.png)

**Comment by Zelfie** [comment]
![WoWScrnShot_122822_175540](https://user-images.githubusercontent.com/45595651/209853141-5e1f8076-ff70-439d-85fc-0b5e8647f284.jpg)

**Comment by Zelfie** [comment]
Don't get me wrong, it isn't incredibly likely.
Seemed to be about 1/40, but getting my monthly bag on the live server and finding it empty felt pretty sad.

**Comment by IntelligentQuantum** [comment]
@Samsequel

**Comment by Gultask** [comment]
The items aren't in a group so there's a small chance to not drop anything. Definitely a bug.

**Comment by EdyGlockenspiel** [comment]
There seems to be a lot of 'openable' items broken like this. Darkmoon fair 12 ticket prize is one of them and there are some lockboxes as well that suffer this same fate.

**Comment by Zelfie** [comment]
Just to clarify it's the same for all rep variants of the consortium monthly bag.
Outcast's Cache from the Arrakoa Feathers is the same, items not grouped. I have another github post regarding that.

**Comment by Jinteki01** [comment]
Just had this issue occur with my gem bag. I opened the "Bag of Premium Gems" (exalted rep variant) and received nothing at all from the bag.
