### ISSUE TITLE
Node spawns seem off. 

### ISSUE THREAD

**Issue by Faeylia** [chromiecraft/chromiecraft#467]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

In my example here I'll be talking about Mageroyal Spawn points in Westfall, but this applies to all herb and ore nodes everywhere.
The node spawns shown on the wowgaming db are very different than the ones we can see on Classic wowhead DB for the same herb. 
![WOTLKDB](https://user-images.githubusercontent.com/83213817/116062782-827c2500-a684-11eb-9b8b-c0a9704bb972.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As far as I can see, the only change that would have affected Mageroyal nodes would have been after WotLK. (Cataclysm as it changed the zones.) And as such I believe the Classic wowhead db is more accurate when it comes to the spawn points. 
As you can see there is quite a difference at certain points of the map. 
![WowClassic_Wowhead_DB](https://user-images.githubusercontent.com/83213817/116063423-409fae80-a685-11eb-8b22-ae659807016e.png)
 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
This is unquestionably correct - nodes are indeed not perfectly Blizz-like. Your maps, and the number of duplicate and near-duplicate nodes in the DB is proof alone of that. 

But it's also so broad and far reaching - as you say, every node spawn across every zone in the game is potentially affected - that it's also un-fixable without better data than we have right now. What we have is an imperfectly reconciled patchwork put together from a few different sources, with duplicates removed by hand. (One active issue in the AC tracker (https://github.com/azerothcore/azerothcore-wotlk/issues/5379) suggests there are as many as a few hundred duplicate nodes in the database.)

Without better data though, this is unfortunately not something we have the ability to fix right now. Thanks for the report, however.
