### ISSUE TITLE
[Quest] `He Will Walk The Earth...` Does Not Provide Expected Item Rewards

### ISSUE THREAD

**Issue by swiftmatt** [chromiecraft/chromiecraft#4676]
### What client do you play on?
enUS

---
### Faction
Horde

---
### Content Phase:
61-64

---
### Summary
- Quest Name: `He Will Walk The Earth`
- Quest ID: `9866`
- Zone: Nagrand
- Faction: The Mag'har
- Player Faction: Tauren, Horde
- Reputation: Neutral
- Links:
  - [AoWoW](https://wowgaming.altervista.org/aowow/?quest=9866) 
  - [WotlkDB](https://wotlkdb.com/?quest=9866)
  - [Wowhead Classic](https://www.wowhead.com/wotlk/quest=9866/he-will-walk-the-earth) 

---
### Current Behaviour
The quest, [He Will Walk The Earth](https://www.wowhead.com/wotlk/quest=9866/he-will-walk-the-earth) did not provide any quest items. AoWoW is incorrectly displaying no item rewards for this quest.

---
### Expected Blizzlike Behaviour
The quest, [He Will Walk The Earth](https://www.wowhead.com/wotlk/quest=9866/he-will-walk-the-earth) should provide quest rewards upon completion.

---
### Source
- [Wowhead comment showing the `He Will Walk The Earth...` quest rewards in Jan 2007](https://www.wowhead.com/wotlk/quest=9866/he-will-walk-the-earth#comments:id=25087)
- [Wowhead comment showing `Greenkeeper's Pantaloons` source in Jan 2007](https://www.wowhead.com/wotlk/item=25574/greenkeepers-pantaloons#comments:id=27871)
- [Wowhead comment showing `Thunderbringer's Guard` source in Jan 2007](https://www.wowhead.com/wotlk/item=25575/thunderbringers-guard#comments:id=27874)
- [Wowhead comment showing `Smuggler's Mitts` source in Jul 2008](https://www.wowhead.com/wotlk/item=25576/smugglers-mitts#comments:id=3101380:reply=1293260)

---
### Steps to reproduce the problem
1. Reach level 64.
2. Reach Neutral with The `Mag'har`.
3. Talk to [Farseer Corhuk](https://wowgaming.altervista.org/aowow/?npc=18067)
4. Accept and complete [The Missing War Party](https://wowgaming.altervista.org/aowow/?quest=9864) (1/3)
5. Turn-in quest to [Saurfang the Younger](https://wowgaming.altervista.org/aowow/?npc=18229)
6. Accept and complete [Once Were Warriors](https://wowgaming.altervista.org/aowow/?quest=9865) (2/3)
7. Turn-in quest to [Saurfang the Younger](https://wowgaming.altervista.org/aowow/?npc=18229)
8. Accept and complete [He Will Walk The Earth...](https://wowgaming.altervista.org/aowow/?quest=9866) (3/3)
9. Turn-in quest to [Farseer Corhuk](https://wowgaming.altervista.org/aowow/?npc=18067)

At this point, you will notice that `Farseer Corhuk` will not provide you any items for completing this quest, which is the bug.

---
### Extra Notes
| Item ID | Item Name                | Link |
|:-------:|--------------------------|------|
| 25574   | Greenkeeper's Pantaloons | https://wowgaming.altervista.org/aowow/?item=25574 |
| 25575   | Thunderbringer's Guard   | https://wowgaming.altervista.org/aowow/?item=25575 |
| 25576   | Smuggler's Mitts         | https://wowgaming.altervista.org/aowow/?item=25576 |

---
### AC rev. hash/commit
https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

---
### Operating system
Ubuntu 20.04

---
### Modules
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

---
### Customizations
None

---
### Server
ChromieCraft

**Comment by davegrier** [comment]
The quest [Solving the Problem](https://wowgaming.altervista.org/aowow/?quest=9878) in Nagrand has identical rewards with different names, perhaps they were moved to this quest at some point.
