### ISSUE TITLE
"Insane Ghoul" wrong spawn location and behavior

### ISSUE THREAD

**Issue by Beastmasterwow** [chromiecraft/chromiecraft#468]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

NPC stands in place without moving on wrong location.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be spawned in church at the Tranquil Gardens Cemetery or be found walking around the church, instead he stands in place at the cemetry without any moving.
Link to the classic wow db: https://classic.wowhead.com/npc=511/insane-ghoul#comments
Link to the youtube video: https://www.youtube.com/watch?v=H-tsD6NGN9k
![image](https://user-images.githubusercontent.com/81812276/116096873-ecf38c00-a6a9-11eb-9f03-250ce9f6858f.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Duskwood, Tranquil Gardens Cemetery. Find the NPC "Insane Ghoul" in front of the church.
2. Don't know
3. No
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
thanks for the report, I fixed it, it will be live soon :wink:
