### ISSUE TITLE
[ Class - Mage ] [ Critical ] - Master of Elements Doesn't Refund Any Mana

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4682]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Master of Elements does not refund mana from any type of school when it crits. 
![mana](https://user-images.githubusercontent.com/62584589/209756964-47870eb7-434b-4dec-b9e0-97a8dbbd7f8d.png)

### Expected Blizzlike Behaviour

Master of Elements will refund 30% of the base cost of the spell from which it crit from. This includes direct crit damage as well as any dot crit damage. 
![image](https://user-images.githubusercontent.com/62584589/209756836-f18b546f-1e03-41d8-b378-e3a5fbba5c83.png)
https://wowgaming.altervista.org/aowow/?spell=29077
![image](https://user-images.githubusercontent.com/62584589/209756861-4df52d62-62ac-4cdf-8344-f49ccf8cb030.png)

### Source

https://wowpedia.fandom.com/wiki/Master_of_Elements?oldid=2396694
Notes from late wrath 2010. 

### Steps to reproduce the problem

1. Create a mage, and spec into 1-3 points of Master of Elements. 
2. Cast any spell that can crit, and watch combat logs for mana given back on crits
3. No crits refund any % of mana

### Extra Notes

This is a critical talent to fire as mana is a high issue for mages. Not getting this mana feedback makes the spec very weak. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
Ticket was opened about this way back last year : https://github.com/chromiecraft/chromiecraft/issues/694
and was confirmed as fixed in this post : https://github.com/azerothcore/azerothcore-wotlk/pull/7102
However something along the line has broken it again.

**Comment by Santaria94** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/14377
