### ISSUE TITLE
Unable to Skin Un'Goro Gorilla mob while on Apes of Un'goro quest line

### ISSUE THREAD

**Issue by KuristZero** [chromiecraft/chromiecraft#4684]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

50-59

### Current Behaviour

Unable to skin [Un'Goro Gorilla](https://www.wowhead.com/wotlk/npc=6514/ungoro-gorilla)'s in Un'Goro Craters North East while on quest [Apes of Un'goro](https://www.wowhead.com/classic/quest=4289/the-apes-of-ungoro) 

May be related to this previous error: https://github.com/chromiecraft/chromiecraft/issues/1923

Unlike the previous error, I have the pelts in my inventory and am able to skin the other Gorilla variants in the area without issue.
The error is "Creature is not Skinnable" and does not mention loot:
[Click here for screenshot](https://ibb.co/nP3ZkpH)

Once the quest is handed in, you are able to skin the gorillas again.
This suggests a loot table issue, where the 'invisible' quest item [Ungoro Gorilla Pelt](https://www.wowhead.com/classic/item=11478/ungoro-gorilla-pelt) may be preventing skinning while on the quest and with 2 of the pelts in your inventory.

Stompers and Thunderers did not appear to be affected

### Expected Blizzlike Behaviour

To be able to skin the Un'Goro Gorilla's mob while on the quest Apes of Un'Goro and with 2 of the skin's quest items in your inventory

### Source

Sorry, unclear on this?

### Steps to reproduce the problem

1. Accept the quest [Apes of Un'goro](https://www.wowhead.com/classic/quest=4289/the-apes-of-ungoro) 
2. Collect two of the item [Ungoro Gorilla Pelt](https://www.wowhead.com/classic/item=11478/ungoro-gorilla-pelt)
3. Defeat a [Un'Goro Gorilla](https://www.wowhead.com/wotlk/npc=6514/ungoro-gorilla)
4. Attempt to skin it

### Extra Notes

Quest: [Apes of Un'goro](https://www.wowhead.com/classic/quest=4289/the-apes-of-ungoro) 
Mob: [Un'Goro Gorilla](https://www.wowhead.com/wotlk/npc=6514/ungoro-gorilla)
Item: [Ungoro Gorilla Pelt](https://www.wowhead.com/classic/item=11478/ungoro-gorilla-pelt)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c05c45c51d3d414ab3bec40e3e4bc2b5c10a977e

### Operating system

Windows 10 Pro - Build 19044

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
I tested on my local server, reproducing all the steps, but everything looks fine to me
[gorillapelt.webm](https://user-images.githubusercontent.com/82369562/211878641-2e9a9aa3-9b33-4101-b395-4d0c6dc4c414.webm)
