### ISSUE TITLE
[TBC] Prospecting rates seem too low

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4691]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Prospecting rates for rare gems from adamantite ore are about 10% (6x 1,67%)

### Expected Blizzlike Behaviour

Patch 2.1 increased the prospecting rates by quite a margin
https://wowwiki-archive.fandom.com/wiki/Patch_2.1.0

Going by the comments of wowhead and an unfortunately deleted blizz forum post, prospecting rates should be around 20% (3% per rare gem) when prospecting adamantite ore, and half of it when prospecting fel iron ore
https://www.wowhead.com/tbc/item=23425/adamantite-ore#comments

Further, there are many sources stating 4% (see below) which would be 3x the rates we have right now.

### Source

this source even suggests 4% for the epic gems each
https://youtu.be/-rPXc24DZOc?t=521

which seems to be supported looking at this video
https://youtu.be/T0dDBoU0zF0?t=22
https://youtu.be/T0dDBoU0zF0?t=95

https://youtu.be/_WBz9IMRETw?t=172
https://youtu.be/F2IM025ZL6s?t=707

### Steps to reproduce the problem

.additem adamantite ore
/cast prospecting
/tar adamantite ore

### Extra Notes

You shouldnt be able to get 2 different rare gems from prospecting, but still have a total combined chance of 6x 4% to get a rare gem from prospecting adamatite ore. Hence, it is 24% chance to get a rare gem, which is then equally divided between each rare gem.

For the uncommon gems, its similar, but since patch 2.1 you are always guranteeed to get at least 1 gem, and rares seem to occur on top of uncommon gems.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c05c45c51d3d414ab3bec40e3e4bc2b5c10a977e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Synful-Syn** [comment]
I am in the process of triaging.
The video on https://youtu.be/_WBz9IMRETw?t=172 is from a private server. It got posted on youtube on March 16th 2021 while Classic TBC was released on June's First 2021.

**Comment by balleny** [comment]
the change only adjusted adamantite ores prospect rates, not fel iron ore
