### ISSUE TITLE
[Underbog] Hungarfen spell Underbog Mushrooms insta kill people

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4693]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

When he spawns Mushroom it is to late :D everyone near it dies instantly.
![WoWScrnShot_122922_183817](https://user-images.githubusercontent.com/80590226/209989447-7ddc8b54-b966-42c5-860b-b8b3b092a690.jpg)
![WoWScrnShot_122822_205632](https://user-images.githubusercontent.com/80590226/209989450-a6f7f6ba-02f8-4e0f-9ddb-1379a484dd54.jpg)

### Expected Blizzlike Behaviour

https://wowwiki-archive.fandom.com/wiki/Hungarfen

Spawn at random locations on the platform and immediately begin to grow in size. After a few seconds they explode and release a Spore Cloud that lasts 20 seconds. The cloud inflicts 360 nature damage every 2 second. This can stack up to 5 times.

Should not 1 shot people

### Source

https://wowwiki-archive.fandom.com/wiki/Hungarfen

Spawn at random locations on the platform and immediately begin to grow in size. After a few seconds they explode and release a Spore Cloud that lasts 20 seconds. The cloud inflicts 360 nature damage every 2 second. This can stack up to 5 times.

Should not 1 shot people

### Steps to reproduce the problem

1. Pull him
2. And see people dying whenever he uses spell on someone

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c05c45c51d3d414ab3bec40e3e4bc2b5c10a977e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Duplicate issue https://github.com/chromiecraft/chromiecraft/issues/4662
