### ISSUE TITLE
Fenclaw Thresher - Faerie Fire

### ISSUE THREAD

**Issue by Lludara** [chromiecraft/chromiecraft#4695]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

Fenclaw Threshers in Serpent Lake (Zangarmarsh) are not displaying immune or resist messages when casting Faerie Fire on them. When the graphic shows above their heads, it should be applied, and it is not.

### Expected Blizzlike Behaviour

Faerie Fire should land or show a resist/immune message.

### Source

![image](https://user-images.githubusercontent.com/92132501/209996548-cd7ac318-db76-49dc-9b0d-c1b045171124.png)

### Steps to reproduce the problem

/cast Faerie Fire on Fenclaw Thresher, between 52.7, 44.5 and 47.4, 42.0 Zangarmarsh
Debug Flag
I cannot view console command, and it is not showing in combat log. Console command would help

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c05c45c51d3d414ab3bec40e3e4bc2b5c10a977e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Lludara** [comment]
Found it is also causing issues on Arrakkoa, Teromoth, and spider mobs in Terokkar

**Comment by avarishd** [comment]
Thanks for the report, Lludara.
As of rev. https://github.com/azerothcore/azerothcore-wotlk/commit/f5421722819342ccd76a0b099cf8ed4d879581d1
There were no issues with Faerie Fire (untalanted, talanted or feral)
Could not reproduce
<details>

![image](https://user-images.githubusercontent.com/46330494/226191973-0c44b1d7-1377-4749-b95f-13d9f50d6b64.png)
![image](https://user-images.githubusercontent.com/46330494/226192061-0c57ad6f-24f2-4c3e-8d86-aa650521169f.png)
![image](https://user-images.githubusercontent.com/46330494/226192070-ecfc47dc-8ff0-4384-b800-54a9730f36c5.png)
![image](https://user-images.githubusercontent.com/46330494/226192130-51ef57e8-6ece-4eb2-b158-ba8c2b81b126.png)
</details>
