### ISSUE TITLE
Quest - Plagued Lands

### ISSUE THREAD

**Issue by Knewklear** [chromiecraft/chromiecraft#47]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### SMALL DESCRIPTION:

![WoWScrnShot_020521_015403](https://user-images.githubusercontent.com/58756521/107109797-276b2c80-6811-11eb-963f-56842e33da24.jpg)

NPC follows player after turn-in.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://www.youtube.com/watch?v=8K8o_qWWNzU&ab_channel=Bue

##### CURRENT BEHAVIOUR:

There is no dialogue and cleansing animation after the turn-in.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
I completed the quest without problems with a gnome warrior.

**Comment by Knewklear** [comment]
> I completed the quest without problems with a gnome warrior.

So you brought the bear to the NPC after using the trap and the NPC cleansed the bear and it vanished?

**Comment by Helias** [comment]
I can confirm this.

The quest can be completed, but the bear is not cleansed, sometimes it disappears before you complete the quest and when you copmlete the NPC does not cleanse the bear.

**Comment by Helias** [comment]
Moreover, the gossip of the NPC "I have lost a trap" should be visible only if you have the quest about the trap
![image](https://user-images.githubusercontent.com/519778/107150537-9013ef80-695e-11eb-8071-3cd5c542cef3.png)

**Comment by Stifler82** [comment]
Fixed
-
**Video Test:** [Quest - Plagued Lands](https://youtu.be/e6mSSaEi6JA)
