### ISSUE TITLE
[NPC] Hezrul Bloodmarks Bodyguards not aggroing

### ISSUE THREAD

**Issue by blackcrowX** [chromiecraft/chromiecraft#472]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ X ] Horde

##### CONTENT PHASE:

- [ X ] Generic
- [ X ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Hezrul Bloodmark is accompanied by 2 Kolkar Bloodchargers which dont aggro onto the player when Hezrul Bloodmark gets aggroed and are a bit behind him.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When aggroing Hezrul Bloodmark the Kolkar Bloodchargers also get aggroed. Also the yfollow him a bit nearer.

https://classic.wowhead.com/npc=3396/hezrul-bloodmark

https://db.rising-gods.de/?npc=3396

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Aggro Hezrul Bloodmark
2.  Watch the two Kolkar Bloodchargers leisurely continuing to walk
3.  Kill Hezrul Bloodmark easily
4.  Wonder why he bothers to hire bodyguards

##### EXTRA NOTES:

https://classic.wowhead.com/quest=852/hezrul-bloodmark#comments

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by blackcrowX** [comment]
Sadly I don't have any more helpful screenshots

![WoWScrnShot_042721_140715](https://user-images.githubusercontent.com/79520609/116240142-ca25ae00-a763-11eb-9e99-ac2fbd800e10.jpg)

**Comment by Helias** [comment]
thanks for the report, I'll fix it
