### ISSUE TITLE
[ Object - Swamp Gas ] Gives Mote of Water Instead of Mote of Life 

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4730]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

[Swamp Gas](https://wowgaming.altervista.org/aowow/?npc=17378) currently gives [Motes of Water](https://wowgaming.altervista.org/aowow/?item=22578) when using [Zapthrottle Mote Extractor](https://wowgaming.altervista.org/aowow/?item=23821)

[gas.webm](https://user-images.githubusercontent.com/62584589/210223627-3c5dc121-31bb-42f4-b471-9bcd2204b9a7.webm)

### Expected Blizzlike Behaviour

Swamp Gas should be giving [Motes of Life](https://wowgaming.altervista.org/aowow/?item=22575) before [patch 2.3](https://wowpedia.fandom.com/wiki/Patch_2.3.0#World_Environment)

![image](https://user-images.githubusercontent.com/62584589/210224286-b600ede1-462f-4a89-867a-08da24e28eaf.png)

### Source

https://wowpedia.fandom.com/wiki/Swamp_Gas
https://wowpedia.fandom.com/wiki/Patch_2.3.0#World_Environment
https://www.wowhead.com/wotlk/npc=17378/swamp-gas#comments (pre 2.3 comments)

### Steps to reproduce the problem

1. Learn engineering and raise skill to 305
2. Equip a Zapthrottle Mote Extractor
3. Harvest a swamp gas node

### Extra Notes

Perhaps to not make another ticket, but in tow with the change to swamp gas nodes, Windy Cloud nodes in Nagrand weren't harvestable till [patch 2.3](https://wowpedia.fandom.com/wiki/Patch_2.3.0#World_Environment) also. 
https://wowpedia.fandom.com/wiki/Windy_Cloud
![image](https://user-images.githubusercontent.com/62584589/210224640-211d7a01-a3bf-46d7-90f3-2d71de965b49.png)
![image](https://user-images.githubusercontent.com/62584589/210224737-6d98bd39-8c34-430f-a800-2892da5b74c5.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c05c45c51d3d414ab3bec40e3e4bc2b5c10a977e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Cooties. The core is 3.3.5. This is blizzlike.

**Comment by Cooties-cc** [comment]
So, are devs just arbitrarily picking things that were specific to TBC progression to include and disclude? I don't know what to report as a bug if the dev team is making changes like not allowing certain items until later patches, since it was true to the original TBC progression release timeline. Yet things like this which were only changed and modified inside TBC itself, not later in a wrath patch, are said to be blizzlike. There is no standard to follow when reporting "bugs" then.

**Comment by Stump876** [comment]
Nothing arbitrary about it. TBH I'm not sure how the progression module works, and how they want it to operate on CC. That is why I left it tagged `Needs Triage` I had to learn a bit about it and see if it was intened, and how it should be handled. I can confirm what you say on CC and the PTR, and your souce is good. But the issue isn't with 3.3.5 AC, instead, with the progression module. It shouldn't be linked to AC. I just wanted to double check. Confirmed and linked.

**Comment by Gultask** [comment]
Hey, @Cooties-cc, not everyone is up to speed on the progression module other than a few of the staff members directly related to it. We do what we feel is best and is within our power to do. So some stuff can't be easily fixed while others is just a few lines of .sql.

Some people have started to add [Progression] in the title of their issues to more easily identify them, but that isn't a requirement. Thanks for the report!
