### ISSUE TITLE
[Progression] Nagrand Gas Clouds shouldnt be available yet

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4739]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Gas Clouds are available in Nagrand

### Expected Blizzlike Behaviour

They were introduced with patch 2.3

### Source

https://wowwiki-archive.fandom.com/wiki/Zapthrottle_Mote_Extractor?oldid=980946

clouds in nagrand introduced in patch 2.3
https://wowwiki-archive.fandom.com/wiki/Zapthrottle_Mote_Extractor#Patch_changes

### Steps to reproduce the problem

.

### Extra Notes

As progression had an adjustment to the clouds in Zangamarsh (Life instead of Water motes) https://github.com/chromiecraft/chromiecraft/issues/4730
the same patch by blizzard also introduced Nagrands clouds. before that they werent available.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/c05c45c51d3d...3ad652d8ab96

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
It's under staff discussion as Cooties pointed this out in the other issue.

I prioritized doing the Mote change first due to it being the less drastic of both suggestions.
Both changes take about the same amount of effort to implement, too. One line of SQL for each.

**Comment by The-GhostRider** [comment]
I am closing the report because it has become "Obsolete" and no longer relevant since the server progress has reached level 70.

**Comment by balleny** [comment]
> I am closing the report because it has become "Obsolete" and no longer relevant since the server progress has reached level 70.

level 70 has nothing to do with the progress of this ticket. the mote content is based on phases / patches.

**Comment by Rorschach91** [comment]
We are in Black Temple phase now. I think that it can be closed.
