### ISSUE TITLE
[MINING] Double Node (Tin/Silver) in Silverpine Forest

### ISSUE THREAD

**Issue by blackcrowX** [chromiecraft/chromiecraft#474]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ X ] Horde

##### CONTENT PHASE:

- [ X ] Generic
- [ X ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Double Node of Tin Vein and Silver Vein at [59,50|75,50] in Silverpine Forest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No double Node spawning at [59,50|75,50] in Silverpine Forest.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Coordinates [59,50|75,50] in Silverpine Forest.
2.  Observe double Nodes
3.  Be Amazed!

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by blackcrowX** [comment]
![WoWScrnShot_042721_190731](https://user-images.githubusercontent.com/79520609/116283858-b6427200-a78c-11eb-8223-f1991b69d301.jpg)
![WoWScrnShot_042721_190733](https://user-images.githubusercontent.com/79520609/116283879-bb9fbc80-a78c-11eb-9874-2facac15f189.jpg)

**Comment by SpaceRaton** [comment]
Observed Tin/Silver double node again at Silverpine [59,34|75.48].

**Comment by heyitsbench** [comment]
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/fd7c8a0bde61508c8654c7be92c9fc2be65d2ac2.
