### ISSUE TITLE
juggernaut and recklessness were reported wrong  and got fixed wrong (obv...)

### ISSUE THREAD

**Issue by Reily93** [chromiecraft/chromiecraft#4740]
basically if u pop reck and after u charge u should consume 1 stack of rek and juggernaut cause the buff stack eachother cause the tooltip says addictional, so if i have 30% and i pop reck i reach 130%100%+30)+ 25% crit(slam or mortal) i have  total of  155% crit chance so my mortal strike have TO BE A CRIT(same for slam) here is the prof from official server Benedition rank 1 warrior watch the clip from minute 23:03-23:16  put attenction to the istant when he pop reck then go charge and the second he lands mortal he crit it and consume juggernaut and 1 stack of reklessness at same time.
https://www.twitch.tv/videos/1696009658

**Comment by Cooties-cc** [comment]
There is still a problem then in that you can gain juggernaut and recklessness, and not get crits, even with above a 100% chance to crit. 

https://user-images.githubusercontent.com/62584589/210718858-444ceb16-7cf8-4577-bf13-77e03e282980.mp4

As seen here, you can gain both the buffs, which alone is 125% increase crit chance, and not crit, but it only eats the Jugg buff. The logic and info at the time present was that the 1st roll was given to jugg chance, then to reck, going by order of buff operations. 

However the true problem isn't that, but instead it's not combining the 2 buffs into the next slam or MS. Only jugg's +25% chance seems to be applied, but if that results in a crit, both jugg and reck get consumed. The correct fix would to look at the logic of jugg and reck while they are both up, and see if the player crit chance is actually correct (it won't show on char pane %).

The data provided is also from wotlk classic, which is a mostly fine as a source. However the snarky attitude isn't really helpful when trying to fix problems.

**Comment by Stump876** [comment]
When making a bug report please don't bypass the template. If there is a bug to be reported, assuming this is still an issue, the template would need to be filled out properly. Please include any sources.
