### ISSUE TITLE
Feedback from Nagrand Event

### ISSUE THREAD

**Issue by Erson33** [chromiecraft/chromiecraft#4746]
Hello! Two bits of feedback.

1. People should need to be flagged for pvp to interact with the wyvern roosts
2. Area for Token generation needs to be expanded to encompass wyvern roosts

Thanks!

**Comment by 55Honey** [comment]
Hi @Erson33 ,
Thanks for the feedback.
Discussions are a better place for these infos. Unless something is not blizzlike or breaks progression. I'm not sure if the interaction should require PvP to be blizzlike tbh. Maybe this is subject of a triage.

**Comment by Stump876** [comment]
Hi Erson33. The "event" part, handles spawns, respawns, and teleports. The actual pvp and capturing of Halaa, or any of the world pvp areas, should be blizzlike. If what you say is the proper blizzlike behavior, we would neeed you to open a new report and fill out the provided template. Please include any sources. 

Looks like someone opened one for Token ranges https://github.com/chromiecraft/chromiecraft/issues/4760
