### ISSUE TITLE
Zaxxis Insignia not dropping

### ISSUE THREAD

**Issue by shaszun** [chromiecraft/chromiecraft#4750]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Item not dropping.

### Expected Blizzlike Behaviour

The item to drop without any prerequisites.

### Source

Drop rate should be 50% from all 3 types of NPC.

https://www.wowhead.com/wotlk/item=29209/zaxxis-insignia

The items should be droppable without completing any of the quests.

https://www.youtube.com/watch?v=7tHrLzUqkGc&ab_channel=PhoenixGaming

### Steps to reproduce the problem

1.Teleport Netherstorm
2.Go south of Area 52
3.Kill Zaxxis npc or Warp-Raider Nesaad

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
they very much behave like the warbeads and powder in Nagrand, and the armaments and plants in Zangas.
seems unlikely that the current behavior is intended, but given that all others drops without having at least the first quest accepted, this might be intentionally and actually blizzlike.
maybe, someone can confirm from the retail ptr, if the items drop also without having the first quest accepted.

**Comment by Cooties-cc** [comment]
Old wowhead comments seem to suggest that if they aren't dropping, to accept the quest. Another mentioned killing Warp-Raider Nesaad if none were dropping, but did nothing on the server. 

The video provided wasn't during wotlk, dated 2016, so it's somewhere near end of WoD. 
![image](https://user-images.githubusercontent.com/62584589/210708413-cab6712a-b5ed-4214-a308-c3c576ecda6a.png)
*patch 6.2.3

I personally want these to be free drops before any quests, but I'm leaning more towards the 1st quest needing to be accepted for them to drop, based on what can be gathered atm.
