### ISSUE TITLE
The Nagrand Mini event between Gankly Rottenfist and Kristen Dipswitch

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#4753]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Gankly got killed by the Nesingwary NPCs. Kirsten is not present.

### Expected Blizzlike Behaviour

Gankly should remain stealth. Gankly is only unstealthed if he has killed Kirsten and got her skins to present to harold lane. 
If Player kills Gankly, Kirsten gives the quest, assuming she is there.

### Source

https://www.wowhead.com/tbc/npc=18297/gankly-rottenfist#comments

https://wowpedia.fandom.com/wiki/Patch_2.0.3

### Steps to reproduce the problem

1. Check if Kirsten even spawns.
2. Check if NPCs at Nesingwary Camp Nagrand can kill Gankly.
3. End

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
I can confirm she spawns, I've done the quest on CC.  Checking on my local, everything seems to be working fine. Do you have any screen shots?
![image](https://user-images.githubusercontent.com/68164076/211168274-d68c1323-0703-4c47-a3c0-2535107a7014.png)
![image](https://user-images.githubusercontent.com/68164076/211168286-0d10ff6c-6d56-482a-8324-67f1189e9058.png)
![image](https://user-images.githubusercontent.com/68164076/211168303-53cf87c3-c5c5-4977-bc5f-fd05f625638c.png)
![image](https://user-images.githubusercontent.com/68164076/211168342-e9eab8eb-760d-41b9-ac5e-fe8fcb8a10d5.png)

**Comment by Stump876** [comment]
Talking it over with CC engineering, this may be related to a server setting.
