### ISSUE TITLE
[warrior] Rage dont get generate from block , parry and dodge

### ISSUE THREAD

**Issue by Reily93** [chromiecraft/chromiecraft#4758]
i noticed that hitting someone with auto attacks(white hits) dont generate rage if the attack get blocked, dodged or parried
https://vanilla-wow-archive.fandom.com/wiki/Rage#:~:text=The%20primary%20cause%20of%20rage,of%20rage%20when%20they%20dodge.
in this patch there is a note about rage where is says fixed a bug where normal hits dont generate rage from parry , block and dodge

**Comment by Reily93** [comment]
i noticed that hitting someone with auto attacks(white hits) dont generate rage if the attack get blocked, dodged or parried
https://vanilla-wow-archive.fandom.com/wiki/Rage#:~:text=The%20primary%20cause%20of%20rage,of%20rage%20when%20they%20dodge.
in this patch there is a note about rage where is says fixed a bug where normal hits dont generate rage from parry , block and dodge

**Comment by Sneften** [comment]
Hey Reily!
The link you shared says that you should generate rage when you block, parry or absorb an attack.
It also says that sucessesful "white hits" generate rage.

**Comment by Reily93** [comment]
[Patch 1.3.0](https://vanilla-wow-archive.fandom.com/wiki/Patch_1.3.0) (patch date:2005-03-07): Fixed a bug where rage was not being generated when normal melee attacks were parried, dodged, and blocked.

**Comment by Sneften** [comment]
> [Patch 1.3.0](https://vanilla-wow-archive.fandom.com/wiki/Patch_1.3.0) (patch date:2005-03-07): Fixed a bug where rage was not being generated when normal melee attacks were parried, dodged, and blocked.

Yes im interpertating that as incoming attacks. But need to look into it more 👍

**Comment by Reily93** [comment]
i have ur same dubt but even if u are the one who block dodge or parry , u still dont generate rage i tested each

**Comment by Sneften** [comment]
Tested on wotlk classic and you do not get rage when a mob block, dodge or parry.
To gain rage when you block, dodge or parry you need to put points in the Shield Specialization.

Here is a template you can use when reporting bugs/issues in the future:https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&template=bug_report.yml
