### ISSUE TITLE
Going, Going, Guano!  Wrong quest level/show

### ISSUE THREAD

**Issue by Jermuwolf** [chromiecraft/chromiecraft#4763]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

30-39

### Current Behaviour

Going, Going, Guano! quest giver does NOT show up at 30lvl from Master Apothecary Faranell unless you track "low level quest".

When taking this quest, it shows itself as "green" aka low level quest.
It's 30lvl quest, it should be orange at 30lvl chars. 

### Expected Blizzlike Behaviour

It should show up normally  30-36  level chars, without being "low level quest" 

### Source

WoWhead:
https://www.wowhead.com/classic/quest=1109/going-going-guano

### Steps to reproduce the problem

1.Level up 30 *ding!*
2. Go undercity, forget portals are gone. Curse at zeppelin.
3. Wonder why there is no quest at undercity.
4. Talk to questgiver
5. Recieve "green"/low level quest.
6. It should be 30lvl orange quest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Hi jermuwolf thanks for the report! 
The Quest is supposed to be green starting from level 29 in wotlk. 
Your source is from classic vanilla.
https://www.wowhead.com/wotlk/quest=1109/going-going-guano
