### ISSUE TITLE
[Progression] sethekk halls giving Lower City Reputation past honored

### ISSUE THREAD

**Issue by Fibri123** [chromiecraft/chromiecraft#4764]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

Shetek Halls Gives rep with Lower City Past Honored, this is intended Behaviour since patch 2.3 in TBC.

### Expected Blizzlike Behaviour

Shetek Halls should give rep with Lower City Past honored since patch 2.3 it is working correctly as of now. 

### Source

https://wowwiki-archive.fandom.com/wiki/Sethekk_Halls
"Killing mobs in the Sethekk Halls grants [Lower City](https://wowwiki-archive.fandom.com/wiki/Lower_City) reputation up to [exalted](https://wowwiki-archive.fandom.com/wiki/Exalted)."
https://www.wowhead.com/tbc/zone=3791/sethekk-halls#comments
<html>
<body>
<div class="comment-header" style="outline: none; max-height: 1e+06px; color: rgb(204, 204, 204); font-size: 13px; margin: 0px; padding: 0px 0px 0px 10px; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 36, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

By 93126 (1,159 – 4·8) on 2007/10/12 (Patch 2.2.3) |   |  
-- | -- | --

</div><div class="text comment-body comment-high-rating" lang="en" style="outline: none; max-height: 1e+06px; overflow: auto; padding: 10px 0px; color: rgb(204, 204, 204); line-height: 1.4; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 36, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">With patch 2.3, running Sethekk Halls will give reputation with Lower City through Exalted.<br style="outline: none; max-height: 1e+06px;">(Source:<span> </span><a href="http://www.worldofwarcraft.com/patchnotes/test-realm-patchnotes.html" target="_blank" style="outline: none; max-height: 1e+06px; color: rgb(255, 209, 0); cursor: pointer; text-decoration: none;">http://<wbr style="outline: none; max-height: 1e+06px;">www.worldofwarcraft.com/<wbr style="outline: none; max-height: 1e+06px;">patchnotes/<wbr style="outline: none; max-height: 1e+06px;">test-realm-patchnotes.html</a>, listed under Dungeons and Raids)</div>
</body>
</html>

So it is currently working as intended, However since we are trying to Emulate tbc progression on chromiecraft, i belive this should be changed back to release tbc status along with Heroic Keys being changed from honored to Revered, Kazzak/doomwalker loot being changed from BoE to BoP. Etc. If it stays like this people will grind LC exalted Next bracket by Spamin SH Normal and Skip the Legendary Shadow lab grind to Revered/Exalted. This is arguable and there are still few reasons to go to shadow labs even without rep, Spellstrike Pants Pattern drop there for Tailors from Murmur for example(it also drops on heroic). 

### Steps to reproduce the problem

1.Enter Sheteks Halls 
2.Kill Stuff
3.Get Exalted in 60-69 Bracket. 

### Extra Notes

This is just an opinion, Me and few people i talked to agree with. that should be changed to keep OG tbc progression.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Win11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Samsequel** [comment]
@Gultask will take a look at this when they have the time :)
