### ISSUE TITLE
Cursed talisman has lower drop chance than WOTLK Classic.

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#4771]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

Cursed Talisman does not abide by chance %. 10 mobs killed should yield at least 2 talismans. Total of 15 mobs yielded 0. I suspect the cursed talisman drop rate may therefore be bugged.

### Expected Blizzlike Behaviour

Cursed Talisman should have 25% drop chance in WOTLK and 80% in TBC.

### Source

https://wotlkdb.com/?item=30157

https://www.wowhead.com/wotlk/item=30157/cursed-talisman

### Steps to reproduce the problem

1. Fight 20 mobs as Alliance player.
2. Check if that yields talismans similar to 25% drop chance.
3. Alternatively, check if they have the correct drop CHANCE. on DB

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
I do not have a local server to check the DB right now, but with the good old boring brute force I got 47 Talismans in 200 kills which is well in the expected value
I also could not find a pull request changing the drop rate and this online DB from an older version of Azerothcore has the same values listed as wowhead and wotlkdb
https://wowgaming.altervista.org/aowow/?item=30157

**Comment by Paradigmxd** [comment]
Must have been unlucky chance for me then! But indeed, your calculations match that. Perhaps I Was unlucky!

Cheers, good one!
