### ISSUE TITLE
[BUG] Line of Sight Issue in the "Hillsbrad Foothills" at [30.10|42.40]

### ISSUE THREAD

**Issue by blackcrowX** [chromiecraft/chromiecraft#478]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

"Hillsbrad Councilman" is not able to follow the Player into the main building/ city hall of the Subzone "Hillsbrad Fields" at [30.11|42.42] to reestablish Line of Sight.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

"Hillsbrad Councilman" should be able to follow the Player into the main building/ city hall and reestablish Line of Sight.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to the main building/ city hall at [30.11|42.42] in the "Hillsbrad Foothills".
2.  Leave the Building and procede to aggro a "Hillsbrad Councilman".
3.  Reenter the Building and hide from Line of Sight.
4.  Wait for it... wait for it...

##### EXTRA NOTES:

https://de.classic.wowhead.com/npc=2387/ratsherr-von-hillsbrad

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by blackcrowX** [comment]
![WoWScrnShot_042721_235958](https://user-images.githubusercontent.com/79520609/116319142-43e68780-a7b6-11eb-8eed-d198314661d5.jpg)
![WoWScrnShot_042821_000003](https://user-images.githubusercontent.com/79520609/116319148-45b04b00-a7b6-11eb-9314-6d5f3d5cb169.jpg)

**Comment by blackcrowX** [comment]
When proceding to the inner area of the building the mob actually restablishs Line of Sight and enters the building.
![WoWScrnShot_042821_001111](https://user-images.githubusercontent.com/79520609/116319302-9162f480-a7b6-11eb-9f95-667a286ca8cf.jpg)

**Comment by blackcrowX** [comment]
Whilst continuing trying around I realised there is also a problem with mobs in the entrance area in the Main Building, which then procede to exit the building when Line of Sight is lost.
![WoWScrnShot_042821_001432](https://user-images.githubusercontent.com/79520609/116319695-45647f80-a7b7-11eb-9870-2d2db31c9897.jpg)
![WoWScrnShot_042821_001441](https://user-images.githubusercontent.com/79520609/116319702-472e4300-a7b7-11eb-9c96-0739696e6526.jpg)
![WoWScrnShot_042821_001457](https://user-images.githubusercontent.com/79520609/116319707-48f80680-a7b7-11eb-94f8-b62e5b636512.jpg)
![WoWScrnShot_042821_001504](https://user-images.githubusercontent.com/79520609/116319710-4a293380-a7b7-11eb-8f93-06e34669f0e3.jpg)

**Comment by blackcrowX** [comment]
Not sure if it has similiarities to this post: https://github.com/azerothcore/azerothcore-wotlk/issues/4620

**Comment by Synful-Syn** [comment]
This looks fixed. AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/1ad79e19011ddbbe57ecd368bbc59b9cb27a3fcf 2022-05-11 11:41:00 +0000 (master branch)

https://user-images.githubusercontent.com/22718174/168499052-5bb91e9d-3bc9-4a2c-9d75-030d201e0c75.mp4
