### ISSUE TITLE
Logging out inside SFK as an Alliance player teleports you to the Sepulcher graveyard

### ISSUE THREAD

**Issue by apav** [chromiecraft/chromiecraft#479]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

![camp](https://user-images.githubusercontent.com/8137930/116323062-441d5d80-a78b-11eb-99c7-b3c9da0d3a14.png)

I was soloing SFK and at the end of the instance I used /camp to log back in outside the instance. I was teleported to the middle of the Sepulcher where the spirit healer is. This is a Horde town and I'm an Alliance player. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

See extra notes.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to SFK (not through dungeon finder), enter the instance and logout.

##### EXTRA NOTES:

I'm not quite sure how this works in WotLK. In Vanilla it teleported you directly outside the instance right in front of the portal, but someone in Discord mentioned it teleports you to the nearest hub. Even if it is supposed to teleport you to the nearest hub, is the intended behavior that it teleports you to the nearest hub no matter what faction it is, or that it teleports you to the nearest hub belonging to your faction? Apologies if this is invalid, but I've been doing research and can't find any answers for Wrath specifically. Just reporting in case it is a bug and someone can confirm it. If this is indeed a bug, I assume this applies to all instances and not just SFK, so that is why I selected Generic. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
No luck reproducing this on my test server unfortunately. I'm wondering if there's some sort of cross-faction issue causing problems - were you in a BG that changed your faction before this, or in a party before running SFK that had Horde players in it?

I do agree that porting you to a hostile graveyard is clearly not valid behaviour.

**Comment by apav** [comment]
> No luck reproducing this on my test server unfortunately. I'm wondering if there's some sort of cross-faction issue causing problems - were you in a BG that changed your faction before this, or in a party before running SFK that had Horde players in it?
> 
> I do agree that porting you to a hostile graveyard is clearly not valid behaviour.
> 
> Update - got it to work (or more accurately, not work) by dying inside SFK. That ported me to Sepulchre.
> 
> What I don't understand is that SFK must have been run hundreds of times by Allies, yet the AC and CC trackers don't mention this issue at all that I can find.

I wasn't in any sort of queue, I was just in a party with my other Alliance character manually entering the instance. Though at one point on a third account I made a new Undead character, ran it to SFK, and invited it to the party so I could summon one of my characters back after I hearthed to vendor stuff. However, that character was logged out and not in the party at the time I logged out from the instance and got sent to the Sepulcher.
