### ISSUE TITLE
[ Class - Hunter ] Tamed Infernal Hounds From Highlord Kruul Event Retain Immolation Aura

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#4790]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Hunters that tamed an Infernal Hound during the Highlord Kruul event are retaining the Immolation Aura
![pet](https://user-images.githubusercontent.com/62584589/211226132-940d7b3d-96aa-4ee9-9acc-cffa49f4e015.png)

### Expected Blizzlike Behaviour

Core Hounds do not have this aura.

### Source

https://wowgaming.altervista.org/aowow/?spell=20153#triggered-by
Triggered aura ingame

https://wowgaming.altervista.org/aowow/?spell=19483#used-by-npc
Stems from this aura

https://wowgaming.altervista.org/aowow/?npc=19207
Used by this creature (summoned by Kruul

https://www.wowhead.com/wotlk/npc=19207/infernal-hound#comments
wotlk wowhead info

### Steps to reproduce the problem

1. Make a level 50+ hunter
2. Tame a summoned Infernal Hound 
3. Take it near an enemy and watch passive aura damage 

### Extra Notes

I am unable to summon NPCs on the PTR, and don't run my own AC server to test. However IDs were snagged from today's raid, when I saw the pet doing 50% of the hunters dps with that aura alone lol. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
https://web.archive.org/web/20100323205408/http://www.wow-petopia.com/html/skills/skills.html

Another link for wotlk petopia pet skill list. Never listed as a spell used or learnable.

**Comment by Cooties-cc** [comment]
![image](https://user-images.githubusercontent.com/62584589/211227179-0a61b0dc-27f7-4c2f-9f12-44496a6d8ce8.png)
Had log from Fankriss fight.

**Comment by Samsequel** [comment]
![image](https://user-images.githubusercontent.com/20357406/211317954-6036fd9d-2e6d-4fb6-a3c5-195cc3345666.png)

Thank you for your report
