### ISSUE TITLE
Spinesever and The Night Blade should be contained in Strong Junkbox like in TBC

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#4793]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Items [Spinesever](https://wowgaming.altervista.org/aowow/?item=34622) and [The Night Blade](https://wowgaming.altervista.org/aowow/?item=31331) are not contained in [Strong Junkbox](https://wowgaming.altervista.org/aowow/?item=29569#contains). 

### Expected Blizzlike Behaviour

In TBC, both items can be acquired from the junkboxes. 

According to this [comment](https://www.wowhead.com/tbc/item=34622/spinesever#comments:id=187298) on Wowhead, it has been possible to acquire Spinesever from these boxes.

According to this Youtube [video](https://youtu.be/yN4iRdZpFSs?t=488), The Night Blade has been acquired from the said junkbox.

### Source

https://wowclassicdb.com/tbc/item/29569

### Steps to reproduce the problem

No necessary steps to reproduce the issue as the two mentioned items are not in the wotlk DB, but in TBC. 

### Extra Notes

This bug report was suggested by Gultask, based on my [suggestion](https://github.com/chromiecraft/chromiecraft/discussions/4792). 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Apathyxia** [comment]
I'm sorry, I think I fail to understand what that essentially means. Is it actually supposed to also be contained in WotLK (referring to the first comment from patch 3.0.1)? I'm also not sure how patch 9.2.7 plays a role here. 

Would you mind clarifying this a bit? :)

**Comment by Gultask** [comment]
Of course, sorry.

The difference is that those 2 items are not exclusive to TBC, but to every expansion up to their removal from the game. So this isn't a Progression issue per-se, but rather something that needs to be changed in the core database. But don't worry I was just rambling a bit up there while making the PR 😛.
Should be fixed soon.

**Comment by Apathyxia** [comment]
Thank you. That makes more sense. :D 

Looking forward to the fix. :)
