### ISSUE TITLE
Laughing Skull Legionnaire lacks scripted abilities

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#4798]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Laughing Skull Legionnaire has no scripted abilities : Uppercut and Sweeping strikes on the LIVE server.

### Expected Blizzlike Behaviour

Laughing Skull Legionnaire is probably one of the trickiest mobs in Blood Furnace because of Sweeping strikes + Upper Cut which should be usable.

### Source

https://www.icy-veins.com/tbc-classic/the-blood-furnace-dungeon-guide 

VIDEO - https://www.youtube.com/watch?v=dhSjk2-4zLA 

https://www.wowhead.com/tbc/npc=17626/laughing-skull-legionnaire#abilities;mode:normal

https://www.wowhead.com/wotlk/npc=17626/laughing-skull-legionnaire#abilities;mode:normal

### Steps to reproduce the problem

1. Fight NPC
2. Check if it uses UpperCut and Sweeping strikes in Normal and heroic
3. End

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by mikeleetoris** [comment]
Can confirm, played on TBC classic, these mobs are one of the reasons BF in heroic is so difficult for melee classes.

**Comment by Pyromanihack** [comment]
I tested on CC, and they actually cast Uppercut and Enrage
![WoWScrnShot_011823_173455](https://user-images.githubusercontent.com/82369562/213242440-2184383e-44a9-4a6b-a352-3a7393d51d75.jpg)
![WoWScrnShot_011823_173448](https://user-images.githubusercontent.com/82369562/213242453-0bf20137-4422-419a-8408-b21efc44b0e2.jpg)
but they don't cast [Sweeping Strikes](https://www.wowhead.com/wotlk/spell=18765/sweeping-strikes) and don't shout "Lok'tar Illidari"

This is the DB referred to Laughing Skull Legionnaire, where you can see that the first event (the one where he is expected to say "Lok'tar Illidari" is empty
![laughing DB](https://user-images.githubusercontent.com/82369562/213243381-1c041d9c-02f6-4913-bdae-fa94c6f6db9a.png)
