### ISSUE TITLE
Felguard Annihilator Lacking Spells in Blood Furnance

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#4799]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Felguard Annihilator does not Charge furthers players.

### Expected Blizzlike Behaviour

Felguard Annihilator should charge furthers players and drop aggro upon charge.

### Source

https://www.wowhead.com/wotlk/npc=17400/felguard-annihilator#comments;mode:normal

https://www.icy-veins.com/tbc-classic/the-blood-furnace-dungeon-guide

### Steps to reproduce the problem

1. Fight NPC in both heroic and normal to check if it uses intercept (second person required, obviously)
2. Check if he drops aggro upon charge (thats what really made this annoying and hard, that and the damage on Heroic)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
I don't know if it's only my problem, but I can't see any Felguard Annihilator spawn point in my DB
![felguard spawn](https://user-images.githubusercontent.com/82369562/213248128-c22090da-eb16-42d3-b41d-43a9815218f6.png)

**Comment by Nyeriah** [comment]
@Gultask do you have any info on this? They're not spawned, I don't have an active subscription anymore

**Comment by Gultask** [comment]
The only Felguards I know of in Blood Furnace are the Felguard Brutes (18894) just before Keli'dan the Breaker.
The Warlocks are also missing their Fel Power spells cast OOC on the Brutes

Other than that I can say that Blood Furnace is one of those custom dungeons in need of a complete spawn rework. It was only just looking better than the others so it flew off my radar.
