### ISSUE TITLE
NPC - Gubber Blump

### ISSUE THREAD

**Issue by Knewklear** [chromiecraft/chromiecraft#48]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### SMALL DESCRIPTION:
![WoWScrnShot_020421_223059](https://user-images.githubusercontent.com/58756521/107109959-f6d7c280-6811-11eb-87c3-eeca48222ae4.jpg)

Selecting the dialogue option doesn't do anything.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://classic.wowhead.com/quest=1141/the-family-and-the-fishing-pole#comments

What I assume is supposed to happen is that he's supposed to lend you a wishing pole should you not have one

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
Confirmed. The npc lacks the gossip.

**Comment by Hemingway1970** [comment]
He also does not teach fishing. The text option is there but does nothing.

**Comment by illfated** [comment]
> He also does not teach fishing. The text option is there but does nothing.

Well, that is what I thought the main issue ticket post was about, but looking back now, it appears that this was not asserted. The gossip should link to the fishing trainer menu. BTW, this is what TrinityCore is currently using:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10216/gubber-blump

```sql
SELECT * FROM `creature_template` WHERE `name`= "Gubber Blump";
```
```
entry  difficulty_entry_1  difficulty_entry_2  difficulty_entry_3  KillCredit1  KillCredit2  modelid1  modelid2  modelid3  modelid4  name          subname  IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family    type  type_flags  lootid  pickpocketloot  skinloot  PetSpellDataId  VehicleId  mingold  maxgold  AIName   MovementType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  spell_school_immune_mask  flags_extra  ScriptName  VerifiedBuild
-----  ------------------  ------------------  ------------------  -----------  -----------  --------  --------  --------  --------  ------------  -------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------  ----------  ------  --------------  --------  --------------  ---------  -------  -------  -------  ------------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  ------------------------  -----------  ----------  -------------
10216            0                   0                   0            0            0             9550      0         0         0     Gubber Blump  (NULL)   (NULL)              2562        15        15       0       55      131           1    1.14286       1       0          0            2000             2000             1              1           1       32768         2048             0       0       7           0       0               0         0               0          0        0        0  SmartAI             0            1               1             1              1               1                   1             0           0            1                     0                         0           66                      12340
```
Note `npcflag`= 131 <=> 128 (trainer) + 2 (questgiver) + 1 (gossip)

**Comment by illfated** [comment]
I can only assume that the gossip menu lacks its SAI commands to open anything, depending on conditions for the quest or lack of fishing skill.

**Comment by Stifler82** [comment]
Fixed
-
**Video Test:** [NPC - Gubber Blump](https://youtu.be/QuJr18__K4A)
