### ISSUE TITLE
[NPC] Lord Aliden Perenolde doesn't cast Renew

### ISSUE THREAD

**Issue by blackcrowX** [chromiecraft/chromiecraft#481]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ X ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ X ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

"Lord Aliden Perenolde" doesn't cast the Spell Renew. When attempting to cast Renew he casts an aditional Powerword: Shield.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

"Lord Aliden Perenolde" shold cast the Spell Renew in addition to Powerword: Shield.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to [39.00|15.10] in Alterac Mountains.
2.  Enter the building and attempt to combat "Lord Aliden Perenolde".
3.  Observe his buffing and casting.
4.  Weird kind of "Renew" going on as in none.

##### EXTRA NOTES:

https://de.classic.wowhead.com/npc=2423/lord-aliden-perenolde#english-comments

https://de.classic.wowhead.com/npc=2423/lord-aliden-perenolde#abilities

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Just tested this with the advantage of godmode, and found that while he does have a definite preference for PW:Shield, he will also cast Renew eventually:

![WoWScrnShot_042921_210153](https://user-images.githubusercontent.com/81782124/116544988-fd686880-a92e-11eb-9e5c-0ea0ccc34b1b.jpg)
![WoWScrnShot_042921_210332](https://user-images.githubusercontent.com/81782124/116545016-06f1d080-a92f-11eb-8727-5fd617a63dfc.jpg)

He seemed quite the handful, and i did wonder about filing a fault based on the PW:Shield spam alone, but some comments on WH Classic show he's always been like this:

"This loser is able to bubble, self-heal, and fight pretty much all at the same time.  As if we needed another reason to hate pallies.  S.O.B. healed back to full health twice on me, burned virtually no mana, and seemingly blinked across the floor at least twice. Lame, to say the least." (https://classic.wowhead.com/npc=2423/lord-aliden-perenolde#comments:id=2815669)

"Lol this fight is ridiculous, a renew that heals 250 a tick and a shield that absorbs 500+ dmg," (https://classic.wowhead.com/npc=2423/lord-aliden-perenolde#comments:id=2815682)
