### ISSUE TITLE
[Magtheridon] Blast nova issues

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#4814]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Blast nova is queued, instead of having flat cooldown. This means that he uses all other abilities that are back from cd before this one;
Mind exhaustion debuff duration is too low;

### Expected Blizzlike Behaviour

[Magtheridon ](https://wotlkdb.com/?npc=17257)should begin casting Blast Nova every 50 seconds.
Mind exhaustion debuff duration should be 3 minutes.

### Source

https://www.icy-veins.com/tbc-classic/magtheridons-lair-guide-strategy-abilities-loot

### Steps to reproduce the problem

Engage https://wotlkdb.com/?npc=17257
Kill all 5 https://wotlkdb.com/?npc=18829
Survive for 60 seconds

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
Blast Nova is queued

1. Quoting your own link https://www.icy-veins.com/tbc-classic/magtheridons-lair-guide-strategy-abilities-loot:
> Approximately every 50 seconds, [Magtheridon](https://tbc.wowhead.com/npc=17257) will begin to cast Blast Nova, periodically dealing massive damage to all nearby players.

2. Blast nova is never cast while quake is still ongoing. (ref. https://www.youtube.com/watch?v=PVL-m0CvfI0)

**Comment by Contrubius** [comment]
@balleny  So what I got out of the video is that Magtheridon always casts Quake, and right as it finishes, he does Blast Nova, and it's about a 2-3 second delay comparing to the Weakaura. Currently on CC it's the other way around.

**Comment by balleny** [comment]
practically, yes, there should always be a few seconds between both abilities.

more importantly, Blast Nova (and potentially the earthquake) should also be delayed if they would overlap with the last phase transition (Debris)
https://github.com/DeadlyBossMods/DBM-BCC/blob/8ffd08ab87ff88e49fe5007bafbb0d84a9c75fc7/DBM-Outlands/Magtheridon.lua#L67

**Comment by Contrubius** [comment]
> practically, yes, there should always be a few seconds between both abilities.
> 
> more importantly, Blast Nova (and potentially the earthquake) should also be delayed if they would overlap with the last phase transition (Debris) https://github.com/DeadlyBossMods/DBM-BCC/blob/8ffd08ab87ff88e49fe5007bafbb0d84a9c75fc7/DBM-Outlands/Magtheridon.lua#L67

I have confirmes this issue in a sense that Balst Nova and Quake spells should be reversed casts, as TBC Classic suggests. Timers seem to be fine in my tests. Can be more concrete after the spell cast order gets reversed.
