### ISSUE TITLE
Quest "A fishy peril" questgiver appears with a gray exclamation mark no matter the level.

### ISSUE THREAD

**Issue by Nimzowitscheh** [chromiecraft/chromiecraft#484]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So, that quest, which is fundamental for human progression through Elwynn Forest, appears with a gray exclamation mark. I was very confused because I've gone thought this leveling zone plenty of times so I talked to the quest giver and it turned out I could take the quest. The problem is I had to make a double trip because I didn't take the quest at first thinking it wasn't possible, so it's pretty annoying and can lead to wasting time. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The questgiver should have a yellow exclamation mark on top of his head.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Create a human
2. Go to Goldshire
3. Check the quest giver
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Just tried reproducing this, and the questgiver was working fine for me:

![WoWScrnShot_042921_222845](https://user-images.githubusercontent.com/81782124/116555099-20007e80-a93b-11eb-984b-1630dc47b679.jpg)

I tried at various character levels and didn't find anything unusual. There are no other reports for this that I can find either. If you've already accepted the quest and moved on, you presumably can't document this further. Perhaps the only thing to do is, next time you're levelling a human, keep an eye out and see if it reoccurs. If it does, take a screenshot, try to relog or /reloadui and see what that does, and feel free to reopen this ticket.
