### ISSUE TITLE
Ashyen is facing the wrong way. Ashien lacks scripted gossip. Ashien has incorrect text message upon buffing

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#4840]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Ashyen is facing the wrong way towards the mountain instead towars the village

Ashyen /says the wrong text attributable to entirely different NPC (he currently says upon buffing a player: THANK YOU FOR HELPING ME I KNOW MY WAY FROM HERE)

### Expected Blizzlike Behaviour

Ashyen should face the village

Ashyen does NOT SAY  THANK YOU FOR HELPING ME I KNOW MY WAY FROM HERE upon buffing.

### Source

https://wowpedia.fandom.com/wiki/Ashyen

https://www.wowhead.com/wotlk/npc=17900/ashyen#videos

### Steps to reproduce the problem

1. Teleport to Ashyen
2. Check his orientation
3. Check if he says the text upon buffing you
4. End
5. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Hey, thanks for the report, can confirm and it has been fixed.

**Comment by Paradigmxd** [comment]
@avarishd 

I just observed the event between the Elder Trents - it is absolutely not working. Ashyen still does not communicate and so Keleth is left speaking to himself alone...

**Comment by avarishd** [comment]
Not a part of this issue.
