### ISSUE TITLE
Flight paths to various locations missing

### ISSUE THREAD

**Issue by biggnomes** [chromiecraft/chromiecraft#4841]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

When selecting a flight master in Orgrimmar, Thunder Bluff, and Crossroads, available flight paths to Dustwallow Marsh, Stonetalon Mountains, and other locations are displayed via black lines but not selectable. When flying from Dustwallow Marsh, similarly, only some flight paths are selectable, though they are passed through.

### Expected Blizzlike Behaviour

All discovered flight paths should be selectable.

### Source

Flight paths were working earlier

### Steps to reproduce the problem

Interact with NPC ID 23612
Mouse over other available flight paths

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Windows 11 22621.1105

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello biggnomes, thanks for the report. Unfortunately I can't verify this issue. I went around learning flight paths, then tried to fly to Brackenwall Village and I had no issues at all. I'm not entirely sure what's causing this for you, but I do not believe it's core related.
![image](https://user-images.githubusercontent.com/68164076/226202955-bf247042-55ad-446b-873a-5a4660f376d5.png) 
![image](https://user-images.githubusercontent.com/68164076/226203073-dbcdd60c-b5e6-413d-9062-5da30409aa35.png)
![image](https://user-images.githubusercontent.com/68164076/226203086-4b1ca936-4e2d-42e0-bd55-54bee86f6b2e.png)


Side note NPC 23612 takes me to a turtle in Tanaris
![image](https://user-images.githubusercontent.com/68164076/226203156-b15ccedb-6b3f-4577-8be6-20f176816612.png)
