### ISSUE TITLE
Karazhan: Moroes - Vanish ends too soon

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#4864]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Moroes vanish sometimes ends almost immediately. He doesn't do the emote or start the sound voice.
https://youtu.be/kcHT_7cOTgE?t=4207

### Expected Blizzlike Behaviour

Moroes should vanish, then yell: "Now, where was I? Oh, yes..." (with a proper sound voice over),  Then cast Garrote on someone and then reappear later, the whole process takes a few seconds, but not immediately.

### Source

TBC Classic
https://youtu.be/Zj_6qPNCOhI?t=49

### Steps to reproduce the problem

1. Enter Karazhan
2. Go to the Banquet Hall. From the entrance go up the stairs and then turn left into Moroes' room.
3. Fight Moroes and time how long it stays vanished.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
could it be that his vanish gets broken by some aoe (consec from pally / flamestrike etc?)

**Comment by heyitsbench** [comment]
> could it be that his vanish gets broken by some aoe

There's nothing in the combat log for it, first attack that hits Moroes after the vanish fades is a ranged shot from a hunter, followed by a bite.

**Comment by elthehablo** [comment]
The problem with the emote is that I think it might not be in the DB. Lemme investigate

**Comment by elthehablo** [comment]
An interesting bug I found is that he casts Garrote on himself under certain conditions

**Comment by elthehablo** [comment]
Nvm it was in the db, just not used in the script

**Comment by elthehablo** [comment]
But... all that being said, I don't see a major difference other than the weird bug to classic's implementation and ours. It doesn't seem to end too quickly under normal circumstances. What balleny said to me is likely. Probably aoe like consec what gets him out. I can make a hack-fix to make him immune for the time being, but would have to confirm with the sniffs what is done on Blizz's end
