### ISSUE TITLE
[Progression] Meta Gem /Primal Might transmutes have their own cooldown

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#4877]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour
Transmute Primal Might, Transmute Earthstorm Diamon and Transmute Skyfire Diamond have their own 20 hour cooldown

### Expected Blizzlike Behaviour

They share the 20 hour cooldown with all other transmutes

### Source

https://wowpedia.fandom.com/wiki/Transmute?oldid=1465246
![image](https://user-images.githubusercontent.com/50233983/214356821-de27e24a-e055-418c-8ed9-9d8b0235908d.png)

### Steps to reproduce the problem

.learn 51304
.setskill 171 450

.learn 28566
.learn 28567
.learn 29688
.learn 32765

.add 22451
.add 9149

Craft the transmute with mats
Relog
Check cooldown of other transmutes

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
Reading https://github.com/azerothcore/azerothcore-wotlk/issues/13710 I can say that the cooldown was removed in 3.0.8 along with that of other professions

**Comment by Tereneckla** [comment]
> Reading [azerothcore/azerothcore-wotlk#13710](https://github.com/azerothcore/azerothcore-wotlk/issues/13710) I can say that the cooldown was removed in 3.0.8 along with that of other professions

And there is a cooldown on them because they were added on Chromiecraft as a progression related change
