### ISSUE TITLE
World PVP Tower/Flag Counter Not Visible - Hellfire Penn, Terokkar, Eastern PL, ETC - 

### ISSUE THREAD

**Issue by shewlace** [chromiecraft/chromiecraft#4879]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

About during the first week of Phase 61-64, the world PVP information (The Tower Count at the center of the screen, and the Flag/Tower Capture Progress) stopped displaying. 
I didn't report the issue at the time because doing these objective were not my focus and figured the issue would be sorted out.  

This issue is only occurring with one of my accounts.  If I sign into a different account (using all the same addons and client) account number two does not have this issue. 

To confirm that it's not a PC/Cache folder issue, I redownloaded the wotlk client from the Chromie website and launched the client on another PC that has never ran a WoW client before. So this environment has zero addons and everything is default in terms of settings. I signed into my main account and still am unable to see any World PVP information in any of the zones that should display this information. 

### Expected Blizzlike Behaviour

The Tower capture number should be displayed at the top/center of the screen and the Tower/Flag capture should be displaying under the map. 

### Source

na

### Steps to reproduce the problem

1. Enter Zone with world PVP objectives (Hellfire Peninsula)
2. PVP Flag eneabled
3. Unable to see the current Tower Capture Totals
4. Unable to see Tower Capture Progress when sitting in opposing factions tower
![2023-01-24 17_25_03-World of Warcraft](https://user-images.githubusercontent.com/111463928/214445383-e676da72-8694-494a-ba68-2aae2f190be4.png)
  

### Extra Notes

The center Tower information should display regardless of PVP flag statues.  When Terokkar towers are all captured, there should be a timer that counts down when they can be captured again.  This timer does not display either. 
![2023-01-24 17_43_37-World of Warcraft](https://user-images.githubusercontent.com/111463928/214445867-c60997dd-64d4-41f1-8bf0-eb6362d67c3b.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Win 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by slicplaya** [comment]
It's bugged here,. You have to /pvp toggle flag off and back on, even though you already have it enabled. It's stupid annoying. Easier solution: Make the server PvP. Done. Easy.

**Comment by shewlace** [comment]
> It's bugged here,. You have to /pvp toggle flag off and back on, even though you already have it enabled. It's stupid annoying. Easier solution: Make the server PvP. Done. Easy.

That definitely doesn't work as I've tried it and also reloaded and logged after. The Tower Status (top center display) should show where or not you're PVP flagged.

**Comment by Stump876** [comment]
This does not seem to be an issue right now.
![image](https://github.com/chromiecraft/chromiecraft/assets/68164076/c4381d00-bbf2-4ca4-abc9-9481f39ac3de)
![image](https://github.com/chromiecraft/chromiecraft/assets/68164076/293cbc52-8db7-4a8d-b6cd-8e6763b7eed8)
