### ISSUE TITLE
Lament of the highborn (book)

### ISSUE THREAD

**Issue by Stump876** [chromiecraft/chromiecraft#488]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Seems like the book isn't coded properly.
![Capture1](https://user-images.githubusercontent.com/68164076/116653686-905bcf80-a93c-11eb-8cd5-738891833a62.PNG)
![Capture2](https://user-images.githubusercontent.com/68164076/116653697-93ef5680-a93c-11eb-86b6-b9704fa1e2e4.PNG)
I didn't screenshot page 3 but you get the idea

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should look like this

![Capture](https://user-images.githubusercontent.com/68164076/116653282-bb91ef00-a93b-11eb-9924-1113c34bf498.PNG)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .additem 30632 
2. Or .quest add 9180 (Journey to Undercity) talk to Sylvanas and complete the quest
3. Talk to Ambassador Sunsorrow to the left of her and he will give you the book
4.

##### EXTRA NOTES:

[https://www.wowhead.com/item=30632/lament-of-the-highborne#comments](url)
[https://www.wowhead.com/quest=9180/journey-to-undercity](url)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Couldn't reproduce this on my test server, the book looks fine:
![WoWScrnShot_050121_003133](https://user-images.githubusercontent.com/81782124/116714561-0e8ba500-aa15-11eb-83bb-b4f986e10c27.jpg)
![WoWScrnShot_050121_003136](https://user-images.githubusercontent.com/81782124/116714563-0fbcd200-aa15-11eb-9400-1881590936a4.jpg)
![WoWScrnShot_050121_003138](https://user-images.githubusercontent.com/81782124/116714566-10edff00-aa15-11eb-95e8-ab28089eb970.jpg)

Maybe try temporarily disabling client-side addons to see if one of them is doing this. Feel free to re-open this if you continue having problems even with addons all disabled.

**Comment by Azcobu** [comment]
See https://github.com/chromiecraft/chromiecraft/issues/302 and https://github.com/azerothcore/azerothcore-wotlk/issues/5352 - it seems if the book is created in your inventory by a GM command, it works fine, but if it's given to you by an NPC, it can get messed up. However, looks like a fix (https://github.com/azerothcore/azerothcore-wotlk/pull/5364) has been committed.
