### ISSUE TITLE
Karazhan: Trash - Arcane Anomaly doesn't cast Mana Shield

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#4880]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Arcane Anomaly gets killed almost instantly as they have low health and high mana.
https://youtu.be/px3WCMXzK_Q?t=5308
https://youtu.be/kcHT_7cOTgE?t=8499

### Expected Blizzlike Behaviour

Arcane Anomaly casts Mana Shield when aggroed. When successfully casted only dies when running out of mana or if killed before it's casted.

### Source

_"While the mana shield cannot be dispelled, Anomalies do not start with one. It is activated after aggroing the group."_
_**Mana Shield:** 100% of all damage absorbed, mana drained equal to damage absorbed. Cannot be dispelled._
https://wowpedia.fandom.com/wiki/Arcane_Anomaly

### Steps to reproduce the problem

1. Enter Karazhan backdoor
2. Go upstairs to Curator
3. Pull a trash group inside Curator's Room where Arcane Anomalies reside.
4. Check if they cast Mana Shield.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by damnablebear** [comment]
This didn't seem to be working the other day for me (worked as described in this issue detail) but today upon testing it, I'm seeing it work correctly. Please see this video I took from the CC PTR showing partial HP reduction and full HP reduction attacks, bringing the Arcane Anomaly's HP to a partial amount (or 1hp if it would've been killed), and subsequently popping Mana Shield, as it should.

https://www.youtube.com/watch?v=LyloC8xZplg

**Comment by Sneften** [comment]
Hi! It was fixed here: https://github.com/azerothcore/azerothcore-wotlk/pull/16921
