### ISSUE TITLE
Item - Weapon Proficiency

### ISSUE THREAD

**Issue by Knewklear** [chromiecraft/chromiecraft#49]
![WoWScrnShot_020321_175004](https://user-images.githubusercontent.com/58756521/107110052-c93f4900-6812-11eb-9cd0-f687a675d7ca.jpg)

##### SMALL DESCRIPTION:

The item is shown to be wieldable but when right clicking it, it tells me "You do not have the required proficiency to wield that item."

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The word sword is supposed to be shown in red.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
@Knewklear What is your actual skill in sword proficiency?

**Comment by eTzmNcbkrng** [comment]
Confirmed.
Picked up a random gray Dagger on a Tauren Warrior, was surprised to see it wasn't red so I tried to equip it and got the message "You do not have the required proficiency to wield that item."
I checked the skills page and do not have Daggers trained.

**Comment by Hacaw** [comment]
I tested with ChromieClient and what should be red is the type. 
For example in your screen what must be red should be the **Sword**.

![image](https://user-images.githubusercontent.com/6963500/107119245-13661000-688f-11eb-878a-d37855a85968.png)

To me it works, couldn't this be an issue on your client ? I see some new models.

**Comment by Knewklear** [comment]
> @Knewklear What is your actual skill in sword proficiency?

I didn't have swords learned but it showed that I could wield it. When I tried, it said I didn't have the required proficiency. The sword was white and not red as it should have been when you don't have the skill learned for handling them.

**Comment by Knewklear** [comment]
> I tested with ChromieClient and what should be red is the type.
> For example in your screen what must be red should be the **Sword**.
> In my screenshot is the **Dagger**
> ![image](https://user-images.githubusercontent.com/6963500/107119245-13661000-688f-11eb-878a-d37855a85968.png)
> 
> To me it works, couldn't this be an issue on your client ? I see some new models.

This isn't model related.

**Comment by 55Honey** [comment]
Can`t replicate. Neither on Chromiecraft, nor on my recent local Master. I suspect your client to be causing this @Knewklear .

**Comment by 55Honey** [comment]
Very detailled, we will try to reproduce again. Thanks!

**Comment by Stifler82** [comment]
Video [Weapon Proficiency](https://youtu.be/q0X5T6lmJLE)

Guys, just **delete the Cache folder before** to get login in the Game

**Comment by eTzmNcbkrng** [comment]
> 
> 
> Video [Weapon Proficiency](https://youtu.be/q0X5T6lmJLE)
> 
> Guys, just **delete the Cache folder before** to get login in the Game

You misunderstand the problem, deleting the Cache is what causes the problem, the game is incorrectly providing/displaying proficiency requirements for items if you have a fresh Cache.
This issue explicitly affects new players.

**Comment by Stifler82** [comment]
> > Video [Weapon Proficiency](https://youtu.be/q0X5T6lmJLE)
> > Guys, just **delete the Cache folder before** to get login in the Game
> 
> You misunderstand the problem, deleting the Cache is what causes the problem, the game is incorrectly providing/displaying proficiency requirements for items **if you have a fresh Cache**.
> This issue explicitly affects new players.

No, I understand the problem perfectly, the one who misunderstood is you.
**I always use a Fresh Cache**, because **I delete it every time** I enter the game.
The "Cache" folder is a "Sniffing" folder, in practice it collects the "Data" of the actions that you do in the game.

The "Cache" folder that you are currently using is a "Compromised" folder with bad data and reflects that bad data within your game giving you "Blast" information.

**Comment by Stifler82** [comment]
Worst case scenario, you have a WoW 3.3.5a Client with compromised/corrupted MPQs files and probably the Cache folder "Sniffs" incorrect information from your Game Client, so I assume you can fix the problem by "Reinstalling" the game client, possibly from a "Clean" Download.

**Comment by eTzmNcbkrng** [comment]
> 
> 
> @eTzmNcbkrng
> Worst case scenario, you have a WoW 3.3.5a Client with compromised/corrupted MPQs files and probably the Cache folder "Sniffs" incorrect information from your Game Client, so I assume you can fix the problem by "Reinstalling" the game client, possibly from a "Clean" Download.

Which is exactly why I provided MD5 hashes for all my MPQ files, don't suppose you can do the same so I can see which files are different and target them.

@Knewklear, who originally reported this problem, is playing on a client downloaded from your website.

**Comment by Stifler82** [comment]
@eTzmNcbkrng
Aaaah! now I understand what is your problem, before I didn't notice it, I saw your documentation on MPQs, but I didn't look carefully, now I noticed something, you have the enGB Client!
the enGB Client is the most BUGGED client ever in the whole Wow story, you have to download the enUS Client, that works perfect!

**Comment by eTzmNcbkrng** [comment]
> 
> 
> @eTzmNcbkrng
> Aaaah! now I understand what is your problem, before I didn't notice it, I saw your documentation on MPQs, but I didn't look carefully, now I noticed something, you have the enGB Client!
> the enGB Client is the most BUGGED client ever in the whole Wow story, you have to download the enUS Client, that works perfect!

Excellent, thank you. I am actually currently trying to torrent the client from the ChromieCraft website but it's stalled.
Is there anything special about this client or can I get any enUS version (assuming it's unmodified)?

**Comment by Stifler82** [comment]
> > @eTzmNcbkrng
> > Aaaah! now I understand what is your problem, before I didn't notice it, I saw your documentation on MPQs, but I didn't look carefully, now I noticed something, you have the enGB Client!
> > the enGB Client is the most BUGGED client ever in the whole Wow story, you have to download the enUS Client, that works perfect!
> 
> Excellent, thank you. I am actually currently trying to torrent the client from the ChromieCraft website but it's stalled.
> Is there anything special about this client or can I get any enUS version (assuming it's unmodified)?
@eTzmNcbkrng
What do you mean with "(assuming it's unmodified)"?

**Comment by eTzmNcbkrng** [comment]
Is there anything special about the ChromieCraft client, or will any unmodified enUS client work fine?

**Comment by Stifler82** [comment]
> Is there anything special about the ChromieCraft client, or will any unmodified enUS client work fine?
> I'm currently downloading the Warmane client (not the HD textures version).

@eTzmNcbkrng
every Client enUS works fine. (at least they should works fine)..

**Comment by FrancescoBorzi** [comment]
> Excellent, thank you. I am actually currently trying to torrent the client from the ChromieCraft website but it's stalled.
> Is there anything special about this client or can I get any enUS version (assuming it's unmodified)?

The ChromieCraft client has been provided by @Nolt (please contact him if you have issues with the download so he can assist you). Meanwhile, you can use the [wowgaming client](https://github.com/wowgaming/client-data/releases/download/v0/clean-game-client.torrent) which is also a clean client (with that you have to manually change the realmlist though).

> Is there anything special about the ChromieCraft client, or will any unmodified enUS client work fine?

There is nothing special added there, just the realmlist. @Nolt can confirm it.

> deleting the Cache is what causes the problem

deleting the Cache cannot be the cause of a problem, actually it's typically the opposite

**Comment by eTzmNcbkrng** [comment]
I have downloaded an enUS client I found online and I am now **unable** to reproduce this bug.
Thanks team, sorry for drama.

**Comment by FrancescoBorzi** [comment]
@eTzmNcbkrng no problem and thanks for letting us know!
