### ISSUE TITLE
[Mining] Wrong display of "Small Thorium Vein" Skill

### ISSUE THREAD

**Issue by blackcrowX** [chromiecraft/chromiecraft#490]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ X ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ X ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When viewing a Small Thorium Vein the game displays a needed skill of 235. When trying to mine the actual needed skill is 230 and is displayed also as 230.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

 
When viewing a Small Thorium Vein it should also display the actual 230 skill needed to mine the vein.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to any Small Thorium Vein.
2.  View the needed skill.
3.  Procede to try to mine the vein (preferably with less than 235 mining skill).

##### EXTRA NOTES:

https://wotlk-twinhead.twinstar.cz/?object=324
![WoWScrnShot_043021_131550](https://user-images.githubusercontent.com/79520609/116689341-444e7080-a9b8-11eb-979f-d210e00e7416.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I can't duplicate this. Everything seems to be working properly. Following the steps, with mining 220 the nodes report "requires mining 230" as pictured below. At mining 230 I can mine the node. Is there a screenshot of the error?
![image](https://user-images.githubusercontent.com/68164076/117559236-6ee39d80-b038-11eb-81d5-eaad6504622d.png)

![image](https://user-images.githubusercontent.com/68164076/117559209-3b087800-b038-11eb-9154-dc26d353eabd.png)

**Comment by Helias** [comment]
It could be related to some custom patch or addon probably, I am clsoing this
