### ISSUE TITLE
[Progression 65-69] Alchemist Specializations

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#4901]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Alchemy has 3 different specializations.
After learning one by finishing the respective quest, it can be unlearned and another one can be learned for 150g without finishing the respective quest.

2 of the 3 quests require loot from Botanica and Black Morass.
The third one does not require loot from any dungeon.

All those quests become available at 68, which is also the level required to enter both mentioned dungeons.
But, Those dungeons will not be accessible because of the progression.

Upon reaching 68 and the required 325 skill in Alchemy, you usually chose one specialization. Often, you do either Elixir or Potion quest. Even if you intend to go for the transmutation specialization, people completed the Elixir or Potion Quests and then paid the 150g premium to switch. Simply for economic reasons.

This will not be feasible here as the quests arent completeable. 

### Expected Blizzlike Behaviour

Technically, every Alchemist can do the Transmute quest and then switch for additional 150g premium. Given the material requirements of the transmutation quest (4 Primal Mights) compared to very few potions / elixirs for the other quests, some may delay it for a full bracket.

But, as this is a Progression induced problem, it would be great to know **AHEAD** of the next bracket, if some kind of progression modification, similar to the Paladin Seal issue, will be made. Technically, only the related dungeon drop items would need to become available by other means (e.g. dropping open world, dropping in any released dungeon, being mailed to you automatically or being available via exchange.

### Source

https://wowgaming.altervista.org/aowow/?quests=5.-181

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Samsequel** [comment]
This is sadly no longer relevant. I think this would have been better suited for a suggestion next time.
