### ISSUE TITLE
[BUG] Makrura Clacker AI in "Durotar" while kiting

### ISSUE THREAD

**Issue by blackcrowX** [chromiecraft/chromiecraft#491]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ X ] Horde

##### CONTENT PHASE:

- [ X ] Generic
- [ X ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When kiting the NPC "Makrura Clacker" at some point it stops chasing the player and starts turning left and right on the spot. As if the NPC is stuck on the spot. This happens only in the water.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When kiting the NPC "Makrura Clacker" it should chase the player without getting stuck on the spot.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to the Echo Isles in Durotar.
2.  Enter the water.
3.  Procede to aggro the NPC "Makrura Clacker".
4.  Kite the NPC "Makrura Clacker"
5.  Observe.

##### EXTRA NOTES:

https://classic.wowhead.com/npc=3103/makrura-clacker

![WoWScrnShot_043021_164304](https://user-images.githubusercontent.com/79520609/116712564-43c3d300-a9d4-11eb-97c5-bb7de3e25681.jpg)

![WoWScrnShot_043021_164334](https://user-images.githubusercontent.com/79520609/116712571-458d9680-a9d4-11eb-8bc5-bfa68af38e30.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by blackcrowX** [comment]
I pinpointed what causes the bug. After casting the Hunter Spell "Serpent Sting" and hitting the NPC with an "Auto-Shoot" triggers the i
![Uploading WoWScrnShot_043021_165239.jpg…]()
mmobilization of the NPC.

**Comment by Azcobu** [comment]
Thanks for the report and the screenshots. Unfortunately, this mob has been bugged for a while now, and we therefore have multiple reports for it already.

https://github.com/chromiecraft/chromiecraft/issues/435
https://github.com/chromiecraft/chromiecraft/issues/334
https://github.com/chromiecraft/chromiecraft/issues/300
https://github.com/azerothcore/azerothcore-wotlk/issues/5341

Closing as a duplicate.
