### ISSUE TITLE
Pet skills such as mend pet, Bestial Wrath aren't retaining duration while pet is away.

### ISSUE THREAD

**Issue by slicplaya** [chromiecraft/chromiecraft#4911]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

When casting Mend Pet or Bestial Wrath, and immediately mounting or dismissing the pet with duration still remaining of said skills, upon dismounting or recalling the pet, those 2 skills, and many others, are wiped or not snapshot/logged(however it's set) While the pet is "away."

### Expected Blizzlike Behaviour

If mend pet is cast (15 second duration), and I the hunter, mount up in 1.5 seconds, then dismount, and pet returns, There should be 12-13 seconds duration of mend pet on the pet.

### Source

https://www.wowhead.com/wotlk/spell=136/mend-pet#comments

### Steps to reproduce the problem

1. Gain any hunter pet
2. Use Mend Pet skill, or Bestial Wrath
3. mount up while duration persists.
4. Dismount to see either duration instantly gone.

### Extra Notes

This might also have some relationship with the same reason pets are not coming back with full hp when dismissed or recalled from an "away" state.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Scrublettt** [comment]
Confirmed.

**Comment by Samsequel** [comment]
Hey,

On WOTLK PTR, the closest thing we have, if you mend pet + dismiss, duration still counts down.
