### ISSUE TITLE
Natures Grasp ICD

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#4919]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

https://wowgaming.altervista.org/aowow/?spell=16689 currently doesnt have an internal cooldown
This is a major issue as this means players can DR themselves making this ability useless

### Expected Blizzlike Behaviour

Natures Grasp should have an internal cooldown  so players cannot DR themselves and in essence break their own root

### Source

https://www.wowhead.com/wotlk/spell=16689/natures-grasp#comments

### Steps to reproduce the problem

Create a druid
duel a player
cast natures grasp
No ICD between charges

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Santaria94** [comment]
Can not reproduce. The ICD should be 1 second, and on PTR it seems to work that way.
This was fixed a year ago https://github.com/azerothcore/azerothcore-wotlk/issues/9475

**Comment by Never6** [comment]
shouldnt the internal cooldown been 1.5seconds not 1second because some classes do have a 1 second gcd and thus can still DR it

**Comment by Santaria94** [comment]
>shouldnt the internal cooldown been 1.5seconds not 1second because some classes do have a 1 second gcd and thus can still DR it

If I'm not mistaken, this information was extracted from the game files. Relatively recently there was a similar report on TrinityCore, they used this DB as a source https://wow.tools/dbc/?dbc=spellauraoptions&build=3.4.0.46368#page=1&colFilter%5B9%5D=16689
![1346](https://user-images.githubusercontent.com/32459796/216540989-9de5fa82-8464-4ced-a4d5-fc4da10f48eb.png)
