### ISSUE TITLE
Zangarmarsh Ango'rosh Stronghold fall of non-death

### ISSUE THREAD

**Issue by Anwyyn** [chromiecraft/chromiecraft#4925]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

I was farming ores scaping from mobs in Ango'rosh Stronghold when i fall down from the edge at [20.5,9.4] aprox.
1st i was n't rlly close to the edge when i fell down
2nd I was on my paladin, so i bubbled. After that i kept falling.
3rd there was a point when i was pushing buttoms and a message at the top appeared saying"you are dead" but i wasnt a ghost in a graveyard, i was even able to move!
4th after that i logged out, quit the game and nothing wokred, kept in the same spot
5th trying to look for anything in the web i suddenly spawned at the graveyard alive

![Screenshot 2023-02-01 232156](https://user-images.githubusercontent.com/124227595/216225554-807e80e7-7ebf-40bf-a684-79597c0856db.png)
![Screenshot 2023-02-01 231654](https://user-images.githubusercontent.com/124227595/216225560-b6883758-9d64-4390-bf10-7079a3b5a671.png)
![Screenshot 2023-02-01 231712](https://user-images.githubusercontent.com/124227595/216225563-907d4c1c-9c3d-4e9c-85fd-743d88cd55e1.png)

### Expected Blizzlike Behaviour

Think that once you fall down from the edge... you should be dead... not in a limbo...

### Source

Dont know what to wirte here...

### Steps to reproduce the problem

1. In Ango'rosh Stronghold at Zangarmarsh go to [20.5,9.4] aprox.
2. fall from the adge
3. Use divine shield (yep, be a paladin, didnt try on other classes yet)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Anwyyn. Thanks for the report. I was able to do this same thing in Hellfire Penisula. The paladin bubble is what protected you from fall death. After a few minutes it will revive and spawn you at the closest graveyard. So it looks like this is working properly. If you have a source for different Blizzlike behavior I'd like to take a look at it and pass it on to the Devs. But for now this will most likely stay as is until we can prove it's not Blizzlike.
