### ISSUE TITLE
Mage "Frostbite" talent completely breaks humanoids "run away when low hp" mechanic.

### ISSUE THREAD

**Issue by Nimzowitscheh** [chromiecraft/chromiecraft#493]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I still don't know how to make it happen especifically, but it happens way too oftenly to be left ignored. 
Whenever a humanoid is hitting you, when you have Frost Armor up as a mage, and you have the Frostbite talent, if that humanoid gets low enough to activate the "run away to seek for help" mechanic that most humanoids have, AND AT THE SAME TIME it gets low enough to proc that mechanic, the humanoid procs your Frostbite by hitting you, then the humanoid literally teleports to it's nearest ally while being root in place with frostbite. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

OF course the humanoid should just stay in place because it can't run while being root in place.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a frostmage to lvl 12 so you can get 3 points on frostbite to get the 15% proc chance
2. Engage humanoids 
3. Wait till it happens
4. It might sound too situational but it happens way too often 

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Fortunately, this has already been reported (https://github.com/azerothcore/azerothcore-wotlk/issues/5538), and a fix is on the way.
