### ISSUE TITLE
Object can't be seen because it is clipping through terrain

### ISSUE THREAD

**Issue by Peti321** [chromiecraft/chromiecraft#4933]
I was collecting "Blood of Heroes" and I've checked for coordinates. I came across one that was indeed there but it can't be seen. Only the cursor shows it.
![WoWScrnShot_020523_101239](https://user-images.githubusercontent.com/115947849/216810924-7629443b-9dcf-43d6-912d-26055ae2c7f6.jpg)

**Comment by heyitsbench** [comment]
[This issue has been reported before](https://github.com/azerothcore/azerothcore-wotlk/issues/8507), but interestingly the CC reports have all been closed as completed, despite not being fixed.

**Comment by Nyeriah** [comment]
I don't remember what was the deal with this but either 1) positions need to be resniffed 2) we need to port trinitycore changes that handle gameobject position/rotation spawning
