### ISSUE TITLE
The Glowing Shard

### ISSUE THREAD

**Issue by Jessica-Antonia** [chromiecraft/chromiecraft#4937]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

The Glowing Shard quest completed and gave the expected experience and rewards. However, the shard did not delete from my inventory. Also, the quest will not complete in my quest log. I closed the client and deleted my cache. The issue persisted.

Database ID is : 6981 (according to the link below)

https://www.wowhead.com/classic/quest=6981/the-glowing-shard#comments

I attempted to see if the quest was flagged as completed without success. I ran both commands, but neither gave output.

/run print(C_QuestLog.IsQuestFlaggedCompleted(6981))

/script print(C_QuestLog.IsQuestFlaggedCompleted(6981))

### Expected Blizzlike Behaviour

The quest should remove the shard from my bag and the quest from my log. 

### Source

![WoWScrnShot_020523_232110](https://user-images.githubusercontent.com/106360885/216884414-1ef85323-b29a-4021-9d7e-f86e0bc6659e.jpg)

### Steps to reproduce the problem

1. Take shared quest: The Glowing Shard.
2. Travel to Rachet and speak with Sputtervalve/
3. Travel to the cave on top of the Wailing Caverns entrance.
4. Turn in the quest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

I am running several mods from Felbite. 

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> I attempted to see if the quest was flagged as completed without success. I ran both commands, but neither gave output.

The reason for this is because those commands are meant for the Classic client, which has different functions from the 3.3.5a client. For the 3.3.5a client, you'd have to do the following:
```
/run QueryQuestsCompleted()
/run local q = [QUESTID]; print(q .. " completed: " .. (GetQuestsCompleted()[q] and "yes" or "no"))
```

**Comment by heyitsbench** [comment]
As for the issue itself, this shard is involved in a bit of a chain, and the shard has to persist throughout the entire chain. Are you sure you're completing this chain to the end? If so, please provide a source with regards to the expected behavior.

**Comment by Jessica-Antonia** [comment]
Yep, there was another thing to do to finish the quest. So sorry!
