### ISSUE TITLE
Broken Quest or really low drop rate

### ISSUE THREAD

**Issue by Peti321** [chromiecraft/chromiecraft#4939]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

30-39

### Current Behaviour

The quest is in Dustwallow Marsh.
Its called "Marsh Frog Legs"
You have to kill critters to get legs. However: Quest item doesnt drop
(i killed a bunch but i think it should drop often)

### Expected Blizzlike Behaviour

Quest item should drop

### Source

Game

### Steps to reproduce the problem

1.Take quest
2.Start killing Frogs
3.???
4.Profit

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, thanks for the report.
ive tested this on live and the ptr, and its 100% drop rate for me from [Giant Marsh Frog](https://www.wowhead.com/wotlk/npc=23979/giant-marsh-frog)
could be a visual bug on your end

https://user-images.githubusercontent.com/11332559/217289869-6d08e702-2df1-4e13-9082-4c7b9d3549e2.mp4


https://user-images.githubusercontent.com/11332559/217289875-29149f08-e523-41c7-bbb9-68d5ea0728ac.mp4

**Comment by FakestLab** [comment]
Hi,
I came here just to check, but it seems it may be bugged in some cases.

For some reason when I killed a frog with simple auto-attack, the items did not drop once, but when I used a skill or auto-attack directly after a skill (charge) the drop was 100%. ([video link](https://drive.google.com/file/d/1EiuChx1hy-VkzBfu98cYq_2S8QNKS5ik/view?usp=share_link)).

Maybe this way it may be easier to reproduce.
I am using enUS version.

**Comment by BeefSteaker** [comment]
> Hi,
> I came here just to check, but it seems it may be bugged in some cases.
> 
> For some reason when I killed a frog with simple auto-attack, the items did not drop once, but when I used a skill or auto-attack directly after a skill (charge) the drop was 100%. ([video link](https://drive.google.com/file/d/1EiuChx1hy-VkzBfu98cYq_2S8QNKS5ik/view?usp=share_link)).
> 
> Maybe this way it may be easier to reproduce.
> I am using enUS version.

I don't have access to that video, if it's small enough you can probably drag it into GitHub. 

I also use the enUS version and my videos above are autoattacks.
If you could put the video somewhere public I'll try to replicate

**Comment by FakestLab** [comment]
I've changed the google drive settings and video should be public now.
If not I'll upload it to youtube or something, sadly the video is 30mb and too big for github I think.

**Comment by Paradigmxd** [comment]
I can confirm - this is broken - using any physical auto attack will result it NO LOOT ,please RE-OPEN

@BeefSteaker

**Comment by Kosiak** [comment]
Can confirm broken on live as of 18/05/23 (8224a90a99cc 2023-05-10). Tried on Orc Hunter. All hunter attacks do autoattack first and using any spells wont help. So it wont drop for me no matter what i'm tried. Even immolation and explosive traps on frogs wont work if frog triggers it. What worked is aggro some mob close to frog and then place explosive trap and let mob trigger it and frog will be killed and then u can loot it. Very very very annoying.
