### ISSUE TITLE
[Hunter][Spell] Explosive shot should stack with different ranks

### ISSUE THREAD

**Issue by bonfax4** [chromiecraft/chromiecraft#4942]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Downranked explosive shots are overriding the previously casted explosive.

### Expected Blizzlike Behaviour

Different ranks should stack.

### Source

www.github.com/JamminL/wotlk-classic-bugs/issues/514

https://www.wowhead.com/wotlk/spell=56344/lock-and-load#comments:id=993102

Patch 3.3.2

`Just tested this with recount. When LnL procs you can cast explosive shot(rank 4) explosive shot(rank 3) explosive shot(rank 4) and it will get all 9 ticks and it does more damage than an explosive shot(rank 4) spam. Very handy when you need that big burst of damage and every second counts.`

### Steps to reproduce the problem

Proc Lock n Load and try to cast different ranks right after each other. ( 2>1>2 )

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BugSquisher9000** [comment]
Im bumping this thread with more clear how it should be. https://www.youtube.com/watch?v=oapdS8BUCh0&ab_channel=VeramosGaming

**Comment by BugSquisher9000** [comment]
Day 3 of fixing this

**Comment by BugSquisher9000** [comment]
day 4 of fixing this

**Comment by BugSquisher9000** [comment]
day 5 of fixing this

**Comment by bonfax4** [comment]
Lmao. I'll do you a favor, I'll close it down and you open a new issue.
