### ISSUE TITLE
[Quest] Invasion Point: Cataclysm

### ISSUE THREAD

**Issue by TheJesterrr** [chromiecraft/chromiecraft#4961]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

Teleporter to the quest area requires a 'Legion Hold Teleporter'. The item should drop from Mo'arg Weaponsmith if you have the quest.

100 kills later, the item has not dropped, making the teleport impossible.

### Expected Blizzlike Behaviour

Item drops allowing use of the teleporter.

### Source

https://www.wowhead.com/wotlk/item=30695/legion-teleporter-control#dropped-by

### Steps to reproduce the problem

1. Get quest, "Invasion Point: Cataclysm"
2. Try teleporter which prompts, "Requires Legion Hold Teleporter"
3. Farm away and realize it doesn't drop

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by veega233** [comment]
Okay so I have just started this quest and currently have the same issue, the quest before this one asks u to kill a certain mob for a 'Legion Hold Teleporter' However after bringing it back to the npc you don't get to keep it and end up being stuck at this point of the quest chain as you need the item to do the next quest and since u finished that quest, you can't make the 'Legion Hold Teleporter' drop again.

**Comment by TheJesterrr** [comment]
Oh, yeah. Quest giver should've given the item back. Forgot about that. Issue isn't the drop, its not having the item to begin with for the quest.

**Comment by veega233** [comment]
well there's 2 scenarios. 1. As you said, the item should have been kept to begin , 2. the item is indeed taken from you and you have to refarm it through mobs. However it would make the quest pointless since the quest asks you to pick up one from mobs so why would it make u go through the same process for the later quests?

**Comment by TheJesterrr** [comment]
Update: Standing in a very specific spot of the teleporter then standing still works. So quest is completable.

However, the prompt needs removed and as noted, it is VERY specific where you stand.

**Comment by slicplaya** [comment]
> Update: Standing in a very specific spot of the teleporter then standing still works. So quest is completable.
> 
> However, the prompt needs removed and as noted, it is VERY specific where you stand.

This is true. The teleporter should not have a cast time of 2 seconds. It should be instant. Easy fix. Get to work devs.

**Comment by Paradigmxd** [comment]
I can also confirm this bug. Unreal

**Comment by Paradigmxd** [comment]
as of 11.05.2023 this is still not addressed and it takes a long time to figure out the  bug and how to actually use the teleporter

**Comment by Pyromanihack** [comment]
I tested with this revision 6cd3b2a32cd9 2023-08-30 and the [quest item](https://www.wowhead.com/wotlk/item=30695/legion-teleporter-control) was dropped normally from various [Mo'arg Weaponsmith](https://www.wowhead.com/wotlk/npc=19755/moarg-weaponsmith)

**Comment by VladimirGaristov** [comment]
I would like to point out another detail: according to [WoWhead comments](https://www.wowhead.com/wotlk/quest=10766/invasion-point-cataclysm#comments) the teleporter should also work if you are mounted. Currently even if you are in the very specific spot where it works it gives an error "You are mounted".
