### ISSUE TITLE
Verog the Dervish - doesn't announce with a yell when spawned

### ISSUE THREAD

**Issue by FrodoFragginz** [chromiecraft/chromiecraft#4962]
I killed about 50 Kolkar trying to spawn him with no luck.  then when i went to check the kolkar chest near his spawn he just spawned without any announcement.  Maybe it's tied to the despawn issue?

**Comment by elthehablo** [comment]
Please fill in the form correctly. Furthermore, I do not think this is bugged, but I could be wrong and some minor detail might be wrong.

**Comment by FrodoFragginz** [comment]
He spawned in front of me without yelling.  Not sure what else you want.  I'm not on the server these days
