### ISSUE TITLE
Giant Softshell Clam in Desolace

### ISSUE THREAD

**Issue by Pudjero** [chromiecraft/chromiecraft#497]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ + ] enUS
- [ ] other (specify)

##### FACTION

- [ + ] Alliance
- [ + ] Horde

##### CONTENT PHASE:

- [ + ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Giant Softshell Clam](https://wotlk-twinhead.twinstar.cz/?object=177784#contains) instantly closes and give no loot.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[Giant Softshell Clam](https://wotlk-twinhead.twinstar.cz/?object=177784#contains) must give [Soft-shelled Clam](https://wotlk-twinhead.twinstar.cz/?item=15874)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Come to Desolace at Sar'theris Strand.
2. Try to open Giant Softshell Clam

##### EXTRA NOTES:

[Video](https://youtu.be/Ugnz9Q3Ew3k)
.gobject ( 31973 (Entry: 177784) - [Giant Softshell Clam X:-588.833984 Y:2648.149902 Z:-19.467100 MapId:1] )
With quest [Clam Bait](https://wotlk-twinhead.twinstar.cz/?quest=6142) works fine, i guess it must be uninteractable without quest

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Gizmoh** [comment]
Giant Soft Shelled clams now are non interactable, even with the quest 
![imagen](https://user-images.githubusercontent.com/4155081/126881872-03d0e8e3-126e-482a-8c82-2d94938aaa7f.png)

**Comment by iraizo** [comment]
This is weird, this should've been fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/6684

**Comment by VFaleiro** [comment]
I've just issued a duplicate #1747 (which I closed), not sure if it has any info not here though.
