### ISSUE TITLE
Changing alchemy specialization

### ISSUE THREAD

**Issue by Ovesss** [chromiecraft/chromiecraft#4972]
I tested it on the ptr and it worked. Now that i went back to the master of alchemy (Alchemist Gribble in Honor Hold) after abandoning a specialization, the specialization options are not there. Please fix this issue.

**Comment by balleny** [comment]
after unlearning the spec, you should be able to visit the 3 different spec. trainers and learn the respective spec they teach for free (only 1 - the other options have to become unavailable again once a spec has been picked again)

**Comment by Ovesss** [comment]
Yeah that is supposed to happen. And that is what happened on ptr. But it doesn´t work on the real server. Hence why i want it to be fixed.
