### ISSUE TITLE
[NPC] Ruga Ragetotem bugged quest

### ISSUE THREAD

**Issue by lightningwolf55** [chromiecraft/chromiecraft#499]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.
A NPC in Camp Tajuro, in the barrens, Ruga Ragetotem has a quest icon above his head but gives no quest when interacting with him.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
Either he should give a quest or should not have a quest icon.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just go to Camp Tajuro in the Barrens and interact with the NPC.
2. 
3. 
4.

##### EXTRA NOTES:

Type here.
Ruga Ragetotem  https://wowgaming.altervista.org/aowow/?npc=6394

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, I wasn't able to replicate this. Ruga is supposed to give a couple of warrior class quests at level 20, what race, level and class was your character when you saw this?

**Comment by Azcobu** [comment]
No response, closing.
