### ISSUE TITLE
NPC - Lunar Festival Harbinger

### ISSUE THREAD

**Issue by Knewklear** [chromiecraft/chromiecraft#50]
![WoWScrnShot_013121_001804](https://user-images.githubusercontent.com/58756521/107110229-56cf6880-6814-11eb-9269-932ece2518f4.jpg)

##### SMALL DESCRIPTION:

Double dialogue.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should have 1 set.

##### CURRENT BEHAVIOUR:

NPC shows two of the same set of dialogue.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
I can confirm this, should be only one gossip menu.

**Comment by nicoaravena** [comment]
Fixed in azerothcore/azerothcore-wotlk#4383
