### ISSUE TITLE
[Dungeon][RDF] Uldaman requires to be level 50 when it should be available from level 35

### ISSUE THREAD

**Issue by mturca** [chromiecraft/chromiecraft#500]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Uldaman requires to be level 50 when it should be available from level 35

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[Dungeon][RDF] Uldaman requires to be level 50 when it should be available from level 35

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Be level 35+ 
2.  Advance to Uldaman entrance on foot / Use the RDF tool to queue up for specific dungeon
3.  Notice that when trying to enter Uldaman you are prompted with a "You must be at least level 50 to enter" / same with RDF tool
4. As per RDF Uldaman should be available starting with level 35.

Attached are more details.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment]
![Uldaman RDF](https://user-images.githubusercontent.com/47978220/116791459-39cccd80-aac3-11eb-92c9-6e667b30762b.JPG)
![Uldaman entrance](https://user-images.githubusercontent.com/47978220/116791460-3a656400-aac3-11eb-9088-04f21d5b882c.JPG)

**Comment by 55Honey** [comment]
Fixed!
