### ISSUE TITLE
[Old Hillsbrad Foothills] Druid still in Tree of Life form while using mount.

### ISSUE THREAD

**Issue by Ziedge** [chromiecraft/chromiecraft#5001]
### What client do you play on?

frFR

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

When shapeshifted into tree form, you can cast mount and keep your tree form.

https://user-images.githubusercontent.com/82708448/218284230-f159f875-2da2-408a-bc06-4d10ea3b9d2c.mp4

### Expected Blizzlike Behaviour

Uppon using your mount, your tree form should be removed.

### Source

Always been like that, you can't shapeshift while mounting. (can't find source tho)

### Steps to reproduce the problem

1. Enter Old Hillsbrad Foothills as a heal druid
2. Cast Tree of Life
3. Cast mount
4. Notice that you're mounted and still under Tree of Life shapeshift

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by foo-17** [comment]
Tested in AzerothCore rev. 65e7bf107da9 2023-11-18 18:05:15 (master branch).

Entered 'Old Hillsbrad Foothills' dungeon as a level 69 ALLIANCE druid, turned on "Tree of Life" form. Casted mount item=47180/argent-warhorse, it took me out of "Tree of Life"-form.

Then tried as Horde and could replciate the issue. Level 69 HORDE druid, "Tree of Life" and "Moonkin" form will not be broken when casting mount (tested with: item=18794/great-brown-kodo). 

This issue may be related to issue https://github.com/chromiecraft/chromiecraft/issues/5027 . Horde druid forms may not be interpreted correctly due to buff "Human illusion" displaying Tauren druid characters as human instead.
