### ISSUE TITLE
Dragon breath cone is bugued on small range

### ISSUE THREAD

**Issue by sassouiabd** [chromiecraft/chromiecraft#5003]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Dragon breath is not working as expected at close ranged: 
https://www.twitch.tv/videos/1735583540?filter=highlights&sort=time

### Expected Blizzlike Behaviour

Dragon breath should work at close ranged

### Source

Dragon breath should work at close range.
this problem happens also with cone of cold (must be verified).

### Steps to reproduce the problem

Press dragon breath in closer range to the target. Turn slighthy the character angle until you are able to reproduce it:
https://www.twitch.tv/videos/1735583540?filter=highlights&sort=time

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Windows

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by foo-17** [comment]
Tested in AzerothCore rev. 65e7bf107da9 2023-11-18 18:05:15 (master branch). Tested as level 79 gnome mage using hostile creatures with id 1138 [Snow Tracker Wolf] and neutral creatures with id 1126 [Large Crag Boar] in Dun Morogh.

Hard to say if this works correctly or not. Enemies are hit when in front or 45 degrees to either side of the caster. Enemies are not hit when 90 degrees to either side of the caster. If caster stands within sprite of the enemy, it depends on exact position - sometimes enemy is hit, sometimes missed. (maybe also depends on whether enemy is already in combat with caster of not.) Found a "temporarily closed" issue stating that "Cone of Cold" was not pointing in correct direction: https://github.com/azerothcore/azerothcore-wotlk/issues/6643

unfortunately, twitch links are not available anymore, so initial report is difficult to validate.

**Comment by Kitzunu** [comment]
I cannot reproduce on https://github.com/azerothcore/azerothcore-wotlk/commit/8180841163e43960b1ef6a741beb9e94c0ace27e target needs to be infront of the caster
