### ISSUE TITLE
Feign Death doesn't make players lose target of the hunter

### ISSUE THREAD

**Issue by Elthz** [chromiecraft/chromiecraft#502]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When using [Feign Death](https://wowgaming.altervista.org/aowow/?spell=5384) the enemy player that is targetting you doesn't lose his target, which doesn't interrupt his attacks against you (casts/auto attacks).

[Video Proof here](https://www.youtube.com/watch?v=Lllj_4JiB6Y)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Feign death is supposed to make people who target you lose their target, interrupting any spell casting, melee or ranged attacks against you until they re-target you and begin attacking/casting again.

Vid from 2012 at minute 1:26 you can see an hunter being melee'd, as soon as he uses FD the warrior instantly loses the target, there are infinite other example in this very video of casts/auto attacks being interrupted by FD making players lose their targets on the hunter.

https://www.youtube.com/watch?v=PVhwiHmV1BI

##### STEPS TO REPRODUCE THE PROBLEM:

1. Target an hunter and attack/cast on him
2. Make him use Feign Death
3. See how the cast/attack goes through

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Before anyone else sees this confirmed and gets worried, the issue only seems to affect people in a party with you. More typical use, against enemies not partied with the hunter, appears to be working correctly.
