### ISSUE TITLE
Escape From Durnholde, Illusion of Alliance prevents Druid forms

### ISSUE THREAD

**Issue by whipowill** [chromiecraft/chromiecraft#5027]
In the Escape from Durnholde encounter, there is a buff applied to Horde players called "Illusion of Alliance" or something.  In a group that includes a Horde druid and an Alliance druid, the Alliance druid forms work fine, but the Horde druid forms are invisible -- presumptively due to this buff "Illusion of Alliance".  So the Horde players will never show any forms at all and have to play by memory w/out visibly seeing the forms that they are in.

**Comment by foo-17** [comment]
Tested in AzerothCore rev. 65e7bf107da9 2023-11-18 18:05:15 (master branch).

Could replicate. HORDE druid forms are not displayed correctly while in "Escape from Durnholde" instance. Leads to odd behavior when mounting as well (see https://github.com/chromiecraft/chromiecraft/issues/5001)
