### ISSUE TITLE
Rabbits/Hares should be skinnable

### ISSUE THREAD

**Issue by Stump876** [chromiecraft/chromiecraft#503]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Like the title says. Rabbits and hares are not skinnable.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to skin them for either light leather or scraps.

I haven't checked it yet but since I'm on the topic, sheep should also be skinnable and have a chance to drop wool as well as light leather or scraps
[https://classic.wowhead.com/npc=1933/sheep](url)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill a rabbit or hare
2. Try to skin it
3. 
4.

##### EXTRA NOTES:

[https://classic.wowhead.com/npc=721/rabbit#skinning](url)
[https://vanillawowdb.com/?npc=721](url)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, rabbits/hares/sheep not being skinnable is correct behaviour as of patch 3.2:

Patch 3.2.0 (2009-08-04): Critters such as Sheep, Cows and Rabbits are no longer skinnable. (https://wowpedia.fandom.com/wiki/Skinning#Patch_changes)

"Skinners were previously able to skin rabbits and other critters for easy  [Ruined Leather Scraps] and  [Light Leather] for beginner Leatherworkers, but this was removed." (https://wowpedia.fandom.com/wiki/Rabbit?oldid=2359445)

https://www.wowhead.com/forums/topic/skinning-critters-not-allowed-in-3-2-anymore-112739
