### ISSUE TITLE
Manaforge Ara questline, final quest can't turn in

### ISSUE THREAD

**Issue by Baezinhas** [chromiecraft/chromiecraft#5034]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

So, I completed the [Shutting Down Manaforge Ara] quest, died at Manaforge Ara to ressurect at Area 52 and turn in the quest. Quest giver is yellow and says completed but wont let me turn in the quest. I attached Screenshots to clarify. Also tried relog and reload and no help.
Please help ! :) 
![WoWScrnShot_021323_185502](https://user-images.githubusercontent.com/125307103/218553038-488c8da5-bcfe-4a6e-be86-2dd6b724f030.jpg)
![WoWScrnShot_021323_185512](https://user-images.githubusercontent.com/125307103/218553045-ab42f83b-b97e-42a7-a3e2-d6c439017a57.jpg)
![WoWScrnShot_021323_185531](https://user-images.githubusercontent.com/125307103/218553050-88129c2d-7ee6-4e55-8772-c62a6f6d4b90.jpg)

### Expected Blizzlike Behaviour

I think there isn't much to add here, it should just turn in the quest. 

### Source

-

### Steps to reproduce the problem

-

### Extra Notes

https://www.wowhead.com/wotlk/quest=10365/shutting-down-manaforge-ara

### AC rev. hash/commit

-

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vexima** [comment]
did it in a group of 3 (all alliance), only one person was able to turn quest in despite the fact that everyone got quest marked as (Complete) in quest log. everyone had looted Access Crystal and got credit for console shutdown. after doing quest again (by dropping it and taking it from quest giver again) with same people (2 of 3 having quest this time), only one was able to turn it in yet again.

FWIW in both cases the person who was able to turn quest in was the one who initiated manaforge shutdown sequence.

**Comment by Spectralus** [comment]
Confirmed bugged, did it in group. Cant turn in even if I have B'naar Access Crystal in inventory. Tried relog and cache deleting.

**Comment by balleny** [comment]
same here, can confirm the issue that the completion is shown for each party member, but turn in not possible

**Comment by foo-17** [comment]
This issue is likely the one reporte din https://github.com/azerothcore/azerothcore-wotlk/issues/15303 : all Manaforge quests were bugged so that when done in a group, only the person initiating the shutdown could turn in the quest (though quest was marked as completed for all members). Was fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/15393

**Comment by elthehablo** [comment]
So fixed. Nice
