### ISSUE TITLE
Quest "Against the Legion" can't be started

### ISSUE THREAD

**Issue by Theleruby** [chromiecraft/chromiecraft#5039]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

After completing the quest "Altruis" (either https://wowgaming.altervista.org/aowow/?quest=10640 or https://wowgaming.altervista.org/aowow/?quest=10689, depending on whether you are doing Aldor or Scryers rep) there should be three follow on quests available:
- "Against the Legion" (https://wowgaming.altervista.org/aowow/?quest=10641)
- "Against the Illidari" (https://wowgaming.altervista.org/aowow/?quest=10668)
- "Against All Odds" (https://wowgaming.altervista.org/aowow/?quest=10669)

However, the quest Against the Legion doesn't display and can't be started. The other two quests are available to start as expected.

### Expected Blizzlike Behaviour

It should be possible to start all 3 quests.

### Source

Quest chain is detailed in many comments on wowhead, for example https://www.wowhead.com/wotlk/quest=10640/altruis#comments:id=156127

### Steps to reproduce the problem

1. Pick either Aldor or Scryers to get reputation with (I went with Aldor)
2. Complete the quest chain up to Altruis
3. Go to Altruis the Sufferer (https://wowgaming.altervista.org/aowow/?npc=18417)
4. Attempt to pick up the 3 follow on quests
5. Observe only 2 can be picked up

### Extra Notes

The aowow page https://wowgaming.altervista.org/aowow/?quest=10641 seems to incorrectly show the quest as requiring "Forge Camp: Annihilated" to be completed. I tried completing that to see if Against the Legion would then be startable, but it still wasn't.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sombritas** [comment]
i'd like to confirm this bug exists, yet i only had it happen to me on alliance side. my draenei shaman only got 2 quests, not getting "against the legion" while my horde characters (and guildies) got all 3 of them. it's not an urgent fix, but the chain continues in later coming dungeons, so it would be neat to have it then.

**Comment by Spectralus** [comment]
Also confirmed bugged. Quest giver does not give this quest. Finished previous quests. Alliance side. Relogged and cache deleted, still nothing.

**Comment by nJDOA** [comment]
Also confirming here. The 3rd Quest "Against the Legion" is not available, stopping the complete Quest-Chain.

Lvl 69 Alliance

**Comment by Si1ker** [comment]
It's not a alliance-only issue.
Orc lvl 69 - Only got Against all the Odds and Against the Illidari / Missing Against the Legion.

(Live ChromieCraft, ofc)
