### ISSUE TITLE
Caster Mobs

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#5046]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Every Caster Mob will not follow you when you kick/silence them

### Expected Blizzlike Behaviour

If you kick them they should follow you unless they have a 2nd school of magic that they can cast from (If you kick them on fire and they have nothing else to cast they follow you, if you kick them on fire and they can cast frost they will cast frost.)
If you silence them they should follow you until the duration of the silence is over

### Source

Self evident but someone reported a similar issue https://github.com/chromiecraft/chromiecraft/issues/3512
seems to me that only the strathholme mobs were fixed when the fix should have been a core fix

### Steps to reproduce the problem

Find a caster ( I tested it with Bloodchewer evoker but this will work with any caster)
Kick or Silence them, any kick works but here is rogue spell https://wowgaming.altervista.org/aowow/?spell=1766#.

### Extra Notes

Like i said someone reported a similar issue and it seems only the strathholme mob got fixed when it should have been a core fix

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Vyperhand** [comment]
This is definitely a global behavior issue.  Any form of silence should cause a caster to immediately begin approaching their target with the highest threat.  This mechanic is key to a number of pulls and behaviors in dungeons and the open world.  In fact, this is a large benefit to the paladin talent Shield of the Templar (https://www.wowhead.com/wotlk/spell=53711/shield-of-the-templar#comments ) .

When tanking for dungeons/raids, this was a key element of pulls to drag casters into the Paladin AoE to maintain threat - as it is now, the casters just stare at you and wait out the silence.

As of right now, caster mobs just stand still doing nothing for the duration of the silence, then resume casting.  Open world and dungeon alike, caster behavior seems to be universally incorrect in this manner.

**Comment by elthehablo** [comment]
Correct this is known, and very likely takes a lot of effort to overhaul and fix. That is why nobody has fixed it yet. There is, well the issue is more broad, even a bounty on it iirc

**Comment by Salehyn** [comment]
Same issue as 
https://github.com/chromiecraft/chromiecraft/issues/3144
