### ISSUE TITLE
[Quest] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5047]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

NPC to kill doesnt spawn
Ghost is transformed to Teron
Teron doesnt transform back to Ghost

### Expected Blizzlike Behaviour

transform into Teron and fight Karsius https://wowgaming.altervista.org/aowow/?npc=21877#summoned-by-npc
https://www.youtube.com/watch?v=Czm_ucQdB9A

### Source

https://wowgaming.altervista.org/aowow/?quest=10645

### Steps to reproduce the problem

.

### Extra Notes

cause the NPC isnt transforming back, the quest chain cannot be turned in or continued by any player on the server

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
`.q a 10634`
`.q c 10634`
`.q a 10635`
`.q c 10635`
`.q a 10636`
`.q c 10636`

Comparing the script to Retail, it's not perfect. I'll see if I can do something today still.

**Comment by Gultask** [comment]
I spent so long trying to figure out what it was.
Karsius spawns with the Shadowmoon Invisibility Aura, which makes him invisible to everyone without the Spectracles
But since they get removed when the player controls Teron, then it means that Karsius stays invisible forever...
I'm fixing it.

**Comment by Gultask** [comment]
Was... a bit harder than I thought

**Comment by balleny** [comment]
video still needed? only got to render it now - but I guess its obsolete already

**Comment by Gultask** [comment]
I don't think so. I think I got it working now.
But thank you!
