### ISSUE TITLE
[Love is in the Air] Unable to start Man on the Inside (Quest ID: 24792)

### ISSUE THREAD

**Issue by andovcr** [chromiecraft/chromiecraft#5057]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

I've completed A Friendly Chat (Quest ID: 24657) which is supposed to open up Man on the Inside (Quest ID: 24792) from Inspector Snip Snagglebolt (NPC ID: 38066) in Stormwind, but all I see is a silver exclamation point (not high enough character level), even though I'm level 69 (which is the current level cap).

Similarly, I see no gossip option from Dungeonmaster Steamheedle Shyster, so I have no way to start the SFK holiday event.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/58115742/219494815-52c7d92f-1b04-4c70-b7e5-3f9a0fab3db5.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/58115742/219494908-30d89907-b00e-4f48-addf-564be45cebde.png">

### Expected Blizzlike Behaviour

I understand that there is probably some level scaling at work within CC, given the current level cap and what this quest was originally designed for, but I believe I'm supposed to be able to pick up this quest upon completing the previous chain.

### Source

https://www.wowhead.com/wotlk/quest=24657/a-friendly-chat#comments
https://www.wowhead.com/wotlk/quest=24792/man-on-the-inside#comments

### Steps to reproduce the problem

Complete quest ID: 24657
See that quest ID: 24792 is not able to be picked from npc ID: 38066 (even as current max level 69)

### Extra Notes

1. What are the current level requirements for these quests?  
2. Does quest=24657/a-friendly-chat require a different level than quest=24792/man-on-the-inside ?  
3. Is quest=24792/man-on-the-inside supposed to be accessible by lvl 69 currently on CC?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
A man on the inside has a level requirement of 78 as it's wotlk
It is not supposed to be available
Inspector Snip Snagglebolt offers to teleport you if you are a party leader

**Comment by andovcr** [comment]
Thanks so much Tereneckla!  Really appreciate the clarification.  I didn't know you needed to be in a party to see the gossip option to go to the dungeon.  I didn't see any instructions anywhere on how to access this dungeon holiday event given the current level cap without doing the quest.

For future reference, it's Dungeonmaster Steamheedle Shyster that would offer the teleport (leader or otherwise) as long as you're in a party.

Feel free to close this.
