### ISSUE TITLE
[Quest] Vahlarriel's Search - Dalinda gets killed by the mobs guarding her before starting the escort quest

### ISSUE THREAD

**Issue by anglerf1sh** [chromiecraft/chromiecraft#506]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Currently Dalinda (GUID 26987) gets killed by the mobs sorrounding her before you start the escort quest https://classic.wowhead.com/quest=1440/return-to-vahlarriel

##### EXPECTED BLIZZLIKE BEHAVIOUR:

She should not to be killed before the player accepts the escort quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Start the questchain to find Dalinda https://classic.wowhead.com/quest=1437/vahlarriels-search
2. Progress through the questchain until you get tasked to search for her in the Thunder Axe Fortress
3. Try to find her in the right building in the middle (Round room, cyrstal in the middle)
4. She most likely won't be there, kill all the mobs in the room and wait for her to respawn

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Closing as invalid.

![image](https://user-images.githubusercontent.com/61223313/116823607-a935d200-ab42-11eb-9a35-7bdb5391135f.png)

Check also https://github.com/azerothcore/azerothcore-wotlk/issues/5593#issuecomment-830851884

**Comment by anglerf1sh** [comment]
I really suggest checking this out on live servers. She was killed when I had the quest accepted as well when I had the quest already finished and turned in. Unless you guys test on a newer version of the azeroth core that has this bug already fixed for some reason.

**Comment by pixelhaufen-cc** [comment]
Same issue here: saw the questionmark on the map, after someone escorted her out of the building.
Seems to affect only the first spawn, after the escort quest maybe?
