### ISSUE TITLE
(Quest) Trapping the Light Fantastic

### ISSUE THREAD

**Issue by Vlaxitov** [chromiecraft/chromiecraft#5067]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

There are no moving small orbs of light to trap. The light orbs that are present don't move and cannot be trapped.
![WoWScrnShot_021823_001622](https://user-images.githubusercontent.com/103907655/219843664-31d293d1-2e70-4bdc-8854-db52c903e98c.jpg)

### Expected Blizzlike Behaviour

There are supposed to be small orbs of light that move and can be trapped.
https://www.youtube.com/watch?v=85S_GIuo8s0

### Source

![WoWScrnShot_021823_001622](https://user-images.githubusercontent.com/103907655/219843664-31d293d1-2e70-4bdc-8854-db52c903e98c.jpg)

https://www.youtube.com/watch?v=85S_GIuo8s0

### Steps to reproduce the problem

This is an open ended quest problem

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by slicplaya** [comment]
This is a repeat of another report. It's still not fixed. https://github.com/chromiecraft/chromiecraft/issues/4946

**Comment by avarishd** [comment]
Hey, thanks for the report, but this issue has been already reported https://github.com/chromiecraft/chromiecraft/issues/4946 (and fixed)
