### ISSUE TITLE
[Mage][Talent] Fiery Payback was wrongfully "fixed".

### ISSUE THREAD

**Issue by bonfax4** [chromiecraft/chromiecraft#5072]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

There's a 1 min icd after this ["fix"](https://github.com/chromiecraft/chromiecraft/issues/3770) was applied.

### Expected Blizzlike Behaviour

Talent should only be subject to diminishing returns.

### Source

https://www.wowhead.com/wotlk/spell=64357/fiery-payback#comments
![9cec3585d56b5f31507b5ea4a80329ef](https://user-images.githubusercontent.com/16911730/219962566-57fd6fcd-5570-4482-ade5-0883bcc6acc2.png)
![4ddada5e9ed5e16101a7b058a9d52f38](https://user-images.githubusercontent.com/16911730/219962594-4f4c7c76-37a0-41d4-8d81-25c28700dc65.png)

### Steps to reproduce the problem

Spec the talent and get attacked.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by slicplaya** [comment]
This is correct. It should not have an icd. As much as I hate to say it against the most broken talent in the game.

**Comment by Reily93** [comment]
https://www.wowhead.com/wotlk/it/spell=64346/fiery-payback it has 1 min cd ,ppl who write things random are untrustworthy as proof

**Comment by bonfax4** [comment]
Classic wowhead is not a good source. Some shit is custom. Same spell shows 9 CD on old databases https://wotlk.evowow.com/?spell=64349. Only way to know for sure is video proof

**Comment by bonfax4** [comment]
I'll look for video proof but there's 3-4 ppl saying the same thing.

**Comment by bonfax4** [comment]
[On classic](https://www.youtube.com/watch?v=TlUmuUVfsi4 )

@2:50 rogue procced it for 6 seconds (no anti disarm enchant)
@3:02 procced again 3 sec duration

**Comment by bonfax4** [comment]
[Old retail video](https://youtu.be/4B667NcfR-Y?t=99)
@1:40 hunter procced it
@1:48 right before he died he procced it again

**Comment by avarishd** [comment]
Can confirm, was wrongfully fixed due to invalid report(s).
