### ISSUE TITLE
[Quest] Getting Down to Business

### ISSUE THREAD

**Issue by Butifarras** [chromiecraft/chromiecraft#5074]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

After completing the previous quest [https://wowgaming.altervista.org/aowow/?quest=10270], and accepting Getting Down To Business if you abandon it, you can't retake the quest and are locked out of the entire questline.

When you use the Ethereal Teleport Pad [https://wowgaming.altervista.org/aowow/?object=184073] you don't have the option to summon Marid.
I suspect you could also be locked out of the questline if you don't immediately accept the quest when you complete the previous one.

![image](https://user-images.githubusercontent.com/89665485/219966699-6438a0ee-061a-49c7-ab92-ea345fd43103.png)

### Expected Blizzlike Behaviour

You should be able resummon Marid [https://wowgaming.altervista.org/aowow/?npc=20518] from the Teleport Pad.

### Source

It is inconsistent from all other quest to be able to be locked out of a quest chain.

### Steps to reproduce the problem

1. Turn in A Not-So-Modest Proposal
2. Accept Getting Down to Business
3. Wait for Image of Wind Trader Marid to despawn.
4. Abandon the quest.
5. Try to summon him again,

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Thanks for the report, can confirm.
