### ISSUE TITLE
Issue with Quest "Dont Kill the Fat One"

### ISSUE THREAD

**Issue by rramk01** [chromiecraft/chromiecraft#5078]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

Could not complete quest "Don't kill the fat one" in terrokar forest. You're supposed to get an NPC to half health. This worked initially but i tried to get the quest but he turned back to unfriendly and I couldnt complete the quest. This worked for other people  but did not work for me, could you help?

I tried to abandon the quest and redo it however i cannot interact with the quest giver 

### Expected Blizzlike Behaviour

complete quest

### Source

no source needed, could not complete 

### Steps to reproduce the problem

All me to redo the quest
Fight the NPC 
Complete quest 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
did you fight in the center area next to the fire? if you fight outside of that, he will not yield but fight to death instead

**Comment by rramk01** [comment]
Hi thanks for the response.

I actually fought him and he turned friendly but as I was reading the text
for the next quest from him. He turned from friendly to hostile and had
full health.

I have already left the area on my character. Is there any way you complete
the quest on that character? or should I try it again in the fire? I am not
sure it will work a second time.

I also did the part of the quest where you kill the 10 boulderfist invaders
however when I click on the other ogres, the note about the quest doesn't
show up - ie "kill 10/10 boulderfist invaders". So I am concerned it won't
work.

Thanks

**Comment by rramk01** [comment]
Hello,
I tried killing the NPC again within the fire area and it did not work. I
cannot abandon or redo the quest. Can you help with this?

thank you

**Comment by rramk01** [comment]
Hello I'm okay if you undo the quest on my character do that I can redo it
and complete it. Not having that quest done causes me to miss some of the
story line

My characters name is Rektan
he is an orc warrior if that helps

thank you

**Comment by BeefSteaker** [comment]
Hi rramk, i wasnt able to replicate this issue. 
as long as you kill the 10 ogre first he submits. as far as i can tell this is blizzlike
![image](https://user-images.githubusercontent.com/11332559/221617164-da217ce5-17df-4876-b7b1-5477e41bb989.png)

**Comment by rramk01** [comment]
Hi thanks for the screenshot. I actually completed the quest and already
killed the 10 boulderfist ogres! I fought him and he surrendered. I click
him and completed the quest.

I was reading through the quest he gives after that part and he went back
to hostile and I couldn't get the quest anymore. I admit there was a pause
because my wife had called me to do something.

I did not accept the quest that he provides called "Success!" and I cannot
fight him again to do it. Can you help? perhaps add "Success!" to my quest
log so I can continue?

thanks

**Comment by rramk01** [comment]
Hi,
I just logged in and saw the NPC with the available quest!!!! He was not in
his usual location - I assume one of the GMs did this?

There was a second or two where I could accept the quest from Unkor the
Ruthless but he started attacking me. Can you do this again? If I knew to
expect this, I would have been quicker to get the quest. Thank you, thank
you, thank you for helping.

I hope doing it again isn't too much trouble.

**Comment by rramk01** [comment]
Hello,
just following up on this issue. Are you guys able to help with this issue
I have with the quest, i tried again to kill this NPC (Unkor the Ruthless)
and talk to the quest giver (Kilrath) but I am stuck in this story.

**Comment by rramk01** [comment]
![image](https://user-images.githubusercontent.com/123597966/222876590-5f99fe90-ae37-478f-a0e1-dde4f049721d.png)

**Comment by rramk01** [comment]
![image (1)](https://user-images.githubusercontent.com/123597966/222876608-b6e3755a-1bf6-4c4d-a959-9e79d658ec36.png)

**Comment by rramk01** [comment]
the quest still does not work and I cannot complete it

**Comment by Eledor-collab** [comment]
Hey guys, for those having the same issue, you can find a solution on the issue "Quest: Don't Kill the Fat One (Mag'har) #5073".
