### ISSUE TITLE
Earthmender Wilda is unresponsive.

### ISSUE THREAD

**Issue by ozgurkuren** [chromiecraft/chromiecraft#5082]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

NPC is unresponsive in either situation: whether you kill the Keeper of Cistern first before speaking with Wilda or not.

### Expected Blizzlike Behaviour

The npc should have a quest dialog and start an escort quest. 

### Source

https://wotlk-twinhead.twinstar.cz/?quest=10451 quest link
https://wotlk-twinhead.twinstar.cz/?npc=21027 npc link

### Steps to reproduce the problem

Steps to Reproduce:
1- Go to Coilskar Cistern.
2- Find the NPC "Earthmender Wilda".
3- Observe the quest mark on her.
4- Click on her to get the quest started.
5- The NPC is unresponsive and nothing happens.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi ozgurkuren, i was able to start and progress the quest with no issue, can you confirm if you are still having the issue?

https://user-images.githubusercontent.com/11332559/220414224-cc91a38a-07b6-4c1a-bacd-093a513ec48c.mp4

**Comment by fabi1010** [comment]
got the same problem.
can confirm npc is still unresponsive

**Comment by ozgurkuren** [comment]
Hi beef, in my version, the npc is underwater, just before the keeper of cistern, and unresponsive. Tried it again now, and still the same issue.

**Comment by BeefSteaker** [comment]
On further testing ive been able to reproduce it. not sure what triggers it, but on some spawns she gets stuck like this
