### ISSUE TITLE
Druid Shapeshift form not showing in Durnhold Keep dungeon

### ISSUE THREAD

**Issue by abse7867** [chromiecraft/chromiecraft#5084]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Can't see shapeshifted forms in Durnhold Keep. 

### Expected Blizzlike Behaviour

Show shapeshifted forms in dungeon.

### Source

Any version of the game with Durnhold Keep.

### Steps to reproduce the problem

1. Use druid
2. Enter Durnhold Keep dungeon.
3.  Shapeshift

### Extra Notes

![Screenshot 2023-02-21 135945](https://user-images.githubusercontent.com/121920001/220458104-84a08278-e9c5-4659-b222-4ab8bfcfd24d.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment]
works just fine for me

**Comment by BeefSteaker** [comment]
Hi, works fine as far as i can test. did you have any texture patches or costumes that might have bugged it?
https://user-images.githubusercontent.com/11332559/221619983-a72ba1e6-13cd-4a70-b1ac-b906adc50c43.mp4

**Comment by whipowill** [comment]
This is duplicate post, but my experience is A) this only is an issue for Horde druids, and B) is probably due to the buff "Human Illusion" that makes you look alliance.

**Comment by abse7867** [comment]
I just use the had texture pack from the downloads. Sent from my iPhoneOn Feb 27, 2023, at 9:22 AM, BeefSteak ***@***.***> wrote:﻿
Hi, works fine as far as i can test. did you have any texture patches or costumes that might have bugged it?
https://user-images.githubusercontent.com/11332559/221619983-a72ba1e6-13cd-4a70-b1ac-b906adc50c43.mp4

**Comment by Gorandor** [comment]
@BeefSteaker I have the Same issue in CoT:Stratholm with my tauren druid. HD-Pack from ChromieCraft website is installed

<img width="3129" height="1243" alt="Image" src="https://github.com/user-attachments/assets/8c0a99ce-2841-4807-9f0d-67c32dbaaa6a" />
