### ISSUE TITLE
Weapons of Choice not dropping shield

### ISSUE THREAD

**Issue by jbockmon** [chromiecraft/chromiecraft#5086]
Razormane Warfrenzy is not dropping the razormane war shield to complete the quest. According to wowhead it should have a 15.2% drop rate. I killed more than 50 of them, and it never dropped. 

https://wowgaming.altervista.org/aowow/?npc=3459
https://wowgaming.altervista.org/aowow/?item=5094

**Comment by BeefSteaker** [comment]
Hi [jbockmon](https://github.com/jbockmon). Seems like youve had some bad luck.

i tested it on my live char and got one to drop after 5 kills 
![image](https://user-images.githubusercontent.com/11332559/221615428-0864031d-4b37-443a-af18-1acab69bdfab.png)

i can also confirm the drop rate is correct in the database
![image](https://user-images.githubusercontent.com/11332559/221615537-e7462626-32eb-4aaf-9fb5-0eb772becb42.png)
