### ISSUE TITLE
Fell to death while bubbled, character is alive but can't do any action as it says I'm dead

### ISSUE THREAD

**Issue by gattostivalato** [chromiecraft/chromiecraft#5091]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

I used https://wowgaming.altervista.org/aowow/?spell=642 to avoid fall damage, but on landing I didn't get https://wowgaming.altervista.org/aowow/?spell=25771  and my character appeared alive with full HP, but couldn't take any action as I received "You are dead" or "You cannot do that when you're dead" error messages. 

I was automatically teleported to the nearest graveyard and was able to move again and act as normal

### Expected Blizzlike Behaviour

Divine shield should've prevented fall damage and I shouldn't have died. 

If death occurred, I should've transitioned to ghost phase to run back to the spirit healer. 

### Source

? expected death behaviour

### Steps to reproduce the problem

1. Jump off the cliff of Telaar into the river below
2. Mid-air, activate https://wowgaming.altervista.org/aowow/?spell=642
3. Fall into the river
4. You're dead per the issue described 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Win 11 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello gattostivalato. Thanks for the report. Unfortunately, I can't confirm casting divine sheild and not getting Forbearance. Every single time I've cast it, I've recieved the debuff. Falling mid-air, on the ground, in water, I always recieved it.

While I couldnt duplicate the "dead but not dead" jumping in water at Telaar. I can confrim jumping off the world and bubbling on the way down keeps you alive, but gives notifications that you are dead after you "land".  I couldn't do anything, and after a few minutes I was "revived" and ported to the graveyard. I don't see why you would be brought back as a ghost, as there would be no way at all to get back to your corpse to rez. Unless you can find something that says otherwise, I believe the behavior is correct.
