### ISSUE TITLE
Unable to enter stockades

### ISSUE THREAD

**Issue by HugginsHomes** [chromiecraft/chromiecraft#5093]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

When attempting to enter the stockades instance in Stormwind I get the error "Map cannot be entered at this time."  I have tried this with two accounts and have reloaded both with the same result.

### Expected Blizzlike Behaviour

Should be able to enter and play the instance

### Source

None

### Steps to reproduce the problem

Attempt to enter the instance.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ohkasdasf** [comment]
Tested with a level 64 Dwarf, Paladin. Was able to enter the instance, worked just fine.

Do you run any client modifications?

**Comment by BeefSteaker** [comment]
Not able to reproduce either, could you have perhaps hit the hourly instance limit?

**Comment by HugginsHomes** [comment]
Hi BeefSteak,

It was an odd issue that seems to have resolved itself.  It was my first 
attempt to enter in two weeks.  When I first entered I had a third group 
member that was offline, which shouldn't have caused any issues.  
Eventually I disbanded the group and relogged the two toons 
individually.  One of them spawned inside the instance (even though it 
had been outside the instance before and when I last logged out).  After 
that, I was able to enter the instance and play normally.  Odd glitch.

Thanks,
Ryan/HolierThanU


------------------------------------------------------------------------
Thank you,
Ryan Huggins, Broker
CISA, CRISC, TLO
Huggins Homes
Conejo Simi Moorpark Association of Realtors: Board of Directors, 
Community Service Award Winner
DRE# 01234617

Serving all your real estate needs in Ventura County, Agoura and Calabasas

***@***.***
c:805.905.4000 <tel:+18059054000>
w:HugginsHomes.com <hugginshomes.com>
Signal and Wire available by request
