### ISSUE TITLE
Iverron's Antidote - Tirisfal Glades

### ISSUE THREAD

**Issue by claymore147** [chromiecraft/chromiecraft#51]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### SMALL DESCRIPTION:

Found bug linked to quest objective [Moonpetal Lilly](https://wowgaming.altervista.org/aowow/?item=10641) in quest [Iverron's Antidote](https://wotlk.evowow.com/?quest=3521) in [Tirisfal Glades](https://wotlk.evowow.com/?zone=85). 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After gathering all pieces of quest objective required to complete quest, this quest objective is expected to be unable for gathering. Sparkling animation should be executed too.

##### CURRENT BEHAVIOUR:

After gathering 4pcs. of [Moonpetal Lilly](https://wowgaming.altervista.org/aowow/?item=10641), sparkling animation 
persists and player is still able to loot quest objective, but without any drop. Quest objective disappears after looting it in that case. 
![quest](https://user-images.githubusercontent.com/78303208/107117044-b874ee80-6877-11eb-8e27-eb25d9c32f8b.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Quest-Line starts at NPC [Dirania Silvershine](https://wotlk.evowow.com/?npc=8583) by quest [A Good Friend](https://wotlk.evowow.com/?quest=4495)
2. Then it is required to teleport to [Iverron](https://wotlk.evowow.com/?npc=8584), take another quest and teleport to Dirania. 
3. After completing quest [A Friend in Need](https://wotlk.evowow.com/?quest=3519), Dirania will finally offer bugged quest [Iverron's Antidote](https://wotlk.evowow.com/?quest=3521). It is required to gather all 4pcs [Moonpetal Lilly](https://wowgaming.altervista.org/aowow/?item=10641) to see a bug. 
4. You can also check [Hyacinth Mushroom](https://wotlk.evowow.com/?item=10639) if there is not same problem.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacaw** [comment]
Thanks @claymore147 for the report.
I confirm the sparkling animation is still present for https://wowgaming.altervista.org/aowow/?item=10641 after you finish loot it.
But the sparkling animation is missing for https://wowgaming.altervista.org/aowow/?item=10639, but it's still lootable.

**Comment by Stifler82** [comment]
It doesn't seem to me that GameObjects are buggy, to me it looks more like someone who has the **shitty enGB Client**...

**Video Test:** [Sparkling loot animation](https://youtu.be/4NQzRJdHPZw)
