### ISSUE TITLE
Ghaz'ans Acid Spit is cast on everyone instead of a single target only

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5101]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Ghaz'ans https://wowgaming.altervista.org/aowow/?npc=18105 ability Acid Spit https://wowgaming.altervista.org/aowow/?spell=34290 is cast on the whole group.

### Expected Blizzlike Behaviour

it should affect only 1 target at a time.
possible targets exclude the current tank while other targets are available

### Source

https://classic.warcraftlogs.com/reports/yT8Dgc4QApZqYwV2#fight=2&type=damage-taken&view=timeline&target=82&start=3382590&end=3426394
https://youtu.be/e3j5ZDfBAYU?t=162
https://classic.warcraftlogs.com/reports/vtGYd3LbNcXaj8Qm#fight=1&type=damage-taken&view=timeline&target=39&start=1102394&end=1148361
https://classic.warcraftlogs.com/reports/9DyAcVjtk7LT842M#fight=90&type=damage-taken&view=timeline&target=359&start=14986942&end=15050826

### Steps to reproduce the problem

engage Ghaz with atleast 3 players

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, spell 34290 has TargetB SRC_AREA_ENEMY, making it effectively an AOE.
Which, judging by the logs and YT videos, it should not be the case.
![image](https://user-images.githubusercontent.com/46330494/232558089-67f22216-8f3f-451f-b217-2ab9a5658891.png)
