### ISSUE TITLE
Mind Vision is considered a hostile action on both enemy and friendly targets.

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#5113]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

When you cast Mind Vision on an enemy, it has a 'hit' chance just like all other spells. But when you cast it on a friendly target, it also uses this same hit chance, meaning you can miss your mind vision cast on a friendly target.

### Expected Blizzlike Behaviour

When you cast Mind Vision on a friendly target such as a guard, it should be considered a buff to the target. Helpful spells such as buffs can not miss.

### Source

Personally installed the wrath classic PTR (which is free), made a lvl 70 template character (human, 70) casted like 50 [Mind Vision] on a lvl 80 guard in SW as a priest and never missed once. I then took off all gear to remove any hit bonuses and did it once more until completely oom. Not one had missed.

### Steps to reproduce the problem

Cast Mind Vision on a friendly NPC higher lvl than you, without the hit% to land hostile spells

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/73e289ad95c551b9ba4822c6149bcc98c3422665

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello EdyGlockenspiel. Thanks for the report. Do you have a Blizzlike source on how it should work. What you say makes sense to me, but we need referance material.

**Comment by EdyGlockenspiel** [comment]
I posted in the report that I DLed the Blizzard classic wrath PTR (which is
free) and tested it myself on a lvl 80 guard at 70 and never missed, with 0
hit rating and went oom casting it so many times.

**Comment by EdyGlockenspiel** [comment]
"Personally installed the wrath classic PTR (which is free), made a lvl 70 template character (human, 70) casted like 50 [Mind Vision] on a lvl 80 guard in SW as a priest and never missed once. I then took off all gear to remove any hit bonuses and did it once more until completely oom. Not one had missed." If you need to test it yourself you just need the free b.net client and install the free wrath classic PTR, then make a lvl 70 template character to test it yourself. This was how I had tested it.

**Comment by EdyGlockenspiel** [comment]
> Hello EdyGlockenspiel. Thanks for the report. Do you have a Blizzlike source on how it should work. What you say makes sense to me, but we need referance material.

I don't know how to get more blizzlike than the actual offical Blizzard wrath classic servers for testing. So if that is not good enough then no, I don't.
