### ISSUE TITLE
Satchel of Helpful Goods (65-70)

### ISSUE THREAD

**Issue by EdyGlockenspiel** [chromiecraft/chromiecraft#5114]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

According to many people, the Satchel of Helpful Goods (65-70) has it's drops bugged and will use *literal* drop chances for it's items. This results in a chance to obtain multiple items as well as a rather high chance to obtain 0 items, as each item has a 'chance' to drop

### Expected Blizzlike Behaviour

Like all lock boxes and DF loot bags, the item inside is supposed to be guaranteed, but randomized. Instead of a 25% chance for X item, it is 'one of these items will drop, 4 items of choice, 25% between which one' 

### Source

Any and all other Satchel of Helpful Goods for brackets prior to (65-70) as I have heard no problems with those, lock boxes ect. 
https://www.wowhead.com/wotlk/item=52005/satchel-of-helpful-goods#comments the first comment here displays what can and can not be obtain in each bracket bag.

### Steps to reproduce the problem

Q for a random fungeon at 65+, finish the instance and open your bag (or use GM commands to grant yourself itemID 52005 and open them all to test drop chances.

### Extra Notes

There are also a handful of lockboxes which seem to have the same problem of possibly containing no loot whatsoever. They have the same bug as this item in which instead of the system picking a single item from a pool at random, it shows each item as being X % drop rate and opening the box runs a % roll for each and every item to see what items dropped, instead of picking one of lets say 100 items (1% chance, 1/100) meaning you have a high chance to get nothing or could get 10 items. This seems to be a common bug on most private servers I have played on. I don't know jack about coding but this is all just my assumption as to how the system would work.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/73e289ad95c551b9ba4822c6149bcc98c3422665

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
While I've seen what you described happen many, many times. This one's different 😛 

Each item actually has conditions attached to it. For some reason one item in the cloth and leather category had their conditions switched around, so they'd never actually drop.
