### ISSUE TITLE
[Jewelcrafting] Kirembri Silvermane is selling Wrath epic JC designs

### ISSUE THREAD

**Issue by anhility** [chromiecraft/chromiecraft#5116]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

Scryers JC trainer Kirembri Silvermane currently have many, if not all, of the 3.2 epic JC designs in her inventory.
![image](https://user-images.githubusercontent.com/7052334/222809618-37ead141-af41-4b9b-adb0-69fb4591dced.png)

### Expected Blizzlike Behaviour

She's only supposed to have the [Jeweler's Kit] and [Simple Grinder] for sale.
Only Timothy Jones in Dalaran should have the lvl 80 epic JC designs in stock.

### Source

Kirembri on Wowhead:
https://www.wowhead.com/wotlk/npc=33637/kirembri-silvermane#sells
Timothy Jones on Wowhead:
https://www.wowhead.com/wotlk/npc=28701/timothy-jones#sells
List of vendors that accept the Dalaran JC token:
https://wowpedia.fandom.com/wiki/Dalaran_Jewelcrafter%27s_Token

### Steps to reproduce the problem

1. Teleport to Kirembri Silvermane, id 33637
2. Browse her inventory

### Extra Notes

Is possible the Aldor JC trainer Nemiha (id 33680) is also selling the wrath JC designs, but I'm not able to check since I'm hated with Aldor.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/73e289ad95c551b9ba4822c6149bcc98c3422665

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi anhility. Thanks for the report. You are correct, they should not be selling these patterns.

**Comment by Kitzunu** [comment]
https://wowpedia.fandom.com/wiki/Kirembri_Silvermane
[Hotfix](http://blue.mmo-champion.com/23/19110152523-recent-ingame-fixes--august-2009.html) (2009-08-05): Epic gem recipes are now available from the following vendors in [Shattrath](https://wowpedia.fandom.com/wiki/Shattrath):
Kirembri Silvermane (Scryer)
[Nemiha](https://wowpedia.fandom.com/wiki/Nemiha) (Aldor)
[Inessera](https://wowpedia.fandom.com/wiki/Inessera) (Aldor)

08-05 is 1 day after patch 3.2 (08-04)

Hotfix patches:
https://wowpedia.fandom.com/wiki/Hotfixes/2009_Archive#August_5

**Comment by anhility** [comment]
> https://wowpedia.fandom.com/wiki/Kirembri_Silvermane [Hotfix](http://blue.mmo-champion.com/23/19110152523-recent-ingame-fixes--august-2009.html) (2009-08-05): Epic gem recipes are now available from the following vendors in [Shattrath](https://wowpedia.fandom.com/wiki/Shattrath): Kirembri Silvermane (Scryer) [Nemiha](https://wowpedia.fandom.com/wiki/Nemiha) (Aldor) [Inessera](https://wowpedia.fandom.com/wiki/Inessera) (Aldor)
> 
> 08-05 is 1 day after patch 3.2 (08-04)
> 
> Hotfix patches: https://wowpedia.fandom.com/wiki/Hotfixes/2009_Archive#August_5

Guess my bad for not properly reading patch notes.

**Comment by Stump876** [comment]
It happens, no worries. I missed it also. It can be added to the progression module. TBH that makes no sense to me why they would sell them, but whatever.

> > https://wowpedia.fandom.com/wiki/Kirembri_Silvermane [Hotfix](http://blue.mmo-champion.com/23/19110152523-recent-ingame-fixes--august-2009.html) (2009-08-05): Epic gem recipes are now available from the following vendors in [Shattrath](https://wowpedia.fandom.com/wiki/Shattrath): Kirembri Silvermane (Scryer) [Nemiha](https://wowpedia.fandom.com/wiki/Nemiha) (Aldor) [Inessera](https://wowpedia.fandom.com/wiki/Inessera) (Aldor)
> > 08-05 is 1 day after patch 3.2 (08-04)
> > Hotfix patches: https://wowpedia.fandom.com/wiki/Hotfixes/2009_Archive#August_5
> 
> Guess my bad for not properly reading patch notes.
