### ISSUE TITLE
When swapping specs some skills from talents are down ranked on that spec page

### ISSUE THREAD

**Issue by slicplaya** [chromiecraft/chromiecraft#5139]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

When swapping from a MM tree on my hunter to another MM tree, My Aimed Shot was down ranked on the swapped spec. Upon swapping back to the other spec, the higher rank was relearned. In this case specifically, Aimed shot rank 6 and 7.

### Expected Blizzlike Behaviour

Learned spells even from talents should stay at the highest rank learned regardless of spec.

### Source

![Capture](https://user-images.githubusercontent.com/6567001/223980558-743847d7-99d0-4dcf-b3ce-8bc9819c464d.JPG)

### Steps to reproduce the problem

1. Make a hunter. Spec into Aimed Shot.
2. learn Dual Talent Specialization.
3. Swap specs and learn Aimed Shot in the second spec,
4. Go learn rank ups in one spec, and swap to another.
5. Notice ranks are unlearned.
6. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0200a288cd89034a8b491253006a0b0055178deb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
I'm testing this with this revision dd647da913ef 2023-09-04 and I can't reproduce it. I made dual spec, each one with MM and Aimed Shot and, when I swap spec, this ability remains at the same rank
