### ISSUE TITLE
[Talent] Druid: Furor & Feral Instinct

### ISSUE THREAD

**Issue by elkdarkshire** [chromiecraft/chromiecraft#514]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Druid Talent "Furor" doesn't apply its Stamina Bonus while in Bear Form.

The Druid Talent "Feral Instinct"'s Capstone Bonus doesn't work, it doesn't reduce the timer of Enrage by 1 Second.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Furor should apply the % to the Stamina Bonus during Bear Form.

Feral Instinct's Capstone Bonus (3/3) should lower Enrage's Cooldown by 1 Second each time Swime deals damage.

##### STEPS TO REPRODUCE THE PROBLEM:

1. ****
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by LalaWTF** [comment]
FAKE

FUROR :
Gives you 40% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form, and you keep up to 40 of your Energy when you shapeshift into Cat Form, and increases your total Intellect while in Moonkin form by 4%. - no stam bonus for bear 

Feral Instinct's :  
Increases the damage done by your Swipe ability by 10% / 20% / 30% and reduces the chance enemies have to detect you while Prowling. - no reduce timers..
