### ISSUE TITLE
[Potentially] Darkmoon Card: Vengeance not proccing on blocks

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5147]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Darkmoon Card: Vengeance proc rates seems a bit low

### Expected Blizzlike Behaviour

it should proc on blocks, but not parrys, dodges or misses - i think it might not be proccing on blocks currently
further, even non-damaging auras should be able to trigger it (e.g. Auchindoun first boss)

### Source

https://www.wowhead.com/tbc/item=31858/darkmoon-card-vengeance#comments:id=100271
https://www.wowhead.com/tbc/item=31858/darkmoon-card-vengeance#comments:id=106737

### Steps to reproduce the problem

a bit more tricky - i am also not a 100% sure if it is actually buggy because it is difficult to test.
but, there might be some auras to check for the second part,
and maybe some ways of artifically generating 100% block chance to verify if it is proccing on blocks or not on the PTR.

### Extra Notes

https://www.wowhead.com/tbc/item=31858/darkmoon-card-vengeance

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0200a288cd89034a8b491253006a0b0055178deb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
I have a question, is it supposed to be triggered if you absorb damage, since you technically don't "take" the damage? Bunch of comments mentioning it being good on priest, but nothing in regards to if it procs while absorbing damage,

**Comment by avarishd** [comment]
Can confirm, thanks
