### ISSUE TITLE
Bogblossoms from "The Ward of the Wakening" quest do not explode

### ISSUE THREAD

**Issue by quigiboo** [chromiecraft/chromiecraft#5163]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

The Blossoms either give you a short debuff with no effect or give the item. I picked well over 30 blossoms by destroying them and only encountered these two outcomes
![WoWScrnShot_031223_111111](https://user-images.githubusercontent.com/114075548/224540864-6078fb8f-9c77-4eb1-b107-225e1484698d.jpg)

### Expected Blizzlike Behaviour

when the bogbossom explodes it should throw the druid back potentially off the mushroom, requiring them to quickly engage flight form to survive.

### Source

https://www.wowhead.com/tbc/item=31950/bogblossom#comments
![image](https://user-images.githubusercontent.com/114075548/224540947-f4cd5ec1-5a13-40b7-bf51-4b018e77b1e2.png)
https://www.youtube.com/watch?v=dpHKfKeOn-4&t=7s

### Steps to reproduce the problem

accept quest "the ward of wakening" as a druid with 280% flying
pick bogblossoms on top of mushrooms in zangermarsh until one "explodes"
observe no knockback.

### Extra Notes

I wasn't knocked back in both flight form and regular form
![WoWScrnShot_031223_111657](https://user-images.githubusercontent.com/114075548/224541082-72560ffc-1519-4694-863e-920593def69e.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03d47897ece3e0a615aac05222d9fbd98b33717d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, missing knocback and despawn. Thanks for the report.
