### ISSUE TITLE
[CoT2] Rifts can spawn without Keepers

### ISSUE THREAD

**Issue by CptMarkka** [chromiecraft/chromiecraft#5173]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Sometimes, under certain circumstances, a rift can spawn without a Rift Keeper or a Rift Lord present.

### Expected Blizzlike Behaviour

Rifts should never spawn without an attached Keeper or Lord.

### Source

https://wowwiki-archive.fandom.com/wiki/Opening_the_Dark_Portal#The_Opening_of_the_Dark_Portal

> Each of the first five waves of the event consists of one elite — either a melee-class [Rift Lord](https://wowwiki-archive.fandom.com/wiki/Rift_Lord) or caster-class [Rift Keeper](https://wowwiki-archive.fandom.com/wiki/Rift_Keeper) — that is tethered to the portal, and a stream of non-elite mobs.

### Steps to reproduce the problem

1. Someone starts the event while rest of the group is pulling and clearing trash, causing an unexpected wipe.
2. Recover, but start the first portal later than normal.
3. Progress through the event as normal until the first boss spawns.
4. While engaged with the boss, the 7th rift spawned without a Keeper or a Lord present.
5. Timing of all subsequent portals gets out of whack.

### Extra Notes

This strange bug caused the portals 7-12 to spawn extremely slowly, but the situation returned to almost normal after the death of the second boss when a new portal spawned in the place of the one orphan portal.

The orphan portal continues to spawn a stream of non-elite mobs for as long as it's active, with no way to shut it down.

Even after that, the timing of all subsequent portals was strange, with sometimes two portals spawning at the same time.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03d47897ece3e0a615aac05222d9fbd98b33717d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I tried this dungeon too many times in the last days. This bug never happened.
There are two possibilities:
It is a rare bug or this issue has been fixed.

Thank you for your report anyway.
