### ISSUE TITLE
Nighteye Panther trinket

### ISSUE THREAD

**Issue by Licse** [chromiecraft/chromiecraft#5174]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Dosn't give improved stealth, as it might changed later phase in original.

### Expected Blizzlike Behaviour

Should increase the effettive stealth level by 1.

### Source

https://www.wowhead.com/tbc/item=24128/figurine-nightseye-panther

### Steps to reproduce the problem

Need revered with cenarion expedition to buy the recipes.
Need jc at minimum level of 370 to craft and wear.
Add to stats "increase your effettive level of stealth by 1"

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03d47897ece3e0a615aac05222d9fbd98b33717d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Hihilist** [comment]
Found the patch when it was changed https://wowwiki-archive.fandom.com/wiki/Patch_3.1.2_(undocumented_changes)
"Trinkets like [[Figurine - Shadowsong Panther]](https://wowwiki-archive.fandom.com/wiki/Figurine_-_Shadowsong_Panther) will no longer offer additional stealth level. The [[Figurine - Black Pearl Panther]](https://wowwiki-archive.fandom.com/wiki/Figurine_-_Black_Pearl_Panther) is an exception."

**Comment by avarishd** [comment]
Can confirm, patch 3.1.2 did in fact remove stealth levels from most trinkets, except Black Pearl Panther, which works fine.
Which can additionally be confirmed by wowhead's wotlk db.
https://wowpedia.fandom.com/wiki/Patch_3.1.2_(undocumented_changes)
