### ISSUE TITLE
Fleeing mobs affected by chill effect do not behave correctly, 100% & 200% run speed. Must be reapplied during flight.

### ISSUE THREAD

**Issue by Fingon93** [chromiecraft/chromiecraft#518]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Mobs affected by the chill effect, be it from the frost armor or frostbolt, (or any other chill) when fleeing are not slowed down.

Sometimes they even clip trough the air. (Only witnessed on miners in the Azurelode mine in Hillsbrad Foothills)

This has happened throughout my leveling 1-27 to almost every mob that flees. When a chill effect is applied when they are currently fleeing it usually slowss them correctly.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Fleeing mobs that have the chill effect applied should be slowed down according to the talents taken. And nod flee at 100% or 200$ speed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Cast frotbolt or be hit closely before the mob starts fleeing.
2. The mob will flee at 100% and 200% speed even though it is shown that the chill effect is still applied.
3. Cast frostbolt during the flight, the mob should be slowed down.
4.

##### EXTRA NOTES:

I was accompanied by IGN: Anthor, he gave me his permission to post his IGN here.

It is extremely prevalent in Azurelode mine but it happened throughout my gameplay with every fleeing mob.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
Seems like a duplicate from https://github.com/chromiecraft/chromiecraft/issues/183
