### ISSUE TITLE
Sal'salabim NPC is not positioned correctly.

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5186]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Sal'salabim is positioned at the entrance, thus not positioned correctly

### Expected Blizzlike Behaviour

NPC has a specific position/location within the House as shown below (deep inside to the right little corner)

### Source

https://wowpedia.fandom.com/wiki/Sal%27salabim

https://www.youtube.com/watch?v=Xix6-CvTUbM

### Steps to reproduce the problem

Teleport to NPC
Check if he is still positioned at the entrance
End

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Hihilist** [comment]
Yesterday it was at the back of the inn when I was doing the related quest.

**Comment by Paradigmxd** [comment]
You can kite him, that is all right - but he should RESET properly. Perhaps the issue is indeed this!

**Comment by Paradigmxd** [comment]
@avarishd just saw this NPC next to the Flight Master???? What's wrong? It was fixed just 2 hours ago?
@Gultask

**Comment by Paradigmxd** [comment]
![WoWScrnShot_042423_212215](https://user-images.githubusercontent.com/100602999/234107911-a989d49a-2dc8-4ab8-b617-f93df341436d.jpg)

**Comment by Paradigmxd** [comment]
Can someone guide me through why this can break like that? I don't really understand. I feel like WOTLK servers always have these issues more often than not - I draw my conclusion from Stormforge's TBC realm (Wolfenstein's core TBC) they never have such issues - is that related to the WOTLK core itself??

**Comment by Gultask** [comment]
Perhaps it's never resetting like Hihilist said. There's a PR open that could address this

> I feel like WOTLK servers always have these issues more often than not

See that's interesting. WotLK servers often use TrinityCore as a base, while I imagine TBC uses Mangos as a base. Those are 2 different cores. And both handle things differently.
In this situation it's because the script for Sal'salabim is very old and incomplete. The open PR should address it.

**Comment by avarishd** [comment]
"evade move = Leaving combat and speaking with the npc again, which causes them to move their home pos, until a server restart."

PR also changes it so they become friendly only when they fully reset.

**Comment by Paradigmxd** [comment]
Guys - this is still broken????? what the actual F is going on here :D 

Did I miss a server update or something? So many NPCs are literary facing the wrong way or MISPLACED??

**Comment by Paradigmxd** [comment]
![WoWScrnShot_052423_192426](https://github.com/chromiecraft/chromiecraft/assets/100602999/2fa7c014-3430-466f-b3a1-1b57d2beef80)

**Comment by Gultask** [comment]
Hey, @Paradigmxd, the update containing the commit should've gone through this morning.
