### ISSUE TITLE
Quest "No Mere Dream" Bug ("blizzlike")

### ISSUE THREAD

**Issue by QuantaCosta** [chromiecraft/chromiecraft#5189]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

If you accept the quest "No Mere Dream" from quest giver "Clintar Dreamwalker" while being in shapeshift form (occured in cat form) you will not get properly transferred to the Emerald Dream. This is required in order to be able to see and escort Clintar's Avatar (an untargetable pet cat) to complete the quest. 

### Expected Blizzlike Behaviour

Player should get transferred into the Emerald Dream State regardless if in shapeshift form or not.

### Source

https://wowpedia.fandom.com/wiki/No_Mere_Dream
> Content Number 6: Notes

https://www.wowhead.com/tbc/quest=10965/no-mere-dream
> Comment by [99328] (Patch 2.4.1)
> Comment by [Xioo] (Patch Classic TBC)

### Steps to reproduce the problem

.teleport npc 22834 (Clintar Dreamwalker)
Accept quest "No Mere Dream" while being in Cat/Bear/Moonkin shapeshift form.
*Optional: Check for visual effects on screen after accepting quest to confirm correct transfer into Emerald Dream State.
Check if cat (Siamese Cat pet model) spawns/ is visible.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Scapulla** [comment]
For me, cat didnt show up for a couple tries. When it appeared, it ran to the first room, then on to the second, then disappeared and the quest didnt get completed.

**Comment by Rorschach91** [comment]
These problems have already been notified on Azeroth Core Git Hub some days before this report. [https://github.com/azerothcore/azerothcore-wotlk/issues/15357](url)

I just tested again the issue and i can confirm that the bugs are not solved yet.

Thank you for your contribution guys.
