### ISSUE TITLE
Enraged Water Spirit lacks scripted Abilities

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5193]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Enraged water spirit has no Water Bolt scripted

### Expected Blizzlike Behaviour

Water Bolt should be part of his ability

### Source

https://www.wowhead.com/wotlk/npc=21059/enraged-water-spirit#comments

### Steps to reproduce the problem

1. teleport to Enraged Water Spirit in ShadowmoonValley NPC ID 21059
2. Engage and observe
3. End

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
Perhaps do you mean [Stormbolt](https://www.wowhead.com/wotlk/spell=38032/stormbolt)? Because in this case, it seems that the spell works fine (the npc casts it on first aggro, then turns into melee and periodically casts again)

**Comment by Paradigmxd** [comment]
Yes, apologies it's stormbolt. When I made that ticket they had zero cast sequence. In TBC classic they would cast that within the 10 seconds they are alive.

When I leveled with a tank paladin and pulled 5 of them none of them did that, it was only mele.

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/16571
