### ISSUE TITLE
Jademir Oracle has a few problems with it.

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#5212]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

The Jademir Oracle has several bugs with it. First off, after being looted it despawns about 1.5 sec afterwards, preventing you from having enough time to skin it unless you are *VERY* quick. 

Next, their leash seems to be completely random, not even tied to distance. While fighting one on my priest, it just randomly ran back to where I had agroed it from, just out of nowhere. I was standing perfectly still hard casting on it then it just evaded and ran back across the lake. 

Finally, the drop chance for Fragment of the Nightmare's Corruption is not 100% like it is supposed to be in wrath, unlike the one from Ashenvale which I did get on my first kill.

### Expected Blizzlike Behaviour

The mob is supposed to have a standard despawn time for it's corpse like most mobs, giving you plenty of time to skin them.

The mob should not evade and leash back while you are attacking it standing still, very few mobs in the game have that effect and the ones that do wont be standing still attacking you, then randomly leash back to their agro point. I have never seen that happen before fighting any mob.

The quest items for The Nightmare's Corruption should be 100% as of 3.0.

### Source

https://www.wowhead.com/wotlk/quest=8735/the-nightmares-corruption

https://www.wowhead.com/wotlk/npc=5317/jademir-oracle#comments;mode:normal (wowhead comments are always incorrect for quest items as it counts all kills made prior to an increase in the drop chance, at this point would be 3.0 as well as all kills made by players without the quest to allow the items to drop. This means the listed drop % for the mob is incorrect.) You wont find any comments here stating that these things have weird leashing problems or that the bodies despawn too quickly. 

### Steps to reproduce the problem

Obtain the quest The Nightmare's Corruption
Kill Jademir Oracle and loot it to watch it despawn right after
Kite one across the lake using ranged attacks, then stop attacking for about 10sec, letting it hit you for that time. It might reset and run back on it's own without any movement needed on either your or it's part.

### Extra Notes

I was not able to kill the Jademir Boughguard as he spams his knock back, thus making it impossible to stay in combat with him, but after killing the Jademir Tree Warder I noticed it also did not drop the quest item, either. All 3 of the mobs should have a 100% chance to drop it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Seems that these problems have already been fixed.

Jademir Oracle npcs don't despawn early. 
Leash and Evade seems to be good.
Fragment of the Nightmare's Corruption seems that have 100% drop rate now.

Thank you for your report. If you discover other bugs feel free to report them.
