### ISSUE TITLE
Wrong critrate value displayed when equiping weapons with lower weapon skill after unequiping weapons with max wep skill

### ISSUE THREAD

**Issue by Zhaamon** [chromiecraft/chromiecraft#5216]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Whenever I'm using either one or more Blade of Unquenched Thirst my crit rate gets lower after Elemental Devastation ends.

I tested the following cenarios:
- no gear, only 2x Fist of Reckoning -> works fine
- no gear, 2x Blade of unquenched thirst -> crit seems to go 4% lower than what it started at, both during and after the proc
- no gear, 1x Blade of unquenched thirst + 1x Fist of Reckoning -> same as above

Screenshots:

No gear whatsoever (10.35% crit)
![image](https://user-images.githubusercontent.com/63854803/226369122-fe07a9eb-74f8-408c-97b9-d1b9bb16fae5.png)

1x Blade of unquenched thirst + 1x Fist of reckoning  before Elemental devastation (11.08% crit):
![image](https://user-images.githubusercontent.com/63854803/226369513-4a623b7e-815d-48ab-984f-d76c2129da71.png)

1x Blade of unquenched thirst + 1x Fist of reckoning  during Elemental devastation (16.40% crit):
![image](https://user-images.githubusercontent.com/63854803/226369806-86a89f7b-c28b-4202-96b8-799719dee259.png)

1x Blade of unquenched thirst + 1x Fist of reckoning  after Elemental devastation (7.40% crit):
![image](https://user-images.githubusercontent.com/63854803/226369977-3ac73839-38cc-4410-83f2-3b0e94cc9746.png)

weapon skills in case it's relevant
![image](https://user-images.githubusercontent.com/63854803/226370291-3857fbf0-6512-4d85-a04f-4bc7a7338851.png)

### Expected Blizzlike Behaviour

Should be working for daggers as it does for maces, +9 during proc, -9 after proc ends

### Source

Source: gameplay on chromiecraft

### Steps to reproduce the problem

1. Create a lvl 70 Draenei Shamman, spec to enhancement untill the end and get 8 points in Elemental to get 3/3 Elemental Devastation
2. Equip 2x Blade of Unquenched thirst, enchant with +40 spellpower
3. Hit a target dummy with spells until Elemental Devastation procs
4. Compare crit% on melee stats before the proc and after it ends, the numbers don't match

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Zhaamon** [comment]
I upped my dagger weapon skill and it seems to fix the issue, i'm really sorry for the inconvenience.
It seems its just some kind of visual bug on crit with lower weapon skills and Elemental Devastation is probably triggering an update on the visual crit rate, which means the lower numbers are actually accurate.

**Comment by HasieEST** [comment]
'The base chance for your attack to be a critical strike is: 5% - (Defense Skill - Weapon Skill)*0.04%'

[[](url)](https://wowwiki-archive.fandom.com/wiki/Weapon_skill) 

What you see  in your tooltip is your current meele crit, that is calculated by previously stated formula (Defense skill = max value of char level). If you have not maxed your wep skill, then your critical strike will naturally be lower. (1.32% from weapon skill + other critical strike adding modifiers.
