### ISSUE TITLE
[Quest] Galen's Escape

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#522]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Galen Goodward does not fight his way nor does he get attacked during his escort quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be attacked by nearby ennemies.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get the quest and let him walk into mobs.

##### EXTRA NOTES:

Quest: https://wowgaming.altervista.org/aowow/?quest=1393
NPC to escort: https://wowgaming.altervista.org/aowow/?npc=5391

Here are some glorious wowhead comments... :)

_Worst escort quest ever, this guy went right into the encampment, aggroed 4-5 mobs and died... all in like 30 seconds._

_Worst escort ever, no matter what you do he WILL find some way to commit suicide._

_If you release him he runs headlong into any and every mob nearby, and will die in seconds._

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment]
https://www.youtube.com/watch?v=JShd-CP_Ggw - video of current behavior
