### ISSUE TITLE
Logout out flightpath now character stuck

### ISSUE THREAD

**Issue by Enghazi** [chromiecraft/chromiecraft#5221]
I logged out while on the flight path from Orgrimmar to Taranis.  My character screen shows me in Durotar.  When I log in, I am ground mounted on the Wyvern, in Taranis, I can walk slowly around and cannot see the NPC's nor any players.  Reloading does not solve the issue.  Logging out and back in does not solve the issue.  Cannot unmount, etc. 

Login screen later showed me in The Barrens.
![Screenshot (8)](https://user-images.githubusercontent.com/112347691/226426140-2f7388d4-79cd-478c-8a08-bd9c82521f8a.png)
![Screenshot (9)](https://user-images.githubusercontent.com/112347691/226426150-b970b74a-5079-48c8-8d75-af3031f45621.png)
![Screenshot (10)](https://user-images.githubusercontent.com/112347691/226426168-b3d7c03c-c454-4817-bb2b-0898b379586d.png)

After waiting the duration of the flight path, I was eventually given control of my character.

Spell bar was glitched and required a reload. 

![Screenshot (4)](https://user-images.githubusercontent.com/112347691/226420901-92e3bd5e-52f6-4ea6-aff4-bb9fd0ec76d9.png)
![Screenshot (5)](https://user-images.githubusercontent.com/112347691/226420917-fd3a12a0-a39e-44c7-95a6-51dcda7b870c.png)
![Screenshot (6)](https://user-images.githubusercontent.com/112347691/226420948-480c00cb-b6ba-40fa-a608-477b0da4d529.png)
![Screenshot (7)](https://user-images.githubusercontent.com/112347691/226420972-c72e953e-96dd-4488-98a0-9d1c09198f9e.png)

**Comment by BeefSteaker** [comment]
Rare client bug due to lag. unable to replicate
