### ISSUE TITLE
Karazhan "Ghostly philanthropist" Doesnt drop large amount of gold it should.

### ISSUE THREAD

**Issue by quigiboo** [chromiecraft/chromiecraft#5223]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

The mob drops approximately 25 silver.
https://youtu.be/jicof0WoZrY

### Expected Blizzlike Behaviour

notably the mob should drop around 12g, around 1g 20s per raid member
https://www.wowhead.com/tbc/npc=16470/ghostly-philanthropist#comments

Difficult to see in this video from tbc classic as it is sped up at this point, but if you pause at 22:32 you can see he receives over a gold per philanthropist kill
https://youtube.com/watch?v=Wu-JKPiqvdI&feature=shares&t=1352
![image](https://user-images.githubusercontent.com/114075548/226469412-d10077a4-85eb-4e1d-87a1-780bb1ef1026.png)

### Source

https://www.wowhead.com/tbc/npc=16470/ghostly-philanthropist#comments
https://youtube.com/watch?v=Wu-JKPiqvdI&feature=shares&t=1352

### Steps to reproduce the problem

go to karazhan
kill moroes to access opera
kill opera
kill a Ghostly philanthropist and loot it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by NinesCC** [comment]
I can confirm we have seen this behavior from the Ghostly philanthropists, not dropping gold, in at least 3 PTR Kara runs. I can find footage of said runs if needed.

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
