### ISSUE TITLE
Draconic for Dummies  "Chapter V" in Stormwind library is currently MiA

### ISSUE THREAD

**Issue by EdyGlockenspiel** [chromiecraft/chromiecraft#5225]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

The book Draconic for Dummies is missing from the Stormwind library. It should be on the pillar on the left side of the room as you enter, but it's not.

### Expected Blizzlike Behaviour

The book is there whether you are alive or dead, horde or alliance, with or without the related quest. 

### Source

https://www.wowhead.com/wotlk/item=21107/draconic-for-dummies#comments In the SSs here you can see exactly where it is supposed to be, but I am there and it is not. https://cdn.discordapp.com/attachments/788799234207252540/1087538390687305818/image.png Here is a SS I took from Blizzard's Wrath Classic PTR server (free to DL and play) where you can clearly see my template character that has no quests, interacting with the book. 

https://cdn.discordapp.com/attachments/788799234207252540/1087538663375769711/image.png Here is a SS of my CC character at the exact same spot with no book present. 

### Steps to reproduce the problem

Go to the Stormwind library at about 75 29 coords and see there is no book.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by EdyGlockenspiel** [comment]
The book it is across from is The Kaldorei and the Well of Eternity on the pillar. https://cdn.discordapp.com/attachments/1083645614698532904/1087553684864520192/image.png

**Comment by EdyGlockenspiel** [comment]
So I found it. It's in the wrong place which is why I thought it was missing. It's on the other side of the room, on the wrong side of the pillar. But it's here. https://cdn.discordapp.com/attachments/788799234207252540/1087560371780472842/image.png

**Comment by heyitsbench** [comment]
Thanks for the report! :heart:
