### ISSUE TITLE
[Flight Path] Shattered Sun Staging Area in Quel'Danas available from Ironforge on Live CC Server

### ISSUE THREAD

**Issue by dieing4me** [chromiecraft/chromiecraft#5226]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Flight path to the Shattered Sun Stagin Area of Quel'Danas is available to take from Ironforge as a level 70 with 300 flight

![Wow_xJn6PFt3Y4](https://user-images.githubusercontent.com/29512498/226496611-31b4b96b-2736-4f90-83d4-7c700e849cca.png)

### Expected Blizzlike Behaviour

Currently it is supposed to be disabled as progression has not hit the Shattered Sun milestone yet.
![image](https://user-images.githubusercontent.com/29512498/226496968-c56bad87-af38-44f0-b9fc-836eed790cec.png)

### Source

https://www.chromiecraft.com/en/progression/

### Steps to reproduce the problem

Head to the Ironforge gryphon master as a level 70 (possibly with TBC swift riding)
Confirm that the flight path is available to take.

### Extra Notes

I did not perform due diligence and take the flight path because as previously stated by one of the moderator staff, taking the FP would disconnect you and consistently do so until a GM unstuck the character.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Apathyxia** [comment]
You actually are not able to fly there - when you reach the border of the Isle, you will get teleported to Booty Bay. The Isle of Quel'Danas flight path is automatically unlocked upon reaching level 65.

**Comment by Stump876** [comment]
Hi dieing4me. Thanks for the report. This is known. Apathyxia pretty much covered it. It is automatically unlocked by the client once you reach a certain level. Nothing we can do about that. So we made it so people will be ported if they try to enter the zone.
