### ISSUE TITLE
Constant Combat bug when fighting NPCs in The SCRAP FIELD 

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5237]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Constant Combat Bug when fighting NPCs in the Scrap Field

### Expected Blizzlike Behaviour

There is no such thing as constant Combat bug

### Source

dont know what to say here 

### Steps to reproduce the problem

1. Fight NPCs at the Scrap Field in Netherstorms
2. can you leave combat whilst in the field?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ElmoMcG** [comment]
I can confirm this issue in the Scrap Field area of Netherstorm. You do not lose health, but you stay in combat: there does not appear to be any invisible mobs attacking you. The distance travelled to leave combat seems much farther than fleeing other mobs. 

The two affected quests are:
- In a Scrap with the Legion - https://wowgaming.altervista.org/aowow/?quest=10232
- One Demon's Trash - https://wowgaming.altervista.org/aowow/?quest=10234 (collecting the quest objects does not cause this combat issue)

Mobs that cause this issue:
- Gan'arg Engineer - https://wowgaming.altervista.org/aowow/?npc=16948
- Mo'arg Doomsmith - https://wowgaming.altervista.org/aowow/?npc=16944

Mob in the zone that does not cause this issue:
- Doomclaw - https://wowgaming.altervista.org/aowow/?npc=19738

**Comment by alecsci** [comment]
Hi @Paradigmxd thanks for your report, also @ElmoMcG for giving out more details. 
I tried to kill (with skills, no gm powers) and leash the Gan'arg Engineer, Mo'arg Doomsmith, Doomclaw on this [version](https://github.com/azerothcore/azerothcore-wotlk/commit/bf18b9bdfb26fd94cd4dfbd6a911ebae5db98569)
and couldn't reproduce it.
If you still encounter it, please add a comment and wewill reopen it and test it on live server.
