### ISSUE TITLE
Can pickpocket Head of Ortor of Murkblood from mob

### ISSUE THREAD

**Issue by manacute** [chromiecraft/chromiecraft#5239]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

Currently, player is able to pick pocket quest item Head of Ortor of Murkblood from associated mob, Ortor of Murkblood

### Expected Blizzlike Behaviour

Player should not be able to pickpocket Head of Ortor of Murkblood

### Source

https://www.wowhead.com/wotlk/item=24543/head-of-ortor-of-murkblood#dropped-by
https://www.wowhead.com/wotlk/npc=18204/ortor-of-murkblood#pickpocketing

Head of Ortor of Murkblood is not in list of pickpocketing items

### Steps to reproduce the problem

1. Get Murkblood Leaders from Farseer Margadesh (https://www.wowhead.com/tbc/quest=9867/murkblood-leaders)
2. Go to Ortor of Murkblood in Sunspring Post (https://www.wowhead.com/tbc/npc=18204/ortor-of-murkblood)
3. Pickpocket Ortor

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
https://www.wowhead.com/wotlk/item=24543/head-of-ortor-of-murkblood#comments:id=1055102

> By 584306 (1,071 – 2·12) on 2010/06/09 (Patch 3.3.3)		
There's funny fact. His head can be pickpocketed :D

It exists in both Trinity and Mangos.

**Comment by neifion-00000000** [comment]
I'mma open this again, because this comment is not reliable

here are a few other things this guy has said:
![image](https://user-images.githubusercontent.com/91289495/232941436-e0745b48-d966-4b2f-9b74-c3511acbfbdb.png)

![image](https://user-images.githubusercontent.com/91289495/232941457-c64d7503-c9bb-40b5-a782-fd2c7af036b6.png)
(note the date on that comment)
