### ISSUE TITLE
First Melee attack/ability does not crit an enemy player when he is sitting down

### ISSUE THREAD

**Issue by fivepointfiveb** [chromiecraft/chromiecraft#524]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When you use a melee ability on an enemy player that is sitting it does not guarantee a critical strike.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you use a melee ability (something like backstab or shred) or an melee autoattack on a target that is sitting down it should give that one melee strike a 100% crit chance.

##### STEPS TO REPRODUCE THE PROBLEM:

best way to reproduce would be dueling i guess
1. Duel another player
2. Tell him to sit down. 
3. Use any melee ability on that target
4. proceed to not get a crit with that ability

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by ProGameDesigns** [comment]
There is a check for this at unit.cpp 2389.
If we are running through this code path, my first thought would be that maybe the sit state is not getting set on player input. 

Not sure if we even run this function though, just installed the database and still looking around.

**Comment by FrancescoBorzi** [comment]
@ProGameDesigns thanks for your input, however it's better to keep the technical discussion on the AC side, which for this issue is:

https://github.com/azerothcore/azerothcore-wotlk/issues/5635
