### ISSUE TITLE
Canonical Questline Manaforge Ara Scryers/Aldor has number of issues and is broken

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5240]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Shutting down Manaforge Ara has number of issues.

1) Overseer Azarad Is not patrolling
2) Technicians spawn without engaging and no animation of casting spell to shut-down the manaforge
3) The moment technicians spawn and appear next to the manaforge a text is displayed 'Interrupted Manaforge Shutdown' this is incorrect and should not occur unless they have successfully channeled the spell for a few seconds
4) The quest should be marked as completed once you kill the FInal Elite Overseer marking the Final Wave

### Expected Blizzlike Behaviour

1. Overseer Azarad patrolls in a cirlce inside the whole area
2. Technicians spawn and run to cast the shutting down channelling spell unless close to people - then they should engage
3. Technicians going near the manaforge should not immediatelly display 'Failed - shutting down of manaforge aborted' text -> this should only be displayed if they successfully stay alive for some time while channeling their spell to shut down
4. Once the Elite giant in the final wave is completed the Manaforge Shutdown should be completed 

### Source

TBC classic https://www.youtube.com/watch?v=KCC4gyQyDuE

PTR TBC classic https://www.youtube.com/watch?v=-hHoIWFAy7w

### Steps to reproduce the problem

Start quest
Observe all points mentioned

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by lord-spirit** [comment]
Confirm that this also happens for Shutting Down Manaforge Duro. Am unable to complete quest because technicians are immediately aborting shutdown before I can even engage with them.

**Comment by cachocarne** [comment]
Confirmed, still happening on all Manaforges (July 3, 2023)

**Comment by Rorschach91** [comment]
Problems related by Manaforges are already known by the staff. There are other reports in AC.

Thank you for your contribution.
