### ISSUE TITLE
Recipe for Destruction QUEST - Voidshriekers inappropriately cast all school of magic damage reductions after each attack

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5245]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Voidshriekers will cast the 75% reduction shield from each successful school of magic if the player uses it, thus the voidshrieker can have al types of magic reductions on him at the same time

### Expected Blizzlike Behaviour

Voidshrieker will ONLY CAST THE 75% REDUCTION SHIELD TO THE FIRST AND ONLY FIRST ATTACK THAT DAMAGES HIM

Example: Attack with Smite -> Trigger Holy shield 75% reduction damage from that type of school of magic

How it works on CC - > Attack with Smite - activates holy shield, Frost shock ,activates Frost shield etc etc resulting in all schools of magic shields AT THE SAME TIME 

### Source

https://www.wowhead.com/tbc/npc=18870/voidshrieker#comments

CHECK THE FIRST COMMENT 2007 thanks

### Steps to reproduce the problem

1. Use all types of magic on Voidshrieker and observes how he casts all types of shield on him at the SAME TIME
2. end

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ff0c607ecec81e9793d521cc1adfe3883e20ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
@Paradigmxd, thanks for your report !
I used this [version](https://github.com/azerothcore/azerothcore-wotlk/commit/bf18b9bdfb26fd94cd4dfbd6a911ebae5db98569)
with a shaman casting fire/frost/nature.
The creature only adds resistance for the first spell.
I think it was fixed here: https://github.com/azerothcore/azerothcore-wotlk/issues/18865
