### ISSUE TITLE
Ruuan Weald Basilisk and all Blade's Edge Basilisks MISSING 'PLAY DEAD' ability.....

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5251]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

All basilisks dont have scripting...They dont play dead

### Expected Blizzlike Behaviour

All basilisks in Blade's Edge play dead and then charge you - the reason why it made them so annoying.

### Source

https://www.wowhead.com/wotlk/npc=20987/ruuan-weald-basilisk#comments

Subject: "Re: Ruuan Weald Basilisk"
They play dead then charge you after a while so watch out

### Steps to reproduce the problem

1. teleport to Ruuan Weald
2. Fight a Ruuan Weald Basilisk
3. End 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/989584b199ee5e4dcc57c30796123275f58aa096

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Paradigmxd** [comment]
IMPORTANT : BASILISKS IN ZANGARMASH ALSO HAVE THIS ABILITY - PLEASE ADD TO THE FIX

**Comment by avarishd** [comment]
Hey, thanks for the report.
Can confirm that all of the mobs that cast [Threshalisk Charge](https://www.wowhead.com/wotlk/spell=35385/threshalisk-charge) are missing Feign Death event.
