### ISSUE TITLE
[Mechanar] Nethermancer Sepethrea Raging Flames Immunities

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5257]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

https://www.wowhead.com/npc=19221/nethermancer-sepethrea summons Raging Flames. these are affected by cc effects like taunt, thunderstorm. 

### Expected Blizzlike Behaviour

the raging flames should be immune to any kind of crowd control effect.

### Source

https://wowpedia.fandom.com/wiki/Nethermancer_Sepethrea
> When the fight is initiated, she summons two Raging Flames (Fire Elementals) that are immune to all forms of crowd control. 

### Steps to reproduce the problem

.

### Extra Notes

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
They're not immune to Taunt: https://www.wowhead.com/npc=20481/raging-flames#comments:id=712836

> In normal mode:
Tested with a Death Knight and they're NOT immune to Dark Command (Taunt).

But they should be immune to knockbacks, yes

**Comment by balleny** [comment]
one comment above https://www.wowhead.com/npc=20481/raging-flames#comments:id=249796
>  They have random aggro, non tauntable, etc.

**Comment by balleny** [comment]
if they would be tauntable, people would have used hunters with distracting shots and other weird tactics, which wasnt the case.

**Comment by Gultask** [comment]
I believe they did change at some point to become tauntable, as well as not being immune to spells anymore. I can't pinpoint exactly but I trust the player running as DK, as they are playing in a later patch

**Comment by Gultask** [comment]
Although I do understand that the missing mechanic might make the experience way different. I might add it to the progression module.
