### ISSUE TITLE
[Mining] Triple node (Iron, Gold, Silver) in STV

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#526]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There is a triple node of Iron, Gold and Silver in Stranglethorn Vale at coords 30.5 ; 7.6.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should only be one node

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to coords 30.5 ; 7.6 in Stranglethorn Vale ;
2. Observe triple node

##### EXTRA NOTES:

Screenshots:
![WoWScrnShot_050321_060411](https://user-images.githubusercontent.com/81818678/116841114-70483c80-abd8-11eb-9a79-2fd0c9d62d52.jpg)
![WoWScrnShot_050321_060413](https://user-images.githubusercontent.com/81818678/116841116-70e0d300-abd8-11eb-9ad3-9eadc8cbbcec.jpg)
![WoWScrnShot_050321_060417](https://user-images.githubusercontent.com/81818678/116841117-71796980-abd8-11eb-9a78-3ee49a1d8be2.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
I'll add it here, please let me know if every double node should be a separate issue?
There's another double node in northern STV at coords 41.5 ; 14.3.
![WoWScrnShot_050321_131727](https://user-images.githubusercontent.com/81818678/116870011-09477980-ac12-11eb-9b17-d752807f457c.jpg)
![WoWScrnShot_050321_131731](https://user-images.githubusercontent.com/81818678/116870016-09e01000-ac12-11eb-9ed0-423eff7da698.jpg)

**Comment by Pudjero** [comment]
5854 (Entry: 1734) - [Gold Vein X:-11490.400391 Y:276.760010 Z:22.915400 MapId:0] 
34036 (Entry: 1733) - [Silver Vein X:-11490.400391 Y:276.760010 Z:22.915400 MapId:0] 
65255 (Entry: 1735) - [Iron Deposit X:-11490.400391 Y:276.760010 Z:22.915400 MapId:0] 
![WoWScrnShot_050321_144747](https://user-images.githubusercontent.com/66913785/116872596-d2c42b80-ac1e-11eb-9f80-8aaceb32bf11.jpg)
