### ISSUE TITLE
[Mechanar] Wave pattern before the final boss

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5261]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

you get outfight between the waves 1-3 and 4-6

boss doesnt auto engage after 15 seconds

### Expected Blizzlike Behaviour

you shouldnt get outfight between the first 3 waves and waves 4-6

boss doesnt auto engage after 15 seconds

### Source

https://youtu.be/5x9UY0pQCSw?t=942
https://youtu.be/O59tAY_ni0w?t=674

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
What do you mean by outfight?

The exact timer for the boss is actually 25s, but I think something might not be triggering it, yes.

**Comment by balleny** [comment]
you drop combat state and can sit and drink, resurrect, etc.
starting from wave 1, until you kill the last mob of wave 3, you should not leave combat.
same for wave 4 to 6

**Comment by Gultask** [comment]
I see. I think I may know how to fix it.

**Comment by balleny** [comment]
https://wowpedia.fandom.com/wiki/Pathaleon_the_Calculator
> The first set of 3 waves consist of a wave of 4 blood elves, followed by a solo robot, followed by another wave of 3 blood elves. The first set will spawn once one person has stepped just beyond the boundary of the door from [Nethermancer Sepethrea](https://wowpedia.fandom.com/wiki/Nethermancer_Sepethrea)'s room onto the bridge. The leader probably will not have enough time to mark when the groups of blood elves spawn, so it maybe easier just to randomly CC any two mobs and have the tank quickly pick up the remaining one or two. Alternately, the whole group can run down the elevator after the mobs spawn, so that they can be marked as usual when come back. You will be removed from combat for a brief moment after the last mob in a wave has been killed, so capitalize upon this to recover mana by drinking. If the healer is low on mana, or anyone is killed, the group can always run down the elevator to get out of combat. After the first 3 waves have been killed, rest to full health and mana, and have one person run down the bridge until the next set of mobs spawn. It's best to engage the second set of waves in Nethermancer Septhera's room, as this will increase the amount of time the group has to rest between waves. On the 6th wave, keep one mob crowd controlled (preferably a Sunseeker Astromage) and allow the group's mana to regenerate to full. If possible, spellsteal the Astromage's fire shield. Once you are confident you have enough mana, move down the bridge. Allow the last mob to come to your group, and kill it. Pathaleon will aggro upon its death.

**Comment by Gultask** [comment]
It's a row I missed. Instead of putting the mob in combat with the zone (all players in combat) it aggroes the closest player instead. I'll try to do something with it.

**Comment by balleny** [comment]
incase you already did attempt to fix it - it did not change yet and you still drop combat

**Comment by Gultask** [comment]
Ye I didn't get around to fixing it yet or the issue would be closed 😛
I hope the Nether Charges are good now, though

**Comment by balleny** [comment]
> Ye I didn't get around to fixing it yet or the issue would be closed stuck_out_tongue I hope the Nether Charges are good now, though

note, practically, nothing changed but them becoming visible (no damage, wrong animation, wrong despawning, wrong location)
https://github.com/chromiecraft/chromiecraft/issues/5264#issuecomment-1488883358
