### ISSUE TITLE
[Mechanar] Mechano-Lord Capacitus Nether Charges missing

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5264]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

https://www.wowhead.com/npc=19219/mechano-lord-capacitus not summoning Nether Charges

### Expected Blizzlike Behaviour

he should summon nether charges frequently, which explode in 15 yards aoe

Further, the bombs should not despawn uppon death but remain til they explode after their 15 sec lifetime

### Source

https://www.wowhead.com/npc=19219/mechano-lord-capacitus

https://wowpedia.fandom.com/wiki/Mechano-Lord_Capacitus
> When the boss dies, the bombs do not despawn, but will all explode!

https://youtu.be/O59tAY_ni0w?t=325

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Paradigmxd** [comment]
I am not sure why this is closed as completed? He now spawns the Bombs but they do NOT do any damage - they also IMMEDIATELLY despawn upon his death.??

**Comment by balleny** [comment]
issue persists @Nyeriah 
charges are now spawning, but only in the sector the boss is positioned, instead of "around him". they dont deal any damage, have the wrong pulsing aoe animation and directly despawn uppon boss death instead of staying until they explode

**Comment by Gultask** [comment]
They do spawn around him. It's built into the spell, they spawn at his' side.

The pulse animation can be seen in sniffs. Spell ID - 35151 Nether Charge Pulse
The detonation is 16500ms after spawn.

![image](https://user-images.githubusercontent.com/100873791/228627337-c311e3ca-623b-40eb-acc3-6afc14d133b3.png)

**Comment by Gultask** [comment]
Right, after looking at the video I can say that the implementation is incorrect.

They spawn.
Random Move for 8500ms
Stop
Wait 2000ms
Pulse 3 times with 2000ms delays
Explodes

**Comment by Nyeriah** [comment]
@Paradigmxd 

Pull requests are usually opened as a fix candidate to a bug report. Once a fix candidate PR is merged, all issues associated to it are closed automatically and instantly.

If the issues they are meant to address are still present after they were merged, we need the original reporter to request the issue to be reopened.

I hope this clears your doubts.

Kind regards.
