### ISSUE TITLE
[Mechanar] Waves preceding Pathaleon the Calculator can drop combat.

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#5268]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

If group runs far enough from, say, wave 1 into the wave 4 (which spawns) and pulls the two waves more towards boss where wave 6 spawns, then after killing the wave 1 does not aggro the mob from wave 2 (or if wave 2 has been cleared in this situation, wave 3 does not aggro). 

### Expected Blizzlike Behaviour

Waves 1-3 should be in combat as well as waves 4-6 after which there should be short break until last boss initiates combat. 

### Source

https://youtu.be/O59tAY_ni0w?t=678

### Steps to reproduce the problem

1. Pull first wave in Mechanar before last boss.
2. Run to the boss.
3. Kill waves 1 and 4.
4. Wave 2 might or might not come -> Kill waves 5 (and 2)
5. Wave 3 does not aggro.
6. Kill wave 6. 

### Extra Notes

Have been able to do this several time on live servers with two different outcomes:
Wave two aggroes normally, wave three does not.
Wave two does not aggro at all.

Combat drops correctly after waves 3 and 6.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
similar to https://github.com/chromiecraft/chromiecraft/issues/5261 but slightly different:

you can engage wave 1, and without killing it, run further down the path.
that will trigger wave 4 (should obviously not trigger just based on proximity).

if you keep running further towards the final boss room, and only then start killing the mobs of wave 1, the mobs of wave 2 are not attacking the group. this practically allows skipping wave 2 and 3.

**Comment by Gultask** [comment]
Wave 4 can indeed be triggered before wave 3 is completed, that's intended behaviour. Wave 4 is triggered solely on proximity. In fact, if you drop combat (Feign Death) wave 1 you can completely skip waves 1-3 and engage the boss. I did it myself in Blizzard servers.

**Comment by Gultask** [comment]
As for waves not attacking players that are far away, I believe fixing #5261 might correct that

**Comment by Gultask** [comment]
Ah, right I get now what you meant in the first paragraphs.
https://github.com/chromiecraft/chromiecraft/issues/5261 is indeed the same issue and was fixed together.
Regardless, thanks for the report!
