### ISSUE TITLE
Moonfire does not aggro a mob on respawn.

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#5277]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Using [Moonfire](https://wowgaming.altervista.org/aowow/?spell=26988) from a range on a mob that respawns drops aggro several times without giving the tag for the mob. This happens on all mobs unless the mob dies from the initial damage. During the time it resets, someone else is able to tag the mob. 

https://user-images.githubusercontent.com/107246426/227957663-5167a7a4-b139-4cc8-877d-d2a9126eff1c.mp4

Here is a reference how [Faerie Fire](https://wowgaming.altervista.org/aowow/?spell=770) works in the same situation:

https://user-images.githubusercontent.com/107246426/227959585-912c3ee4-9204-4bee-902d-2275d6ffe3b0.mp4

### Expected Blizzlike Behaviour

Using an ability on a mob yields the tag to you if no one else has tagged it before. 

### Source

-

### Steps to reproduce the problem

1. Kill a mob.
2. Wait for it to respawn.
3. Right when it respawns, spam moonfire from a range (don't be close enough for it to body pull).
4. See how the mob resets few times before you actually get the tag and aggro.

### Extra Notes

This might extend to all instant cast abilities that cause a damage over time effect. I had some talk with a friend who had encountered this with Shaman's [Flame Scock](https://wowgaming.altervista.org/aowow/?spell=25457).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
the issue is not moonfire specific and exists also with other abilities (abilities with and without initial damage aswell)

**Comment by Alethrion** [comment]
I believe this may be all aura abilities as immolate does it as well. I may look into this soon. If you find any example that doesn't apply a dot let me know as it may help to refine my search
