### ISSUE TITLE
Loot not rolled and distributed.

### ISSUE THREAD

**Issue by Jinteki01** [chromiecraft/chromiecraft#5282]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

While doing The Mark of the Nexus-King quest in Blade's Edge Mountains, the mob we killed dropped Slatesteel Shoulders of the Champion. 3 people rolled and 2 of us passed on the item, but item was never distributed to a party member. The loot log didn't show us passing on the item either or a roll for it. Hesdeadjim, rolled need on the item, but never received it. Again there is no record of rolls as seen in the screenshots.

### Expected Blizzlike Behaviour

The two passed rolls should have went through. The item should have then been rolled on and distributed.

### Source

The normal behavior of all loot, including the other drops that happened while in this group.

### Steps to reproduce the problem

1. Slatesteel Shoulders of the Champion dropped from mob in Blade's Edge Mountain prison.
2. All 5 members selected a loot option (Greed, Need and Pass)
3. Only 3 members options showed in the loot window (Greed and Need)
4. Group goes on to kill 2 other mobs from the prisons.
5. That specific item never rolled on after both passes and just disappears.
6. Other items that are passed on roll fine (the key) and other gear rolls fine as well.

### Extra Notes

Screenshots of my loot chat window and also party chat with guild member. Guildie had intended to equip item for Tmog then pass the item to me. After we had killed another 2 mobs we realized no one ever got the item.

![Shoulders](https://user-images.githubusercontent.com/60189062/228107372-80fe5695-cbf8-4841-8fd3-cb3b27e37da5.PNG)
![shoulders2](https://user-images.githubusercontent.com/60189062/228107374-8353243d-fb2b-49d0-a150-20c233ee927b.PNG)
![shoulders3](https://user-images.githubusercontent.com/60189062/228107375-1d537df0-1e97-450e-9a2c-090d7af518b4.PNG)
![shoulders4](https://user-images.githubusercontent.com/60189062/228107379-3d36b76f-20f2-4f4b-bd71-0dea575e9b58.PNG)
![shoulders5](https://user-images.githubusercontent.com/60189062/228107381-102014d8-aa94-4d68-965c-526e914b5267.PNG)
![chat](https://user-images.githubusercontent.com/60189062/228107382-a6ca2e09-7293-400c-9a60-79f3e7293203.PNG)
![chat2](https://user-images.githubusercontent.com/60189062/228107383-2593e009-54a4-4c9e-9837-95f56bdbf450.PNG)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Jinteki01** [comment]
Some more screenshots of the same thing happening with the loot from the mobs inside the Netherstorm prisons. It seems to be tied to the loot decision timing out. If it times out for one person, the loot just never gets rolled out. Instead of automatically passing for that person and rolling, it just indefinitely waits for their loot decision.

![Keys](https://user-images.githubusercontent.com/60189062/232739659-195ef42e-fb2e-44e9-886e-066b320e9002.PNG)
![Keys2](https://user-images.githubusercontent.com/60189062/232739693-ac8084e9-cc96-4b0d-9bb5-2c5547e83644.PNG)
![keys3](https://user-images.githubusercontent.com/60189062/232739754-70103ad7-7e2d-4abe-95c6-06add2c605dc.PNG)
![keys4](https://user-images.githubusercontent.com/60189062/232739758-ea591404-6eb0-4a4e-a194-de5bc5ec9f7f.PNG)
![keys5](https://user-images.githubusercontent.com/60189062/232739760-324ef299-3bbd-4876-9384-604282bad081.PNG)
![keys6](https://user-images.githubusercontent.com/60189062/232741648-af6694bb-b693-463d-819a-af33981bbd4a.PNG)

**Comment by Jinteki01** [comment]
Same issue happened again on my druid yesterday. There was a group member in an entirely different zone who couldn't roll on the items. All the other group members that were in Netherstorm confirmed they had passed on the Ethereum Prisoner I.D. Tag.  3 different drops showed my need and their passes, but the tags were never rolled and distributed. Prior to the other group member joining who wasn't in the same zone, the loot worked fine. Again seems to be an issue where if one person doesn't or can't select a loot option for an item, then it just stays in limbo.

**Comment by Kitzunu** [comment]
cannot reproduce on https://github.com/azerothcore/azerothcore-wotlk/commit/8bca8a45edf85a73fe77ee28b6d7a9009e2ebd25
