### ISSUE TITLE
Storm Chops food completely broken, adds absurd amount of damage, other items/enchants likely broken as well

### ISSUE THREAD

**Issue by InvictaChromie** [chromiecraft/chromiecraft#5290]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Hey, apologies in advance for the very long post, but trying to contribute as much info as possible in one go:

The food "storm chops" (https://www.wowhead.com/tbc/spell=43758/stormchops) which comes from a recipe via cooking dailies, is absolutely busted on this server and adds completely crazy amounts of AoE damage, heard from others on the server in both worldchat and guildmates today talking about how broken it is and decided to test myself in 3 quick dungeon runs, attaching recount picture below from the 3 runs:

![sc](https://user-images.githubusercontent.com/86496802/228431226-c0322f09-7a44-455c-a3e5-492242fe744b.png)

I think picture says it all, 10% of overall damage give or take, on same level as main abilities like divine storm, and this was just from a couple sloppy/quick RDF runs without really optimizing for it with huge pulls or anything like that, with more preparation/huge pulls and so on where it can really shine then I bet it is even more busted, and would be higher up on overall damage contribution.

looking at a upvoted comment from 2008 on wowhead (https://www.wowhead.com/tbc/spell=43758/stormchops#comments) for example someone wrote this:

**_"Nevermind. With a little testing I found that [Electrified](https://www.wowhead.com/tbc/spell=43730) works a little like [Thorns](https://www.wowhead.com/tbc/spell=26992) in that it only procs when you're attacked, and even then only sometimes (I lost interest soon after I figured this out and didn't try to figure out actual proc rate or cooldown details). The proc is about 30 damage (disappointing!) and will arc to nearby enemies."_**

Which tells me that how it currently works on chromiecraft is absolutely not blizzlike,

I'm playing retribution paladin but I heard other classes benefit even more from it, after some digging around I also heard from others on the server that this item is not the only case of items with a proc effect being busted on the server currently, 

supposedly the low level enchant Fiery Weapon (https://www.wowhead.com/classic/spell=13898/enchant-weapon-fiery-weapon) enchant is outperforming higher level enchants like Crusader (https://www.wowhead.com/classic/spell=20034/enchant-weapon-crusader)  which makes no sense,

and I also want to mention that for example at the level 60 bracket the trinkets Darkmoon Card:Maelstrom (https://www.wowhead.com/classic/spell=23686/lightning-strike) and Heart of Wyrmthalak (https://www.wowhead.com/classic/spell=27656/flame-lash) were busted as well and both added a huge amount of total damage, in the range of 4-7% or more overall damage each, every single time I checked overall stats on damagemeters like recount after dungeon/raid sessions. So much so that they were the best in slot trinkets for any retribution paladins as long as the target was not nature/fire immune, where you would then swap out either of the trinkets for another one and so on.

(Can't say if this goes for all classes that could make use of them, or if paladin seals / abilities are a factor etc, but definitely the case for ret paladin anyway)

I don't have any recounts or testing for the Fiery Weapon enchant, but I have seen more than one melee player use it over Crusader enchant currently, it's just that most people have no idea about any of this stuff and logically use the recommended enchants/items/trinkets assuming that everything is working normally / blizzlike on the server which just doesn't seem to be the case,

Also don't have any screenshots/tests for Maelstrom/Wyrmthalak trinkets since I don't use them anymore, and it also leaves a kind of "bad taste"/feeling so to speak to get expensive trinkets/enchants/items and then finding out they are worse than older/lower level stuff when they shouldn't be, if that makes sense.

Anyway, considering all of this I really think it at least would be a good idea, if the devs could take a look into items/enchants like these and see if some multiplier or something is wrong somewhere, making them proc far more often than intended, outperforming higher level enchants / items and so on,

other enchants/items that come to mind I've heard others talk about being busted currently are for example Spellsurge (https://www.wowhead.com/wotlk/spell=28003/enchant-weapon-spellsurge) and Battlemaster (https://www.wowhead.com/wotlk/spell=28004/enchant-weapon-battlemaster) 

I'm not a dev myself and not too familiar with PTR testing or any of that, so i'm sorry if this bug report is kind of lacking but I just wanted to explain it as good as I can for now, considering I don't have much hard data to back it up yet, other than the storm chops screenshots above which prove that at least that effect is completely busted at the moment.

### Expected Blizzlike Behaviour

Wowhead comment for stormchops : (https://www.wowhead.com/tbc/spell=43758/stormchops#comments)

_**"Stormchops is different from most buff food. When you eat Stormchops, you get no health back and you get the [Electrified](https://www.wowhead.com/tbc/spell=43730) buff immediately (none of this eating for 10 seconds stuff--you don't even sit down).

Stormchops does overwrite any other Well-Fed buffs you might have, and Stormchops' buff can be overwritten by a Well-Fed buff.

I'm a shadow priest, so I bring foods like [Blackened Basilisk](https://www.wowhead.com/tbc/item=27657) to raids. I suspect that "Electrified" isn't better than +23 spell damage, but I'm curious, has anyone done any theorycrafting to figure out how much dps Stormchops adds?

Nevermind. With a little testing I found that [Electrified](https://www.wowhead.com/tbc/spell=43730) works a little like [Thorns](https://www.wowhead.com/tbc/spell=26992) in that it only procs when you're attacked, and even then only sometimes (I lost interest soon after I figured this out and didn't try to figure out actual proc rate or cooldown details). The proc is about 30 damage (disappointing!) and will arc to nearby enemies.

If you get close enough to a critter then there seems to be a very high chance that the buff will proc without your having been struck by anything, and the critter will be zapped for something more like 700 damage.

I knew there was a reason no one was buying this on the AH! Someday this and chocolate cake are going to get buffed and become the staple raid food, and then won't you all be sorry you didn't stock up when I was selling them cheap!"**_

------------------------

I think it's safe to say expected Blizzlike behaviour is not a procrate so high it contributes to 10%+ of overall damage on a quick test, as for the other enchants/items mentioned above I can't say much more than it just seems like procrates are way off the chart, if one item is definitely busted, it wouldn't be too bold to assume that others on the server with proc effects could be as well, as far as I see it anyway.

### Source

Only sources I have for now I guess would be the wowhead comments linked above as well as my recount pictures regarding stormchops, and my personal experiences on this server playing for over a year here as paladin main with the other trinkets mentioned above and so on.

### Steps to reproduce the problem

In the case of stormchops, just eat the food and gain the buff, run a dungeon or two and gain massive aoe damage! outclassing core abilities in several cases, like shown in recount screenshots above.

as for the other items/enchants mentioned, hard for me to say how to reproduce other than just testing one vs the other in case of fiery weapon vs crusader enchant and so on I guess, which will probably have to be done at least some time before heroics/raids are released when performance will matter more than it does now with only normal dungeons available.

### Extra Notes

Again my apologies for maybe not having that much "hard data" yet so to speak, but as someone who has played here for over a year now and spent a ton of playtime on the server, I at least personally feel it would give a sense of "relief" to not having to worry about getting expensive items/enchants/farm for best in slot gear that then turns out to be worse than other/older items just because of broken mechanics / code, if that makes sense!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by bonfax4** [comment]
I'm surprised this bug made it to live tbh, the lack of cd has been [reported](https://github.com/chromiecraft/chromiecraft/issues/5066) and discussed [here](https://github.com/chromiecraft/chromiecraft/issues/4484) . [Fiery weapon and similar procs](https://github.com/chromiecraft/chromiecraft/issues/4226)  being good for warr deep wounds has been mentioned before and it's intended if that's what you're referencing.

**Comment by Stump876** [comment]
Thanks for the report InvictaChromie.  You've clearly put some research into this. However, as bonfax4 stated there is already an open report about this. Any additional info should really be put into the already open report instead of opening a new one.
