### ISSUE TITLE
NPCs in Outland - All worm-like NPCs are not working as intended (tunnelers, Marauder Crust Bursters etc.)

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5297]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

All worms in outlands are broken on Chromiecraft - They do not perform the BURROW mechanic where they submerge and emerge on a different location from where they submerged

### Expected Blizzlike Behaviour

They submurge..Its the only thing that made these TBC mobs so annoying

### Source

https://www.wowhead.com/tbc/npc=16968/tunneler#comments

Sorry had to, anyhow these mobs are very difficult to kill. not because they have a really high health pool or a ton of dps but they tunnel under the ground and pop up at a random location constantly when your fighting it, get multiple of these mobs on you and have fun chasing them around for a few mins..

### Steps to reproduce the problem

Fight any worm-like NPC in Outlands on Chromiecraft//

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
HI Paradigmxd. Thanks for the report. I'd tell you this is a duplicate, but you already know because you commented on the original. https://github.com/chromiecraft/chromiecraft/issues/4571 There are actually 2 open and linked reports about the worm behavior https://github.com/chromiecraft/chromiecraft/issues/4629  I do not think we need a 3rd.

**Comment by Paradigmxd** [comment]
oh shit - sorry haha! There are so many opened issues sometiems i forget ...
