### ISSUE TITLE
Skyriss loot slots and tempest keep attument

### ISSUE THREAD

**Issue by Rholik** [chromiecraft/chromiecraft#5299]
### What client do you play on?

esES

### Faction

Horde

### Content Phase:

70

### Current Behaviour

The event of skyriss boss fight have some issues with the loot and tempest keep attument. [Trial of the Naaru: Tenacity] has to be completed in archatraz heroic but can be completed in normal mode (which is not intended) And the loot slots of skyriss are limited to only one item.

### Expected Blizzlike Behaviour

First of all:
https://www.wowhead.com/tbc/quest=10886/trial-of-the-naaru-tenacity
Only can be completed in heroic mode which is future update in the progression of the server
 
With the skyriss loot slot have to be 2 items (and 10% chance of a third one who is primal nether)
This last i sure can be fixed because have the same way was fixed panthaleon loot slots in Mechanar

### Source

![WoWScrnShot_033123_085531](https://user-images.githubusercontent.com/109829814/229129601-4ad631e8-ba8a-4f88-a4b9-f5d50b604d6b.jpg)
![WoWScrnShot_033123_085536](https://user-images.githubusercontent.com/109829814/229129605-19bef9e7-e8a2-4b71-9f0f-57fb16900d27.jpg)

### Steps to reproduce the problem

1. Have done the cipher of damnation quest chain
2. take the quests from a'dal to get access to tempest keep
3. Run Archatraz and fight Skyriss

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thanks for the report!

Unfortunately the loot issue was reported here: https://github.com/chromiecraft/chromiecraft/issues/5292
And the quest issue was reported here: https://github.com/chromiecraft/chromiecraft/issues/5293

Technically those 2 things should be reported separately, too, since they are unrelated.
But I appreciate the report regardless.
