### ISSUE TITLE
Mobs standing idle (Kodos in Mulgore, Gazelle in the Barrens)

### ISSUE THREAD

**Issue by fishworld** [chromiecraft/chromiecraft#530]
#### WHAT CLIENT DO YOU PLAY ON?

- [X] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Kodos not roaming around in Mulgore. Just standing AFK basically at their current locations
Same with the Gazelle in the Barrens.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should move around in certain patterns. 

##### STEPS TO REPRODUCE THE PROBLEM:

--

##### EXTRA NOTES:
--

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
use .npc info
Where you see NPCs/Mobs with issues, with this lack of information we cannot work.
