### ISSUE TITLE
Bank still accepts item even when all slots are full. Not able to see or retrieve item.

### ISSUE THREAD

**Issue by DcWalker90** [chromiecraft/chromiecraft#5326]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

Went to Ironforge bank and attempted to store a few items.  Bank accepted items but they could not be seen or retrieved once they were accepted.  One of the items submitted was some raw fel iron ore which is now lost.  I then cleared some banking spots and deposited more fel iron ore, but they seem to now be stacking on the invisible banking slot that cannot be seen. 

### Expected Blizzlike Behaviour

If no banking slots are available, the deposit should be rejected with an error stating there are no available slots. 

### Source

?

### Steps to reproduce the problem

1. fill all banking slots
2. attempt to store another item once bank is full
3. item disappears

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
I'd say the most likely case is that he uses an add-on that merges bank slots and accidentally shift(or ctrl, I never remember the keys) clicked one of the bags in bank. In that case the specific bags content goes invisible until you repeat the same key combination to re-enable it.
Same thing can happen in your regular inventory, then you go crazy looking for the loot you just picked up until you stare at the screen long enough to realize your bag is 8slot smaller than it was.
Iirc most addons won't anyhow display if one of the bags are "turned off", everything looks normal except you can't see some slots.
