### ISSUE TITLE
Giant Clam doesn't drop Blue Pearl when looted or has incorrectly low droprate

### ISSUE THREAD

**Issue by Beastmasterwow** [chromiecraft/chromiecraft#533]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X ] 20-29
- [X ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Object "Giant Clam" doesn't drop Blue Pearl at expected droprate.
I looted 12 Giant Clams and got only 1 Blue Pearl.
Classic wowhead link: https://classic.wowhead.com/object=2744/giant-clam
Wowhead link: https://www.wowhead.com/object=2744/giant-clam

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Giant Clam should drop Blue Pearl at droprate of 100% 
Screenshot from wowhead link linked before:
![image](https://user-images.githubusercontent.com/81812276/116941702-7be74200-ac70-11eb-9840-fce6b26654e8.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Stranglethorn Vale or Blackfathom Deeps ( Instance)
2. Find the Giant Clam.
3. Loot the Giant Clam.
4. See for yourself incorrect droprate/

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
ref #497

**Comment by necropola** [comment]
Only those found in **The Vile Reef**are supposed to drop Blue Pearls. 
I'm currently doing some pearl diving on my local AC and I have found one **Giant Clam"" in ''The Vile Reef** (almost instant respawn) which appears to have an equal chance to drop either 1 **Blue Pearl** or 1 "Giant Clam Meat**.

**Comment by iraizo** [comment]
> 
> 
> ref #497

This is a duplicate and not even related to the original issue you linked.

**Comment by YunataSavior** [comment]
The root issue is not resolved. EVERY single Giant Clam is supposed to be guaranteed to drop a Blue Pearl.

This is a really simple SQL update that can be performed, otherwise, farming Blue Pearls for ppl to complete the Badlands quest is completely annoying.

Not only that, but there should be a lot more Giant Clam spawns, if you look up the game object on Wowhead (vs WOTLKDB)

https://classic.wowhead.com/object=2744/giant-clam

https://wotlkdb.com/?object=2744

Please reopen this issue.
