### ISSUE TITLE
[PTR] Heroism affects only alliance, Bloodlust affects only horde

### ISSUE THREAD

**Issue by unitscan** [chromiecraft/chromiecraft#5332]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Heroism affects only alliance, Bloodlust affects only horde

### Expected Blizzlike Behaviour

Heroism should affects both alliance and horde, Bloodlust should affects both alliance and horde

### Source

PTR

### Steps to reproduce the problem

1. Make a raid with one alliance shaman and one horde shaman
2. Go inside Gruul's Lair
3. Test Heroism and Bloodlust

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
I naively declare this is likely related to the attributes flag for Alliance/Horde only (512/256 respectively) for these spells. WDBX has this column called AttributesExG, don't care enough to figure out what it's called in AC's DB. This'll be a fun one to try and fix. 🙂

**Comment by Nyeriah** [comment]
> I naively declare this is likely related to the attributes flag for Alliance/Horde only (512/256 respectively) for these spells. WDBX has this column called AttributesExG, don't care enough to figure out what it's called in AC's DB. This'll be a fun one to try and fix. 🙂

Works as intended as you’re not supposed to have bloodlust as an alliance vice and versa, cross faction groups are custom  

the custom implementation needs a workaround though

**Comment by Nyeriah** [comment]
Seems to be working as intended for me 

![image](https://github.com/chromiecraft/chromiecraft/assets/47818697/e3703a21-3b12-4653-b840-472470afc7a4)

**Comment by Nyeriah** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/47818697/45482db4-1bf9-4902-8891-8d6d9c6f4709)
