### ISSUE TITLE
[Arcatraz] Mind controlling the Warden Mellichar too early makes the last gauntlet have double the encounters.

### ISSUE THREAD

**Issue by Drathnor** [chromiecraft/chromiecraft#5334]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

It is known that the Warden Mellichar at the end of Arcatraz is Mind Controllable at the end of the instance. But for some reasons, if he is mind controlled before he starts spawning mobs, and then breaking the Mind Control, the gauntlet event will have the encounters duplicated. Last boss also gets duplicated, but since the Warden dies from the first boss RP, the "2nd final boss" will be in "stasis".

### Expected Blizzlike Behaviour

Warden shouldn't be mind controllable, and even if that was possible, there would be no reason why that would spawn duplicated mobs for the gauntlet.

### Source

![image](https://user-images.githubusercontent.com/61948874/229625503-ee4f184a-b160-46d9-ac81-3ebe6ab7a1a7.png)
As it is visible in the screenshot, there are 2 flamewalkers and 2 dragonkins ( should only be 1 of each )

A video of the encounter, followed by the page of the encounter, that clearly states only 1 mob should spawn from each cell:
https://www.youtube.com/watch?v=fhrrROEEsCg
https://www.wowhead.com/npc=20912/harbinger-skyriss

### Steps to reproduce the problem

1. Have priest in party
2. When you get to the end, Mind Control Warden Mellichar before he starts summoning the mobs for the gauntlet.
3. Break Mind Control

If done properly, double mobs should spawn, the time between originals and duplicates spawning is aprox. the same between the start of his RP and the time you mind control him.

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=20904 ( Warden Mellichar ) 
https://wowgaming.altervista.org/aowow/?npc=20911 ( Blackwing Drakonaar ) 
https://wowgaming.altervista.org/aowow/?npc=20910 ( Twilight Drakonaar )
https://wowgaming.altervista.org/aowow/?npc=20977 ( Millhouse Manastorm )
https://wowgaming.altervista.org/aowow/?npc=20909 ( Sulfuron Magma-Thrower )
https://wowgaming.altervista.org/aowow/?npc=20912 ( Harbinger Skyriss ) 
https://wowgaming.altervista.org/aowow/?npc=20906 ( Phase-Hunter )

Here are all the NPCs that are involved with this bug.

The one thing to note, is that, when you get to the third mob spawn ( Drakonaars ) it will first be Twilight Drakonaar, followed by Blackwing Drakonaar. Or so I experienced from the 2 attempts that I did this in.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
also mentioned here https://github.com/chromiecraft/chromiecraft/issues/5312

**Comment by Rorschach91** [comment]
Considering that this issue is a duplicate, I close it.

Thank you for your report.
