### ISSUE TITLE
Cute Training Dummy gives bow skill points

### ISSUE THREAD

**Issue by Elthz** [chromiecraft/chromiecraft#534]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The lvl 40 Cute Training Dummy is giving skill points to bows (ranged weapons in general?) 

![WoWScrnShot_050321_224357](https://user-images.githubusercontent.com/33559707/116962893-9d175500-aca7-11eb-9062-56134e5f4815.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Training dummies should not give weapon skill.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Equip Bow below max level skill and wait for skill ups

 [08:20:09] Found near gameobjects (distance 10.000000): 0 
[08:20:14] Player selected NPC
[08:20:14] DB GUID: 3110366, current GUID: 3110366.
[08:20:14] Faction: 7.
[08:20:14] npcFlags: 0.
[08:20:14] Entry: 1111003.
[08:20:14] DisplayID: 28047 (Native: 28047).

##### EXTRA NOTES:

At the moment this only seems to work with bows (or ranged weapons in general, haven't tested others as I've already got guns to max), however I did try with melee weapons (sword and dagger) for a a few minutes and it didn't give any skill points, so it may be just certain weapons or only ranged ones.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anglerf1sh** [comment]
Can confirm this on live servers for wands too. I used https://wowgaming.altervista.org/aowow/?item=7001
![WoWScrnShot_050421_175234](https://user-images.githubusercontent.com/82279027/117032336-b220d200-ad01-11eb-958e-77bbc0d755b1.jpg)

**Comment by cachocarne** [comment]
I have a question about weapon skill. Should it go up when you attack very low (gey) level mobs? I thought they needed to be AT LEAST green. Because so far it is working on enemies extremely low...
![ 2023-05-22 a las 15 43 26](https://github.com/chromiecraft/chromiecraft/assets/77953030/8cab4e9a-7b23-4a4b-8962-b64ce24abdd1)
