### ISSUE TITLE
Quest "Scarlet Diversions" Doesnt require you to burn the tent.

### ISSUE THREAD

**Issue by quigiboo** [chromiecraft/chromiecraft#5351]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

50-59

### Current Behaviour

All that is needed is to place the banner to complete the quest.

### Expected Blizzlike Behaviour

You should need to burn down the tent using the item in a crate near the quest giver, then be able to place the banner.

### Source

https://www.youtube.com/watch?v=_FhiOza4A5g
https://www.wowhead.com/classic/quest=5096/scarlet-diversions#comments
![image](https://user-images.githubusercontent.com/114075548/230648780-63ff5f2c-8b27-4e72-be65-a5a283b7176e.png)

### Steps to reproduce the problem

.quest add 5096
.tele dalson
plant flag without burning tent just to the west

### Extra Notes

Im finding it hard to replicate this on the ptr, it wont allow me to hand in the quest when i give it to myself via gm commands, however i noticed this on an actual character on chromiecraft and was able to hand that in.

On the ptr you do however get the completion popup as if you burnt the ten when you haven't, i think the flag is only supposed to be able to be used on the burnt tent.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, thanks.
