### ISSUE TITLE
You can buy from Rathis Tomber at any point.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#5356]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

[Rathis Tomber](https://wowgaming.altervista.org/aowow/?npc=16224) can be bought from at any point.

### Expected Blizzlike Behaviour

You should only be able to buy from him once you've completed [Tomber's Supplies](https://wowgaming.altervista.org/aowow/?quest=9152).

### Source

Wrath Classic, semi-assumption. Seen him not be a vendor from a template character, seen him be a vendor on a well-played character, Wowhead states that the quest is the restriction.

### Steps to reproduce the problem

1. `.tele tranquillien`
2. Interact with Tomber.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
He is also almost definitely missing movement, but I didn't stick around for an hour to find out. Separate issue.

**Comment by avarishd** [comment]
Thanks for the report, but the condition exists, although he is missing the npc_text AFTER the quest is rewarded.

 After the quest
> Such a delight to see you again, <class>. No, really. You're the reason that I'm making money here, hand over fist.
Now, what can I sell to you today?

**Comment by heyitsbench** [comment]
> Thanks for the report, but the condition exists

Just checked again and you are correct. Don't know why I thought that that he was a vendor before the quest was completed. Guess the reported issue is invalid then.

**Comment by avarishd** [comment]
Partially valid, still missing that npc_text.

**Comment by heyitsbench** [comment]
> Partially valid, still missing that npc_text.

Sure but that wasn't the issue I reported. 😛
