### ISSUE TITLE
Flying Kobold in Fargodeep Mine

### ISSUE THREAD

**Issue by jendryk** [chromiecraft/chromiecraft#537]
#### WHAT CLIENT DO YOU PLAY ON?

- 

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

While doing quests in Fargodeep Mine in Elwynn Forest I saw a Kobold Tunneler "flying" and going through textures.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs normally don't go through textures.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to the middle of Fargodeep Mine
2.  Observe flying Kobolds
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Si1ker why closing this? please specify the reason

**Comment by jendryk** [comment]
No proof or he saw that it wasn't properly wrote down, because I posted it before editing.

**Comment by Azcobu** [comment]
Thanks for the report. Unfortunately, I couldn't verify this. Took a stealthy druid into the mine and wandered around for 15 mins watching the kobolds, and didn't spot anything unusual. You say 'go to the middle of the mine' - do you have any more details? Were the bugged kobolds fleeing from you or in combat at the time, or just wandering around?

**Comment by jendryk** [comment]
I wish I have made a screenshot of it. The kobold was just wandering around, jumping in the air and going through textures. I'm sorry I can't help more, when I get back from work I'll get in there and check, maybe I will get a screenshot

**Comment by Azcobu** [comment]
Thanks, that would be appreciated. If you target him and type '.npc info' and screenshot the output, that would also be very helpful.

**Comment by jendryk** [comment]
Guess it got fixed or it was a one time bug. Was there and watched the  Kobolds and they were all wandering nicely on the floor.
