### ISSUE TITLE
[Dungeon Shadow Labs] Cabal Warlock has multiple issues

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5373]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

1. Seed of corruption damage is significantly incorrect, dealing 1 damage to nearby units... and it does not work as a normal seed of corruption (i.e. it is NOT dealing damage overtime..)
2. Shadow Bolt deals about 500-600 damage and it should be 900-1k ...
Cabal Warlock can summon pets:
2. Maide of Discipline is not using charm
3. Felhunter is not TARGETTING MANA USERS TO DO MANA BURN at all.

### Expected Blizzlike Behaviour

1. Seed of corruption does more than 1 damage to nearby units :D, Seed of corruption works like it works FOR PLAYERs (i.e. it must do shadow dot effect)
2. Shadow bolt deals 900-1k damage..
3. Maiden Casts charm
4. Felhunter uses Mana burn to mana users

### Source

WOTLK classic 

https://www.wowhead.com/wotlk/npc=18640/cabal-warlock#abilities;mode:normal

https://www.youtube.com/watch?v=fxb7QT-1BTE as u can see Shadow Bolt deals about 900-1k damage.. 
As u can see Maiden uses CHARM
as u can see SEED OF CORRUPTION deals damage overtime and explodes...

### Steps to reproduce the problem

Do the dungeon

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I didn't find these bugs. They have probably already been solved.

Thank you for the report anyway.
