### ISSUE TITLE
[Dungeon Shadow Labs] Grandmaster Vorpil is quite bugged

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5377]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

1. When a voidwalker is sacrificed he gets an aura for increased shadow damage done - that aura however doesnt apply the bonus on subsequent shadowbolt volleys 
2. When group is teleported, he begins casting Shadow rain and immediatelly gets interrupted, rendering the phase useless.
3. He is NOT taunt immune
4. Once defeating him, players run to the next room and the door is opened

### Expected Blizzlike Behaviour

1. Aura affects his shadow damage done
2. He channels the reign of fire spells and cannot be interrupted
3. He is TAUNT IMMUNE
4. The door becomes open when players's character can physically see the door 

### Source

https://www.wowhead.com/wotlk/npc=18732/grandmaster-vorpil#comments;mode:normal

https://www.youtube.com/watch?v=fxb7QT-1BTE

### Steps to reproduce the problem

Do the dungeon

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Paradigmxd** [comment]
@Gultask 

I believe this is still valid

1. He doesn't cast Rain of Shadows for a duration of 65seconds (my Skada timer) 
2. On the PTR he randomly interrupts his own cast

**Comment by Gultask** [comment]
> Once defeating him, players run to the next room and the door is opened

About this one, we don't have a better system in place so far. We're trying to see what exactly is triggering the door being opened, as there are a large amount of possibilities, but it seems that Blizz uses none of them, unless it's something we're missing.

**Comment by Rorschach91** [comment]
Regarding the first problem:
Where did you see that voidwalkers increase Vorpil shadow damage when they explode?
I read the [tactics](https://www.wowhead.com/tbc/npc=18732/grandmaster-vorpil#comments) and seems that this feature is not present in this bossfight.

Anyway rain of fire doesn't stop anymore and boss is tantuable now.

Thank you for the report. If you find other bugs feel free to report them.
