### ISSUE TITLE
[Shadow Labs Dungeon - Murmur Room and event and boss fight have MULTIPLE issues

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5378]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Boy - lets begin.

1. Way too many extra add spawned
2. Cabal Spellbinder not using MIND control
3. Cabal Summoner's Firebolt is dealing less damage (lower rank spel again..) it should be about 900-1k  as a 70 elite

Murmur:
1. YOU CAN INTERRUPT HIS MURMUR TOUCH

### Expected Blizzlike Behaviour

1. Some extra adds shouldnt be there
2. Cabal Spellbinder uses Mind Control which is interruptable
3. Firebolt does 900-1k damage 

MURMUR CANNOT BE INTERRUPTED

### Source

https://www.youtube.com/watch?v=fxb7QT-1BTE

https://www.wowhead.com/wotlk/npc=18708/murmur#comments;mode:normal

### Steps to reproduce the problem

Do the dungeon

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
> Way too many extra add spawned

All spawns there are sniffed as of https://github.com/azerothcore/azerothcore-wotlk/pull/15635 and as blizzlike as I could make it. Which means:

2 Executioner adds at the entrance along with 2 Summoners with scripted deaths.
3 groups of 4 adds, made up of Executioners, Spellbinders and Summoners
5 ungrouped adds moving around the room
3 Spellbinders holding Murmur

> Cabal Spellbinder not using MIND control

They do, but they don't cast if you're playing solo. That's a very common mechanic to make soloing viable

> Cabal Summoner's Firebolt is dealing less damage

Like in your first point, this data is sniffed and they are using the correct spell.

![image](https://user-images.githubusercontent.com/100873791/232920773-2525a7ef-6e3d-4e3c-b26e-58078ced7daf.png)

> YOU CAN INTERRUPT HIS MURMUR TOUCH

https://github.com/azerothcore/azerothcore-wotlk/pull/16010 :)
