### ISSUE TITLE
[Rogue] Distract interrupts spell casts

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#5385]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Distract interrupts spell casts

### Expected Blizzlike Behaviour

Distract does not interrupt spell casts

### Source

Rogues don't need yet another CC

No mention anywhere that it does
https://www.wowhead.com/wotlk/spell=1725/distract#comments
https://wowwiki-archive.fandom.com/wiki/Distract

This one even says a targeted spellcast gets "interrupted" because the caster is facing another direction at the end of the cast, not because of Distract itself
https://www.wowhead.com/wotlk/spell=1725/distract#comments:id=2746339

### Steps to reproduce the problem

2 Chars
Cast one reasonably long spell with the first one
Use Distract from the other Char

For example:
.cast 688    (Summon Imp)

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=1725

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Paradigmxd** [comment]
I can confirm that - the only thing Distract can interrupt is when a Player is assaulting the Flag in AB for instance ^_

**Comment by Tereneckla** [comment]
> I can confirm that - the only thing Distract can interrupt is when a Player is assaulting the Flag in AB for instance ^_

Got a source that it should interrupt flag capping in AB?

**Comment by Paradigmxd** [comment]
Yeah - Log on Classic and do it with a rogue

**Comment by Tereneckla** [comment]
If it is that easy make a quick video proof

**Comment by Paradigmxd** [comment]
I mean is it worth it, half the time anything I report doesn't get noticed. 
I can't make you a video because it requires a fucking rogue to throw distract at me while assaulting the base, I mean this is something that you'd notice in the Tbc scene.

**Comment by vvranceanu** [comment]
> I can confirm that - the only thing Distract can interrupt is when a Player is assaulting the Flag in AB for instance ^_

can you please link me a mention of this being legal, anywhere on the internet. i dont think someone can he as retarded, not even wow designers

**Comment by Paradigmxd** [comment]
First of all,

What do you even mean game designers like blizz aren't shall we say sometimes crazy at what they coded for spells during different patches. 1 min polymorph? Remember that? 

Second of all, distract interrupts spell cast if player out of combat. The distract also interuptS Mount casting ,which as we know is in the same family of uses like opening a chest i.e if hit spell cast stops.

So, unfortunately I haven't found someone simply stating "hey I'm rogue I can distract capture cast and interrupt it" because it's one of those hard to get things.
Secondly, I can confirm that this used to happen on Tbc classic and was super annoying 

I'm sorry but as of now I can't really show you evidence. I no longer have subscription on Wrath as well.

**Comment by Paradigmxd** [comment]
Another interesting example, that most are familiar ,Blizzard should not be interrupting capture the flag because the scripting for blizzard was "in a way" like a dot, 

So there you go ,more weirdly "retarded" examples
