### ISSUE TITLE
Tirisfal Glades- Hounds daze on first hit

### ISSUE THREAD

**Issue by Cr0m86** [chromiecraft/chromiecraft#539]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

In Tirisfal Glades, every type of hound (e.g. Cursed Darkhound) will daze the player on first hit, no matter the direction of the attack. Tried all different types of hounds and the behavior is the same in all cases. First hit gets you dazed for 9 seconds.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Getting dazed is part of the game of course but there should be a chance per hit to get you dazed, not every hit automatically. According to WoWpedia that should be between 0-40% with smaller chance the lower the level (e.g. level 10 should have about 7% chance to get dazed). Additionally, you should only be dazed if attacked from behind, not any direction. According to patch logs, on patch 3.3.0 the behavior was fixed as follows: 

Wrath of the Lich King Patch 3.3.0 (2009-12-08): Creatures attacking a player from behind can no longer cause players level 1-5 to be dazed, and have a reduced chance to cause players level 6-10 to be dazed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. It's very easy to recreate. Just spawn in Tirisfal glades and get attacked by any type of hound. 
2. 
3. 
4.

##### EXTRA NOTES:

-

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
Related to #61 
They should no longer be able to apply this daze from the front or the side.
Also note that this daze is not the 3 second daze (from behind) implemented in the core which has indeed a "noob" protection.

**Comment by necropola** [comment]
@Cr0m86 I'm going to close this as Duplicate. Feel free to reopen the issue, if
- you have in-game evidence that the daze is actually applied from the front or the side or
- you have proof (a source from the WotLK era) that this daze shouldn't be there at all.
