### ISSUE TITLE
Quest - [5726] Hidden Enemies

### ISSUE THREAD

**Issue by Foosiq** [chromiecraft/chromiecraft#54]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Point of Interest is showing wrong area, I've spent minutes trying to find it before finally realizing what was the problem after watching the video.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

PoI shown in the northeast durotar cave

##### CURRENT BEHAVIOUR:

Quest with broken PoI https://wowgaming.altervista.org/aowow/?quest=5726

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept the quest
2. Check the map where PoI is shown
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
Extra info related to the quest area/areas Skull Rock / Durotar / Dustwind Cave:

- Skull Rock (https://wowgaming.altervista.org/aowow/?zone=817)
- https://wow.gamepedia.com/Skull_Rock
- Dustwind Cave (https://wowgaming.altervista.org/aowow/?zone=371)
- https://wow.gamepedia.com/Dustwind_Cave
- https://wow.gamepedia.com/Lieutenant%27s_Insignia
- https://wow.gamepedia.com/Hidden_Enemies_(quest)
- https://wow.gamepedia.com/Skull_Rock_(quest)
- https://wow.gamepedia.com/The_Burning_Blade_(quest)

**Comment by nicoaravena** [comment]
I don't see any problem 
![imagen](https://user-images.githubusercontent.com/4155059/107151299-92ffe780-6940-11eb-84bd-3994e0020282.png)

Are you referencing the site or the server?

**Comment by nicoaravena** [comment]
The site is good if you check the Durotar map 
![imagen](https://user-images.githubusercontent.com/4155059/107151341-d3f7fc00-6940-11eb-8eb0-600b4d3913cb.png)

**Comment by Helias** [comment]
I confirm that it's invalid, in the Quest POI you can find a lot of orcs that can drop the quest item

**Comment by illfated** [comment]
Maybe there was a time when the NPCs dropping the Lieutenant's insignia could only be found in Skull Rock, but most of the time during TBC & WotLK it could drop from humanoid NPCs in Dustwind Cave (entrance facing Razor Hill, (also a site for warlock quest?)), from Burning Blade NPCs near Fizzle Darkstorm in Thunder Ridge, and from the named Skull Rock inhabitants.
