### ISSUE TITLE
[Steamvault] Some mobs evade from time to time

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#5400]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Currently, some mobs evade in Steamvault. I'm not entirely sure whether it's due to my jumping, but this behaviour doesn't appear in any other dungeon even if I jump. However, I clearly landed after the second jump on the first video after which mobs evaded (and they weren't even targetting me). Note that the mobs, despite evading, kept constantly moving. 

https://user-images.githubusercontent.com/107246426/231467937-611903d6-21d8-4886-a0d4-c7ee15285317.mp4

https://user-images.githubusercontent.com/107246426/231468077-7b563b2f-7fee-4a5c-8e8a-e7ab6a88f2e3.mp4

### Expected Blizzlike Behaviour

Mobs should not evade in the dungeon, even if you jump. 

### Source

.

### Steps to reproduce the problem

1. Pull mobs
2. AoE (Swipe in bear form)
3. *Jumping _might_ be necessary for it to evade

### Extra Notes

I asked the other members of my group and the mobs did not evade them. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Unable to reproduce. It has probably already been fixed.

Thank you for your report anyway. If you find other issue feel free to report them.
