### ISSUE TITLE
[Karazhan] Spectral Performer are not immune to all crowd control and taunts

### ISSUE THREAD

**Issue by v-mstrs** [chromiecraft/chromiecraft#5426]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Not immune to all crowd control and taunts

### Expected Blizzlike Behaviour

immune to all crowd control and taunts

### Source

https://www.wowhead.com/tbc/npc=16473/spectral-performer#comments

### Steps to reproduce the problem

1. .npc add 16473

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/00e42645b8b6

### Operating system

Linux Mint 21.1

### Customizations

None

### Server

Local

**Comment by Si1ker** [comment]
@Gultask  close
