### ISSUE TITLE
Possible issue with Commanding Shout and spells like it.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#5432]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Commanding Shout, a warrior spell that increases max health of party/raid members by a certain amount, also adds health to those players, likely proportional to the percentage of health the character has before the shout goes out.

### Expected Blizzlike Behaviour

Not entirely known, but iirc from my experience no health is given to players when this spell is cast, not even when health is at 100% before the shout.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.learn 469`
2. Cast the spell at various health percentages.
3. Observe the effect it has on your current health.

### Extra Notes

This almost definitely affects other spells with the same effect, not just commanding shout.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
A side effect of this issue is that players (warrior mains, like yours truly) can use this spell as a quick health boost. Relatively small impact, but it definitely exists.

**Comment by vexima** [comment]
comment on wowhead from 2007 confirms that this is indeed blizz-like
> Commanding Shout maintains your current health percentage when it is used or goes away.
https://www.wowhead.com/wotlk/spell=469/commanding-shout#comments:id=135318

so it's working as intended.

**Comment by heyitsbench** [comment]
Will close for now, I do believe something is still wrong with the spell but it may very well not be consistent and I don't currently have the time to investigate it as much as I'd like.
