### ISSUE TITLE
[Stormwind City bugs - Melris Malagan and Justine Demalier are not Interracting with PLAYERS]

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5433]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Melris Malagan and Justine Demalier are not Interracting with PLAYERS

### Expected Blizzlike Behaviour

They talk
1. Recruiting for Highlord Bolvar with Justine Demalier

Justine Demalier says: That one, Malagan. I know <him/her>. Dependable, brave, and trustworthy. <name> is <his/her> name.
Melris Malagan says: <name>, eh? Oy! Citizen <name>, come 'ere. Bolvar Fordragon has requested that all able bodied heroes o' the Alliance meet with him at Stormwind Keep. You just been recruited, mate! Get a move on!

2. When the death knight player first enters the city
How dare you set foot in our city!
Murderer!
You disgust me.

### Source

https://wowpedia.fandom.com/wiki/Melris_Malagan?so=search

### Steps to reproduce the problem

Teleport to NPC IDS 12480 and 12481

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Santaria94** [comment]
This event is the trigger to get the quest "The First and the Last". However, my guess is that this event was removed with the release of Wotlk after Varian became the questgiver for this quest.

https://www.wowhead.com/tbc/quest=6182/the-first-and-the-last#comments
>By Apotheoun on 2008/06/13 (Patch 2.4.1)		
>1. You do need exalted to be offered this quest.
>2. You do not need to be 'recruited' by the two soldiers standing in the city center first.  That's just a bit of color.  Also, they will start spamming the "recruitment" text as soon as you hit exalted, but this does not mean you can get the quest.  See point 
>3. You do need to be level 56 or higher.
>4. The quest is obtained in the royal throne room.  Turned in in the rogue's guild on the second floor.

https://www.wowhead.com/quest=6182/the-first-and-the-last
>By 78426 (2,389 – 12·33) on 2008/10/02 (Patch 3.0.1)		
Right now in beta, Varian Wrynn gives out this quest since Bolvar is in Northrend.

>By 395903 (1,406 – 2·26) on 2009/06/19 (Patch 3.1.3)		
How do you get this quest I stood next to those 2 npcs in Stormwind City but nothing happened. And anyway Bolvar is dead he died at the wrath gate. So what do I do is there a pre-quest

**Comment by heyitsbench** [comment]
Can't get these NPCs to talk on the Classic PTR, doesn't look like this issue is valid for 3.3.5.

**Comment by avarishd** [comment]
> doesn't exist in 3.3.5

Can close?

**Comment by FrancescoBorzi** [comment]
Closing this as it looks like not much to do here. Please leave a comment if you think this is a mistake.
