### ISSUE TITLE
[Shadow Labs] Cabal Assassins

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5438]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Cabal Assassins spawned in Blackhearts room before killing Ambassador Hellmaw

### Expected Blizzlike Behaviour

All tbc sources explain that the Cabal Assassins in Blackhearts room only spawn once the first boss Ambassador Hellmaw has been killed.

There is a single source from 3.3.3 stating that they are actually spawned ahead and not linked to the boss. It would make sense to cross check this on the wotlk ptr.

apparently also respawn periodically.

### Source

Sources for spawn only after boss is killed:
https://youtu.be/kXLuDZnJLc0?t=90
https://www.wowhead.com/wotlk/npc=18636/cabal-assassin#comments:id=31846

Source for independent spawn
https://www.wowhead.com/wotlk/npc=18636/cabal-assassin#comments:id=1022146

respawn periodically:
https://wowwiki-archive.fandom.com/wiki/Shadow_Labyrinth
> Assassins appear to spawn periodically; the longer you spend in the entry to Blackheart's room, the more times you will see them spawn. 

### Steps to reproduce the problem

.

### Extra Notes

https://www.wowhead.com/wotlk/npc=18636/cabal-assassin

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Si1ker** [comment]
Invalid

![image](https://user-images.githubusercontent.com/61223313/232662336-9e035498-8535-4ca8-a0da-8cc4b6c245c5.png)
https://www.wowhead.com/npc=18636/cabal-assassin#comments:id=1022146

**Comment by Gultask** [comment]
They have looong waypoints and are found before the boss is engaged, I'm sure of it.
I actually had a lot of trouble finding them both in Retail and Classic but they're there. It's actually very easy to mistake it for respawning if you lose track of them.

An easy way to tell if they respawn is checking the rep reward on kill. Anything higher than 3 doesn't respawn.

**Comment by balleny** [comment]
I added the bug report specifically, because all sources from TBC pointed towards a delayed spawn, and only 1 single source i could find so far said that they are already spawned before the first boss is defeated - the sources are all in the initial bug report, everything is stated in the ticket already, no need to repeat the information.

As also stated in the bug report, a PTR check would make sense assuming that this wasnt point of attention during the data gathering. Further, it seems to affect only the assassins spawned / pathing in the room of the second boss, not other parts of the dungeons.

And yes, this is a low prio but imo could be subject of confirmation in case anyone is running slabs on the ptr anyway.

**Comment by Gultask** [comment]
I have them logged from when I did an initial sweep of the dungeon. In that one I didn't engage Hellmaw, only passed by him, so they definitely do spawn before he's engaged.

```
Entry: 18636
Leader: False
[0] Name: Cabal Assassin
Type Flags: 0 (None)
Creature Type Flags 2: 0
CreatureType: 7 (Humanoid)
CreatureFamily: 0 (None)
Classification: 1 (Elite)
```

**Comment by Si1ker** [comment]
> I have them logged from when I did an initial sweep of the dungeon. In that one I didn't engage Hellmaw, only passed by him, so they definitely do spawn before he's engaged.
> 
> ```
> Entry: 18636
> Leader: False
> [0] Name: Cabal Assassin
> Type Flags: 0 (None)
> Creature Type Flags 2: 0
> CreatureType: 7 (Humanoid)
> CreatureFamily: 0 (None)
> Classification: 1 (Elite)
> ```

There's only 2 of them in the instance in wotl classic / pt r?
