### ISSUE TITLE
[druid] Dash is usable outside Cat Form

### ISSUE THREAD

**Issue by ninjaskija** [chromiecraft/chromiecraft#5452]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Dash skill is usable outside Cat Form

### Expected Blizzlike Behaviour

Dash should not be usable outside Cat Form

### Source

https://postimg.cc/kRyFT7hw

### Steps to reproduce the problem

1. Log is with a druid that has Dash skill learned
2. Use Dash outside Cat Form

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
The Source field is providing a source for your claim, not proving the current behavior

The tooltip  supports being able to use Dash outside of Catform
![image](https://user-images.githubusercontent.com/50233983/233055814-6660f551-259c-4b77-bb86-a1ec2e07c14e.png)

**Comment by Apathyxia** [comment]
To my understanding, Dash is *usable* outside of cat form, however, it only provides the movement speed increase while in cat form.

**Comment by Never6** [comment]
Dash is useable outside cat form however the speed bonus is only applied in cat form

**Comment by ninjaskija** [comment]
I know but it is still a bug, meaning you should not be able to use the skill outside Cat Form. Contributes to the overall feeling/experience.

**Comment by Tereneckla** [comment]
> I know but it is still a bug, meaning you should not be able to use the skill outside Cat Form. Contributes to the overall feeling/experience. @Tereneckla thanks for the clarification!

As I said, you have not provided any proof that it should not be able to be used outside of Cat Form

**Comment by ninjaskija** [comment]
@Tereneckla here is a screenshot from WotLK Classic which I made today with the error message when using Dash skill https://postimg.cc/8FCqB1Nb

**Comment by Tereneckla** [comment]
Thank you very much

**Comment by Never6** [comment]
> Thank you very much

Pretty sure it's bugged on wrath classic. I have played every wrath private server and I am able to use dash outside cat form on every single one of those
If we gonna start using classic wrath as the end all be all of sources might all well make faerie fire proc clearcasting 100% of the time since that's how it is on classic

**Comment by Tereneckla** [comment]
Sometimes it is the best source we have.
There also are enough things that were wrong on every wrath private server

**Comment by Never6** [comment]
> Sometimes it is the best source we have.
> There also are enough things that were wrong on every wrath private server 

Yes because a modified legion client is totally accurate to 3.3.5 client
Classic really isn't that good of a source because of this
Everything works differently
That's why my macros I used in vanilla wow don't work on a 1.12 client
