### ISSUE TITLE
Enhancement Shaman Improved Windfury Totem not applying 4% haste

### ISSUE THREAD

**Issue by howboutabeer** [chromiecraft/chromiecraft#546]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I have specced into improved windfury totem, 2 points for +4% melee haste. When I look at the ability tooltip it accurately reflects the 20%, however when I drop the totem I am only receiving the base 16% melee haste rendering those 2 talent points useless. I have attached screenshots below: 

![image](https://user-images.githubusercontent.com/83741540/117235376-735f4a80-addb-11eb-90d3-345bf448f607.png)

![image](https://user-images.githubusercontent.com/83741540/117235428-8a9e3800-addb-11eb-9262-6faf9852d02b.png)

![image](https://user-images.githubusercontent.com/83741540/117235746-2760d580-addc-11eb-98e5-9a3f33eb644b.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should be giving the full 20% if you have 2 talent points in improved windfury totem

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Keep up the awesome work, I've been having so much fun so far. Thank you so much!

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
I think it's just that the tooltips are not updated (it's the same with several other "talent boosted" spells).
I've tried with my shamy who also has Improved WF totem specc'd, it seems to work:
- base attack speed: 3.10 ;
- with improved WF totem: 2.58
- ratio is: 3.10/2.58 = 1.20

Screenshots:
![WoWScrnShot_050621_081812](https://user-images.githubusercontent.com/81818678/117250765-fe742b00-ae43-11eb-8c1b-4b68e40e62cb.jpg)
![WoWScrnShot_050621_081825](https://user-images.githubusercontent.com/81818678/117250770-ff0cc180-ae43-11eb-84dd-6401e35e3ac8.jpg)

**Comment by necropola** [comment]
There are multiple known client-side tooltip issues especially with talents that improve spells/buffs. and as @pop-pig demonstrated, it's usually best to check your character sheet in order to figure out, if a spell/buff/talent is working correctly.

Since the talent itself appears not to be bugged (thanks, @pop-pig) and we can't do anything about display inconsistencies in the client, I'll go ahead and close this issue.

Nevertheless, thanks for your report. It's essential to have watchful players when you want to find and fix as many bugs in AC as possible.
