### ISSUE TITLE
The Dead Fields quest not completable

### ISSUE THREAD

**Issue by asdff134242** [chromiecraft/chromiecraft#5472]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

[The Dead Fields][0] requires one to both enter the Dead Fields and to kill Nightlash to collect the Essence of Nightlash. However, the "enter the Dead Fields" objective never completes when entering the area, even after exiting and reentering it. This prevents completing the quest and turning it in.

[0]: https://wowgaming.altervista.org/aowow/?quest=437

### Expected Blizzlike Behaviour

The "enter the Dead Fields" objective should be completed upon entering the Dead Fields area:

https://www.youtube.com/watch?v=XztwCwTeSME&t=135s

There are no comments about this part of the quest not completing properly on Wowhead:

https://www.wowhead.com/classic/quest=437/the-dead-fields

### Source

https://www.wowhead.com/classic/quest=437/the-dead-fields

### Steps to reproduce the problem

1. Pick up The Dead Fields from High Executor Hadrec in The Sepulcher.
2. Go to the Dead Fields and kill Nightlash.
3. Pick up the Essence of Nightlash.
4. The quest will not be fully completed because the "enter the Dead Fields" objective is not completed.

### Extra Notes

![image](https://user-images.githubusercontent.com/131519988/233773007-7c23a2e0-066d-4655-9d34-ec200a8ce839.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Windows 10 build 19042.630

### Modules

- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Velomania** [comment]
Up because I like leveling in the Silverpine Forest. Idk how exactly it has been broken, but it was working perfectly before.

**Comment by KhobarKast** [comment]
Confirmed, same behavior here as well, the quest won't complete.

**Comment by 7Katta** [comment]
Agree with others, I cannot complete. Have killed Nightlash numerous times, but "Enter the Dead Fields" doesn't complete when I enter the Dead Fields.  *sob*
