### ISSUE TITLE
[Terrokar Forest - Allerian Stronghold Bugs - Eckert the Party Gnome Missing Dialogue]

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5499]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

Eckert just dances without periodically saying 'its time to party'

### Expected Blizzlike Behaviour

Should often say 'It is time to party'

### Source

https://www.wowhead.com/wotlk/npc=21400/eckert#comments

### Steps to reproduce the problem

Teleport to Eckert at Allerian Stronghold 
Observe if the party gnome says anything.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Santaria94** [comment]
Are you sure that he should systematically pronounce this text?
I saw the use of this text as part of the implementation from TrinityCore of the event after the completion of the quest "The Final Code"
![333](https://github.com/chromiecraft/chromiecraft/assets/32459796/0772af96-c2b6-437b-a003-d9a479b1ea77)

**Comment by Paradigmxd** [comment]
Hi, 

This gnome says his quote upon the final code for sure, but that doesn't work alongside the night elf that is part of the final event in the stronghold.

So in any case he doesn't use his quotes.

I remember him particularly because he would dance all the time and I have caught him say something on Tbc classic.

**Comment by heyitsbench** [comment]
He definitely dances on Wrath Classic, but it does seem that he has no quotes while idle.

**Comment by Cythisiax** [comment]
> He definitely dances on Wrath Classic, but it does seem that he has no quotes while idle.

Confirming this too, does not have idle quotes.

**Comment by TheSCREWEDSoftware** [comment]
From the triages above, it seems he only dances, I will be closing this issue, if this issue comes in the future and you've additional information about, be free to re-open this one or open a new one mentioning this one, thanks for reporting.
