### ISSUE TITLE
Burning Blade Apprentice - Summon Voidwalker

### ISSUE THREAD

**Issue by Foosiq** [chromiecraft/chromiecraft#55]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Summoned voidwalker by Burning Blade Apprentice is aggro-ed only when close range, pulling the apprentice with ranged attack/spell will not trigger the voidwalker and he will just stay near the NPC even tho I'm in combat with the Apprentice.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Pet (voidwalker in this case) should start attacking the player together with the NPC owning the pet.

##### CURRENT BEHAVIOUR:

Apprentice: https://wowgaming.altervista.org/aowow/?npc=3198
Voidwalker: https://wowgaming.altervista.org/aowow/?spell=12746

##### STEPS TO REPRODUCE THE PROBLEM:

1. Cast the spell on the NPC at max range
2. See how the voidwalker just stays idle
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
Yes, this is a real issue, thanks for the report.

**Comment by bonfax4** [comment]
This is a issue with every npc with a pet.

**Comment by nicoaravena** [comment]
Yes, you are right.

**Comment by Stifler82** [comment]
Fixed
-

https://user-images.githubusercontent.com/1884642/108665042-e7bc6a00-74cb-11eb-80b5-7a300d0b4da7.mp4
