### ISSUE TITLE
[Furbolg Medicine Pouch] from Timbermaw Hold reputation dont work the effect of the item

### ISSUE THREAD

**Issue by tarshel** [chromiecraft/chromiecraft#550]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ +] enUS
- [ ] other (specify)

##### FACTION

- [ +] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ +] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.  The item  [Furbolg Medicine Pouch] from Timbermaw Hold reputation dont work when u click to use the effect of the item it says am not hight level ... The item can be use at low level.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here. The item can be use at low level. is biss offhand at low levels

##### STEPS TO REPRODUCE THE PROBLEM:

1. fix the item to use the effect
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I've checked this item on WOTLK-DB, and although you can indeed equip the item at low levels, it apears that you should not be able to use the spell on it before level 50.

Item: https://wotlkdb.com/?item=16768
Spell: https://wotlkdb.com/?spell=20631 - note the 'level 50' requirement.

This is backed up by comments on TBC Wowhead - "I got it with my level 19 warlock [...] You can not use the health but the 10 stamina are enough." - https://tbc.wowhead.com/item=16768/furbolg-medicine-pouch#comments:id=2688444

"Be aware though: While you CAN equip the pouch with lvl 10, the use effect CANNOT be activated." - https://tbc.wowhead.com/item=16768/furbolg-medicine-pouch#comments:id=201879

If you can find some evidence that the heal on the pouch could be used by a character below level 50, fee free to send it along.
