### ISSUE TITLE
[TBC, Draenei Starting Zone]

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5503]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

1. Warrior training quest incorrectly offered at level 1 - should be 2.  https://wowwiki-archive.fandom.com/wiki/Quest:Warrior_Training

2. Healing the Draenei Survivor NPCs for Rescue the Survivors! flags for PvP (this one could be a problem if population increases, griefing opportunity)
https://www.wowhead.com/quest=9283/rescue-the-survivors

3. Nestlewood Owlkin when giving the emote indicating they should become aggressive instead "level up" complete with golden swirl and level up sound.  https://www.wowhead.com/npc=16518/nestlewood-owlkin#comments  https://www.wowhead.com/quest=9303/inoculation

UPDATE - out of curiosity, I replayed the zone to check these out again.  This seems to be two separate minor oddities.  The Nestlewood Owlkin don't aggro as expected for sure, but the "level up" animation happens about 50% of the time regardless of what emote the NPC uses.  Might just leave that, it's randomly funny.  :) 

4. Techician Zhanaa does not display the ! icon for her final quest, Travel to Azure Watch.  (https://www.wowhead.com/quest=9313/travel-to-azure-watch)

UPDATE - On retest I noticed that after turning in the previous quest, the ! icon displays for a fraction of a second before the scene starts and never reappears once it has completed.  This might be an issue/conflict with whatever is auto-accepting the 1-5 zone quests, in that case.

### Expected Blizzlike Behaviour

1.  Warrior training should be available at level 2
2.  Healing the Draenei survivors should NOT flag for PvP
3.  Nestlewood Owlkin should attack when emoting they didn't like that.
4.  Technician Zhanaa should display the ! icon for Travel to Azure Watch after the transmitter scene completes.

### Source

Personal experience +the WoWHead links for each issue above.

### Steps to reproduce the problem

These can all be verified quickly with a newly rolled warrior - 

1. Create a new Draenei Warrior - observe that Warrior Training is immediately available.
2. Pick the nearest Draenei Survivor and heal them with gift of the naaru.  Observe that you are flagged for PvP
3.  During the quest Inoculation, observe the Nestlewood Owlkin will sometimes "level up" when they should have become aggressive.
4.  Complete quest The Emitter
6.  Report to Technician Zhanaa and observe the cutscene.
7. Note no ! above her head.
8. Right-click her anyway and she will offer the quest Travel to Azure Watch.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Window 10 Home 21H2

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Firstly, thanks for the reports! I do ask that each individual issue you find be raised in their own individual reports. Going through your issues:
1: According to the [Wrath Wowhead page for the quest](https://www.wowhead.com/wotlk/quest=9289/warrior-training), the quest does in fact require level 1 as opposed to level 2. CC behavior seems to be blizzlike.
2: I have a feeling this is related to a possible hackfix done at one point involving the priest quest NPCs being given a PvP flag to make them healable/buffable, causing the player to become PvP flagged. Would appreciate a better source for this issue, but intuition says CC behavior is not blizzlike.
3: This seems to [already be reported](https://github.com/chromiecraft/chromiecraft/issues/3775), but the hostility is not, only that they turn neutral. Would also appreciate a better source on that, but otherwise CC behavior is not blizzlike. Note: Keep in mind that Wrath changed hostility of certain starter area mobs to neutral, such as the Defias in Northshire or the spiders in Shadowglen, this may be a similar case.
4: Are you sure that the quest wasn't too low level to the point where you'd have to tick 'Low Level Quests' tracking to see it displayed like that? If not, this may be symptomatic of a greater issue, would also prefer a better source on that.

**Comment by Vyperhand** [comment]
Thank you for the feedback - I'll make sure to break them out in the future.  I'll leave this one as the report for # 2 and recreate #4 with your feedback there.  1 and 3 are too minor to spend further energy on so they can be disregarded.

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️

**Comment by heyitsbench** [comment]
I was mistaken, it seems the (second) issue has already been reported at https://github.com/azerothcore/azerothcore-wotlk/issues/16319#issuecomment-1553712429, making this a duplicate. I apologize for the confusion.
