### ISSUE TITLE
Opening Big-Mouth Clams with full inventory space results in Clams loot drop being destroyed

### ISSUE THREAD

**Issue by Beastmasterwow** [chromiecraft/chromiecraft#551]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

My bags were full and I was opening Big-Mouth Clams and item/s inside the Clam got destroyed, it happened 2 times. Clams where looted from Naga Explorers in Stranglethrone Vale.
Link to the Big-Mouth Clam: 
https://wowgaming.altervista.org/aowow/?item=7973

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If there is insufficient inventory space for the contents of the clam (both the meat and the pearl, if there is one), the clam will simply remain in your inventory and the opening will "fail."
Quote is from this link: https://wowpedia.fandom.com/wiki/Clam

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have full bags
2. Go to STV and kill Naga Explorers and loot Big-Mouth Clam or you can test is from somewhere else.
3. Try to open the clam with full bags.
4. Conclusion 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Beastmasterwow** [comment]
Someone should test other things like satchels, bags, containers etc.

**Comment by necropola** [comment]
Tested on a current local AC server with a bag full of **Big-mouth clams**.
I'm getting an **Inventory is full** error message and the clam stays in my inventory. 

![image](https://user-images.githubusercontent.com/7461137/117565583-41d3d100-b0b2-11eb-8d59-fdb506555c9a.png)
