### ISSUE TITLE
"the big bone worm" quest

### ISSUE THREAD

**Issue by morpez121** [chromiecraft/chromiecraft#5514]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

Big bone worm disappears also if you kill it. So you can't loot it for the requested quest item.
5 time the big worm spawned for me:
- three times it went underground (as a Shy'ulud is expected to do) and disappeared before I managed to kill;
- two times I manage to kill it (yes I'm sure) but the worm disappeared underground with no possibilities to loot it.

### Expected Blizzlike Behaviour

don't know

### Source

NPC Dwarfowitz
quest "Fumping" and then quest "The Big Bone worm"

### Steps to reproduce the problem

1 go Terokkar Forest, Sha'tari base camp at Auchindoun south west
2 get the quest Fumping, do it near the camp itself, then get the quest "the big bone worm"
3 go at Auchindoun (est side, where Kodoes are)
4 Kill a Kodo; use your drum to evoke mobs of various type
5 repeat step 4 until a Big Bone Worm spawns
6 try to kill it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Windows 111

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by kerricsson** [comment]
Just a friendly ask for triagers to triage this issue, since bug was confirmed at CC discord. Thanks in advance.

**Comment by Stump876** [comment]
Hi Morpez121, thanks for the report. I can confirm this on a clean AC. Seems like the spawns hang around for 1 minute before despawning killed or not.
