### ISSUE TITLE
Challenge HC/IM/BT Hunter's Pet's talent's points

### ISSUE THREAD

**Issue by Gundisal** [chromiecraft/chromiecraft#5533]
### What client do you play on?

esES

### Faction

Horde

### Content Phase:

40-49

### Current Behaviour

Simply: I don't know since when, but now i can use my pet's talent's points. Just tried when i reached level 46

### Expected Blizzlike Behaviour

In Iron Man challenge you shouldn't be able to use any talent point on you or on your pet.

### Source

![WoWScrnShot_043023_173544](https://user-images.githubusercontent.com/132215316/235362874-a6b99a1b-8ecb-4c81-b01f-76c5e71991fa.jpg)

### Steps to reproduce the problem

1. Enable "Preview Talent Changes" at Menu -> Interface -> Features
2. Open your pet's talent's tree
3. Asign talent's point

### Extra Notes

Thanks to ElmoMcG/Kayshahc and PonytailHC for helping to reproduce the bug

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
CC: @r-o-b-o-t-o

**Comment by ElmoMcG** [comment]
Hello, I'm trying to help Gundisal/Zorgo discover the cause of this issue. We are both 3/3 hunters. I'm KayshaHC below.

We tried the following ideas:
 - Turning level 46: 
      - Zorgo accidentally discovered this issue after turning level 46
      - KayshaHC tested after each level up from level 42-46 and cannot set pet talents
 - Lower level pet (than player):
      - Zorgo can set pet talents
      - KayshaHC cannot
- Pet species:
     - Zorgo can set pet talents on carrion bird, wolf, spider, and bear
     - KayshaHC cannot set on carrion bird, wolf, cat
 - enUS client vs non-enUS client:
     - Zorgo can set on esES client using Roboto's patch-Z.mpq file (for non-enUS clients posted on Discord)
     - KayshaHC tested on enUS, esES, esMX, enGB clients using default patch-Z.mpq and non-enUS patch-Z.mpq files and still cannot set pet talents.

Maybe my non-enUS client testing is missing something, because we can't think of anything else different from Zorgo and KayshaHC client-server interactions. We have asked a few other 3/3 hunters if they can/cannot set pet talents and the only thing we have found in common is that enUS hunters cannot set and non-enUS clients _can_ set pet talents.

Please let us know if there's anything else you'd like us to try and help triage.

**Comment by ElmoMcG** [comment]
It looks like the community has already figured out how to set pet talents. It's by using the "Preview Talents" feature. 


https://user-images.githubusercontent.com/127156002/236104349-ff8323fc-4a33-4a09-b5fe-334a5418a333.mp4

**Comment by ElmoMcG** [comment]
After making this clip, I hearthed to Orgrimmar to reset my pet talents :)
