### ISSUE TITLE
[Blackwing Lair] Ebonroc keeps following its path even in combat

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#5536]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

60

### Current Behaviour

After engaging Ebonroc in combat, it kept moving back and forth its path it traverses when not in combat. It just stopped to use its abilities and kept going on.

https://user-images.githubusercontent.com/107246426/235371559-9e0f2adb-05e4-42a0-98d6-2eed6c8ac0f3.mp4

### Expected Blizzlike Behaviour

Ebonroc should be fixated on the highest threat target and be stationary instead of moving around. 

### Source

Any video about the fight on YouTube, so here's the first one: https://www.youtube.com/watch?v=u6qIcQNELhs

### Steps to reproduce the problem

1. Exact steps to reproduce are not clear as we just engaged Ebonroc in fight normally (we skipped the 3 big dragonkins before the boss).
2. Right after we attacked, it kept moving. 

### Extra Notes

When I used shadowmeld, it switched targets - after I got out of Shadowmeld, it stayed stationary as it should have initially.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I tested the issue on ptr and seems that Ebonroc hasn't this bug. Maybe has been fixed time ago.

Thank you for the report. If you find other bugs feel free to report them.

**Comment by Rorschach91** [comment]
Oh, Thank you  @heyitsbench. I forgot to close it.
