### ISSUE TITLE
[Children's Week] Back to the Orphanage bugged

### ISSUE THREAD

**Issue by creativemonkeyz** [chromiecraft/chromiecraft#5539]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

In Caverns of Time, after finish [Time to Visit the Caverns] quest, Draenei Orphan NPC should give Back to the Orphanage quest in order to return to Shattrath.
Current Behavior: After Finishing [Time to Visit the Caverns] quest, Draenei Orphan does not give Back to the Orphanage quest.

### Expected Blizzlike Behaviour

Expected Behavior: After Finishing [Time to Visit the Caverns] quest, Draenei Orphan does must give Back to the Orphanage quest.

### Source

(https://www.wowhead.com/tbc/quest=10966/back-to-the-orphanage)

### Steps to reproduce the problem

1. Complete [Time to Visit the Caverns]
2. While orphan out, no quest appear.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ken748** [comment]
i have the same problem on character Shele

**Comment by Tereneckla** [comment]
The problem seems to be that Call on the Farseer (10968) requires 10962 to take

**Comment by creativemonkeyz** [comment]
Yes, @Tereneckla is right, the problem seems to be the order of quests. In the moment of bug creation, I did not known about the quest that appeared after i completed [Time to Visit the Caverns] in caverns of time.

**Comment by Gultask** [comment]
The requirement to complete Call on the Farseer (10968) is blizzlike, but it seems that we can't pick up the quest properly

**Comment by ken748** [comment]
just do Time to Visit the Caverns first then The Seat of the Naaru.  I was then able to pick up Call on the Farseer   cheers
