### ISSUE TITLE
 [High Warlord's Scaled Chestpiece] isn't 'transmogable'

### ISSUE THREAD

**Issue by JoaoLisot** [chromiecraft/chromiecraft#5543]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

![BUG](https://user-images.githubusercontent.com/128121489/235564281-89a47d34-9fd5-409a-a757-222e3b9a41cd.png) isn't 'transmogable', it is in my inventory for a couple days now, can't refund, but it simply doesn't add in my transmog list, but kinight captain does. im horde

### Expected Blizzlike Behaviour

i should be able to transmog it

### Source

literally my in game inventory. every plate item i equip gets into my transmog[], except this one piece. have no idea why.

### Steps to reproduce the problem

buy ** [High Warlord's Scaled Chestpiece] **, wait for it to run the timer out, equip and see that nothing pops in chat as it should be '  [High Warlord's Scaled Chestpiece]' has been added into your transmog list. please help this is the last piece i need to begin playing

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Follow this tutorial than tell me if It worked.

![Desktop Screenshot 2024 08 11 - 19 16 07 97](https://github.com/user-attachments/assets/c7d4d3f4-5bf7-4bf6-99e3-e6c766af7370)
