### ISSUE TITLE
[LBRS] Overlord Wyrmthalak missing items from loot table

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#5544]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

50-59

### Current Behaviour

[Overlord Wyrmthalak](https://wowgaming.altervista.org/aowow/?npc=9568) misses [Chillpike](https://wowgaming.altervista.org/aowow/?item=13148) and [Heart of the Scale](https://wowgaming.altervista.org/aowow/?item=13164) from its loot table, as well as green items.

AzerothCore rev. 2ee046bfde0e+ 2023-04-19 01:55:35 +0000 (master branch): 

![image](https://user-images.githubusercontent.com/107246426/235621970-0fa393bc-fa12-4034-a861-cdf52a54cbeb.png)

### Expected Blizzlike Behaviour

[Chillpike](https://www.wowhead.com/wotlk/item=13148/chillpike) should be ~1% drop rate from [Overlord Wyrmthalak](https://www.wowhead.com/wotlk/npc=9568/overlord-wyrmthalak). 
[Heart of the Scale](https://www.wowhead.com/wotlk/item=13164/heart-of-the-scale) should be ~0.8% drop rate.

### Source

https://www.wowhead.com/wotlk/npc=9568/overlord-wyrmthalak

### Steps to reproduce the problem

1. Go into LBRS
2. Kill Overlord Wyrmthalak
3. Loot it

### Extra Notes

I think the NPC should also have a 100% chance on a random green item: https://www.wowhead.com/wotlk/npc=9568/overlord-wyrmthalak#comments:id=347020

Also the drop chances of items seem a bit off. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
The comments on that threat say it doesn't drop anymore. The first one essentially confirmed and the latter one is also doubtful according to some. I will close this until otherwise proven.
