### ISSUE TITLE
[Zul'Farrak] Sergeant Bly and his party do not use hearthstone if not talk with Sergeant Bly/Weegli Blastfuse for 2 mins

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#5546]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

40-49

### Current Behaviour

Quest: https://wowgaming.altervista.org/aowow/?quest=2768
NPC: https://wowgaming.altervista.org/aowow/?npc=7604
NPC: https://wowgaming.altervista.org/aowow/?npc=7607
NPC: https://wowgaming.altervista.org/aowow/?npc=7605
NPC: https://wowgaming.altervista.org/aowow/?npc=7606
NPC: https://wowgaming.altervista.org/aowow/?npc=7608

Sergeant Bly and his party do not use hearthstone if not talk with Sergeant Bly/Weegli Blastfuse for 2 mins.

### Expected Blizzlike Behaviour

Sergeant Bly and his party should use HS after 1-2 mins if players are not enganing them.

### Source

https://www.youtube.com/live/-nVNT3anBP4?feature=share&t=11711

https://www.wowhead.com/classic/quest=2768/divino-matic-rod#comments - By 6020 (877 – 1·9) on 2007/01/28 (Patch 2.0.6)		
There is an easy way to take out Bly and his crew after you've finished off all the spawns.
(after you have the Demolition guy blow up the door to the last boss that is)
Wait for them to begin to Hearthstone (yes if you wait long enough Bly and his gang will begin to hearth away).
Then talk to Bly at the last second and his teammates will continue to hearth and leave.... leaving only Bly to kill.

https://wowpedia.fandom.com/wiki/Sergeant_Bly%27s_party - If you decide to ask Weegli to open the doors, Bly's party will begin to use their hearthstones after 1-2 min. If timed correctly, you can attack Bly alone as he hearths out, greatly reducing the fight's difficulty.

### Steps to reproduce the problem

1. Go to Zul'Farral.
2. Free Sergeant Bly  and his party at pyramid.
3. Kill all mobs + boss and wait to Sergeant Bly and his party to come down.
4. Do not do nothing for 2 mins - observe that NPC will stay in place instead of using their HS.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. 42848897d1e3 2023-04-26 20:49:57 +0000 (master branch) (Unix, Debug, Static)

**Comment by Paradigmxd** [comment]
Can confirm this is true - They DO NOT hearthstone.

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
