### ISSUE TITLE
[Dungeon] Incorrect Respawn Behaviour - No respawn when zoning in after wipe

### ISSUE THREAD

**Issue by Testbaby02** [chromiecraft/chromiecraft#555]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Zoning into the dungeon your body is in, as a ghost, does not resurrect you.
You are able to walk through the dungeon in ghost form.
Reaching your body inside the dungeon gives you a normal resurrection prompt, but accepting it does nothing.
The only way to ress is to use a spirit healer.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Zoning into a dungeon as a ghost should instantly resurrect you.

##### STEPS TO REPRODUCE THE PROBLEM:

As this bug has only happened to me once, I can only describe the steps that happened beforehand, not how to reproduce it. Testing this would require intentionally wiping a group of players and I cannot do that.
1. Join a dungeon via RDF
2. Have a full party wipe
3. While walking back to the dungeon portal as a ghost, leave the party
4. Zone in
If the bug happens, you will now be a ghost inside the dungeon instance, able to freely move within it. Reaching your body will give you a useless respawn prompt, which will have no effect.

##### EXTRA NOTES:

![WoWScrnShot_050621_233536](https://user-images.githubusercontent.com/83083464/117369679-8c442a80-aec5-11eb-863c-82ffe4d24dbe.jpg)

![WoWScrnShot_050621_233855](https://user-images.githubusercontent.com/83083464/117369704-936b3880-aec5-11eb-988b-f4939c3fbbb6.jpg)

Video of the useless respawn prompt:
https://imgur.com/p2vc9aa

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment]
The issue is not that you are not resurrected.

Standard RDF behavior should be as per below:

1. Die while in a RDF group - inside the dungeon
2. While dead, leave the group.
3. When you try to use the Instance entrance portal - you should be Teleported and resurrected at the point from where you entered RDF.

As a note on that - not even blizzard made it work 100% and it will still throw out errors like the described one from time to time.

**Comment by 55Honey** [comment]
https://github.com/chromiecraft/chromiecraft/issues/569
Seems related?
