### ISSUE TITLE
[NPC Buddy is being wrongly killed by Bog Giants]

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5551]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour
![WoWScrnShot_050423_154158](https://user-images.githubusercontent.com/100602999/236242776-b951a25e-6774-4c33-8afb-a1abb6af407f.jpg)
![WoWScrnShot_050323_213216](https://user-images.githubusercontent.com/100602999/236242786-24589202-bafe-4e07-a3f9-4d789fdc043a.jpg)

NPC Buddy the panther gets wrongly killed by Bog giants

### Expected Blizzlike Behaviour

Never has this happened in WoW.

He stays near his master - Watcher Leesa Oh

### Source

https://www.wowhead.com/wotlk/npc=17953/buddy

### Steps to reproduce the problem

Teleport to NPC 17953 in Zangarmash and see if he gets killed by bog giants after some time

I suspect it is after the completion of the last quest https://www.wowhead.com/wotlk/quest=9709/stealing-back-the-mushrooms

When Watcher and buddy go to plant the Mushroom!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/590dcca82b9c6e5d5f49fb5f954b084a88070f84

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Paradigmxd** [comment]
Just did the last quest STEALING BACK THE MUSHROOMS as stated above - indeed when they go to plant the mushroom buddy stays there, then gets destroyed by Bog Giants which has never happend before

**Comment by Paradigmxd** [comment]
Basically - instead of going back to the tent where they stay - he MARCHES forward toward the Field with Bog Giants... and then gets killed lol

**Comment by alecsci** [comment]
Hi @Paradigmxd,
Thanks for you report !
Based on your source I found this comment https://www.wowhead.com/wotlk/npc=17953/buddy#comments:id=419187 and also https://www.wowhead.com/wotlk/quest=9709/stealing-back-the-mushrooms#comments:id=8079:reply=27680
Buddy being attacked by Bog Lords is not a bug, since on retail also happened to be attacked.

Also, given the distance where the Bog Lords where are spawned vs where Buddy patrols in CC I couldn't reproduce it either.
