### ISSUE TITLE
Mai'Zoth does not cast Frost Armor.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#5556]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

40-49

### Current Behaviour

Mai'Zoth does not cast Frost Armor according to his [AoWoW page](https://wowgaming.altervista.org/aowow/?npc=818).

### Expected Blizzlike Behaviour

He should cast Frost Armor.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.go c id 818`
2. Observe his lack of armor of frost.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/590dcca82b9c6e5d5f49fb5f954b084a88070f84

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gchekenny** [comment]
Tested, he does not use frost armor
![WoWScrnShot_061623_223931](https://github.com/chromiecraft/chromiecraft/assets/65800273/b2b57e00-1f03-4dae-9ec7-8a6cbfb76907)


However frost armor is listed as "controlled ability" https://wowgaming.altervista.org/aowow/?npc=818#controlled-abilities and when you mind control him you'll get it.
![WoWScrnShot_061623_224549](https://github.com/chromiecraft/chromiecraft/assets/65800273/9aee1b2c-f70f-4093-b9ab-efe1e2b44b2b)


cancel mind control and he'll keep the frost armor buff
![WoWScrnShot_061623_224605](https://github.com/chromiecraft/chromiecraft/assets/65800273/a7e69c08-e08e-4b19-8411-edb602e20aa2)


Can't find evidence of frost armor without mind control in wowhead comments, but found this video with frost armor https://www.youtube.com/watch?v=sFNQM6D7XkY presumably wrath classic though i'm not sure.

and then this one https://www.youtube.com/watch?v=sFNQM6D7XkY without frost armor nor chilled debuff on party/pet.

I can't really tell whether we should report it or not.

**Comment by heyitsbench** [comment]
> I can't really tell whether we should report it or not.

If I say my source is 'Wrath Classic', more often than not, that means I saw it firsthand while playing Classic.

**Comment by heyitsbench** [comment]
As well, the [creature's Wrath Wowhead page](https://www.wowhead.com/wotlk/npc=818#abilities) also lists Frost Armor as a cast spell.
