### ISSUE TITLE
[Heroic Hellfire Ramparts] Reinforced Fel Iron Chest after last boss does not contain a badge of justice

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#5558]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

After killing Vazruden in Hellfire Ramparts (heroic), the [Reinforced Fel Iron Chest](https://wowgaming.altervista.org/aowow/?object=185169) does not contain a [Badge of Justice](https://wowgaming.altervista.org/aowow/?currency=42), (nor does killing Vazruden yield one either, which is right).

### Expected Blizzlike Behaviour

The aforementioned chest should contain one Badge of Justice.

### Source

https://www.wowhead.com/tbc/npc=17307/vazruden-the-herald#comments:id=2830291
https://youtu.be/Q4BTXMQrkhA?t=1858
https://www.wowhead.com/tbc/object=185169/reinforced-fel-iron-chest

### Steps to reproduce the problem

1. Have at least level 70 character (.level 70) 
2. Alliance character: Have required reputation for Honor Hold (.modify reputation 946 42000)
3. .teleport honorhold
4. Buy Flamewrought Key from Honor Hold Quartermaster
5. .teleport Hellfire
6. Set dungeon difficulty to heroic
7. Enter the instance, kill NPCs/bosses, and observe how on the last boss there is no reward for a badge even in the chest

### Extra Notes

I am not entirely sure if the badge mechanics changed in WotLK for the badges that should be in a container. In any case, as of now, the last boss in Hellfire Ramparts (heroic) does not yield a Badge of Justice.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/590dcca82b9c6e5d5f49fb5f954b084a88070f84

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by kerricsson** [comment]
Good evening. Please have a loot at this issue, since it's a real  problem what affects all lvl70 players doing HC dungeons. Dungeon itself is not easy so lack of 1/3 targeted reward (means badge) is really frustrating.

Thanks in advance for triage and confirmation.

**Comment by Samsequel** [comment]
Confirmed. Someone will come along and set the labels I hope :)
