### ISSUE TITLE
aura given by spell=5781 missing newline in tooltip

### ISSUE THREAD

**Issue by vorobyevites** [chromiecraft/chromiecraft#5567]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

1-19

### Current Behaviour

when fighting mobs [3056](https://wowgaming.altervista.org/aowow/?npc=3056), [2958](https://wowgaming.altervista.org/aowow/?npc=2958), [2960](https://wowgaming.altervista.org/aowow/?npc=2960), [21956](https://wowgaming.altervista.org/aowow/?npc=21956), or [20748](https://wowgaming.altervista.org/aowow/?npc=20748), they have a chance to cast [threatening growl](https://wowgaming.altervista.org/aowow/?spell=5781), which applies an aura of the same name. the aura currently has no newline between **Strength reduced by 2.** and **Agility reduced by 2.** making it read as **Strength reduced by 2.Agility reduced by 2.**

https://user-images.githubusercontent.com/94198350/236701084-1346d562-cce2-4881-89a5-1149705aa5de.mp4

### Expected Blizzlike Behaviour

newline should be between **Strength reduced by 2.** and **Agility reduced by 2.** making it read as:
**Strength reduced by 2.**
**Agility reduced by 2.**

### Source

https://wowgaming.altervista.org/aowow/?spell=5781#used-by-npc
https://www.wowhead.com/wotlk/spell=5781/threatening-growl

### Steps to reproduce the problem

1 - fight mobs [3056](https://wowgaming.altervista.org/aowow/?npc=3056), [2958](https://wowgaming.altervista.org/aowow/?npc=2958), [2960](https://wowgaming.altervista.org/aowow/?npc=2960), [21956](https://wowgaming.altervista.org/aowow/?npc=21956), or [20748](https://wowgaming.altervista.org/aowow/?npc=20748)
2 - wait for them to cast [threatening growl](https://wowgaming.altervista.org/aowow/?spell=5781)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/590dcca82b9c6e5d5f49fb5f954b084a88070f84

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vorobyevites** [comment]
wasn't sure which content tag to use and "generic" didnt seem right, apologies if i was wrong about that

**Comment by Tereneckla** [comment]
Not happening on my side with a clean client
![image](https://github.com/chromiecraft/chromiecraft/assets/50233983/a3c5cf91-18be-496b-bad0-e191b0578641)

The AIO addon is causing that issue I think, see for example
![image](https://github.com/chromiecraft/chromiecraft/assets/50233983/18b6b328-95a6-453f-b8c4-4d7b0f69f7a9)
