### ISSUE TITLE
Section in Undercity not giving rested bonus

### ISSUE THREAD

**Issue by Stump876** [chromiecraft/chromiecraft#557]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Like the subject says. Specifically the area behind the throne room where the burial vault is for Terenas Menethil II is, on the way to the elevators to go down into Undercity. However, if you stand on the vault you get the rested Zzz's

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Anywhere in a capitol city should be rested.
[https://wowwiki-archive.fandom.com/wiki/Rest](https://wowwiki-archive.fandom.com/wiki/Rest)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele undercity or brill
2. Walk behind the throne into the mausoleum 
3. Check for Zzz's
4. It might help to be horde and turn GM mode off to get out of the "Retaking of Undercity" phase

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by fendwe** [comment]
This seems to be working correctly now.

**Comment by damnablebear** [comment]
Confirmed today on Chromie PTR, rested XP is being granted at the spots noted in the original issue report.
