### ISSUE TITLE
[Warrior]  Overpower sometimes reports "That ability requires combo points"

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5572]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Intermittently, when Overpower procs and you attempt to use it, you will get a red error message "That ability requires combo points"

### Expected Blizzlike Behaviour

The ability should work when triggered.  If something causes it to fail, it should report "invalid target" or fail with no error if the ability was not actually available.

### Source

Looks like this might be a Blizz-original bug with how the ability's trigger is defined:

https://www.wowhead.com/spell=37321/overpower

See Flags:
==
Flags	
Is Ability
Cannot be used while shapeshifted
Do Not Sheath
Cannot be dodged, parried or blocked
**Requires combo points on target**
Discount Power On Miss

### Steps to reproduce the problem

1.  Be a warrior with high enough level to have Overpower
2.  Use the ability on proc, the error will intermittently appear.

### Extra Notes

I THINK this might happen when you do a multi-mob pull, and you kill the mob that procc'ed Overpower but the button doesn't fade properly.  So when you use it, you're on a different target than the one that caused the proc.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/590dcca82b9c6e5d5f49fb5f954b084a88070f84

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cythisiax** [comment]
Hi hello, as of https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e I am unable to replicate the overhead/combat log text stating overpower (on proc and when available) is asking for combo points.

**Comment by TheSCREWEDSoftware** [comment]
I can confirm the above I was testing with them. I will be closing this issue
