### ISSUE TITLE
Auction House mails don't have any gold/name info on them

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#558]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Auction house mails don't list any gold stats or name sof the buyers/seller.
![auction1](https://user-images.githubusercontent.com/80769357/117404538-668d4480-af0a-11eb-84b3-4ee30ae8ff18.jpg)
![auction2](https://user-images.githubusercontent.com/80769357/117404540-6725db00-af0a-11eb-93c1-14189a36af46.jpg)
![auction3](https://user-images.githubusercontent.com/80769357/117404541-67be7180-af0a-11eb-99c3-d50e28ca8b97.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Auction house mails should include the gold information and the name of the buyer/seller.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Sell or Buy any item on AH
2. See the attached mail

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
I have the same issue lately with some AH mails, but not all of them. It started happening 2 days ago I think (05/05/2021).

**Comment by necropola** [comment]
Same here. It started after the last restart which wiped the AH.
Additional to this, I notice a significant delay when opening the Mailbox to check for new mail.

**Comment by tabakisp** [comment]
I can also confirm this happened to me yesterday, after the server update.
![Screenshot_20210508_043853](https://user-images.githubusercontent.com/7551798/117537116-a423c780-b007-11eb-8a7d-b57919f42fa4.png)
