### ISSUE TITLE
[Reopen][CoT2] Non-elites spawning from portals should stop on final boss spawn

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5584]
https://github.com/chromiecraft/chromiecraft/issues/5155
wasnt reopened within 3 weeks, hence new ticket.
issue persists, the amount of mobs spawning from the final portal, besides the boss, is still greater 0

**Comment by Cythisiax** [comment]
Consolidated this with the other BM portal issues.
