### ISSUE TITLE
Lady Sathrah Spawns as Unknown

### ISSUE THREAD

**Issue by Xero-Kill** [chromiecraft/chromiecraft#5592]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

While doing "Tears of the Moon" quest in The Oracle Glade area of Teldrassil I found the NPC "Lady Sathrah" was spawned as "Unknown" and did not show up on track as a beast. She is a white spider that is to be killed as the main objective of the quest to obtain "Silvery Spinneretes". She dropped the appropriate item for the quest, and it was completed without issues. The only problem was the NPC not having a name and not being trackable as a beast.

### Expected Blizzlike Behaviour

Should be named Lady Sathrah and be trackable by Hunters as a beast type mob.

### Source

https://www.wowhead.com/quest=2518/tears-of-the-moon

### Steps to reproduce the problem

Lady Sathrah
Priestess A'moora (Quest Giver) in Darnassus

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft
![WoWScrnShot_051123_194515](https://github.com/chromiecraft/chromiecraft/assets/133294656/7f03fa8f-516c-46d1-950f-d48117003158)

**Comment by gchekenny** [comment]
Tested, found her with proper name and trackable on minimap, killed her to check respawn and spawned properly.
![WoWScrnShot_061623_202119](https://github.com/chromiecraft/chromiecraft/assets/65800273/13c99d5a-e879-4b3a-a95b-3c9495018447)
![WoWScrnShot_061623_202715](https://github.com/chromiecraft/chromiecraft/assets/65800273/c97aec4d-00ef-435c-8d3a-cc40ce3089a7)

**Comment by Si1ker** [comment]
@Gultask close.
