### ISSUE TITLE
Gold amount not scaled based on level from daily Quests

### ISSUE THREAD

**Issue by Foosiq** [chromiecraft/chromiecraft#56]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Currency reward from daily quests should scale based on character level.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I shouldn't be getting that much gold from world event daily quests for example

##### CURRENT BEHAVIOUR:

![WoWScrnShot_020721_213335](https://user-images.githubusercontent.com/4582413/107158915-3f67bb00-698d-11eb-8a65-ca7d9e8e0283.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
I can confirm this.

**Comment by JamesGent** [comment]
Fixed now with @FrancescoBorzi's adjustment to the core and today's restarts.
