### ISSUE TITLE
Karazhan - Random Servant's Quarters Bosses don't spawn

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#5604]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

You can clear the whole Random Servant's Quarters and the bosses won't spawn.
https://youtu.be/rOt6FpZuBRI

### Expected Blizzlike Behaviour

A random boss should spawn while doing a emote after a certain number of kills occur.

### Source

https://wowpedia.fandom.com/wiki/Karazhan_(raid)

> You do not have to clear the entire quarters for a boss to spawn. It appears that the boss will spawn after a certain number of kills occurs. Look for an emote, such as 'Hyakiss the Lurker emerges from...' The boss can also spawn multiple times if the quarters continue to get cleared.

Patch 8.3 footage, but it clearly shows how it works exactly as the wiki
https://youtu.be/EbGiZI5FqsM?t=304

### Steps to reproduce the problem

1. .tele Karazhan
2. Enter the main entrance and take a right into the Servant Quarters.
3. Kill enemies and wait for any of the random bosses to spawn while emoting.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
> Reported already in [azerothcore/azerothcore-wotlk#16919](https://github.com/azerothcore/azerothcore-wotlk/issues/16919) - needs linkage.

other way around
