### ISSUE TITLE
Karazhan - Chess Event - Can't take control of some pieces of your faction

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#5610]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

You can't take control of some of the pieces that are the same faction as yours or would only be available at certain moments.
https://youtu.be/78ggh0O5-WE

(Tested only as Horde)

### Expected Blizzlike Behaviour

You should be able to pick up any piece that is not being used by anybody else.

### Source

**https://wowpedia.fandom.com/wiki/Chess_Event**
> After the event begins, raid members can control any currently uncontrolled piece of their own faction by talking to it.

TBC Classic
https://youtu.be/QUwBKeHr3d0?t=125
The player interacts with a random piece and its able to control it.

### Steps to reproduce the problem

1. .tele kara
2. Go to Chess Event (its on the way to Prince Malchezzar)
3. Start the event, try controlling all the piece of your same faction.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
I'm not sure this issue is valid. The reason you can't control any of the pieces before the event begins is because the king (or warchief in your case) has to be controlled to start the event, until then no other pieces can be controlled. The reason it seemed to be inconsistent after the event started is because you seemed to have a debuff that doesn't let you assume control of any pieces during its duration.

These two points in particular I've verified on Wrath Classic to be accurate, but there may still be a couple issues with the specifics regarding pieces and their interactions that I will look at and report when I am able. If you do happen to find evidence to the contrary, please feel free to re-open the issue.
