### ISSUE TITLE
Karazhan - Spectral Performer: Spotlight

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#5618]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

**Currently Spectral Performers are:**
- Casting _Spotlight_ that gives a 50% damage increase
- Spotlight stacks the damage when multiple lights are present
- Spotlight does not buff the player

https://youtu.be/RJ6zYtDCgag

### Expected Blizzlike Behaviour

- Spotlight buff should be 20% not 50%
- Spotlight should buff the player when they are inside it like it does the NPCs

### Source

Older sources that say it's 20% damage
https://wowpedia.fandom.com/wiki/Spectral_Performer
> Spotlight: Physical. In the spotlight! Increases all damage done by 20%. Lasts 15 seconds. Range: 2 yards. This is a beneficial debuff.

https://wowwiki-archive.fandom.com/wiki/Spectral_Performer
> Spotlight. Physical. In the spotlight! Increases all damage done by 20%. Lasts 15 seconds. Range: 2 yards. This is a beneficial debuff.

Wowhead TBC says its 50% damage
https://www.wowhead.com/tbc/spell=351655/spotlight#used-by-npc
https://www.wowhead.com/tbc/npc=16473/spectral-performer#abilities;mode:n10

https://youtu.be/XAIrLaTOob4?t=2437
Doesn't seem to stack when a NPC is standing on two lights but its hard to tell.

### Steps to reproduce the problem

1. tele kara
2. take a right into the ball room, then head as if going to the Opera event
3. Wait for Spectral Performers to cast Spotlight
4. Get inside it and see if you can get the buff
5. Check if NPCs are getting multiple stacks of the buff

### Extra Notes

Sources contradict in the amount of damage that this spell should do, older sources seem to point to 20% and TBC Classic source points to 50% damage increase. It's also hard to tell if this debuff should stack or not. Damage spikes really high when it stacks.

What we know for sure it's that the player should be able to get this **beneficial debuff** when standing on it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
see also: https://github.com/azerothcore/azerothcore-wotlk/issues/16274
