### ISSUE TITLE
Mana Potion Injector cannot Increase effect for engineers appropriately

### ISSUE THREAD

**Issue by HolyPontiff** [chromiecraft/chromiecraft#5624]
### What client do you play on?

Other

### Faction

Horde

### Content Phase:

70

### Current Behaviour

[https://www.wowhead.com/wotlk/item=33093/mana-potion-injector#created-by-spell](url)
I am an engineer (skill 360) and use Mana Potion Injector never gain mana over 3000.

### Expected Blizzlike Behaviour

[https://wowpedia.fandom.com/wiki/Mana_Potion_Injector](url)
Potion Injectors now increase the amount gained by 25% when used by engineers. 
Quantity produced by recipes for Runic Healing and Mana Injectors has been increased.
For engineers, the injector now restores 2,250 to 3,750 mana.

### Source

[https://www.wowhead.com/wotlk/item=33093/mana-potion-injector#created-by-spell](url)

### Steps to reproduce the problem

Use Mana Potion Injector in battle or out off battle, but it cannot trigger the bonus.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment]
Oof

**Comment by eusss** [comment]
To elaborate on this issue:

I tested this on the PTR using the following macro:

/target player
.additem 33093
/use Mana Potion Injector
.cooldown

Engineering is at skill level 375
<img width="292" alt="Screenshot 2023-09-15 at 12 14 17" src="https://github.com/chromiecraft/chromiecraft/assets/96571151/8ff4d416-52ae-4542-8bf6-2ae745cfc4c6">

Results are: 
<img width="493" alt="Screenshot 2023-09-15 at 12 12 55" src="https://github.com/chromiecraft/chromiecraft/assets/96571151/1f3c578f-8976-450b-9f9e-9140b0350218">

As seen, the mana returned never exceeds 3000. Characters with engineering should get increased effects which is +25% added energy gained. This is referenced in [Patch notes 3.2](https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0): "Potion Injectors now increase the amount gained by 25% when used by engineers." In that case the lowest amount of mana gained using Mana Potion Injector by an engineer can't be lower than 1800*125% = 2250 mana. However if you look at the combat log there are many times the mana returned is lower than that (1891, 1954, 1814, 1842 etc.), this should not be possible.

Looking at the code in [azerothcore-wotlk](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb)/[src](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb/src)/[server](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb/src/server)/[game](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb/src/server/game)/[Spells](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb/src/server/game/Spells)/[SpellEffects.cpp](https://github.com/chromiecraft/azerothcore-wotlk/blob/642bd1936b341a098d7c8d5f3089988409e4d6bb/src/server/game/Spells/SpellEffects.cpp#L1933), line 1933 there is code for the addition of 25% mana return for spell ID 67490 [Runic Mana Injector](https://www.wowhead.com/wotlk/spell=67490/runic-mana-injector), but not for spell ID 67487 [Mana Potion Injector](https://www.wowhead.com/wotlk/spell=67487/mana-potion-injector). The case for spell ID 67487 should therefore be added.

The same is true for [Healing Potion Injector](https://www.wowhead.com/wotlk/item=33092/healing-potion-injector). The increased healing is only implemented for [Runic Healing Injector](https://www.wowhead.com/wotlk/item=41166/runic-healing-injector) Spell ID [67489](https://www.wowhead.com/wotlk/spell=67489/runic-healing-injector), see [azerothcore-wotlk](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb)/[src](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb/src)/[server](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb/src/server)/[scripts](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb/src/server/scripts)/[Spells](https://github.com/chromiecraft/azerothcore-wotlk/tree/642bd1936b341a098d7c8d5f3089988409e4d6bb/src/server/scripts/Spells)/[spell_item.cpp](https://github.com/chromiecraft/azerothcore-wotlk/blob/642bd1936b341a098d7c8d5f3089988409e4d6bb/src/server/scripts/Spells/spell_item.cpp#L3334), line 3348
