### ISSUE TITLE
[Arathi Highlands] Guile of the Raptor - Missing NPC dialog

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5629]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

30-39

### Current Behaviour

The NPC Gor'mak should have dialog at the end of the Guile of the Raptor quest.  This bug looks to be a carryover from Trinity Core that has possibly re-broken.

https://www.wowhead.com/quest=26108/guile-of-the-raptor

### Expected Blizzlike Behaviour

Gor'mak has dialog after you turn in the quest to him.

### Source

https://github.com/TrinityCore/TrinityCore/issues/20734

### Steps to reproduce the problem

complete all lead-in quests, then turn in quest 26108 to Gor'mak.  Observe that he has no dialog.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
I will point out that it seems you linked the wrong quest ID. The quest ID this issue applies to seems to be [702](https://www.wowhead.com/wotlk/quest=702), 26108 doesn't exist in Wrath.

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️

**Comment by Vyperhand** [comment]
You are correct, I had the wrong instance selected on Wowhead.  https://www.wowhead.com/wotlk/quest=701/guile-of-the-raptor is the Wotlk classic version, at least.
