### ISSUE TITLE
[Arathi Highlands] Guile of the Raptor - Heart Drops in Party

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5630]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

30-39

### Current Behaviour

When killing raptors for hearts for the quest Guile of the Raptor, if one party member finishes the quest, the hearts that drop on the mobs that are their loot do not properly unlock to be lootable by party members that have not finished the quest.

### Expected Blizzlike Behaviour

If a party member gets all 12 hearts before another party member does, once they have looted a corpse, the quest item should then be lootable by any member of the party that does not yet have 12 hearts.  This is standard behavior for drop quests in party.

### Source
EDIT:  Updated key links to be from correct version of Wowhead.

https://www.wowhead.com/wotlk/quest=701/guile-of-the-raptor
https://www.wowhead.com/wotlk/item=4513/raptor-heart
https://www.wowhead.com/wotlk/npc=2561/highland-fleshstalker

### Steps to reproduce the problem

1. Have a party of at least two characters on guile of the raptor quest 701
2. Kill Highland Raptors until one party member has all 12 hearts - this may be easier to observe if you kill them in large packs before looting
3. The party member who has completed the gathering will see redded-out hearts on corpses that are their loot, and these items will not be lootable by other party members.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Seems that the quest works well. It has probably already been fixed.

Thank you for the report anyway.
