### ISSUE TITLE
Blackfathom Villainy is not available at level 20

### ISSUE THREAD

**Issue by Grevmak** [chromiecraft/chromiecraft#5638]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

20-29

### Current Behaviour

I am level 20, enter Blackfathom deeps, go to the Nightelf that should have the quest (WOWhead link) https://www.wowhead.com/classic/quest=1200/blackfathom-villainy and don't get the quest.

### Expected Blizzlike Behaviour

I should be able to get the quest. It's for level 18 minimum and I saw a bloodelf with the wand. So it works for Horde nor for Ally.

### Source

https://www.wowhead.com/classic/quest=1200/blackfathom-villainy

"Minimum level: 18"

And as I said, I've seen level 20 folks run around with the wand Hordeside.

### Steps to reproduce the problem

1. Go to BFD
2. Be level 20
3. Be Alliance
4. Don't get quest from Elf.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Hihilist** [comment]
Are you sure you took the prerequisite quest from Darnassus https://www.wowhead.com/classic/quest=1198/in-search-of-thaelrid ? Cause it 2-quests-chain and without that one from Darnassus, dead Nelf in BRD will not give you the Blackfathom Villainy.

**Comment by gchekenny** [comment]
Tested, you need to have https://www.wowhead.com/wotlk/quest=1198/in-search-of-thaelrid first
![WoWScrnShot_061623_143020](https://github.com/chromiecraft/chromiecraft/assets/65800273/2e73f449-517b-4646-bc84-ad848a65ccc6)

**Comment by Si1ker** [comment]
@Gultask close.
