### ISSUE TITLE
ERROR #132 Fatal exception on loading character list

### ISSUE THREAD

**Issue by younver** [chromiecraft/chromiecraft#5646]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

The game is crashing while loading character screen on Apple Silicon. It gives the exception below. 

<img width="311" alt="210126079-d8b058c1-c5df-4505-8d53-1fccab8e64b2" src="https://github.com/chromiecraft/chromiecraft/assets/69584310/79b2fad6-abbc-40ba-bf06-063ad8b4dfc4">

### Expected Blizzlike Behaviour

It supposed to load character list and let me play with my character or create new one.

### Source

None

### Steps to reproduce the problem

- download the game following the [instructions](https://www.mangosrumors.org/how-to-run-wow-32-bit-on-mac-os/) on MacBook Air M2.
- open the game
- login to the account
- select the server

after selecting the server, the character list screen is loading and in 1 second (or less) game is crashing.

### Extra Notes

I've searched and tried many things I've found from the web such as deleting `Interface`, `WTF` and `Cache` folders. None of them worked. Also https://github.com/chromiecraft/chromiecraft/issues/4704 is the same issue, I just wanted to see if there are any solutions I've missed out.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

macOs Monterey Version 12.6
MacBook Air (M2, 2022)

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sukuidoardo** [comment]
++

**Comment by Samsequel** [comment]
You should try a local setup and see the error log from worldserver to maybe see what is wrong.

**Comment by younver** [comment]
Hey @Samsequel, thanks for the info. By "local setup", do you mean trying azerothcore client? 

If not how can I setup local? Thanks in advance^^

**Comment by cachocarne** [comment]
May I ask why you use a Windows client when there's a Mac one that works perfectly?

**Comment by younver** [comment]
Because the instructions for Mac client works not perfectly on Macbook Air M2.

Anyways, as a solution, I've been playing using Parallels Desktop for a while. For those who face the same issue can use Parallels free for 2 weeks for trial.
