### ISSUE TITLE
Multiple Solid Chests with short respawn timer in Winterfall Village, Winterspring

### ISSUE THREAD

**Issue by Beastmasterwow** [chromiecraft/chromiecraft#565]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ X] 50-59

##### CURRENT BEHAVIOUR:

Multiple Chests (4) in Winterfall Village in Winterspring have respawn timer of 5 minutes. There is more chests but I haven't been able to reach them and loot them.
https://classic.wowhead.com/object=153454/solid-chest
![Screenshot_6](https://user-images.githubusercontent.com/81812276/117505101-d25fc380-af83-11eb-9888-dfb5af0b7121.png)
![Screenshot_7](https://user-images.githubusercontent.com/81812276/117505111-d5f34a80-af83-11eb-87cb-50a0f25130f2.png)
![Screenshot_8](https://user-images.githubusercontent.com/81812276/117505126-d8ee3b00-af83-11eb-94b8-20c5aad8aa6e.png)
![Screenshot_9](https://user-images.githubusercontent.com/81812276/117505137-db509500-af83-11eb-9d6c-8af6d55e9f5d.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Solid Chests should not respawn at 5 minutes timer.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Winterfall Village, Winterspring
2. Find Solid Chests and loot them.
3. Wait next to spawn location to record the respawn timer of the chest.
4.

##### EXTRA NOTES:

There is more chest/s In the zone that should be checked including a few in Winterfall Village, Winterspring.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Happy to say that this one has already been taken care of, and the chest respawn time adjusted from 5 minutes to 2 hours, in line with most other Solid Chests. See https://github.com/azerothcore/azerothcore-wotlk/pull/5695. The fix hasn't made it to ChromieCraft just yet, but it's on the way.
