### ISSUE TITLE
[Eversong woods] Arcane wraith wrong position.

### ISSUE THREAD

**Issue by enheken** [chromiecraft/chromiecraft#566]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

A Arcane wraith is scaling the mountain when it is supposed to be on the floating platform.
![WoWScrnShot_050721_231831](https://user-images.githubusercontent.com/74271513/117509516-a7c53900-af8a-11eb-9508-e9e2f2241101.jpg)
DB GUID 54923

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mob in question is supposed to move around on the platform not the mountain

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to DB GUID 54923.
2. See for yourself.
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Been there for a long time and didn't saw something wrong...

![image](https://user-images.githubusercontent.com/61223313/117517960-2904d780-af5b-11eb-9647-54af63279e23.png)

**Comment by enheken** [comment]
![again](https://user-images.githubusercontent.com/74271513/117535664-1b049480-aff7-11eb-8309-ba8bd9d59d5b.jpg)
Checked myself again and saw that when the mob is able to walk up and down the ledge that I painted in blue (mad paint skills)
