### ISSUE TITLE
[Quest zone marker] Warrior Kinship (8423)

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#5671]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

50-59

### Current Behaviour

Class quest "Warrior Kinship" (8423) requires us to kill 7 Helboars in Blasted Lands.
Upon opening zone map to view the area where to complete quest, we are only shown a little triangle close to the Dark Portal which, apart from a few Helboars, also has a lot of other mobs.

![Helboars_triangle](https://github.com/azerothcore/azerothcore-wotlk/assets/77953030/f3ad0a93-62c4-4c4f-88ce-b6645371a5d5)

### Expected Blizzlike Behaviour

Actually, there are many more Helboars around the map, most of them much easier to kill since there are no higher level mobs around.

On this image you can see how I found more Helboars not far away from there.
![ 2023-05-25 a las 16 26 01](https://github.com/azerothcore/azerothcore-wotlk/assets/77953030/47464ba5-b9f7-4fb2-97a3-bdce56dfd167)

And this is the map of locations from Wowhead:
![ 2023-05-26 a las 9 31 21](https://github.com/azerothcore/azerothcore-wotlk/assets/77953030/200dd372-96dc-4ceb-a59c-e71a9c8cddb9)

Quest zone marker should reflect those areas as well as the one on the lower end.

### Source

https://www.wowhead.com/wotlk/quest=8423/warrior-kinship

### Steps to reproduce the problem

Have a Warrior character at least level 50
Get quest Warrior Kinship (8423)
Open zone map to see quest locator

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gchekenny** [comment]
Tested, I believe the map marks only that small area because it's likely to be the only area where hellboards are going to spam 100% of the time. If you have a look at the comments https://www.wowhead.com/wotlk/quest=8423/warrior-kinship#comments you'll notice several players discussing about the hellboars sharing spawn points with other creatures. And the location of these shared spawns are unlikely to be marked on the map for this particular quest.

Yes the marked area is small but I can't find evidence that proves this as incorrect behaviour.
![WoWScrnShot_061523_224121](https://github.com/chromiecraft/chromiecraft/assets/65800273/b0774844-b860-4ba2-898a-5f09b38f3fd4)

**Comment by alecsci** [comment]
I think there are a huge list of quests that mobs spawn in more area than the quest locator shows.
I also agree with @GastonCK this is not a bug.
