### ISSUE TITLE
[NPC/Spell] Gnarlpine Mystic wrong spell damage/animation

### ISSUE THREAD

**Issue by Salehyn** [chromiecraft/chromiecraft#5682]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

This NPC is blasting for a shocking 30+ damage per wrath cast at lvl 6 as opposed to the roughly ~10 damage their spell dealt on Blizz Classic (you can verify this damage on any walkthrough videos such as these https://www.youtube.com/watch?v=yZ8_-yGxEnc / https://www.youtube.com/watch?v=QBcacPdw15Y

For reference, a lvl 6~ player has about 120-150 health depending on class and dies in 3-4 shots to these enemies currently.

As I understand on Azerothcore this spell was added manually by Azerothcore devs as a fix to this issue https://github.com/chromiecraft/chromiecraft/issues/148 however it seems to me that the wrong spell was added. It is also clear based on the dev's test video which was done by a lvl 27 character who resisted each and every cast that the spell damage was never tested, only the casts were verified.

### Expected Blizzlike Behaviour

This lvl 6-7 NPC's spell is supposed to deal about 10~ damage with their casts as seen on the retail video(s) I linked and uses a different color animation as well, which further confirms it's probably a different spell ID.

More in detail:
When it comes to spell IDs there is a bit of a mess here as the aowow database seems to be currently using this specific player spell ID https://wowgaming.altervista.org/aowow/?spell=5177 for these NPCs, which is incorrect, but I assume this is what our devs added for now. The problem is that its 30-35 damage corresponds to a lvl 15 druid, not a lvl 6 random mob. On top of that, if you notice on the video the spell animation is different as well (the druid ability is distantly green, while the NPC ability is supposed to be distantly blue lightning)

EDIT: the wowhead 3.3.5 database has this https://www.wowhead.com/wotlk/spell=9739/wrath which has the flag "damage depends on caster level" and a value of 43 dmg at lvl 20. I assume this must be the spell to scale down to lvl 6 in order to receive the expected ~10 damage and the distantly blue cast animation.
I don't know much about how this is scripted in the core and if this is possible to do on AzerothCore in specific, because caster NPCs using the wrong spells (and notably overpowered ones) seems to be a general issue on ChromieCraft.
So if a proper fix is not possible:
Alternatively you can downrank the current rank2 wrath to the rank1 version of the spell which would more closely match the npc's lvl and damage https://www.wowhead.com/classic/spell=5176/wrath but this ability is still higher in damage and uses the wrong animation. It's a good plan B though.

If any further info is needed, please let me know.

### Source

I linked everything above where appropriate but ill repeat:

retail vids https://www.youtube.com/watch?v=yZ8_-yGxEnc / https://www.youtube.com/watch?v=QBcacPdw15Y

### Steps to reproduce the problem

NPC ID 7235 from wowhead https://www.wowhead.com/classic/npc=7235/gnarlpine-mystic
Test this npc's damage as a lvl 6 character when fixing so that the spells don't keep missing on you. Note the difference in damage from official servers and the difference in cast animation

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️

I've triaged the incorrect spell ID portion of this report, since that should hopefully correct the animation/damage if/when it's fixed. If that happens and the damage/animation are still incorrect, please feel free to open a new issue.

**Comment by elthehablo** [comment]
This issue should be fixed now with the linked PR. Thanks for this detailed report. Keep it up!
