### ISSUE TITLE
[SHH] Grand Warlock Nethekurse

### ISSUE THREAD

**Issue by KostovDimitar** [chromiecraft/chromiecraft#5685]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

When the boss mentioned in the title of the report is pulled together with any of the 4 mobs in front of it, and if we kill the mobs before the boss, the boss patrols back to its original position as if resetting/evading, however, he stays in combat but not targeting anyone and his health is not regenerating, he is just going back and forth. When we kill all mobs pulled with the boss he resumes normal behavior.

### Expected Blizzlike Behaviour

The boss shouldnt return to its original position when its pulled with the mobs AND the mobs killed first.

### Source

https://youtu.be/0phkTyrfzpo?t=218

### Steps to reproduce the problem

1. .go creature 151089
2. pull the boss and the Fel Orc Convert
3. Pull them all away and do some damage to the boss so you can clearly see the behavior
4. Kill the Fel Orc Converts before you kill the boss

### Extra Notes

ScriptName: boss_grand_warlock_nethekurse
https://www.wowhead.com/wotlk/npc=16807/grand-warlock-nethekurse

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
Thank you, a fix for this has been merged with Azerothcore already
https://github.com/azerothcore/azerothcore-wotlk/pull/16395
