### ISSUE TITLE
[Dungeon Finder] Requeueing after a run for the same dungeon should reset the dungeon

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#569]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Queueing with the dungeon finder while being in a cleared dungeon doesn't reset the dungeon (thus the boss required for the completion of the run is missing).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should teleport the group to the entrance (inside) and reset the whole dungeon.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Queue for a dungeon finder.
2. Clear the dungeon.
3. Queue for the same dungeon as the one you've cleared (without teleporting out of the dungeon).
4. Accept. Notice that you didn't move to the entrance (inside) of the dungeon and mobs are still dead.

##### EXTRA NOTES:

Should happen with both factions.
Happened when we tried to queue for a random dungeon and our levels made that only one specific dungeon (Scarlet Monastery - Library) would happen.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment]
as a note this happens only if you stay in the same group - redoing the party / switching a member after finishing the dungeon will not trigger the issue

**Comment by Maurowin** [comment]
yes, but normally, at least today, the system automatically resets the dungeon if it is in normal mode.

**Comment by Maurowin** [comment]
AC repos : https://github.com/azerothcore/azerothcore-wotlk/issues/5914

**Comment by Synful-Syn** [comment]
When it happened, teleporting out and in, trashes were simply gone (despawned by the timer) or dead.

**Comment by Maurowin** [comment]
I can't test because my pc is not powerful enough to run the server and 5 wow applications. If someone could do it?

Because indeed, this is not a normal behavior of the system.

**Comment by 7Skidoo** [comment]
Just had the same exact thing happen, cleared RFK, 3 out of 5 people left and we remaining two requeued without disbanding the group. We got into RFK again, all bosses were down for all five of us, barely any trash (respawn or not killed before, not sure).
It does appear to trigger the 15min CD on queuing for a dungeon which is mildly annoying.

**Comment by 7Skidoo** [comment]
I'm not sure how to deal with the merged post but this is still an issue, or the issue re-appeared atleast.
Got into an empty Uldaman on a solo RDF queue, I suspect it was this issue. Then later requeued with another Uldaman group, we got into Uldaman again and the dungeon was empty.
