### ISSUE TITLE
[TBC Shattered Halls] Fel Orc Converts stay unattackable when pulled before AreaTrigger

### ISSUE THREAD

**Issue by elthehablo** [chromiecraft/chromiecraft#5692]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/2012bc6d-a087-4fc4-9be6-3f8d075a26a5)

when Fel Orc Converts get pulled through the door by aoe hitting them or something comparable (which is a bug in itself, but that happens a lot here), they stay unattackable, likely because the AreaTrigger is not hit yet. If they then are far away when the AreaTrigger hits, the will stay unattackable and have to be killed with aoe and thorn like mechanics.

**Note: the tint of the creature's level 69 is similar to a player's tint. It should be yellow if they are attackable.**

### Expected Blizzlike Behaviour

They should be attackable when they are also attacking you.

### Source

Common sense, but this is likely also how it works on live servers.

### Steps to reproduce the problem

1. go to SHH on PTR or local server
2. try your hardest with aoe spells to pull the adds (boomkins are good at this) close to the door
3. profit

### Extra Notes

I think in our run it might have been a pet that pulled them as we jumped into the sewers. So maybe try jumping down without dismissing. As you can see from the screenshot we had a warlock with an imp

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
see also https://github.com/chromiecraft/chromiecraft/issues/5681

**Comment by balleny** [comment]
issue also exists if you have a rogue and unlock the door. you have to run into the sewer part to trigger them attackable

**Comment by elthehablo** [comment]
> issue also exists if you have a rogue and unlock the door. you have to run into the sewer part to trigger them attackable

that is because the areatrigger is there. at this point I am unsure what this is like on classic, but the existance of this areatrigger and it causing the events to happen is sniffed from there

**Comment by Francoporto** [comment]
Hi, i'm also pretty sure the issue come from the pets that can't jump like players and go through the locked door and aggro one Fel Orc.

**Comment by elthehablo** [comment]
> Hi, i'm also pretty sure the issue come from my pet that can't jump like players and go through the locked door and aggro one Fel Orc

Yes correct. That is what seems to cause it
