### ISSUE TITLE
[NPC name error] Timber (1132) appears as Unknown

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#5696]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

NPC [Timber](https://www.wowhead.com/wotlk/npc=1132/timber) (rare spawn) spawns correctly in the middle of the frozen lake in Dun Morogh. However, instead of its name, it appears as "Unknown". This mob should be tameable by a hunter.

![ 2023-05-21 a las 14 25 34](https://github.com/chromiecraft/chromiecraft/assets/77953030/5cb16cdb-229f-4daf-a687-a9056c897849)

### Expected Blizzlike Behaviour

NPC should appear with its name, "Timber"

### Source

https://www.wowhead.com/wotlk/npc=1132/timber

![ 2023-05-29 a las 20 16 47](https://github.com/chromiecraft/chromiecraft/assets/77953030/a802e425-fccb-49e7-b72e-aedc15f47e8e)

### Steps to reproduce the problem

Go to location in Dun Morogh (aprox 34,41)
Spawn creature id 1132

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Vecel91** [comment]
Appears to be a client-side issue. 

![001](https://github.com/chromiecraft/chromiecraft/assets/80687806/336386a3-df0c-4cc6-9985-faefc220fc07)

No issue with enUS client connected to local AzerothCore server. 

### AC rev. hash/commit
https://github.com/azerothcore/azerothcore-wotlk/commit/79d6f4e2334334822ecea16c06207b9701d1d81f

**Comment by elthehablo** [comment]
> Appears to be a client-side issue. 
> 
> ![001](https://github.com/chromiecraft/chromiecraft/assets/80687806/336386a3-df0c-4cc6-9985-faefc220fc07)
> 
> No issue with enUS client connected to local AzerothCore server. 
> 
> ### AC rev. hash/commit
> https://github.com/azerothcore/azerothcore-wotlk/commit/79d6f4e2334334822ecea16c06207b9701d1d81f 

Very likely yes

**Comment by cachocarne** [comment]
Please mark as Denied or remove from Issues. Thanks!
