### ISSUE TITLE
The Family Crypt (Tirisfal Glades) quest location group aggro issue

### ISSUE THREAD

**Issue by Salehyn** [chromiecraft/chromiecraft#5699]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

When entering the crypt to complete this quest https://www.wowhead.com/wotlk/quest=408/the-family-crypt, however carefully you tread, if you are level appropriate (lvl 10-12) you will immediately aggro 5-6 npcs of these types https://www.wowhead.com/wotlk/npc=1530/rotting-ancestor https://www.wowhead.com/wotlk/npc=1534/wailing-ancestor
This is not intended and nearly impossible to handle for the characters whom this quest was designed for. You shouldn't aggro two entire floors of enemies as soon as you enter. This might be either an issue with NPC placement or NPC group aggro distance (making the two groups somehow linked) or possibly a line of sight issue between the two floors. Either way you seem to have no way to aggro these groups separately unless you vastly overlevel the enemies, which is not intended.

### Expected Blizzlike Behaviour

Here is a video from classic retail that shows the manner in which these enemies should engage as you enter https://www.youtube.com/watch?v=R9JkA_so9dM

Note that there are 2-3 enemies on each floor of the crypt, who are not linked to each other and the player only engages a group of 3 mobs at a time. This quest has been a solo adventure throughout from vanilla to WOTLK and never required the player to face a mass pull of 5-6 enemies.

### Source

linked above

### Steps to reproduce the problem

Enter the crypt above Agamand Mills in Tirisfal glades as a lvl 10-12 character, slowly descending the stairs as shown on the video. Note that the NPCs are in different positions from that on the video and you aggro 5-6 mobs at once, instead of just 3.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gchekenny** [comment]
Tested, there's indeed a big pull of 4 mobs 
![WoWScrnShot_061623_104550](https://github.com/chromiecraft/chromiecraft/assets/65800273/c6bbed11-560f-46e3-8955-e2751093643f)

But according to videos on youtube from classic, they are meant to be pulled altogether.
https://www.youtube.com/watch?v=kw6qgoEISuQ
https://www.youtube.com/watch?v=R9JkA_so9dM

Therefore the big pull is correct behaviour.

**Comment by Salehyn** [comment]
First, the videos you linked are from vanilla classic not 3.3.5a. Back on classic the to-go strategy for this quest was to die and rezz down below, as shown on the video you linked, this is however not meant to be on LK anymore.
Here is a retail wotlk classic video from 2021, which shows the mobs position was altered on this expansion, spreading them out more and allowing you to pull them separately if you move carefully:
https://www.youtube.com/watch?v=PT33vrPXE2M

Second, there is a wallpull issue on AC, which didn't exist on even the prenerf vanilla version. I recorded a video of this on our PTR.
https://github.com/chromiecraft/chromiecraft/assets/134880284/3168c82b-3ad8-488a-8dee-821148dd4f00

You see the 5th mob that runs in? That's supposed to be LOS from the stairs below. I swear there is a 6th sometimes that appears out of nowhere.

So on this server you end up fighting a pull of 5-6 instead of the intended 2-3.

**Comment by gchekenny** [comment]
The video from your first post (https://www.youtube.com/watch?v=R9JkA_so9dM) shows the same creature positioning as in Chromie's PTR.
However the video from your second post (https://www.youtube.com/watch?v=PT33vrPXE2M) shows an entirely different distribution of creatures and positioning. This positioning that you claimed to be the correct one for wotlk is actually recorded during 2020 classic, not wotlk.
![image](https://github.com/chromiecraft/chromiecraft/assets/65800273/2925082f-1fdd-495a-89fb-ede9cf3c5e3f)
![image](https://github.com/chromiecraft/chromiecraft/assets/65800273/39e7fbe5-8944-4b84-88c1-603d4d9deee8)

Reading the comments https://www.wowhead.com/wotlk/quest=408/the-family-crypt#comments from all versions, including original wotlk, we find they had a lot of problems dealing with the big pulls.

In my opinion if the creature positioning of the PTR is truly wrong, we will need more evidence as valid source, the current one is inconclusive (again this is just my opinion)

Now regarding the 5th creature pulled in your personal video https://www.youtube.com/watch?v=kUGBZmcLip4 it looks to me like the Rotting Ancestor that was the closest one to the stairs was the one that chain-pulled the 5th creature. Not sure whether this is an issue or not, when I tested I avoided that chainpull by not stepping onto the floor like you did. Instead I pulled from the stairs, here I show you:
![WoWScrnShot_061723_221226](https://github.com/chromiecraft/chromiecraft/assets/65800273/b11f5f92-f43d-40b3-9480-4d5ebfa5b7a4)
![WoWScrnShot_061723_221228](https://github.com/chromiecraft/chromiecraft/assets/65800273/fcbfb120-e21f-4285-ab39-6792014d7cdb)

**Comment by Salehyn** [comment]
As someone who played wotlk back in 2010, I actually remember how this quest worked, that is why I made a report. Yes, even pulling 2-3mobs together was a challenge, but you never had to deal with this many. This behavior is wrong.

I realized I put the wrong link in the original post, that's why I searched for a newer video. Because vanilla follows different scripts from wotlk. As blizzard released wow-classic, they first emulated original vanilla, then BC, then wotlk. So earlier classic videos show the vanilla positioning, newer ones show the WOTLK ones. There is nothing inconclusive about this: the different videos were recorded on different patches. They don't always outline which classic-version they show, but you can tell by the time-frame. As cataclysm-classic doesn't yet exist, the newer videos all belong to WOTLK-classic, which is an exact copy of mechanics as 3.3.5a was. Hence the difference in positioning.

I understand bug fixing must rely on evidence, but sometimes it feels like I'm talking to people who never actually played the game. If you had, you would know that the strategy which most videos use (running out and resetting 2 out of 4 mobs) doesn't even work on AC because the mobs follow you forever on this server.
This quest on 3.3.5a used to be a challenging solo, while here it's a hard skip that players just don't bother with because the server is so buggy. I find this sad, but if you want to leave it as-is, I just don't care enough to argue further.

**Comment by elthehablo** [comment]
I agree with the issue. I lost my HC to this :p

**Comment by heyitsbench** [comment]
I've gotten a sniff of this entire crypt. If/when the spawns are reconstructed, we can go back and see if the pull behavior matches Classic or not.

I ask that more care be taken with sources in the future for any issue. Videos from an emulator/pserver and memory of retail, at least as far as I go, will not be considered valid sources.

**Comment by Salehyn** [comment]
Those videos aren't from an emulator/pserver. They are from retail and I pointed out the difference in vanilla and wotlk positioning. I only cited my memories to add emphasis.

**Comment by heyitsbench** [comment]
> Those videos aren't from an emulator/pserver.

This video:

> https://www.youtube.com/watch?v=kw6qgoEISuQ

is even within the first minute very obviously taken from an invalid source.

> I only cited my memories to add emphasis.

I appreciate that it wasn't a foundational piece of the issue, just want to make it clear that to someone like me, it means effectively nothing.

**Comment by Salehyn** [comment]
I didn't post that video, the triaging person did...

**Comment by heyitsbench** [comment]
> I didn't post that video, the triaging person did...

I did not say you posted it. I'm only pointing it out broadly (trying to be nice here).
