### ISSUE TITLE
Quest timer gone after getting back online

### ISSUE THREAD

**Issue by Foosiq** [chromiecraft/chromiecraft#57]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

**|======MODERATION EDIT Strart======|**
Quest: [Apothecary Zamah](https://wotlkdb.com/?quest=853)
NPC_Start: [Apothecary Helbrim](https://wotlkdb.com/?npc=3390)
NPC_End: [Apothecary Zamah](https://wotlkdb.com/?npc=3419)
**|======MODERATION EDIT End======|**

The quest timer is completely gone after getting back online (in my case after 2-3 hours).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quest timer shown both in quest log and in quest objectives.

##### CURRENT BEHAVIOUR:

![WoWScrnShot_020721_213635](https://user-images.githubusercontent.com/4582413/107160483-c8cfbb00-6996-11eb-8dce-b7165e53ff24.jpg)

I can't confirm if the quest fails, but I've seen 30 mins left before going offline and then I just finished the Q and I bet it took me less than the remaining time.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Foosiq 
The quest timer is not bugged.
I tested the quest.
Quest Evidence, Video: [Apothecary Zamah](https://youtu.be/z-ZYDliwofY)


And in the future try to report with Links, as I showed you in the edit I did in your post, pls.
Having the **IDs** of the **NPC/ITEM/QUEST/ETC** at hand, you facilitate the work in its execution.
