### ISSUE TITLE
[Eversong woods] Wretched hooligan wrong position

### ISSUE THREAD

**Issue by enheken** [chromiecraft/chromiecraft#570]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Wretched walks along the wall instead of the ramp.
Db guid 56766
![bild](https://user-images.githubusercontent.com/74271513/117534405-982d0b00-aff1-11eb-8687-1f0731dbd987.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I do belive that the mobs in question should walkon the ramp above him.

##### STEPS TO REPRODUCE THE PROBLEM:

1. teleport to Db guid 56766
2. See if he still walks the wall.

##### EXTRA NOTES:
--

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I have tried both with some that are inside the building and others outside and in any cases they have followed me correctly up the ramp, not sure if I could do something else to try to cause them to go along the wall:

![WoWScrnShot_051121_104625](https://user-images.githubusercontent.com/82579073/117778661-8db77f00-b246-11eb-88e2-768a7fe64238.jpg)

**Comment by Eldarix** [comment]
Can someone try to replicate this ? :)

**Comment by temperrr** [comment]
I've tried numerous things both on CC and AC, and could not replicate this either. Thanks for your report, I'll close it and mark it as cannot replicate! If you manage to let it happen again, we will gladly open it again.
