### ISSUE TITLE
[Quest]  Akiris Reed drops broken in party.

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5700]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

40-49

### Current Behaviour

This is the exact same behavior as a similar quest in Arathi Highlands already reported:  https://github.com/chromiecraft/chromiecraft/issues/5630

The Akiris Reed item has the exact same behavior - drops for a player that have finished the quest do not properly unlock to be lootable by other players.
https://www.wowhead.com/wotlk/item=4029/akiris-reed#objective-of
https://www.wowhead.com/wotlk/quest=617/akiris-by-the-bundle

### Expected Blizzlike Behaviour

When a party member gets all of their drops, their future drops become available to all other party members as secondary loot, similar to how loot unlocks when a party member examines their loot but does not take it.

### Source

Standard party drop behavior.

### Steps to reproduce the problem

1. Create a party of two or more characters.  This may be easier to reproduce with an AoE focused character such as a Prot Paladin or Frost Mage.
2. Kill the quest mobs en masse.
3. Loot
4. Repeat
5. Eventually, Akiris reeds will drop for the first character that completed the quest, and these will not be lootable by the other party members, even after the loot is released.  
6. Secondary note - all the other loot on the mob will behave normally.    If player A looks at the loot, and it's a white, a grey, and the quest item, the other party members B, C, etc. can subsequently take the white and the grey as appropriate, but the quest item will remain red-locked.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
Hi @Vyperhand,
Thanks for your reports !

I tested against latest core version and cannot reproduce it anymore.

If player 1 finishes the quest and more mobs are killed, the quest item can be be now looted by player2, and the quest loot is released and not visible anymore for player 1.
Similar ticket https://github.com/chromiecraft/chromiecraft/issues/5630 has also been addressed.
