### ISSUE TITLE
[Quest] Wrong requirements for Weaken the Ramparts (9575)

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#5707]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

At the moment, it's possible to access to the quest [Weaken the Ramparts](https://www.wowhead.com/wotlk/quest=9575/weaken-the-ramparts) without fulfilling the requirements.
I could take the quest (at least on Alliance Side) without two of the required quests.
There must be an error on the order in which starting quests in Honor Hold are unlocked.
As an example, the npcs at Expedition Point offer you quests even before having the "Expedition Point" quest that sends you there.

I haven't checked if the issue is repeated on Horde side at Thrallmar, would be nice if someone could test it.

### Expected Blizzlike Behaviour

The Alliance version of [Weaken the Ramparts](https://www.wowhead.com/wotlk/quest=9575/weaken-the-ramparts) requires to complete the following quests (the last 3 are required, the first 3 unlock them):

1 - The Legion Reborn (10141)
2 - The Path of Anguish (10142)
3 - Expedition Point (10143)
4 - Know your Enemy (10160)
5 - Fel Orc Scavengers (10482)
6 - Ill Omens (10483)

only then we could access to the quest for the dungeon.

### Source

https://www.wowhead.com/wotlk/quest=9575/weaken-the-ramparts
https://www.wowhead.com/wotlk/npc=17557/lieutenant-chadwick#comments

### Steps to reproduce the problem

1 - Have an Alliance character of at least level 58
2 - Take all quests upon arrival and at Honor Hold
3 - Do not turn in quests Expedition Point (10143) and Ill Omens (10483)
4 - Notice [Lieutenant Chadwick](https://www.wowhead.com/wotlk/npc=17557/lieutenant-chadwick) offers you [Weaken the Ramparts](https://www.wowhead.com/wotlk/quest=9575/weaken-the-ramparts) (9575)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
Just an update to this. I was testing with another character and was able to take many of the quests without turning in any and going back to check every time to see if there was a change on the npc. The issue seems to be between quest 2 and 3 of the list. At the moment, it's possible to get quests 4, 5 and 6 without first completing quest 2 "The Path of Anguish" (quest 3 remains locked). Once quest 2 "The path of Anguish" is turned in, quest 3 is available, but we can take "Weaken the Ramparts" even without first doing "Expedition Point".
I hope this helps a bit.

**Comment by Cythisiax** [comment]
I am unable to replicate this as of https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

https://streamable.com/op4hqo

**Comment by cachocarne** [comment]
Thanks a lot for your time. As I am leveling more characters both on Alliance and Horde side, I will check it again.
