### ISSUE TITLE
[SLabs] Shadow Labyrinth: Doors at the beginning of the last room (Screaming Hall / Murmur) are missing

### ISSUE THREAD

**Issue by Buggyswires** [chromiecraft/chromiecraft#5713]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

There should be some opening swinging doors at the entry to the last room: Screaming Hall (boss: Murmur)
They are missing.

### Expected Blizzlike Behaviour

Doors at the entrance to the Screaming Halls are opening as soon as the group approaches

### Source

Couldn't find any recent WotLK video, but that one is from TBC
https://youtu.be/itYGw9k7rro?t=3570

### Steps to reproduce the problem

Defeat Grandmaster Vorpil and move up the hallway the the final room

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gchekenny** [comment]
Tested, the door is there and opens automatically when the boss Grandmaster Vorpil dies.
![WoWScrnShot_061523_190938](https://github.com/chromiecraft/chromiecraft/assets/65800273/ddb0b4ed-103f-41a3-8551-8a5f3b5b2396)
![WoWScrnShot_061523_191215](https://github.com/chromiecraft/chromiecraft/assets/65800273/fb4a38de-b90d-429a-adcd-52a955ee459e)

**Comment by Buggyswires** [comment]
Ah, so the door opens as soon as Vorpil dies. Usually everyone fights him first and then moves to the next area so i didnt notice that there was a door earlier.
Closing the issue

**Comment by Gultask** [comment]
Hey, so the behaviour you described is correct. The door should open when players get close, but we're waiting for improvements to the Core before we move forward to fixing this.

I also believe this bug has already been reported before, but regardless, thanks for the report!
