### ISSUE TITLE
[UI] Snake statue not showing "?" for quest completition (Sunken Temple)

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#5714]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

40-49

### Current Behaviour

I am not sure if this is a minor UI error or it was meant like this.
In Sunken Temple, after completing "[Secret of the Circle](https://www.wowhead.com/wotlk/quest=3447/secret-of-the-circle)" (3447) by activating the statues in the correct order, we spawn the optional boss that stands on the way to the big Snake statue.

Since quest is completed and statue is spawned at the bottom pool, all left to do is turn it in by clicking on it. However, the question mark that marks objectives for completing quest shows in the mini map but is missing on the statue itself. This could be a bug or maybe not, but wanted to let you know.
I suspect the floating "?" might exist but be INSIDE the statue, since it's very tall.

![ 2023-06-02 a las 17 28 12](https://github.com/chromiecraft/chromiecraft/assets/77953030/504a259d-4cbd-4acf-afdf-8639020eead2)

### Expected Blizzlike Behaviour

I think there should be a big floating "?" above the statue, as it even shows on the minimap.

### Source

Haven't found anything to support this, was just considering it would be the "logic" thing, not to miss clicking on the statue or be stuck wondering how to complete it.

### Steps to reproduce the problem

Have a character level 46 or higher
Get quest 3447
Complete quest by clicking the statues in the right order: S, N, SW, SE, NW, NE
Spawn big Snake statue "Idol of Hakkar"
Observe it's clicklable and "?" will not be seen on screen but only on minimap

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gchekenny** [comment]
Tested, quest works as intended.
I couldn't find any video, screenshot or text to prove that the statue should have a "?" on its head. I'd say it's safe to assume that the absence of the "?" is correct behaviour.
![WoWScrnShot_061423_232025](https://github.com/chromiecraft/chromiecraft/assets/65800273/7bdfecc3-abbe-4265-b948-2e61dd0ee2f2)

**Comment by cachocarne** [comment]
Thanks for taking the time to review it! No "?" it is, then.
