### ISSUE TITLE
HC challenge appeal

### ISSUE THREAD

**Issue by Dfmage** [chromiecraft/chromiecraft#5716]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

20-29

### Current Behaviour

I want to file an appeal for the restoration of the character due to the fact that I fell into the textures after using Blink. The action took place in the north of Darkshore. I am attaching screenshots.
![WoWScrnShot_060423_163356](https://github.com/chromiecraft/chromiecraft/assets/135523173/1ef46da3-3f6d-45f6-a200-f0836d30d172)
![WoWScrnShot_060423_163425](https://github.com/chromiecraft/chromiecraft/assets/135523173/023a0851-7d87-4255-9e14-beb055804d3c)
![WoWScrnShot_060423_163427](https://github.com/chromiecraft/chromiecraft/assets/135523173/8d55aebb-b98d-447f-8fef-4a06ee7eaba4)
![WoWScrnShot_060423_163429](https://github.com/chromiecraft/chromiecraft/assets/135523173/bc90c03d-08a3-42d9-b687-e1d71384a67d)
![WoWScrnShot_060423_163430](https://github.com/chromiecraft/chromiecraft/assets/135523173/1524fa18-4e45-44b2-9ca7-2b47feb8aa26)
![WoWScrnShot_060423_163453](https://github.com/chromiecraft/chromiecraft/assets/135523173/8fb989b8-8bab-411e-92f4-5296eb1c2eda)

### Expected Blizzlike Behaviour

Using Blink should not cause the character to fall under textures

### Source

https://www.youtube.com/watch?v=mpX5kzpYk9s
You can see in this movie that none of the Blinks caused a drop under the textures.

### Steps to reproduce the problem

You need to make sure that the move point after using Blink is always **above** the texture, and not **below** it

### Extra Notes

Df, a 21lvl draenei mage, HC+IM+BT

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
HC deaths can be appealed via Discord. Open a support ticket in there.
