### ISSUE TITLE
Black Morass Heroic - Rift Keepers Immune to physical interrupts

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#5721]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

The rift keepers are only interruptible by spells and not by physical abilities.
https://youtu.be/I-kiTYD_atU

### Expected Blizzlike Behaviour

They should be interruptible by melee as well.

### Source

I couldn't find any source that states that they are immune to ONLY physical abilities or that they are immune to interrupts at all.

### Steps to reproduce the problem

1. Get a melee class like a warrior or rogue
2. .tele blackmorass
3. fight a Rift Keeper
4. Try to interrupt it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by v-mstrs** [comment]
https://www.wowhead.com/tbc/npc=21104/rift-keeper#comments;mode:heroic 
`Shadowbolt Volley can be reflected by Warrior. None of the casts can be interupted via Pummel Shield Bash Kick etc.`

**Comment by balleny** [comment]
actually surprised magical interrupts still work. was that missed here https://github.com/chromiecraft/chromiecraft/issues/5159
@Nefertumm ?

**Comment by elthehablo** [comment]
Might be arcane/nature immune?

**Comment by Nefertumm** [comment]
Yeah it seems like I spotted the error. But to be clear, are they supposed to be interruptable or not?

**Comment by balleny** [comment]
Icy Veins "suggests to interrupt whenever possible"
wowhead from 2007 states not interruptable
youtube video from TBC classic shows not interruptable (via warriors shield bash).

I would be confident to say that they should not be interruptable by physical or magical means
