### ISSUE TITLE
Windcaller Claw bugged

### ISSUE THREAD

**Issue by Kirishiki** [chromiecraft/chromiecraft#5725]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

the boss fight with swamplord musel ek and claw, the bear should turn into friendly npc at low hp and be talked to for getting credit for quest "lost and action" but he just doesnt turn and dies.

### Expected Blizzlike Behaviour

the bear turns into friendly windcaller claw at low hp and u can talk to him for credit for quest "lost in action"

### Source

???

### Steps to reproduce the problem

1. go to underbog
2. go to boss swamplord musel ek and claw
3. kill boss and start nuking the bear
4. when hes low hp ull realise hes not gonna get any friendlier and keeps ferociously biting ya
5. u deside to let him out of his misery and dwell in agony for no quest credit

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Buggyswires** [comment]
Confirmed: Claw can be killed and doesn't turn into the human druid form (Windcaller Claw)

**Comment by cachocarne** [comment]
Please fix this so we can all get the quest out of our log XD

**Comment by Vaxsysl** [comment]
Can confirm that it does not work. We cannot make Claw shapeshift back no matter what.

**Comment by 0mnimodus** [comment]
Confirmed. Doesn't turn into the human druid form. Quest "Lost in Action" impossible to complete.

**Comment by KhobarKast** [comment]
Confirmed, quest "Lost in Action" not possible to complete due to missing transformation of Claw at 20% HP while the other boss is already killed.

**Comment by Ren013** [comment]
Confirmed

**Comment by elthehablo** [comment]
Yes this has been an issue since we moved him to script. Will look into fixing it

**Comment by JoPeAlmeida** [comment]
Just did the quest, can confirm it's working now live, thak you very much :)
