### ISSUE TITLE
[Badlands]Node: Double Magenta Fungus Cap Spawns

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#573]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The are double node spawns of Magenta Fungus Cap (https://wowgaming.altervista.org/aowow/?object=128293 and https://wowgaming.altervista.org/aowow/?object=126049)
![doubletwo](https://user-images.githubusercontent.com/80769357/117539276-36c56600-b00a-11eb-8cd7-80164a9a1416.jpg)
![doubleone](https://user-images.githubusercontent.com/80769357/117539278-375dfc80-b00a-11eb-9db5-5110f2a93c89.jpg)
 There are 3 entries so I am not sure which one is the extra one.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only one node should be spawned at a time in these 2 locations, and its either a normal one or the trap one which gives you a disease.
https://www.wowhead.com/item=8047/magenta-fungus-cap#comments
https://classic.wowhead.com/quest=17/uldaman-reagent-run#comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be level 38+ and Have https://wowgaming.altervista.org/aowow/?quest=2500 complete
2. Take https://wowgaming.altervista.org/aowow/?quest=17 and go to provided GUIDs and loot
3. Or Have herbalism and go to provided GUIDs and loot
4. See the double node spawn in these 2 locations

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by heyitsbench** [comment]
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/fd7c8a0bde61508c8654c7be92c9fc2be65d2ac2.
