### ISSUE TITLE
[UI] Observing the Sporelings (9701) - Quest marker not showing up on npc

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#5742]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

On quest [Observing the Sporelings](https://www.wowhead.com/wotlk/quest=9701/observing-the-sporelings) we are required to go to The Spawning Glan zone for observation. Once complete, we need to return to Watcher Leesa'oh at the Cenarion Watchpost.
"?" marker shows on main map, but for some reason it doesn't show on minimap or over the head of the npc which ends the quest. This behavior doesn't happen with other quests from the same npc.

On this image you can see how the "?" shows on main map but not on minimap.
![ 2023-06-08 a las 13 09 54](https://github.com/chromiecraft/chromiecraft/assets/77953030/b407e892-b528-428a-8929-f67426d00dcc)
"?" also doesn't show on top of npc, even tho quest is complete and ready to turn in.
![ 2023-06-08 a las 13 10 03](https://github.com/chromiecraft/chromiecraft/assets/77953030/58f0d655-e629-4a41-8b0c-ee6aa2b8d71a)

### Expected Blizzlike Behaviour

NPC should show a "?" once we complete the quest and until we turn in the quest.

### Source

https://www.wowhead.com/wotlk/quest=9701/observing-the-sporelings

### Steps to reproduce the problem

Have a character of level 61 or more. 
Complete pre-quest "[Watcher Leesa'oh](https://www.wowhead.com/wotlk/quest=9697/watcher-leesaoh)" (9697)
Take quest "Observing the Sporelings" (9701) and go to Spawning Glen until "Complete" appears on screen
Return to Watcher Leesa'oh and check she doesn't show a "?" over her head

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gchekenny** [comment]
Tested as neutral, friendly, revered and exalted, It does always show the "?" for me. 
![WoWScrnShot_061423_225240](https://github.com/chromiecraft/chromiecraft/assets/65800273/dc4f6440-fcac-4192-9bcd-f6be0ba46eee)

**Comment by cachocarne** [comment]
Client-side bug then? Addon issue? Thanks a lot for taking the time to review this.

**Comment by cachocarne** [comment]
Just did the quest with another character and exact same addons. No issues at all. Go figure.
