### ISSUE TITLE
Slave Pens HC, Rokmar the Crackler missing Water Spit

### ISSUE THREAD

**Issue by Nefarianist** [chromiecraft/chromiecraft#5744]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

While fighting Rokmar the Crackler for about 3 minutes, he did not cast Water Spit once.
https://wowgaming.altervista.org/aowow?npc=19895

### Expected Blizzlike Behaviour

Like in this video from 14 years ago, you can see the boss uses Water Spit regularly thoughout the fight.
https://www.youtube.com/watch?v=HT1qtxXWa_c

Sry, i dont know how to link Wowhead comments but here is a citation:
"By 12070 (2,151 – 8·13) on 2007/02/07 (Patch 2.0.6) |  
Heroic: A relatively easy fight, he has the same abilities (the debuff which does not expire unless healed to full), and the water bolt AoE. The water bolt doesn't hit for too much, maybe around 1500. easily healed through.
He hits pretty hard, so I advise you have 2 healers healing for this fight.
He has around 170k hp in heroic"

### Source

Youtube, Wowhead, and https://wowgaming.altervista.org/aowow/

### Steps to reproduce the problem

Fight against Rokmar in SP HC and see if he casts it.

### Extra Notes

https://wowgaming.altervista.org/aowow?npc=19895

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23
 

### Operating system

Ubuntu 20.04
 

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
thought him twice in hc, used it both times.

**Comment by elthehablo** [comment]
Yes can confirm he does cast it today 09/07
