### ISSUE TITLE
Forge Camp: Annihilated

### ISSUE THREAD

**Issue by limgmwmt** [chromiecraft/chromiecraft#5746]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Quest Forge Camp: Annihilated cannot be completed.

The overseers at each camp did drop the keys.

But player unable to use the key to turn and fire the fel cannons to complete the quest.

### Expected Blizzlike Behaviour

Description
Gather your courage, <name>. You will need it if you are to face an overseer.

Once you are ready, find and kill the overseers at each camp. Take their keys and use them to turn and fire the fel cannons upon the camps. Return to me once the camps are destroyed.

### Source

https://www.wowhead.com/quest=10011/forge-camp-annihilated

### Steps to reproduce the problem

![WoWScrnShot_060823_221624](https://github.com/chromiecraft/chromiecraft/assets/88711712/b3783f88-f761-4e13-9a9a-b1f38d6b2a25)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gchekenny** [comment]
Tested, quest works as intended. Stand close to the canons and use the key.

![WoWScrnShot_061423_152233](https://github.com/chromiecraft/chromiecraft/assets/65800273/a2ef0c2a-90cf-4fa8-8266-3a1183df3d60)
![WoWScrnShot_061423_152339](https://github.com/chromiecraft/chromiecraft/assets/65800273/8eda5e25-16d5-46de-a751-cdf48c0a6c7d)

**Comment by limgmwmt** [comment]
ohh so need to right click the key. i was trying to rightclick the cannon. thank for info

**Comment by Si1ker** [comment]
@Gultask close.
