### ISSUE TITLE
Missing object "Waterlogged Envelope" (Item-ID: 4433)

### ISSUE THREAD

**Issue by pixelhaufen-cc** [chromiecraft/chromiecraft#575]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Ingame object "Waterlogged Envelope" (Item-ID: 4433), which starts quest "Sully Balloo's Letter" (Quest-ID: 637), is missing.

![image](https://user-images.githubusercontent.com/83879570/117548077-355c6380-b033-11eb-9838-73ed1d09d948.png)

(waited for ~17 minutes for the object to spawn, to rule out that another player interacted with the missing object)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

In Arathi Highlands (at around 44.29/92.88) there should spawn a small envelope (object) next to a crushed dwarf, which provides a simple delivery-quest "Sully Balloo's Letter" and ends in Ironforge at Sara Balloo (NPC-ID: 2695; 63.8/67.6).

![image](https://user-images.githubusercontent.com/83879570/117548092-40af8f00-b033-11eb-9e2e-c388354ddd2f.png)

Also opens up the follow-up quests:
* Sara Balloo's Plea (Quest-ID: 683)
* A King's Tribute (Quest-ID: 686)
* A King's Tribute (Quest-ID: 689)
* A King's Tribute (Quest-ID: 700)

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

https://classic.wowhead.com/item=4433/waterlogged-envelope

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Synful-Syn** [comment]
I did that quest a few weeks ago.
It has a 2 hours cooldown according to this. https://wowgaming.altervista.org/aowow/?object=2656

**Comment by gurveleg** [comment]
Yes, I just looted the quest myself earlier, maybe thats why it wasnt there

**Comment by pixelhaufen-cc** [comment]
Alrighty, wasn't aware of the higher than normal respawn time. Will check later if I've got more luck then.
