### ISSUE TITLE
[Loot] Nexus-Prince Shaffar heroic only drops 1 item

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#5767]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Nexus-Prince Shaffar only drops one blue quality piece of gear in heroic version.

### Expected Blizzlike Behaviour

Should drop two blue quality pieces of gear in heroic version.

### Source

https://youtu.be/ybocfErQyUc?t=925

### Steps to reproduce the problem

.add 30633
.tele manatombs
.char level 70
Set to heroic and kill Nexus-Prince Shaffar.

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=20266

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by pangolp** [comment]
I don't know the dungeon, but I have made it on the test server and the result can be seen in the final photo. All the bosses, which if I remember correctly, are 3 in total, gave me 1 blue item each, except the last boss, which gave me a little more loot, although I don't know if it is the expected or not. I hope to have collaborated with the tests, anything, let me know.

![WoWScrnShot_061123_112258](https://github.com/chromiecraft/chromiecraft/assets/2810187/af446e91-d9f3-465c-929d-88370774f80a)

**Comment by pangolp** [comment]
I did the instance again just in case, because I saw that there were several reports on different bosses, so I could take individual pictures of the loot obtained in each one of them.

![WoWScrnShot_061123_113837](https://github.com/chromiecraft/chromiecraft/assets/2810187/44494f24-5c78-4c43-a2d2-99f334ac057c)
![WoWScrnShot_061123_113840](https://github.com/chromiecraft/chromiecraft/assets/2810187/c43368f7-b841-48df-9975-d9a79fd65b45)
![WoWScrnShot_061123_113909](https://github.com/chromiecraft/chromiecraft/assets/2810187/89700138-d10d-40aa-8f44-0d1570219cfa)
