### ISSUE TITLE
"You have unread mail"

### ISSUE THREAD

**Issue by BugSquisher9000** [chromiecraft/chromiecraft#5770]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

So I bought faction change for my hunter and I can not faction change beacuse there is a major bug that blocks me from faction change because of this bug here

When I close mailbox it still gives me same message.

### Expected Blizzlike Behaviour

It should remove you have unread mail and be able to make me faction change. 

### Source

There are no better source than this is a major bug

### Steps to reproduce the problem

No idea how it started

### Extra Notes

GM HELP ME

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vkdog** [comment]
I've seen comments in Discord suggest this is 'known issue' and is 'hard to resolve' yet no update here. Never really an issue until I tried to faction change also.. 

Currently have an open support ticket for the faction change.

**Comment by Nyeriah** [comment]
If you are trying to faction change and there are pending mails it has nothing to do with this issue, faction change only blocks you if you actually have pending mails (action house, quest rewards, npc mails, etc.). Time quest mails (e.g winterfall fire water) may take up to 3 days to be delivered.

**Comment by vkdog** [comment]
I have no pending mails or auctions or quest rewards. Will await the outcome of the ticket I raised

**Comment by BeefSteaker** [comment]
This is an issue for #support-ticket not a general game bug
