### ISSUE TITLE
Corrupted Ashbringer causes you to aggro neutral mobs and guards

### ISSUE THREAD

**Issue by GoblinKing1337** [chromiecraft/chromiecraft#5776]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

If you equip Corrupted Ashbringer, neutral/yellow mobs will aggro you as if they are hostile. Neutral Guards will also 'aggro' you but not attack, placing you in combat.

### Expected Blizzlike Behaviour

No effect on regular yellow mobs or guards.

### Source

PTR, equipping CA

### Steps to reproduce the problem

Equip CA
Run to a yellow mob (like start zone mobs) and watch them aggro you like hostile mobs.
Teleport to Shattrath, and walk to city guard, watch them try to dismount and attack you, but reset instantly, keeping you in combat.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

windows10

### Customizations

None

### Server

ChromieCraft, PTR

**Comment by gchekenny** [comment]
Tested, Issue confirmed
Item: https://www.wowhead.com/wotlk/item=22691/corrupted-ashbringer#comments
Spell: https://www.wowhead.com/wotlk/spell=28282/ashbringer#comments

Being attacked by random neutral creatures: is INCORRECT behaviour
![WoWScrnShot_061423_125919](https://github.com/chromiecraft/chromiecraft/assets/65800273/44395b49-b7cf-46f7-aa8f-0e9a30ad8409)

Aggro and resetting neutral npcs: is INCORRECT behaviour
![WoWScrnShot_061423_133806](https://github.com/chromiecraft/chromiecraft/assets/65800273/94dd61e2-2bd5-4f71-a75d-928a1cd779a4)

Hostile to Argent Dawn: Works and is correct behaviour
![WoWScrnShot_061423_131701](https://github.com/chromiecraft/chromiecraft/assets/65800273/6ac31123-d887-45eb-b09a-ee7fd69b1300)

Friendly at Scarlet Monastery's Cathedral: Works and is correct behaviour
![WoWScrnShot_061423_132508](https://github.com/chromiecraft/chromiecraft/assets/65800273/83478aac-6626-46c0-8164-23ed450b427a)

**Comment by heyitsbench** [comment]
Should be fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/0895ed0899cdd52818c94e3dda1795e1db4447be.
