### ISSUE TITLE
[Outlands, Mobs, Loot] Inappropriate loot levels from HFP mobs.

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5785]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

HFP mobs drop items inappropriate to their level and the level of quests that they are objectives of.   During the 58-61 quest tier, mobs are dropping level 62+gear almost exclusively, with very rare pieces of level-appropriate gear.  The ratio is roughly 1:3 appropriate vs. inappropriate.  

This is disregarding the known boost of blue drops, focusing purely on the required level of BoE regardless of rarity.

### Expected Blizzlike Behaviour

Early Hellfire Peninsula mobs generally drop the Level 58-61 Outlands BOE greens/blues.

### Source

https://www.wowhead.com/wotlk/items/armor/min-level:80/min-req-level:58/max-req-level:61?filter=3;1;0

If you go through this, you will see which mobs should be dropping the appropriate items by default.  Also, in general, mobs should drop level appropriate items.

### Steps to reproduce the problem

Can be triaged concurrently with this one:
https://github.com/chromiecraft/chromiecraft/issues/5784

When checking runecloth, also check the required level on the BOE drops you have collected.  Roughly 75% of them will be required level 62 or higher.

This can also be observed with mass slaughter of the low-level bonechewer orcs to the north or south of the road of glory area, such as https://www.wowhead.com/wotlk/npc=16925/bonechewer-raider

Also, the low-level boars near Thrallmar or Honor Hold can easily be killed en masse to observe the off-kilter drop rates.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cythisiax** [comment]
As of https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e the loot tables are matching current source to also what is live on Classic WOTLK. BOE/SB drops ranging from level 58 to 61.
