### ISSUE TITLE
Samuel Fipps

### ISSUE THREAD

**Issue by Riphook** [chromiecraft/chromiecraft#58]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

**|======MODERATION EDIT Strart======|**
NPC: [Samuel Fipps](https://wotlkdb.com/?npc=1919)
**|======MODERATION EDIT End======|**

Samuel Fipps was identified as "Unknown" when I first saw him, killed him, respawned with proper name. Not sure if this is a bug or just a cache issue.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Unknown is bad

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
It is not a bug, the NPC has the name and it works, this is a classic "Cache" problem, I suggest you clear the Cache every time before opening the WOW Client.

And in the future try to report with Links, as I showed you in the edit I did in your post, pls.
Having the IDs of the NPC/ITEM/QUEST/ETC at hand, you facilitate the work in its execution.

**Comment by illfated** [comment]
Can confirm, this happens in other repo servers as well. If your game client does not update its cache often enough or as fast as expected, you get those "Unknown" NPCs and even the player's own pet (sometimes also the player name itself). Make it a habit of cleaning your game client cache manually once in a while.
