### ISSUE TITLE
Deadmines: Patrols rushes through the closed door during Rhahk'Zor fight

### ISSUE THREAD

**Issue by Jinmcx** [chromiecraft/chromiecraft#580]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Patrols rushes into the battle of Rhahk'Zo.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Patrols would stay behind the door and not get involved until the doors open.

##### STEPS TO REPRODUCE THE PROBLEM:

1. It just occurred during dungeon not sure if it's reproducible. 

##### EXTRA NOTES:
--

N/Ad

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Jinmcx** [comment]
![WoWScrnShot_050821_184555](https://user-images.githubusercontent.com/19652090/117560010-41eab700-b047-11eb-9fbc-27e930297362.jpg)

**Comment by Stump876** [comment]
That is interesting. I tried to reproduce without any success. I tanked Rhahk'Zor as close to the door as I could get him. I even did an area taunt to see if I could pull them from the other room. Nothing. The watchmen don't run, so I pulled some mobs I had skipped earlier down to the room to see if they would run through the door, and they did not.  I can't argue the screenshot, but I can't duplicate it either.

**Comment by Azcobu** [comment]
Yep, same. Tried on my bear, and spammed area taunts at the door and around either side of the entrance, and never got a response from the mobs on the other side. Looking at your party, you have a shammy and 2 pallies - wondering if a chain lightning or one of the ranged pally abilities might have managed to tag a mob on the other side of the door somehow?

**Comment by FrancescoBorzi** [comment]
@Stump876 @Azcobu thanks for your feedback guys, don't forget to apply the [Unable to Reproduce] label ;)
