### ISSUE TITLE
[NPC] Kilrath (18273) - Possible incorrect behavior/reaction

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#5804]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

NPC [Kilrath](https://www.wowhead.com/wotlk/npc=18273/kilrath) (level 68 Orc elite) is a questgiver located in Terokkar Forest (19.8, 60.8).
This NPC is currently passive when approached by Alliance players.
![ 2023-06-18 a las 16 03 15](https://github.com/chromiecraft/chromiecraft/assets/77953030/4008adab-b1c4-4e43-9f51-888082c9d98a)

### Expected Blizzlike Behaviour

According to Wowhead and Wowpedia, the NPC is friendly to Horde players and hostile to Alliance players.
When approached by Alliance, he should react and attack. 

### Source

https://www.wowhead.com/wotlk/npc=18273/kilrath
https://wowpedia.fandom.com/wiki/Kilrath
Even the first [comment on Wowhead](https://www.wowhead.com/wotlk/npc=18273/kilrath#comments) is about how dangerous he is to Alliance players.

### Steps to reproduce the problem

Have an Alliance character
Move to Terokkar Forest, close to where npc is (around 20,61)
Observe how npc is passive and won't mind you.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> ### Source
> Even the first comment on Wowhead is about how dangerous he is to Alliance players.

That first comment specifically says the following: 'If you're alliance : don't touch him !'

This would indicate to me that not touching him (in my mind, not hitting him) wouldn't aggro him. Either way, on Classic he is also passive.

**Comment by cachocarne** [comment]
Oh, you might be probably right about this. I was thinking that having him move around every time he aggroes could be a terrible idea for players who might need the quests.
