### ISSUE TITLE
Kruul's Costume (HC Pala reward) has no attack animations

### ISSUE THREAD

**Issue by GoblinKing1337** [chromiecraft/chromiecraft#5807]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Kruul's Costume doesnt have any attack animations (reward from Hardcore completion of Paladin class).

Equipping the costume and attacking with it triggers no animations, Kruul just stands there with weapon in hand.

### Expected Blizzlike Behaviour

Not sure about blizzlike but the costume could have attack animations like normal Kruul: https://www.youtube.com/watch?v=-dIJtXEylV8

### Source

Kruul's costume rewarded in game for HC paladin completion 

### Steps to reproduce the problem

Finish Paladin hardcore to 70 and obtain Kruul's Costume Reward
Equip Costume
Attack a mob with costume equipped, and observe no attack animations.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Windows 10

### Customizations

None

### Server

ChromieCraft

**Comment by InvictaChromie** [comment]
tested just now a little bit (26th june 2023)  on my paladin on target dummy while shapeshifted with kruul costume:

autoattacks have animations, jumping has no animation, casting spells like heals/consecration/exorcism have animations,
melee abilities like divine storm/crusader strike seem to have no animation,

judgement has animation, technically considered a spell I think? 

not sure if this helps but that's what I could see on a quick test at least!

**Comment by Nyeriah** [comment]
Thanks for the report but unfortunatelly this is not something we can fix as we cannot add animations to the client. We'll see what we can do at our side of things.

Thanks once again,

Kind regards.
