### ISSUE TITLE
Buffs not effecting NPCs

### ISSUE THREAD

**Issue by Stump876** [chromiecraft/chromiecraft#581]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Buffs that can be applied to NPCs should provide them with the buff. However, at least with stamina altering buffs it does not effect them at all. I would assume this would apply to other stats as well.
![image](https://user-images.githubusercontent.com/68164076/117559654-ff6fad00-b03b-11eb-8485-82d8fda3edfe.png)
![image](https://user-images.githubusercontent.com/68164076/117559661-0e565f80-b03c-11eb-821e-5730ad4f51b2.png)

![image](https://user-images.githubusercontent.com/68164076/117559719-86248a00-b03c-11eb-8b6e-c1e82649869b.png)
![image](https://user-images.githubusercontent.com/68164076/117559711-76a54100-b03c-11eb-976d-6bc084412e3f.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

"Power infuses the target, increasing their stamina"
[https://classic.wowhead.com/spell=10938/power-word-fortitude](https://classic.wowhead.com/spell=10938/power-word-fortitude)
"Places a blessing on the friendly target, incresing total stats by 10%"
[https://classic.wowhead.com/spell=20217/blessing-of-kings](https://classic.wowhead.com/spell=20217/blessing-of-kings)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Try buffing random NPCs I know we've all buffed the auctioneer or banker accidently at some point.
2. 
3. 
4.

##### EXTRA NOTES:

I like turtles

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5745#issuecomment-835834204
