### ISSUE TITLE
[Fire Festival]  Bonfire Graphics Missing from all non-capital locations.

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5813]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

There is only the firepit and coals - the fire itself (which should be interactive for extinguishing) is not present.

Sample fireless fire:
![image](https://github.com/chromiecraft/chromiecraft/assets/131016474/07a76461-73e3-40b5-9457-5bfc59b4a2fc)

### Expected Blizzlike Behaviour

There should be fires present that can be interacted with to extinguish or ignite.

### Source

![image](https://github.com/chromiecraft/chromiecraft/assets/131016474/ecce1a44-ec67-4dee-8bab-99a207d7ce1a)
https://www.wowhead.com/event=341/midsummer-fire-festival#screenshots

### Steps to reproduce the problem

1. teleport to any major quest hub that is not a capital, and go to the nearby fire festival tent.
2. note that there is no actual fire present, only the firepit and coals.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
This appears to be a character issue. I went to Tarren mill/ Southshore and put out the horde fire. It went out. 
![image](https://github.com/chromiecraft/chromiecraft/assets/68164076/2efb3105-3a91-46d1-98d6-779537ed2882)
![image](https://github.com/chromiecraft/chromiecraft/assets/68164076/a5c2fd76-3507-418c-9483-24517533a44f)

I then went to a horde character and the bonfire was there. 
![image](https://github.com/chromiecraft/chromiecraft/assets/68164076/8749f60e-b9e4-4138-96dd-2815ea614975)

Logging back over to alliance it stil showed it stomped out
![image](https://github.com/chromiecraft/chromiecraft/assets/68164076/a4782af9-1d65-41e3-aaad-7ca270001776)


I'd like to get another triager's thoughts on this.

**Comment by Vyperhand** [comment]
Neither my wife nor I have yet to see a correct fire at any quest hub, though we both see the quest-hub style fires as the "extras" that have spawned in the cities.  Using a burning blossom to "ignite" a fire gives the buff, but makes no graphical change.

If there's some form of client repair that might affect this I would be happy to try it on both our PCs, but the basic clearing cache and WTF didn't fix it for either of us.  Have chatted with other characters in-game and confirmed they were seeing the same graphics.

**Comment by Vyperhand** [comment]
I have screenshots from this morning from multiple characters, both factions, zones on each continent + HFP/outlands if that helps at all.

**Comment by Vyperhand** [comment]
Hostile fires same.   Desecration quest works normally, get the smoke/steam animation and sounds from the coals.  Tested on HH fire in HFP and Southshore fire in Hillsbrad.
![WoWScrnShot_062523_103813](https://github.com/chromiecraft/chromiecraft/assets/131016474/64c2d5b6-8ffe-4686-8e0f-31ae799dcb37)
![WoWScrnShot_062523_103417](https://github.com/chromiecraft/chromiecraft/assets/131016474/dba0f36b-c4d2-4811-8564-0a255aa8af62)

**Comment by Vyperhand** [comment]
@Stump876 - the fire graphics have been spawning correctly since the Ahune restart.  Seems someone might have stealth fixed this?

**Comment by Gultask** [comment]
Seems to be a side-effect of fixing that bug where multiple bonfires were spawning on top of each other in capital cities.

I currently don't know why they're disappearing, though. I placed bonfires everywhere

**Comment by sudlud** [comment]
As of current AC master this issue should not exist anymore.

Bonfire handling was completely rewritten and should always work as intended now.
