### ISSUE TITLE
[NPC] Blackpaw Shaman won't move when silenced

### ISSUE THREAD

**Issue by Salehyn** [chromiecraft/chromiecraft#5817]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

https://www.wowhead.com/wotlk/npc=16337/blackpaw-shaman this npc uses lightning bolts to attack by default (which works fine) however when their spells are interrupted/silenced, or they run out of mana, they become idle and just stare at you, refusing to follow the player as any other caster would in similar circumstances.

### Expected Blizzlike Behaviour

The NPC should move to the player and attempt to melee when they cannot cast spells due to silence/oom.

### Source

https://www.wowhead.com/wotlk/npc=16337/blackpaw-shaman
https://www.youtube.com/watch?v=_f-tsARPHw8&t=91s you can see on this video that the shamans melee between casts and when interrupted

### Steps to reproduce the problem

Engage NPC, silence them or wait for them to run out of mana, then attempt to move them by stepping backwards with your character. The NPC will just stand still and do nothing until it can cast again.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Vyperhand** [comment]
This seems to be a global or near-global issue with how caster mobs react to being silenced.  Whatever the fix is will end up being a global/core change, I think.

**Comment by Salehyn** [comment]
Most casters I met here properly follow you once they run out of mana. It's a different story that casters on AC seem to be fucked in general... but it's usually their damage that is off.

**Comment by Vyperhand** [comment]
True, they do eventually run up when oom.  But in general, you silence and they just stand there - the default "if you can't do anything else close to melee" seems to either be missing or not working for the silence condition specifically.  If these don't close when full oom, that's probably a separate issue.

**Comment by elthehablo** [comment]
This has to do with proper distinguishable caster AI missing in the core. It is indeed a known issue.

**Comment by elthehablo** [comment]
Looks like someone tried to script this behaviour for this specific mob manually. It would be interesting if this is what messes it up. For reference, I'm comparing this to this mob: https://www.wowhead.com/wotlk/npc=453/riverpaw-mystic

**Comment by elthehablo** [comment]
After testing, the Riverpaw Mystic, which only essentially has some lines to flee and cast spells doesn't walk to me when silenced (which is normal behaviour on AC unfortunately), but does walk up to me and does melee attacks when OOM. For the Shamans, the behaviour is as you described.
