### ISSUE TITLE
Watertight trunks sometimes empty

### ISSUE THREAD

**Issue by Stump876** [chromiecraft/chromiecraft#582]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Watertight chests occasionally are empty. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should contain something.
[https://www.wowhead.com/item=21113/watertight-trunk#contains](https://www.wowhead.com/item=21113/watertight-trunk#contains)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .additem 21113 
2. Open boxes and you should get an empty one occasionally
3. 
4.

##### EXTRA NOTES:

Testing on a local server, spawning 16 I had 2 come up empty.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
I can confirm that this sometimes happens. I also **believe** that on retail I never encountered an empty trunk, yet I haven't found any evidence that would prove it.
@Stump876 Do you have any source from the WotLK era to back up your (and my) claim?

**Comment by Stump876** [comment]
If you're asking if I can find a statement from Wrath that says these contain loot 100% of the time. That will not exist. On the flip side I can't find evidence of there NOT being loot. I checked comments for someone saying they received an empty trunk. Same with finding a statement that says all rare spawns drop something. I never encountered it on retail either and after getting 2 I thought it should be reported. The best I can do is give the loot table. I can see if this happened one time it would be a fluke. Twice, ok, maybe just really unlucky, but its been reproduced and confirmed. If the general consensus it "it's not normal" then it's not normal.

**Comment by necropola** [comment]
Since we all have access to the AzerothCore loot tables (open soucre), I can see that it pretty much implements what you can find on WotLKDB, aowow DB, etc., but it's possible by design that it also drops zero loot (so not a fluke) which non of the sources mentioned above does explicitly exclude.

I found a video of someone opening 100 of each type of trunk and none was empty, but that was sadly from 4.x (cataclysm). It would have been exactly what we needed. **General consensus** is most likely not enough to get a change pushed through.

I'll talk to some devs to find out what they think. Meanwhile you could try to find a video or something similar from WotLk times to back up the "general consensus*.

**Comment by necropola** [comment]
FYI, I found a source for Classic.
Someone doing [unboxing videos on YT](https://www.youtube.com/watch?v=PUV9kUAgiQM ) for various trunks received from fishing. 
It's not a perfect (WotLK) source but not too bad either.

**Comment by Stump876** [comment]
I think that might be the problem. I don't think I noticed any coins at all in my tests. Honestly, I was not paying attention for coins. Do you think the blank ones should have contained coins and that's what was missing? Thanks for helping look into this, I've been getting inconclusive on a lot of it. I thought if the Devs would agree, it would save a lot of legwork. I'll retest later today looking for coin.
