### ISSUE TITLE
[NPC] Burning Blade Cultist / Imp minion spell damage

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#5820]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

This lvl 10 NPC's https://www.wowhead.com/wotlk/npc=3199/burning-blade-cultist imp pet https://www.wowhead.com/wotlk/npc=12922/imp-minion is currently doing 18-20 damage with their firebolts https://www.wowhead.com/wotlk/spell=20801/firebolt#used-by-npc, which is roughly double the intended value.

The Cultist himself does 24-26 damage with their immolate https://www.wowhead.com/wotlk/spell=11962/immolate burst damage and 7 damage per tick afterwards, which is roughly 40% higher than the original values as well.

### Expected Blizzlike Behaviour

Here is a video that shows their damage on blizz https://www.youtube.com/watch?v=SPSjgW-GgCY you can see the numbers on the shaman's portrait... 9-11 damage from the imp casts (yellow numbers), only the Cultist's immolate hits for 19. The immolate ticks do only 5 damage.
Note, while the video was recorded on classic, enemies in Azeroth received no boosts to their power, only nerfs as the expansions progressed to 3.3.5a. There is no reason why spellcasters on this server deal twice as much damage as they did on vanilla classic (or on any other 3.3.5a server for that matter)

### Source

linked above

### Steps to reproduce the problem

Engage these npcs and their pets and observe damage done against a player in the adequate level range (9-12).
Note that the bloody imps do more damage than their owners....

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/17649
