### ISSUE TITLE
Avatar of the Martyred not dropping any item

### ISSUE THREAD

**Issue by anjachan** [chromiecraft/chromiecraft#5824]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Avatar of the Martyred did not drop any item on death whatsoever.

### Expected Blizzlike Behaviour

He should drop items

### Source

https://cdn.discordapp.com/attachments/788799234207252540/1121779696695255060/image.png
https://cdn.discordapp.com/attachments/788799234207252540/1121778397136310292/Shortcut_2023-06-23_14-25-12.png

### Steps to reproduce the problem

1. Get Maladaar to 50%
2. slow dps him until he spawn the Avatar
3. Kill the spawned Avatar before the main boss
4. he doesn't drop anything 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fb7164be05ff507a0e25200c9e267b87186e2850

### Operating system

Arch Linux

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sombritas** [comment]
I was part of the run, yesterday was one bug of loot disappearing cause main boss died. And today no loot at all from the avatar

**Comment by Vyperhand** [comment]
Looks like WoWHead confirms - boss has no drops on normal mode, but a table of blues should drop on heroic.
https://www.wowhead.com/wotlk/npc=18478/avatar-of-the-martyred#drops;mode:heroic
https://www.wowhead.com/wotlk/npc=18478/avatar-of-the-martyred#comments;mode:heroic

**Comment by elthehablo** [comment]
Indeed on normal mode he does not drop loot. I've killed him on heroic and got loot. My assumption would be that this kill was on normal mode. But I will leave this up for a confirmation that this was instead on heroic mode. Whatever the case https://github.com/azerothcore/azerothcore-wotlk/pull/16523 should've fixed any loot bugs on heroic
