### ISSUE TITLE
Dungeon Browser Queue sorting issue

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5825]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

1) When you have a dungeon group forming being cancelled or unsuccessful aborting, you receive the notification
> ... you have been placed at the top of the search queue
but actually, you arent placed back to your "top position" but are instead dropped further down the line.

2) In a similar manner, when you queue with a group that is already inside an dungeon (hence a group which already formed successful once) because you have to fill up the group again, you are supposed to be sorted on top of already waiting groups. this might be off, too - but I couldnt confirm it yet.
=> called Looking for More

### Expected Blizzlike Behaviour

1) when an attempt to create a group fails, you should be moved back to your original position instead of being moved down the waitlist.

2) if you queue from an existing group, from an unfinished dungeon, you are supposed to be moved on top of the current stack. if a second group is queuing too, it would be sorted after the first group (or practically, you would have 2 separate queues (prio and regular).

### Source

https://wowpedia.fandom.com/wiki/Dungeon_Finder

dont have the right sources at hand right now - just generic ones - will add later

### Steps to reproduce the problem

1)
queue with 2 heals (= h1, h2) and 6 damage dealers (d1, d2, d3, ...).
then queue with a tank (=t1).
h1, d1, d2, d3, t1 should receive a popup. accept the queue with h1, d1, d2, t1 and then let the queue (via d3) expire.

Now, h1, d1, d2, d4, t1 should receive a popup. But, instead it seems that h2, d4, d5, d6, t1 receive the popup.

2)
in a similar manner, successful queue and enter a dungeon with h1, d1, d2, d3, t1.
Next queue with h2, d4, d5, d6
then leave the dungeon with t1.
requeue the dungeon group consisting of h1, d1, d2, d3
now, queue with t2.
t2 should get grouped with h1, d1, d2, d3 and not with h2, d4, d5, d6

### Extra Notes

this report is based on ingame experience and may contain errors. the steps to reproduce should help verifying behavior

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fb7164be05ff507a0e25200c9e267b87186e2850

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Wosser** [comment]
It feels really shitty to have RDF pop after waiting for a while only for a DPS to be AFK and decline and then have the tank and/or healer be put into a different group and you have to wait again for an unknown time, being punished for someone else not accepting the queue.

**Comment by emuduck** [comment]
bump. on a low pop server an insanly annoying bug that deserves some prio.

**Comment by balleny** [comment]
so far, duplicate tag was used with a reference to the original database WITHIN the same repository.
reports made in CH bugtracker have been copied over into AZ repository usually and getting a Linked tag, but not a duplicate tag.
