### ISSUE TITLE
[Progression] Profession adjustments

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5835]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Inscriptions Darkmoon Cards (oversight) and Engineering goggles (intentional) have been made available ahead of their supposed point in time of progression.
Tailoring cloth cds are 20h instead of 3d20h.

Jewelcrafters Brilliant Glass is currently removed.

### Expected Blizzlike Behaviour

Given that the other crafting professions have had their blizzlike progression being altered already, i would suggest to enable the Brilliant Glass for jewelcrafters, too.

It should have a regular cooldown (once a day iirc).
Given the current state of content, the existing, yet slim, chance for epic gems to be included should be removed for obvious reasons, until later part of the content.

### Source

https://github.com/chromiecraft/chromiecraft/issues/4399

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fb7164be05ff507a0e25200c9e267b87186e2850

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
staff review / progress discussion appreciated

**Comment by balleny** [comment]
i know its supposed to be a suggestion, anyway would hope for a timely response

**Comment by Nyeriah** [comment]
This is a suggestion and not an issue.

**Comment by balleny** [comment]
nope, this is a bugreport for inconsistencies applied to chromiecraft and present in
https://github.com/azerothcore/mod-progression-system

**Comment by Nyeriah** [comment]
> i know its supposed to be a suggestion, anyway would hope for a timely response

Please post a proper suggestion if you wish your suggestion to be analyzed and implemented and receive a proper response. Reiterating that this is a suggestion and not an issue, locking this report for the time being.
