### ISSUE TITLE
Rare mob Gorefang not dropping loot

### ISSUE THREAD

**Issue by Stump876** [chromiecraft/chromiecraft#584]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Gorefang dropped nothing
![image](https://user-images.githubusercontent.com/68164076/117561254-f38ae780-b049-11eb-9d23-18be7004dd51.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As with all rare mobs, they should all drop a common (white) quality or higher item. 
[https://wowwiki-archive.fandom.com/wiki/Rare_mob](https://wowwiki-archive.fandom.com/wiki/Rare_mob)
Loot table for Gorefang
[https://www.wowhead.com/npc=12431/gorefang](https://www.wowhead.com/npc=12431/gorefang)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .npc add 12431
2. Kill and see if there is loot.
3. Make sure to .npc delete any spawns or it will respawn in that spot
4.

##### EXTRA NOTES:

Testing on a local server, sometimes loot was dropped, sometimes it wasn't.
7/10 dropped loot that was not standard wolf loot. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
c.f. - https://github.com/chromiecraft/chromiecraft/issues/583

I think the discussion there applies equally to this mob as well, and need not be repeated.
