### ISSUE TITLE
Ahune is only dropping normal mode loot on heroic mode

### ISSUE THREAD

**Issue by quigiboo** [chromiecraft/chromiecraft#5841]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Currently ahune drops cloaks, the normal mode loot table on heroic mode.
https://www.wowhead.com/tbc/object=187892/ice-chest#contains;mode:normal;0+4-20+1

### Expected Blizzlike Behaviour

He should be dropping necklaces on heroic mode
https://www.wowhead.com/wotlk/object=188124/ice-chest#contains;mode:heroic;0+10-20+1

### Source

heroic: https://www.wowhead.com/wotlk/object=188124/ice-chest#contains;mode:heroic;0+10-20+1
normal: https://www.wowhead.com/tbc/object=187892/ice-chest#contains;mode:normal;0+4-20+1

### Steps to reproduce the problem

set difficulty to heroic
enter slave pens
summon ahune
kill ahune
open chest
loot only normal mode loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fb7164be05ff507a0e25200c9e267b87186e2850

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by quigiboo** [comment]
loot from 18 ahune kills on heroic difficulty on the ptr.
![image](https://github.com/chromiecraft/chromiecraft/assets/114075548/03abcadb-7a1e-4789-bff1-f879a8dbc189)

**Comment by heyitsbench** [comment]
CC: @Nyeriah

**Comment by Nyeriah** [comment]
CC: @Gultask ❤️
