### ISSUE TITLE
Paladin:  5/5 points Seals of the pure talent not adding 15% damage to seal of corruption, judgement part seems OK though

### ISSUE THREAD

**Issue by InvictaChromie** [chromiecraft/chromiecraft#5842]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

first of all this already seems to have been reported here(?): https://github.com/azerothcore/azerothcore-wotlk/pull/16559 
but wanted to add my own test here on the chromiecraft specific bug tracker for extra confirmation, so to speak.

Currently, having 5/5 points specced into seals of the pure talent does not add 15% damage to seal of corruption damage, it does add 15% damage to judgement of corruption though, so the judgement damage bonus of the talent seems OK.

![sealofcorruption_withandwithouttalent](https://github.com/chromiecraft/chromiecraft/assets/86496802/08535160-de11-4d98-b552-f3397ce9bc02)

top right + bottom right shows 15% damage difference in judgement with/without talent specced,

top left + bottom left shows 0 damage difference in seal damage with/without talent specced

there was two adjustments/nerfs to paladin seals in the recent past, on the 7th march 2023 and 25th may 2023:

(screenshot from changelog channel on chromiecraft discord)

![s](https://github.com/chromiecraft/chromiecraft/assets/86496802/acc64e2d-3cac-4f10-8fb7-b55fcb4eccb9)

possibly something went wrong there? other than this specific 15% seal damage bonus not working there might be other issues as well after the changes on 7/3/2023 and 25/5/2023 but can't confirm that at this moment.

### Expected Blizzlike Behaviour

the talent seals of the pure should add 15% damage not only to the judgements but also to seal damage:

https://wowgaming.altervista.org/aowow/?spell=20332

"Increases the damage done by your Seal of Righteousness, Seal of Vengeance and Seal of Corruption and their Judgement effects by 15%"

### Source

see above screenshots / wowgaming link / talent description

### Steps to reproduce the problem

 perform a dps test with 0/5 talent points specced into Seals of the pure vs 5/5 talent points specced, after test is done compare "seal of corruption" damage on your damage meter, there will be no difference when there should be a 15% difference

### Extra Notes

no extra notes at this time that I can think of

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fb7164be05ff507a0e25200c9e267b87186e2850

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
usually, the best approach for a test like this is using a naked char, with a white/grey weapon, which has a minimal range between weapon min and weapon max damage. this reduces variations coming from procs, buffs, etc.

further, it makes sense to test it without any talent and then stepwise adding talent points, every time screenshotting / resetting recount.

(these are mostly hints to make it easier for someone to validate / reproduce your tests)

**Comment by avarishd** [comment]
Couldn't reproduce for any of the seals, all work as intended.
