### ISSUE TITLE
Incorrect reputation gains from kills while grouped

### ISSUE THREAD

**Issue by Rhikza** [chromiecraft/chromiecraft#5848]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Killing a mob that gives reputation to a faction outdoors (for example, Syndicate mobs in Hillsbrad Foothills or Venture Co. goblins in Stranglethorn Vale) gives 5 reputation when solo. If you are grouped with another person, the reputation is halved to 2.5 rep for each person. Adding another player to the group again halves the reputation to 1.6 rep for each person.

### Expected Blizzlike Behaviour

The reputation should be gained fully by the whole party, no matter how many people are in the group. So a solo person should get 5 rep, a two person group should each get 5 rep, and a full party of 5 members should each get the full 5 rep.

### Source

Any guide to any reputation farming that includes killing mobs, for example:
https://www.wowhead.com/classic/guide/neutral-faction-reputation-overview-wow-classic
After extensive searching, I have yet to find any guide/mention that says you should avoid grouping as reputation would get halved. Most guides recommend grouping for faster farming with no mention of getting less reputation for each kill.
Another generic guide to how reputation works:
https://wowpedia.fandom.com/wiki/Reputation
Again, no mention that grouping would halve your reputation gained for killing mobs.

### Steps to reproduce the problem

1. Kill a Syndicate mob solo in Hillsbrad Foothills, check how much reputation you gain.
2. Add a party member, kill another Syndicate mob, check how much reputation you gain.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a779cca9e3a3d673761d6bbe6d1c5d1f51c2f6f3

### Operating system

Windows 10 Pro 64-bit

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
[And it does not get affected on Classic.](https://github.com/chromiecraft/chromiecraft/assets/38561765/43ade927-8706-4bf8-8df3-1625d1001637)

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
