### ISSUE TITLE
Against the Legion

### ISSUE THREAD

**Issue by Wosser** [chromiecraft/chromiecraft#5853]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Altruis the Sufferer doesn't give me the quest "Against the Legion".

### Expected Blizzlike Behaviour

The quest should become available from lvl 68 after completing Forge Camp: Annihilated.

### Source

https://wowgaming.altervista.org/aowow/?quest=10641

### Steps to reproduce the problem

Complete the quest chain starting with https://wowgaming.altervista.org/aowow/?quest=9991 

### Extra Notes

Quest: https://wowgaming.altervista.org/aowow/?quest=10641
NPC: https://wowgaming.altervista.org/aowow/?npc=18417

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a779cca9e3a3d673761d6bbe6d1c5d1f51c2f6f3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Vyperhand** [comment]
The AoWoW link shows the quest as disabled - but I cannot find any reason WHY it is disabled.  It's not in the list of quests disabled for progression.
![image](https://github.com/chromiecraft/chromiecraft/assets/131016474/76a8f347-0f20-430f-91ec-51095601f9ef)


Does anyone know why it was disabled in the first place?

**Comment by Wosser** [comment]
I got the quest now, but it only unlocked after completing https://wowgaming.altervista.org/aowow/?quest=10640 , which according to the database shouldnt be a prerequisite.

**Comment by BeefSteaker** [comment]
> I got the quest now, but it only unlocked after completing https://wowgaming.altervista.org/aowow/?quest=10640 , which according to the database shouldnt be a prerequisite.

this is blizzlike
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/a433c235-50b9-489b-869b-2e087dd0f5b8)
