### ISSUE TITLE
Inconsistency regarding Scourge Invasion bosses in dungeons

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#587]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Currently, Scarlet Monastery: Graveyard features a boss that was available on retail only during the Scourge Invasion in Classic.
[Scorn](https://classic.wowhead.com/npc=14693/scorn#drops;mode:normal) (see comments)
[Scorn](https://db.rising-gods.de/?npc=14693)

But, other bosses from the Scourge Invasion event are not available, e.g.
[Lady Falther'ess](https://classic.wowhead.com/npc=14686/lady-faltheress#comments) in Razorfen Downs
[Lady Falther'ess](https://db.rising-gods.de/?npc=14686)

List of bosses:
[https://wowwiki-archive.fandom.com/wiki/Scourge_Invasion#New_bosses](https://wowwiki-archive.fandom.com/wiki/Scourge_Invasion#New_bosses)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Additional invasion NPCs should only be available during scourge invasion event or wotlk event [Classic wowhead comments](https://classic.wowhead.com/npc=14693/scorn#drops;mode:normal)

##### STEPS TO REPRODUCE THE PROBLEM:

Enter Scarlet monastery graveyard and kill the final boss. Go back up and see Scorn spawned.
But, entering Razorfen Downs, proceed to the prisons. Lady Falther'ess is not available.

##### EXTRA NOTES:

Besides the classic scourge event leading to the original naxxramas, there was a second one in patch 3.0.2 introducing also lvl 70 quests and scourge invasion bosses
[https://wowwiki-archive.fandom.com/wiki/Scourge_Invasion#New_bosses](https://wowwiki-archive.fandom.com/wiki/Scourge_Invasion#Patch_changes)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Can confirm this NPC still spawns. This NPC along with the others should have been removed from the game following the 1.11 Scourge Invasion event.

**Comment by j-hdt** [comment]
> Can confirm this NPC still spawns. This NPC along with the others should have been removed from the game following the 1.11 Scourge Invasion event.

this is not correct - they return during 3.0.2 scourge event
