### ISSUE TITLE
[ World Boss - PTR ] - Doomwalker Chain Lightning Is Being Cast Too Frequently 

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#5880]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

[CL timers.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/08ef30cf-d835-4caf-a7cd-67d727dd9b25)
Currently on the PTR, chain lightning is being cast incredibly fast on players. 

### Expected Blizzlike Behaviour

Chain lightning, by classic TBC standards, had CL cast time much longer between each cast during the fight. 
https://youtu.be/5DqEJMLnNEU?t=77
At the 1:20 mark, CL is cast from the boss. The next possible cast from him wasn't done till 1:35. The boss will always face the target he is casting CL onto (as a way to determine if it was him casting, or getting hit by a shaman's CL). 

### Source

For now only the video had the best visual of it. There are some other classic kill videos, but it was hard to determine if it was boss or shaman casting the spell. 

### Steps to reproduce the problem

1. Log into 2 accts and go to boss
2. Have both start combat
3. Watch frequency of CL on non-tank target

### Extra Notes

This one actually had rather limiting data on how often the CL should be cast. I however think getting 4 casts on a player in under 2 seconds to be a little much. The boss is doable, but it doesn't seem correct mechanic wise. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a779cca9e3a3d673761d6bbe6d1c5d1f51c2f6f3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
similar matters apply for earthquake and Charge

# Earthquake
https://github.com/azerothcore/azerothcore-wotlk/blob/718b0000baec41da5f810db62e842b2c3cce227a/src/server/scripts/Outland/boss_doomwalker.cpp#L106
> context.Repeat(30s, 55s);

DBM -> Lower end 52 seconds

# Charge
https://github.com/azerothcore/azerothcore-wotlk/blob/718b0000baec41da5f810db62e842b2c3cce227a/src/server/scripts/Outland/boss_doomwalker.cpp#L111
> context.Repeat(25s, 40s);

DBM -> lower end 42 seconds

**Comment by NinesCC** [comment]
For reference, for correct scripting on the cooldowns and the amount of casts:

2008 TBC Footage
https://www.youtube.com/watch?v=J9BC1rd55jM

ChL=  Chain Lightning
0.11 ChL
0.26 ChL
0.37 ChL
0.53 Earthquake
1.08 ChL
1.26 ChL
1.42 ChL
1.51 Earthquake
2.04 ChL
2.18 ChL
2.32 ChL
2.45 ChL
2.56 Earthquake
3.18 Death

Doomwalker doesn't cast Chain Lightning while doing Earthquake

**Comment by elthehablo** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/65956938-2fd5-4ee9-878d-a1d51c24a691)

average of 17s for chain lightning which would mean 11 casts average in a fight of 3m18s. So this can be correct? Needs sniff

**Comment by elthehablo** [comment]
With the way TaskScheduler works. By default spells shouldn't overlap.

**Comment by NinesCC** [comment]
For some reason I was lagging a lot when I recorded this earlier on the PTR. Here https://youtu.be/FCOQ2jMEeuE you can see how often Doomwalker is casting the chain lightning, it seems to be casted every 3 to 4 seconds. The double and triple damage are probably due to my lag, so that can be ignored from the footage.

**Comment by elthehablo** [comment]
Aiaiaiai. It looks like we are dealing with 2 broken spells here. Because the timer does look correct. Needs spellscript to fix them probably.

**Comment by PaullyDM** [comment]
This is happening still, got chain lightning'd 3 times in a row and essentially got 1 shot within 1 second. It was brutal.

**Comment by BeefSteaker** [comment]
Tested and appears to have been fixed by above PR. Could somone confirm if this is still an issue
