### ISSUE TITLE
[Warrior] tier 5 set bonus Overpower buff disappears on ability use

### ISSUE THREAD

**Issue by Hogofogo1** [chromiecraft/chromiecraft#5888]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

![Screenshot 2023-07-07 143620](https://github.com/chromiecraft/chromiecraft/assets/97225391/b92bf389-377e-4e48-9b7d-eec1e5d2aa2a)
Buff 100AP should stay for 5 seconds
The buff disappears after using any ability

### Expected Blizzlike Behaviour

The buff should remain for 5 seconds

### Source

Set bonus description

### Steps to reproduce the problem

1. Equip Warbringer set
2. Cast Rend on target with Taste for Blood talent (Arms)
3. On proc use Overpower - now you got buff
4. Use any other skill - buff disappears immediately

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a779cca9e3a3d673761d6bbe6d1c5d1f51c2f6f3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by v-mstrs** [comment]
This is T5

**Comment by Hogofogo1** [comment]
Could you post the original?

**Comment by therelus** [comment]
I tested it right now and it still bug, when you get the bonus with 2 pieces of tier 5, before you use overpower and get the bonus for 5 seconds, if you do some attack more, the bonus dissapear instantly, not wait the 5 seconds that must be

**Comment by Maria-sequel** [comment]
https://github.com/chromiecraft/chromiecraft/issues/4446
