### ISSUE TITLE
[Herb] Out of place herb nodes in Silverpine Forest

### ISSUE THREAD

**Issue by sij1nk** [chromiecraft/chromiecraft#589]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Bruiseweed nodes 2944 and 3069 are located inside buildings.
![WoWScrnShot_050921_174843](https://user-images.githubusercontent.com/39011611/117579498-5c7a6a00-b0f3-11eb-957b-aa25318fdaf0.jpg)
![WoWScrnShot_050921_174807](https://user-images.githubusercontent.com/39011611/117579500-61d7b480-b0f3-11eb-9e0e-51d386f0abda.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The nodes should be moved outside of the buildings.

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.go o 3069` 
2. `.go o 2944`
3. `.gobject near` if they're not spawned and you want to be sure

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I'm not sure why but they come out differently for me :

![WoWScrnShot_051121_100852](https://user-images.githubusercontent.com/82579073/117773922-96f21d00-b241-11eb-8240-c83177b7bbc5.jpg)
![WoWScrnShot_051121_101022](https://user-images.githubusercontent.com/82579073/117773930-99547700-b241-11eb-9222-11857b8075dd.jpg)

and in the second place something strange happens with the detection of gobject near :

![WoWScrnShot_051121_101116](https://user-images.githubusercontent.com/82579073/117774011-b0936480-b241-11eb-98f8-e98ffab94286.jpg)
![WoWScrnShot_051121_101234](https://user-images.githubusercontent.com/82579073/117774018-b426eb80-b241-11eb-9b05-564ab117cd1e.jpg)
![WoWScrnShot_051121_101245](https://user-images.githubusercontent.com/82579073/117774025-b7ba7280-b241-11eb-9194-e386b25553d8.jpg)

it detects it in the place of the given coordinates but right next to it, where it really appears; no, not even the node mineral that exists there.

**Comment by anguaive** [comment]
The coordinates for nodes 2944 and 3069 in your chat log match with mine, so they're there, just not spawned in. As far as I know, nodes are arranged into pools and only a certain number of nodes in a pool can be spawned in at once. 

As for the mineral node not being detected... I think you're standing too far from it? `.gobject near` takes a `#distance` parameter which defaults to 10 units.

**Comment by FrancescoBorzi** [comment]
@anguaive @Eldarix what's the status of this? shall we link it to AC?

**Comment by anguaive** [comment]
Ah yeah sorry, will take care of it. Kinda forgot about this

**Comment by FrancescoBorzi** [comment]
@anguaive you forgot to link it :)

**Comment by anguaive** [comment]
@FrancescoBorzi Yup sorry. I hope this is correct

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi Yup sorry. I hope this is correct

it's ok for this one but typically we do it a bit differently, please read:

https://github.com/chromiecraft/chromiecraft#chromiecraftcom-bug-tracker
