### ISSUE TITLE
[Spell] Lightning Shield cast by NPCs wrong spell ID/behavior

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#5893]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

There are multiple issues with the way this spell behaves currently. Note, I don't have the capacity to test every single shaman mob, but this possibly affects dozens of NPCs, not only those i'll link as examples.

Firstly, many shaman-type of NPCs seem to use the same ability that player shamans have, a lightning shield that deals strong damage, has no cooldown, and procs on any kind of attack against them; in short, a powerful ability that normally belongs to players, not NPCs. 
Example: https://wowgaming.altervista.org/aowow/?npc=1544 

I looked into this and found that there are many many spell IDs listed under the wowhead page of each of these Npcs (example, https://www.wowhead.com/classic/npc=1544/vile-fin-minor-oracle#abilities;50), but you can distinctly tell **two** different types of Lightning Shield apart among them:

1) This one https://www.wowhead.com/classic/spell=325/lightning-shield is the player ability, a spell which procs on any type of attack, has no cooldown, and deals strong damage, this should be **PLAYER ONLY.**

2) This one https://www.wowhead.com/wotlk/spell=12550/lightning-shield is one I observed on other wotlk servers used by all NPC shamans, this ability is not a guaranteed proc (50%), only procs against melee/ranged attacks, deals considerably less damage, and has a cooldown which starts upon the last charge being consumed (10sec), which means that the mobs can't immediately recast it when it falls off.

Secondly, some shamans use a correct ID but the spell behaves wrong and procs off spells when it shouldn't.
Example: https://wowgaming.altervista.org/aowow/?npc=7439 these guys use a correct spell ID https://www.wowhead.com/wotlk/spell=13585/lightning-shield however on CC the effect procs on offensive spells too, not only on melee and ranged as it should.

Lastly, some shaman NPCs on CC have a wrong uptime on the shield, recasting it too frequently, or never at all.
Example: these vile fin guys spam it https://wowgaming.altervista.org/aowow/?npc=1544 usually the new shield pops up on them right after the last charge is consumed (even if the shaman is busy casting a lightning bolt, which is kinda weird)
Same thing with https://wowgaming.altervista.org/aowow/?npc=5236 they spam it too.
Meanwhile as https://wowgaming.altervista.org/aowow/?npc=4852 have a script to cast it just once on pull, which is also wrong, they never reapply the spell.

### Expected Blizzlike Behaviour

Shaman NPCs who currently use the player ability Lightning shield should be using those intended for mobs instead, a different spell ID with different characteristics. This shield deals less damage, has only 50% proc chance, only procs on melee/ranged attacks, and has a cooldown. 

Shamans who already use the correct ID of spell should be fixed so that the charges don't do damage/aren't consumed when damaging spells hit the shaman, only upon melee/ranged attacks.

Fixing the spell ID should also add a 10sec cooldown after the charges are fully consumed, which would sort out the uptime issue with the mobs who currently spam it, but the best would be if the script can be modified so that the shamans only cast it at certain intervals. This also includes mobs who currently only cast it once upon pull (should repeat sometimes)

### Source

As far as video evidence goes, most videos I found from retail the shamans didn't have a shield up at all which confirms they must have a timer to cast it, rather than each shaman always being shielded (as it currently is on CC)
https://www.youtube.com/watch?v=uhQd65OLNRw&t=27s this is a random leveling video which shows the player killing shamans without a single shield being cast or damaging them 
Notice these are the same NPCs I linked above, who spam their shields 24/7 on CC.

Here is a video where you can see a mage attacking shamans with spellcasts https://www.youtube.com/watch?v=0d5EZvtKOtU notice there is no incoming damage to the mage upon the frostbolt landing against a shaman with shield up (you can see the animation around shaman). This is because the shield does not proc on spell damage.

Lastly, here is a video that shows shamans randomly casting shield during combat https://www.youtube.com/watch?v=pQ7zy_ix1k0 they dont have it up before the pull (notice the lack of animation) and don't pop it immediately on the pull either, but randomly 10-15sec into the encounter. That is correct behavior for most.

### Steps to reproduce the problem

Check out the multiple shaman NPCs I linked above. 
Notice the tooltip of the spell when you mouseover the shield buff they have is different for i.eg. the Vile fins, or the Winterfall shamans. 
Cast spells such as frostbolt against them, and notice it consumes charges and damages you. (shouldn't)
Notice that the Vile Fins and Gordunni recast their shield as soon as you consume the last charge, while the Stonevault guys never recast it unless you reset the NPC.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a779cca9e3a3d673761d6bbe6d1c5d1f51c2f6f3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
I'll try to get some fresh data from classic wotlk

**Comment by FrancescoBorzi** [comment]
> I'll try to get some fresh data from classic wotlk

closing as this will never happen
