### ISSUE TITLE
Patroling Deathguards (mounted) chain aggro range

### ISSUE THREAD

**Issue by Riphook** [chromiecraft/chromiecraft#59]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

**|======MODERATION EDIT Strart======|**
NPC: [Deathguard Abraham](https://wotlkdb.com/?npc=1735)
**|======MODERATION EDIT End======|**
Huge aggro range

##### EXPECTED BLIZZLIKE BEHAVIOUR:

not killing off their path so far away

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find a patroling Deathguard in Tirisfal Glades
2. Watch him until he fights something
3. Watch how far he will stray from his point of origin if he chain kills

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Riphook 
Verified. NPC [Deathguard Abraham](https://wotlkdb.com/?npc=1735)
Quest Evidence, Video: [Deathguard Abraham](https://youtu.be/8gXTm78Q4Gw)

 has too much aggro range.

And in the future try to report with Links, as I showed you in the edit I did in your post, pls.
Having the **IDs** of the **NPC/ITEM/QUEST/ETC** at hand, you facilitate the work in its execution.

And anyway, your **SMALL DESCRIPTION** was too SMAAAAAL! xD

**Comment by illfated** [comment]
Thanks for the funny video evidence. That is a really overzealous Deathguard right there. I bet you could "kite" him to clean up most of Tirisfal Glades if you wanted to. 😆 🤣

**Comment by necropola** [comment]
These also have a **huge** aggro range and run miles wild life not even close to the roads: [Ironforge Mountaineer](https://wotlkdb.com/?npc=727)

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Patroling Deathguards chain aggro range](https://youtu.be/GAgINSUQdac)

**Comment by necropola** [comment]
[Razor Hill Grunts](https://wotlkdb.com/?npc=5953) also have anger issues. They really hate Scorpids it seems.

**Comment by necropola** [comment]
There is definitely something wrong with aggro range at least at lower levels. I just tested this on my level 14 shaman against level 7 Harpies. They start to attack when they face me from around 15..20 yd distance. This is a pretty precise measurment since Flame Shock has a 25 yd range, so I know when I'm 25 yd away.

**Comment by necropola** [comment]
> ## Fixed!
> **Video Test:** [Patroling Deathguards chain aggro range](https://youtu.be/GAgINSUQdac)
> I Also Fixed [Ironforge Mountaineer](https://wotlkdb.com/?npc=727) @necropola

@Stifler82: Those [Ironforge Mountaineers](https://wotlkdb.com/?npc=727) are now completely passive, i. e. a hostile beast can now run through them while they are "patrolling" the road. I wouldn't consider this a fix.

**Comment by Stifler82** [comment]
> 
> @Stifler82: Those [Ironforge Mountaineers](https://wotlkdb.com/?npc=727) are now completely passive, i. e. a hostile beast can now run through them while they are "patrolling" the road. I wouldn't consider this a fix.

@necropola 
it is normal that **(you)** do not consider it **a "Fix"**.
it's like if a mechanic goes to a pastry chef and tells him that those pastries don't consider them like wrenches.

You must know, my dear **know-it-all** friend, that **"The Guards"** (in fact) **are Guards!**, the guards **(both those inside the city and those patrolling the city limits)**, are not intended to kill the local fauna, or **to help the other Players farm exp.**

**Instead**, the Guards **have the one and only purpose** of **"Protecting" the (citizens) from raids by opposing factions**, so yes..
if the guards are in front of a mob, they don't attack it, but **go there with a horde character**, and then let me know if they are still **"passive"**.

**Comment by Stifler82** [comment]
@necropola 

https://user-images.githubusercontent.com/1884642/109384930-0fef0300-78e8-11eb-9bb9-311a9beb3fa5.mp4

**Comment by necropola** [comment]
https://wow.gamepedia.com/Guard#Combat
>Guards also at times attack hostile creatures that come nearby. This can sometimes be used to the player's advantage, such as running towards guards when a mob is about to kill the player.
