### ISSUE TITLE
Tank Permanent MS effect (-50% healing) on HCs.

### ISSUE THREAD

**Issue by Aliwings108** [chromiecraft/chromiecraft#5901]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

So this is the second time this happens, in two days. Tank receiving 50% less healing in HCs. First it was in MT HC yesterday (Jule 06 2023) and today again inside Arcatraz (July 07 2023). I was healing with my dpriest when I noticed the reduced healing and then I swapped to shaman (resto) and tried again just to confirm. When it happened the first time it seemingly fixed it self cause I've been running HCs fine until now. It doesn't seem to be xfaction because horde dps are getting regular heals, is just tanks.

### Expected Blizzlike Behaviour

I know there is a heal reduction, I don't even know if its 10%, 20% of 30% I keep getting different answers. But It definitively shouldn't be 50%.

### Source

I have no idea what source is... Healing are being cut in half? HCs? I have screenshots to show the problem we were having tho.

### Steps to reproduce the problem

Healing and absorbs (any PW:S, HoTs, direct heals)
Only when casted on tanks

### Extra Notes

Hopefully this will help (screenshots)
https://imgur.com/a/lXYzu4C
Here are more screenshots
https://imgur.com/a/ca98XxA

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a779cca9e3a3d673761d6bbe6d1c5d1f51c2f6f3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
CC: @55Honey

**Comment by 55Honey** [comment]
@Aliwings108 This is an individual issue and does affect only singular players. Feel free to ask in our discords #support channel or open a ticket on our discord in case of personal problems which do not happen to everyone.
To solve this problem in particular, please type `.fixnoheals` in your chat window in the game.

**Comment by balleny** [comment]
it is definitely not an individual issue, multiple healers are affected by this in dungeons
having players from different guilds report on the issue already

**Comment by balleny** [comment]
may be related
https://github.com/chromiecraft/chromiecraft/issues/5902

**Comment by balleny** [comment]
more players reporting this issue.
I would recommend to reopen it and consider it a regular issue

> This is an individual issue and does affect only singular players. Feel free to ask in our discords #support channel or open a ticket on our discord in case of personal problems which do not happen to everyone.
