### ISSUE TITLE
Ethereum Prisons in Netherstorm dont Drop Cloak or Rings of resistance

### ISSUE THREAD

**Issue by rutter28** [chromiecraft/chromiecraft#5909]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

After killing more then 100 hostile creatures from Netherstorm Ethereum Prisons in the PTR, i got:
![297ca81e594b4ada836e5972a5ad6174](https://github.com/chromiecraft/chromiecraft/assets/87255892/a74c5c59-b7ee-4bb1-aa0d-31a5d4a55ea4)
gray items and gear, a few greens, and some of the specific blues that drop from the hostile ads that can be summoned by opening the prisons. Not a single Cloak or Ring of resistance gear, what seems strange when you consider that all the ads SHARE a loot table of cloaks and rings of resistance. 

### Expected Blizzlike Behaviour

Make them drop¡ am pretty sure isnt me the one thats unlucky, i been doing it not just in the PTR but also in the live server and never got to see a cloak or ring before.

### Source

Pretty sure theres something happening that make the drop table have this wacky outcome. i remember that in classic bracket , some items from Kazzak didnt drop bcs they got blocked , this happend in the begining of the realese when the guild Synergy farm him every time it spawned, was reported by one of their guild memebers and later fixed. Pls fix this problem since its the only way to get Varius Resistance cloaks and rings¡

### Steps to reproduce the problem

1. make a macro that one shots and another that respawn a target.
2. open a ethereum prison until u find an hostile target.
3. kill him and respawn him constantly till 100 times(just to be sure).
4. expect no Cloaks or rings.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a779cca9e3a3d673761d6bbe6d1c5d1f51c2f6f3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
Definitely something weird going on. Lemme show:

![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/21726fa2-2fd7-4d86-ae39-4b8cb074f7fe)
only entry that has it as pure drops

![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/354c2fdc-95b2-4946-b851-7d8596244dea)
a reference entry with all of them you mentioned

![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/fdb20a39-07f4-4b7a-a833-081378803283)
these are all of them fyi

![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/cbce9a7d-8f22-40fe-b7c5-578cf849de71)
querying this reference in `creature_loot_template` gives no entries... unfortunately...
