### ISSUE TITLE
Possible core issue regarding mobs a

### ISSUE THREAD

**Issue by S3rafym** [chromiecraft/chromiecraft#5913]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Went to Manatombs, Found some mobs called Ethereum Spellbinders. One of the spells they cast is arcane missiles. Noticed that if they start casting and you LoS them, they keep channeling but no further missiles go towards you, and you don't take any further damage. Might apply to all mobs casting channeling spells at the player, that if you los them they keep channeling but the spell no longer works.

### Expected Blizzlike Behaviour

Spells like arcane missiles cast by mobs should continue hitting the player even if he goes LoS. Just like regular arcane missiles from mages. 

### Source

Not sure where i would get a source for this, but it's obvious, right? 

### Steps to reproduce the problem

1. Pull a mob that casts a channeling spells, like an ethereum spellbinder.
2. Wait for him to start channeling the spell at the player
3. LoS the mob
4. Watch him continue channeling but the spell no longer working

### AC rev. hash/commit

?

### Operating system

Win10

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
that would indeed be a critical issue if it can be confirmed

**Comment by Samsequel** [comment]
I think you mean Ethereal Spellfilcher

**Comment by Samsequel** [comment]
actually no, i have no clue which mob you mean now

**Comment by balleny** [comment]
i did partially test it in between and couldnt confirm the issue yet

**Comment by alecsci** [comment]
Hi, I tested fc735e37a2166bbb39b272abd6950a5ae70ae761 and I cannot reproduce it.

I cross-checked all NPCs prefixed with Ethereal from Mana Tombs wowhead against ac (normal/hc), and there is no NPC that has the channeling arcane spell .
