### ISSUE TITLE
[Alchemy] Can't unlearn mastery

### ISSUE THREAD

**Issue by Hogofogo1** [chromiecraft/chromiecraft#5926]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

When I acquired Potion Mastery I can't unlearn it at the respective npc - Lauranna Thar'well (Potion mastery)
![WoWScrnShot_071323_122735](https://github.com/chromiecraft/chromiecraft/assets/97225391/d889de2c-829f-409c-8969-154fb5592e06)

### Expected Blizzlike Behaviour

After learning an Alchemy mastery you should be able to unlearn it at the npc you gained the mastery.
In this case Lauranna Thar'well (Potion mastery)

### Source

Official retail functionality 
Was working on CC few weeks back

### Steps to reproduce the problem

1. Become Potion Master
2. Visit Lauranna Thar'well at Cenarion Refuge
3. There should be an option to unlearn Potion Master

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a8964a6ed1dc9295a85a816e5d11740e90a1fb79

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
hm interesting - about 10 days ago, the gossip menu was shown just right and unlearning worked (although requiring like multiple clicks)

**Comment by Hogofogo1** [comment]
Even multiple dialog pops don't give the option to unlearn.
The npc doesn't recognize I have the potion mastery for some reason.

**Comment by Hogofogo1** [comment]
Identified the issue as being locked till skill 350
So get your mastery at 325, level up to 350 and now you can unlearn (y)

**Comment by Samsequel** [comment]
Well, technically you could only (Solo) get the potion mastery if you are skill lv 360 :3, but I can see the issue...

**Comment by Hogofogo1** [comment]
You can obtain the mastery at skill 325 and lvl 68 according to this site:
https://www.wow-professions.com/tbc/alchemy-specializations-tbc-classic

So is the case on our server

**Comment by Samsequel** [comment]
yea but I mean you cant make the potions required for it yourself before 360

**Comment by Hogofogo1** [comment]
True 
Guess Blizz wasn't expecting people to buy the potions and relearn mastery without achieving required skill necessary.
