### ISSUE TITLE
Problem with the camera pitch for 'Gray Elekk', randomly and only sometimes.

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#593]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS 
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When activating the native draenei mount there are times when the pitch of the camera does not adjust as it should, leaving it at the center and not a little higher as it normally does. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should just always work as expected.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make a Draenei (Don't know if with other races the bug exists)
2. Go up to the level needed to have a mount.
3. Buy a gray elekk (Don't know if with other colors occurs)
4. Turn the mount on and off as many times as necessary to reproduce the bug.

##### EXTRA NOTES:
--

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Not sure, happened to me only on Chromie.

**Comment by FrancescoBorzi** [comment]
Probably a client bug. Nothing we can do :(

**Comment by Eldarix** [comment]
Luckily it happens very rarely at least .

**Comment by Shineslippers** [comment]
I will re-open this one because of https://github.com/azerothcore/azerothcore-wotlk/issues/2207#issuecomment-907773747

**Comment by Mitradis** [comment]
> Probably a client bug. Nothing we can do :(
stop responding like this all the time. It's not funny anymore.

**Comment by Mitradis** [comment]
> Probably a client bug. Nothing we can do :(
stop responding like this all the time. It's not funny anymore.
