### ISSUE TITLE
[Progression] T4 Bosses drop too much loot

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5930]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

For proper progression the amount of loot dropping from the T4 25 player bosses is too high

currently dropping:

Maulgar: 3 tokens, 1 or 2 items (dont remember)
Gruul: 3 tokens, 2 items
Magtheridon: 3 tokens, 2 items, head, bag (gems), satchel

### Expected Blizzlike Behaviour

Maulgar: 1 token, 1 item
Gruul: 1 token, 2 items
Magtheridon: (vanilla) 1 token, 2 items, no bag, no head, no gem bag
Magtheridon: (classic) 1 token, 2 items, 1 bag, 1 head, 1 gem bag

### Source

https://youtu.be/QpgdAHJANcA?t=457
https://youtu.be/PVL-m0CvfI0?t=605
https://youtu.be/qYJbPHZ9CIg?t=455
https://youtu.be/2bXzGm_Dvho?t=252

### Steps to reproduce the problem

.

### Extra Notes

in vanilla, one token each was less of an issue as you could directly also go into t5 content.
in wow classic, the amount of tokens was increased with phase 2
Phase 1: June 1st - September 14th.
Phase 2: September 14th - January 27th.
PTR Update August 4, 2021
> High King Maulgar, Gruul the Dragonkiller, and Magtheridon will drop two Tier 4 tokens each when Serpentshrine Cavern and The Eye are released.

my 2 cents: this could have been a great incentive for groups to go for a mythic / tuned version instead.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a8964a6ed1dc9295a85a816e5d11740e90a1fb79

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BaoZaiz** [comment]
If you gonna reduce it, please keep it to 2 tokens instead of 1 ... 
25 man raids = 2 tokens
10 man raids = 1 token
Sounds better
Thanks

**Comment by Nyeriah** [comment]
Thanks for the report however we don’t intend to do progression changes after content has been released. Specially since it’s been out for a month now

**Comment by Nyeriah** [comment]
Issue has been addressed however it won't affect the Chromiecraft server as we don't intend to make progression changes after content has been released.
