### ISSUE TITLE
"Recipe: Insane Strength Potion" seems to have strangely limited drop sources

### ISSUE THREAD

**Issue by quigiboo** [chromiecraft/chromiecraft#5935]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Currently the recipe seems to only drop from a handful of mobs. https://wowgaming.altervista.org/aowow/?item=22903#dropped-by

I'm told this database is 7 months old, but I've never seen this recipe or anyone with it in game in my time playing.

### Expected Blizzlike Behaviour

According to wowhead, the recipe should drop from most high level outland mobs, like a world drop. you can see in both the dropped by section and the comments for anecdotes on where people say they got it
https://www.wowhead.com/wotlk/item=22903/recipe-insane-strength-potion#dropped-by;0+2-10-9+1

### Source

https://wowgaming.altervista.org/aowow/?item=22903#dropped-by
https://www.wowhead.com/wotlk/item=22903/recipe-insane-strength-potion#dropped-by;0+2-10-9+1

### Steps to reproduce the problem

Difficult to reproduce as you would have to kill thousands of specific mobs to verify.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a8964a6ed1dc9295a85a816e5d11740e90a1fb79

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UndoUreche** [comment]
The recipe is available. Though the selection of mobs it can drop from is very low, it can drop.
![image](https://github.com/chromiecraft/chromiecraft/assets/50205200/f4ef408d-f689-4700-9ab6-b158cef9dad4)
This was my very fortunate moment, after a significant period of time spent grinding it.

**Comment by elthehablo** [comment]
With these really low droprates, using WoWhead as a source alone does not really say much, even if it's only to try to get proof that it does drop, at whatever low rate, from a specific mob. That being said, the drops are likely not correct. Usually what we do is we take a look at other dbs from other projects and compare

**Comment by quigiboo** [comment]
Sorry if i was unclear, but the wowhead source was intended to prove that it's closer to a world drop than what it currently is on chromie.
Sam was kind enough to look into chromie's DB and confirm that the data on aowow is correct: ![image](https://github.com/chromiecraft/chromiecraft/assets/114075548/aaf7a638-4bb9-47d3-b312-c19f3b26bb34)
I have no idea how to look at other project's DBs, but the one currently on chromie is definitely incorrect, I asked on another well respected project's discord where the drop was supposed to be from, they told me a world drop, although I think what some guy told me on a discord is less reputable than wowhead.
![image](https://github.com/chromiecraft/chromiecraft/assets/114075548/a5208ac4-be62-4e56-8351-1d01e50eeba3)
If it were up to me I'd just make it drop from the same places as a similar recipe like haste potion.

**Comment by balleny** [comment]
easiest would likely be to add it to the same mobs that drop haste and heroic potion
