### ISSUE TITLE
[Dungeon - Slave Pens  Heroic Rokmar is not scripted appropriately]

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5943]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Rokmar the Crackler does not use his abilities correctly -> [Ensnaring Moss] is cast only on the tank lol.

Water Spit is supposed to hit EVERYONE in 45 yards as the Spell actually says.

### Expected Blizzlike Behaviour

Rokmar Should cast Ensraning moss on any member, not just the tank.

Water Spit is cast and hits everyone

### Source

https://www.wowhead.com/wotlk/npc=17991/rokmar-the-crackler#abilities;mode:normal

https://www.youtube.com/watch?v=RDq6E9uHbaE  --> 24 minutes (see HOW THE WATER SPITS HITS FOR 1.5k EVERYONE 

AT minute 24:51 U CAN SEE THE SHAMAN GETTING ENSNARING MOSS...

### Steps to reproduce the problem

.tel to Slave pens
.tel to 17991 Rokmar the Crackler
See if water spit is aoe for everyoe and if damage is correct
see if ensaring moss is only casted on the tank lol

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a8964a6ed1dc9295a85a816e5d11740e90a1fb79

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
caanot confirm. both abilities work fine in hc

**Comment by elthehablo** [comment]
Water spit does hit everyone https://wowgaming.altervista.org/aowow/?spell=35008

![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/8e4a02dc-bb88-400e-a002-831a31d707d1)
ensnaring moss is cast on a random target. you just got unlucky
