### ISSUE TITLE
Can hand in "The Path of the conqueror" quest repetively.

### ISSUE THREAD

**Issue by Macuhroni** [chromiecraft/chromiecraft#5945]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

At the caverns of Time, spoke with Anachronos handed in "The Path of the conqueror" quest to get [Signet Ring of the Bronze Dragonflight], which give the ring + 14s 25c + 250 rep towards "Brood of Nozdormu". but rather than the NPC not offering the quest again, i was able to hand the quest in several times.

Once I exited the window and waited 5 minuets it doesn't seem to be replicable. 

### Expected Blizzlike Behaviour

At the caverns of Time, spoke with Anachronos handed in "The Path of the conqueror" quest to get [Signet Ring of the Bronze Dragonflight], which give the ring + 14s 25c + 250 rep towards "Brood of Nozdormu".

Expected behaviour is that you can only hand in the quest once.
https://www.wowhead.com/classic/quest=8752/the-path-of-the-conqueror#comments

Once I exited the window and waited 5 minuets it doesn't seem to be replicable. 

### Source

Don't have any screenshots or proof other than looking at my character incident happened around 16/07/2023 between 8pm & 9pm.

### Steps to reproduce the problem

not sure if its reproducible but it was while speaking to "Anachronos" at the caverns of time.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a8964a6ed1dc9295a85a816e5d11740e90a1fb79

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Do keep in mind that you can upgrade the rewarded ring based on your Brood of Nozdormu reputation level. For example, getting the ring at neutral or whatever it is, then trading it for better and better rings at each reputation level up to exalted. Are you sure that isn't what happened here?

**Comment by BeefSteaker** [comment]
unable to reproduce on live & local.
i think bench is correct, there are a series of quests with the same name that upgrade the ring. if you hadnt obtained it previously and had exalted rep, you get the quest 5 times
