### ISSUE TITLE
"Survey the Land" bugged.

### ISSUE THREAD

**Issue by Dotieee** [chromiecraft/chromiecraft#5947]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Quest "Survey the Land" https://wowgaming.altervista.org/aowow/?quest=9991 is unable to be completed in its current state, so the whole quest chain is inaccessible. Even while unmounted and standing still next to the questgiver, you just stand still and do not auto mount the dragon.

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=v2_E7WyjJ14

Quest "Survey the Land" https://wowgaming.altervista.org/aowow/?quest=9991 should automatically mount you on the unit https://wowgaming.altervista.org/aowow/?npc=18418 for the quest to complete. 

### Source

https://www.wowhead.com/tbc/quest=9991/survey-the-land#comments

### Steps to reproduce the problem

Go to NPC altruis-the-sufferer (in nagrand)
While dismounted and standing still, accept the quest "Survey the Land"

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a8964a6ed1dc9295a85a816e5d11740e90a1fb79

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by InfernalDark** [comment]
Yep, I'm stuck in this quest too.

**Comment by BeefSteaker** [comment]
Quest works on my end. you have to complete the dialogue with altruis
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/3da42f71-30b7-46db-9620-03302f0baffb)

**Comment by Ocwil** [comment]
Ummhh am i missing something or does this quest have a prerequisite? 
I cant seem to start this quest im lvl 69 the requirement should be 66.
The NPC does have a gossip action that initiate's a flight over the Forge camps like the quest is supposed to do but there is no quest?

EDIT: So the quest "He Called himself Altruis" is the requirement but this is not visible on the page DB page of the quest talked about in this issue
EDIT2: after taking the quest use the gossip option to complete it. What is weird though the gossip option was already available before the quest.
