### ISSUE TITLE
Cannot equip weapon

### ISSUE THREAD

**Issue by rramk01** [chromiecraft/chromiecraft#5952]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Cannot equip a 
![Untitled](https://github.com/chromiecraft/chromiecraft/assets/123597966/83fd8afb-004e-4077-8959-f205d2334a86)
weapon and get a message saying "you cannot equip more than one of those"

### Expected Blizzlike Behaviour

Should be able to equip weapon. I have done this before. 
I tried socketing a gem in the weapon that I already had in there and got an error message that said "you cannot equip more than one of those". I started getting this same message when trying to equip said weapon. 

### Source

n/a

### Steps to reproduce the problem

1. Allow me to equip the weapon (see screenshot)
![Untitled](https://github.com/chromiecraft/chromiecraft/assets/123597966/e895cd8c-8329-40e4-94f8-c3732ce513b8)

### Extra Notes

![Untitled](https://github.com/chromiecraft/chromiecraft/assets/123597966/2d11a552-9429-4928-a4a7-cb4d4edc441e)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30197f40d687eae97a07d6730b6933c63f1a3983

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
> you are probably using a unique gem in the weapon that you also have equipped somewhere on your armor
> you cant use more than one of those unique gems at a time

This is the problem. Closing the issue
