### ISSUE TITLE
[(Heroic) Mana Tombs] Ethereal Darkcasters are not pickpocketable

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#5959]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Ethereal Darkcaster](https://wowgaming.altervista.org/aowow/?npc=18331) has no pockets to pick. Note that on Aowow there is a tab for pickpocketing - however, comparing these to Wowhead's wotlk or tbc loot table, the rates / loot is wrong.

![image](https://github.com/chromiecraft/chromiecraft/assets/107246426/5dc82713-89c0-462b-8e94-4a2be6d4751a)

### Expected Blizzlike Behaviour

[Ethereal Darkcaster](https://www.wowhead.com/wotlk/npc=18331/ethereal-darkcaster#pickpocketing) (wowhead/wotlk link), should have better rates for pickpocketing as well as a very small chance for Noble Topaz and Star of Elune. 

### Source

https://www.wowhead.com/wotlk/npc=18331/ethereal-darkcaster#pickpocketing
https://www.wowhead.com/wotlk/npc=18331/ethereal-darkcaster

### Steps to reproduce the problem

1. Go to Mana Tombs (heroic) as a rogue
2. Find Ethereal Darkcasters
3. Try to pickpocket them

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30197f40d687eae97a07d6730b6933c63f1a3983

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Samsequel** [comment]
confirmed, no loot pickpocket loot table in heroic mode, can't find good source for loot except wowhead...
