### ISSUE TITLE
[Dungeon Shattered Halls - Champion randomly drops aggro and has no working abilities]

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5962]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

1. Drops TPS (threat) randomly, complete wipeout of TPS
2. Does not use Shield Block

### Expected Blizzlike Behaviour

1. Unheard of reset of aggro - he does not do that
2. This is a Prot Warrior style NPC and uses Shield block

### Source

https://www.wowhead.com/wotlk/npc=17671/shattered-hand-champion#abilities;mode:normal

https://www.youtube.com/watch?v=C4uGJ6QWNpk ---> 51:20 Min he fights Champs - as yo see they do not AGGRO RESET...

### Steps to reproduce the problem

1. Tel to Shattered Halls
2. Tel to NPC ID 17671
3. Check for aggro reset (needs a second person)
4. Check he does not use Shield block at all (fights are 30 seconds so cant confirm if longer, but on TBC classic the timer was definitely way shorter than that)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30197f40d687eae97a07d6730b6933c63f1a3983

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Samsequel** [comment]
https://youtu.be/C4uGJ6QWNpk?t=3728

it's tied to concussion blow, however, i see no threat drop here too

**Comment by Samsequel** [comment]
They are casting shield block though
