### ISSUE TITLE
Kul Tiras Marine Spawning Underground

### ISSUE THREAD

**Issue by Ragundah** [chromiecraft/chromiecraft#597]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Youtube Video - Too Large To Upload To Github](https://www.youtube.com/watch?v=jxeGD2jqiEw)
[Second Video - Shows clipping through wall](https://www.youtube.com/watch?v=7xLSmA6vMAg)

As can be seen in the video provided the Kul Tiran Marine at the entrance of the ruined keep spawns underground.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should spawn above ground.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to coordinates listed (see above character health bar)
2. Notice mob Kul Tiran Marine wondering underground.
3. If not there kill and await respawn.

##### EXTRA NOTES:

Out of 3 spawns I've encountered 2 were underground and 1 was both underground and aboveground clipping through the walls.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Ragundah** [comment]
@Azcobu I returned this morning and found the NPC in the wall again.
I ran .npc info and all the relevant information can be found in the following new clip:
[Third Video - Including Npc Info](https://www.youtube.com/watch?v=9x_uP0RU6Bs)

**Comment by Si1ker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5778#issuecomment-837632280
