### ISSUE TITLE
[Heroic Shadow Labyrinth] Murmur way too bugged

### ISSUE THREAD

**Issue by unitscan** [chromiecraft/chromiecraft#5973]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

1. Murmur's Touch is cast while Sonic Boom is channeling
2. Sonic Boom pierces through Divine Shield and Cloak of Shadows
3. Sometimes, Murmur doesn't restore his health after a wipe

### Expected Blizzlike Behaviour

1. While Sonic Boom is channeling, no other spells should be casted
2. Divine Shield and Cloak of Shadows should prevent damage from Sonic Boom
3. Murmur should restore his health after a wipe

### Source

murmur WOW TBC Classic: https://youtu.be/dov_V-Ubo1A

### Steps to reproduce the problem

1. Enter Shadow Labyrinth
2. Engange Murmur

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a5e84f610a0e5fb83c58256676f98cc1b387e3d0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
related
https://github.com/chromiecraft/chromiecraft/issues/5856

**Comment by balleny** [comment]
also pulling in someone and directly casting sonic boom, without any chance to escape in time

**Comment by Manuel91CC** [comment]
1. Not confirmed - No other spell are casted.
2. Not sure -  There are some bosses abilities that can bypass player's immunity spells like Cloak of Shadow or Divine Shield. I don't know if this is the case but i can't find any reliable source. So i cannot confirm this as an issue.
3. Not Confirmed - Murmur do restore his health after a wipe.

Thank you for your report.
