### ISSUE TITLE
Naberius Glitch in Netherstorm

### ISSUE THREAD

**Issue by VaskT86** [chromiecraft/chromiecraft#5981]
In Netherstorm (62.6, 78.9) There is an elite named Naberius. I've found 2 bugs with this elite.
1) Naberius will charm and mind control a player if in a party according to Wowhead, but even fighting Naberius solo, he is charming me, which ends combat and his health regens to max, as he is no longer in combat.
2) Once Naberius has charmed me and ended combat, it seems an invisible wall appears in the doorway to the chapel Naberius is in. There is no escape from this chapel unless you Hearthstone or die and res outside of the chapel. 

In once attempt to mess around with this glitch, other players came near the chapel and as Naberius charmed me, I was able to exit the chapel and begin attacking the random players nearby while charmed, this helped me escape from the chapel on one attempt of getting past the invisible wall.

**Comment by elthehablo** [comment]
known issue (https://github.com/chromiecraft/chromiecraft/issues/5015) but you're likely correct on the ability not being able to be cast when you solo engage him

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️

I only triaged the first issue you mentioned as, like elthehablo said, the second has already been reported.
