### ISSUE TITLE
Two parts bonus from shamans enhancement tier 4

### ISSUE THREAD

**Issue by alexisgohan2** [chromiecraft/chromiecraft#5982]
### What client do you play on?

esMX

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

T4 bonus (+12 strength) https://www.wowhead.com/wotlk/spell=37223/improved-strength-of-earth doesn´t multiply by the talent Enhancing Totems https://www.wowhead.com/wotlk/spell=52456/enhancing-totems#modifies

### Expected Blizzlike Behaviour

(+12 strength) bonus should be  13,8 for the mentined talent 

### Source

https://www.wowhead.com/wotlk/item-set=633/cyclone-harness
https://www.wowhead.com/wotlk/spell=37223/improved-strength-of-earth
https://www.wowhead.com/wotlk/spell=52456/enhancing-totems#modifies

### Steps to reproduce the problem

1. equip two parts from the set Cyclone Harness (enhancement shaman)
2. Get enhancing totems talent with 3 points
3. summon Strength of Earth totem 
4. Look up how Strenght only incrase by 12 on your stats

### Extra Notes

I am Magnarar from Chromiecraft :D 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/642bd1936b341a098d7c8d5f3089988409e4d6bb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
Hi @alexisgohan2, 
Thanks for your report !
I did some testing on a shamy lvl 70 for this version:

1. STR totem (Rank 8) gives 155 STR (flat, with no talents)
2. with T4 set 2 pieces bonus (+12 **flat** STR, if it's FLAT it shouldn't be affected by talents) = 167 (based on your source) 
3. with talent active = 167+15/100*167 = 192.05 (in game it's rounded 190)

If you still think it's an issue or my calculation is wrong, please let me know in the comment section, and we will reopen it but you have to provide more source context so we can look further.
