### ISSUE TITLE
Hand of sacrifice is causing spell pushback

### ISSUE THREAD

**Issue by quigiboo** [chromiecraft/chromiecraft#5985]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Currently if you cast hand of sacrifice on a player and they take damage, the damage transferred to the paladin causes spell pushback.

https://youtu.be/B1c9bVUYQwE

### Expected Blizzlike Behaviour

Does not cause pushback. as can be seen in this clip from wotlk classic.
https://youtu.be/6lrSXOYWpZo?t=1393

EDIT- Bench was kind enough to test this on classic, he used exorcism which is unaffected by any pushback prevention talents. https://www.youtube.com/watch?v=1i2NLW2UyqQ

### Source

https://youtu.be/B1c9bVUYQwE
https://youtu.be/6lrSXOYWpZo?t=1393
https://github.com/SunstriderEmu/BugTracker/issues/1737
https://www.youtube.com/watch?v=1i2NLW2UyqQ -new

### Steps to reproduce the problem

paladin casts hand of sacrifice on a player
that player takes damage, transferring some to the paladin
the paladin casts a spell such as holy light and will receive spell push back.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/642bd1936b341a098d7c8d5f3089988409e4d6bb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
i think the report is correct/true.
but, the second source of a pve holy pala from NOTA is not sufficient prove. a holy pala will suffer no pushback given 70% pusback prevention from talents and 30% from the aura of concentration.

**Comment by quigiboo** [comment]
oh cool man, if you can find a better one feel free to post it.

**Comment by quigiboo** [comment]
big thanks to bench for testing this on classic for me. - https://www.youtube.com/watch?v=1i2NLW2UyqQ

**Comment by Salehyn** [comment]
Confirmed, same problem happens with spell ID=64205 (divine sacrifice)
Could be a generic issue with damage transfers, none of these should cause any spell pushback, as they aren't direct damage. Spell pushback should only ever occur from taking direct damage.
