### ISSUE TITLE
[Paladin, Spell, NPC?]  Avenger's shield ignoring NPC's pets

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5988]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

When using Avenger's Shield, the shield will never bounce to an NPC's pet.
If you target the pet, it will bounce normally from them to other NPCs nearby.

Confirmed using Wyrmcult mobs in Blade's Edge.

### Expected Blizzlike Behaviour

Avenger's shield should include NPC's pets if they are in range.

### Source

Issue originally noticed on these NPCs.
https://www.wowhead.com/wotlk/npc=21809/wyrmcult-poacher
https://www.wowhead.com/wotlk/npc=21811/wyrmcult-broodling
https://www.wowhead.com/wotlk/npc=21810/wyrmcult-hewer

### Steps to reproduce the problem

1.  As a paladin with Avenger's shield, teleport to Ruuan Weald in Blade's Edge - near 64:36
2.  Target a wyrmcult poacher (21809) with Avenger's shield, observe the shield will not bounce to any adjacent broodling (21811)
3. Target a broodling directly, observe the shield bouncing correctly as expected to any nearby hostile NPC.

NOTE:  If a Wyrmult Hewer (21810) is close enough, you can observe the same - target the hewer and the shield ignores the broodling, but the shield will bounce as expected from the broodling to the hewer.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/642bd1936b341a098d7c8d5f3089988409e4d6bb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
Confirmed, the ability jumps from pet to owner but not from owner to pet, same behavior happens on different type of NPCs with pets too.

**Comment by Vyperhand** [comment]
> Thanks for the report! ❤️

Minor clarification - it will never go to the pet/summon, not only from the master/summoner, but from **any** nearby NPC.  The pet/summon is ignored unless targeted first.

**Comment by heyitsbench** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/28696e4ff83dcc30093f991b191361e48ff5027e
