### ISSUE TITLE
[Quest, Party, NPC]  Whelps of the Wyrmcult does not work properly in party.

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5989]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

When completing this quest in party, a number of strange behaviors occur regarding the nets.

When any member of the party uses their net on a wyrmling, the credit for the catch as well as spawning the item into inventory seems to happen at random, not crediting the character that used the net as expected.

It did not seem to be based on proximity, nor aggro either.  With Character A having aggro and standing near the whelp and character B using the net, it was about 50/50 which character would be given credit for the catch.

This used up enough charges from some party members' nets that they had to drop and re-take the quest because their net was out of charges.

### Expected Blizzlike Behaviour

The character that uses the net should be credited with the catch and spawn the in-inventory item.

### Source

https://www.wowhead.com/wotlk/quest=10747/whelps-of-the-wyrmcult
https://www.wowhead.com/wotlk/item=31129/blackwhelp-net
https://www.wowhead.com/wotlk/npc=21387/wyrmcult-blackwhelp

### Steps to reproduce the problem

1.Have all party members on quest 10747, in a party of at least two.
2. Teleport to the cave near 32:34 in the Blade's Edge Mountains.
3. Have party members use the quest item 31129 as normal to attempt to catch whelps.
4. Observe the inconsistent behavior for which party members are given catch credit and spawn the item into their bags.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/642bd1936b341a098d7c8d5f3089988409e4d6bb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
It seems that this problem is not correct. It has probably been fixed.

Thank you for the report anyway.
