### ISSUE TITLE
Certain items works @ lvl 70 even though it's not intended for them to do so

### ISSUE THREAD

**Issue by bojan112** [chromiecraft/chromiecraft#5993]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Tidal Charm
Ultra-Flash Shadow Reflector
Hyper-Radiant Flame Reflector
Gyrofreeze Ice Reflector
all 4 items always work at lvl 70 even though tooltip clearly states that it can be resisted

### Expected Blizzlike Behaviour

there should be high chance for items to be completelly resisted when used against players above lvl 60

### Source

i'm banned from wowhead, i hope someone can find something there and post it here

### Steps to reproduce the problem

duel against other player, activate item and tell him to use targeted spells against you, everything gets reflected to caster

### Extra Notes

bugged reflectors are main issues as players are already abusing it in arena against casters comps

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/642bd1936b341a098d7c8d5f3089988409e4d6bb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
Hi @bojan112,
Thanks for your report !
I can confirm that all 4 trinkets can be easily used against lvl 70 targets.

Although, I would kindly ask you to provide more info about the source, and what should be the resistance rate maybe.

**Comment by FrancescoBorzi** [comment]
closing as not enough info provided. Please feel free to comment here if you have more useful info to confirm this bug and we will reopen it

**Comment by balleny** [comment]
those items should have around 90-95% chance of resisting against level 70 targets
source: none but retail experience
