### ISSUE TITLE
[WIP] Paladin proc to test

### ISSUE THREAD

**Issue by Yehonal** [chromiecraft/chromiecraft#6]
##### SMALL DESCRIPTION:

This issue is a "work in progress"

We need to test the paladin proc of the Judgement of spells since has been reported so far that the proc is triggered with a fixed interval. 

Please leave feedback with a video if you had the chance to test it

PS A proper issue with all the steps and the info will be created on AC soon

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The proc is dynamic, but cannot be triggered twice in a range of 4 seconds as stated here: https://github.com/azerothcore/azerothcore-wotlk/issues/698#issuecomment-340587479

however, there are people affirming that the proc is very dynamic and that can also proc twice in a second.

Some info:

* https://github.com/azerothcore/azerothcore-wotlk/issues/698#issuecomment-340211955
* https://github.com/azerothcore/azerothcore-wotlk/issues/698#issuecomment-340615695
* http://www.worldoflogs.com/reports/0w1utsdyg1suwv3a/xe/?s=6425&e=7362&x=healSpell+%3D+%22Judgement+of+Light%22%0D%0AAND+targetName+%3D+%22Jumii%22 (wow official logs from wotlk retail era)

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/38bf355bf479

**Comment by nicoaravena** [comment]
Was reading the issue, patch notes and even watch the video jumping second by second, and the judgement procs was once every 4 seconds as it says the notes.
Also, there is 2 types of ways to gain mana, judgement of the wise and judgement of wisdom, the first is the proc of 2% of mana, de second is the restored mana when using the judgment https://wowwiki.fandom.com/wiki/Judgement_of_Wisdom here you can find the 2 of them (5% when use it and 2% of the proc). Same percentages applies to judgement of light.

**Comment by Yehonal** [comment]
Thanks! I'm going to close this issue, with the hope to not re-open it again.
