### ISSUE TITLE
Walking on Water when alive.

### ISSUE THREAD

**Issue by Giaco96** [chromiecraft/chromiecraft#60]
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
I was alive, but i could walk on water like a ghost

##### EXPECTED BLIZZLIKE BEHAVIOUR:
normal swimming when in water

##### CURRENT BEHAVIOUR:
I was able to run on water, like how you're a ghost, I've also succesfully tried to submerge for swim, but going up and jumping I was returned in "jesus mode". I've suicided and bug was resolved.

https://cdn.discordapp.com/attachments/805462723424550934/808354520689147914/video0.mov

##### STEPS TO REPRODUCE THE PROBLEM:
I lefted a BG when I was dead, maybe the bug was caused by that

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
Feels a little bit like a game client missing cache update issue, but I only remember seeing other players not being updated on live, so I will wait for others to test reproducing this issue first (I still haven't set up a chromiecraft server for myself yet).

**Comment by Stifler82** [comment]
@Giaco96 
Next time this happens to you, simply try logging out and logging back in **(but clear the cache before reopening the game client)**, and check if you can walk in the water again, (so without killing yourself).

**Comment by JamesGent** [comment]
![WoWScrnShot_030721_001507](https://user-images.githubusercontent.com/61194190/110225138-4c1ef680-7eda-11eb-82f2-02c729b9945a.jpg)

Leave a BG whilst dead. Either it ends, you /afk out, or you get disconnected.

You can walk on water whilst alive (the property of ghosts walking on water isn't removed).

This is replicatable.

**Comment by FrancescoBorzi** [comment]
@JamesGent can you please link it to AC?

**Comment by JamesGent** [comment]
> 
> 
> @JamesGent can you please link it to AC?

Lmao I don't know how. :(

**Comment by FrancescoBorzi** [comment]
@JamesGent easy,

- open a report on AC, copy pasting this one (click "Edit", copy the raw text, paste in a new AC report)
- copy paste the link of the ChromieCraft report in the new AC report and github will automatically link the issues
- don't forget to update the labels accordingly

**Comment by claudiodfc** [comment]
fixed on https://github.com/azerothcore/azerothcore-wotlk/pull/5033
