### ISSUE TITLE
[Visual bug] Wounded Blood Elf Pilgrim (16993) - Incorrect behavior

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#6000]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

Horde players can get "[The Road to Falcon Watch](https://www.wowhead.com/wotlk/quest=9375/the-road-to-falcon-watch)" (9375), an escort quest from NPC 16993 at Hellfire Peninsula.
Talking with this npc will start the RP.
However, there is a small visual bug since the cage in which the NPC is locked is not showing any animation for opening, so the NPC simply goes through the bars and starts walking
![ 2023-07-06 a las 14 12 56](https://github.com/chromiecraft/chromiecraft/assets/77953030/4b096b7c-8772-4b2c-bdce-dd1283a45af2)

### Expected Blizzlike Behaviour

As you can see on [this video](https://youtu.be/1pB6EVLleAY?t=16), the gate of the cage should open before the NPC can step out and start the escort quest.

### Source

https://youtu.be/1pB6EVLleAY?t=16

### Steps to reproduce the problem

Have a Horde character of level 61 or more
Talk with NPC 16993 (Hellfire Peninsula [24,76]) to receive and start quest "The Road to Falcon Watch".
Observe how NPC goes through the cage gate while it remains closed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e5fe783fb956132502cdc35daea4f2aefd0a3d91

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by damnablebear** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/127447064/adbdca48-8b03-43db-92fe-1c93611be37c)
This works correctly on the PTR. Door opens, pauses for several seconds, and NPC steps out.

**Comment by heyitsbench** [comment]
This issue should have been resolved by https://github.com/azerothcore/azerothcore-wotlk/pull/16566. @cachocarne, would you be able to double check the quest on the PTR?

**Comment by heyitsbench** [comment]
Tested a few times on my local AC install, [saw the same results as damnablebear](https://github.com/chromiecraft/chromiecraft/assets/38561765/5596570c-5f14-45ee-95c5-616ed1832397). If you're able to reproduce it, please let us know, otherwise the issue will be closed.
