### ISSUE TITLE
[Mage][Talent] Deep Freeze can be removed by Paladin's Hand of Freedom

### ISSUE THREAD

**Issue by Velomania** [chromiecraft/chromiecraft#6004]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

I just joined WSG as a frost mage and found out that Paladin's [Hand of Freedom](https://wowgaming.altervista.org/aowow/?spell=1044) removes stuns such as mage's [Deep Freeze](https://wowgaming.altervista.org/aowow/?spell=44572)

### Expected Blizzlike Behaviour

[Hand of Freedom](https://wowgaming.altervista.org/aowow/?spell=1044) only removes [movement impairing effects that would be something that slows and/or roots you but still allows you to attack or cast spells, like Frost Nova or Entangling Roots. ](https://www.wowhead.com/wotlk/forums/topic/whats-the-difference-between-movement-imprairing-effect-and-loss-of-control-102837)
And it doesn't remove [loss-of-control effects that make your character unusable for the duration, such as Mind Control or Fear effects like Psychic Scream.](https://www.wowhead.com/wotlk/forums/topic/whats-the-difference-between-movement-imprairing-effect-and-loss-of-control-102837)

### Source

https://www.wowhead.com
https://wowgaming.altervista.org/aowow/

### Steps to reproduce the problem

1. Create a mage and a paladin
2. Duel each other
3. Use Deep Freeze on a paladin
4. Use paladin's Hand of Freedom 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e5fe783fb956132502cdc35daea4f2aefd0a3d91

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Velomania** [comment]
Correct me if I'm wromg

**Comment by balleny** [comment]
retribution talent adds removal of stuns
https://wowgaming.altervista.org/aowow/?search=divine+purpose#talents

**Comment by Never6** [comment]
It was probably a ret in which they have a talent that removes stuns
