### ISSUE TITLE
Problem quest Ishamuale

### ISSUE THREAD

**Issue by Kullnnt** [chromiecraft/chromiecraft#6011]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

I took the carcass after killing the zevhra with the hunter and placed it near the death tree which is in Thorn Hill. I try to put the received carcass but it doesn't place it on the ground so the Ishamuale raptor doesn't materialize. The hulk disappears and even if you take it back it doesn't work.

### Expected Blizzlike Behaviour

https://www.wowhead.com/classic/it/quest=882/ishamuhale

https://www.youtube.com/watch?v=PK6pGtG2YJ0

Image position tree
https://freeimage.host/i/Ht7b24t

### Source

(https://www.wowhead.com/classic/it/quest=882/ishamuhale)

### Steps to reproduce the problem

I right click on the carcass I receive in my backpack and it should automatically place the piece on the ground for the raptor to arrive, but the meat does not place it on the ground

### Extra Notes

Jorn  Skysser gives you the quest to go and kill this raptor at camp Taurajo in the Barrens

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e5fe783fb956132502cdc35daea4f2aefd0a3d91

### Operating system

windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Vanheden** [comment]
I tried it on Azerothcore and it worked and she spawned try go a bit to the right on your picture https://freeimage.host/i/wow-ishamuhale.Ht7b24t

**Comment by Kullnnt** [comment]
I don't work the carcass with the hunter he tells me he doesn't recognize the tree of death.

**Comment by elthehablo** [comment]
Were you in the right place?

**Comment by Kullnnt** [comment]
I tried it again and it was successful I don't know after 5 tries it didn't recognize the tree. I tested it yesterday and it worked. Thanks for the help, I believe after doing the zebra the meat carcass was not recognized by the tree. I can't explain to you how yesterday went. We can close problem solved
