### ISSUE TITLE
[NPC] Kolkar Centaur resistance values

### ISSUE THREAD

**Issue by Salehyn** [chromiecraft/chromiecraft#6023]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

30-39

### Current Behaviour

Kolkar centaurs in Desolace (all types) have randomly 70 fire and 30 shadow resistance for no apparent reason. Basically fire mages and warlocks do less than half their DPS against these enemies on CC, every spell is at average 50% resisted in the correct level bracket (lvl 30 vs lvl 30)
These mobs have thematically nothing to do with either fire or shadow damage, they never had resistances on any other server, nor is it indicated anywhere, ever, especially not this high values. 

### Expected Blizzlike Behaviour

There is no reason these enemies should have any sort of resistance values (other than the innate resistance they gain against lower level players). They shouldn't have any resistance to fire or shadow damage.

### Source

I can't find anything explicitly stating they have no resistances, but that's true for about 99% of npcs in the game. High magic resistances weren't a thing on 3.3.5a anymore, perhaps for a few specific elemental type of mobs it would make sense but not for random centaurs that have nothing to do with magic.

### Steps to reproduce the problem

Test spell damage as a lvl 30 fire mage or destruction warlock against the npcs I linked below

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=4636
https://wowgaming.altervista.org/aowow/?npc=4632
https://wowgaming.altervista.org/aowow/?npc=4637
https://wowgaming.altervista.org/aowow/?npc=4634
https://wowgaming.altervista.org/aowow/?npc=4633
https://wowgaming.altervista.org/aowow/?npc=4635

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e5fe783fb956132502cdc35daea4f2aefd0a3d91

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
