### ISSUE TITLE
[Item] Disappearance of Spirits Shards

### ISSUE THREAD

**Issue by Drugadu** [chromiecraft/chromiecraft#6025]
### What client do you play on?

esES

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

I can't find in any of my bags all my Spirits Shards, just only five about 205 as shown on the video. This happen around one week ago, i gave some time bc maybe fix it allone but stil having this issue. I'm pretty sure that i didn't destroy it because, when you destroy any item bagnon takes off the numbers of item you burn it and when i did on my video you could see it's working perfectly subtracting an item.

### Expected Blizzlike Behaviour

Spirits shards must to be on my bag (more if they are soul linked) to change for PVP gear.

### Source

Just personal problem of my account, i cant give any source..

### Steps to reproduce the problem

You can't reproduce it just loking bags and addons.

### Extra Notes

https://www.wowhead.com/tbc/item=28558/spirit-shard  (ittem)
https://youtu.be/yiZlSRIhYHY (video)
pic pre video
![Screenshot_7](https://github.com/chromiecraft/chromiecraft/assets/95693449/77bd685b-50c3-4149-a594-3d5174df97ed)

pic post video 
![fragmentos](https://github.com/chromiecraft/chromiecraft/assets/95693449/1f82a41c-0a6e-419f-b1a8-311587a84e64)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e5fe783fb956132502cdc35daea4f2aefd0a3d91

### Operating system

Windows 10 PRO 22H2

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Account issue, unable to replicate. make a support ticket if you didnt months ago
