### ISSUE TITLE
[Quest] Elixir of Agony (5): missing event

### ISSUE THREAD

**Issue by r-o-b-o-t-o** [chromiecraft/chromiecraft#603]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

For the last part of the questchain [[Elixir of Agony]](https://classic.wowhead.com/quest=524/elixir-of-agony) in the Hillsbrad Foothills, the barrel is already spawned before turning in the quest, and when the quest is completed, nothing happens.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The barrel appears only when turning in the quest, then the captured farmers are supposed to go to the barrel and die, and the barrel releases some sort of smoke.

https://youtu.be/WOdmiOJ9wts?t=121

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.q add 524`
2. `.go obj 20800`
3. See that the barrel is already spawned
4. Complete the quest
5. Nothing happens with the Captured Farmers

##### EXTRA NOTES:

Elixir of Agony: https://wowgaming.altervista.org/aowow/?quest=524
Captured Farmer: https://wowgaming.altervista.org/aowow/?npc=2284

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
hey man, being you a contributor who was able to reproduce it locally, please report this to the AC bugtracker.

This issue tracker is only meant to be a bridge between CC players and AC. The process is explained here: https://github.com/chromiecraft/chromiecraft

let me know if you have any questions :)

**Comment by fendwe** [comment]
This seems to be working correctly now.
