### ISSUE TITLE
[Progression:Arena] Arena teams should start at 1500 rating until Season 6

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6038]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Arena teams start at rating 0

### Expected Blizzlike Behaviour

Until season 6, teams should start at Rating 1500

### Source

https://wowwiki-archive.fandom.com/wiki/Arena_point
> As of Season 6 and later, the arena system was changed so that new teams start with a rating of 0 rather than 1500. Consequently, the formula was changed so that all teams below 1500 rating will earn points as if they were a 1500 rated team.

### Steps to reproduce the problem

.

### Extra Notes

Formulas for calculation of rating has already been updated, but start rating wasnt adjusted yet

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e5fe783fb956132502cdc35daea4f2aefd0a3d91

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Maria-sequel** [comment]
Hi, not staff, but the formula changed to wotlk values starting next week, therefor the rating should be 0 too.If they decide to not use the wotlk value, then you would have been correct.

cc @Gultask

**Comment by Maria-sequel** [comment]
Correct

**Comment by balleny** [comment]
alright, then this can be closed
