### ISSUE TITLE
[Quest][NPC][Item] Suppression / Imprisoned Doomguard (Commander) - Erroneous behavior

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#6042]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Warlock-only quest [Suppression (7583)](https://www.wowhead.com/wotlk/quest=7583/suppression) is the last one of a small chain started by [Daio the Decrepit](https://www.wowhead.com/wotlk/npc=14463/daio-the-decrepit) that we need to complete to recieve a new spell/ability: [Ritual of Doom](https://www.wowhead.com/wotlk/spell=18540/ritual-of-doom).

On this quest, we are asked to "capture" a [Doomguard Commander](https://www.wowhead.com/wotlk/npc=12396/doomguard-commander) using the [Glowing Crystal Prison](https://www.wowhead.com/wotlk/item=18601/glowing-crystal-prison), an item that requires us to cast still for a few seconds (15-20?).
During this time, it's recommended to use our Voidwalker to tank the demon, which I did. After the cast is complete, the Doomguard Commander despawns/disappears and instead, there is a big crystal standing where he was. We need to click on this crystal so we "imprison" the Doomguard Commander inside the crystal and take it to the questgiver.

However, even when we do this perfectly, we remain on combat and we keep on getting attacked by the Doomguard Commander (now invisible) as if he was still outside and not in the crystal. We get damage from many sources, including Rain of Fire, Cripple, War Stomp… and we cannot target the enemy or do anything else.
The list of abilities is [here](https://www.wowhead.com/wotlk/npc=12396/doomguard-commander#abilities;mode:normal). 
![ 2023-08-14 a las 21 16 22](https://github.com/chromiecraft/chromiecraft/assets/77953030/ff077e6a-e25e-4196-9ca9-ee910dec9442)
![ 2023-08-14 a las 21 16 27](https://github.com/chromiecraft/chromiecraft/assets/77953030/8b501415-fda9-4bba-b4e8-096dd9372409)

### Expected Blizzlike Behaviour

Once we complete the cast with the crystal and the mob despawns/disappears, and click to obtain the crystal in which the Doomguard Commander is imprisoned, we shouldn't be in combat with anything anymore and we should be able to leave.

### Source

https://www.wowhead.com/wotlk/quest=7583/suppression

### Steps to reproduce the problem

Have a warlock of at least level 60
Complete prequests:
[The Prison's Bindings (7581)](https://www.wowhead.com/wotlk/quest=7581/the-prisons-bindings)
[The Prison's Casing (7582)](https://www.wowhead.com/wotlk/quest=7582/the-prisons-casing)
Obtain next quest:
[Suppression (7583)](https://www.wowhead.com/wotlk/quest=7583/suppression)

Use the [provided item](https://www.wowhead.com/wotlk/item=18601/glowing-crystal-prison) on a [Doomguard Commander](https://www.wowhead.com/wotlk/npc=12396/doomguard-commander).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86bfef8874883a1726966326368918567c5531cd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, thanks.
