### ISSUE TITLE
Forward Commander To'arch in wrong location

### ISSUE THREAD

**Issue by Darconus** [chromiecraft/chromiecraft#6061]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

Forward Commander To'arch, questgiver at Reaver's Fall is not at Reaver's fall and is instead, South of the road nearby.

### Expected Blizzlike Behaviour

The NPC should be near the hut in Reaver's Fall

### Source

 attached image of current NPC location ![image](https://github.com/chromiecraft/chromiecraft/assets/142753389/e3624ff3-bc9d-416c-a437-9b4e99926287)

### Steps to reproduce the problem

1. Accept quest, Forward Base; Reaver's Fall
2. Travel to Reaver's Fall, NPC is not in correct location.

### Extra Notes

Link to relevant NPC, includes correct location: https://wowgaming.altervista.org/aowow/?npc=19273

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86bfef8874883a1726966326368918567c5531cd

### Operating system

Ubuntu 20.04
Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
Something must have bugged him out, because (on local AC):

![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/8a9b83b8-4257-4e7a-ad06-906e7c4d98d7)

closing this, sorry

**Comment by Darconus** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/142753389/31e00c8e-ae84-45b3-8fe6-64dd9a9e04e5)

It appears to be a specific issue with Chromie then, he's still there, and I've noticed several people asking where he is these past couple days, so it appears to not just affect me

**Comment by elthehablo** [comment]
> ![image](https://github.com/chromiecraft/chromiecraft/assets/142753389/31e00c8e-ae84-45b3-8fe6-64dd9a9e04e5)
> 
> It appears to be a specific issue with Chromie then, he's still there, and I've noticed several people asking where he is these past couple days, so it appears to not just affect me
> 

Yes that is strange

**Comment by Darconus** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/142753389/b2334fed-d58a-4a3e-bee7-5c9bd7d42099)

Server restart convinced him to return to his post. Looks resolved.

**Comment by elthehablo** [comment]
> ![image](https://github.com/chromiecraft/chromiecraft/assets/142753389/b2334fed-d58a-4a3e-bee7-5c9bd7d42099)
> 
> Server restart convinced him to return to his post. Looks resolved.

Yup that is what I thought. Weird that a mob like this gets stuck though. Mobs have a home position generally that they should return back to
