### ISSUE TITLE
[PvP] Consider Implementing WotlK Classic Arena Point reward formulas

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6062]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Currently, AZ has 2 options for arena point calculation: before and after season 6 mode from vanilla wotlk.

### Expected Blizzlike Behaviour

With TBC and WotlK Classic, further arena point calculations were introduced, partially re-creating the original state and partially reflecting modern changes. these also shifted over the time and are documented in here https://www.reddit.com/r/classicwow/comments/us1cg5/tbc_arena_calculator_formula_updated_for_s4/
the current formulas are active since season 4 and are the proposal for implementation in here
these calculations overall increase the amount of points gained and shift the focus to the larger brackets (3s and 5s)

they are supposed to be linked with the "personal" rating in wotlk classic and require each player to do 10 games per week - which is different from the current implementations

wotlk classic (past season 4) differences to wotlk vanilla:
- player have a personal rating, instead of team rating and team membership rating. for vanilla calculation, the team rating is taken into account, if the team membership rating is equal to or not less than 150 rating below the teams rating. if the membership rating is 150 or more rating below the team rating, the membership rating is taken into account for the calculation
- the team has to play at least 10 games per week in vanilla. each member has to have atleast 30% of the teams weekly games to be considered for point calculation. in classic, each player has to do 10 games only
- starting with season 6 in vanilla, arena teams were starting at rating 0 instead of 1500. arena points calculated for each week did default to 1500 rating if the players rating was below 1500 (this has been implemented in AZ recently). in classic teams also start at rating 0, but take this already into account. hence, the calculation is not requiring a differentiation if above or below 1500 rating

### Source

formulas:
https://www.desmos.com/calculator/vmehkbt2ur

5s: 1022/ (1+123 * (2.71828^{-.00412x}))+580

penalties factor
2s: 76/100
3s: 88/100

https://tbc.wow-tools.com/tbc_arena_calculator
https://www.curseforge.com/wow/addons/final-arena-calculator

### Steps to reproduce the problem

.

### Extra Notes

the biggest conflict is the personal players rating from classic and the rating structure from vanilla wotlk. for practical purpose, an adoption of the points formula, considering the old systematic of team rating to team membership rating (and the 150 rating below buffer) could be utilized regardless.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86bfef8874883a1726966326368918567c5531cd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vvranceanu** [comment]
I just want to add it would be sensible to do something about the points to not get in the situation in which we are farming points in s1 so we can afford s2

**Comment by balleny** [comment]
> I just want to add it would be sensible to do something about the points to not get in the situation in which we are farming points in s1 so we can afford s2

this is github, not discord/facebook. dont spread any nonsense which doesnt help the matter (nonsense because there is a arena point reset between seasons)

**Comment by vvranceanu** [comment]
> > I just want to add it would be sensible to do something about the points to not get in the situation in which we are farming points in s1 so we can afford s2
> 
> this is github, not discord/facebook. dont spread any nonsense which doesnt help the matter (nonsense because there is a arena point reset between seasons)

ok, let me reply to your petty-discord manner reply that dont matter with noting that if you were as smart as you want to convince yourself you are, you would have got the just of the comment that the point is that the point gain is too low compared to the cost of the items, while the ecosystem is just not there. i cannot "spread" non-sense, since this isn't discord/facebook and i will comment however i see fit since this is a suggestion, not a core issue to be fixed. it is a discussion by its very nature. k, false intellectual? ktnx

**Comment by balleny** [comment]
> ok, let me reply to your petty-discord manner reply that doesnt contribute with nothing that if you were as smart as you want to convince yourself you are, you would have got the just of the comment that the point is that the point gain is too low compared to the cost of the items, while the ecosystem is just not there. i cannot "spread" non-sense, since this isn't discord/facebook and i will comment however i see fit since this is a suggestion, not a core issue to be fixed. it is a discussion by its very nature. k, false intellectual? ktnx

the fact that you have to justify your comment, already proofs my point.

Every straight forward comment like "true, an increase in arena point gains would be beneficial imo" or alike would yield  better results, given that some of the people fixing issues and implementing suggestions reported in AZ aren't active or involved in CC. _Smart-assed, ironic or sarcastic_ comments have their place (to some extend) in discussions, but can lead to confusion wrt. to bug fixing and resolving of issues.

**Comment by balleny** [comment]
see also
https://github.com/chromiecraft/chromiecraft/issues/6089

**Comment by Maria-sequel** [comment]
This is more a suggestion then a bug report, and I think you should therefor report it here:   https://github.com/chromiecraft/chromiecraft/discussions
