### ISSUE TITLE
[Visual] Anchorite Karja (19467) - Wrong placement

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#6066]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

NPC [Anchorite Karja](https://www.wowhead.com/wotlk/npc=19467/anchorite-karja) is not sitting on the bench where she should. Or yes, she is technically "sitting on the bench", but she should sit a bit differently since she's not a kangaroo.
Other npcs in the same room are also kinda wrong, with their legs through the bench, but they are not so noticeable as this one.
![ 2023-08-24 a las 10 44 17](https://github.com/chromiecraft/chromiecraft/assets/77953030/4f9ee550-44e2-4d24-9221-b0430413c8d8)
![ 2023-08-24 a las 10 44 30](https://github.com/chromiecraft/chromiecraft/assets/77953030/443c4c50-9eae-4865-be1c-8fc06dd266ce)

### Expected Blizzlike Behaviour

[This](https://wow.zamimg.com/uploads/screenshots/normal/12681-anchorite-karja.jpg) is how she should be sitting ON the bench. 

### Source

Gravity

### Steps to reproduce the problem

Go to Area 52 in Netherstorm and find npc at [32,64]

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4c287e2873c3464a64baafc8c93a47521bccfbc9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
appears correct on live/my local

![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/6b5119c8-78f9-4b44-94a5-c4023601f4b2)
