### ISSUE TITLE
The Real Threat Npc not spawning after been killed and not looted

### ISSUE THREAD

**Issue by lsevoDev** [chromiecraft/chromiecraft#6067]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

40-49

### Current Behaviour

Quest https://wowgaming.altervista.org/aowow/?quest=680

Npc for the quest was killed and after that he does not respawn. After half hours of killing mobs around the place nothing happens. On discord posted question and one of the members checked on PTR for result, see the message https://discord.com/channels/788063059926712341/788799234207252540/1144351883427860550. If the npc is not looted then his respawn time takes long and if he is looted he will spawn after 5 sec.

### Expected Blizzlike Behaviour

His respawn time should be long like regular quest npcs but not over half hour. 

### Source

https://www.wowhead.com/wotlk/quest=680/the-real-threat

### Steps to reproduce the problem

1. teleport to Or'Kalar in Arathi Highlands
2. kill him and don't loot him
3. wait for his body to despawn
4. see how long does it take compared to when he is looted

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4c287e2873c3464a64baafc8c93a47521bccfbc9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
Hi @lsevoDev,
Thanks for you report.
I cannot reproduce this issue anymore on latest AC version.
The NPC is spawned at a different location after 6 minutes (default time) of the first kill.
You should scout the local area.
