### ISSUE TITLE
Dropin replacement of bags not possible if not empty

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6070]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

when you try to drag and drop an unused bag above a used bag, but the used bag contains items, you receive the error:
"you can only do this with empty bags"

right now, you have to empty the bag, exchange it, and then you  can refill it.

### Expected Blizzlike Behaviour

You should be able to exchange a bag in use with a different bag from your inventory if
1. the slots used/occupied in the bag are less or equal to the number of slots of the new bag
2. you dont have conflicting itemtypes (regular bag with ores and herbs, trying to replace it with a herb-only bag)

### Source

.

### Steps to reproduce the problem

equip a bag, put in 1 item.
drag and drop a different bag ontop of the filled bag

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4c287e2873c3464a64baafc8c93a47521bccfbc9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
https://worldofwarcraft.fandom.com/et/wiki/Bag
Confirmed as per stated in the wiki. In vanilla you needed to empty bags before changing them but this was fixed sometime during BC. 
Here is another thread discussing to add it to classic ahead of its time:
https://www.reddit.com/r/classicwow/comments/9rqijf/swap_bags_without_emptying_them_first_should_they/

This is a consistent issue on cc.

**Comment by cachocarne** [comment]
I never thought this should be possible, I assumed they had to be empty no matter what.
