### ISSUE TITLE
Major Auto Attack bug: Rotating the character or moving during auto attack during weapon swing animation, will delay the first hit and batch it with the second.

### ISSUE THREAD

**Issue by ndnd123** [chromiecraft/chromiecraft#609]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Rotating the character or moving during auto attack during weapon swing animation, will delay the first hit and batch it with the second. This is more noticeable on slower weapons. This is a similar glitch to a well known one in vanilla where using an instant ability during the weapon swing animation would batch the hit with the next one, however this glitch is game breaking because it happens on things as simple as movement and players cannot avoid it.

Apparently this bug has been around for months but to my surprise it has not been reported so I am doing so now.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Rotating or moving should not a auto attack hit with the next hit, however using a instant ability should.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Because this bug is more noticeable on slow weapons, equip two handed weapon
2.  As soon as you notice the weapon swing begin, rotate character a little bit
3.  Watch the combat text, you will see the first auto attack white hit batch with the second
4. 

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
I don't have a lot of private server experience but on the 2 vanilla p-servers I played I had the same bug, I figured it was "a common/can't be fixed bug that's also here".

**Comment by Azcobu** [comment]
I tried this but apparently wasn't doing it right. When I rotated, it would cancel the next swing's animation, but it would still show up in the combat log as a separate attack, not batched with the third. Video is here:

https://user-images.githubusercontent.com/81782124/117827781-70b79600-b2b0-11eb-9bc8-aa91b47752fc.mp4

Was my timing off or something?

**Comment by pop-pig** [comment]
Here is a video: https://www.youtube.com/watch?v=eJvndoUWQTg
Starting at 00:38 (unless youtube has authorized me to cut the video online, sorry youtube noob)
You can see in the combat log that the swing for 1+103 overkill is not displayed, but at the next auto-attack it is correctly displayed with the other swing.
I will try to get some footage on real mobs to show how their HP is not lowered by the "swing that is batched with the next auto-attack" (ie the 1+103 overkill swing in this case).

**Comment by pop-pig** [comment]
Another clip: https://www.youtube.com/watch?v=CUyqTSBwyk4
Wielding Vanquisher's Sword, 2.20 speed.
It happens around 00:09.
I'm not sure I'm reading everything correctly but it seems to me:
Mob has 2591 HP before "the bug" (after the hit for 65 is displayed)
Batched "not displayed auto-attack" hits for 57.
Next auto-attack hits for 54.
Mob has 2537 HP after hits for 57 and 54 are displayed.
2591 - 2537 = 54 so it seems that even if the batched auto-attack is not displayed, it does correctly lower the mob's HP.

However I seem to recall that sometimes it's not the case, will try to record more stuff happening.
It was especially annoying if your "batched" auto-attack would kill the mob and you'd then have to wait another auto-attack to overkill the mob.

**Comment by Azcobu** [comment]
Closing as it does seem that this is an animation/display issue, and the damage is being tracked by the server correctly as per comment above.
