### ISSUE TITLE
Grelin Whitebeard No Quest Hand In Notification

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#6095]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

Grelin Whitebeard in the start area in Dun Morogh does not have a quest question mark notification above his head or on the mini-map once the quest objective is completed (retrieving his journal/having his journal in possession).

### Expected Blizzlike Behaviour

Grelin Whitebeard should have a yellow question mark above his head and on the minimap at his location to notify that the quest can be turned in.

### Source

![grelin1withoutaddons](https://github.com/chromiecraft/chromiecraft/assets/143846899/97a20174-5e6a-4fc6-b207-1dfedaa85f5d)
![grelin2withaddonsanotherchar](https://github.com/chromiecraft/chromiecraft/assets/143846899/d6c29482-7daf-467f-856c-6a19d2e960a5)

### Steps to reproduce the problem

Accept the quest "The Stolen Jounral" from Grelin questbeard.
Retrieve his journal completing the quest objective.
Return to Grelin to see he has no quest marker above his head/or on minimap.

### Extra Notes

Both times checked with a gnome character, not sure if different on dwarf.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/280822cb8350213f374e59741506a607ce17dcaa

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
I can't reproduce this:
![WoWScrnShot_090723_232714](https://github.com/chromiecraft/chromiecraft/assets/134880284/0bab2c8e-9745-41e4-a005-950067b8c6ac)

I noticed both of you who reported this use enGB client, which is known to cause some issues. Could you try with an enUS client?

**Comment by cachocarne** [comment]
I use enUS client but some of the new textures patches. I experienced this effect of "!" or "?" missing but they showed up after relogging.
