### ISSUE TITLE
[Dungeon - Sethek Halls - Talon King Ikiss is INTERRUPTABLE.......]

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#6105]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

1. Talon King Ikiss is interruptable..

### Expected Blizzlike Behaviour

1. He is NOT interruptable./.

### Source

https://www.youtube.com/watch?v=YHVREaqvrH8 ...

### Steps to reproduce the problem

Go inside Sethek Halls
Fight End Boss - Talon King Ikiss

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/280822cb8350213f374e59741506a607ce17dcaa

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Paradigmxd** [comment]
To confirm - His polymorph for some insane reason is interruptable, never was and never will be.

**Comment by balleny** [comment]
as it should be.
the polymorph is supposed to be interruptable. the arcane explosion should technically not matter because his immunity shield should negate any attempts to interrupt. for the purpose of the boss script being poorly implemented, it would make sense to set the arcane explosion to uninterruptable

**Comment by Paradigmxd** [comment]
How is this as it should be, the point of the cast sequence is shield to explosion...

And polymorph was not interruptable on tbc classic at least in phase 1 ,why would it be here?

**Comment by balleny** [comment]
true, did some checking again and afaik he isnt supposed to be interruptable.
[before patch 2.07 he was interruptable, which then got changed.](https://www.wowhead.com/wotlk/npc=18473/talon-king-ikiss#comments:id=19998:reply=2494)

also seen in this video that the kicking has no effect / returns an immune
https://www.youtube.com/watch?v=WPpz07e6Cic

**Comment by Paradigmxd** [comment]
yep

**Comment by avarishd** [comment]
Edited the report, teleporting, explosion and the shield work correctly.
