### ISSUE TITLE
Grelin No Quest Question Mark/Notification

### ISSUE THREAD

**Issue by PSAdventures** [chromiecraft/chromiecraft#6107]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Grelin Whitebeard has no quest notification - question mark, when returning the quest "The Stolen Journal", neither does a quest completion icon - question mark, appear on the minimap to mark the hand in once the objective is completed.

### Expected Blizzlike Behaviour

On retrieving the journal which completes the only objective of the stolen journal a question mark should appear above Grelin Whitebeard's head and on the minimap at his location.

### Source

![grelin1withoutaddons](https://github.com/chromiecraft/chromiecraft/assets/143937215/d37a4159-4a6d-4708-8927-01ccb9c19a1e)
![grelin2withaddonsanotherchar](https://github.com/chromiecraft/chromiecraft/assets/143937215/00bdac69-b95a-4f25-b470-530a26f9314e)

### Steps to reproduce the problem

Accept the quest "The Stolen Journal"
Complete Objective
Return to Grelin
See there's no question mark above his head or on the mini map at his position.

### Extra Notes

Both times I was on gnome race characters, both seperately made characters one with addons on and one with addons off. Same bug twice.

https://www.wowhead.com/classic/quest=218/the-stolen-journal

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/280822cb8350213f374e59741506a607ce17dcaa

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
@Salehyn, if the issue is being closed as a duplicate, please attach the previously reported issue.

**Comment by Salehyn** [comment]
Good call this is the open report https://github.com/chromiecraft/chromiecraft/issues/6095
