### ISSUE TITLE
There was a giant friggen boat blocking the entrance of Mana tombs

### ISSUE THREAD

**Issue by xinmpg** [chromiecraft/chromiecraft#6110]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

I zoned into Mana tombs last night via RDF. When I came in, I had some weird bar/partial wall blocking my way. I could see the party in front of me, and I can see them fighting mobs. I cast a blizzard, but the blizzard appeared behind me. I couldnt figure out what was going on until I blinked forward and turned around. There was a giant night elf looking boat parked right in the entrance blocking the way.  

I swear I wasn't high, and took a screenshot to show this. I can't think of what could have triggered this except I believe I was in water in Zangarmarsh when the queue came up and I teleported in. I also think I was in combat when I accepted the queue and had to manually teleport in to the dungeon after combat. Sorry can't remember all the details, it was pretty late local time.

![Screenshot 2023-09-03 at 10 39 34 PM](https://github.com/chromiecraft/chromiecraft/assets/127726906/bde7903f-fe40-4fe5-91ba-69240aa7da98)

### Expected Blizzlike Behaviour

I don't think there should be a boat there.

### Source

n/a

### Steps to reproduce the problem

Teleport into Manatombs via RDF. See if there is a boat or not.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/280822cb8350213f374e59741506a607ce17dcaa

### Operating system

Win 11 Home VM inside Parallels on Macos 13.5.1.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

These are my addons. I'm not using any HD patch or anything else:

C:\ChromieCraft_3.3.5a\Interface\AddOns>dir /b
AtlasLoot
AtlasLoot_BurningCrusade
AtlasLoot_Crafting
AtlasLoot_OriginalWoW
AtlasLoot_WorldEvents
AtlasLoot_WrathoftheLichKing
AuctionHouseDepositFixer
aux-addon
Blizzard_AchievementUI
Blizzard_ArenaUI
Blizzard_AuctionUI
Blizzard_BarbershopUI
Blizzard_BattlefieldMinimap
Blizzard_BindingUI
Blizzard_Calendar
Blizzard_CombatLog
Blizzard_CombatText
Blizzard_DebugTools
Blizzard_GlyphUI
Blizzard_GMChatUI
Blizzard_GMSurveyUI
Blizzard_GuildBankUI
Blizzard_InspectUI
Blizzard_ItemSocketingUI
Blizzard_MacroUI
Blizzard_RaidUI
Blizzard_TalentUI
Blizzard_TimeManager
Blizzard_TokenUI
Blizzard_TradeSkillUI
Blizzard_TrainerUI
DBM-AQ20
DBM-AQ40
DBM-Azeroth
DBM-BlackTemple
DBM-BWL
DBM-ChamberOfAspects
DBM-Coliseum
DBM-Core
DBM-EyeOfEternity
DBM-Gruul
DBM-GUI
DBM-Hyjal
DBM-Icecrown
DBM-Karazhan
DBM-Magtheridon
DBM-MC
DBM-Naxx
DBM-Onyxia
DBM-Outland
DBM-Party-BC
DBM-Party-Classic
DBM-Party-WotLK
DBM-PvP
DBM-Serpentshrine
DBM-SpellTimers
DBM-StatusBarTimers
DBM-Sunwell
DBM-TheEye
DBM-Ulduar
DBM-VoA
DBM-VPVEM
DBM-WorldEvents
DBM-ZG
DBM-ZulAman
OmniCC
OmniCC_Config
Postal
Quartz
sellgrey
ShaguDPS
Skada
WeakAuras
WeakAurasArchive
WeakAurasModelPaths
WeakAurasOptions
_NPCScan

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi, this is a clientside issue that happens when an incorrect packet is received. 
A refresh should fix it.
