### ISSUE TITLE
Magic Rooster Egg mount

### ISSUE THREAD

**Issue by Thelebronz** [chromiecraft/chromiecraft#612]
ok

 type here

  Magic Rooster Egg 

![cascccasvafaf](https://user-images.githubusercontent.com/84021161/117815032-51dfe200-b265-11eb-8fba-6746417d4f51.png)
![czxvasfav](https://user-images.githubusercontent.com/84021161/117815053-56a49600-b265-11eb-8ebc-3acc2e2c3f45.png)
![caczxcz](https://user-images.githubusercontent.com/84021161/117815521-dc284600-b265-11eb-8d1d-8b1fdad97da8.png)

 the Magic Rooster Egg that i bouth in the shop need level 60 to learn it  but in wowlk database it says u need level 40 to learn it.

  its a game shop bug
 i dont have a video
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS <-------
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde <---------

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39<-------
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
 

Type here.
https://wotlkdb.com/?item=49290#see-also

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
you can see in the video the mount is for level 40 
https://www.youtube.com/watch?v=Rn9fQMirE2k

##### STEPS TO REPRODUCE THE PROBLEM:

1. just bouth it from the game shop
2. and it was send to me buy mail
3. when i loot it it was for level 60
4.

##### EXTRA NOTES:

Type here.
https://wotlkdb.com/?item=49290#see-also
make it for level 40

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
There are 2 magic rooster eggs in the shop, the lvl 40 one https://wowgaming.altervista.org/aowow/?item=49290 and the level 60 one https://wowgaming.altervista.org/aowow/?item=46778. IF you click "details" on the mount it opens up these links and you can see which is which.

**Comment by Helias** [comment]
@Thelebronz contact me on Discord at Helias#9347 if you want a refund for this mistake.
Anyways I've just updated the title of the products to make it less confusing.

![image](https://user-images.githubusercontent.com/519778/117857357-f88ba900-b28c-11eb-8fa2-37d0945252a2.png)
