### ISSUE TITLE
[Karazhan] Terestian Illhoof

### ISSUE THREAD

**Issue by shaszun** [chromiecraft/chromiecraft#6130]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

1. Terestian Illhoof creates only 1 portal, instead of 2 for the summmons to appear.
2. No imps appear from the portal/s.
3. No sacrifice was casted during the fight.

### Expected Blizzlike Behaviour

1-2. When the fight starts, he should create 2 portals near the wall behind him and imps to be summoned at specific interval.
3. Ocassionally a random person to be sacrificed at the green floor. The binding should be targetable and destroyable to free the person.

### Source

https://www.wowhead.com/tbc/npc=15688/terestian-illhoof#comments;mode:n10
https://youtu.be/Iv6zSyhmLGc?si=RoyLwrfZJ2idgqgg&t=1326

### Steps to reproduce the problem

1. Go in Kara
2. Get to Terestian
3. Start the fight

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by the-Deleuzian** [comment]
We did a test run last night on PTR and for our fight there was also only one portal and no imps.
Players would be sacrificed on the green floor but the shackling chains appeared on the players last position before being teleported to the green floor for sacrifice.

**Comment by shaszun** [comment]
> We did a test run last night on PTR and for our fight there was also only one portal and no imps. Players would be sacrificed on the green floor but the shackling chains appeared on the players last position before being teleported to the green floor for sacrifice.

I tested solo, so maybe it's logical that I didn't get any sacrifices.

**Comment by the-Deleuzian** [comment]
Ive opened an issue just concerning the chains here:
https://github.com/chromiecraft/chromiecraft/issues/6147

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/17297
