### ISSUE TITLE
[Priest] Prayer of Mending

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#6138]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

[Inspiration](https://www.wowhead.com/wotlk/spell=15363/inspiration) does not proc from [Prayer of Mending](https://www.wowhead.com/wotlk/spell=33076/prayer-of-mending) crits

### Expected Blizzlike Behaviour

[Inspiration](https://www.wowhead.com/wotlk/spell=15363/inspiration) should proc from [Prayer of Mending](https://www.wowhead.com/wotlk/spell=33076/prayer-of-mending) crits

### Source

Talent tooltip
"Reduces your target's physical damage taken by 10% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Penance, **Prayer of Mending**, Prayer of Healing, or Circle of Healing spell."

Wowhead:
By [350513](646 – 2·9) [on 2009/07/07] (Patch 3.1.3)
Inspiration currently (3.1.2) procs on Prayer of Mending crits but not on Empowered Renew crits

### Steps to reproduce the problem

1. Use Prayer of Mending with Inspiration talent
2. Wait for PoM crit

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, thanks.
extra source https://www.engadget.com/2009-10-05-spiritual-guidance-can-prayer-of-mending-be-improved.html
