### ISSUE TITLE
[Shaman] Shamanistic Rage ppm

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#6139]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Shamanistic Rage ppm is only about 10, so you get very little mana from it

### Expected Blizzlike Behaviour

PPM should be much higher than 10. About 14-18ppm(not sure, sniffs needed)

### Source

1.
https://classic.warcraftlogs.com/reports/pLdq2YVyjvNf38rQ
proc/hits - 	23/45
wpn speed - 	1.8/2.7

2.
https://classic.warcraftlogs.com/reports/mh7y2FvPtwDAkVM6
proc/hits - 	23/30	22/39	21/31	
wpn speed - 	2.6/2.7	1.8/2.7	1.8/2.7

3.
https://classic.warcraftlogs.com/reports/DkRHCwJGd1W9v2jg
proc/hits -	19/28	25/33	18/32	21/33	22/27
wpn speed - 	2.7/2.7	2.7/2.7	2.7/2.7	2.7/2.7	2.7/2.7

### Steps to reproduce the problem

1. Use Shamanistic Rage
2. Hit target with any weapon 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm by logs (different logs) and https://wowsims.github.io/wotlk/ that ppm is 18~ for recycled version at least.
Find any random log with enhancer, select buff apply-end timestamp then use filter expression "ability.name = "Shamanistic Rage", go to resources(mana)->events
