### ISSUE TITLE
AoE Buffs Not Ignoring Line of Sight as Intended

### ISSUE THREAD

**Issue by minthes** [chromiecraft/chromiecraft#6145]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

AoE buffs from priests, druids, paladins, and mages fail to apply when obstructed by line of sight.

### Expected Blizzlike Behaviour

as long as the player is in range, buffs, such as [Prayer of Fortitude], Paladin blessings, Mage AoE intellect buff, and Druid AoE Mark of the Wild buff, is that they should be applied, even when the target is obstructed by Line of Sight from the caster

### Source

Thank you @heyitsbench for helping sniff this bug on classic. As you can see in the video, [Flash heal] cannot be cast when the target is out of LoS, but the Prayer of Fortitude applies.
https://www.youtube.com/watch?v=ito5CNpDe_0

### Steps to reproduce the problem

1. Make a priest and any other character
2. Learn the spell [Prayer Of Fortitude]
3. Have the two characters be in the same group
4. Make the second character LoS the priest while still being in range to be buffed (40 yards)
5. Cast [Prayer Of Fortitude]
6. Observe how the second character is not buffed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, thanks for report & source.
