### ISSUE TITLE
[Karazhan] Moroes not applying Garrote Debuff

### ISSUE THREAD

**Issue by the-Deleuzian** [chromiecraft/chromiecraft#6146]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

After Moroes Vanish finishes he doesn't apply his Garrote debuff to any of the players in Raid.

### Expected Blizzlike Behaviour

After reappearing from his Vanish he should apply this debuff called Garrote on a random player that deals damage over a long time.

Burning Crusade Boss Guide for Moroes on WoWHead:
https://www.wowhead.com/tbc/guide/moroes-karazhan-strategy-burning-crusade-classic

Spell Page for Wotlk Database on WoWHead (Comments referenced from Thottbot linking Moroes to this debuff):
https://www.wowhead.com/wotlk/spell=37066/garrote#comments

### Source

https://www.youtube.com/watch?v=YOH184e0Om0

### Steps to reproduce the problem

1. Enter Karazhan
2. Engage Moroes Boss fight
3. Observe the Vanish Phase of the boss and its immediate aftermath

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by minthes** [comment]
This was working a few weeks ago when Rum Rage did a PTR test run. On our yesterday's run it did not work

**Comment by elthehablo** [comment]
It does work on my local

**Comment by Apathyxia** [comment]
On TLD's PTR runs, it did ONLY work during enrage phase around 5 weeks ago. Yesterday it didn't work at all. 5 weeks ago Moroes applied the garrote to himself.

**Comment by shaszun** [comment]
And it wasn't reported 5 weeks ago?

**Comment by Apathyxia** [comment]
We made a bigger list of issues and directly sent it to those involved in fixing the bugs as was guided by a developer.

**Comment by kerricsson** [comment]
We made guild run yesterday and he's applied Garrote. PTR version was from 15.09

**Comment by Nyeriah** [comment]
My theory is that if the player garroted is casting it won't get the garrote debuff

**Comment by the-Deleuzian** [comment]
Update (10/5/2023): On our last raid night the garrote debuff was applied. Seems fixed
