### ISSUE TITLE
[Karazhan] Terestian Illhoof - Demon chains don't appear on the sacrifice place

### ISSUE THREAD

**Issue by the-Deleuzian** [chromiecraft/chromiecraft#6147]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

When Terestian Illhoof is sacrificing a player the Demon chains don't appear around the player at the sacrifice place with the green floor.
It seems they spawn at the players last spot before being teleported to the sacrifice place.

### Expected Blizzlike Behaviour

The Demon Chains should appear at the same spot as the player who is sacrificed at the place of sacrifice with the green spot on the floor.

WoWHead Bossguide:
https://www.wowhead.com/tbc/guide/terestian-illhoof-karazhan-strategy-burning-crusade-classic

Spell Page on WoWHead (WotLK):
https://www.wowhead.com/wotlk/npc=17248/demon-chains

### Source

https://www.wowhead.com/wotlk/npc=17248/demon-chains#screenshots

### Steps to reproduce the problem

1. Enter Karazhan
2. Engage the boss Terestian Illhoof
3. Observe the Sacrificing Phase of the fight

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Is this still an issue?

**Comment by the-Deleuzian** [comment]
I am raiding again on thursday and will post an update afterwards

**Comment by avarishd** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/46330494/a05604f7-72e1-4593-8d86-537a4fcd7244)
