### ISSUE TITLE
Paladin Divine shield in lava

### ISSUE THREAD

**Issue by rawrgargar** [chromiecraft/chromiecraft#615]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Divine shield (Big boy bubble) doesn't stop lava damage. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Divine shield should cause immunity to any and all things, because that is the paladin way.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go into lava
2. Press the bubble button
3. ???
4. Die a fiery death

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Found a Wrath-era source and added it to the AC issue. It doesn't specifically mention lava, but it does mention drowning, which is also not being blocked by Div Shield.

**Comment by rawrgargar** [comment]
As a side note, divine shield is supposed to make you immune to everything except specific boss mechanic 1 shots. It blocks all other types of damage in the game. The ultimate bubble.

**Comment by CadmannG** [comment]
Divine Shield is also not removing ordinary magic debuffs (e.g. Faerie Fire cast by Winterfall Pathfinder), and it does not properly prevent combat damage from interrupting bandage items.

**Comment by Azcobu** [comment]
@CadmannG cheers, have updated the AC issue with that info.
