### ISSUE TITLE
Recklessness

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#6158]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

https://www.wowhead.com/wotlk/spell=1719/recklessness provides fear immunity 
![WoWScrnShot_091923_105517](https://github.com/chromiecraft/chromiecraft/assets/66432845/7c6aade9-7cbf-4732-9dc8-f0d21864b4d7)

### Expected Blizzlike Behaviour

recklessness should no longer provide fear immunity on 3.3.5 https://www.wowhead.com/wotlk/guide/classes/warrior/fury/dps-overview-pve

### Source

https://www.wowhead.com/wotlk/guide/classes/warrior/fury/dps-overview-pve

### Steps to reproduce the problem

duel a warlock
cast reck
lock casts fear
warrior is immune

### Extra Notes

this was reported before hand https://github.com/chromiecraft/chromiecraft/issues/6126 but it was closed as im not sure why 
the screenshot attached above was taken from ptr the day i am writing this so im really not sure why it was closed as it is a  bug and should be fixed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> but it was closed as im not sure why

It was closed because the behavior doesn't match Classic.

**Comment by heyitsbench** [comment]
Allow me to point out you used a Wowhead guide targetting Wrath Classic as a source for this issue.

**Comment by Hihilist** [comment]
Checked all the patch notes (documented and not) and there were no changes to Recklessness regarding Fear (Fleeing) mechanic.
Also provided link to spell states that 
![obraz](https://github.com/chromiecraft/chromiecraft/assets/71841180/6b8cc948-3a41-4382-b7fe-1a651cd6c815), sam fo ther DBs like https://wowgaming.altervista.org/aowow/?spell=1719 or https://db.rising-gods.de/?spell=1719

**Comment by Reily93** [comment]
recklessness provide fear immunity , was reworked from classic in which it worked like berseker rage, now it only make u immune toi fear while active but cant remove it if alredy up, i saw some high rated warr using it on classic woltk
