### ISSUE TITLE
[NPC]Stonemaul Spirit doesn't auto aggro if player stands still and is missing the text quotes

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#617]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Stonemaul Spirit (https://wowgaming.altervista.org/aowow/?npc=23786) for quest Spirits of Stonemaul Hold (https://wowgaming.altervista.org/aowow/?quest=11159) is missing the quote texts when he is attacking and doesn not aggro/attack the player when summoned if player does not move or attack him.
![nodanger](https://user-images.githubusercontent.com/80769357/117859535-6b961f00-b28f-11eb-9077-b6f28ff48754.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Stonemaul Spirit should auto aggro/attack player once summoned even if the player stands still, and they should be using their text quotes while attacking.
https://youtu.be/jHpHWzHj42s?t=65

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be level 35+ and have ://wowgaming.altervista.org/aowow/?quest=11158 and https://wowgaming.altervista.org/aowow/?quest=11160 completed
2. Take the quest https://wowgaming.altervista.org/aowow/?quest=11159
3. Go to quest target (GUID 40811 for example) and use the quest item on it
4.Do not move when you summon the ogre and see that he does not attack unless you move or attack him
5. When he is attacking see that he is not using his text quotes

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by fendwe** [comment]
This seems to be working correctly now.

**Comment by avarishd** [comment]
fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/5812
