### ISSUE TITLE
Scarlet key dropping off mobs

### ISSUE THREAD

**Issue by rawrgargar** [chromiecraft/chromiecraft#618]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When inside the library dungeon, we were getting scarlet key drops. We seemed to only get them off of monks however, so probably just a miss tagged loot table.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The key should only come out of the chest after Doan in library, not off random mobs.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill mobs in library, I have not seen this before tho, but it happened twice in 1 run.
2.  It seems like it is only monks so try grinding them.

##### EXTRA NOTES:

Screenshot attached of the drop.

![WoWScrnShot_051121_123614](https://user-images.githubusercontent.com/26581194/117860990-88623080-b256-11eb-903e-6b6d91e12303.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I've seen it drop from a Diviner in the Library on another server running AC. So it may not be limited to monks. Either way I don't believe it should be part of their loot tables.
[https://classic.wowhead.com/npc=4540/scarlet-monk](https://classic.wowhead.com/npc=4540/scarlet-monk)
So far I've run this a dozen times in a row with no key drops. I can't argue the screenshot, it's right there. I even have one myself from another AC server, but I can't reproduce it right now. Maybe one of the smarter people can take a peek at the loot table for us. If not I'll try again tomorrow.

**Comment by Azcobu** [comment]
@Stump876 Thanks for checking. If you have a look at the Keira3 DB viewer, it shows Monks, Diviners and Chaplains all drop it with a 0.02% rate. So no wonder a dozen runs didn't see any drops - I'm only surprised the original reporter apparently found _multiple_ keys. Clearly @rawrgargar is a person you want to bring along for rare drop farming runs...

**Comment by rawrgargar** [comment]
Sadly, I still haven't found any other rare gear, that is crazy tho getting 2 in 1 run, I'll have to tell the people I was with lmao
