### ISSUE TITLE
Heroic presence not working

### ISSUE THREAD

**Issue by BeastieBM** [chromiecraft/chromiecraft#6181]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

I did Karazhan with 7.04% hit + Heroic Presence as a BM hunter and i ended up missing 13 autoshots, 6 steady shots, 2 arcane shots, 1 multishot, 3 serpent stings + my pet missed 16 autoattacks, 6 bites, 3 monstrous bites.
As 8% hit is cap i should not be missing like this so there is something not working with the racial skill.

### Expected Blizzlike Behaviour

Heroic Presence should be recieved.

### Source

![Heroic Presence](https://github.com/chromiecraft/chromiecraft/assets/146030943/a5d2e739-e147-45dc-acdc-02803a125f35)

### Steps to reproduce the problem

Log onto a lvl 70 draenei hunter. 
Get 7% hit.
Go into Karazhan and smash some bosses.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/152429867b8193c9403e5b5271c0c3d7d4c13a3c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Attumen reduces hit chance. What boss is this data from?

**Comment by BeastieBM** [comment]
It is from whole Kara run all bosses. I did not check specific from horseman since it did not get saved. Next week I will do a more thorough review of data.
________________________________

**Comment by mturca** [comment]
Same for Nightbane - you might want to exclude those 2 to avoid any spells that will reduce your chance to hit to get a baseline.

**Comment by avarishd** [comment]
Update?

**Comment by avarishd** [comment]
No information has been given in quite some time, if it happens again, reopen.
