### ISSUE TITLE
Undertaker Mordo is either standing in the wrong place for 3.3.5 or the quest text is wrong.

### ISSUE THREAD

**Issue by Istox** [chromiecraft/chromiecraft#62]
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
In Deathknell Hes standing outside the tomb. and the quest text for quest "Rude Awakening" states..
"To get out of the crypt, take the steps up the to surface."

##### EXPECTED BLIZZLIKE BEHAVIOUR:
This would indicate to me that either the quest text is wrong for your target expansion or the NPC location is wrong for the target expansion.

##### CURRENT BEHAVIOUR:
As above

##### STEPS TO REPRODUCE THE PROBLEM:
1. Start fresh UD character
2. Run out of the tomb and at the top
3. Talk to Undertaker Mordo / Read "rude awakening".

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
I confirm, the NPC [Undertaker Mordo](https://wotlkdb.com/?npc=1568) 

who gives the Undead Starter quest [Rude Awakening](https://wotlkdb.com/?quest=363)
 **is in the wrong coordinate.**
 **Video** of my **Test**: [Undertaker Mordo](https://youtu.be/touQVsCOIXg)

**Comment by FrancescoBorzi** [comment]
The fix is now on ChromieCraft. Thanks for your report.
