### ISSUE TITLE
[NPC]Smolderwing Missing his scripted text quotes

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#620]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When Smolderwing (https://wowgaming.altervista.org/aowow/?npc=23789) spawns (for the quest https://wowgaming.altervista.org/aowow/?quest=11162) he is not saying his quotes.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When Smolderwing spawns he should say his quotes.
https://youtu.be/0S-Hrc8gdpc?t=120

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be 35+, Have the quests ID 11158, 11159 and 11160 complete (the chan leading up to https://wowgaming.altervista.org/aowow/?quest=11162)
2. Take https://wowgaming.altervista.org/aowow/?quest=11162 and move to Onyxia Lair entrance
3. Plant the banner infront and see Smolderwing spawn
4.Observe no text from him

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5810
