### ISSUE TITLE
[Aura] Dire Brew - Incorrect behavior on Draenei

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#6203]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

50-59

### Current Behaviour

After talking (and drinking a lot) with the [Dark Iron Brewer](https://www.wowhead.com/wotlk/npc=28067/dark-iron-brewer) in Blackrock Depths tavern, we get a big Mug of Dire Brew on the ground. Clicking on it gives us the item [Dire Brew](https://www.wowhead.com/wotlk/item=38320/dire-brew).
Drinking (using) this item will transform our character into a Dark Iron Dwarf (with different sets of gear and male or female, depends on our gender or other effects applied).

Currently this effect works on all Alliance races except on Draenei, which for some reason doesn't show up.
I haven't tested it on Horde, but could be that there is a similar eror on Blood Elves, being also from TBC content.
![ 2023-09-27 a las 10 36 17](https://github.com/chromiecraft/chromiecraft/assets/77953030/33b623b4-0877-47cf-a837-96174ad0c1cc)

### Expected Blizzlike Behaviour

Dire Brew should transform our character into a Dark Iron Dwarf for one hour, no matter our race.

### Source

https://wowpedia.fandom.com/wiki/Dire_Brew
https://www.wowhead.com/wotlk/item=38320/dire-brew
https://wowwiki-archive.fandom.com/wiki/Dire_Brew

### Steps to reproduce the problem

Have a Draenei character with proper level enough to enter BRD
Get to Blackrock Depths tavern
Talk to Dark Iron Brewer and follow his dialogue and options to drink with him until he passes out and drops the mug
Use Dire Brew from your inventory and observe effect not being applied (although it works on other alliance races)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Crumen** [comment]
I can confirm that this isn't bugged on Blood Elves.

**Comment by Kitzunu** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/24550914/9eb31dc9-79f5-4656-a645-cfa4fbb64f0b)

Can't reproduce https://github.com/azerothcore/azerothcore-wotlk/commit/b87407907271ad8fefaa81f513de729eba3fe8d2

**Comment by cachocarne** [comment]
Thanks a lot for testing and commenting. I would imagine this is another issue related to HD/Legion textures. Therefore, a game client issue.
