### ISSUE TITLE
Attacking Mograine with ranged ability won't aggro other mobs in Scarlet Monastery Cathedral

### ISSUE THREAD

**Issue by Beastmasterwow** [chromiecraft/chromiecraft#621]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Attacking Mograine with ranged ability in this case Exorcism doesn't pull the remaining mobs in the Cathedral.
We cleared the Cathedral  leaving only mobs left from Mograine, when I casted Exorcism they failed to aggro.
Link to the classic wowhead: https://classic.wowhead.com/npc=3976/scarlet-commander-mograine

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Engaging Mograine with melee or ranged attacks should aggro basiclly every mob you haven't killed in the Cathedral itself.

Proof in comments: https://classic.wowhead.com/npc=3976/scarlet-commander-mograine#comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the last boss Mograine in SM Cathedral.
2. Clear the trash, leaving mobs from the left cript alive.
3. Engage Mograine with Exorcism
4.

##### EXTRA NOTES:

Test with other ranged abilities.

EDIT: I tested it with paladin's and warrior's taunt, it aggroed other mobs.
I even asked a priest to pull the boss with Smite, it aggroed entire room, maybe it must be a bug with paladin's Exorcism.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Couldn't reproduce this, tried with both a druid and a pally using Exorcism as you suggested:

https://user-images.githubusercontent.com/81782124/118350231-b2885b00-b594-11eb-893b-7fa730758d6b.mp4

There are one or two mobs who didn't aggro in the second clip, but otherwise it looks fine. Have you run into this problem repeatedly, or was it a one-off?

**Comment by j-hdt** [comment]
can be reproduced with a warrior using a bow.

**Comment by Azcobu** [comment]
Thanks for the update. Tried with a bow-armed warrior, and didn't see any issues. I'm wondering if it's a positioning issue, am I standing in the same place you were?

https://user-images.githubusercontent.com/81782124/119348882-998e5100-bcdc-11eb-837a-352485c826c9.mp4

**Comment by cts17** [comment]
We just experienced this in our RDF. A mob fled from our group and triggered the boss. Doing this made the boss pull without triggering the rest of the mobs.
