### ISSUE TITLE
/invite-ing a player while they are solo in a Normal dungeon results in a "{Player} is ignoring you" message

### ISSUE THREAD

**Issue by andovcr** [chromiecraft/chromiecraft#6211]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

When Player A is in a Normal difficulty dungeon, solo (and thus invite-able), and Player B invites Player A to party, then Player B will receive a message that Player A is ignoring them, even though they are still able to /w Player A (Player B is not on Player A's Ignore List).

This seems to only happen on Normal dungeon difficulty (not Heroic & not in raid instances)

### Expected Blizzlike Behaviour

I'm not 100% certain what Blizzard's behavior would be, but I would expect it to allow the invitation to go through (just like on Heroic mode for dungeons or in raid instances), but failing that, at the very least I strongly believe it should send a different message (rather than that the player is ignoring you).

### Source

In this case, I would argue that the invite going through on the Heroic version of a dungeon (but not on the Normal version) should be proof enough?

### Steps to reproduce the problem

1. Player A zones into Normal dungeon
2. Player B /invite Player A
3. Player B sees incorrect message

repeat for Heroic dungeon, and invite goes through successfully

### Extra Notes

![image](https://github.com/chromiecraft/chromiecraft/assets/58115742/de5d2f71-ae21-451c-b9a3-09c57ef02034)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf
![image](https://github.com/chromiecraft/chromiecraft/assets/58115742/cb9cddd9-af63-4080-aa89-3c68fc69a3db)

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by andovcr** [comment]
@heyitsbench

**Comment by minthes** [comment]
It happens when a player is in a heroic or a battleground as well

**Comment by shaszun** [comment]
Isn't this due to an addon?

**Comment by Kitzunu** [comment]
Cannot reproduce

**Comment by heyitsbench** [comment]
Possibly a result of a CC addon?
