### ISSUE TITLE
[Item] "Plans: Ragesteel Shoulders" droprate possibly bugged for character.

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#6217]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Item ID 33174 {Plans: Ragesteel Shoulders) may drop from Enraged Air / Earth / Fire / Water Spirits in Shadowmoon Valley, with a possibly major reduced drop chance. 

Currently in the process of exterminating each and every Enraged Elemental Spirit in Shadowmoon Valley from existence.
However, doing this for multiple days and countless kills am still yet to see a glimpse of the Blacksmith Pattern. I understand the low percentage chance, but something does seem quite off.

### Expected Blizzlike Behaviour

It should drop from the following Npc's:

WoWhead:
Npc 21050 (Enraged Earth Spirit) 0.3% drop rate. 
Npc 21060 (Enraged Air Spirit) 0.06%, 
Npc 21059 (Enraged Water Spirit) 0.08%
Npc 21061 (Enraged Fire Spirit) with 0.1%.

However these drop rates are inconsistent, as the source also takes into account of those who didn't have the blacksmithing profession when attempting to farm the drop. But have had players with Blacksmithing take only a short time to obtain.

Alternative source:
https://wowgaming.altervista.org/aowow/?item=33174

This source reveals a higher percentage of drop rates for the item in question.
Air: 0.21%
Earth: 0.37%
Fire: 0.18%
Water: 019%

### Source

https://www.wowhead.com/tbc/item=33174/plans-ragesteel-shoulders

https://wowgaming.altervista.org/aowow/?item=33174

### Steps to reproduce the problem

Check database? ^^;

### Extra Notes

Have recently installed Mobinfo 3.75 to keep track.

Also screenshot of the kills so far:
![SMVDrop-RageSteelShoulders](https://github.com/chromiecraft/chromiecraft/assets/147021592/c532466a-2f4e-4602-8586-06a31eadab6b)

Never tried to fill out a form like this before, apologies if missing vital info - have tried to add as much as I could.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vkdog** [comment]
Yeah a strange experience with these recipes and others. I got a lot of recipes on first mob relevant mob kill, the shoulders in question however took me a few hours. Two friends of mine got the recipe on first mob kill though.

**Comment by InfernalDark** [comment]
For me it took 3 weeks of (almost) daily farming to get these.

**Comment by Bonham01** [comment]
same issue for me. nearly 6 hours killing every type of elemental (earth, fire, water, air) in SMV. still nothing

**Comment by Kitzunu** [comment]
The item is present in the loot templates, so not bugged.

Loot is calculated per mob per kill. So if you are unlucky you can kill a billion and get no loot. There is no loot guarante
