### ISSUE TITLE
Dr. Whitherlimb inside building, silverdragon addon

### ISSUE THREAD

**Issue by Kitakoni** [chromiecraft/chromiecraft#622]
![image](https://user-images.githubusercontent.com/84040696/117869139-1b28bc80-b2a3-11eb-85b7-4f72dbb83a42.png)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I have no idea, wow newbie here but it shouldnt be inside the building?

##### STEPS TO REPRODUCE THE PROBLEM:

1. I was using SilverDragon addon, then the mob spawned, then i saw it inside the building
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Actually he wanders around that area, not necessarily inside. Look like he fell through the floor. I had no problem with Dr. Whitherlimb, but I had a similar issue with the Darkmages from inside. It seems like they can sometimes ignore the stairs and just clip to outside. Sometimes like in the screenshot they just fell through the floor. It might be a hollow spot in the floor or something (Sorry, I'm not a dev). But I can confirm something isn't working right, and it has nothing to do with your addon. Thanks for the report!
![image](https://user-images.githubusercontent.com/68164076/117911777-34297180-b293-11eb-9986-6c2c36b4c12c.png)
![image](https://user-images.githubusercontent.com/68164076/117911829-4c00f580-b293-11eb-8e06-d99f063ebf28.png)
![image](https://user-images.githubusercontent.com/68164076/117911882-5f13c580-b293-11eb-8040-cc3293706ba8.png)

**Comment by Kitakoni** [comment]
After couple hours of grinding, i came back to this spot to see he is not bugged now.

**Comment by necropola** [comment]
CC has a daily (early morning in EU) restart.

**Comment by fendwe** [comment]
This seems to be working correctly now.

**Comment by damnablebear** [comment]
I can kind of reproduce this but it feels really dubious. I think it's an issue with ziggurats in general. You can get this to happen even if you aggro some of the gargoyles from the outside and run up on the sides or back of the ziggurat. However, it's pretty tough to get onto some of the back sections of the ziggurat (you have to make a very specific jump) so I can't see this happening that much. They seem to clip into the ziggurat's bottom layer's perimeter, but they are still targetable, and run back out of the wall perimeter when you jump off the ziggurat. I think that the bug that is reported here was that the mobs don't exit the ziggurat, which they now seem to do. There just seems to be a sort of visual bug about them entering that bottom section, if you kill them down there, they should still be able to be looted based on proximity, etc. I feel like this is pretty inconsequential in the long run, but if we want this to be perfect, then we might want to investigate how or why enemies can clip through that bottom ziggurat layer, and change the pathing to the outside of that perimeter.

**Comment by Salehyn** [comment]
I could reproduce this steadily by walking up on the edge of the ziggurat in the back, where the ground is higher. (no gm cheat required)
![WoWScrnShot_082523_181128](https://github.com/chromiecraft/chromiecraft/assets/134880284/443574c7-c368-4191-96da-f9dde44d6233)
There seems to be pathing issues here.

**Comment by Salehyn** [comment]
This issue is not specific to NPC position but part of this problem https://github.com/chromiecraft/chromiecraft/issues/1364
So I will leave that one open instead.

Apparently there are multiple issues opened about this on AC and all have been closed with "cant reproduce", but that might be an issue with which ziggurats they tested, i reopened this which specifically speaks of ghostlands one
https://github.com/azerothcore/azerothcore-wotlk/issues/7269
