### ISSUE TITLE
Mage Blink when slow fall is active removes the downside of slow fall

### ISSUE THREAD

**Issue by mturca** [chromiecraft/chromiecraft#6220]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Mage Blink when slow fall is active removes the downside of slow fall

### Expected Blizzlike Behaviour

Should not remove the slow part of slow fall - animation wise you should still fall slowly towards the ground if it was not in range when using blink

### Source

https://www.wowhead.com/wotlk/spell=130/slow-fall

### Steps to reproduce the problem

1. as a mage find a high enough place 
2. cast slow fall on you 
3. jump to your not so impending doom
4. cast blink while in the air
5. notice that you will start accelerating towards the ground 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by mturca** [comment]
if a video is needed of the behavior let me know and i'll make one

**Comment by Stump876** [comment]
Hi mturca. Thanks for the report. But doesn't blink remove all movement imparing effects? I see nothing in the link that says they can be used together. Do you have a source that says/shows they can be used at the same time? I found this, but I have no idea how reliable it is https://us.forums.blizzard.com/en/wow/t/a-random-mage-question-blink/74616. Maybe we can get someone with retail access to check it.

**Comment by mturca** [comment]
Not all movement impairing as far as i know - it removes root / snare & stun. Overall they can be used at the same time with no issue i just saw it as a strange interaction where the downside of slow fall was removed - that is why i reported it. 

https://wowpedia.fandom.com/wiki/Blink this is the best i could find as in what should blink do - but i can't find anything specific on the interaction between the spells.

**Comment by TheSCREWEDSoftware** [comment]
I can't reproduce this issue in AC or CC PTR, I will see if i get any of the staff to test this in the Live server.

- Make sure you got blink and slow fall learn
- `.additem 17056 20` (reagent needed)
I used the Baelgun's Exacavation in my test as it was high place
- `.tele explorersleague`
- Go east and jump off
- Cast `slow fall` on yourself and let yourself drag a little to the middle of the caynon.
- When you're a little far from the ledge and you're still falling cast `blink`.

This for me just continued slow falling normally and without the proper animation that's it.

**Comment by TheSCREWEDSoftware** [comment]
Can't reproduce this neither in CC
