### ISSUE TITLE
[Spell] Hunter pet ability "Call of the Wild" affects party members

### ISSUE THREAD

**Issue by JanEbbing** [chromiecraft/chromiecraft#6222]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Despite what its tooltip says, casting Call of the Wild puts the buff not only on the hunter and his pet, but also party members.

Screenshot of paladin with the buff: 
![pally_cotw](https://github.com/chromiecraft/chromiecraft/assets/5873110/58b8406d-17e4-4a06-b477-db60addd6853)

![image](https://github.com/chromiecraft/chromiecraft/assets/5873110/dc4243f1-0fc5-40a2-8cc8-173556ad483d)

Link to spell: https://wotlk.evowow.com/?spell=53434 (provided site in template does not have this spell)

### Expected Blizzlike Behaviour

Only the hunter and his pet should gain the CotW buff.

### Source

For example https://www.icy-veins.com/wotlk-classic/marksmanship-hunter-dps-pve-spell-summary#hunter-cooldowns clearly states this (caveat: from wotlk classic). I can get more sources on this if required, every site I would usually check is down however, and wayback machine doesnt have snapshots of what I want...

### Steps to reproduce the problem

1. Join a party with a hunter with a ferocity pet and the CotW talent
2. Stand next to the hunter and have the pet cast CotW
3. Gain CotW buff

### Extra Notes

Me hitting dummy without CotW
![no_cotw](https://github.com/chromiecraft/chromiecraft/assets/5873110/404d4fbf-bde7-4e9c-aba3-e4c03a79fa14)

With CotW (during CotW window)
![with_cotw](https://github.com/chromiecraft/chromiecraft/assets/5873110/e7d50ceb-c530-44af-a287-3e7cec4be81a)

I have no procs aside from the Vengeance talent, and didn't use any seal/spell etc.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, thanks for the report.
