### ISSUE TITLE
[NPC] Crippler walks under the ground

### ISSUE THREAD

**Issue by Wayran-is-typing** [chromiecraft/chromiecraft#6227]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

The Rare NPC Crippler from The Bone Wastes (Terokkar Forest) walks under the ground
![WoWScrnShot_101323_132633](https://github.com/chromiecraft/chromiecraft/assets/74470790/2740c332-7fe3-4de4-a413-79bc5f26a131)
![WoWScrnShot_101323_132637](https://github.com/chromiecraft/chromiecraft/assets/74470790/5f821b05-eb2b-43a6-be54-d8f3da5d7420)
![WoWScrnShot_101323_132618](https://github.com/chromiecraft/chromiecraft/assets/74470790/b537052b-8b4b-4a98-bd60-f71e6ad56625)
![WoWScrnShot_101323_132623](https://github.com/chromiecraft/chromiecraft/assets/74470790/669c6471-ef99-48d1-b97d-6403905a34c2)
![WoWScrnShot_101323_132624](https://github.com/chromiecraft/chromiecraft/assets/74470790/a1a2ed0b-144c-4789-997c-85c693a8fd11)
![WoWScrnShot_101323_132628](https://github.com/chromiecraft/chromiecraft/assets/74470790/55b9e0d4-e6a3-4953-86b7-74cdcb8037a6)

### Expected Blizzlike Behaviour

-

### Source

-

### Steps to reproduce the problem

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
I followed this NPC for his all cycle path but I cannot reproduce this issue anymore.
