### ISSUE TITLE
Incorrect NPC dialogue texts in front of Stormwind & Undercity auction houses - all text dumped at once

### ISSUE THREAD

**Issue by Amrx2** [chromiecraft/chromiecraft#623]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

NPC dialogues all get dumped in chat within a second, instead of it flowing like a normal conversation. Please see attached screenshots for example, all these were posted instantly by the NPC instead of a single line of dialogue dropping every few seconds.
![Samatha Shackleton error](https://user-images.githubusercontent.com/80728005/117892696-1965f580-b2b1-11eb-8484-2b5885ab8a6f.png)
![Stormwind npc](https://user-images.githubusercontent.com/80728005/117892830-4fa37500-b2b1-11eb-864b-27d84176f59c.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC text dialogue should be posted line by line, with each line taking a few seconds each to post to simulate a normal conversation.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Please see attached .npc data in both Undercity (Samantha Shacklton) & Stormwind (Multiple)
![Samatha Shackleton error](https://user-images.githubusercontent.com/80728005/117892674-0eab6080-b2b1-11eb-9e87-1fe23ecfbfb1.png)
 from the NPCs at fault.
2. 
3. 
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
For Samantha Shackleton, see previous ticket https://github.com/chromiecraft/chromiecraft/issues/473

Tried standing next to both sets of mobs with chat timestamps on, and couldn't reproduce this on a vanilla AC server:

Samantha Shackleton (GUID 31864):
![WoWScrnShot_051221_235434](https://user-images.githubusercontent.com/81782124/117991953-ad04f800-b37d-11eb-80fb-20f3ad283077.jpg)

Following Lisan Pierce (GUID 86597) and the other mages:
![WoWScrnShot_051221_235314](https://user-images.githubusercontent.com/81782124/117991988-b726f680-b37d-11eb-9638-24eca8a1ee08.jpg)

In both cases there are appropriate pauses in chat. This makes me wonder if this is issue is something to do with the differences between the live CC server and a fresh vanilla AC server - could any mods be affecting chat?

**Comment by FrancescoBorzi** [comment]
I've seen this being reported by other people on different NPCs, it's probably something generic and not related to a specific NPC.

@Azcobu what version is your local AC?

**Comment by Azcobu** [comment]
My version was rev. 0bc23075bf88 2021-05-12 08:54:12 +0000 when I wrote the above. I do daily updates for testing, so should never be more than 24 hours behind the latest.

**Comment by FrancescoBorzi** [comment]
very strange... this needs further investigation

**Comment by Salehyn** [comment]
As of today this works as intended on the CC PTR. The NPC dialogue flows at discussion speed, forming that wall of text over approximately 1minute. Even disrupting the NPC's speech by engaging in pvp combat does not cause any anomalies. What the bug reporter experienced could be possibly due to lag, either server or clientside.
