### ISSUE TITLE
[SSC] Lady Vashj - Tainted core loot issue

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#6235]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

During Phase 2 of the fight when[ Tainted Elemental](https://wotlk.evowow.com/?npc=22009#drops) dies who can get [Tainted core.](https://wotlk.evowow.com/?item=31088) is dependent on current loot type.
I.E. for Master loot only Master looter can loot it.
For Group loot only the player who owns the corpse can loot it.

For Free For all it has no issues with [Tainted core.](https://wotlk.evowow.com/?item=31088) per se, however leaving this till the very end of the fight can cause some severe drama.

### Expected Blizzlike Behaviour

During Phase 2 of the fight when[ Tainted Elemental](https://wotlk.evowow.com/?npc=22009#drops) dies any raid member should be able to loot [Tainted core.](https://wotlk.evowow.com/?item=31088)

### Source

https://www.icy-veins.com/tbc-classic/lady-vashj-guide-strategy-abilities-loot

### Steps to reproduce the problem

Start the fight
Enter phase 2. 
Kill Tainted Elemental

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

All

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by shaszun** [comment]
I think this was always the case for this boss.

**Comment by elthehablo** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/17997
