### ISSUE TITLE
[NPC] Items with not available proficiency aren't glowing red in Vendors and Inventory

### ISSUE THREAD

**Issue by palimoschnitzel** [chromiecraft/chromiecraft#6237]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

![Screenshot_50](https://github.com/chromiecraft/chromiecraft/assets/93767462/79927e33-577d-4f75-baae-87bd525b1526)
As a 5 lvl shaman, Mail items shouldn't be possible to wear, and so, should be glowing red. But now, they are coloured (and it's name in tooltip too), as If I can wear it (I can't). By the way, item drops from mobs are still red.

### Expected Blizzlike Behaviour

Should be with red overlay and armor type item in tooltip also should be red

### Source

.

### Steps to reproduce the problem

1. Create a low-level cloth- or leather-bearing class
2. Go to armorsmith vendor

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi JustVityok. Thanks for the report. Do you have a source or screenshot for the expected behaviour?

**Comment by heyitsbench** [comment]
[Cannot reproduce](https://github.com/chromiecraft/chromiecraft/assets/38561765/f99c4036-058d-4ea5-996c-437b5b3ffeed) as a level 27 shaman with mail armor proficiency not learned.

**Comment by virgo77** [comment]
Hi! As a BloodElf hunter, I got the same issue. Mail stuff isn't in red, vendors, bags, loots, etc.
I can tell that the weapons are included too. In fact, a young hunter can't use Staff (until learning with a weapon master) and the icon of the loot is not red too.

I don't know if it's relevant, but when I search for players in the 'who' chat tab, I can list all players, whatever the faction they are. Is it a cross faction server? Maybe isn't it because of that?

Thanks
