### ISSUE TITLE
Quest - Creature of the Void (Orgrimmar) - missing chest

### ISSUE THREAD

**Issue by Quenchy** [chromiecraft/chromiecraft#624]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Quest: https://wowgaming.altervista.org/aowow/?quest=1501
Chest: https://wowgaming.altervista.org/aowow/?object=58595

Cannot find this chest in the correct place! It is either not spawning or the respawn timer is ridiculously long.
While waiting for this chest to spawn, at least 10 mins, another player logged in who told me he was waiting as well and logged in 12 times that day to see if it was there.

![WoWScrnShot_051221_004845](https://user-images.githubusercontent.com/36773713/117894662-225cc400-b2bd-11eb-9edf-45f641179083.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The chest should be there.
According to this https://www.wowhead.com/object=58595/burning-blade-stash at coordinates 51.9

See another screenshot here https://www.wowhead.com/quest=1501/creature-of-the-void

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the given coordinates in Durotar

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I have checked it and in my local installation I found the chest and complete the mission without problems:

![WoWScrnShot_051221_125145](https://user-images.githubusercontent.com/82579073/117956087-62ee2900-b321-11eb-9794-2700820871c9.jpg)
![WoWScrnShot_051221_125151](https://user-images.githubusercontent.com/82579073/117956110-671a4680-b321-11eb-82c7-468a25a1bda4.jpg)
![WoWScrnShot_051221_125255](https://user-images.githubusercontent.com/82579073/117956123-68e40a00-b321-11eb-801e-7a740cbd7e99.jpg)
![WoWScrnShot_051221_125303](https://user-images.githubusercontent.com/82579073/117956130-6bdefa80-b321-11eb-839d-e600ac84879d.jpg)

**Comment by Eldarix** [comment]
I have checked it and in my local installation I found the chest and complete the mission without problems:

**Comment by Azcobu** [comment]
Had a look in the DB, the Burning Blade Stash's respawn time is set to 2 seconds. so that looks like it's fine.

**Comment by FrancescoBorzi** [comment]
ok well, then I guess we can close this. If someone still thinks this is bugged, please leave a comment and explain.

Thanks @Azcobu and @Eldarix .

**Comment by MorksFoot** [comment]
Can confirm the chest was not spawning as of last night (05/11/2021) between the hours of 12am-4am server time. Logged back on approximately 5:30pm server time today (05/12/2021) and the chest was spawned.
