### ISSUE TITLE
[SSC[ Coilfang Hate-Screamer silence should be AoE

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#6242]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Coilfang Hate-Screamer ](https://wotlk.evowow.com/?npc=21339) only uses its [silence ](https://wotlk.evowow.com/?spell=38491)on its current target.

### Expected Blizzlike Behaviour

[Coilfang Hate-Screamer ](https://wotlk.evowow.com/?npc=21339) [silence ](https://wotlk.evowow.com/? should be 20 yard aoe for 5 second duration.

### Source

https://wotlk.evowow.com/?spell=38491

### Steps to reproduce the problem

Pull [Coilfang Hate-Screamer](https://wotlk.evowow.com/?npc=21339)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

All

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Please find another source. The site you're linking is a pserver database and is not a valid source.

**Comment by shaszun** [comment]
Source: 
https://www.wowhead.com/tbc/npc=21339/coilfang-hate-screamer#comments;mode:n25

**Comment by IskrenPlashkov** [comment]
As Shaszun pointed. Also seen numerous guides warning about the aoe silence.

**Comment by heyitsbench** [comment]
> As Shaszun pointed. Also seen numerous guides warning about the aoe silence.

I fully believed it was valid, just want to make clear we don't use pservers as sources for changes.

**Comment by InfernalDark** [comment]
Most of your bug reports seems to use that pserver site as "proof". Better use wowhead or similar site.

**Comment by IskrenPlashkov** [comment]
Their database has not been wrong so far when I was referencing possible issues. As there is no official list of acceptable sources imma keep using this unless explicitly requested by server staff.

**Comment by heyitsbench** [comment]
> As there is no official list of acceptable sources imma keep using this unless explicitly requested by server staff.

I am a member of the triaging team, the one that actually takes these issues and confirms them and links them to AC issues. I am telling you not to use this source in the future or your issues may very well not be triaged or closed as they lack a proper source.

**Comment by avarishd** [comment]
It is a cone silence, works as expected.

![WoWScrnShot_111423_200854](https://github.com/chromiecraft/chromiecraft/assets/46330494/97f23517-1572-46be-8744-62ad5c3bac30)
