### ISSUE TITLE
[BRD] Private Rocknot is bugged

### ISSUE THREAD

**Issue by InfernalDark** [chromiecraft/chromiecraft#6251]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

50-59

### Current Behaviour

Completing [Rocknot's Ale](https://www.wowhead.com/wotlk/quest=4295/rocknots-ale) 3 times doesn't start the event to make [Phalanx](https://www.wowhead.com/wotlk/npc=9502/phalanx#comments), who blocks the door, hostile. Rocknot just stands there doing nothing after completing the quest 3 times.

Confirmed with 3 characters. Everything was working just fine a week ago.

### Expected Blizzlike Behaviour

Buy 6 [Dark Iron Ale Mug](https://www.wowhead.com/wotlk/item=11325/dark-iron-ale-mug) from [Plugger Spazzring](https://www.wowhead.com/wotlk/npc=9499/plugger-spazzring).
Complete [Rocknot's Ale](https://www.wowhead.com/wotlk/quest=4295/rocknots-ale) 3 times.
[Rocknot](https://www.wowhead.com/wotlk/npc=9503/private-rocknot#comments) starts wandering around, attacking barrels and when he breaks one, Phalanx turns hostile.

### Source

https://www.wowhead.com/wotlk/npc=9503/private-rocknot#comments

### Steps to reproduce the problem

1. Go to the Grim Guzzler
2. Buy 6 ale's from Spazzring
3. Complete Private's quest 3 times
4. See nothing happening

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Working fine on both ptr and live


https://github.com/chromiecraft/chromiecraft/assets/11332559/86fd01e0-470b-4b5d-a73f-a3315c494a87


https://github.com/chromiecraft/chromiecraft/assets/11332559/da962bcb-a8b8-4adc-91b6-30806d5c1adb
