### ISSUE TITLE
Darkmoon Card: Vengeance

### ISSUE THREAD

**Issue by Sfaccim** [chromiecraft/chromiecraft#6252]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Hello in this post i wanna talk about the really strange and disappointing proc of all dark moon cards the Vengeance card. It Does DMG when u get HITTED by a spell or a melee dmg and it has a 10% CHANCE to proc. Now i know as tank with a lot of dodge pary or block rating the card lose some value but for example ( i done like 20 run to test the card proc ) in a full Shadow Labyrint run as a Warr tank, and by doing IMMENSIVE pulls (like half the room like usual) at the end of the dungeon after doing 1 MILION DMG the card deal a FAIR 5k dmg with 45 procs... dunno if this is legit or a complit disappoint cause the card could be a fantastic card 51 stamina and a usfull aggro dmg for big pulls but its probably a nice dreams of mine... sadge

### Expected Blizzlike Behaviour

Dunno wierd procs

### Source

.

### Steps to reproduce the problem

1 equip the trinket
2 get spanked
3 cry
4 well done u done 200 dmg  after getting hitted for probably more than 50 times

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
Hello, Sfaccim.
I think you need to work a little bit more on your post if you want it to be considered. I read a little bit about it and seems to be optimal trinket for Paladins but not so good for Warriors, despite the plain stamina. In any case, the point of that extra damage is to help a little bit with the aggro, I suppose.
Try to elaborate some more so they can actually have a look on it, a "Dunno wierd procs" doesn't sound enough.

**Comment by balleny** [comment]
duplicate
https://github.com/chromiecraft/chromiecraft/issues/5147
