### ISSUE TITLE
[Event] Headless Horseman is Level 80+

### ISSUE THREAD

**Issue by TimrodDX** [chromiecraft/chromiecraft#6254]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

The Headless Horseman for the Hallow's End event should be level 74 (?? Elite at 70) but is instead level 84, easily told by the fact that a hit-capped 70 is almost incapable of hitting him. 

### Expected Blizzlike Behaviour

Expected behavior would be that the boss is a level 74 elite, as would be the case for all TBC bosses. 

### Source

https://www.wowhead.com/tbc/npc=23682/headless-horseman

### Steps to reproduce the problem

1. Summon the Headless Horseman as a 70 Warlock with a combined 17% hit rating
2. Miss 80% of your casts
3. Wipe and realize something is very off.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> Expected behavior would be that the boss is a level 74 elite [...]

Please provide a source for this. On Wrath, he is level 80 and in your linked source (TBC Wowhead), he's listed as level 70.

**Comment by TimrodDX** [comment]
> > Expected behavior would be that the boss is a level 74 elite [...]
> 
> Please provide a source for this. On Wrath, he is level 80 and in your linked source (TBC Wowhead), he's listed as level 70.

Oh, that should be 70, it didn't occur to me that he was ?? Elite because he was 80, not because he was "Boss" level.

**Comment by mturca** [comment]
> > Expected behavior would be that the boss is a level 74 elite [...]
> 
> Please provide a source for this. On Wrath, he is level 80 and in your linked source (TBC Wowhead), he's listed as level 70.

well it depends on which type of content phase you want to consider this - if you consider it to be wotlk - then yes it's lvl 80 if you want to consider this a tbc phase then the linked source is the correct one - refer to the comment from the linked source :


Highlighted the date

**By chillabis on 2007/10/14 (Patch 2.2.3)**		
Subject: "Re: Headless Horseman"
Headless Horseman is a lvl 70 Elite. He can be summoned during the Hallow's End event in Scarlet Monestery - Graveyard.
Every character can summon him once a day. So my group did this boss 5 times in a row.

For us dropped:

Swift Magic Broom: https://www.wowhead.com/tbc/item=33184
Magic Broom : https://www.wowhead.com/tbc/item=33183
Witching Band : https://www.wowhead.com/tbc/item=34074
Pumpkin Head and some other stuff not shown on the page.

**Comment by heyitsbench** [comment]
Okay, tell me where in that source it says the Horseman is level 74 as the issue author expected.

**Comment by mturca** [comment]
think that was a mistake or typo for lvl 74 what i posted was for either 70 or 80 - that is all i can find

**Comment by heyitsbench** [comment]
> that is all i can find

That is all I could find as well. Hence why I asked for a source on the level being 74. But the issue author has already accepted that it should be 70, therefore I have no issue with the TBCC Wowhead source.

**Comment by mturca** [comment]
lvl 70 now on live CC
