### ISSUE TITLE
[Event]Headless Horseman has no loot 

### ISSUE THREAD

**Issue by mturca** [chromiecraft/chromiecraft#6255]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Headless Horseman has no loot 

### Expected Blizzlike Behaviour

Even if no mount or items the loot table should contain
 https://www.wowhead.com/tbc/item=34068/weighted-jack-o-lantern - is the only reliable way of getting them for the achievment.
 
 Medium chance for :
 
 https://www.wowhead.com/tbc/item=33154/sinister-squashling
 https://www.wowhead.com/tbc/item=33292/hallowed-helm
 
 And a small chance for:
 
 https://www.wowhead.com/tbc/item=33277/tome-of-thomas-thomson

### Source

https://www.wowhead.com/tbc/npc=23682/headless-horseman

### Steps to reproduce the problem

1. Summon headless horsemen
2. Kill it 
3. Loot is empty (after restart)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by mturca** [comment]
This is under assumption that the mount has a very low chance of drop and we just didn't see it so far

**Comment by Nyeriah** [comment]
The mount drops off the daily pumpkin rewarded from the RDF queue, not the boss, therefore isn’t available.

**Comment by InfernalDark** [comment]
Last I heard was that all loot is disabled atm because the boss is lvl 80. Let's wait and see what happens after they fix it.

**Comment by mturca** [comment]
this can be considered solved with the addition of the daily quest
