### ISSUE TITLE
Orgrimmar Grunt saying Barber is out of Cleft of Shadows, while the barber is there.

### ISSUE THREAD

**Issue by Crumen** [chromiecraft/chromiecraft#6259]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

SO when you ask an Orgrimmar Grunt about the barber, it will mention that it moved out of the cleftshadows, just to relocate into the valley of strength, where the "fruit" vendor used to be.

If you go ingame, the barber is in the cleft of shadows, meaning that what the Orgrimmar Grunt is saying, is absolutely wrong, because from my knowledge the barber has always been in the cleft of shadows (I only played from vanilla to wotlk)

Either this, or the Barber shouldn't be there in the first place (but I doubt it)

### Expected Blizzlike Behaviour

I suspect that the Orgrimmar Grunt is supposed to have a different dialogue.
This dialogue seems like to come from... Cataclysm or another wow version, as it makes no sense for a wrath server considering that the barber is in it's appropriate location

On wowhead wotlk, you can see that the NPC location is listed in the Cleft of Shadows.
https://www.wowhead.com/wotlk/npc=29143/bebri-coifcurl

### Source

![Barber](https://github.com/chromiecraft/chromiecraft/assets/96357766/db870d61-bbab-427e-8489-0c074b67eec0)
![Barber 2](https://github.com/chromiecraft/chromiecraft/assets/96357766/57761202-443f-45a2-8000-4daafca75472)

### Steps to reproduce the problem

Go to Orgrimmar and speak to a Grunt.
Read the dialogue.
Go to the cleft of shadows to find the barber.
Contemplate what's wrong.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
The gossip is indeed incorrect That change doesn't happen until Cata (4.0.3a). I just need to find out what he should be saying.

**Comment by heyitsbench** [comment]
> I just need to find out what he should be saying.

I'll grab the text once I'm done with sniffing for Winter Veil. 👍
