### ISSUE TITLE
Defias Rummager in Dustwallow Marsh patrol has her in water / buggy

### ISSUE THREAD

**Issue by ndnd123** [chromiecraft/chromiecraft#626]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

This Defias Rummager mob has a weird patrol that has her going between the ocean and land very rapidly.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

She should be patrolling on land.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  NPC: Defias Rummager in Dustwallow Marsh, DB GUID 31261
2. Position: -2801.146240 -4230.116211 -1.254361
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Couldn't reproduce this, but there's been a few reports recently of wandering NPCs falling through things, and they can never be reproduced on a fresh AC server. However, a fix is being worked on for this class of problem - see https://github.com/azerothcore/azerothcore-wotlk/pull/5778.

![WoWScrnShot_051321_214116](https://user-images.githubusercontent.com/81782124/118124005-2828e580-b434-11eb-9fa3-49be29986e11.jpg)
