### ISSUE TITLE
[T4] Shadow Priest 4 Set bonus is not functioning.

### ISSUE THREAD

**Issue by HasieEST** [chromiecraft/chromiecraft#6270]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

In the current version of AzerothCore Shadow Priest Tier 4 4 set bonus (+5% Damage increase to Mind Flay and Smite) is not functioning properly, as in it doesn't apply 5% buff to Mind Flay. 

Down below there is a screenshot of a fellow Shadow Priest, who has 4 T4 pieces to use. Swaping Chest out non tier piece item has resulted in loss of 1 dmg on Mind Flay on Mind Flay  on near identical spell power mark. (1053 t4 gear set vs 1052 without t4 4 set gearset).  It can be assumed that Mind Flay 4 set bonus without procing any additional spell power modifiers should give roughly 30 damage points more (disregarding futher modification, for example applying Shadow Word: Pain)

![image](https://github.com/chromiecraft/chromiecraft/assets/25981761/fa5fbbff-322c-4ff1-b710-2604fa71ac32)
Tier 4 4set equipped

![image](https://github.com/chromiecraft/chromiecraft/assets/25981761/2c0167dd-199f-402b-83d3-cc4ed27d0f9d)
Tier 4 3 set + SpellFire robes equipped.

`https://drive.google.com/file/d/1zqurdy5ky64KiCMRgtVsmbPTSWHmbFMf/view` - Without Tier 4
`https://drive.google.com/file/d/1nNL0hgCytTMdxjl2ZBamvi-Mkmt91e-z/view` - With Tier 4

### Expected Blizzlike Behaviour

DPS Priest tier 4 4 set bonus should apply 5% dmg buff to Smite and Mind Flay, similarly to talents that amplify specified spell(s) i.e Improved Shadow Word: Pain, Misery etc.

### Source

https://www.wowhead.com/wotlk/spell=37571/improved-mind-flay-and-smite#modifies

### Steps to reproduce the problem

Assemble 2 gear sets with almost identical spellpower -> one with tier 4 4 set bonus "enabled" and one without. 
If possible, try to avoid using glyph of shadow and spirit tap talent to reduce void ticks due to procs (think of increased spirit or better coefficiency for spirit to spell power).
Apply Mind Flay to gain 5 stacks of shadow (if taken) and observe values.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, thanks!
