### ISSUE TITLE
Orgrimmar Warlock Trainers speak in alliance language when horde players interact with them

### ISSUE THREAD

**Issue by Crumen** [chromiecraft/chromiecraft#6276]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

When you talk to the three warlock trainers in Orgrimmar, Mirket, Grol'Dar, Zevrost, their text is in what appears to be Common, or any of the other non-horde languages, meaning that horde players cannot understand what these three orc says.

This bug has already been spotted in Undercity, where a paladin trainer spoke in the same way to horde players.

### Expected Blizzlike Behaviour

Their text should be understandable to horde players, as they are orcs, and orcs don't go around speaking in alliance languages to their fellow friends
![WoWScrnShot_102423_155227](https://github.com/chromiecraft/chromiecraft/assets/96357766/da789c8e-7152-431d-813e-7fc1dc3c9a22)
.
![WoWScrnShot_102323_155424](https://github.com/chromiecraft/chromiecraft/assets/96357766/59d173e4-4884-48e3-9273-cd102296af5c)
![WoWScrnShot_102423_155208](https://github.com/chromiecraft/chromiecraft/assets/96357766/4605af3e-322f-486f-8ab5-c3adfc73b2cb)

### Source

Their dialogues.

### Steps to reproduce the problem

1. Go to Orgrimmar as a horde character (I tested it as a blood elf mage)
2. Talk to them
3. See gibberish instead of proper words

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/1212

This bug is related.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/22766827f90a713cb2f105d5cc59861dce67ac77

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi Crumen. Thanks for the report. I can confirm Zevrost, Mirket, and Grol'dar are speaking some laguage other than orcish to non warlocks. For warlocks you can read the dialog but is the incorrect gossip.
