### ISSUE TITLE
[Shadowlabs] Murmur sonic boom delay

### ISSUE THREAD

**Issue by realbluerabit** [chromiecraft/chromiecraft#6277]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Issue with Murmur's sonic boom ability.
There is a long (several seconds) delay between the end of the sonic boom casting and the actual sonic boom for at least the first sonic boom on heroic shadowlabs.  We experienced this issue twice, the first time it caused a wipe, the second we were prepared for it and waited it out.  The second sonic boom seemed to work correctly on our second attempt.

this delay was not there several days ago so it is a new issue.

### Expected Blizzlike Behaviour

No delay between end of casting and the aoe dmg/effect of murmur's sonic boom

### Source

I am not 100% sure how to fill in this field.
This is a youtube video of a murmur kill, i think it is TBC classic but not certain.
In the video you can see that the player are able to return to mumur right after sonic boom casting is done.  If we try on CC at the moment, we get hit by the sonic boom a few seconds later.
https://www.youtube.com/watch?v=vZhtT03c9FI

### Steps to reproduce the problem

Run heroic shadow labs
Engage murmur
Observe first sonic boom timing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/22766827f90a713cb2f105d5cc59861dce67ac77

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Manuel91CC** [comment]
Not confirmed, Sonic Boom does not have any delay. Already fixed probably. Thank you anyway for your report.
