### ISSUE TITLE
"Shadow and Flame" Talent not working properly

### ISSUE THREAD

**Issue by Wosser** [chromiecraft/chromiecraft#6279]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

It seems like the talent just increases the spelldamage coefficient by 20%, so 0.857*1.2=1.03 for sShadow Bolt and 0,714*1.2=0,857 for Incinerate.

### Expected Blizzlike Behaviour

The bonus should be additive, not multiplikative, so 0.857+0.2=1.057 for Shadow Bolt and 0.714+0.2=0.914 for Incinerate.

### Source

https://www.wowhead.com/wotlk/spell=30292/shadow-and-flame#comments see comments.
The 5 ranks: https://wowgaming.altervista.org/aowow/?search=shadow+and+flame#talents

### Steps to reproduce the problem

Tested with 5 points into it, with 1300 Spellpower Rank 11 shadowbolt should do at least 544+1300*1.057=**1918** damage, but does generally less.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/22766827f90a713cb2f105d5cc59861dce67ac77

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
>This talent increases spell damage coefficient by 20%, that means multiplicative, not a flat 20%. The coefficient of Incinerate is 71.42%, with this talent it increases to 71.42% * 1.2 = 85.71%
It's NOT 91.42%. It might have been that case before, but if so, it's changed now.
This was tested and confirmed in 3.1.1.

https://www.wowhead.com/wotlk/spell=30292/shadow-and-flame#comments:id=710320
