### ISSUE TITLE
Bugged Heal inside Rdf

### ISSUE THREAD

**Issue by Sfaccim** [chromiecraft/chromiecraft#6288]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Inside the Random Dungeon Finder Heroic and standard i saw that all the healer im queued with they heal me by half of the corect amount. for example if they heal me outside the dungeon , so basically around the world at shattra orgri stormwind etc, they will heal me basically they cure me of double the amount of cures cast in the dungeon. is it me or inside the rdf the healers are nerfed? also why im the only 1 affected? and yes inside the rdf if they heal me they will heal me by half BUT if they heal someone else thats not me ( the tank) it will get double the amount i receive....  why?

### Expected Blizzlike Behaviour

Heal shouldnt be cutted by half of their magical power i guess since they heal half of what should they do

### Source

wtlk 3.3.5

### Steps to reproduce the problem

queue as tank with my account
try a rdf heroic
ask a healer some heals
then ask him to heal u and then someonelse
compare the cure

### Extra Notes

am i cursed? o.O

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/41dba1affbb5a24457a894bf3d503f4aa6303a1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by shaszun** [comment]
Normally raids and maybe heroics have reduced healing to tune and balance the content, because of wrath gear stats and talents. What might happened is either you have some bug with WB healing reduction, it happened in the past or something similar. I would suggest you to write a ticket in discord to the staff.

**Comment by Stump876** [comment]
Hi Sfaccim. Thanks for the report. This is indeed intended as part of the progression system as shaszun said. This tuning has since been removed. So this should not be an issue any longer.
