### ISSUE TITLE
[AH] Searching by rarity only shown different results than category+rarity

### ISSUE THREAD

**Issue by lovelord83** [chromiecraft/chromiecraft#629]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If you search AH for ALL items of a specific "rarity" , using "rarity" filter you obtain A LOT less results than searching ALL items of a specific "category" + "rarity"

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If you search for "rarity" only filter you should get ALL items with that rarity in list, not bunch of items.
Think what this means for sellers: not present items in list = less opportunity to sell that item!

##### STEPS TO REPRODUCE THE PROBLEM:

Example:

Reset filters > select "Epic" > press "Search" (example: 4 "Fiery war axe" are present)
Reset filters > select category "Weapons" > select rarity "Epic" > press "Search" (got 7 "Fiery war axe")

##### EXTRA NOTES:

Here you can see I'm selling a "Fiery war axe" (got it in my Auctions tab) but searching by rarity it doesn't shown
![image](https://user-images.githubusercontent.com/18720065/117947262-51505580-b310-11eb-8729-edc5facbb5c1.png)

It is present searching for category + rarity filters
![image](https://user-images.githubusercontent.com/18720065/117947387-6fb65100-b310-11eb-9129-bc9eab1e64cd.png)

NOTE: always shown if you search by name, using or not other filters.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
Did you go through all **pages** in your first example? My guess the following actually happened:
* Your auction just wasn't shown on the first page, because the **epic** filter alone did produce more than one page in the response
* When you further restricted your search to **epic axes** the response consisted of a single page and your auction was shown, too.

If this is what happened, then there is no bug. Working as intended.

**Comment by lovelord83** [comment]
So, let'me understand. AH got pagination, and this is clear and work as intended, but maybe is the default sorting the problem?

Doesn't it group up by item name, does it? Or which mechanics is in use as default sorting priority? iLevel, item name, time left? this seems weird. I think correct sorting (by default) should group all items by name, in any case using a descending order like this:

iLevel (group by name, than time left)
Item name (group time left, than bid offer value)

in this way you can guarantee that any items present in any page, are sorted correctly and not spread in different pages (if you're not searching a specific item name, this is clear. But this method could be applied even to direct item name search I suppose). 

What do you think about this? In my honest opinion is a smarter sorting method than this, but tell me what's yours.

**Comment by necropola** [comment]
I understand this as "yes, this is what happened, but I wish the AH would work differently". Right?

**Comment by lovelord83** [comment]
LoL , reductive, but yes. My interaction about this issue is more than that, but I understand what you're doing.

**Comment by lovelord83** [comment]
Thanks anyway @necropola
