### ISSUE TITLE
[Textures] Stormwind AH stairs - Incorrect textures causes character to turn invisible or fall under the floor

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#6293]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Well, this is a weird one.
I have noticed since very long –and I am sure many other players have seen this– that there is an unusual gap at the lowest part of the steps going to the Auction House in Stormwind. 
![ 2023-10-30 a las 22 39 58](https://github.com/chromiecraft/chromiecraft/assets/77953030/3054796d-ad40-417f-999c-8603910a7bc4)

When approached from the front, our character simply goes over the steps and enters the building. However, accessing from the side of the stairs can make our character disappear.
It's pretty easy to replicate, simply nudge your way from the side with the big gap and you will see how the character bugs in a space that is not really UNDER the textures but also not on top. 
![ 2023-10-30 a las 22 28 16](https://github.com/chromiecraft/chromiecraft/assets/77953030/071545b6-5765-4e65-8df7-a933341160ae)
![ 2023-10-30 a las 22 28 20](https://github.com/chromiecraft/chromiecraft/assets/77953030/a4c2235d-990b-4d08-b1bb-8ec4265fabcb)

Speaking with /s shows the text on the chat box, but it doesn't show the "speaking bubble" floating in place. When "invisible", we can still jump and our shadow will be projected on the floor (since we are not under it), but our character will remain invisible. On the following image you can see my shadow projected right under the sitting gnome.
![ 2023-10-30 a las 22 30 30](https://github.com/chromiecraft/chromiecraft/assets/77953030/d5133329-9879-40fb-aff7-b3b8e0821040)

Eventually, after a while of fidgeting around I found myself falling under the floor of the city.
![ 2023-10-30 a las 22 45 36](https://github.com/chromiecraft/chromiecraft/assets/77953030/65ae2a34-79c4-4837-b1ef-8244aa678ecf)

### Expected Blizzlike Behaviour

Having a complete texture under the last step of the stairs would probably fix the issue.
Characters should not become invisible or bug between textures.

### Source

Common sense.

### Steps to reproduce the problem

Get a character at AH stairs in Stormwind [61.7, 70.0]
Move slowly across the gap at the bottom
Watch your character disappear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/41dba1affbb5a24457a894bf3d503f4aa6303a1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
I'm quite confident this is an issue with your HD patch, and not something that can be fixed on the side of AC/CC.

**Comment by Rorschach91** [comment]
> I'm quite confident this is an issue with your HD patch, and not something that can be fixed on the side of AC/CC.

No, it isn't. I tested this issue with the old wotlk client and this bug is also present with it.
But I don't know if this bug was also present in offical servers (I always played horde XD).
In any case It could be nice a second opinion.

[Youtube Video](https://youtu.be/skf3WH453VU)

**Comment by heyitsbench** [comment]
In that case, it's 100% a client bug, thank you for correcting me on that. 😛
