### ISSUE TITLE
Karazhan - One of Moroes adds pulling and not the others

### ISSUE THREAD

**Issue by siorse** [chromiecraft/chromiecraft#6296]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Seems to happen when paladins use their range shield thing on trash then hits a moroes add, but not moroes himself

can see in pic where adds are pulled but not him

[https://cdn.discordapp.com/attachments/1169292226304671864/1169293434411040768/moroes2.png?ex=6554e05f&is=65426b5f&hm=f6c910378582c3ebf5d5cbe1ad27f7aaa0b5a8671d795a90f78f04204cc4129c&](url)

### Expected Blizzlike Behaviour

If one of his adds pulls, the boss and his other adds should also pull

### Source

unsure how to source this? generally any other time you pull an add of his, the whole encounter pulls

### Steps to reproduce the problem

paladin using their range shield thing on trash then hits a moroes add, but not moroes himself, pulling the add but no one else

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/41dba1affbb5a24457a894bf3d503f4aa6303a1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
The shield not bouncing to the summoner has been reported [here](https://github.com/azerothcore/azerothcore-wotlk/issues/17015), but Moroes and his adds not being linked definitely seems to be a new report.

**Comment by avarishd** [comment]
Couldn't reproduce with or without avenger's shield. Tried every add, always pulled everything.
Reopen if it happens again
