### ISSUE TITLE
Seer's Linked Spaulders cannot be trasmogrifed

### ISSUE THREAD

**Issue by unitscan** [chromiecraft/chromiecraft#6297]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Seer's Linked Spaulders (https://www.wowhead.com/wotlk/item=35385/seers-linked-spaulders) doesn't appears on the trasmog shoulders slot list.
Of course, I have all the requirements to wear this item: I had this item inside my bag, my class is shaman, and I am honored with Cenarion Expedition.

### Expected Blizzlike Behaviour

.

### Source

AzerothCore

### Steps to reproduce the problem

1. Go to [Fedryen Swiftspear](https://www.wowhead.com/wotlk/npc=17904/fedryen-swiftspear) on Cenarion Refuge in Zangarmarsh;
2. Buy Seer's Linked Spaulders;
3. See if appears on the trasmog shoulders slot list. 

### Extra Notes

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/41dba1affbb5a24457a894bf3d503f4aa6303a1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None
Tansmog NPC

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
They appear on my trasmog list. If it is a personal problem I don't know how to help you.
![Desktop Screenshot 2024 09 16 - 10 35 37 69](https://github.com/user-attachments/assets/53379f74-d6ae-4545-9997-dc19fd4f7567)

I close this report. Thank you anyway.
