### ISSUE TITLE
Pumpkins at Solliden Farmstead in tristfall have incorrect spawn time for 3.3.5

### ISSUE THREAD

**Issue by Istox** [chromiecraft/chromiecraft#63]
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
Pumpkins at Solliden Farmstead in tristfall have incorrect spawn time for 3.3.5. They spawn after 10+ minutes currently

**|======MODERATION EDIT Strart======|**
GameObject: [Tirisfal Pumpkin](https://wotlkdb.com/?object=375) at **Solliden Farmstead** in [Tirisfal Glades](https://wotlkdb.com/?zone=85) I think it has a wrong respawn time for 3.3.5a, because their respawn time is after 10+ minutes currently and I suppose it should be less than 10 minutes.

**[Note]:** _This is the minimum requirement to make a well done report. Then, if you wish to enter "More Details". **you could add**:_

This GameObject in question is used to complete:
Quest: [Fields of Grief](https://wotlkdb.com/?quest=365)
The Quest requires you to loot 10 [Pumpkins ](https://wotlkdb.com/?item=2846) from [Tirisfal Pumpkin](https://wotlkdb.com/?object=375)
The Quest can be taken and delivered by:
**NPC_Start:** [Deathguard Simmer](https://wotlkdb.com/?npc=1519)
**NPC_End:** [Apothecary Johaan](https://wotlkdb.com/?npc=1518)
**|======MODERATION EDIT End======|**

##### EXPECTED BLIZZLIKE BEHAVIOUR:
I believe these have 3-5 minute spawn time in wrath, but certainly its not 10.

**|======MODERATION EDIT Strart======|**
I assume (because I don't know for sure), that the Respawn Time of this Game Object should be around 5 minutes.

**|======MODERATION EDIT End======|**

##### CURRENT BEHAVIOUR:
10+ minute spawn, too long.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Fields of Grief
2. Loot some pumpkins
3. 

**|======MODERATION EDIT Strart======|**
1. Go to [Tirisfal Glades](https://wotlkdb.com/?zone=85) **Solliden Farmstead** Area
2. Take the Quest: [Fields of Grief](https://wotlkdb.com/?quest=365) From: **NPC_Start:** [Deathguard Simmer](https://wotlkdb.com/?npc=1519)
3. Loot some pumpkins 
4. And wait for its respawn.

**|======MODERATION EDIT End======|**

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
The Respawn Time is right, is 5min.
indeed, we should probably raise it to 24min. **(but I'm not sure about it).**
There is a difference between "Respawn Time" and "Despawn Time" they aren't the same thing..
This is the **Video** of my **Test**: [Farmer Solliden](https://youtu.be/Jp_b-ZAX5ns)

**Comment by nicoaravena** [comment]
> The Respawn Time is right, is 5min.
> indeed, we should probably raise it to 24min. **(but I'm not sure about it).**

The time is right, as far as I know and readed in forums, the time is near to 5 mins since TBC, they reduced it to a couple of minutes in Cata.

**Comment by Istox** [comment]
@Stifler82 My report had absolutely nothing to do with Farmer Solliden.. :/

**Comment by Stifler82** [comment]
> @Stifler82 My report had absolutely nothing to do with Farmer Solliden.. :/

@Istox
Ok, can you explain better your issue, trying to explain in order:
What your issus
What kind of issue is it, which a NPC, G.OBJ, ITEM, Quest, and maybe you could trying to take some link from WoWHead or something like that? pls..

**Comment by Istox** [comment]
Its all in the original discription mate. Fields of Grief - quest

**Comment by nicoaravena** [comment]
Actual version of AC is using time as 700secs for respawn of the tirisfal pumpkin. But I don't remember were I red that this is not so far from retail, and after cata they reduced to a few minutes. So if you find some more information I think it apply as an issue.

**Comment by Stifler82** [comment]
@Istox 
I gave you an example of how you should have reported
**(Of course, without the moderation frame)**

Anyway, **I haven't been able** to find **"Official Information"** regarding the **respawn time of this Game Object**, so I can't tell you if you're right or not.

With a little common sense, I could tell you that you are right.
In that, a respawn time of 10+ minutes (to be exact they are 11min and 30 sec) seems a bit excessive and that 5min of time seems a reasonable respawn to me..
