### ISSUE TITLE
[T4] Prot Warrior Set - Four Item Set Bonus Doesn't Work

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#6300]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

4p set bonus only works for heroic strike/cleave

### Expected Blizzlike Behaviour

4p set bonus should work for every warriors damaging skill

### Source

"Your Revenge ability causes your next damaging ability to do 10% more damage."

### Steps to reproduce the problem

1. Use any damage skill after revenge 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Next time please mention which spells are not working, in this case it's only shield slam.

**Comment by avarishd** [comment]
@heyitsbench Is it possible for this to be tested in recycled?
Concussion Blow, Rend (unlikely, but you never know), Heroic Throw, Devastate/Shield Slam (wowhead comments say it works with them), Shockwave and Shattering Throw.

**Comment by heyitsbench** [comment]
> Is it possible for this to be tested in recycled?

It would be incredibly difficult for me to obtain the pieces required, as older raids (e.g. Magtheridon/Gruul) are not easy to solo nor to find groups for on Classic.

**Comment by avarishd** [comment]
Wait, there are no vendors for stuff like that on the ptr? lmao

Guess I'll follow the tooltip and add the listed stuff (without rend).

**Comment by Plasmashield** [comment]
> Can partially confirm (need more info), next time please mention which spells are not working.

I have no idea. I did a short test - It worked only for heroic strike/cleave. Didn't work for shield slam, deva, shockwave. Tooltip says it should work for every damaging ability. Devs can open the code and see which abilities are added and which are not otherwise it's just dumb to test everything from players side **in this case**
