### ISSUE TITLE
Mount not learned when used

### ISSUE THREAD

**Issue by Raulfin** [chromiecraft/chromiecraft#6304]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Purchased Riding @20 and Pinto Bridal, got the Giddy Up! achievement, used the mount, but it wasn't added to collection and Stable Keeper achievement shows 0/10.

### Expected Blizzlike Behaviour

Using a mount item adds the mount to the collection.

### Source

https://www.wowhead.com/wotlk/quest=14079/learn-to-ride-in-elwynn-forest
https://www.wowhead.com/wotlk/npc=4732/randal-hunter
https://www.wowhead.com/wotlk/npc=384/katie-hunter
https://www.wowhead.com/wotlk/item=2414/pinto-bridle

### Steps to reproduce the problem

As a lvl20 Human priest, took 'Learn to Ride in Elwynn Forest' (14079) quest item from mail.
Join RDF
Ran to Randal Hunter (4732) to turn in, and train riding.
RDF pops
Purchased Pinto Bridal (2414) from Katie Hunter (384).
Used item from bag.
Item is consumed.
Mount is not added to collection.
accept RDF invite, run dungeon, notice can't mount.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Win 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Raulfin** [comment]
didn't notice till after dungeon, so couldn't screenshot chat log, and tried to relog, and disabe all addons.

**Comment by Kitzunu** [comment]
Cannot reproduce
