### ISSUE TITLE
Ending Their World

### ISSUE THREAD

**Issue by Raulfin** [chromiecraft/chromiecraft#6305]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Ending Their World (9759) does not unlock after completing What We Know... (9753). It seems that Clearing the Way (9761) is currently a pre-req, but the 2 quests are meant to be done at the same time.

### Expected Blizzlike Behaviour

Ending Their World (9759) should unlock after completing What We Know... (9753). 

### Source

https://www.wowhead.com/wotlk/quest=9759/ending-their-world
https://wowwiki-archive.fandom.com/wiki/Quest:Ending_Their_World

### Steps to reproduce the problem

Reach level 18
Complete What We Know...
Ending Their World is not available

### Extra Notes

This is a side-quest/strand to reward Draenei with unique ring and tabard. Can upload a screenshot from classic in a few days showing both quests active.

What We Know... > What We Don't Know... > Vindicator's Rest > Clearing the Way
v
Ending Their World > The Unwritten Prophecy

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Raulfin** [comment]
Leveled a Draenei on classic to check and Ending Their World unlocks after What We Don't Know..., and is available when going to turn in Vindicator's Rest.

After turning in What We Know, the quest is not there.
![ShareX_7Qycue96b1](https://github.com/chromiecraft/chromiecraft/assets/7994405/8c3bb187-079e-4b55-b821-5ddfef2a9dac)

After turning in What We Don't Know, it is.
![WowClassic_moQfFXz1ax](https://github.com/chromiecraft/chromiecraft/assets/7994405/7eb2fe02-b7d4-4e1b-bd73-07c79fd20e86)

Both quests in the log together
![WowClassic_FHD8vfeaSc](https://github.com/chromiecraft/chromiecraft/assets/7994405/eb4fdf58-c77e-49cf-806b-571e8ebf2e3b)

**Comment by Stump876** [comment]
Hi Raulfin. Thanks for the report. Nicely done! You even verified proper behavior on classic. You're making my job easy. I've also confirmed this behavior on my local AC.

**Comment by heyitsbench** [comment]
Fixed with https://github.com/azerothcore/azerothcore-wotlk/commit/d3136c2745c7310505c791012adcb11ef25dde27.
