### ISSUE TITLE
[Mob] The Kurken (White Corehound) small after taming as hunter pet

### ISSUE THREAD

**Issue by MurderGizmo2013** [chromiecraft/chromiecraft#6309]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

On a level 60 hunter with Beast Mastery talent, traveling to Azuremyst Isle to tame The Kurken (50.0, 12.8, npc=17447) results in the new pet model being smaller than it should.

### Expected Blizzlike Behaviour

The pet should remain about as tall as the blood elf character models while still slightly smaller than original size.

### Source
The Kurken lv. 12 NPC database:
https://www.wowhead.com/wotlk/pet=45/core-hound
https://wowgaming.altervista.org/aowow/?npc=17447#.

![image](https://github.com/chromiecraft/chromiecraft/assets/26947458/df76f9bc-1f8d-41c2-bbb2-84ae9e378cc7)
The current size of the pet model

![image](https://github.com/chromiecraft/chromiecraft/assets/26947458/71ec4642-1a88-40a6-beac-8649871d3ae6)
https://www.youtube.com/watch?v=lDJQSQHA9dA This image and video demonstrates the white glowing effects correctly lining up with the size of the proposed larger model.

### Steps to reproduce the problem

1. Be lvl 60+ Hunter with Beast Mastery Talent, allowing you to tame exotic beasts.
2. Travel to the cave at the Furbolg camp on northern Azuremyst Isle (50.0 12.8)
3. Use Tame Beast on The Kurken named mob
4. Successfully finish the channel
5. The pet is now noticeably smaller than intended 

### Extra Notes

![image](https://github.com/chromiecraft/chromiecraft/assets/26947458/b25c9a86-23a5-4699-b578-3ebe9a3c17ac)   
![image](https://github.com/chromiecraft/chromiecraft/assets/26947458/1d1a33bb-ee1f-43e8-8b7b-a40b4559042f)

A tamed gorilla from Stranglethorn Vale for reference vs playermodel

I am aware of [this report](https://github.com/azerothcore/azerothcore-wotlk/issues/14488), and other exotic pets such as the devilsaur and worms from silithus appear normally, this specific mob does not. I apologize if this is considered a duplicate thread or if I am meant to add/contribute to the other thread.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Windows 11 Home 64-bit (10.0, Build 22621)

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/18867
