### ISSUE TITLE
Dying in certain areas in EPL results in being sent to Acherus Graveyard

### ISSUE THREAD

**Issue by xrenari** [chromiecraft/chromiecraft#631]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Dying in approximately this spot brings you to the spirit healer in Acherus. There is no way to rez without spirit healing. 

Abuse case for hunters is ability to buy level 40-65 bullets in vicinity of EPL, saving time while farming.
Abuse case for plate wearers is being able to buy white-quality armor. It is not 'good', but is otherwise inaccessible in current bracket.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only DKs can access this zone, as stated by this comment on WoWhead:
![image](https://user-images.githubusercontent.com/83146715/118029311-08a99400-b332-11eb-84a9-a3a601292319.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Die in approximately this location: 
![image](https://user-images.githubusercontent.com/83146715/118029513-3e4e7d00-b332-11eb-90cf-56470ec0768c.png)
2. Release and your spirit should be in Acherus.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by JamesGent** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5815
