### ISSUE TITLE
[Mob] Galvanoth's War Stomp has smaller effective range than it should

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#6313]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Elite mob Galvanoth (https://wowgaming.altervista.org/aowow/?npc=22281), which can be randomly spawned by the gossip option at Fel Crystal Prism (https://wowgaming.altervista.org/aowow/?object=185927) in Blade's Edge Mountains, has the ability War Stomp (https://wowgaming.altervista.org/aowow/?spell=38750). It should be affecting all mob's hostile targets within 10 yards, although right now its effective range is at or below 5 yards and can be easily avoided, trivializing the fight.
![Przechwytywanie](https://github.com/chromiecraft/chromiecraft/assets/71841180/126096ca-d163-4585-b7f4-b6473323733a)
![Przechwytywanie2](https://github.com/chromiecraft/chromiecraft/assets/71841180/81760a0f-8ec9-44b9-92b5-2dbf19b64017)

### Expected Blizzlike Behaviour

Galvanoth's War Stomp should be knocking back, interrupting casts, and dealing damage to all hostile targets within 10 yards of the mob.

### Source

https://www.wowhead.com/wotlk/npc=22281/galvanoth
https://www.wowhead.com/wotlk/spell=38750/war-stomp

### Steps to reproduce the problem

1. Go to Blade's Edge Mountains zone that features Fel Crytal Prism (at one of the following coords 31.7 39.3 | 33.9 44.2 | 35.6 36.8 | 37.7 41.4 | 26.8 83.6 | 27.1 75.5 | 30.2 77.1 | 31.1 86.5)
2. Prepare at least 350 Apexi Shards (https://wowgaming.altervista.org/aowow/?item=32569) in bags 
3. By using the gossip option at Fel Crystal Prism, try to summon Galvanoth
4. If Galvanoth has been successfully summoned, melee him from the maximum possible distance without moving him (at the edge of the circle for the target, around 6 yards for the center of the model)
5. Wait until War Stomp is being cast
6. Observe the effects of War Stomp

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
@Hihilist thanks for your report.
I used this version https://github.com/azerothcore/azerothcore-wotlk/commit/bf18b9bdfb26fd94cd4dfbd6a911ebae5db98569
From a distance of 10yards, I got knocked back from the stomp spell, my spell got interrupted, and I got damaged.
I cannot reproduce your described issue. 
If you still encounter it, please add a comment, so we can test it further.
