### ISSUE TITLE
Death by fall damage when riding over a smal root

### ISSUE THREAD

**Issue by crazy2d** [chromiecraft/chromiecraft#6315]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Rode Dreadstread over the root in the picture. and died instantly. no falling trough the earth. rode from north to south

### Expected Blizzlike Behaviour

Not die on flat ground

### Source

![WoWScrnShot_111223_004805](https://github.com/chromiecraft/chromiecraft/assets/127353829/baaf6337-5130-4171-b03f-0e8b686ce7d9)
![WoWScrnShot_111223_005308](https://github.com/chromiecraft/chromiecraft/assets/127353829/7ca124ad-ec43-4cc3-ba9c-412e197febaa)

### Steps to reproduce the problem

I do not know

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hi crazy2d. Thanks fot the report. I tried to reproduce this and couldn't. I ran over it a bunch of timest, back and forth, mounted, running, walking with mo dmage. Unfortunately if it can;t be reprodcues we can't know what to fix. I'm going to make it as "cannot reproduce" for now. If someone has any additional info we can always reopen it.

If anyone else would like to try, the command `.go xyz 6468.503418 -1717.264648 508.984009` will put you in the spot pictured above,
