### ISSUE TITLE
[Mob] Obsidia has '$r' reference instead of its summoner's race text

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#6318]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Elite mob Obsidia (https://wowgaming.altervista.org/aowow/?npc=23282), which spawns from the gossip option at Obsidia's Egg (https://wowgaming.altervista.org/aowow/?object=185932) in Blade's Edge Mountains, has scripted yell dialogue on a spawn that does include '$r' reference.
![WoWScrnShot_111223_135509](https://github.com/chromiecraft/chromiecraft/assets/71841180/5e49b97b-555f-446d-b0f1-e3bb800516cb)

### Expected Blizzlike Behaviour

Obsidia's scripted yell dialogue on spawn should refer to its summoner's race in the text.

### Source

https://wowgaming.altervista.org/aowow/?npc=23282

### Steps to reproduce the problem

1. Go to Blade's Edge Mountains zone that features Obsidia's Egg (coords 33.9 54.8)
2. Prepare 35 Apexi Shards (https://wowgaming.altervista.org/aowow/?item=32569) in bags 
3. By using the gossip option at Obsidia's Egg, summon Obisida
4. Pay attention to the chat and yell dialogue from Obsidia during her spawning

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Can confirm, thanks.
