### ISSUE TITLE
Dustwallow Marsh: Firemane mobs not consistently dropping leather

### ISSUE THREAD

**Issue by Jinmcx** [chromiecraft/chromiecraft#632]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Firemane Scout, Scalebane, Flame Caller, and Ash Tail are not consistently dropping leather.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should always be a leather drop.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill a Firemane mob
2. Skin

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Jinmcx** [comment]
<img width="621" alt="1" src="https://user-images.githubusercontent.com/19652090/118037510-cd539900-b322-11eb-8f30-872db2bb7931.PNG">
<img width="624" alt="2" src="https://user-images.githubusercontent.com/19652090/118037518-d04e8980-b322-11eb-97f1-f584ad8eacf1.PNG">

**Comment by Eldarix** [comment]
Can you add in which zone are the mentioned mobs?

**Comment by Jinmcx** [comment]
<img width="301" alt="specific" src="https://user-images.githubusercontent.com/19652090/118097406-7e8c1a80-b387-11eb-9885-2bfe42388410.PNG">
The firemane mobs are mainly in this area. I listed them aboved.

**Comment by Eldarix** [comment]
Thanks ;)
