### ISSUE TITLE
[Item] 'Bag of Fishing Treasures' may have incorrect drop chance values for its content

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#6325]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Item 'Bag of Fishing Treasures' (https://wowgaming.altervista.org/aowow/?item=34863) which is a reward from 4 (out of 5) Fishing Daily quests in Outland at NPC 'Old Man Barlo' (https://wowgaming.altervista.org/aowow/?npc=25580) has certain loot pool with set drop chance value for particular items.
When comparing the drop values from TBC versus what is suggested in the Wowgaming database, there are visible discrepancies and now the item has a much lower chance of giving better loot than in TBC.

Moreover, during a manual test of 1000 tries to verify the chance of getting possible items, the following results have been noted (please note that some items can drop in higher quantity per opening so the average amount was used to calculate percentages):

| **Item** | **Received amount** | **CC drop chance value** | **TBC drop chance value** |
| --- | ---: |  ---: | ---: |
| Sharpened Fish Hook | 3675 | 73,5% | 73,6% |
| Elixir of Water Walking | 677 | 27,1% | 24,1% |
| Salvaged Scrap Metal | 167 | 8,4% | 11,5% |
| Razor Sharp Fillet Knife | 70 | 7,0% | 11,4% |
| Rusted Lock | 59 | 5,9% | 11,2% |
| Giant Shark Tooth | 62 | 6,2% | 11,1% |
| Broken Spyglass | 66 | 6,6% | 10,9% |
| Jaggal Pearl | 182 | 9,1% | 10,2% |
| Piece of Polished Driftwood | 66 | 6,6% | 9,4% |
| Recipe: Captain Rumsey's Lager | 0 | 0,0% | 8,8% |
| Mote of Water | 207 | 8,3% | 8,8% |
| Shadow Pearl | 19 | 1,9% | 3,1% |
| Weather-Beaten Journal | 0 | 0,0% | 2,4% |
| Beautiful Glass Eye | 12 | 1,2% | 1,8% |
| Silver Statuette | 6 | 0,6% | 1,8% |
| Ancient Coin | 13 | 1,3% | 1,7% |
| Spun Truesilver Fishing Line | 2 | 0,2% | 1,5% |
| Antique Silver Cufflinks | 9 | 0,9% | 1,4% |
| Mithril Shaving Razor | 7 | 0,7% | 1,4% |
| Noble's Monocle| 8 | 0,8% | 1,4% |
| Eye of the Sea | 0 | 0,0% | 1,4% |
| Gold Wedding Band | 5 | 0,5% | 0,9% |
| Mariner's Log | 5 | 0,5% | 0,9% |
| Ornate Drinking Stein | 5 | 0,5% | 0,6% |
| Weather-Beaten Fishing Hat | 3 | 0,3% | 0,4% |
| The 2 Ring | 0 | 0,0% | 0,1% |

### Expected Blizzlike Behaviour

'Bag of Fishing Treasures" has proper drop chance values for its possible loot.

### Source

https://wowwiki-archive.fandom.com/wiki/Bag_of_Fishing_Treasures_(Terokkar_Forest)

### Steps to reproduce the problem

1. Use `.additem 23162 4` command to receive 4  'Foror's Create of Endless Resist Gear Storage' items
2. Equip all newly created bags
3. Use `.additem 34863 100` command to receive 100 'Bag of Fishing Treasures' items
4. Open all newly created items
5. Pay attention to the received loot, noting down their amount
6. Sell/delete received items
7. Repeat steps 3-5 until you open 1000 'Bag of Fishing Treasures' items
8. Calculate the chance for getting certain items from 'Bag of Fishing Treasures' items

### Extra Notes

Please note that quest 'Crocolisks in the City' (https://wowgaming.altervista.org/aowow/?quest=11665) also rewards with item named 'Bag of Fishing Treasures' but it has a different ID (https://wowgaming.altervista.org/aowow/?item=35348) thus different drop chance values. This bag was not tested against this ticket but it may be worth checking the applied drop chance value there as well, yet pets drop chance values should remain unchanged.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
The fishing treasure bag loot was improved with this commit: https://github.com/azerothcore/azerothcore-wotlk/commit/b1fc1c34b71df9596fd0e43b4907d59deb422f56, you should notice the drop chances should align a bit closer to the expected values. I'm going to close this as I feel most if not all of the outliers pointed out in this issue have been improved.
