### ISSUE TITLE
无法绑定炉石

### ISSUE THREAD

**Issue by zz123456ys** [chromiecraft/chromiecraft#6336]
奥尔多旅店无法绑定炉石

**Comment by zz123456ys** [comment]
游戏ID：Liqun，当前奥尔多阵营声望友善，无法在沙塔斯城奥尔多高地的旅店绑定炉石

**Comment by lgm002** [comment]
he is saying he unable to set aldor inn as home. reputation is friendly.

**Comment by Stump876** [comment]
Hello. I don't believe this is a bug in the core, but a singular instance. Please open a support ticket on the Chromiecraft discord to have this addressed.
