### ISSUE TITLE
Lesser Bloodstone Deposit slow respawn rate

### ISSUE THREAD

**Issue by gratzlapor** [chromiecraft/chromiecraft#634]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.
There aren't enough Lesser Bloodstone Deposits in Drywhisker Gorge (Arathi Highlands), and the respawn rate is way too slow. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
Normally when go to Drywhisker Gorge, there are always 3-4 Lesser Bloodstone Deposits which you can start mining right away, and the respawn rate is pretty fast (I don't know the exact number).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get the quest called Favor for Krazek in Stranglethorn Vale. (optinal)
2. Go to Arathi Highlands and locate Drywhisker Gorge (it is a cave in the northeastern part of the map).
3. Look for a Lesser Bloodstone Deposit.
4. Mine it and wait for respawn.

##### EXTRA NOTES:

Type here.
https://classic.wowhead.com/object=2653/lesser-bloodstone-deposit

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gratzlapor** [comment]
Also I waited for about 40 minutes and not one Lesser Bloodstone Deposit respawned, but several Silver, Gold, Mithril and Truesilver Deposits.

**Comment by Maurowin** [comment]
i agree, like said here : https://fr.classic.wowhead.com/item=4278/minerai-de-pierre-de-sang-inf%C3%A9rieur#english-comments it have fast respawn.
![image](https://user-images.githubusercontent.com/31663279/118508524-910fa680-b72f-11eb-8c32-768e546c9315.png)

**Comment by shilofax** [comment]
Confirmed this is still bugged.

**Comment by simonasbuj** [comment]
> Confirmed this is still bugged.

well, tbh, maybe it's intended. Bloodstone ore share the same spots with other ores (gold, mythril). So I just mined gold, waited and then Bloodstone ore spawned.

**Comment by Jalehandro** [comment]
Still bugged.

**Comment by Arystor** [comment]
I confirm, the respawn is still bad.
It is very annoying to go over and over to the damn cave to see if you are lucky to find an ore. I've mine 3 out of 4. And it's the typical mission that everyone has on their mission list.

**Comment by Rykehuss** [comment]
Still bugged.

**Comment by Vladimirjov** [comment]
Still not fixed ... respawn time feels way too slow. i'm waiting over 20 minutes now and still waiting

**Comment by larsvangool** [comment]
Current respawn time is set to 900 seconds (15 minutes) however each node only has a 1 out of 5/6 (or even more) change to be a Lesser Bloodstone Deposits. What would be a reasonable solution? Increase the change of the node being a Lesser Bloodstone Deposits by removing most of the other options? This Cave is mainly visited by people doing the quest and less by people training their mining skill.

**Comment by GrenderG** [comment]
Just for the record, this issue still happens.

**Comment by heyitsbench** [comment]
Still an issue as of https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1.

**Comment by jeyrella** [comment]
Still an issue, no veins to be found.  Halts progress in the quest chain :(

**Comment by UnePomme** [comment]
Still an issue. I believe the increased spawn rate of gold/truesilver/mithril/iron nodes are not allowing the lesser bloodstone nodes a chance to spawn.

**Comment by heyitsbench** [comment]
> Is it a possibility to turn off the gold/truesilver/mithril/iron node spawns in Drywhisker Gorge?

From what I see, the chance for a node spawn to be Lesser Bloodstone is the same as any other ore since they are all pooled together. I.e., if you keep mining out the nodes in the area, Lesser Bloodstone *will* appear.
