### ISSUE TITLE
Timber Worg Alpha Tail drops 11/19

### ISSUE THREAD

**Issue by TelumehtarCC** [chromiecraft/chromiecraft#6344]
Based on the statistical average of 18% drop rate of worg tails. It'd seem mathematically impossible to kill 50+ Timber Worgs and not receive a *single* tail for the Timber Worg Tails quest out of Allerian Stronghold.

**Comment by TelumehtarCC** [comment]
Oh a funny note, I have enough bloody fangs to make several gold off of it. :D

**Comment by Stump876** [comment]
HI TelumehtarCC. Thanks for the report. However, I'll need to ask you to open a new report for this. Please don't delete the template when trying to report a bug. We need all of the information asked, including the current server version (which is auto generated in the template), and a source on how it should work.
