### ISSUE TITLE
[Duskwood] Can't fully loot Solid Chest

### ISSUE THREAD

**Issue by IcemanHHW** [chromiecraft/chromiecraft#636]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Can't fully loot Solid Chest next to Blind Mary's house in Duskwood. Burnt Leather Breeches cant be looted from the chest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Fully loot the solid chest

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to chest next to Blind Mary's house
2. Loot the chest
3. See if it can fully be looted
4.

##### EXTRA NOTES:

 Solid Chest ID: 17033 (Entry: 2850) - [Solid Chest X:-10773.900391 Y:-1378.969971 Z:38.946800 MapId:0]

Screenshot: 
![WoWScrnShot_051321_111515](https://user-images.githubusercontent.com/20383130/118106059-7c54ab00-b3dd-11eb-840b-8470522590dd.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I have been able to loot all:

![WoWScrnShot_051421_080610](https://user-images.githubusercontent.com/82579073/118224219-6271a180-b48b-11eb-9398-21b08291e4bb.jpg)
![WoWScrnShot_051421_080647](https://user-images.githubusercontent.com/82579073/118224229-67365580-b48b-11eb-9b90-3596ce2b7198.jpg)

**Comment by Azcobu** [comment]
Had a look at this chest in the DB (class entry is 2850), it's your standard Solid Chest with low level stuff in there. There's 57 of this type alone. Didn't spot anything unusual about the chest or the Burnt Leather Breeches (ID 2962) Also went there and filled up quite a few bags emptying the chest over and over, and never ran into any problems. I'd be inclined to close this as a one-off, possibly client error or network issue.

**Comment by IcemanHHW** [comment]
Guess it was on my side then. Will close this issue.
