### ISSUE TITLE
The `Portal to Ironforge` in Stormwind is invisible and unusable to players.

### ISSUE THREAD

**Issue by tabakisp** [chromiecraft/chromiecraft#637]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Portal to Ironforge in Stormwind is not visible to players but visible and usable to GMs.

Player View
![Screenshot_20210513_141247](https://user-images.githubusercontent.com/7551798/118119239-bd0cee00-b3f6-11eb-9e47-8b33b6b3e557.png)

GMs View
![Screenshot_20210513_140947](https://user-images.githubusercontent.com/7551798/118119337-e3cb2480-b3f6-11eb-81a4-78d9ad13f81b.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Portal to Ironforge should be visible and usable by the players.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Stormwind
2. Go to Mage Tower located in The Mage Quarter
3. Go up the tower to the portals
4. The portal is there but not visible and not usable.

##### EXTRA NOTES:

`.gobject near` 
```
2000010 (Entry: 500002) - [Portal to Exodar X:-8983.280273 Y:852.043030 Z:29.620600 MapId:0] 
2000009 (Entry: 500003) - [Portal to Ironforge X:-8983.950195 Y:856.786011 Z:29.620600 MapId:0] 
2000011 (Entry: 500001) - [Portal to Darnassus X:-8994.919922 Y:846.252991 Z:29.620600 MapId:0] 
Found near gameobjects (distance 10.000000): 3 
```

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
very strange, I've spawned those portals myself and I don't see why one should be acting different than others

**Comment by FrancescoBorzi** [comment]
very strange, I've spawned those portals myself and I don't see why one should be acting differently than others

for the triaging team: these portals are not spawned in a clean AC, but the issue might still be in AC as they started behaving differently. Needs investigation.

**Comment by necropola** [comment]
I've checked in game and the IF portals are working in Exodar and Darnassus. 

I've checked my pretty current local AC DB, but neither found the gameobject (spawn) guids nor the gameobject_template entries of the portals. No overlap here.

Someone should check the DB's of the live system. Maybe some typo in an SQL statement fixing nodes spawns caused it?

Or maybe it's just a current glitch and a server restart fixes it?

**Comment by tabakisp** [comment]
> @tabakisp As a GM, does ` .gobject info` of the IF portal give a hint what is broken/changed?

@necropola 

```
Syntax: .gobject info [$object_entry]    Query Gameobject information for selected gameobject or given entry.
Entry: 500003
Type: 22
Lootid: 0
DisplayID: 4394
Name: Portal to Ironforge
```

**Comment by necropola** [comment]
@tabakisp
@55Honey just said on discord that the portal is phased,.

**Comment by necropola** [comment]
Portal is back. Did the server restart tthis morning just fix it?

**Comment by tabakisp** [comment]
@necropola portal is back and working as intended from what I tested.

**Comment by 55Honey** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5771
Fixed from the patches this morning :-)

**Comment by necropola** [comment]
> @necropola portal is back and working as intended from what I tested.

It was already back 2 days ago. AFAIK, the patch this morning removed the wrongly phased portal to Tirisfal Glades at Varian. But whatever. All good now.

**Comment by 55Honey** [comment]
The patch this morning was the fix for all portal related issues. We've changed the portal to IF manually meanwhile so we don't have to wait for this.

**Comment by necropola** [comment]
I disagree and here is why (second part of https://github.com/azerothcore/azerothcore-wotlk/pull/5885#issuecomment-842036629).
![image](https://user-images.githubusercontent.com/7461137/118479527-67e01d80-b711-11eb-9b25-e467064c2284.png)
And if I'm right, we should probably try to figure out what actually caused it.

**Comment by 55Honey** [comment]
Let's do this discussion in AC and not in a closed CC issu
