### ISSUE TITLE
[Herbs] Peacebloom spawns in the midde of the road in Redrige Mountains

### ISSUE THREAD

**Issue by IcemanHHW** [chromiecraft/chromiecraft#638]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Peacebloom spawns in the middle of the road close to the bridge to Duskwood in Three Corners.

![WoWScrnShot_051321_155843](https://user-images.githubusercontent.com/20383130/118137547-9ace9c80-b405-11eb-8129-dc8d74ce7ce6.jpg)

WoWhead Gathermate data with Peacebloom filter turned on
![WoWScrnShot_051321_161129](https://user-images.githubusercontent.com/20383130/118137866-fb5dd980-b405-11eb-8106-bfb2c16fca46.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Peacebloom not spawning in the middle of the road or in Redrige Mountains at all. WoWhead and Classic/TBC WoWhead has a list of zones it should spawn in:

https://www.wowhead.com/object=1618/peacebloom
https://tbc.wowhead.com/object=1618/peacebloom

##### STEPS TO REPRODUCE THE PROBLEM:

1. Walk over the bridge from Duskwood to Redridge Mountains
2. Go trough the corner
3. Peacebloom is in the middle of the road just after the corner
4.

##### EXTRA NOTES:

.gobject near

1396 (Entry: 1618) - [Peacebloom X:-9816.000000 Y:-1788.000000 Z:24.076000 MapId:0] 
Found near gameobjects (distance 10.000000): 1

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
![WoWScrnShot_051421_081324](https://user-images.githubusercontent.com/82579073/118224669-51756000-b48c-11eb-8c8f-87741fd15f0e.jpg)
![WoWScrnShot_051421_081344](https://user-images.githubusercontent.com/82579073/118224678-55a17d80-b48c-11eb-9161-a61a43db2933.jpg)

Didn't found it in my local setup.

**Comment by anguaive** [comment]
You can confirm it's there by doing `.go o 1396`

![WoWScrnShot_051421_093045](https://user-images.githubusercontent.com/39011611/118237086-2a705b80-b497-11eb-8e0d-c4844223d98a.jpg)

**Comment by Eldarix** [comment]
![WoWScrnShot_051421_143451](https://user-images.githubusercontent.com/82579073/118265289-99fb4080-b4c1-11eb-814a-b6b7a28c37bf.jpg)

indeed :)
