### ISSUE TITLE
Eclipsion Dragonhawk dealing extreme amounts of damage

### ISSUE THREAD

**Issue by WeatherOrc** [chromiecraft/chromiecraft#6391]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

The [Eclipsion Dragonhawk](https://wowgaming.altervista.org/aowow/?npc=20502), located in Eclipse Point, Shadowmoon Valley, is dealing an extreme amount of damage with their [Fire Breath](https://wowgaming.altervista.org/aowow/?spell=37985) spell.

### Expected Blizzlike Behaviour

The Eclipsion Dragonhawk's Fire Breath spell states in the description that it should be dealing 75 fire damage until cancelled.

### Source

Witnessed in person on two separate characters. Two images of the combat log are included.
![eclipsiondragonhawkbugreportexample1](https://github.com/chromiecraft/chromiecraft/assets/153065400/155f9eda-f0c0-426f-aa88-e2b3e1131d6f)
![eclipsiondragonhawkbugreportexample2](https://github.com/chromiecraft/chromiecraft/assets/153065400/e2212d71-a312-4083-b970-038fe126ee90)

### Steps to reproduce the problem

1. Go to Eclipse Point in Shadowmoon Valley
2. Find an [Eclipsion Dragonhawk](https://wowgaming.altervista.org/aowow/?npc=20502)
3. Wait 2.5 seconds in combat with the [Eclipsion Dragonhawk](https://wowgaming.altervista.org/aowow/?npc=20502), after which it will cast [Fire Breath](https://wowgaming.altervista.org/aowow/?spell=37985)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Can confirm, the fire does a bit over ten times as much as expected, plus it melees a bit more than twice as hard as it should.

**Comment by Stump876** [comment]
Hi WeatherOrc. Thanks for the report. It seems to be the wrong Flame Breath spell being used on this mob. It does tick for a ton of damage.
