### ISSUE TITLE
Gathering proffession node spawns/respawns/locations are incorrect

### ISSUE THREAD

**Issue by fungus-beep** [chromiecraft/chromiecraft#64]
##### SMALL DESCRIPTION:

**Mining and herbalism spawns are very strange/incorrect.** 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
**Mining and herb nodes should have fairly regular respawn times and spawn locations. All areas should have at least some base level of mine/herb nodes**

##### CURRENT BEHAVIOUR:
**Some areas seem to have very little to no mining/herb node spawns at all. For example herb nodes in bloodmyst isle are very rare in general, and mining nodes in loch modan seem to be very rare as well. 

Locations of the spawns seem to be correct, frequency seems to be off, as are respawn times. 
I'm not aware of the blizzlike respawn times but from wow classic it seems to be about 5-30 minutes. I have had herbs not respawn in >30 min. I have also been told (circumstantially) of some herbs respawning in seconds in elwynn forest.**

##### STEPS TO REPRODUCE THE PROBLEM:

**1. The gathermate and gathermate data will show potential node spawn locations. In some zones you wont see a herb/mining node spawn in almost all (99%) of these locations despite the zone being empty
Gathermate: https://www.gnarlyguides.com/wotlk/addons/gathermate/
Gathermate data 3.3.5a : https://www.gnarlyguides.com/wotlk/addons/gathermate-data/
2. Some herbs in azuremyst isle take longer than 30 min to respawn
3. Most if not all node locations for herbalism in bloodmyst isle and mining in loch modan are unpopulated. (check against gathermate addon data)** 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
I confirm, there are not enough Herbs and Minerals on the map.
![WoWScrnShot_020921_122812](https://user-images.githubusercontent.com/1884642/107364207-0e919e00-6ad3-11eb-8b13-d0cc638ebe6e.jpg)
