### ISSUE TITLE
[NPC]Blackwater Deckhand paths underground in Faldir's Cove

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#641]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Blackwater Deckhand GUID 11197 has a part of his pathing going underground in Faldir's Cove in Arathi Highlands.
![mole](https://user-images.githubusercontent.com/80769357/118176156-56f18c80-b431-11eb-851e-fb6e2071b16c.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should now go under textures.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Faldir's Cove in Arathi Highlands (or teleport to GUID 11197)
2. Observe the pathing of a Blackwater Deckhand that is on the pier next to First Mate Nilzlix
3. See him go underground and then back up as a part of the pathing pattern

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Not sure about how to reproduce it, but I waited and waited and neither of the two npc's went underground:

![WoWScrnShot_051421_144059](https://user-images.githubusercontent.com/82579073/118266392-2d814100-b4c3-11eb-933d-3fb78fc7da1e.jpg)
![WoWScrnShot_051421_144424](https://user-images.githubusercontent.com/82579073/118266395-307c3180-b4c3-11eb-88c6-a59073dd51a0.jpg)
![WoWScrnShot_051421_144444](https://user-images.githubusercontent.com/82579073/118266400-33772200-b4c3-11eb-8d58-b51f9518564d.jpg)
![WoWScrnShot_051421_144510](https://user-images.githubusercontent.com/82579073/118266408-35d97c00-b4c3-11eb-8f70-ab40c8829495.jpg)

**Comment by gurveleg** [comment]
OK I checked again now, It was todays fixes that fixed this issue. I guess fixing #437 also fixed the pathing of this mob. Valid yesterday, no longer now so It can be closed.
