### ISSUE TITLE
[SSC] Leotheras the Blind adds not linked

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6410]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

https://wowgaming.altervista.org/aowow/?npc=21806 can be pulled individually

### Expected Blizzlike Behaviour

they should be linked

### Source

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by quigiboo** [comment]
I'm unable to recreate this, is there a special way to pull them individually?

https://youtu.be/eO72INOvAWI

**Comment by balleny** [comment]
> I'm unable to recreate this, is there a special way to pull them individually?
> 
> https://youtu.be/eO72INOvAWI

Moonfired the top right one, other adds didnt chain.

issue was also reported here : https://github.com/chromiecraft/chromiecraft/issues/6244

**Comment by quigiboo** [comment]
> > I'm unable to recreate this, is there a special way to pull them individually?
> > https://youtu.be/eO72INOvAWI
> 
> Moonfired the top right one, other adds didnt chain.
> 
> ![WoWScrnShot_121023_172352](https://private-user-images.githubusercontent.com/12682004/289372041-dfb2714e-1584-46b8-b05e-be0e3449de89.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzMxMTgsIm5iZiI6MTcwMjIzMjgxOCwicGF0aCI6Ii8xMjY4MjAwNC8yODkzNzIwNDEtZGZiMjcxNGUtMTU4NC00NmI4LWIwNWUtYmUwZTM0NDlkZTg5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDE4MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNDhjN2JiZWJkOGRjOTk0MjcyMGFkNGU0ZDhmN2M1OWY4MjJhMmVjNTc5OWU0NmFhODhlY2IxMDExODY5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g1Cx2-JU4I4eEBoVovz6yDsUSlcHFB3GalTsLiy9wIw)
> 
> issue was also reported here : #6244

I can confirm all 3 can be pulled individually using moonfire, I tried a few other single target spells (corruption, hand of reckoning and fire blast) which all pulled them together.
I'm not sure what it is about moonfire that causes this but there's probably other spells out there.
