### ISSUE TITLE
[SSC] Lurker - Water on Ring triggers Scalding Water

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6432]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

The water on the ring of Lurkers platform triggers Scalding Water debuff if all 6 platforms are cleared.
https://www.wowhead.com/wotlk/spell=37284/scalding-water

![WoWScrnShot_121023_151154](https://github.com/chromiecraft/chromiecraft/assets/12682004/20143ba3-bc33-4d75-a5d4-2503674e41d2)

### Expected Blizzlike Behaviour

Only  areas where a char is swimming, but not standing in water, should affect you with Scalding Water debuff (if all 6 platforms are cleared)

### Source

.

### Steps to reproduce the problem

clear all 6 platforms
move into the water spots on the ring

### Extra Notes

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cythisiax** [comment]
As of https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e I am unable to replicate the described behavior above. Scalding Water debuff applies with the six defeated, but is not triggering on the boss' platform for the Lurker.

Once Lurker is defeated, the debuff goes away entirely on the water.

**Comment by Tereneckla** [comment]
![image](https://github.com/user-attachments/assets/4e820e31-12b6-474a-b85b-caa1b0768379)
it still applies when standing in the water on the platform

**Comment by Cythisiax** [comment]
> ![image](https://private-user-images.githubusercontent.com/50233983/389699702-4e820e31-12b6-474a-b85b-caa1b0768379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Njg2MDYsIm5iZiI6MTczMjU2ODMwNiwicGF0aCI6Ii81MDIzMzk4My8zODk2OTk3MDItNGU4MjBlMzEtMTJiNi00NzRhLWI4NWItY2FhMWIwNzY4Mzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDIwNTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYmVhZDA5YjE3OTI0YTY0NDhhMDdiZGJhMDcwZDZjZWZkNDdjNzNjNjM2OTI5Zjk5NzU5YmE3MjAwYzdiOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pp2mI6ZvwLZPwe8Rkj7deOd1e6MqyDyHCiD9wJhIVns) it still applies when standing in the water on the platform

I was able to produce **that**, but that is under water layer with the object's dip where the aura applies. I'm not able to go to SSC on retail to test against this though.

**Comment by Tereneckla** [comment]
That is the behavior described above

checking videos it also is the correct behavior

https://youtu.be/3pXQaOcWeus?t=131
![image](https://github.com/user-attachments/assets/e7f6c29e-56dc-42db-b7d9-7facc5c22cbc)
