### ISSUE TITLE
[SSC] Leotheras - Insidious Whisper Ghosts of other players are visible

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6434]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

The adds spawned by https://wowclassicdb.com/tbc/spell/37676 are visible to everyone.

### Expected Blizzlike Behaviour

You should see only your own

(and not be able to damage the others - here trying to attack the others results in a "missing")

### Source

https://www.icy-veins.com/tbc-classic/leotheras-the-blind-guide-strategy-abilities-loot

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
I don't know that this one is correct. In [this retail TBC kill](https://youtu.be/VbgkWIHbsoU?si=gF1mJ-nujenq7jGc&t=161), you can see an Inner Demon attacking a player and running behind the tank, despite the tank not being targetted by the Insidious Whispers.

**Comment by balleny** [comment]
ye, phrasing on the report was maybe not correct. You should be able to see them, but you shouldnt be able to target them, attack them, see their nameplate (hp bar), etc. if it aint your linked demon.

**Comment by heyitsbench** [comment]
CC: @Nyeriah

**Comment by balleny** [comment]
but, tbf the state of not seeing them is still better than seeing and being able to attack everyone elses

**Comment by heyitsbench** [comment]
> but, tbf the state of not seeing them is still better than seeing and being able to attack everyone elses

100% agree.

**Comment by Nyeriah** [comment]
This is difficult to me to replicate because no such mechanic is ever used elsewhere. It's usually phasing or personal summon (right now its more akin to a personal summon). As for only the summoner being able to attack/target while everyone else sees it just fine, I have never seen it anywhere else/there is nothing to replicate this in our expansion, so we might be missing something, but I am unable to test this as it requires more than just a single player to spawn them
