### ISSUE TITLE
[SSC] Lady Vashj - Tainted Elementals dont despawn after 15 seconds

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6445]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Not able to verify right now because the phase does not start on the PTR, but Tainted Elementals summoned by Lady Vashj should despawn within 15 seconds.
I didnt find a related section in the script, hence opening the ticket.

### Expected Blizzlike Behaviour

Tainted Elementals should despawn after 15 seconds if still alive. If dead, the lootable body should stay a bit longer.

### Source

https://wowwiki-archive.fandom.com/wiki/Lady_Vashj_(tactics)

> Despawns after 15 seconds

> When a Tainted Elemental spawns, it is imperative that it be killed as quickly as possible because it despawns after 15 seconds. 

### Steps to reproduce the problem

.

### Extra Notes

just checked https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp and didnt saw any section regarding the Tainted Elementals despawning.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Looks like it may be handled through SmartAI rather than core scripting, but I'm not sure since there's two Tainted Elementals on AoWoW.
[Tainted Elemental](https://wowgaming.altervista.org/aowow/?npc=22009):
![SmartAI](https://github.com/chromiecraft/chromiecraft/assets/38561765/917a1f1a-ed5d-47a5-8874-68e863a75b49)
[Tainted Water Elemental](https://wowgaming.altervista.org/aowow/?npc=21253)

**Comment by Nefertumm** [comment]
The one that the script is currently using is 22009, which has a smart_script linked to it. I took a look and the creature despawns after 15s, working as expected.
