### ISSUE TITLE
Silvermane Stalkers in Hinterlands should not stealth and appear black instead of grey 

### ISSUE THREAD

**Issue by ndnd123** [chromiecraft/chromiecraft#645]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

They do not break stealth when they hit you. If you are facing them they look see-through, if you turn your back on them they are completely invisible.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They probably should break stealth when they start attacking you.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Silvermane Stalker in Hinterlands
2.  Facepull them to get them to attack you
3. Turn your back on them
4. They attack you (and even daze you) while remaining stealthed

##### EXTRA NOTES:

![image](https://user-images.githubusercontent.com/46521438/118254971-56e6a080-b4b4-11eb-8cdf-061582d46e7a.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
According to Wowhead they should not be able to stealth since patch 3.2.0
https://wowpedia.fandom.com/wiki/Silvermane_Stalker?oldid=2482355
