### ISSUE TITLE
[Warrior] Deep Wounds for thunderclap is less than should be

### ISSUE THREAD

**Issue by vvranceanu** [chromiecraft/chromiecraft#6452]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Critting with thunder clap applies a bleed that is less than what is triggered by the rest of the abilities(e.g. i get 120 tick with bladestorm, heroic strike, mortal strike and 96 for thunder clap).

### Expected Blizzlike Behaviour

Every deep wounds proc should have the same damage provided same weapon damage

### Source

https://www.wowhead.com/wotlk/spell=12867/deep-wounds

The description states: "Your critical strikes cause the opponent to bleed, dealing 48% of your melee weapon's average damage over 6 sec.", so no matter the crit source, the bleed should be 48% of melee weapon damage. 

### Steps to reproduce the problem

1. Have deep wounds
2. Crit with a singural melee ability/swing and observe damage. Let it run out
3. Crit with a singural thunder clap cast and observe lower damage than previously

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
Think I may have found the problem (or a problem) here. Thunder clap is not applying Trauma when it crits, thus the deep wounds is not gaining the +30% bleed damage. 

![DW test](https://github.com/chromiecraft/chromiecraft/assets/62584589/44f85ea1-19e3-4c9c-b68c-2becdf0228a3)

I noticed first on combat logs, then tested again with video to make sure

[dw test.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/f8291f0b-dfb7-4489-a3e7-ad0012109732)

If you see the tclap ticks are only 65 per, whereas the trauma'd white ticks were 71, you add 30% to tclaps and -% from dummy armor, it would be near the same as 71 per tick. Similar to original values of 120 v 96.

**Comment by vvranceanu** [comment]
Didnt take Trauma into account
