### ISSUE TITLE
[Quest]Scouring the Desert- Can't get the silithid aura from silithid mounds.

### ISSUE THREAD

**Issue by rugzoneruk** [chromiecraft/chromiecraft#6457]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Trying to get the silithid from a mound does not give the aura/buff. So quest can't be turned in. https://wowgaming.altervista.org/aowow/?quest=9419

### Expected Blizzlike Behaviour

Clicking on a silithyst geyser should give a buff/aura to the character.

### Source

https://wowgaming.altervista.org/aowow/?quest=9419
https://www.youtube.com/watch?v=i30NuEzK2xk

### Steps to reproduce the problem

Have pvp enabled.
Go to silithus.
Get the https://wowgaming.altervista.org/aowow/?quest=9419 from https://wowgaming.altervista.org/aowow/?npc=17080
Find a Silithyst geyser while roaming around.
Click the geyser.
Observe that character does not get the aura like the video linked above.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by attacksnack** [comment]
Reproduced in latest Azerothcore.
Go to Silithus/General Kirika (.go c 43204)
Accept quest Scouring the Desert (.quest add 9422)
Find a Silithyst Geyser (.gobject target 181598)
Right-click it - no aura is applied. Manually apply correct aura: .aura 29519.
Turn Silithyst by going to X:-7589, Y:757, Z:-15 - this completes the quest which can be turned in
