### ISSUE TITLE
Jade Ooze mobs drop Scum Covered Bag which has 0 loot inside.

### ISSUE THREAD

**Issue by ndnd123** [chromiecraft/chromiecraft#647]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

These drop a "Scum Covered Bag" which should have loot but it never does. I tested this twice.

![image](https://user-images.githubusercontent.com/46521438/118261665-8bf6f100-b4bc-11eb-82b2-37d89c5ee0eb.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should drop some loot.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Skull Rock in Hinterlands, kill Jade Oozes until a bag drops
2.  Loot bag, see that nothing drops.
3. 
4.

##### EXTRA NOTES:

Scum covered bag db code: 20767

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5844
