### ISSUE TITLE
[Quest][Trial of the Naaru: Mercy] Unused Axe of the Executioner not dropping from Shattered Hand Executioner

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#6478]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Unused Axe of the Executioner not dropping from Shattered Hand Executioner even tho buff is present. Tryed twice on HC mode, not getting item.

### Expected Blizzlike Behaviour

Should drop quest item when killed within 55 mins of killing first boss in dungeon

### Source

![WoWScrnShot_121423_224542](https://github.com/chromiecraft/chromiecraft/assets/80590226/839c3a5d-54a5-4916-93c9-e0d108b7eb8d)
![WoWScrnShot_121423_224539](https://github.com/chromiecraft/chromiecraft/assets/80590226/c67be7b6-abc1-4681-a80b-35a116ca4451)
![WoWScrnShot_121423_002444](https://github.com/chromiecraft/chromiecraft/assets/80590226/6ddf48ca-3f84-4c58-9173-752e6fbb914a)
![WoWScrnShot_121423_002219](https://github.com/chromiecraft/chromiecraft/assets/80590226/d2e2079e-fb5e-4001-a8b8-24a7622ad865)
![WoWScrnShot_121423_224606](https://github.com/chromiecraft/chromiecraft/assets/80590226/01748a84-a96b-4257-9a6e-4fb94f734d21)

### Steps to reproduce the problem

1. Kill first boss on HC
2. Kill last boss within 55 mins of killing first boss on HC
3. Item not dropping
4. Note: Don't try this in solo GM mode, but try to reproduce bug in 5 man HC real dungeon.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4d40b036440069fcfa964eac36eebda9d60140cb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
https://cata-twinhead.twinstar.cz/?quest=10884

**Comment by BeefSteaker** [comment]
Obtained the item with no issued on live as of 18/12/23
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/d9032572-ac47-4643-923e-df968c6b6b0a)

**Comment by Elexias** [comment]
Yes idd, I had to abandon quest in order for it to get to work. Explain?

**Comment by BeefSteaker** [comment]
> Yes idd, I had to abandon quest in order for it to get to work. Explain?

No idea, but good to hear its fixed
