### ISSUE TITLE
[Quest][The Cudgel of Kar'desh] Completed quest description is not valid

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#6479]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

![image](https://github.com/chromiecraft/chromiecraft/assets/80590226/9a2bf917-0c61-4da5-9bad-8e126a235d77)

Says that I should turn it in Alterac Mountains, must be because it is completed within dungeon.

### Expected Blizzlike Behaviour

Should say to go to Slave Pens to mob named [Skar'this the Heretic](https://cata-twinhead.twinstar.cz/?npc=22421) https://cata-twinhead.twinstar.cz/?quest=13431

### Source

https://cata-twinhead.twinstar.cz/?quest=13431

### Steps to reproduce the problem

1. Complete quest and look at description

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4d40b036440069fcfa964eac36eebda9d60140cb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by attacksnack** [comment]
It looks like this may have been an authentic bug that was also in original TBC: 
![image](https://github.com/chromiecraft/chromiecraft/assets/2423794/37fc70a6-4794-4477-8f51-0d581002520b)

**Comment by alecsci** [comment]
:x: I cannot reproduce this on https://github.com/azerothcore/azerothcore-wotlk/commit/4ed1815de64e97a373bacf075073b7e2cde46dc5 and neither on PTR.

@Elexias the description to me looks correct, the only thing that I have different is that I have an enUs client.
