### ISSUE TITLE
BUG : NPC threat on pull

### ISSUE THREAD

**Issue by Maurowin** [chromiecraft/chromiecraft#648]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [X] other (frFR)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When I miss my pull attack, I don't take the NPC's aggro
![WoWScrnShot_051421_200220](https://user-images.githubusercontent.com/31663279/118311502-481ddf00-b4f0-11eb-9941-6786378bf1bf.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When I miss my pull attack, I have to take the aggro of the NPC

##### STEPS TO REPRODUCE THE PROBLEM:

1. Miss attack on the pull like Judgment 

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
reported on AC tracker here: https://github.com/azerothcore/azerothcore-wotlk/issues/5874

**Comment by Maurowin** [comment]
@eldarix can u test to confirm that ? I discover this bug on CC server and in my local server too have same trouble.
