### ISSUE TITLE
Chain Quest: The Missing Diplomat 

### ISSUE THREAD

**Issue by Dasthian** [chromiecraft/chromiecraft#649]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enUS

##### FACTION

- [ ] Alliance

##### CONTENT PHASE:

- [ ] 30-39

##### CURRENT BEHAVIOUR:

**https://wowgaming.altervista.org/aowow/?quest=1248
Type here. Can't talk with NPC: Mikhail**

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Closed/Duplicate.
[https://github.com/chromiecraft/chromiecraft/issues/599](https://github.com/chromiecraft/chromiecraft/issues/599)
