### ISSUE TITLE
[SSC] Bridge can be lowered with bosses alive

### ISSUE THREAD

**Issue by ICarebear** [chromiecraft/chromiecraft#6490]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Bridge was lowered with 1/6 bosses dead

### Expected Blizzlike Behaviour

All bosses except lurker need to die

### Source

![image](https://github.com/chromiecraft/chromiecraft/assets/110199518/e4dc7f0e-2f09-4361-b17a-80214a998fea)
This happened during raid today on live server
![image](https://github.com/chromiecraft/chromiecraft/assets/110199518/2fc34285-163d-4f70-8816-e4c9b2da3b6a)

### Steps to reproduce the problem

Kill a boss
Go to bridge and click 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4d40b036440069fcfa964eac36eebda9d60140cb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
I believe this has been reported at #6247 already.

**Comment by ICarebear** [comment]
Ahh, I thought it had been considered fixed already and had open a new one since it popped up again

**Comment by Nyeriah** [comment]
Not a duplicate in this case as the previous issue wasn’t triaged/updated in time. It worked during release but had issues if the raid was continued the next day, turns out the latest patch to address that didn’t work correctly and made it available regardless

**Comment by UndoUreche** [comment]
Joined a trash run, the bridge was down with no bosses downed. We were able to cross it too

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/mod-progression-system/commit/07dd031865f690776dba9dfe4a44ddf0a87a3c1c
