### ISSUE TITLE
Druid shift forms

### ISSUE THREAD

**Issue by daniboiz** [chromiecraft/chromiecraft#65]
##### CONTENT PHASE:

19

##### SMALL DESCRIPTION:

sometimes im in human/cow/tauren form but it shows like travel or bear.
https://imgur.com/a/Tgmp9fK

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@daniboiz 
**We need more information,** we need to figure out if it's a Spell or Cache problem.

Not seeing the Tauren form is:
```
- You see yourself in Tauren form but do other players see you in animal form?
- You still see yourself in Animal form but other Players see you in Tauren form?
- Both you and the other Players can't see the Tauren form?
- Does this Bug only happen from Animal forms towards Tauren Form or vice versa too?
```

**Comment by Stifler82** [comment]
I tried the Druid shift forms and they work fine.
Probably yours it is a **Client Cache Issue**..
**Video** of my **Test**: [Druid shift forms](https://youtu.be/PQHZYUMFTcA)

**Comment by illfated** [comment]
Very likely a game client issue combined with a Cache issue.
