### ISSUE TITLE
Winter Hats

### ISSUE THREAD

**Issue by savalina6** [chromiecraft/chromiecraft#6506]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

The Prince Tortheldrin in DM is not wearing the green winter hat during the Winter Veil event. He has a chance to drop it during the event to be worn as part of the holiday garb.
![WoWScrnShot_122523_140127](https://github.com/chromiecraft/chromiecraft/assets/106502295/b9159959-e4cb-410a-8bed-19ac99bee161)

Have not ran BRD to check on the Emperor at the end to see if he was wearing the red hat. 

### Expected Blizzlike Behaviour

Prince Tortheldrin should be wearing a green holiday hat during the event with a chance to drop it.

### Source

![image](https://github.com/chromiecraft/chromiecraft/assets/106502295/c4a19ebb-d119-444d-a24e-e53a196ad28f)
https://www.wowhead.com/wotlk/item=21525/green-winter-hat

### Steps to reproduce the problem

Go into the library in Dire Maul
look at Prince Tortheldrin
To kill Prince, you have to kill the other boss, after killing the crystals 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e2ecbf44cc19450109bee1ef7ce6aaa7621c5af4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
This is almost certainly not true. As each expansion came out, the hats were moved to the most recent expansion's dungeon bosses, i.e. since we're in TBC content, the hats drop off of TBC dungeon bosses. I am rather confident in saying that the hat drops on Wowhead's page are still polluted from Winter Veil of vanilla Classic.

**Comment by Nyeriah** [comment]
Yes, else you would just get it off the easy bosses instead of grouping up to do the current, harder content

**Comment by heyitsbench** [comment]
Closed for the aforementioned reasons, though do note that if CC were in its vanilla brackets, the Winter Hats would be dropping from these vanilla bosses.
