### ISSUE TITLE
[SSC] Morogrim Tidewalker's attackable radius by melee is tiny

### ISSUE THREAD

**Issue by vvranceanu** [chromiecraft/chromiecraft#6508]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Morogrim Tidewalker's attackable radius by melee is tiny. It's similar to what Kazzak had originally

### Expected Blizzlike Behaviour

Shouldn't have to sit almost inside his model to be able to attack him

### Source

https://www.youtube.com/watch?v=YzcIKmUZGDU

### Steps to reproduce the problem

1. Go on ptr
2. Try to attack Morogrim in melee

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e2ecbf44cc19450109bee1ef7ce6aaa7621c5af4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by clovaek** [comment]
https://youtu.be/zUFKmxeaRfk?si=hZmL6nUyKO5GHybV&t=367
https://youtu.be/FEYAX7l5H6A?si=Tk0C_FQL18ddyd7Y&t=1130

you can see him being attacked from a considerably larger distance than on CC in original tbc and tbc classic

**Comment by heyitsbench** [comment]
[Eyeballed radius](https://github.com/chromiecraft/chromiecraft/assets/38561765/7957049f-cc87-4081-8dcb-97e333528684) based off https://www.youtube.com/watch?v=YzcIKmUZGDU, definitely bigger than CC currently.

**Comment by heyitsbench** [comment]
```
BoundingRadius: 6.315000057220458984
CombatReach: 6
```
Source: 50791 sniff.

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
