### ISSUE TITLE
"Schematic: Mana Potion Injector" seems to have strangely limited drop sources

### ISSUE THREAD

**Issue by quigiboo** [chromiecraft/chromiecraft#6514]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Currently the recipe seems to only drop from a handful of mobs. https://wowgaming.altervista.org/aowow/?item=23884#dropped-by

### Expected Blizzlike Behaviour

According to wowhead, the recipe should drop from most high level outland mobs, like a world drop. you can see in both the dropped by section and the comments for anecdotes on where people say they got it
https://www.wowhead.com/wotlk/item=23884/schematic-mana-potion-injector#dropped-by;0+2-10-9+1

### Source

https://www.wowhead.com/wotlk/item=23884/schematic-mana-potion-injector#dropped-by;0+2-10-9+1
https://wowgaming.altervista.org/aowow/?item=23884#dropped-by

### Steps to reproduce the problem

Difficult to reproduce as you would have to kill thousands of specific mobs to verify.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e2ecbf44cc19450109bee1ef7ce6aaa7621c5af4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by rugzoneruk** [comment]
can https://wowgaming.altervista.org/aowow/?item=22540#dropped-by and https://wowgaming.altervista.org/aowow/?item=22542#dropped-by also be checked to see if their drop rates are blizzlike?

**Comment by Apathyxia** [comment]
> can https://wowgaming.altervista.org/aowow/?item=22540#dropped-by and https://wowgaming.altervista.org/aowow/?item=22542#dropped-by also be checked to see if their drop rates are blizzlike?

Relevant issue which I reported a while back: https://github.com/chromiecraft/chromiecraft/issues/5342

**Comment by quigiboo** [comment]
"Schematic: Healing Potion Injector" also suffers the same problem.
https://wowgaming.altervista.org/aowow/?item=23883#dropped-by
https://www.wowhead.com/wotlk/item=23883/schematic-healing-potion-injector
