### ISSUE TITLE
Druid Bear Form not Improving Armor Received from Weapons

### ISSUE THREAD

**Issue by zwillan** [chromiecraft/chromiecraft#652]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Armor stat on weapons such as https://wowgaming.altervista.org/aowow?item=12252 are not being improved by shapeshifting into the druids bear form.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The armor stat should be improved by the druids bear form armor bonus.
Comments on this page: https://classic.wowhead.com/item=12252/staff-of-protection#comments indicate that it should work this way.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Shapeshift into bear form
2. Equip weapon with armor stat such as Staff of Protection
3. Observe armor from weapon not being multiplied by bear form

##### EXTRA NOTES:

https://classic.wowhead.com/item=12252/staff-of-protection#comments

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, the Wowhead quotes you linked to are from Classic and TBC era-Wow. In patch 3.0.8 they changed how Bear/Dire Bear forms worked:

> As previously announced, we are changing the way bear armor works so that bonus armor on items does not receive the bear armor multiplier. Specifically this means that weapons, trinkets, rings, necks and cloaks with bonus armor will not be multiplied by the bear bonus. Only cloth and leather will benefit from the Bear and Dire Bear multiplier. (https://wowthinktank.blogspot.com/2008/11/druid-now-thats-armor-nerf.html)

See also https://wowwiki-archive.fandom.com/wiki/Patch_3.0.8, although it's not as clear there.

So unfortunately (I play a bear as well), this is not a bug, but is the expected Wrath-era behaviour.
