### ISSUE TITLE
Unable to loot lurker below

### ISSUE THREAD

**Issue by lgm002** [chromiecraft/chromiecraft#6523]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

killed the boss the moment spout ended and about to enter P2, while boss corpse was on surface of water, nobody is able to loot it.

### Expected Blizzlike Behaviour

should be able to loot boss corpse

### Source

na

### Steps to reproduce the problem

na

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e2ecbf44cc19450109bee1ef7ce6aaa7621c5af4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UnePomme** [comment]
I can confirm this as well. During Phase 2, Lurker is supposed to clear all dots and be immune to damage. Instead it looks like dots continue to damage while in this phase which can result in a boss kill and glitched loot.

https://wowwiki-archive.fandom.com/wiki/The_Lurker_Below#Phase_2

**Comment by UnePomme** [comment]
Video starts at Phase 2 (4:09) (when he submergs and ads spawn)
When Lurker becomes non-targetable the dots continued to kill him (off screen) which results in a floating non-lootable dead body.

Note: It could be 1 of 2 scenarios, but I'm not 100% sure which one is supposed to happen.
1. Lurker clears dots and becomes immune to damage to prevent off-screen kill (which I believe is the case).
2. Dots continue to happen and off-screen kill is allowed, but body should be lootable.

**Comment by elthehablo** [comment]
> Lurker Below Fight https://youtu.be/bOgVubpALOI?t=249
> 
> Video starts at Phase 2 (4:09) (when he submergs and ads spawn) When Lurker becomes non-targetable the dots continued to kill him (off screen) which results in a floating non-lootable dead body.
> 
> Note: It could be 1 of 2 scenarios, but I'm not 100% sure which one is supposed to happen.
> 
> 1. Lurker clears dots and becomes immune to damage to prevent off-screen kill (which I believe is the case).
> 2. Dots continue to happen and off-screen kill is allowed, but body should be lootable.

Lurker does clear all dots (debuffs), a spell to do this shows up in sniffs. We also do this, so the problem that dots kill the Lurker off-screen is highly unlikely. It could be something else that kills them offscreen though. Or direct damage killing the Lurker during movement messing up the body position and thus makes it unlootable

Source:
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/b76a642c-96ee-4e72-8b7e-f34f7010fc74)
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp

**Comment by UnePomme** [comment]
> Or direct damage killing the Lurker during movement messing up the body position and thus makes it unlootable

That would also make sense. I do not know how to check for sniffs yet, so thank you for that info.

**Comment by elthehablo** [comment]
> > Or direct damage killing the Lurker during movement messing up the body position and thus makes it unlootable
> 
> That would also make sense. I do not know how to check for sniffs yet, so thank you for that info.

https://www.azerothcore.org/wiki/sniffing-and-parsing but we have sniffs of this already. Unfortunately that won't tell us much in this situation
