### ISSUE TITLE
[Hunter] Intimidation incorrect aggro

### ISSUE THREAD

**Issue by bieliqus** [chromiecraft/chromiecraft#6543]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Intimidation spell assigns aggro to hunter instead to pet.

https://wowgaming.altervista.org/aowow/?spell=19577

### Expected Blizzlike Behaviour

Agro should be pet's, not hunter's

### Source

https://www.wowhead.com/wotlk/spell=19577/intimidation#modified-by

### Steps to reproduce the problem

Pull few mobs as hunter, attack only one and use intimidation, then all other mobs will attack you

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cythisiax** [comment]
Unable to replicate this https://streamable.com/o5iksm

Pet taunt is individual, not an AOE taunt. Pet would need to be attacking respective target, and taunt- for hunter to not have main threat on target. Not seeing other mobs turn towards hunter after pet taunts either.

**Comment by Gazeshooter** [comment]
Not sure if this was ever fixed or modified but Intimidation sends aggro to the hunter, not the pet. At level 44 pressing Intimidation sends 3k threat to me. Intimidation can be cast and will generate threat but not stun even when the pet does not have a target (attack, follow then stay).

This can be easily replicated by pulling multiple mobs via pet, pressing intimidation and noticing the remaining mobs will aggro onto the hunter.
