### ISSUE TITLE
Deadmines door behind the Ogre boss is closed after a group wipe forcing to end the dungeon.

### ISSUE THREAD

**Issue by Fingon93** [chromiecraft/chromiecraft#655]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After defeating the ogre boss in Deadmines the door opens. If the group wipes after and comes back the door stays closed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The door should not be closed after a wipe.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Beat the ogre boss.
2. Wipe.
3. Run back to the door.
4.

##### EXTRA NOTES:

Imgur Link:

https://imgur.com/0Hc3Zmo

Another player pointed out that the bug happened to him also beforehand.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Can you tell me where exactly you wiped? I thought it might be connected to when another door opens, but I tried a few times, and I have yet to see the door close on it's own. I can manually close it with the lever the door, but I can reach the lever through the door. If anything, I think that might be a bug. I'll have to test it more, but right now I have more questions than answers.

**Comment by Fingon93** [comment]
We wiped in the goblin foundry, the rogue also stipulated that he had previously wiped and the door was also closed for him.

**Comment by Fingon93** [comment]
It is to note that the pathing in the goblin foundry is weird, maybe it's related?

**Comment by Stump876** [comment]
I did a bit of searching to find this as well.
https://github.com/TrinityCore/TrinityCore/issues/23785 
That being said I couldn't duplicate that either. Running back from the graveyard and waiting 10 minutes total before re-entering the instance, the door remained open. Even after manually closing the doors, I was still able to get a gear for the lever on the other side of the door to open it. Resetting, I even did it during the boss fight. (I had GM turned off for the run)
![image](https://user-images.githubusercontent.com/68164076/118415803-63f4c280-b661-11eb-9629-38ed6dc88ffb.png)
![image](https://user-images.githubusercontent.com/68164076/118415828-7b33b000-b661-11eb-89b4-d8d71d28609d.png)

I can't duplicate it. That doesn't mean it's not happening, bugs are odd like that. If you see it happen again check to see if you can get a gear for the door lever on the spot circled above. Though I cant prove that is blizzlike, but it would solve you problem. Feel free to report anything new found here.

**Comment by Fingon93** [comment]
OK if it happens again I will come back here with a follow-up.
