### ISSUE TITLE
Druids cannot auto melee attack when oom in tauren form.

### ISSUE THREAD

**Issue by ndnd123** [chromiecraft/chromiecraft#656]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If you are in regular form and you are oom you cannot auto attack and you receive a warning "not enough mana".

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Auto attack doesnt require mana.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make yourself oom
2. Try to auto attack
3. You get the  warning "youre out of mana"
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I'm sorry I just can't duplicate the problem. I followed the steps, and while if I try to cast it will say "out of mana", melee swings still connect.
![image](https://user-images.githubusercontent.com/68164076/118407516-f1222200-b635-11eb-85ac-be2a82b0dc48.png)

If you find something additional to help me duplicate, please post it and we'll take another looks at it. In the meantime I'm going to close this for now.
