### ISSUE TITLE
Paladin's SoV on-hit Effect

### ISSUE THREAD

**Issue by mussy44** [chromiecraft/chromiecraft#6566]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Seal of Vengeance's on-hit effect (weapon damage component based on the number of seal stacks) procs only when the target has 5 SoV stacks

### Expected Blizzlike Behaviour

Seal of Vengeance's on-hit effect should apply a percentage of weapon damage that scales with the number of stacks on the target, maxing out at 33% weapon damage at 5 stacks.

> [Seal of Vengeance] and [Seal of Corruption]: These seals have been redesigned. Only auto-attacks and Ability [Hammer of the Righteous] can place the debuff on the paladin's current target(s). However, while the seal is active, each melee swing or ability (excluding judgements) that lands on the target will deal a percentage of weapon damage as Holy damage to the target. This damage maxes out at 33% weapon damage with 5 applications of the debuff and scales upward evenly based on how many applications of the debuff are active. This Holy damage deals double-damage critical strikes. In addition, the damage-over-time debuff is now considered a melee attack for the purposes of determining its chance to hit, miss, be dodged or parried.

From Wowpedia fandom

### Source

[Patch 3.2.0 - latter patches don't mention any changes to SoV's on-hit proc condition](https://wowpedia.fandom.com/wiki/Patch_3.2.0)
[Retribution: Updated for 3.3](https://web.archive.org/web/20100523150101/http://elitistjerks.com/f76/t68951-retribution_updated_3_3_a/)
[Wowhead comments](https://www.wowhead.com/wotlk/spell=31801/seal-of-vengeance#comments:id=955889)
[Info from Light Club for WotLK Classic](https://discord.com/channels/705379591816085635/705462982607372348/1025535976002572318)
![4N09I0F](https://github.com/chromiecraft/chromiecraft/assets/84478740/c863c6bc-38ec-43f9-9ad4-c567aad2f2b5)

### Steps to reproduce the problem

1. Play Paladin and enable Seal of Vengeance
2. Find a target dummy and auto attack it while looking at a damage meter, you'll only see "Holy Vengeance (DoT)" and "Melee"
3. Once 5 SoV stacks have been applied to the target, you'll be able to proc SoV's on-hit effect and you'll start seeing "Seal of Vengeance" in the damage meter

### Extra Notes

N/A

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
