### ISSUE TITLE
List of bugged quests 

### ISSUE THREAD

**Issue by Mojoo1** [chromiecraft/chromiecraft#6576]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Greetings. (Chromiecraft) 
I hope this message finds you well.

As i've recently passed through full Loremaster of Kalimdor/Eastern Kingdoms/Outland, i was able to find few quests which are bugged and cannot be completed for some reason.

1) https://www.wowhead.com/classic/quest=5721/the-battle-of-darrowshire
The Battle of Darrowshire quest cannot be completed as for some reason Captain Redpath (spirit) is not spawning during the fight, and even before spawning, one of the friendly npc spirits tells that he died. 

2) https://www.wowhead.com/classic/quest=5943/gizelton-caravan
Gizelton Caravan quest cannot be completed as for some reason when escorting the caravan through the demon area, even if you are able to kill all the demon waves without losses, in the middle of the quest it just becomes Failed. 

3) https://www.wowhead.com/classic/quest=4642/melding-of-influences
Melding of Influences quest cannot be completed as after releasing the slime from a Encased Corrupt Ooze item in the direction of a Primal Ooze in Un Goro, the "merge" of 2 slimes is not happening and Gargantuan Ooze is not spawning,

4) https://www.wowhead.com/classic/quest=5125/aurius-reckoning
Aurius' Reckoning quest cannot be completed as the quest cannot be taken into the player's Quest Log and for that reason the quest item Medallion of Faith https://www.wowhead.com/classic/item=12845/medallion-of-faith from Malor the Zealous never drops when you kill him. (quest item never drops)

5) https://www.wowhead.com/classic/quest=4121/precarious-predicament
Precarious Predicament quest cannot be completed as at the end of the escort of the quest npc through all the waves of foes, the Npc is getting executed (killed) as he should be, but the Prisoner Transport  (quest requirement) is not given to the player (is not counted) after execution of the prisoner.

### Expected Blizzlike Behaviour

.

### Source

.

### Steps to reproduce the problem

.

### Extra Notes

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Windows 10

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Hi Mojoo, all of these are already reported. also in the future could you report each bugged quest individually unless the bug is linked
https://github.com/chromiecraft/chromiecraft/issues/2982
https://github.com/chromiecraft/chromiecraft/issues/3377
https://github.com/chromiecraft/chromiecraft/issues/639
https://github.com/chromiecraft/chromiecraft/issues/1999
