### ISSUE TITLE
Can't loot if npc is killed by player's pet

### ISSUE THREAD

**Issue by Mojoo1** [chromiecraft/chromiecraft#6577]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

And additional bug i want to report is that if any Mob killed by the Player's pet (or most part of the mob's HP is damaged by Player's pet, but not the player himself) this killed mob at the end cannot be looted by player. (it shows as empty corpse)

### Expected Blizzlike Behaviour

Any mob killed by the player's pet should be available to loot it normally by the Player

### Source

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Windows 10

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Provide a source. I am confident this is Blizzlike.

**Comment by Mojoo1** [comment]
Hello, im new here and i don't know how to provide this Source.
The server is called ChromieCraft.  Yes its kinda blizz like

**Comment by heyitsbench** [comment]
> i don't know how to provide this Source

You need to provide some sort of proof that the behavior you claim is Blizzlike is actually Blizzlike, whether that be from a public website (such as Wowhead/Wowpedia), or videos from the game being played on Blizzard's servers.

**Comment by BeefSteaker** [comment]
This is blizzlike behavior. hunter must personally do significant damage to the mob in 3,3,5
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/6b333d2d-cc71-45d6-9214-2c73736fb31c)
https://www.bluetracker.gg/wow/topic/eu-en/13200796582-looting-bugged/
