### ISSUE TITLE
[SSC] Vashj Phase 2 Tainted Elemental does not attack targets not in line of sight

### ISSUE THREAD

**Issue by SirenxAA** [chromiecraft/chromiecraft#6582]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Before last patch, during phase 2 the tainted elemental will attack random players by spitting poison bolts at them regardless of line of sight. Right now it will target a player but if he/she is not in line of sight it will not attack until (another) aggro target is in line of sight

### Expected Blizzlike Behaviour

During phase 2, when tainted elemental spawn it should attack (poison bolt) random players on map regardless if it is in line of sight or not.

### Source

In current patch and also in PTR

### Steps to reproduce the problem

1. Engage Vashj and enter phase 2, stay on the platform and not on stairs
2. Wait 50 seconds for tainted to spawn, you will notice no poison bolt attacks on map or hit you even if tainted elemental is present (given you are at the top of stairs, not in line of sight of the tainted elemental), it will be targeting you though.
3. Run into line of sight of the tainted elemental (or .gm fly on)
4. It only attacks when it "sees" you

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by SirenxAA** [comment]
I also like to add that some of the enchanted elemental will travel underground (through the stairs) to Vashj which is unkillable due to line of sight.

**Comment by sudlud** [comment]
Might be related to azerothcore/azerothcore-wotlk#18225

**Comment by balleny** [comment]
ye, the ability of the tainted should ignore LoS
