### ISSUE TITLE
Grinding syndicate members for revered Ravenholdt reputation

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#659]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

You may get reputation with Ravenholdt while being revered with them by killing syndicate mobs.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once Revered, the only option is with a repetable quest ( https://classic.wowhead.com/quest=8249/junkboxes-needed ).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill syndicate npc all the way until revered.
2. Repeat step 1 and notice you still gain reputation while revered.

##### EXTRA NOTES:

(Please no ban, I stopped  :O  )
![WoWScrnShot_051621_161620](https://user-images.githubusercontent.com/22718174/118411610-5c361d80-b663-11eb-9266-e849322b947b.jpg)

Faction: https://classic.wowhead.com/faction=349/ravenholdt
Guide: https://www.wowhead.com/guide=156/ravenholdt-reputation-guide

Mobs I killed that I did get reputation while being revered
Syndicate Watchman: https://wotlkdb.com/?npc=2261
Syndicate Shadowmage: https://wotlkdb.com/?npc=2244

It might happens to every other syndicate members found in that list https://wotlkdb.com/?faction=349#npcs

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/0d699222de92185681f9a78822a0e5d9898294f4

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
You are partially correct. You should not get rep as revered. However, you are only honored, not revered. 
![image](https://user-images.githubusercontent.com/68164076/118413265-3bfe6280-b653-11eb-91f6-8ed0c2eee056.png)
From the links you posted "you can get up to 11999/12000 Honored by killing NPCs"
Keep up the grind my friend!
