### ISSUE TITLE
Mail send and never received

### ISSUE THREAD

**Issue by Cozmalon** [chromiecraft/chromiecraft#6616]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

I have send a mail using the ingame Mailbox from the Scryer bank Mailbox, in Shattrath City.
The mail was send between 2 characters from the same account: from my lvl 70 paladin to my lvl 1 bank-character.
The ingame name of the lvl 70 character from which I sent the mail is "Burebista"
In the mail there were no gold ammount send - just items: around 40+ Bars of Eternium (https://wowgaming.altervista.org/aowow?item=23447)

That mail never reached my bank character.
I have send later, for testing, some Netherweave cloth (just to see if that mail also will stuck and never reach it's recipient, but this time it worked in an instant.

Please check the database to confirm the affirmations above and also to find out what happend with the mail and the attached items.

Thank you for your time and attention!

### Expected Blizzlike Behaviour

Without the error the mail should have arrived in the inbox of my other character, within 30 min or less.

### Source

[x]

### Steps to reproduce the problem

1. Enter on your account and Log in ingame to one of your characters.
2. Send a mail only with items attached - to other character from the same account.
2. Press escape and Logout from the "sender" character.
3. On the same account, now enter on the character that should receive the mail sent previously.
4. There is a chance (like it happend to me) that the mail sent will not reach the inbox of the recipient.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
Hi there. This bug report is likely best reserved for a in game ticket via Discord (check #support). We will likely be able to help you there or at least discuss some steps with you to resolve your problems. Thanks!
