### ISSUE TITLE
all the love is in the air perfumes can be used at once for massive buffs

### ISSUE THREAD

**Issue by quigiboo** [chromiecraft/chromiecraft#6631]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

can use all perfumes at once.
![image](https://github.com/chromiecraft/chromiecraft/assets/114075548/0f1669c7-4e15-49fa-9ce8-639d7fa04cd6)

### Expected Blizzlike Behaviour

should only be able to use one, they stack with food and flasks etc though

### Source

https://www.wowhead.com/wotlk/item=49860/wizardry-cologne#comments
https://www.wowhead.com/wotlk/item=49861/stalwart-cologne#comments
https://www.wowhead.com/wotlk/item=49859/bravado-cologne#comments
no mention of being able to use them all at once, someone would have mentioned it.

### Steps to reproduce the problem

buy all the perfumes
use them all 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️

**Comment by veredis1** [comment]
U normally could just use one, the purple ones only used for females and the green one for male.

**Comment by heyitsbench** [comment]
> U normally could just use one, the purple ones only used for females and the green one for male.

Feel free to provide a source on that, can't see that anywhere.

**Comment by veredis1** [comment]
Hey sorry for the late answer, I found no source for the female/male thing, but if u look in youtube videos for Love in the Air they all can just get one buff (not two of the same kind).

Vid example: https://www.youtube.com/watch?v=34tFZ5aS29k

**Comment by heyitsbench** [comment]
Resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/0c95ddf285e3f00a06d5c2a1257708d4163fbf20.
