### ISSUE TITLE
Edgar Boatwrighte (The custom arena NPC) and the alliance counterpart both dont get the "Sample Satisfaction Debuff" from the Bonbon Blitz Daily

### ISSUE THREAD

**Issue by SmoothMoose7** [chromiecraft/chromiecraft#6632]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

For the Bonbon Blitz Daily, you have to sample NPCs or Players chocolate treats. You use the item on them, when thrown to a npc or player the receive a debuff "Sample Satisfaction" its a 10min Debuff. The custom arena NPCs in the major cities (Orgrimmar and Stormwind) dont receive the buff. Meaning you can infinitly throw the sample to them without a debuff. This daily can be complete in about 10seconds now, which isnt blizzlike.

![NODEBUFF](https://github.com/chromiecraft/chromiecraft/assets/145289036/d0d15692-6adb-49e7-abb8-f9e5cd086952)

### Expected Blizzlike Behaviour

The custom NPCs should get the 10min Debuff.

### Source

https://www.wowhead.com/wotlk/quest=24636/bonbon-blitz#guides

### Steps to reproduce the problem

- Accept the Dailyquest "Bonbon Blitz" from the NPC "Public Relation Agent"
- Target "Edgar Boatwrighte" or the alliance npc counterpart.
- Use "Crown Chocolate Sampler" on them 10 times for the quest completion

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
CC: @55Honey

**Comment by 55Honey** [comment]
Thanks for the report, the NPC will despawn shortly.
