### ISSUE TITLE
[Tempest Keep] - Ember of Al'ar Not Damaging 2% Boss HP 

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6637]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

[HP.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/3765b744-8f3d-4c93-8c72-714481dc48a0)

Currently when an Ember of Al'ar dies, they do not do 2% of the bosses total hp as damage. 

### Expected Blizzlike Behaviour

Anytime an Ember of Al'ar dies, is phase 1 or phase 2, it should do 2% of the bosses total hp as damage.

### Source

https://youtu.be/YJL79tY6cvk?si=eplCVV2vbk71o8Cw&t=141 [he says 3%, but it's 2%]
https://youtu.be/jsVmTdm1mx4?si=ktR5U-sd5Gl21MIJ&t=351
I would also link wowpedia stuff, but their strats seem to only reflect post-nerf data. Idk what ver staff is picking. 

### Steps to reproduce the problem

1. Enter TK
2. Start fight with Al'ar
3. Kill an Ember of Al'ar
4. Watch boss hp remain the same

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by shaszun** [comment]
This was working before the latest changes.

**Comment by Cooties-cc** [comment]
[hp.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/f8dcf0af-e442-4107-a692-195647ba8057)

As a heads up since some PTR patches have gone out, the -HP% still isn't working correctly. Was tested on 2/25/24.
