### ISSUE TITLE
[TK] - Al'ar Platform Position After Flame Quills

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6643]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Pre-nerf currently has Al'ar go to any 1 of the 6 platform positions after Flame Quills. 

### Expected Blizzlike Behaviour

Post-nerf, since platforms were cut down to only 4, Al'ar should only go to either platform 1 (west) or platform 4 (east). 

### Source

![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/62f2b158-63f3-4b09-b495-22e2d30efe8e)
https://wowpedia.fandom.com/wiki/Al%27ar?oldid=2352262#Flame_Quills
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/7ccb160f-53cc-4d4c-a97d-18e79786f96f)
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/d1a2432c-33fc-489a-8243-e237d2d59a18)
https://www.wowhead.com/wotlk/npc=19514/alar#comments (patch 2.1.3 comments)

### Steps to reproduce the problem

1. Enter TK
2. Pick a fight with Al'ar
3. After each Flame Quill, notice he goes randomly to a platform, not just 1 or 4 (its designed pre-nerf atm)

### Extra Notes

Can't find a solid video depicting this that was post-nerf. Often, they would enter p2 too fast for a Flame Quill to be cast. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
This was fixed :)
