### ISSUE TITLE
Sunfury Eradicator [NPC=21742] bugged when gets aggro

### ISSUE THREAD

**Issue by Wayran-is-typing** [chromiecraft/chromiecraft#6656]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

The NPC Sunfury Eradicator from Ruins of Karabor (outside of Black Temple) gets stuck and doesn't move when you attack it.

![WoWScrnShot_021124_114259](https://github.com/chromiecraft/chromiecraft/assets/74470790/991dd7ca-bb66-4d73-847e-dea45670955a)
![WoWScrnShot_021124_114317](https://github.com/chromiecraft/chromiecraft/assets/74470790/0720a3b7-530c-41e0-8be4-275938e3a46f)
![WoWScrnShot_021124_114338](https://github.com/chromiecraft/chromiecraft/assets/74470790/3c8680cb-8158-41e0-8a57-a4e9343b1b6d)
![WoWScrnShot_021124_114635](https://github.com/chromiecraft/chromiecraft/assets/74470790/6614fcbd-54e3-42f4-963f-48c830af566c)
![WoWScrnShot_021124_115208](https://github.com/chromiecraft/chromiecraft/assets/74470790/cab662b1-9b3a-4bb4-a90e-5c62b37589f3)
![WoWScrnShot_021124_113902](https://github.com/chromiecraft/chromiecraft/assets/74470790/fb11d582-8b33-47e1-af6b-4c9d411147b7)
![WoWScrnShot_021124_113912](https://github.com/chromiecraft/chromiecraft/assets/74470790/3166af87-0ec5-4af4-b77f-6accdcb20b11)

### Expected Blizzlike Behaviour

they should move like all the mobs when you attack them

### Source

-

### Steps to reproduce the problem

-

### Extra Notes

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02
-

### Operating system

Ubuntu 20.04
-

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None
-

### Server

ChromieCraft

**Comment by avarishd** [comment]
Cannot reproduce, reopen if issue appear again.

https://github.com/chromiecraft/chromiecraft/assets/46330494/0cdbd1fe-9c96-4379-a756-e6e987694e02
