### ISSUE TITLE
[The Eye]Thaladred's movement speed is too high

### ISSUE THREAD

**Issue by vvranceanu** [chromiecraft/chromiecraft#6657]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Thaladred's movement speed is too high, he outruns the player character

### Expected Blizzlike Behaviour

He should be in walking speed

### Source

https://youtu.be/50rC95LSCZE?si=9jVuJoSlOTyf4fSG&t=1413

### Steps to reproduce the problem

1. Engage Kael Thas
2. Observe Thaladred velocity

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by NinesCC** [comment]
https://youtu.be/Y8cMTH3vIng?si=SdIQaXQ_Pz71TVBj&t=9948

**Comment by elthehablo** [comment]
but I've tried, and will keep trying

**Comment by balleny** [comment]
indeed quite "annoying"

**Comment by vvranceanu** [comment]
could he not be made vulnerable to slow and afflicted with an infinite slow effect(invisible one ideally)?

**Comment by elthehablo** [comment]
That is not how we fix things

**Comment by vvranceanu** [comment]
i understand but if its a core issue with potentially big research time, a placeholder would be cute

**Comment by amed80** [comment]
i don't know if this helps or not (i know nothing about codes) but changing his speed_run fixed this problem for me unless you can't change that ?

UPDATE`creature_template` SET `speed_run`=0.7 WHERE  `entry`=20064;

**Comment by heyitsbench** [comment]
@amed80, that is a hackfix and falls under `That is not how we fix things`.

**Comment by elthehablo** [comment]
What Bench said. I know it is frustrating, but we'd rather not patch in something that isn't correct.

This seems to really be a core issue related to how creatures behave in combat. Movechase movement apparently doesn't really seem to support walking.

**Comment by amed80** [comment]
can't you just make Thaladred specific to alwayswalk or that's also considered as a hack ?
i saw in another core report ([Trinitycore](https://github.com/TrinityCore/TrinityCore/pull/23073)) that 20064 and 28654 had set to alwayswalk but checking Azerothcore only 28654 is set to alwayswalk but 20064 is set to run.
20064 ([Thaladred](https://wowgaming.altervista.org/aowow/?npc=20064))
28654 ([Dark Rider of Acherus](https://wowgaming.altervista.org/aowow/?npc=28654))

UPDATE `creature_template_movement` SET `Chase`=2 WHERE  `CreatureId`=20064;

**Comment by elthehablo** [comment]
Chase is not an AzerothCore creature template colum as far as I am aware

**Comment by elthehablo** [comment]
> can't you just make Thaladred specific to alwayswalk or that's also considered as a hack ?
> i saw in another core report ([Trinitycore](https://github.com/TrinityCore/TrinityCore/commit/956158d299b3264f883f49ac647154179182fbea)) that 20064 and 28654 had set to alwayswalk but checking Azerothcore only 28654 is set to alwayswalk (Chase=2) but 20064 is set to run (Chase=0).
> 20064 ([Thaladred](https://wowgaming.altervista.org/aowow/?npc=20064))
> 28654 ([Dark Rider of Acherus](https://wowgaming.altervista.org/aowow/?npc=28654))
> 
> UPDATE `creature_template_movement` SET `Chase`=2 WHERE  `CreatureId`=20064;

I can try. Thanks for the tip. It might be very likely that it gets overwritten by movechase calling run again though

**Comment by amed80** [comment]
one more attempt without changing any number in chase or his speed.
![opera_07%22%35=28-03-2024](https://github.com/chromiecraft/chromiecraft/assets/8395873/afa9f6dc-212d-40e1-b6a1-62e4ebfeb95b)

I don't know if this will cause any problem with other NPC but it fixes Thaladred and make him walk instead.

**Comment by elthehablo** [comment]
yeah it works. thanks

**Comment by amed80** [comment]
Adding this just as suggestion , **i know that i have no source or proof of this number or it may also consider as a hack** , but looking at his current walking speed and comparing it to what we see in TBC videos like [this one](https://youtu.be/1AKe2yevmVg?t=49), currently he looks a lot more slower than he should be , is there a chance you can change his walking speed to 2.0 which for me looks more accurate than 1.1 ? like this
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/bde56e62-55dc-41fa-ac3b-848da7a4d63c)

**Comment by elthehablo** [comment]
> Adding this just as suggestion , **i know that i have no source or proof of this number or it may also consider as a hack** , but looking at his current walking speed and comparing it to what we see in TBC videos like [this one](https://youtu.be/1AKe2yevmVg?t=49), currently he looks a lot more slower than he should be , is there a chance you can change his walking speed to 2.0 which for me looks more accurate than 1.1 ? like this
> ![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/bde56e62-55dc-41fa-ac3b-848da7a4d63c)
> 

We do that in the DB. It's not a hack and speeds can be sniffed but it unlikely the current speed is. I will amend it when I get home
