### ISSUE TITLE
[The Eye] Kael'Thas Mind Control's dispel by dagger doesn't work reliably

### ISSUE THREAD

**Issue by vvranceanu** [chromiecraft/chromiecraft#6665]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

People with dagger equipped would do 2-3 Devastate and would not be able to dispell

### Expected Blizzlike Behaviour

Dispel should be 100% on ability use

### Source

The description implies 100% https://www.wowhead.com/tbc/item=30312/infinity-blade

### Steps to reproduce the problem

1. Get in p4 of Kael'Thas and get Mind Controlled
2. Have someone with https://www.wowhead.com/tbc/item=30312/infinity-blade use abilities that deal damage to you, such as Shiv, Devastate, etc. in an attempt to dispel
3. Repeat few times till observation

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
at least pre-nerf, it was not a 100% as can be seen here
https://youtu.be/FEYAX7l5H6A?t=6128
rogue + additional person doing at least 1 abilites + auto attacks before MC faded

small room of error in case the MC'ed tank was actually avoiding attacks but most attacks seem to be done from the back

**Comment by vvranceanu** [comment]
The balance is post nerf and for the record auto attacks should not dispel ever(in case this is a bug). Got footage of what may or may not be considered a source:
https://www.youtube.com/watch?v=50rC95LSCZE&t=1888s
https://youtu.be/50rC95LSCZE?si=5w4lQsWwFen38e_g&t=1910
https://youtu.be/50rC95LSCZE?si=YKg6zgX4cWMKCNHN&t=2044
Point is the dispels happen instantaneously < 1s. Abilities have 1.5s gcd, so it must have been 100%

**Comment by vvranceanu** [comment]
But later on in the video i see this https://youtu.be/50rC95LSCZE?si=PQv55CWXnJEwRmDy&t=2096 , seems the MC on the left too 3 people few seconds to dispel. Idk, maybe could get a sniff on this one or some reliable source if someone has it
