### ISSUE TITLE
Bountiful Feast expiry not working correctly

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6669]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

people are still in possession and able to use https://wowgaming.altervista.org/aowow/?item=46887 several weeks after the event

### Expected Blizzlike Behaviour

the item should disappear after 7 days

### Source

https://www.wowhead.com/wotlk/item=46887/bountiful-feast#comments

### Steps to reproduce the problem

.

### Extra Notes

Likely, the expiry on the feast itself or on the materials is not working as it is supposed to.
the reagents would provide a "legal" leeway to conjure and use the items up to two weeks (1 week reagents, 1 week feast) after the event ends

item is still actively abused on Chromiecraft and should be removed - you should be able to verify characters / banks etc with the item or mats present easily.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sudlud** [comment]
Thanks for the report - can you please share a screenshot of the item still in the inventory/bank or please add some additional information on how this could be accomplished?

I tried to reproduce the issue on latest AC, but the item always gets correctly deleted from the inventory / bank when the duration ends, also the remaining duration in the DB is beeing updated correctly on player logout.

**Comment by sudlud** [comment]
But if some players (who recently logged in) actually still have the item / the ingredients in their bank / in their bags, this could maybe be confirmed in the CC database 👀

**Comment by balleny** [comment]
i didnt yet try to reproduce but noticed people using these in raids as recently as 1 week ago, hence the report.

my assumption is that the counter doesnt actually tick while offline and people just store the reagents or finished feasts on bank chars

**Comment by sudlud** [comment]
The remaining duration of items gets updated on player login based on the difference current time and last login time, and then also in player update while the player is online.

If it exceeds the remaining duration, items get deleted, from bank or bags.

Also you can't put these items in the guild bank, can't mail them, can't auction them.

So it would be really interesting to understand how this was accomplished.

**Comment by avarishd** [comment]
Odd, it does have ITEM_FLAGS_CU_DURATION_REAL_TIME custom flag, with specified time... hmm.

**Comment by balleny** [comment]
issue might be related to the reagents like https://wowgaming.altervista.org/aowow/?item=46888 but I can just tell that people where using it in raids plenty past the actual event

**Comment by balleny** [comment]
and i guess a sql lookup, who still has the items in the inventory could lead at least to the culprits, may they share what they are doing

**Comment by balleny** [comment]
someone ingame just confirmed that they have (due to inactivity on that char) still https://wowgaming.altervista.org/aowow/?item=44844 from Pilgrims in their inventory.
as this should be the same mechanic, the overall mechanic seems to be broken

**Comment by sudlud** [comment]
Thanks for the update - that's some helpful information.

**Comment by sudlud** [comment]
> someone ingame just confirmed that they have (due to inactivity on that char) still https://wowgaming.altervista.org/aowow/?item=44844 from Pilgrims in their inventory.
> 
> as this should be the same mechanic, the overall mechanic seems to be broken

Could you please ask them what the remaining time on the item was right after logging in?

**Comment by balleny** [comment]
6 days

**Comment by sudlud** [comment]
Item 44844 seems unrelated to this issue unfortunately as it was missing the real-time flag.

**Comment by sudlud** [comment]
Alright I'm able to reproduce the issue on my local AC now, so this issue is valid.
