### ISSUE TITLE
Ambiente e posizione personaggio alterati.

### ISSUE THREAD

**Issue by maurocass71** [chromiecraft/chromiecraft#6673]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

50-59

### Current Behaviour

After login the character drop down for 1 second and rest in a strange zone
![WoWScrnShot_021424_181145](https://github.com/chromiecraft/chromiecraft/assets/160052311/f14c959f-3dc8-4a1d-8f43-ef7f7528ad7d)
This is not the first time
![WoWScrnShot_032721_191530](https://github.com/chromiecraft/chromiecraft/assets/160052311/858bb0d2-e3ef-421e-8046-ab766a7823a6)

![WoWScrnShot_032721_191729](https://github.com/chromiecraft/chromiecraft/assets/160052311/ee2c096b-d694-4b24-8d75-7531f46b2e57)
This is Stormwind city
![WoWScrnShot_021424_183434](https://github.com/chromiecraft/chromiecraft/assets/160052311/528b8378-2ed6-46e5-a586-be188443dd25)

### Expected Blizzlike Behaviour

After login th character still rest in same place that I leave after logoff.

### Source

![WoWScrnShot_032721_191759](https://github.com/chromiecraft/chromiecraft/assets/160052311/387efa57-7f76-4792-9218-0a75c151caa0)
Stormind seems to be bugged.

### Steps to reproduce the problem

1- Log-in in Silvermoon in 71,72
![WoWScrnShot_021424_183323](https://github.com/chromiecraft/chromiecraft/assets/160052311/fdf2214a-5918-4979-ae4d-446962a88bd1)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Windows 11 Pro - 22631.3155

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
This is a rare bug that can happen if the client lags while on a flight path
