### ISSUE TITLE
[Bloody Rare] Voidhunter Yar may not be properly spawning

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#6689]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

I know that I have already opened ticket on discord and that I have received answer from staff that they have seen him spawning, but have you camped him?

Maybe he bugged up somehow and you've maybe only seen him after server crash/restart? I'm camping him for days and waisting time along with other people whom are also missing him as last rare, he hasn't spawned once if you ask me. Hadn't seen him for days, probably he only spawn once per crash/restart and then he never again spawns.

It is impossible that I haven't seen him for > 10 days. Please investigate properly, he is spawned on PTR atm.

### Expected Blizzlike Behaviour

Should respawn each 8 hours.

### Source

https://www.almarsguides.com/wow/achievements/outland/yar.cfm
https://wowpedia.fandom.com/wiki/Voidhunter_Yar
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2389

### Steps to reproduce the problem

1. Kill him and wait for his respawn.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
Can confirm he has a spawn location so you might just be very unlucky

**Comment by Elexias** [comment]
Do you have any proof that he spawned in past 10 days without server having CRASH or been restarted? I hadn't nor more farmers seen him at all... I'm afraid that he is not spawning PROPERLY when killed once after restart.

**Comment by Elexias** [comment]
> Can confirm he has a spawn location so you might just be very unlucky

And can you prove that in last patch you've seen him regularly or only after server crash/restart.

**Comment by elthehablo** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/7f6ad2ed-6735-4d05-b7d8-e15b6f280dfc)
on the live server. just killed by someone

**Comment by elthehablo** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/e82d1a56-6b01-4db9-8f16-4ec65db19141)
on the live server. just killed by someone. so this can be closed

**Comment by Elexias** [comment]
I seriously believe that this rare is not working.

3rd week can't spot him, been on spot > 12 hours and he is not spawning, his spawn time is not working. He spawns either once per CRASH or weekly reset or something. I've been talking to people who are also looking for him, so strange that I see 5 people looking for him and that his is last rare missing for their achievements? Outland rares are not Time Lost Proto Drake, I'm here on my rogue for 3 weeks waisting time, not farming anything else but waiting, and he is never there. When I wake up at 6 AM he is not there, when I'm 8 hours waiting he doesn't spawn, whenever I check he is not there nor corpse.

@heyitsbench @BeefSteaker @elthehablo

**Comment by Elexias** [comment]
I may have been wrong, but prove me that his spawn timer is between 8 to 12 hours.

**Comment by heyitsbench** [comment]
> I may have been wrong, but prove me that his spawn timer is between 8 to 12 hours.

```sql
INSERT INTO `creature` (`guid`, `id1`, `spawntimesecs`) VALUES
(151928, 18683, 43200);
```

**Comment by elthehablo** [comment]
Bench coming in clutch

**Comment by Elexias** [comment]
I mean thank you all for trying to help and pointing that out @heyitsbench , but you know, sometimes your scripts is well written but it doesn't work, I'm thinking of that seriously, so many people just missing that guy, it is rare whom is same as any other, Hemathion is rare who spawns at Ogri"la daili quest zones but people have no problem with him... even tho that area is overwhelmed by people...

**Comment by heyitsbench** [comment]
Currently checking this guy on my local AC install, if he spawns fine there there's nothing we can do. I'll report back in ~12 hours.

**Comment by elthehablo** [comment]
Lol

**Comment by sudlud** [comment]
@heyitsbench showing some dedication

**Comment by BeefSteaker** [comment]
here are his specific spawn details
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/15a2d7ca-145d-4c3e-b149-384042ebfddb)

spawned on my local 
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/e90ecf2f-b84a-4dd4-aff9-58d09f7fd656)
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/563ae0ca-ad98-4c68-ba83-7e6eab715c20)

**Comment by BeefSteaker** [comment]
So i killed him and used .respawn on him but he didnt respawn. maybe he is bugged?

**Comment by elthehablo** [comment]
> So i killed him and used .respawn on him but he didnt respawn. maybe he is bugged?

Pooled spawn maybe. It is normal for rares

**Comment by elthehablo** [comment]
I say pooled but I mean more possible spawn locations.

**Comment by heyitsbench** [comment]
> Pooled spawn maybe. It is normal for rares
> I say pooled but I mean more possible spawn locations.

This was my first thought, but Yar appears to have a single spawn (which is itself in a pool of its own).

**Comment by Elexias** [comment]
He should have single spawn location and patrol, but he spawns on location that was linked by Beef. Imagine how it is to wait 15 days for nothing :S

**Comment by heyitsbench** [comment]
Update: He did not spawn on time. Upon killing him, he did have an entry listed in `characters.creature_respawn`, but once the epoch time was hit, the entry was removed but he did not spawn. As of writing, he has not spawned. Will keep the server running and check again in the morning, if he is not spawned then either, then I will reopen and triage the issue.

**Comment by Elexias** [comment]
> Update: He did not spawn on time. Upon killing him, he did have an entry listed in `characters.creature_respawn`, but once the epoch time was hit, the entry was removed but he did not spawn. As of writing, he has not spawned. Will keep the server running and check again in the morning, if he is not spawned then either, then I will reopen and triage the issue.
> 
> EDIT: This is very much not the outcome I expected lol.

Thanks for showing interested in this case, I wanna kill myself now! :D

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️

**Comment by elthehablo** [comment]
I stand corrected on this one. Thanks for showing me I was wrong

**Comment by Elexias** [comment]
This becomes live when it is announced on CHANGELOG-CHROMIECRAFT or after first restart?

**Comment by heyitsbench** [comment]
> This becomes live when it is announced on CHANGELOG-CHROMIECRAFT or after first restart?

It will go live with the next restart.
