### ISSUE TITLE
Lazy Peon "Work! Work!" noise is bugged

### ISSUE THREAD

**Issue by Istox** [chromiecraft/chromiecraft#67]
##### CONTENT PHASE:
"1-19"

##### SMALL DESCRIPTION:
https://wowgaming.altervista.org/aowow/?npc=10556
Lazy Peon in Valley of Trials (Orc starting area) occasionally say "Work! Work!" which you can hear through sound. Unfortunately the sound always seems to be played at your character location rather than at the location of the Lazy Peon NPC

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Sound "Work! Work!" played at the location of the Lazy Peon NPC

##### CURRENT BEHAVIOUR:
Lazy Peon NPC sound "Work! Work!" is played at your character location

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Create Orc Character
Step 2 Run around Valley of Trials
Step 3 Dont get close to Lazy Peon but have them in long range sight
Step 4 "Work! Work!" sound will be played originating on your character instead of the Lazy Peon in the distance.

I suppose its possible this is a client bug?

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Duplicate [NPC audio banter heard from afar](https://github.com/chromiecraft/chromiecraft/issues/17)
