### ISSUE TITLE
[Stranglethorn Vale] Issue with Bloodscalp Tusks not dropping

### ISSUE THREAD

**Issue by uhuglue** [chromiecraft/chromiecraft#670]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

All Bloodscalp trolls in Stranglethorn Vale drop Bloodscalp Tusks (https://wowgaming.altervista.org/aowow/?item=3901), needed for quests Hunt for Yenniku (https://wowgaming.altervista.org/aowow/?quest=581) and the warrior quest Cyclonian (https://wowgaming.altervista.org/aowow/?quest=1712). However, after turning in the first quest, while still having the second one active, the quest item no longer drops from any of the trolls, making it impossible to complete.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The item (https://wowgaming.altervista.org/aowow/?item=3901) should still drop even after turning in the first quest, if the concurrent quest is still active.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be warrior, lvl 30+
2. Pick up both quests - Hunt for Yenniku and Cyclonian
3. Gather some Bloodscalp Tusks, turn in Hunt for Yenniku
4. Tusks no longer drop for the Cyclonian quest

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ed3a575ba4ba3eff9d218d018de6a20b6e29db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Cannot reproduce :(

**Comment by uhuglue** [comment]
Dropping and restarting the Cyclonian q makes the item drop again.

**Comment by anguaive** [comment]
I can't reproduce this either. Bloodscalp Tusks keep dropping after collecting 9 for Yenniku, before and after handing them in.
