### ISSUE TITLE
[TBC The Eye] - Ember of Al'ar Spawn Position

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6719]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Ember of Al'ar are sometimes spawning on top of the platforms

[b1.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/3c67bda0-772c-4afd-93b1-d3c8f4e9ccaf)

[b2.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/471845ca-05cd-4cbf-bc22-8420e3d594e5)

### Expected Blizzlike Behaviour

Ember of Al'ar should only be spawning below the platforms. 

### Source

https://youtu.be/Yz1lNZmRmSs?si=_zZzKVgIu87wwM57&t=132

Spawns are at  : 2:15, 2:52, 3:31

https://youtu.be/lJevFcZiafY?si=k2znCQTkAB73DBAH&t=47
Explains post-nerf spawns at 1:35
Spawns : 0:51, 1:05, 1:40

### Steps to reproduce the problem

1. Zone to TK and fight Al'ar
2. Watch Ember spawns each transition
3. Often they will spawn above the platforms (not 100% of the time)

### Extra Notes

The 2nd video also explains more about post-nerf changes, but nothing that hasn't been brought up in bug reports thus far I think.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
Oooh they should spawn in the same circle as in p2. Okay that's an easy fix now
