### ISSUE TITLE
Wrong loot table for Shiver Blade

### ISSUE THREAD

**Issue by gabryatfendor** [chromiecraft/chromiecraft#672]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Shiver blade](https://wowgaming.altervista.org/aowow/?item=5182) just dropped from a mob inside Wailing Caverns

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Shiver blade should drop only from the rare mob [Gesharahan](https://wowgaming.altervista.org/aowow/?npc=3398) as reported for example [here](https://classic.wowhead.com/item=5182/shiver-blade)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ed3a575ba4ba3eff9d218d018de6a20b6e29db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
![WoWScrnShot_051921_032839](https://user-images.githubusercontent.com/82579073/118739543-610cf400-b852-11eb-9497-abc4797cab13.jpg)

Cleared all the instance with no drop of it, checking again later ;)

**Comment by gabryatfendor** [comment]
I think it's a pretty rare drop in the instance (like a world drop). I think it would be quicker to check if the item appear in any loot table aside Gesharahan (I don't know if this is possible :D)

**Comment by Eldarix** [comment]
Surely, but I had nothing to lose and I always like a little exploration of the ancient dungeons :)

One of our colleagues who knows how to look at those tables maybe can do it.

**Comment by anguaive** [comment]
Yup I can confirm this; Shiver Blade is dropped by 464 distinct creature types, one of them being Gesharahan.
```
SELECT COUNT(*)
FROM
    `creature_loot_template` clt
    JOIN `reference_loot_template` rlt ON rlt.entry = clt.Item
    JOIN `item_template` it ON it.entry = rlt.Item
WHERE it.name = "Shiver Blade";

+----------+
| COUNT(*) |
+----------+
|      464 |
+----------+
```

Thanks for the report.

**Comment by gabryatfendor** [comment]
@anguaive could it be useful if I report all the rare mob that should have unique loot that is instead looted from other mobs too? Testing all of them would be a bit hard, but with the SQL query you wrote I could check directly in the DB.
