### ISSUE TITLE
World Breaker doesn't show its proc buff

### ISSUE THREAD

**Issue by vvranceanu** [chromiecraft/chromiecraft#6728]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

https://www.wowhead.com/tbc/item=30090/world-breaker does not apply(or at least show as a buff) https://www.wowhead.com/tbc/spell=36111/world-breaker on the player

### Expected Blizzlike Behaviour

https://www.wowhead.com/tbc/spell=36111/world-breaker should be visible by the player

### Source

-

### Steps to reproduce the problem

1. Get a proc from World Breaker

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment]
animation absolutely works its the same as thunderclap

**Comment by vvranceanu** [comment]
> animation absolutely works its the same as thunderclap

could you show where in this bug report did it mention the animation not working?

**Comment by avarishd** [comment]
2021 recycled
https://www.wowhead.com/tbc/item=30090/world-breaker#comments:id=5288822
>On proc, an animation will play very similar to thunder clap. The buff doesn't shows up among your buffs, but while it is active, your character is surrounded my a glowing aura, as if you would have been hit by thunder clap.

2007
https://www.wowhead.com/tbc/item=30090/world-breaker#comments:id=175445:reply=19435 
>I haven't noticed much of a change in the proc rate of this weapon since 2.3, but the incredible (and long overdue) Paladin buffs make this weapon a beast. The World Breaker does not have a buff icon but instead shows the effect Thunder Clap would have on a target only that it's on you (around your feet). The effect is then used up in the next swing/attack (yes, Windfury, Seal of Command/Blood) or it disappears after 4 seconds.

blizzlike "feature" ¯\_(ツ)_/¯
