### ISSUE TITLE
Group of Sunscale Lashtails (Raptors) near Crossroads not wandering while idle

### ISSUE THREAD

**Issue by Tachtzehn** [chromiecraft/chromiecraft#673]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde (this bug is not faction specific, but Horde is preferable for verification due to guard proximity)

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

3 (marked) Sunscale Lashtail mobs just southeast of Crossroads are fixed in place and not exhibiting normal wandering behavior for their mob type. There is a 4th (unmarked) member of the group that is wandering as normal.
![WoWScrnShot_051821_194935](https://user-images.githubusercontent.com/83389835/118743084-48331d00-b817-11eb-832a-637a82f1e5b0.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mobs that are fixed in place should wander around while not in combat

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to/near Crossroads in the Barrens
2. From south gate of Crossroads, look southeast, and you should see the Sunscale Lashtail, if not, just take a few steps in that direction
3. Observe the group of Sunscale Lashtail. You'll notice that 3 of the 4 are not doing the usual random wandering pattern

##### EXTRA NOTES:

.npc info for mobs identified by marks in the screenshot:
**Skull:** DB GUID: 40496
Entry: 3254
**X:** DB GUID: 40495
Entry: 3254
**Circle:** DB GUID: 40493
Entry: 3254
**Unmarked (This mob is behaving normally, no fix needed, but I put here for reference):** DB GUID: 19816
Entry: 3254

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ed3a575ba4ba3eff9d218d018de6a20b6e29db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. Thanks for the report.
![image](https://user-images.githubusercontent.com/68164076/118750705-c3df9a80-b814-11eb-8a0d-3c07f470ac39.png)
I aggro'd and ran out of combat to reset and the skull started to wander. But the other two went right back to their assigned spot.
![image](https://user-images.githubusercontent.com/68164076/118750754-e4a7f000-b814-11eb-8af5-ddd90c42283c.png)
