### ISSUE TITLE
[TBC The Eye] - Al'ar's Divebomb Not Summoning Adds Always

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6734]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

[adds.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/116f6e10-53d3-4e88-b0f0-ce1a89376e78)

After the update, not every Divebomb that Al'ar casts will summon 2 Ember of Al'ar.

### Expected Blizzlike Behaviour

Every Divebomb should summon 2 Ember of Al'ar.

### Source

![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/c5954a27-62ce-4d54-bd96-ca8f8bfcb14c)
https://wowpedia.fandom.com/wiki/Al%27ar?oldid=2352262#Phase_2

Various post nerf fight vids & guides, as well as wowhead comments. Don't know if you want them all linked lol. 

### Steps to reproduce the problem

1. Fight Al'ar and enter phase 2
2. Watch each Divebomb over time, not all will spawn Embers

### Extra Notes

Not sure what is causing it. Tested 3 times and each test had diff rates of spawning embers. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I tested the issue, but adds spawn correcty. It has probably already been fixed.

Thank for the report anyway.
