### ISSUE TITLE
Main tank can get bubbled during Tidewalker fight.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#6739]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

During Morogrim Tidewalker's fight, the main tank for Tidewalker can get bubbled.

### Expected Blizzlike Behaviour

I believe they shouldn't be able to be bubbled (though murloc tanks can).

### Source

Assumption, hearsay.

### Steps to reproduce the problem

1. Do Tidewalker fight.
2. Continue to roll dice until main tank gets bubbled.
3. Observe the main tank was bubbled.

### Extra Notes

Not too sure if this is true, but I want to jot it down in case it is so I don't forget about it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/51c414b9d58c224c1a2238f8bfc07cbed0060a02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
I do know that in 4.X soloing videos, the player does not get bubbled.

**Comment by Cooties-cc** [comment]
https://www.youtube.com/watch?v=QvmA7Yf3azU

Pretty much confirms to me that Water Graves never get cast on highest threat targets. I also swore there was already a ticket up about this exact issue.

**Comment by vvranceanu** [comment]
https://wowpedia.fandom.com/wiki/Morogrim_Tidewalker
Soloing Morogrim Tidewalker

**Comment by balleny** [comment]
On a side note there tho: Bosses behave differently based on raid size / players engaged.
If you are in a dungeon solo (pets included regardless), bosses will e.g. not use mind control abilities on retail.

so while it may hold true that MC, bubble or other abilities shouldnt be cast on the person currently highest in the threat table, they should also not be casted when only 1 player is present (even if there are e.g. 2 units in the threat table because there are pets, totems, etc).

I think in most cases, this is still implement incorrect / not at all in the boss fight scripts. Sometimes, there is an exclusion for the highest target in the threat table, sometimes an exclusion for the current target, and most often not a proper check at all
