### ISSUE TITLE
[TK] Solarian missing Split yell

### ISSUE THREAD

**Issue by UndoUreche** [chromiecraft/chromiecraft#6747]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

After 52s Solarian splits. She plays the audio line, but the monster yell event is empty.
![image](https://github.com/chromiecraft/chromiecraft/assets/50205200/bf255d72-7cd0-41a5-a2fc-fa7bddf4ff0e)
![image](https://github.com/chromiecraft/chromiecraft/assets/50205200/3ec19c8e-33e7-47a2-b5d9-aa050d424380)

Similarly, there is no text message when the priests spawn.

Moreover, her phase transition quote is missing entirely:
![image](https://github.com/chromiecraft/chromiecraft/assets/50205200/a220369f-bb88-4b3c-94f0-add457cd9319)

### Expected Blizzlike Behaviour

Solarian should be yelling "I will crush your delusions of grandeur!" when agents spawn
Solarian should be yelling "You are hopelessly outmatched!" when the priests spawn
Solarian should be yelling "I become ONE... with the VOID!" upon phase transition

### Source

DBM localization file and her functional audio line.

### Steps to reproduce the problem

Open eventtrace
Engage Solarian
Wait until split
Notice that there's nothing in chat and the CHAT_MSG_MONSTER_YELL event is empty

### Extra Notes

While all chat messages are empty, over two splits she played the first line 3 times (I will crush your delusions of grandeour!) three times, and her second line (You are hopelessly outmatched) only once.

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
From what I can see the first two lines you mention seem to be random on disappearing. No line on re-appearing. See:

https://youtu.be/y9gumQpLzEY?si=dZR3GpSvm2PzM9tl&t=68
https://youtu.be/y9gumQpLzEY?si=5dVHmYPnf50Fnbqs&t=163

**Comment by elthehablo** [comment]
Also. The lines were not showing up because apparently at least yells by invisible creatures do not show up in the text box either. Maybe an interesting report to make as well if not done so already.

However... I'm not sure if blizz does this correctly themselves
