### ISSUE TITLE
[The Eye] Al'ar does Dive Bomb too frequently

### ISSUE THREAD

**Issue by vvranceanu** [chromiecraft/chromiecraft#6750]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

After the first one, Al'ar does Dive Bomb every 20s in P2, count starting after he lands. There is virtually no time to actually engage the boss after dodging all the mechanics

### Expected Blizzlike Behaviour

Should occur every 50 seconds

### Source

https://www.warcrafttavern.com/tbc/guides/alar/

### Steps to reproduce the problem

1. Get to Al'ar P2
2. Observe the rotation

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vvranceanu** [comment]
I think you should take into consideration making this timer a bit longer than normal, since the adds are quite beefy

**Comment by Cooties-cc** [comment]
Doing some more digging for additional sources, here is a video of post-nerf al'ar during phase 2. 
https://youtu.be/JdKnhQhVjEQ?si=twCHouTpHi7tfPZ8&t=264

I documented 3 strikes to get the following numbers:

4:27 1st fly
4:41 1st strike

5:24 2nd fly
5:38 2nd strike

6:19 3rd fly
6:33 3rd strike

Time between fly initiate and strikes : 14 seconds
Time between fly initiates : _1->2_ 57 seconds; _2->3_ 55 seconds
Time between strike to initiate : _1->2_ 43 seconds; _2->3_ 41 seconds

I'm not sure how the code is written, but there was avg of 56 seconds between each start of Divebomb. I would guess that it's not a hard 50 seconds, but more of a float with 50 seconds being the minimum value.
