### ISSUE TITLE
[The Eye] Al'ar does Rebirth after every Dive Bomb

### ISSUE THREAD

**Issue by vvranceanu** [chromiecraft/chromiecraft#6752]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Al'ar does Rebirth after every Dive Bomb

### Expected Blizzlike Behaviour

Rebirth is his revival after death in P1, should only be used to transition to P2

### Source

https://www.wowhead.com/tbc/guide/alar-the-eye-tempest-keep-strategy-burning-crusade-classic
https://www.icy-veins.com/tbc-classic/al-ar-guide-strategy-abilities-loot

>>Phase 2 - Rebirth will trigger at the start of the Phase, dealing fire damage and knocking back all nearby players.
>>[Rebirth] Starts the second phase of the fight, once again knocking back everyone near the boss and dealing Fire damage.

### Steps to reproduce the problem

1. Al'ar P2

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by vvranceanu** [comment]
Note that behaviour is somewhat desired, but the cast should be hidden, no animation for rebirth should be shown(should happen while invisible and untargetable, as opposed to becoming targetable and then "dying" to then perform the rebirth animation). The damage and knockback is there. https://youtu.be/tbWJrx8kO8M?si=Lk9vfSQmO9f5TG-Q&t=235

**Comment by Cooties-cc** [comment]
I honestly had trouble seeing what you were saying, but it makes sense now checking PTR and seeing how it works. 

[RB.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/db580b71-de8a-47d0-99da-4ea424916df4)

Currently, Al'ar is targetable and is visually hard casting Rebirth on the PTR. I would agree that this is wrong. 
However in your video, the player doesn't ever try and target Al'ar for the 1-2 seconds after Dive Bomb (he only focused on adds, then boss), so we can't verify if he has a cast bar or is even targetable, since it does visually spawn and have a delay to cast, similar to PTR

I would say it should be done in the fashion that TBCC did it, in that rebirth is "cast" as Al'ar visually appears. Basically he is precasting the spell as he is unseen phased out. 
https://youtu.be/JdKnhQhVjEQ?si=sgSNOFEnyL4xuUvb&t=392
You can see it here pretty clear. 

I would agree that for the most part, Al'ar shouldn't be targetable during Rebirth, but could be visible. However I think the spell should go off like it does into P2, in that it triggers as he "respawns", which makes more sense. There just has to be a visual marker for his location, like in the TBCC video, for that to be possible. If not, like the old one posted, he will visually appear then shortly after, Rebirth will be cast.

**Comment by vvranceanu** [comment]
> I honestly had trouble seeing what you were saying, but it makes sense now checking PTR and seeing how it works.
> 
>  RB.webm 
> Currently, Al'ar is targetable and is visually hard casting Rebirth on the PTR. I would agree that this is wrong. However in your video, the player doesn't ever try and target Al'ar for the 1-2 seconds after Dive Bomb (he only focused on adds, then boss), so we can't verify if he has a cast bar or is even targetable, since it does visually spawn and have a delay to cast, similar to PTR
> 
> I would say it should be done in the fashion that TBCC did it, in that rebirth is "cast" as Al'ar visually appears. Basically he is precasting the spell as he is unseen phased out. https://youtu.be/JdKnhQhVjEQ?si=sgSNOFEnyL4xuUvb&t=392 You can see it here pretty clear.
> 
> I would agree that for the most part, Al'ar shouldn't be targetable during Rebirth, but could be visible. However I think the spell should go off like it does into P2, in that it triggers as he "respawns", which makes more sense. There just has to be a visual marker for his location, like in the TBCC video, for that to be possible. If not, like the old one posted, he will visually appear then shortly after, Rebirth will be cast.

sometimes is a bit worse than that. he would appear visible as in your capture, then go into a sliver of fire as he first appears here https://youtu.be/JdKnhQhVjEQ?si=sgSNOFEnyL4xuUvb&t=392 and then cast rebirth

**Comment by TheSCREWEDSoftware** [comment]
Issue confirmed to also happen in AC, has been linked here: https://github.com/azerothcore/azerothcore-wotlk/issues/20569

**Comment by TheSCREWEDSoftware** [comment]
Intended behaviour, sniff information about the Dive Bomb and Rebirth https://github.com/azerothcore/azerothcore-wotlk/issues/20569#issuecomment-2478922020
