### ISSUE TITLE
[The Eye] Crystalcore Mechanic doesn't cast Recharge

### ISSUE THREAD

**Issue by vvranceanu** [chromiecraft/chromiecraft#6773]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Crystalcore Mechanic doesn't cast Recharge

### Expected Blizzlike Behaviour

Should

### Source

https://www.wowhead.com/tbc/guide/trash-mobs-the-eye-tempest-keep-strategy-burning-crusade-classic#crystalcore-mechanic

### Steps to reproduce the problem

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
In my experience testing this can be triggered. That being said, I do trigger by dealing a chunk of damage to the golems. To fix the issue where recharge was being cast on humanoids as well, I just added a condition to the spell, but according to those reports recharge was being cast under normal circumstances as well.

In short, I'm not 100% sure if the spell should now no longer trigger whatsoever, would be nice to see some proof of this/hear about other people running into the same problem.

**Comment by vvranceanu** [comment]
Ok, i did get them to cast it, but the trigger seems to be half hp(~1.2mil). I'm not sure how it's supposed to be, since in the few footage i saw online, they usually get banished. We can close this ticket since no further proof, i initially just damaged the golem somewhat and i saw the mechanics not reacting.

**Comment by elthehablo** [comment]
That's fine. It is set at 50% health afaik

**Comment by vvranceanu** [comment]
idk about healing tunning plans, but fyi they do 100% healing, meaning 10k/s. its not noticeable over the 2 mil hp

**Comment by elthehablo** [comment]
> idk about healing tunning plans, but fyi they do 100% healing, meaning 10k/s. its not noticeable over the 2 mil hp

We can't tune creature healing right now. It needs to be developed and I lack the time/insight myself rn
