### ISSUE TITLE
[TK] Al'ar not transitioning to Phase 2 when doing the fight organically with a raid 

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#6798]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

When doing Al'ar in an organic 25m group, meaning we kill the boss in a normal fashion as it would occur on the live server, Al'ar fails to Rebirth and transition to Phase 2.

When you go solo and use damage commands to force it to transition it does work correctly.

March 1st run: https://youtu.be/Y8cMTH3vIng?si=fZHDyxSLp62J-U46&t=2582
March 3rd run: https://youtu.be/kSt8VJxral0?si=fRaoqgiLtwHQobi2&t=1240

### Expected Blizzlike Behaviour

When Al'ar dies, it should transition to Phase 2 by Rebirthing.

### Source

https://wowpedia.fandom.com/wiki/Al%27ar

### Steps to reproduce the problem

1. .tele eye
2. Fight Al'ar
3. Kill Al'ar in P1 in a normal fashion
4. Wait for it to transition to Phase 2

### Extra Notes

On both of our full 25m runs on the PTR, we had adds alive when Al'ar was killed. It's unknown if this is related to the problem.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
Anyone have an idea yet what causes this?

**Comment by elthehablo** [comment]
Or some more information about under what conditions this happens

**Comment by heyitsbench** [comment]
Looked like he was doing Flame Quills when killed in the first video and maybe the second. Could that have anything to do with it?

**Comment by elthehablo** [comment]
> Looked like he was doing Flame Quills when killed in the first video and maybe the second. Could that have anything to do with it?

It shouldn't

**Comment by elthehablo** [comment]
> Looked like he was doing Flame Quills when killed in the first video and maybe the second. Could that have anything to do with it?

I tried killing him during transitioning and during quills but that didn't replicate this issue. It's very strange

**Comment by elthehablo** [comment]
I had a guild reporting on the last test that they managed to get him to p2 fine even though it was breaking a week earlier

**Comment by amed80** [comment]
I don't know if this is related to the same thing but if you wipe while Al'ar transition into p2 (or the rebirth after dive bomb) lets say killed by adds aoe for example ( .combat give the same result) , it may cause it to bug out and the boss either doesn't show up at all or it became untargetable , maybe after it death in those videos , something caused it to go out of combat which led to it not showing up ?

**Comment by heyitsbench** [comment]
Has this been fixed, @elthehablo?

**Comment by elthehablo** [comment]
He-he-heck yeah!
