### ISSUE TITLE
Captured Scarlet Zealot never "Despawns"

### ISSUE THREAD

**Issue by Istox** [chromiecraft/chromiecraft#68]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
The Fields of Grief quest is completable, the problem is what happens after completion; in practice, the NPC to which you deliver the quest receives a Buff that transforms it into a Goul and after a short animation of movement of the NPC it should die and then despawn.

Quest: [Fields of Grief](https://wowgaming.altervista.org/aowow/?quest=407)
NPC_Start: [Apothecary Johaan](https://wowgaming.altervista.org/aowow/?npc=1518)
 NPC_End: [Captured Scarlet Zealot](https://wowgaming.altervista.org/aowow/?npc=1931)

Spell: [Ghoul Form](https://wowgaming.altervista.org/aowow/?spell=3287)

Zone: [Tirisfal Glades](https://wowgaming.altervista.org/aowow/?zone=85) **(Brill)**

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After turning into a ghoul dialogue should be initiated leading to him walking about then dying. See:
Video: [Fields of Grief - Quest WoW Classic](https://www.youtube.com/watch?v=zZIfXkIC4b8)

##### CURRENT BEHAVIOUR:

Just stands there in Ghoul Form forever.
NPC: [Captured Scarlet Zealot](https://wowgaming.altervista.org/aowow/?npc=1931)
Spell: [Ghoul Form](https://wowgaming.altervista.org/aowow/?spell=3287)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Complete [Fields of Grief](https://wowgaming.altervista.org/aowow/?quest=407)
Step 2 Watch the result
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Istox 
**This is how you were supposed to report the Bug**, do "EDIT" and **see how I modified it,** the next time you fail to comply with the Bug Report Form, **the post will be deleted.**

**Comment by Istox** [comment]
I will add as much detail as possible where it is warranted. But this was a very simple case and easy to explain without needing to and fetch links for all the game objects and everything else. All you have done is add a few links to third party wowhead.

Also when i first started reporting a few days ago, all that linking wasnt part of the original new issue template.. Its more important I report issues with adequate details than worry about being a stickler for the template. I also notice you havent said the same on a variety of other issues that dont match your "format" so perhaps you dont like me for some reason.

**Comment by FrancescoBorzi** [comment]
@Istox first of all thank you for reporting issues. We appreciate every effort.

> all that linking wasnt part of the original new issue template.. 

you're right, we've been improving the template in order to make the reports as clear as possible for developers

>  Its more important I report issues with adequate details than worry about being a stickler for the template

the purpose of template is exactly that: making issue reports adequate 

>  I also notice you havent said the same on a variety of other issues that dont match your "format" so perhaps you dont like me for some reason.

this is because the issue report template has been changed, as you mentioned. So there is nothing personal here going on. We will require **new** issues reports to adhere to the new template.

Thanks for your understanding
