### ISSUE TITLE
[TK] Al'ar nad Kael'thas trash not linked to their bosses

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#6818]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Trash in Al'ar and Kael'thas rooms are not linked.

### Expected Blizzlike Behaviour

Trash should pull when engaging the bosses

### Source

https://wowpedia.fandom.com/wiki/Kael%27thas_Sunstrider_(tactics)
https://wowpedia.fandom.com/wiki/Al%27ar

> **Soloing Al'ar**
> Al'ar is straightforward, so long as the room is clear before engaging him. Just stand in one spot (on the ground in the center of the arena) and nuke him. Remember that Al'ar must be killed twice, since it is a phoenix.

### Steps to reproduce the problem

1. tele eye
2. Engage Al'ar or Kael'thas without clearing their rooms
3. Check if the trash packs engage

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
kaelthas trash is not supposed to be linked 
https://youtu.be/YlCfJB7RN6U?t=1968

**Comment by balleny** [comment]
and alar iirc shouldnt be linked either because the boss fight itself encourages you to clear - not totally sure tho

**Comment by amed80** [comment]
> and alar iirc shouldnt be linked either because the boss fight itself encourages you to clear - not totally sure tho

I don't know if there was a change to TK between Wotlk and MoP but this is a [video](https://youtu.be/5gXo_L5J7xo?t=429) of someone doing a solo run in MoP which you can see he skipped killing the adds

**Comment by BeefSteaker** [comment]
Closing as comments above would suggest this is blizzlike.
