### ISSUE TITLE
Mallet of Zul'farrak bug - doesnt recognize as a melee weapon

### ISSUE THREAD

**Issue by abcjinzhu** [chromiecraft/chromiecraft#684]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I finished the mallet of aul'farrak mace quest, but when I equipped the weapon, it does not allow me to use my warrior skills like heroic strike or revenges etc..as the error message keep saying "Must have a melee weapon equipped in main hand"

ss below:
![image](https://user-images.githubusercontent.com/84652656/119247757-6754e600-bb5a-11eb-90a2-9de6626c203f.png)
![mallet of zulfarak bug](https://user-images.githubusercontent.com/84652656/119247769-7b004c80-bb5a-11eb-801b-8c25c2739baa.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I should be able to equip the mallet of zul'farrak and use as a normal weapon and my warrior skills.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Sorry, I wasn't able to reproduce this. I can see you do have some kind of problem. Did you try on another training dummy? Does this give the error on everything you try to attack?
![image](https://user-images.githubusercontent.com/68164076/119249594-89486b80-bb4e-11eb-974f-e14fc6f03bab.png)

**Comment by abcjinzhu** [comment]
I tried everthing. Tried relog, tried un-equip and equip again, tried on mobs and different training dummy, same problem.  I can not equip the mallet of zul farrak by right click, i had to drag it to my main hand weapon slot - which is weird!!

It only works on auto attach now, cant use any warrior skills that require a main hand weapon - cuz it does not recognize as a weapon...

![image](https://user-images.githubusercontent.com/84652656/119260610-93478a00-bba1-11eb-9793-baadc393057f.png)

Pls help, I worked hard for this item.

**Comment by abcjinzhu** [comment]
![image](https://user-images.githubusercontent.com/84652656/119260718-03eea680-bba2-11eb-8a41-e30d620c0bc2.png)

**Comment by anguaive** [comment]
Very strange. I can't reproduce this either.

**Comment by Azcobu** [comment]
Wasn't able to reproduce this either. Had a look at the Mallet in Keira and didn't spot anything odd - it's correctly listed as class 2 (a weapon), subclass 4 (1H mace). The item's flags do have the PLAYERCAST bit set (item's spells are castable by players) which seems a bit superfluous since it doesn't have any spells listed - perhaps quest related? Wondering if it's worth running through the quest chain to get a mallet created 'naturally' by the game instead of just using .additem.

I believe at this point it's also traditional to suggest renaming the Cache and WTF directories on the rather slim chance that it might do something.

**Comment by Stump876** [comment]
It was not equip-able and used to summon Gahz'rilla in vanilla and BC. As of WOTLK, they removed that function, and anyone can summon it. They turned it blue and added some stats to still make it useful to get. Sounds like they just left the cast flag on.

Doing it without GM assistance. Killing the NPC and walking the mallet to the alter and creating it there, and getting the "Made by my character" tag, I was still able to use it. I rerolled a dwarf and tried again just to see if race had something to do with it. No luck.

**Comment by Eldarix** [comment]
![WoWScrnShot_052321_215348](https://user-images.githubusercontent.com/82579073/119272969-66cb5680-bc11-11eb-97dc-f1873e9ce432.jpg)
![WoWScrnShot_052321_215357](https://user-images.githubusercontent.com/82579073/119272980-79459000-bc11-11eb-8de2-2c354fd75523.jpg)

The same here, it seems that it works correctly, I don't know what could be failing for you, good luck :)

**Comment by Stump876** [comment]
@abcjinzhu  As suggested, try renaming you WTF, and Cache folders. Since we can't reproduce this issue it might just be local to you.

**Comment by abcjinzhu** [comment]
I tried renaming, also deleting the WTF folder, no luck =[

**Comment by tabakisp** [comment]
@abcjinzhu is this a stock ChromieCraft client with no addons? also what is your OS, I see custom window borders.

**Comment by 55Honey** [comment]
I have copied the character from the ChromieCraft server to my local PC and did some testing. I can not at all reproduce this problem.

Please close WoW, delete your Cache folder, temporarily rename your WTF and Interface folder and try again. If the problem was solved, please let us know. @abcjinzhu

**Comment by abcjinzhu** [comment]
I run on my MAC OS high sierra, with the decurse addon only. 

Tried deleting Cache folder and renaming WTF and Interface folder. Still no luck, same problem - wouldnt let me equip it unless I drag the weapon to my main hand slot, and still cant use any skills that require a main hand weapon at all..

**Comment by 55Honey** [comment]
Well, i can offer to copy your character on ChromieCraft to my own account and check it there again. However, i'd need to lock it until i am done so there are no further problems.

**Comment by abcjinzhu** [comment]
> Well, i can offer to copy your character on ChromieCraft to my own account and check it there again. However, i'd need to lock it until i am done so there are no further problems.

Sure. pls check, let me know when your done.

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/119703101-7c7d8d80-be56-11eb-912e-4d2238a50ecf.png)
I have copied your character on ChromieCraft to my account and succesfully equipped the Mallet with a right click and could also use abilities on mobs, no problem. I will move the character back and unlock your account as soon as i can @abcjinzhu
