### ISSUE TITLE
Fire Hardened Mail

### ISSUE THREAD

**Issue by SniperGiova** [chromiecraft/chromiecraft#6841]
Chimaera Matriarch doesn't drop the quest item Galvanized Horn if killed in party. I tried 2 times, my loot was free for all. 
When i tried without party it dropped at the first try.

**Comment by Cooties-cc** [comment]
[loot.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/d9a93f21-0c6d-41ca-a624-d3410a6c5614)

Works fine. 1st kill in party with group loot (can see party crown leader icon on frame, and 2nd person in party clicked [Raids]). Quest item isn't 100% drop rate, more around 40% ish (based on WH tables), if going by pserver DB, more around 80%.

**Comment by BeefSteaker** [comment]
no issues in party for me either. its 80% in the database. potentially could be incorrect data from kills without the quest, so if you can find a source you could make a new issue for  the drop rate
