### ISSUE TITLE
Uldaman: Revelosh doesn't drop The Shaft of Tsol

### ISSUE THREAD

**Issue by Buggyswires** [chromiecraft/chromiecraft#685]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Shaft of Tsol (quest item, https://wowgaming.altervista.org/aowow/?item=7741) should be dropped by Revelosh in Uldaman. It is needed to create the staff to open the door to Ironaya.

It dropped in the past, but in the last 5 runs it didnt drop any longer.
Maybe the loot table got messed up by the latest fix: https://github.com/chromiecraft/chromiecraft/issues/559

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Staff of Tsol should drop every time from Revelosh

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Uldaman
2.  Kill Revelosh (https://wowgaming.altervista.org/aowow/?npc=6910)
3.  Staff should drop

##### EXTRA NOTES:

Item: https://wowgaming.altervista.org/aowow/?item=7741
NPC: https://wowgaming.altervista.org/aowow/?npc=6910

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
Hi @Buggyswires! Thanks for the report.

The drop chance of The Shaft of Tsol is 41% according to [classic wowhead](https://classic.wowhead.com/item=7741/the-shaft-of-tsol), which is the most reliable source for vanilla content.

The fix you referenced adjusted the Revelosh loot table to line up with the loot table from wowhead. It currently looks like this:

```
SELECT clt.*
FROM
    `creature_template` ct
    JOIN `creature_loot_template` clt ON clt.Entry = ct.entry
WHERE ct.name = "Revelosh";

+-------+------+-----------+--------+---------------+----------+---------+----------+----------+---------------------------------+
| Entry | Item | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment                         |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+---------------------------------+
|  6910 | 1708 |         0 |      2 |             0 |        1 |       0 |        1 |        1 | Revelosh - Sweet Nectar         |
|  6910 | 3771 |         0 |      2 |             0 |        1 |       0 |        1 |        1 | Revelosh - Wild Hog Shank       |
|  6910 | 4306 |         0 |     13 |             0 |        1 |       0 |        1 |        4 | Revelosh - Silk Cloth           |
|  6910 | 4338 |         0 |      2 |             0 |        1 |       0 |        1 |        3 | Revelosh - Mageweave Cloth      |
|  6910 | 7741 |         0 |     41 |             0 |        1 |       0 |        1 |        1 | Revelosh - The Shaft of Tsol    | <----
|  6910 | 9387 |         0 |     23 |             0 |        1 |       1 |        1 |        1 | Revelosh - Revelosh's Boots     |
|  6910 | 9388 |         0 |     21 |             0 |        1 |       1 |        1 |        1 | Revelosh - Revelosh's Armguards |
|  6910 | 9389 |         0 |     23 |             0 |        1 |       1 |        1 |        1 | Revelosh - Revelosh's Spaulders |
|  6910 | 9390 |         0 |     21 |             0 |        1 |       1 |        1 |        1 | Revelosh - Revelosh's Gloves    |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+---------------------------------+
```

The aowow database viewer you linked is sourced from the AzerothCore database, therefore it's often wrong (plus it seems like it hasn't been updated in a while). I wouldn't recommend using it to look up loot tables because it also has [some other shortcomings](https://github.com/chromiecraft/chromiecraft/issues/675#issuecomment-846381926), but in this case they're not relevant.

Everything is working as it should as far as I can tell, so I'm closing this issue.
