### ISSUE TITLE
Disciple of Naralex ( Wailing Caverns ) disappeared when interacted with.

### ISSUE THREAD

**Issue by Mikel0ke** [chromiecraft/chromiecraft#6858]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Interacted with Disciple of Naralex and he despawned. ( I was in combat, maybe that had something to do with it ).

### Expected Blizzlike Behaviour

He should be interactable to finish the dungeon.

### Source

![report](https://github.com/chromiecraft/chromiecraft/assets/83586527/8709ef98-c5a6-4175-8f06-a67af646a8f8)

### Steps to reproduce the problem

Go inside Wailing Caverns, kill all bosses then interact with Disciple of Naralex.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3bcdc4d23e9b9fa951bf02a74a77a4313078e823

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Mikel0ke** [comment]
update : ran the dungeon again this time, I made sure i wasnt in combat before interacting with the Disciple of Naralex and the event started properly.

**Comment by EldritchtheSnitch** [comment]
This might be related. Just did a WC run through RDF. Cleared all bosses up until Verdan the Everliving, teleported out and back in and the Disciple of Naralex was not there anymore. I do not believe anyone in the group attempted to speak with him prior to teleporting out and back in.

**Comment by TheSCREWEDSoftware** [comment]
I can only reproduce this in CC PTR (can't test on live).

Go to Wailling Carverns, talk to Naralex at the start, kill all the bosses and go back to the npc, he just dissepears. He's suppose to give you a gossip. I got a video of AC and CC PTR if needed.

- `.tele wc`
- `go c i 3671` // Lady Anacondra
- `go c i 3670` // Lord Pythas
- `go c i 3673` // Lord Serpentis
- `go c i 3669` // Lord Cobrahn 
- `go c i 3678` // Disciple of Naralex

**Comment by TheSCREWEDSoftware** [comment]
From @sogladev testing, if you're in Combat he dispawns and thoerically if you go out and go in he should spawn back. I will be linking this issue to AC
