### ISSUE TITLE
minor bug

### ISSUE THREAD

**Issue by hemanmaguy** [chromiecraft/chromiecraft#686]
durator cooper not begin there where the map showed after relog still not there might be under the map 
super minor thing but i though i post it
![cooper](https://user-images.githubusercontent.com/84204078/119256045-f8f63f00-bbbe-11eb-9671-6d9179733ced.png)

**Comment by anguaive** [comment]
Please fill out the issue template that's presented to you when opening a bug report

**Comment by hemanmaguy** [comment]
nevermind
