### ISSUE TITLE
Shadow Labyrinth NPC Murmur ability [Sonic Boom]

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#6861]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

The last boss of Shadow Labs, Murmur has an ability called [Sonic Boom](https://wowgaming.altervista.org/aowow/?spell=33666). I am unable to find what it actually hits for but got hit for 10.5k Nature Damage (See blow).

This damage can NOT be reduced by using abilities such as Shield Wall, Cloak of Shadows, or Divine Shield. 

Here is a death report of my warrior using shield wall. Shield Wall did not reduce Sonic Boom damage but did reduce Murmur's other ability Shockwave. 

![image](https://github.com/chromiecraft/chromiecraft/assets/62799885/d56abf58-43ed-4c15-b7ee-94ecd8c68deb)

### Expected Blizzlike Behaviour

I would expect an ability that reduces **ALL** damage by 60%, would actually reduce the damage. 

### Source

I have no source

### Steps to reproduce the problem

1. Engage Murmur. 
2. Wait for Murmur to cast Sonic Boom.
3. Use an ability that reduces or stops damage. 
4. Compare damage taken to boss ability damage. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3bcdc4d23e9b9fa951bf02a74a77a4313078e823

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
there are certain abilities that are supposed to bypass damage reduction effects, and some also bypass immunities like ice block and pala bubble

**Comment by balleny** [comment]
also, in case this is the aoe that pulses around murmur, this may actually be the reduced damage. This abilities is supposed to kill and not be ignored

**Comment by Manuel91CC** [comment]
I close this report for missing reliable information. Thank you anyway for your report.
