### ISSUE TITLE
[TK] Alar dropping too much loot

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6866]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

alar drops 4 pieces of loot (on the ptr)

### Expected Blizzlike Behaviour

2 pieces pre-nerf
3 pieces post-nerf

### Source

.

### Steps to reproduce the problem

.

### Extra Notes

observed on the timestamp of the ticket

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3bcdc4d23e9b9fa951bf02a74a77a4313078e823

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
in an repeated attempt alar dropped 3 items.
so there seems to be a chance on a 4th item which isnt a recipe.

likely, the ids got mixed up and alar chance for recipes includes a non-recipe item.
worth checking if all regular items are part of the regular loot table and to confirm the other bosses, given we have more loot issues https://github.com/chromiecraft/chromiecraft/issues/6701

**Comment by elthehablo** [comment]
I need to check this out. Couldn't replicate.

**Comment by balleny** [comment]
happend on ptr and live so far

**Comment by elthehablo** [comment]
Oh nvm this is alar

**Comment by elthehablo** [comment]
I will look into it

**Comment by balleny** [comment]
there are plenty more, potential, loot issues. like the tank ring dropping only from 1 type of mob (of which there are 4 in total only in the dungeon) - that may be right but may be wrong, too

**Comment by elthehablo** [comment]
It's weird. Looking at the DB values it looks correct

**Comment by elthehablo** [comment]
maxcount 3 for the items and then 2 10% change options for a pattern

**Comment by amed80** [comment]
out of 20 attempts 3 times i get 4 items (no pattern) and even got 5 items once
![Wow_12%27%31=31-03-2024](https://github.com/chromiecraft/chromiecraft/assets/8395873/581c2eea-6318-4f83-ae40-38e5f599be50)

**Comment by balleny** [comment]
5 items even, amazing

**Comment by balleny** [comment]
as i stated initially, I assume that the pattern slots contain regular loot pieces, hence you see non-recipes in the pattern slots dropping

**Comment by elthehablo** [comment]
Yet they don't. But yeah that does seem to be what is happening

**Comment by elthehablo** [comment]
The culprit seems to be the Talon of Al'ar, it idd sometimes seems to show up instead of a pattern

**Comment by elthehablo** [comment]
I found the problem

**Comment by elthehablo** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/bb0fb20a-14e8-458d-9e5c-2dc02fa6e835)
don't start pinging other devs over nothing please. if you can show me we still get 4x/5x items after this PR then we can open this up

**Comment by elthehablo** [comment]
creature loot template:
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/ed8877d9-7196-4662-8e29-0bba5bf9a7d3)

**Comment by balleny** [comment]
prior state (based on my local, not up2date copy)

Alar overall
![image](https://github.com/chromiecraft/chromiecraft/assets/12682004/ab990de5-b900-4391-86bf-de590f251534)

loot references
![image](https://github.com/chromiecraft/chromiecraft/assets/12682004/b1b4af0d-2413-49a1-acc9-5d03f6b32e01)

referenced reference
![image](https://github.com/chromiecraft/chromiecraft/assets/12682004/5612e06b-98fa-4fac-9eed-67e0404ac3ab)

the PR moved 30448 into 34053 but didnt INSERT 32944 into 34053 too.
now, 34053 is stored in 34377 which isnt referenced anywhere anymore.
hence, 19514 doesnt drop multiple items any more but misses 32944 from the loot table overall

**Comment by elthehablo** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/3e81f456-d0ab-4e67-a0cd-3f9be6ed1aed)
this shouldn't be in your db anymore after the PR

**Comment by elthehablo** [comment]
I don't understand what you mean

**Comment by elthehablo** [comment]
oh you said prior state, that makes sense I guess. Now, yes I was sloppy in not deleting the not referenced reference, but it shouldn't do anything anymore as it's not called anywhere

**Comment by balleny** [comment]
yes, but you overwrote the reference with 1 item only. the reference contained two items

**Comment by balleny** [comment]
you either delete the reference and add both items, or overwrite the refrence with 1 item and insert the other

**Comment by elthehablo** [comment]
Oh okay I see what happened

**Comment by balleny** [comment]
and thats why I pinged when this issue got closed, because it wasnt actually resolving the issue. the PR only solved it partially and created another issue

**Comment by elthehablo** [comment]
Yes I missed that item and confused it with another
