### ISSUE TITLE
Scarab Brooch

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#6879]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Scarab brooch https://wowgaming.altervista.org/aowow/?item=21625#. in any content that has a global healing reduction (think T4 Mythics or whatever the current raid is) Is currently being nerfed twice
The first nerf is the original heal the 2nd heal is the shield that is puts up
Lets say that you cast a heal that heals for 2k, how it should work is 15% of that heal gets put into an absorb shield making it a 300 absorb. How it currently works with the heal reduction is. The first heal will be nerfed by 50% making it a 1k heal and thus the shield would be 150. But since the shield is also nerfed in reality it makes the absorb 75

### Expected Blizzlike Behaviour

This seems to be an oversight when doing the global nerfs, as I really don't think it should be nerfed again as the original cast is already nerfed by 50%, nerfing the shield on top of that makes it pretty much worthless. But if this is absolutly intended behavior feel free to close this

### Source

This was an issue early in the 60 bracket where certain spells would be double dipped by the healing nerf https://github.com/chromiecraft/chromiecraft/issues/3028
https://github.com/chromiecraft/chromiecraft/issues/3027
but as the nerfs are custom there is no "real source" 

### Steps to reproduce the problem

Go to Gruul
activate mythic mode
Active Scarab brooch
heal nerfed and absorb on top of it

### Extra Notes

Like I said this may be intentionally but IMO its pretty terrible to have an item that already takes  a % of your healing and converts it into something else be nerfed again when the original heal is already nerfed 
makes the item pretty much not worth using as it turns normally as the example I posted
Global nerfs turn a 300 shield all the down to 75 after all nerfs are added
And Other spells like living seed and glyph of rejuvenation were fixed a while ago, and this item is still nerfed twice. Saw no other reports for it and this item has laid dormant in my bags since i first tested it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3bcdc4d23e9b9fa951bf02a74a77a4313078e823

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
should then also apply to pvp

**Comment by Nyeriah** [comment]
After the next restart
