### ISSUE TITLE
[NPC weird behavior] Shakes O'Breen and Blackwater Deckhand

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#688]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

(Most likely happens to both factions)

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Fighting a Blackwater Deckhand near Shakes O'Breen (while being hostile/hated with Booty Bay) makes Shakes O'Breen behave weirdly.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No idea but something feels really off.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get hostile or hated with Booty Bay.
2. Attack a Blackwater Deckhand near Shakes O'Breen (without attacking him).
3. Listen all the "Yarr"s Shakes does at you. Only happens when a Blackwater Deckhand is running (he doesn't "Yarr" if a Blackwater Deckhand isn't moving).

##### EXTRA NOTES:

Shakes O'Breen seems to be the only NPC in the area that behaves like that.

(Ingame sound included)
https://user-images.githubusercontent.com/22718174/119266047-3060ed80-bbb7-11eb-8703-76d4fe6ef99c.mp4

Copy-paste of the Shakes O'Breen
```
DB GUID: 11311, current GUID: 1247.
Faction: 121.
npcFlags: 2.
Entry: 2610.
DisplayID: 11358 (Native: 11358).
Level: 40.
EquipmentId: 1 (Original: 1).
Health (base): 1753. (max): 1753. (current): 1753.
Unit Flags: 0.
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 121.
SpawnTime: Full:6m40s Remain:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 1938
Position: -2086.350098 -2028.790039 3.371661.
AIName: SmartAI ScriptName: 
* is quest giver (2)
MechanicImmuneMask: 0
```

Copy-paste of the Blackwater Deckhand
```
DB GUID: 11198, current GUID: 1244.
Faction: 121.
npcFlags: 0.
Entry: 2636.
DisplayID: 11357 (Native: 11357).
Level: 39.
EquipmentId: 1 (Original: 1).
Health (base): 1678. (max): 1678. (current): 1678.
Unit Flags: 32768.
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 121.
SpawnTime: Full:6m40s Remain:0s
Loot: 2636 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 1684
Position: -2102510498 -2044.893555 4.709343.
AIName:  ScriptName: 
MechanicImmuneMask: 0
```

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Shakes has the Civilian flag set (under flags_extra in the creature_template.) The description for that is "CIVILIAN - not aggro (ignore faction/reputation hostility)" which is why he's acting like this. (If there's a flag that governs going 'Yarr' at people I was unable to locate it.) Not sure if he has that flag because he's a questgiver for two quests, but I'd want to see evidence that he did not behave like this during Wrath before removing it.

Incidentally, if anyone else gets confused like I was by the faction ID being 121 when Booty Bay's faction ID is just 21, it turns out that the .npc info display shows the FactionTemplate.dbc data, not the faction ID from Faction.dbc. Faction template 121 is linked to Booty Bay, so that is actually fine.

Anyway, will leave this issue open for a day or so for any further discussion re: his behaviour and then close as working as intended.

**Comment by Synful-Syn** [comment]
I am pretty sure he is still available on Classic and he also seems available on retail and I can't find any changes about him either (except quests and some numbers). He might have the same behavior on both classic and retail, but it's just a matter of finding someone that is willing to ruin their reputation with the goblin cities just to try it out in order to test out an "out of the way" behavior.

One of his quests is to protect him from some mobs that would come at him so it could be some script that makes him behave like that.

https://classic.wowhead.com/npc=2610/shakes-obreen
https://classic.wowhead.com/quest=667/death-from-below
