### ISSUE TITLE
Gravis Slipknot

### ISSUE THREAD

**Issue by RandomlyRadio** [chromiecraft/chromiecraft#689]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Gravis Slipknot is showing as a floating weapon with a massive size difference rather than normal model.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normal model.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Spawn Gravis Slipknot.

##### EXTRA NOTES:

This is the current model in Chromiecraft.
![image](https://user-images.githubusercontent.com/83517900/119299187-127da200-bc24-11eb-96d9-dc412297b55b.png)

This is the model he should have.
![image](https://user-images.githubusercontent.com/83517900/119299308-48bb2180-bc24-11eb-88af-aa24e637bb83.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, his model seems fine when I just checked it:

![WoWScrnShot_052421_202525](https://user-images.githubusercontent.com/81782124/119337630-3ac1db00-bcce-11eb-9652-9d9852b65e0c.jpg)

Please be sure that you do not have any custom model patches installed. If you don't, and you still encounter this error, please let us know.
