### ISSUE TITLE
[TBC The Eye] - Mechanical Units Are Immune To Bleeds

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6901]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

All of the mechanical units in The Eye are immune to bleeds

Crystalcore Sentinel 
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/2a4f4ef3-a1e4-46e6-a4f3-816d779eaed3)
Crystalcore Devastator 
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/21804c55-3a29-4585-ba8a-834f570bc0eb)

### Expected Blizzlike Behaviour

Wotlk client should have all Mechnical and Undead able to bleed. This was changed in patch 2.4

![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/6b92eeb5-cfef-4d5a-b783-db4eee9327e6)

### Source

https://wowpedia.fandom.com/wiki/Patch_2.4.0#Dungeons_and_raids

### Steps to reproduce the problem

1. Enter TK with bleed spell
2. Cast bleed on mechnical units
3. They are immune

### Extra Notes

It not really based around the prog branch, since elementals bled since Molten Core, which was a patch change later. It's also not a surprise a ton of mobs have inconsistent immunities or what not. Long thread about it way back with https://github.com/azerothcore/azerothcore-wotlk/issues/5915 . However seems its more on a base by base change, instead of blanket change atm. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by XC-ahhaVA** [comment]
Wouldn't the "non-corporeal" part restrict that behavior to some mechanical summons or undead wisps like mobs?
Like, for example, the Astral flare in curator event. For the others... maybe Stratholme has some.

The page for Mechanical mobs wasn't update to reflect that change. Patch 2.4 -> 25 March 2008
https://wowpedia.fandom.com/wiki/Mechanical?oldid=1492784 -> 4 July 2008

The above page also lists some examples of mechanical mobs, but none specifically of non corporeal ones.

p.s.
Corroborating evidence of the bleed on void reaver:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4258
https://www.youtube.com/watch?v=HpUR4fvATeo&ab_channel=bigredkitty -> 1:31 and 1:51 -> video from 6 Jul 2008
![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/bd0c7fcc-0a36-46dc-9b4e-4b5d8bdaaf46)
Garrote seen applied on boss. https://www.wowhead.com/wotlk/spell=26884/garrote

And also for Deep Wounds from arms warrior.
![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/2e762088-7e64-456a-8d7b-876e7b105cb1)
https://www.wowhead.com/wotlk/spell=12834/deep-wounds

**Comment by Cooties-cc** [comment]
Patch 2.4 was released March 25th, 2008. This was the patch that introduced the bleed effects. You mentioned Void Reaver as an example, whereas _all_ pre 2.4 wiki pages list him as immune to bleeds. However on April 1st, 2008, the updated info corrected to say that as of patch 2.4, he was now susceptible to bleed effects.  

![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/38a61ba9-4ccf-4d0d-a552-001e79c939cf)
https://wowpedia.fandom.com/wiki/Void_Reaver?oldid=1290220#Notes

This change cannot be coincidence, which means _generally_ all mechanicals and undead were updated to now bleed. I don't think the wiki pages get updated often or super accurately, just enough to start an investigation. 

One _very_ overlooked obvious answer is that all training dummies are _**Mechanical**_ mobs. 
https://wowpedia.fandom.com/wiki/Training_Dummy

I think the 2.4 patch change was a blanket change on the mob types, however, they could have made exceptions to the rule. However this ticket isn't to investigate those exceptions, but rather fix incorrect behavior. 
I still point towards that all mechanical mobs in TK shouldn't be immune to bleeds.
