### ISSUE TITLE
Players turning 180 Degrees in Stuns

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#6906]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Stuns (like rogue's cheap shot and druids pounce) will sometimes cause players to turn 180 degrees (sometimes not even visually)
This is a big deal because your highest damaging abilities on these classes require you to be behind the target

### Expected Blizzlike Behaviour

Players shouldn't turn around mid stun 

### Source

This just shouldn't happen

### Steps to reproduce the problem

1. Use any stun on Player 
2. Player might turn around

### Extra Notes

This was an issue a while back and it seems to either have never gotten fixed or seems to have regressed to now work on players
(used to be only mobs)
https://github.com/chromiecraft/chromiecraft/issues/2605

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
:x: I cannot reproduce this on [30a790117be921ed0eff513322af1793995b2b4d](https://github.com/azerothcore/azerothcore-wotlk/commit/337135bf9e409d97628f6f8778d32433991058fc)
I tested cheapshot, gouge, backstab, and the enemy player is not turning 180.

If someone has multiple accounts on PTR can also test, and reopen if necessary.

**Comment by Never6** [comment]
> ❌ I cannot reproduce this on [30a790117be921ed0eff513322af1793995b2b4d](https://github.com/azerothcore/azerothcore-wotlk/commit/337135bf9e409d97628f6f8778d32433991058fc) I tested cheapshot, gouge, backstab, and the enemy player is not turning 180.
> 
> If someone has multiple accounts on PTR can also test, and reopen if necessary.

idk what you were doing to test it or what, I wish i knew how to reproduce it  but I can assure you this is a bug and it happens in PvE as well as pvp.
As far as how to reproduce, i have no clue, sometimes it just happens and sometimes it doesnt 
https://youtu.be/8vMpAOuwCEo?si=PA2sZYgEpT4K_dMI&t=17 but here u can clearly see it happens
i shred before shockwave (shred can only be casted from behind) then shockwave lands, The mob doesnt turn around visually but he does on the server side so his Back is now his front which is why I have to move to his front to shred him
after shockwave ends he reverts to being normal (meaning front is now front and back is now back)
my only advice, just play the server, you will see it happen i promise
now reopen it
