### ISSUE TITLE
Furious howl [inocrrectly applies buff to whole party instead of just master and pet] spell=24604

### ISSUE THREAD

**Issue by unexpect3d** [chromiecraft/chromiecraft#691]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

SPELL [Furious Howl] spell ID=24604

incorrectly applies the buff to other party members.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

_Increases melee and ranged attack power by 18 for_ **the wolf and its master** _for 20sec._

Should only apply buff to master and its pet. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be hunter class.
2. Have Wolf pet.
3. Be in a party with other characters. Be close to them. 
4. Use pet ability: Furious Howl. 
5. Notice as buff applies to whole party members. 

##### EXTRA NOTES:

Link: https://wowgaming.altervista.org/aowow/?spell=24604

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by fendwe** [comment]
This seems to be working correctly now.

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/6047
