### ISSUE TITLE
[TBC Netherwing] - Dragonmaw Race: The Ballad of Oldie McOld NPC Breaks

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6943]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Doing the quest [Dragonmaw Race: The Ballad of Oldie McOld](https://wowgaming.altervista.org/aowow/?quest=11064) the NPC seems to break hard. If you fail and wait on respawn, he sometimes does not get back on a mount (as seen in webm). He doesn't fly his correct path. The pumpkins don't seem to dismount you. Tried 3 times, and he disappears at the same spot, failing the quest. 

[wut.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/ba2c15b8-fb16-40a8-a3e8-eab7b7594afe)

### Expected Blizzlike Behaviour

He flies slower, throwing pumpkins which dismount, and does ~2 loops around airfield. 

### Source

Can't actually find a TBC classic vid, only retail versions or other pservers. Not sure those would be 100% accurate. 

### Steps to reproduce the problem

1. Accept Dragonmaw Race: The Ballad of Oldie McOld tbc classic
2. Watch NPC zoom around and fade out

### Extra Notes

I'm going to guess all the pathing on these quests is busted up. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> The pumpkins don't seem to dismount you.

The pumpkins do not dismount on Wrath Classic, only a small pseudo-stun.

**Comment by heyitsbench** [comment]
Based on some Wowhead comments, it sounds like these races were nerfed with 3.3, originally they apparently did dismount, but no longer do.

**Comment by Cooties-cc** [comment]
Yeah could add the dismount to prog mod, later removing it. Or just have it be the mini stun to simplify the problem. Overall all the races are probably messed up and can't really be tested without .quest complete command enabled on PTR (or on own AC client). These chains give a lot of rep (3200) and reward you with the 10% mount trinket, so they aren't some trash side quest stuff.

**Comment by arcosin** [comment]
Either way, this quest is non-functional for me. I'm not sure it's currently possible to win. In my case, he just disappears after a few seconds of flying. with or without a mount visible on the model.
