### ISSUE TITLE
Rage generation

### ISSUE THREAD

**Issue by Xykyta1** [chromiecraft/chromiecraft#6956]
Class - Warrior. Got no rage if mob dodged and parried my autoattacks. Parried, dodged and blocked player`s attacks should generate base rage - without "damage factor" in formula.

**Comment by heyitsbench** [comment]
Please fill out the template.

**Comment by Xykyta1** [comment]
> Please fill out the template.

What is the template? I dont see any templates here

**Comment by heyitsbench** [comment]
> What is the template? I dont see any templates here

Hit the `Get started` button, that is the template.
