### ISSUE TITLE
The Shattered Halls - mob packs chain pulling

### ISSUE THREAD

**Issue by XC-ahhaVA** [chromiecraft/chromiecraft#6961]
### What client do you play on?
enGB

### Faction
Both

### Content Phase:
Level 70 - Tier 5

### Current Behaviour
In the Shattered Halls dungeon, there are some issues with the packs that are placed in the room after Blood Guard Porung (in that big long tunnel).
Basically if you pull 1 pack. Eventually after some time the nearest pack down that tunnel will also be pulled. This eventually chain triggers to the point that 5 packs are pulled.

### Additionally
In the room before Grand Warlock Nethekurse, the one that has the door locked, the same happens. If you pull the pack there, eventually all mobs that were sleeping will wake up, regardless of how far back you pull the original pack into.

This happens on both normal and heroic versions.

### Images
![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/f93314ba-35ff-4650-9d17-bed387671270)

![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/8fb96b2c-25c1-4719-b813-56f90d1ff36b)
Notice green mark mob from original pack that was pulled and others all the way back to orange circle mark mob.

### Expected Blizzlike Behaviour
Mob packs should not chain pull. Nor chain pull with a delay. They should be independent.

### Source
TBC Classic - dungeon run - where they accidently pull 1 extra pack, but not the whole tunnel.
So in case it was some mob "calling for help" spell, it should have also triggered there.
https://youtu.be/FoSHqeb4lPA?t=1940

### Steps to reproduce the problem
Go to SHH in test realm. Put god mode on. Fly/kill mobs that do not matter.
Pull packs and see which packs end up also chain pulling past some time.

### Extra links
https://www.wowhead.com/tbc/npc=20923/blood-guard-porung
https://www.wowhead.com/tbc/npc=16807/grand-warlock-nethekurse

### Operating system
Windows 11

### Modules
Just basic add ons.

### Customizations
None.

### Server
ChromieCraft

**Comment by Tharabas87** [comment]
Hello I've tested the issue intensively and maybe I come to a conclusion.

It appears that some mobs are linked togheter for some reasons.
In particular ****"Shattered Hand Heaten"** in the first pack (GUIDS: 17420 ENTRY: 151134; 151136)** are linked to the ****"Shattered Hand Savage"** (GUIDS: 16523 ENTRY: 151165; 151167)** just behind the pack hiting the dummies.
The **"Shattered Hand Heaten" (GUIDS: 151167 ENTRY: 17420)** is linked with **"Shattered Hand Reaven" (GUIDS: 151169 ENTRY: 16699)** hiting the mannequin after the second room.
Same happens for the second pack in the second room where the **"Shattered Hand Heaten" in the pack (GUIDS: 151140 ENTRY: 17420)** appears to be linked to first its **ALL PACK** and second to the **"Shattered Hand Savage" behind him (GUIDS: 151173 ENTRY: 16523)**.
So whenever a player inside the dungeon is killing one of those npc the linked one gets aggroed, runs towards the group and the result it's a domino effect/chain pull that leads almost all the npcs on in the corridor to attack the team.

**Comment by TheSCREWEDSoftware** [comment]
I can't seem to reproduce this in either AC or the CC PTR, will tag this issue to see if anyone of the team can check this issue on CC Live. 

I will leave this with triage in progress but also unable to reproduce.

**Comment by TheSCREWEDSoftware** [comment]
Can't reproduce this issue neither in CC live
