### ISSUE TITLE
The perfect storm achievement (1600-0) not working.

### ISSUE THREAD

**Issue by Milecc** [chromiecraft/chromiecraft#6962]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

The ''The perfect storm'' achievement is not working.  https://wowgaming.altervista.org/aowow/?achievement=783 
After few players whispered me that their game didnt count for 1600-0 achievement  (in 2024).  i have decided to test it on ptr and ended up with same conclusion.
![eots](https://github.com/chromiecraft/chromiecraft/assets/165961786/9414f8a2-10c7-445e-ab3f-e00933c01de1)

### Expected Blizzlike Behaviour

If team gets perfect victory, meaning enemy doesnt manage to get even one point, achievement should trigger.

### Source

https://wowgaming.altervista.org/aowow/?achievement=783

### Steps to reproduce the problem

Just join PTR Eye of the storm battleground and  finish the game with perfect result 1600-0, and see the issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sudlud** [comment]
azerothcore/azerothcore-wotlk#11998

**Comment by sudlud** [comment]
Thanks for the report, is this only broken for alliance?

In the linked issue above I had tested this for horde and found no issue some while ago.

**Comment by Milecc** [comment]
I have tested it for horde and alliance and both didnt work yesterday.
