### ISSUE TITLE
[TBC Hyjal Summit] - Doomfire ticks Deals No Damage

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6970]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

[df.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/45059817-fce6-4ec2-a4d6-a8c2865db06b)

Doomfire currently deals no damage, ~~either entering and staying in it~~, or via the debuff.

### Expected Blizzlike Behaviour

The fires should deal 2.4k dmg per tick while standing in the fire. The debuff should start at 2.4k on 1st tick, and lower the damage for each tick after by 150 damage each time. The debuff does **NOT** stack, but can refresh when stepping into the fire. 

### Source

https://www.wowhead.com/wotlk/npc=17968/archimonde#comments
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/1f8a8049-bf24-43f9-9cab-322f84e32d1b)
https://www.wowhead.com/wotlk/spell=31944/doomfire
https://youtu.be/ftQoYnr7zbo?si=sI69tJjRTY6M6xKT&t=123
https://youtu.be/SxbjsCtBhsU?si=p5aVLym8_SarD1cU&t=251

### Steps to reproduce the problem

1. Enter Hyjal and fight Archimonde
2. Stand in fire and get debuff

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
After doing more test on this , Doomfire does deal damage on the first impact but it doesn't show on the combat log i think this is related to NPC that dealing damage is invisible , the same problem happens with Kael'thas phoenix when they are in egg form , and currently can fire deal too much damage i assume because the fire is moving too slow or it's putting too much fire on the same place leading to people getting one shotted , maybe the invisible NPC moving in circle on the same place ?
For the 45sec dot still deals no damage
