### ISSUE TITLE
[TBC Hyjal Summit] - Archimonde Doesn't Cast Finger of Death

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6971]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Archimonde doesn't cast Finger of Death when there is no melee target within range

[fod.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/0eaa5c51-1c4a-458f-8e0a-a9efc319c958)

### Expected Blizzlike Behaviour

He should cast this when there is no melee target in range of him. 

### Source

https://wowpedia.fandom.com/wiki/Archimonde_(tactics)#Abilities
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/0ec5cc88-3957-4c9d-a132-da34cbb0418e)
https://www.wowhead.com/wotlk/npc=17968/archimonde#comments
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/f1aeb6e1-5974-4806-ad72-098c23e7638b)
https://www.wowhead.com/wotlk/spell=31984/finger-of-death#comments
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/a6a4b4fe-e425-4338-8839-cdc8b4ecd6bb)

### Steps to reproduce the problem

1. Fight Archimonde
2. Run away out of melee range

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
If I'm reading the script right, he does cast it, but only when he's below 10% health.

**Comment by Cooties-cc** [comment]
> If I'm reading the script right, he does cast it, but only when he's below 10% health.

You might be reading the other death spell, Hand of Death. That goes off on 2 occasions. 1 - you hit enrage timer (9 minutes). 2 - you killed him (he technically dies at 10%). One death he spams the spell, but you have a buff that protects you from it. 

You can see the Hand of Death casts here after 10%
https://youtu.be/dOkiwje10dM?si=jeHdGxhn1cxU1ASy&t=183

Maybe there is a chance that Finger of Death is falling into the same restrictions as Hand of Death?

**Comment by heyitsbench** [comment]
You can see the Finger of Death cast in the script [here](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp#L286), contained and scheduled within the 10% health check, where Hand of Death is also scheduled.

**Comment by Cooties-cc** [comment]
I find it odd that there's 2 FoD events. One being normal, and one for "[phase 4](https://github.com/azerothcore/azerothcore-wotlk/blob/3a93ae1af1158f552838375f454c9dff6d3bc95b/src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp#L88)". Checking some comments, I think the oldest one about his abilities is from [a thottbot post](https://web.archive.org/web/20070707223414/http://thottbot.com/c17968) about 13 days after his page was created (by Shinji_Okuzawa). You can see he states that the FoD will be free cast if no melee are in range of the boss. 
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/bb1d4d38-dc84-4054-aef7-6d8ed60df960)
My guess was this spell was designed to prevent "kiting" the boss around? I'll keep searching if I can find some video somewhere that actually shows a cast above 10% hp.

**Comment by Cooties-cc** [comment]
Yeah I went over like 15+ vids, tbcc and original, and couldn't find an instance in which players were out of melee range enabling him to cast FoD. However I did more digging on the code section, and found some _slight_ possible problems. 

To start, I thought it was odd he had 2 FoD event calls, so I checked the spells out. Turns out, there are 2 finger of death spells used by Archimonde. Spell ID [31984](https://www.wowhead.com/wotlk/spell=31984/finger-of-death) is the correct one I've been saying that should be cast if there is no melee target while people are in combat with boss. You can check in the [comments](https://www.wowhead.com/wotlk/spell=31984/finger-of-death#comments) section as well, as it's said many times it's done when no melee in range and boss is engaged. 

This brought me to the [2nd finger of death spell](https://www.wowhead.com/wotlk/spell=32111/finger-of-death). You can see it uses the spell ID 32111. Checking back in the CC boss scripts, that is however labeled as "[SPELL_RED_SKY_EFFECT](https://github.com/azerothcore/azerothcore-wotlk/blob/3a93ae1af1158f552838375f454c9dff6d3bc95b/src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp#L47C5-L47C25)". This leads me to think that this spell is _only_ cast during the kill RP phase when every player gets an immune shield, since this version only has a range of 80y and is counted as a "tower". Tower to me implies his strict stationary behavior during his death phase. 

I also went in the PTR and checked what was being cast during the death phase with immunity bubble, and both 31984 & 32111 were being rotated cast. I would think it is suppose to only use 32111 during the death phase, since using both spells makes no sense. 

Overall I don't think looking at the AC code for the boss will do much good to find a correct answer, since odds are to me it's not scripted in, so you're checking for something that doesn't exist as an event. All the spells are in there, just not the right trigger for normal FoD. I think 31984 should be taken off the death phase (only use 32111), and a script of some kind should be written for 31984 for when there's no enemy in melee range when boss is engaged. Probably need some update check of 2-3 seconds maybe so he doesn't just insta cast when starting the pull lol.

**Comment by amed80** [comment]
Adding this here which it shows he cast [Finger of Death](https://wowgaming.altervista.org/aowow/?spell=31984) even before 10%

https://youtu.be/o2thG7neNkI

it looks like he have 10sec delay before using it ?
