### ISSUE TITLE
Archmage Leryda not giving any quests besides "Archmage no more"

### ISSUE THREAD

**Issue by Aslyte** [chromiecraft/chromiecraft#6980]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

![image](https://github.com/chromiecraft/chromiecraft/assets/153112690/de7f3897-4853-4ac5-9f7c-a9a9f7231bf8)

She supposed to give all the ring quests, but she is only giving this one, i have the DPS ring, i want to exchange for the Healer ring.

### Expected Blizzlike Behaviour

![image](https://github.com/chromiecraft/chromiecraft/assets/153112690/b9ef95f6-5419-4b5e-8c1c-981575d9f44b)
She should give all these 4 quests.

### Source

Chromiecraft

### Steps to reproduce the problem

Just talk to the NPC.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
https://us.battle.net/support/en/article/289285
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/b09a3509-92c0-4096-b1f1-9961d965f3fe)

I think this works as intended ?

**Comment by Aslyte** [comment]
Thx amed80, it worked: i've destroyed my DPS ring and then she gave me the archmage link
