### ISSUE TITLE
Estelle Gendry does not give tools

### ISSUE THREAD

**Issue by Nosreme70** [chromiecraft/chromiecraft#6981]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

The NPC estelle gendry in Undercity is supposed to give me tools to complete the quest Tools of teh Trade but the link does not work, she does not give any tools. I've tried rebooted and it doesn't help. 

### Expected Blizzlike Behaviour

She should give tools when you click the link of text when you talk to her

### Source

I'm not sure what sources you need here. The quest doesn't work.

### Steps to reproduce the problem

1. get the rogue class quest Tools of the Trade.
2. Talk to Estelle Gendry and when prompted in speech, click the link to receive tools to complete the task.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
Can confirm. Made a (undead, not sure it matters) rogue alt on PTR and went to level 25. TPd to UC and got the starting quest [Fenwick Thatros](https://wowgaming.altervista.org/aowow/?quest=1998). Gave self item, and got follow up, [Tools of the Trade](https://wowgaming.altervista.org/aowow/?quest=1999). Tried to go to [Estelle Gendry](https://wowgaming.altervista.org/aowow/?npc=6566) and talk to her for a set of [Thieves' Tools](https://wowgaming.altervista.org/aowow/?item=5060). Her chat option when clicked does nothing. I gave myself a set of Thieves' Tools, and she still had a chat option (she shouldn't when you have a set). I then del that set, and she still wouldn't give me a set. Overall not working one bit. 
Note in [comments](https://www.wowhead.com/wotlk/npc=6566/estelle-gendry#comments) a few things : 
- She does not talk to you if you have the tools
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/20204b27-1cf1-4642-98b2-085a0b7e800c)
- She does in fact give the tools
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/1fbd5b2f-6b1d-4a24-a797-b6e4487cd56e)
- Early on ppl seem to even make a comment that she might've been buggy
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/530186cb-52ae-4f74-b259-97da1fa0aca3)

**Comment by Nosreme70** [comment]
I've learned the tools were removed from the game.  They're not needed to do the quest any longer.

**Comment by veredis1** [comment]
than u can close the ticket probably :]
