### ISSUE TITLE
[Hyjal] Kaz'rogal's Mark of Kaz'rogal have wrong timer

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#6983]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Kaz'rogal](https://wowgaming.altervista.org/aowow/?npc=17888)'s [Mark of Kaz'rogal](https://wowgaming.altervista.org/aowow/?spell=31447) always being casted after 45sec
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/2ad77e42-c734-4f44-9d8d-40c357f5d791)

### Expected Blizzlike Behaviour

Only the first [Mark of Kaz'rogal](https://wowgaming.altervista.org/aowow/?spell=31447) happens after 45sec into the fight then the timer is reduced by 5 sec until it reaches 10 sec (cap)

### Source

[WarcraftTavern Guide](https://www.warcrafttavern.com/tbc/guides/kazrogal/)
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/813909a1-d9b8-4d2d-a737-a45538e2df8b)
[Wowpedia Guide](https://wowpedia.fandom.com/wiki/Kaz%27rogal)
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/e4f137ba-0d4c-450a-a3c6-76970449b6af)

[Wotlk Classic Solo](https://youtu.be/zGxYtL6Tdfk) you can see dbm timer (from the 8th mark and later it's always 10sec)

### Steps to reproduce the problem

1. .tele hyjals
2. Fight Kaz’Rogal

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
I will try to triage this tonight. The function called in repeat should enable the behaviour you described

**Comment by elthehablo** [comment]
The screenshot you provided does not immediately make it clear the ability is indeed always cast in-game after 45s, because it clearly shows a function being called that determines the repeat timer.

The issue could still be that that does not work for some reason.

But it is not immediately evident from the screenshot you provided that it should not work.

**Comment by amed80** [comment]
Yeah still new to understand those codes 😅 , i remember even at his 20th mark is still 45sec
didn't see this at first 
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/9d9a5943-3a96-435a-b712-a9df20976907)
but my thought is probably because the _markCounter is set at 0 without any thing to add +1 for it ?

**Comment by elthehablo** [comment]
> Yeah still new to understand those codes 😅 , i remember even at his 20th mark is still 45sec
> didn't see this at first 
> ![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/9d9a5943-3a96-435a-b712-a9df20976907)
> but my thought is probably because the _markCounter is set at 0 without any thing to add +1 for it ?

Yep that is definitely why then. I hadn't looked at the code myself yet.

**Comment by amed80** [comment]
yeah adding _markCounter = _markCounter +1; looked like it fixed it for me
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/4cc63c05-fb9d-4c8a-af19-e1f1544ee548)

**Comment by elthehablo** [comment]
> yeah adding _markCounter = _markCounter +1; looked like it fixed it for me
> ![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/4cc63c05-fb9d-4c8a-af19-e1f1544ee548)
> 

We do ++_markCounter; for counters. Wanna make the PR yourself?

**Comment by amed80** [comment]
can you do it ? 
i am new to this and know absolutely nothing about coding 😅

**Comment by heyitsbench** [comment]
> i am new to this and know absolutely nothing about coding

You've already done the hard part. 😛

**Comment by elthehablo** [comment]
No better way to learn than by doing.

**Comment by amed80** [comment]
well i made an attempt , idk if that's how it works ...
