### ISSUE TITLE
[Transmog] Megathread for Transmog issues

### ISSUE THREAD

**Issue by UnePomme** [chromiecraft/chromiecraft#6984]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

*Note I do not have a version of retail to test these features in a blizzlike environment. If some of these should be labeled suggestion, I will move them over.

1. **Unnecessary Accept/Cancel button.**
Expected: Once the "Search" button is pressed, the "Please enter code:" screen should display.
 ![image](https://github.com/chromiecraft/chromiecraft/assets/44067875/21043a40-34e8-4ed2-b86c-d2a8ce512fb2)

2. **Text says "Please enter code:" suggesting item codes are able to be searched for, which *seems in testing* incorrect.**
Expected: Ability to search with item code, or less confusing text "Please enter item name"
 ![image](https://github.com/chromiecraft/chromiecraft/assets/44067875/be18b7f4-85c2-44f3-8520-1c25ae928b65)

3. **Pressing "Enter" on your keyboard at the "Please enter code:" screen will emulate the "Cancel" button press.**
Expected: Keyboard "Enter" press should emulate "Accept" button.
 ![image](https://github.com/chromiecraft/chromiecraft/assets/44067875/be18b7f4-85c2-44f3-8520-1c25ae928b65)

4. **Transmog search is case sensitive.**
Expected: ability to use non-case sensitivity for the search

5. **Missing White Transmog items for Tier 3 Sub (Time Keeper)**
- [[Chest] Vestment of Summer](https://wowgaming.altervista.org/aowow/?item=34685)
- [[Feet] Sandals of Summer](https://wowgaming.altervista.org/aowow/?item=34683)
- [[Shoulder] Mantle of the Fire Festival](https://wowgaming.altervista.org/aowow/?item=23324)

### Expected Blizzlike Behaviour

*Listed underneath each issue in Current Behavior

### Source

.transmog portable

### Steps to reproduce the problem

1. Go to tmog vendor
2. Attempt one of the steps listed in Current Behavior

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
We dont use megathreads and each issue needs to be reported in their own report
