### ISSUE TITLE
[Hyjal] Azgalor's Doom can be casted on the MT

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#6986]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Azgalor](https://wowgaming.altervista.org/aowow/?npc=17842)'s [Doom](https://wowgaming.altervista.org/aowow/?spell=31347) can be casted on the MT

https://github.com/chromiecraft/chromiecraft/assets/8395873/7978ee5c-fafc-46ae-a03c-0bb669dcb9b1

### Expected Blizzlike Behaviour

[Azgalor](https://wowgaming.altervista.org/aowow/?npc=17842)'s [Doom](https://wowgaming.altervista.org/aowow/?spell=31347) shouldn't have the MT as a possible target.

### Source

[Wowhead comment](https://www.wowhead.com/tbc/spell=31347/doom#comments:id=230457)
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/d22b2504-c903-4b01-b969-fd202153df59)

[Wotlk Classic Solo](https://youtu.be/-uP7OdsehZ0) Azgalor didn't use Doom for the whole fight as the prot paladin is the only player in the raid and he is the highest on threat

### Steps to reproduce the problem

1. .tele hyjals
2. Fight Azgalor

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
This problem still exist.
Doom will not be casted if you are solo but if you are in a raid , Doom can target the MT

**Comment by amed80** [comment]
more source and clips in this report #7066

**Comment by heyitsbench** [comment]
![Still valid issue](https://github.com/chromiecraft/chromiecraft/assets/38561765/84dd17c8-7f88-4f0e-b21a-71f815ac55fd)

**Comment by heyitsbench** [comment]
Hopefully resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/79ec83d03e0a9534331606f1223bcf62a51fd4f7.
