### ISSUE TITLE
Starting zone NPC position

### ISSUE THREAD

**Issue by Yehonal** [chromiecraft/chromiecraft#7]
We need to import this commit asap. It's an important one to improve the blizzlike feeling

https://github.com/azerothcore/azerothcore-wotlk/commit/e1636237dfc724054c3ccc90c825df51cc19b611

**Comment by Hacaw** [comment]
Which commit ? Link typo ?

**Comment by Si1ker** [comment]
just update the core, my PR is already merged into AC
https://github.com/azerothcore/azerothcore-wotlk/pull/4010

**Comment by Helias** [comment]
Updated, need to find the right time to restart the server
