### ISSUE TITLE
Quest Item "Hardened Tumor" has too high drop rate for 3.3.5

### ISSUE THREAD

**Issue by Istox** [chromiecraft/chromiecraft#70]
##### SMALL DESCRIPTION:
As the title explains. See comments on here for patch 3.3.5 for evidence:
https://www.wowhead.com/item=3258/hardened-tumor

In particular:

"Kokusmus on 2010/03/27 (Patch 3.3.3) its not changed for sure just done the quest and it took **at least 20 kills** to drop 1"

"Bengarion on 2010/08/28 (Patch 3.3.5) **After ganking untold minions**, I followed your suggestion. Second drop - level 12 no less. Thanks! (This may be just a fluke - but this bunch is a lot lower level so it would be much quicker to go through the number of kills for it to drop.) So there!"

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Should be 5% drop

##### CURRENT BEHAVIOUR:
100% drop?

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Player comments (unless documented) cannot be considered "Evidence".

Today you gave me a lot to do with your Reports, in fact (for example), I spent the last 3 hours looking for (True Evidence) about the Drop Rate of this Item, and after looking in ALL the Patch Notes of WOTLK starting from 3.0.2 up to 3.3.5a and after having done 10,000,000 searches on this Item on Google, when I received an email from Mr.Google who told me: "it is useless to search, so there are no documents of the Drop Rate of this Item".
I realized that today I could use my time to fix a spell or something else, instead I did research that it was better if you did, before posting a Bug that most likely Bug is not.

But that's okay so feel free to Report anything you deem necessary, even if your knee itches let us know, let's see how to fix it..

**Comment by Istox** [comment]
Stifler. A players job is to find **potential** issues and report them that's it. Its isn't a job, I don't get paid to be here, I'm spending my own free time deliberately going through the game in a way that isn't optimal for my own fun finding all possible issues for this project because the very nature of the project that Chromiecraft claims is to improve the overall quality of emulation for everyone, so you might want to drop the sarcasm and have a little more respect for those trying to help. It is the Vetter or triage job to turn **potential** issues into **confirmed** issues.

You act like you are hard done by like im flooding useless reports but In the last 3 days my "knee itching" has reported 9 bugs. Of those 6 confirmed, 1 Confirmed-WontFix and 1 Confirmed-Dupe. So in total 8 of 9 of my reported issues were completely valid and useful to the project and what it stands for. Its only this one that is not confirmed. So dont talk to me about "even if your knee itches let us know".

In this particular case all minor issues, "knee itching" as you put it, that **may have** and impact on RP or game quality for everyone that might play on **any server that uses this core** in the future are also completely valid and worth investigation.. not just issues that you as an individual think are important. 

You assert that im making an assumption. But in reality it is you making the assumption, you are assuming that "The current state of the droprate is correct" On what basis? If you had to provide evidence that the current state of the quest is correct? You wouldn't be able to provide any at all. Atleast in this case I was able to provide **some** evidence that that droprate may not be correct which gives it merit to be looked into. So dont go around telling people that they are making assumptions before you have got you logic straight.

Anyway you wont have to put up with it anymore, players shouldnt have to put up with sarcastic comments from someone as illogical as you when they are just trying to be helpful to the cause behind the project. Ill go find somewhere else to spend my time.

Have a good one.
