### ISSUE TITLE
Cyclone

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#7008]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

https://wowgaming.altervista.org/aowow/?spell=33786#. has a bug where you can reapply buffs during the duration
like hots etc.

### Expected Blizzlike Behaviour

When a target is cyclone they are banished and immune to everything 
this includes getting any healing/damage (that works fine)
and buffs like a druids hots
how it currently works is you can apply hots during cyclone when a target should more or less be out of the game for 6seconds

### Source

https://www.wowhead.com/spell=33786/cyclone#comments
wowhead comments were my best option
but ive watched and played pvp for years and I have never not once seen a druid reapply lifebloom into clone

### Steps to reproduce the problem

get 2druids
1 druids cyclones some 3rd person
2nd druid can reapply hots/lifebloom

### Extra Notes

This is a big deal as cycloning off a targets 3 stacks of lifebloom when they are at 40% HP is a really big deal
now the druid can just reapply lifebloom which shouldnt be a thing
Edit: I should note its not just lifebloom but probably most buffs, So for example you can innervate into cyclone. what is supposed to happen is that innervate gets lost forever, instead you will just get buff, while you still get no mana from it, thats just not how the spell is supposed to work
### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
checked some pvp videos in wotlk classic:
[Rdruid in 2s](https://youtu.be/DSqDsotWzFo?t=3756) at 1:02:37 and 2 seconds after , the DK is in Cyclone and the Rdruid tried to use Lifebloom and it was immune twice as you can see it didn't add stacks or refresh the one that's already on the DK.
[Another Rdruid in 3s](https://youtu.be/Xt-il1uFtQs?t=3644) at 1:00:47 , the Rdruid uses Wild Growth and it was immune on the DK and no one in the party got the HoT.

Here is clip from PTR , where Lifebloom is refreshing and adding stack and also Wild Growth can be used and even put the HoT on the party when it shouldn't.

https://github.com/chromiecraft/chromiecraft/assets/8395873/b5d6f29c-5a94-4695-bb36-cb0a6d5eb593

**Comment by heyitsbench** [comment]
Are DoTs/HoTs supposed to continue to tick while cycloned or does the target get immunity from the ticks?

**Comment by amed80** [comment]
From those videos i see the hots are still ticking but the target is not getting any heals which is working correctly atm.
From this [video](https://youtu.be/gZlA9_t4DDQ?t=705) at 11:45 , you can see the rogue is in cyclone and the dot (i believe that's Devouring Plague) is ticking but he's taking no damage. (didn't test this in PTR)

There is also this in cyclone wowpedia page (didn't test it yet) but looking at it you can assume that the target will take no damage during cyclone.
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/bc9355e1-3a5a-4a5b-937a-a57a4842866c)

**Comment by Never6** [comment]
> Are DoTs/HoTs supposed to continue to tick while cycloned or does the target get immunity from the ticks?

they continue to tick but youget no damage or healing from it
which like started that part works, if you are in a cyclone you do not receive any healing or damage from sources
but just to clarify the bug is that you can reapply hots on a cyclone target which shouldn't be possible

**Comment by alecsci** [comment]
I also reproduced the behavior on https://github.com/azerothcore/azerothcore-wotlk/commit/fc735e37a2166bbb39b272abd6950a5ae70ae761 but since the tick from HOTs do not apply any healling, what's the impact in player experience ? They just waste mana 🤔

**Comment by Never6** [comment]
> I also reproduced the behavior on [azerothcore/azerothcore-wotlk@fc735e3](https://github.com/azerothcore/azerothcore-wotlk/commit/fc735e37a2166bbb39b272abd6950a5ae70ae761) but since the tick from HOTs do not apply any healling, what's the impact in player experience ? They just waste mana 🤔

the impact is that
they reapply hots, which the entire purpose of cyclone is to make it so the druid cannot reapply hots.
also 3stacks of lifeblooms heals for a lot
so negating all that healing on say a target that is 40% health is a really big deal

**Comment by Never6** [comment]
> I also reproduced the behavior on [azerothcore/azerothcore-wotlk@fc735e3](https://github.com/azerothcore/azerothcore-wotlk/commit/fc735e37a2166bbb39b272abd6950a5ae70ae761) but since the tick from HOTs do not apply any healling, what's the impact in player experience ? They just waste mana 🤔
its more than a "really big deal" its actually game changing

i had a 2v2 earlier where i cloned the warrior low ~40% with no hots up
and cyclone was coming off dr on the resto druid
The goal of my clone on the warrior is to do many things
but the most important is that it ensures I get a full cyclone on the healer as warrior is CC'd he has no way of stopping
and i cloned the warrior when he had 0 hots up which actually allows me to burst him while healer is CC'd
but since the druid can reapply i get 0 pressure cause hes allowed to full hot him in cyclone which shouldn't be possible 
and since you're a class without mortal strike you get screwed over when you played something correctly
not sure why this needs a 2nd opinion after 5months considering someone linked videos from classic but oh well i guess
