### ISSUE TITLE
Somnus not patrolling in Swamp of Sorrows

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#701]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Somnus, the big green dragon in Swamp of Sorrows, is currently static. He should be patrolling: https://www.wowhead.com/npc=12900/somnus#comments
DB GUID: 42880 ; current GUID: 22654
![WoWScrnShot_052521_192150](https://user-images.githubusercontent.com/81818678/119541934-45907480-bd8f-11eb-908f-7ca78d0e55cd.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Somnus should be patrolling.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Swamp of Sorrows, coords 82.3 ; 56.7 

##### EXTRA NOTES:

I'm not sure if there is path in the database for the mob to follow.
Also, I checked the bracket "30-39" since it's in Swamp of Sorrows, but the dragon mobs around the Sunken Temple are for 40-49, and Somnus was meant for the Vanilla Onyxia quest chain at level 60.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed on a test server. He's just hovering in place. Thanks for the report. 
FYI his path should be like this: 
[https://vanillawowdb.com/?npc=12900#comments](https://vanillawowdb.com/?npc=12900#comments)

**Comment by Stump876** [comment]
Actually this is a known issue on AC.
[https://github.com/azerothcore/azerothcore-wotlk/issues/2586](https://github.com/azerothcore/azerothcore-wotlk/issues/2586)
