### ISSUE TITLE
Extremely high respawn rate

### ISSUE THREAD

**Issue by MadMD26** [chromiecraft/chromiecraft#7014]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

1-19

### Current Behaviour

In Darkshore, at the Cliffspring Cave entrance, the Stormscale mobs (ie. Sirens and Waveriders) were respawning extremely fast.  My wife and I would kill two mobs at the cave entrance as part of "The Principal Source" quest and they would be dead for maybe 30 seconds before respawning.

This happened to my wife by herself the previous day but in the Ghostlands while on her paladin.  She was in the cave system (coordinates 57, 28) with the trolls and she would kill a few and then they would respawn super quick and kill her.  They would also aggro from extreme distances.

We didn't think this was worth reporting when she experienced it alone but now that it is happening elsewhere we've come to realize that this is a larger issue.

### Expected Blizzlike Behaviour

Regular respawn times and aggro distances.

### Source

I don't really know what this question is wanting.  My wife and I experienced this first hand so the source is our eye-witness account.

### Steps to reproduce the problem

Go to the locations described, kill some mobs, and then time their respawn.  It's super fast.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Windows 10 and 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
[res.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/3e1281d6-c2db-4f2f-b093-c63164c9e7c4)

Seems fine on PTR, if not a little longer that DB timer lists. You might wanna add some vid/pic proof of the spawn rates or something, cause they all seemed fine at this timer. 
https://wowgaming.altervista.org/aowow/?npc=2180
Siren's DB page, shows its more around +1min longer than "should" be.

**Comment by heyitsbench** [comment]
> [...] shows its more around +1min longer than "should" be.

You may notice that's a global quality for every respawn, they're all ~60s longer than is set in DB.
