### ISSUE TITLE
[TBC Progression] World Boss and Raid Bosses drops wrong amount of gold

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7019]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Currently almost every 25 raid boss have their pre patch 2.4 cash drops.
Doom Lord Kazzak max cash drop is 14g46s38c
Sunwell every boss have average drop of 250g (it shouldn't be average but an exact number)

### Expected Blizzlike Behaviour

After patch 2.4.0 there was increase to the cash drop for 25 raid bosses and World Bosses.
Gruul and High King Maulgar : each should have drop 250g
Magtheridon should have drop average of 500g
SSC : every boss should drop 250g except Vashj 300g
TK : every boss should drop 250g except Kael'thas 300g
Hyjal : every boss should drop 250g except Archimonde 300g
BT : every boss should drop 250g except Illidan 300g and each boss of the council drops 62.5g (4 boss = 250g)
Sunwell : every boss should drop 250g except Eredar Twins 350g and Kil'jaeden 500g
Doom Lord Kazzak should drop average of 500g
Doomwalker should also drop average of 500g (currently his max drop is 500g)

### Source

Pretty much every boss has his cash drop updated in wowhead classic to the latest cash drop.

https://wowpedia.fandom.com/wiki/Patch_2.4.0#Dungeons_and_raids
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/fad0626a-7e31-4e46-b672-a85408ff2baa)

[Gruul](https://www.wowhead.com/tbc/npc=19044/gruul-the-dragonkiller) : [Comment from 2.4.0](https://www.wowhead.com/tbc/npc=19044/gruul-the-dragonkiller#comments:id=261761) Old Videos:  [video1](https://youtu.be/gpUWzcQ3EIc?t=212) , [video2](https://youtu.be/73hjs5t4BQ0?t=463) , [video3](https://youtu.be/VPxZCP2iqtc?t=260) , [video4](https://youtu.be/u_G-uEL8HAA?t=205) , [video5](https://youtu.be/KD5YQq4607Q?t=242) 
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/ea5ed344-2983-46fa-9dc8-0c6864f87a54)
[Maulgar](https://www.wowhead.com/tbc/npc=18831/high-king-maulgar) the [only old clip](https://youtu.be/8VWXwRqAtDA?t=176) that i can find , you can kinda see it's "10 Oro"

[Magtheridon](https://www.wowhead.com/tbc/npc=17257/magtheridon) : [Old Wotlk Solo](https://youtu.be/dypC8EcQ0dU?t=376) , [Old TBC Video](https://youtu.be/4lhSrfxMsCs?t=527) , another [Old TBC Video](https://youtu.be/aSzJTqjg3w8?t=326) raid 25 , he got 20g56s20c.

SSC:
[Hydross](https://www.wowhead.com/tbc/npc=21216/hydross-the-unstable) : [Old TBC Video](https://youtu.be/zoJ609lNs8I?t=597)
[The Lurker Below](https://www.wowhead.com/tbc/npc=21217/the-lurker-below) : [Old TBC Video](https://youtu.be/0iMhuL1LUEI?t=355)
[Leotheras the Blind](https://www.wowhead.com/tbc/npc=21215/leotheras-the-blind) : [Old TBC Video1](https://youtu.be/K2fTTRmI3Lc?t=235) , [Video2](https://youtu.be/fIqVPbW4TOg?t=473)
[Fathom-Lord Karathress](https://www.wowhead.com/tbc/npc=21214/fathom-lord-karathress) : [Old TBC Video](https://youtu.be/wv6_6o_u-mE?t=248)
[Morogrim Tidewalker](https://www.wowhead.com/tbc/npc=21213/morogrim-tidewalker) : [Old TBC Video ](https://youtu.be/91b1upPiA08?t=235) it's not clear but you can still see it.
[Lady Vashj](https://www.wowhead.com/tbc/npc=21212/lady-vashj) : [Old TBC Video](https://youtu.be/nDJrTDRbVgI?t=350) , [Video2](https://youtu.be/yN5jkroHyf8?t=338) , [Video3](https://youtu.be/KSxpqCePU2w?t=470) 12g each at last second

TK: 
[Al'ar](https://www.wowhead.com/tbc/npc=19514/alar) : [Old TBC Video](https://www.youtube.com/watch?v=gNg-sG2j2aE) just at the last frame you can see 10g (each) , [Video2](https://youtu.be/uNstZDlVWVQ?t=429)
[Void Reaver](https://www.wowhead.com/tbc/npc=19516/void-reaver) : couldn't find a video for this boss.
[High Astromancer Solarian](https://www.wowhead.com/tbc/npc=18805/high-astromancer-solarian) : [Old TBC Video](https://youtu.be/chdGB-zi-pE?t=206)
[Kael'thas](https://www.wowhead.com/tbc/npc=19622/kaelthas-sunstrider) : [Old TBC Video](https://youtu.be/cVm6LZEDprI?t=560) i think you can kinda see the 12g at the end?

Hyjal:
[Rage Winterchill](https://www.wowhead.com/tbc/npc=17767/rage-winterchill) : [Comment from 3.3.3](https://www.wowhead.com/wotlk/npc=17767/rage-winterchill#comments:id=1040327) , [Old TBC Video](https://youtu.be/KQKzA0zYcWo?t=248) , [Video2](https://youtu.be/BnN676XwMUw?t=363) , [Video3](https://youtu.be/LTk-wLHNVDY?t=155) , [Video4](https://youtu.be/r-WW-bVBmus?t=366) , [Video5](https://youtu.be/hd2IKrm-nYY?t=392)
[Anetheron](https://www.wowhead.com/tbc/npc=17808/anetheron) : [Old TBC Video](https://youtu.be/tXmO8FHVsrY?t=218) , [Video2](https://youtu.be/UOtEvsQespw?t=362) , [Video3](https://youtu.be/_u4anMWBdAY?t=457)
[Kaz'rogal](https://www.wowhead.com/tbc/npc=17888/kazrogal) : [Old TBC Video](https://youtu.be/-FwA33QYBkQ?t=504) , [Video2](https://youtu.be/XlleW2F3c_U?t=129) , [Video3](https://youtu.be/XLeiv0A4Q3Q?t=372)
[Azgalor](https://www.wowhead.com/tbc/npc=17842/azgalor) : [Old TBC Video](https://youtu.be/vV2yQZyb0Io?t=504) , [Video2](https://youtu.be/-FwA33QYBkQ?t=505) , [Video3](https://youtu.be/Qb4YBJM6Tww?t=235)
[Archimonde](https://www.wowhead.com/tbc/npc=17968/archimonde) : [Old TBC Video](https://youtu.be/28BuxT5bzP0?t=281) , [Video2](https://youtu.be/kzpJy9lM3O4?t=448) , This is a video from [Old Wotlk](https://youtu.be/E0FT9FnfkOg?t=57) 25g each (12 players)

BT:
[Naj'entus](https://www.wowhead.com/tbc/npc=22887/high-warlord-najentus) : [Old TBC Video](https://youtu.be/kXN3MlWAHRY?t=300) , [Video2](https://youtu.be/cjoqYAM01-E?t=384)
[Supremus](https://www.wowhead.com/tbc/npc=22898/supremus) : [Old TBC Video](https://youtu.be/bQDIWWcjDKw?t=282)
[Shade of Akama](https://www.wowhead.com/tbc/npc=22841/shade-of-akama) : [Old TBC Video](https://youtu.be/frd07xTUA8Y?t=136) , [Video2](https://youtu.be/69DDuYcj_B4?t=252) , [Video3](https://youtu.be/gsfWHDxKshw?t=305)
[Teron Gorefiend](https://www.wowhead.com/tbc/npc=22871/teron-gorefiend) : [Old TBC Video](https://youtu.be/jhd6BG7OuVM?t=228) , [Video2](https://youtu.be/kqvLVaKZo_I?t=395) , [Video3](https://youtu.be/lPyGvVKVFkE?t=344) , [Video4](https://youtu.be/yHHRwVmn_ss?t=263)
[Gurtogg Bloodboil](https://www.wowhead.com/tbc/npc=22948/gurtogg-bloodboil) : The only [old tbc video](https://youtu.be/h-YuDPvGVKk?t=235) i found where the amount of gold is kinda visible
[Essence of Anger](https://www.wowhead.com/tbc/npc=23420/essence-of-anger) ([Reliquary of Souls](https://www.wowhead.com/tbc/npc=22856/reliquary-of-the-lost)) : [Old TBC Video](https://youtu.be/fAKQF352CD4?t=453) , [Video2](https://youtu.be/_gz9xj1cazk?t=417) , [Video3](https://youtu.be/1symmwGzr1A?t=430)
[Mother Shahraz](https://www.wowhead.com/tbc/npc=22947/mother-shahraz) : [Old TBC Video](https://youtu.be/w5WlYCHK3DY?t=449) , [Video2](https://youtu.be/yNa9DOgtNTM?t=407) , [Video3](https://youtu.be/_pEw9hr45qQ?t=346) , [Video4](https://youtu.be/ctBU0vvSOzo?t=377) , [Video5](https://youtu.be/N7brMZWEN0o?t=276)
[The Illidari Council](https://www.wowhead.com/tbc/npc=23426/the-illidari-council) : [Old TBC Video](https://youtu.be/Wiyx6agh3SQ?t=492) 2g50s from each boss (10g each person)
[Illidan Stormrage](https://www.wowhead.com/tbc/npc=22917/illidan-stormrage) : [Old TBC Video](https://youtu.be/nR_EGCUABis?t=407) , [Video2](https://youtu.be/I3UO0IOvlSI?t=478)

Sunwell Plateau:
[Kalecgos](https://www.wowhead.com/tbc/npc=24850/kalecgos) & [Sathrovarr](https://www.wowhead.com/tbc/npc=24892/sathrovarr-the-corruptor) : [Old TBC Video](https://youtu.be/_3ADxPej1GI?t=275) , [Video2](https://youtu.be/9UD115eShnA?t=414) , [Sunwell PTR 2008](https://youtu.be/zDltcLq8HC8?t=531)
[Brutallus](https://www.wowhead.com/tbc/npc=24882) : [Old TBC Video](https://youtu.be/ZKLzP5aI7wc?t=395) , [Video2](https://youtu.be/7N4s9OyStYw?t=413) , [Video3](https://youtu.be/77ZvVYQEjCk?t=398)
[Felmyst](https://www.wowhead.com/wotlk/npc=25038) : [Old TBC Video](https://youtu.be/aKi-Dx7cm1w?t=483) , [Video2](https://youtu.be/dn9LR2Nk7gw?t=567)
[Kil'jaeden](https://www.wowhead.com/tbc/npc=25315/kiljaeden) : [Old Wotlk](https://youtu.be/lu6VVZgyc6c?t=232) Raid of 22 people , he got 22g72s73c |  [Old TBC Video1](https://youtu.be/rhEqGe4YNwM?t=602) 20g , [Old TBC Video2](https://youtu.be/eFa3MJCKhgU?t=742) Alliance 1st - 20g

[Alythess](https://www.wowhead.com/tbc/npc=25166) & [Sacrolash](https://www.wowhead.com/tbc/npc=25165) : with 2.4.0 release this used to drop 250g [Video1](https://youtu.be/SXoSZ8wgM6Y?t=400) , [Video2](https://youtu.be/8FyFN4S6bZU?t=516) and [Video3 at 5:47](https://vimeo.com/1066703) then it looks like it was changed to 350g later
[Bluetracker](https://www.bluetracker.gg/wow/topic/us-en/7116579218-twins-dey-not-be-stealin-the-loots/)
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/22577ca5-30f4-474e-bc12-7a9eed0c68ad)
Videos of them dropping 350g (14g each person) : [Video1](https://youtu.be/AKdBJFzvJcY?t=288) , [Video2](https://youtu.be/O1CWD9jqIeM?t=344).

[Doom Lord Kazzak](https://www.wowhead.com/tbc/npc=18728/doom-lord-kazzak) : i can't find a clear video of Kazzak in old tbc so this is from Wotlk Classic [first kill](https://youtu.be/7s4mOzSSwkY?t=264) , [second kill at 9:49](https://youtu.be/7s4mOzSSwkY?t=589)
[Doomwalker](https://www.wowhead.com/tbc/npc=17711/doomwalker) : [Hunter solo from Old Wotlk](https://youtu.be/IuQg_JorkT8?t=564) , [another video](https://youtu.be/3WmsZ4Rildg?t=733) from wotlk classic in both he drops more than 500g

### Steps to reproduce the problem

Check DB.

### Extra Notes

I don't know if this already planned for progression.
<sub>Yeah, i don't know why i did all of this , can someone just sniff the number from classic please</sub>

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
Just to chime in with some quick maffs. Based on Nihilum WF kill on Archimonde, since we know for fact it's pre 2.4 values and is pretty clear to read the text lol, we could reverse the math to find out what % increase was given to bosses, then also find out how much they _should_ drop pre 2.4 loosely. World bosses I'm not 100% sure on, or single boss raids like maggy (and sorta gruul). 

In their video, the player got 4g 80s 78c. This appears to be with 25 players in the raid to receive the loot, so it's x25. This means pre 2.4, archi should drop around 120g 19s 50c. Now from this, I know there is a value range of min/max, so the math going forward is going to assume this is more or less "average". It would mean with the 2.4 patch change increasing the value to 300g, the bosses got a 250% increase to gold drops in raids. 

That doesn't help a whole lot, since we're trying to find a comparison between patched values, and seeking the pre-patch data. We could just reverse the math and find what it takes to deduct from 300g, down to 120g. This would mean pre 2.4, all bosses should be deducted 60% of the patched value. I'm not 100% sure this affects all bosses the same way, however. 

This is also just for prog-mod if they want to do it that way. Else I am on board for post 2.4 patch values and leave it at that. Makes it much more simple, no harm to server, and lets a problem be done away with not to be worked on again forever.

**Comment by amed80** [comment]
Went with the changes after 2.4 because it seems they made almost everything a fixed number other than Mag and both WBs.

Didn't want to check the numbers before that because i don't think throwing random numbers will be accepted.

I put both WB in the report because of the inconsistence of how Doomwalker have an average of 472g which is closer to the amount after 2.4 while Doom Lord Kazzak that have average of 12g which still i don't know from where did that number come from and what version.

**Comment by heyitsbench** [comment]
Linked PR corrects AC values to match post-2.4, but I elect not to close it until a staff member weighs in in case progression changes would be desired, either now or in the future.
