### ISSUE TITLE
Manual Crowd Pummeler item cooldown resets

### ISSUE THREAD

**Issue by Undersalt** [chromiecraft/chromiecraft#702]
#### WHAT CLIENT DO YOU PLAY ON?

- [X] enUS

##### FACTION

- [X] Alliance

##### CONTENT PHASE:

- [X] 20-29

##### CURRENT BEHAVIOUR:

Manual Crowd Pummeler (https://wowgaming.altervista.org/aowow?item=9449) cooldown resets on reload / instance change.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

60 minute on use cooldown.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Equip Manual Crowd Pummeler (https://wowgaming.altervista.org/aowow?item=9449) 
2. Use item effect in open world environment
3. Join RDF and check if cooldown has reset
4. IF not, unequip weapon, reequip, log out of wow and back
5. IF it has reset, re-use item effect.
6. Exit RDF and check if cooldown has reset

##### EXTRA NOTES:

The item effect is extremely potent for Feral druids, I was able to make use of it twice in a single run using this method. I cannot yet confirm if weapon swapping or logging out of wow is responsible. Or if this can somehow be replicated in BGs.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Undersalt** [comment]
After some testing, this is a potentially game breaking bug, especially once raiding begins.

I am able to reset the cooldown multiple times per instance.

All that is required to reset Manual Crowd Pummeler (https://wowgaming.altervista.org/aowow?item=9449) cooldown is:

1. Unequip
2. Reequip
3. Log out
4. Log in

![WoWScrnShot_052621_013220](https://user-images.githubusercontent.com/84802481/119582278-9ec6cb00-bdc4-11eb-8f0f-b61cf42fc019.jpg)
![WoWScrnShot_052621_013345](https://user-images.githubusercontent.com/84802481/119582376-adad7d80-bdc4-11eb-87cc-06df21e96166.jpg)
![WoWScrnShot_052621_013317](https://user-images.githubusercontent.com/84802481/119582391-b7cf7c00-bdc4-11eb-9717-2e64b3f31fee.jpg)

Message me (Oversalt) in game if you need further information.

**Comment by Stump876** [comment]
Hi @Undersalt. Thanks for the report. I can confirm the unequip, re-equip, and log out and in method.
![image](https://user-images.githubusercontent.com/68164076/119601284-b2ab0680-bd9d-11eb-9cfd-89f5c2054475.png)
After login in it had about 21seconds left on the timer.
![image](https://user-images.githubusercontent.com/68164076/119601348-dc642d80-bd9d-11eb-82a5-a8595d54a7b4.png)

**Comment by Undersalt** [comment]
Thanks for checking up on this.

Have a great day!

**Comment by Undersalt** [comment]
Further testing has shown that ALL item cooldowns can currently be reset using this method.
