### ISSUE TITLE
(Old issue #4445) Ignite Munching | Fire Mage

### ISSUE THREAD

**Issue by Eledor-collab** [chromiecraft/chromiecraft#7028]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

So, I saw that the issue #4445 made reference to Ignite munching, and it was categorized as invalid and closed because this bug has always existed, unfortunately.

However, I'd like to ask to reconsider keeping this issue open for the following reason:

https://www.youtube.com/watch?v=jhGqzYRla-8 

And an wowhead article:
https://www.wowhead.com/wotlk/news/ignite-munching-and-why-mages-wanted-a-fix-wotlk-classic-ptr-3-4-2-332826

### Expected Blizzlike Behaviour

No Ignite Munching happens.

### Source

https://www.wowhead.com/wotlk/news/ignite-munching-and-why-mages-wanted-a-fix-wotlk-classic-ptr-3-4-2-332826

https://www.youtube.com/watch?v=jhGqzYRla-8 

### Steps to reproduce the problem

1. crit with two fire spells at the same time
2. open combat log and watch ignite ticks
3. ignite only ticks for only one spell, instead of both of them

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Similar issue in spirit to https://github.com/chromiecraft/chromiecraft/issues/5669. Keeping open and labelling for staff review in the same manner.

**Comment by heyitsbench** [comment]
Munching is now a configurable option on AzerothCore as of next restart, whether staff turn it on or not is up to them.
