### ISSUE TITLE
Specific tmog skins do not appear on the NPC's list

### ISSUE THREAD

**Issue by daesztar** [chromiecraft/chromiecraft#7029]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

After equipping item (t4 pala / holy spec in particular) - the skin did not appear on the list of possible mogs for plate, i gem'd and chanted it to remove 2hour exchange delay. The same issue happened with another token (t4 pala / prot spec legs) in the past, i didnt appear on the list ever.

I posted more details on discord / ticket 2354-438376139900321802

### Expected Blizzlike Behaviour

There is no tmog on wotlk, so i dont know :)

### Source

There is no tmog on wotlk, so i dont know :)

### Steps to reproduce the problem

1. additem Pauldron of the Wardancer
2. additem Justicar Pauldron
3. additem Justicar Legguards
4. additem Crystalforge Greaves
5. equip 2 and 4 to unlock skins
6. tmog 1 and 3 into unlocked skins

### Extra Notes

At first i thought there is some weird interaction between different spec variations that does let me tmog ret piece into prot piece. So i duplicated the situation on test server and it worked just fine. At a time when i tried that on nm server i had t5 (ret) leggings equipped and non-token plate shoulder piece from hydross.
I have the other character (rogue) with unlocked almost all t4 and t5 tokens, and there is no issues with tmoggin anything into anything.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Windows 11 / update 23H2

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
It perfectly works with me.

Look this comment than tell me if it works: https://github.com/chromiecraft/chromiecraft/issues/5543#issuecomment-2282830923
