### ISSUE TITLE
[Hyjal] Archimonde aggro radius is too small

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7038]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Archimonde aggro radius is too small (10y)

https://github.com/chromiecraft/chromiecraft/assets/8395873/d854b7c4-32b9-4b70-9e6a-201bb268ce6b

### Expected Blizzlike Behaviour

Archimonde aggro range should bigger than 10y (probably 50?)

### Source

You can see when he start running towards players from those videos:
[Wotlk Prot Paladin Solo](https://youtu.be/H75VAelrbIc)
[Cata Ret Paladin Solo](https://youtu.be/5op8dkL2yKU)
[MoP Rogue Solo](https://youtu.be/3sht_V7mcfc)
[TBC Classic Raid](https://youtu.be/CWoEnK41gTQ?t=2614) at 43:34

### Steps to reproduce the problem

1. .tele hyjals
2. get closer to Archimonde

### Extra Notes

Probably need sniff for the exact aggro radius ?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
Using the solo wotlkc vid, and stopping right on aggro, I used this as a marker for distance. 
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/3c2bff7e-5ada-40f5-93e6-0fe6967831cb)

In PTR, gave myself various ranged spells, and seems the aggro range should be around 60 yards. 

[rng.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/f50787df-3a23-44f0-b1de-1e5382ec874e)

However I am not sure aggro range is set by center of mob, or edge of hitbox. Plus Archimonde had a hitbox patch in 2.4 ("_Also, the hitbox of Archimonde has been reduced significantly_"), but I think all classic stuff is mostly following post 2.4 things like this.
