### ISSUE TITLE
Standards and Practices Quest Glitch - Horde

### ISSUE THREAD

**Issue by Vogrin** [chromiecraft/chromiecraft#7040]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

Hello, I believe on of the quests in Nagrand for the horde, Standards and Practices, is bugged, I can't find the second pyre. All three are there but they're mislabled.

### Expected Blizzlike Behaviour

Three pyres that are not mislabeled

https://www.youtube.com/watch?v=OgADB0AKaG0.

https://www.wowhead.com/tbc/quest=9910/standards-and-practices

### Source

I attempted to do the quest last night

### Steps to reproduce the problem

I don't know

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
[quest.webm](https://github.com/chromiecraft/chromiecraft/assets/62584589/0777a365-a1c8-45b9-b333-f52e8795b7d1)

Quest works fine, however, the pyres are indeed mislabeled via the tooltip. Seems they all display "first burning blade pyre"

![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/e4e31325-ba4f-4624-a3d9-25dbd5f95bc3)

**Comment by alecsci** [comment]
✅ Partially confirmed, indeed there are gameobjects with incorrect labels, but in my recent version https://github.com/azerothcore/azerothcore-wotlk/commit/fc735e37a2166bbb39b272abd6950a5ae70ae761 firstpyre is summoned near 2nd and 3rd.

Quest can be completed, but gameobjects spawns and types must be adjusted, see https://wowgaming.altervista.org/aowow/?search=Burning+Pyre
