### ISSUE TITLE
[Item] Switching stances as warrior sometimes causes DM card Vengeance to damage player

### ISSUE THREAD

**Issue by vexima** [chromiecraft/chromiecraft#7049]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Wearing Darkmoon Card: Vengeance as a warrior and switching stances sometimes does damage to the player wearing it. It happens randomly roughly every 10 switches or so. Any stance switching might cause it, battle to defensive, berserker to battle, doesn't matter.

### Expected Blizzlike Behaviour

DC:V should only proc on incoming damage, switching warrior stances should have no effect.

### Source

https://wowgaming.altervista.org/aowow/?item=31858

### Steps to reproduce the problem

1. create warrior character of any race/faction
2. .level 69
3. .learn 71
4. .learn 2458
5. .additem 31858
6. equip trinket
7. switch between battle and defensive stances repeatedly

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sogladev** [comment]
can confirm 
![image](https://github.com/chromiecraft/chromiecraft/assets/46423958/1f20b760-cbad-4fd3-a773-ff4dcc37760e)

**Comment by sogladev** [comment]
The aura bonusses from stances are proccing cast effects. They most likely shouldn't.
https://github.com/azerothcore/azerothcore-wotlk/blob/ef6db03e1351f4f0c0ddc81f98086c9d99ff04ed/src/server/game/Entities/Unit/Unit.cpp#L17728

https://wowgaming.altervista.org/aowow/?spell=2457
https://wowgaming.altervista.org/aowow/?spell=2458
https://wowgaming.altervista.org/aowow/?spell=7376

this fixes it `SpellInfoCorrections.cpp`
```
    // Warrior Stances bonuses
    ApplySpellFix({ 2457, 2458, 7376 }, [](SpellInfo* spellInfo)
    {
        spellInfo->AttributesEx3 |= SPELL_ATTR3_SUPRESS_CASTER_PROCS;
    });
```

**Comment by Spoon722** [comment]
Might be proccing from the decrease in stats, same thing happens with the debuff aura in terokkar which can proc the trinket when the aura gets applied

**Comment by alecsci** [comment]
✅ Tested and confirmed on [30a790117be921ed0eff513322af1793995b2b4d](https://github.com/alecsci/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d)
![image](https://github.com/user-attachments/assets/d3591c11-fbcc-4286-9876-833201713a68)



P.S: Thanks for the documented repro steps.

**Comment by avarishd** [comment]
fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/19796
