### ISSUE TITLE
Arcane Missiles not cancelling on LOS

### ISSUE THREAD

**Issue by Undersalt** [chromiecraft/chromiecraft#705]
#### WHAT CLIENT DO YOU PLAY ON?

- [X] enUS

##### FACTION

- [X] Horde

##### CONTENT PHASE:

- [X] Generic

##### CURRENT BEHAVIOUR:

Arcane missiles (https://wowgaming.altervista.org/aowow?spell=5143) does not recheck for line of sight after initial cast begins. 
This behavior allows the spell to be cast through walls and others objects, as long as LOS was clear when first channeled.
This gives the spell an unfair advantage, as players cannot escape its range when talented nor dodge behind other objects as the projectiles path through them.
Once missile barrage becomes available, the issue could become game breaking in pvp.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Arcane missiles should be cancelled when enemy player LOS your cast. The spell should be rechecked for LOS on each "tick", and cancelled if a player moves out of sight.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a mage
2. Spam arcane missiles

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jendryk** [comment]
I believe all channeled spells are working like that. Definetly Warlock's Drains and it is a blizzlike behaviour.

**Comment by Stump876** [comment]
I can confirm that arcane missiles will not cast if the target is out of LOS, and once cast, if the target then goes out of LOS it will continue to cast. However this is blizzlike. If you can find anything in a later patch that shows otherwise, please post it. Thanks for the report.
[https://wowwiki-archive.fandom.com/wiki/Arcane_Missiles#:~:text=Arcane%20Missiles%20is%20a%20mage,time%2C%20dealing%20direct%20arcane%20damage.](https://wowwiki-archive.fandom.com/wiki/Arcane_Missiles#:~:text=Arcane%20Missiles%20is%20a%20mage,time%2C%20dealing%20direct%20arcane%20damage.)
![image](https://user-images.githubusercontent.com/68164076/119606627-c5c2d400-bda7-11eb-8e55-f2a1864c8e76.png)

**Comment by Stifler82** [comment]
@Stump876 
When you put the label "Closed" you have also tu close the report pls.

**Comment by Undersalt** [comment]
You are absolutely correct.

https://countdowntoclassic.libsyn.com/episode-96-pvp-news-wow-class-designer-talks-mages-the-unwritten-rules-of-vanilla-wow

At around 42 minutes they discuss the originally intended interaction.

I played on a WOTLK server that had "fixed" the LOS issue it a while back, and assumed that was how it was supposed to be. 

LOS ignore was a concession to overcome how finicky the spell was as Blizz didn't have the tech to correctly implement missiles (It was meant to cost mana on each tick) the way they wanted it. 

Thanks for clarifying.
