### ISSUE TITLE
Arcane Power spell not working for mage

### ISSUE THREAD

**Issue by Appu001122** [chromiecraft/chromiecraft#7051]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Arcane Power https://wowgaming.altervista.org/aowow/?spell=12042 is not working at times . Need to relog to make it work. Whenever i click on the spell, it says - Spell is not ready yet. Even when Arcane Power is not in cd

### Expected Blizzlike Behaviour

By clicking on the spell when not in cd, it should not say - Spell is not ready yet.

### Source

![WoWScrnShot_051224_142312](https://github.com/chromiecraft/chromiecraft/assets/169583408/a682c529-6b22-476c-8f51-dfdf9cab9854)

### Steps to reproduce the problem

1) Use Arcane Power
2) Not on any specific NPC

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Appu001122** [comment]
When I relog it is fine outside dgs. But in dungeons, it gets bugged. Till now it happened in steamvault and Botanica

**Comment by alecsci** [comment]
Hi @Appu001122 I cannot reproduce it anymore.
I tested the following scenarios: 
- in cities / dungeons (SV, BOTANICA)
- cast the spell, wait for cd, cast it again w/o issue
- cast the spell, reset cd, cast it again w/o issue

If you encounter it again and you have more repro steps or conditions, you can reopen it again.
