### ISSUE TITLE
[TK] Kael'thas, spell reflected Nether Beam procs Judgement of Light

### ISSUE THREAD

**Issue by manacute** [chromiecraft/chromiecraft#7074]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

When a player reflects Nether Beam during Gravity Lapse using Spell Reflection, it will proc Judgement of Light and Kael'thas will heal himself. 

https://drive.google.com/file/d/1NYkqowwiYkmt0QUFC6N4ghqc3Yj0AwpP/view

### Expected Blizzlike Behaviour

Spells shouldn't proc Judgements, and enemies shouldn't be able to proc Judgements on themselves

### Source

https://www.wowhead.com/wotlk/spell=20271/judgement-of-light

### Steps to reproduce the problem

1. Go to Kael'thas fight in The Eye (ID = 19622)
2. Get Kael'thas to 50% and wait for him to cast Gravity Lapse
3. Apply Judgement of Light to Kael'thas (spell ID = 20271)
4. Use Spell Reflection to reflect Nether Beam (spell reflect ID = 23920)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
> Spells shouldn't proc Judgements

I don't know about the second part but Spells do proc Judgements in Wotlk.

**Comment by Nyeriah** [comment]
@heyitsbench this got fixed with your PR yes?

**Comment by heyitsbench** [comment]
> this got fixed with your PR yes?

Almost certainly.
