### ISSUE TITLE
[Hyjal Summit] Bosses and Mobs HP values

### ISSUE THREAD

**Issue by XC-ahhaVA** [chromiecraft/chromiecraft#7079]
On PTR bosses and most mobs seem have too much health.

For example Azgalor:
https://www.youtube.com/watch?v=-FwA33QYBkQ
random video form 16 years ago video - HP: 4 085 487
![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/c9ed300f-d634-4406-b1c5-8d751429cd9d)

https://www.youtube.com/watch?v=lymosyRMwHI
video from other server know to be overtuned - HP: 8 922 900
![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/04067fab-9a70-468e-b66a-de88a532ad37)

wowpedia 1st entry 11 July 2007 - HP: 2 100 000
![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/765b88ab-c734-4a40-9c0c-61bfcd23d66e)
https://wowpedia.fandom.com/wiki/Azgalor_(tactics)?direction=next&oldid=731731

wowpedia 2nd entry 27 July 2007 - HP: 4 100 000
https://wowpedia.fandom.com/wiki/Azgalor_(tactics)?direction=next&oldid=771930
![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/b354e7bc-3f72-494e-9b8d-90864287b66e)

wow classic PTR - HP: 4 248 783
https://www.youtube.com/watch?v=Jh-1ExM9cL4&ab_channel=SubtleFW
![image](https://github.com/chromiecraft/chromiecraft/assets/164023764/e7f00dd6-3e17-4f4f-8695-ea04bb86c44f)

On chromie's PTR last i checked it was ~ 8 920 000. Which would make it okay, for mythic mode, if it was available.
Same could be said for other tuning issues such as damage from autos, and spells.

No idea if those values from the Sunday test will make it live. But here it is, as when i searched i did not found this mentioned on any other topic at first glance.
p.s. Please pardon bad english. :)

**Comment by 55Honey** [comment]
Thanks for the detailed feedback!
Let me redirect you to https://github.com/chromiecraft/PTR-review.
