### ISSUE TITLE
Trial of the Sea Lion - Pendant of Aquatic Agility [Horde]

### ISSUE THREAD

**Issue by Zathras1974** [chromiecraft/chromiecraft#7082]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

Strongbox containing Pendant of Aquatic Agility is supposed to be located at bottom of Sludge Fen (56.7,8.3). Strongbox located, but cannot interact with it (aka: no sparkles, no gear cursor) to open it to receive item. 
This breaks further quest progress.

### Expected Blizzlike Behaviour

Strongbox should be able to be opened and player should be able to receive item, allowing quest to proceed.

### Source

https://warcraft.wiki.gg/wiki/Half_Pendant_of_Aquatic_Agility
https://classicdb.ch/?item=15883#comments
https://wowpedia.fandom.com/wiki/Half_Pendant_of_Aquatic_Agility

### Steps to reproduce the problem

1) Go to sludge fen
2) Swim to bottom of lake
3) See strongbox
4) Notice you cannot interact with said strongbox.
5) Cry.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
There might be an issue with this quest and the Alliance version mixed up somehow. I reported it long ago.
https://github.com/chromiecraft/chromiecraft/issues/1464

**Comment by alecsci** [comment]
Thanks for your report @Zathras1974.
Thanks for the suggestion @cachocarne.
Looks like a duplicate report, and will be handled in https://github.com/azerothcore/azerothcore-wotlk/issues/7456
