### ISSUE TITLE
[TBC Netherwing] - Sludge-covered Object & Other Sources of Netherwing Eggs

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#7083]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

**_Cannot 100% be certain, since I do not have server loot tables._** 

However I am pretty sure the [Sludge-covered Object](https://wowgaming.altervista.org/aowow/?item=32724#contains) if going by the vistaDB sources, do not drop the [Netherwing Egg](https://wowgaming.altervista.org/aowow/?item=32506#dropped-by) for now. 

### Expected Blizzlike Behaviour

The [Sludge-covered Object](https://www.wowhead.com/wotlk/item=32724/sludge-covered-object#contains) when going by wotlk classic data, does contain these at a _very small chance_. When checking the [Netherwing Egg](https://www.wowhead.com/wotlk/item=32506/netherwing-egg#dropped-by) via WHDB, they also show up under [Nethercite Deposit](https://www.wowhead.com/wotlk/object=185877/nethercite-deposit), which isn't shown on vistaDB either ([Netherdust Bush](https://wowgaming.altervista.org/aowow/?object=185881) was). 

### Source

Links above n stuff

### Steps to reproduce the problem

1. Check the loot table scripts of the objects I guess?

### Extra Notes

![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/73b329f7-70d8-4dd4-ba11-c8b2bfaac610)
blame bench if this was fine all along. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
