### ISSUE TITLE
[tmog] Cataclysm Chestguard not appearing in list of tmog options

### ISSUE THREAD

**Issue by Boov-CC** [chromiecraft/chromiecraft#7096]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Cataclysm Chestguard (https://wowgaming.altervista.org/aowow/?item=30164) doesn't appear in list of possible skins to transmog other mail chests to. 

### Expected Blizzlike Behaviour

Be able to tmog other mail chests to appear like Cataclysm Chestguard

### Source

Other Cataclysm set pieces appear in their respected item slot tmog options. 

### Steps to reproduce the problem

1. Purchase Cataclysm Chestguard using token from TK
2. Equip Cataclysm Chestguard to add it to your wardrobe/possible tmog items
3. Equip a different mail chest
4. Speak to tmog vendor 
5. Select Chest and view list: Cataclysm Chestguard should be an option but currently isn't (other Cataclysm set pieces properly show)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a6425c36309f59eebbd1369dbfc5b09099a4dde5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Have you waited out the 2 hour refund window? the ele chest works fine, just wating ti test resto on the ptr
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/c0a9b0fb-0e7d-41b3-9c9d-c562bcfab0ba)

**Comment by Rorschach91** [comment]
Look this comment, than tell me if It works: https://github.com/chromiecraft/chromiecraft/issues/5543#issuecomment-2282830923

**Comment by Boov-CC** [comment]
It may have been the 2 hour window that Beef mentioned - I'm not sure - but I can tmog it now. Thanks for the feedback and assistance.
