### ISSUE TITLE
[warrior ] Rage generation :auto attacks (parried , blocked and dodged) dosent generate rage

### ISSUE THREAD

**Issue by Reily93** [chromiecraft/chromiecraft#7098]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

casting auto attack on a target that executes a dodge , parry , and block dosent give rage

### Expected Blizzlike Behaviour

auto attack parried, blocked , dodged should generate rage without the damage part ofn the formula

### Source

https://wowpedia.fandom.com/wiki/Rage

Fixed a bug where rage was not being generated when normal melee attacks were parried, dodged, and blocked.
that cause a lot of dps loss in raid when u dont generate any rage from auto cause it got denied 

Attacks that are blocked, parried, dodged or absorbed (as with [Power Word: Shield](https://wowwiki-archive.fandom.com/wiki/Power_Word:_Shield)) also generate rage. patch 1.3.0 it refers to the attack send by the warrior not received cause in the 3.1.0 they added that basorbed attack like by power world shield also generate rage so its logical to assume it is from the one one who go out not the auto u receive

https://wowwiki-archive.fandom.com/wiki/Rage#Rage_generation

![image](https://github.com/chromiecraft/chromiecraft/assets/96992763/c2c6abf9-47f6-47a2-8219-fb3118367c92)

as u can see this is the formula of generating rage , the first part is about generating rage from the damage done, the second part is the hit factor and weapon speed . IF the attack get parried , blocked or parried we dont have the first part but we skip to the second where the attackl get rolled for a normal hit or crit . s is the weapon speed F is the hit factor 3.5 normal hit 2h ,7 crit hit 2h weapon

https://www.youtube.com/watch?v=x3g7oIT9saU 
minute 23:12 he charge get 15 rage on the rogue rend him - 10 rage he is 5 at that point he get an auto dodged and go back to 24 ( 23:16 ) as u can see the rogue dosent perform any attack on him so its not generated by damage taken

https://www.youtube.com/watch?v=VXz2JEkf8x0

minute 8:12-8:14 he is 39 rage perform a parry on him and get to 61 rage he uses hamstring and go to 54 (-7 with gloves passive )

https://www.youtube.com/watch?v=zDPb2uDL098

1.15-1.18  charge and he get 20 rage spend 7 in hamstring go to 13 rage auto attack parried he go to 33 rage he spend into mortal strike (-30 rage) to 3 rage but some aoe and berseker rage up give him 6

https://www.youtube.com/watch?v=4d1MPlgLsjI

6.16-6.19 auto attack dodged bring him to 22 to 45 rage no direct hit from dk on him and the rage genrated is too much to give credit to some dot

### Steps to reproduce the problem

1duel an hunter or rogue
2 make him hunter(deterrance) rogue(evasion)  ( i didint chose an npc cause u cant get a guarantee parry, block,dodge from em)
3 auto attack him (during that spell and be sure not hitting him trough it)
4 no rage generated
5 bug confirmed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a6425c36309f59eebbd1369dbfc5b09099a4dde5
 
### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
#4758  ?

**Comment by Reily93** [comment]
that was closed cause lack of information i found that video check it

**Comment by amed80** [comment]
Found this in wowsims discord from wotlk warrior section 
![Discord_05%24%17=24-06-2024](https://github.com/chromiecraft/chromiecraft/assets/8395873/d636fa1a-ae3e-4333-b896-d0eca691dfe1)
Based on that conversation , parry and dodge should generate rage like a normal auto attack.
On the other side ,i couldn't find that much about Block but for my understanding block does not prevent the full damage like parry and dodge do , so you should still be able of dealing damage and the rage from blocked AA should work like glancing blow? i don't know if block is even bugged?

**Comment by Reily93** [comment]
if i search better on some video i can find it but i think is pointless block works like an absorb it can negate the damage or mitagte it partially

**Comment by amed80** [comment]
Going from wowsims work which i will assume the most accurate thing we have to wotlk , you can test and see that block gives you ~30% less of average normal attack
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/39336302-97ff-42f8-ad2c-6260d0977270)

**Comment by Reily93** [comment]
yeah but the point is u should generate same rage like it was'' absrobed'' also depends cause if u fight a tanbk with lot of block that value is not flat

**Comment by amed80** [comment]
block =/= absorb , block can't neglect the whole damage like parry/dodge or absorb , that 30% explanation was my fault , i should have showed the normal AA damage and the Blocked AA damage which in that attack it was ~30% from the average normal AA , being the damage in not fully neglected , i will assume if glancing blow is working correctly then blocking should be already working correctly as they have similar rage results.
The testing were made in https://wowsims.github.io/wotlk/

**Comment by Reily93** [comment]
block is similar to absorb, also u are making a sim on certain stats so a flat ammount but u need to evalutate more varibales examples: im a proit warr with 1k block and i stop 600 inc damage , im a warr arms with 1000 weapon dmage and with reduction of armor i do 500 then i get full blocked , but if im arms warrior with block up and i stop 400 bloack damage stopped and 2 arms warr hit me with 1000 weapon dmaage for 600 i got a 400 damage mitigated so iu do 200 damage a partial block
same as absorb if i have  ashield for 1 k and i hot for 1 damage is negated but i get rage, same if the ammoutn absorbed is 600 is go for 1000-600 400 damage

**Comment by amed80** [comment]
Again block is not absorb , if you hit 1000 dmg on a target , and the target absorb 600 from it you will still get the rage for the full 1000 , with block as it's shown in the wowsims (which again i believe the closest we have to actual wotlk retail/classic) you can see a blocked attack act like glancing blow and it will not rewards you rage for the damage that was blocked but only for the damage that was dealt.

Fully blocked attack is considered as a miss which is referred in this classic reddit post (there was no changes to block until Cataclysm so it should work the same in wotlk)
https://www.reddit.com/r/classicwow/comments/mb2x3g/fully_blocked_attacks_are_considered_misses/

**Comment by Reily93** [comment]
I repeat but i explain it better , as u linked above parry and dodge arre considered missed ,but we are talkinbg about auto attack white hits ,so they are considered non glancing non critical and should generate more rage than a normnal hit, so now block has 2 parts 1 poartially blocked so as u say it generate rage for the ammoutn of damage done ( block- damage) but as Parry and Dogdge , block is considered miss so it shpould be considered as non glancing ?non critical?  aboput the effects u mention above he refers to special attack like hamstring thaty can be blocked for example an dother ones, white it itself dont have special effects and u cant count rage as aeffect of white it its just a power source , if u can sims a full block maybe is more clear

**Comment by amed80** [comment]
Parry and Dodge are NOT considered a miss , you will gain exactly the amount you usually get from a normal hit.
Block and Shield used to be the same before as both do not generate rage if they completely neglect the damage because both are a miss , the only change was later made with Wotlk was for absorb to give rage and not Blocked , it will make literally no sense that partially blocked attack give you partial damage based on the damage was made and not blocked but a full block which deal 0 damage will give you the full rage , even in the post above from wowsims , you can see that there was mentions of Dodge and Parry only and not block for the full rage amount.

**Comment by Reily93** [comment]
i will see on some video but about parry and dodge we have a bug thats what is important

**Comment by Reily93** [comment]
https://www.youtube.com/watch?v=QJ9pw5LQSlg 1.23-125 39 rage -->rend 29 rage (-10) -- auto attack blocked 45 rage+3 from pala auto it happen fast but check it 48 rage end ,into execute proc
