### ISSUE TITLE
Quest "Encrypted Scroll" should not be available before completing quest "The Mindless Ones"

### ISSUE THREAD

**Issue by Istox** [chromiecraft/chromiecraft#71]
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
Quest "Encrypted Scroll" (https://wowgaming.altervista.org/aowow/?quest=3096) should not be available before completing quest "The Mindless Ones" (https://wowgaming.altervista.org/aowow/?quest=364)

This is obvious from the quest text for Encrypted Scroll that states:
"_Ah, **while you were off dealing with the mindless Scourge**, this scroll arrived for you. I would think it's some matter of importance as it seems it bears the seal of the rogue trainer David Trias. I would take some time to read it before heading out again._"

##### EXPECTED BLIZZLIKE BEHAVIOUR:
"Encrypted Scroll" quest should only become available after completing "The Mindless Ones" quest.

##### CURRENT BEHAVIOUR:
"Encrypted Scroll is available at start without any other quest requirement.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Create new undead character 
Step 2 Run down the hill and you can immediately pickup "Encrypted Scroll" quest.

As an additional note, you may want to check **all** initial class quests because they are probably all incorrect this this rogue one.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
The only quests that "The Mindless One" should unlock are:
1. Simple Scroll
2. Tainted Scroll
3. Rattling the Rattlecages

If you have another source from wotlk or before could work, but from the text of the quest is not valid in my opinion.

**Comment by Istox** [comment]
Quest text part of the game literally stating that this is chained outweighs non official wowhead where the original data source is not known.

For example atleast the quest text provides some evidence. non official wowhead may or may not be correct and so cannot be used as evidence at all. I will search for additional proof but it seems obvious to me.

**Comment by Istox** [comment]
Heres evidence from wow classic:
https://www.youtube.com/watch?v=_hrYv8KeYwo&ab_channel=Bannik13

You can see that the quest is not available until after The Mindless Ones. We can assume blizzard has the correct data for this era onwards.

**Comment by illfated** [comment]
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=364/the-mindless-ones
- Opens quests:
    - https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3096/encrypted-scroll
    - https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3097/hallowed-scroll
    - https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3098/glyphic-scroll
    - https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3099/tainted-scroll
    - https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3901/rattling-the-rattlecages

From Blizzard's side, the whole point of having the other quests open up only after the first quest is completed is that each and every player can do/has to do 1 single classless quest before they are given their class specific assignment. This is true for all the starter zones, be it Elwynn Forest/Northshire, Durotar/Valley of Trials, Dun Morogh/Coldridge Valley, Teldrassil/Shadowglen or Tirisfal Glades/Deathknell or any of the other starter zones.

**Comment by nicoaravena** [comment]
Thanks for the feedback and the report, will triage this issue.

**Comment by FrancescoBorzi** [comment]
The fix is now on ChromieCraft. Thanks for your report.
