### ISSUE TITLE
[Quest] Portals of The Legion - Demon Portals don't despawn

### ISSUE THREAD

**Issue by formiclol** [chromiecraft/chromiecraft#710]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

During the quest [Portals of the Legion](https://wotlkdb.com/?quest=5581), you are tasked to banish 6 [Demon Portals](https://wotlkdb.com/?object=177243) using the Hand of Iruxos.  After right clicking on a Demon Portal, a [Demon Portal Guardian](https://wotlkdb.com/?npc=11937) spawns, and killing the demon gives 1 credit towards the objective of banishing 6 portals.  After you kill the demon, the portal should despawn and you need to find another in the area, however, the portal does not despawn and you can repeat the task 5 more times on the same portal to complete the quest.  Based on wowhead comments, the portals should have a ~5 minute respawn timer.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Right click on a demon portal.  Portal guardian spawns.  Kill the guardian for 1 quest credit.  Portal despawns.  Find next portal in the area.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Right lick on portal
2. Kill demon
3. Receive 1 quest credit
4. Right click on same portal again
5. Kill demon
6. Receive 1 quest credit
7. Repeat until quest is complete

##### EXTRA NOTES:

Quest chain starts with [Hand of Iruxos](https://wotlkdb.com/?quest=5381)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
This is a known issue (it hasn't been posted on this bug tracker before, so it's not technically a duplicate). Thanks for the report though!

https://github.com/azerothcore/azerothcore-wotlk/issues/5798
