### ISSUE TITLE
Ring replacement gossip from Scale of the Sands rep reward has bad conditions.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#7102]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Got the exalted and revered rings at the same time.

### Expected Blizzlike Behaviour

No.

### Source

Me.

### Steps to reproduce the problem

1. Rep.
2. Ring.
3. Rings?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a6425c36309f59eebbd1369dbfc5b09099a4dde5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IskrenPlashkov** [comment]
Can confirm.

The dialog for the lost ring is available at all times and rewards the exalted version of the rings without checking if a previous iteration of it is still on the character.

**Comment by avarishd** [comment]
I couldn't reproduce this on my local (tested all 4 rings + switch quest), she yoinks back the previous tier ring.
Could this be a CC specific issue?

**Comment by amed80** [comment]
this is how you reproduce the problem https://github.com/azerothcore/azerothcore-wotlk/issues/4316
just tested it , the npc shows the 'I've lost my ring ....." at the wrong stage.
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/db906ad3-18ee-4457-b408-82b6d04394c5)

**Comment by avarishd** [comment]
I see the issue now. Issue was a bit vague on information.

**Comment by amed80** [comment]
adding to this , the 2nd quest when you choose the healer ring , Restorer's Vow (quest ID 10465) , is being offered at the wrong rep rank , it should be offered at Friendly level but instead currently it's being offered when you reach Honored.
