### ISSUE TITLE
[Black Temple] Coilskar General's Free Friend does not dispel CC

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7114]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Coilskar General's Free Friend does not dispel CC and it does not give immunity against Banish.

https://github.com/chromiecraft/chromiecraft/assets/8395873/74affc80-41c7-46d4-bfdd-79c1380619d0

### Expected Blizzlike Behaviour

[Free Friend](https://wowgaming.altervista.org/aowow/?spell=40081) should dispel every incapacitating effects.

### Source

[PTR TBC Classic](https://youtu.be/NRl78646E4M?t=415) at 6:55 , you can see the General turns towards Soothsayer who was polymorphed and uses his Free Friend ability which frees the Soothsayer from it.
[PTR TBC Classic](https://youtu.be/K8mEU_dHyd4?t=1386) at 23:07 you can see the General turns towards the banished Aqueous Spawn and dispel the banish, and also dispel the polymorph from Soothsayer after.

### Steps to reproduce the problem

1. .tele bt
2. engage with any of the packs that have Coilskar General
3. start using any CC on the other mobs around Coilskar General.

### Extra Notes

[Free Friend](https://wowgaming.altervista.org/aowow/?spell=40081) does give immunity to the target mob for 5 sec for every CC that i have tested but it does not for Banish (as shown above at the end of the clip)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a6425c36309f59eebbd1369dbfc5b09099a4dde5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Banish has a specific flag to bypass spell immunities that could be interferring with this
