### ISSUE TITLE
[Black Temple] High Warlord Naj'entus doesn't enrage after 8mn

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7116]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[High Warlord Naj'entus](https://wowgaming.altervista.org/aowow/?npc=22887) doesn't enrage after 8mn

### Expected Blizzlike Behaviour

[High Warlord Naj'entus](https://wowgaming.altervista.org/aowow/?npc=22887) should enrage after 8mn

### Source

[Wowhead Comment](https://www.wowhead.com/wotlk/npc=22887/high-warlord-najentus#comments:id=121387)
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/4992c5cf-139d-4e95-9c99-8478e68884ca)

### Steps to reproduce the problem

1. .tele bt
2. engage with Naj'entus
3. wait for 8mn

### Extra Notes

It looks like the enrage timer is set at 8mn already but because of DelayAll() for Tidal Shield is causing the enrage to be delayed by 1mn and 30sec
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/36d42231-5ccd-4be8-b0d3-458ad38baff3)
probably should switch it to DelayGroup() or if you can make enrage timer not affected by DelayAll() ?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a6425c36309f59eebbd1369dbfc5b09099a4dde5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
After a wipe , Najentus will enrage way too early , this happens if you wipe before his enrage timer and try to attempt him again.

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/4e385304c0e6dcf159f66c83df2b5962e3749fd3
