### ISSUE TITLE
[Barrens] Double Mining Veins Spawns

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#712]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

GUID 5067 & GUID 15496
![double1](https://user-images.githubusercontent.com/80769357/119775712-470f8900-bec4-11eb-9fe3-194375a27a3f.jpg)

GUID 4780 $ GUID 15009
![double2](https://user-images.githubusercontent.com/80769357/119775734-4c6cd380-bec4-11eb-9aee-743874be5974.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Veins should not be spawn next to eachoter/inside eachother.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID
2. See double spawn

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Therier** [comment]
Confirmed
