### ISSUE TITLE
[Black Temple] Supremus's Molten Punch wrong behavior

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7121]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Supremus](https://wowgaming.altervista.org/aowow/?npc=22898) only uses [Molten Punch](https://wowgaming.altervista.org/aowow/?spell=40126) (summons fire) in his first phase 1 then stops using it for the rest of the fight after the first switch to phase 2.
[NPC 23095](https://wowgaming.altervista.org/aowow/?npc=23095) keep chasing the targeted player the whole time.

### Expected Blizzlike Behaviour

[Supremus](https://wowgaming.altervista.org/aowow/?npc=22898) should keep using his [Molten Punch](https://wowgaming.altervista.org/aowow/?spell=40126) for the whole fight.
[NPC 23095](https://wowgaming.altervista.org/aowow/?npc=23095) should stop chasing his targeted player after 6sec from his spawn.

### Source

[2 man retail Cataclysm](https://youtu.be/t9PWzId-xKg) you can see that the fire stop moving after 6sec from it's spawn , 0:19 to 0:25 , 0:35 to 0:41 , 0:53 to 0:59 , 1:11 to 1:17 and the last one was during his phase 2 as he charged towards the hunter.

[PTR TBC Classic](https://youtu.be/e-d8RErZwsw?t=4493) you can see at 1:14:53 the fire spawned while the boss in phase 2 (walking slow and chasing a player) and that fire is moving towards a paladin which stops at 1:14:59 before even reaching him.

[Nihilum World First](https://youtu.be/V9kzgJryqjs?t=257) at 4:19 he summon the fire during phase 2 and at 4:39 you can see it chase the druid until 4:45

[Wotlk Classic Solo](https://youtu.be/t3KO1ehz-Ds) the fire kept spawning for the whole fight in both phases.

### Steps to reproduce the problem

1. .tele bt
2. fight Supremus
3. Watch the fire chasing the player for 10sec and in gm mode you can see the npc keep chasing until despawn.
4. Wait 60sec when the boss switch to phase 2 and he never spawn the fire again.

### Extra Notes

I think the [NPC 23095](https://wowgaming.altervista.org/aowow/?npc=23095) should stay for the whole duration even when he stops moving after 6sec , despawning him might cause the fire trail to despawn instantly?
Also i think the inconsistency of spawning fire in phase 2 which is seen is some of those videos it's that the highest on threat is not near the boss hitbox range. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a6425c36309f59eebbd1369dbfc5b09099a4dde5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
I'll look further into their movement. But from what I'm seeing they could be actually changing targets. The chase is defined by threat, it looks like 10k threat at spawn added at random, so they could be changing targets to a healer, for example.

**Comment by amed80** [comment]
I don't know if that timer is related to the fire despawning? atm in the current version and in videos the fire despawn after 10s which is similar to what this spell have 40253
The only difference is the NPC 23095 keep spawning the fire for 10s when i think it should be less (as soon as they drop threat?)
And also NPC 23095 keep chasing for 20s then despawn
