### ISSUE TITLE
[Warrior] Casting & Queued Attacks

### ISSUE THREAD

**Issue by mussy44** [chromiecraft/chromiecraft#7131]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

casting spells (namely slam) does not allow you to cancel your currently queued on-hit ability (cleave, heroic strike)

### Expected Blizzlike Behaviour

casting spells should not interfere with the player's ability to cancel queued attacks. instead, casting spells should cancel currently queued on-hit abilities, and the player should still be able to queue the said abilities afterwards before the current swing timer runs out

### Source

[Fight Club discord invite](https://discord.gg/RbCZJtw): [Slam cancelling HS is blizzlike](https://discord.com/channels/383596811517952002/1013562071486570564/1026193232675213334)
![bpETKcL](https://github.com/chromiecraft/chromiecraft/assets/84478740/951d2c82-3434-4f49-b31c-fa820c26129d)

aforementioned video
https://www.youtube.com/watch?v=5jrQO_8JqHQ&t=80s

### Steps to reproduce the problem

1. create an arms warrior and go to the nearest enemy or target dummy
2. cast slam, queue HS/cleave and try to cancel the HS/cleave you just queued. you will notice you can't

### Extra Notes

N/A

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a6425c36309f59eebbd1369dbfc5b09099a4dde5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sogladev** [comment]
can confirm, q'ing heroic strike then casting slam does not clear heroic strike
