### ISSUE TITLE
[Hyjal] Archimonde Doomfire doesn't work as intended

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#7137]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Doomfire damage ticks by decimals of seconds killing anyone who gets into the fire in less than 3 seconds. The damage is being applied while you are over the fire and the debuff is doing no damage.

### Expected Blizzlike Behaviour

- Doomfire should tick every 3 seconds, making it intensive on the healers the more people get it on the long run, Doomfire is not supposed to be a burst mechanic but a long debuff that deals damage over 45 seconds.

### Source

TBC Classic: https://youtu.be/Z10ESPoWKE0?si=0e7azZqYPt8bARCg&t=58
You can see that the healers have enough time to handle the people with the fire instead of them dying in less than 3 seconds.

https://www.wowhead.com/wotlk/spell=31944/doomfire
Says 2250 damage every 3 seconds for 45 seconds.

https://www.wowhead.com/wotlk/npc=17968/archimonde
**Doomfire:** Trail of fire on the ground that does 2,250 fire damage per second on first tick and does less with every following tick. Fire resistance does not affect this effect.

### Steps to reproduce the problem

1. .tele hyjals
2. Fight Archimonde
3. Stand on Doomfire
4. Log the damage per second
5. Watch the debuff not do any damage once outside the fire

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a6425c36309f59eebbd1369dbfc5b09099a4dde5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
I think only the first effect is working atm 
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/0aaafa69-ae82-4e13-8fc3-0f4c75907da6)

The extra damage that is being taken is because of the fire being put down close to each other that can cause the person taking the first hit twice (sometimes even 3) and with tuning the 2400 is 3240 so people can be hit with 6480 and even 9720 in a single hit 
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/2d6595e6-c0f9-443d-9c0d-9681591167c3)
I don't know if there is a way to make it that if a person is sitting on 2 or 3 patches of fire he will take only one hit instead of 2 ?

**Comment by elthehablo** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/19209 progresses this. But is this now also fixed or does the debuff still deal no damage?

**Comment by heyitsbench** [comment]
> [...] does the debuff still deal no damage?

Debuff still deals no damage, fixed by the linked PR.

**Comment by elthehablo** [comment]
> > [...] does the debuff still deal no damage?
> 
> Debuff still deals no damage, fixed by the linked PR.

Awesome
