### ISSUE TITLE
Quest: "Return to Krog" = missing

### ISSUE THREAD

**Issue by Tmetheorcfemale** [chromiecraft/chromiecraft#714]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49

##### CURRENT BEHAVIOUR:

Questgiver "Mosarn" in Thunderbluff Hunter Rise does NOT give the quest "Return to Krog". 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC "Mosarn" should give the quest "Return to Krog" so the questline can be continued.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  DB GUID 24771, current GUID 287
2.  turn in quest: https://www.wowhead.com/quest=27258/the-black-shield
3.  then no new quest appears from Mosarn
4.  54.21, 80.59 Thunderbluff, Hunter Rise

##### EXTRA NOTES:

https://www.wowhead.com/quest=27292/return-to-krog
Hope this helps fix it.
With kind regards
Tme
The female orc.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Undertower** [comment]
The quest https://tbc.wowhead.com/quest=1276/the-black-shield is available before you have done the prequest https://tbc.wowhead.com/quest=1273/questioning-reethe. 
You can read a good comment about the quest chain on https://tbc.wowhead.com/quest=1276/the-black-shield#comments, the 3rd comment from the top has the proper information.
