### ISSUE TITLE
[Black Temple] Illidan, Parasitic Shadowfiend Targeting

### ISSUE THREAD

**Issue by Alethrion** [chromiecraft/chromiecraft#7141]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Currently when soloing Illidan the Shadowfiends can and will target the only viable player, doubling the debuffs applied each time until crash.

### Expected Blizzlike Behaviour

When soloing the Shadowfiends are meant to recognize there is no valid target and die.

### Source

https://youtu.be/tBeEcGi7N_8?t=67

### Steps to reproduce the problem

1. Fight Illidan solo
2. Get parasited nerd
3. Kys before the game dies if it still isn't fixed

### Extra Notes

May also apply to non-solo with Shadowfiends choosing their host as a target, but it is as of yet untested

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dbec1a14417a968e6f874a637330ceac8cd16020

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Alethrion** [comment]
During the Illidan fight Akama runs off and fights a seemingly infinite wave of ~18k hp BloodElves. Have no clue if that's intended and I would imagine it's somehow abusable for procs or something. On the plus side, Akama can't die and softlock anything here as far as I've tested

**Comment by heyitsbench** [comment]
This issue is still valid after the rewrite.

**Comment by Nyeriah** [comment]
I need information on how this should work. Should they skip targetting players affected by parasitic shadowfiend aura? Mobs apply aura on autoattacks, so every often they apply a new shadowfiend aura to their targets, and that makes them multiply fast

**Comment by Alethrion** [comment]
The 2 fiends exit the debuffed target and each search out a new target. When there is only one target they are just supposed to automatically die without reapplying the debuff.
