### ISSUE TITLE
The Majordomo fight in MC resets itself over and over

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#7143]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

During a MC run we killed all the adds at Majordomo but on the last add kill, all the adds respawned. Majordomo went friendly and started role playing. The loot box spawned and we got loot. 
Upon killing the second pack, a new pack spawned and a new loot box spawned. 
This happened 5 times in a row until we ran away. 
We were unable to talk to Majordomo to spawn Rag. 

### Expected Blizzlike Behaviour

Last add dies, no adds should spawn. 

### Source

Basic info

### Steps to reproduce the problem

1. Kill adds
2. observe new adds spawning
3. Loot the box
4. Kill adds
5. repeat

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dbec1a14417a968e6f874a637330ceac8cd16020

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Plan414** [comment]
This happened again in the MC raid on other character on the same day.

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/19139
