### ISSUE TITLE
[Black Temple] regular trash NPC enter the room during Shade of Akama fight

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#7153]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

If not killed beforehand regular trash NPC near the akama gate get agroed during the [boss](https://wowgaming.altervista.org/aowow/?npc=22841) fight.

### Expected Blizzlike Behaviour

Once [boss](https://wowgaming.altervista.org/aowow/?npc=22841) is engaged no outside trash NPC should be able to enter the room and join the fight.

### Source

Didnt find any particular source about this but it is pretty clear as it has not been mentioned as an issue in any guides either.

### Steps to reproduce the problem

Enter Back temple
Do not clear any trash packs left of the akama gate
Initiate the fight
wait few seconds for the first add waves to spawn

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dbec1a14417a968e6f874a637330ceac8cd16020

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
Is there more steps that help reproduce this behavior ? 

I left everything alive in the raid apart from first 2 bosses to open the gates , even though i don't think it's possible to reach Akama's fight without clearing the trash in front of his gate without flying , that trash pack didn't aggro (or any outside trash NPC ) during the encounter even when i tried to lure the adds spawned during the fight near the closed gate.

https://github.com/chromiecraft/chromiecraft/assets/8395873/33142151-922b-4528-b9d7-9293d1af1bbf

**Comment by IskrenPlashkov** [comment]
Not sure how but we managed to get a nightlord. Was probably a boomking starfall or something...

**Comment by amed80** [comment]
Seen that it's the Nightlord that aggro'd , did any of the shamans leave their totems behind ? 😅

**Comment by IskrenPlashkov** [comment]
That wouldnt surprise me but cant recollect for sure, need to test this scenario during our next run.

**Comment by Rorschach91** [comment]
I tried to reproduce this issue, but nothing. I wait for more feedbacks.

**Comment by Nyeriah** [comment]
Unable to reproduce
