### ISSUE TITLE
[Black Temple] Teron Gorefiend adds do not move

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#7154]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Adds](https://wowgaming.altervista.org/aowow/?npc=23111) do not move.

### Expected Blizzlike Behaviour

[Adds](https://wowgaming.altervista.org/aowow/?npc=23111) should be moving towards the boss.

### Source

6:40 in https://www.youtube.com/watch?v=cvMTW85NQJU&t=235s or any other kill video

### Steps to reproduce the problem

Enter Black Temple
be in group with at least 2 people
After 1 player dies from Shadow of Death adds will spawn
Notice they never move

### Extra Notes

There could be a follow up issue after one is resolved - them not attacking the raid once they reach boss. Will be further tested then.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dbec1a14417a968e6f874a637330ceac8cd16020

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
> [Adds](https://wowgaming.altervista.org/aowow/?npc=23111) should be moving towards the boss.
> There could be a follow up issue after one is resolved - them not wiping the raid once they reach boss. Will be further tested then.

They shouldn't wipe the raid if they reach the boss , they target players and start attacking them.
you can see here [1:48:16 ](https://youtu.be/wy1nf_RM_Qg?t=6496) [Shadowy Construct](https://wowgaming.altervista.org/aowow/?npc=23111) reaching the boss and start attacking players.

They usually have 3-4 sec delay after they spawn before moving , can be seen in this video [36:28](https://youtu.be/jl0eC51036s?t=2188)

**Comment by IskrenPlashkov** [comment]
Dayum, thanks for pointing that out. Frankly I never had them reach the boss before so just assumed they would be acting as an enrage mechanic. Adjusted my original post accordingly.

**Comment by Nyeriah** [comment]
Thanks for the tip
