### ISSUE TITLE
Warlock demons speed

### ISSUE THREAD

**Issue by Toniculus** [chromiecraft/chromiecraft#716]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The demons should get more movement speed the farther he is then the players,atm it has the same movement speed..usuly when a player jumps from a higher ground the pet walks back the path to follows him at the same speed but because the players still runs foward it may result in the demon being a very long way behind or in some cases desummoning(ofc depends on how high the jump is and how long the path back is ) 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The demons should get a bonus movement speed when not in combat ofc and the player get at a certain distance(think 5-8 yards idk tbh :( ) and also the movement  bonus should stop when the player or the demon gets into combat 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get to the mage tower in SW ,on the top of the platform that leads to mage trainers
2.  Jump down and run to the trade distric in SW
3. the demon should run back the path and be with u by the time u get to the tailoring / herbalism trainer 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Toniculus** [comment]
Not only this but now with i testing using nifty speed watch for 40 %movement speed and they get despawned soo the demons do not scale with the player movement speed

**Comment by anguaive** [comment]
Thanks for the report! 

Can you point me to a pre-cata or classic source that confirms this?

**Comment by Toniculus** [comment]
> Thanks for the report!
> 
> Can you point me to a pre-cata or classic source that confirms this?

Patch 1.5.0 of classic wow - https://wowwiki-archive.fandom.com/wiki/Patch_1.5.0
"Pet speed has been increased when out of combat and following their master."  for both warlock and hunter
