### ISSUE TITLE
Dragonmaw Transporters do not fly their intended path

### ISSUE THREAD

**Issue by Chundelac** [chromiecraft/chromiecraft#7166]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Mob [Dragonmaw Transporter](https://wowgaming.altervista.org/aowow/?npc=23188) spawns at the dock where they usually spawn but stays there, stacks to tens or maybe hundred's of mobs. I could not count them as enabling name plates froze the game.

Due to the dock being in the area where players get the Dragonmaw Illusion it makes them not able to be attacked for the purpose of quest[ The Not-So-Friendly Skies...](https://wowgaming.altervista.org/aowow/?quest=11035) make it extremely hard to finish the quest.

![image](https://github.com/chromiecraft/chromiecraft/assets/11510682/05a82ee3-595f-4dfa-9b58-4681bacdd0e9)

Bug observed as of time of creating this bug report.

### Expected Blizzlike Behaviour

The Transporters should spawn and fly out on their intended fly path.

### Source

I dont have a source but that was how it worked a few days before and it seemed to work good.

### Steps to reproduce the problem

1. Go to Nethwerwing ledge on the dock where [Dragonmaw Transporters](https://wowgaming.altervista.org/aowow/?npc=23188) spawn
2. Either right away or after some time they will be stacking on top of each other

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dbec1a14417a968e6f874a637330ceac8cd16020

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
You should be able to attack them even with the illusion.

**Comment by heyitsbench** [comment]
Likely caused by https://github.com/azerothcore/azerothcore-wotlk/commit/c3fd59325cb1e0762d703e51e7d0a567b2d6b286.
