### ISSUE TITLE
[Hyjal] Archimonde uses his first Fear too soon

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7167]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Archimonde](https://wowgaming.altervista.org/aowow/?npc=17968) uses first [Fear](https://wowgaming.altervista.org/aowow/?spell=31970) after 25-35sec from the encounter starting.

### Expected Blizzlike Behaviour

[Archimonde](https://wowgaming.altervista.org/aowow/?npc=17968) shouldn't use his first [Fear](https://wowgaming.altervista.org/aowow/?spell=31970) before 40sec from starting the encounter

### Source

[TBC Classic1](https://youtu.be/Z10ESPoWKE0) fight start at 0:24 , first fear at 1:11 (47s)
[TBC Classic2](https://youtu.be/qJ8f4hAWnXg) fight start at 0:05 , first fear at 0:49 (44s)
[TBC Classic3](https://youtu.be/-mFAC2-Orv4) fight start at 0:15 , first fear at 0:57 (42s)
[TBC Classic4](https://youtu.be/_CRKCmwOngM) fight start at 0:06 , first fear at 0:51 (45s)
[TBC Classic5](https://youtu.be/G8zTshHWF5A) fight start at 43:05 , first fear at 43:52 (47s)
[TBC Classic6](https://youtu.be/JHeowAn-8X4) fight start at 0:05 , first fear at 0:49 (44s)

Multiple WClogs , i couldn't find any fear being casted before 40s
[Log1](https://classic.warcraftlogs.com/reports/1KVf2YzMCgNhc9tm#fight=1&hostility=1&source=5&type=casts&view=events&ability=31970) , [Log2](https://classic.warcraftlogs.com/reports/kXpWdaFPnbQRMy64#fight=71&hostility=1&source=186&view=events&type=casts&ability=31970) , [Log3](https://classic.warcraftlogs.com/reports/vbdBCFQ3XPzxHMVD#fight=8&hostility=1&source=43&type=casts&view=events&ability=31970) , [Log4](https://classic.warcraftlogs.com/reports/CTdR1GDytwfZrXLc#translate=true&fight=40&hostility=1&source=129&type=casts&view=events&ability=31970) , [Log5](https://classic.warcraftlogs.com/reports/12fzAqxhrpndwXRg#fight=38&hostility=1&source=135&type=casts&view=events&ability=31970) , [Log6](https://classic.warcraftlogs.com/reports/nv26Bj7aNKx1c8QG#fight=37&hostility=1&source=60&view=events&type=casts&ability=31970) , [Log7](https://classic.warcraftlogs.com/reports/txNJfGjwA6QHTrW9#translate=true&fight=103&hostility=1&source=472&view=events&type=casts&ability=31970) , [Log8](https://classic.warcraftlogs.com/reports/WAKRhfmnBcN3LDv6#fight=last&translate=true&hostility=1&source=199&view=events&type=casts&ability=31970) , [Log9](https://classic.warcraftlogs.com/reports/gnayAk4M3XKT86GV#fight=42&hostility=1&translate=true&type=casts&view=events&ability=31970) , [Log10](https://classic.warcraftlogs.com/reports/jHb34wR2VpzWJCMg#fight=last&hostility=1&type=casts&view=events&ability=31970&source=130)

### Steps to reproduce the problem

![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/df3334ff-c56b-48a8-8357-8e0b1d7f837e)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dbec1a14417a968e6f874a637330ceac8cd16020

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Thanks for the report! ❤️
