### ISSUE TITLE
Warlock T6 Hood of the Malefic has no wing effect.

### ISSUE THREAD

**Issue by Tzelanit** [chromiecraft/chromiecraft#7176]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

The flapping wings effect on Warlock T6 Helm does not appear.

On retail, the effect used to appear on every jump (until something in Cataclysm screwed it up for a while) but through all of TBC and WOTLK, it was on every jump and randomly while running around and idle.

I've stared at my character for a few hours running around, jumping, and idling, and it has not appeared once.

The item has not been transmogged and is toggled as visible in the display settings.

### Expected Blizzlike Behaviour

Wing effect should animate on every jump, and randomly otherwise.

### Source

In my research, there does not appear to be any specific spell ID attached to this affect, but there are countless posts over the years about the wing effect and their behavior across the internet.

These comments talk about the expected behavior in relatively decent depth, and at the least verify that the effect exists.

https://www.wowhead.com/item=31051/hood-of-the-malefic#comments

### Steps to reproduce the problem

There are no steps to reproduce this bug outside of donning the helm and watching as the wing effect never appears.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Seems to work for me, tried with/without transmog. it even works while mounted 
![image](https://github.com/chromiecraft/chromiecraft/assets/11332559/5ceea170-a040-4b3a-b274-732c80fce92e)

**Comment by heyitsbench** [comment]
The effect works fine, either a modified client or very unlucky.

**Comment by Tzelanit** [comment]
I wouldn't begin to know how to modify a client. I just downloaded what's offered through the CC website and added the HD patch and have been playing normally since.

I saw another Warlock with the helm today and followed them around like a creep for about 10-15 minutes, and I never saw their wings either. 

I suppose I'm just very unlucky.
