### ISSUE TITLE
Mob abilities in Darkshore

### ISSUE THREAD

**Issue by SLS20** [chromiecraft/chromiecraft#718]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

*Please consider reading extra notes first, there is the foundation of this report.*
1. In Darkshore, the whole Foreststrider family, including [Foreststrider Fledgling](https://wowgaming.altervista.org/aowow?npc=2321), [Foreststrider](https://wowgaming.altervista.org/aowow?npc=2322) and [Giant Foreststrider](https://wowgaming.altervista.org/aowow?npc=2323) possess ability [Thrash trigger(spell=12787)](https://wowgaming.altervista.org/aowow?spell=12787).![WoWScrnShot_052721_201002](https://user-images.githubusercontent.com/84748472/119985118-891ef480-bfc2-11eb-91ec-34d325fb6659.jpg)
2. [Blackwood Pathfinders](https://wowgaming.altervista.org/aowow/?npc=2167#abilities) have incorrect version of Thrash trigger, please note that this is only my speculation of comparing AoWoW DB and [ref DB](https://wotlkdb.com/), not in-game testing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. None of them should be able to cast any kind of Thrash.
2. Blackwood Pathfinder should have [Proc chance: 25% version](https://wotlkdb.com/?spell=54913#used-by-npc), not the 35% version.

##### SOURCE:

ref DB: https://wotlkdb.com/

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to darkshore (preferably around level 14 as a cloth-type class)
2. Challenge any previously mentioned mobs
3. !?
4. Check the combat log

##### EXTRA NOTES:

1. A confusing detail of AoWoW DB, although Thrash(spell=12787) is mentioned on the [Foreststrider's page](https://wowgaming.altervista.org/aowow/?npc=2322), Foreststrider isn't listed on the "Used by" of [Thrash(spell=12787)](https://wowgaming.altervista.org/aowow/?spell=12787#used-by-npc).

2. It's difficult to find a good source of knowledge for wotlk, as classic wotlk hasn't arrived yet and wayback machine is incomplete for reference in general, so for the purpose of this report I use https://wotlkdb.com/ as my reference, but it isn't much better to be honest, for example: [Blackwood Tracker](https://wotlkdb.com/?npc=11713#abilities) is described to have [Thrash(spell=3391)](https://wotlkdb.com/?spell=3391#triggered-by), but that spell is only an action(hit two extra times), not a percentage trigger, It's not clear to me how that's supposed to work.

3. I also tried to check the classic wowhead page, but it's even more confusing there, as [Blackwood Tracker](https://classic.wowhead.com/npc=11713/blackwood-tracker#abilities) is listed to have multiple versions of thrash-triggers, which one(10%, 15%, 35%) is supposed to be used?

4. *Update*, I found a video of a player fighting striders in classic wow, if it would be of any help: https://youtu.be/vhKiSTZnjLI?t=180

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
I never understood why any of those low level creatures (there are quite a few) have such a powerful ability (granting them a triple attack). According to Wowpedia **Thrash** is an ability or rather proce effect that certain **bosses** have.

https://wowpedia.fandom.com/wiki/Thrash_(proc)

I know that quite a few databases (last but not least `classic.wowhead`)  list "**Thrash** as a combat ability of many creatures (often multiple versions), but it does not make any sense at all.

**Comment by SLS20** [comment]
> I never understood why any of those low level creatures (there are quite a few) have such a powerful ability (granting them a triple attack). According to Wowpedia **Thrash** is an ability or rather proc effect that certain **bosses** have.
> 
> https://wowpedia.fandom.com/wiki/Thrash_(proc)
> 
> I know that quite a few databases (last but not least `classic.wowhead`) list **Thrash** as a combat ability of many creatures (often multiple versions), but it does not make any sense at all.
> 
> As for the video you linked. I couldn't see a single triple attack. I'm pretty sure, he woud have died on CC doing the same thing.

Yes, I suppose games in general are tolerant of quirks, it can be confusing to blizzard's own developers as well😅, after all game devs love to use "hack-techniques" to circulate problems, not that it's wrong tho ;)

**Comment by Stump876** [comment]
This is actually something I had on my list to check out more. The [ogres](https://wowpedia.fandom.com/wiki/Mosh%27Ogg_Brute) in Stranglethorn right outside of Grom gol do the same thing. It also looks like the ability is indeed proccing off itself cause it happened a few times in a row with me and it took a huge amount of health seemingly all at once. I was dead before I knew it. 
![image](https://user-images.githubusercontent.com/68164076/120051862-4ddaf080-bfd7-11eb-833e-5f3ff43c3cb7.png)

**Comment by Azcobu** [comment]
Checking the DB, the Forestriders and the Blackwoods are using the same Thrash spell, ID 12787. It has a 35% proc rate. The Spells.DBC file also contains data for 10%, 15%, 25% and 100% proc Thrash spell variants, so I don't think it would be difficult to tone down the Pathfinder's version of it if we decided to. 

Also found brief footage of another Foreststrider attack here: https://youtu.be/pa4SuHwKULM?t=1686 No signs of triple attacks, but it's only a short clip so not very good proof either way. Might check the TC DB in the absence of any better data and see what they have for these mobs.
