### ISSUE TITLE
Flying Machine Audio Issues

### ISSUE THREAD

**Issue by Cremdeuspai** [chromiecraft/chromiecraft#7187]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

I have recently acquired the Flying Machine from Engineering and when i went to test it out I noticed the audio was not playing properly. When you move forward sometimes the audio will start very quietly untill it gets to normal volume and then it will fadeout, repeating this proccess. Sometimes it'll fly silent for 5-6 seconds before the audio fades in again. Strafing (default keybind Q and E) also "resets" the audio. When it's idle it plays normally but flying makes the audio go kinda wonky. Thank you.

### Expected Blizzlike Behaviour

This was the best video i could find, its the faster version of the mount but the audio is the same I'd imagine. https://www.youtube.com/watch?v=PLiPdf_0d20

### Source

I don't know if i understood but the source is 1st hand experience, i noticed this not too long after using the mount.

### Steps to reproduce the problem

1. Mount on Flying Machine
2. none
3. Fly using different keys and notice how the audio isnt constant.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I understand what you mean. I checked the issue, but I don't know if It is a server problem or a client problem.
I need a second opinion.

**Comment by heyitsbench** [comment]
I believe this would be a client problem, not something we can solve.
