### ISSUE TITLE
Mage - Blinking through the world

### ISSUE THREAD

**Issue by Negativfraction** [chromiecraft/chromiecraft#7188]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

50-59

### Current Behaviour

Couldn't see an obvious way to log this call on the website or the discord, you are potentially not having as many bugs reported if people cant see how to report them.
Its happened for a while but its been here and there, maybe 3 times in total before the last couple of days, but i will blink, i usally jump first anyway but its pulling me through the world floor and spitting me out some where different after a long fall so i have to rekill everything or travel back.
Its happened 3-4 times this week and its putting me off my mage tbh,
I have cata textures installed from the chromie site, all apart from the trees which would conflict with the cities, but as this updated the character models i would imagine not?

### Expected Blizzlike Behaviour

In retail i mained a mage for cata and in days of gameplay and raiding, i didnt have this once, so i would expect it not to happen in a perfect world, but i will take once every so often atm.

### Source

Icant see how this would be a applicable to a spell interaction with the game world.

Seems mage related, but after speaking in world, it seems a warriors charge can do this also, so it may be the world textures.

### Steps to reproduce the problem

1. Get a mage
2. Level it to 55 and blink a lot
3. get rekt

### Extra Notes

i am happy to talk to anyone about this, i'm a platform engineer so im quite technical and would be happy to help if i can

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I don't need to test this bug, because it happened to me too.
