### ISSUE TITLE
Pathing issue for a Disembodied Vindicator in Netherstorm

### ISSUE THREAD

**Issue by FrodoFragginz** [chromiecraft/chromiecraft#7198]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

A Disembodied Vindicator has a minor pathing issue where he runs away and up to find a path to me.  starts at 4:28 when I taunt it.

https://www.youtube.com/watch?v=7fr10JGtQ6s&t=266s

### Expected Blizzlike Behaviour

Ideally mobs will run towards you once aggrod.

### Source

Standard mob behavior is to run towards the player.  Must be a weird terrain issue in that spot.

### Steps to reproduce the problem

1. Aggro the specified Disembodied Vindicator from the direction in the video.  Observe it run away from you to find a path to you.
2. keep moving forward and you'll pass the point where it can actually now run at you.  I'm guessing it's roughly at the spot where it spawns.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
It seems that this problem is no longer present. It has probably already been fixed.

I close this issue. Thank you for the report.
