### ISSUE TITLE
Azgalor rain of fire is not even remotely close to blizzlike.

### ISSUE THREAD

**Issue by goldritens** [chromiecraft/chromiecraft#7200]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Rain of fire casting way too fast and has an inaccurate hitbox. There are pulls on CC where it will cast back to back to back with no time in between the previous RoF ending and the new RoF starting, causing melee/tank to basically be running and kiting the boss for large portions of the fight because of how inaccurate the hitbox is.

### Expected Blizzlike Behaviour

TBC classic Azgalor RoF casted 2-4 times (roughly every 40 seconds) on a decent performing raid group. Hitbox should be adjusted so that melee/tanks barely have to move. Damage on the DoT is probably too high, but I don't think it would matter if the hitbox and casting patterns were more accurate.

### Source

https://www.youtube.com/watch?v=i5LSvCZzHqs

### Steps to reproduce the problem

pull the boss

### Extra Notes

as you can see in the video, RoF is casted 3 times in a 2ish minute fight and the tank has to move one time. Melee barely moves at all because the hitbox should allow melee to just swap to the other side of the boss or walk towards the front legs on the side of the boss. This is historically supposed to be the easiest boss in the raid, but buffed RoF damage, inaccurate casting behavior, inaccurate RoF hitbox, and increased boss melee damage make it an RNG fight where you are just hoping that RoF is casted on ranged and not melee.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> RoF casted [...] roughly every 40 seconds

This does not look to be true, from what I can see in the linked video, first cast appears to be at 0:20 (these all judging by either seeing RoF or seeing the DoTs on players in the raid frames), second at 0:44 (24s), third at 1:07 (23s), fourth at 1:26 (19s), and fifth at 1:55 (29s). Currently on CC, it's cast 25s into the fight and repeats every 15s, so that does look like it could use adjustment.

> Hitbox should be adjusted so that melee/tanks barely have to move.

This is almost certainly a symptom of a global hitbox problem with AoE spells calculating from model edges rather than centers.

> Damage on the DoT is probably too high, [...]

Compared to Wrath values, almost certainly, but that is a tuning issue and would not be made in an issue report.

**Comment by amed80** [comment]
Those are the timers for RoF in this Wotlk Classic solo video https://youtu.be/-uP7OdsehZ0?t=404
![image](https://github.com/user-attachments/assets/83de76d5-dc3c-49b4-af27-dd05e4fd763f)

**Comment by heyitsbench** [comment]
Timings have been adjusted in the linked PR, as far as I'm concerned all that's left of this issue is the Rain of Fire calculating from hitbox edges rather than centers.

**Comment by BeefSteaker** [comment]
> Timings have been adjusted in the linked PR, as far as I'm concerned all that's left of this issue is the Rain of Fire calculating from hitbox edges rather than centers.

Closing then as this was fixed by terenecklas recent PR. marking linked as the report was valid
