### ISSUE TITLE
Infernal cant be commanded

### ISSUE THREAD

**Issue by veredis1** [chromiecraft/chromiecraft#7202]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

If u use the Infernal inside a Raid or Dugeon at least at bosses u cant command it and the pet bar disappears. Afterwards it stands 1 min by ur side. It happend for me in Hyjal at Archimonde like 3 times than I tried it and also in Steamvault heroic at Warlord Kalithresh there the same happened. In the Overworld it seems to work fine.

### Expected Blizzlike Behaviour

The Infernal should be under your command for 1 min after using it.

### Source

Sorry didnt make a screenshot or video 

### Steps to reproduce the problem

1. enter dugeon or Raid
2. fight the bosses
3. use Infernal
4. see that the petbar disappears and the Infernal idles

### Extra Notes

didnt had the time to try it on other bosses, but I think it could be a generic bug for all bosses, I didnt testet it on trash 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
I can't really produce it on my local, could be a cc only issue.

**Comment by forvlen** [comment]
i can confirm that it doesn't work i used it on hellfire dungeon and i couldnt control it .

**Comment by heyitsbench** [comment]
Please feel free to reopen it if you find consistent reproduction steps.
