### ISSUE TITLE
Karazhan Nightbane

### ISSUE THREAD

**Issue by AcetylGer** [chromiecraft/chromiecraft#7203]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Not flapping his wings, untargetable in the air, flying around the tower, landing somewhere and then flying/strafing to the other side just to notice that tank has aggro and speeding back to the tank. 

### Expected Blizzlike Behaviour

Should be flapping his wings while flying. Should not "speed up" after every flight phase. It seemed like the boss was all over the place with his pathing and even with the Tank grabbing aggro immediately after landing he ran all the way to the furthest away range dps and then before reaching the dps ran back towards the tank and what feels like 4x speed.

### Source

.

### Steps to reproduce the problem

Problem happened on live with a full 10 man Grp

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by AcetylGer** [comment]
Seperate Issues created for each Problem:

- Nightbane not flapping his wings: HD patch prevents this visual, without HD patch it looks normal.
- Nightbane is too fast: #7204 
- Nightbane untargetable while in the air #7205

**Comment by AcetylGer** [comment]
With HD patch
![Screenshot 2024-07-14 022647](https://github.com/user-attachments/assets/91ccb7fc-21ba-4f41-8701-eab68aea0a2f)

Without HD patch
![Screenshot 2024-07-14 025710](https://github.com/user-attachments/assets/374279cc-028d-419b-877c-6070cbbe1095)

**Comment by Tharabas87** [comment]
I've tested some issues you reported on the PTR and I can confirm them all in their specific reports.
The comment here is only to confirm also the not flapping wings visual bug from HD patch. During the summoning and also during the fight (both ground phase and air phase) Nightbane looks static, not animating at all from his "pre summon" posture.

- Nightbane not flapping his wings: HD patch prevents this visual, without HD patch it looks normal.
- Nightbane is too fast: https://github.com/chromiecraft/chromiecraft/issues/7204
- Nightbane untargetable while in the air https://github.com/chromiecraft/chromiecraft/issues/7205

Thank you for your report. If you notice other issues during your playing on CC feel free to report them.
