### ISSUE TITLE
[Black Temple] Vengeful Spirit wrong behavious

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7210]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Killing [Teron Gorefiend](https://wowgaming.altervista.org/aowow/?npc=22871) instantly make the players dismiss their [Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109).
After a player release their [Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109) manually , it will not disappear unless 1mn has passed from when it appeared is reached.
[Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109)'s abilities have wrong key position , they are at 1 2 3 4 5.

### Expected Blizzlike Behaviour

Killing [Teron Gorefiend](https://wowgaming.altervista.org/aowow/?npc=22871) should not dismiss any existing [Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109) , the should be dismissed if the player remove them manually or the [1mn buff](https://wowgaming.altervista.org/aowow/?spell=40268) timer is over.
[Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109) should instantly be removed if the player dismiss them manually.
[Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109)'s ability should be at 1 3 4 5 7

### Source

[TBC Classic1](https://youtu.be/jl0eC51036s?t=2230) at 37:11 Vengeful Spirit disappear as soon the paladin dismiss it.
[TBC Classic2](https://youtu.be/6RRa9Oi6KCg?t=6716) after killing [Teron Gorefiend](https://wowgaming.altervista.org/aowow/?npc=22871) at 1:52:16 , you can see 2 [Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109) are still moving around and they disappear later as people dismiss them/the timer runs out.
[Pre-Wotlk Classic](https://youtu.be/bh2oqwB8mKw?t=664) at 11:04 you can see the position of the abilities in his action bar 

### Steps to reproduce the problem

1. .tele bt
2. engage with [Teron Gorefiend](https://wowgaming.altervista.org/aowow/?npc=22871) with 2 characters
3. Wait for [Teron Gorefiend](https://wowgaming.altervista.org/aowow/?npc=22871) to cast his Shadow of Death on your second character
4. Wait for the [Shadow of Death](https://wowgaming.altervista.org/aowow/?spell=40251) timer to run out and see your [Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109)'s abilities position on your action bar
5. dismiss [Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109) before the [1mn buff](https://wowgaming.altervista.org/aowow/?spell=40268) runs out
6. revive 2nd character and repeat 3-4 then kill [Teron Gorefiend](https://wowgaming.altervista.org/aowow/?npc=22871) while you are still controlling [Vengeful Spirit](https://wowgaming.altervista.org/aowow/?npc=23109).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
The thing about the spells being in the wrong places in the action bar is a problem in the core and harder to fix, rather in the creature's or boss' script. Once that core problem is handled, though, it should automatically fix it.

See https://github.com/azerothcore/azerothcore-wotlk/issues/16047 for more info.

**Comment by heyitsbench** [comment]
Spell position issue *should* be resolved by https://github.com/azerothcore/azerothcore-wotlk/pull/19811 if/when it's merged.
