### ISSUE TITLE
Ritual of summoning minor bug

### ISSUE THREAD

**Issue by goldritens** [chromiecraft/chromiecraft#7218]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Cannot summon yourself from warlock summoning portals, unsure if summoning stones share same behavior. Had whole group try to summon themselves to be sure it wasn't a user error/bug. Nobody was able to click the summoning portal while selecting themselves as the summon target.

### Expected Blizzlike Behaviour

Should be able to target yourself and summon yourself at a warlock summoning portal.

### Source

![image](https://github.com/user-attachments/assets/8a20e8b6-152c-4b14-a7c8-a920d8cfb8ba)
https://www.wowhead.com/wotlk/spell=698/ritual-of-summoning#comments

### Steps to reproduce the problem

1. cast ritual of summoning for warlock summoning portal
2. select self and try to summon self

### Extra Notes

unsure if you can self summon at meeting stones, have not been able to test.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/441fdc324f5c28c7859cb670103d93b771f80438

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
The comment is from 2006 so TBC. 
Are you sure that this "feature" hasn't been removed in wotlk? 
I'm the first that don't believe to his question, but I want to hear (read) other opinions.

**Comment by heyitsbench** [comment]
This did work in Wrath Classic iirc.
