### ISSUE TITLE
Flame Cap herbs in Zangarmarsh not spawning as required

### ISSUE THREAD

**Issue by Mordecaii2018** [chromiecraft/chromiecraft#7221]
Good Afternoon,

Per title, this is regarding the Flame Cap herbs in Zangarmarsh.

They should be a rare spawn from Ragveil, but I've been farming the zone a couple of days and what I can find is:

1. Ragveil doesn't rarely spawn Flame Caps at all.
2. Flame Caps exist in ZM, but they have a fixed location, so when you pick them, they will eventually respawn at the same location, rather than actually spawning off rarely from all Ragveil herbs in Zangarmarsh.

It's either the above, or I'm extremely unlucky / bad RNG, but still I have a feeling it's not working as it should (i.e. Flame caps should be spawning rarely from Ragveil, not having their own spawn points on the map), considering I've been farming for over 5 days periodically.

Thank you

**Comment by heyitsbench** [comment]
Wowhead indicates Ragveil does not drop Flame Caps at all. Please open a new issue [following the provided issue template](https://github.com/user-attachments/assets/79da6fd8-a44b-45ef-af3a-896c17022d0a) including a source for the behavior you expect to see.
