### ISSUE TITLE
Report related to ticket "#7221" (Flame Cap related)

### ISSUE THREAD

**Issue by Mordecaii2018** [chromiecraft/chromiecraft#7227]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Hi,

As described on https://github.com/chromiecraft/chromiecraft/issues/7221, Flame Cap spawns should be happening from Ragveil, rather than having their own spawn points.

I probably didn't explain the issue correctly on ticket 7221.

Current behavior:

Flame Cap herbs have a fixed spawn location on Zangarmarsh.

### Expected Blizzlike Behaviour

Flame Caps should NOT drop from Ragveil, BUT should spawn where Ragveil herbs usually spawn.

To explain this a bit further, when you pick up a Ragveil herb successfully, there is a small chance for it to respawn as a Flame Cap (and obviously a high chance for it to spawn as Ragveil again). This is the issue - Flame caps have their own spawn points currently; they are not spawning rarely instead of Ragveil, atleast from what I have seen the past few days farming in Zangarmarsh.

### Source

https://www.wowhead.com/tbc/item=22788/flame-cap#comments

See the first comment - **Flame Cap is the rare spawn of Ragveil.**

### Steps to reproduce the problem

Farm Ragveil endlessly, no Flame Caps are rarely spawning instead of Ragveil.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/441fdc324f5c28c7859cb670103d93b771f80438

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Mordecaii2018** [comment]
Extra note I just remembered to add - The few fixed Flame Cap herb locations around Zangarmarsh do not spawn Ragveil either - They are always respawning as Flame Caps.

**Comment by heyitsbench** [comment]
CC: @Gultask

**Comment by Gultask** [comment]
Ough I'll do it after I finish an Uni assignment >:(

From like 20 or so dungeon runs I think Flame Cap chances there were 10%, so I'll use that. It'll also be super easy to change chance *after* anyways.

Current pooling for Ragveil is this:
![196072356-e6610ea6-0a5b-4a31-8c46-16dda4d352ba](https://github.com/user-attachments/assets/749e69e2-1d46-4c37-9bb9-b57376141de9)
Current pooling limit for Flame Cap is 3 so I'll divide Zangarmarsh into 2 like above and make it 18-18

**Comment by Gultask** [comment]
![196072344-1b26fb57-9bbf-42a3-9634-f5e79d8b6c2e](https://github.com/user-attachments/assets/fbbe2318-7e03-4de3-ab7a-abb5aaf2be8d)
