### ISSUE TITLE
[Black Temple] Essence of Suffering and Essence of Desire missing taunt immunity

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7234]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Essence of Suffering](https://wowgaming.altervista.org/aowow/?npc=23418) and [Essence of Desire](https://wowgaming.altervista.org/aowow/?npc=23419) can be taunted

### Expected Blizzlike Behaviour

[Essence of Suffering](https://wowgaming.altervista.org/aowow/?npc=23418) and [Essence of Desire](https://wowgaming.altervista.org/aowow/?npc=23419) should be immune to taunt

### Source

[TBC Classic](https://youtu.be/6LaUtP65n9g?t=6683) at 1:51:24 , Druid uses [Growl](https://wowgaming.altervista.org/aowow/?spell=6795) on [Essence of Suffering](https://wowgaming.altervista.org/aowow/?npc=23418) which shows Immune
[Pre Wotlk Classic](https://youtu.be/TRPy6G0UhcA?t=3345) at 55:46 the Warrior uses [Taunt](https://wowgaming.altervista.org/aowow/?spell=355) on [Essence of Desire](https://wowgaming.altervista.org/aowow/?npc=23419) which shows Immune

### Steps to reproduce the problem

1. .tele bt
2. start the fight with Reliquary of Souls
3. try to taunt (ex 62124) Essence of Suffering (phase 1)
4. Kill Essence of Suffering
5. try to taunt (ex 62124) Essence of Desire.

### Extra Notes

This does not affect the p3 [Essence of Anger](https://wowgaming.altervista.org/aowow/?npc=23420) which should stay tauntable.
https://youtu.be/wy1nf_RM_Qg?t=9175

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/339506cbedab8608f97eeb985f326a14260fbc0d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
I wonder if this is related to https://github.com/chromiecraft/chromiecraft/issues/7157 because Fixate is a taunt spell
![image](https://github.com/user-attachments/assets/050575b6-4268-4a51-ab92-904d2c23361d)

**Comment by amed80** [comment]
The problem is if Essence of Suffering is Fixated on a target , other people can taunt him atm which make him play a ping pong game between his fixated target and the people that keep taunting him. I don't believe adding "no taunt" flag to it will cause any problem with that spell.
I don't know if the information in that report are accurate or if there was any changes to the boss between that report and now but Fixate seemed to be working correctly? it was switching to the closest target every time i test the boss.

**Comment by Gultask** [comment]
That Fixate spell has a script, maybe something happened between both fights that caused the script not to function properly. I don't usually work with spell scripts so it's uncharted territory for me 😭

**Comment by Nyeriah** [comment]
Adding the flag according with the feedback above
