### ISSUE TITLE
[Black Temple] Mother Shahraz's Fatal Attraction is in pre-nerf state

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7239]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Mother Shahraz's Fatal Attraction is in pre-nerf state (dealing 3k damage each tick)

### Expected Blizzlike Behaviour

Mother Shahraz's Fatal Attraction should deal reduced damage with the first two ticks  , first tick should be 1k , second tick should be 2k then all subsequent ticks should be 3k

### Source

[Old TBC](https://youtu.be/ctBU0vvSOzo?t=43) at 0:43 the warrior gets teleported and take damage 1k>2k>3k
[Bluetracker](https://www.bluetracker.gg/wow/topic/us-en/711993555-raid-and-dungeon-encounter-update/)
![image](https://github.com/user-attachments/assets/8b3ed3d6-0927-41e1-8f48-fe98337b8465)
[WClog](https://classic.warcraftlogs.com/reports/VPNbjR7kGDBWv83Z#fight=35&translate=true&type=damage-done&view=events&hostility=1&ability=40871&target=37)
![image](https://github.com/user-attachments/assets/59939553-2259-4a3e-b617-2d416fbee524)
1st tick at 00:28.485 was 1k , 2nd tick at 00:29.498 was 2k , 3rd tick at 00:30.510 was 3k , 4th tick at 00:31.476 was 3k

### Steps to reproduce the problem

1. .tele bt with at least 3 characters
2. Tank Mother Shahraz with one character
3. wait for it to cast Fatal Attraction on the other 2 characters.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/339506cbedab8608f97eeb985f326a14260fbc0d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IskrenPlashkov** [comment]
This should be in line with existing server philosophy of keeping TBC content in its original format when it was current content, not with the additions brought by WotLK.
I.E. Attunements, gates before last boss opening after you clear all else etc.

**Comment by amed80** [comment]
Firstly i think the core is suppose to mimic everything in their wotlk version which is why for example Vashj didn't have MC and Illidan will not have Shear.
Secondly the nerf from 3k first tick to 1k then 2k was made in TBC as it shown in the source above and not related to wotlk release.
This is another blue post shows that the change was also mentioned in [Patch 2.2.0](https://www.bluetracker.gg/wow/topic/us-en/1777875139-world-of-warcraft-client-patch-220-notes/)
![image](https://github.com/user-attachments/assets/c7b96696-6d0c-4f65-b4b5-e50d95ae622e)

**Comment by avarishd** [comment]
https://wowpedia.fandom.com/wiki/Patch_2.2.0
Fatal Attraction now deals 750 damage on the first tick, 1500 on the second, 2250 on the third, and 3000 on all subsequent ticks.

**Comment by amed80** [comment]
I think that was misinformation in wowpedia? i tried to check multiple videos for it and basically the numbers don't add up of how resistance used to work in TBC and it's the same shown in the logs , it's why the first bluepost say the first two seconds.

**Comment by avarishd** [comment]
Could be.

**Comment by Nyeriah** [comment]
How should it be then?

**Comment by amed80** [comment]
I believe the first tick should be 1k and second tick should be 2k and the rest are 3k , i believe those are the correct numbers that were live on retail and same for classic.
Also should be the same amount if anyone have a sniff from cata classic
