### ISSUE TITLE
[Black Temple] Mother Shahraz spamming Beams

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7241]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Mother Shahraz](https://wowgaming.altervista.org/aowow/?npc=22947) is using multiple Beams at the same time.
![image](https://github.com/user-attachments/assets/efe1174d-f7ea-4300-ab2c-a831fed31a8e)

### Expected Blizzlike Behaviour

[Mother Shahraz](https://wowgaming.altervista.org/aowow/?npc=22947) randomly pick one beam from [Sinful Beam](https://wowgaming.altervista.org/aowow/?spell=40862) , [Sinister Beam](https://wowgaming.altervista.org/aowow/?spell=40863) , [Vile Beam](https://wowgaming.altervista.org/aowow/?spell=40865) and [Wicked Beam](https://wowgaming.altervista.org/aowow/?spell=40866) and she keep using the same beam 3 times with interval of 9s each time then after the 3rd time it will pick another random beam and repeat the same cycle.
From the logs below (and more in WClogs) the same behavior happens every time , it choose a random Beam that it uses it 3 times with 9s interval then after the 3rd cast it has longer CD (12-18s) then it repeat the same steps again.

### Source

[Bluetracker](https://www.bluetracker.gg/wow/topic/us-en/711993555-raid-and-dungeon-encounter-update/)
![image](https://github.com/user-attachments/assets/350dc724-394f-4305-b8e8-b7332cb4779c)
WClogs:
[Log1](https://classic.warcraftlogs.com/reports/cA4CYFjhJw6kzr7b#translate=true&fight=10&hostility=1&type=damage-done&view=events&source=92)
First Beam was Sinister Beam
First Cast at 00:14.268 ,Second Cast at 00;23.246 , Third Cast at 00:32.241
Second Beam was Vile Beam
First Cast at 00:50.292 , Second Cast at 00:59.287 , Third Cast at 01:08.292
Third Beam was Wicked Beam
First Cast at 01:20.624 , Second cast at 01:29.628 , Third Cast at 01:38.647
Fourth Beam was Sinful Beam at 01:50.007 then the fight ended
[Log2](https://classic.warcraftlogs.com/reports/Bb9qa6p7Lk8hGFHA#translate=true&fight=16&type=damage-done&hostility=1&source=61&view=events)
First Beam was Sinister Beam
First Cast at 00:15.456 , Second Cast at 00:24.461 , Third Cast at 00:33.464
Second Beam was Wicked Beam
First Cast at 00:47.858  , Second Cast at 00:56.855 , Third Cast at 01:05.856
Third Beam was Sinful Beam
First Cast at 01:20.285 , Second Cast at 01:29.293 , Third Cast at 01:40.005

### Steps to reproduce the problem

1. .tele bt
2. fight Mother Shahraz
3. look at the

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/339506cbedab8608f97eeb985f326a14260fbc0d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IskrenPlashkov** [comment]
How many characters were u using during the test ? We did not encounter this few weeks ago.

**Comment by amed80** [comment]
I believe this was caused by a recent change

**Comment by avarishd** [comment]
@Gultask

**Comment by Gultask** [comment]
Ohhhh I messed up big time I see it now. My bad. Fixing this right now
