### ISSUE TITLE
[Black Temple] Mother Shahraz shouldn't have Frenzy ability

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7242]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Mother Shahraz](https://wowgaming.altervista.org/aowow/?npc=22947) uses [Frenzy](https://wowgaming.altervista.org/aowow/?spell=40683) when it reaches 10%

### Expected Blizzlike Behaviour

[Mother Shahraz](https://wowgaming.altervista.org/aowow/?npc=22947) shouldn't use [Frenzy](https://wowgaming.altervista.org/aowow/?spell=40683) at any point of the fight.
She emotes? going Frenzy and yell "Stop toying with my emotions!" at 10% but she doesn't use any ability related to frenzy.

### Source

In those videos , you can see she uses no frenzy ability or do any Frenzy behaviors from when she hit 10% hp until they kill her.
[TBC Classic1](https://youtu.be/fUDIErjbUHs?t=224) starting from 3:47
[TBC Classic2](https://youtu.be/DCbhQePBqXo?t=94) starting from 1:34
[TBC Classic3](https://youtu.be/knJwOn1GznY?t=231) starting from 3:51
[PTR TBC Classic1](https://youtu.be/wRi05I7Fry4?t=242) starting from 4:02 , you can see he was expecting it to go frenzy/enrage following what some guides say but the boss never does.
[PTR TBC Classic2](https://youtu.be/x5WBlrP6IBU?t=197) starting from 3:17
[TBC Vanilla](https://youtu.be/bJCdpfwiwNo?t=212) starting from 3:32
[TBC Vanilla](https://youtu.be/CAsGBT0kWzU?t=580) Nihilum World First , starting from 9:42

### Steps to reproduce the problem

1. .tele bt
2. start the fight with Mother Shahraz
3. .damage Mother Shahraz until it reaches 10%

### Extra Notes

She might using her other abilities differently when she hit 10% hp but i have no proof or clear evidence about that 🤷

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/339506cbedab8608f97eeb985f326a14260fbc0d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Judging from https://wowpedia.fandom.com/wiki/Mother_Shahraz the emotes should be on enrage.

**Comment by amed80** [comment]
![image](https://github.com/user-attachments/assets/5dc133c9-a85d-4074-8147-3b097e7e7ddc)
talking about that yellow text at the top "Mother Shahraz becomes enraged!" , i don't know if that is related to an addon or the fight itself? probably need a sniff for that part

**Comment by heyitsbench** [comment]
The text shows up in the sniff at 10%, but no spell gets cast alongside it.

**Comment by avarishd** [comment]
classic bait by activision

**Comment by amed80** [comment]
In this [video](https://youtu.be/fUDIErjbUHs?t=209) , it seems that after the 10% , Mother Shahraz will stop her normal rotation with the beams (3 casts for the same beam before choosing a new one) it will start casting a random beam each 9? seconds
At 3:33 and before reaching 10% , she was using Vile Beam (the dot on the tank) then after reaching the 10% , she used Wicked Beam (-1000 mana) then Sinister Beam (knocked the casters to the air)
