### ISSUE TITLE
"Smily" Smalls seems to spawned in twice (Arena Vendor)

### ISSUE THREAD

**Issue by veredis1** [chromiecraft/chromiecraft#7246]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

In area 52 the arena vendor Leeni "Smily" Smalls seems to spawned in twice on top of each other

### Expected Blizzlike Behaviour

She should be there just once

### Source

https://www.wowhead.com/wotlk/npc=24392/leeni-smiley-smalls

### Steps to reproduce the problem

1. Go there
2. Observe

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/339506cbedab8608f97eeb985f326a14260fbc0d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
# Tested :x:

I am using enUs client compared to the reporter.

Cannot reproduce on PTR
![WoWScrnShot_082024_171546](https://github.com/user-attachments/assets/90e040ff-691f-4870-9c8f-c4b89ffddeb4)

**Comment by heyitsbench** [comment]
![Live realm.](https://github.com/user-attachments/assets/107fa97b-6c48-4196-9888-4d32208cf146)

**Comment by alecsci** [comment]
What client do you have @heyitsbench ?

**Comment by alecsci** [comment]
What client do you have @heyitsbench ?

**Comment by heyitsbench** [comment]
Client is irrelevant for this issue, but enUS.

**Comment by alecsci** [comment]
I cannot reproduce this issue at all in PTR. 
Neither on my local setup which uses the last commit of AC.
@heyitsbench is your SS from the live server ?

**Comment by heyitsbench** [comment]
> is your SS from the live server ?

Yes.

**Comment by alecsci** [comment]
Maybe someone from staff can have a look, seems specific only to CC server, not AC.

**Comment by alecsci** [comment]
Similar reports: https://github.com/chromiecraft/chromiecraft/issues/7324#issue-2498942953

**Comment by Rorschach91** [comment]
Issue solved.
