### ISSUE TITLE
[Black Temple] Gathios the Shatterer shouldn't use Hammer of Justice on random players

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7259]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Gathios the Shatterer](https://wowgaming.altervista.org/aowow/?npc=22949) keep using [Hammer of Justice](https://wowgaming.altervista.org/aowow/?spell=41468) on random players.

### Expected Blizzlike Behaviour

[Gathios the Shatterer](https://wowgaming.altervista.org/aowow/?npc=22949) should only use his [Hammer of Justice](https://wowgaming.altervista.org/aowow/?spell=41468) on his current target if he is between 10-40y
![image](https://github.com/user-attachments/assets/739445aa-82c1-4391-bb62-868cc6401554)

### Source

[Old TBC](https://youtu.be/iB5CuV3_CQk)
[TBC Classic1](https://youtu.be/_tSYK-ah6rg?t=1665)
[TBC Classic2](https://youtu.be/w2J_LVAXHvY)
[TBC Classic3](https://youtu.be/mKHqlPZ_Htk)
[TBC Classic4](https://youtu.be/MH2BKL4G_BQ?t=9930)
All the above videos shows that Hammer of Justice was never used during the raid as the tank was always close to him.
[Pre-Wotlk Classic](https://youtu.be/TRPy6G0UhcA?t=5616) at 1:33:36 the tank dies then you can see that the shaman in group3 got hit with Hammer of Justice which is probably because he was the next person on threat and was away by 10-40y from Gathios.
Same thing happens at 1:39:37 and 1:52:23 you can see Gathios turn around the warlock and stun him before running towards him
The clearest one comes at 1:58:59 , Gathios target the warlock Muffz and stuns him and he used it again at 1:59:17 which probably mean it has CD of ~18s.

### Steps to reproduce the problem

1. .tele bt
2. fight Illidari council with 2 characters
3. have one character tank [Gathios](https://wowgaming.altervista.org/aowow/?npc=22949) and the seconds one sit away from him with in 10-40 range
4. watch 2nd character keep getting stunned each 20s

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Carriola-wotlk** [comment]
Behavior reported confirmed by code (file: src\server\scripts\Outland\BlackTemple\illidari_council.cpp):
![immagine](https://github.com/user-attachments/assets/ebbea546-953b-4c9a-8953-875fc7c03730)

**Comment by Carriola-wotlk** [comment]
Selecting a random player as the target is the correct behavior, as you can see from this link: https://www.wowhead.com/tbc/npc=22949/gathios-the-shatterer

![immagine](https://github.com/user-attachments/assets/44f9e8eb-f361-42ae-9178-0b0c9b186859)

**Comment by heyitsbench** [comment]
Videos are more trustworthy than a Wowhead synopsis.

**Comment by Carriola-wotlk** [comment]
> Videos are more trustworthy than a Wowhead synopsis.

ok, so I confirm behavior reported by amed80. I'll open a PR to fix it

**Comment by Carriola-wotlk** [comment]
PR here: https://github.com/azerothcore/azerothcore-wotlk/pull/19653

**Comment by Carriola-wotlk** [comment]
link AC: https://github.com/azerothcore/azerothcore-wotlk/issues/19665

**Comment by heyitsbench** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/01c8344cc8df536255e2d501acb59ca6437f35e4
