### ISSUE TITLE
Nether vortex not lootable or delivered in mail when inventory full

### ISSUE THREAD

**Issue by trose-pbb** [chromiecraft/chromiecraft#7260]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

After Killing Lady Vashj, inventory was filled by the quest item. Loot roll won on Nether vortex. cleared full bags but still could not pickup. postmaster never delivered either.

### Expected Blizzlike Behaviour

expected to be able to pick up from boss loot, or delivered in mail. This feature did work for arcane dust in the same raid, but not the Nether vortex.

### Source

Instance ID1127

### Steps to reproduce the problem

1. verify the logs from raid loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Windows 10
![WoWScrnShot_080424_213138](https://github.com/user-attachments/assets/847af8f5-415d-4d17-8360-b4df59d53c22)

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
Hi @trose-pbb thanks for your report. 
I just tested against https://github.com/azerothcore/azerothcore-wotlk/commit/fc735e37a2166bbb39b272abd6950a5ae70ae761

If your bags are full and you won the roll > items stay on the boss until you free up your bags.
Another staff-member also confirmed this here https://github.com/chromiecraft/chromiecraft/issues/3556#issuecomment-1140026888.

The other members who lost the roll won't see your item, so you are safe to pick it up for a certain amount of time.
