### ISSUE TITLE
[Black Temple] Gathios the Shatterer shouldn't use the same seal twice in a row + Judgement timer

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7261]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Gathios the Shatterer](https://wowgaming.altervista.org/aowow/?npc=22949) randomly select his seal all the time which can lead to him using the same seal twice in a row.

### Expected Blizzlike Behaviour

[Gathios the Shatterer](https://wowgaming.altervista.org/aowow/?npc=22949)'s first seal is random but after he should rotate between his seals and not use the same seal twice in a row
From the videos below , it seems that Seals have 16-18s CD before using another one with rare occasions it gets delayed and takes up to 22s and the first seal happen instantly as soon Gathios enter combat.
For [Judgement](https://wowgaming.altervista.org/aowow/?spell=41467) , first seems to happen between 14-18s and the rest follow the same timer as seals 16-18s CD.

### Source

1/ [Pre Wotlk Classic](https://youtu.be/TRPy6G0UhcA?t=7471) 

Start 2:04:31

[Judgement](https://wowgaming.altervista.org/aowow/?spell=41467): 2:04:46 (15) , 2:05:02 (16) , 2:05:18 (16) , 2:05:34 (16) , 2:05:51 (16) , 2:06:07 (16) , 2:06:23 (16) , 2:06:39 (16) , 2:06:55 (16) , 2:07:11 (16)

Seals=

[SoC:](https://wowgaming.altervista.org/aowow/?spell=41469): 2:04:31 (0) , 2:05:05 (16) , 2:05:39 (18) , 2:06:12 (17) , 2:06:44 (16) , 2:07:16 (16)

[SoB](https://wowgaming.altervista.org/aowow/?spell=41459): 2:04:49 (18) , 2:05:21 (16) , 2:05:55 (16) , 2:06:28 (16) , 2:07:00 (16)

2/ [PTR TBC Classic](https://youtu.be/5CgZFHonpGU) 

Start 0:03

[Judgement](https://wowgaming.altervista.org/aowow/?spell=41467): 0:21 (18) , 0:38 (17) , 0:54 (16) , 1:10 (16) , 1:26 (16) , 1:42 (16) , 2:02 (20) , 2:20 (18) , 2:36 (16) , 2:52 (16) , 3:08 (16) , 3:26 (18) , 3:44 (18) , 4:00 (16) , 4:16 (16) , 4:34 (18) , 4:52 (18) , 5:10 (18) , ! , 5:42 (32!) , 5:58 (16) , 6:18 (20) , 6:34 (16) , 6:50 (16)

Seals=

[SoC:](https://wowgaming.altervista.org/aowow/?spell=41469): 0:04 (1) , 0:36 (16) , 1:08 (16) , 1:42 (17) , 2:20 (18) , 2:52 (16) , 3:26 (18) , 4:00 (16) , 4:34 (18) , 5:08 (16) , 5:41 (33!) , 6:18 (21) , 6:50 (16)

[SoB](https://wowgaming.altervista.org/aowow/?spell=41459): 0:20 (16) , 0:52 (16) , 1:25 (17) , 2:02 (20) , 2:36 (16) , 3:08 (16) , 3:44 (18) , 4:16 (16) , 4:52 (18) , ! , 5:57 (16) , 6:34 (16)

3/ [TBC Classic](https://youtu.be/a2Qd7tPYra4) 

Start 0:31

[Judgement](https://wowgaming.altervista.org/aowow/?spell=41467): 0:45 (14) , 1:02 (17) , 1:18 (16) , 1:34 (16) , 1:52 (18) , 2:08 (16) , 2:24 (16) , 2:40 (16) , 2:57 (17) , 3:13 (16) , 3:31 (18) , 3:47 (16) , 4:03 (16) , 4:19 (16) , 4:35 (16) , 4:51 (16) , 5:08 (17) , 5:29 (21) , 5:45 (16)

Seals=

[SoC:](https://wowgaming.altervista.org/aowow/?spell=41469): 0:31 (0) , 1:11 (18) , 1:44 (17) , 2:19 (19) , 2:52 (17) , 3:24 (16) , 3:56 (16) , 4:30 (16) , 5:06 (16) , 5:43 (16)

[SoB](https://wowgaming.altervista.org/aowow/?spell=41459): 0:53 (22) , 1:27 (16) , 2:00 (16) , 2:35 (16) , 3:08 (16) , 3:40 (16) , 4:14 (18) , 4:50 (20) , 5:27 (21)

4/ [TBC Classic](https://youtu.be/yquXE1dZj8I)

Start 0:15?

[Judgement](https://wowgaming.altervista.org/aowow/?spell=41467): 0:29 (14) , 0:45 (16) , 1:01 (16) , 1:17 (16) , 1:34 (17) , 1:51 (17) , 2:08 (17) , 2:24 (16) , 2:40 (16) , 2:56 (16) , 3:12 (16) , 3:28 (16) , 3:45 (17) , 4:01 (16)

Seals=

[SoB](https://wowgaming.altervista.org/aowow/?spell=41459): 0:15? (0) , 0:51 (17) , 1:25 (16) , 1:58 (16) , 2:33 (17) , 3:07 (16) , 3:40 (16) , 4:17 (18)

[SoC:](https://wowgaming.altervista.org/aowow/?spell=41469) 0:34 (19) , 1:09 (18)  , 1:42 (17) , 2:16 (18) , 2:51 (18) , 3:24 (17) , 3:59 (19)

5/ [Pre Wotlk Classic](https://youtu.be/aMgw7LSdGOI) 

Start 0:17

[Judgement](https://wowgaming.altervista.org/aowow/?spell=41467): 0:33 (16) , 0:49 (16) , 1:05 (16) , 1:21 (16) , 1:37 (16)

Seals=

[SoC:](https://wowgaming.altervista.org/aowow/?spell=41469): 0:17 (0) , 1:00 (24) , 1:33 (17)

[SoB](https://wowgaming.altervista.org/aowow/?spell=41459): 0:36 (19) , 1:16 (16) , 1:49 (16) 

6/ [Pre Wotlk Classic](https://youtu.be/xecG6X_huB4?t=8766) 

Start 2:26:06

[Judgement](https://wowgaming.altervista.org/aowow/?spell=41467): 2:26:22 (16) , 2:26:38 (16) , 2:26:57 (19) , 2:27:18 (21) , 2:27:38 (20)

Seals=

[SoB](https://wowgaming.altervista.org/aowow/?spell=41459): 2:26:06 (0) , 2:26:38 (16) , 2:27:18 (21)

[SoC:](https://wowgaming.altervista.org/aowow/?spell=41469) 2:26:22 (16) , 2:26:57 (19) , 2:27:38 (20)

### Steps to reproduce the problem

1. .tele bt
2. fight Illidari council
3. watch the seals on Gathios the Shatterer

### Extra Notes

With 2nd and 6th videos , it seems that Judgement probably check if there is a seal active before casting , if no then it will wait for one to be active before casting which why they starting having similar timer.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Judgement timer component of this issue still needs correcting.
