### ISSUE TITLE
The damage of some magic attacks is way to high

### ISSUE THREAD

**Issue by krutoj87** [chromiecraft/chromiecraft#7263]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

Some magic attacks from quest mobs do way to high damage. 
Some examples I noticed while questing:
- Fireball by Wyrmcult Acolyte in Blade's Edge Mountains does over 3k damage.
- Fire Breath by Eclipsion Dragonhawk in Shadowmoon Valley does 3k damage per tick. For most player's questing in the zone it's half their health and the first tick is instant and can't be avoided.
- Energy Flux by Ethereum Archon and Warp-Raider Nesaad in Netherstorm does about 2-3k damage per tick.

All those magic attacks are absolutely deadly for players with leveling gear, who have about 6k health when they quest in the zone. Of course the health might vary depending on class and gear, but I've had about 6-7k on all my chars with leveling gear at level 70.

There also have been other mobs with magical attacks, which seemed to have too high damage to me. Those are just the examples I still remember from the top of my head.

### Expected Blizzlike Behaviour

I can't tell how much damage those attacks are supposed to do, but I would asume Fire Breath and Energy Flux should do about 3k when they fully tick to the end and not per tick. And Fireball should probably rather be at 1-2k. But those are just guesses. I don't think those attacks should take away half a players health and much less so per tick.

### Source

I don't know if it's of use to you, but I link the wowhead pages of the mobs.

Wyrmcult Acolyte:
https://www.wowhead.com/wotlk/npc=21383/wyrmcult-acolyte#abilities

Eclipsion Dragonhawk:
https://www.wowhead.com/wotlk/npc=20502/eclipsion-dragonhawk#abilities;mode:n10

Ethereum Archon:
https://www.wowhead.com/wotlk/npc=20458/ethereum-archon#abilities

Warp-Raider Nesaad
https://www.wowhead.com/wotlk/npc=19641/warp-raider-nesaad#abilities

### Steps to reproduce the problem

1. Initiate the fight with those mobs
2. Wait for them to do their spells

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Same sort of issue as https://github.com/chromiecraft/chromiecraft/issues/6391, I'd wager these mobs are all melee'ing for more than they should which is causing their scaling spells to deal more damage.
