### ISSUE TITLE
[Paladin, Prot] T6 2p bonus does nothing

### ISSUE THREAD

**Issue by TotallyNotMyAccount** [chromiecraft/chromiecraft#7266]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Protection T6 2piece set bonus does nothing. 

### Expected Blizzlike Behaviour

Spiritual Attunement should provide an additional 10% of effective healing taken as mana.

### Source

Set bonus tooltip.

### Steps to reproduce the problem

1. Make a paladin on the ptr
2. Spec at least 1 point into Spiritual Attunement
3. Equip 2 pieces prot T6
4. Damage yourself so you can take effective healing
5. Get healed by another player
6. Compare actual mana gained to what it's supposed to be.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Tier 6 bonus 2 pieces works perfectly.

Set description is misleading. 

![Desktop Screenshot 2024 08 09 - 16 18 51 38](https://github.com/user-attachments/assets/6aeb6219-3718-47e5-840f-1b7b7f12c0f6)



In shorts, It is the 10% of the 10%, so 1% (11%). 

This is a 2007 comment on wowhead TBC:

![1232131313123213](https://github.com/user-attachments/assets/878723f1-7ff4-409e-9310-acc08d728ff5)

This is my screen on ptr:

![Desktop Screenshot 2024 08 09 - 16 15 35 71](https://github.com/user-attachments/assets/ac870356-b8d0-417e-95b2-8cf490d1e056)

**Comment by FrancescoBorzi** [comment]
@TotallyNotMyAccount closing as it seems invalid. If you think this was a mistake, feel free to leave a comment here.

@Rorschach91 thanks for taking care of this.
