### ISSUE TITLE
Autoattackrange bugged ?! (IMPORTANT)

### ISSUE THREAD

**Issue by Dexra** [chromiecraft/chromiecraft#727]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I just saw this bug on my Warrior yet. So what happens is that melee autoattackrange gets bugged alot of times. In PvE i sometimes cant attack NPC that are just infront of my face and it keeps saying "It's to far away". Also in warrior vs warrior scenario the warrior that GETS charged weirdly loses his first autoattack. like it just doesnt go off while ur swing timer resets. this is very very bad no its getting even worse: If a mage roots me via nova for example i keep spamming my thrown weapon and this is what happens:
Sometimes i hit the mage with my thrown weapon but he gets the damage from my 2H weapon and even the 2h swing sound is hearable !!! i have never experienced smth like that ever but here

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It's obviously.

##### STEPS TO REPRODUCE THE PROBLEM:

1. duel Warrior vs Warrior and check if the warrior that got charged gets his first autoattack out after the charge stun ends (which should be immediatly)
2. Warrior vs Mage spam thrown weapon and see if ur 2h weapon hits at range (I use a macro where i switch to thrown weapon and then cast thrown because i normaly run the 7hit bow and maybe thats whats messing it up ? idk)
3. 
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I've been trying to replicate this, especially issue 2, mage vs warrior and the 2H weapon hitting at range. What's I've found so far is that if the mage runs in and casts nova, the warrior will often get an auto-attack off on them, but it won't always play the strike sound (or it's lost in the Frost Nova sound). The next attack the warrior makes, which in this case is the throw, can sometimes then use the same 2H weapon sound. However, it is still only doing thrown weapon damage. In cases where the warrior didn't get an auto-attack off on the mage, the 2H sound was never played.

Here's 3 instances, slightly zoomed in on the combat log, showing that although the 2H hit noise is being played, the damage is still only that of a thrown weapon:
https://user-images.githubusercontent.com/81782124/120096412-83fca980-c16a-11eb-8578-dbe81c358b64.mp4

If you can see something I'm not doing right to replicate this, or even better, if you have combat log screenshots showing a 2H strike at range (tricky to get in a fight, I know), please let us know. 

I'll try to look at your other issue as well, but that's trickier for one person to test and document.

**Comment by Dexra** [comment]
thanks for testing !  yeah i think its not easy to replicate it since it happened to me like twice the whole time i play this server but it happened tho so smth is weird there. Have u tried to use bow first and macro the thrown weapon ? thats how i do it maybe its even cause if the macro idk, what about Issue 1 ? :)

**Comment by Azcobu** [comment]
Happy to try the macro - if you paste it in here so I'm not guessing what's in it, I'll give it a try.

As for issue #1, you can always speed things up with a video or other documentation of the problem in action.

**Comment by Azcobu** [comment]
I downloaded an attack timer to try to track this from https://www.curseforge.com/wow/addons/attack-bar-timer. That is what the two bars under my character are tracking. Then I charged a warrior into another warrior repeatedly, and watched for missed auto-attacks after both stuns and resisted stuns. So far, the various attacks all look to be performed at the right time, and I'm not seeing evidence of incorrectly missed auto-attacks. 

https://user-images.githubusercontent.com/81782124/120199275-35323b00-c262-11eb-9c6e-3c22ba302eb1.mp4

I'll flag this for a second look in case I'm missing something here.

**Comment by Azcobu** [comment]
Closing this, as neither of the errors discussed are actionable. The first problem (charged warrior loses autoattack) couldn't be replicated, and the second issue (thrown weapons doing 2H damage) seems to be a client-side animation/sound glitch - annoying, but the combat log shows that no extra damage is being done. However, if you do come up with evidence in future, preferably video given the nature of the issues, feel free to let us know.
