### ISSUE TITLE
[Warrior][Animation] Night elf warrior Charge does not apply Leg Animations for the first attack.

### ISSUE THREAD

**Issue by Kasmeen-Dev** [chromiecraft/chromiecraft#7277]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

When using the "Charge" ability on a Female Night Elf Warrior (Untested on others), the character model will not play the attack animation for the lower half of the body. 

### Expected Blizzlike Behaviour

Directly after using the Charge ability, the full animation should play, not just the upper half. 

### Source

https://github.com/user-attachments/assets/65c89407-3491-488a-8d9e-9d4bc016c5c8

https://github.com/user-attachments/assets/4f1b7204-c5d4-4df2-b642-22c2232e5915

https://github.com/user-attachments/assets/961041ba-4cab-47fd-8263-4bcbb914f728

### Steps to reproduce the problem

1. Create a Female Night Elf Warrior
2. Learn the "Charge" ability
3. Target an enemy and use the "Charge" ability

### Extra Notes

Possibly affecting all warriors, more testing will be needed if possible.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
This is most likely a client issue, needs more investigation

**Comment by Rorschach91** [comment]
Ok, I tried with two different clients.

1) Simple wow 3.3.5a this bug doesn't appear.
2) WoW 3.3.5a HD (with Dragonflight graphic) this bug appear.

I think Nyeriah was right, It is a client problem. 
In any case I will let open this report for a week. If others want to say their opinion are welcome.
