### ISSUE TITLE
[Loottable] Ruins of Farahlon - no loot at all

### ISSUE THREAD

**Issue by veredis1** [chromiecraft/chromiecraft#7282]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

If u kill mobs in the Ruins of Farahlon, Eye of Culuthas (https://www.wowhead.com/npc=20394/eye-of-culuthas) and Hound of Culuthas (https://www.wowhead.com/tbc/npc=20141/hound-of-culuthas) they dont drop anything. 

### Expected Blizzlike Behaviour

They should drop loot as the loottable in the links suggests.

### Source

(https://www.wowhead.com/npc=20394/eye-of-culuthas)
(https://www.wowhead.com/tbc/npc=20141/hound-of-culuthas)

### Steps to reproduce the problem

1. Go to the Ruins of Farahlons
2. kill the Hounds and Eye-creatures
3. see there is no loot

### Extra Notes

The elite mob there does have a loottable like it seems.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
There is some drops but they have very low drop rate , the highest is 5% to drop a grey item. (screenshot from live server)
![Wow_18%27%26=16-08-2024](https://github.com/user-attachments/assets/7553f878-484f-43be-aa7f-521b5dc3c77f)

Also reading the wowhead comments , those two seems to barely drop anything
![image](https://github.com/user-attachments/assets/ea7f012c-22e3-4d7d-a4d4-bb477881a152)
![image](https://github.com/user-attachments/assets/538b1c34-deef-4c8d-855d-0c4b2c6f065c)
![image](https://github.com/user-attachments/assets/80afb5d7-e472-49d7-994b-4350f410a15b)

**Comment by Rorschach91** [comment]
I checked on offy retail. 
In retail they drop something (junks and a green piece one time).
Unfortunely I cannot check this on Cataclysm classic (My pg is still level 30).
I need a second opinion. In any case thank you amed80 for screenshots.

**Comment by heyitsbench** [comment]
> Unfortunely I cannot check this on Cataclysm classic

I would recommend making a test realm account on your Battle.net account page, the PTRs when they're open oftentimes have template characters available that are high level that you can use to test various issues, Cataclysm included.

**Comment by Rorschach91** [comment]
> > Unfortunely I cannot check this on Cataclysm classic
> 
> I would recommend making a test realm account on your Battle.net account page, the PTRs when they're open oftentimes have template characters available that are high level that you can use to test various issues, Cataclysm included.
> 
> EDIT: These test realm accounts also last past your subscription date, so you should always have access to them.

Ok I tried these mobs on cata ptr, and I can confirm the issue.

Hound of Culuthas and Eye of Culuthas should drop junks every time and, sometimes, a green piece.

Regarding the junks:

[Hound of Culuthas](https://www.wowhead.com/wotlk/npc=20141/hound-of-culuthas) drop [Razor Sharp Fang](https://www.wowhead.com/wotlk/item=25418/razor-sharp-fang) (Almost every time) and [Gnarled Claw](https://www.wowhead.com/wotlk/item=25421/gnarled-claw) (sometimes).
[Eye of Culuthas](https://www.wowhead.com/wotlk/npc=20394/eye-of-culuthas) drop [Lifeless Tendril](https://www.wowhead.com/wotlk/item=29799/lifeless-tendril) (Almost every time) and [Evil Eye](https://www.wowhead.com/wotlk/item=29800/evil-eye) (sometimes).

Naturally, if they drop one junk, they don't drop the other.

Thank you for your report veredis1 and thank you for the help heyitsbench.
