### ISSUE TITLE
Removed alchemy specialization quest

### ISSUE THREAD

**Issue by Yamba78** [chromiecraft/chromiecraft#7298]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

After leveled to 68 and got Alchemy 360+ i took the quest at Thrallmar Alchemy Trainer.
The 3 quests were there, took Transmutation but removed the quest after 5minutes as i wanted Elixer instead. (Didnt completed Transmutation quest, so unlearn wasnt the case)

Once the quest was gone the Alchemy trainer at Thrallmar / Shatt City nor anywere else wasnt giving any quests, leaving me no option to get an Alchemy specialization.

### Expected Blizzlike Behaviour

No idea how it should work, but common sense would say you could retake a deleted quest.

### Source

none

### Steps to reproduce the problem

Thrallmar Alchemy trainer

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/de1e42bd83fe149b9d24239df05e4d5ae7f72d38

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
:x: Tested on [PTR](https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d) and [local AC server ](https://github.com/azerothcore/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d) but cannot reproduce it. 

Repro steps:
.level 68
.setskill 171 325 350
.go c id 16588
.take quests, wait, abandon and take the others.

@Yamba78 I think it would be best to talk to a GM if you still have no specialization taken.
