### ISSUE TITLE
Shadowfang Keep voice continues outside of dungeon.

### ISSUE THREAD

**Issue by Bullbutter** [chromiecraft/chromiecraft#730]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

While tanking Shadowfang Keep the voice of Arugal came on "You will die" This repeated through the whole dungeon during every pull. I shut down the client and rebooted and the voice continued outside of the dungeon during all my pulls. I went to discord and was told to delete the Cache fold which did not help.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

here is a clip outside of dungeon.
https://www.youtube.com/watch?v=zr3a0L3ko9s

##### STEPS TO REPRODUCE THE PROBLEM:

I wish I knew other then tank Shadowfang and get audio to come on.
1. 
2. 
3. 
4.

##### EXTRA NOTES:

please help

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. I'm sorry to say, I wasn't able to reproduce this. Is it still doing it after the server restart? Is it account wide of just on that character?

On a side note that is creepy.

**Comment by Bullbutter** [comment]
Issue was account wide. Re-downloading client resolved the issue. I have kept the original client though just incase I have an idea for a video.
