### ISSUE TITLE
[Black Temple] Promenade Sentinel is always running even out of combat

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7308]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[Promenade Sentinel](https://wowgaming.altervista.org/aowow/?npc=23394) is always in running mode (or walking too fast) even out of combat

https://github.com/user-attachments/assets/cd8e0067-a0df-47d9-a552-b9241c169273

### Expected Blizzlike Behaviour

[Promenade Sentinel](https://wowgaming.altervista.org/aowow/?npc=23394) should be walking and only start running when he enter combat

### Source

[TBC Classic](https://youtu.be/-sD3ikeZjZg?t=5764) at 1:36:04 you can see the speed of [Promenade Sentinel](https://wowgaming.altervista.org/aowow/?npc=23394) as it took it ~40s to do a full circle compared to the video above from AC which it made a full circle in less than 18s
[TBC Classic](https://youtu.be/y-Sh_ef5za4?t=3387) at 56:27 another video shows the speed of [Promenade Sentinel](https://wowgaming.altervista.org/aowow/?npc=23394)

### Steps to reproduce the problem

1. .tele bt
2. check the 3 walking/running [Promenade Sentinel](https://wowgaming.altervista.org/aowow/?npc=23394) after killing [Mother Shahraz](https://wowgaming.altervista.org/aowow/?npc=22947)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Should be running


https://github.com/user-attachments/assets/6812383d-118c-47bb-a3e7-457456dc5341

**Comment by amed80** [comment]
from that video, the speed is still very clear , it's different that what we have in CC/AC
