### ISSUE TITLE
Npcs arent moving

### ISSUE THREAD

**Issue by Kirishiki** [chromiecraft/chromiecraft#7314]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Ive been wondering this for many days but i think some npc´s walking route paths been broken, specificly in orgrimmar, most of the npcs who patrol trough the city just stand still.

### Expected Blizzlike Behaviour

the npc´s should walk around to make the city look more alive.

### Source

seen in game

### Steps to reproduce the problem

1. go to orgrimmar
2. see npc who u know should be patrolling
3. notice hes not moving
4. stand next to him to see if he starts moving soon BUT HE AINT!
5. get depressed.

### Extra Notes

![image](https://github.com/user-attachments/assets/bf517cee-ff26-491c-a7ef-f10387e43836)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Confirmed. This problem is only present on CC live (on PTR, npcs' pathfinding works well).
Maybe this issue could be fixed with a simple server restart.
I ask a second opinion before linking this issue on AC.

![Desktop Screenshot 2024 08 28 - 09 10 40 51](https://github.com/user-attachments/assets/2843155f-9c73-41c7-b133-b594bd5bee96)

**Comment by cachocarne** [comment]
This started happening just recently with many mobs. It feels they did something that affected a great amount of npcs. I had it just now with some zhevras in the barrens, for example. Many NPC's in Ironforge are suddenly frozen in place instead of following their traditional path/route

#7290

**Comment by heyitsbench** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/8f127f9e2135a70cdb5573d052f50304d1b3875c

**Comment by Rorschach91** [comment]
> This started happening just recently with many mobs. It feels they did something that affected a great amount of npcs. I had it just now with some zhevras in the barrens, for example. Many NPC's in Ironforge are suddenly frozen in place instead of following their traditional path/route
> 
> #7290

I suspected that it was the same problem. So I can consider this issue as known. 

Thank you guys, and thank you too @Kirishiki.

**Comment by vexima** [comment]
this is a completely different issue, not related to pathfinding. friendly NPCs in towns stop patrolling after the first player interaction. so they wander around normally after a server restart, but once stopped by player interaction they never resume their routine and stay still until the next server restart.

if this issue is not re-opened I'll create a new one with concise description, so it's not mixed up with unrelated issues.
