### ISSUE TITLE
[Outland] A'dal's Song of Battle still active outside of supposed zone

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7319]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

[A'dal's Song of Battle](https://wowgaming.altervista.org/aowow/?spell=39953) a zone buff gained after turn-in [Verdant Sphere](https://wowgaming.altervista.org/aowow/?item=32405) in Shattrath , still active outside of supposed zone (The Botanica, The Mechanar, and The Arcatraz)

### Expected Blizzlike Behaviour

[A'dal's Song of Battle](https://wowgaming.altervista.org/aowow/?spell=39953) should only be active while inside The Botanica , The Mechanar and The Arcatraz

### Source

[A'dal's Song of Battle](https://wowgaming.altervista.org/aowow/?spell=39953)
![image](https://github.com/user-attachments/assets/adc4a352-73f8-4ee1-903f-5fc39de3d170)
[Wowhead Comment](https://www.wowhead.com/wotlk/spell=39953/adals-song-of-battle#comments:id=247584)
![image](https://github.com/user-attachments/assets/3b5c859f-2206-4dc6-8178-ace6dc29578b)
[Wowpedia](https://wowpedia.fandom.com/wiki/A%27dal%27s_Song_of_Battle)
![image](https://github.com/user-attachments/assets/37897778-46ae-4bee-937e-affe78b86836)

### Steps to reproduce the problem

1. .learn 27216 (Corruption)
2. use Corruption on any training dummy in one of the capital cities
3. .tele shattrath
4. .learn 39953 and use it
5. use Corruption again on any training dummy in one of the capital cities
6. _**it deals more damage**_

### Extra Notes

There is a lot more comments in wowhead that says the buff doesn't require you to be inside Shattrath and should be giving (aura?) to everyone in Outland including Isle of Quel'Danas also inside Raids and Dungeons in Outland.
The buff will get removed but still hiding if you exit Shattrath , The Botanica, The Mechanar or The Arcatraz and you will gain it back if you enter them again (the timer still ticks down depends on your playing time and not real-time)
This might need someone to check it on retail/classic?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sogladev** [comment]
linking acore magtheridon issue as it's 1 of 3 outland zone buffs with the same issue https://github.com/azerothcore/azerothcore-wotlk/issues/1685#issuecomment-2155592145

**Comment by heyitsbench** [comment]
Resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/3565e4a9eba5475f7377f694838000c8837b9785.
