### ISSUE TITLE
Tooltips formatting issue containing newline/line breaks

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#7323]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

For some time now, there is a visual bug with tooltips for spells that contain line breaks. If there are lines seperated by a line break (newline), the lines are fused together and there is no space between them. This happens even on a fresh install.

![newline1](https://github.com/user-attachments/assets/7628e87d-20b0-4fb3-88a7-83c900bedbec)

### Expected Blizzlike Behaviour

In-game formatting for newline should look like this (taken from any WotLK database, ignore the mathematic formula). This was previous behaviour.

![newline2](https://github.com/user-attachments/assets/844a56f6-a94a-485b-bcd9-be36a0e50021)

### Source

Obvious formatting issue

### Steps to reproduce the problem

Clear cache folder before testing, then start the game.
.learn spell 20375
Look at the tooltip of the spell.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Spell descriptions are entirely contained clientside. There is nothing CC can do to fix this issue.

**Comment by godnesso** [comment]
I remember I logged in with a second fresh installed client to confirm a long time ago. Doing this once more, it now works as expected. It seems I remembered wrong, thanks for confirming.
