### ISSUE TITLE
The Skettis Offensive

### ISSUE THREAD

**Issue by Kosiak** [chromiecraft/chromiecraft#7326]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

After all the bird waves killed quest is not completing.

### Expected Blizzlike Behaviour

After killing  Avatar of Terokk last wave bird quest should complete.

### Source

https://wowwiki-archive.fandom.com/wiki/Quest:The_Skettis_Offensive

### Steps to reproduce the problem

1. Accept Quest the [The Skettis Offensive](https://www.wowhead.com/quest=10879/the-skettis-offensive)
2. KIll all bird waves
3. Observe that quest not completing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
I cannot reproduce this on PTR. 
Maybe someone from Staff can test this on live.

**Comment by amed80** [comment]
I tried this quest on my alt on CC live , i attempted to finish it solo , in group and in a raid , the quest completed on all the attempts.
@Kosiak can you give more steps to reproduce your problem?

**Comment by Kosiak** [comment]
I clean cache and try again later tonight.

**Comment by KuristZero** [comment]
Just wanted to add I was in a similar situation to Kosiak with this quest today:
Level 69 Hunter, unable to complete quest.
When I put my pet into passive mode and defeated the Avatar of Terokk solo, I was able to complete the quest.
Does seem like pets are playing a role in preventing the award of the complete state :)
