### ISSUE TITLE
"Shield Wall" not available from Darnassus-trainer as Draenei

### ISSUE THREAD

**Issue by cy-one** [chromiecraft/chromiecraft#7327]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

20-29

### Current Behaviour

My (at the time) lv31 Draenei warrior "Alatya" couldn't get the lv28 warrior spell "Shield Wall" from the warrior trainer in Darnassus.
When I later checked the warrior trainer in the Exodar, I could get the spell there.
I don't know if "being a draenei" played any role here.

### Expected Blizzlike Behaviour

Shield wall should be available from all warrior trainers as a 28+ warrior.
https://www.wowhead.com/classic/spell=871/shield-wall#taught-by-npc
Arias'ta Bladesinger is listed as teaching that spell. But I couldn't get it from her.

### Source

I'm not sure what to put here, to be perfectly honest.
https://www.wowhead.com/wotlk/spell=871/shield-wall#taught-by-npc This is the same link as before, but in the "wotlk"-version of Wowhead. Same difference :D

### Steps to reproduce the problem

Due to lacking a second warrior on the same level, I wasn't able to reproduce it :(
However, I had been to the trainer in Darnassus 2 times between 28 and 31 and Shield Wall was never available.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
I verified all Darnasus Warrior Trainers as a Draenei lvl 28 warrior and Shield Wall is available.
