### ISSUE TITLE
XS-001 Constructor Bot sfx too loud

### ISSUE THREAD

**Issue by Undersalt** [chromiecraft/chromiecraft#733]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Item shop XS-001 Constructor Bot (non-combat pet) sound effects are too loud. Not sure if this is a bug as the item was never available on live servers but its really annoyingly loud.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No idea.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Purchase XS-001 Constructor Bot
2. Annoy everyone within 100 yards
3. 
4.

##### EXTRA NOTES:

I would have liked to swap it for something else, but unfortunately that is not possible. I would not recommend purchasing until the sound level has been adjusted as it literally causes a headache after 3-5 minutes of use.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
You weren't kidding about the noise, I summoned it and it sounds like a malfunctioning dump truck. Unfortunately I think this is a client-side issue, which is where the sound file for this pet is stored. This means that short of deleting it altogether, it's not something AzerothCore can actually fix.

Instead, there is a process to replace sound files that you could probably use to make this pet more bearable, but I don't know much about it so can't help much. The base sound seems to be this:

https://www.wowhead.com/sound=23559/pet-constructorbot-loop

There's a Wrath-era guide to replacing sound files here: http://www.orcisharmyknife.com/2010/06/how-to-use-custom-sounds-in-wow.html

Hopefully that should give you what you need to silence the bot.
