### ISSUE TITLE
Naralex's Nightmare spell in Wailing Caverns breaks hunter's pet description

### ISSUE THREAD

**Issue by initialactivity** [chromiecraft/chromiecraft#7331]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

1-19

### Current Behaviour

Boss of Wailing Caverns [Mutanus the Devourer](https://wowgaming.altervista.org/aowow/?npc=3654) casts [Naralex's Nightmare](https://wowgaming.altervista.org/aowow/?spell=7967). If he casts it on the hunter, after the effect ends, hunter pet keeps his name under pet's name in the brackets, as shown in the screenshots. In the brackets it says <Mutanus the Devourer's Pet> . 
![WoWScrnShot_083124_222817](https://github.com/user-attachments/assets/390aff8a-d70a-4f89-81f6-0c6652ce636d)

### Expected Blizzlike Behaviour

Hunter pet should stay to <Ironscout's pet>.

### Source

https://wowgaming.altervista.org/aowow/?npc=3654
https://wowgaming.altervista.org/aowow/?spell=7967

### Steps to reproduce the problem

1. Go to Wailing Caverns dungeon
2. Go to and fight Mutanus the Devourer as Hunter
3. Boss should cast Naralex's Nightmare at the hunter
4. Wait for the effect to end

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by M4th3m4tic4l** [comment]
Something I notice is that it is temporary, although at least in my case I did not get it on my pet directly, however I see that the bug exists and it is more evident in CC

![image](https://github.com/user-attachments/assets/462eb849-5436-4abc-bc49-ddd55b5c0f12)
![image](https://github.com/user-attachments/assets/ed6ac10b-4a35-46a9-b311-fcb286e33ff0)

**Comment by M4th3m4tic4l** [comment]
sorry, missclick xd

**Comment by initialactivity** [comment]
Yes I forgot to mention that it was temporary. I think that after re-summoning my pet, or a re-log, everything was back to normal.
Thank you for looking into this issue.

**Comment by Rorschach91** [comment]
> Something I notice is that it is temporary, although at least in my case I did not get it on my pet directly, however I see that the bug exists and it is more evident in CC

It is more evident on CC, but It is an AC bug anyway, right?

**Comment by Cythisiax** [comment]
Unable to replicate this with solo hunter and pet. Mutanus will not cast Nightmare if hunter has aggro, only when pet has aggro; Casting Nightmare on PC. However, does not rename pet's ownership from PC to Mutanus.

https://streamable.com/bko4ke

**Comment by Cythisiax** [comment]
Played with this for a little bit longer, still wasn't able to reproduce. Please re-open this if you experience it going forward.
