### ISSUE TITLE
Los issue - some mobs in Hillsbrad Foothills are unkillable after server restart

### ISSUE THREAD

**Issue by Rottenness14** [chromiecraft/chromiecraft#7342]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

30-39

### Current Behaviour

Hello,

First of all, I am using the ChromieCraft WoW 3.3.5a client from the site.

After the server restart done today (6-Sep) at about 09:40 server time, all mobs in Hillsbrad Foothills region are almost unkillable.
I took 3 videos for both caster and melee attacking mobs and they seem to lose the LoS without any reason and go to evade state.

Video 1: https://www.youtube.com/watch?v=0A1UoN2mqSY
Video 2: https://www.youtube.com/watch?v=4YLNEcliyYw
Video 3: https://www.youtube.com/watch?v=yFmibZedAeo

For all melee mobs you need to be exactly on top of them, without moving a millimeter so that they won't evade.

Regards,
Rottenness

### Expected Blizzlike Behaviour

N/A

### Source

N/A

### Steps to reproduce the problem

N/A - all mobs in Hillsbrad Foothills area.

### Extra Notes

Worked fine (with the regular LoS and path finding issues that CC has) before today's server restart.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Edition: Windows 11 Pro
Version: 23H2
OS build: 22631.4112
Experience: Windows Feature Experience Pack 1000.22700.1034.0

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
This is the same old pathfind bug that only regard CC Live. I'm starting to think that should be some type of conflict.

Thank you for your report, and thank you for the help in game. If you find other problem feel free to report them.

**Comment by Rorschach91** [comment]
I retested the issue and seems that these mobs works well. I close this report as solved.
