### ISSUE TITLE
[Black Temple] Mother Shahraz Fatal Attraction bugs

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#7348]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Fatal attraction teleport now works, however sometimes people get teleported into a corner, making separating fast enough impossible. I know the tooltip of the mechanic says the teleport location is random but in all my years doing TBC raiding we never had an issue with people jammed into a corner and us dying/wiping because of that. There must be whitelist of acceptable teleport locations somewhere.

Fatal attraction does its 3k dmg multiple times in the same tick - does over 50k dmg in a single second. 

Fatal attraction chains appear again and start doing dmg if players get close to each other after initially breaking them.

### Expected Blizzlike Behaviour

The teleport location is in the middle of an open space in the room.

The shadow dmg is done once every second.

Once broken the chains should not reappear if players get closer that 25 yards to each other.

### Source

https://www.wowhead.com/npc=22947/mother-shahraz

14:23 in https://www.youtube.com/watch?v=cvMTW85NQJU

### Steps to reproduce the problem

Engage Mother Shahraz with more than 4 people.
Wait for Fatal Attraction to be cast on 3 of them.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dccec8764408a58eb01ba85827f8686b196d370c

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Capoguerra** [comment]
Fatal Attraction ticks two/three times for second. It should tick one time for second.
Fatal Attraction's Ticks should multiply their damage ONLY for each linked player.
When player breaks Fatal Attraction chain, Fatal Attraction debuff should vanish.

Watch this video at: 3:49:50 (how should work it)
https://www.youtube.com/watch?v=FcmL8BBMYQk&t=14284s

Watch this (how work on CC)
https://youtu.be/3Aub2xgNsdA

**Comment by QuantaCosta** [comment]
https://wowpedia.fandom.com/wiki/Patch_2.2.0
-> Section: Black Temple.
Fatal Attraction damage supposed to ramp up over 4 seconds rather than dealing it's full 3000 from second 1.

**Comment by Nyeriah** [comment]
> https://wowpedia.fandom.com/wiki/Patch_2.2.0 -> Section: Black Temple. Fatal Attraction damage supposed to ramp up over 4 seconds rather than dealing it's full 3000 from second 1.

Already how it works

**Comment by QuantaCosta** [comment]
so it does 50k damage in 1s by overlapping 3x 750 dmg sources?

**Comment by Nyeriah** [comment]
> so it does 50k damage in 1s by overlapping 3x 750 dmg sources?

I don't how where the huge amount of damage comes from, but it does ramp up from 1000, to 2000, then finally 3000

**Comment by Nyeriah** [comment]
3 players - 3 ticks per second - 9k damage per second

Should it only tick once if them all are stacked together ?

**Comment by Rorschach91** [comment]
It Always ticks One time per second.

**Comment by Nyeriah** [comment]
Then there’s nothing wrong about it in this case

**Comment by Rorschach91** [comment]
Video From CC: [Youtube](https://youtu.be/3Aub2xgNsdA)
Clip from TBC Classic: [Youtube](https://www.youtube.com/watch?v=N2QEGmSqgZE)
It seems that the ticks are right. I've the impression that the problem is the damage. I need to do more research on PTR.

**Comment by Nyeriah** [comment]
I advise adding this spell to the list of exceptions in the tuning module to prevent the mechanic from being too punishing.

**Comment by Carriola-wotlk** [comment]
> I advise adding this spell to the list of exceptions in the tuning module to prevent the mechanic from being too punishing.

do you mean to override the spell behavior on the spell_dbc, right?

**Comment by Nyeriah** [comment]
> > I advise adding this spell to the list of exceptions in the tuning module to prevent the mechanic from being too punishing.
> 
> do you mean to override the spell behavior on the spell_dbc, right?

No, we use a module to handle the tuning of abilities in raids due to progression

**Comment by Rorschach91** [comment]
I updated the report on AC. Take a look: https://github.com/azerothcore/azerothcore-wotlk/issues/19940#issue-2520007860
