### ISSUE TITLE
[Black Temple] Illidary Council boss HP not linked

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#7349]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Their hp is not linked. They take dmg independently and most importantly when they reach 1 hp they dont die.

### Expected Blizzlike Behaviour

Bosses should have their health values linked and should die together when it reaches 0.

### Source

https://www.wowhead.com/tbc/guide/illidari-council-black-temple-bt-strategy-burning-crusade-classic
16:00 in https://www.youtube.com/watch?v=cvMTW85NQJU

### Steps to reproduce the problem

Engage the bosses
Start doing dmg to them
Try to kill one and them and notice their hp is different and the main target does not die

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dccec8764408a58eb01ba85827f8686b196d370c

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Bosses are linked. There seems to be some kind of delay with the stabilisation of the HP, but I'm not sure.

[Video](https://youtu.be/-j2DwJvXohA)

**Comment by heyitsbench** [comment]
The delay is intentional and Blizzlike. Watching any TBCC kill video will show the health percentages jumping up/down every 3.2s.

**Comment by Rorschach91** [comment]
Perfect. So I can close this issue. 

Thank you for the report, and thank you @heyitsbench.
