### ISSUE TITLE
Commander Felstrom infinite loot

### ISSUE THREAD

**Issue by NWKDenmark** [chromiecraft/chromiecraft#735]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Commander Felstrom, a rare mob found in Duskwood (https://wowgaming.altervista.org/aowow/?npc=771), drops his loottable upon succesfully casting his rebirth skill. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If succesfully rebirthing, Commander Felstrom's corpse should be unlootable. Only an actual kill should yield loot.

##### SOURCE:

https://wowgaming.altervista.org/aowow/?spell=3488

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Commander Felstrom.
2.  Bring him to low HP: 1-120 Hp.
3.  Let him succesfully cast Felstrom Resurrection.
4.  Loot corpse, repeat steps 2 - 4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/bc101780e815de73bd0b9eeef122be2ba4033246
