### ISSUE TITLE
[Black Temple] Illidan Flames of Azinoth spawn enraged

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#7351]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[The Phase 2](https://www.wowhead.com/npc=112831/flame-of-azzinoth) adds spawn already enraged, doing 1 shot dmg to tanks and moving lightning fast.

### Expected Blizzlike Behaviour

1 Flame of Azinoth should spawn on each of his twinblades. They should only [enrage](https://www.wowhead.com/spell=39869/uncaged-wrath?dd=33) and get the extra 500% dmg and 200% speed if taken outside the required range (I couldnt find a reliable source of how many yards we are talking about sadly).

### Source

https://www.wowhead.com/npc=22917/illidan-stormrage

### Steps to reproduce the problem

Pull boss
Get to phase 2

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fafd351e44b4556b9ceda4bfaa72c6e5f22c3f78

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Tecnically, they go in enrage just a few seconds after they spawn. 
In any case I can confirm the bug. Thank you for the report.

**Comment by Rorschach91** [comment]
Seems that Flames of Azzinoth works well. I close this report, thank you anyway.

**Comment by heyitsbench** [comment]
I can confirm it does not work well. Might be inconsistent to reproduce, but it definitely still happens.

**Comment by Rorschach91** [comment]
Lol. I tried that phase 4 times. Alright, I will do other tests tomorrow.

**Comment by Rorschach91** [comment]
I re-tried the fight another five times, but Flames of Azzinoth still continue to spawn without enrage.
At this point if someone can do a video that shown the issue could be a good thing.
I will re-try again this evening in case.

**Comment by heyitsbench** [comment]
Video here: https://youtu.be/5KAWBjSvIl0&t=11090 timestamped to Azzinoth spawn point.

**Comment by Rorschach91** [comment]
Ok, I watched the video.
It seems that one of the mobs charges a player, going far from its spawn point and causing the enrage. 
This is normal, in fact players should take position between the warglaives to prevent mobs enrage.
If you try to mantain mobs in their original spawn position, they don't go in enrage.

At this point there are two questions:
1) Is it normal that mobs charge a player instantly when they spawn?
2) Is it right the distance for the enrage?

![evidence](https://github.com/user-attachments/assets/12db621d-f3cf-4034-9f41-8a8b8c16a35e)

For this report I seriously need our help, guys.

**Comment by heyitsbench** [comment]
> Is it normal that mobs charge a player instantly when they spawn?

No, in fact the Flames of Azzinoth are another example of summoned creatures that [should have an AI delay](https://github.com/azerothcore/azerothcore-wotlk/issues/19062).

> Is it right the distance for the enrage?

According to [this post](https://eu.forums.blizzard.com/en/wow/t/illidan-flame-azzinoth-charge-mechanic/335503/5), the range should be 40y away from the flame itself, not the glaive. Not sure how AC currently does it.

> Is it normal that mobs go in enrage soo fast when they go too far from their warglaive?

That I don't know.

**Comment by heyitsbench** [comment]
I misread your question and thought it was asking about the charge. Checking with sniffs, the enrage range appears to be ~30y away from the blade creature.

**Comment by Carriola-wotlk** [comment]
based on the code, it seems to match what is described in the screenshots posted by @Rorschach91 from Icy Veins. If the Flame of Azinoth are more than 25 yards away from the Tear of Azzinoth, they receive the UNCAGED_WRATH buff
![immagine](https://github.com/user-attachments/assets/f7f5da2d-6854-4f22-9abc-3fe92284095d)

@heyitsbench could you confirm if the 25.0f value represents the range?

**Comment by heyitsbench** [comment]
> could you confirm if the 25.0f value represents the range?

As far as I understand it, yes.

**Comment by Carriola-wotlk** [comment]
here my test: https://youtu.be/60-n0UDbPYY
it seems that their behavior is correct

**Comment by Nyeriah** [comment]
So we need to increase the distance check and add AI delay? @heyitsbench

**Comment by Rorschach91** [comment]
> So we need to increase the distance check and add AI delay? @heyitsbench

Regarding the distance I don't know. Icy Veins says that the distance is 25 yard. 
I can confirm the AI Delay.

**Comment by heyitsbench** [comment]
AI delay needs to be added, enrage distance needs extending, and something *is* wrong with charge, but it needs more investigation to figure out exactly when it's cast on official servers (in a Classic sniff, it was cast on a player in melee range behind the elemental).

**Comment by Rorschach91** [comment]
It could be a good idea going to cata classic ptr, but every time that I try to enter in a instance client freeze itself and I'm not able to enter.

**Comment by Rorschach91** [comment]
I made this collage of videos regarding the fight with the Flames of Azzinoth. 
Take a look: [Youtube ](https://youtu.be/tWw8eF-8zgE)

**Comment by Rorschach91** [comment]
OK, guys. I have finished my research and I think I can do my final report:

1. Blades of Azzinoth are 40 yards apart from each other and this is right. 

![cattura](https://github.com/user-attachments/assets/8a36c510-6ee0-4cf5-a2a9-be3cafa49b03)

2. If a Flame of Azzinoth goes too far from its glaive (beyond 40 yards), it goes in enrage (It seems that this feature works well on AC).

3. Watching some videos from TBC classic (an [example](https://www.youtube.com/watch?v=tWw8eF-8zgE)), you can see that if a player move more than 40 yard from a Glaive of Azzinoth, the Flame of Azzinoth linked to that glaive charge them (and naturally it goes in enrage).
On AC this mechanic is clearly bugged.
Evidence: [Youtube](https://youtu.be/wrFCSDGLvsw) (consider that in this video Avelle is exactly upon the Glaive of Azzinoth).

4. Looking at guides and some videos I can say that [Flame Blast](https://www.wowhead.com/tbc/spell=40631/flame-blast) and [Blaze](https://www.wowhead.com/tbc/spell=40611/blaze) abilities are missing from Flames of Azzinoth.

Source: Always [this](https://youtu.be/tWw8eF-8zgE).
![evidence 2](https://github.com/user-attachments/assets/14a49d78-e683-4488-9228-db556b77815f)

I have nothing else to add @heyitsbench @Nyeriah.
