### ISSUE TITLE
Eversong Woods Tor'Watha Ground Clipping

### ISSUE THREAD

**Issue by slothfulstomp** [chromiecraft/chromiecraft#7357]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

In the zone Eversong Woods at the unused raid entrance of Tor'Watha there is a bug where you can fall through the ground while walking on the right path. You can see the floor bug out and change color as you approach it.
![tor'watha_01](https://github.com/user-attachments/assets/3645b568-d192-42a4-8a39-cf4918d80769)
![tor'watha_02_floor_color_change](https://github.com/user-attachments/assets/63d34aae-41c1-4110-9f9e-5ba5f9a1f983)
![tor'watha_03_fell_through_floor](https://github.com/user-attachments/assets/eb6ce14d-6a33-447f-87c2-dd02aba1ec8a)

### Expected Blizzlike Behaviour

You shouldn't fall through the floor.

### Source

3.3.5

### Steps to reproduce the problem

1. Go to Tor'Watha
2. Go along the right path.
3. Fall through the ground.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fafd351e44b4556b9ceda4bfaa72c6e5f22c3f78

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I can confirm the issue.
Basically the entire platform after the two bridges is bugged.

Video: [Youtube](https://youtu.be/yRZzXQxetBg)
Video: [Youtube](https://youtu.be/gueZRDZgClg)

![Desktop Screenshot 2024 09 12 - 00 51 06 26](https://github.com/user-attachments/assets/104643c8-a900-4c1d-b0de-b6a43331ecbf)


It is also probably bugged the two areas after the doors.
If I may be honest, I don't think it can be considered a client issue. 
In any case, I appreciate another opinion.

**Comment by cachocarne** [comment]
I had some clipping issues on different spots but all related to HD remodels applied on 3.3.5a. If you are using them. Try disabling the HD patches and checking again, it might be a client-only problem.

**Comment by Rorschach91** [comment]
> I had some clipping issues on different spots but all related to HD remodels applied on 3.3.5a. If you are using them. Try disabling the HD patches and checking again, it might be a client-only problem.

Confirmed. It is an HD client issue. I close this report, thank you cachocarne.
