### ISSUE TITLE
Stormpike faction reputation from killing Stormpike soldier NPCs in AV

### ISSUE THREAD

**Issue by leetrobotz** [chromiecraft/chromiecraft#7360]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

50-59

### Current Behaviour

Noticed in Alterac Valley today as I kill the Stormpike (Alliance) guards ("Seasoned Defender") at Stonehearth graveyard, I get 5 reputation with Stormpike for each guard as I kill and capture. My reputation tab in character screen shows 210/hated with Alliance Forces: Stormpike Guard

### Expected Blizzlike Behaviour

Killing these guards should yield Frostwolf reputation; similar to killing tower guards ("Stormpike Defender") 

### Source

https://www.wowhead.com/wotlk/npc=13326/seasoned-defender

### Steps to reproduce the problem

1. Create a Horde character at least lvl 51
2. Queue for the Alterac Valley battleground
3. Race north from the Frostwolf cave to the Stonehearth graveyard
4. Kill one of the 4 guards there

### Extra Notes

https://www.wowhead.com/wotlk/faction=729/frostwolf-clan

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fafd351e44b4556b9ceda4bfaa72c6e5f22c3f78

### Operating system

Debian 6.1.94

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-playerbots] (https://github.com/liyunfan1223/mod-playerbots) 

### Customizations

None

### Server

Azerothcore/Chromiecraft

**Comment by Nyeriah** [comment]
Report playerbots issues in the playerbots repo.
