### ISSUE TITLE
Missing NPC - Grikkin Copperspring

### ISSUE THREAD

**Issue by Rottenness14** [chromiecraft/chromiecraft#7361]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

NPC [Grikkin Copperspring](https://wowgaming.altervista.org/aowow/?npc=26383) (added in patch 2.0.3.) does not exist.

### Expected Blizzlike Behaviour

To have the NPC spawned at 65.8, 59.9

Proof 1 (NPC added on Patch 2.0.3 (2007-01-09): https://wowpedia.fandom.com/wiki/Grikkin_Copperspring
Location: 65.8, 59.9

NOT CORRECT (on the server): NPC is completely missing
![WoWScrnShot_091624_154239](https://github.com/user-attachments/assets/9634bca8-6b3c-43c3-828b-2621a11a820b)

CORRECT BEHAVIOR: 
DB1: https://wotlk.evowow.com/?npc=26383
DB2: https://www.wowhead.com/wotlk/npc=25176/grikkin-copperspring#map
DB3: https://wowclassicdb.com/tbc/npc/25176

### Source

provided above

### Steps to reproduce the problem

provided above

### Extra Notes

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fafd351e44b4556b9ceda4bfaa72c6e5f22c3f78

### Operating system

Edition: Windows 11 Pro
Version: 23H2
OS build: 22631.4112
Experience: Windows Feature Experience Pack 1000.22700.1034.0

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
It probably has been removed intentionally. Judging what it sells, it will probably added with the future arena season (season 3 or 4).

But I could be wrong, I ask another opinion.

**Comment by HasieEST** [comment]
Generally speaking, during TBC, that vendor had inventory change based on seasons. Same way how Dalaran sewer vendor has current gear and season prior gear in inventory. Change back then was implemented for connivence of players, who were queueing in Nagrand.
