### ISSUE TITLE
[Black Temple] - Mythic Items Missing on NPC Vendor From Bosses

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#7371]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

After reviewing all items on the NPC, then cross-referencing them on the AOwowDB site, I found that they are missing quite a few items to select from. 

Missing items : 
High Warlord Naj'entus 
- [Ring of Captured Storms](https://wowgaming.altervista.org/aowow/?item=32247)

Shade of Akama
- [Ring of Deceitful Intent](https://wowgaming.altervista.org/aowow/?item=32266)
- [Focused Mana Bindings](https://wowgaming.altervista.org/aowow/?item=32270)
- [Wristbands of Divine Influence](https://wowgaming.altervista.org/aowow/?item=32513)

Essence of Anger
- [Pendant of Titans](https://wowgaming.altervista.org/aowow/?item=32362)
- [Elunite Empowered Bracers](https://wowgaming.altervista.org/aowow/?item=32351)
- [Naturewarden's Treads](https://wowgaming.altervista.org/aowow/?item=32352)
- [Boneweave Girdle](https://wowgaming.altervista.org/aowow/?item=32346)

High Nethermancer Zerevor (council)
- [Cloak of the Illidari Council](https://wowgaming.altervista.org/aowow/?item=32331)
- [Belt of Divine Guidance](https://wowgaming.altervista.org/aowow/?item=32519)
- [Forest Prowler's Helm](https://wowgaming.altervista.org/aowow/?item=32376)
- [Helm of the Illidari Shatterer](https://wowgaming.altervista.org/aowow/?item=32373)

These should be all the missing items, and none to my knowledge are "post nerf/patch" added items. 

### Expected Blizzlike Behaviour

All these items are normal drops from the bosses, and thus should be included in the mythic point vendor NPC. 

### Source

Links included with all items. 
Manual checking NPC dialog for each item section. 
Each item link can also be checked on wowhead redirect link. 
Can also check [Wowpedia BT page](https://wowpedia.fandom.com/wiki/Black_Temple), and expand bosses, and check their loot as well. 

### Steps to reproduce the problem

1. Enter PTR
2. Go to shat, and talk with mythic point NPC
3. Check items to sections
4. They are missing

### Extra Notes

Afaik only tier tokens and legendary items are excluded as bought items. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fafd351e44b4556b9ceda4bfaa72c6e5f22c3f78

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I can only confirm that these items are missing from npc, but I don't know if this is intentional.

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/mod-zone-difficulty/commit/189cdcb0c8ffe54903a9aa04679eb13a6a9b377c#diff-f69e418d5b797dfa9330fcd591cd1894c0410f6c04ae578661b1759db7e70bf7R22
