### ISSUE TITLE
 [[63] Avruu's Orb (9418)] Quest is bugged

### ISSUE THREAD

**Issue by Monet01** [chromiecraft/chromiecraft#7379]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

1) kill Avruu
2) loot item: Avruu's Orb
3) right click item and start quest: Avruu's Orb
4) go to location and summon
5) Aeranas turns hostile 
6) batter Aeranas
7) Aeranas turns friendly when their HP reaches to around 30%
8) after few seconds, Aeranas turns hostile again, batter Aeranas
9) Aeranas turns friendly when their HP reaches to around 30%
10) after few seconds, Aeranas turns hostile again , batter Aeranas
11) Aeranas turns friendly when their HP reaches to around 30%

repeated this 50 times.

### Expected Blizzlike Behaviour

1) kill Avruu
2) loot item: Avruu's Orb
3) right click item and start quest: Avruu's Orb
4) go to location and summon
5) Aeranas turns hostile 
6) batter Aeranas
7) Aeranas turns friendly when their HP reaches to around 30%
8) speaks with Aeranas and complete quest.

### Source

sources:
https://www.wowhead.com/wotlk/npc=17085/aeranas#comments
https://www.youtube.com/watch?v=Z_w63bPetQY

### Steps to reproduce the problem

1) kill Avruu
2) loot item: Avruu's Orb
3) right click item and start quest: Avruu's Orb
4) go to location and summon
5) Aeranas turns hostile 
6) batter Aeranas
7) Aeranas turns friendly when their HP reaches to around 30%
8) after few seconds, Aeranas turns hostile again, batter Aeranas
9) Aeranas turns friendly when their HP reaches to around 30%
10) after few seconds, Aeranas turns hostile again , batter Aeranas
11) Aeranas turns friendly when their HP reaches to around 30%

repeated this 50 times.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/da3109809463ff4223038d2fc9d48610d67c9238

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I tried to reproduce this bug on PTR and on my personal AC server, but nothing happens. 
Aeranas seems to work well. It could be a rare bug, but I'm not sure. 
I leave this report open for a few days, if someone want to comment.

**Comment by icelament** [comment]
are these two related?
https://github.com/azerothcore/azerothcore-wotlk/issues/20893

**Comment by icelament** [comment]
@Rorschach91
