### ISSUE TITLE
Shattrath flasks stack with normal flasks

### ISSUE THREAD

**Issue by Wosser** [chromiecraft/chromiecraft#7381]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

You can have a Shattrath flask and a normal one active at the same time.
Up until some time ago, Shattrath flasks disappeared when leaving a tier 5+ raid. This got fixed exactly the wrong way round so that their buff icon disappeared, but the effect stayed even when not inside a raid. I assume due to the buff icon missing the server doesn't register that you have a flask active and let's you use another one without overwriting the previous?

### Expected Blizzlike Behaviour

Shattrath flasks' buff icons shouldn't disappear, no matter where you go, just the effect. Effect should become active again when entering a tier 5+ raid. (don't have prove for that)
You shouldn't be able to have a shattrath and a normal flask active at the same time. (don't tell me I need to prove that)

### Source

.

### Steps to reproduce the problem

Go inside a tier 5 or higher raid dungeon, use a Shattrath Flask of Pure Death.
Leave the raid dungeon.
Use a normal Flask of Pure Death.
Your Shadow, Fire and Frost spell power should be 160 higher than your overall spell power now, +80 from both flasks.

### Extra Notes

Shattrath Pure Death: https://wowgaming.altervista.org/aowow/?item=35716
Normal Pure Death: https://wowgaming.altervista.org/aowow/?item=22866

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8a0604479af820c5b0cfdb3fdb02985d240d79d3

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
`AzerothCore rev. 8a0604479af8 2024-09-26 07:13:47 -0300 (master branch) (Win64, RelWithDebInfo, Static)`
Same rev: https://github.com/chromiecraft/azerothcore-wotlk/commit/8a0604479af820c5b0cfdb3fdb02985d240d79d3

Can confirm the above. 35716 | 22866

With 35716 (buff visually gone)
![image](https://github.com/user-attachments/assets/61e0a471-8bd4-4ace-ad06-c5a886dbe86b)

With 35716 (buff visually gone) + 22866
![image](https://github.com/user-attachments/assets/02bb681f-aed0-4e8d-b9bf-85e16e83471a)

**Comment by veredis1** [comment]
It probably works for any Flask and any combination of them I suppose, pls fix this before BT.

**Comment by heyitsbench** [comment]
Think I've figured out part of this issue. The Shattrath flasks all trigger another spell which does the actual effect. This is why the flask's effects are still active when the buff icon itself is not. When you consume a flask that interferes with a Shattrath flask, the main buff is removed, but the triggered spell is not, thus the effects stack up.
