### ISSUE TITLE
Another Year, Another Souvenir not appearing for characters

### ISSUE THREAD

**Issue by Grumond** [chromiecraft/chromiecraft#7386]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

there's suppose to be a quest for Brewfest called "Another Year, Another Souvenir", where you get a collectors stein you can fill up at the kegs during the event. however, the quest is no longer available for characters that haven't completed it yet. what's odd, is that it was available for the first week of the event, but now its gone.

and according to questie, its suppose to be there.

![WoWScrnShot_092924_092450](https://github.com/user-attachments/assets/e03e4b62-3d6e-4659-acd4-1d74de813729)
![WoWScrnShot_092924_091316](https://github.com/user-attachments/assets/b8322e7c-c200-4989-919b-98202f0e8486)
![WoWScrnShot_092924_091335](https://github.com/user-attachments/assets/859d115f-ba6d-4e83-8277-2ede689a1135)
![WoWScrnShot_092924_091341](https://github.com/user-attachments/assets/9b27e113-57dc-4dc1-99bb-1d130b78e25b)

### Expected Blizzlike Behaviour

you should be able to pick up the quest, and turn the voucher in to the token redeemer at the Brewfest grounds, to get the stein and the FoS achievement.

### Source

https://www.wowhead.com/wotlk/quest=13932/another-year-another-souvenir

### Steps to reproduce the problem

1. speak to Pol Amberstill at the Brewfest Grounds outside Ironforge, or Driz Tumblequick outside Orgrimmar.
2. you're then suppose to take the Brewfest Stein Voucher to either Blix Fixwidget or Belbi Quikswitch to get the stein and achievement.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8a0604479af820c5b0cfdb3fdb02985d240d79d3

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
Tested in normal AC.

It seems quest 13932 (alliance) nor 13931 (horde) (Another year another souvenir) has no Creature Queststarter, i pressume is why he doesnt give you the request, since you're supposed to get this quest after completing 11318 (alliance) and 11409 (horde) (now this ram racing almost)

**Comment by TheSCREWEDSoftware** [comment]
Can confirm previous statement i've added each NPC as their respective Quest Starter and they give the quest and the respective loot
