### ISSUE TITLE
[Mechanar] Panthaleon the Calculator crashes the server at 20%

### ISSUE THREAD

**Issue by CptMarkka** [chromiecraft/chromiecraft#7389]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

When reaching 20% with Panthaleon the Calculator, he casts his enrage ability and consumes the spawned nether wraith adds. Consequently, this crashes the server.

### Expected Blizzlike Behaviour

The server should not crash.

### Source

A Mechanar RDF run ended crashing the server three times when hitting the 20% phase.

### Steps to reproduce the problem

1. Go to Mechanar.
2. Engage Panthaleon the Calculator.
3. DPS until 20%.
4. Observe crash.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8a0604479af820c5b0cfdb3fdb02985d240d79d3

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
I tried to replicate the issue on AC and on CC PTR, without results. If it is an issue that only regard CC live a GM should test it.

**Comment by CptMarkka** [comment]
Could it be possible that Seed of Corruption could be causing some strange interaction with the wraiths or the spell Panthaleon casts? We had two Warlocks in the party and someone suggested that it could be the common thread.

![image](https://github.com/user-attachments/assets/a2b37dc0-e9e0-458e-bad8-70a92d5560d5)

**Comment by Nyeriah** [comment]
Pathaleon casts a spell at 20% that kills all creatures

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/20124
