### ISSUE TITLE
Oozing Bag don't drop anything at all. 

### ISSUE THREAD

**Issue by XionDemise** [chromiecraft/chromiecraft#740]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Oozing Bags don't drop anything at all, I opened 3 and to no avail got nothing at all.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Depending on the loot pool i should at least get a 64.81% to at least get one thing from the entire oozing bag loot pool. So in retrospect i should at least get one of these items contained in these bags. but got none 3 times. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Open any Oozing Bag. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Related to [https://github.com/chromiecraft/chromiecraft/issues/647](https://github.com/chromiecraft/chromiecraft/issues/647)
I can confirm that these will occasionally be empty. I believe these both should contain some coin as well. 
[https://vanillawowdb.com/?item=20768#comments](https://vanillawowdb.com/?item=20768#comments) from 2.4.3
A simple google search shows tons of videos of people opening oozing bags from more recent expansions all of which contained some coin.
