### ISSUE TITLE
Rich thorium and small thorium veins

### ISSUE THREAD

**Issue by ledu91** [chromiecraft/chromiecraft#7402]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Rich thorium and small thorium veins missing in Winterspring (Darkwhisper George and Lake Kel'Theril), Western Plaguelands (The Weeping Cave and Hearthglen). There are 0 of them. Tested on Public Test realm and on main realm.

### Expected Blizzlike Behaviour

There should be mining nodes.

### Source

I can't find any source, but 0 mining nodes seems bugged. 

### Steps to reproduce the problem

Just make it spawn regularly

### Extra Notes

/

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/529e9140323edeef916bd6a1b6c97e13aa38db08

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None
/

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
[Rich Thorium Veins}(https://wowgaming.altervista.org/aowow/?object=175404) and [Small Thorium Veins](https://wowgaming.altervista.org/aowow/?object=324) are placed along Lake Kel'theril and Heathglen, though the other two locations are sparsely populated, if at all.

**Comment by cachocarne** [comment]
Totally agreed. I sometimes found Thorium nodes around the lake. But the ones at Darkwhisper George have disappeared. Being s particularly "dangerous" zone, plagued with elites and high level mobs. It was always a good place to farm rich Thorium nodes. They are not spawning there anymore, since weeks.

**Comment by Rorschach91** [comment]
I have checked this issue on my AC server and everything seems to be ok. 
I keep this report open for a week just to allow to the author (or to another players) to share their opinions.

**Comment by ledu91** [comment]
I farmed for hours in WesternPlaguelands and thoriums never spawned in the weeping cave or in front of the cave(one spawn is infront of the cave).

**Comment by Rorschach91** [comment]
Have you tried to Tanaris, Un'goro crater or Silithus?
