### ISSUE TITLE
Challenge rewards visual bug

### ISSUE THREAD

**Issue by DusanJovanovic1991** [chromiecraft/chromiecraft#7420]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Challenge rewards(for paladin) icons are bugged (mount and companions) showing as ? in inventory. Putting it in personal bank shows it like empty cell like there is no item in there.
![bug](https://github.com/user-attachments/assets/a5bf9aa4-8463-4444-ad38-fb3ec27dbea8)

### Expected Blizzlike Behaviour

Items should have icons and players should be able to put them in personal bank.

### Source

Can't find source

### Steps to reproduce the problem

Items should have icons and we players should be able to put it personal bank.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0fa770d56788196bda608343dde4ceb452848f89

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by DusanJovanovic1991** [comment]
Forgot to mention also costumes are included in this report

**Comment by Nyeriah** [comment]
You need to download a MPQ in order to see the icons and use the pets/mounts. It is in the instructions: https://www.chromiecraft.com/en/challenge-modes/

**Comment by DusanJovanovic1991** [comment]
Hi, i already have the patch since i completed the challenge. Items that are bugged,
Costumes: Kruul , Crowd pummeler, Flamewalker
Mounts: Reins of the bengal tiger
Companions: Holy Chime, Imperial Eagle hatchling, Clefthoof Calf.
These items are shown as ? in inventory.
Only Reins of the Primal Leopard and Reins of the Tawny Sabercat have icon

**Comment by TheSCREWEDSoftware** [comment]
> Hi, i already have the patch since i completed the challenge. Items that are bugged, Costumes: Kruul , Crowd pummeler, Flamewalker Mounts: Reins of the bengal tiger Companions: Holy Chime, Imperial Eagle hatchling, Clefthoof Calf. These items are shown as ? in inventory. Only Reins of the Primal Leopard and Reins of the Tawny Sabercat have icon

Clear your cache and see if they appear

**Comment by TheSCREWEDSoftware** [comment]
@DusanJovanovic1991 can you provide me your paladin's name?

**Comment by TheSCREWEDSoftware** [comment]
Closing due due to no response. Be free to open a new issue and mentioned this one
