### ISSUE TITLE
Monstrous Kaliri Eggs do not spawn

### ISSUE THREAD

**Issue by Mervin31** [chromiecraft/chromiecraft#7434]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

When accepting (or without accpeting) the daily quest Fires Over Skettis, Monstrous Kaliri Eggs do not spawn at Skettis at all.

### Expected Blizzlike Behaviour

There should be objects on top of the tree huts called Monstrous Kaliri Eggs to bomb, to complete the quest.
https://www.youtube.com/watch?v=I64nZuj_t1A

### Source

Wrath classic

### Steps to reproduce the problem

1. Fly to Skettis
2. Observe that there are no monstrous kaliri eggs at all

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/572be7d69f8b9a0100d95ecaa045247e574c38a4

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sudlud** [comment]
azerothcore/azerothcore-wotlk#20041

**Comment by sudlud** [comment]
can't reproduce on a clean AC installation at azerothcore/azerothcore-wotlk@88db984e52b2c0daf533c6a1ef769a3d50d7347c

```
.tele skettis
.quest add 11008
observe eggs on each tower
throw bombs at eggs
get quest credit
observe eggs respawning after some time
```

![WoWScrnShot_110624_205715](https://github.com/user-attachments/assets/dff8941a-3897-46a7-b9c9-8c719d093509)

![WoWScrnShot_110624_205723](https://github.com/user-attachments/assets/b4b654c8-113b-490a-9e22-4b7e2aaa722b)

@grimgravy I can't reproduce the issue

**Comment by grimgravy** [comment]
@sudlud must be tested in chromiecraft

**Comment by Nyeriah** [comment]
A server setting caused this (preloadgrids). Should work at the next restart
