### ISSUE TITLE
[NPC] Grimtotem Raider (7725) casting Net while Stunned

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#7440]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

40-49

### Current Behaviour

[Grimtotem Raider](https://www.wowhead.com/wotlk/npc=7725/grimtotem-raider) is able to cast Net on player even when under the effects of [Freezing Trap](https://www.wowhead.com/wotlk/spell=43448/freezing-trap). Net immobilizes the player and roots it to a fixed spot unable to run away and keep distance from mob.

### Expected Blizzlike Behaviour

Mobs that are CC'd with a stun effect shouldn't be able to cast any spells or abilities for the whole duration of the CC.

### Source

https://www.wowhead.com/wotlk/npc=7725/grimtotem-raider
https://wowgaming.altervista.org/aowow/?npc=7725
https://www.wowhead.com/wotlk/npc=7725/grimtotem-raider#abilities

### Steps to reproduce the problem

Have a hunter with Freezing Trap
Go to Feralas
Set Trap and force mob to walk into it
Observe how mob can still cast Net on you while frozen

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/572be7d69f8b9a0100d95ecaa045247e574c38a4

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
This issue has been already reported months ago: https://github.com/chromiecraft/chromiecraft/issues/5554

Thank you for your report anyway.
