### ISSUE TITLE
Black Temple : Judgment of Light will heal Gurtogg Bloodboil

### ISSUE THREAD

**Issue by zhekaimao** [chromiecraft/chromiecraft#7444]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

When the paladin uses Judgment of Light on Gurtogg Bloodboil. After the boss uses the first Fel Rage. If the boss has the Judgment of Light dbuff paladin will heal him.

### Expected Blizzlike Behaviour

Judgment of Light shouldn't heal him

### Source

![WoWScrnShot_102424_081959](https://github.com/user-attachments/assets/150970f1-1f19-427a-8f57-e94304a5afd7)
For experimentation I used the .damage 2000000 instruction to test

![WoWScrnShot_102424_082222](https://github.com/user-attachments/assets/54795393-137c-4756-b826-2cb38863ec3d)
Soon after, the boss HP was healed. The addon showed that the source of healing the boss was Judgment of Light.

### Steps to reproduce the problem

1. Go there
2. Deal some damage to the boss and use Judgment of Light on him then observe

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/572be7d69f8b9a0100d95ecaa045247e574c38a4

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
This needs some sources, because from past experiences we checked in other places it should happen just like this, and there's nothing preventing jol healing (no healing immunity or anything like that)

**Comment by SirenxAA** [comment]
I think what zhekaimao is saying that when casting judgement of light (from a paladin in raid) on the boss, the judgement somehow causes the boss to heal himself during phase 2 (enrage) phase.
Picture 1 shows boss have 656.0W health and in picture 2 the boss have 805.9W health indicating the boss was healed

**Comment by zhekaimao** [comment]
> I think what zhekaimao is saying that when casting judgement of light (from a paladin in raid) on the boss, the judgement somehow causes the boss to heal himself during phase 2 (fel rage) phase. Picture 1 shows boss have 656.0W health and in picture 2 the boss have 805.9W health indicating the boss was healed (from the recount table in picture 2) by judgement of light from the paladin.

Thank you very much SirenxAA. This is what I want to express. Generally speaking, this Boss should not have any self healing skills.
https://www.wowhead.com/tbc/guide/gurtogg-bloodboil-black-temple-bt-strategy-burning-crusade-classic

**Comment by amed80** [comment]
For some reason , Gurtogg start applying [Acidic Wound](https://wowgaming.altervista.org/aowow/?spell=40481) on himself in phase 2 which lead to it triggering JoL and healing himself.
![Wow_12%03%40=31-10-2024](https://github.com/user-attachments/assets/4e817457-b1c0-421c-9e03-7312b1bccdce)
