### ISSUE TITLE
Crudely Wrapped Gift does not contain Weighted Jack-o'-Lantern

### ISSUE THREAD

**Issue by bjagaz** [chromiecraft/chromiecraft#7447]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Crudely Wrapped Gifts https://www.wowhead.com/wotlk/item=34077/crudely-wrapped-gift, do not contain Weighted Jack-o'-Lantern's.

### Expected Blizzlike Behaviour

They should contain the item with a around 96% chance.
https://www.wowhead.com/wotlk/item=34068/weighted-jack-o-lantern
https://www.wowhead.com/wotlk/item=34077/crudely-wrapped-gift#contains

### Source

https://www.wowhead.com/wotlk/item=34077/crudely-wrapped-gift
https://wowpedia.fandom.com/wiki/Crudely_Wrapped_Gift?so=search

### Steps to reproduce the problem

1. Save one of the villages from the headless horseman.
2. Accept the daily quest "Smash the Pumpkin", from the spawning pumpkin.
3. Deliver the quest and open the gift you get as a reward.
4. Open the bag and observe. (Wowhead states a 96% droprate)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/47c61b2576a5c86b405b6dce60b1daf4d69b93ca

### Operating system

Void Linux

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
According to the "original" database of EvoWoW (no WotLK Classic or any revamp) it does NOT have that loot table:

https://wotlk.evowow.com/?item=34077#contains

**Comment by heyitsbench** [comment]
> According to the "original" database of EvoWoW

EVOWOW is a private server and not a valid source. [Allakhazam circa Oct. 2010](https://web.archive.org/web/20101023003352/http://wow.allakhazam.com/db/item.html?witem=34077) *does* have the Jack-o'-Lantern listed under the Crudely Wrapped Gift.

**Comment by cachocarne** [comment]
It DOES appear in the DB of Tauri, even stating a 100% drop of several units.

https://wotlk-shoot.tauri.hu/?item=34077

However, being a private server as well it's probably not a valid source either
