### ISSUE TITLE
[Zul'Aman] Hex Lord Malacrass

### ISSUE THREAD

**Issue by Peti321** [chromiecraft/chromiecraft#7461]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

He is in the wrong position
![ss](https://github.com/user-attachments/assets/02b22d37-9a96-4734-987e-81d7f47c0fa1)

### Expected Blizzlike Behaviour

He should stay in between his adds.

### Source

any picture or video

### Steps to reproduce the problem

1.Kill 4bosses to open Hex Lord gate
2.Check him 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4b59c867e141cf210c654b05fdddb3c12f7e7ea2

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
```
Object Guid: Full: 0x0 Creature/0 Map: 568 Entry: 24363 // Malacrass
Position: X: 116.2857 Y: 1277.4407 Z: -15.268659
Orientation: 4.590215682983398437

Object Guid: Full: 0x1 Creature/0 Map: 568 Entry: 24241 // Thurg
Position: X: 128.48448 Y: 923.04285 Z: 33.97255
Orientation: 1.588249564170837402

Object Guid: Full: 0x2 Creature/0 Map: 568 Entry: 24243 // Lord Raadan
Position: X: 122.60526 Y: 923.24536 Z: 33.97256
Orientation: 1.570796370506286621

Object Guid: Full: 0x3 Creature/0 Map: 568 Entry: 24245 // Fenstalker
Position: X: 111.69282 Y: 923.15314 Z: 33.972576
Orientation: 1.570796370506286621

Object Guid: Full: 0x4 Creature/0 Map: 568 Entry: 24246 // Darkheart
Position: X: 105.40299 Y: 923.3421 Z: 33.972588
Orientation: 1.553343057632446289
```

**Comment by heyitsbench** [comment]
Also pretty confident none of these creatures are supposed to be spawned (including Malacrass) until the gate is opened, might be mistaken on that though.

**Comment by Ottawia** [comment]
Also that bug results in: you can kill 2 adds separently and then 2 more without pulling boss (however thay will respawn during fight)

**Comment by Peti321** [comment]
The orientation of Hex clearly shows its bugged.
I'm not sure about they spawning before gate is opened.

I can confirm Ottawia's bug. The adds can be killed but they respawn when boss is pulled.

**Comment by Rorschach91** [comment]
Confirmed. Thank you for your report.
