### ISSUE TITLE
[Sunwell Plateau] Sunblade Vindicator does not use Mortal Strike

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#7463]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Sunblade Vindicator does not use ability Mortal Strike.

### Expected Blizzlike Behaviour

They should Mortal Strike on tanks.

### Source

https://www.wowhead.com/wotlk/npc=25369/sunblade-vindicator#abilities;mode:n25

### Steps to reproduce the problem

1. Go into Sunwell Plateau
2. Find one of the first packs with Sunwell Vindicator in them
3. Let them hit you, and observe they never use mortal strike

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4b59c867e141cf210c654b05fdddb3c12f7e7ea2

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Sunblade Vindicator should use Cleave and Brutal Strike. If you are using WoWHead guide to search possible bugs I should advise you that WoWHead is not always reliable. In this particual case WoWHead has probably confused Mortal Strike with Brutal Strike.

Thank you for your report anyway.

**Comment by Apathyxia** [comment]
Online guides also show that they would do mortal strike: 
https://youtu.be/0nDOh1RhMTs?t=38
https://www.wowhead.com/tbc/guide/trash-mobs-sunwell-plateau-swp-strategy-burning-crusade-classic

**Comment by Rorschach91** [comment]
It is normal, because WoWHead guide use WoWHead database and youtube guide use WoWHead database :)
Anyway I'm sure about this because I just tried the mob on WoW Classic PTR.

**Comment by Apathyxia** [comment]
Hmm, I see. I'm still not sure what do we go by, as at one point in time using WoW classic stuff for bug reports wasn't valid, but had to find sources from times when, say, TBC was in retail.
Wowhead [comment](https://www.wowhead.com/npc=25369/sunblade-vindicator#comments:id=260805) also indicates a mortal strike (patch 2.4.0).

**Comment by heyitsbench** [comment]
Can see in [this video](https://youtu.be/NW-Uvs7acyU?si=5RUl_3F-jZcwmAUF&t=118) a Mortal Strike affect be applied to a druid named Bbaron tanking a Sunblade Vindicator.

**Comment by heyitsbench** [comment]
Confirmed with 3.4.2 50664 sniff, [25369](https://wowgaming.altervista.org/aowow/?npc=25369) does cast [39171](https://wowgaming.altervista.org/aowow/?spell=39171).

**Comment by heyitsbench** [comment]
Looks like the spell took on a different name/effect with Cataclysm, would explain why you're not seeing it on the Cata PTR, Rorschach.

**Comment by Rorschach91** [comment]
Do you mean that in Cata Mostal Strike has been changed with Brutal Strike?
In this case also AC has this change, because Vindicators use Brutal Strike.

**Comment by heyitsbench** [comment]
It does look like with Cataclysm they *did* replace their Mortal Strike with Brutal Strike, I don't see Brutal Strike being cast anywhere in the sniff, maybe that's what you meant.

**Comment by Rorschach91** [comment]
> It does look like with Cataclysm they _did_ replace their Mortal Strike with Brutal Strike, I don't see Brutal Strike being cast anywhere in the sniff, maybe that's what you meant.

Correct.

Look, this screenshot comes from Cata Classic PTR:

![Cata Classic ptr](https://github.com/user-attachments/assets/9cfe5b01-a981-43a9-8554-9d3a4c8b229b)

And this comes from my AC server:

![AC](https://github.com/user-attachments/assets/4f02a787-b099-4365-b7ac-9df49afc235a)

**Comment by Rorschach91** [comment]
Lol. Direct Fix without AC linking. I like it.

**Comment by heyitsbench** [comment]
Simple fix, no need for an intermediate issue. 😛
