### ISSUE TITLE
Nightsaber Stalker loot table, dropped a black pearl

### ISSUE THREAD

**Issue by Sunnypotato** [chromiecraft/chromiecraft#7474]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

[Black Pearl,7971](https://wowgaming.altervista.org/aowow/?item=7971#dropped-by:0+2+1), dropped from level 8 [Nightsaber Stalker, 2043](https://wowgaming.altervista.org/aowow/?npc=2043#drops:0-2+1-14)

### Expected Blizzlike Behaviour

Black pearl should not drop from any mobs according to wotlk wowhead, and for sure not from low level mobs

### Source

[wowhead for black pearl](https://www.wowhead.com/wotlk/item=7971/black-pearl)
[wowhead for nightsaber stalker](https://www.wowhead.com/wotlk/npc=2043/nightsaber-stalker#drops;0-3-1+17-21)

### Steps to reproduce the problem

Kill npc=2043 a bunch of times I guess

### Extra Notes

prob not needed but proof that it happened: https://youtu.be/7YKt_PyrcY8

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/07a6327c8c2d08d44710ec00931d0a8420621465

### Operating system

Windows 11

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Ok, this is very strange. 
AC database says that black pearl can be dropped by some mobs, but WoWHead says that is only contained in some sacks or it can be obtained by fishing.

I need a second opinion. In case this is easy to fix.

**Comment by Sunnypotato** [comment]
looking at wowhead from other expansions, (vanilla, tbc, cata) wotlk seems to be the odd one out - the black pearl page for the other expansions has the pearl drop from 3 different mobs

[tbc wowhead for black pearl](https://www.wowhead.com/tbc/item=7971/black-pearl)

**Comment by Exitare** [comment]
I checked the most recent TC db release. They seem to use the wowhead entries. 
No npcs drop the item. Only the bags.

What should we do about it?

**Comment by Rorschach91** [comment]
> I checked the most recent TC db release. They seem to use the wowhead entries. No npcs drop the item. Only the bags.
> 
> What should we do about it?

I needed a second opinion and I got it from you. In this case I proceed to remove the black pearl from all creature loot tables.
Thank you for your second opinion @Exitare.
