### ISSUE TITLE
[Quest] Fire over Skettis: too few eggs

### ISSUE THREAD

**Issue by Mervin31** [chromiecraft/chromiecraft#7483]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Quest currently is completable. 4 eggs spawn and they can be destroyed, as opposed to my  previous (now closed) report: https://github.com/chromiecraft/chromiecraft/issues/7434.
With only 4 eggs spawning the quest takes a very long time as well as makes the related achievement unobtainable.

Empty buildings, that should have eggs:
![image](https://github.com/user-attachments/assets/e94ce628-9f37-4f92-b05d-d557412a40a1)
![image](https://github.com/user-attachments/assets/b20563c8-af9e-4c2a-9dfb-df13ba742811)

and the 4 eggs that do spawn:
three
![image](https://github.com/user-attachments/assets/96e3d25b-00ca-4d5e-a993-30c60ce14ec3)
and +1
![image](https://github.com/user-attachments/assets/70fbf923-a199-4ffa-8761-ec3f1565dbff)

### Expected Blizzlike Behaviour

There should be eggs spawning on top of almost every building in Skettis, all over the place.
https://www.youtube.com/watch?v=w96f7RMGYS0&ab_channel=Bue

### Source

My observation with screenshots included and a video of the desired behaviour.

### Steps to reproduce the problem

.tele skettis
.quest add 11008
.observe eggs on 2 towers and the absence on the others
.throw bombs at eggs
.get quest credit
.observe only the 4 eggs respawning after some time

### Extra Notes

Previous report:
https://github.com/chromiecraft/chromiecraft/issues/7434

Bombs are now usable and 4 eggs do spawn now.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/88db984e52b2c0daf533c6a1ef769a3d50d7347c

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Those eggs spawned while I was investigating the issue last night. It will be properly working after the next restart.
