### ISSUE TITLE
<Essence of Souls> Putting Pets on aggressive causes them to attack in their immunity phase

### ISSUE THREAD

**Issue by Krateozshael** [chromiecraft/chromiecraft#7485]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

During the intermission phase of the 3 Mainphases you can stack underneath the "cage".
When you put your pets (of hunter, warlocks) on aggressive they attack the boss. This causes them not updating their tuned hp-pools, since they are treated as "infight".
This causes them spawning with about 33-50% hp.

### Expected Blizzlike Behaviour

This issue is most likely only due to the custom tuning of CC.
Therefore theoretically this shouldnt happen with untuned versions of bosses.

### Source

forgot to make a screenshot :(

### Steps to reproduce the problem

1. Be a Pet-Class
2. Engage ROS normally and bring it to the intermission phase
3. stack underneath the cage and kill the adds normally
4. boss should spawn at like 50%

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/88db984e52b2c0daf533c6a1ef769a3d50d7347c

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
This happens with every summoned boss/mob in the raid that have tuning applied to it , as this causes the mob to not fully apply the tuning health? and it shows up with base health (2.120k) and the rest tuned health missing
Can happen to Reliquary of Souls p2 and p3 and also to both Illidan's Flame of Azzinoth.

**Comment by Rorschach91** [comment]
I've tried to replicate the issue on my personal AC server, but pets don't attack essence of soul during its immunity phase.
At this point I can say that this is just a CC issue, probably related to the tuning module.
This issue shouldn't be triaged on AC repositary, but a staff review is needed.

Thank you for your report.

**Comment by Krateozshael** [comment]
In our run they werent attacking it either. More the "aggressive" stance cause them to be in fight probably, i also got to know that this works most likely on the Illidan fire elementals as well, tho i havent tested it yet

**Comment by sogladev** [comment]
I'm able to reproduce this locally with [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty) 
```
config
ModZoneDifficulty.Mythicmode.Enable = 1


shaman
.go xyz 497.772 114.97 94.852 564 1.5
summon a felhunter on aggressive 
.learn 691
.add 6265 10
macro to summon ghouls
.cast 42651
shaman totems: earth ele, searing totem 
```

cause is the fullhp check failing. Pets reduce hp <100 before the update can set the hp correctly https://github.com/sogladev/mod-zone-difficulty/blob/f1e555aabec6f416fdfbbb8e7bd88e7d29a9f5c0/src/mod_zone_difficulty_scripts.cpp#L1124

**Comment by Rorschach91** [comment]
So, it is a custom module issue, right?

**Comment by Rorschach91** [comment]
So it is a custom module issue. In any case it shouldn't be linked to AC.
