### ISSUE TITLE
[Website] - Transmog logging out

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [chromiecraft/chromiecraft#7486]
### Bug Title

Rewards Catalogue => transmog-dalaran-sword Log-out

### Current Behaviour

Out of all the catalogue entries, for tranmog this one is the only keep killing my session.

### Expected Behaviour

Wouldn't kill my session if it was active.

### Steps to Reproduce

- Go to https://www.chromiecraft.com/en/rewards-catalogue/product-category/transmogs/

- Choose any tranmog, works fine

- Choose dalaran swords, kills your session and asks you to login again.

### Browser

Chrome

### Device

Desktop

### Operating System

Windows 10 x64

### URL

https://www.chromiecraft.com/en/rewards-catalogue/product-category/transmogs/

**Comment by Yehonal** [comment]
I can't reproduce this
