### ISSUE TITLE
Ashtongue Mythic's Cyclone Totem CCs the whole Raid for the duration of cyclone

### ISSUE THREAD

**Issue by SmoothMoose7** [chromiecraft/chromiecraft#7489]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

https://wowgaming.altervista.org/aowow/?npc=22845 (BT Trash Mob) puts down https://wowgaming.altervista.org/aowow/?spell=39589 (Cyclone Totem) and instant Cyclones the whole raid including pets, making the raid unable to kill the totem. Which results in the whole raid being cycloned until the totems "dies" (i assume 30secs). 

### Expected Blizzlike Behaviour

The totem should only have a radius of 3 yards according to Aowow or Wowhead: https://wowgaming.altervista.org/aowow/?spell=39589 . 

![WoWScrnShot_110724_155414](https://github.com/user-attachments/assets/4a64a6a2-f847-46b5-a4ae-afd169bdec75)
![WoWScrnShot_110724_155412](https://github.com/user-attachments/assets/fba65ad1-7a18-45dd-8ed7-aa363c537a80)

You cant see too much on the screenshots but everyone was in the cyclone until the totem died, we couldnt iceblock/bubble or anything to kill it. Pets were cycloned aswell.

### Source

Aowow:

https://wowgaming.altervista.org/aowow/?spell=39589
https://wowgaming.altervista.org/aowow/?npc=22845

Wowhead (wotlk):

https://www.wowhead.com/wotlk/npc=22845/ashtongue-mystic#abilities;mode:n25
https://www.wowhead.com/wotlk/spell=39589/cyclone-totem#summons

### Steps to reproduce the problem

1) Teleport into Black Temple
2) Go to the Sanctuary of Shadows
3) Approach "Ashtongue Mystic" (https://wowgaming.altervista.org/aowow/?npc=22845)

### Extra Notes

Its my second bug report, hopefuly i do it correctly!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/88db984e52b2c0daf533c6a1ef769a3d50d7347c

### Operating system

Windows 10

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment]
That is the summoned spell for the totem as it's summoned 3y around Ashtongue Mystic and not related to what the totem do.

[Cyclone](https://wowgaming.altervista.org/aowow/?spell=39594) from totems should target up to 3? people in 40y range and not the whole raid.

Source:
[PTR TBC Classic1](https://youtu.be/t5SL62WLr_U?t=4248) at 1:10:48 you can see 3 people in the raid are being cycloned and as soon the visible totem get killed all of them get freed.
[PTR TBC Classic2](https://youtu.be/MH2BKL4G_BQ?t=2711) at 45:11 you can see 3 people cycloned , at 49:46 and 51:59 , 2 people are in cyclone.
[PTR TBC Classic 3](https://youtu.be/NRl78646E4M?t=2072) at 34:32 , 3 people in cyclone and at 40:10 only one person in cyclone.


I am not sure if it's suppose to target pets or not as i couldn't see any pets in cyclone yet.

**Comment by amed80** [comment]
That is the summoned spell for the totem as it's summoned 3y around Ashtongue Mystic and not related to what the totem do.

[Cyclone](https://wowgaming.altervista.org/aowow/?spell=39594) from totems should target 4-5? people/pet/totems in 40y range and not the whole raid.

Source:
[PTR TBC Classic1](https://youtu.be/t5SL62WLr_U?t=4248) at 1:10:48 you can see 3 people in cyclone and a totem.
[PTR TBC Classic2](https://youtu.be/MH2BKL4G_BQ?t=2711) at 45:11 you can see 3 people in cyclone and 2 totems  , at 49:46 there is 2 players cycloned and 2? totems (or 1 pet and 1 totem) , at 51:59 could only see 2 players and one totem in cyclone. (i think there is 4th cyclone also visible but not sure)
[PTR TBC Classic3](https://youtu.be/NRl78646E4M?t=2072) at 34:32 , 3 people in cyclone and 2 totems and at 40:10 there is 1 player in cyclone and 3-4? totems in cyclone too.
