### ISSUE TITLE
Not rewarded for arena 3v3 solo queues

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#7498]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

I did not receive the reward for 3v3 solo queue matches. This should have been 275 points. 
I had done necessary games in 2s which gave me 261 points.

Are the solo queue points even working or how are the rewards determined currently? Shouldn't the reward be from the bracket that would give the most points? 

With 14 point difference it does not matter really, but I'm bringing this up if this turns out to be the issue with > 1500 ratings as well. 

### Expected Blizzlike Behaviour

I think the expectation is that the reward would be from the bracket that would yield the most points, in this case from the solo queue 3v3. 

### Source

No source since this is regarding a module for 3v3 solo queue.

### Steps to reproduce the problem

1. Have enough 2s arena games
2. Have enough solo queue 3s arena games
3. Wait for the flush

### Extra Notes

According to several other people on Discord, no one has received points from solo queues.
1v1 solo queue apparently has given points.

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/88db984e52b2c0daf533c6a1ef769a3d50d7347c

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Helias** [comment]
This is weird, if you are level 70 you should be able to receive ArenaPoints

**Comment by Apathyxia** [comment]
That is what I thought as well when looking at the code.

Maybe there is something wrong in how the games are counted and in reality in the counted games no one reached 10? Just an idea.

**Comment by Helias** [comment]
> That is what I thought as well when looking at the code.
> 
> Maybe there is something wrong in how the games are counted and in reality in the counted games no one reached 10? Just an idea.

I was thinking the same because I recently fixed this, I will investigate

**Comment by Belodina** [comment]
Can confirm, didn't do 2s games and received 0 arena points after the flush despite doing the necessary games in 3v3 soloq.

**Comment by Apathyxia** [comment]
A little update regarding this:
Apparently some have received 275 points. However, my friend replayed 10 games on a character and got 275 points on it, but didn't play a single game. 

Also, on a character he replayed 10 games and played 10 games, he received 275 points. 

I did not watch any games, only did 2s and played enough games in solo Q 3s, I only got points from 2s. 

I think the counter only counts replayed games?

**Comment by Belodina** [comment]
Just to confirm what Apatia has mentioned, I also did not receive the arena points from soloq 3v3.

I currently have 520 arena points from the last 15 days of daily BG win (20x8 for non-CtA + 45x8 for CtA) since the arena wipe on Wednesday 30th October.

I think an update on the CC discord would also be greatly appreciated for those who do not check GitHub or frequent the CC discord to corroborate with other players and aren't sure what is happening.

As always, thank you for the immense work and effort! And no rush, have a good weekend <3

**Comment by Apathyxia** [comment]
Hello @Helias! Now it seems like the arena points were correctly rewarded with the flush. 
However, I do not know if it gives points from the bracket that yields the most - I didn't do 2s this week.
