### ISSUE TITLE
Arcane Concentration + Arcane missiles issue

### ISSUE THREAD

**Issue by bonfax4** [chromiecraft/chromiecraft#75]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:
Arcane missiles interaction with the talent is wrong.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[Arcane concentration](https://wowgaming.altervista.org/aowow/?spell=12577) should only be able to proc on the initial cast of arcane missiles, before the initial hit. I presume the invisible debuff it applies would have a % to proc while the spell cast would consume the buff.

Links that support this [here](https://wowwiki-archive.fandom.com/wiki/Arcane_Missiles) and [here](https://us.forums.blizzard.com/en/wow/t/arcane-missiles-and-clear-casting-arcane-concentration-bug/302706/5l)

Unrelated but while checking this out you could also check if [Arcane potency ](https://wowgaming.altervista.org/aowow/?spell=31572) interaction with missiles is working properly because it most likely isn't considering how it currently works. Relevant info [here](https://wow.gamepedia.com/Arcane_Potency).Missiles should be able to double dip potency if you consume it on cast and clearcasting/potency buff triggers at the same time if i'm understanding this correctly, meaning teh cast should fully benefit from the 30% crit buff when consumed + the 30% crit buff that remains active due to the subsequent cleacasting proc until a next spell is cast.

##### CURRENT BEHAVIOUR:

every missile of the channel seems to have a chance to proc it, and if it does proc, only the last missile of the next consumes the [Clearcasting](https://wowgaming.altervista.org/aowow/?spell=12536) buff from the talent. You can kinda abuse this and recast the spell before the last tick and get an extra mana free cast.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Spam arcane missiles 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by bonfax4** [comment]
Honestly, it's just unpredictable how it works. Sometimes the buff is consumed on the channel ticks, sometimes it isn't.

**Comment by Stifler82** [comment]
Both the **Spell and the Talent** work perfectly, as I demonstrated in **this video**.
**Video:** [Arcane Concentration   Arcane missiles](https://youtu.be/EgF3sjkibAk)

**Comment by bonfax4** [comment]
This is so wrong why woudl you test while being atacked ? you get at most 2 missles in so you van't rly see it happening in most cases. I Used my alt to tank the mobs and test. here's a video back from wotlk https://www.youtube.com/watch?v=c2RtyFh5TnE and see hwo it works. It's far perfect, the proc happens right when he casted it, and not on spell hit like it's currently happening. This has been a bug on most private servers. No individual hits of arcane missilesshould ever proc it, only the initial cast where the mana in spent. Try it on a dummie this time if you can.

**Comment by bonfax4** [comment]
> This is so wrong why woudl you test while being atacked ? you get at most 2 missles in so you can't rly see it happening in most cases. I Used my alt to tank the mobs and test. here's a video back from wotlk https://www.youtube.com/watch?v=c2RtyFh5TnE and see how it works. It's far perfect, the proc happens right when he casted it, and not on spell hit like it's currently happening. This has been a bug on most private servers. No individual hits of arcane missiles should ever proc it, only the initial cast where the mana in spent. Try it on a dummie this time if you can.

**Comment by bonfax4** [comment]
I've been doing dungeons with arcane and I've seen it happen multiple times btw the proc happening mid channel.

**Comment by bonfax4** [comment]
Here's a proper video from [retail](https://www.youtube.com/watch?v=3NLSkJRDaso) and check @ 7:55 and slow the video down and you can see clearcasting proc before the 1st miss1le hit

**Comment by bonfax4** [comment]
Retest this while not being atacked and you ann see it way clearer.
