### ISSUE TITLE
Fishing: no patches of Elemental Water in Azshara

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#751]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

There are currently no spawns of Patch of Elemental Water in Azshara https://wowgaming.altervista.org/aowow/?object=180753 .
I also couldn't find them in the AzerothCore SQL database (but maybe I didn't look at the right place?).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be 6 spawning points in Azshara: https://classic.wowhead.com/item=7080/essence-of-water
Coords (from a wowhead comment):
- 54.8, 38.8
- 60.1, 39.7
- 55.6, 51.1
- 79.2, 54.4
- 66.3, 68.5
- 74.6, 72.6

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Azshara, to the 6 locations
2. Wait 3 hrs (should be the respawn time according to wowhead comment)

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. Thanks for the report.
