### ISSUE TITLE
[Zul'Aman] Hex Lord Malacrass can only drop 2 gear items at a time

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7513]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) always drops 2 random gear items each kill

### Expected Blizzlike Behaviour

[Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) should be able to drop between 2 and 3 random gear items.

### Source

[TBC Classic1](https://youtu.be/DpHR5V7KnOk?t=1117) Hex Lord kill at 18:37 , drops 3 gear items
[TBC Classic2](https://youtu.be/XDGZM7GQNoo?t=2680) Hex Lord kill at 44:42 , drops 3 gear items
[TBC Classic3](https://youtu.be/P5ycvN09UiY?t=3007) Hex Lord kill at 50:09 , drops 2 gear items
[Wotlk PrePatch](https://youtu.be/0CtPGmyOOlY?t=376) Hex Lord kill at 6:18 , drops 3 gear items
[Wotlk PrePatch](https://youtu.be/7b-OtoM5Xpw?t=1637) Hex Lord kill at 27:19 , drops 2 gear items

### Steps to reproduce the problem

1. go c id 24239
2. or using Keira3
![image](https://github.com/user-attachments/assets/56af69fb-15d5-448a-b58e-0e685206bdd0)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6fd034c8b3038a967e17136ece47df13009e1d68

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by godnesso** [comment]
Third item dropping seems to always be the Tiny Voodoo Mask? More of a fun item than actual gear.

item id 34029

**Comment by amed80** [comment]
> Third item dropping seems to always be the Tiny Voodoo Mask? More of a fun item than actual gear.
> 
> item id 34029

After checking multiple ZA runs (+30) , this seems to be indeed the case , every 3 item drop have [Tiny Voodoo Mask](https://wowgaming.altervista.org/aowow/?item=34029) and never seen it when there is 2 items drops

I guess it should have it's own separate slot as currently it's listed with the other items and can take a slot in the 2 drops.

Also from [wowhead](https://www.wowhead.com/tbc/item=34029/tiny-voodoo-mask) it does look like it have higher chances to drop compared to the rest.

**Comment by amed80** [comment]
2 drop :
https://youtu.be/19uQEdbm9As?t=1981
https://youtu.be/googefOx9RA?t=3206
https://youtu.be/4At1FNloaRA?t=1667
https://youtu.be/5YjPHwv0HD4?t=1510
https://youtu.be/po_7Cn9vhqs?t=2739
https://youtu.be/g124lbdrMEo?t=2115
https://youtu.be/iDbfonka6x4?t=1567
https://youtu.be/_YbDuWzE6u8?t=2954
https://youtu.be/nGRj2EwaeKY?t=10768
https://youtu.be/dTGgVDFsbtk?t=2980
https://youtu.be/CAi_FBOFVZI?t=3885
https://youtu.be/sX82w7v7COI?t=2526
https://youtu.be/LWGNGn0veVA?t=4497
https://youtu.be/eIFvDv_kE8s?t=1201
https://youtu.be/0OdusEkySXI?t=3152
https://youtu.be/Y559AFZmXl8?t=3755
https://youtu.be/2a1TRn625vs?t=5985
https://youtu.be/vzh9AlubdAI?t=4005
https://youtu.be/q8tJvuVQvFk?t=3326
https://youtu.be/jEbQdd9ygWg?t=2820

3 drop:
https://youtu.be/XNx0Ljoks1k?t=16018
https://youtu.be/g_hXZzq-HFE?t=1131
https://youtu.be/hjjwsHLCj3M?t=2824
https://youtu.be/ta35ymRM3CY?t=2276
https://youtu.be/g8hLSqRrJq0?t=994
https://youtu.be/bdSM3IYvxjI?t=2815
https://youtu.be/U4le4ITLSr0?t=2280
https://youtu.be/hmjUEbDESiw?t=4414
https://youtu.be/tBBMdykycSg?t=2442
https://youtu.be/OOLItG3vROE?t=3929
https://youtu.be/0CtPGmyOOlY?t=379

Those some of the videos i could find which shows the loot after killing Hex Lord Malacrass

**Comment by Rorschach91** [comment]
@heyitsbench Do you know something about this?
