### ISSUE TITLE
[Zul'Aman] Amani Charms don't always work

### ISSUE THREAD

**Issue by Ottawia** [chromiecraft/chromiecraft#7550]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Amani Charms, which are items that provide four different buffs, don't always work. The game displays an error message saying, "You are in the wrong zone," when the player tries to use an Amani Charm inside a raid.
https://www.youtube.com/watch?v=S3BEjwLNeMo
During za tests with Night Howlsers turned out that paladin blood elf was able to use it and after tests that can be confirmed:

https://github.com/user-attachments/assets/35a3d443-9944-4dc1-b60a-6eb1ab32b592

So its possible that some specific class/race can use them now like paladyn/blood elf.

### Expected Blizzlike Behaviour

Amani charms should be usable inside raid by any class/race

### Source

https://www.wowhead.com/item=33930/amani-charm-of-the-bloodletter#comments

### Steps to reproduce the problem

1. Make few characters on PTR (to avoid "being lucky")
2. Set level to 70 and .tele za
3. Add Amani charms to your inventory (so far when 1 works every work so 1 should be enough)
4. Try to use it on characters
5. Find out that some on characters can not use them

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
I can confirm this issue part of `You are in the wrong zone.` only happens in CC, can't reproduce this in AC.

I was never able to give the buff to myself or another player (in CC).

For testing if anyone wants to add charms inside of Zul'aman

Amani Charms: 
- `.additem 33930` // Bloodletter
 
- `.additem 33931` // Mighty Mojo

- `.additem 33932` // Witch Doctor

- `.additem 33933` // Raging Defender

**Comment by Nyeriah** [comment]
Seem to work correctly on the live server, tried gnome rogue
