### ISSUE TITLE
[Zul'Aman] Hex Lord Malacrass keep using his previous class abilities after casting Spirit Bolts

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#7553]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) schedule previous class's abilities from his [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501) and cast them immediately after [Spirit Bolts](https://wowgaming.altervista.org/aowow/?spell=43383).

https://github.com/user-attachments/assets/f843fa7f-d442-405d-bac1-4289eb8d1020

### Expected Blizzlike Behaviour

[Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) shouldn't use any abilities from the previous class after the timer for [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501) is over

### Source

[TBC Classic](https://youtu.be/wPc2NNXfHNk?t=82) at 1:25 , [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) finishing channeling [Spirit Bolts](https://wowgaming.altervista.org/aowow/?spell=43383) and cast [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501) without using any of the previous class abilities (rogue) , and same at 2:05 and 2:45

### Steps to reproduce the problem

1. .go c id 24239
2. Fight [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) with 2 characters
3. Wait for [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) to use his first [Spirit Bolts](https://wowgaming.altervista.org/aowow/?spell=43383) then Siphon Soul
4. Wait for [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) to use his second [Spirit Bolts](https://wowgaming.altervista.org/aowow/?spell=43383).
5. [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) will use an abilities from the previous class before casting [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
@amed80 while you testing did you also notice that he doesn't cast syphon but it's an insta cast?

**Comment by amed80** [comment]
It insta cast it , tbh i am not sure if he should be channeling it or not.
In this [video](https://youtu.be/YM63vd5kPN0?t=4064) at 1:07:44 for example you can see it channeling? but it stops when Malacrass uses holy light

**Comment by TheSCREWEDSoftware** [comment]
Maybe channels to get a new ability but can be interrupted by itself (internal timer) to cast the stolen ability

**Comment by TheSCREWEDSoftware** [comment]
Linked to AC: https://github.com/azerothcore/azerothcore-wotlk/issues/20740
