### ISSUE TITLE
Unable to continue scryers questline in Area 52

### ISSUE THREAD

**Issue by cordyyyceps** [chromiecraft/chromiecraft#7555]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

I've got the breadcrumb from the Scryers I'm Shattrath and turned it in at Area 52 however the next quest is only available from the Anchorite and not the Scryer NPC, and she is unfriendly with me so I cannot accept the quest. She's also levitating.

### Expected Blizzlike Behaviour

The next quest should be available from the Scryers NPC.

### Source

Unsure

### Steps to reproduce the problem

Unsure- may be related to my race change. I've never been anything except scryer on this character (Cordy) so contact me in game or on discord (cordyceps) to show in game.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Windows 10

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
@cordyyyceps I'm looking into this. Can you clarify about your race change (just in the case be the cause), I will pressume was race change for the same faction and not an (race change) of a faction change

**Comment by cordyyyceps** [comment]
Sure, I changed from blood elf which had Scryer rep because of the race, to
a Troll.
I've not noticed any other changes to reputation but will check around when
I have time to today.

**Comment by TheSCREWEDSoftware** [comment]
Did you by any change pick the wrong Allegiance?

**Comment by cordyyyceps** [comment]
I've not picked one, I cannot talk to any faction npcs within aldor and the
quests are available from scryer, so rather this being a me problem it
looks like if you don't select a faction or do that questline it defaults
you to aldor.

**Comment by cordyyyceps** [comment]
So I didn't do the breadcrumb as a blood elf, sorry for confusion. I handed
in one arcane tome as a blood elf and then race changed, then went to the
npc for the breadcrumb as a troll, was able to take that from the scryer
npc and head to area 51, but then when I hand in the ! appears over the
anchorite  but because of my rep I can't talk to her to even see what quest
she gives

**Comment by TheSCREWEDSoftware** [comment]
Do you recall what was your rep between them?

**Comment by cordyyyceps** [comment]
So I will have been friendly because of being a belf, and then the arcane
tome will have put me at +350 over friendly, but not up to honored.

**Comment by TheSCREWEDSoftware** [comment]
You lose the bonus of being a blood elf the moment you changed to troll. So only the arcane tome rep? no quest rep?

**Comment by cordyyyceps** [comment]
Not sure, didn't do anything specifically  but may have got some passively,
sorry not sure.

**Comment by TheSCREWEDSoftware** [comment]
> then went to the npc for the breadcrumb as a troll, was able to take that from the scryer npc and head to area 51

At this point you did not talk to Khadgar and chosen your Allegiance, correct?

![image](https://github.com/user-attachments/assets/fd49ae4e-9c37-4fe4-bd5f-eb4985d3631f)

Which NPC did you talk to the Scryer? Since the only breadcum you need to do with `A'dal` and `City of Light` to unlock the screenshot above. And allow you to progress with that faction.

**Comment by cordyyyceps** [comment]
No, haven't spoken to khadgar at all. In fact I don't think he even has a
quest for me but I'm not sure if there's a breadcrumb for that

**Comment by cordyyyceps** [comment]
Hello!

I've got to the point of City of Light and I think that's broken for me too!

The servant just joined me as a pet would, and didn't go anywhere for 5
minutes or say anything, so I dropped the quest and restarted it, and if
you see the screenshot I now just have two pets! They follow me around and
don't whisper anything as they're supposed to...

**Comment by TheSCREWEDSoftware** [comment]
Just tested this on the PTR, I can confirm the situation what you reported above. While i find a way to still complete the quest. Accept the quest and abandon (until you have 2 Serveants following you) the 3rd should spawn and do the normal path and whispers. Try this to see if this fixes your rep issue. 

Meanwhile i will open a new issue related to this quest (since this problem with the servent is only happening in CC and CC PTR), thanks for report and being able to follow up each question

**Comment by TheSCREWEDSoftware** [comment]
I stand corrcted. Not the 3rd one. Keep accept and abandon until you see the serveant going to khadgar and walking around, while we try to fix this

**Comment by cordyyyceps** [comment]
Yes, but i had some guild things I needed to sort after so haven't gone to
area 52 to check I can do the next bit now.

**Comment by TheSCREWEDSoftware** [comment]
With no worries, please confirm the outcome here when you can

**Comment by cordyyyceps** [comment]
Yes of course :)

**Comment by cordyyyceps** [comment]
No worries! I wasn't sure if it was a client side bug but if it's known
then no bother :)
Thanks for your help

**Comment by TheSCREWEDSoftware** [comment]
You're welcome, don't be shy to ask questions in our support channel or tickets or an issue here.

Happy holidays
