### ISSUE TITLE
All Along the Watchtowers uncompleteable

### ISSUE THREAD

**Issue by cordyyyceps** [chromiecraft/chromiecraft#7578]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

50-59

### Current Behaviour

Quest is bugged with tower 2. The other towers work - you place the torch and it displays on the ground, but the credit isn't given in the quest. If you try too many times, you lose the torch and have to drop the quest to be able to get a new one.

I tried to get Tower 2 to acknowledge the torch twice.

### Expected Blizzlike Behaviour

1. The torch shouldn't be placeable if it is in the wrong location
2. If the torch appears on the ground, proper credit should be given

### Source

Classic wow

### Steps to reproduce the problem

1. Take the quest All Along the Watchtowers
2. Head to tower 1, place torch - this gives credit
3. Head to tower 2, enter the doorway, use the torch - the torch will appear on the ground but no credit will be given.
4. This can be repeated until the torch item runs out of charges.

### Extra Notes

It might be worth giving the torch infinite charges/allow you to pick up a new one from the questgiver, even though I don't think that is blizzlilke (I have never needed to use more than one charge in a tower because you shouldn't be able to place it without getting credit)

Please see the screenshot to see that the tower has not been marked and credit given, even though i have visited it twice.

![Screenshot 2024-12-02 111709](https://github.com/user-attachments/assets/ded50f03-4742-4eb1-967d-c1aa633be47d)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Windows 11

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cythisiax** [comment]
Not replicating this with current source. All torches can be placed, and credit is provided for all four; https://streamable.com/6ay6ac
