### ISSUE TITLE
Instant Log out and Ability to log off during combat

### ISSUE THREAD

**Issue by Jinmcx** [chromiecraft/chromiecraft#760]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

1. Instant log off outside of Inn
2. Ability to Log off during combat

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. 20 second timer to log off
2. Unable to log off during combat

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Used Log out in STV area outside of booty bay instantly
2. Enter combat with mob and client will log out within 20 seconds timer
3. 
4.

##### EXTRA NOTES:

Seem to happen on june 2, 2021

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Jinmcx** [comment]
![WoWScrnShot_060221_014358](https://user-images.githubusercontent.com/19652090/120444292-bbbf4900-c344-11eb-81cd-62e1f82301fa.jpg)

**Comment by gurveleg** [comment]
not just STV. It is possible to log out instantly everywhere.
