### ISSUE TITLE
Deadwood Warrior interrupts its own cast with melee swing

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#7614]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Currently, [Deadwood Warriors](https://wowgaming.altervista.org/aowow/?npc=7153) in Felwood interrupt their cast of [Curse of the Deadwood](https://wowgaming.altervista.org/aowow/?spell=13583) on their melee swing. When fighting in melee, they will never get the cast off.

https://github.com/user-attachments/assets/a14bb520-f69e-47bf-9479-56eec30d3b6e

### Expected Blizzlike Behaviour

The melee swing should not interrupt the cast. The melee swing should not happen while the cast is happening.

### Source

This points to the fact that warriors would be affected by this one, exactly from these mobs. It is a clear indication that the swing would not happen while the cast is happening. 

https://www.wowhead.com/wotlk/npc=7153/deadwood-warrior#comments:id=212299

### Steps to reproduce the problem

1. Go to south western Felwood to Deadwood Village. 
2. Aggro one of the Deadwood Warriors and go into the melee range
3. Observe how they swing you, then start casting Curse of the Deadwood, and then interrupt it when they next swing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Apathyxia** [comment]
The spell itself is interruptable. The report I made is about the warrior interrupting its own cast by using a melee swing.

I did not observe Pathfinder to interrupt its own cast. I think Gardener might interrupt only when it casts a heal. But neither would interrupt because of a melee attack.

**Comment by Sunnypotato** [comment]
guessing that that is caused by its SmartAI
![Screenshot 2024-12-11 153213](https://github.com/user-attachments/assets/0cc2f596-5229-4038-b542-9c2d667932e0)
