### ISSUE TITLE
Frayfeather Stagwings and Skystormers use their abilities while CC'd

### ISSUE THREAD

**Issue by Apathyxia** [chromiecraft/chromiecraft#7616]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

40-49

### Current Behaviour

[Frayfeather Stagwings](https://www.wowhead.com/wotlk/npc=5304/frayfeather-stagwing) use their ability Swoop while they are under effects of crowd control.

https://github.com/user-attachments/assets/a1c4fbf4-b491-4400-9e02-8be5289a5404

[Frayfeather Skystormers](https://www.wowhead.com/wotlk/npc=5305/frayfeather-skystormer#abilities) use their ability Lightning Cloud while they are under effects of crowd control.

https://github.com/user-attachments/assets/05c82887-41bd-462e-92a1-2feb90654bba

### Expected Blizzlike Behaviour

Mobs should not use abilities while stunned or incapacitated.

### Source

No source: should be clear that this should not happen. 

### Steps to reproduce the problem

1. Find a Frayfeather Stagwing or Skystormer in Feralas
2. Use any of form stun or incapacitating ability on it
3. Walk to melee range
4. Observe how Swoop or Lightning Cloud is used.

### Extra Notes

There was another similar issue from before where some other mobs were using abilities while crowd controlled.
https://github.com/chromiecraft/chromiecraft/issues/4983

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/60667e75c3c3e45e8caf7554308594d9d00bb17d

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
You were somehow very luckly or unluckly that they only cast that while charmed.

![image](https://github.com/user-attachments/assets/7e63616f-bc61-4f72-80a5-03c264c9353e)

![image](https://github.com/user-attachments/assets/29c25af8-49bf-4f66-8662-457583f847b6)

Validated that this is not thei ntended behaviour, will make a PR to fix this, thanks for the report!
