### ISSUE TITLE
[Felwood] Multiple Plaguebloom nodes very close

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#762]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

There are 3 plaguebloom nodes very close to each other in Felwood, near coords 62 ; 26.0 .
Ids: 19879 ; 19919 ; 19878 (entry number 176587).
There is also another node (id 85912) with different entry number (176641), but there are only 3 nodes, so that's weird.
Screenshot:
![WoWScrnShot_060221_124649](https://user-images.githubusercontent.com/81818678/120468290-577ea280-c3a1-11eb-9dcf-d3048f5eaf6c.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nodes should not all respawn together.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Felwood, coords 62 ; 26.0

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I believe you're in felwood, not Azshara 😉
![image](https://user-images.githubusercontent.com/68164076/120586843-21fda780-c3e9-11eb-82de-9014bf73ca02.png)

**Comment by Stump876** [comment]
While I didn't necessarily see 3 plaguebloom, I did see many in very close proximity. 
![image](https://user-images.githubusercontent.com/68164076/120588104-7570f500-c3eb-11eb-9197-da1da96eff11.png)

**Comment by pop-pig** [comment]
Haha thanks it was indeed in Felwood, my bad :)
I corrected the title and the issue

**Comment by v-mstrs** [comment]
Done

**Comment by heyitsbench** [comment]
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/25797238026ca87a9a3906add11ebfc9cc9802d4.
