### ISSUE TITLE
visual - background image on talent selector stretches upon selecting specific talent

### ISSUE THREAD

**Issue by spiralofhope** [chromiecraft/chromiecraft#7620]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

When selecting a specific talent (perhaps a specific tier) the background image becomes stretched/distorted.

Before:
![01 - before](https://github.com/user-attachments/assets/b22f4e72-7eb0-4362-8600-049fc69b2477)

After:
![02 - after](https://github.com/user-attachments/assets/4b3389b4-32d7-4c64-855b-0fd9754f5bdd)

Side-by-side (it is much easier to see this effect when opening the two above images in new tabs and tabbing between them, or observing the bug in-game)
![03 - side-by-side](https://github.com/user-attachments/assets/adde821c-0c29-47d1-a783-f79998c93b6c)

### Expected Blizzlike Behaviour

Any interaction with the talent selector trainer dialog should keep an unchanged background image dimensions/stretch.

### Source

(I'm not sure what this is, and README.md doesn't elaborate)

Development/Chromiecraft as of 2024-12-14

Client login screen:
```
3.3.5 (12340) (Release)
June 24 2010
```

```
/dump select( 4, GetBuildInfo() )
30300
```

### Steps to reproduce the problem

1. Be a level 15 warlock
2. Visit the Warlock Trainer "Briarthorn" in Ironforge
3. For Affliction, select the talents:
  -- 2/2 Curse of Agony
  -- 3/3 Suppression
4. View the background image of the talent selector and note the vertical appearance
5. Apply and confirm
6. For Affliction, select the talent:
  -- 1/2 Improved Drain Soul
7. Apply and confirm
8. View the background image of the talent selector:  The background image is stretched vertically

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/60667e75c3c3e45e8caf7554308594d9d00bb17d

### Operating system

Windows 11 64 bit latest update

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

High resolution textures

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
This is not an issue. is Feature `Preview Talent Changes` in Interface > Features.

![image](https://github.com/user-attachments/assets/b3bc7088-c093-4fde-976c-7518f6b8840f)

**Comment by spiralofhope** [comment]
> While you have points to spend the confirmation buttons will appear. when there's no points to spend (after confirmation or no points in general, no button appears)

I see. Because the buttons are absent the window is a different size. The background image aspect ratio is fixed to the inner window aspect ratio.

I guess Blizzard didn't implement a viewport to a larger image and just scaled/stretched.

Thanks!
