### ISSUE TITLE
web: restore deleted character

### ISSUE THREAD

**Issue by Helias** [chromiecraft/chromiecraft#7639]
### Bug Title

restore deleted character

### Current Behaviour

the restore deleted character service does not work, it works only "sometimes".

I verified it multiple times but apparently "sometimes" it does not work, I need more logs to debug and understand why, in a clean fresh install of the website it works without any issue.

### Expected Behaviour

it should always work

### Steps to Reproduce

make an order

**Comment by TheSCREWEDSoftware** [comment]
To add to this, it supposed to only take 1 (Restore) at the time. Or you should be able to Restore multiple chars (1 restore per char (assuming it tracks each entry of char in the restore in the cart). and charge X amount points for the total.

But also this store issue could be the same related to not all the emails not working properly, probably a recent change?

**Comment by Helias** [comment]
I've enforced an option to make only one character per order as a workaround, in the future we could allow multiple character in one order but I think it's not necessary right now

**Comment by Helias** [comment]
fixed, it will be live soon
