### ISSUE TITLE
[Barrens] Two very close Peacebloom nodes

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#766]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There are two very close Peacebloom nodes in the Barrens, near coords 49.4 ; 30.1 .
Spawn ids: 1742 and 63422
Screenshot:
![WoWScrnShot_060321_082003](https://user-images.githubusercontent.com/81818678/120597094-e42e6c80-c444-11eb-9847-6d7a06be6ecd.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nodes should not be that close.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Barrens, coords 49.4 ; 30.1 (i think the GM command is ".go o 1742" ?)

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I can't confirm that one. I just see one on my local server.
![image](https://user-images.githubusercontent.com/68164076/120730623-bd008b00-c496-11eb-9bb3-39fddec75ed7.png)

**Comment by pop-pig** [comment]
I've checked again today a few times after server restart (1hr, 2hrs, 3hrs after restart), it seems like it has been fixed.
I guess we can close the issue! :D

**Comment by pop-pig** [comment]
Issue is back (or is still here :( )
Screenshot taken on June 6th 2021 at 6:24 AM server time
![WoWScrnShot_060621_082449](https://user-images.githubusercontent.com/81818678/120914819-c5c4ad00-c6a0-11eb-830b-750f2e14b8ba.jpg)

**Comment by Stump876** [comment]
Herb and Mine spawning are a known issue and they are working on a solution. In the meantime I'll link this over to AC for reference

**Comment by heyitsbench** [comment]
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/25797238026ca87a9a3906add11ebfc9cc9802d4.
