### ISSUE TITLE
[Barrens] Razormane Hunter's wolf disappearing as hunter dies

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#767]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Currently, killing Razormane Hunter while his Razormane Wolf is still alive makes the Wolf disappear out of thin air.
Video recorded on ChromieCraft: https://youtu.be/vh3VBQRHpCM
Razormane Hunter: https://wowgaming.altervista.org/aowow/?npc=3265
Razormane Wolf: https://wowgaming.altervista.org/aowow/?npc=3939

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Wolf should not disappear, it should stay in the open world.

##### SOURCE:

This is from Classic Wow (the retail one that released late August 2019): https://youtu.be/p_mlzteluTE?t=2854
At 47:34 the player engages a Razormane Hunter and kills the hunter, the Wolf stays alive and then dies. The Wolf does not disappear when the Razormane Hunter dies.
Sorry for the very bad quality, I'll try to find another better quality source.
It is not WotLK but there should be no reason why this kind of behaviour would be changed ?

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Barrens, near 55 ; 26, and find a Razormane Hunter.
2. Kill the Razormane Hunter while not killing the Wolf.
3. See the Razormane Wolf disappear as the Hunter dies.

##### EXTRA NOTES:

As stated, evidence is from Classic Wow. I do not think that this behaviour would have been changed when retail went to WotLK but I could be wrong.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Can confirm this behaviour is happening with multiple NPC pet classes. Whether it is Blizzlike or not is considerably more hazy. However, I've checked a number of Classic videos of multiple pet classes, and they all showed that enemy pets were not despawning on their master's death. Also found a TBC-era comment confirming that behaviour as well, so that seems enough to take the issue across to AC.
