### ISSUE TITLE
[Felwood] Truesilver node "inside" a tree

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#768]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Near coords 63.4 ; 21.2 in Felwood, there is a Truesilver node inside the root of a tree.
Node id is 9351.
![felwood](https://user-images.githubusercontent.com/81818678/120685266-f4c00080-c49f-11eb-9d5e-86660535f577.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Truesilver node should not be in the tree?
I'm not sure if it's actually a "real" issue, it just looks very weird. 
Maybe the node could be slightly moved to be near the tree but not inside it?

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Felwood, coords 63.4 ; 21.2

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40cf7b46d221e562a20264316d660318af213690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I can confirm it's there. It's accessible. It just happens to be next to 2 trees. Maybe one is petrified wood? I agree this might not be a "real" issue. There are no other veins in close proximity. So unless you have something that says it shouldn't be there. Let's let this one go.
