### ISSUE TITLE
Unable to log out

### ISSUE THREAD

**Issue by 55Honey** [chromiecraft/chromiecraft#77]
##### CONTENT PHASE:

1-19
Issue probably not dependant on levelrange.

##### SMALL DESCRIPTION:

Unable to log out log out / exit game via the games respective buttons when standing on another toon. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The positioning of a character inside another should not affect the ability to log out.

##### CURRENT BEHAVIOUR:

When following with multiple toons and hereby standing inside another, the "Logout" and "Exit Game" button **rarely** return  "You can not log out now".

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Log multiple toons and have them all follow the same main.
Step 2 Play a while. 
Step 3 Try to log out inside an Inn with all followers standing inside of each other. 

Moving the slightest bit, lets that toon log out just fine. The phenomenon does only appear when they are perfectly stacked.

I myself have been unable to reproduce the problem reliably. It seems to be mandatory to be logged in for a while. However, it did appear multiple times.
I will try to remember to record a video of the issue when i have a longer playsession and the error appears the next time.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
https://streamable.com/mkxi97
Footage of the bug happening. IF it happens, it is 100% solved by the slightest bit of movement.

**Comment by eTzmNcbkrng** [comment]
You get the same error if you are `/afk`
