### ISSUE TITLE
[Deadmines] LOS bug on wizard after smelting room

### ISSUE THREAD

**Issue by expigator** [chromiecraft/chromiecraft#775]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

#####Faction

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE

- [ ] Generic
- [x ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.

hallway after Goblin smelting room in Deadmines. Wizard npc if attempt to line of sight mob it will run all the way down the hall and aggro every mob instead of coming after the tank.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When LOS the mob should follow the tank into the goblin smelting room.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40cf7b46d221e562a20264316d660318af213690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. In the future, please consider giving us steps to reproduce. The more info you can provide us, the easier it will be for us to verify, reproduce, and potentially solve the issue. You can learn a lot of helpful information about an NPC by typing in chat `.npc info` Also screenshots or videos of the bug and/or how it is supposed to work would be helpful. 

Mob LOS is a know issue and is a high priority work in progress. [https://github.com/azerothcore/azerothcore-wotlk/issues/5022](https://github.com/azerothcore/azerothcore-wotlk/issues/5022)
