### ISSUE TITLE
[Deadmines] Smite shouldn’t aggro group at ship entrance

### ISSUE THREAD

**Issue by expigator** [chromiecraft/chromiecraft#776]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When pulling Smite in Deadmines, the mobs at the top of the gangplank should not also aggro. They are tied to him even if you pull only the hidden mobs at bottom. Not sure if it’s level based but they came when 18 tank and also with 23 tank.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only Smite and his guards should pull as part of this boss encounter.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40cf7b46d221e562a20264316d660318af213690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thank you for the report. But next time please remember to fill out the report completely and correctly or it might get closed right away. [https://github.com/chromiecraft/chromiecraft#readme](https://github.com/chromiecraft/chromiecraft#readme) Also, don't forget to check and see if the bug has been reported before reporting it as new. This has been reported [here](https://github.com/chromiecraft/chromiecraft/issues/280) and Linked to AC [here](https://github.com/azerothcore/azerothcore-wotlk/pull/5373) and [here](https://github.com/azerothcore/azerothcore-wotlk/issues/2588) and these are still open.  I can confirm that this still happens, but it looks like this is a known issue on AC and they are still looking into it.
