### ISSUE TITLE
Polearms can be learned before level 20

### ISSUE THREAD

**Issue by 55Honey** [chromiecraft/chromiecraft#78]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

NPC [Woo Ping](https://wotlkdb.com/?npc=11867) teaches Pole Arms before the player has reached level 20.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Level 20 should be mandatory for Polearms to become available.

##### CURRENT BEHAVIOUR:

NPC [Woo Ping](https://wotlkdb.com/?npc=11867) teaches Pole Arms before the player has reached level 20.
Archibald in UC does not teach it to a player below level 20.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Have an alliance character below level 20.
Step 2 Talk to [Woo Ping](https://wotlkdb.com/?npc=11867) in Stormwind Trade District.
Step 3 Learn Polearms before level 20.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Voxstrasza** [comment]
Fixed :)

**Comment by FrancescoBorzi** [comment]
@Voxstrasza thanks, please add the `[Fix Ready]` label whenever something got fixed. We will close the issue once the fix is live on ChromieCraft.
