### ISSUE TITLE
[Eastern Plaguelands] Mob named Unknown

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#782]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

There is mob "Unknown" GUID 91933 in Eastern plaguelands
![unknown_91933](https://user-images.githubusercontent.com/80769357/120859874-1fd05000-c585-11eb-8f73-ab296c920655.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should not be named Unknown

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID 91933
2. Observe the mob named Unknown

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40cf7b46d221e562a20264316d660318af213690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
This is a game client bug caused by a few dropped packets or lag. See issues https://github.com/chromiecraft/chromiecraft/issues/411, https://github.com/chromiecraft/chromiecraft/issues/260 and https://github.com/chromiecraft/chromiecraft/issues/229.

![WoWScrnShot_060521_120119](https://user-images.githubusercontent.com/81782124/120877455-c94f2a00-c5f5-11eb-9b02-1dcf6fff8a3f.jpg)
