### ISSUE TITLE
[Eastern Plaguelands] Wrong level of summoned Skeletal Servants by Necromancers

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#783]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Necromancers (https://wowgaming.altervista.org/aowow/?npc=8553) in Eastern Plaguelands have wrong level of their summoned Skeletal Servants 
They are all level 42, while the spell they should use ( https://wowgaming.altervista.org/aowow/?spell=12420) says the Skeletal Servants are of lvl 51-58 (https://wowgaming.altervista.org/aowow/?npc=8477)
![necro](https://user-images.githubusercontent.com/80769357/120863453-ddaa0d00-c58a-11eb-807f-734696700226.jpg)
![42](https://user-images.githubusercontent.com/80769357/120863454-de42a380-c58a-11eb-818e-a405d98fdfae.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Summoned mobs should have the appropriate level.

##### SOURCE:

https://youtu.be/rI7-l4oiAzg?t=22

https://www.wowhead.com/npc=8477/skeletal-servant

https://wowpedia.fandom.com/wiki/Skeletal_Servant says
Patch changes

    Cataclysm Patch 4.0.3a (2010-11-23): Level reduced from 51 - 58. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to Necromancers in Epl (guid 92274 for example)
2. See the summoned skeletal servants are level 42

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40cf7b46d221e562a20264316d660318af213690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
I just had a look at all the Necromancers spawned in EPL (not that hard since there's only 8 in the DB) and couldn't find any with underlevelled skellies. they were all 54-55 as expected.

![WoWScrnShot_060521_121424](https://user-images.githubusercontent.com/81782124/120877924-48ddf880-c5f8-11eb-9b55-0d91d9bd4d9d.jpg)
![WoWScrnShot_060521_121457](https://user-images.githubusercontent.com/81782124/120877925-49768f00-c5f8-11eb-8b33-c191a4c6bce9.jpg)
![WoWScrnShot_060521_121501](https://user-images.githubusercontent.com/81782124/120877928-4a0f2580-c5f8-11eb-94f2-910dd898ae97.jpg)
![WoWScrnShot_060521_121535](https://user-images.githubusercontent.com/81782124/120877929-4aa7bc00-c5f8-11eb-83e9-56f97d426714.jpg)

The spell ID of the spell they cast is 12420 (Summon Skeletal Servant) which looks like it could be worth investigating - wondering about level scaling issues now. Will retry with a lower level char.

**Comment by Azcobu** [comment]
Just did the circuit of 8 Necros with a lvl 39, and the skellies were spawning as 54-55s again, so showing to a lvl 39 as skull mobs. 
![WoWScrnShot_060521_124404](https://user-images.githubusercontent.com/81782124/120878501-1209e180-c5fc-11eb-9793-b7790e24a2a7.jpg)
![WoWScrnShot_060521_124444](https://user-images.githubusercontent.com/81782124/120878503-133b0e80-c5fc-11eb-9720-3ec19d1a151b.jpg)

Looking up the summon spell on WOTLKDB https://wotlkdb.com/?spell=12420 show it's also used by a lvl 35 elite Death's Head Necromancer (https://wotlkdb.com/?npc=7337) , and a 60-61 elite, Thuzadin Necromancer (https://wotlkdb.com/?npc=10400) The same spell being used by mobs 25 levels apart does suggest it might be intended to scale by summoner level, but that doesn't explain why the ones you found were the wrong level.

**Comment by gurveleg** [comment]
I deleted cache and go look again:
![42skele](https://user-images.githubusercontent.com/80769357/120879139-955a1180-c5c1-11eb-8ddb-c93002c1e60f.jpg)
![again42](https://user-images.githubusercontent.com/80769357/120879140-95f2a800-c5c1-11eb-9258-ef272964ebab.jpg)
![skele](https://user-images.githubusercontent.com/80769357/120879141-968b3e80-c5c1-11eb-8066-ec39070bbd2c.jpg)
![skele42](https://user-images.githubusercontent.com/80769357/120879142-968b3e80-c5c1-11eb-84b2-b80fd8f948af.jpg)

if you cant reproduce localy then check on chromie server, it might be specific to chromie only

**Comment by Stump876** [comment]
I couldn't reproduce locally either. I even gave myself the spell to see what level it would spawn and it matched my level, no matter what level I picked. They should be spawning at the level of the caster. This might be limited to CC.

**Comment by eTzmNcbkrng** [comment]
```
.go cr 91940
.go cr 91946
.go cr 92235
.go cr 92264
.go cr 92269
.go cr 92271
.go cr 92274
.go cr 92279
```
Just checked all the Necromancers on ChromieCraft. All their skeleteons are L42.

**Comment by gurveleg** [comment]
They are now lvl 52 on Chormiecraft
![servants](https://user-images.githubusercontent.com/80769357/126776028-b8dd20e5-0a0a-4bed-a591-6326a510918d.jpg)
No longer valid report so I will close this.
