### ISSUE TITLE
Health pot not activating & autoattack stopping 

### ISSUE THREAD

**Issue by Hemingway1970** [chromiecraft/chromiecraft#79]
##### CONTENT PHASE:
lvl 14 rogue using either of smallest two potions fail. 

##### SMALL DESCRIPTION:
Attempting to use a health potion fails from bottom right action bar. Subsequently autoattack stops working and only special attacks can be used. 

##### EXPECTED BLIZZLIKE BEHAVIOR:
Health potions should activate, be used up and provide health points. Autoattack should be unaffected. 

##### CURRENT BEHAVIOUR:
Rogue with alchemy attempts to use health pot. Pot is not used up. No health is provided and health pot on action bar remains highlighted. Autoattack stops working and cannot be restarted. 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Use health pot from lower right action bar
Step 2 watch health bar 
Step 3 watch autoattack

Unfortunately I'm not sure how reproducible this is as I have not seen it on any other toon. I have reproduced it consistently on this rogue with alchemy, with and without addons. My guess is its connected to alchemy or mixology but that doesnt really fit either. It is a game breaking bug for this toon. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
Level 14 rogue with mixology and 150 skill in Alchemy:  Can not reproduce. Minor and Lesser Healing Potion are both consumed and restore health. No effect on Auto Attack.

**Comment by Hemingway1970** [comment]
Disregard. Switching to a different client fixed it. No idea what caused it but its apparently client side.

**Comment by Hemingway1970** [comment]
Switched to a new client and though initially the bug disappeared I have now reproduced it. Seems to only happen in combat. I generally use combination of ss/s&d/gouge. Gouge may be involved since it also shuts off autoattack?

**Comment by illfated** [comment]
Test if this happens also when using the item directly from the bags, not from the toolbar. The issue could be caused by a toolbar addon, but I don't know.

**Comment by Hemingway1970** [comment]
Just tested with virgin Chromie client with zero add-ons and am still getting this bug.

**Comment by illfated** [comment]
> Edit: Went to test whether potion worked straight out of bag and it did. After that the bug seems to have disappeared. Now I cannot reproduce the bug. No clue O.o

Thanks for confirming that it works on unmodified. Sometimes, even the toolbars on their own can cause some odd behaviour when placing bag items in the toolbars, even if the items never caused issues before. I can only suggest a combination of game client Cache + UI/Lua issue.

**Comment by orfaze** [comment]
Have the same problem with an alchemist, can't use lesser healing potion, i remenber using one before getting the trait "mixology"
No matter what i do, i can't use them => Relog / disable addon / delete addon completely / click from bag, none work :(

**Comment by 55Honey** [comment]
@orfaze 
Close wow, delete your Cache folder. Make sure you're using an enUS client, not enGB, by checking the subfolder names in the Data directory. The one from ChromieCraft is enUS.
Then retry.
