### ISSUE TITLE
Vultros Incorrect Drop

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#791]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After killing the rare Vultros it dropped item https://classic.wowhead.com/item=5514/mana-agate which isn't supposed to be dropped at all.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It shouldn't drop that item.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Westfall
2. Find Vultros
3. Kill him and loot him
4. Observe

##### EXTRA NOTES:

Vultros: https://classic.wowhead.com/npc=462/vultros

![WoWScrnShot_060221_125607](https://user-images.githubusercontent.com/84775498/120919907-71c7c180-c6bc-11eb-927b-40250ee9e213.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. Thanks for the report. This should not be in the loot table at all, it's a conjured item.
