### ISSUE TITLE
[NPC patrol] Brumeran should be patroling

### ISSUE THREAD

**Issue by Synful-Syn** [chromiecraft/chromiecraft#793]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

Should be seen by both factions.

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Brumeran is not patroling. He doesn't move away from 62,57 on it's own.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Brumeran should be patroling.

##### SOURCE:

https://classic.wowhead.com/npc=10807/brumeran

##### STEPS TO REPRODUCE THE PROBLEM:

1. 

##### EXTRA NOTES:

![image](https://user-images.githubusercontent.com/22718174/120927293-6ff70180-c6ae-11eb-8701-a3f27d241da1.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. He's just hanging out. Thanks for the report. 
![image](https://user-images.githubusercontent.com/68164076/120936383-5361c600-c6bc-11eb-9503-b9b244c2cd9f.png)
