### ISSUE TITLE
Hunter attacks between ranged and melee cancel auto attack

### ISSUE THREAD

**Issue by creativemonkeyz** [chromiecraft/chromiecraft#795]
- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I remarked this issue with my lvl 2 hunter: If I right click a NPC to auto attack it with range DPS my char will stop attacks when NPC reach me and every time when i'm trying to run away from the mob, when it dmg me, auto attack will reset and i need to right click again to attack.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If i start attacking a mob and the mob reach me, my attacks should change from ranged to melee without cancelling my attacks.
##### STEPS TO REPRODUCE THE PROBLEM:

1.  Create a lvl 1 hunter
2.  Go to a max attackable range to a mob
3.  Attack the mob with range weapon
4. When mob reach you, your auto attack will be cancelled instead of switching to melee.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. Thanks for the report. Make sure to remove the space between the [X] on reports going forward. 😉

https://user-images.githubusercontent.com/68164076/120938572-359a5e00-c6c8-11eb-9157-b03fdd82ac02.mp4
