### ISSUE TITLE
[Herb] Two very close Bruiseweed nodes in Arathi Highlands (Stromgarde Keep)

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#796]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There are two very close Bruiseweed nodes in Arathi Highlands, in Stromgarde Keep.
Nodes id are 3859 & 3151, at coords 21.1 ; 59.7.
Unfortunately I picked one before realizing there were another one right behind...
![WoWScrnShot_060621_183701](https://user-images.githubusercontent.com/81818678/120935116-7c587a00-c701-11eb-83a4-0b09c06e48e5.jpg)

Also, right after starting a local AzerothCore server, there is only one node:
![WoWScrnShot_060621_195155](https://user-images.githubusercontent.com/81818678/120935431-fb9a7d80-c702-11eb-9a7c-9a108fdceb4c.jpg)

Maybe kinda linked with issue #766 ?

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nodes should not be this close.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Stromgarde Keep at coords 21.1 ; 59.7 in Arathi Highlands, or ".go object 3859"

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I only saw one spawned on my local server  
![image](https://user-images.githubusercontent.com/68164076/121101643-11667c00-c7b1-11eb-822e-0aff79594c5d.png)But I found double wild steelbloom behind the keep
![image](https://user-images.githubusercontent.com/68164076/121103777-74f2a880-c7b5-11eb-976d-c10a26120637.png)

Talking with the devs, Herb and Mine spawning are a known issue and they are working on a solution. In the meantime I'll link this over to AC

**Comment by heyitsbench** [comment]
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/fd7c8a0bde61508c8654c7be92c9fc2be65d2ac2.
