### ISSUE TITLE
When fighting 2+ mobs using Wand weapon, character will stop autoshooting if the mob who was attacked first dies

### ISSUE THREAD

**Issue by Beastmasterwow** [chromiecraft/chromiecraft#797]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [ X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If you are fighting 2+ mobs using wand weapon, after you switch target using default "Tab" keybind, autoshooting will stop when the mob who was attacked first is killed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Character should be able to continue to autoshoot other mob even when first target is killed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make Warlock, get wand weapon.
2. Send your Voidwalker to attack 2 mobs.
2. Start using wand on 1 mob
3. Before first target is killed switch to other mob using default "tab" keybind
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. Thanks for the report. However, I believe this is blizzlike. Wand `Shoot` and hunter `Auto shot` are not the same. If anything I think the bug would be that it continues to attack after you tab target.  According to this it should stop.

[https://wowwiki-archive.fandom.com/wiki/Wand](https://wowwiki-archive.fandom.com/wiki/Wand)
**To use a wand:**

Equip a wand in your ranged weapon slot on the Character panel.
Move the 'Shoot' ability from the General Abilities tab of your Spellbook to a hot button on your button bar.
Target an enemy.
Push the Shoot button.

**To stop using a wand, do any of these:**

Use an ability.
Take a few steps in any direction, or jump.
Press the Esc key.
Click the fire button again.
Right-click a mob (this should put you back into melee mode).
Re-target a mob by pressing 'T' (assuming you have the default key shortcut).
Activate an item.
Use a /stopcasting macro.

I'll leave this open to see if anyone else has any input.

**Comment by Stump876** [comment]
Actually it was pointed out to me this was a duplicate. [https://github.com/chromiecraft/chromiecraft/issues/322](https://github.com/chromiecraft/chromiecraft/issues/322) and it is under evaluation.

Please remember to search for you're issue before reporting it as new. That goes for me too 😆
