### ISSUE TITLE
Character creation cinematic intro video and other flyby

### ISSUE THREAD

**Issue by Yehonal** [chromiecraft/chromiecraft#8]
Issue on AC: https://github.com/azerothcore/azerothcore-wotlk/issues/4039

**Comment by Helias** [comment]
Maybe we can use this instead of that closed PR https://github.com/TrinityCore/TrinityCore/commit/87b4533046d337fe05d7891c3632d34f8811b73e

**Comment by Yehonal** [comment]
Sure thing! Thank you

**Comment by Yehonal** [comment]
I've moved this issue on AC
