### ISSUE TITLE
[Eastern Plaguelands] Wrong level of summoned Carrion Scarabs

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#800]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

This issue looks a bit like issue #783 : same zone, same wrong level of summoned creature.
In the tunnel between Terrordale & Tirion Fordring (around 8.5 ; 32.4) in Eastern Plaguelands, Crypt Horrors ( https://wowgaming.altervista.org/aowow/?npc=8557 ) will summon little Carrion Scarabs ( https://wowgaming.altervista.org/aowow/?npc=10699 ). These mobs are currently level 42 instead of 57-58:
![WoWScrnShot_060721_051545](https://user-images.githubusercontent.com/81818678/120956049-0d0b7600-c753-11eb-87d1-0f7b4bac1c9e.jpg)
It seems like it's only the displayed level that could be wrong, as it has the correct health and mana points.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Carrion Scarab should be level 57-58.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go inside the tunnel between Tirion Fordring & Terrordale.
2. Aggro a Cryp Horror, wait for it to summon a Carrion Scarab

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I'm going to leave this open, in case someone else wants to take a crack at it, but much like the other one I can't duplicate. they come up same level at the mob that spawns them.
![image](https://user-images.githubusercontent.com/68164076/120959615-0a872d00-c70f-11eb-9f48-e9e7b637c314.png)
Level 42 keeps coming up. I imagine it's the same solution. The problem just needs to be identified.

**Comment by Eldarix** [comment]
![WoWScrnShot_060921_182206](https://user-images.githubusercontent.com/82579073/121382989-c9319000-c94f-11eb-9196-71d012a258cc.jpg)
![WoWScrnShot_060921_182241](https://user-images.githubusercontent.com/82579073/121383049-d3538e80-c94f-11eb-983e-50d5cb2c6646.jpg)

Same here :)

**Comment by eTzmNcbkrng** [comment]
TODO: Test this bug with a lower player level (current max on ChromieCraft is 39).

**Comment by temperrr** [comment]
Tested it on AC with a level 39, 50+ spawns, all spawned guardians are skull level (57/58) @Eldarix 
I'll leave the decision to you.

**Comment by pop-pig** [comment]
I can confirm that on a local AC server, it is now lvl 57/58 as a lvl 38 character.
I guess we can close this? :)
