### ISSUE TITLE
[Eastern Plaguelands] Two close Dreamfoil nodes in Terrordale

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#801]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

In Terrordale in EPL, around coords 14.7 ; 28.3 , there are two very close dreamfoil nodes.
In the screenshot below, there are 3 object ids: 19536, 19537 & 19428.
![WoWScrnShot_060721_050119](https://user-images.githubusercontent.com/81818678/120956325-96bb4380-c753-11eb-82ce-1bb16d0703a5.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nodes should be further apart.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to coords 14.7 ; 28.3 in EPL, or ".go object 19536"

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Herb and Mine spawning are a known issue and they are working on a solution. I'll link this over to AC for reference

**Comment by heyitsbench** [comment]
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/fd7c8a0bde61508c8654c7be92c9fc2be65d2ac2.
