### ISSUE TITLE
[Tirisfal Glades] Two very close Earthroot nodes

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#802]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There are two very close Earthroot nodes in Tirisfal Glades, near coords 81.8 ; 56.9.
There are three nodes ids: 2014, 35473 & 32216.
Screenshot:
![WoWScrnShot_060721_120431](https://user-images.githubusercontent.com/81818678/121000486-912d2000-c78a-11eb-97cc-d1fa18606f92.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nodes should be further apart.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Tirisfal Glades, coords 81.8 ; 56.9 or ".go object 2014"

##### EXTRA NOTES:

I've check Alliance as I was playing a human character, but it's in the forsaken starting zone, so maybe I should have checked Horde? Feel free to edit and correct :)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Herb and Mine spawning are a known issue and they are working on a solution. I'll link this over to AC for reference.

**Comment by heyitsbench** [comment]
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/fd7c8a0bde61508c8654c7be92c9fc2be65d2ac2.
