### ISSUE TITLE
Deadmines party could not ressurrect after wipe

### ISSUE THREAD

**Issue by Jinteki01** [chromiecraft/chromiecraft#804]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There was only 3 of us left in Deadmines. We could not re-queue and we were no longer in the RDF system it seemed (no indicator on the minimap to teleport out). We wiped on Smite from him pulling the pirates on the platform (known bug). After running back as a ghost, we could not enter the instance or revive. The message "Map cannot be entered at this time." kept displaying. We each attempted a logout for 1 minute at least twice, but could still not enter the instance or revive outside the instance.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normally it should either let us in the instance to revive or revive us right outside the instance with the message saying we can't enter.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 1 person left while queued for RDF and in the instance.
2. The 3 of us left couldn't re-queue or teleport out of the instance.
3. Wiped on Smite.
4. Ghost ran back to enter instance.
5. Repeatedly got the message "Map cannot be entered at this time."
6. Logged out for a minute and tried to enter on re-log with the same result.
7. Repeated step 6.

##### EXTRA NOTES:

Not sure if it makes a difference, 2 of us were alliance and the 3rd was horde. Again we were no longer part of the RDF system (no queue or teleport), but still had the buff.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
Is this a case not yet covered by https://github.com/azerothcore/azerothcore-wotlk/pull/6106?

**Comment by necropola** [comment]
@r-o-b-o-t-o Seeing that you have confirmed the issue, shall I copy it to AC and link it?

**Comment by temperrr** [comment]
This should be fixed by the PR Necropola linked. If it is not the case, please make a new bug report!

**Comment by r-o-b-o-t-o** [comment]
> This should be fixed by the PR Necropola linked. If it is not the case, please make a new bug report!

If you are talking about https://github.com/azerothcore/azerothcore-wotlk/pull/6106, no it will not fix it, this is a different problem. Sorry necro, I forgot to answer you back then. The real issue is: when someone leaves the RDF group, and the group decides to search for another member to replace the one that left, if another member leaves during the search, it will "disband" the RDF group, which prevents remaining members from entering the instance again.

**Comment by temperrr** [comment]
@r-o-b-o-t-o 

Is there already an issue for such thing or should I make a report for that on AC?

**Comment by r-o-b-o-t-o** [comment]
I can't find anything for this on AC, you can go ahead 🙂
