### ISSUE TITLE
[Shaman] Auto attack stops once a totem expires/is destroyed.

### ISSUE THREAD

**Issue by Aragonath** [chromiecraft/chromiecraft#805]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Auto attack stops once a totem expires/is destroyed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thank you for the report. I'd like to help you, but can you provide any more information than "Auto attack stops once a totem expires/is destroyed"? Is it all or specific totems? PVE or PVP? What is expected blizzlike behavior? How do we reproduce the problem?

**Comment by Aragonath** [comment]
I checked with several shamans, they confirm the bug. I tested it and found that its on every totem, it happens when they expire or when they are destroyed in PvE and PvP. 
Also when you use totemic recall(however, when you use totemic recall when no totems are planted it DOES NOT stop auto attack). 
It should not stop auto attacking . 
Reproduce it by testing on dummy/mobs/players.

**Comment by Stump876** [comment]
Confirmed. Thanks for the report.

**Comment by Helias** [comment]
it should be fixed now or in the next update, if not, re-open or comment this issue
