### ISSUE TITLE
[Felwood] Winterfall Runner in Felpaw Village not attacking on sight

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#808]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

In Felpaw Village in northeastern Felwood, there is a Winterfall Runner ( https://wowgaming.altervista.org/aowow/?npc=10916 ) at coords 60.6 ; 5.5. He is not aggroing on sight and will not attack you unless you attack him.
DB GUID: 40473
Here is a video of me saying hi to a passive Winterfall Runner and then attacking him: https://youtu.be/AxwY5cUC3n4
![WoWScrnShot_060821_130051](https://user-images.githubusercontent.com/81818678/121176716-d4f05a00-c85c-11eb-862a-652bfe1d4316.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Winterfall Runner should aggro on sight.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Felpaw Village in Felwood, at coords 60.6 ; 5.5 (or ".go creature 40473" )

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Having a look in the DB, these guys are set to have a unit flag listed as Civilian: "not aggro (ignore faction/reputation hostility)" which explains this behaviour. They're possibly set this way as the other 3 of them (there's only 4 total spawned in the game world) patrol the road in Winterspring as quest targets, and maybe Blizz didn't want them rushing off the road and attacking things randomly and getting killed. 

Anyway, checking TBC Wowhead, it seems this behaviour is Blizzlike. One comment there says:
> Even through they show up as aggressive (red), they usually leave you alone unless you are at the end of their run in Winterfall Village or attack them first. (https://tbc.wowhead.com/npc=10916/winterfall-runner#comments:id=242380)

So on that basis, will close this as working as expected.
