### ISSUE TITLE
Lighting for some objects not disappearing after they are looted

### ISSUE THREAD

**Issue by eTzmNcbkrng** [chromiecraft/chromiecraft#81]
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
Two quests in Eversong Woods require the player to loot objects on the ground, when these objects are looted they disappear but their lighting effects remain visible.

Quest: [Corrupted Soil](https://www.wowhead.com/quest=8487)
GameObject: [Tainted Soil Sample](https://www.wowhead.com/object=180921)

Quest: [Unstable Mana Crystals](https://www.wowhead.com/quest=8463)
GameObject: [Unstable Mana Crystal Crate](https://www.wowhead.com/object=180600)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When the objects fade out after being looted, the lighting effects should also disappear

##### CURRENT BEHAVIOUR:
Looting and Unstable Mana Crystal or a Tainted Soil Sample causes the object to slowly fade out, but the lighting effect remains visible.

##### STEPS TO REPRODUCE THE PROBLEM:
Step 1 Pick up quest Corrupted Soil from [Apprentice Mirveda](https://www.wowhead.com/npc=15402/apprentice-mirveda)
Step 2 Loot a Corrupted Soil Sample
Step 3 Watch the object disappear but the green haze remains
OR
Step 1 Pickup quest Unstable Mana Crystals from [Aeldon Sunbrand](https://www.wowhead.com/npc=15403/aeldon-sunbrand)
Step 2 Loot an Unstable Mana Crystal Crate
Step 3 Watch the object disappear but the yellow haze remains

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f4e317f518fdc96b964ecd9b2f65cca9619577a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/107975462-6ee37c80-6fb8-11eb-9055-4bca67a77b06.png)
![image](https://user-images.githubusercontent.com/71938210/107976936-9fc4b100-6fba-11eb-9749-870fc51ae924.png)
Thats how it looks with a cleared cache and clean Client. You tell me if that's what you see, too and wheter it's blizzlike. :)

**Comment by Stifler82** [comment]
Yhea, Dude, that's normal, it's BlizzLike in this way..
It isn't a bug.
