### ISSUE TITLE
Contagion of Rot (spell=7102) stacks many times on me.

### ISSUE THREAD

**Issue by slightdilemma** [chromiecraft/chromiecraft#811]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I'm fighting ghouls named Fetid Corpse (npc=1270) in Duskwood and they put on you a disease called Contagion of Rot (spell=7102).

Contagion of Rot: Increases the time betwen an enemy's attacks by 33% and its casting by 25%, as well as adding 10% chance to spread the contagion to an ally when hit.

I did some tests fighting against them and apparently they can only put a disease on you or update the time of the disease BUT it seems that that 10% probability of spreading TO AN ALLY each time I hit also counts for oneself, because I have a stack of three diseases, and I do not think that should happen.

Screenshot: ![Contagion of Rot](https://user-images.githubusercontent.com/85563750/121192742-85fef080-c86d-11eb-93a5-073b18002e88.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I understand that the disease can spread to other allies, as expressly says, but not to stack over and over again on you.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

NPC: Fetid Corpse (npc=1270)
SPELL: Contagion of Rot (spell=7102)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. Typing `.npc info` in game will give a lot of info on the creature. Please make a note of the GUID (in this case 6077). 1270 indicated above directs me to a basilisk in Stranglethorn. Also steps to reproduce, while seemingly silly, do walk us through the process. I was able to get the Contagion of Rot, but I don't see clearly how to spread it to myself. 

After standing there for almost 5 minutes letting them hit on me and not doing anything. I never got a second stack. My current stack was always refreshed. Once I started attacking I was eventually able to get a second stack, and then a third. Looking at the debuff it seems like there are 2 different versions of the spell `Contagion of Rot` [https://www.wowhead.com/spell=7102/contagion-of-rot](https://www.wowhead.com/spell=7102/contagion-of-rot) which gives a -25% attack speed and 10% to spread, and [https://classic.wowhead.com/spell=7102/contagion-of-rot](https://classic.wowhead.com/spell=7102/contagion-of-rot) which says it's a -33% attack speed and 5% chance to spread, but mouseover effect 3 says 10%. I believe this is the one they cast. 
![image](https://user-images.githubusercontent.com/68164076/121285293-fbc98300-c892-11eb-81d8-98b0459697ed.png)
![image](https://user-images.githubusercontent.com/68164076/121285342-169bf780-c893-11eb-9574-9c9ecbe86f4e.png)
![image](https://user-images.githubusercontent.com/68164076/121285252-eb190d00-c892-11eb-94c6-9a8a2a019fd0.png)
I'm not entirely sure which one is correct. I'll leave that to the devs. The 5% one refreshes, the 10% one seems to stack. Regardless of which one is correct, I do not think they should stack. I am spreading it to myself during attacks. Tested by attacking a Spider.
![image](https://user-images.githubusercontent.com/68164076/121287622-be66f480-c896-11eb-8d51-b9db99389961.png)
