### ISSUE TITLE
[Wintersterspring] Wrong dialog for Malyfous Darkhammer

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#812]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

NPC Malyfous Darkhammer (DB GUID: 42207) in Everlook (coords 61.0 ; 38.7) has wrong dialog texts.
Here is a video: https://youtu.be/DLWDROvB_Xg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Correct dialog texts.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go chat with Malyfous Darkhammer (".go creature 42207")

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I can confirm he does this, but what is the correct dialog text / expected blizzlike behavior?

**Comment by pop-pig** [comment]
On wowpedia, there is an extract of the text: https://wowpedia.fandom.com/wiki/Malyfous_Darkhammer
See "Quotes"

**Comment by pop-pig** [comment]
Also, Malyfous's Catalogue, that's sitting on the barrel right next to him and the forge, is bugged too. All the dialog options are incorrect (all it says is "Greetings, <Playername>"). I think we can keep this in this issue?

**Comment by Stump876** [comment]
OK I see. So looks like his dialog text is correct. He just doesn't emote, or /say after clicking the final "OK" 

What is blizzlike behavior for the catalog?
