### ISSUE TITLE
Cracked Silithid Carapace does not drop

### ISSUE THREAD

**Issue by formiclol** [chromiecraft/chromiecraft#815]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

A quest start item [Cracked Silithid Carapace](https://wotlkdb.com/?item=5877) is supposed to drop from the Silithid mobs in southwest Shimmering Flats ([1](https://wotlkdb.com/?npc=4133), [2](https://wotlkdb.com/?npc=4131), [3](https://wotlkdb.com/?npc=4130), [4, rare](https://wotlkdb.com/?npc=4132)).  It is supposed to be a guaranteed drop for Horde players only.  I have done the quest [The Swarm Grows](https://wotlkdb.com/?quest=1147) on two characters and have not received the drop.  [Wowhead comments](https://classic.wowhead.com/item=5877/cracked-silithid-carapace#comments) suggests that players need to be on The Swarm Grows for the item to drop.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The item in question drops when players are on The Swarm Grows (3rd quest in chain).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be horde
2. Be on quest [The Swarm Grows](https://wotlkdb.com/?quest=1147)
3. Kill any of the required quest mobs (linked above)
4. [Cracked Silithid Carapace](https://wotlkdb.com/?item=5877) should drop on first kill, but doesn't

##### EXTRA NOTES:

Should be a 100% drop rate on first kill.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
It's not a 100% drop chance. According to `classic.wowhead.com` and `wowgaming.altervista.org` **Silithid Searchers (4130)**  have the highest drop chance of about 12%.

I did the quest myself on **ChromieCraft** a few days ago. The quest starter item dropped for me after killing a few more of the **Searchers** than needed for **The Swarm Grows**.  Closing as invalid.

**Comment by necropola** [comment]
I did some further research and it looks like the item should indeed drop at 100% from the first Silithid you kill while on the quest **The Swarm Grows (1147)**:

https://wowpedia.fandom.com/wiki/Cracked_Silithid_Carapace?oldid=2026412
> This item drops from Silithid Searchers, Silithid Hive Drones, and Silithid Invaders at the Rustmaul Digsite in the Shimmering Flats, Thousand Needles. If you are eligible for the drop, it will drop from the first Silithid you kill here.

https://www.wowhead.com/item=5877/cracked-silithid-carapace#comments:id=243225
> Actually, I think you need to have the "The Swarm Grows" quest to find this drop. I killed 100+ of them and didn't find any but as soon as I got the quest I found the drop. On the first kill.
