### ISSUE TITLE
[Winterspring] Spellmaw is static

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#817]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Spellmaw (DB GUID: 42265, https://wowgaming.altervista.org/aowow/?npc=10662 ) is currently static in his position in Mazthoril in Winterspring, around coords 58.7 ; 46.6.
![WoWScrnShot_060821_174305](https://user-images.githubusercontent.com/81818678/121226988-65de2a00-c88b-11eb-948e-49f3a8fc0a33.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be patrolling around:
- on https://tbc.wowhead.com/npc=10662/spellmaw , on the map you can see there are several locations (maybe they are "mob killed there" locations though)
- I found this video from WoW Classic (retail version): https://youtu.be/lO60l6tdTps . At the timestamp 39:04, you can see the player hovering his mouse over Spellmaw, and Spellmaw appears to be patrolling.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go see Spellmaw in Winterspring ( ".go creature 42265")

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. Confirmed. He's just chilling there. I don't think he paths, but at the very least he should wander a bit.
