### ISSUE TITLE
Entering Darnassus always pops mail notification without any mail in box

### ISSUE THREAD

**Issue by XionDemise** [chromiecraft/chromiecraft#818]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So it seems that whenever i port or enter darnassus it would always trigger my mail notification but nothing's ever in it when i go to check?

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No other major city does this and the mailbox notification should only indicate that there is mail in said mailbox

##### STEPS TO REPRODUCE THE PROBLEM:

1. take the port from stormwind to darnassus or enter through any entrance to darnassus
2. look towards the top right towards the mail notification
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I'm Sorry, I can't duplicate this on a local server. The portals are specific to Chromiecraft. But I still didn't see it on my alliance characters on Chromiecraft. Granted mine are a pretty low level. Do you happen to have a video or a couple screenshots, showing it? I'll leave this it open just in case anyone else has any input.

**Comment by Eldarix** [comment]
Same here.

**Comment by XionDemise** [comment]
![WoWScrnShot_060821_133808](https://user-images.githubusercontent.com/85085161/121346424-18e26e00-c8f4-11eb-8515-64fbaed8b92d.jpg)

**Comment by XionDemise** [comment]
as you can see it shows i have unread mail but it doesn't say from who and when i go to look its empty

**Comment by XionDemise** [comment]
https://youtu.be/68868GTyx0M

**Comment by Stump876** [comment]
That's perfect. I see you also have a mail add on. Can you try again, but this time disable all your addons, and see if it still happens?

**Comment by XionDemise** [comment]
yes ofc ill try today

**Comment by XionDemise** [comment]
![WoWScrnShot_061021_061534](https://user-images.githubusercontent.com/85085161/121508187-5823c400-c9b3-11eb-8f96-7768d8bd38ef.jpg)

it seems like the addons were to blame, I have tried multiple ways to recreate it and got nothing so far.
