### ISSUE TITLE
Pet Dash

### ISSUE THREAD

**Issue by Ashaemage** [chromiecraft/chromiecraft#820]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [✓ ] enUS
- [ ] other (specify)

##### FACTION

- [✓ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ✓] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here. The hunter pet ability Dash does not increase the pet's movement speed while out of comat, rather it only increases it's movement speed once it gets into combat.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here. Hunter pet Dash ability should increase the pet's movement speed regardless of it being in or out of combat.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here. Not sure if I filled out enough information, as I don't know hardly anything about coding. Sorry if there's a lack of information, seems to be a simple bug to me.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. However, there are a few things wrong with the report that not letting the bot to track and tag it. Check out the [readme](https://github.com/chromiecraft/chromiecraft/blob/main/README.md) and edit the post. Also, posting any screenshots, videos, links to spells, both of the bug and blizzlike behavior and any steps to reproduce the issues will speed up the triage process.

**Comment by formiclol** [comment]
Looks like this was recently fixed? 
[406](https://github.com/chromiecraft/chromiecraft/issues/406) and [5250](https://github.com/azerothcore/azerothcore-wotlk/issues/5250)

**Comment by Stump876** [comment]
Correct! We should be seeing it soon.
