### ISSUE TITLE
Tainted Ooze/Cursed Ooze drop empty tainted/cursed jars without quest

### ISSUE THREAD

**Issue by XionDemise** [chromiecraft/chromiecraft#821]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

It seems that these empty jars drop even though im only lvl 39 and can't possibly accept the quest associated with these items, The quest items themselves work and function as normal but i assume they aren't supposed to drop without the quest associated that being "A little slime goes a long way" other than that i can't find anything else but drop percentages? i could be wrong but im making it anyways. i didn't capture the cursed ooze jar but i can confirm its in the loot pool as i received one earlier and destroyed it.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Going off the classic quest they should be contained in a different item in the quest itself.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill multiple oozes and see that they drop in either tainted ooze in felwood
2. DB GUID:3955 Current GUID:10699
3. Position:5247.567383 -626.278625 326.328766
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by XionDemise** [comment]
![WoWScrnShot_060821_174306](https://user-images.githubusercontent.com/85085161/121263037-0d0a9380-c883-11eb-948a-4181a255d258.jpg)

**Comment by Stump876** [comment]
I'm sorry but I couldn't duplicate on my local server. First off GUID 3955 is a guard outside of Karazahn. Not a big deal. It was easy enough to see where you were. I think you were missing a number at the end 3955x 5, 6, 7 are all tainted oozes. I spent about 45 minutes killing oozes. I even had a `Wall of the Dead` drop, but I didn't get any jars. I see the screen shots, I just can't duplicate it. I'll leave this open for now in case anyone else has any input.

**Comment by Eldarix** [comment]
Me neither, just the typical grey trash:

![WoWScrnShot_060921_104039](https://user-images.githubusercontent.com/82579073/121313896-8354d780-c90f-11eb-8c9c-38f1e729e4e9.jpg)
![WoWScrnShot_060921_104211](https://user-images.githubusercontent.com/82579073/121313996-9f587900-c90f-11eb-97ff-199f9cba043b.jpg)

**Comment by Eldarix** [comment]
'Needs third opinion' :)

**Comment by Asthalor** [comment]
Should be closed
PR: https://github.com/azerothcore/azerothcore-wotlk/pull/6334
