### ISSUE TITLE
Lorgus Jett should not be a Rare spawn

### ISSUE THREAD

**Issue by eTzmNcbkrng** [chromiecraft/chromiecraft#823]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Lorgus Jett is currently a Rare spawn in Blackfathom Deeps.
https://wotlkdb.com/?npc=12902
According to Keira3 he has a 60% chance to despawn.
![image](https://user-images.githubusercontent.com/26512802/121327250-621fd580-c967-11eb-9f45-019f535ca06e.png)

Lorgus Jett has historically been assumed to be a rare spawn because he has 4 possible spawn points, two of which are off the main path so, on average, a player not specifically looking for him would have only seen him on 50% of their runs in Blackfathom Deeps.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Lorgus Jett should be present in 100% of Blackfathom Deeps runs.

##### SOURCE:

Personally saw him in 8/8 runs in BFD on WoW Classic, in various spawn points - screenshots in next post.
Historical information about this guy mentions that he has multiple spawn points, and nothing mentions he is a rare spawn.

- https://wowpedia.fandom.com/wiki/Lorgus_Jett?oldid=2297733
- https://classic.wowhead.com/quest=6565/allegiance-to-the-old-gods#comments

He is a required kill for a Horde Quest - [Allegiance to the Old Gods](https://classic.wowhead.com/quest=6565/allegiance-to-the-old-gods)
Some time between [4/Nov/2011](http://web.archive.org/web/20111104020715/http://www.wowhead.com/npc=12902) and [4/Dec/2011](http://web.archive.org/web/20111204190511/http://www.wowhead.com/npc=12902) he was changed from a standard Elite to a Rare Elite, [this was between patches 4.2 and 4.3 (Cataclysm).](https://wowpedia.fandom.com/wiki/Patch/4.x)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter Blackfathom Deeps
2. Try to find Lorgus Jett
3. 60% of dungeons he is not present
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment]
![WoWScrnShot_081820_225252](https://user-images.githubusercontent.com/26512802/121333275-c4c7a000-c96c-11eb-8ab5-159447454ddd.jpg)
![WoWScrnShot_082020_151923](https://user-images.githubusercontent.com/26512802/121333284-c6916380-c96c-11eb-811f-149e8356d7c7.jpg)
![WoWScrnShot_082120_151416](https://user-images.githubusercontent.com/26512802/121333288-c729fa00-c96c-11eb-8b0b-6d1e763cd564.jpg)
![WoWScrnShot_082120_230618](https://user-images.githubusercontent.com/26512802/121333290-c85b2700-c96c-11eb-8f18-3faba1a71287.jpg)
![WoWScrnShot_082220_223449](https://user-images.githubusercontent.com/26512802/121333294-c8f3bd80-c96c-11eb-849f-ac73bf6a0132.jpg)
![WoWScrnShot_082320_225258](https://user-images.githubusercontent.com/26512802/121333297-c98c5400-c96c-11eb-8fd7-ce7228c24f0b.jpg)
![WoWScrnShot_082520_004318](https://user-images.githubusercontent.com/26512802/121333298-cabd8100-c96c-11eb-9b03-d2843aef255f.jpg)
![WoWScrnShot_082520_144128](https://user-images.githubusercontent.com/26512802/121333301-cb561780-c96c-11eb-8c77-5b5e4a096a1e.jpg)

**Comment by necropola** [comment]
I agree 100%.
The simple fact he can also be the target of a quest ([Allegiance to the Old Gods](https://wowgaming.altervista.org/aowow/?quest=6565)) should be reason enough to not depawn him.
