### ISSUE TITLE
Disgusting Oozeling doesn't attack and eat other critters

### ISSUE THREAD

**Issue by XionDemise** [chromiecraft/chromiecraft#824]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So i put my disgusting oozeling near a critter in this case a rabbit and doesn't immediately aggro and devour it or kill it, But i get nothing my oozeling just stays there looking at the rabbit without killing intent.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Aggro onto all critters and kills them.

##### STEPS TO REPRODUCE THE PROBLEM:

1. somehow get the pet to drop or use a GM command to put it in your bag
2. Witness it not do anything at all near a critter
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by XionDemise** [comment]
![WoWScrnShot_060921_072547](https://user-images.githubusercontent.com/85085161/121347017-be95dd00-c8f4-11eb-81ee-d7abb56cdba0.jpg)

**Comment by Azcobu** [comment]
Thanks for the report.The critter-eating pet is the Toxic Wasteling. The Disgusting Oozeling (DO) turns you green and debuffs your defense and resistances, the TW eats critters.

https://wowpedia.fandom.com/wiki/Disgusting_Oozeling?oldid=2028212
https://wowpedia.fandom.com/wiki/Toxic_Wasteling?oldid=2196067
