### ISSUE TITLE
[Warrior] Talent "Improved Disciplines", and the "12 seconds cooldown on the 3 spells"

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#826]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

It seems like having specced "Improved Disciplines" (I have 2/2, maybe 1/2 also does it?) makes that using one of the three spells "Retaliation", "Shield Wall" or "Recklessness" does not trigger the "display" of the 12 seconds cooldown so that you can't have two or more of those spells active on you at the same time.
Nonetheless, you still can't stack these spells.
Here is a video, also showing that you can't stack the spells: https://youtu.be/0ZawfOiAV30

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The "12 seconds cooldown" should start on the other spells and be displayed in tooltip.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Spec Improved Disciplines 2/2
2. Use Retaliation
3. Hover over "Shield Wall" ability to see tooltip without the 12 seconds cooldown

##### EXTRA NOTES:

Maybe it is a client side issue, so can't be fixed? I'm not sure so I felt like I should still report it.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I'm not sure if i'm understanding correctly, but the 12 sec. are duration:

![WoWScrnShot_061721_061217](https://user-images.githubusercontent.com/82579073/122325438-42724980-cf33-11eb-9799-c23a2e80b893.jpg)

And here's the tooltips of the modified cooldowns:

![WoWScrnShot_061721_061018](https://user-images.githubusercontent.com/82579073/122325510-66ce2600-cf33-11eb-959c-68b863b2dc24.jpg)
![WoWScrnShot_061721_061209](https://user-images.githubusercontent.com/82579073/122325535-73527e80-cf33-11eb-8360-e60bd8617d03.jpg)

**Comment by pop-pig** [comment]
I've resetted my talent points, here is the "12 seconds cooldown" I'm talking about:
![12s](https://user-images.githubusercontent.com/81818678/122333786-f0342700-cf38-11eb-8a0f-28a275550dc0.jpg)

**Comment by Eldarix** [comment]
I see, i'm going to check it again so ;) thanks mate

**Comment by Eldarix** [comment]
Follow your ''steps to reproduce the problem'' and still can't see that:

![WoWScrnShot_061721_123307](https://user-images.githubusercontent.com/82579073/122372685-8bdd8b80-cf69-11eb-804f-d5e9a1613b15.jpg)
![WoWScrnShot_061721_123317](https://user-images.githubusercontent.com/82579073/122372744-9a2ba780-cf69-11eb-8824-9aa08c7c7e52.jpg)

Waiting for a second opinion, take care pal ;)

**Comment by pop-pig** [comment]
Sorry maybe my issue was not clear. I'll try to explain it again:

WITHOUT Improved disciplines:
When you use one of the 3 spells, it triggers a 12 seconds cooldown on the tooltip to prevent you from using multiples spells at the same time. Currently, without the talent, the 12 seconds cooldown is correctly displayed on the tooltip of the other spells, when one is being used (see my previous screenshot in comments).

WITH Improved disciplines:
When you use one of the 3 spells, you cannot use another one for 12 seconds (so NO BUG here, it is the expected behaviour), BUT it is not displayed on the tooltip of the other spells that you have to wait 12 seconds (see the video I recorded in my original issue post).

The issue is that the "12 seconds cooldown" is not displayed on the tool tip when Improved disciplines has been spec'd.

**Comment by Eldarix** [comment]
Now i totally understood, thanks for the clarification, going to test it again :)

**Comment by tabakisp** [comment]
> Video 2, WITH Improved Disciplines: https://youtu.be/yboMy9fgCfE
> There is no cooldown displayed when using Shield Wall.

@pop-pig Are you sure the cd is not shown because it requires Battle Stance and you go from Defensive to Berserker Stance which is unusable?

**Comment by pop-pig** [comment]
> 
> 
> > Video 2, WITH Improved Disciplines: https://youtu.be/yboMy9fgCfE
> > There is no cooldown displayed when using Shield Wall.
> 
> @pop-pig Are you sure the cd is not shown because it requires Battle Stance and you go from Defensive to Berserker Stance which is unusable?

Yes, see the video from my original post where I switch to battle stance: https://youtu.be/0ZawfOiAV30
