### ISSUE TITLE
Quest dialogue fails to close when finishing quest with just the right amount of bag slots free

### ISSUE THREAD

**Issue by rdallastra** [chromiecraft/chromiecraft#827]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When delivering a quest (for instance, when completing [Wild Hearts](https://wowgaming.altervista.org/aowow/?quest=429) I had just 2 slots open in my bag, just enough for the quest rewards. I received the rewards but the quest dialogue failed to close (as if I had trouble finishing the quest). After I close the dialogue by clicking the quest X button, the next quest is available, meaning the game recognizes the previous quest was successfuly finished.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When finishing a quest with enough empty slots in the character bag for the rewards to be collected, end the quest successfuly.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Rane Yorick in Silverpine Forest
2. Start the quest Wild Hearts
3. Collect the Discolored Vorg Hearts
4. Deliver the quest to  Apothecary Renferrel with just 2 free slots in your bag

##### EXTRA NOTES:

The quest mentioned is [Wild Hearts](https://wowgaming.altervista.org/aowow/?quest=429)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Thx for the report pal, take care ;)
