### ISSUE TITLE
[NPC not moving] Lizzarik and Jorb

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#839]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Sometimes both Lizzarik and Jorb seem to be stuck. They stop moving for a few minutes and then continue on their path.

![WoWScrnShot_061021_222314](https://user-images.githubusercontent.com/84775498/121662161-4b7f9880-caa5-11eb-8802-1c13ed9520cd.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They shouldn't stop for no reason.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Barrens
2. Find Lizzarik and Jorb
3. Watch them for some time

##### EXTRA NOTES:

Lizzarik: https://classic.wowhead.com/npc=3658/lizzarik#comments
Jorb: https://classic.wowhead.com/npc=3659/jorb#comments

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
This happens when a player interacts with a creature that is following a set path. The creature stops when interacted with and their companions keep moving until the next waypoint and stop there. They wait for a couple minutes and then continue on their path. 

If this behavior is wrong then please let me know (preferably provide sources too). I can't check on blizz servers myself and found nothing useful on youtube.

**Comment by Avyxis17** [comment]
That I understand, however I didn't interact with them. This is how I found them. I suppose it is possible that someone before me did interact with them. Maybe it would be wise to follow them to see if it truly was the above mentioned case or not.

**Comment by anguaive** [comment]
> I suppose it is possible that someone before me did interact with them.

I'm 100% certain this is what happened. Their waypoint data is correct (I know because I ported it from TC and I tested it thoroughly). They patrol between their outposts in Ratchet and The Crossroads without interruption and hang around for 30 minutes (if I recall correctly) at each outpost.
