### ISSUE TITLE
[Glyphs] Incorrect Spell Tooltip for Cleave after applying Glyph of Cleaving

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#840]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After applying Glyph of Cleaving, the tooltip for spell Cleave doesn't reflect the changes made by the glyph. Glyph of Cleaving increases the number of targets that the Cleave hits by 1. While the ability works as intended and Cleave does indeed hit 3 targets, the tooltip for the spell stays unchanged. 

![WoWScrnShot_061121_102807](https://user-images.githubusercontent.com/84775498/121667103-3ce7b000-caaa-11eb-8af0-e4528afb04db.jpg)
![WoWScrnShot_061121_102815](https://user-images.githubusercontent.com/84775498/121667109-3eb17380-caaa-11eb-9652-84e3d7631b02.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After applying Glyph of Cleaving, the tooltip for spell Cleave should say the following: A sweeping attack that does your weapon damage plus X to the target and his two nearest allies.

##### STEPS TO REPRODUCE THE PROBLEM:

1. As a warrior, apply Glyph of Cleaving
2. Check the tooltip for the Cleave

##### EXTRA NOTES:

Glyph of Cleaving: https://wowgaming.altervista.org/aowow/?item=43414
Cleave: https://wowgaming.altervista.org/aowow/?spell=845#modified-by

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
This is a client side issue, many talents / glyphs that improve your skills are not displayed correctly.
For instance there's also this issue that was closed: #546 
There is no way around this :(

**Comment by pop-pig** [comment]
Oh really? Oh didn't know, then maybe it's not client side :D

**Comment by Avyxis17** [comment]
Yeah that's why I noticed it in the first place.

**Comment by Avyxis17** [comment]
I quickly logged on Warmane now and it indeed works. See for yourself:

![WoWScrnShot_061121_122715](https://user-images.githubusercontent.com/84775498/121672825-8affb200-cab0-11eb-82f7-e4f29e5b7bc9.jpg)
![WoWScrnShot_061121_122723](https://user-images.githubusercontent.com/84775498/121672829-8cc97580-cab0-11eb-989e-96fd1e70fa2b.jpg)

**Comment by Eldarix** [comment]
Thx for the report mate, btw, what texture mod do you use ? doesnt seems the same as the imported from retail, enjoy ;)

**Comment by Avyxis17** [comment]
I got it from Warmane forums some time ago. I am not really sure which one but I think it was this one: https://forum.warmane.com/showthread.php?t=433477

**Comment by Eldarix** [comment]
> 
> 
> I got it from Warmane forums some time ago. I am not really sure which one but I think it was this one: https://forum.warmane.com/showthread.php?t=433477

thx for sharing it, i just downloaded it and i must say it's an impressive work, don't know who made it but i'm pretty sure that the textures are not the same ones from retail, looks impressive

**Comment by Eldarix** [comment]
Retail:

![WoWScrnShot_061321_104543](https://user-images.githubusercontent.com/82579073/121799445-d511a080-cc34-11eb-808c-d5baeccde8eb.jpg)

3.3.5 mod:

![WoWScrnShot_061321_104613](https://user-images.githubusercontent.com/82579073/121799461-ee1a5180-cc34-11eb-9726-6b49ecca1de5.jpg)

**Comment by Eldarix** [comment]
And the revamp of stormwind looks great as well:

3.3.5 mod:

![WoWScrnShot_061321_102926](https://user-images.githubusercontent.com/82579073/121799568-887a9500-cc35-11eb-82cf-1a1d5cbf6a7c.jpg)

retail:

![WoWScrnShot_061321_105141](https://user-images.githubusercontent.com/82579073/121799590-ae079e80-cc35-11eb-8d1f-aa6a4313132f.jpg)
