### ISSUE TITLE
Lesser Heal cooldown

### ISSUE THREAD

**Issue by airness456** [chromiecraft/chromiecraft#845]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Everytime you use an item with a cooldown such as [Crystalized Mana Residue](https://wowgaming.altervista.org/aowow?item=23354) or [Cracked Power Core](https://wowgaming.altervista.org/aowow/?item=23334), the spell Lesser Heal (Rank 2) is not usable and it says: "Spell not ready to use yet".

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Obviously no item should trigger a cooldown on a spell like Lesser Heal.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use Lesser Heal (Rank 2) - it works.
2. Use Crystalized Mana Residue - now Lesser Heal (Rank 2) cannot be used.
3. Once Crystalized Mana Residue is off cooldown, you can now use Lesser Heal (Rank 2)

##### EXTRA NOTES:

Only affects Lesser Heal (Rank 2) and no other ranks.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. Thanks for the report. Lesser heal 2 does appear to share the cool down on Crystalized Mana Residue and Cracked Power Core

**Comment by necropola** [comment]
Related to
- PR https://github.com/azerothcore/azerothcore-wotlk/pull/6191
- AC issue https://github.com/azerothcore/azerothcore-wotlk/issues/5475,
- CC issue https://github.com/chromiecraft/chromiecraft/issues/466
