### ISSUE TITLE
Hints of a New Plague? part 3 (the elf you have to protect is not waiting for you ) 

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#846]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

On 3 occasions I was left alone against the orcs while she continued her slow walk, luckily I completed the mission despite this, but it should not be like that, since an extra difficulty is added not necessary for the mission itself.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As in all escort missions, when you go into battle, the npc in question must fight as well.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get the 3rd part of the quest chain 'Hints of a New Plague?'
2. Proceed normally next to the elf 
3. See if she goes into battle with all the orcs that attack you or laughs at your face and continues on her way :)

##### EXTRA NOTES:

Here is a video of how it should be:

https://www.youtube.com/watch?v=3sKVUdK4OfM

And here an old link to wowhead:

https://classic.wowhead.com/quest=657/hints-of-a-new-plague#comments

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Windows 10 20H2

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Need a GUID, an area, or a name, Eldarix!  /bonk 🤭

GUID 14653 The quest is an escort in Arathi so I would suggest .questadd 657 and hand that in manually so you're not taken by suprise starting the escort in question. (quest 660)

I can confirm her behavior. She does indeed laugh at my face and continue on her way. I have that effect on women. Pretty much if I aggro, she ignores the mob(s), if she aggros she will fight. I believe she should assist the player.   

![image](https://user-images.githubusercontent.com/68164076/121791492-135c8080-cb9f-11eb-9518-2d842a496483.png)

**Comment by Eldarix** [comment]
Thx mate !! in relation to the GUID thing, sorry but didnt think about it at all :D i guess that i'm more classical and whenever i can run away of numbers i do it !!

I also took it for granted that whoever wants to test it will have plenty of tools to do 'lookup quest' and 'quest add' from the title itself :)

She fights when she aggroed indeed, the problem is when she does not and you are still fighting the previous ones like in your screenshot.

Regarding the issue of women, I don't know how old you are, but I used to suffer from the same :D and that changed at some point hehe, now I don't care, just this month I'll be 10 years together with my beloved, maybe it's simply that you haven't yet crossed your chosen one, don't lose hope :P

**Comment by Stump876** [comment]
Congrats, married 16 years with 2 kids myself. What I typically will do is check a supposed bug on my local server beforehand. So, I'll end up with all that information anyway, and it would be just tabbing over to see the numbers. Not a big deal but it definitely makes it easier for another triage person to verify.

**Comment by Eldarix** [comment]
So, are you telling me seriously that no one is going to put in at AC if the 'guid' is lacking? xDD

**Comment by damnablebear** [comment]
Tested today on the PTR. If I aggro an enemy and pull it toward Kinelory, she'll run toward me and help me attack, from a fair distance away.

**Comment by elthehablo** [comment]
> Tested today on the PTR. If I aggro an enemy and pull it toward Kinelory, she'll run toward me and help me attack, from a fair distance away.

Lemme verify this in the db tomorrow

**Comment by elthehablo** [comment]
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/80e15612-ff2e-4804-9219-6c98ca17fdab)
reactstate defensive on wp so looks good to me
