### ISSUE TITLE
Matis the Cruel does not gain aggro when attacked.

### ISSUE THREAD

**Issue by Joy-ccraft** [chromiecraft/chromiecraft#847]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Matis the Cruel did not gain aggro when attacked. Instead he ignored me, then paused and remained idle.

NB  I had already completed the quest 'Matis the Cruel', and did not test when the quest is undone or active.

![Screenshot from 2021-06-11 22-22-40 copy](https://user-images.githubusercontent.com/85800188/121782411-a00c3c00-cba9-11eb-87af-55e635a958e2.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mob should gain aggro and not allow me to pelt him with frost bolts.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Completed quest Matis the Cruel.
2. Attacked Matis the Cruel for sport.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. I'm sorry to say I could not duplicate this.  I did it as horde first not thinking, then as alliance both with and without the quest. He was hostile and ran at me each time. 
![image](https://user-images.githubusercontent.com/68164076/121786706-84d40900-cb76-11eb-89a9-f6dd9ed69149.png)
![image](https://user-images.githubusercontent.com/68164076/121786723-9a493300-cb76-11eb-8dec-248679e90b9d.png)
Typing .NPC info with the mob targeted will give you information on the mob. What really helps us is the GUID So we can port right to the mob in question. GUID for this mob is 63387 He does pat on the road. His pathing is a little wonky, I think he might be letting the horse drive.
