### ISSUE TITLE
[Quest] Ending the Bloodcurse: possible to destroy the Statue of Queen Azshara multiple times.

### ISSUE THREAD

**Issue by Joy-ccraft** [chromiecraft/chromiecraft#848]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Statue of Queen Azshara can be destroyed multiple times when doing the quest 'Ending the Bloodcurse'. 
Each occurrence will spawn another Atoph the Bloodcursed.
All Atoph the Bloodcursed will stand idle behind the statue until one is attacked.

![Screenshot from 2021-06-11 21-40-16 copy](https://user-images.githubusercontent.com/85800188/121782708-3b51e100-cbab-11eb-8a5d-c5726352efad.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should only be possible to destroy the statue a single time, spawning only a single Atoph the Bloodcursed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept the quest Ending the Bloodcurse.
2. Click the  Statue of Queen Azshara multiple times.
3. Attack one of the spawned Atoph the Bloodcursed.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I confirmed it does this, and agree he should not spawn more than one at a time. However, I do not believe the blizzlike behavior you wrote is entirely correct. What happens if he kills me and despawns? Or someone tags my spawn. I just wasted my one chance to summon him. I found someone doing the quest [here](https://youtu.be/pWmAazW3ULo?t=159) that shows how it should work.  Thank you for the report! Going forward when reporting bugs, if possible, check to see if the bug is repeatable and find a source to verify how it should act.

**Comment by Joy-ccraft** [comment]
Judging by the video (and my common sense), this is how I would expect the quest to work:

1. Accept the quest.
2. Click the statue; it catches fire and NPC spawns behind the player, already tagged and hostile to the player. 
It is not possible to click the statue again while the NPC is spawned.
4. If the player is killed, the NPC will remain until the despawn timer kicks in. At this point I see two possibilities:

  a)  If possible, the player is able to return and click the statue anew, or- 
  b)  the player must abandon the quest and accept it again.


The choice of either option likely depends on what is technically possible with the wotlk mechanics, of which I am entirely ignorant. I've played Vanilla for a year and, by that standard, would expect option b).

Thanks for your patience with my mediocre bug reporting, I'm new at this. :)

**Comment by Stump876** [comment]
No problem🙂 I hope you keep reporting bugs. It's a good report. Your filled everything out and did it correct, which seems silly, but you'd be surprised how often people don't. You were just missing a little bit of important info. I believe your observations are correct, it's definitely wrong. But we not only need to show it's wrong, but we need show how it should work properly. That's usually the harder part, and devs like evidence over assumptions and memory.
