### ISSUE TITLE
Argent Guard Thaelrid from Blackfathom Deeps dungeon does not have the quest available 

### ISSUE THREAD

**Issue by mturca** [chromiecraft/chromiecraft#85]
##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
Argent Guard Thaelrid from Blackfathom Deeps dungeon does not have the quest available for alliance players (didn't checked for horde)

Quest: [Blackfathom Villainy](https://classic.wowhead.com/quest=1200/blackfathom-villainy) 
NPC_Start: [Name Argent Guard Thaelrid](https://classic.wowhead.com/npc=4787/argent-guard-thaelrid#starts) 
NPC_End: [Name Dawnwatcher Selgorm](https://classic.wowhead.com/npc=4783/dawnwatcher-selgorm) 

[Blackfathom Deeps](https://classic.wowhead.com/blackfathom-deeps)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
He should have a quest available...

##### CURRENT BEHAVIOUR:
Not having any quest available when you approach him 

Quest: [Blackfathom Villainy](https://classic.wowhead.com/quest=1200/blackfathom-villainy) 
NPC_Start: [Name Argent Guard Thaelrid](https://classic.wowhead.com/npc=4787/argent-guard-thaelrid#starts) 
NPC_End: [Name Dawnwatcher Selgorm](https://classic.wowhead.com/npc=4783/dawnwatcher-selgorm) 

[Blackfathom Deeps](https://classic.wowhead.com/blackfathom-deeps)

##### STEPS TO REPRODUCE THE PROBLEM:
Enter Blackfathom Deeps via RDF 
Reach Argent Guard Thaelrid location - underwater cave after the first boss
There isn't any quest available from the NPC

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f4e317f518fdc96b964ecd9b2f65cca9619577a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
Classic wowhead is not a fully trusted source, because a lot of content was revamped, this quest for WotLK needs level 20 https://wow.gamepedia.com/Blackfathom_Villainy_(quest).

**Comment by bonfax4** [comment]
Every wotlk database shows lvl 18 min and only cata databases are showing 20 as minimum. This should be reconsidered

**Comment by mturca** [comment]
> Classic wowhead is not a fully trusted source, because a lot of content was revamped, this quest for WotLK needs level 20 https://wow.gamepedia.com/Blackfathom_Villainy_(quest).

@nicoaravena - as the horde side are able to get the quest at lvl 18 would it be possible to let me know if the issue can be reopened ?

**Comment by nicoaravena** [comment]
There is no problem, as you can see [horde side of the quest](https://wow.gamepedia.com/Blackfathom_Villainy_(Horde)) requires level 18, and alliance side [requires level 20](https://wow.gamepedia.com/Blackfathom_Villainy_(quest))

**Comment by locus313** [comment]
@nicoaravena i also checked several wotlk databases and it does look like it should be level 18 for the alliance side as well. Here is one example:
https://wowgaming.altervista.org/aowow/?quest=1200

**Comment by bonfax4** [comment]
DB links show this quest should be shareable (no prereq).
Did you guys try to do the other quest linked to that npc from Darnassus first ? Maybe they are wrongfully linked. 

https://wowgaming.altervista.org/aowow/?quest=1198

**Comment by nicoaravena** [comment]
> Edit : Here's a wowhead link before the quest got revamped to be an alliance only quest in cataclysm.
> https://web.archive.org/web/20100802000856/https://wowhead.com/quest=1200/blackfathom-villainy

Nice catch, thanks.

**Comment by nicoaravena** [comment]
Sorry, this should not be reopen, for the alliance side of the quest you need to finish this https://classic.wowhead.com/quest=1198/in-search-of-thaelrid first.
