### ISSUE TITLE
Arathi Highlands: Summoning the Princess - No summon 

### ISSUE THREAD

**Issue by Jinmcx** [chromiecraft/chromiecraft#853]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Used the scroll to summon the princess and no princess appears.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Princess should be summoned.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Gather scroll to summon princess, use scroll, no summon.
2. 
3. 
4.

##### EXTRA NOTES:
 The princess did summon after the 3rd attempt but it requires traveling to another zone to abandon quest and retry.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Just tried this quest 3 times on 3 different characters, and had no problems on any of them, she was summoned first time on all of them. I wondered if other previous summons might cause problems (so if someone summoned her a few minutes ago it might not work for you), but my characters were able to summon her even with her body from the last summons still visible. So the quest isn't affected by other people doing it before you.

Did you get an error message or anything in the combat log telling you what was wrong when you tried the first few times?

**Comment by Jinmcx** [comment]
I did not the scroll just disappear.
