### ISSUE TITLE
Warlock Imp Minion extra Stamina Value too High

### ISSUE THREAD

**Issue by temperrr** [chromiecraft/chromiecraft#854]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Stamina extra value is too high. It should in my case only get +6 stamina, but pet gets +16 stamina from caster stats. See screenshot for details

![image](https://user-images.githubusercontent.com/20357406/121798970-b3f78280-cc29-11eb-929d-7a09a8875885.png)
![image](https://user-images.githubusercontent.com/20357406/121798976-bb1e9080-cc29-11eb-9baf-f7f97691edd8.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Minion should only be getting the extra stats based on buffs or warlock caster stats. It seems it gets too much.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Level 3 Human warlock
2.  Summon Imp
3. Check statmina stats. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
https://wowpedia.fandom.com/wiki/Warlock_minion?oldid=2478495#Minion_scaling
![image](https://user-images.githubusercontent.com/7461137/121800443-33894f80-cc32-11eb-9145-36bf4032cf70.png)
