### ISSUE TITLE
Quest: The Corruptor (Part 3) Missing Roleplay

### ISSUE THREAD

**Issue by Nargemn** [chromiecraft/chromiecraft#856]
<!Quest: The Corruptor (Part 3) missing roleplay>

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After turning in the quest The Corruptor (Part 3) to Maurin Bonesplitter at Ghost Walker Post in Desolace, where you gather an Oracle Crystal from naga in Desolace, there is supposed to be a short roleplaying event.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After completing the quest, there should be a short roleplaying encounter where images of the orc warlock Jug'kar Grimrod and his master Lord Azrethoc appear and speak a few lines of dialogue. The full encounter is recorded here (https://wowpedia.fandom.com/wiki/The_Corrupter_(3))

##### STEPS TO REPRODUCE THE PROBLEM:

1. DB GUID: 29068
2. Faction. 68.
3. npcFlags: 2.
4. Entry: 4498

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by VFaleiro** [comment]
If anyone needs, [here is a video of the event](https://www.youtube.com/watch?v=d2Q5VBeXxb0&t=276s) (it begins at 4:36).
