### ISSUE TITLE
loot mancante

### ISSUE THREAD

**Issue by pippocadoni** [chromiecraft/chromiecraft#857]
#### WHAT CLIENT DO YOU PLAY ON?

- [x ] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The quest Zanzi'l Secret, (621), requires 12 quest items Zanzil's Mixture, I looted so far 10 quest items and now it's more than 3 days that I can't loot them anymore.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?npc=1488#drops .

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
@pippocadoni you can't write a report in italian, I translated this report (and shorted it a bit) but next time you have to write it in english or we have to close the report.

You can even use GoogleTranslator :wink:

**Comment by Azcobu** [comment]
Thanks for the report. When you say you cannot loot the quest items anymore, is there an error message of some kind? Or are the items not dropping for you?

Checking the database shows the quest items are set to drop with a 33% chance from NPCs in the area, which is correct. I also just ran through the quest on my test server and had no problems:

![WoWScrnShot_061421_132553](https://user-images.githubusercontent.com/81782124/121837255-483e1400-cd14-11eb-92da-5b906037b37f.jpg)

So I think we will need more details about what exactly is going wrong for you before we can help. A screenshot of any error message you get would also be useful.

**Comment by pippocadoni** [comment]
well I'll be back on the spot and I'll let you know in more details. Thank you for your kindness
Inviato da Yahoo Mail su Android 
 
  Il lun, 14 giu, 2021 alle 6:01, ***@***.***> ha scritto:   


Thanks for the report. When you say you cannot loot the quest items anymore, is there an error message of some kind? Or are the items not dropping for you?

Checking the database shows the quest items are set to drop with a 33% chance from NPCs in the area, which is correct. I also just ran through the quest on my test server and had no problems:



So I think we will need more details about what exactly is going wrong for you before we can help. A screenshot of any error message you get would also be useful.
