### ISSUE TITLE
Pygmy Tide Crawler doesn't interact correctly with terrain.

### ISSUE THREAD

**Issue by Joy-ccraft** [chromiecraft/chromiecraft#863]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
NPC DB GUID 38518 moves erratically, seems to fall up and down along the slope and sometimes clips through the terrain.

![Screenshot from 2021-06-14 20-27-45 copy](https://user-images.githubusercontent.com/85800188/121943923-5c086b00-cd52-11eb-97c7-f9a38a086d4f.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
NPC should move as its fellow crawlers and not pass through the world terrain.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Observe NPC DB GUID 38518 move through its patrol pattern. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Can't confirm it, notice some up and down weirdness but not the passing through the world terrain:

![WoWScrnShot_061521_023159](https://user-images.githubusercontent.com/82579073/121971845-617da980-cd82-11eb-92ae-daeb9a75ef34.jpg)
![WoWScrnShot_061521_023326](https://user-images.githubusercontent.com/82579073/121971860-6c383e80-cd82-11eb-8671-b6be2f5ff350.jpg)

**Comment by Eldarix** [comment]
Thx for the report likewise pal ;)

**Comment by temperrr** [comment]
Confirmed, he is wandering through the hill!

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9272
