### ISSUE TITLE
Racial languages not working

### ISSUE THREAD

**Issue by sparklynoe** [chromiecraft/chromiecraft#866]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
Selecting a different language via the bubble at the left of the chat doesn't change the language your character speaks.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Clicking on a different language should change the language your character speaks.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Change character's language
2. Speak on /say
3. Your character speaks common/orcish instead of the selected language.

##### EXTRA NOTES:
Tested only with night elf, dwarf, draenei, tauren. Appears to be a bug on all races.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, wasn't able to reporoduce this on an AC server. Tested with tauren, undead, troll, blood elf, dwarf, night elf and draenei, and didn't run into any problems:

Tauren:
![WoWScrnShot_061621_002746](https://user-images.githubusercontent.com/81782124/122077896-4f137680-ce3b-11eb-9b39-0d5720c45f07.jpg)

Troll:
![WoWScrnShot_061621_002744](https://user-images.githubusercontent.com/81782124/122077966-5cc8fc00-ce3b-11eb-988e-9273aa867568.jpg)

Undead:
![WoWScrnShot_061621_002838](https://user-images.githubusercontent.com/81782124/122077903-5044a380-ce3b-11eb-8c5c-c1ff8c2f2308.jpg)

Blood elf:
![WoWScrnShot_061621_003530](https://user-images.githubusercontent.com/81782124/122077962-5cc8fc00-ce3b-11eb-84c1-8a4ec4f8e586.jpg)

Dwarf and Draenei
![WoWScrnShot_061621_003414](https://user-images.githubusercontent.com/81782124/122077907-50dd3a00-ce3b-11eb-8060-212c04e9054c.jpg)

Night elf:
![WoWScrnShot_061621_003311](https://user-images.githubusercontent.com/81782124/122077959-5c306580-ce3b-11eb-9633-5b0bf4b0af0c.jpg)

However, it's probable that ChromieCraft, which is running some mods to enable cross-faction play in BGs and dungeons, might be behaving differently to my vanilla AC setup. I'll try to find out more.

**Comment by Shineslippers** [comment]
>Selecting a different language via the bubble at the left of the chat doesn't change the language your character speaks.

Did some tests and nothing. Need to mention. Change of language doesn't do anything to speaking person. Only add `language` tag. Difference can see other players if they don't know this language.
