### ISSUE TITLE
[Shaman] Far Sight will not return you to your character after the channeling ends

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#870]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There seems to be an issue with Far Sight when using it to "very far away" locations. If you don't "right click the buff" or do an action to get back to your character before the 1 min mark ends, your camera stays to where you previously used Far Sight. An action after that will not switch the camera back to your character, but using Far Sight again and "right clicking the buff" will teleport the camera to your character.
Here is a video without the bug, using Far Sight to a "close" location: https://youtu.be/4mMG7Zl8wG8
Here is a video of the bug, using Far Sight to a "very far away" location: https://youtu.be/jj3B8W1mW5o

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Far Sight should teleport your camera back to your character after it ends.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use Far Sight on a very far location (maybe so far away that your character is not rendered?)
2. Wait 1 min

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. Thanks for the report.
