### ISSUE TITLE
[Shaman] Far Sight will reset camera to character between "jumps" when casting

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#871]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If you cast Far Sight, and from that location, cast another Far Sight, the camera will be back at your character so you can see yourself casting Far Sight.
Here is a video: 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Casting Far Sight while you're looking far away should not reset the camera.

##### SOURCE:

Here is a video from classic WoW (retail): https://youtu.be/CTnTtXcqTHU
Or another one: https://youtu.be/py2SjorgEaM

##### STEPS TO REPRODUCE THE PROBLEM:

1. Cast Far Sight to a location A
2. Within 1 min, cast another Far Sight from location A
3. Watch your camera being reset to your character, while it should stay at location A

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Confirmed. I'm going to combine with [this issue](https://github.com/chromiecraft/chromiecraft/issues/870) and call it "Far Sight not working properly"
