### ISSUE TITLE
you can reset the cooldown of any item with just a relog

### ISSUE THREAD

**Issue by tbcxd** [chromiecraft/chromiecraft#875]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So after relogging to disable an addon, I noticed something very interesting:

Placing an item in your bag then back on your character and relogging, resets the cooldown of ANY ITEM.
This can cause a lot of abuse by resetting the cooldown of very strong items in just 20 seconds.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

the cooldown shouldn't reset by doing what I described above

##### STEPS TO REPRODUCE THE PROBLEM:

1. place an item that is currently on cooldown in your bags and back on your character
2. relog
3. the cooldown of that item is reset.
4.

##### EXTRA NOTES:

![Screenshot_11](https://user-images.githubusercontent.com/85901661/122121880-cbef2200-ce34-11eb-9b8c-5a1fca3fbb9d.png)
![Screenshot_12](https://user-images.githubusercontent.com/85901661/122121928-d90c1100-ce34-11eb-9d07-696815cc6698.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I want to say this was a known issue. I tested this on a weapon a few weeks ago, but I can't find it in AC anywhere so maybe it was overlooked. I can confirm it. So I'll link it now
