### ISSUE TITLE
charge animation not working when charging on Searing Lava Spider on Searing Gorge

### ISSUE THREAD

**Issue by Scapulla** [chromiecraft/chromiecraft#877]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When charging Searing Lava Spiders, sometimes the charge animation will cancel and my toon will be instantly transported to said spider's location

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Expected behaviour would be as any other charge on a selected enemy within the same game version, with the white trail behind you and the running animation heading in the direction of the said enemy.

##### STEPS TO REPRODUCE THE PROBLEM:

1. as a warrior, charge on a Searing Lava Spider in Searing Gorge a few times to see that sometimes the charge animation doesnt work as intended
2. 
3. 
4.

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?npc=5857

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Can't confirm it, checked several times without issues ( AC HASH/COMMIT: 466cdb68d635 )

![WoWScrnShot_061721_050011](https://user-images.githubusercontent.com/82579073/122319662-94ae6d00-cf29-11eb-84fd-193a77cccebe.jpg)
![WoWScrnShot_061721_050033](https://user-images.githubusercontent.com/82579073/122319692-a3951f80-cf29-11eb-845c-671435fee8a5.jpg)
![WoWScrnShot_061721_050057](https://user-images.githubusercontent.com/82579073/122319734-b3146880-cf29-11eb-8477-50b5c6c19269.jpg)
![WoWScrnShot_061721_050139](https://user-images.githubusercontent.com/82579073/122319757-bdcefd80-cf29-11eb-980f-52658de0d931.jpg)

**Comment by Scapulla** [comment]
might be a problem with my UI then. After installing the upgraded textures it hasnt heppened again. thanks for reviewing it and sorry for any time lost. will still be farming them for a while, if it starts happening again i'll notify y'all.

**Comment by Scapulla** [comment]
I logged in today and tried charging at them again, and the animation worked. Joined an RDF, when i got out of the Dungeon, it was bugged again. Linked a video this time. First charge went as usual, next 2 were bugged. It's not a framerate issue because when i'm not using the recording program i dont have the performing issues. 


https://user-images.githubusercontent.com/85845643/122630935-d8c27e80-d09d-11eb-8c79-f3530135ed6d.mp4

**Comment by Scapulla** [comment]
I logged in today and tried charging at them again, and the animation worked. Joined an RDF, when i got out of the Dungeon, it was bugged again. Linked a video this time. Sometimes it works, sometimes it doesnt. My ping is around 180ms, but it doesnt look like Lag.
https://www.youtube.com/watch?v=dNXOVhqiUIY&ab_channel=LoHiddad
https://www.youtube.com/watch?v=dlo-ya9c9_E&ab_channel=LoHiddad

**Comment by Stump876** [comment]
I could not duplicate this either. At first I thought it was because the charge missed, but even if it missed during testing it still showed the charge animation. I think if this were a server problem there would be more people pointing this out. I think it might have something to do with your client.
