### ISSUE TITLE
Fell through terrain on landing flying from Sentinel Hill - Stormwind

### ISSUE THREAD

**Issue by temperrr** [chromiecraft/chromiecraft#878]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I was flying from Sentinel Hill as a Female Dwarf to Stormwind. I was alt tabbed out during the flight. when I tabbed back in I was under stormwind. 

![image](https://user-images.githubusercontent.com/20357406/122174252-dcc68480-ce82-11eb-9384-42818a0e058f.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

 I would like to not be under stormwind

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Female Dwarf 
2.  Fly from Sentinel Hill, westfall, to Stormwind, Elwynn Forest.
3.  Maybe being alt tabbed during flight.
4.

##### EXTRA NOTES:

Tried it twice before and didn't happen.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Checked a couple of times, 'alt-tabbed' without any issues:

![WoWScrnShot_061721_051724](https://user-images.githubusercontent.com/82579073/122320748-6df13600-cf2b-11eb-98f4-9d5071da6855.jpg)

**Comment by temperrr** [comment]
Must have been a one of case probably? Been flying a couple of times aswell with alt tabbing and hasn't happened since.

**Comment by Azcobu** [comment]
Tried 10 flights between Sentinel Hill and SW, most while alt-tabbed, and no visits to the underworld. It looks like your client might have dropped a few crucial packets at the wrong time, so will close this issue accordingly. As always, if you have further issues, feel free to let us know.

**Comment by Ziedge** [comment]
I know this is closed but I encountered the issue two times now, both time was under those circumpstences : 

- Fly to SW from SH
- Alt tab
- Come back after a while, so being AFK you are sit
- Directly run (get out of sitting/afk) and fall
