### ISSUE TITLE
Two mining nodes on top of each other in Silverpine Forest

### ISSUE THREAD

**Issue by rdallastra** [chromiecraft/chromiecraft#879]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ X] Horde

##### CONTENT PHASE:

- [ X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Two mining nodes spawning on top of one another, a silver and a tin ones.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mining nodes should not spawn on top of each other

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Silverpine Forest, (59.28 75.60)
2.  There should be two nodes on top of each other
3. 
4.

##### EXTRA NOTES:

Screenshot of the .object near:
![WoWScrnShot_061621_205732](https://user-images.githubusercontent.com/45319286/122314269-e2a18180-cee5-11eb-98a3-0208e99f5e1d.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Known issue. https://github.com/chromiecraft/chromiecraft/issues/474 But thanks for the report.
