### ISSUE TITLE
Pet Stuck in Warsong Gulch

### ISSUE THREAD

**Issue by Cromisaid** [chromiecraft/chromiecraft#88]
##### ISSUE: FACTION SIDE: 

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)
**Hunters and Warlocks**
##### CONTENT PHASE:
 Every Content Phases, not linked to a specific level

##### SMALL DESCRIPTION:
If you join WG with your pet, 100% of time when you get down from the hill near the Alliance Graveyard, your pet stuck on the top of the hill and it cannot follow you. (Take a look of the picture below)
![WoWScrnShot_021821_133921](https://user-images.githubusercontent.com/78354696/108358820-780a5e80-71ef-11eb-855e-49e2175e8530.jpg)

Spell: Every PETS
Zone: Warsong Gulch

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Pets should follow their masters without stucking on the top of the hill

##### CURRENT BEHAVIOUR:
Pets stuck on the top of the alliance graveyard in **Warsong Gluch**,  moreover in Horde Graveyard they have to climb from the right of the hill and the master have to wait for their arrival.

##### STEPS TO REPRODUCE THE PROBLEM:

**Step 1** Join Warsong Gulch with a class that has Pet (hunter or warlock)
**Step 2** Get down from the top of Alliance Graveyard (100% of stuck the pet) or from Horde Graveyard (the pet has to climb from the right of the hill, and it comes to his master very slowly)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by JamesGent** [comment]
Can confirm have had both Warlock and Hunter pets stick.

**Comment by Stifler82** [comment]
it's definitely a Pathfinding problem..

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by Yehonal** [comment]
we worked on a fix here: https://github.com/azerothcore/azerothcore-wotlk/pull/5103

**Comment by Stifler82** [comment]
Maybe fixed:
- here https://github.com/azerothcore/azerothcore-wotlk/pull/4922
or
- here https://github.com/azerothcore/azerothcore-wotlk/pull/5103
