### ISSUE TITLE
[Searing Gorge] Badly positioned Heavy War Golem in the Slag Pit

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#881]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There is a Heavy War Golem in a bad position in the Slag Pit.
DB GUID: 5687
![WoWScrnShot_061721_085704](https://user-images.githubusercontent.com/81818678/122355374-20d48a80-cf52-11eb-8f43-af6f3889b78b.jpg)
![WoWScrnShot_061721_085711](https://user-images.githubusercontent.com/81818678/122355395-2500a800-cf52-11eb-8b65-0bbe1e2ce0bf.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Maybe he should be on the bridge.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Slag pit, but easiest way would be ".go creature 5687"

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Synful-Syn** [comment]
There are 2 of them, the other one is in the lava.
DB GUID: 5608, current GUID: 4159.
![WoWScrnShot_070521_190327](https://user-images.githubusercontent.com/22718174/124523143-ce092880-ddc3-11eb-9484-1d289b5b9930.jpg)
