### ISSUE TITLE
[Incorrect Drop] Pesterhide Hyena

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#889]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Pesterhide Hyena drops Bearded Boneaxe.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Pesterhide Hyena shouldn't drop Bearded Boneaxe according to the wowhead tbc.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Thousand Needles
2. Kill Pesterhide Hyena on repeat
3. Wait for it to drop Bearded Boneaxe

##### EXTRA NOTES:

Pesterhide Hyena: https://tbc.wowhead.com/npc=4248/pesterhide-hyena#drops
Bearded Boneaxe: https://tbc.wowhead.com/item=2878/bearded-boneaxe#dropped-by;0+3-10-9+1

![WoWScrnShot_061621_102833](https://user-images.githubusercontent.com/84775498/122549521-dd058200-d032-11eb-8869-27a6175e6e0f.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Pretty much the same situation as https://github.com/chromiecraft/chromiecraft/issues/888. The Pesterhide Hyena shares RLT 24049, which is what contains the Bearded Boneaxe, with 271 other creatures. It shouldn't have the axe as a drop, but a lot of the other 271 should - TBC Wowhead lists 75 creatures that drop it.
