### ISSUE TITLE
Cluck!

### ISSUE THREAD

**Issue by Hemingway1970** [chromiecraft/chromiecraft#89]
##### ISSUE: FACTION SIDE:
Not faction specific

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
Quest Cluck is broken. As soon as quest is accepted npc turns yellow and will not be engageable with quest in log. 

Chicken (Westfall?)
Chicken

Westfall

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Chicken is engaged with /chicken which turns him from neutral yellow to npc green and quest becomes available. He remains green for a short time and quest can be completed by buying a quest item from nearby NPC. 

##### CURRENT BEHAVIOUR:
Chicken becomes NPC green as expected with /Chicken. However, as soon as the quest is accepted he truns back to neutral yellow and cannot be interacted with for completion. No amount of /Chicken will turn him green again. If the quest is dropped he will once again turn green with /chicken. 

Cluck!

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
@Hemingway1970 : A closing comment would be useful to us others, as in whether you found out that it works due to some missing steps in "STEPS TO REPRODUCE THE PROBLEM" or if you closed it by a mistake.

**Comment by Hemingway1970** [comment]
Sorry, although I think retail did have a delay before the chicken would return to neutral allowing you to turn in the quest, ultimately the quest is still working in game and using the /cheer emote will activate it as it states in the quest description. My error in trying to use /chicken and not /cheer. So I closed the issue.

**Comment by illfated** [comment]
Very good. Thank you for the added explanation.
