### ISSUE TITLE
[Incorrect Drop] Kaskk

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#890]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Kaskk drops Glyphed Epaulets.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Kaskk shouldn't drop Glyphed Epaulets according to the wowhead tbc.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Desolace
2. Kill the rare Kaskk on repeat
3. Wait for it to drop Glyphed Epaulets

##### EXTRA NOTES:

Kaskk: https://tbc.wowhead.com/npc=14226/kaskk
Glyphed Epaulets: https://tbc.wowhead.com/item=4731/glyphed-epaulets#dropped-by;100+3-10-9+1

![WoWScrnShot_061821_112208](https://user-images.githubusercontent.com/84775498/122549932-543b1600-d033-11eb-98e5-08b887f9e99c.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
See https://github.com/chromiecraft/chromiecraft/issues/888 for closure reason.

In this case, RLT 24056 containing the Glyphed Epaulets is shared by 440 creatures.
