### ISSUE TITLE
[Incorrect Drop] Undead Ravager

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#891]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Undead Ravager drops both Imperial Leather Gloves and Grimp Reaper.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Undead Ravager shouldn't drop either Imperial Leather Gloves or Grimp Reaper according to the wowhead tbc.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Desolace
2. Kill Undead Ravager on repeat
3. Wait for it to drop mentioned items

##### EXTRA NOTES:

Undead Ravager: https://tbc.wowhead.com/npc=11561/undead-ravager#drops
Imperial Leather Gloves: https://tbc.wowhead.com/item=4063/imperial-leather-gloves#dropped-by;0+3-10-9+1
Grim Reaper: https://tbc.wowhead.com/item=13054/grim-reaper#dropped-by;0+3-10-9+1

![WoWScrnShot_061821_112714](https://user-images.githubusercontent.com/84775498/122550893-8f8a1480-d034-11eb-8d49-c1621eb63460.jpg)
![WoWScrnShot_061821_113512](https://user-images.githubusercontent.com/84775498/122550907-93b63200-d034-11eb-9a4f-f696dc60b5a0.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
See https://github.com/chromiecraft/chromiecraft/issues/888 for closure reason.

in this case, the Gloves are in RLT 24039, shared with 511 creatures, and the Grim Reaper is in RLT 24038, shared with 252.
