### ISSUE TITLE
Black Lotus Spawn Rates

### ISSUE THREAD

**Issue by CadmannG** [chromiecraft/chromiecraft#894]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Black Lotus can spawn multiple nodes within the same zone at the same time (tested in Winterspring). After one of the daily server resets, there were six black lotuses at the same time. By the end of the day (before server reset), no black lotus spawned at all for several hours even though there were no other players in the zone.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No zone should ever spawn more than one Black Lotus node at a time. Respawn time for each zone should be approximately 60-75 minutes (various sources differ).

##### SOURCE:

https://us.forums.blizzard.com/en/wow/t/black-lotus-and-wsg-adjustments/539024
This source is for Classic Wow, but comes directly from Blizzard. Various old farming guides describe this same limitation. As far as I can tell, this spawn rate was never changed in later patches and should be relevant to 3.3.5a.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Check known Black Lotus spawn locations immediately after daily server reset
2. Locations shown at https://wowgaming.altervista.org/aowow/?object=176589

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. Herb and mine pooling is a known issue https://github.com/azerothcore/azerothcore-wotlk/issues/2211
