### ISSUE TITLE
Overlapping Food/Drink boxes Goldshire

### ISSUE THREAD

**Issue by temperrr** [chromiecraft/chromiecraft#899]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

![image](https://user-images.githubusercontent.com/20357406/122634364-1d6e0a00-d0de-11eb-8fbd-b71967fe537b.png)
![image](https://user-images.githubusercontent.com/20357406/122634462-a5541400-d0de-11eb-9803-878a54dabd6c.png)

Food + drink spawned in eachother. This is not blizzlike behaviour.
32313 [entry 3658] water barrel and 32754 [entry 3719] food crate
30677 [entry 3658] water barrel and 30839 [entry 3719] food crate

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only 1 of them should be spawned at a time 
##### STEPS TO REPRODUCE THE PROBLEM:

1. go to Goldshire, Elwynn Forest, near 42.0 , 67.3
2.  See both of the items spawned in eachother
3.  They keep respawning in same spot. (after some time ofcourse)
4. go to Goldshire Inn, Elwynn Forest, near 43.9, 65.7
5.   See both of the items spawned in eachother
6  They keep respawning in same spot. (after some time ofcourse)

##### EXTRA NOTES:

https://wowpedia.fandom.com/wiki/Water_Barrel
https://wowpedia.fandom.com/wiki/Food_Crate
https://www.wowhead.com/object=3658/water-barrel
https://www.wowhead.com/object=3662/food-crate

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Possibly fixed by this?  https://github.com/azerothcore/azerothcore-wotlk/pull/6415

**Comment by anguaive** [comment]
Yes. Thanks for the report though :)
