### ISSUE TITLE
[Mining] Failed attempt

### ISSUE THREAD

**Issue by Wowhungarian** [chromiecraft/chromiecraft#9]
##### SMALL DESCRIPTION:
Failed attempt, when mining.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
I don't know, if there should be a warning message like this at all. But I'm sure, it should not appeare, when I'm not moving, just standing still and tryin to do some mining.

##### CURRENT BEHAVIOUR:
When I try to pick up a mine, for example a Copper Vein, sometimes I got a "Failed attempt" error message, even if I'm close to the mine object.

##### STEPS TO REPRODUCE THE PROBLEM:
Just try to mine some Copper Vein, and interrupt your casts.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/38bf355bf479

**Comment by Hacaw** [comment]
I can confirm this, I started mining yesterday on my mage and it's randomly giving the "Failed attempt".

**Comment by Yehonal** [comment]
This is a feature not a bug

**Comment by Yehonal** [comment]
But you probably are right, just checked, they removed the failed attempt in 3.1 https://wow.gamepedia.com/Patch_3.1.0#Gathering_Skills

**Comment by Yehonal** [comment]
Related TC issue:  https://github.com/TrinityCore/TrinityCore/issues/21038

Fix: https://github.com/TrinityCore/TrinityCore/pull/21039

**Comment by Helias** [comment]
fixed, let's test it https://github.com/azerothcore/azerothcore-wotlk/pull/4036

**Comment by szepi23** [comment]
It works fine now, thank you all! :)

**Comment by Yehonal** [comment]
GG!

**Comment by FrancescoBorzi** [comment]
@Wowhungarian where did you test it? the fix is not yet on ChromieCraft

**Comment by Wowhungarian** [comment]
@FrancescoBorzi Somehow, the error message is not showing up right now on ChromieCraft, Idk why then.

**Comment by Wowhungarian** [comment]
Can someone explain to me pls, how is this seem to be fixed on Chromie, when noone merged it to there? I said, what I said, cause it really works for me. I'm not joking...

**Comment by Wowhungarian** [comment]
Perhabs, my mining skill left the orange level. That's why I didn't got the message and tought it was fixed. Sorry guys.

**Comment by FrancescoBorzi** [comment]
no problem! and thanks for your feedback
