### ISSUE TITLE
Misplaced NPC

### ISSUE THREAD

**Issue by dzKostoff** [chromiecraft/chromiecraft#900]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Low priority bug.
NPC Entry ID: 15951
NPC Name: Magister Duskwither
Current Behavior: Misplaced position and the NPC is hovering above the ground.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Expected Behavior:
The NPC should not be hovering above the ground and should be placed between the two telescopes.

##### SOURCE:

  
https://www.youtube.com/watch?v=AxrFFaz_7_M&ab_channel=Bue
Note that a 3.3.5a video clip from youtube will probably be from another private server and will not guarantee the exact behavior. The video above is from classic TBC.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I have no idea which commands you use to teleport to NPCs
2. No
3. No
4. DB GUID: 56398 GUID: 3285

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Efymer** [comment]
Confirmed also in AzerothCore rev. ba96e8140323

![WoWScrnShot_061921_133638](https://user-images.githubusercontent.com/79163132/122641116-743a0a80-d103-11eb-84f4-b275096bae32.jpg)

**Comment by Efymer** [comment]
I just noticed there was already an opened issue yesterday about this same NPC: https://github.com/chromiecraft/chromiecraft/issues/892

**Comment by dzKostoff** [comment]
Apologies for the duplicate. I wasn't sure how to search for other reported
issues.
I believe you can close it in that case. Thanks!

**Comment by anguaive** [comment]
No worries. 

You can search for existing issues on the Issues page. It's also worth checking whether a relates issue exists on https://github.com/azerothcore/azerothcore-wotlk/
