### ISSUE TITLE
Quest drops still visible after requirements fulfilled

### ISSUE THREAD

**Issue by CadmannG** [chromiecraft/chromiecraft#902]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After collecting all required quest items from mobs, those items will incorrectly continue to drop (or remain visible) under two circumstances: (a) the player's quest items are in their bank; (b) the player killed multiple mobs before looting.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once a player has collected all dropped items for a quest (even if they are stored in the bank), they should never see extra copies of these items on mobs. These extra item drops should also not prevent skinning.

##### SOURCE:

I've looked for a while and I'm not sure I can find a source for this one. AoE videos either don't show looting, or they've already completed the relevant quests prior to filming. Most players don't usually store quest items in their bank, but the progressive level cap on ChromieCraft is a unique circumstance. Having played multiple AoE classes (which would encounter this specific situation regularly) throughout various retail expansions including 3.3.5, I can't recall having ever encountered this issue on an official server. This is absolutely a bug, but not an urgent one.

Players with skinning can work around this issue by deleting a quest item from their bag, looting the mob, and then skinning it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept any quest to collect drops from mobs, especially skinnable mobs (e.g. Singing Blue Shards from Crank Fizzlebub in Booty Bay).
2. Collect all but one of the required items (e.g. 9/10).
3. Kill multiple mobs before looting any. You should see extra items, but be unable to loot them after fulfilling the quest requirement (this incorrectly prevents skinning).
4. Put all these quest items in your bank and continue killing the same mobs. You should be able to incorrectly collect additional quest items.

##### EXTRA NOTES:

This appears to affect a large number of quests; although there a handful of specific quest issues listed here on github, I did not see a generic bug report for all quest drops. Apologies if this is a known issue.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Thx for the detailed report ;)

Have fun.
