### ISSUE TITLE
Cortello's Riddle Quest not working. Musty Scroll object non interactible.

### ISSUE THREAD

**Issue by marcusorcheart** [chromiecraft/chromiecraft#904]
Cortello's Riddle Quest not working. Musty Scroll object non interactible.

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There is a scroll that should be interactible, and should start a quest, give a note, etc. I've added an image with location.  The scrool is inactive. It does nothing. 
Here's the link to the database quest. 
https://wotlk-twinhead.twinstar.cz/?quest=626
The quest is called Cortello's Riddle and the innactive object is Musty Scroll
Type here.

![image1](https://user-images.githubusercontent.com/84984021/122649351-1e328a80-d136-11eb-9583-d961119a4f9e.jpg)
![image3](https://user-images.githubusercontent.com/84984021/122649352-1ecb2100-d136-11eb-9f5b-a1a2267c0679.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
The quest you linked is not the first quest of the chain.
Here it is on aowow: https://wowgaming.altervista.org/aowow/?quest=624
You can see the quest starts in one of the pirate ships south of Stranglethorn Vale. This is what I remembered also from Classic WoW (2019 retail), so I checked on classic Wowhead: https://classic.wowhead.com/object=2554/cortellos-riddle
Did you start the quest in the pirate ships? Else it's normal behaviour that you cannot interract with the scroll in Dustwallow Marsh.

**Comment by Azcobu** [comment]
Just ran through the chain to check (teleport ftw) and @pop-pig was correct. The object needs you to be on the correct step of the quest chain, but once you are doing that, the scroll does work.

Only on first stage:
![WoWScrnShot_062021_120458](https://user-images.githubusercontent.com/81782124/122660413-7f9f3b80-d1c0-11eb-9b7c-714cc9b3e93c.jpg)

With correct quest active:
![WoWScrnShot_062021_120715](https://user-images.githubusercontent.com/81782124/122660417-84fc8600-d1c0-11eb-886b-6c1fbc683983.jpg)

![WoWScrnShot_062021_120728](https://user-images.githubusercontent.com/81782124/122660427-96de2900-d1c0-11eb-9443-3f0b286fe799.jpg)
![WoWScrnShot_062021_120731](https://user-images.githubusercontent.com/81782124/122660430-980f5600-d1c0-11eb-9d68-a047c9e997f1.jpg)

**Comment by Eldarix** [comment]
Awesome dude, well done !! :)

**Comment by Azcobu** [comment]
@eldarix - thanks, but @pop-pig did the important bit, I just teleported around to confirm they were right. 

Incidentally, this is one of those issues where five minutes with the database can save an hour of running around. I'd definitely recommend installing Keira3 and MySQL on your machine to make testing easier for you. I know you're not necessarily into the technical stuff, but it does save an awful lot of time when you can just look up an item or a mob in the DB and teleport directly to them instead of trying to find them in the open world. If you have problems installing or running the software, let any of us on Discord know and we'll try to help out.

**Comment by marcusorcheart** [comment]
Thanks for solving this. The information on twinhead site was wrong. Sorry for wrong repport and thanks for the help. Now I can try once more with the quest.

**Comment by Eldarix** [comment]
Thx azcobu, i wouldn't say that I'll never get into it, but for now, after 2 months of intensive learning, I'm fine like that, before last days of march y have zero, totally nothing inside my head related to any of this :)

Take care.
