### ISSUE TITLE
Arena Season 6 items are available for purchase

### ISSUE THREAD

**Issue by Skadi999** [chromiecraft/chromiecraft#905]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

It is already possible on ChromieCraft to buy Arena Season 6 items (Furious Gladiator) from the pvp vendor at Gadgetzan.
In fact, you can buy Season 7 and 8 items, too, but those require Arena Points which we cannot get yet.
Links to the pvp vendors:
https://wotlk.evowow.com/?npc=34093
https://wotlk.evowow.com/?npc=33939
https://wotlk.evowow.com/?npc=33935
https://wotlk.evowow.com/?npc=33929

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It works correctly for a 3.3.5a server. However, these items should not be obtainable yet on chromiecraft, because if we start the level 80 bracket with only naxx patch, that means only Deadly Gladiator (Season 5) items should be the highest ones available for purchase. In theory, one could already gather the honor points needed for the Furious Gladiator gear and buy it.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Gadgetzan
2.  Talk to the PVP vendors by the "arena" in the middle of the town.
3. 
4.

##### EXTRA NOTES:

This is NOT an AzerothCore bug or a problem with other 3.3.5a servers, like I said it's only an oversight that should be addressed on ChromieCraft itself due to the way content is gradually unlocked.
I apologize if I should've reported a problem of such nature somewhere else.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. While you're correct that this is a CC issue, AC is also concerned with progression and the ability to selectively disable things like the PVP vendors you found on a bracket-by-bracket basis. (See https://github.com/azerothcore/azerothcore-wotlk/issues/5861) So this is definitely useful information.

**Comment by Azcobu** [comment]
Moved the report to the progression system repo it turns out we have.

**Comment by Helias** [comment]
npc vendors disabled
