### ISSUE TITLE
Unable to skin Nighbane Worgan

### ISSUE THREAD

**Issue by Hemingway1970** [chromiecraft/chromiecraft#91]
##### ISSUE: FACTION SIDE:
Non specific Faction

##### SMALL DESCRIPTION:
Attempting to skin Nightbane Worgan gives the error "Creature must be looted first" 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Mob should be skinniable.

##### CURRENT BEHAVIOUR:
After killing worgan it is tagged as "skinnable" with no loot but attmpting to skin gives error "Creature must be looted first". This may be a loot issue since 5/5 Worgan had no loot and were not skinnable. 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Kill Worgan
Step 2 Attempt to skin
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Duplicate issue: https://github.com/chromiecraft/chromiecraft/issues/86
