### ISSUE TITLE
Deadwind Pass - TBC mobs in front of Karazhan

### ISSUE THREAD

**Issue by Skadi999** [chromiecraft/chromiecraft#916]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

This is another problem related to the progression system.

There are mobs in Deadwind Pass, near Karazhan, that were added in TBC and drop TBC items (Netherweave Cloth, greens and blues). It is a problem especially if one can obtain a TBC item with required level of 60 or less, as they are more powerful than many vanilla raid items, allowing one to get a large advantage in the 50-59 and 60 brackets.
![WoWScrnShot_062021_115704](https://user-images.githubusercontent.com/56880336/122670153-c8ef8b00-d1c0-11eb-8061-e3e0363d35ad.jpg)
![WoWScrnShot_062021_115839](https://user-images.githubusercontent.com/56880336/122670159-cee56c00-d1c0-11eb-9c01-80c7da625b5e.jpg)
![WoWScrnShot_062021_121415](https://user-images.githubusercontent.com/56880336/122670211-12d87100-d1c1-11eb-8f23-e63d02f7ab0d.jpg)

Links to the mobs in question:
https://wotlk.evowow.com/?npc=12380
https://wotlk.evowow.com/?npc=12379
https://wotlk.evowow.com/?npc=12378
https://wotlk.evowow.com/?npc=12377
https://wotlk.evowow.com/?npc=7370

##### EXPECTED BLIZZLIKE BEHAVIOUR:

These mobs were not present in vanilla. They should be removed until the TBC content phase is out.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Deadwind Pass, near Karazhan and in the Master's Cellar below it
2.  Find one of the specified mobs
3.  Kill, loot, respawn, repeat.
4.

##### EXTRA NOTES:

Other mobs in Deadwind Pass (Sky Shadows, ogres, etc) are not TBC mobs and so are not part of the problem.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by tbcxd** [comment]
Hello! Last time I checked on Chromiecraft, those were removed! 
I'm going there right now to check.

**Comment by Skadi999** [comment]
Hello. My apologies, I couldn't find a bug report about them here, so I assumed they're there on CC. I tested it on my own AC server.
