### ISSUE TITLE
Gamon drop

### ISSUE THREAD

**Issue by daniboiz** [chromiecraft/chromiecraft#92]
##### ISSUE: FACTION SIDE: H

![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

Generic

##### SMALL DESCRIPTION:

Gamon droped me today 2x green items around 45-50 lvl which are around 3-4g both.
I killed him like 10 more times to check if it gonna happen again but it doesnt. 
  https://ibb.co/NKzf8rL

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@daniboiz

It doesn't seem to be a Bug, I have tried to search for information on the web, and through official channels, and also through Patch notes, and there are no references to Gamon until after Catclysm.

So it would seem to be correct as well.
Below I post the links of my research.

[wow.gamepedia.com](https://wow.gamepedia.com/Gamon)
[Gamon Loot - classicdb.ch](https://classicdb.ch/?npc=6466#drop:0-2-16+1)
[Gamon Loot - wotlk.evowow.com](https://wotlk.evowow.com/?npc=6466#drops:0-2-14+1)
[Gamon Loot - wotlkdb.com](https://wotlkdb.com/?npc=6466#drops:0-2-14+1)
[Gamon Loot - wotlk-twinhead.twinstar.cz](https://wotlk-twinhead.twinstar.cz/?npc=6466#drop:0-2-13+1)
[Gamon Loot - db.rising-gods.de](https://db.rising-gods.de/?npc=6466#drops:0-2-14+1)
[Gamon Loot - wowgaming.altervista.org](https://wowgaming.altervista.org/aowow/?npc=6466#drops:0-2-14+1)

**Comment by illfated** [comment]
I agree with this conclusion. Also, if you compare the TC page
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=6466/gamon (based on sniffs)
  with the updated content in Classic WoW
- https://classic.wowhead.com/npc=6466/gamon

you will notice that there is still some similarity (except for the total number of items) between the 2 pages. Sure, it would have been good if the original 2010 wowhead.com pages were stored in a more complete state, but it should not matter much in this case.
