### ISSUE TITLE
[Thousand Needles] Missing NPC dialog for quest "Free at Last"

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#922]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

At the end of the escort quest "Free at Last" ( https://wowgaming.altervista.org/aowow/?quest=4904 ), Lakota Windsong leaves without saying anything, once you reach the end of the escort path.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Lakota should say thanks and tell you that she can go back home by herself: https://youtu.be/iQQBpUo49LI?t=4151
You can see the dialog text in the chat window (this is from retail Classic WoW).

##### SOURCE:

https://youtu.be/iQQBpUo49LI?t=4151
You can see the dialog text in the chat window (this is from retail Classic WoW).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Lakota Windsong ( ".go creature 21594").
2. Do the escort quest.
3. See her leave without saying thanks.

##### EXTRA NOTES:

N/A

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Nefertumm** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/commit/246babb12c7ae85aad6f24056b8d48cbec2efa23
