### ISSUE TITLE
Glyph of Rejuvenation not working

### ISSUE THREAD

**Issue by Undersalt** [chromiecraft/chromiecraft#926]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Glyph of Rejuvenation is not affecting amount healed.
This was tested both when recasting Rejuvenation on target below 50% health, and when letting target health drop to sub 50% with the spell already active.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

While your Rejuvenation targets are below 50% health, you will heal them for an additional 50% health.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use Glyph of Rejuvenation
2. Cast Rejuventation on target
3. Note amounts healed at +50% less than 50% and from +50% while damaged to lower than 50%

##### EXTRA NOTES:

Tested while healing Warrior in PVE.

Rejuvenation kept ticking for 168 per tick in all cases.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Is working as intended.

![Naamloo2s](https://user-images.githubusercontent.com/20357406/122685445-b6e70a00-d20b-11eb-950b-aa81098e8293.png)
