### ISSUE TITLE
midsummer event gives too much gold

### ISSUE THREAD

**Issue by tbcxd** [chromiecraft/chromiecraft#929]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Altho some databases say these quests/bonfires should give between 4 and 7 gold from completing them, there is no way on earth this is normal.
Even level 1 characters can get 10 gold from a single bonfire making it HIGHLY abusable using summoning stones from warlocks and deleting those lvl 1 characters after completing the quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be some limitations on these.

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to any bonfire
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Seems like it's not scaling at all. The question is, what should it be giving?
![image](https://user-images.githubusercontent.com/68164076/122701378-fa3c7b00-d201-11eb-8dbb-9db3d601c9db.png)
![image](https://user-images.githubusercontent.com/68164076/122701557-5b644e80-d202-11eb-94b5-fc2717091ed9.png)
According to [this](https://www.wowhead.com/news/midsummer-fire-festival-2009-june-21-july-5-quest-guide-information-103454) "If you visit one of your faction's bonfires, you can speak to the nearby Flame Keeper (or Flame Warden) to Honor the Flame, which will reward you with  Burning Blossom x5 and 6G 63S at level 80. If you visit one of the opposing faction's bonfires, you can right-click to Desecrate this Fire!, which will extinguish the flame and will reward  Burning Blossom x10 and 13G 23S at level 80."  I'll look more into it.

**Comment by Stump876** [comment]
It seems like the reward scales per zone, not per level, I do believe this is incorrect.
Rewards in Gold shire at 1 and 80 (including max level gold bump)
![image](https://user-images.githubusercontent.com/68164076/122711258-bef87700-d216-11eb-8f98-db326a4895b4.png)

![image](https://user-images.githubusercontent.com/68164076/122711164-91abc900-d216-11eb-9375-3b7fe70fbdba.png)


Rewards in Stranglethorn at level 1 and 80 (including max level gold bump) 
![image](https://user-images.githubusercontent.com/68164076/122708903-147e5500-d212-11eb-895d-5aafda2572a1.png)
![image](https://user-images.githubusercontent.com/68164076/122710806-e3078880-d215-11eb-86a6-a99f1cf73e54.png)


Rewards at level 1 and 80 (including max level gold bump) in Burning steppes
![image](https://user-images.githubusercontent.com/68164076/122710589-75f3f300-d215-11eb-9b1a-e588bc0fc1ce.png)

![image](https://user-images.githubusercontent.com/68164076/122710131-83f54400-d214-11eb-9fbb-596a2bd90143.png)
