### ISSUE TITLE
Too many concurrent Herbalism nodes spawning

### ISSUE THREAD

**Issue by eTzmNcbkrng** [chromiecraft/chromiecraft#93]
##### ISSUE:
Often time, too many herb nodes are spawning

##### FACTION SIDE:

Not Faction specific.

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

There is a noticeably too high number of herb nodes spawning in parts of The Barrens, I noticed this to a lesser extent in Mulgore but have no supporting evidence.
There are 7 nodes visible on the minimap in the below screenshot, and 4 are visible in the game world.
![WoWScrnShot_021921_153727](https://user-images.githubusercontent.com/26512802/108556306-af961980-735b-11eb-88f5-1e1eda0ed783.jpg)

This may (probably - it can't be just the two zones I've quested in) affect other zones, unsure if mining nodes have the same issue.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I don't have any facts to prove it, but the number of nodes spawned at any one time was never this high on live realms.
It makes the profession feel too easy.

##### CURRENT BEHAVIOUR:

Too many herb nodes spawning concurrently in some zones.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Acquire Herbalism Profession (optional but makes step 3 easier)
Step 2 Enable Track Herbs ability from Herbalism profession (optional but makes step 3 easier)
Step 3 Run around The Barrens or Mulgore to find nodes

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
That's right, in the low-level areas there are more herbs

**Comment by illfated** [comment]
@eTzmNcbkrng : Just to reassure you, it is also a matter of difference from retail when you play on a low-population realm (or running a local server with you as the only player). In those cases, you don't get the retail experience of respawn frequency, more like a first spawn experience, since most of the gathering comes from initial spawns.
