### ISSUE TITLE
Midsummer event daily "More Torch Catching" - Using "Unlit Torches" away from bonfire counts towards quest completion

### ISSUE THREAD

**Issue by rdallastra** [chromiecraft/chromiecraft#930]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Whenever you have the daily More Torch Catching, if you try throwing the quest item "Unlit Torches" away from the bonfire (for instance at Tirisfal Glades (60, 59)) the character will not throw a torch, but will gain the buff as if it caught the torch (doing it 10 times counts as if the quest is complete).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not sure, maybe "Unlit Torches" shouldn't work away from the bonfire? Definitely it should not count towards completion of the daily quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get the Midsummer daily Catch More Torches
2. Go somewhere like Tirisfal Glades (60, 59)
3. Use "Unlit Torches" on yourself
4.

##### EXTRA NOTES:

N/Z

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Confirmed. Thanks for your report

**Comment by temperrr** [comment]
@FrancescoBorzi This one needs some labels! :)
