### ISSUE TITLE
[Midsummer Fire Festival] Quests reward issues

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#934]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Torch Tossing(Allince)](https://www.wowhead.com/quest=11731/torch-tossing) - reward 13 silver. 
[Torch Tossing(Horde)](https://www.wowhead.com/quest=11922/torch-tossing) - reward 7 gold 40 silver.
[More Torch Tossing(Allince)](https://www.wowhead.com/quest=11921/more-torch-tossing) - reward 15 silver.
[More Torch Tossing(Horde)](https://www.wowhead.com/quest=11926/more-torch-tossing) - reward 4 silver.
[Torch Catching(Allince)](https://www.wowhead.com/quest=11657/torch-catching) - reward 7 gold 40 silver.
[Torch Catching(Horde)](https://www.wowhead.com/quest=11923/torch-catching) - reward 3 silver.
[More Torch Catching(Allince)](https://www.wowhead.com/quest=11924/more-torch-catching) - reward 7 gold 40 silver. !!! DAILY !!!
[More Torch Catching(Horde)](https://www.wowhead.com/quest=11925/more-torch-catching) - reward reward 4 silver.

1. Same quests has different rewards
2. Allince have daily quest with reward several gold. This quest available for Lvl 1.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. Same quests - same rewards.
2. Daily quests available for lvl 1 characters shouldn't have several gold reward.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
this is related to https://github.com/chromiecraft/chromiecraft/issues/929
