### ISSUE TITLE
Bloodmyst Isle Webbed Creature tauntable 

### ISSUE THREAD

**Issue by temperrr** [chromiecraft/chromiecraft#941]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Webbed Creature for quest They're Alive! Maybe... are tauntable and will then move towards you. They will also start hitting you for considerable amount of damage

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Webbed Creature is a stationary unit and should not attack you. See the comments under the [wowhead source](https://tbc.wowhead.com/quest=9670/theyre-alive-maybe#comments). 

> Be warned that hurting the cocoons will leave you in combat unless you finish them off. I accidentally tagged a couple with some AoE's.

which indicates clearly that they are not coming for you to engage in combat or hurt you.

##### SOURCE:

https://tbc.wowhead.com/quest=9670/theyre-alive-maybe#comments
https://tbc.wowhead.com/npc=17680/webbed-creature

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to amberweb pass , bloodmyst isle
2.  Use Taunt on a Webbed Creature ( I used bear form Growl)
3.  walk around with a webbed creature following you, and hitting you for twice the amount of damage a normal creature would from that bracket.
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Resolved by https://github.com/azerothcore/azerothcore-wotlk/pull/6481
