### ISSUE TITLE
[Midsummer Festival] Feralas Feathermoon Stronghold duplicate tent and decorations

### ISSUE THREAD

**Issue by Landaz2** [chromiecraft/chromiecraft#944]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There is an additional set of Festival Decorations and NPC (GUID 248582) at the Forgotten Coast (46.6,44.2), but no fire.
At the correct location east of Feathermoon Stronghold, some decorations are missing, but the fire is in place.

![WoWScrnShot_062121_102427](https://user-images.githubusercontent.com/81629712/122732375-81c6d000-d27c-11eb-9429-361bad254f49.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be only one festival location, most likely the one close to Feathermoon stronghold

##### SOURCE:

  https://www.engadget.com/2010-06-18-the-overachiever-guide-to-midsummer-festival-2010-achievements.html
  

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to the noted location
2. See for yourself
3. 
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
https://github.com/chromiecraft/chromiecraft/issues/933 double
