### ISSUE TITLE
[Stranglethorn Vale] Multiple Goblin Commoner spawns

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#948]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There are several double/triple sapwns of Goblin Commoners (https://wowgaming.altervista.org/aowow/?npc=20102) at alliance and horde flightmaster.
Even humans are listed as Goblin Commoner which is another bug.

![bb3](https://user-images.githubusercontent.com/80769357/122753909-37048280-d293-11eb-92ef-c5c95e2fe27f.jpg)
![bbh](https://user-images.githubusercontent.com/80769357/122753912-379d1900-d293-11eb-9639-a5efefc052f5.jpg)

There should only be 2 spawned. There is an issue with the goblin commoners spawned when theres no events going on, but now for each location 2 additional ones were spawned.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should oly be a pair of "goblin" commoners spawned at flightmasters.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 93639 and observe spawns
2. Move to horde flightmaster and observe spawns

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9710
