### ISSUE TITLE
Alliance: Quest - The tome of divinity

### ISSUE THREAD

**Issue by psyhlo** [chromiecraft/chromiecraft#95]
![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:

Quest: [Tome of Divinity](https://www.wowhead.com/item=23926/tome-of-divinity)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Can not resurrect Henze Faulk 

##### CURRENT BEHAVIOUR:
the dead body is there but when right click on the book or on the body, noting happens

Quest: [Tome of Divinity](https://www.wowhead.com/item=23926/tome-of-divinity)
##### STEPS TO REPRODUCE THE PROBLEM:
go to coordinates 72.61 and 51.42 in Elwynn Forest near Stone Cairn Lake

[image](https://prnt.sc/102ky7m)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by psyhlo** [comment]
my bad everything is working fine
I was using the wrong item

**Comment by psyhlo** [comment]
it has one minor problem 
after i complete all the quests of the series - tome of divinity remains in my inventory
when i click on it says - You don't meet the requirements for the quest

**Comment by illfated** [comment]
@psyhlo : That happens to some quest items. Most people don't even spend time mentioning it on wowhead.com, they just drop it out of their bags.
It only becomes an issue if it is a looted quest item dropping from almost every mob related to the quest.

**Comment by psyhlo** [comment]
ok got it thanks
