### ISSUE TITLE
[Tanaris] Double Spawns of Goblin Commoners in Gadgetzan

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#950]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Many humans are labeled Goblin Commoner
Multiple Double Spawns

GUID 91761 (human), 91760       GUID 91759 (human)
![tanaris3](https://user-images.githubusercontent.com/80769357/122767370-e137d680-d2a2-11eb-8dab-967c4463192e.jpg)

GUID 91753, 91764       GUID 91754, 91765 (all human)
![tanaris1](https://user-images.githubusercontent.com/80769357/122767374-e2690380-d2a2-11eb-8b4e-80247cddc388.jpg)

GUID 91762, 91755 (human)       GUID 91756, 91763 (both human) 
![tanaris2](https://user-images.githubusercontent.com/80769357/122767375-e3019a00-d2a2-11eb-85f4-520a04cf1746.jpg)

GUID 91758, 91757 (both human)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Commoners should not doublespawn and should not be human.

##### SOURCE:

https://tbc.wowhead.com/npc=20102/goblin-commoner#screenshots

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID
2. Observe double spawns

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9710
