### ISSUE TITLE
[Midsummer Festival] Honor The Flame and Desecrate This Fire! quests are repetable

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#955]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

All Honor the flame quests (https://wowgaming.altervista.org/aowow/?quest=11583  see the list) and All Desecrate this Fire! quests (https://wowgaming.altervista.org/aowow/?quest=11580   see the list) are repetable, acting like daily quests. I did them all yesterday and got the achivement, and today I saw they were available again.
![westfall](https://user-images.githubusercontent.com/80769357/122877935-7389ba00-d337-11eb-9f4e-7527b9a6d3b3.jpg)
![elwyn](https://user-images.githubusercontent.com/80769357/122877937-74bae700-d337-11eb-9dc9-cfeb8a35e896.jpg)
![swamp](https://user-images.githubusercontent.com/80769357/122877939-75537d80-d337-11eb-9996-29641d85be4c.jpg)

I wont link every zone, but they are all available.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Each of the quests should be available for completion 1 time 
https://www.wowhead.com/midsummer-fire-festival-guide

https://www.engadget.com/2010-06-18-the-overachiever-guide-to-midsummer-festival-2010-achievements.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLnNpLw&guce_referrer_sig=AQAAAHZc4On34thGRwRzjRq-RWZoSdN3w0hM5vQmA7ur2A9V0qysg0doV-nucjy3z6V7TNcMKSwxYyZPOvwx2VdV1H-YWjUzpf77b7eAzKjjWMV4-dVyXFops_zcK3L7utG9Fcc735ujIa0IAN6MuGkimKgAnc7BGjEGLgzBAa89MKAi

##### STEPS TO REPRODUCE THE PROBLEM:

1. Complete any Honor the flame/Desecrate this fire! quest
2. Check in next day and see it available again (or maybe restart server does it too, i dont know)

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment]
There is also an issue (maybe related?) about achievements.
I honored & extinguished in Hillsbrad this morning around 6:00 AM server time, and after logging back at 8:00 AM server time, my achievements were unchecked for Hillsbrad.

**Comment by Azcobu** [comment]
Well, can say restarting the server doesn't reset the quests, but will have to wait until tomorrow to see if they repeat for me on the local server.

**Comment by gurveleg** [comment]
Well Midsummer event is disabled on Chromiecraft until they fix this, because it was abused widely. Sometimes even reloging forced a reset, but that might be tied to another issue.

**Comment by gurveleg** [comment]
> There is also an issue (maybe related?) about achievements.
> I honored & extinguished in Hillsbrad this morning around 6:00 AM server time, and after logging back at 8:00 AM server time, my achievements were unchecked for Hillsbrad.

That seems to be a seperate but related issue, as many people were reporting "micro-rollbacks" in chats regarding the midsummer quests, where blossoms were being deleted and some quests being reset (like stealing the fire from enemy capitals) on relogging a character - tho gold rewarded stayed. Event was disabled on CC before I had a chance to test it out more, but it seems something was clearly breaking Midsummer quests, since all the quests were repeatable/stayed in log after completing/reseting on relogging - not just the daily ones.

I'm curious if anyone managed to replicate the Fire Quests being repatable on local AC.

**Comment by Azcobu** [comment]
> I'm curious if anyone managed to replicate the Fire Quests being repatable on local AC.

I was never able to reproduce that issue on a vanilla AC server.

**Comment by Eldarix** [comment]
I haven't been able to confirm this, I've waited more than a day and it does not give me the option to repeat it.

**Comment by gurveleg** [comment]
It had to be chromiecraft specific then if it can't be replicated on local AC. The question is what made it break on CC. I fear unless they find the issue and fix it, the next Midsummer Event will face the same gold abusing issues.
