### ISSUE TITLE
[Ratchet] Goblin Commoners humans and doublespawns

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#957]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There are double spawns of Goblin Commoners in Ratchet, also many are humans labelled as goblin commoner.

GUID 91118, 91749(both human)   GUID 91117 (human), 91707
![ratchet1](https://user-images.githubusercontent.com/80769357/122895235-3679f380-d348-11eb-9ee2-d93aeb46441c.jpg)

GUID 91115, 91750   GUID 91116, 91751  (all 4 human)
![ratchet2](https://user-images.githubusercontent.com/80769357/122895230-34b03000-d348-11eb-99e1-6ca56e8178fa.jpg)

GUID 91704        GUID 91706, 91705  (all 3 human)
![ratchet3](https://user-images.githubusercontent.com/80769357/122895218-337f0300-d348-11eb-93e8-9808f8bcbe0d.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Goblin commoners should not double spawn, and should not be human.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUIDs
2. Observe the spawned commoners

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9710
