### ISSUE TITLE
Ability to disenchant when in a party without a enchanter

### ISSUE THREAD

**Issue by Cosmic-Lattee** [chromiecraft/chromiecraft#96]
##### ISSUE: FACTION SIDE:
Issue is for both sides I imagine though I only have horde toons at the moment.

##### CONTENT PHASE:
1-19 Phase.

##### SMALL DESCRIPTION:
Option to disenchant when nobody can disenchant in a party.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When you are in a party without a enchanter you should only be able to green or need.

##### CURRENT BEHAVIOUR:
When in a party and a green (or better) item drops a option for disenchant appears. Below is a screenshot from my computer, my wifes computer, and the strange dust that was made from the item

![image](https://user-images.githubusercontent.com/24766235/108614788-49dd7800-73c3-11eb-8ae4-77d77eaba7d8.png)

##### STEPS TO REPRODUCE THE PROBLEM:
Be in a party
Attack mobs till a green item drops
See if the option to disenchant is there.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Cosmic-Lattee** [comment]
So more recent drops don't seem to let us disenchant items now. So it seems to be inconsistent. Will report if I see it again.

**Comment by Stifler82** [comment]
> So more recent drops don't seem to let us disenchant items now. So it seems to be inconsistent. Will report if I see it again.

@Cosmic-Lattee 

What version of WoW do you have **"enGB"** or **"enUS"**?

**Comment by Cosmic-Lattee** [comment]
![image](https://user-images.githubusercontent.com/24766235/109092050-80750480-76db-11eb-9da9-5c3590b7001b.png)

![image](https://user-images.githubusercontent.com/24766235/109092115-9a164c00-76db-11eb-8ac6-f0a9d8625fae.png)

ESRB is the American one so I am pretty sure this is enUS. I downloaded this client from Warmane.

**Comment by Stifler82** [comment]
mhmhm...  I don't trust Warmane, they may have "Customized" their client...
Will you please me to download another enUS?
indeed, forget it, in these days I will make my enUS Client available for all players which is perfect and working.

**Comment by Stifler82** [comment]
@Cosmic-Lattee just out of curiosity, did the bug happen again?

**Comment by Cosmic-Lattee** [comment]
We are just about to play some more. I will report if I see it again.

**Comment by Stifler82** [comment]
> We are just about to play some more. I will report if I see it again.

@Cosmic-Lattee  Can I close the case for the moment?

**Comment by Cosmic-Lattee** [comment]
Sure.

**Comment by Cosmic-Lattee** [comment]
Since I opened this I went ahead and downloaded your new client from here: https://www.chromiecraft.com/downloads/ 

![image](https://user-images.githubusercontent.com/24766235/109600862-8146d580-7ae3-11eb-9f07-54b555469cda.png)

So it happened again on a different character this time.

![image](https://user-images.githubusercontent.com/24766235/109601232-121db100-7ae4-11eb-96b1-c4d773a55c58.png)

![image](https://user-images.githubusercontent.com/24766235/109601253-1d70dc80-7ae4-11eb-8884-a407a5df24ad.png)

**Comment by Cosmic-Lattee** [comment]
Happened again just now:

![image](https://user-images.githubusercontent.com/24766235/109601530-a6881380-7ae4-11eb-9cb2-03925f53b29b.png)

**Comment by Cosmic-Cocoa** [comment]
Papyrus' professions are Blacksmith / Jewelcrafting. I was the only other person in the party. I also had the option to disenchant the items in the screenshots. Many of the greens we saw drop today did not have the disenchant option, so it's very inconsistent. When the option is there it seems to be there for both of us.

**Comment by eTzmNcbkrng** [comment]
@Cosmic-Cocoa @Cosmic-Lattee Can I suggest you keep track of the iLvl of items that this happens on?
Perhaps it only affects items that are disenchantable in a specific range, like only affect items that don’t require > 25 enchanting to DE.

**Comment by Cosmic-Cocoa** [comment]
@eTzmNcbkrng For sure. So far it's only happened in Ghostlands. Originally I suspected it might be related to the TBC stuff. But we'll definitely start keeping track of iLvl as we play if we encounter it again.

**Comment by AbraKabastard** [comment]
Group.cpp
```c++
            if (r->totalPlayersRolling > 0)
            {
                r->setLoot(loot);
                r->itemSlot = itemSlot;
                if (item->DisenchantID && m_maxEnchantingLevel >= item->RequiredDisenchantSkill)
                    r->rollVoteMask |= ROLL_FLAG_TYPE_DISENCHANT;
```

``if (item->DisenchantID && m_maxEnchantingLevel >= item->RequiredDisenchantSkill)```
Greater  than or equal to 0 much?

**Comment by FrancescoBorzi** [comment]
@chromiecraft/bug-triagers  What's the status of this?

**Comment by eTzmNcbkrng** [comment]
> Edit: Blood elves get a racial bonus to enchanting... Could have some effect here.

In the first couple of screenshots there are definitely Blood Elves involved, but in a few of the screenshots @Cosmic-Lattee posted, it looks like two Undead characters. I think it's something to do with low level items requiring 0 Disenchant skill.

The entry for Hutning Tunic - [data\sql\base\db_world\item_template.sql#L:2080](https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/base/db_world/item_template.sql#L2080) reads:
`(2973,4,2,-1,'Hunting Tunic',14539,2,0,0,1,2421,484,5,-1,-1,17,12,0,0,0,0,0,0,0,0,1,0,2,7,4,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,73,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,-1,0,0,0,0,-1,0,-1,0,0,0,0,-1,0,-1,0,0,0,0,-1,0,-1,0,0,0,0,-1,0,-1,2,'',0,0,0,0,0,8,0,0,0,0,0,65,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,'',2,0,0,0,0,12340),`
15th value from the end is the required disenchanting level, which is `0`.

Abomination Cleaver and Scalping Tomahawk are also both `0`

I think solution is `Group.cpp` as quoted by @AbraKabastard needs to include a check for whether anyone in the group actually has enchanting.

**Comment by r-o-b-o-t-o** [comment]
Hi there!

> 15th value from the end is the required disenchanting level, which is 0.

The required disenchanting level is the 12th column, I suspect you were looking at the `item_template.sql` file and mistook the keys for columns: 😛 
![image](https://user-images.githubusercontent.com/24357633/116283542-47651900-a78c-11eb-9278-1eba2fc0476d.png)
Knowing this, if you look again, all of these items have 1 as the required disenchant skill level (at least on my local database):
![image](https://user-images.githubusercontent.com/24357633/116284209-1d602680-a78d-11eb-8134-8e38d6f77d44.png)

So right now, the blood elf racial bonus seems like a good culprit, and would probably be fixed by checking if anyone in the group actually has the enchanting profession - as stated before, but then I really don't know how it happened with two undeads...

This is a long shot, but by any chance @Cosmic-Cocoa @Cosmic-Lattee do you remember if you had invited an enchanter or a blood-elf in your group before looting the [Abomination Cleaver] and [Hunting Tunic]?

**Comment by r-o-b-o-t-o** [comment]
> This is a long shot, but by any chance @Cosmic-Cocoa @Cosmic-Lattee do you remember if you had invited an enchanter or a blood-elf in your group before looting the [Abomination Cleaver] and [Hunting Tunic]?

I just tested this with @Sedatyf, and my hunch seems correct!
It looks like the skill level for the group is not correctly refreshed when a member leaves, so if you invite an enchanter and remove them from the group, you're still registered as a group with a skill in enchanting, and you're able to disenchant looted items:

https://user-images.githubusercontent.com/24357633/116290920-49cb7100-a794-11eb-92a4-f7a3335d0949.mp4

(not shown in the video, but obviously the character Warriora is not an enchanter)

I'll take a look at the code and if my suspicion turns out to be correct I'll do a PR for this.
