### ISSUE TITLE
[Badlands] Siege Golem (Rare) Is moving too fast

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#960]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Siege Golem GUID 134465 (https://wowgaming.altervista.org/aowow/?npc=2749) Is moving around too fast.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be moving slower, like other golems of his type - normal and rares. Seems odd that only this npc would move much faster than any other golem in the game.

There is also no comment saying he is fast, which if it was the case would likely be mentioned
https://tbc.wowhead.com/npc=2749/siege-golem#comments

##### SOURCE:

https://youtu.be/A1535Tk94F8?t=238

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID
2. Observe movement speed

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Efymer** [comment]
The fix is included in this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/6502/files#diff-15c3ef08691a2fb15ca627f27d1fc9d1bf1077265a2897e9a9465d94efc1c208R207
