### ISSUE TITLE
(Quest): Lost but not forgotten

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#961]
#### WHAT CLIENT DO YOU PLAY ON?

- [X] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Kron's Amulet that drops from Crocolisks that are in the border with The Barrens has a 100% drop chance.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Drop chance should be around 10% according to source.

##### SOURCE:

https://classic.wowhead.com/item=4891/krons-amulet

##### STEPS TO REPRODUCE THE PROBLEM:

1. Take quest 
2. Kill 1 creature in the River
3. Loot the item

##### EXTRA NOTES:

https://classic.wowhead.com/quest=816/lost-but-not-forgotten
https://classic.wowhead.com/item=4891/krons-amulet
https://classic.wowhead.com/npc=3231/corrupted-dreadmaw-crocolisk
https://classic.wowhead.com/npc=3110/dreadmaw-crocolisk

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
You just got lucky. The drop rate *is* 10%.

```sql
SELECT * from `creature_loot_template` WHERE `Item` = 4891;
```

```
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+----------------------------------------------+
| Entry | Item | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment                                      |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+----------------------------------------------+
|  3110 | 4891 |         0 |     10 |             1 |        1 |       0 |        1 |        1 | Dreadmaw Crocolisk - Kron's Amulet           |
|  3231 | 4891 |         0 |     10 |             1 |        1 |       0 |        1 |        1 | Corrupted Dreadmaw Crocolisk - Kron's Amulet |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+----------------------------------------------+
```
