### ISSUE TITLE
[Bloodmyst Isle] Aggressive Monster "Nazzivus Summoner" does not react to players walking close

### ISSUE THREAD

**Issue by Vladimirjov** [chromiecraft/chromiecraft#962]
[Bloodmyst Isle] Aggressive Monster "Nazzivus Summoner" does not react to players walking close

![WoWScrnShot_062321_032215](https://user-images.githubusercontent.com/81888445/123020212-3a525800-d3d2-11eb-8afc-b804e25ea7d1.jpg)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
Look on the screenshot, the aggressive monsters "Nazzivus Summoner" on Bloodmyst Isle don't react to low level players walking close by. They should attack the player immediately like every other aggressive monsters.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They should attack the player immediately like every other aggressive monsters.

##### SOURCE:
Common sense.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Just walk by with a low level Character. In my case it was a level 13 Warrior Draenei named "Excalibur"

##### EXTRA NOTES:
Thank you for fixing! :D 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment]
Actually, these should not really be around. They should summon Trezak as listed here in the comments https://tbc.wowhead.com/npc=17524/nazzivus-summoner#comments
When he is summoned, Trezak should walk to the monument (in about 10 minutes) and despawn there
https://tbc.wowhead.com/npc=17528/tzerak#comments
Then summoners respawn to start the ritual again to summon him.
You can interrupt the summoners (they won't aggro, but if you hit one all six should come to kill you)
