### ISSUE TITLE
Paladin Quest Line Tome of Divinity

### ISSUE THREAD

**Issue by Vancrot** [chromiecraft/chromiecraft#964]
#### WHAT CLIENT DO YOU PLAY ON?

- [x] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here. Doing the quest line Tome of Divinity part 6 give by "Gazin Tenorm" where its suppose to get the symbol of life in order to resurrect "Henze Faulk" to complete this quest but the quest giver does not give me the item so its impossible to complete the quest. My character its Aratian Paladin lvl 14 alliance thanks

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here. The quest giver "Gazin Tenorm" should give the item "Symbol of Life" in order to complete his quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Need second opinion here, when i add the quest 1781, the dwarf gives me the item:

![WoWScrnShot_062421_133336](https://user-images.githubusercontent.com/82579073/123248979-323d0a00-d4f1-11eb-8732-618cbfc74ab7.jpg)
![WoWScrnShot_062421_133347](https://user-images.githubusercontent.com/82579073/123249050-42ed8000-d4f1-11eb-852e-1841e62ab48b.jpg)

But after that no other quest is given.

**Comment by Eldarix** [comment]
A couple of links related:

https://classic.wowhead.com/guides/paladin-class-quests-classic-wow

https://classic.wowhead.com/quest=1781/the-tome-of-divinity

**Comment by Azcobu** [comment]
The Symbol of Life is actually given in the quest before, number 5 in the series, when you accept it. If you talk to Duthorian Rall, he's the one who gives it to you. 

Anyway, just ran through the chain and didn't have any problems, so closing this accordingly.
