### ISSUE TITLE
Iverron's Antidote (Shadowglen)

### ISSUE THREAD

**Issue by bganderson** [chromiecraft/chromiecraft#99]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Quest: [Iverron's Antidote](https://wowgaming.altervista.org/aowow/?quest=3521)

This looks like it may have been brought up in #51 but was closed as an enGB client issue. I'm using the enUS client downloaded from the ChromieCraft.com direct web URL. 

I've recorded a video to demonstrate the issue here: https://youtu.be/UyArLOiWD_0

It's like if the object has already been drawn on screen / loaded into memory, it stays sparkling and remains interactive/loot-able, but when going a decent distance away and returning, the sparkling will stop and the item becomes non-interactive. 

It's still possible this is a client issue as I'm running the client in a Wineskin (Engine: WS11WineCX64Bit19.0.1-1, Wrapper: Wineskin-2.9.0.7-rc1) on macOS 10.15.7.

GameObject: [Moonpetal Lily](https://wowgaming.altervista.org/aowow/?object=152095)
GameObject: [Hyacinth Mushroom](https://wowgaming.altervista.org/aowow/?object=152094)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Sparkling quest object should stop sparkling and become non-interactive once required items for quest have been collected.

##### CURRENT BEHAVIOUR:

When collecting [Moonpetal Lily](https://wowgaming.altervista.org/aowow/?object=152095) and [Hyacinth Mushroom](https://wowgaming.altervista.org/aowow/?object=152094) for [Iverron's Antidote](https://wowgaming.altervista.org/aowow/?quest=3521) once 4/4 Lily's and/or 7/7 Mushroom's have been collected, I'm allowed to continue interacting with the objects, opening them and de-spawning them but receiving no additional items. It seems like if I go outside of draw distance and come back the Lily's and Mushrooms are no longer sparkling or interactive. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a Night Elf
2. Go to [Dirania Silvershine](https://wowgaming.altervista.org/aowow/?npc=8583)
3. Complete [A Good Friend](https://wowgaming.altervista.org/aowow/?quest=4495) and the follow up [A Friend In Need](https://wowgaming.altervista.org/aowow/?quest=3519)
4. Pick up [Iverron's Antidote](https://wowgaming.altervista.org/aowow/?quest=3521) from [Dirania Silvershine](https://wowgaming.altervista.org/aowow/?npc=8583)
5. Go collect 4x[Moonpetal Lily](https://wowgaming.altervista.org/aowow/?object=152095)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a4115862de1cd6f37b70969c87df79f327457dd1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@bganderson 
Ok, now I understand what **"The misunderstanding"** was.
**It is not a Bug.**
Basically you are able to collect the items of the quest **(even after having collected them all)**, because the quest **is (NOT FINISHED!)** in fact, in the video **you still lacked a quest objective**, that is to collect **"Webwood Ichor"** from spiders.
**Since the quest is still "Active"** even **the GameObjects remain "Active"**, in fact, once the quest is over you are no longer able to collect them..

**Comment by bganderson** [comment]
@Stifler82 

That isn't accurate, the video I recorded refutes that assessment. If you watch you clearly see a Moonpetal Lily sparkling, I leave to collect a Mushroom far away, then return and the same Lily is no longer sparkling and loot-able and the quest is not complete. Same thing happens with a Mushroom later on in the video.

**Lily is sparkling and interactive:**
<img width="659" alt="Screen Shot 2021-02-21 at 5 11 44 PM" src="https://user-images.githubusercontent.com/39788238/108645570-23254d00-7468-11eb-99e5-60e5b97c7aec.png">

**After walking far away and returning, the same lily is no longer sparkling and interactive:**
<img width="867" alt="Screen Shot 2021-02-21 at 5 12 57 PM" src="https://user-images.githubusercontent.com/39788238/108645601-3b956780-7468-11eb-89d6-4be87c99086b.png">

**Still need Webwood Ichor but Mushroom is not sparkling or interactive:**
<img width="881" alt="Screen Shot 2021-02-21 at 5 08 40 PM" src="https://user-images.githubusercontent.com/39788238/108645385-8793dc80-7467-11eb-942a-e31cfafdd179.png">

**Comment by Stifler82** [comment]
@bganderson 
**Video:** [Iverron's Antidote Shadowglen](https://youtu.be/OXSGKaDRdgA)
And this video I think closes the matter, definitively.
